### ISSUE TITLE
[BUG] Tracing network calls are inconsistent

### ISSUE THREAD

**Issue by manuelriveragax** [microsoft/playwright#11518] opened 2022-01-20 16:40 UTC
**Context:**
- Playwright Version: 1.7.1
- Operating System: Windows/WSL
- Node.js version: 12.16.1
- Browser: Chromium

**Code Snippet**

POM

```javascript
import { expect, Locator, Page } from '@playwright/test';

export class SelfSignUpPage {
  readonly page: Page;
  readonly freeTrialNavbar: Locator;
  readonly settingUpSiteModal: Locator;
  readonly startFreeTrialButton: Locator;
  readonly signUpModal: Locator;
  readonly siteNameInput: Locator;
  readonly emailInput: Locator;
  readonly passwordInput: Locator;
  readonly signUpModalButton: Locator;
  readonly guidedTourModal: Locator;
  readonly skipTourCheckbox: Locator;
  readonly adminsSideBar: Locator;
  readonly passwordRequirements: Locator;
  readonly validEmailError: Locator;
  readonly validPasswordError: Locator;
  readonly siteNameAvailable: Locator;
  readonly errorModal: Locator;
  readonly accountData: String;

  constructor(page: Page) {
    this.page = page;
    this.freeTrialNavbar = page.locator('[data-testid="freetrial-navbar"]');
    this.settingUpSiteModal = page.locator(
      '[data-testid="setting-up-modal-popup"]'
    );
    this.startFreeTrialButton = page.locator("text=START FREE TRIAL");
    this.signUpModal = page.locator(
      ':nth-match(div:has-text("Start your 14-day free trialCreate your accountYour Site Namemaestro.tv/EmailPas"), 4)'
    );
    this.siteNameInput = page.locator('[data-testid="sitename-input"]');
    this.emailInput = page.locator('[placeholder="Enter your email address"]');
    this.passwordInput = page.locator('[placeholder="Enter your password"]');
    this.signUpModalButton = page.locator('[data-testid="signup-button"]');
    this.guidedTourModal = page.locator(
      '[data-testid="start-screen"] input[type="checkbox"]'
    );
    this.skipTourCheckbox = page.locator("text=Skip the Tour");
    this.adminsSideBar = page.locator('[data-testid="adminAdmins"]');
    this.passwordRequirements = page.locator('text=Password Requirements');
    this.validEmailError = page.locator('text=Please enter a valid email address')
    this.validPasswordError = page.locator('text=Please enter a valid password')
    this.siteNameAvailable = page.locator('text=This site name is available');
    this.errorModal = page.locator('[data-testid="errormodal-title"]');
    this.accountData = `QaE2E${Date.now().toString()}`    
  }

  async goToHome() {
    await this.page.goto("STAGING ENV");
  }

  async startSignUp() {
    await this.page.click("text=START FREE TRIAL");
    await expect(this.signUpModalButton).toBeVisible();
  }

  async fillDataSignUp() {
    const siteLocator = this.siteNameInput;
    await this.siteNameInput.fill(this.accountData.toString());
    await expect(siteLocator).toHaveValue(this.accountData.toString());

    await this.emailInput.fill(`stg${this.accountData.toString()}@test.com`);
    await this.passwordInput.fill("Password");
  }

  async inputErrorValidation(){
    await this.signUpModalButton.click();
    await expect(this.validEmailError).toBeVisible();
    await expect(this.validPasswordError).toBeVisible();
  }

  async passwordValidation(){
    await this.page.waitForSelector('text=Password Requirements')
    await expect(this.passwordRequirements).toBeVisible();
  }

  async checkSiteNameAvailable(){
    await expect (this.siteNameAvailable).toBeVisible();
  }

  async confirmSignUp(){
    await this.signUpModalButton.click();
    await expect(this.signUpModalButton).toBeHidden();
  }

  async siteCreatedModal(){
    await expect (this.settingUpSiteModal).toBeVisible();
    await expect (this.settingUpSiteModal).toBeHidden({timeout: 30000});
  }

  async errorCreateModal(){
    await expect (this.errorModal).toBeHidden({timeout:5000})
  }
}
```

Test file
```javascript
import { test, expect } from "@playwright/test";
import { SelfSignUpPage } from "../NS-4233-stg-e2e/ssu-stg-page";

test.describe("Login", () => {
  let selfSignUpPage: SelfSignUpPage;

  test.beforeEach(async ({ page }, testInfo) => {
    selfSignUpPage = new SelfSignUpPage(page);
    await selfSignUpPage.goToHome();
  });

  test.afterEach(async ({}, testInfo) => {
    selfSignUpPage.page.close();
  }); 

  test("Free trial flow", async ({page}) => {
    await selfSignUpPage.startSignUp();
    await selfSignUpPage.fillDataSignUp();
    await selfSignUpPage.passwordValidation();
    await selfSignUpPage.checkSiteNameAvailable();
    await selfSignUpPage.confirmSignUp();   
    await selfSignUpPage.siteCreatedModal();
    await selfSignUpPage.errorCreateModal();
  });
});
```

**Describe the bug**

Hi, sorry if the POM page is too long I'm just starting with Playwright and I have been struggling with how to implement POM.

I made this really quick test because we had an endpoint failing randomly and we were trying to debug it so it's not clean at all I just needed to trigger the endpoint thru a FE user flow.

Tracing network calls were very inconsistent, the endpoint was shown about 30%ish of the time in the tracing recordings and I can't understand why.

Trace with the POST api error:
![image](https://user-images.githubusercontent.com/60678271/150381753-1d3973f4-0b4d-45e2-a0ea-c6a5845037ca.png)

Trace without the POST API error, but the API still failed:
![image](https://user-images.githubusercontent.com/60678271/150381879-def3b8a2-dda8-43e4-a8bd-d94ea4d32011.png)

Attaching both trace files for reference.
[trace-no-api.zip](https://github.com/microsoft/playwright/files/7906949/trace-no-api.zip)
[trace-api.zip](https://github.com/microsoft/playwright/files/7906951/trace-api.zip)

**Comment by mxschmitt** [comment] 2022-01-21 11:22
Inside your afterEach you close the page but you never await it. Also this is the the page instance from the built-in fixtures so you don't have to close it, we do it for you.

How can I reproduce this 400 error? It might be that the networking events are attached to other Playwright actions, since these are just assertions.

**Comment by manuelriveragax** [comment] 2022-01-21 16:02
Unfortunately, we cannot repro this 400 error because it has been fixed 😞 so feel free to close the issue,  but thanks anyway!

I modified the after each as you mentioned in another issue.

```javascript
  test.afterEach(async ({}, testInfo) => {
    await selfSignUpPage.page.context().close();
  });
```

Also removed the page from the test 

```javascript
  test("Free trial flow", async ({}) => {
    await selfSignUpPage.startSignUp();
    await selfSignUpPage.fillDataSignUp();
    await selfSignUpPage.passwordValidation();
    await selfSignUpPage.checkSiteNameAvailable();
    await selfSignUpPage.confirmSignUp();
    await selfSignUpPage.siteCreatedModal();
    await selfSignUpPage.errorCreateModal();
  });
```

**Comment by mxschmitt** [comment] 2022-01-21 17:21
Then closing for now since we can't repro it :/

**Closed by mxschmitt** 2022-01-21 17:21 UTC
Labels: triaging
