### ISSUE TITLE
[BUG] Playwright button click works unpredictably

### ISSUE THREAD

**Issue by EgoPingvina** [microsoft/playwright#26652] opened 2023-08-23 12:04 UTC
### System info
- Playwright Version: [v1.37.1]
- Operating System: [Windows 11, Debian 11]
- Browser: [Chromium]
- Other info:
- Project: ASP.Net 7

### Source code

The class is registered as Singleton to always work with a single browser instance.

```
        ...

        private async Task<IBrowserContext> Initialize()
        {
            var pw = await Playwright.CreateAsync();

            var browser =
                await pw.Chromium.LaunchAsync(
                    new BrowserTypeLaunchOptions
                    {
                        IgnoreDefaultArgs = new List<string>() { "--enable-automation" },
                        Headless = true, // does not depend on headless
                        Channel = "chrome",
                        Timeout = 60000
                    });

            var context =
                await browser.NewContextAsync(
                    new BrowserNewContextOptions()
                    {
                        AcceptDownloads = true,
                        ViewportSize = new()
                        {
                            Height = 1024,
                            Width = 1280
                        },
                        Locale = "ru-RU"
                    });

            return context;
        }

       ...

        private async void LogError(IPage page)
        {
            var name = $"{DateTime.Now:dd - MM - yyyy HH - mm - ss}";

            File.WriteAllText($"{name}.html", await page.InnerHTMLAsync("html"));

            await page.ScreenshotAsync(new()
            {
                Path = $"{name}.png"
            });
        }

         public async ValueTask<string?> AskAsync(string prompt)
        {
            if (string.IsNullOrWhiteSpace(prompt))
            {
                throw
                  new ArgumentException();
            }

            var context = await this.Browser.ConfigureAwait(false);

            var page = await context.NewPageAsync();
                page.SetDefaultTimeout(60000);

            await page.GotoAsync(this.Url);

            var input = page.GetByPlaceholder("Введите запрос");

            await input.WaitForAsync();

            var cookies = page.Locator("button", new() { HasText = "Понятно" });

            if (await cookies.IsVisibleAsync())
            {
                await cookies.ClickAsync();
            }

            var rules = page.Locator("span", new() { HasText = "Да, согласен" });

            if (await rules.IsVisibleAsync())
            {
                await rules.ClickAsync();
            }

            await input.FillAsync(prompt);

            // This click sometimes does not work and fails with timeout on awaiting "Скачать" click
            await page.GetByRole(AriaRole.Button, new() { Name = "Создать" })
                      .ClickAsync(new() { Force = true });

            try
            {
                await page.Locator("span", new() { HasText = "Подготавливаем изображение" })
                          .WaitForAsync(
                              new LocatorWaitForOptions
                              {
                                  State = WaitForSelectorState.Hidden
                              });
            }
            catch (TimeoutException ex)
            {
                LogError(page);
                throw ex;
            }

            var hasError =
                await page.Locator("span", new() { HasText = "не соответствует" })
                          .IsVisibleAsync();

            if (hasError)
            {
                return null;
            }

            try
            {
                await page.GetByText("Скачать")//Locator("button", new() { HasText = "Скачать" })
                          .ClickAsync();
            }
            catch (TimeoutException ex)
            {
                LogError(page);
                throw ex;
            }

            var waitForDownloadTask = page.WaitForDownloadAsync();

            try
            {
                await page.GetByText("Скачать")
                          .ClickAsync();
            }
            catch (TimeoutException ex)
            {
                LogError(page);
                throw ex;
            }

            var download = await waitForDownloadTask;

            await download.PathAsync()
                ?? throw
                     new FileLoadException("Не удалось скачать результирующий файл.");

            var name = Guid.NewGuid();

            var path = Path.Combine("downloads", $"{name}.png");

            await download.SaveAsAsync(path);

            await page.CloseAsync();

            return path;
        }
```

**Expected**

All actions with the site have been successfully completed and the image has been received.

**Actual**

With multiple launches, sometimes it succeeds, sometimes it doesn't (described [here](https://stackoverflow.com/questions/76959007/playwright-button-click-works-unpredictably)).

Error message:
![image](https://github.com/microsoft/playwright/assets/9804340/8f8a39ea-d919-478e-9d82-549691b1d3fc)

**Comment by yury-s** [comment] 2023-08-23 16:05
The log clearly says that the `element is not enabled`, apparently the code is flaky depending on the page timing. What is the issue with playwright? Also, if you think there is a bug in playwright, please attach full self-contained repro that we could run locally, preferably with the source of the page you are automating.

**Comment by EgoPingvina** [comment] 2023-08-23 19:46
I found the root of problem.
The `await page.GetByRole(AriaRole.Button, new() { Name = "Создать" }).ClickAsync(new() { Force = true });` does not really perform a wait operation. Because increasing the timeout does nothing, and calling again after a timeout (even a very short one in a second) is guaranteed to succeed.
As far as I understand, the wait value is sent to Chrome via Connection.SendMessageToServerAsync, but no real wait is made. It seems to me that it would be a good idea to implement repeated attempts to obtain a component during a timeout using the library.

**Comment by yury-s** [comment] 2023-08-23 20:05
You pass [`Force = true` ](https://playwright.dev/dotnet/docs/api/class-locator#locator-click-option-force) which disables actionability checks. Playwright would [auto-wait](https://playwright.dev/dotnet/docs/actionability) otherwise. Closing as this is working as intended.

**Closed by yury-s** 2023-08-23 20:05 UTC
Labels: triaging

**Comment by EgoPingvina** [comment] 2023-08-24 05:03
It seems to me that you are not reading the full description of the problem. The Force parameter does not affect the behaviour, I described it back in the original SO question.

**Comment by CXRunfree** [comment] 2024-04-12 01:10
This problem usually occurs while operating a dom.However, adding more autowait makes no sense.  The only way to resolve it seems to force  `page.wait_for_timeout()`.
