### ISSUE TITLE
[BUG] Codegen automatically crashes on fresh install

### ISSUE THREAD

**Issue by noahbaron91** [microsoft/playwright#26706] opened 2023-08-25 15:40 UTC
### System info
- Playwright Version: [v1.37.1]
- Operating System: [macOS Ventura 13.4.1]
- Browser: [Chromium]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

Config:
```
module.exports = defineConfig({
  testDir: './tests',
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://127.0.0.1:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },

    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: { ...devices['Pixel 5'] },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: { ...devices['iPhone 12'] },
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { ...devices['Desktop Chrome'], channel: 'chrome' },
    // },
  ],

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   url: 'http://127.0.0.1:3000',
  //   reuseExistingServer: !process.env.CI,
  // },
});
```

**Steps**

https://github.com/microsoft/playwright/assets/32229274/323765db-76de-40b0-bdc0-7b0c52df1840

**Expected**

Codegen browser will not crash

**Actual**

Codegen browser immediately crashes

**Comment by yury-s** [comment] 2023-08-25 18:28
I cannot reproduce it. Does it happen in an empty directory?

**Comment by noahbaron91** [comment] 2023-08-25 20:10
Yes it does. I've noticed that bug only occurs when the "chromium"  browser is installed. If only firefox, or webkit are installed it works properly. 

This same bug seems to also affect UI mode.

Here is a video showing the issue using the default code generated by: yarn create playwright

https://github.com/microsoft/playwright/assets/32229274/ecd044f7-3448-45f9-a6a0-0b69603f2154

**Comment by yury-s** [comment] 2023-08-25 22:42
Still cannot reproduce it. If I uninstall all browsers I get the following error box and after installing chromium everything works:
```
$ yarn playwright uninstall --all
yarn run v1.22.19
warning package.json: "test" is also the name of a node core module
$ /private/tmp/test/node_modules/.bin/playwright uninstall --all
Removing unused browser at /Users/yurys/Library/Caches/ms-playwright/chromium-1076
Removing unused browser at /Users/yurys/Library/Caches/ms-playwright/ffmpeg-1009
Removing unused browser at /Users/yurys/Library/Caches/ms-playwright/firefox-1422
Removing unused browser at /Users/yurys/Library/Caches/ms-playwright/webkit-1883
✨  Done in 0.89s.
yurys:/tmp/test$ yarn playwright codegen
yarn run v1.22.19
warning package.json: "test" is also the name of a node core module
$ /private/tmp/test/node_modules/.bin/playwright codegen
Error: i.parse: Executable doesn't exist at /Users/yurys/Library/Caches/ms-playwright/chromium-1076/chrome-mac/Chromium.app/Contents/MacOS/Chromium
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yurys:/tmp/test$ yarn playwright install chromium
yarn run v1.22.19
warning package.json: "test" is also the name of a node core module
$ /private/tmp/test/node_modules/.bin/playwright install chromium
Downloading Chromium 116.0.5845.82 (playwright build v1076) from https://playwright.azureedge.net/builds/chromium/1076/chromium-mac-arm64.zip
124.8 Mb [====================] 100% 0.0s
Chromium 116.0.5845.82 (playwright build v1076) downloaded to /Users/yurys/Library/Caches/ms-playwright/chromium-1076
Downloading FFMPEG playwright build v1009 from https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac-arm64.zip
1 Mb [====================] 100% 0.0s
FFMPEG playwright build v1009 downloaded to /Users/yurys/Library/Caches/ms-playwright/ffmpeg-1009
✨  Done in 9.65s.
yurys:/tmp/test$ yarn playwright codegen
yarn run v1.22.19
warning package.json: "test" is also the name of a node core module
$ /private/tmp/test/node_modules/.bin/playwright codegen
^C
```


Can you delete `/Users/yurys/Library/Caches/ms-playwright` directory (this will kill playwright's browser cache so you'll have to reinstall browsers again) it and repeat the test?

If it still reproduces I wonder if there are any playwright vars in you env, can you run `env | grep PLAYWRIGHT` and see if the result is empty?

**Comment by noahbaron91** [comment] 2023-08-26 00:30
Sorry, small miscommunication there.

The second video showed that the bug also occurred with UI mode since I realized it wasn't just scoped to the codegen feature.

Here are the logs of it crashing when using codegen with chromium:
When running codegen with chromium (when it crashes):
```
noahbaron@Noahs-MacBook-Pro playwright-chromium-bug % yarn playwright codegen
yarn run v1.22.19
$ /Users/noahbaron/Documents/playwright-chromium-bug/node_modules/.bin/playwright codegen
✨  Done in 6.09s.
noahbaron@Noahs-MacBook-Pro playwright-chromium-bug % 
```

These are the logs when running codegen with firefox (does not crash):
```
noahbaron@Noahs-MacBook-Pro playwright-chromium-bug % yarn playwright codegen -b firefox     
yarn run v1.22.19
$ /Users/noahbaron/Documents/playwright-chromium-bug/node_modules/.bin/playwright codegen -b firefox
✨  Done in 27.50s.
```

The output of "env | grep PLAYWRIGHT" is:
```
noahbaron@Noahs-MacBook-Pro playwright-chromium-bug % env | grep PLAYWRIGHT
noahbaron@Noahs-MacBook-Pro playwright-chromium-bug % 
```

I've also confirmed that deleting ```Library/Caches/ms-playwright``` does not fix the issue for me

**Comment by yury-s** [comment] 2023-08-26 01:20
Weird. Can you try running same command with `DEBUG=pw:browser`?

**Comment by aslushnikov** [comment] 2023-08-30 23:36
@noahbaron91 any updates on it?

**Comment by noahbaron91** [comment] 2023-08-31 23:09
Here is the output running ```DEBUG=pw:browser yarn playwright codegen```:
```
noahbaron@Noahs-MacBook-Pro playwright-test % DEBUG=pw:browser yarn playwright codegen
yarn run v1.22.19
$ /Users/noahbaron/Documents/playwright-test/node_modules/.bin/playwright codegen
  pw:browser <launching> /Users/noahbaron/Library/Caches/ms-playwright/chromium-1071/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/var/folders/hv/lqw8b_y579v5j4ct_d95tb5w0000gn/T/playwright_chromiumdev_profile-FLKWxB --remote-debugging-pipe --no-startup-window +0ms
  pw:browser <launched> pid=13475 +3ms
  pw:browser [pid=13475][err] [13475:259:0831/160648.815874:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled. +2s
  pw:browser <launching> /Users/noahbaron/Library/Caches/ms-playwright/chromium-1071/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --no-sandbox --app=data:text/html, --window-size=600,600 --window-position=1020,10 --test-type= --user-data-dir=/var/folders/hv/lqw8b_y579v5j4ct_d95tb5w0000gn/T/playwright_chromiumdev_profile-6qi3tk --remote-debugging-pipe about:blank +74ms
  pw:browser <launched> pid=13493 +2ms
  pw:browser [pid=13493][err] [13493:259:0831/160649.058204:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled. +166ms
  pw:browser [pid=13493] <gracefully close start> +1s
  pw:browser [pid=13475] <gracefully close start> +36ms
  pw:browser [pid=13493] <process did exit: exitCode=0, signal=null> +43ms
  pw:browser [pid=13493] starting temporary directories cleanup +0ms
  pw:browser [pid=13475] <process did exit: exitCode=0, signal=null> +7ms
  pw:browser [pid=13475] starting temporary directories cleanup +0ms
  pw:browser [pid=13493] finished temporary directories cleanup +20ms
  pw:browser [pid=13493] <gracefully close end> +0ms
  pw:browser [pid=13475] finished temporary directories cleanup +1ms
  pw:browser [pid=13475] <gracefully close end> +0ms
✨  Done in 4.35s.
```

**Comment by aslushnikov** [comment] 2023-09-01 23:53
@noahbaron91 is everything else working? Can you run a simple playwright script with chromium? Can you launch `/Users/noahbaron/Library/Caches/ms-playwright/chromium-1071/chrome-mac/Chromium.app/Contents/MacOS/Chromium` manually and see if it loads?

**Comment by noahbaron91** [comment] 2023-09-02 00:59
Seems like just booting up Chromium by itself is also causing the same crashing issue:

https://github.com/microsoft/playwright/assets/32229274/f0c5d20e-d38f-4193-8a8a-d8fcdbbd3ec6

**Comment by aslushnikov** [comment] 2023-09-05 16:02
@noahbaron91 I'm out of ideas, unfortunately. It does look like something's wrong with the machine; the same chrome build is launching successfully across thousands of different machines for us.

I'll have to close this since there's not much else we can help with, but please write back here for future reference if you manage to debug this down to something!

**Closed by aslushnikov** 2023-09-05 16:02 UTC
Labels: triaging
