### ISSUE TITLE
[BUG] click visibility check fails for visible element

### ISSUE THREAD

**Issue by mamacdon** [microsoft/playwright#5765] opened 2021-03-09 15:56 UTC
**Context:**
- Playwright Version: [what Playwright version do you use?] **1.9.1**
- Operating System: [e.g. Windows, Linux or Mac] **Mac**
- Node.js version: [e.g. 10.12, 10.14] **v12.16.3**
- Browser: [e.g. All, Chromium, Firefox, WebKit] **Chromium**
- Extra: [any specific details about your environment]
```
  System:
    OS: macOS 10.15.7
    Memory: 765.40 MB / 16.00 GB
  Binaries:
    Node: 12.16.3 - ~/.nodenv/versions/12.16.3/bin/node
    npm: 6.13.4 - ~/.nodenv/versions/12.16.3/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    playwright: 1.9.1 => 1.9.1
```
**Code Snippet**
This code snippet should reproduce the bug. It loads [a Stackblitz project](https://stackblitz.com/edit/xntbhj) that I've created.

```javascript
const { chromium } = require("playwright");

(async () => {
  const browser = await chromium.launch({
    headless: false
  });
  const context = await browser.newContext();

  // Open new page
  const page = await context.newPage();

  // ---------------------
  // Load & run project
  await page.goto("https://xntbhj.stackblitz.io/");
  await page.waitForSelector(`text="Run this project"`)
  await page.click(`button:has-text('Run this project')`);

  // Wait for the app to render
  await page.waitForSelector(`#go-to-sign-up`)
  await page.waitForTimeout(1000);
  
  await page.click(`#go-to-sign-up`) /// <<<<<<<< this click fails in chromium

  // ---------------------
  await context.close();
  await browser.close();
})();
```

**Describe the bug**

I'm trying to make Playwright click the "Sign up" link. Although the link is visible (and can be clicked if you visit [the app](https://xntbhj.stackblitz.io/)), Playwright thinks that it's not. Each attempt fails with "element is not visible":

```
pw:api => page.click started +0ms
pw:api waiting for selector "#go-to-sign-up" +2ms
pw:api   selector resolved to visible <ws-a href="#signup" id="go-to-sign-up">…</ws-a> +3ms
pw:api attempting click action +3ms
pw:api   waiting for element to be visible, enabled and stable +0ms
pw:api   element is visible, enabled and stable +17ms
pw:api   scrolling into view if needed +0ms
pw:api   done scrolling +1ms
pw:api   element is not visible +1ms
pw:api retrying click action, attempt #1 +0ms
pw:api   waiting for element to be visible, enabled and stable +0ms
pw:api   element is visible, enabled and stable +31ms
pw:api   scrolling into view if needed +0ms
pw:api   done scrolling +1ms
pw:api   element is not visible +0ms
< retries until failure >
```
The app is built with LitElement, and something about its use of `<slot>` seems to trigger this bug. I tried using a few alternative selectors (`a#go-to-sign-up`, `ws-a >> a`, etc) but they fail in the same fashion.

**Comment by yury-s** [comment] 2021-03-09 22:43
@mamacdon it looks like a chromium-specific bug in Playwright, I managed to reproduce it.

@stefanteixeira do you have a test script to reproduce you case? The code above interacts with shadow dom and I don't think the problem that @mamacdon reported is a regression from 1.8.1.

**Comment by stefanteixeira** [comment] 2021-03-10 02:43
Hey @yury-s, you can reproduce with this script below. It works fine on `1.8.1` but fails on `1.9.1`/`1.9.2`. I just want to select a different option inside [this page](http://toptal.com/freelance-jobs) (search for the section named `What Sets`).

```
const { chromium } = require('playwright')

;(async () => {
  const browser = await chromium.launch({
    headless: false
  })
  const context = await browser.newContext()
  const page = await context.newPage()

  await page.goto('http://toptal.com/freelance-jobs', {
    waitUntil: 'networkidle'
  })

  await page.selectOption(
    'select[aria-label="Select work type"]',
    'Traditional Employment'
  )

  await context.close()
  await browser.close()
})()
```

Playwright says that this element is hidden:

```
waiting for selector "select[aria-label="Select work type"]"
  selector resolved to hidden <select class="_1P9ZR2q8" aria-label="Select work type">…</select>
  selecting specified option(s)
    element is not visible - waiting...
```

I already tried:
- scrolling the page
- using `click` instead of `selectOption`
- using `click` with `force: true` (didn't worked at all, it still tried to check for visibility)

**Comment by yury-s** [comment] 2021-03-10 17:20
@stefanteixeira the element you are trying to select is not visible on the page, it is inside a hidden div so playwright keeps waiting until it shows up:

![image](https://user-images.githubusercontent.com/9798949/110669982-c2915200-8181-11eb-9058-3d84e56ac476.png)

**Comment by stefanteixeira** [comment] 2021-03-10 18:49
Thanks for the follow-up, @yury-s! And why was this different in `1.8.1`? Could you send the commit/PR where this behavior changed?

**Comment by yury-s** [comment] 2021-03-10 19:07
I don't think this behavior has changed since 1.8.1, it has been there since the very beginning. It might be that the page has changed and the element used to be visible before.

**Comment by stefanteixeira** [comment] 2021-03-10 19:45
@yury-s that's the thing: it passes normally in `1.8.1`, the page wasn't changed too. This is really weird 🤔

**Comment by yury-s** [comment] 2021-03-10 21:44
#5036 comes to mind but it was in 1.8.1 release.

**Comment by yury-s** [comment] 2021-03-16 22:47
Filed http://crbug.com/1188919 upstream.

**Comment by thernstig** [comment] 2021-03-22 16:21
@yury-s https://github.com/microsoft/playwright/pull/5850 says it fixes this issue reported here. And that PR points to https://chromium-review.googlesource.com/c/chromium/src/+/2766028 which has been merged.

But in the comment above you linked to http://crbug.com/1188919 and that seems to have no relation to the PR and chromium bug above. What am I missing? And could we expect a new Playwright version soon with these fixes?

**Comment by yury-s** [comment] 2021-03-22 21:43
http://crbug.com/1188919 points to a difference in the implementation of `elementFromPoint` which we use in our code. I found a workaround for that (#5850) so it should not block us. We should be able to merge the fix after rolling next Chromium Dev release which includes merged patch (see https://omahaproxy.appspot.com/ for the current Dev revision).

**Closed** 2021-04-02 17:36 UTC

**Comment by thernstig** [comment] 2021-04-03 09:27
@yury-s since it has been merged, will it be included in 1.10.1 or 1.11.0? Asking since our tests are pretty much useless now.

**Comment by yury-s** [comment] 2021-04-05 01:11
It requires bumping browser revision and so far we've been following the policy of updating browser version only during minor releases (not patch releases). Based on that it should normally be released in 1.11.0 Will this work for you? It's already in @next version so you can give it a try.

**Comment by thernstig** [comment] 2021-04-05 08:39
I might try the @next soon if I get a chance just to see if it works.

**Comment by divyapt** [comment] 2022-08-23 19:48
the same issue is reoccurring with 1.25.0, we just updated playwright version and our tests started failing.
