### ISSUE TITLE
[BUG] Page Visibility API does not work when doing test

### ISSUE THREAD

**Issue by hanzhihong9** [microsoft/playwright#22634] opened 2023-04-25 19:55 UTC
### System info
- Playwright Version: [v1.32.3]
- Operating System: [All, Windows] I only has Windows
- Browser: [Chromium, Firefox]

Page Visibility API :  https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

**Steps**
- Start a test and wait for the browser opens (let the test wait log, we need do following steps manually )
- open inspect/'dev tool' in a tab
- In console panel run the following script 
```
document.addEventListener("visibilitychange", () => {
 console.log('visibilitychange  work', document.visibilityState === 'visible')
}); 
```
- open another new tab --just open it manually 
- switch to the previous tab and watch the console log

**Expected**
We can see the console log:
"visibilitychange  work false"
"visibilitychange  work true"

**Actual**
There is not such log. looks 'visibilitychange' event never triggered

Note: open the browser(Chromium) manually , Page Visibility API works OK.
But when running in test env, Page Visibility API does not work OK.

**Comment by aslushnikov** [comment] 2023-04-26 22:19
This is a dupe of https://github.com/microsoft/playwright/issues/3570

**Closed by aslushnikov** 2023-04-26 22:19 UTC

**Comment by hanzhihong9** [comment] 2023-05-02 19:25
Surprise!!! the answer is here: hacks like https://github.com/microsoft/playwright/issues/2286#issuecomment-1442368623
