### ISSUE TITLE
[Feature]: waitFor

### ISSUE THREAD

**Issue by Meemaw** [microsoft/playwright#11736] opened 2022-01-29 19:03 UTC
Sometimes you need to assert something that will eventually become true, and is not related to the default page DOM expect matchers. Example:

```js
await waitFor(async () => {
  const cookies = await context.cookies()
  expect(cookies.find(c => c.name === "my-cookie")?.value).toBeDefined()
})
```

Would be great to exporting something like this from `@playwright/test` so no separate package is needed.

Obviously its also trivial to write a custom helper for this, but one advantage of having it in the core library is that it could respect the config timeouts by default.

**Comment by aslushnikov** [comment] 2022-01-31 18:08
Looks like a dupe of #10235

**Closed by aslushnikov** 2022-01-31 18:08 UTC
