### ISSUE TITLE
[Bug]: Dockerfile dont see last default version of playwright

### ISSUE THREAD

**Issue by SpaceShitBreaker** [microsoft/playwright#32509] opened 2024-09-09 06:18 UTC
### Version

1.47.0

### Steps to reproduce

Hi!
I use in Dockerfile commend to get the last version of playwright:
FROM mcr.microsoft.com/playwright:focal
and now a have version  error after update to v1.47 (from v1.46.1)
Error:
```
Error: browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1134/chrome-linux/chrome
    ╔══════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to 1.47.0. ║
    ║ Please update docker image as well.                                  ║
    ║ -  current: mcr.microsoft.com/playwright:v1.46.1-focal               ║
    ║ - required: mcr.microsoft.com/playwright:v1.47.0-focal               ║
    ║                                                                      ║
    ║ <3 Playwright Team                                                   ║
    ╚══════════════════════════════════════════════════════════════════════╝
    
```
normal upadate dosnt work, but working when i change on correct version in dockerfile:

    `FROM  mcr.microsoft.com/playwright:v1.47.0-focal`

Why did it stop working for the old configuration? 
`FROM mcr.microsoft.com/playwright:focal` ??
 

### Expected behavior

Working old ver of config in Dockerfile:

`FROM mcr.microsoft.com/playwright:focal`

### Actual behavior

```
Error: browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1134/chrome-linux/chrome
    ╔══════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to 1.47.0. ║
    ║ Please update docker image as well.                                  ║
    ║ -  current: mcr.microsoft.com/playwright:v1.46.1-focal               ║
    ║ - required: mcr.microsoft.com/playwright:v1.47.0-focal               ║
    ║                                                                      ║
    ║ <3 Playwright Team                                                   ║
    ╚══════════════════════════════════════════════════════════════════════╝
    
```

### Environment

```shell
System:
    OS: Windows 11 
  Binaries:
    Node: 20.15.0 
    npm: 10.8.2
  IDEs:
    VSCode: 1.93.0 
  npmPackages:
    @playwright/test: 1.47 => 1.47.0
```

**Comment by mxschmitt** [comment] 2024-09-09 06:52
We strongly recommend to pin the Docker image versions.

See https://github.com/microsoft/playwright/issues/32483#issuecomment-2333537056 and the release notes for more information: https://github.com/microsoft/playwright/releases/tag/v1.47.0#:~:text=%7D)%3B-,Miscellaneous,-The%20mcr.microsoft

Closing as working as intended.

**Closed by mxschmitt** 2024-09-09 06:52 UTC
