### ISSUE TITLE
[BUG] page.goto: Navigation failed because page crashed!

### ISSUE THREAD

**Issue by rinogo** [microsoft/playwright#5687] opened 2021-03-02 22:33 UTC
**Context:**
- Playwright Version: `1.8.0-next` (`3eef2548e4d55db5970a81582bc0276d814c42da`)
- Operating System: macOS 10.15.7
- Node.js version: Node v14.15.1
- Browser: Chromium Version 89.0.4344.0 (Developer Build) (x86_64)

Info from `npx`:
```
  System:
    OS: macOS 10.15.7
    Memory: 436.29 MB / 32.00 GB
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Code Snippet**

```javascript
const { chromium } = require("playwright");
 
(async () => {
  const browser = await chromium.launch({ headless: false }); //Crashes
  //const browser = await chromium.launch({ headless: true }); //Doesn't crash
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto("https://www.californiaorganics.com/");
  const dimensions = await page.evaluate(() => {
    return {
      width: document.documentElement.clientWidth,
      height: document.documentElement.clientHeight,
      deviceScaleFactor: window.devicePixelRatio
    }
  });
  console.log(dimensions);
 
  await browser.close();
})();
```

Output upon crashing:
```
(node:40976) UnhandledPromiseRejectionWarning: page.goto: Navigation failed because page crashed!
=========================== logs ===========================
navigating to "https://www.californiaorganics.com/", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
```

**Describe the bug**
I get the aforementioned error message (`page.goto: Navigation failed because page crashed!`) when I simply try to load `https://www.californiaorganics.com/`. Actually, it looks like it crashes "randomly" at different times - sometimes while loading, other times once loading is complete and my script's actions are underway.

I've written a script (above) that seems to consistently demonstrate the problem. Note that I get different behavior if `headless: false` is specified. Headless doesn't crash whereas non-headless (headful) does crash.

**Comment by pavelfeldman** [comment] 2021-03-03 18:22
It works for me on the same settings. Could you try latest Playwright? That would be 1.9.

**Comment by delimmy** [comment] 2021-03-07 07:13
It's crashing for me as well. Same OS version. Node 14.15.4. On playwright 1.9 (latest)

**Comment by aslushnikov** [comment] 2021-03-18 06:46
@rinogo @delimmy Usually, pages are crashing when they run out of memory. If you just open the chromium browser regularly and navigate it manually to the webpage - does it crash for you?

**Comment by aslushnikov** [comment] 2021-03-18 17:33
@rinogo the best way would be to e-mail them to anlushni [at] microsoft [dot] com

**Comment by aslushnikov** [comment] 2021-03-29 23:57
@rinogo I received your crash video, but that's not actionable by itself, unfortunately. The only way to act upon this would be to have a good repro that we can reproduce locally - this way we can debug what's going on. Any chance you can give us this?

**Comment by rinogo** [comment] 2021-03-30 00:14
@aslushnikov The Code Snippet in this Issue is the best that I can do - it crashes for me. It doesn't crash for you? Maybe it's something specific to this version of OS X.

**Comment by pavelfeldman** [comment] 2021-03-30 15:59
@rinogo does not crash for me, could you try Playwright 1.10? It has newer Chromium...

**Comment by pavelfeldman** [comment] 2021-04-05 20:33
Please file a new bug and link this one if this still is a case for you! Closing this bug as non-actionable for now.

**Closed by pavelfeldman** 2021-04-05 20:33 UTC
Labels: triaging
