### ISSUE TITLE
[BUG] Issue with self-closing popups on Firefox browser.

### ISSUE THREAD

**Issue by terckert** [microsoft/playwright#27543] opened 2023-10-11 11:50 UTC
### System info
- Playwright Version: 1.38.1
- Operating System: Windows 11
- Browser: Firefox
- Other info:

The live environment I'm testing has an iframe that contains a button that opens a pop-up containing an upload element. On clicking the save button, it handles the upload, closes the popup, and refreshes the iframe. I have simplified an approximation of the live environment found at the link below and included a playwright test that I wrote to highlight the issue I'm having.

The test runs fine on safari, chromium, msedge, google chrome, but fails on firefox.

I initially requested help on the discord and was assisted by tphililips who pointed me to here to open a bug report. Additional information provided by tphillips in the course of helping me:

I am seeing the same behaviour, looking into it

It seems like the firefox browser can't see the opened window

actually it can see the window, just not the button for some reason

this is a good case for a bug report on Github

this code works:

```js
test('test', async ({ page }) => {
  await page.goto('https://terckert.github.io/pw-firefox-test/');
  const page1Promise = page.waitForEvent('popup');
  await page.frameLocator('#iframe-id').getByRole('button', { name: 'Click to open a pop up that will take user upload or input.' }).click();
  const page1 = await page1Promise;
  await page1.getByText('I do something, like upload a file or get user input.').click();
});
```

(clicking on the text in the popup)

but even while recording, PW can't record clicking on the button in the popup

works fine with chrome as you say

only broken in firefox
 
### Source code

Site I created to help reproduce the error:
Website: https://terckert.github.io/pw-firefox-test/
Code: https://github.com/terckert/pw-firefox-test

**Test file (self-contained)**

```js
import { test, expect } from '@playwright/test';

test('access iframe after reload', async ({ page }) => {
    await page.goto(`https://terckert.github.io/pw-firefox-test/`)
    for (let i = 0; i < 4; i++) {
        console.log(`Run ${i}`)
        await page.waitForLoadState();
        const popupPromise = page.waitForEvent('popup');
        await page.frameLocator(`#iframe-id`).locator("#iframe-button").click();
        const popup = await popupPromise;
        await popup.waitForLoadState();
        const button = await popup.locator('#popup-button').click()
    }
});
```

**Steps**
- Run the test

**Expected**
Pass

**Actual**
```
locator.click: Target closed
=========================== logs ===========================
waiting for locator('#popup-button')
  locator resolved to <button id="popup-button" onclick="closePopupAndRefreshI…>↵        Click me to close the popup and refresh …</button>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
============================================================
```

**Comment by dgozman** [comment] 2023-10-11 15:51
@terckert Thank you for the great issue! This is a duplicate of #26900, so merging there. Please upvote #26900 to express your interest in the fix - this helps us prioritize.

**Closed by dgozman** 2023-10-11 15:51 UTC
