### ISSUE TITLE
How can I figure out secure connection failed?ignorehttpserror doesn't work.

### ISSUE THREAD

**Issue by jsjs0827** [microsoft/playwright#4855] opened 2020-12-30 05:52 UTC

**Comment by mxschmitt** [comment] 2020-12-30 10:31
Could you provide us a full example from your code?

**Comment by jsjs0827** [comment] 2020-12-30 12:01
I use firefox or webkit of playwright,but I can't link the url of my server with the firefox browser, is there any way to fix this?
By the way, I can link the url with chromium.
Browser Firefox:Secure connection failed

**Comment by mxschmitt** [comment] 2020-12-30 12:03
Are you sure that you pass the option to the context options in the right casing etc. like that?

```js
  const browser = await playwright.chromium.launch();
  const context = await browser.newContext({
    ignoreHTTPSErrors: true
  });
  const page = await context.newPage();
```

**Comment by jiby-gh** [comment] 2021-01-02 10:19
@mxschmitt happens for me with webkit

launch code
```
const browser = await webkit.launch({
    headless: false,
    proxy: { server: `http://${address}:${port}` }
});
const context = await browser.newContext({ ignoreHTTPSErrors: true});
const page = await recorderContext.newPage();
page.goto("https://www.youtube.com");
```

logs
```
> DEBUG=pw:api node index.js

  pw:api => browserType.launch started +0ms
  pw:api <= browserType.launch succeeded +127ms
  pw:api => browser.newContext started +0ms
  pw:api <= browser.newContext succeeded +72ms
  pw:api => browserContext.addInitScript started +0ms
  pw:api <= browserContext.addInitScript succeeded +1ms
  pw:api => browserContext.exposeBinding started +0ms
  pw:api <= browserContext.exposeBinding succeeded +1ms
  pw:api => browser.newContext started +0ms
  pw:api <= browser.newContext succeeded +1ms
  pw:api => browserContext.addInitScript started +0ms
  pw:api <= browserContext.addInitScript succeeded +0ms
  pw:api => browserContext.newPage started +1ms
  pw:api <= browserContext.newPage succeeded +199ms
  pw:api => page.goto started +0ms
  pw:api => browserContext.newPage started +0ms
  pw:api navigating to "https://www.youtube.com", waiting until "load" +1ms
  pw:api <= page.goto failed +98ms
node:internal/process/promises:225
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.goto: An SSL error has occurred and a secure connection to the server cannot be made.
=========================== logs ===========================
navigating to "https://www.youtube.com", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Connection.sendMessageToServer (/Users/jibyjose/Projects/poc/node_modules/playwright/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/Users/jibyjose/Projects/poc/node_modules/playwright/lib/client/channelOwner.js:44:61)
    at /Users/jibyjose/Projects/poc/node_modules/playwright/lib/client/frame.js:80:71
    at Frame._wrapApiCall (/Users/jibyjose/Projects/poc/node_modules/playwright/lib/client/channelOwner.js:72:34)
    at Frame.goto (/Users/jibyjose/Projects/poc/node_modules/playwright/lib/client/frame.js:78:21)
    at /Users/jibyjose/Projects/poc/node_modules/playwright/lib/client/page.js:267:60
    at Page._attributeToPage (/Users/jibyjose/Projects/poc/node_modules/playwright/lib/client/page.js:202:20)
    at Page.goto (/Users/jibyjose/Projects/poc/node_modules/playwright/lib/client/page.js:267:21)
    at file:///Users/jibyjose/Projects/poc/index.js:70:10
    at runNextTicks (node:internal/process/task_queues:58:5)
npm ERR! code 1
npm ERR! path /Users/jibyjose/Projects/poc
npm ERR! command failed
npm ERR! command sh -c DEBUG=pw:api node index.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jibyjose/.npm/_logs/2021-01-02T10_16_02_007Z-debug.log

Process finished with exit code 1
```

**Comment by pavelfeldman** [comment] 2021-01-16 18:23
Sorry for the delay here, what is the OS?

**Comment by yury-s** [comment] 2021-01-19 19:03
> I use firefox or webkit of playwright,but I can't link the url of my server with the firefox browser

@jsjs0827 do you also create context with a proxy?

**Comment by jiby-gh** [comment] 2021-01-19 19:08
@pavelfeldman no need to be sorry :), in my case the os is mac 11.1.

**Comment by aslushnikov** [comment] 2021-01-27 17:45
@jiby-gh what playwright version do you run? Did this regress at some moment or it was like this forever?

**Comment by jiby-gh** [comment] 2021-01-28 11:51
@aslushnikov 1.7.1, though I just tested with 1.8.0, and it's the same behavior. I only started using this with 1.7.1, so I cannot tell if it is a regression or it has always been there.

Also, the proxy I am using is something I just hacked together quickly to test something, so it could be some issues there that trigger it also. As it works with chromium and firefox, didn't look into it further.

**Comment by pavelfeldman** [comment] 2022-01-01 23:06
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing such issues to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-01-01 23:06 UTC
Labels: P2-bug
