### ISSUE TITLE
[Bug]: VSCode extension Watch mode not working (MacOS)

### ISSUE THREAD

**Issue by sarah-gelt** [microsoft/playwright#30951] opened 2024-05-22 09:33 UTC
### Version

1.43.1 / extension 1.1.5

### Steps to reproduce

1. Toggle Watch mode on for a test
2. Wait for the test to finish running
3. Change a test spec file
4. Save the test spec file

### Expected behavior

The test automatically runs again so the saved changes can be validated

### Actual behavior

The test doesn't run again

### Environment

```shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 242.19 MB / 16.00 GB
  Binaries:
    Node: 18.17.1 - /opt/homebrew/opt/node@18/bin/node
    npm: 9.6.7 - /opt/homebrew/opt/node@18/bin/npm
    pnpm: 6.35.1 - ~/.nvm/versions/node/v16.15.1/bin/pnpm
  IDEs:
    VSCode: 1.89.1 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.43.1 => 1.43.1 
    playwright-qase-reporter: ^1.2.0-alpha.3 => v1.2.2 

VSCode:
Version: 1.89.1 (Universal)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:24.611Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```

**Comment by pavelfeldman** [comment] 2024-05-22 16:06
It works for me locally, could you share exact repo / zip where this reproduces?

**Comment by sarah-gelt** [comment] 2024-05-23 08:16
We have quite a complex setup of projects in our config so I'll see if can reproduce which part could be causing it. I can't share our existing repo as-is unfortunately. I'll get back as soon as I can with more info.

**Comment by pavelfeldman** [comment] 2024-05-23 14:36
Ok, I'll leave it open for now!

**Comment by dgozman** [comment] 2024-05-28 15:56
> The only other thing that's unusual is that we use rush to manage a monorepo with the application projects and automation projects together.

This could easily be the problem. I'd recommend to create a new small monorepo managed by rush, with a single minimal app project and a single minimal test project, and see whether things work there. If not, share the project with us.

**Comment by sarah-gelt** [comment] 2024-06-03 15:46
> This could easily be the problem. I'd recommend to create a new small monorepo managed by rush, with a single minimal app project and a single minimal test project, and see whether things work there. If not, share the project with us.

Unfortunately I'm still stumped. I built a rush repo with two playwright projects in it and tried to configure them closely to the ones we have but I still can't reproduce.

I've also tried cutting down our real repo to see if there was anything I could cut out or simplify that would cause the problem to resolve but I'm still nowhere.

Lastly I cloned a whole new copy of our repo from github and the problem also occurred with a fresh one.

So far I've used probably a whole business day trying to find the magic sauce to cause or resolve the issue, but I remain at a loss. It's really frustrating because this would be such a useful tool for the devs in my team if we could get it working.

Is there any way I can debug what's happening, or failing to happen, with the plugin when I save a spec file?

**Comment by mxschmitt** [comment] 2024-06-04 08:08
> Unfortunately I'm still stumped. I built a rush repo with two playwright projects in it and tried to configure them closely to the ones we have but I still can't reproduce.

This means its working there?

> Is there any way I can debug what's happening, or failing to happen, with the plugin when I save a spec file?

Unfortunately not, a reproduction / steps would be the best for us in order to investigate issues like this.

Just to make sure we follow since the issue is getting longer and we are changing triagers:

- Your project is a fairly complex rush project - there you can reproduce (watch doesn't work)
- You tried to reproduce it on a new rush project, a smaller one - there you cannot reproduce (watch works)
- It works for you on a normal non-rush project, following [our intro](https://playwright.dev/docs/intro) - there watch should work

**Comment by sarah-gelt** [comment] 2024-06-04 08:46
> Just to make sure we follow since the issue is getting longer and we are changing triagers:
> 
> * Your project is a fairly complex rush project - there you can reproduce (watch doesn't work)
> * You tried to reproduce it on a new rush project, a smaller one - there you cannot reproduce (watch works)
> * It works for you on a normal non-rush project, following [our intro](https://playwright.dev/docs/intro) - there watch should work

Correct - the only place I can reproduce is our actual complex rush repo which unfortunately I can't share. In a new simpler rush repo and in a normal non-rush project the watch mode works correctly.

**Comment by mxschmitt** [comment] 2024-06-05 12:37
I have to close it unfortunately for now, since we need more information to act on that. Feel free to re-file if you have something to share. Ideally something which we can clone and run locally. Thanks for your understanding!

**Closed by mxschmitt** 2024-06-05 12:37 UTC

**Comment by TesterrA** [comment] 2024-09-05 07:25
I am encountering the same issue with the VSCode extension's Watch mode not working on my MacOS setup. Unfortunately, like the original author, it's quite challenging for me to share our repository due to its complexity and internal constraints. I see that this thread is currently closed, but I wanted to highlight that this problem still persists for others. If there’s any additional debug information or steps I can provide that might help without sharing the repo, please let me know. It would be great to have this functionality working, as it would be very valuable for our team.
