### ISSUE TITLE
Installing only required playwright packages in existing Docker image

### ISSUE THREAD

**Issue by ThatYodaCoder** [microsoft/playwright#31186] opened 2024-06-06 13:01 UTC
I have an existing docker image of my Java based application. I want to open web page in headless browser mode in my existing java application using playwright java library.
Can some one please help me with this. I want install required packages in my docker image from playwright docker image.

Can some please explain how to do this in Docker file?
Also, do I need Node.js to run headless browser when using java library?

**Comment by ThatYodaCoder** [comment] 2024-06-06 13:05
I have an existing docker image of my Java based application. I want to open web page in headless browser mode in my existing java application using playwright library. 
Can some one please help me with this. I want install required packages in my docker image from plawright docker image.

Can some please explain how to do this in Docker file?
Also, do I need Node.js to run headless browser when using java library?

**Comment by mxschmitt** [comment] 2024-06-06 14:11
> Can some please explain how to do this in Docker file?

See here: https://playwright.dev/java/docs/browsers#install-system-dependencies

> Also, do I need Node.js to run headless browser when using java library?

No, only the Playwright for Java package is needed.

I'm going to close it for now, since this is not a bug / feature request.

**Closed by mxschmitt** 2024-06-06 14:11 UTC

**Comment by ThatYodaCoder** [comment] 2024-06-07 03:54
> > Can some please explain how to do this in Docker file?
> 
> See here: https://playwright.dev/java/docs/browsers#install-system-dependencies
> 
> > Also, do I need Node.js to run headless browser when using java library?
> 
> No, only the Playwright for Java package is needed.
> 
> I'm going to close it for now, since this is not a bug / feature request.

@mxschmitt : Is there anyway I can predownload the required dependencies/binaries and keep it in some folder so that I can use it at the time of docker creation.

Or can I use existing playwright docker image to install required dependencies at the time of my java app docker file creation?

**Comment by mxschmitt** [comment] 2024-06-07 07:25
Unfortunately not, you need to install the Maven dependencies first and then the Playwright dependencies. Since they contain OS dependencies (`apt`), you can't cache them.

You could probably create some multi-layer Docker image with only Playwright first and extend from that in order to benefit from caching, so that the whole image does not need to be rebuilt when you change something in your project.

We also have an official Java Docker image, if that helps: https://playwright.dev/java/docs/docker
