### ISSUE TITLE
[BUG] v1.31.2 project dependencies did not take effect. All testcases are skipped during execution.

### ISSUE THREAD

**Issue by tomoyachen** [microsoft/playwright#21418] opened 2023-03-06 05:51 UTC
I referenced this document and made changes to my project.
https://playwright.dev/docs/next/api/class-testproject#test-project-dependencies

I added setup and dependencies to the `playwright.config.ts` and created the `global.setup.ts`.

playwright.config.ts
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/42526054/223028808-de14554a-dbb1-4b16-b17f-b94c9c36def9.png">

global.setup.ts
```
import { test as setup } from '@playwright/test';

setup('normal user', async ({page}) =>{
  page.goto('/')
})

```

However, when I use the execution use case all testcases are skipped.
```bash
chen@MacBook-Pro-CW lc-playwright % yarn playwright --version                                           
yarn run v1.22.4
$ /Users/chen/qa/lc-playwright/node_modules/.bin/playwright --version
Version 1.31.2
✨  Done in 1.16s.

chen@MacBook-Pro-CW lc-playwright % yarn playwright test tests/lccn/examples --headed --project chromium
yarn run v1.22.4
$ /Users/chen/qa/lc-playwright/node_modules/.bin/playwright test tests/lccn/examples --headed --project chromium

Running 9 tests using 0 workers
  9 skipped

To open last HTML report run:

  npx playwright show-report

✨  Done in 1.53s.
```

I'm guessing that  `testMatch: /. *\.setup\.ts/` does not match the `global.setup.ts` file in the project.

------

I have done the following attempts
  1. move `global.setup.ts` to the root directory of the project
  2. test matching to `/global\.setup\.ts/`, `"global.setup.ts"`.
  3. Use an extremely simple `global.setup.ts` that does not contain any code other than the standard output.

**Comment by Nav-2d** [comment] 2023-03-06 08:48
Related https://github.com/microsoft/playwright/issues/21270

**Comment by mxschmitt** [comment] 2023-03-06 08:53
How does your global setup files look like? If you use it via dependencies, it needs to be written like that: 

```ts
import { test as setup, expect } from '@playwright/test';
setup('do login...', () => {
  // ...
});
```

Exporting it as a global object does not work like it was done before, thats most likely the issue in your scenario.

**Comment by tomoyachen** [comment] 2023-03-06 09:20
> Related #21270

Thank you, I have found the problem with the link you provided.

My configuration file defines `"testDir": ". /tests/lccn",` and the `testMatch: /. *\.setup\.ts/` seems to only find for files in the `testDir` directory.


My project is structured like this, and that's the problem.

tests/
  - project_1/
      - case_1.spec.ts
  - project_2/
      - case_2.spec.ts
  - global.setup.ts

**Comment by mxschmitt** [comment] 2023-03-06 09:23
You can set a custom testDir for your setup project if you like: `testDir: '.'`

**Comment by tomoyachen** [comment] 2023-03-06 09:31
> You can set a custom testDir for your setup project if you like: `testDir: '.'`

Hi, thanks for your follow up. I have resolved my issue. But I'm not sure if this really makes sense, and it would largely affect the value of `testDir `.

I now have to remove my `testDir` from the config file. And use a more specific command to execute different projects.

```bash
yarn playwright test tests/project_1
yarn playwright test tests/project_2
```


My project is structured like this. 

tests/
 - project_1/
   - case_1.spec.ts
 - project_2/
   - case_2.spec.ts
 - global.setup.ts

**Comment by mxschmitt** [comment] 2023-03-07 23:22
Sounds reasonable to me! since the setup project will match setup files only anyways. Since the issue is resolved, I'm closing it for now.

**Closed by mxschmitt** 2023-03-07 23:22 UTC
Labels: triaging
