### ISSUE TITLE
[BUG] iFrame content with different domain not visible in WebView2

### ISSUE THREAD

**Issue by alminveh** [microsoft/playwright#28577] opened 2023-12-11 13:58 UTC
[WinForms_GettingStarted_Test.zip](https://github.com/microsoft/playwright/files/13635804/WinForms_GettingStarted_Test.zip)
[WinForms_GettingStarted.zip](https://github.com/microsoft/playwright/files/13636264/WinForms_GettingStarted.zip)
### System info
- Playwright Version: 1.40.0 (.NET)
- Operating System: Windows 11
- Browser: WebView2

### Source code

Attached.

**Steps**
- Extract, open, and run WinForms_GettingStarted
- Extract, open, and run test (UnitTest1/Test1) in WinForms_GettingStarted_Test

**Expected**

Test should pass. There are two frames on the page (main one and one iFrame), elements inside the iFrame are visible.

**Actual**

Test fails. There is only one frame on the page (main one), elements inside the iFrame are not visible.

**Comment by mxschmitt** [comment] 2023-12-12 00:46
I see that you are using a very old version of the WebView2 package. Could you try upgrading? `0.9.579-prerelease` is almost 3 years old and not marked as stable (pre-release).

We internally use this project to run our tests on WebView2: https://github.com/microsoft/playwright/tree/main/tests/webview2/webview2-app

Would be awesome if you could try on a more recent WebView2 version before we dig deeper into this specific issue.

**Comment by alminveh** [comment] 2023-12-12 08:15
That is just the version used in this example app, in our application we use 1.0.2088.41and we see the same issue. I will try to reproduce the issue with your webview2-app as well.

**Comment by alminveh** [comment] 2023-12-12 08:43
Issue is reproducible with https://github.com/microsoft/playwright/tree/main/tests/webview2/webview2-app as well, I can provide the steps to reproduce if needed.

**Comment by mxschmitt** [comment] 2023-12-12 16:03
> Issue is reproducible with https://github.com/microsoft/playwright/tree/main/tests/webview2/webview2-app as well, I can provide the steps to reproduce if needed.

That would be awesome!

**Comment by alminveh** [comment] 2023-12-12 16:28
1. Comment out or remove line 44 in Form1.Designer.cs (this one https://github.com/microsoft/playwright/blob/10dda30c7f417a92f782e21368fbb211a679838a/tests/webview2/webview2-app/Form1.Designer.cs#L44)

2. Update Form1.cs like this -> 
[Form1.txt](https://github.com/microsoft/playwright/files/13650689/Form1.txt)

3. Run webview2-app

4. Run test from [WinForms_GettingStarted_Test](https://github.com/microsoft/playwright/files/13635804/WinForms_GettingStarted_Test.zip)

**Comment by mxschmitt** [comment] 2023-12-13 04:19
Looks like an upstream bug an similar/duplicate of https://github.com/microsoft/playwright/issues/17656#issuecomment-1292433595.

**Comment by mxschmitt** [comment] 2023-12-13 18:03
Folding into it for now.

**Closed by mxschmitt** 2023-12-13 18:03 UTC
