### ISSUE TITLE
[Bug]: Tag printed twice on html report when put on a test.describe block using the new syntax.

### ISSUE THREAD

**Issue by PramodKumarYadav** [microsoft/playwright#29962] opened 2024-03-15 17:11 UTC
### Version

1.42.1

### Steps to reproduce

1. Tag `test.describe` with a tag name so that we dont have to tag individual tests. Example below. 

![image](https://github.com/microsoft/playwright/assets/11694972/42014a52-6a3e-4f4d-9df2-89beb25c4b83)

### Expected behavior

Expected to see the tag value only printed once agains the test. 

### Actual behavior

Found it to be printed twice on the html report. 

![image](https://github.com/microsoft/playwright/assets/11694972/17c6f7cf-279a-4ed8-94bf-b559a8bd8d61)

### Environment

```shell
System:
  Hardware Overview:
  Model Name:	MacBook Air
  Model Identifier:	Mac14,15
  Chip:	Apple M2
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	16 GB

npm packages:
  "@playwright/test": "^1.42.1",
```

**Comment by mxschmitt** [comment] 2024-03-15 17:16
Would it be possible to provide a self-contained reproduction? We are unfortunately not able to reproduce scenarios based on screenshots.

**Comment by PramodKumarYadav** [comment] 2024-03-16 11:24
@mxschmitt : I tried replicating it with a sample hobby project but could not replicate. I will have a look at my real project and see what is different there that triggers this response. Hopefully by Monday I can give you the reason and code to replicate it. If not, we can close the ticket.

**Comment by yury-s** [comment] 2024-03-18 23:41
Closing per the last comment. Feel free to open a new issue once you have a reproduction.

**Closed by yury-s** 2024-03-18 23:41 UTC
