### ISSUE TITLE
[REGRESSION]: Tests with angular 13 and transloco no longer work

### ISSUE THREAD

**Issue by Wandang** [microsoft/playwright#14352] opened 2022-05-23 16:30 UTC
**Context:**
- GOOD Playwright Version: 1.16
- BAD Playwright Version: 1.22
- Operating System: Mac
- Extra:  typescript <4.5, transloco >=4.0.0 (4.x is compatible with angular 13)

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

**Describe the bug**

I tried several configurations:

Angular | ESM active | typescript | playwright | transloco | outcome
-- | -- | -- | -- | -- | --
13 | ⛔ | <4.5 (angular 13 is not compatible with 4.5 and above yet) | 1.22.2 | >=4.0.0 | Tests don’t workError [ERR_REQUIRE_ESM]: require() of ES Module /Users/cde/dev/appname/node_modules/@ngneat/transloco/fesm2015/ngneat-transloco.mjs not supported.
  | :check_mark: with classic import of modules (/foo) | <4.5 (angular 13 is not compatible with 4.5 and above yet) | 1.22.2 | >=4.0.0 | Tests don’t workError [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/cde/dev/appname/src/app/shared/models/check.model' imported from /Users/cde/dev/appname/src/app/shared/models/actor-document.model.ts
  | :check_mark: with new import of modules (/foo.js) | <4.5 (angular 13 is not compatible with 4.5 and above yet) | 1.22.2 | >=4.0.0 | App no longer compiles

So when I change my imports to the new ESM standard angular 13 will no longer compile. if I use the old approach with esm activated (package.json has "type": "module") test won't work because the modules can no longer be resolved

When I take the even older approach of no ESM and classic imports I get errors regarding requires in third party dependencies.

```
// tsconfig.json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./src",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "skipLibCheck": true,
    "target": "es2020",
    "module": "ES2020",
    "lib": ["es2020", "dom"],
    "resolveJsonModule": true
  },
  "exclude": ["node_modules"]
}

```

not sure what config combination would need to be taken to use angular 13 with playwright 1.22 and third parties with require imports.

**Comment by pavelfeldman** [comment] 2022-05-23 21:09
Could you provide a repro or files I could paste to give it a try?

**Comment by Wandang** [comment] 2022-05-24 08:39
thanks for your quick reply:

https://github.com/Wandang/angular-transloco-playwright-test

if you try to execute the test via npm run e2e you will face this error:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/cde/dev/angular-transloco-playwright-test/angular-transloco-playwright-test/node_modules/@ngneat/transloco/fesm2015/ngneat-transloco.mjs not supported.
Instead change the require of /Users/cde/dev/angular-transloco-playwright-test/angular-transloco-playwright-test/node_modules/@ngneat/transloco/fesm2015/ngneat-transloco.mjs to a dynamic import() which is available in all CommonJS modules.
```

we had those UI tests running with angular <13 in the past. not sure what is forcing the new esm imports for playwright tests

**Comment by pavelfeldman** [comment] 2022-05-31 23:09
I copied a part of `transloco-e2e.ts` into the following snippet:

test.mjs
```js
import {
  HashMap,
} from '@ngneat/transloco';

console.log(HashMap);
```

And I could not run it. Also, you do want to use `type: module` for TS to import EJS.

**Comment by Wandang** [comment] 2022-06-02 13:17
Thanks for pointing out a few things.

I adjusted my example to be even simpler. I only import Transloco now, threw out the transloco-e2e setup usage. Furthermore I fixed the PlaywrightConfig typeimport and added the module type to package.json.

This is the current error
```
file:///Users/<username>/dev/angular-transloco-playwright-test/angular-transloco-playwright-test/node_modules/@ngneat/transloco/fesm2015/ngneat-transloco.mjs:5
import { unflatten as unflatten$1, flatten as flatten$1 } from 'flat';
                                   ^^^^^^^
SyntaxError: Named export 'flatten' not found. The requested module 'flat' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'flat';
const { unflatten: unflatten$1, flatten: flatten$1 } = pkg;
```

It is unclear to me whether the issue lies with Transloco or with Playwright. How can we configure the project to make playwright tests work? Thanks in advance

**Comment by pavelfeldman** [comment] 2022-06-03 00:21
It my repro above, I don't use Playwright at all, and I get the same error about flatten. So I believe the issue is with how `transloco` consumes `flat`. Playwright is not even mentioned in my (and your) snippet.

**Comment by pavelfeldman** [comment] 2022-06-03 00:22
I'll close this as not a bug, please feel free to file a new issue and link this one if you discover Playwright has anything to do with the problem!

**Closed by pavelfeldman** 2022-06-03 00:22 UTC
Labels: v1.23
