### ISSUE TITLE
[Question] How to generate HTML report when an unhandled exception happens

### ISSUE THREAD

**Issue by paymog** [microsoft/playwright#16811] opened 2022-08-24 20:57 UTC
I'm finding that playwright doesn't generate an html report if there's an unhandled exception during testing. I have a test that looks like the following:

```
      const firstSubgraphName = cuid();
      const subgraphPath = await cloneSubgraph({ subgraphPath: ethBlocksSubgraphPath, startBlock: 100 });
      await buildSubgraph(subgraphPath);
      await deploySubgraph(firstSubgraphName, '1', { cwd: subgraphPath });
      await removeSubgraphDeployment(firstSubgraphName, '1');
      expect(...)
```

and it's possible that these functions could fail. I find that when they fail I get output like the following:

```
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "- Removing subgraph
 ✖ Subgraph removal failed: Make sure to run 'goldsky login' before running any commands requiring authorization.
 - Removing subgraph
✖ Subgraph removal failed: Make sure to run 'goldsky login' before running any commands requiring authorization.
".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

and then a `playwright-report` directory with a report isn't generated.

Is there a way to configure playwright to generate a report, even when an unhandled rejection occurs?

**Comment by yury-s** [comment] 2022-08-24 23:19
What playwright and node versions are you using? I tried with the simple test case below where a promise throws unhandled error and the report is generated just fine with playwright 1.25.1:

```ts
import { test } from '@playwright/test';

async function throwError() {
    throw new Error('xxx');
}

test('test', async({ page }) => {
    throwError();
});
```
Can you reproduce it with the latest playwright? If so please attach a reproducible example that we can run locally.

**Comment by paymog** [comment] 2022-08-25 14:05
Ah, I did a bit more debugging and this was a typing snafu by me!

The error was happening in a `test.describe` block and not a `test` block which I guess is why the whole framework exited.

**Comment by yury-s** [comment] 2022-08-25 16:50
Closing as the problem seems to be solved, feel free to file another bug if it's not.

**Closed by yury-s** 2022-08-25 16:50 UTC
Labels: triaging
