### ISSUE TITLE
[Feature] Recorder - specify preference order of locators

### ISSUE THREAD

**Issue by dmcweeney** [microsoft/playwright#27180] opened 2023-09-19 11:30 UTC
When using the recorder Playwright mostly generates the tests using getByPlaceholder/getByLabel/getByText.

My number 1 preference for locators is getByTestId - and I would like the recorder to generate as much the test code as possible using getByTestId. The testId setting should be picked up from the config.ts testIdAttribute setting.

One option might be to specify a command line argument to specify the preferential order for locator generation.

Thanks, Donal

**Comment by aslushnikov** [comment] 2023-09-20 14:07
Merging this as a dupe of https://github.com/microsoft/playwright/issues/19439

**Closed by aslushnikov** 2023-09-20 14:07 UTC

**Comment by aslushnikov** [comment] 2023-09-20 17:16
> The testId setting should be picked up from the config.ts testIdAttribute setting.

@dmcweeney how do you launch recorder? If you were to use VSCode extension, then it will read your config settings for the `testId`.

If you launch codegen from terminal, then you can pass it in as an argument:

```bash
npx playwright codegen --test-id-attribute="data-test-id"
```

**Comment by dmcweeney** [comment] 2023-09-21 09:45
@aslushnikov thanks for the pointer - I had not realised you could specify it as a command line argument.
Passing this through to codegen results in much better locator generation.
