### ISSUE TITLE
[Bug] Firefox fails with STATUS_DLL_NOT_FOUND on some Win 10 setups

### ISSUE THREAD

**Issue by kdivekar** [microsoft/playwright#2298] opened 2020-05-19 14:06 UTC
HI,

I have been experimenting playwright for our product UI automation.
I have a package.json and login page script. When I run it, it works well and launches Chromium and Firefox for me. I am on Ubuntu.
When I ask my team members to try the code. For 2 users firefox does not launch on their machines. One user is on Ubuntu and one is on Windows. ESame code works for other 2 users without any issue.

Error is -

```
Failed to launch browser!


 TROUBLESHOOTING: https://github.com/Microsoft/

 at onClose (node_modules/playwright-core/lib/server/processLauncher.js:151:20)
 at Interface.<anonymous> (node_modules/playwright-core/lib/server/processLauncher.js:144:65)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.241s
Ran all test suites.
/home/ui-automation/node_modules/playwright-core/lib/server/firefox.js:107
                if (browserServer)
                ^

ReferenceError: Cannot access 'browserServer' before initialization
    at Object.onkill (/home/ui-automation/node_modules/playwright-core/lib/server/firefox.js:107:17)
    at ChildProcess.<anonymous> (/home/ui-automation/node_modules/playwright-core/lib/server/processLauncher.js:77:21)
    at Object.onceWrapper (events.js:417:26)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ui-automation@1.0.0 test:firefox: `BROWSER='firefox' jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ui-automation@1.0.0 test:firefox script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Below is my package.json
```
{
  "name": "ui-automation",
  "version": "1.0.0",
  "description": "UI Testing Framework",
  "main": "index.js",
  "scripts": {
    "test:webkit": "BROWSER='webkit' jest",
    "test:chrome": "BROWSER='chromium' jest",
    "test:firefox": "BROWSER='firefox' jest",
    "test:debug": "node --inspect node_modules/.bin/jest --runInBand"
  },
  "keywords": [
    "jest",
    "playwright",
    "jest-playwright",
    "example"
  ],
  "dependencies": {
    "dotenv": "^8.2.0",
    "jest-cli": "^26.0.1",
    "regex": "^0.1.1",
    "jest-environment-node": "^25.2.3",
    "jest-playwright-preset": "^0.1.3"
  },
  "jest": {
    "preset": "jest-playwright-preset"
  },
  "devDependencies": {
    "jest": "^26.0.1",
    "playwright": "^1.0.1"
  }
}
```
Can someone help me understand what could be the issue here?

**Comment by pavelfeldman** [comment] 2020-05-19 15:35
`Cannot access 'browserServer' before initialization` is our bug, we'll fix it right away. But the issue is that for some reason Playwright can't start the browser. Could you ask users that suffer from this issue to set an environment variable `DEBUG=pw:browser*` and see if there are any hints in the output?

**Comment by kdivekar** [comment] 2020-05-19 17:33
Thank you for the reply..
here are the logs with DEBUG=pw:browser*


  pw:browser <launching> /home/.cache/ms-playwright/firefox-1089/firefox/firefox -no-remote -headless -profile /tmp/playwright_dev_firefox_profile-oDsgah -juggler 0 -silent +0ms
  pw:browser <launched> pid=3441 +43ms
  pw:browser:err XPCOMGlueLoad error for file /home/.cache/ms-playwright/firefox-1089/firefox/libxul.so: +0ms
  pw:browser:err **/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found** (required by /home/.cache/ms-playwright/firefox-1089/firefox/libxul.so) +0ms
  pw:browser:err Couldn't load XPCOM. +3ms
 FAIL  test/login.spec.js
  ● Test suite failed to run

    Failed to launch browser!


    TROUBLESHOOTING: https://github.com/Microsoft/playwright/blob/master/docs/troubleshooting.md

      at onClose (node_modules/playwright-core/lib/server/processLauncher.js:150:20)
      at Interface.<anonymous> (node_modules/playwright-core/lib/server/processLauncher.js:143:65)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.468 s
Ran all test suites.
  pw:browser <process did exit 255, null> +472ms
/home/ui-automation/node_modules/playwright-core/lib/server/firefox.js:105
                if (browserServer)
                ^

ReferenceError: Cannot access 'browserServer' before initialization
    at Object.onkill (/home/ui-automation/node_modules/playwright-core/lib/server/firefox.js:105:17)
    at ChildProcess.<anonymous> (/home/ui-automation/node_modules/playwright-core/lib/server/processLauncher.js:76:21)
    at Object.onceWrapper (events.js:417:26)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ui-automation@1.0.0 test:firefox: `BROWSER='firefox' jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ui-automation@1.0.0 test:firefox script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2020-05-19T17_23_14_843Z-debug.log


seems to be missing library - /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found

**Comment by pavelfeldman** [comment] 2020-05-19 17:57
It looks like you are on Ubuntu 16, while we require 18 for Firefox. Is that the case?

**Comment by aslushnikov** [comment] 2020-05-20 00:08
> ReferenceError: Cannot access 'browserServer' before initialization

For the record: this is already fixed in e8e761f77.

**Comment by kdivekar** [comment] 2020-05-20 04:57
@pavelfeldman as you [ointed out, user is on ubuntu 16 where the failure is observed
below are debud logsfor windows user -

(node:6616) ExperimentalWarning: The fs.promises API is experimental
  pw:browser <launching> C:\Users\MUKESH\AppData\Local\ms-playwright\firefox-1089\firefox\firefox.exe -no-remote -headless -profile C:\Users\MUKESH\AppData\Local\Temp\playwright_dev_firefox_profile-fNVzTM -juggler 0 -silent +0ms
  pw:browser <launched> pid=12960 +34ms
  console.log
    undefined

      at Object.beforeAll (test/login.spec.js:18:11)

 FAIL  test/login.spec.js
  Test Login with SP:
    × Login as Service Provider (7 ms)

  ● Test Login with SP: › Login as Service Provider

    Failed to launch browser!


    TROUBLESHOOTING: https://github.com/Microsoft/

      at onClose (node_modules/playwright-core/lib/server/processLauncher.js:150:20)
      at Interface.helper_1.helper.addEventListener (node_modules/playwright-core/lib/server/processLauncher.js:143:65)

  ● Test Login with SP: › Login as Service Provider

    TypeError: Cannot read property '$' of null

      38 |      it('Login as Service Provider', async () => {
      39 |
    > 40 |              await page.$(loginPage.SELECT_ACCOUNT);
         |                         ^
      41 |              await page.click(loginPage.SELECT_ACCOUNT);
      42 |
      43 |              await helpers.typeText(page, input.ServiceProvider.domain, loginPage.SELECT_ACCOUNT);

      at Object.it (test/login.spec.js:40:14)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        4.546 s
Ran all test suites.
  pw:browser <process did exit 3221225781, null> +317ms
D:\ui-automation_Playwright\node_modules\playwright-core\lib\server\firefox.js:105
                if (browserServer)
                ^

ReferenceError: browserServer is not defined
    at Object.onkill (D:\ui-automation_Playwright\node_modules\playwright-core\lib\server\firefox.js:105:17)
    at ChildProcess.spawnedProcess.once (D:\ui-automation_Playwright\node_modules\playwright-core\lib\server\processLauncher.js:76:21)
    at Object.onceWrapper (events.js:285:13)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ui-automation@1.0.0 test:firefox: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ui-automation@1.0.0 test:firefox script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MUKESH\AppData\Roaming\npm-cache\_logs\2020-05-20T04_52_18_937Z-debug.log

**Comment by pavelfeldman** [comment] 2020-05-20 15:40
Your Windows machine returns `STATUS_DLL_NOT_FOUND` error (Exit code 0xC0000135). It can't fine one of the required Windows DLLs. Could you share the version of the OS?

**Comment by pavelfeldman** [comment] 2020-05-20 15:43
@aslushnikov should we push 1.0.3 with the fox for missing browserServer right away? It removes the noise from the launch error logs and makes it easier to spot the actual problem error.

**Comment by kdivekar** [comment] 2020-05-20 16:10
Its windows 10

**Comment by nesrineabdmouleh** [comment] 2020-06-01 16:11
Hello, 
I have the same problem in my machine when I run the test using firefox but it works well when I launch Chromium.
I use the Debian GNU/Linux 8 distribution.

Please see the test results.
```
"before all" hook:
     Uncaught ReferenceError: browserServer is not defined
      at Object.onkill (node_modules/playwright-core/lib/server/firefox.js:105:17)
      at ChildProcess.spawnedProcess.once (node_modules/playwright-core/lib/server/processLauncher.js:76:21)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

  if (browserServer)
                ^

ReferenceError: browserServer is not defined
    at Object.onkill (/projet/node_modules/playwright-core/lib/server/firefox.js:105:17)
    at ChildProcess.spawnedProcess.once (/projet/node_modules/playwright-core/lib/server/processLauncher.js:76:21)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

```

**Comment by kdivekar** [comment] 2020-06-05 09:31
@aslushnikov when can we expect the fix to be available?

**Comment by yury-s** [comment] 2020-07-31 23:14
Launch doctor now has functionality that should provide more insight into what libraries are missing on the system. Please give it a try (currently available in playwright@next) and reopen this issue if it's still not working for you.

**Closed by yury-s** 2020-07-31 23:14 UTC
