### ISSUE TITLE
[ONGOING OUTAGE / INTERMITTENT DOWNLOAD FAILURE]: CDN for browser downloads is not public, returns 409

### ISSUE THREAD

**Issue by emma-sg** [microsoft/playwright#32185] opened 2024-08-15 21:10 UTC
### Version

1.46.0

### Steps to reproduce

1. Run `npx playwright install chromium` — I have tested on macOS and Linux

### Expected behavior

I expect Chromium to be downloaded and installed

### Actual behavior

The download fails with a 409 status code and a `PublicAccessNotPermitted` error code in the response XML.

### Additional context

Full error log:
```
Downloading Chromium 112.0.5615.29 (playwright build v1055) from https://playwright.azureedge.net/builds/chromium/1055/chromium-mac-arm64.zip
Error: Download failed: server returned code 409 body '<?xml version="1.0" encoding="utf-8"?><Error><Code>PublicAccessNotPermitted</Code><Message>Public access is not permitted on this storage account.
RequestId:5de1b575-f01e-00a2-2457-ef41d6000000
Time:2024-08-15T21:07:07.0949013Z</Message></Error>'. URL: https://playwright.azureedge.net/builds/chromium/1055/chromium-mac-arm64.zip
    at IncomingMessage.handleError (/Users/emma/Work/Webrecorder/browsertrix/frontend/node_modules/playwright-core/lib/server/registry/oopDownloadMain.js:46:23)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Downloading Chromium 112.0.5615.29 (playwright build v1055) from https://playwright-akamai.azureedge.net/builds/chromium/1055/chromium-mac-arm64.zip
Error: Download failed: server returned code 409 body '<?xml version="1.0" encoding="utf-8"?><Error><Code>PublicAccessNotPermitted</Code><Message>Public access is not permitted on this storage account.
RequestId:edcc0f1e-501e-0060-5557-ef0750000000
Time:2024-08-15T21:07:07.3289090Z</Message></Error>'. URL: https://playwright-akamai.azureedge.net/builds/chromium/1055/chromium-mac-arm64.zip
    at IncomingMessage.handleError (/Users/emma/Work/Webrecorder/browsertrix/frontend/node_modules/playwright-core/lib/server/registry/oopDownloadMain.js:46:23)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Downloading Chromium 112.0.5615.29 (playwright build v1055) from https://playwright-verizon.azureedge.net/builds/chromium/1055/chromium-mac-arm64.zip
Error: Download failed: server returned code 409 body '<?xml version="1.0" encoding="utf-8"?><Error><Code>PublicAccessNotPermitted</Code><Message>Public access is not permitted on this storage account.
RequestId:edcc0f46-501e-0060-6557-ef0750000000
Time:2024-08-15T21:07:07.5114117Z</Message></Error>'. URL: https://playwright-verizon.azureedge.net/builds/chromium/1055/chromium-mac-arm64.zip
    at IncomingMessage.handleError (/Users/emma/Work/Webrecorder/browsertrix/frontend/node_modules/playwright-core/lib/server/registry/oopDownloadMain.js:46:23)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Failed to install browsers
Error: Failed to download Chromium 112.0.5615.29 (playwright build v1055), caused by
Error: Download failure, code=1
    at ChildProcess.<anonymous> (/Users/emma/Work/Webrecorder/browsertrix/frontend/node_modules/playwright-core/lib/server/registry/browserFetcher.js:95:16)
    at ChildProcess.emit (node:events:518:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

### Environment

```shell
System:
    OS: macOS 14.5
    Memory: 143.94 MB / 16.00 GB
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by emma-sg** [comment] 2024-08-15 21:11
A user on the Discord seems to be having this same issue with Firefox: https://discord.com/channels/807756831384403968/1273732372956839967

**Comment by TimChild** [comment] 2024-08-15 21:20
I am also having the same issue with firefox.

**Comment by mxschmitt** [comment] 2024-08-15 21:20
should be fixed, please retry!

**Comment by emma-sg** [comment] 2024-08-15 21:32
Can't seem to reproduce any more, thank you!

**Comment by alexmt** [comment] 2024-08-15 23:57
Just got the same error :( 


```
curl https://playwright-verizon.azureedge.net/builds/driver/playwright-1.45.1-mac-arm64.zip
<?xml version="1.0" encoding="utf-8"?><Error><Code>PublicAccessNotPermitted</Code><Message>Public access is not permitted on this storage account.
RequestId:3a2322dc-c01e-003f-626e-efb36c000000
Time:2024-08-15T23:57:21.1588539Z</Message></Error>%
```

**Comment by emma-sg** [comment] 2024-08-16 00:43
Yeah, can reproduce, it still seems to be occurring at the moment

**Comment by S64** [comment] 2024-08-16 00:59
Same issue here.
I thought maybe only some hosts were down, so I tried defining `PLAYWRIGHT_DOWNLOAD_HOST` as a workaround, but the behavior did not change. It seems that the issue is happening on every of hosts.

- https://github.com/microsoft/playwright/blob/b2ccfc3d01f8c1e228ec7af683115696fbf806fa/docs/src/browsers.md?plain=1#L625-L631
- https://github.com/microsoft/playwright/blob/b2ccfc3d01f8c1e228ec7af683115696fbf806fa/packages/playwright-core/src/server/registry/index.ts#L39-L43

**Comment by TerenceTian625** [comment] 2024-08-16 01:26
Same issue here, failed to download browser on windows and ubuntu-24.04

**Comment by justin-roller** [comment] 2024-08-16 01:51
Just started working for us again 🤞

**Comment by pavelfeldman** [comment] 2024-08-16 01:54
We are experiencing intermittent Azure-related CDN access failures, apologies for the inconvenience.

**Comment by Skn0tt** [comment] 2024-08-19 08:51
The outage is resolved, closing.

**Closed by Skn0tt** 2024-08-19 08:51 UTC
