### ISSUE TITLE
[BUG] Playwright 1.38 cannot run Chromium nor Firefox on macOS 13/14

### ISSUE THREAD

**Issue by fdv3** [microsoft/playwright#27358] opened 2023-09-29 11:41 UTC
### System info
- Playwright Version: [v1.38.1]
- Operating System: [macOS 13.5.2, macOS 14.0]
- Browser: [Chromium, Firefox]
- Other info: Chromium 117.0.5938.62 (playwright build v1080), Firefox 117.0 (playwright build v1424)

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```js
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await browser.close();
})();
```

```js
const { firefox } = require('playwright');

(async () => {
  const browser = await firefox.launch();
  await browser.close();
})();
```

**Steps**
- Run the tests.

**Expected**

The tests end without any error.

**Actual**

The first test causes this error:

```shell
/Users/.../nodejs/playwright/node_modules/playwright-core/lib/server/chromium/crPage.js:377
      this._firstNonInitialNavigationCommittedReject(new Error('Page closed'));
                                                     ^

Error: Page closed
    at CRSession.<anonymous> (/Users/.../nodejs/playwright/node_modules/playwright-core/lib/server/chromium/crPage.js:377:54)
    at Object.onceWrapper (node:events:627:28)
    at CRSession.emit (node:events:525:35)
    at /Users/.../nodejs/playwright/node_modules/playwright-core/lib/server/chromium/crConnection.js:211:39
```

The second test causes this error:

```shell
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

browserType.launch: Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> /Users/.../Library/Caches/ms-playwright/firefox-1424/firefox/Nightly.app/Contents/MacOS/firefox -no-remote -headless -profile /var/folders/dt/9bj0djrs22x5g66k9_nbz2zc0000gn/T/playwright_firefoxdev_profile-dxdJBm -juggler-pipe -silent
<launched> pid=18686
[pid=18686][err] *** You are running in headless mode.
[pid=18686] <process did exit: exitCode=null, signal=SIGSEGV>
[pid=18686] starting temporary directories cleanup
=========================== logs ===========================
<launching> /Users/.../Library/Caches/ms-playwright/firefox-1424/firefox/Nightly.app/Contents/MacOS/firefox -no-remote -headless -profile /var/folders/dt/9bj0djrs22x5g66k9_nbz2zc0000gn/T/playwright_firefoxdev_profile-dxdJBm -juggler-pipe -silent
<launched> pid=18686
[pid=18686][err] *** You are running in headless mode.
[pid=18686] <process did exit: exitCode=null, signal=SIGSEGV>
[pid=18686] starting temporary directories cleanup
============================================================
    at /Users/.../nodejs/playwright/test/example.test2.js:4:33
    at Object.<anonymous> (/Users/.../nodejs/playwright/test/example.test2.js:7:3) {
  name: 'Error'
}
```

Notice that in this second test, not even the call to create the new page is made.

It seems that the browser versions Chromium 117.0.5938.62 (playwright build v1080) and Firefox 117.0 (playwright build v1424) crash when launched in macOS 13.5.2 and macOS 14.0.

NOTE: I experienced a similar issue but with Playwright 1.36.2 and Firefox and Webkit. The only browser that worked fine was Chromium.

**Comment by fdv3** [comment] 2023-09-29 11:53
Additional info:

I installed the new browsers with the following command:

```shell
npx playwright install --with-deps
```

When running Chromium from its installation folder, it does not get opened and I get the following error:

```shell
Received signal 11 <unknown> 000000000000
 [0x000121656d82]
 [0x000121649143]
 [0x000121656cd1]
 [0x7ff81813737d]
 [0x000121603fc0]
 [0x0001237b3e0e]
 [0x0001237b3a58]
 [0x000120ffc11f]
 [0x000120ffd194]
 [0x000120ffcc29]
 [0x00011f30e1d8]
 [0x00011fa339db]
 [0x00011f30e75f]
 [0x00011f31126a]
 [0x00011f30cddf]
 [0x0001208a0df6]
 [0x0001208a1f96]
 [0x0001208a1df0]
 [0x0001208a056f]
 [0x0001208a0755]
 [0x00011cb598b1]
 [0x0001090238de]
 [0x7ff817d813a6]
[end of stack trace]
[0929/135034.230873:WARNING:crash_report_exception_handler.cc(235)] UniversalExceptionRaise: (os/kern) failure (5)
[1]    18937 segmentation fault  ./Chromium
```

When running Firefox from its installation folder, it does not get opened and I get the following error:

```shell
[1]    19065 segmentation fault  ./firefox
[1]    19089 segmentation fault  ./firefox-bin
```

**Comment by yury-s** [comment] 2023-09-29 17:58
Looks like something is busted on your machine as the browsers cannot start. Our tests run on macOS 13.5 bots and locally with no issues. We cannot do much without being ale to reproduce this locally and not having enough diagnostic information.

**Comment by fdv3** [comment] 2023-09-30 09:57
I have a MacBook Pro 16-inch, 2019.

Processor: 2,3 GHz 8-Core Intel Core i9
Graphics: Intel UHD Graphics 630 1536 MB
Memory: 32 GB 2667 MHz DDR4

I downloaded the Chromium version 117.0.5938.112 Official Build x86_64 (not the Playwright build) and it works fine.

Just in case this helps.

**Comment by pavelfeldman** [comment] 2023-10-04 16:58
Let's check that you are downloading Intel version of the browser:

Run
```sh
file /Users/<user>/Library/Caches/ms-playwright/chromium-1080/chrome-mac/Chromium.app/Contents/MacOS/Chromium
```

It should not say arm, should be amd something. If it is saying arm, try reinstalling the browsers:

Run 
```sh
npx playwright uninstall --all
npx playwright install
```

You should see the browser URLs that are getting downloaded from the CDN. Could you share those and double check if the Intel versions of the browsers are downloaded?

**Comment by fdv3** [comment] 2023-10-05 08:51
When I execute the command:
```shell
file /Users/<user>/Library/Caches/ms-playwright/chromium-1080/chrome-mac/Chromium.app/Contents/MacOS/Chromium
```
I get the following output:
```shell
/Users/<user>/Library/Caches/ms-playwright/chromium-1080/chrome-mac/Chromium.app/Contents/MacOS/Chromium: Mach-O 64-bit executable x86_64
```

And the output when I install the browsers is as follows:
```shell
Downloading Chromium 117.0.5938.62 (playwright build v1080) from https://playwright.azureedge.net/builds/chromium/1080/chromium-mac.zip
136.1 Mb [====================] 100% 0.0s
Chromium 117.0.5938.62 (playwright build v1080) downloaded to /Users/<user>/Library/Caches/ms-playwright/chromium-1080
Downloading FFMPEG playwright build v1009 from https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip
1.1 Mb [====================] 100% 0.0s
FFMPEG playwright build v1009 downloaded to /Users/<user>/Library/Caches/ms-playwright/ffmpeg-1009
Downloading Firefox 117.0 (playwright build v1424) from https://playwright.azureedge.net/builds/firefox/1424/firefox-mac-13.zip
75.9 Mb [====================] 100% 0.0s
Firefox 117.0 (playwright build v1424) downloaded to /Users/<user>/Library/Caches/ms-playwright/firefox-1424
Downloading Webkit 17.0 (playwright build v1908) from https://playwright.azureedge.net/builds/webkit/1908/webkit-mac-13.zip
64.2 Mb [====================] 100% 0.0s
Webkit 17.0 (playwright build v1908) downloaded to /Users/<user>/Library/Caches/ms-playwright/webkit-1908
```

It seems that everything is correct. However, I downloaded Chromium directly using the url https://playwright.azureedge.net/builds/chromium/1080/chromium-mac.zip, I decompressed it using the Archive Utility.app or The Unarchiver.app and it worked fine.

If I decompress it using the unzip command from the terminal, then the browser does not work.

If I get a md5 from both executables, the result is the same.

Could it be, maybe, a problem related to the way the symlinks are being decompressed?

**Comment by pavelfeldman** [comment] 2023-10-05 18:32
This is indeed unexpected, could you compare the extracted files using these two utilities? We can't repro it on our side...

**Comment by fdv3** [comment] 2023-10-05 19:23
Which utilities?

**Comment by pavelfeldman** [comment] 2023-10-05 19:37
I meant if Archive Utility.app produces working build and unzip produces not working build, can you extract them into sibling folders and compare them?

**Comment by fdv3** [comment] 2023-10-06 09:21
Ok, understood.

The comparison gets the following results (in the left side, the working browser):

Chromium:
<img width="1633" alt="chromium_comparison" src="https://github.com/microsoft/playwright/assets/854308/8ea929f0-b361-417e-acd0-ac35903488c9">

Firefox:
<img width="1617" alt="firefox_comparison" src="https://github.com/microsoft/playwright/assets/854308/b706cd8d-8f08-41ef-9d37-15783fbc248a">

Here you are a link to download both browsers. The one uncompressed with Archive Utility.app (working fine) and the other uncompressed by npx (not working) for both, Chromium and Firefox: [browsers](https://we.tl/t-vwhlsHHd59)

FYI: to compress/uncompress I used Archive Utility, version 10.15

**Comment by pavelfeldman** [comment] 2023-10-06 16:05
Thanks for the additional info. Some binary files are indeed different, I'm seeing diffs like:

```
< 00a0b350: 0000 0000 0000 4700 6900 dd1e 2000 4800  ......G.i... .H.
---
> 00a0b350: b1ae 1a00 0000 4700 6900 dd1e 2000 4800  ......G.i... .H.
```

Given that simple unzip results in different results on your system, and that there were no other reports of this kind, we believe that your Node installation or operating system is corrupted. I would start with reinstalling Node, but otherwise, there is nothing we can do on our side to recover from this error.

**Comment by pavelfeldman** [comment] 2023-10-06 16:06
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2023-10-06 16:06 UTC
Labels: triaging

**Comment by fdv3** [comment] 2023-10-07 09:58
Thank you very much. At least, I have the workaround of downloading the browsers manually and replace them in the folder npx installs them.

**Comment by tomowang** [comment] 2024-08-20 12:00
Same issue here. But the manually downloaded and unzipped files are same with the npx installed ones. And the manually downloaded one crashed the same way.

![image](https://github.com/user-attachments/assets/233e1ec0-cb04-44d1-b8fb-27622e5b31cf)


After digging deeper, it seems to be the `DYLD_LIBRARY_PATH` env as per https://github.com/microsoft/playwright/issues/31064#issuecomment-2138905093.

Remove this from my zshrc and chromium works as expected.
