### ISSUE TITLE
[BUG] What is the wrong with page.on method?

### ISSUE THREAD

**Issue by YusuffOzt** [microsoft/playwright#21707] opened 2023-03-16 11:02 UTC
My aim is here reading a authenticate request's json body from network. But when I run below code,the below message shown in terminal ;
`Promise { <pending> }`

Is there should be a bug or Am I doing something wrong when I reading the authenticate request's json body?

 ```
setup('authenticate as uber admin user', async ({ page }) => {
  await page.goto(`${configEnv.baseURL}`)
  await page.locator(LoginPageRepository.emailTextField!).fill(process.env.U_EMAIL!)
  await page.locator(LoginPageRepository.passwordTextField!).fill(process.env.U_PASS!)
  await page.locator(LoginPageRepository.loginButton!).click() _//when click the login authenticate request will be visible on the network_
  page.on('requestfinished', async (request) => {
    if (request.url().match(/authenticate/)) {
        let response = await request.response();
        console.log(response?.json())
        fs.writeFileSync(
          "./fixtures/asset/a.json",
          JSON.stringify(response?.body())
        );
   }
  })
  await page.context().storageState({ path: configAuth.UberAuth });
});
```

By the way here I m writing to a json file.Is there any way writing to localStorage or sessionStorage using page.on() or page.evalute() methods? Could you show me a sample how to write response.body() to localStorage or sessionStorage and how to read response.json from different file using a localStorage or sessionStorage?

**Comment by ltsuda** [comment] 2023-03-16 12:46
I don't know if the `page.on` block is correct or not but **think** it should be before the `click` line.

Regarding the local/sessionStorage, see if this helps
https://github.com/microsoft/playwright/issues/16094#issuecomment-1201265040
https://playwright.dev/docs/next/auth#session-storage

**Comment by YusufOzt** [comment] 2023-03-16 12:53
@ltsuda thanks for response. I see it is my fault 

Forgot "await", I fixed not a bug. 

console.log(await response?.json())

**Comment by dgozman** [comment] 2023-03-16 19:24
Closing per above.

**Closed by dgozman** 2023-03-16 19:24 UTC
