### ISSUE TITLE
[Bug]: Playwright Test runner struggles with clicking combobox elements and opening option lists. Inconsistent behaviour.

### ISSUE THREAD

**Issue by toduyemi** [microsoft/playwright#31741] opened 2024-07-17 19:48 UTC
### Version

1.45.0

### Steps to reproduce

The product code is proprietary and runs on a local environment. Even so, as a tester, reproducing this is out of my depth. I've included videos showing the headed browser and Playwright Inspector opening. I'd like to emphasize that this behaviour does not occur when I go through these user flows manually. I have no problem clicking these elements manually.

### Expected behavior

To able to click and open a list of options. See video 3.

### Actual behavior

Video1: https://drive.google.com/file/d/1BYTFZ5O_0dwTKAuS3siqiQseh8LcWYmH/view?usp=drive_link

Video2: https://drive.google.com/file/d/1fyBVhQM2brEAdgJQNeRcLRtJNfXGnNMq/view?usp=drive_link

Video3: https://drive.google.com/file/d/1DthXDwi6HGg_NDV5LtitkaGocYbaR69Y/view?usp=drive_link

Video 1: There is a weird issue where the runner can't click on the element. This is the error: "subtree intercepts pointer events retrying click action"

so I try .click({force: true}) and it works but then

Video 2: the next combobox fails to open the list, however since the actionability checks are disabled there is no retry, it passes that step and stalls at the next. Why does the force api work for one combobox but fails on the next?

Video 3: The behaviour takes another left. If I pause the script and step through the test, the combobox clicks and the list opens passing the next step without a hitch. If I click through manually, again I experience no problems opening up the list of options.

This behaviour has come up in multiple place throughout the app, and ignoring it isn't possible anymore.

I would really appreciate some help diagnosing this problem and figuring out the source of this behaviour. 

I've tried different solutions locator.dispatchEvent and even locator.evaluate(e => e.click). To no effect. There is no calculated z-index property on any of the relevant elements so an overlay interception seems unlikely.

Since it works when I use debugging tools, those are of little help. Is there a way to capture and log the element that receives the click event?

### Additional context
**Here's a trace viewer sc showing the test steps working on a combobox element:**
<img width="1818" alt="Screenshot 2024-07-17 at 1 46 10 PM" src="https://github.com/user-attachments/assets/043ffe66-cb63-4e71-8012-6496d60ad084">

 **In the step after, with another combobox:**
<img width="1862" alt="Screenshot 2024-07-17 at 12 45 10 PM" src="https://github.com/user-attachments/assets/c160e002-f46b-4a12-9fee-35b246bc4af1">

This image of the trace viewer shows that the locator resolves to the intended target element.

### Environment

```shell
System: macOS Sonoma 14.5

Node 20.14.4

npm 10.7.0
```

**Comment by dgozman** [comment] 2024-07-18 20:47
@toduyemi Unfortunately, we won't be able to help without a repro. I'd recommend digging in the trace viewer to see what's going on. You can also debug with the inspector, as seen on the video, and see the live page. There is no way around opening browser developer tools and figuring out the issue.

Note that `subtree intercepts pointer events` log line shows exactly which element intercepts the click from the target element. You can find that element on the page using Playwright Inspector or browser developer tools and see what's going on.

If you believe the problem is not in the page or your test, but in the Playwright itself, we will need a reproduction that we can run locally in order to proceed.

**Comment by pavelfeldman** [comment] 2024-07-22 23:12
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Closed by pavelfeldman** 2024-07-22 23:12 UTC
