### ISSUE TITLE
[Bug]: getComputedStyle() and Element.style  are not working as expected in WebKit and Firefox

### ISSUE THREAD

**Issue by serferdinand2** [microsoft/playwright#30208] opened 2024-04-02 13:57 UTC
### Version

1.42.1

### Steps to reproduce

Test looks like this: 

```ts 

let canvas: FrameLocator;
test.beforeEach(async ({ page }) => {
	canvas = (await loadStory(page, 'button')) as FrameLocator;
});

test.describe('Button component', () => {
	test.only('basic', async ({ page }) => {
		const btn = canvas.getByRole('button');
		await expect(btn).toBeVisible();
		const styles = await getStyles(btn);
		const btnRect = await btn.boundingBox();

		await expect(btn).toHaveClass(/sp-button/);
		await expect(btn).toHaveClass(/sp-button--primary/);
		await expect(btn).toHaveClass(/sp-button--medium/);
		await expect(btn).not.toHaveClass(/sp-button--active/);

		expect(await btn.innerText()).toBe('Submit');
		expect(styles.backgroundColor).toBe('rgb(25, 31, 41)');
		expect(styles.borderRadius).toBe('5px');
		expect(styles.color).toBe('rgb(255, 255, 255)');
	});
	// some other tests
});
```

My utility that returns the styles is: 

```ts 
export const getStyles = async (
	locator: Locator
): Promise<CSSStyleDeclaration> => {
	console.log(
		'THIS IS THE LOCATOR',
		await locator.evaluate((el) => el.style)
	);
	return await locator.evaluate((el) => {
		return window.getComputedStyle(el, null) as CSSStyleDeclaration;
	});
};
```

My settings are: 

```ts 
import { defineConfig, devices } from '@playwright/test';
export default defineConfig({
	testDir: './src/tests',
	timeout: 20 * 2000,
	expect: {
		timeout: 5 * 2000,
	},
	fullyParallel: true,
	forbidOnly: !!process.env.CI,
	retries: process.env.CI ? 2 : 0,
	workers: process.env.CI ? 1 : undefined,
	/* Reporter to use. See https://playwright.dev/docs/test-reporters */
	// reporter: [['html', { open: 'never' }]],
	reporter: 'list',
	use: {
		testIdAttribute: 'data-id',
		baseURL: 'http://localhost:6006',
		screenshot: process.env.CI ? 'off' : 'only-on-failure',
		trace: 'on-first-retry',
		actionTimeout: 10000,
		navigationTimeout: 10000,
		viewport: {
			width: 1200,
			height: 1800,
		},
	},
	webServer: {
		command: 'npm run dev',
		url: 'http://localhost:6006',
		reuseExistingServer: !process.env.CI,
	},
	/* Configure projects for major browsers */
	projects: [
		{
			name: 'chromium',
			use: { ...devices['Desktop Chrome'] },
		},
		{
			name: 'firefox',
			use: { ...devices['Desktop Firefox'] },
		},
		{
			name: 'Microsoft Edge',
			use: { channel: 'msedge' },
		},
		{
			name: 'webkit',
			use: { ...devices['Desktop Safari'] },
		},

	],

});
```

In Chrome and Edge the test passes fine 
in WK and FF the test fails 

### Expected behavior

Expected to pass the test and console the el.style. 

### Actual behavior

The test fails for FF and WK and reeds styles as undefined. The console, instead of returning the element styles, returns an empty object 

![Screenshot_2024-04-01_at_22 58 49](https://github.com/microsoft/playwright/assets/93290291/bb187b78-ff4d-4e74-a8d8-8e78126a1e5e)

### Additional context

The images below show the console.log of element.style I got from the locator first one is in chrome the second one is from webkit 

![Screenshot 2024-04-02 at 15 59 51](https://github.com/microsoft/playwright/assets/93290291/cde97bb9-96ea-4ff0-99b3-ff881feca62c)

![Screenshot 2024-04-02 at 15 59 34](https://github.com/microsoft/playwright/assets/93290291/71c77965-2c15-40c5-b460-52b8f152d30b)

### Environment

```shell
System: MacOS 
Framework: SvelteKit 2 with Svelte 5 preview
Node: v18.19.1
```

**Comment by dgozman** [comment] 2024-04-02 16:20
@serferdinand2 I did some testing, and I cannot reproduce the issue. `getComputedStyle()` always returns all styles in all browsers. `element.style` returns all styles in Chromium and only the styles directly defined on the element in Firefox/WebKit. Also note that on your screenshot you call `getComputedStyle()` passing `:before`, while it should be `::before` with double colon.

If you still believe there is a bug, please provide full self-contained repro that we can run locally. Unfortunately, we cannot run the snippets above since they are missing a lot of code, including the web page itself.

**Comment by dgozman** [comment] 2024-04-05 20:15
Closing as per above. If you still encounter problems, please file a new issue with a repro by filling in the "Bug Report" template.

**Closed by dgozman** 2024-04-05 20:15 UTC
