### ISSUE TITLE
[BUG] OPTIONS requests are not intercepted for HAR generation

### ISSUE THREAD

**Issue by alinmihailiuc** [microsoft/playwright#22783] opened 2023-05-03 12:01 UTC
### System info
- Playwright Version: [v1.32]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [Chromium]

### Source code
```
@pytest.fixture(scope="session")
def browser_context_args(browser_context_args):
    current_test = os.environ.get("PYTEST_CURRENT_TEST").split(":")[-1].split(" ")[0]
    tc_id = current_test.split("_")[1]
    path = f"results/{tc_id}.har"
    return {
        **browser_context_args,
        "viewport": {
            "width": 1920,
            "height": 1080,
        },
        "record_har_path": path,
        "record_har_omit_content": False,
    }
```

- [x] I provided the exact source code that allows reproducing the issue locally.

**Steps**
- I'm using the attached fixture within the tests 
- At the end the HAR is created with all the requests done in Browser, except the `OPTIONS` method requests
- I also tried creating the HAR file 'manually' by using `page.on("requestfinished")` but it looks like `OPTIONS` requests are not intercepted 🤔 

Is there some extra configuration I'm missing to 'force' the `OPTIONS` request to be present?

**Expected**

`OPTIONS` requests to be present

**Actual**

`OPTIONS` requests are missing

**Comment by yury-s** [comment] 2023-05-04 00:18
I can reproduce it with cors fetch request that issues a preflight `OPTIONS` request. That request doesn't have matching frame so we don't dispatch `request/requestfinished` events for it, neither it settles in the har file. With that said replaying from the har should still work as playwright will automatically fulfill preflight OPTIONS requests with 204. Does it cause any problems for you when replaying from har or is it just the fact that the request is missing in the har file?

**Comment by alinmihailiuc** [comment] 2023-05-04 06:33
Firstly, thanks for looking into it!
It does not cause any problems, the fact that the request is missing is an issue... We're suspecting that we're receiving sometimes, intermittently, 5** Status Codes for those requests and we want to provide the HAR file to the support team that can investigate this issue. They've requested the HAR file where we capture these `OPTIONS` requests as well.

**Comment by yury-s** [comment] 2023-05-04 16:45
Are these `OPTIONS` requests preflight requests for `fetch` calls or something else? To provide a fix we need to better understand if there are other places where `OPTIONS` request is missing, in addition to the preflights mentioned above.

**Comment by yury-s** [comment] 2023-05-04 20:11
Ok, but at least all of them are preflight requests.

**Comment by yury-s** [comment] 2023-05-05 22:27
Node.js repro https://github.com/yury-s/bug-22783.git

**Comment by dgozman** [comment] 2023-05-05 23:32
### Chromium
- We receive both OPTIONS and DELETE requests, but OPTIONS is missing the `frameId`, because it [comes without one](https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:content/browser/devtools/network_service_devtools_observer.cc;l=147;drc=2d9e261c929ea4e27b76421069b488c6feae61f2) from the network service.
- We can fix this by taking `frameId` from the original request: https://github.com/microsoft/playwright/commit/0ba5a319d5db15ecd5c2e648c407254a1394b15f.

### Firefox
- We receive `Network.responseReceived` and `Network.requestFinished` for the OPTIONS, but not `Network.requestWillBeSent`. This gives me hope that it's possible to fix this in Firefox.

### WebKit
- No events whatsoever about the OPTIONS request. It's not very likely we'll get them in WebKit.

### Notes
Given the above, we can try to fix for Chromium and Firefox, or not report OPTIONS in all browsers as we do today.

**Comment by dgozman** [comment] 2023-05-08 17:29
We discussed this issue with the team. It is very unlikely that we can report options preflights in WebKit on MacOS due to the proprietary network stack. Given the above options, it would be better to omit preflights across all browsers, as we do today. Therefore, closing this issue as not planned. Thank you for filing!

**Closed by dgozman** 2023-05-08 17:29 UTC
Labels: browser-chromium, v1.34
