### ISSUE TITLE
[Question]route.fulfill method use path or body params on Macos load more than 20M jsfile is too slow

### ISSUE THREAD

**Issue by Faye-dirzzle** [microsoft/playwright#13292] opened 2022-04-01 00:41 UTC
route.fulfill method use path or body params on Macos load more than 20M jsfile is too slow

like this:
```
def handle_pass(self, route):
     url = route.request.url
     if 'index.js' in url:
         route.fulfill(path=cwd + '/air_3u_new/static/index.js')
     if 'vendor.js' in url:
         route.fulfill(path=cwd + '/air_3u_new/static/vendor.js')
     elif 'awsc.js' in url:
         route.fulfill(path=cwd + '/air_3u_new/static/aws.js')
     elif 'app.css' in url:
         route.fulfill(path=cwd + '/air_3u_new/static/app.css')
     elif 'manifest.js' in url:
         route.fulfill(path=cwd + '/air_3u_new/static/mainifest.js')
     elif 'app.js' in url:
         route.fulfill(path=cwd + '/air_3u_new/static/app.js')
         # route.fulfill(body=app_js_content)
     elif 'fireyejs.js' in url:
         route.fulfill(path=cwd + '/air_3u_new/static/fire.js')
     elif 'nc.js' in url:
         route.fulfill(path=cwd + '/air_3u_new/static/nc.js')
     elif 'getProcessTrackingForApi' in url:
         self.data = route.request.post_data
         self.headers = route.request.all_headers()
         self.post_url = url
         route.abort()
     else:
         route.continue_(url=url)```

**Comment by mxschmitt** [comment] 2022-04-04 12:51
Do you have a repro for it? Loading a 20 MB JavaScript file is a heavy process for a browser.

**Comment by Faye-dirzzle** [comment] 2022-04-06 02:13
> Do you have a repro for it? Loading a 20 MB JavaScript file is a heavy process for a browser.

MacOS takes almost a minute, while windows takes only about five seconds

**Comment by mxschmitt** [comment] 2022-04-06 08:33
Which Python version are you using? You could try to use the Node.js variant so we can exclude that its caused by the Python language binding.

**Comment by aslushnikov** [comment] 2022-04-14 21:15
Closing since the discussion has staled. Feel free to re-file!

**Closed by aslushnikov** 2022-04-14 21:15 UTC
Labels: triaging
