### ISSUE TITLE
Can playwright team publish paths to binaries on playwright.azureedge.net?

### ISSUE THREAD

**Issue by rschlotman** [microsoft/playwright#14173] opened 2022-05-15 19:00 UTC
Hello,

Our corp firewalls are aggresively blocking us from being able to do the typical bin\Debug\netX\playwright.ps1 install chromium commands successfully.  The TLS handshake fails:

![image](https://user-images.githubusercontent.com/74566220/168489351-7d63d6f6-d692-402d-92db-317fe25d770e.png)

With that said I did notice a different github issue with the full path to the chromium zip was hittable over http.  Yes - that means I have to then go shift everything after download to be in the appropriate folders here for my Windows box: %USERPROFILE%\appData\Local\ms-playwright  .  Thats fine and I managed to do that with the chromium one I could directly hit.

However, I need to do the same for FFMPEG and others in the future.  Can the team just publish paths to them so we can take care of the work manually the the .ps1 file tried to make easy for us?  That way we can adopt your tools in our env despite the corporate constraints.

**Comment by rwoll** [comment] 2022-05-16 18:35
While this information can technically be gathered from https://github.com/microsoft/playwright/tree/main/packages/playwright-core/src/server/registry, I don't suggest it. 

> With that said I did notice a different github issue with the full path to the chromium zip was hittable over http.

Can you access other https sites from your machine and from node? Or is it just a problem when access Playwright's CDN?

**Comment by rwoll** [comment] 2022-05-21 02:22
Closing as part of triage! We'll need more information to make recommendations. Thanks!

**Closed by rwoll** 2022-05-21 02:22 UTC
Labels: triaging

**Comment by rschlotman** [comment] 2022-05-22 13:25
@rwoll apologies for slowness in response.  Its an issue with the ps1 script trying to call out to Playwright's azure edge cdn from behind aggressive corp firewalls / zscalers etc.  AzureEdge seems to need another cert type to be trusted by the machine itself in order to complete the ssl handshake to it.  Its not available in the windows machines cert trust store in mmc.  I was looking around for what that might be, but didn't have enough time to finish that thread.

What I did notice is its relatively easy to reverse engineer the azureedge paths for your ffmpeg and chromium custom build browsers etc.  Its not ideal state to manually go grab and drop in appropriate folder structure but is a valid workaround for now in our context.  I thought it might be easier if you just published them though so that others didn't have to reverse engineer like I did that are facing same type of issues

**Comment by rwoll** [comment] 2022-05-22 21:06
> AzureEdge seems to need another cert type to be trusted by the machine itself in order to complete the ssl handshake to it. Its not available in the windows machines cert trust store in mmc. I was looking around for what that might be, but didn't have enough time to finish that thread.

Hmm…something sounds off here. Stock Windows, Mac, Linux, etc. trust our CDN's certs. There shouldn't be anything special about them.

Since you mention zscaler, it sounds like there's a few layers in between Playwright's install script and our CDN, so I'd recommend debugging to try to figure out what across your network is preventing the download.

I'm going to leave this closed given the above, but if after debugging your network you find that it's Playwright, please file a new issue and we can triage again and try to get things working happily for you without needing the paths to be published.

Thanks!

**Comment by rschlotman** [comment] 2022-05-22 22:23
@rwoll its kind of you to answer on a weekend.  Thanks for doing so.  As mentioned we have aggressive blocking and its likely around Zscaler on our side.  With that said the simple request was to just publish your new artifact paths so others living in these corporate scenarios can go down a more manual way than the playwright.ps1 script to achieve adoption of playwright as a whole by using the browser to download them instead of the ps1 which is actually reflecting into the microsoft.playwright.dll and then attempting calls to azureedge for downloading.

Either way we are able to work around - I just wanted this project to get as much adoption as possible.  Given I see the project having to direct people to proxy and other things I imagine others are struggling and a % of them fall out from adopting because of it.

**Comment by rwoll** [comment] 2022-05-23 13:54
I failed to state an explicit assumption/goal: before recommending and helping folks more generally with a workaround, I'd like to ensure the root cause is determined and there's not a better fix on the PW side.

For instance, based on your comments, it sounds like it might be zscaler, but we don't know that for sure yet. If you could assist in debugging that, I'd greatly appreciate it since I'm don't have a network setup that mocks your environment.

Furthermore, if it is zscaler, what about the PW CDN's certs specifically are not compatible with it? Do other sites suffer the same fate, or is there something else PW needs to do differently to make sure it's supported? If we're on some zscaler blocklist outside of your organization, that would also be good to know, too.

Between the fact that HTTP works for you but not HTTP**S**, and I can put https://playwright.azureedge.net/builds/chromium/1006/chromium-mac-arm64.zip in my browser, and it downloads without complaint, suggests the certs are fine and some proxy or something is misbehaving and doing some bad MITM or something (or some cert needs to be trusted on your end related to the proxy/zscaler).

Thanks for your patience!
