### ISSUE TITLE
[Bug]: Playwright tests cannot read indexedDb stores when accessing a browser extension with `chrome-extension` protocol

### ISSUE THREAD

**Issue by harel** [microsoft/playwright#30421] opened 2024-04-18 20:43 UTC
### Version

1.43.1

### Steps to reproduce

Reproduction here: https://github.com/harel/pw-db-bug

Open extension page which uses indexedDB using 

`page.goto(`chrome-extension://{extensionId}/somefile.html`)`

In the test use evaluate or evaluateHandle to read the DB and query it. 

### Expected behavior

I expect the database to fire `onupgradeneeded` when the new page context is created and the objectStores created to be accessible and available. 

### Actual behavior

The database exists, but `onupgradeneeded` is not fired and the object stores are not there.

### Additional context

When using playwright to test a browser extension which makes use of indexedDb, there are problems accessing the database objectStores properly within the context of the tests if accessing the page as a `chrome-extension://`. The database is there and accessible but none of the `objectStores` are created or available, and the `onupgradeneeded` event handler is never fired. 

I can call `page.goto` to the extension using the `chrome-extension://` protocol, which works fine. But opening the extensions like that and trying to access the objectStoreNames of the DB yields an empty object store name list. Trying to execute a transaction against an object store that is meant to be there fails saying it's not there. 
Calling runtime.sendMessage works (as in, it doesn't error).

I can also call `page.goto` to the extension using a simple `file://` protocol. In that case, the DB is accessible and the objectStores ARE available. However any call to runtime.sendMessage will error. 

This puts me in a stuck position of being unable to write tests for this kind of extension. Am I doing something wrong here? Is th

I am running playwright with:
`PW_EXPERIMENTAL_SERVICE_WORKER_NETWORK_EVENTS=1 npx playwright test --ui`

I'm also importing `test` and `expect` from a fixture where I'm using `launchPersistentContext` and loading the extension, as per the recommendations regarding browser extensions. This behaviour is exhibited with headless true or false.

Because of the nature of this problem providing a simple code example won't do. So I've created a tiny repo which demonstrates the issue here:  https://github.com/harel/pw-db-bug

once cloned you can execute the tests to demonstrate the problem using: 

`PW_EXPERIMENTAL_SERVICE_WORKER_NETWORK_EVENTS=1 npx playwright test --ui`

### Environment

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 9.63 GB / 31.05 GB
    Container: Yes
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1
```

**Comment by yury-s** [comment] 2024-04-18 23:53
> When using playwright to test a browser extension which makes use of indexedDb, there are problems accessing the database objectStores properly within the context of the tests if accessing the page as a chrome-extension://.

I see the same behavior without Playwright too, so it seems to be a problem with the app.

**Comment by yury-s** [comment] 2024-04-19 00:25
Looks like a bug in Chromium to me, if I start the browser like this
```
/Users/user/Library/Caches/ms-playwright/chromium-1112/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-extensions-except=/Users/user/sandbox/pw-db-bug --load-extension=/Users/user/sandbox/pw-db-bug --user-data-dir=/tmp/p1
```

and then open `chrome-extension://gknkhkamgkalmpdhmhodmfakdhhfmmpa/test.html`, there is no onupgradeneeded event. But if I delete the indexeddb via devtools and then reload the page, everything works. We cannot do anything about it on Playwright end, you can file a bug in the Chromium repository (https://crbug.com/).

**Comment by harel** [comment] 2024-04-19 08:13
@yury-s what you describe is actually the correct behaviour of onupgradeneeded. When a database exists, onupgradeneeded will only fire when the version is increased (or when the database was just created and the default version of 1 constitutes a version change). 

However, in playwright if I open the extension within the chrome-extension:// protocol context, it doesn't fire onupgradeneeded even if I change versions or the database is newly created. Also I would have assumed the page being opened is a brand new browser page without any database initially. So either way it should have been fired. 
If I open the extension as a file - the onupgradeneeded is fired and the objectStores do exist but then I have no "extension context" and no service worker etc. etc.

**Comment by yury-s** [comment] 2024-04-19 15:54
> When a database exists, onupgradeneeded will only fire when the version is increased (or when the database was just created and the default version of 1 constitutes a version change).

I start the browser with a fresh profile directory, so there are no existing dbs. Did you try it without playwright? Did the event fire for you?

**Comment by harel** [comment] 2024-04-19 17:03
Yes without playwright it works as expected. When you run it in the browser the DB will be created if it does not exist, when you open it, then fire the upgrade event  IF the database requested is new or a new version than what exists.. In playwright it is created as well, just not firing the event and therefore the object stores are not being created. The only way that it works under playwright is if I open the page like a regular file, and not like an extension. 

Note in my reproduction repository  there are multiple test cases, two are demonstrating the issue when opening it like an extension and the other two show when it is open as a file.

**Comment by yury-s** [comment] 2024-04-19 18:02
> Yes without playwright it works as expected. When you run it in the browser the DB will be created if it does not exist, when you open it, then fire the upgrade event IF the database requested is new or a new version than what exists..

I just checked on 2 other machines, everywhere I start chromium with a new profile ( hence db does not exist yet), the db gets created and dbRequest.onsuccess is fired, but there is **no** dbRequest.onupgradeneeded.  Loading with existing profile and bumped version in `open()` does not change anything. This is all when I manually navigate to `chrome-extension://<ext id>/test.html` and then check the output in devtools console. On linux I cannot even load details of MYDB in Application tab in DevTools. Not sure what you do differently to see `onupgradeneeded` event fired.

**Comment by harel** [comment] 2024-04-20 00:07
Here is what I observe:

I installed the extension to my Chrome, and navigate to  my local url which is;

chrome-extension://ommghkdmchelbkhbfabokcmaknpjolig/test.html

onsuccess will fire on successful connection to the database. 
onupgradeneeded is fired when schema changes are occurring (i.e., version changed from 1 to 2, 2 to 3 etc.). 

If i add a version number (and subsequently raise it: 

`const dbRequest = window.indexedDB.open(DATABASE_NAME, 2);`

onupgradeneeded is triggered and the object store `mydata` IS created for me.

However in the playwright test, i can change the version number many times - it never fires onupgradeneeded when in the test context.

**Comment by yury-s** [comment] 2024-04-20 00:28
> I installed the extension to my Chrome, and navigate to my local url which is;

It sounds like you installed it to Chrome via its UI rather than launching Chromium with a new profile a passing the command line arguments pointing to the extension directory. This is not apples to apples comparison as the bug may well be specific to the extensions loaded from the directory passed via `--load-extension` flag.

**Comment by harel** [comment] 2024-04-20 01:07
Yes, that's kinda my point - the problem exists only when I'm trying to create tests in playwright. 
My tests using the chrome-extension error because the object store mydata is not being created and therefore not available. 
When I install it in chrome, as I would any extension, it works fine. I'm using --load-extension in the args to launchPersistentContext as it was recommended by the docs.

**Comment by mxschmitt** [comment] 2024-04-22 17:43
I tried running this command:

    ~/Library/Caches/ms-playwright/chromium-1112/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-extensions-except=$PWD --load-extension=$PWD --user-data-dir=./profile

and the database is empty (no onupgradeneeded was fired):

<img width="753" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/24ba3b97-b528-4aa4-95f4-df0f22e6b561">

I was also not able to reproduce it in normal Google Chrome (Stable) - so this does not look like a Playwright bug to me.

**Comment by yury-s** [comment] 2024-04-22 17:45
Closing this bug, as `onupgradeneeded` event is just not fired when you load extension from a directory specified in `--load-extension` flag. It has nothing to do with Playwright. Feel free to open a bug in Chromium repository.

**Closed by yury-s** 2024-04-22 17:45 UTC
