### ISSUE TITLE
[Regression]: Self signed certificate now produces ERR_SSL_KEY_USAGE_INCOMPATIBLE

### ISSUE THREAD

**Issue by SteveW94** [microsoft/playwright#31143] opened 2024-06-04 09:06 UTC
### Last Good Version

1.40.1

### First Bad Version

1.41.0

### Steps to reproduce

Due to customer data restrictions etc. I am sadly not able to provide a repo or sth. Nontheless I would be very happy If you could support me in any way to get this working again and do not reject this immidiatly...

So what we do is, we test against  server with a self-signed certificate. For now this certificate is a blackbox...nothing can be changed there for now that easily.
We use the chromium of PW to test.
Until PW 1.40.1 everything worked fine...locally and on our AzureDevOps pipeline.
From every further PW version, the Error described here occured.
It seemed it has sth. to do with the chrome version similar as described here:

https://community.netgear.com/t5/Orbi-Pro-WiFi-for-Small-Business/Chrome-Certificate/td-p/2347230

Also we tried the following start arguments to chromium already addtitional to the "ignoreHTTPSerrors" property:
                         '--ignore-certificate-errors',
                        '--use-fake-device-for-media-stream',
                        '--ignore-certificate-errors-spki-list',
                        '--force-fieldtrials=RSAKeyUsageForLocalAnchors/DisabledLaunch',
                        
What seems also weird/what we discovered is the following:
- It does not work anymore on the Pipeline but did before
- It does work locally against a VM with the same Image (we were unable to reproduce this locally
- Also accessing the app in the chrome web browser as a real user works as before (it shows the invalid certificate message as before for all self signed certs, but this was always ignored with "--ignore-certificate-errors"
- Even accessing it our "regular" way via an Electron shell with chromium 124 inside works without any certificate issues.
- Only the Pipelines using later than PW 1.40.1 seem to cause this errors...but executing the exact same commands against the same VM locally work...which is odd.

As we currently dont know if we are allowed to make any changes to that certificate-creation process we are really trying to just make PW work again in the pipelines as it does locally.
It would be really awesome if someone could maybe make some suggestions or provide any help how to fix this :)

If you need any further infos I try my best to provide them (without violating some privacy-conditions ofc)

Thanks a lot in advance! :)

### Expected behavior

I expect to be able to call my Server on the pipeline without any SSL-Errors or at least ignore them completely.

### Actual behavior

Calling every page.goto(...) on the AzureDevOps Pipeline causes:

<img width="688" alt="image" src="https://github.com/microsoft/playwright/assets/36530889/86edab5b-cc70-48b4-8f86-05a6dbfbbd9a">

### Environment

```shell
Local:

  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
    Memory: 14.72 GB / 31.23 GB
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.89.1 - C:\Users\stefan.wagner\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: 1.44.1 => 1.44.1


Pipeline:
 System:
    OS: Windows 10 10.0.17763
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 3.46 GB / 8.00 GB
  Binaries:
    Node: 20.14.0 - F:\E2EAgent01\_work\_tool\node\20.14.0\x64\node.EXE
    Yarn: 1.22.22 - F:\E2EAgent01\_work\_tool\yarn\1.22.22\x64\yarn-v1.22.22\bin\yarn.CMD
    npm: 10.7.0 - F:\E2EAgent01\_work\_tool\node\20.14.0\x64\npm.CMD
  npmPackages:
    @playwright/test: 1.44.1 => 1.44.1
```

**Comment by mxschmitt** [comment] 2024-06-04 10:08
Since this looks like a Chromium regression, I recommend to file it against https://issues.chromium.org/.

In order to help them to have a minimal reproducible, I recommend the following doing first:

1. Try to reproduce it via `chrome.exe --headless --ignore-certificate-errors --screenshot=foo.png https://example.com`

Good should be v1.40.1: https://playwright.azureedge.net/builds/chromium/1091/chromium-win64.zip
Bad should be v1.41.0: https://playwright.azureedge.net/builds/chromium/1097/chromium-win64.zip

Try both locally and on your Azure Pipelines server. This also makes sure, that you can still reproduce it and its not some configuration change on Azure Pipelines etc.

This should ideally reduce the scope already.

> It does work locally against a VM with the same Image (we were unable to reproduce this locally

This makes me think the network might be different, maybe a proxy or so is in place?

**Comment by SteveW94** [comment] 2024-06-04 11:25
> Since this looks like a Chromium regression, I recommend to file it against https://issues.chromium.org/.
> 
> In order to help them to have a minimal reproducible, I recommend the following doing first:
> 
> 1. Try to reproduce it via `chrome.exe --headless --ignore-certificate-errors --screenshot=foo.png https://example.com`
> 
> Good should be v1.40.1: https://playwright.azureedge.net/builds/chromium/1091/chromium-win64.zip Bad should be v1.41.0: https://playwright.azureedge.net/builds/chromium/1097/chromium-win64.zip
> 
> Try both locally and on your Azure Pipelines server. This also makes sure, that you can still reproduce it and its not some configuration change on Azure Pipelines etc.
> 
> This should ideally reduce the scope already.
> 
> > It does work locally against a VM with the same Image (we were unable to reproduce this locally
> 
> This makes me think the network might be different, maybe a proxy or so is in place? Since you mentioned that the image seems to be the same.

Thanks a lot for the suggestions so far :)

I am also now pretty sure that it has to be a Chrom(ium) thing, as it also affects our integration tests (which run via karma and just use the PW chromium instance).

As it perfectly works fine (just tested) in the local environment I am really tending to some weird network issue on azure side.
I currently have my difficulties to set up the whole verifying thing on azure, as each run takes quite some time.

But in the meantime I will try to connect to one of our runner-agents and look if they can reach our app servers in desktop environment with the new chrome and generelly find out if there is any proxy or sth in place there.

Sadly I dont entirely get what @mxschmitt said. Does that mean I need to Update the Windows of the serving VMs to support this cipher? Or where is the next theoretical actionpoint?

Just FYI, our setup is: We have some generic runner Agents from AzureDevops which run PlayWright tests against some custom setup VMs which live in the same network (IP visible above). How they are hooked up into the Azure Environment, I dont know so far

**Comment by mxschmitt** [comment] 2024-06-04 16:31
> Sadly I dont entirely get what you said in the second reply. Does that mean I need to Update the Windows of the serving VMs to support this cipher? Or where is the next theoretical actionpoint?

The problem is most likely the certificate which is used to serve the website - a certificate contains ciphers which _seem_ to be the problem. I recommend looking into that to see if you are following the best practises and comparing it with certificates from big websites e.g. https://github.com.

This issue seems not actionable from our side. Feel free to post status updates here - so future users who run into it could benefit from it. I'll close it in the meantime.

**Closed by mxschmitt** 2024-06-04 16:31 UTC

**Comment by SteveW94** [comment] 2024-06-04 16:38
Yes this seems reasonable 👍 
As the certificate works in the local network in newer chromes, it has to be sth. about how the Azure machines are connected.

We now have 4 options to look into I guess:
- Fix the way the way our azure network works
- Force chrome somehow to just give a damn about this error and ignore it as it does with the wrong authority error before
- Try to reverse engineer the EXE Program which currently creates our Certificate during the automated server setup and try to create a "better" certificate
- Throw away this self signed certificate completely

I will post updates here, as soon as there are any

**Comment by SteveW94** [comment] 2024-06-05 12:27
We finally discovered what was causing the issue today! 🥳 
In the base Image we provided back in the day there was still a testing certificate included which was rather generic and was in the list of IISs certificates rather high as it seems, and so picked all the time, even though a newly generated, more specific, fine certificate was  created by our setup process!...What also explains, why it works fine on our local systems/production.

We now will adjust the base image and I think it will work then...hopefully^^
