### ISSUE TITLE
[BUG] PW for VS Code - Running as debug doesn't update status indication

### ISSUE THREAD

**Issue by RThuys** [microsoft/playwright#19960] opened 2023-01-09 14:52 UTC
- Playwright Version: 1.28.1
- Operating System: WINDOWS 10 10.0.19045
- Node.js version: v14.17.3
- VS Code version: 1.74.0
- Extra: Playwright Test for VS Code version v1.0.3

After running a successful test through clicking on the 'play' button, the indicator becomes green.
When I change the test to a failing state, run it through 'play', the indicator becomes red. 
However, if I do the exact same with 'debug' the state does not update

This issue does not occur on my mac, also with PW v 1.28.1 and PW Test VS code 1.0.3

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/20083678/211334479-cbb88940-0554-45c3-8887-6bfd2073217e.png">

**Comment by aslushnikov** [comment] 2023-01-10 04:52
> This issue does not occur on my mac, also with PW v 1.28.1 and PW Test VS code 1.0.3

@RThuys So do I read correctly that this issue occurs only with old Playwright version and on Windows?

**Comment by RThuys** [comment] 2023-01-10 06:39
@aslushnikov, indeed, updating to 1.29.2 gives me more errors so I haven't tested it on the latest version

**Comment by debs-obrien** [comment] 2023-01-10 17:53
Hi @RThuys can you check if you have a breakpoint set on the line where the test is, line 3 in your example. Sometimes the breakpoint can get stuck there and you don't see it cause the green check is on top of it which can cause some issues such as a red checkmark.

**Comment by RThuys** [comment] 2023-01-11 09:48
@debs-obrien, thx for the suggestion, unfortunately this is not the case. As seen in the image, there is the possibility to add a breakpoint. I've also created the scenario where the breakpoint is under the check to see what it would look like.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/20083678/211772846-6c436f94-87b1-49e1-bb8c-e7bc54c7525a.png">

**Comment by aslushnikov** [comment] 2023-01-11 18:12
@RThuys could you please record a video to demonstrate the issue?

**Comment by RThuys** [comment] 2023-01-12 07:01
(Scenario: expect to pass)
1: Blank run, debug -> result the check doesn't indicate that the test has run
2: Run as normal -> the check is now green as the the test is true

(Scenario change: expect to fail)
3: Run as debug -> the check stays green and no feedback is provided inline
4: Run as normal -> The check goes red, feedback is provided 


https://user-images.githubusercontent.com/20083678/211998961-6b269442-7dc6-4fea-b9f3-34fdcb362197.mov

**Comment by aslushnikov** [comment] 2023-01-13 22:41
@mxschmitt could you please try reproducing this on Windows?

**Comment by mxschmitt** [comment] 2023-02-09 17:03
Looks like its fixed in VSCode 1.75.0. Please re-file if you still experience this issue.

**Closed by mxschmitt** 2023-02-09 17:03 UTC
Labels: feature-vscode-extension, v1.31
