### ISSUE TITLE
[Question] Why chromium and webkit open two windows?

### ISSUE THREAD

**Issue by Niyarlatotep** [microsoft/playwright#1059] opened 2020-02-19 06:28 UTC
Why when I run a sample test on chromium or webkit playwright opens two browser windows? At the same time firefox opens one window but two tabs. Is it possible to have only one window? 

```
const playwright = require('playwright');

(async () => {
    const browser = await playwright.webkit.launch({headless: false});
    const page = await browser.newPage();
    await page.goto('http://whatsmyuseragent.org/');
    await browser.close();
})();
```

**Comment by pavelfeldman** [comment] 2020-02-19 16:43
We are working on eliminating the default context that the original window/tab belong to.

**Comment by pavelfeldman** [comment] 2020-02-20 13:08
Closing this as a duplicate of https://github.com/microsoft/playwright/issues/981

**Closed by pavelfeldman** 2020-02-20 13:08 UTC
