### ISSUE TITLE
[BUG] [uiMode] Test is executed but browser is blank

### ISSUE THREAD

**Issue by hardeepCDX** [microsoft/playwright#22078] opened 2023-03-29 21:25 UTC
### System info
- Playwright Version: [v1.32.1]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

When I run the test case using the uiMode
Then The test is executed and passed but I can not see anything in the uiMode browser.

Screenshot
![image](https://user-images.githubusercontent.com/117135138/228670834-17efe7be-01d3-4e2f-82c0-a1aea28bbd3e.png)

**Comment by Nav-2d** [comment] 2023-03-29 21:31
Looking at the above screenshot, you need to click the test name to view the traces. Seems like you are clicking the file name

**Comment by hardeepCDX** [comment] 2023-03-29 21:40
Same issue, even I click on the test name.

**Comment by pavelfeldman** [comment] 2023-03-29 21:51
We can't reproduce your screenshot! Please follow the issue template to provide enough info for us to reproduce!

**Comment by hardeepCDX** [comment] 2023-03-29 22:05
I am experiencing a problem where the test suite is causing an issue, despite the test case appearing to be working fine.
![image](https://user-images.githubusercontent.com/117135138/228678169-55b0625f-d2e5-4f42-b5e9-c049a2c74951.png)

**Comment by denkorz** [comment] 2023-03-30 11:02
The same happens in my case. During the test everything is fine, but then trace and so on disappears and test fails on this line
```typescript
await Promise.all([onePage.close(), anotherPage.close()]);
```
with this error `Error: file data stream has unexpected number of bytes`

**Comment by denkorz** [comment] 2023-03-30 11:09
@pavelfeldman this might help you to reproduce the issue

**Comment by datguychen** [comment] 2023-03-30 11:39
You have to click the eye icon next to the test file name

**Comment by pavelfeldman** [comment] 2023-03-31 22:54
@denkorz you gave me a hint that you have two pages. Are these pages from the same context or different contexts?
@datguychen I can't click that eye icon on the screenshot above, I need a real repo with a repro...

**Comment by denkorz** [comment] 2023-03-31 23:00
@pavelfeldman the context are different

**Comment by pavelfeldman** [comment] 2023-04-04 20:41
Could you update to 1.32.2 and see if the problem persists?

**Comment by pavelfeldman** [comment] 2023-04-07 22:33
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Closed by pavelfeldman** 2023-04-07 22:33 UTC
Labels: triaging
