### ISSUE TITLE
[Bug]: Crashed playwright has open handles

### ISSUE THREAD

**Issue by ayroblu** [microsoft/playwright#31138] opened 2024-06-04 02:12 UTC
### Version

1.31.2

### Steps to reproduce

Our setup is we have a storybook and we just open the storybook and take a screenshot with playwright, and we do about 10 of these in parallel. Pretty simple, but I can't share any kind of reproduction. While running these tests, (about 360, doing 10 in parallel), we encounter very reliably:

```
==================== Browser output: ====================
<launching> chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-Js4X5W --remote-debugging-pipe --no-startup-window
<launched> pid=491769
[pid=491769][err] [0603/182712.098562:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[pid=491769][err] [0603/182712.138990:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
[pid=491769][err] [0603/182949.910339:ERROR:http_connection.cc(37)] Too large read data is pending: capacity=104857600, max_buffer_size=104857600, read=104857600
[pid=491769][err] [0603/182949.910383:ERROR:devtools_pipe_handler.cc(284)] Connection closed, not enough capacity
```

Reducing the number of tests that we do also seems to stop this from happening, but for this combination of tests, it is what it is.

But this is fine, I just add a catch and retry for the failures.

However, after my function has finished running, it stays open cause there's an open handle. And my test box eventually times out after 1 hour (normally takes less than 10 minutes)

### Expected behavior

When playwright / chrome crashes, it should cleanup the resource

### Actual behavior

Node process stays open, due to open handle

### Environment

```shell
I can't run this command, but centOS 7 and node 16 I believe (I know deprecated, but I don't think that's the issue here)
```

**Comment by mxschmitt** [comment] 2024-06-04 07:42
We unfortunately need a reproduction in order to look into issues like this. You are also using a very old Playwright version on an unsupported operating system. Please make sure to only run on supported ones, with Node.js LTS (20) and retry with latest Playwright. I'll close in the meantime until we have a repro which we can run locally, so we can act on it, thanks for your understanding!

**Comment by ayroblu** [comment] 2024-06-04 09:07
Repro https://github.com/ayroblu/playwright-repro-31138

<img width="753" alt="image" src="https://github.com/microsoft/playwright/assets/4915682/4da2629f-3882-458e-a6fa-174870ba510d">

See the fact I have to press <kbd>Ctrl</kbd> + <kbd>c</kbd> at the bottom, it should close all references, but it's leaking references when it crashes

**Comment by mxschmitt** [comment] 2024-06-04 09:14
This looks expected, you are closing the context while there is still a route handler active. When closing the page, this one will throw that the page has been closed. To fix this, you can call:

    await browserContext.unrouteAll({ behavior: 'ignoreErrors' });

before you close the context.

**Comment by mxschmitt** [comment] 2024-06-04 09:53
Investigation: I had to make a few adjustments to make it behave different:

- doing `context.unrouteAll` will prevent unhandled promise rejections aka seeing `fetch:  Target page, context or browser has been closed``
- so I also had to remove the console.error in your try/catch handler
- This then will only end up in a page.goto timeout, Chromium doesn't like to to fulfil a 162MB request as of today and closes the page instead.

How does such a large video relate to storybook tests? I'd recommend to skip large videos for now. 

```diff
diff --git a/cache.ts b/cache.ts
index 413a510..cdcaeb8 100644
--- a/cache.ts
+++ b/cache.ts
@@ -1,9 +1,7 @@
-import type { APIResponse, BrowserContext } from "playwright";
-
-const routeCache = new Map<string, APIResponse>();
+const routeCache = new Map();
 
 /** This function is just to overload the devtools <-> chrome inter connect, the caching itself is not important */
-export async function cacheAllRoutes(context: BrowserContext) {
+export async function cacheAllRoutes(context) {
   await context.route(/.*/, async (route, request) => {
     const url = request.url();
     console.log("url", url);
@@ -16,13 +14,12 @@ export async function cacheAllRoutes(context: BrowserContext) {
       }
     } else {
       try {
-        const response = await route.fetch({ url });
+        const response = await route.fetch();
         if (response.ok()) {
           routeCache.set(url, response);
         }
         await route.fulfill({ response });
       } catch (err) {
-        console.error("!! failed to fetch", err);
         await route.continue().catch(() => {});
       }
     }
diff --git a/index.ts b/index.ts
index 6ddd772..7210f23 100644
--- a/index.ts
+++ b/index.ts
@@ -1,13 +1,13 @@
 import { chromium } from "playwright";
-import { cacheAllRoutes } from "./cache.ts";
+import { cacheAllRoutes } from "./cache.mjs";
 
 const url =
   "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4";
 const browser = await chromium.launch();
+const context = await browser.newContext({
+  viewport: { width: 800, height: 600 },
+});
 try {
-  const context = await browser.newContext({
-    viewport: { width: 800, height: 600 },
-  });
   await cacheAllRoutes(context);
   console.log("started browser");
   await Promise.all(
@@ -22,6 +22,7 @@ try {
         );
       }),
   );
+  await context.unrouteAll({behavior: 'ignoreErrors'})
   await context.close();
 } catch (err) {
   console.error("Error", err);line at end of file

```

**Comment by ayroblu** [comment] 2024-06-05 08:08
> How does such a large video relate to storybook tests? I'd recommend to skip large videos for now.
This was just context. It took me a month to realise this was an issue with the route cache + videos. Anyone in our team can make a test that has video in it, so it's not that easy to catch

**Comment by ayroblu** [comment] 2024-06-05 08:09
> How does such a large video relate to storybook tests? I'd recommend to skip large videos for now.

This was just context. It took me a month to realise this was an issue with the route cache + videos. Anyone in our team can make a test that has video in it, so it's not that easy to catch.

But this is not the point, the point is after it's crashed, it retains the open handle. But it should release it, it has crashed.

**Comment by mxschmitt** [comment] 2024-06-05 12:50
Could you help us what you mean with handles? Are you referring to this line in the logs?

    [pid=491769][err] [0603/182949.910383:ERROR:devtools_pipe_handler.cc(284)] Connection closed, not enough capacity

So far its not intended to fulfil such large requests, I'd mark it as a feature request for now to see how much demand is for that.

**Comment by ayroblu** [comment] 2024-06-05 16:17
Most server side JS engine's implementation of the event loop uses libuv's handles where if a handle is active, it doesn't stop the process. Imagine you create a node webserver listening on port 3000, it doesn't immediately close until you close your server. This is commonly accessed via the `process._getActiveHandles()` command though there are libraries that make this much easier.

This means that in the event of a crash you have a memory leak, because the resources / memory is not being free'd up

**Comment by mxschmitt** [comment] 2024-06-05 16:49
Yes, could you give us a reproduction which uses getActiveHandles and prints that its growing?

**Comment by mxschmitt** [comment] 2024-06-05 17:43
I see, thank you for clarifying it. When the browser closes the connection via `  pw:browser [pid=57332][err] [57332:75779:0605/194011.032383:ERROR:http_connection.cc(37)] Too large read data is pending: capacity=104857600, max_buffer_size=104857600, read=104857600` there is no way of gracefully closing the browser anymore, since we can't tell the browser 'hey please close', so we wait 30s to let him close itself - what the browser is not able to and then close it.

So for me when I run the script browser.close() takes 30s which is expected here. I saw you are using Bun, which might behave different.

**Comment by mxschmitt** [comment] 2024-06-10 18:02
Closing as intended since waiting for 30s is intentional here.

**Closed by mxschmitt** 2024-06-10 18:02 UTC
