### ISSUE TITLE
[BUG]  network calls are cached and test fails with page.waitForResponse()

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#26613] opened 2023-08-22 17:46 UTC
### System info
- Playwright Version: ^1.36.2
- Operating System: Mac
- Browser: All
- Other info:

### Source code

<img width="1135" alt="Screen Shot 2023-08-22 at 12 51 56 PM" src="https://github.com/microsoft/playwright/assets/113629123/bff5b25b-5e96-4c5b-a9e8-408042d15045">

This is the dropdown, they have options 1, 2, 3 and 4, 5 etc, when i select value 1 from the dropdown, sometimes it is not set properly as the selected value and it is reset to 5 (which is the default value), in the round dropdown, looks like playwright is selecting the value from the dropdown even before the page is fully loaded before all needed network calls are finished in order to properly set the values in the dropdown...

and if i add await page.waitForTimeout(1000) it works fine, but i don't want to use static wait, and also confirmed with developers that it is not related to hydration as our application is REACT single paged application. Please confirm if hydration is still possible for single paged application?

secondly, i added wait for the response call to finish, as i select the option from the dropdown, network call is made and data are retrieved from backend calls. hence i added page.waitForResponse, after i select the option from the dropdown before performing assertion,
But the problem is i have to end up selecting the same option from the dropdown several times, looks like network responses are cached, and no new network call is made when i select the same value from the dropdown.

Can you please advise how to disable caching so network call will be made everytime i select option from the dropdown? or is this the ideal way to disable caching, does it cause any performance issues?

Meanwhile i found page,route() , i tried to use page.route() instead of page.waitForResponse() , can you please advise if page.route() disable caching in the browser, so network calls will be made everytime i select option in the dropdown?
https://playwright.dev/docs/api/class-page#page-route
NOTE
Enabling routing disables http cache.

```javascript
//option 1
 await Promise.all([
                    page.waitForResponse(resp => resp.url().includes('/reports/awards-alpha?base=DAL&round='+data.roundNo) && resp.status() === 200),
                    page.waitForResponse(resp => resp.url().includes('/reports/banner/base/DAL/round/'+data.roundNo) && resp.status() === 200),
                    page.locator('.react-select__option').filter({hasText: data.roundNo}).click()
                ]);


//option 2
                await page.locator('.react-select__option').filter({hasText: data.roundNo}).click();
                await page.route('/reports/awards-alpha?base=DAL&round='+data.roundNo, route => {
                  route.continue();
                });
                console.log("awards-alpha")
                await page.route('/reports/banner/base/DAL/round/'+data.roundNo, route => {
                    route.continue();
                });
                console.log("reports/banner/base")

```

**Comment by yury-s** [comment] 2023-08-22 19:29
> looks like playwright is selecting the value from the dropdown even before the page is fully loaded before all needed network calls are finished in order to properly set the values in the dropdown...

This is a bug in the page code caused by a [hydration](https://playwright.dev/docs/navigations#hydration) issue. Playwright behaves as a very fast user, but the same can happen with a human on e.g. a slow network connection.

> But the problem is i have to end up selecting the same option from the dropdown several times, looks like network responses are cached, and no new network call is made when i select the same value from the dropdown.

Sounds like browser's memory cache kicks in. This is the same behavior which the user would face. Disabling cache would change browser behavior, there is no direct way to disable it.

> Meanwhile i found page,route() , i tried to use page.route() instead of page.waitForResponse() , can you please advise if page.route() disable caching in the browser, so network calls will be made everytime i select option in the dropdown?

Yes, as the [documentation says](https://playwright.dev/docs/api/class-page#page-route): "Enabling routing disables http cache.". You can use that as a workaround.

**Comment by InduKrish** [comment] 2023-08-22 19:49
Can you please confirm if hydration is still possible in Single paged application? when i discussed with developers in the team, i was told that it is a single paged application hence hydration is not possible, and advised me to wait for network calls to finish every time i select the value form the dropdown , hence i decided to use page.waitForResponse or page.route(), Can you please advise?


Also, is there any other options to wait for network response other than page.waitForResponse and page.route()?

**Comment by yury-s** [comment] 2023-08-22 21:15
> Can you please confirm if hydration is still possible in Single paged application? when i discussed with developers in the team, i was told that it is a single paged application hence hydration is not possible, and advised me to wait for network calls to finish every time i select the value form the dropdown , hence i decided to use page.waitForResponse or page.route(), Can you please advise?

Hydration is possible in single-page applications. It's a concept that involves taking a server-rendered (or statically rendered) page and making it fully interactive by adding client-side JavaScript logic. Also, if the application removes event listeners when you perform an action and only adds them back later (e.g. after a network response is received), selecting a new value in the dropdown will have no effect until the listener is added back. Like I said, end user could face the same issue, so this is usually a bug in the application. A better approach could be to make the UI element non-interactive until the page is ready again and leverage Playwright's [auto-wait](https://playwright.dev/docs/actionability) functionality.

> Also, is there any other options to wait for network response other than page.waitForResponse and page.route()?

page.waitForRequest()/waitForResponse() and page.route() are the right methods for observing/intercepting network calls made by the page.

**Comment by yury-s** [comment] 2023-08-28 15:59
Closing per the response above, feel free to open a new issue if it doesn't work.

**Closed by yury-s** 2023-08-28 15:59 UTC
Labels: triaging
