### ISSUE TITLE
[BUG] TimeoutError: electronApplication.firstWindow: Timeout 30000ms exceeded while waiting for event "window"

### ISSUE THREAD

**Issue by abhijan1234** [microsoft/playwright#27628] opened 2023-10-16 11:06 UTC
### System info
- Playwright Version: 1.31.1
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info: Node V18.18.0

Error: Getting timeout error when playwright is trying to open the electron application window. 

 TimeoutError: electronApplication.firstWindow: Timeout 30000ms exceeded while waiting for event "window"

       at Utils.tsx:52

      50 |       console.log(`Coming herweeeee ${electronApp}`);
      51 |     // CleanUp local storage before running ITSYN.
    > 52 |     (await electronApp.firstWindow()).evaluate(() => {
         |                        ^
      53 |       localStorage.clear();
      54 |     });

**Comment by mxschmitt** [comment] 2023-10-16 13:29
Closing since this issue is not following the bug template. We need a reproducible in order to look into such bugs. Thanks for your understanding. Please re-file, thanks!

**Closed by mxschmitt** 2023-10-16 13:29 UTC
