### ISSUE TITLE
[Question] Application page is not loading in Playwright

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#14842] opened 2022-06-13 21:06 UTC
I have a scenario when I search for the customer name in my application, for some reason playwright is not loading the page. It works fine on the local browser when I test it.

After debugging, I figured some of the header requests were missing(including `Cookie`) so I added it by using `page.setExtraHTTPHeaders` right after the `openURL`. I do see all the header requests now but page is still not loading. 

I tried postman to see if API is returning all the data but at first, it was not showing me any data until I turned off `SSL request validation` in postman. Then it worked fine. 

My question is if there is something in Playwright that might be blocking API request to load the page? Like in postman I had to turn off the `SSL request validation` for the request. Can someone please help? I also see `Referrer Policy: unsafe-url` in chromium when I run tests.

**Comment by gauravgandhi1315** [comment] 2022-06-13 21:40
I just tried in chromium locally with both normal and incognito mode, works fine. I think Playwright is blocking something fore sure. I don't know if the above information is enough but if someone can help that would be great! thanks in advance

**Comment by gauravgandhi1315** [comment] 2022-06-13 21:41
@pavelfeldman Would you be able me here?

**Comment by gauravgandhi1315** [comment] 2022-06-14 13:58
I just tested on Firefox and it works fine. Only chrome and chromium not working for some reason

**Comment by dgozman** [comment] 2022-06-14 14:30
@gauravgandhi1315 Perhaps you need [`ignoreHTTPSErrors`](https://playwright.dev/docs/api/class-testoptions#test-options-ignore-https-errors)?

```ts
// playwright.config.ts

const config = {
  // ... other options
  use: {
    ignoreHTTPSErrors: true,
  },
};
```

If this does not help, could you please provide a repro that developer can run locally to reproduce the issue?

**Comment by gauravgandhi1315** [comment] 2022-06-14 14:36
@dgozman Unfortunately, this is not working. My application is not public so I won't be able to provide the repo. How come firefox is working fine? May be some cache issue or something?

**Comment by dgozman** [comment] 2022-06-14 14:40
@gauravgandhi1315 Since I don't see the error message or any screenshots, nor I have a repro to run locally, I am not able to help. Browsers are different, something may work in Firefox and not work in Chromium. That's why cross-browser testing is useful 😄 

As a last resort, try [recording a trace](https://playwright.dev/docs/trace-viewer) and sharing it with us. Maybe we can spot an issue from the trace.

**Comment by dgozman** [comment] 2022-06-14 16:36
@gauravgandhi1315 The `trace.zip` file.

**Comment by gauravgandhi1315** [comment] 2022-06-14 16:41
@dgozman My application is private and I am not sure if it is safe to send it here. Any suggestions?

**Comment by dgozman** [comment] 2022-06-14 16:48
@gauravgandhi1315 You can email to me at dgozman [at] microsoft [dot] com.

**Comment by gauravgandhi1315** [comment] 2022-06-14 16:57
@dgozman I see that `Cookie` is not being loaded in the `header request` on chrome/chromium for some reason and that is needed to load the page. When I run tests on Firefox, I do see the cookie in the `header request` and hence works fine on firefox.

i tried to use `page.setExtraHTTPHeaders` in my test file but didn't work. Is there something that is blocking the cookie on chrome/chromium?

**Comment by dgozman** [comment] 2022-06-14 17:07
@gauravgandhi1315 I am not aware of anything Playwright-specific that would block cookies. However, browsers are different, so they can treat cookies differently.

**Comment by gauravgandhi1315** [comment] 2022-06-14 17:08
@dgozman Is there any other way to set the cookie?

**Comment by dgozman** [comment] 2022-06-14 17:10
You can use [`browserContext.addCookies()`](https://playwright.dev/docs/api/class-browsercontext#browser-context-add-cookies).

**Comment by gauravgandhi1315** [comment] 2022-06-14 19:37
@dgozman Im using this to set the cookie:
```
await context.addCookies([
    { name: 'cookie1', value: 'value1', url: 'https://example.com', },
    { name: 'cookie2', value: 'value2', url: 'https://example.com', },
  ]);


But sometimes is works and other times it doesn't. When it works, I see the cookie was being setting up correctly. Other times, I don't see cookie and it fails. What should be the url here? Application url?

**Comment by gauravgandhi1315** [comment] 2022-06-14 19:43
I am setting it up in `global-setup`

**Comment by gauravgandhi1315** [comment] 2022-06-14 19:54
```
this is my state.json

"cookies": [
    {
      "sameSite": "Lax",
      "name": "Cookie",
      "value": "bluetoken=......",
      "domain": "example",
      "path": "example",
      "expires": -1,
      "httpOnly": false,
      "secure": true
    },

**Comment by dgozman** [comment] 2022-06-15 20:04
> I am setting it up in `global-setup`

What are you doing after that? Note that cookies are not automatically transferred from the global setup to the test, unless you save and restore `storageState`. Try setting cookies in the test directly to see whether that helps. If it does, we may figure out a solution for you.

```ts
test('my test', async ({ page }) => {
  await page.context().addCookies([...]);
  // ...continue with the test...
});
```

**Closed** 2022-06-21 09:41 UTC
Labels: triaging

**Comment by sumitsg004** [comment] 2022-07-21 10:45
@gauravgandhi1315 is your issue resolved? 

I am facing similar issue. I search for customer and click submit.
Manual - It navigates to next page.
Playwright Automation - does not navigate further.

If your issue is fixed, please let me know how you were able to achieve it. It would be great help. thanks in advance.

**Comment by Faizan-Mamji** [comment] 2023-01-09 07:58
I am facing similar issue.
Can you please help me to resolve this issue?

**Comment by josearilson** [comment] 2025-02-07 23:26
> @sumitsg004 @Faizan-Mamji In my case, page was not loading because I had to set the cookies before opening the application URL. This fixed this issue for me:
> 
> ` await context.addCookies(pass cookie here);`

Tem o projeto no Github para compartilhar, estou com o mesmo problema, mas não consegui usar o comando que para vc resolveu.
