### ISSUE TITLE
[BUG] page.fill() Protocol error in Firefox

### ISSUE THREAD

**Issue by nikolay-yankov** [microsoft/playwright#8374] opened 2021-08-23 18:10 UTC
**Context:**
- Playwright Version: [1.10.0]
- Operating System: [Windows]
- Node.js version: [14.15.4]
- Browser: [Firefox]

**Code Snippet**

```javascript
const { firefox } = require("playwright-firefox");

const browser = await firefox.launch({
      headless: false,
      firefoxUserPrefs: {
        "layers.acceleration.disabled": true,
        "media.navigator.streams.fake": true,
        "dom.webnotifications.enabled": false,
      },
    });

const context = await browser.newContext({})
const page = await context.newPage();
await page.goto("mywebsite.com");
await page.fill("selector", "Some Input");
```

**Describe the bug**

Occasionally Playwright throws an error when trying to execute `page.fill("selector", "Some Input");`
Unfortunately I cannot reproduce it. It just happens randomly. This is what the error looks like:
```javascript
Error: page.fill: Protocol error (Page.adoptNode): error in channel "content::page": exception while running method "adoptNode" in namespace "page": Cannot find object with id = id-20 unsafeObject@chrome://juggler/content/content/PageAgent.js:101:11
_adoptNode@chrome://juggler/content/content/PageAgent.js:529:53
_onMessage@chrome://juggler/content/SimpleChannel.js:165:37
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
 _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
``` 
And on another occasion I got such a similar error:

```javascript
Error: page.fill: Protocol error (Page.insertText): error in channel "content::page": exception while 
running method "insertText" in namespace "page": Component returned failure code: 
0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsITextInputProcessor.commitCompositionWith] _insertText@chrome://juggler/content/content/PageAgent.js:880:32
```

**Comment by JoelEinbinder** [comment] 2021-08-24 04:08
Given your other bug report, it sounds like your page is navigating under your feet. However we still shouldn't throw a protocol error, so this seems like a bug.

**Comment by aslushnikov** [comment] 2021-08-24 13:53
This seems to be a dupe of #5460

I tried multiple times, and yet wasn't able to repro that bug.. If there's a script that can help us reproduce that bug - please send it to us!

**Closed by aslushnikov** 2021-08-24 13:53 UTC
Labels: P2-bug
