### ISSUE TITLE
[Feature] Can we add the ability to mock websocket messages?

### ISSUE THREAD

**Issue by btvanhooser** [microsoft/playwright#6781] opened 2021-05-27 23:03 UTC
We have the ability to sniff websockets and use events on messages bi directionally, which is great, but can we also modify those messages? Either change them if they are fired, or send them directly to the websocket? It seems like following the "Route.ContinueAsync" flow works well, but it'd be even better if we can create a request since we already have the "WebSocket" class within the event handler.

Note: also created on the C# implementation repo since that's what I'm using, but figured I'd put it here too since this appears to be the main repo. We can close whichever is more appropriate:
https://github.com/microsoft/playwright-sharp/issues/1450

**Comment by yury-s** [comment] 2021-05-27 23:10
Closing as duplicate of  #4488

**Comment by btvanhooser** [comment] 2021-05-27 23:11
sorry, just found that only minutes too late.

**Closed by yury-s** 2021-05-27 23:10 UTC
