### ISSUE TITLE
[Question] I am using global teardown to zip playwright report folder. But zip folder is always empty .

### ISSUE THREAD

**Issue by Rohanpandey268** [microsoft/playwright#20527] opened 2023-01-31 12:44 UTC
async function globalTeardown() {
    const reportPath = path.join(__dirname, `playwright-report`);
    const zip = new AdmZip();
    zip.addLocalFolder(reportPath);
    zip.writeZip('./html.zip');

}
export default globalTeardown;

 In config file its- globalTeardown: './global-teardown',

**Comment by dgozman** [comment] 2023-01-31 19:23
Closing as a duplicate of #18951.

**Closed by dgozman** 2023-01-31 19:23 UTC

**Comment by Rohanpandey268** [comment] 2023-01-31 20:09
As mentioned in #18951, this I am able to achieve earlier also in one of my CI steps. But my question remain as its is- even the Global tearDown step should also work when added in config.

**Comment by dgozman** [comment] 2023-01-31 20:54
Global teardown runs before the report is generated, this is by design.

**Comment by Rohanpandey268** [comment] 2023-02-01 06:52
Thanks alot, now this makes sense.
