### ISSUE TITLE
[BUG] Extension required when importing other files with type="module"

### ISSUE THREAD

**Issue by IanVS** [microsoft/playwright#13078] opened 2022-03-25 19:48 UTC
**Context:**

```md
## System:
 - OS: macOS 12.2.1
 - Memory: 802.27 MB / 32.00 GB
## Binaries:
 - Node: 16.13.1 - ~/.volta/tools/image/node/16.13.1/bin/node
 - Yarn: 1.22.17 - ~/.volta/bin/yarn
 - npm: 8.3.0 - ~/.volta/tools/image/npm/8.3.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
```

**Describe the bug**

I am using type="module" in my package.json, and running with `PW_EXPERIMENTAL_TS_ESM=1`.  I found that when I attempt to import another of my files from my global setup file, I need to specify the full filename with extension, which I think is a node esm requirement, but then typescript complains with `An import path cannot end with a '.ts' extension. Consider importing './generateTOTP' instead.`.  If I don't include the extension, playwright will not start and I get an error of:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/xxx/e2e/config/generateTOTP' imported from /xxx/e2e/config/global-setup.ts
```

**Comment by dgozman** [comment] 2022-03-26 01:37
@IanVS Are you using typescript for your config file, e.g. `playwright.config.ts`? Could you please share a full repro that we can run locally?

**Comment by IanVS** [comment] 2022-03-26 21:17
Sure, I'll put one together soon, thanks.

**Comment by frederikhors** [comment] 2022-03-27 14:56
On Windows too with 1.20.1. With 1.20.0 it works.

**Comment by IanVS** [comment] 2022-03-28 15:16
Here's a reproduction, @dgozman.  https://github.com/IanVS/playwright-issue-13078

**Comment by pavelfeldman** [comment] 2022-03-28 16:59
I can repro on 1.20, but I can't repro on 1.19. So it is a regression. Starting with 1.20 we require file extensions when importing Typescript files.

**Comment by dgozman** [comment] 2022-03-29 19:11
We discussed this issue and arrived to the following conclusion. We follow [TypeScript's experimental support for ESM](https://www.typescriptlang.org/docs/handbook/esm-node.html) in the test runner. TypeScript insists on using the extension of the output file for imports:
 ```ts
 // example.spec.ts
 import { foo } from './bar.js';
 ```
PR #13137 made sure that this syntax works. It is also supported by VSCode, so you should not get any errors when compiling or using an IDE.

We also allow using `import { foo } from './bar.ts'` because you are not usually compiling the tests and never actually see the `bar.js` file.

The fact that `import { foo } from './bar'` worked previously in ESM mode was a misleading bug. Sorry!

Note that everything above **only** applies to experimental TypeScript + ESM mode. When not using ESM, the old syntax `import { foo } from './bar'` continues to work.

---

Given the above, marking this issue as fixed. #13137 will be merged to v1.20.2. Meanwhile, you can try it out by installing `@playwright/test@next`.

**Closed by dgozman** 2022-03-29 19:11 UTC
Labels: P1-resolve-asap, v1.20

**Comment by frederikhors** [comment] 2022-03-30 10:53
I'm having this issue using both `1.20.1` and `next`:

![image](https://user-images.githubusercontent.com/41120635/160815400-1ff794fd-a4d7-4e07-acc5-e49de13b9754.png)

Only a VSCode issue. The tests are working.

How can I fix?

**Comment by frederikhors** [comment] 2022-03-30 10:54
If I use `./constants` (without `.ts`) I get error in pw at runtime.

**Comment by frederikhors** [comment] 2022-03-30 10:57
`[ERR_MODULE_NOT_FOUND]` using `PW_EXPERIMENTAL_TS_ESM=1 playwright test`.

**Comment by IanVS** [comment] 2022-03-30 13:05
@frederikhors did you try using a `.js` extension?

**Comment by frederikhors** [comment] 2022-03-30 13:09
I wanna use TS! 😄

**Comment by frederikhors** [comment] 2022-03-30 13:09
I'm importing from .ts files used in the project.

**Comment by IanVS** [comment] 2022-03-30 13:32
Name the file with .ts, but try importing it with a .js extension.

**Comment by frederikhors** [comment] 2022-03-30 14:46
Wow! I tried. VSCode is OK now but PW obviously errors with:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\prj\tests\constants.js' imported from C:\prj\tests\test.spec.ts
```

I'm using `PW_EXPERIMENTAL_TS_ESM=1 playwright test` command.

**Comment by IanVS** [comment] 2022-03-30 14:51
Hmmm, according to https://github.com/microsoft/playwright/issues/13078#issuecomment-1082271101, that should work on the `next` release.

**Comment by frederikhors** [comment] 2022-03-30 14:56
I just tried with `"@playwright/test": "next"`: the same error: `Cannot find module 'C:\prj\tests\constants.js'`.

I'm using Windows 10, node v16.14.2, npm 8.5.5. 😢

**Comment by frederikhors** [comment] 2022-03-30 15:05
I'm using a new SvelteKit project (they are using playwright by default).

**Comment by frederikhors** [comment] 2022-03-30 15:09
Does your `package.json` contain "type": "module"?

**Comment by frederikhors** [comment] 2022-03-30 15:11
Can you please post your code so I can try with it?

**Comment by IanVS** [comment] 2022-03-30 15:12
https://github.com/IanVS/playwright-issue-13078

**Comment by frederikhors** [comment] 2022-03-30 15:27
Done: https://github.com/IanVS/playwright-issue-13078/pull/1.

`npm i && npm test`: it errors.

**Comment by frederikhors** [comment] 2022-03-30 15:44
It works! THANKS!

**Comment by ryanjduffy** [comment] 2022-07-28 23:19
:wave: Running into this error on `@playwright/test@1.19.2` and we're not able to upgrade beyond that right now. Any way to work around it in the interim?

**Comment by dgozman** [comment] 2022-07-28 23:57
See [this comment](https://github.com/microsoft/playwright/issues/13078#issuecomment-1082271101).

**Comment by colemars** [comment] 2024-03-02 16:09
> TypeScript insists on using the extension of the output file for imports:

Explain?

I get a TS error that tells me the opposite:

> An import path cannot end with a '.ts' extension. Consider importing '../../../util.js' instead.
