### ISSUE TITLE
[Feature] Make component testing possible for React, Vue etc.

### ISSUE THREAD

**Issue by nand1234** [microsoft/playwright#7148] opened 2021-06-15 18:50 UTC
guys, any plans to implement component testing for vue and react js applications.

--- 

### Edit: From the maintainers.

A beta just launched, which supports Vue, React, and Svelte, see here: https://playwright.dev/docs/test-components

**Comment by aslushnikov** [comment] 2021-06-15 19:31
@nand1234 good question! While we are here - could you please elaborate what exactly do you expect from a "component testing" in a perfect world?

**Comment by nand1234** [comment] 2021-06-15 19:42
Typically component tests are run using a Node.js testing framework like jest or mocha. Components we want to test are rendered in a virtualized browser called jsdom.

With component testing , you can achieve the same goal: test a component in isolation. Instead of having components render inside a terminal, renders components in a real browser. Since the components you are testing are visible in the browser, this makes it easier to test and debug when a test fails.

**Comment by mxschmitt** [comment] 2021-06-16 08:23
Would you like to do something like this?

(this is non-functional code, just an idea)

```js
import YourComponent from './YourComponent'

it("should show hello after clicking the button", async ({ page, renderReactComponent }) => {
  await renderReactComponent(<YourComponent foo={123} />)
  await page.click("button")
  await page.waitForSelector("text=hello")
})
```

**Comment by nand1234** [comment] 2021-06-16 09:44
@mxschmitt brother you got it exactly what i envisioned.

**Comment by davidNHK** [comment] 2021-07-12 09:46
Can I have some timeline on this feature?

Or where I can get ideas on how can contributing to remove the blocker?

**Comment by visortelle** [comment] 2021-07-12 13:47
As I see, initially there is should be a way to bundle modules and upload them to the browser page.

Two days ago I implemented a script for my personal project that uses webpack and `context.addInitScript(..)` under the hood to achieve it.

How it looks now:

TestButton.tsx

<img width="489" alt="Screen Shot 2021-07-12 at 4 28 56 PM" src="https://user-images.githubusercontent.com/9302460/125295798-43c64480-e32e-11eb-8b05-81c5dbd5abb9.png">

TestButton.spec.tsx

<img width="755" alt="Screen Shot 2021-07-12 at 4 30 39 PM" src="https://user-images.githubusercontent.com/9302460/125296000-80923b80-e32e-11eb-8951-1606c00a1b33.png">

Run tests

<img width="989" alt="Screen Shot 2021-07-12 at 4 32 30 PM" src="https://user-images.githubusercontent.com/9302460/125296655-2d6cb880-e32f-11eb-9a87-30497ebcee91.png">

Test results

<img width="968" alt="Screen Shot 2021-07-12 at 4 35 53 PM" src="https://user-images.githubusercontent.com/9302460/125296704-3c536b00-e32f-11eb-8497-5b6077284bf9.png">

Now it works well for my pet project.

If Playwright maintainers don't have any better vision how to implement it right now and such API looks normal for Playwright community, then I can fix few minor issues and make it a public library.

What do you think?

**Comment by visortelle** [comment] 2021-07-15 07:16
I updated README and published my lib for component testing to npmjs.

Here is how React component test looks now:

<img width="525" alt="Screen Shot 2021-07-15 at 10 11 38 AM" src="https://user-images.githubusercontent.com/9302460/125745060-53098086-09f9-406e-be77-1e8237a49667.png">

[https://github.com/visortelle/playwright-module-loader/blob/191ebf08fe8d10f50428b942e4514228ad07cd56/packages/test-react-ts/src/Button/Button.spec.ts](link)

**Comment by itpropro** [comment] 2021-09-15 16:31
Please consider implementing component testing capabilities into playwright. The natural competitor to playwright is Cypress and they are pushing into component testing, which is the argument I hear most often when people try to decide which one to use.

**Comment by davidNHK** [comment] 2021-09-25 17:29
Would it more easily to achieve that if i already transpile my project code to ESM module that able to directly running on browser ? 

Recently i migrated my project to snowpack + web-test-runner, it great for able to run test and see running result in actual browser.

and i realise the blocked issues here mostly related to transpiler config like Babel, TS ...etc. 

if i already transpiled then feel like i don't need care about that ?

**Comment by jgoux** [comment] 2022-01-11 21:25
Seems like it's not blocked anymore! https://github.com/microsoft/playwright/issues/7121#issuecomment-1009140849 🎊

**Comment by hklsiteimprove** [comment] 2022-01-27 13:49
Hi - this seems like an awesome addition to playwright - is there anything we can do to move it forward, as we would love to have the functionality for our test project.

**Comment by thernstig** [comment] 2022-02-04 11:16
Would the scope of testing Web Components (lit more specifically) be possible to do in the same way? Maybe this is already possible and I'm not thinking straight today.

**Comment by pavelfeldman** [comment] 2022-03-22 01:40
I looked into component testing with Playwright and filed a bug with the ideas / proposed approach. It is somewhat manual, yet powerful. Would be curious what you all think!

https://github.com/microsoft/playwright/issues/12799

**Comment by lorainegarutti** [comment] 2022-04-20 20:59
Hello maintainers!
Right now we're migrating from Jest runner for Playwright runner regarding e2e tests.
We also would like to migrate from Next.js runner for Playwright runner to run Happo tests (visual regression) - using [this integration](https://docs.happo.io/docs/playwright).
BUT we really want to have a way to mount component (as Cypress have) to stub data in order to build more stable tests.

My question is: do you have any idea what is missing for us to leverage this idea and make it happen?
We might offer some help if needed!

🥲 💚

**Comment by jhanink** [comment] 2022-05-13 21:45
✅ Playwright ❤️
✅ Component Testing ❤️
🚫 No support for Angular 💔 

Hey Microsoft - Please support Angular (from Google). Thanks!

**Comment by itpropro** [comment] 2022-06-17 09:10
Great to have component testing ready now for the major languages! This issue can be closed I think, thanks for listening 👍

**Comment by CosminGramada** [comment] 2022-07-11 08:54
@pavelfeldman 
Is adding Angular to the list of already supported frameworks for component testing  on the roadmap?

**Comment by paoramati** [comment] 2022-11-08 18:50
Is there any roadmap for supporting importing functions? I'm currently unsure how to use any lib functions, and end up duplicating mocks within tests.

**Comment by mrmckeb** [comment] 2022-11-10 03:54
It would be great to get a clear roadmap for this feature - as we'd like to use it more heavily, but know that it's still in early development.

In the meantime, following the `feature-components` label may help people understand what has been requested/etc.
https://github.com/microsoft/playwright/labels/feature-components

**Comment by yjaaidi** [comment] 2022-12-07 16:22
We (jscutlery), just released Angular support here: https://github.com/jscutlery/devkit/tree/main/packages/playwright-ct-angular
but you'll have to follow the [Versatile Angular Style](https://marmicode.io/blog/versatile-angular): standalone, `inject()`, inline templates & styles.

**Comment by sand4rt** [comment] 2023-01-06 16:32
@thernstig created a package for lit and web components. See: https://github.com/microsoft/playwright/issues/14241#issuecomment-1368124560

**Comment by sand4rt** [comment] 2023-04-22 09:40
@jhanink @CosminGramada also created a package for Angular component testing: https://github.com/sand4rt/playwright-ct-angular. It has an identical API to Playwright's API.

**Comment by GermanJablo** [comment] 2023-10-04 13:34
@nand1234 and @denis-domanskii have already mentioned the possibility of testing the component in a real browser.

I agree with them 100%, but I would like to add that it would also be great to be able to run them in a simulated browser like jsdom.

Since on occasions when so much confidence is not required, the tests could be executed much faster. Changing the execution of a test from a simulated browser to a real one and vice versa would be trivial if they shared the same API, and we wouldn't have to have `testing library` for some tests, and playwright for others.

I have opened an issue about this here: https://github.com/microsoft/playwright/issues/27424

**Comment by dmitriybo** [comment] 2024-02-20 22:57
It would be great if it were possible to select browsers for a specific test. For example, in cases where it is not necessary to test in all browsers defined in playwright-ct.config.ts.

**Comment by mxschmitt** [comment] 2024-12-03 22:41
There are no action items for this issue - hence I'm closing it.

**Closed by mxschmitt** 2024-12-03 22:41 UTC
Labels: P3-collecting-feedback, feature-test-runner, feature-components
