### ISSUE TITLE
[BUG] WebKit browser crash on Ubuntu when calling page.goto() twice on some pages

### ISSUE THREAD

**Issue by terryknowlton** [microsoft/playwright#21531] opened 2023-03-09 15:08 UTC
### System info
- Playwright Version: [v1.31.2, v1.30.0]
- Operating System: [Ubuntu 20.04, Ubuntu 22.04]
- Browser: [WebKit]
- Other info: Works as expected on macOS

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**
I have created [this repo ](https://github.com/terryknowlton/double-goto-webkit-crash-linux) with an example test that reproduces the bug. I have also provided the test snippet below.

```TypeScript
import { test } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://mail.google.com/');
  await page.goto('https://mail.google.com/');
  await page.goto('https://github.com');
  await page.goto('https://github.com');
  await page.goto('https://www.disneyplus.com/account');
  await page.goto('https://www.disneyplus.com/account');
  await page.goto('https://app.mabl.com');
  await page.goto('https://app.mabl.com');
});
```

**Steps**
- Run the test on Ubuntu 22.04 or 20.04

**Expected**
- Test passes on all three browsers (WebKit, Chromium, Firefox)

**Actual**

WebKit test fails with a browser crash on the second `await page.goto('https://app.mabl.com')` call but none of the other addresses.

**Comment by mxschmitt** [comment] 2023-03-09 15:29
I tried to reproduce it on Ubuntu 22 via Docker on M1 mac which ends up in linux-arm64 there it was working.

But if I run it on Ubuntu 20.04 linux-amd64 then it ends up in:

```

    page.goto: Navigation failed because page was closed!
    =========================== logs ===========================
    navigating to "https://github.com/", waiting until "load"
    ============================================================

      4 |   await page.goto('https://mail.google.com/');
      5 |   await page.goto('https://mail.google.com/');
    > 6 |   await page.goto('https://github.com');`
```

but I can also confirm that it crashes on mabl:

```
  1) [webkit] › example.spec.ts:3:5 › test ─────────────────────────────────────────────────────────

    page.goto: Navigation failed because page crashed!
    =========================== logs ===========================
    navigating to "https://app.mabl.com/", waiting until "load"
    ============================================================

       7 |   await page.goto('https://www.disneyplus.com/account');
       8 |   await page.goto('https://app.mabl.com');
    >  9 |   await page.goto('https://app.mabl.com');
         |              ^
      10 | });

        at /tmp/myproject/tests/example.spec.ts:9:14
```

with just:

```ts
import { test } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app.mabl.com');
  await page.goto('https://app.mabl.com');
});
```

**Comment by mxschmitt** [comment] 2023-03-11 08:01
investigation notes:

- mabl crash: https://gist.github.com/mxschmitt/03a13bf9a67f1d3e3df19c1fa7585f35
- GitHub crash not able to reproduce with a fresh build (might be fixed upstream, we need to follow-up)
- when compiling with gcc-12 it crashes
- when compiling with clang it does not crash
- looks like a compiler bug / memory corruption since the code path it follows looks good and it just randomly segfaults.

Next steps:
- [ ] check if it crashes with gcc-12
- [ ] try on Canary build if we can get github.com to crash the process

**Comment by yury-s** [comment] 2023-03-13 16:25
Debugging notes:
```cpp
static Lock allRegistriesLock;
static Vector<URLRegistry*>& allRegistries() WTF_REQUIRES_LOCK(allRegistriesLock)
{
    static NeverDestroyed<Vector<URLRegistry*>> list;
    return list;
}

void URLRegistry::forEach(const Function<void(URLRegistry&)>& apply)
{
    Vector<URLRegistry*> registries;
    {
        Locker locker { allRegistriesLock };
        registries = allRegistries();
    }
    for (auto* registry : registries)
        apply(*registry);
}
```
This is the crashing code, removing `&` from `allRegistries` return type fixes the crash.

**Comment by aslushnikov** [comment] 2023-04-18 17:31
Blocked on Layout Tests being run with CLANG compiler

**Comment by aslushnikov** [comment] 2023-04-19 22:39
For the record: webkit-gtk built with clang-14 passes upstream webkit layout tests.

**Comment by mxschmitt** [comment] 2023-04-20 14:17
should be fixed with WebKit 1835 and is already available on Canary: https://playwright.dev/docs/canary-releases

**Closed by mxschmitt** 2023-04-20 14:17 UTC
Labels: browser-webkit, v1.33
