### ISSUE TITLE
[BUG] WebKit browser gets stuck when interacts with specific UI elements

### ISSUE THREAD

**Issue by propnysedu** [microsoft/playwright#28550] opened 2023-12-08 15:01 UTC
### System info
- Playwright Version: [v1.39.0]
- Operating System: [Windows 11, Ubuntu 20]
- Browser: [WebKit]
- Other info: Stack i use for writing tests: TypeScript/Cucumber/Playwright(playwright's test runner is not used because I use cucumber test runner for BDD)

Hi,

I'm running tests against WebKit and it always gets stuck and stops working completely when it tries to login(when clicks on login button). Similar behavior I encountered on other websites including github website when interacting with UI elements that suppose to redirect you or to open new tab/instance of browse and then with some delay crash report pop up window is occurred. It could be different issues but i am stuck and need help.

**Steps to reproduce from the video:**

1. Navigate to github website(using webkit)
2. Click on 'Solutions'
3. From the list select 'DevOps'

**Expected result:**
WebKit opens DevOps tab.

**Actual results:**
WebKit gets stuck for good.

https://github.com/microsoft/playwright/assets/38424027/a4c3c991-b783-4829-9a99-a8c25181f856

[CrashReport.dmp](https://github.com/microsoft/playwright/files/13615544/CrashReport.dmp)

**Comment by dgozman** [comment] 2023-12-08 19:23
@propnysedu I cannot reproduce this on Windows 11:

```sh
mkdir repro
cd repro
npm init -y
npm install @playwright/test@1.39
npx playwright install
npx playwright wk github.com
# Now click on DevOps and a new window opens
```

Something's wrong with your setup, but it's unclear what could that be.

**Comment by propnysedu** [comment] 2023-12-09 20:46
`npx playwright wk github.com`
This way works even from my project root but it doesn't when i run test in debug mode and then navigate to github. Furthermore it doesn't work at all when I try to login to the app i'm testing.

Could you please try to login to dev.orthologiq.net and try to login with any random email/password just to check whether you will be able to see wrong credentials message or will get stuck as well?

**Comment by fujii** [comment] 2023-12-10 00:04
I confirmed the https://dev.orthologiq.net/ issue with the latest Windows WebKit.
I'm going to take a look at https://bugs.webkit.org/show_bug.cgi?id=266160 .

**Comment by yury-s** [comment] 2024-01-11 21:48
Closing as the upstream issue was fixed in https://commits.webkit.org/272730@main and should be available with the next WebKit roll.

**Closed by yury-s** 2024-01-11 21:48 UTC
Labels: browser-webkit, upstream, v1.42
