### ISSUE TITLE
[BUG] storageState initialized by globalSetup in config not available for POM

### ISSUE THREAD

**Issue by GeGerardo** [microsoft/playwright#20638] opened 2023-02-05 13:05 UTC
**Context:**
- Playwright Version: 1.30
- Operating System: MacOS and Linux
- Node.js version: v16.18.0
- Browser: Chromium

Using Playwright with POM and globalState, the execution always open 2 different page instances and does not share the state. I never had that issue before because I was using custom fixtures

Ex:
POM
```ts
import { Locator, Page } from "@playwright/test";

export class LoginPage {
    readonly page: Page;
    readonly userEmail: Locator;
    readonly userPassword: Locator;
    readonly loginButton: Locator;
    readonly loginHeader: Locator;
    readonly userName: Locator;

    constructor(page: Page) {
        this.page = page;
        this.userEmail = page.getByLabel('Your Email');
        this.userPassword = page.getByLabel('Password');
        this.loginButton = page.getByRole('button', { name: 'Login' });
        this.loginHeader = page.getByRole('heading', { name: 'Login' });
    };

    async navigateToUrl(url: string) {
        await this.page.goto(url);
    };

    async loginInfo() {
        return await this.loginHeader;
    };

    async userLogin(email: string, password: string) {
        await this.userEmail.fill(email);
        await this.userPassword.fill(password);
        await this.loginButton.click();
    };

    // This method is used to avoid the redirection timeout problem
    async userInformation(userName: string, initials: string) {
        await this.page.getByText(userName).waitFor();
        await this.page.getByRole('button', { name: initials }).waitFor();
    };

    async uiAuthentication(url: string, email: string, password: string) {
        await this.navigateToUrl(url);
        await this.userLogin(email, password);
    };

};
```
global-setup
```ts
import { request } from '@playwright/test';
import { envConfig } from '@data/env-config';

async function globalSetup() {

    const appUser = await request.newContext({
        baseURL: envConfig.sandBoxUrl,
    });
    await appUser.post('/portal/v1/actions/login', {
        data: {
            'email': envConfig.userEmail,
            'password': envConfig.encryptPass
        }
    });
    await appUser.storageState({ path: 'state/api-login.json' });
    await appUser.dispose();
};

export default globalSetup;
```

test.spec.ts (Does not work)
```ts
import { test, expect } from '@playwright/test';
import { LoginPage } from '@pageRepo/login-page';
import { envConfig } from '@data/env-config';

test.describe(() => {
    test.use({ storageState: `state/${loginState}.json` });

    test('Please work', async ({ page }) => {
        const loginPage = new LoginPage(page);
        await loginPage.navigateToUrl('/dashboard');
    ...
});
```

With custom fixture (Works fine)
```ts
test.describe(() => {
    test.use({ storageState: `state/${loginState}.json` });

    test("For users:", async ({ ahvPage }) => {
        await ahvPage.navigateToLibrary();
        const modal = await ahvPage.addVessel();
        await expect(modal).toBeVisible();
        ...
```

The fixture I created using the same inheritance organization as the POM.

So something is not being shared when we use POM. Checking the storageState.json the cookies configuration is normal. It is because I am creating a new instance doing `const loginPage = new LoginPage(page);`?

I tried to follow this example: https://playwright.dev/docs/test-parallel#serial-mode

If I uncomment the commented line on that code, it opens a new instance but not logged in: 

```ts
test.describe.configure({ mode: 'serial' });

let page: Page;
let loginStep: LoginPage;

test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    loginStep = new LoginPage(page);
    await loginStep.uiAuthentication('/', envConfig.userEmail, envConfig.userPassword);
});


test.describe('', () => {
    test('Check if application was created previously', async () => {
        const application = new ApplicationPage(page);
        // await loginStep.navigateToUrl('/dashboard');
        await page.getByText(envConfig.userName).waitFor();
        const veri = await application.appCaseIsVisible(envConfig.appName);
        expect(veri).toBeFalsy();
    });
});
```
I found this ticket from last year where he is having a similar issue https://github.com/microsoft/playwright/issues/19724#issue-1512001765

**Comment by mxschmitt** [comment] 2023-02-06 16:03
What did you `ahvPage` fixture do before? Could you provide us a full repro with what's working / what's not working?

**Comment by jaredbash** [comment] 2023-02-06 20:11
I have the same problem that I had posted in my issue linked by @GeGerardo. Here is the information I shared before about this problem:

I am developing tests for a website that requires login for the whole page. This website uses Google Sign-In for authentication. All of the Google accounts used for authentication require two-factor authentication.

This means to test one part of the website, the test suite needs to sign in for each test three times - which eventually leads to problems with authentication requiring human interaction, or even requiring extra steps to authenticate.

To resolve this problem, I followed the [Reuse Signed-In State](https://playwright.dev/docs/auth#reuse-signed-in-state) part of the Playwright documentation so that sign in would happen once and then saved and shared among the tests.

This works fine for just normal tests, the login works properly.  However, I also started using Page Object Models to describe my pages and allow for easier maintenance of the test suite. For some reason, in tests that create new instances of Page Object Model classes, the tests do not make use of the saved state and thus are not logged in.

How can this saved state be passed onto a POM instance in Playwright so that signed-in state can be reused? Perhaps I've missed something simple?

Used a global-setup.ts file to declare login:

```
async function globalSetup(config: FullConfig) {
  const browser = await chromium.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto("http://localhost:8000/login");
  await page.getByRole("button", { name: "Connexion" }).click();
  await page.getByRole("button", { name: "Continue with Google" }).click();
  await page.getByRole("textbox", { name: "Adresse e-mail ou numéro de téléphone" }).fill(process.env.USERNAME);
  await page.getByRole("textbox", { name: "Adresse e-mail ou numéro de téléphone" }).press("Enter");
  await page.getByRole("textbox", { name: "Saisissez votre mot de passe" }).fill(process.env.PASSWORD);
  await page.locator("#passwordNext").click();
  await page.goto("http://localhost:8000");
  // Save signed-in state to 'storageState.json'.
  await page.context().storageState({ path: "storageState.json" });
  await browser.close();
}

export default globalSetup;
```

I added this to my playwright.config.ts file:

```
const config: PlaywrightTestConfig = {
  globalSetup: require.resolve('./global-setup'),
  use: {
    storageState: 'storageState.json'
  }
};
```

Here is an example of a test making use of the POM, which then doesn't use the state created in global setup. The login still happens, but then the new browser opened doesn't have the state and thus gets stuck on the login page:

```
test("apply a filter", async ({ page }) => {
  const dashboardHome = new DashboardHome(page);
  await dashboardHome.goto();
  await dashboardHome.bookingLink.waitFor();
  await dashboardHome.bookingLink.click();
  const reservationsPage = new ReservationsPage(page);
  await reservationsPage.orderNumberFilter.waitFor();
  reservationsPage.filter({ orderID: "22222" });
  await expect(page).toHaveURL("http://localhost:8000/booking/22222");
});
``

Unfortunately, when the test starts - it's not recuperating the storageState. My tests start, and arrive at the login page and don't go any further because they are based on the idea that I'm already logged in. I hope this is clear and enough to help figure out better what is going on.

**Comment by mxschmitt** [comment] 2023-02-08 00:34
Can you provide us a repro which we can run locally? Otherwise we are not able to able to assist unfortunately, thanks!

**Comment by gegoncalves** [comment] 2023-02-10 15:15
Hi @mxschmitt I am sorry for the late response. Unfortunately, I cannot make the code available for the ahvPage. However, I found this repo that has the same structure as my ahvPage. https://github.com/akshayp7/playwright-typescript-playwright-test/blob/main/pageFactory/pageRepository/MyAccountPage.ts

To sum up the issue: I can see that PW is open 2 browser instances using the storageState or beforeAll/Each if the code follow POM.

My bet would be: the new instance `const loginPage = new LoginPage(page);`
PW does always create a new browser for each new instance? For example:
```ts
const loginPage = new LoginPage(page);
const blabla = new LoginPage2(page);
const test = new LoginPage3(page);
```

Will they be logged on using storageState?

**Comment by GeGerardo** [comment] 2023-02-10 15:19
Hi @mxschmitt  I am sorry for the late response. Unfortunately, I cannot make the code available for the ahvPage. However, I found this repo that has the same structure as my ahvPage. https://github.com/akshayp7/playwright-typescript-playwright-test/blob/main/pageFactory/pageRepository/MyAccountPage.ts

To sum up the issue: I can see that PW is open 2 browser instances using the storageState or beforeAll/Each if the code follow POM.

My bet would be: the new instance `const loginPage = new LoginPage(page);`
PW does always create a new browser for each new instance? For example:
```ts
const loginPage = new LoginPage(page);
const blabla = new LoginPage2(page);
const test = new LoginPage3(page);
```

Will they be logged on using storageState?

**Comment by cpolera** [comment] 2023-02-10 16:27
@GeGerardo, any chance that the values you need are session storage values? Those don't get get included in the storageState.json 

Also in your test.spec.ts, I don't see where you instantiated `loginState` to use in the path

**Comment by GeGerardo** [comment] 2023-02-10 16:44
> @GeGerardo, any chance that the values you need are session storage values? Those don't get get included in the storageState.json
> 
> Also in your test.spec.ts, I don't see where you instantiated `loginState` to use in the path

All the needed values for the state are present in the file, I double checked just in case. :P
Regarding the second part, I did not understand your observation.

**Comment by aslushnikov** [comment] 2023-02-16 10:21
@GeGerardo I have this dummy website that we can use for cookie auth workflows: https://demopages.aslushnikov.com/login_cookie.html

With this website, the following workflow works just fine for me:

```ts
// globalsetup.ts
import { request } from '@playwright/test';

export default async function setup() {
  const appUser = await request.newContext({
    baseURL: 'https://demopages.aslushnikov.com',
  });
  const response = await appUser.post('.netlify/functions/login_cookie', {
    data: {
      'username': 'John Doe',
    }
  });
  await appUser.storageState({ path: 'storageState.json' });
  await appUser.dispose();
}
```

And later in your test:

```ts
// a.spec.ts
import { test, expect } from '@playwright/test';

test.use({ storageState: `storageState.json` });

test('should be logged in', async ({ page }) => {
  await page.goto('https://demopages.aslushnikov.com/login_cookie.html');
  await expect(page.locator('h1')).toHaveText('Hello, "John Doe"!');
});
```

With the config like this `playwright.config.ts`:

```ts
import { defineConfig } from '@playwright/test';

export default defineConfig({
  globalSetup: './globalsetup.ts',
});
```

So can you please amend this code and demonstrate what doesn't work? You can fork https://github.com/aslushnikov/demopages and change the `e2e/login_test` to reproduce the issue.

**Comment by aslushnikov** [comment] 2023-02-21 15:51
Looks like the discussion has stalled so I'll speculatively close this.

However, if you still can build a repro to illustrate the problem, please do not hesitate to file a new issue so that we can take a look.

Thanks!

**Closed by aslushnikov** 2023-02-21 15:51 UTC
Labels: triaging

**Comment by sdseenu** [comment] 2024-08-12 18:14
Please suggest storage in pom design with Java
