### ISSUE TITLE
[BUG] Component Testing typeError when running tests in CLI

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#17360] opened 2022-09-15 13:26 UTC
**Context:**
- Playwright Version: latest
- Operating System: Mac M1
- Node.js version: 16.6
- Browser: n/a
- Extra: 

Repo: https://github.com/debs-obrien/component-testing-vue
```
npm run test-ct
```
**Describe the bug**

Tests don't run yet they run in VS Code Extension without any issues however using terminal they are skipped with following error:
1 error was not a part of any test, see above for details:

<img width="1068" alt="Screenshot 2022-09-15 at 15 24 02" src="https://user-images.githubusercontent.com/13063165/190415209-f850d262-b940-4606-b169-1752cfd1e7e2.png">

**Comment by debs-obrien** [comment] 2022-09-15 16:44
removing cache folder fixes it ;)

**Comment by mxschmitt** [comment] 2022-09-16 09:50
Closing for now, please try @next and re-file with clear repro steps if you still encounter issues.

**Closed by mxschmitt** 2022-09-16 09:50 UTC
Labels: triaging

**Comment by AIS-Brandon** [comment] 2022-10-26 11:09
I got this exact same error, and solved it by deleting that playwright cache, in a SvelteKit project on Windows.

To help others find this problem, the type error message is:

> TypeError: Cannot read properties of undefined (reading: 'fullName')

Searching for this message did not turn up in searches because the issue is described with an image.
