### ISSUE TITLE
[BUG] browser.newContext: Target page, context or browser

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#13324] opened 2022-04-05 14:59 UTC
**Context:**
- Playwright Version: 1.20.1
- Operating System: any
- Node.js version: 14.6
- Browser: firefox

**Error in debug mode**

```
  ✘  [Desktop Firefox] › PublicSearch/LandingPage.test.ts:56:5 › Landing page Test Suite › User can search for  (1ms)
  pw:browser [pid=30113] <process did exit: exitCode=0, signal=null> +8ms
  pw:browser ffmpeg onkill exitCode=0 signal=null +0ms
  pw:browser [pid=30113] starting temporary directories cleanup +0ms
  pw:browser [pid=30113] finished temporary directories cleanup +0ms
  pw:browser [pid=30113] <gracefully close end> +0ms
  
  
  1) [Desktop Firefox] › PublicSearch/LandingPage.test.ts:56:5 › Landing page Test Suite › User can search for a city using EN/DE/IT lang while selected lang is FR 

    browser.newContext: Target page, context or browser has been closed
```

**Code Snippet**

```javascript
    test.beforeEach(async ({ page, landingPage }) => {
        await page.goto(path.en.landingPage, { waitUntil: "load", timeout: 30000 })
        await landingPage.waitForText('Log in')
    });
    
        test('User can search for a city using EN/DE/IT lang while selected lang is FR', async ({ page, landingPage }) => {
        await page.goto(path.fr.landingPage, { waitUntil: "load" })
        await landingPage.searchForCity('c')
        await expect.soft(page.locator('text=c >> nth=0')).toBeVisible();
        await landingPage.searchForCity('c')
        await expect.soft(page.locator('text=zurich >> nth=0')).toBeVisible();
        await landingPage.searchForCity('c')
        await expect.soft(page.locator('text=zurich >> nth=0')).toBeVisible();
    });
```

**Describe the bug**

I have noticed that I'm getting the following error so often `browser.newContext: Target page, context, or browser` when a test is running against firefox, it happens randomly with different tests, I failed to find certain steps to reproduce.

but it's obviously happening when you run multiple tests with firefox. especially if the tests are executed in a very short time, this is my guess, all failure was happening on the hook

<img width="1009" alt="Screenshot 2022-04-05 at 16 07 19" src="https://user-images.githubusercontent.com/32042806/161783573-1d351b4c-4db0-4abf-b7bb-43b212e78f86.png">

**Comment by mxschmitt** [comment] 2022-04-06 08:22
Could you share your landingPage fixture with us? There you might call something and forgot an await.

**Comment by amrsa1** [comment] 2022-04-06 10:08
@mxschmitt might be but its always with firefox 

```
const fixtures = base.extend<{ landingPage: LandingPage, dataProvider: DataProvider }>({

    landingPage: async ({ page }, use) => {
        const landingPage = new LandingPage(page)
        await use(landingPage)
    },
    dataProvider: async ({}, use) => {
        const dataProvider = new DataProvider()
        await use(dataProvider)
    }

});

export { fixtures };
```


```
import { Page } from "playwright-core";

export default class LandingPage {

    private page: Page

    constructor(page: Page) {
        this.page = page;
    }

    /********************************************************** Elements ********************************************************* */

    textElement(text: string) { return this.page.locator(`text=${text} >> nth=0`) }
    get searchInput() { return this.page.locator('input[placeholder] >> nth=0') }
    get langSwitcher() { return this.page.locator(`button[role="menuitem"]`) }
    langSwitcherList(lang: string) { return this.page.locator(`a[title="${lang}"]:has-text("${lang}") >> nth=0`) }


    /********************************************************** Actions ********************************************************* */

    async waitForText(text: string){
        await this.textElement(text).waitFor()
        return this;
    }
    
    async searchForCity(value: any) {
        await this.searchInput.waitFor()
        await this.searchInput.fill('')
        await this.searchInput.type(value, { delay: 50 })
        return this;
    }

```

**Comment by liuxingbaoyu** [comment] 2022-04-06 13:41
Looks like there are some logs before this

**Comment by amrsa1** [comment] 2022-04-06 13:52
> Looks like there are some logs before this

Loogs before this, is related to previous test. As  far as i checked.

But i can post it, once i reproduce it.

**Comment by mxschmitt** [comment] 2022-04-07 18:48
@amrsa1 are you able to reduce to a minimal reproducible which we can run locally?

**Comment by amrsa1** [comment] 2022-04-07 20:02
> @amrsa1 are you able to reduce to a minimal reproducible which we can run locally?

I will try to reproduce it in some other public domain and upload the solution.

Just note: that issue is happening randomly but also happening so often, so sometimes it could happen some other time not

**Comment by amrsa1** [comment] 2022-04-08 15:39
@mxschmitt here is again same error, catch it during debugging mode
<img width="1444" alt="Screenshot 2022-04-08 at 17 37 47" src="https://user-images.githubusercontent.com/32042806/162475839-449d77e7-2472-42d2-9e47-eca4d3eb225b.png">

<img width="1404" alt="Screenshot 2022-04-08 at 17 39 33" src="https://user-images.githubusercontent.com/32042806/162475887-533635e0-4724-4184-96d9-10415e579a98.png">

**Comment by mxschmitt** [comment] 2022-04-19 13:46
This does unfortunately not help much. I'm closing it for now since without a clear repro which we can run locally we can't act on it.

Feel free to submit a new issue with a clear repro. Thanks!

**Comment by super-brian** [comment] 2022-05-19 18:38
I have exactly the same issue.
this error line shows randomly only for firefox when I ran tests with --headed option.

`browser.newContext: Target page, context or browser has been closed`

And when I see the test report, there is read 'x' next to the 'Before Hooks' while 'After Hooks' has green checkmark.

it happened to this simple test, which uses a few page objects, and I don't handle browser or context at all.

```
    test(`2 Homepage - ${user.level}`, async ({ page }) => {
      const empty = new Empty(page);
      await empty.gotoTestPage();

      const loginAspx = new LoginAspx(page);
      await loginAspx.clickLogin();

      const login = new Login(page);
      await login.loginWith(user.id, user.pw);

      const home = new Home(page);
      await home.verifyElements(user.level);
    });
```

**Comment by amrsa1** [comment] 2022-05-20 12:33
@mxschmitt  could we reopen this ticket again, i might be able to provide a reproducible code.

**Comment by joannamorgas** [comment] 2022-06-22 16:26
Getting the same issue frequently:  `browser.newContext: Target page, context or browser has been closed`
it fails for random test cases but always  in beforeEach hook, when many tests are ran in headed mode

**Comment by dcprime** [comment] 2022-06-23 13:37
I'm also getting this randomly with firefox (not with other browsers). Maybe once every dozen or so test runs.

**Comment by joannamorgas** [comment] 2022-06-23 13:51
[mxschmitt](https://github.com/mxschmitt) could we reopen this issue - seems more people is encountering the bug currently

**Comment by amrsa1** [comment] 2022-06-23 15:10
This issue is really serious and causing alot of falkiness.

I have decide to disable all test against firefox to avoid such cases.

**Comment by diSharma007** [comment] 2022-06-28 09:42
yeah I am also facing this issue with Firefox every now and then, @mxschmitt please reopen it.

**Comment by rwoll** [comment] 2022-06-29 18:38
See additional info from @amrsa1 on https://github.com/microsoft/playwright/issues/15171#issue-1287117454

**Comment by aslushnikov** [comment] 2022-07-13 09:42
Everybody else: could you please try [installing @next](https://github.com/microsoft/playwright/issues/13324#issuecomment-1181628771) as well? I can no longer reproduce anything similar on tip-of-tree.

**Closed** 2022-07-13 09:44 UTC
Labels: browser-firefox, v1.24

**Comment by dinaRodeny** [comment] 2023-10-09 11:25
I have the same issue
