### ISSUE TITLE
Add ability to use AND and OR expression via grep from command line

### ISSUE THREAD

**Issue by humbienri** [microsoft/playwright#9667] opened 2021-10-20 22:39 UTC
To bring Windows usage up to par with usage on Mac OS X or Linux, 
`npx playwright test -g "tag1|tag2"`

should also work from the Windows command line. Please.

---

Edit by maintainers: Here are Git Bash and PowerShell solutions:

**PowerShell:**

```PowerShell
npx playwright test --grep  "`"@test1|@test2"`"
```

**Git Bash**

```bash
 npx playwright test --grep "@test1^|@test2"
```

**Comment by pavelfeldman** [comment] 2021-10-21 00:25
@humbienri : on Windows do this:

`npx playwright test -g "tag1^|tag2"`

**Comment by jatin-karla11** [comment] 2022-05-05 18:24
how to use and condition in grep?

-g "xy&yz" is not working

**Comment by timtait** [comment] 2022-05-20 08:49
> how to use and condition in grep?
> 
> -g "xy&yz" is not working

Grep is just matching the test title, so you could do something like
```-g "xy.+yz"```

**Comment by btadros** [comment] 2022-07-07 15:45
I also get 
'commission' is not recognized as an internal or external command, operable program or batch file.

my full command on Powershell:
npx playwright test --grep -g "register|commission" --config=playwright.config.js --workers=3 --retries=1

P.S.: tried escaping it, but still didn't help

**Comment by i-savitski** [comment] 2022-08-04 08:04
In Powershell the [stop-parsing token](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parsing?view=powershell-7.2#the-stop-parsing-token) helps:  
`npx playwright test -g --% "tag1|tag2"`

**Comment by imartinflores** [comment] 2022-10-04 14:51
Could someone execute this from the package.json script ?

I m trying:
 "test:textbox": "npx playwright test --config=./configs/playwright-web.config.js --project=chromium --grep text1 | text2"
 "test:textbox": "npx playwright test --config=./configs/playwright-web.config.js --project=chromium -g text1|text2"
 
 And also using the stop-parsing token mentioned above. Always getting the same kind of error
 
 "'text2' is not recognized as an internal or external command"

**Comment by shashankkvs309668** [comment] 2022-10-25 10:53
> p-parsing token mentioned above. Always getting the same kind of erro

Still facing the issue.

**Comment by GustavoBernardi** [comment] 2022-11-03 11:43
@imartinflores - same here...

"test:form": "npx playwright test --project=chromium -g @payx|@ezlm"

**Comment by mihalqesko** [comment] 2022-11-16 19:20
The issue in pwsh is how the command is interpreted! One workaround is by starting the npm process manually and passing the arguments split by pipe as it is used on bash:
```
$npxArgs = "playwright", "test", "-g", "tag1|tag2|tag3"
Start-Process npx -ArgumentList $npxArgs -Wait -NoNewWindow -ErrorAction Stop
```

**Comment by skumar09** [comment] 2023-03-25 07:25
> > how to use and condition in grep?
> > -g "xy&yz" is not working
> 
> Grep is just matching the test title, so you could do something like `-g "xy.+yz"`

- This has really worked in Windows / VSCode powershll. 
-  `-g "xy.+yz"` is a And condition

**Comment by joeflan** [comment] 2023-03-27 18:38
> * This has really worked in Windows / VSCode powershll.
> * `-g "xy.+yz"` is a And condition

This worked for me in powershell. Do you know how to escape the quotes in a package script format?

**Comment by shashankkvs309668** [comment] 2023-03-28 06:45
> Could someone execute this from the package.json script ?
> 
> I m trying: "test:textbox": "npx playwright test --config=./configs/playwright-web.config.js --project=chromium --grep text1 | text2" "test:textbox": "npx playwright test --config=./configs/playwright-web.config.js --project=chromium -g text1|text2"
> 
> And also using the stop-parsing token mentioned above. Always getting the same kind of error
> 
> "'text2' is not recognized as an internal or external command"

i tried this way with grep under projects in playwright.config.js, and it is working for me,
grep:/^(?=.*\bsmoke\b)(?=.*\bregression\b).*$/m,

**Comment by irharrier2** [comment] 2023-06-08 08:21
> npx playwright test -g "tag1^|tag2"

This clearly doesn't work on Windows and many people have already mentioned this, however, it is still being replied as answer to multiple threads.

Any updates on this?

**Comment by hsuraweera** [comment] 2023-07-10 08:07
Is there any way to --grep based on three annotations?
Condition: 
Run test that contain @API or @UI on @PROD

**Comment by mxschmitt** [comment] 2023-07-19 10:17
Escaping a pipe symbol in PowerShell is unfortunately not straightforward. Escaping it in Git Bash and PowerShell is both different:

**PowerShell:**

```PowerShell
npx playwright test --grep  "`"@test1|@test2"`"
```

**Git Bash**

```bash
 npx playwright test --grep "@test1^|@test2"
```

Unfortunately this is not something we can fix on our side (since the "magic" happens inside the terminals), but what we can do is update our docs to include these two workarounds.

**Comment by jaktestowac** [comment] 2023-07-19 11:53
@mxschmitt unfortunately those commands don't work (tested PS and Git Bash). I have a clean W11 installation. Looks like bug since I have no real possibility to correctly execute those expression on Windows.
If you have some ideas or solutions, I can check it.

**Comment by jaktestowac** [comment] 2023-07-19 13:05
Here are tested solutions (W11 in VS Code) :

For PowerShell: 
`npx playwright test --grep --% "@fast^|@slow"`

For Git Bash:
`npx playwright test -g "@fast|@slow"`

For CMD:
`npx playwright test --grep "@fast^|@slow"`

For npm script:
`"npx playwright test -g \"@fast|@slow\""`

Remember to check console where script is ran:
![obraz](https://github.com/microsoft/playwright/assets/72373858/162fdf7b-4ca9-4a3a-bac5-44afa9d492e8)

**Comment by jaktestowac** [comment] 2023-07-21 20:26
@mxschmitt have look on PR with docs update https://github.com/microsoft/playwright/pull/24304

**Comment by bisvo01** [comment] 2023-08-31 17:15
What's the proposed approach when you want to combine some rules from npm script and interactive command line? Example ([suggested by](https://github.com/microsoft/playwright/issues/9682#issuecomment-1311077730) @ffluk3):
> ```json
> {
>   "scripts": {
>     "e2e": "playwright --grep-invert \"@wip\""
>   }
> }
> ```
> 
> However, if I wanted to omit another tag on the fly, I wouldn't be able to run `npm run e2e -- --grep-invert @flaky`. Is there a recommended way to approach this use case?

**Comment by ZachMcCorkhill** [comment] 2024-01-25 19:35
In my Windows terminal I'm able to get the OR grep to work by adding a space around the pipe:
npx playwright test -g "@fast | @slow"

**Comment by mxschmitt** [comment] 2024-02-12 14:29
Different shells require different escaping, we updated our documentation recently to reflect these changes: https://playwright.dev/docs/test-annotations#tag-tests

Please re-file if you have concrete filters which don't work. Please let us know the following:

- Which shell you are using
- How your test is named
- What your expectation is

Closing for now since we addressed it.

**Closed by mxschmitt** 2024-02-12 14:29 UTC
Labels: P3-collecting-feedback, feature-test-runner
