### ISSUE TITLE
[BUG] Timeout of 60000ms exceeded while running fixture "context" teardown.

### ISSUE THREAD

**Issue by azad-derakhshani-GS** [microsoft/playwright#14686] opened 2022-06-07 17:11 UTC
**Context:**
- Playwright Version: 1.22
- Operating System: Manjaro Linux
- Node.js version: v16.15.0
- Browser: Chromium

When running my entire testsuite (currently 23 tests, 4 skipped, total duration 4 minutes, 7 spec files & workers), some tests fail with

`[BUG] Timeout of 60000ms exceeded while running fixture "context" teardown.`

But the issue doesn't occur when running those tests individually (same as in https://github.com/microsoft/playwright/issues/14685, so maybe both issues have a shared cause), so it seems like there might be a performance issue with PW.
Often the attachments are missing too when this issue occurs.

Since I can't share the entire testsuite, I could maybe show someone in a call via screensharing if that helps.
Or I could also share my Fixtures file but I'm not sure that's what the error message is referring to.

**Comment by pavelfeldman** [comment] 2022-06-07 19:08
Is there a chance we could get a repro for it?

**Comment by azad-derakhshani-GS** [comment] 2022-06-07 19:13
Since it only happens when running the entire test suite and not individual tests, I would have to give you the entire test suite, which of course I can't, so that's why I suggested showing it in a call instead.

**Comment by pavelfeldman** [comment] 2022-06-09 18:39
Closing as non-actionable since we can't reproduce it.

**Closed by pavelfeldman** 2022-06-09 18:39 UTC
Labels: v1.23

**Comment by nachee** [comment] 2022-06-17 15:31
@azad-derakhshani-GS were to able to solve this after discussing it privately? I'm getting the same timeout after I rerun recently passing tests.

**Comment by fobdy** [comment] 2022-06-20 18:28
Ah, ok got it. The issue was caused by general slowness of the test. So it took a bit more than 30S that's why it was hard to clarify the root cause problem. Because deadline was at the time of "context" teardown.

**Comment by azad-derakhshani-GS** [comment] 2022-06-20 20:58
> @azad-derakhshani-GS were to able to solve this after discussing it privately? I'm getting the same timeout after I rerun recently passing tests.

Hey, yeah we had a call and from what I understand the timeout is also needed for the teardown, so if the timeout is too short (30s seems a bit short to me), it will fail even if the test itself passed, because there's no time left for the teardown. Basically what @fobdy figured out too. :)

**Comment by elliotgaramendi** [comment] 2023-11-06 04:13
Can someone explain to me why Test2 is very slow?

`
import { test } from '@playwright/test';

test('Test 1', async ({ page }) => {
  await page.goto('https://twitter.com');
});

test('Test 2', async ({ page }) => {
  await page.goto('https://twitter.com');
});
`
![image](https://github.com/microsoft/playwright/assets/62267772/877730cd-8506-4c6c-9385-89a161a7403d)
