### ISSUE TITLE
Weird issues with unreliable test results, passes and fails arbitrarily 

### ISSUE THREAD

**Issue by bobbyngwu** [microsoft/playwright#12193] opened 2022-02-17 21:18 UTC
**Playwright version**
v1.17, 1.19

**Operating system**
Windows

**What browsers are you seeing the problem on?**
All supported projects

I am very new to Playwright and just started using the framework for our e2e tests. I have about 16 tests that I am running across Chromium and Firefox. Webkit just fails with various errors such as "Element out of the ViewPort", so I have just commented the webkit project for now because its not obvious to me why same tests will run fine on Chromium and Firefox but struggle in Webkit.

The issue I have is about unreliability even with the limit to just chromium and firefox and I am not sure yet whats causing this. When I execute the tests especially in headless mode, some of the tests fail but when retried, they pass. Next time some of those that passed previously would fail and the others will pass. I have never had a clean session where all my tests passed successfully. The nature of my tests involve the critical paths of our application from the user logging to performing various tasks. I am reusing the storage state from the login to complete all the other tests.

My question is why will the tests not run successfully all the time. Some of the the errors that are thrown:

1. Waiting for Element to be visible, sometimes it will report that the element was resolved to a visible element but then scrolled it into view and then its no longer attached. At times, elements which are visible and on the DOM, it will not be able to find them.
2. Waiting for Response from the server (where I have made a request and I am awaiting a response) - this times out and throws an error
The funny thing is when this re-runs, same tests will run fine. 

```
 Retry #1 ---------------------------------------------------------------------------------------

    page.click: Timeout 120000ms exceeded.
    =========================== logs ===========================
    waiting for selector "button[data-test-id="release-from-hold-btn"]"
      selector resolved to visible <button pbutton="" label="Release from Hold" data-test-i…>…</button>
    attempting click action
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
    ============================================================
```
You wonder why the above element which is visible will timeout clicking after 2mins.

Can someone give me a pointer or a clue of what I can be looking out. When I just run 1 test it works fine, issue starts to creep in when I am running multiple tests and number of workers increase... Wondering if there is a race condition somewhere... I have a feeling there may be something I have not done right

**Comment by dgozman** [comment] 2022-02-17 23:17
There is usually a race condition in cases like this one. Perhaps your test is missing an `await` somewhere. Or the machine is slow at the moment and just does not handle it during the timeout. Or your web app backend is timing out for some reason.

I'd suggest to [record a trace](https://playwright.dev/docs/trace-viewer) for the failing run and explore it - maybe you'll see what's going on.

**Comment by bobbyngwu** [comment] 2022-02-18 00:15
Hi @dgozman thanks for responding. I have several traces to be honest and sometimes running in headed mode, I see this just freezeing and not responding for unknown reasons. Sometimes, I have to help the browser sort of to continue with the test. Like I said several tests are executed in parallel. Perhaps I will just disable parallelism and see what the result is like. I am just worried as that may take hours to complete. my 16 tests currently takes about 30 + minutes running against the two browsers.

**Comment by bobbyngwu** [comment] 2022-02-22 13:58
Made some code changes and used the route.fulfill functionality to intercept requests to the server and served the stub json data. This seems to have improved performance. Will continue to look into the cause of the race condition. Will close for now

**Comment by jamalebp-formant** [comment] 2022-06-17 17:51
@bobbyngwu were you able to solve this race condition?? I'm running into similar errors and wondering what I'm doing wrong as everything appears to be awaited.

**Comment by bobbyngwu** [comment] 2022-06-18 08:24
Hi @jamalebp-formant , I managed to get this stabilised. It was down to incorrect use of the async and awaits especially when using the Locator to find elements within the page. 

In my case:
I initially had this to fetch me all Next Buttons:

`nextButton = async (): Promise<Locator> => await this.page.locator('button:has-text("Next")').first();`

and was calling it like this:

`await (await this.nextButton()).click();`.

I realised I was causing problems for myself with the multiple async operations, I later refactored this to be a bit cleaner like this:


`nextButton = (): Locator => this.page.locator('button:has-text("Next")')?.first();`

Then I called it as such `await this.nextButton().click();`

Also not that there were few scenarios where it failed but I had set each test to retry if it fails at least twice. 

There were few modifications I made here and there including some specific issue with Safari (Webkit) which was fixed by removing the {force: true} attribute on the click event.

If you let me know specifically what issue you are facing, perhaps I could be a bit more helpful

**Comment by chundhau** [comment] 2022-07-16 19:13
@bobbyngwu, I'm having similar issues. I get unreliable results in this test:

```
  test('Open Settings menu item via keyboard', async ({ page }) => {
    await page.keyboard.press('Enter'); //Select first ("Settings") menu item
    await expect(page.locator('#sideMenu')).not.toBeVisible();
    await expect(page.locator('#menuBtn')).toBeFocused();
  });
```

If I set up a test configuration with multiple projects, this test often fails for one of the projects, but succeeds for the others. 

However, if I run each project individually, this test passes consitently!

If I modify the app menu's focus behavior by giving the menu button focus only after a delay forced by a JavaScript `setTimeout()` function:

```
setTimeout(() => GlobalMenuBtn.focus(),1); //Give menu btn focus after slight delay
```
all tests in all projects pass consistently!

From these observations, I conclude that the unreliable test performance is an issue with the parallel nature of test execution in Playwright. Is there a way I can rewrite the test in Playwright to introduce some sort of delay that will make the tests reliable? I have tried using `test.setTimeout(100)` before `await expect(page.locator('#menuBtn')).toBeFocused();`, but that didn't work.

Thanks in advance!

**Comment by chundhau** [comment] 2022-07-16 19:22
@bobbyngwu Running the tests in the file in serial seems to cause the tests to succeed reliably, thus confirming my suspicion about parallelization issues:

```
test.describe.serial("menu tests",() => {
  test.beforeEach(async({ page }) => {
    await page.goto(''); //goes to base URL set in config file
    await page.keyboard.press('Tab'); //Focus skip link
    await page.keyboard.press('Tab'); //Focus menu
    await page.keyboard.press('Enter'); //Select menu
  });
//Tests go here
```

**Comment by thedavidhoffman** [comment] 2022-08-29 19:37
We're having this issue on ver 1.25.1. We currently have around 360 tests, and it's rare to get a full clean run, but if you keep running the test suite over and over, eventually it will get a full clean run. If we take any of the test that randomly fail and run them individually, they always pass. So it seems like Playwright can be unreliable when executing a larger batch of tests.

**Comment by bobbyngwu** [comment] 2022-08-29 19:50
@thedavidhoffman this is similar to the experience I have had. I honestly don't know why, but I suspected it may have something to do with context sharing or so. Also could randomly happen in different browsers.

What I have done for our CI, as a workaround though is to repeat failed tests at least thrice. Have been having them all pass since then though.

**Comment by bobbyngwu** [comment] 2022-08-29 19:51
> @bobbyngwu Running the tests in the file in serial seems to cause the tests to succeed more reliably:
> 
> ```
> test.describe.serial("menu tests",() => {
>   test.beforeEach(async({ page }) => {
>     await page.goto(''); //goes to base URL set in config file
>     await page.keyboard.press('Tab'); //Focus skip link
>     await page.keyboard.press('Tab'); //Focus menu
>     await page.keyboard.press('Enter'); //Select menu
>   });
> //Tests go here
> ```
> 
> However, some tests still fail on occasion.

Nice. Will give that a try

**Comment by bobbyngwu** [comment] 2022-08-29 19:52
Reopening as this still seem to be reoccurring ... Will require a proper fix or documentation to ensure we are doing it right

**Comment by pavelfeldman** [comment] 2022-08-29 20:03
> await page.keyboard.press('Tab'); //Focus skip link

Your tests seems non-deterministic, you don't know when the element becomes active, hence you don't know where the `Tab` is dispatched.

I'll close this since the problems described here are due to the tests being non-deterministic. Using web-first assertions `await exect(locator).to` are the advice we can give to unflake the tests, everything else requires exact steps so that we could reproduce and fix on our side.

**Closed by pavelfeldman** 2022-08-29 20:03 UTC
Labels: triaging
