### ISSUE TITLE
[BUG] Use different browser with recorder in vscode

### ISSUE THREAD

**Issue by morganBlanloeil** [microsoft/playwright#24276] opened 2023-07-18 09:08 UTC
**Context:**
- Playwright Version: 1.36
- Operating System: Linux or Windows
- Node.js version: 16.18.1
- Visual Studio Code version: 1.80.0
- Playwright for VSCode extension version: 1.0.14
- Browser: All

**Code Snippet**
`  /* Configure projects for major browsers */
  projects: [

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'chromium',
      use: { 
        ...devices['Desktop Chrome'],
      }
    }`
**Describe the bug**

When I run "Record New" from intergration playwright to vscode, vscode run always chromium despite of choose default profile as firefox.  How to force vscode to use firefox instead of chrome ?

**Comment by mxschmitt** [comment] 2023-07-18 09:31
To use a different browser, aka. the browser which you last time ran your tests with do the following:

1. Change the default profile in VSCode:
    <img width="754" alt="Screenshot 2023-07-18 at 11 28 10" src="https://github.com/microsoft/playwright/assets/17984549/269b90a6-8764-476e-9c8a-9370eda7072d">
2. Run some test
3. Click on Record New

Then the browser from the last test run with its configuration gets used. Would that work for you?

**Comment by morganBlanloeil** [comment] 2023-07-18 10:06
Thanks for your quick answer, but this solution don't working for me, vscode run always chromium

**Comment by aslushnikov** [comment] 2023-07-18 10:48
@morganBlanloeil could you please record & show us video, that demonstrates your playwright.config.ts, your default profile, and how you run code generation?

**Comment by morganBlanloeil** [comment] 2023-07-18 11:54
Sure, 

My playwright config : 

`import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  reporter: 'html',
  use: {
    headless: false,
    trace: 'on-first-retry',
  },

  /* Configure projects for major browsers */
  projects: [

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      }
    }
  ],
});
`

And record attached
[record_playwright](https://github.com/microsoft/playwright/assets/4191050/0765488a-3e11-4c83-894f-3f3ddf982e6e)

**Comment by mxschmitt** [comment] 2023-07-18 13:20
The issue is that you need to have "Show browser" checked, then the browser stays open and it will work: 
<img width="142" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/2bbc4b97-d77f-49bc-adfe-4093cef35560">

**Comment by morganBlanloeil** [comment] 2023-07-18 13:24
Ok thanks it's work . 
You know il an issue is planned for launch the correct browser without run test before ?

**Comment by aslushnikov** [comment] 2023-07-19 17:23
@morganBlanloeil out of curiosity, why do you need specifically Firefox when recording?

**Comment by morganBlanloeil** [comment] 2023-07-20 06:25
I need to use firefox with my local environment, because,even if chrome is running in privacy mode, it use WIA (Integrated Windows Authentication) and we use another user for our tests. So we use firefox to bypass this. If you have another solution, i take it :)

**Comment by aslushnikov** [comment] 2023-07-21 22:13
I see, thank you for sharing. I'll close this then given that workaround works for you!

**Closed by aslushnikov** 2023-07-21 22:13 UTC
Labels: triaging

**Comment by SD1982** [comment] 2024-03-15 13:06
Hello @aslushnikov 
I have the same issue than @morganBlanloeil with the same configuration even with the "show browser" option checked
here is the recording 


https://github.com/microsoft/playwright/assets/40635814/9f8a2cde-2def-4a28-8a17-411b15b78ef8

**Comment by mxschmitt** [comment] 2024-03-15 13:14
@SD1982 looks like this is about https://github.com/microsoft/playwright/issues/26777 - you need to execute a test with your preferred configuration first until we have fixed the issue.

**Comment by SD1982** [comment] 2024-03-15 13:30
It worked with this :+1: 
i will use it like this for now and I will follow #26777 to know when it's fixed :+1: 
Thanks @mxschmitt
