### ISSUE TITLE
[BUG] Webkit should launch on Ubuntu/Pop! 22.04 with screenshotting

### ISSUE THREAD

**Issue by curiousercreative** [microsoft/playwright#13934] opened 2022-05-04 16:51 UTC
**Context:**
- Playwright Version: 1.21.1
- Operating System: Linux Pop!_OS 22.04
- Node.js version: v14.19.0
- Browser: WebKit

System:
 - OS: Linux 5.16 Pop!_OS 22.04 LTS
 - Memory: 29.55 GB / 125.80 GB
 - Container: Yes

Binaries:
 - Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
 - Yarn: 1.22.17 - ~/.nvm/versions/node/v14.19.0/bin/yarn
 - npm: 8.5.4 - ~/.nvm/versions/node/v14.19.0/bin/npm

Languages:
 - Bash: 5.1.16 - /usr/bin/bash

npmPackages:
 - playwright: ^1.21.1 => 1.21.1

**Code Snippet**

`yarn playwright test path/to/some/test/with/page.screenshot.spec.ts --browser=webkit --update-snapshots`

```javascript
import { test, expect } from '@playwright/test';

test('webkit screenshot test', async ({ page }) => {
  // login screen
  await page.goto('https://github.com/microsoft/playwright');
  expect(await page.screenshot()).toMatchSnapshot('test.png');
});
```

**Describe the bug**
Playwright fails to launch webkit browser with error:
```
1) [webkit] › path/to/some/test/with/page.screenshot.spec.ts:3:1 › webkit screenshot test

    browserType.launch: 
    ╔══════════════════════════════════════════════════════╗
    ║ Host system is missing dependencies to run browsers. ║
    ║ Missing libraries:                                   ║
    ║     libwebp.so.6                                     ║
    ╚══════════════════════════════════════════════════════╝
```

**Workaround**
```bash
sudo apt install libwebp-dev
sudo ln -s /usr/lib/x86_64-linux-gnu/libwebp.so /usr/lib/libwebp.so.6
```

**Comment by mxschmitt** [comment] 2022-05-04 17:38
Ubuntu 22 is not supported yet, this sounds then like a duplicate of https://github.com/microsoft/playwright/issues/13738

**Comment by dgozman** [comment] 2022-05-04 20:00
Closing per above.

**Closed by dgozman** 2022-05-04 20:00 UTC
