### ISSUE TITLE
[BUG] Zephyr API is not working in beafore each hook (https://api.zephyrscale.smartbear.com/v2/testexecutions) getting invalid URL error

### ISSUE THREAD

**Issue by KAjayGoutham** [microsoft/playwright#33201] opened 2024-10-21 13:29 UTC
Zephyr API is not working in beafore each hook (https://api.zephyrscale.smartbear.com/v2/testexecutions) getting invalid URL error where as the same API is working in postman

**Comment by mxschmitt** [comment] 2024-10-21 13:33
Maybe baseURL is null or an empty string?

Could you try out canary? https://playwright.dev/docs/canary-releases

**Comment by KAjayGoutham** [comment] 2024-10-21 13:47
no @mxschmitt  actually we are doing UI automation where i am using zephyr API to check the testcase is already passed or if not am executing the scripts, but some how the API is throwing invalid URL issue in only before each hook, FYI the same API is working in custom reports.ts

**Comment by mxschmitt** [comment] 2024-10-21 13:49
I'll close it for now because this issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!

**Closed by mxschmitt** 2024-10-21 13:49 UTC

**Comment by KAjayGoutham** [comment] 2024-10-22 05:07
No Issues @mxschmitt actually thank you, the problem is with latest release of playwright I believe, with **https://playwright.dev/docs/canary-releases** command : npm install -D @playwright/test@next resolved the issue.
