### ISSUE TITLE
executable doesn't exist at /app/.meteor/heroku build/apps/programs/server/npm/node_modules/playwright/.local-browsers/chromium-907428/chrome-linux/chrome heroku[BUG]

### ISSUE THREAD

**Issue by javDevInd** [microsoft/playwright#21053] opened 2023-02-21 11:14 UTC
**Context:**
- Playwright Version: [1.14.0]
- Operating System: [heroku]
- meteor :[v 1.9.2]
- Node.js version: [12.16.1](The reason for using node version 12.16.1 is my application supports only meteor 1.9.2 and meteor internally uses particular node version )
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium} = require('playwright');

(async () => {
  const browser = await chromium.launch({
headless:true,args:['--no-sandbox','--disable-setuid-sandbox']
});
  const context = await browser.newPage();
 await page.goto(url,{waitUntil:'networkidle'});
await page.pdf({
displayHeaderFooter:true,
printBackground:true,
headerTemplate:'',
footerTemplate:''
})
  await browser.close();
})();
```

**Describe the bug**

Add any other details about the problem here.

**Comment by yury-s** [comment] 2023-02-21 22:11
1.14.0 is quite old, can you reproduce the issue with the latest Playwright version?

From the error message it looks like you set [custom browsers location](https://playwright.dev/docs/browsers#managing-browser-binaries) but the browsers are not there. Make sure the binaries are downloaded to the same directory (you can run `npx playwright install`)

**Comment by javDevInd** [comment] 2023-02-22 08:50
Hi yury-s fyi the above code snippet only we are using in our application we are not setting any custom browser locations . the reason for using old playwright version is my application is strict with meteor 1.9.2 and meteor 1.9.2 is internally uses node 12.16.1 which is not possible to upgrade. with playwright 1.14.0 pdf generation is working fine and other versions requires higher node version.  i have ran the command(npx playwright install) after application build in heroku cli. by default the browsers are getting installed in the following location ( /app/.cache/ms-playwright ). we have added buildpacks also. any suggestion please.

**Comment by javDevInd** [comment] 2023-02-22 18:05
Hi Yury Semikhatsky, we are using heroku stack-20. and after deploying the application when i try to generate pdf following error appears. 
browserType.launch: Executable doesn't exist at /app/.meteor/heroku_build/app/programs/server/npm/node_modules/playwright/.local-browsers/chromium-907428/chrome-linux/chrome

![image001 (2)](https://user-images.githubusercontent.com/43812076/220715046-223aba55-7fbc-4abd-9dd4-bec8212e799c.png)


but when i looking into the location browsers are already installed and chrome file is exists.

![image001 (1)](https://user-images.githubusercontent.com/43812076/220716620-40f801c7-299e-4d4d-aaef-52b5e1a5b8af.png)

can you please guide me further i am blocked with this issue.

**Comment by yury-s** [comment] 2023-02-24 02:40
> i have ran the command(npx playwright install) after application build in heroku cli. by default the browsers are getting installed in the following location ( /app/.cache/ms-playwright ). we have added buildpacks also. please provide suggestion and guidance further.

That is the expected default location. Playwright will be looking for the browser under `node_modules/playwright/.local-browsers` only if you pass `PLAYWRIGHT_BROWSERS_PATH=0` as described on [this page](https://playwright.dev/docs/browsers#hermetic-install). You can try running `PLAYWRIGHT_BROWSERS_PATH=0  npx playwright install` to install browsers into the non-default location. But it looks very fishy, if the browser is there playwright should just use it. 

We don't support playwright 1.14 anymore, I'd suggest you try find a way to update to a newer version (also Node 12 extended supported ended a year ago).

**Comment by yury-s** [comment] 2023-02-27 21:41
Closing per the response above, feel free to open a new issue if it doesn't work.

**Closed by yury-s** 2023-02-27 21:41 UTC
Labels: triaging
