### ISSUE TITLE
[BUG] subtree intercepts pointer events

### ISSUE THREAD

**Issue by LongLiveY96** [microsoft/playwright#19423] opened 2022-12-13 10:58 UTC
**Context:**
- Playwright Version: [1.28.0]
- Operating System: [Windows]
- Node.js version: [16.15.1]
- Browser: [Chromium]

![image](https://user-images.githubusercontent.com/23394317/207299733-5d0c79ec-8d1a-481b-96ac-b220eff33da6.png)
![image](https://user-images.githubusercontent.com/23394317/207299789-6c436f2f-b1aa-4d34-ae9a-75cf1589bdbc.png)

**Code Snippet**

```javascript
await page1.getByText('状态:').click();
```

**Describe the bug**
playwright cannot click on an element visible on the page. And showed 'subtree intercepts pointer events'
I hava sent the trace file to anlushni@microsoft.com. I'm trying to figure out why the click action is not works, thanks.

**Comment by cpolera** [comment] 2022-12-13 16:07
I've also experienced the same issue just this morning.

```
  pw:api waiting for locator('.foo, .bar, [data-cauto-id="pls_help"]').first().locator('label').locator('input') +2s
  pw:api   locator resolved to <input type="checkbox" class="css-11mq73q e1excnjx2" da…/> +10ms
  pw:api <= locator.isChecked succeeded +7ms
```
And then on that same chained locator I attempt a click(). This block below then just repeats endlessly 
```
  pw:api attempting click action +1ms
  pw:api   waiting for element to be visible, enabled and stable +0ms
  pw:api   element is visible, enabled and stable +30ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +0ms
  pw:api   <span aria-hidden="true" class="css-1stafj2 e1excnjx1"></span> intercepts pointer events +6ms
```

**Comment by yury-s** [comment] 2022-12-13 20:40
Can you upload the trace here or send it to the email in my github profile?  Having a full repro would be even better.

**Comment by aslushnikov** [comment] 2022-12-13 23:58
(requested access from my gmail address)

**Comment by LongLiveY96** [comment] 2022-12-14 02:00
> Can you upload the trace here or send it to the email in my github profile? Having a full repro would be even better.

accessing is ok now

> (requested access from my gmail address)

**Comment by aslushnikov** [comment] 2022-12-14 22:31
@LongLiveY96 in the trace, I see there's a glasspane with loading indicator that overlays the whole page. It looks like it captures all clicks, so the button indeed cannot be clicked.

**Comment by LongLiveY96** [comment] 2022-12-15 02:02
> @LongLiveY96 in the trace, I see there's a glasspane with loading indicator that overlays the whole page. It looks like it captures all clicks, so the button indeed cannot be clicked.

I sent the new attachment as an email and I can see that the icon mask does not load when the page performs the click action.

**Comment by aslushnikov** [comment] 2022-12-15 17:21
@LongLiveY96 now I can see the weird behavior. Any chance you can share the website privately with us so that we can debug it locally?

**Comment by LongLiveY96** [comment] 2022-12-16 02:21
> @LongLiveY96 now I can see the weird behavior. Any chance you can share the website privately with us so that we can debug it locally?

Is the har file enough to locate the problem? I sent the ts script that reproduces the problem and the corresponding har file to the email address.

**Comment by aslushnikov** [comment] 2023-02-03 10:17
@LongLiveY96 oops sorry, I got carried away from this discussion and forgot about it.

I didn't find the HAR file on my e-mail address nor the TS source. 
Can we start over?

**Comment by LongLiveY96** [comment] 2023-02-03 17:58
> @LongLiveY96 oops sorry, I got carried away from this discussion and forgot about it.
> 
> I didn't find the HAR file on my e-mail address nor the TS source. Can we start over?

send it to anlushni@microsoft.com again, please check.

**Comment by aslushnikov** [comment] 2023-03-02 18:11
Hey @LongLiveY96,

I came back to this issue, found the HAR, but it's not enough for figure out what's going on. Can you prepare a small repo that illustrates the issue so that I can debug it locally?

**Comment by aslushnikov** [comment] 2023-03-10 01:36
@LongLiveY96 I'll speculatively close this; feel free to re-file if you have a small repro that we'll be able to run locally to reproduce this!

**Closed by aslushnikov** 2023-03-10 01:36 UTC
Labels: v1.32
