### ISSUE TITLE
Feature: hide/remove Elements from Screenshots

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#10326] opened 2021-11-15 16:15 UTC
### Discussed in https://github.com/microsoft/playwright/discussions/5068

<div type='discussions-op-text'>

<sup>Originally posted by **rollin-cogers** January 20, 2021</sup>
Hey everyone! I've been very excited to use this tool for testing, as I've previously been using protractor for all my testing.

In the past I've used modules like webdriver-image-comparison that allow for options like [hiding and removing elements](https://github.com/wswebcreation/webdriver-image-comparison/blob/master/docs/OPTIONS.md#hideelements-5) from a screenshot by adding `visibility: hidden` or `display: none` to the styling for the passed elements.

Is this a feature that we might see in the future with playwright? Would anyone else benefit from the ability to exclude elements from screenshots?

I would love to see something like this:
```javascript
page.screenshot({fullpage: true, hideElements: ['div.dynamic_content', 'div#profilePicture']})
```</div>

**Comment by aslushnikov** [comment] 2021-11-16 07:45
Dupe of https://github.com/microsoft/playwright/issues/10162

**Closed by aslushnikov** 2021-11-16 07:45 UTC
Labels: v1.18
