### ISSUE TITLE
[Feature] Locator to implement Iterable 

### ISSUE THREAD

**Issue by bnesteruk** [microsoft/playwright#15841] opened 2022-07-21 14:22 UTC
A Locator object apparently can be resolved to several elements, so can represent a list. 
And there are some useful methods to use in this case (e.g. `Locator.first()` `Locator.nth()` etc). 
Same time, If I need to iterate several locators, the only way I see (please correct me if I'm wrong) is to  get the count first, and then take each new item by index from locator list manually:

```
let itemsCount = await this.pickLkistItem.count() // find the count
for (let index = 0; index < itemsCount; index++) { 
    let item = this.pickLkistItem.nth(index) //get the element by index within locator list
    // . . . do what you need
}
```
And this looks really overwhelming. 
If a locator can be a list, could we use the Iterable functions instead? E.g.: 

```
for (const item of [this.pickLkistItem]) {
      item // . . . do what you need
}
```

Or: 

```
this.pickLkistItem.forEach(it => { arr.push(await it.textContent()) });
this.pickLkistItem.reduce((result, item) => { . . . }
```

I guess that the count of the locator items should be frozen at the point of the iterable function start, so if it increases, additional iterations are ignored. Otherwise, a 'missing element' error should be thrown if the count decreased 

Or I'm missing something and this is already supported somehow?

**Comment by mxschmitt** [comment] 2022-07-21 15:05
Looks like a duplicate of https://github.com/microsoft/playwright/issues/12336.

**Closed** 2022-07-22 00:23 UTC
