### ISSUE TITLE
[Question] All Firefox tests from the todomvc example timeout and fail

### ISSUE THREAD

**Issue by jmcgavin** [microsoft/playwright#18004] opened 2022-10-11 20:22 UTC
- I have initialized a repo that contains the tests and playwright config from [https://github.com/microsoft/playwright/tree/main/examples/todomvc](https://github.com/microsoft/playwright/tree/main/examples/todomvc)
- I bumped the @playwright/test version to latest (1.27.0)
- I ran `npm install` and `npx playwright install`

When I run `npm test` all tests pass on Chrome and Safari but on Firefox, all the tests fail after reaching the 30s timeout.

![playwright-firefox-fail](https://user-images.githubusercontent.com/39205937/195190420-cec1bdd2-06ac-4e64-a9b2-b6c885565dc2.jpg)

Am I doing something wrong or is there an issue with the [Playwright config](https://github.com/microsoft/playwright/blob/main/examples/todomvc/playwright.config.ts) I am using?

Things to note:

- Playwright version: 1.27.0
- OS: Windows
- Node version: 16.14.0
- Extra: I am behind a corporate firewall

**Comment by pavelfeldman** [comment] 2022-10-12 00:12
Works for me:

```sh
$ npx playwright test
Running 75 tests using 28 workers
  75 passed (13s)
To open last HTML report run:
  npx playwright show-report
```

> Extra: I am behind a corporate firewall

This would be the reason.

**Comment by dubpal** [comment] 2022-10-13 12:45
Did the Firefox freeze/hang? I had this happen a few times today, wasn't able to find the root cause though (manually starting Firefox nighlty and repeating the steps of the test doesn't lead to a freeze.. 
The firefox freeze happens like 1 out of 3 runs on my machine.

**Comment by dgozman** [comment] 2022-10-19 20:16
@dubpal Unfortunately, we cannot reproduce this issue. Perhaps the problem is in your network/firewall, so that browser is not able to load the url? Not sure how we can help.

**Comment by dubpal** [comment] 2022-10-21 09:51
@dgozman thx for your reply. 
The page im testing is hosted on the same machine and I never have issues reaching the page.
Im facing "heavy" flickering on Firefox - which I think is related to the issue that Firefox freezes occasionally.
I've tried to set the viewport to 'null' as recommended here (https://github.com/microsoft/playwright/issues/2576). But I think this isn't allowed anymore.

**Comment by dubpal** [comment] 2022-10-24 11:11
I've updated the test machine to win11 22h2 and installed the latest AMD graphics drivers. The firefox stopped flickering and the freeze of the browser isn't reproducible anymore 😀

**Comment by dgozman** [comment] 2022-10-24 16:09
Closing per https://github.com/microsoft/playwright/issues/18004#issuecomment-1275423530.

**Closed by dgozman** 2022-10-24 16:09 UTC
Labels: triaging
