### ISSUE TITLE
[BUG] Non-expected symbols added to text/plain attachments

### ISSUE THREAD

**Issue by cat-ninja** [microsoft/playwright#10630] opened 2021-12-01 08:47 UTC
**Context:**
- Playwright Version: 1.17
- Operating System: Mac OS
- Node.js version: 16.3
- Browser: Chromium

**Code Snippet**
```javascript
// wallet.address is a string
testInfo.attachments.push({
      name: 'address',
      body: wallet.address as any,
      contentType: 'text/plain',
    })

console.log(wallet.address)
```

**Describe the bug**
I'm trying to add an attachment with `contentType: 'text/plain'` to my html report. 
The problem I'm seeing is there are some additional symbols added to my string:
![telegram-cloud-photo-size-2-5275988481706931671-y](https://user-images.githubusercontent.com/17785134/144199793-99046243-7b92-434b-a149-6fb812df6a6c.jpg)

I also tried to use `Buffer.from(wallet.address)` as the body expects to see an instance of the Buffer but all I get is this:
![image](https://user-images.githubusercontent.com/17785134/144200229-6010fda9-38f2-4f64-bd3c-00da20b3c8d4.png)

**Comment by mxschmitt** [comment] 2021-12-01 10:02
This seems related to / duplicate of #10076.

**Comment by pavelfeldman** [comment] 2021-12-08 02:37
Folding into https://github.com/microsoft/playwright/issues/10076

**Closed by pavelfeldman** 2021-12-08 02:37 UTC
Labels: v1.18
