### ISSUE TITLE
[BUG] Scrollbars are not hidden

### ISSUE THREAD

**Issue by Anrb13** [microsoft/playwright#3330] opened 2020-08-06 18:42 UTC
**Context:**
- Playwright Version: @1.2.1
- Operating System: Windows
- Node.js version: v12.18.2
- Browser: WebKit iPhone

scrollbars are not hidden
![2020-08-06T18-33-08 939Z_iphone](https://user-images.githubusercontent.com/53814667/89569560-939eb080-d82d-11ea-99d1-7829a67da71d.jpeg)
![2020-08-06T18-16-49 254Z_iphone](https://user-images.githubusercontent.com/53814667/89569565-94374700-d82d-11ea-8a8d-c7d4d48e17b4.jpeg)
![2020-08-06T18-30-24 798Z_iphone](https://user-images.githubusercontent.com/53814667/89569570-94cfdd80-d82d-11ea-9a05-dcc4f3abfc92.jpeg)
![2020-08-06T18-32-21 374Z_iphone](https://user-images.githubusercontent.com/53814667/89569572-95687400-d82d-11ea-8c48-5e046b900b9c.jpeg)

**Comment by Anrb13** [comment] 2020-08-06 19:15
same at desktop
![2020-08-06T19-12-34 972Z_webkit_EMPTY_A1_VAR](https://user-images.githubusercontent.com/53814667/89572795-4d981b80-d832-11ea-981a-d5835835a34a.jpeg)
![2020-08-06T19-12-34 972Z_webkit_EMPTY_A2_VAR](https://user-images.githubusercontent.com/53814667/89572798-4ec94880-d832-11ea-9420-b103b019c8fe.jpeg)

**Comment by yury-s** [comment] 2020-08-10 16:02
@Anrb13 can you share you code snippet? I tried to reproduce it with the following code in Playwright 1.2.1 and 1.3.0:

```js
const { webkit, devices } = require('playwright');
const iPhone11 = devices['iPhone 11'];

(async () => {
  const browser = await webkit.launch({
     headless: false,
  });
  const context = await browser.newContext({
    ...iPhone11,
    locale: 'ru-RU',
  });
  const page = await context.newPage();
  await page.goto('https://www.wildberries.ru/');
  await page.screenshot({ path: 'w.png' });
  await browser.close();
})();
```

The result image doesn't contain any scrollbars:
![w](https://user-images.githubusercontent.com/9798949/89803773-1e123900-dae8-11ea-875e-0b5bf0814c45.png)

**Comment by Anrb13** [comment] 2020-08-10 20:30
I tried to localize problem, think its about cookie dat i add in test, but no,
have scrollbars on same code
`const { webkit, devices } = require('playwright');
const iPhone11 = devices['iPhone 11'];

(async () => {
  const browser = await webkit.launch({
     headless: false,
  });
  const context = await browser.newContext({
    ...iPhone11,
    locale: 'ru-RU',
  });
  const page = await context.newPage();
  await page.goto('https://www.wildberries.ru/', { waitUntil: 'networkidle' });
  await page.screenshot({ path: 'w.png' });
  await browser.close();
})();`
![w](https://user-images.githubusercontent.com/53814667/89827937-fe6b2700-db60-11ea-907e-00e5c0ab9e3c.png)
Update playwright to 1.3.0, same result, 
My repo: [](https://github.com/Anrb13/testsm)

**Comment by Anrb13** [comment] 2020-08-10 20:33
AND, your screenshot have whitespace too, wildberries app looks like:
![image](https://user-images.githubusercontent.com/53814667/89828476-c31d2800-db61-11ea-9730-48a79ba1f370.png)

**Comment by yury-s** [comment] 2020-08-10 20:39
@Anrb13 did you attach correct screenshot? I don't see scrollbars on [this image](https://github.com/microsoft/playwright/issues/3330#issuecomment-671574290). The page layout seems a bit off indeed but this is likely a different issue. I'd like to first reproduce the scrollbars problem if it still exists.

**Comment by Anrb13** [comment] 2020-08-10 22:34
https://github.com/Anrb13/testsm - my repo, if it helps,
have issue on desktop/screen.test.js and mobile/screen.test.js
different behavior: scrollbars were cut of, black or not hidden, like on my first message.

**Comment by yury-s** [comment] 2020-08-11 17:28
Thanks for sharing the repo, I managed to reproduce it with the sportmaster site. Looks like the particular state that depends on the cookies is important. This is clearly a bug in the Windows port of WebKit we ship.

![webkit_iPhone 8_EMPTY_A1_VAR](https://user-images.githubusercontent.com/9798949/89928871-4d46aa00-dbbd-11ea-9c7b-7e3b402a215e.jpeg)

**Comment by arjun27** [comment] 2020-09-02 18:41
![Screen Shot 2020-09-02 at 11 40 02 AM](https://user-images.githubusercontent.com/284612/92023165-39e8b380-ed11-11ea-89b4-d7ab7606d23f.png)

Seeing the same behavior on apple.com launched with playwright-cli@0.2.0

**Comment by yury-s** [comment] 2020-09-08 21:29
Should be fixed now.

**Closed by yury-s** 2020-09-08 21:29 UTC
Labels: v1.4
