### ISSUE TITLE
[Question] is there a way to ensure webkit waits a little bit longer than other engines?

### ISSUE THREAD

**Issue by Balky79** [microsoft/playwright#12080] opened 2022-02-14 17:20 UTC
Hi, 

I'm planning to use Playwright for our E2E tests. 

On the website (I can't post screenshots due to professional reasons, sadly), there is a silly animation that brings up login modal, and renders logo in SVG with 2 fields and a button (username, password, submit - classic).

In order to "wait" for things to be loaded, stable, animations over - I click into the "username" field, I even wait for network activities (not that it matters, those are probably done faster than animation itself):

```
test.only('should be visually the same as previous version',async ({ page, browserName }) => {
        await page.locator('id=1-email').click();
        await page.waitForLoadState('networkidle');
        let landed_img = await page?.screenshot({ path: join('screenshots', `landed-${browserName}.png`), fullPage: true });
        expect(landed_img).toMatchSnapshot(`landing-${browserName}.png`);
      
    })
```

For Chrome and FF this seems ok, and working fine, but for webkit/Safari it seems like SVG animation is lagging, so the screenshot taken on webkit has a weird sublayer, like "previous position" of the logo with lower opacity and 50% transparency, like a bad shadow under the actual logo position. 

![image](https://user-images.githubusercontent.com/18532205/153913777-543872eb-f92c-4c7a-b375-8407e745e788.png)

(Above is final destination, below is the shadow). 

How do I force webkit/safari to wait a tiny bit longer? how do I add some  more stability to it?

Thanks,
I

**Comment by dgozman** [comment] 2022-02-14 22:02
@Balky79 Is there any change you can share just the svg animation itself? We'd love to help, but we need a repro.

**Comment by Balky79** [comment] 2022-02-14 22:58
Unfortunately no, legalities, third party client... It's a logo with a brand name, so can't do that. 

But, I'll try to swap it locally for some random SVG and see if I can reproduce the same.

**Comment by mxschmitt** [comment] 2022-02-21 17:47
@Balky79 any change for a repro? If not, we'd have to close it since we can't act on it.

**Comment by mxschmitt** [comment] 2022-02-25 10:48
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.

**Closed by mxschmitt** 2022-02-25 10:48 UTC
Labels: triaging
