### ISSUE TITLE
[BUG] Locator value using .filter method raised twice in Traceback on AssertionError.

### ISSUE THREAD

**Issue by mecklena** [microsoft/playwright#19910] opened 2023-01-05 22:23 UTC
**Context:**
- Playwright Version: 1.29.1
- Operating System: macOS Ventura 13.1
- Node.js version: N/A; 
- Python version: 3.10.5
- Browser: [All]
- Extra: [platform darwin -- Python 3.10.5, pytest-7.2.0, pluggy-1.0.0, playwright 1.29.1
configfile: pyproject.toml
plugins: xdist-2.5.0, playwright-0.3.0, forked-1.4.0, html-3.2.0, base-url-2.0.0, dotenv-0.5.2, repeat-0.9.1, metadata-2.0.4]

```
from playwright.sync_api import Page, expect

def test_show_bug(page: Page):
    page.goto("https://playwright.dev/python/docs/intro")
    expect(page.locator("[class='language-bash codeBlockContainer_Ckt0 theme-code-block']").filter(has_text="I love Playwright! I do!")).to_be_visible()
```
<img width="993" alt="Screenshot 2023-01-05 at 4 18 04 PM" src="https://user-images.githubusercontent.com/107941296/210891279-57143735-95bb-4a9d-8777-17087156ddb1.png">

**Comment by mxschmitt** [comment] 2023-01-06 10:29
We made improvements recently which get released with Playwright 1.30. Then it looks like that:

```txt
    def test_show_bug(page: Page):
        page.goto("about:blank")
>       expect(page.locator("input2")).to_be_visible()
E       AssertionError: Locator expected to be visible
E       Actual value: None 
E       Call log:
E       LocatorAssertions.to_be_visible with timeout 5000ms
E       waiting for locator("input2")
E         unexpected value "hidden"
E       waiting for locator("input2")
E         unexpected value "hidden"
E         unexpected value "hidden"
E         unexpected value "hidden"
E         unexpected value "hidden"
E         unexpected value "hidden"
E         unexpected value "hidden"
E         unexpected value "hidden"
E         unexpected value "hidden"
```

would that work for you?

**Comment by mecklena** [comment] 2023-01-07 00:24
Why is this displayed twice in your example?  I would expect to see it only once.
```
E       waiting for locator("input2")
E         unexpected value "hidden"
E       waiting for locator("input2")
E         unexpected value "hidden"
```

**Comment by mxschmitt** [comment] 2023-01-11 19:31
This is as designed, you can set ``DEBUG=pw:api` to see these logs live or use Playwright Inspector, there you can use it to identify when the actual request to the page aka. the check/assertion was performed.

**Closed by mxschmitt** 2023-01-11 19:31 UTC
Labels: v1.31
