### ISSUE TITLE
webkit browser returns additional line feed with innerText on certain elements

### ISSUE THREAD

**Issue by VaasRamsay** [microsoft/playwright#7698] opened 2021-07-18 05:41 UTC
### Playwright version

1.12.3

### Operating system

MacOS

### What browsers are you seeing the problem on?

WebKit

### Other information

macOS 10.15.7
node v12.20.0

### What happened? / Describe the bug

On webkit browser, when grabbing `innerText` additional line feed is added at the end. This happens on parent elements, not on children holding the text directly. 

```
<button class="MuiButton-containedPrimary">
   <span class="MuiButton-label">Primary</span>
</button>
```
In this example, `innerText` on `span` return the text properly, while grabbing `innerText` from the parent `button` adds an extra line feed at the end. 

### Code snippet to reproduce your bug

```shell
const playwright = require('playwright');
(async () => {
    const browser = await playwright['webkit'].launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('https://material-ui.com/components/buttons/');
    await page.waitForSelector('text=Buttons allow users to take actions, and make choices, with a single tap');
    const buttonLabel = await page.$(`.MuiButton-containedPrimary .MuiButton-label`);
    console.log(await buttonLabel.innerText()); // <-- Prints "PRIMARY"
    const button = await page.$(`.MuiButton-containedPrimary`);
    console.log(await button.innerText()); // <-- Prints "PRIMARY \n" additional line feed at the end
    await browser.close();
})();
```

**Comment by mxschmitt** [comment] 2021-07-18 07:08
Sounds like a duplicate of https://github.com/microsoft/playwright/issues/5478. So using textContent() instead should fix it.

**Comment by VaasRamsay** [comment] 2021-07-18 09:38
Thanks. `textContent` messes up multi-line text, hence I rely on `innerText`.

**Comment by aslushnikov** [comment] 2021-07-19 16:13
@VaasRamsay `innerText` is a WebAPI and this is how it works in Safari. If you think it's a bug, please file over to WebKit bug tracker at https://bugs.webkit.org/

**Comment by pavelfeldman** [comment] 2021-07-19 22:34
Yes, this is expected to be browser-specific. That's why we did Playwright!

**Closed by pavelfeldman** 2021-07-19 22:34 UTC
Labels: triaging
