### ISSUE TITLE
[Feature] Make video rewindable in Html report

### ISSUE THREAD

**Issue by Kremliovskyi** [microsoft/playwright#10647] opened 2021-12-01 14:41 UTC
It would be convenient to rewind video back and force to see the issue. Now it is required to download video to do so. Allure report support this, would be nice to have it in Html report.

**Comment by mxschmitt** [comment] 2021-12-01 15:02
Seems like a duplicate of #10333. Could you please install `npm install @playwright/test@next`? Thanks!

**Comment by mxschmitt** [comment] 2021-12-01 17:25
Closing then, since it's fixed and gets released in 1.18 next month.

**Closed by mxschmitt** 2021-12-01 17:25 UTC
Labels: triaging
