### ISSUE TITLE
[Question]Core.xxxx files, are they chromium dump files? How can we disable it?

### ISSUE THREAD

**Issue by wispxjtu** [microsoft/playwright#9704] opened 2021-10-22 08:51 UTC
We're using Playwright official docker image and deploy our node JS application in it, every time this application recieve an request, it start a chromium browser instance and close it before send back response. After run several days, we found several core files(several KB ~ several GB) generated in application root directory, our disk space exhausted by these files.
Our questiones,
1. Are they chromium dump files? I checked chromium documents but seems chromium dump file always ends with dmp extension.
2. How can we disable them? 

Docker image version: playwright:v1.10.0-bionic
Chromium start arguments
    args: [
        '--single-process', 
        '--no-zygote',
        '--no-sandbox'
    ]

Thanks for your time, any comments would be appreciated.

**Comment by wispxjtu** [comment] 2021-11-01 01:43
Could you please help us on this issue? @aslushnikov @mxschmitt

**Comment by mxschmitt** [comment] 2021-11-01 08:14
Do you have a full reproducible for us (script, repo, or e.g. Docker container)? Is it reproducible for you every time?

**Comment by mxschmitt** [comment] 2021-11-07 16:38
Closing since we can't reproduce it. If you have a reproducible / code for us which demonstrates the bug. Or websites which generate these files, let us know and create a new issue. Thanks!

**Closed by mxschmitt** 2021-11-07 16:38 UTC
Labels: triaging

**Comment by colinsarah** [comment] 2022-11-29 07:15
> Our node application is an Express application, these files are generated in the project root directory.
> 
> We can have a try to use latest version.

I also meet this question, node generate som core.xxxx file under root dictory  in docker container.
gdb -c core.xxx,  console Core was generated by `/usr/local/lib/python3.8/site-packages/playwright/driver/node /usr/local/lib/py'.

playwright:1.27.0
Chromium 90.0.4430.212
