### ISSUE TITLE
Playwright Test Generator Custom HTML Attribute

### ISSUE THREAD

**Issue by maneeshjapa** [microsoft/playwright#16273] opened 2022-08-04 21:59 UTC
Can playwright test generator be configured to look for specific HTML attribute as precedence and record it?

Example : If my web page has an input field with attribute myId like:  <input myId="MyProject.Data.Username" placeholder="Username"/>

Can I configure test generator to look for myId attribute and generate a step as:
await page.FillAsync("//*[@myId='MyProject.Data.Username']", "My Text");

**Comment by mxschmitt** [comment] 2022-08-05 08:17
Sounds similar or a duplicate of https://github.com/microsoft/playwright/issues/9015.

**Closed** 2022-08-06 18:58 UTC
Labels: triaging
