### ISSUE TITLE
[BUG] Electron launch `recordVideo` causes timeout only on windows

### ISSUE THREAD

**Issue by dan-cooke** [microsoft/playwright#26648] opened 2023-08-23 10:11 UTC
### System info
- Playwright Version: 1.36.2
- Operating System: Windows
- Browser: All

### Source code

- [ x] I provided exact source code that allows reproducing the issue locally.

This test will not run on Windows
```.ts
import {
  test,
  expect,
  _electron as electron,
  Page,
  ElectronApplication,
} from '@playwright/test';
import path from 'path';

test.describe('Uptime Reporting', () => {
  let page: Page;
  let electronApp: ElectronApplication;

  test.beforeAll(async () => {
    electronApp = await electron.launch({
      args: [
        path.join(__dirname, '..', 'release', 'app', 'dist', 'main', 'main.js'),
      ],

      recordVideo: {
        dir: path.join(__dirname, '..', 'playwright-videos'),
        size: {
          width: 1280,
          height: 720,
        },
      },
    });

    page = await electronApp.firstWindow();

    await page.reload();

    page.on('console', console.log);
  });

  test.afterAll(async () => {
    await electronApp.close();
  });
});

```

**Config file**

```js
// eslint-disable-next-line
import { defineConfig } from '@playwright/test';

import dotenv from 'dotenv';

dotenv.config();

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  testDir: './tests',
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,

  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [['json', { outputFile: 'test-results/results.json' }], ['html']],

  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // THIS does not work on eletron, as we do not have a projects array
    baseURL: 'http://127.0.0.1:1212',

    video: 'on',

    contextOptions: {
      // this is just not working for us idk why
      recordVideo: {
        dir: 'playwright-videos',
      },
    },

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */

    trace: 'on-first-retry',
  },

  /* Configure projects for major browsers */

  /* Run your local dev server before starting the tests */
  webServer:
    process.env.NODE_ENV === 'development'
      ? {
          command: 'npm run start:playwright',
          url: 'http://127.0.0.1:1212',
          reuseExistingServer: false,
        }
      : undefined,
});

```

**Steps**
- Run the test from above

**Expected**
It should not hang

[Describe expected behavior]

**Actual**
It hangs

## Workaround
If you remove the `recordVideo` option this test runs perfectly fine on Windows, so there is an issue with this option. 
There is no issue on linux or mac with the record video option

**Comment by yury-s** [comment] 2023-08-23 17:04
Please provide full self-contained repro (including main.js, package.json with the server command definition etc) that we could launch locally and see the problem.

**Comment by dan-cooke** [comment] 2023-08-23 17:05
@yury-s i have not had a chance to create a reproduction repro but this is the case with any electron app I have tested

**Comment by yury-s** [comment] 2023-08-23 17:48
I appreciate the information you've provided about the issue occurring with any Electron app you've tested. Unfortunately, we won't be able to proceed on this without a specific reproduction repository (this will allow us to closely replicate the environment and conditions you're experiencing).

**Comment by dan-cooke** [comment] 2023-08-23 18:10
@yury-s i will attempt to get a reproduction repo for you when I get a chance

**Comment by yury-s** [comment] 2023-08-28 16:00
We need a repro to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by rafael-anachoreta** [comment] 2023-10-13 18:07
@yury-s this is the same thing I reported in https://github.com/microsoft/playwright/issues/20575#issuecomment-1761901376

Here are the steps to reproduce (tested against `"@playwright/test": "1.39.0"`)

```JavaScript
const findExecutablePath = () => {
 // path to your executable
 return "MyElectronApp.app/Contents/MacOS/MyElectronApp"
}

test.describe('Record Video bug', () => {
  test('Works when recordVideo is not set', async ({ playwright }) => {
    const electronApp = await playwright._electron.launch({
      executablePath: findExecutablePath(),
    })

    console.log('Before firstWindow()', electronApp.windows().length)
    await electronApp.firstWindow()
    console.log('After firstWindow()', electronApp.windows().length)
  })

  test('Hangs when recordVideo is set', async ({ playwright }) => {
    const electronApp = await playwright._electron.launch({
      executablePath: findExecutablePath(),
      recordVideo: {
        dir: 'test-results/videos',
      },
    })

    console.log('Before firstWindow()', electronApp.windows().length)
    await electronApp.firstWindow()
    console.log('After firstWindow()', electronApp.windows().length)
  })
})
```

Could you kindly re-open this issue? 🙏

**Comment by stpsomad** [comment] 2023-11-20 08:05
having the same issue.

**Comment by baparham** [comment] 2023-12-15 15:02
See if this reproduces for you @yury-s https://gist.github.com/baparham/c2b4c2e1771e27bdd7eb5d23033fa5fd

**Comment by baparham** [comment] 2023-12-15 15:03
Not sure if it's exactly the same symptom as the original poster, but certainly a blocker. The electron renderer won't even startup when we specify `recordVideo` in the launch options

**Comment by zhanjinfeng1222** [comment] 2024-01-02 06:08
I have encountered the same issue.

**Comment by mxschmitt** [comment] 2024-02-03 11:53
> See if this reproduces for you yury-s https://gist.github.com/baparham/c2b4c2e1771e27bdd7eb5d23033fa5fd

I'm unfortunately not able to reproduce using this code. Both test-cases pass for me on Windows.

**Comment by mxschmitt** [comment] 2024-02-15 09:02
Closing as per above. Please re-file with a reproduction if you still encounter this issue in the latest Playwright version.

**Closed by mxschmitt** 2024-02-15 09:02 UTC
Labels: feature-electron, v1.43

**Comment by MatthijsvBoven** [comment] 2024-11-27 07:00
npx playwright install chromium fixed the issue for me.

**Comment by mxschmitt** [comment] 2024-12-06 17:54
I filed an issue for it here: https://github.com/microsoft/playwright/issues/33899 / `npx playwright install ffmpeg` seems to be the recommendation. The issue is that it hangs for now instead of throwing.
