### ISSUE TITLE
[BUG] `uncheck` action fails, but `check` succeeds on same element

### ISSUE THREAD

**Issue by aldeed** [microsoft/playwright#6850] opened 2021-06-02 15:33 UTC
**Context:**
- Playwright Version: 1.10.0
- Operating System: Linux
- Node.js version: 14.17.0
- Browser: All

**Code Snippet**

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto('https://v2.grommet.io/checkbox');
  await page.check('[type="checkbox"]');
  await page.uncheck('[type="checkbox"]');
})();
```

**Describe the bug**

The `uncheck` fails, seemingly due to actionability checks, even though the `check` immediately preceding succeeds. It is an invisible (0 width and height) `input[type=checkbox]`, but because check/uncheck only work on the input element, there is no choice but to target the invisible underlying element.

Adding `force` does not help (just fails sooner).

I realize this is a tricky area, but for check/uncheck to be useful, I think they should both work on visually hidden inputs like this. I'm not sure how click area can be determined, or if you just programmatically update the `checked` prop when it's hidden, but if it's working for `check` then it should be possible for `uncheck`?

EDIT:

Forgot to include error message:

```
page.uncheck: Timeout 30000ms exceeded. waiting for selector "[type="checkbox"]" selector resolved to hidden <input checked type="checkbox" class="StyledCheckBox__S…/> attempting click action waiting for element to be visible, enabled and stable element is not visible - waiting...
```

**Comment by pavelfeldman** [comment] 2021-06-02 15:58
The reason `check` works is that it queries the input state and it is already checked, so it does nothing. But when you try to `uncheck` it, it waits for the input to become visible, which never happens. Since what we see isn't really a checkbox, but is rather a div with svg, you can't use `check` on it. You can click though.

**Comment by aldeed** [comment] 2021-06-02 16:10
@pavelfeldman Oh right that makes sense. Then I guess the bug is that neither check nor uncheck work properly. For more real world (component library) situations, I think they would either need to ignore visibility, or you'd have to relax the requirement that the selector point to an `input`. Maybe targeting visible selectors with checkbox or radio descendants should be okay?

**Comment by pavelfeldman** [comment] 2021-06-02 19:08
I'd say things are working as intended. Playwright is an end-to-end testing framework - it can only interact with the elements that are visible. If Playwright is told to check a checkbox and that checkbox is missing in the UI, that's a bug that Playwright found.

There are couple of ways to fix your scenario. One would be to make your control accessible and assign aria state to your svg artwork (`aria-checked`). Then you can `page.check` the artwork itself, because you told browser that it is a checkbox. Second would be to programmatically check it with `page.$evaluate('input', input => input.checked = true)` if you you are fine with users checking controls that are missing in the screen.

**Comment by aldeed** [comment] 2021-06-03 19:21
@pavelfeldman That seems fine as a design choice. I looked into Material UI React checkbox, and they make the input fill the width and height, but it is just hidden behind the visible SVG or div. Doing it this way allows check/uncheck to work, so maybe Grommet needs to move more in that direction. (btw I don't think adding `aria-checked` on svg is wise or necessary when there is already a checkbox input. I didn't test it but I assume that would be interpreted as a second checkbox.)

If you don't see any changes needed here, feel free to close.

**Comment by dgozman** [comment] 2021-06-07 21:11
Seems like there is no action item here, closing.

**Closed by dgozman** 2021-06-07 21:11 UTC
Labels: triaging
