### ISSUE TITLE
[Bug]:  With playwright test, an 'expect' fail causes beforeAll to re-run

### ISSUE THREAD

**Issue by GwynDavies** [microsoft/playwright#7554] opened 2021-07-12 04:56 UTC
### Playwright version

1.12.3

### Operating system

Windows

### Other information

Node = v14.17.3
NPM/NPX = 7.18.1

### What happened? / Describe the bug

Issue:
    With playwright test, the hook test.beforeAll, is getting run more than once.

Expecting:
    I was expecting the beforeAll hook to run only once

More info:

This happens when a test 'expect' fails, otherwise the test.beforeAll runs just once, as expected.

I attached a mocked example below, to try and demonstrate. It simply adds the 3 test names to an array - created in beforeAll.

If you run it :
    > npx playwright test
... then you see that **test.beforeAll** **runs twice**, the array gets reset - leaving only the 3rd test name to be recorded

If in 'Test2' you fix the expect to pass, the **test.beforeAll hook runs just once,** and you get the 3 test names

Thanks-

### Code snippet to reproduce your bug

```shell
const { test, expect } = require("@playwright/test");

console.log("SCRIPT STARTED");

let testsRun;

test.beforeAll(() => {
  console.log("****** test.beforeAll called ...");
  testsRun = [];
});

test.afterAll(() => {
  testsRun.forEach((element) => console.log(element));
});


test.beforeEach(async ({ page }, testInfo, browserContext) => {
  console.log("******         test.beforeEach called ...");
});

test.afterEach(async ({ page }, testInfo, browserContext) => {
  console.log("******         test.afterEach called ...");
  testsRun.push(await testInfo.title);
});


test("Test1", async ({ page }) => {
  console.log("******     Test1 called ...");
  expect(1).toBe(1);
});

test("Test2", async ({ page }) => {
  console.log("******     Test2 called ...");
  // Cause a fail here
  expect(1).toBe(2);
});

test("Test3", async ({ page }) => {
  console.log("******     Test3 called ...");
  expect(1).toBe(1);
});
```

### Relevant log output

```shell
>npx playwright test

SCRIPT STARTED

Running 3 tests using 1 worker

SCRIPT STARTED
****** test.beforeAll called ...                                 <-----------beforeAll called
  ✓ tests\has_beforeall.spec.js:27:1 › [chromium] Test1 (676ms)

******         test.beforeEach called ...
******     Test1 called ...
******         test.afterEach called ...
  x 1) tests\has_beforeall.spec.js:32:1 › [chromium] Test2 (131ms)

******         test.beforeEach called ...
******     Test2 called ...
******         test.afterEach called ...

SCRIPT STARTED
****** test.beforeAll called ...                                 <-----------beforeAll called again?
  ✓ tests\has_beforeall.spec.js:38:1 › [chromium] Test3 (661ms)
******         test.beforeEach called ...     
                  
******     Test3 called ...
******         test.afterEach called ...
Test3                                            <---- only records one test, as the array was reset


  1) tests\has_beforeall.spec.js:32:1 › [chromium] Test2 ===========================================

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: 2
    Received: 1

      33 |   console.log("******     Test2 called ...");
      34 |   // Cause a fail here
    > 35 |   expect(1).toBe(2);
 ...
  1 failed
    tests\has_beforeall.spec.js:32:1 › [chromium] Test2 ============================================
  2 passed (3s)


###################################################
Now fix the expect clause, to pass in Test2
  Change expect(1).toBe(2);
  To expect(1).toBe(1);
###################################################

Now the tests all run as expected, with beforeAll called just once ...

>npx playwright test

SCRIPT STARTED

Running 3 tests using 1 worker

SCRIPT STARTED
****** test.beforeAll called ...                     <----- Called just once now
  ✓ tests\has_beforeall.spec.js:27:1 › [chromium] Test1 (628ms)

******         test.beforeEach called ...
******     Test1 called ...
******         test.afterEach called ...
  ✓ tests\has_beforeall.spec.js:32:1 › [chromium] Test2 (128ms)

******         test.beforeEach called ...
******     Test2 called ...
******         test.afterEach called ...
  ✓ tests\has_beforeall.spec.js:38:1 › [chromium] Test3 (133ms)

******         test.beforeEach called ...
******     Test3 called ...
******         test.afterEach called ...
Test1
Test2
Test3

  3 passed (2s)
```

**Comment by mxschmitt** [comment] 2021-07-12 11:20
The reason behind that behaviour is that when a test is failing, Playwright Test does run the rest of the test in a new worker, to ensure a clean state etc.

Are you running into any issues caused by that behaviour?

**Comment by GwynDavies** [comment] 2021-07-12 15:25
Okay that explains things. I will work to isolate the setup, so it is not affected by the starting of the new worker on a test fail

**Comment by mxschmitt** [comment] 2021-07-12 15:48
Closing then, thanks for confirming. 👍

**Closed by mxschmitt** 2021-07-12 15:48 UTC
Labels: triaging
