### ISSUE TITLE
[REGRESSION]: Blank screenshots on mobile Safari (Webkit) since v1.15.1

### ISSUE THREAD

**Issue by z0n** [microsoft/playwright#9429] opened 2021-10-11 13:55 UTC
**Context:**
- GOOD Playwright Version: 1.15.0
- BAD Playwright Version: 1.15.1
- Operating System: Linux (Docker)

**Code Snippet**
https://github.com/z0n/playwright-webkit-screenshot

Run `yarn test:playwright`.

**Describe the bug**

Since v1.15.1 (and also v1.15.2), this test fails as the screenshots Playwright takes are blank in mobile Safari/Webkit. Mobile Chrome still works fine. You'll see the issue once you run `yarn test:playwright` in the mentioned repo and check the `test-results` folder afterwards.

If you then set the Playwright version to 1.15.0 in the `docker-compose.yml` and `package.json` files, the test will pass again.

Maybe I made a mistake somewhere in my code, it's working in 1.15.0 though 😄

**Comment by z0n** [comment] 2021-10-11 18:41
> 
> 
> Can you provide a simple repro that wouldn't require docker-compose (just a test that fails in docker?), I'm getting 'ERROR: Version in "./docker-compose.yml" is unsupported." when running your example?

If you still want to try it in Docker, you could probably set the version in the docker-compose file to something your local docker-compose supports, `3` will probably work. I didn't test it on Linux directly but it seems like you're good 😄

**Comment by yury-s** [comment] 2021-10-15 15:04
@z0n it'd be very helpful if you could create a standalone page where this reproduces. The author of the webkit patch that regressed this says that he just restored previous behavior which had been broken before (likely long ago since it's not reproducible with recent webkit builds) so it will require further investigation.

**Comment by pavelfeldman** [comment] 2022-10-20 03:03
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-10-20 03:03 UTC
Labels: browser-webkit, P3-collecting-feedback
