### ISSUE TITLE
[BUG] Error: page.setInputFiles: Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by yesgs** [microsoft/playwright#6266] opened 2021-04-22 10:46 UTC
**Context:**
- Playwright Version: [1.10.0]
- Operating System: [Linux]
- Node.js version: [14.10.0]
- Browser: [Chromium]
- Extra: []

**Code Snippet**

Generate a 400M large file

````shell
dd if=/dev/zero of=/tmp/400M bs=1M count=400
````

```javascript
const { chromium } = require("playwright");


const dataPath='/tmp/400M';

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.setContent(
    '<input type="file" name="fileToUpload" id="fileToUpload">'
  );
  await page.setInputFiles("input", dataPath);

  await browser.close();
})();
```

**Describe the bug**
Can't upload a large file(about 400MB).

```shell

  pw:api => browserType.launch started +0ms
  pw:api <= browserType.launch succeeded +85ms
  pw:api => browser.newContext started +0ms
  pw:api <= browser.newContext succeeded +3ms
  pw:api => browserContext.newPage started +0ms
  pw:api <= browserContext.newPage succeeded +20ms
  pw:api => page.setContent started +1ms
  pw:api setting frame content, waiting until "load" +1ms
  pw:api   navigated to "about:blank" +4ms
  pw:api <= page.setContent succeeded +13ms
  pw:api => page.setInputFiles started +0ms
  pw:api <= page.setInputFiles failed +1s
(node:25801) UnhandledPromiseRejectionWarning: Error: page.setInputFiles: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (buffer.js:653:37)
    at Buffer.toString (buffer.js:801:14)
    at /home/king/Desktop/wifi/node_modules/playwright/lib/client/elementHandle.js:280:77
    at async Promise.all (index 0)
    at async Object.convertInputFiles (/home/king/Desktop/wifi/node_modules/playwright/lib/client/elementHandle.js:275:26)
    at async /home/king/Desktop/wifi/node_modules/playwright/lib/client/frame.js:366:60
    at async Frame._wrapApiCall (/home/king/Desktop/wifi/node_modules/playwright/lib/client/channelOwner.js:77:28)
    at async /home/king/Desktop/wifi/index2.js:12:3
(Use `node --trace-warnings ...` to show where the warning was created)
(node:25801) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25801) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by dgozman** [comment] 2021-04-22 15:28
Duplicate of #3768.

**Closed by dgozman** 2021-04-22 15:28 UTC
