### ISSUE TITLE
[Feature]: Hovering over the timeline in a trace illustrates a blurry image.

### ISSUE THREAD

**Issue by shtlrs** [microsoft/playwright#9172] opened 2021-09-27 11:07 UTC
**Context:**
- GOOD Playwright Version: [what Playwright version worked nicely?] 1.14
- BAD Playwright Version: [what Playwright version doesn't work any more?] 1.15
- Operating System: [e.g. Windows, Linux or Mac] Windows

**Describe the bug**

When hovering over the timeline in a trace, the image appears blurry.

Here's an example of a trace where the image appears blurry.
[trace.zip](https://github.com/microsoft/playwright/files/7235725/trace.zip)
.
**Note**
When you click on one of the actions, the image appears nice & clear.

**Comment by dgozman** [comment] 2021-09-27 16:07
@shtlrs I see you use `viewport: { width: 1920, height: 1080 }`. We default to 800x600 timeline thumbnails, so it is a bit blurry. 

I am running the following script with v1.14.1 and v1.15 and I get the same result - equally blurry images. Are you sure this is a regression? Could you please attach the trace produced by v1.14?

```js
const { chromium } = require('@playwright/test');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext({
    viewport: { width: 1920, height: 1080 },
  });
  await context.tracing.start({ screenshots: true, snapshots: true });
  const page = await context.newPage();

  await page.goto('https://appdev.expensya.com/Portal/#/Login');
  await context.tracing.stop({ path: 'trace.zip' });

  await browser.close();
})();
```

**Comment by shtlrs** [comment] 2021-09-28 07:21
@dgozman Now that I tested it with v1.14, I'm not sure it's a regression anymore.
Because the images are very small in v1.14's traceviewer so I can't really see.

Is there a solution for this ?

**Comment by dgozman** [comment] 2021-09-28 16:00
To reiterate, you probably want higher-resolution thumbnails in the timeline. There is a performance vs quality trade off here. Perhaps we can introduce some kind of setting here, but there is no workaround currently.

**Comment by shtlrs** [comment] 2021-09-29 07:20
I see.
It's a bit strange when you look at it as a blackbox because the snapshots that we see when clicking on the actions are very clear, but I don't how it works on the inside so I can't say much.
Shall we close this then ?

**Comment by dgozman** [comment] 2021-09-29 16:03
There is a difference between screenshots (at the top timeline) and snapshots (below, for each action):
- Screenshots are images from the page. They are always accurate (as the user would see it) but lower quality.
- Snapshots are live DOM replicas. You can open DevTools and inspect elements in the snapshot.

We have [some documentation](https://playwright.dev/docs/trace-viewer#snapshots), but I think the difference is not expressed clearly.

**Comment by shtlrs** [comment] 2021-09-30 10:28
Understood, thanks for the explanation Dmitry !

**Comment by pavelfeldman** [comment] 2022-10-20 03:18
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-10-20 03:18 UTC
Labels: P3-collecting-feedback, feature-trace
