### ISSUE TITLE
[BUG] Playwright-core - page.waitForEvent: Timeout 30000ms exceeded 

### ISSUE THREAD

**Issue by osmenia** [microsoft/playwright#3726] opened 2020-09-02 10:42 UTC
**Context:**
- Playwright Version: 1.3.0
- Operating System: AWS Lambda
- Node.js version: 12
- Browser: [Chromium]
- Extra: playwright-aws-lambda

Hi Team, 

I am testing playwright-core with AWS lambda.

there is problem with page.waitForEvent("download") in playwright-code 1.3.0.

page.waitForEvent("download") works fine with playwright-code 1.0.2 but with playwright-code 1.3.0 does not. 

Error: 

  "TimeoutError: page.waitForEvent: Timeout 30000ms exceeded.",
        "Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.",
        "    at ProgressController.run (/opt/node_modules/playwright-core/lib/progress.js:71:30)",
        "    at Page.waitForEvent (/opt/node_modules/playwright-core/lib/page.js:243:35)",
        "    at Page.waitForEvent (/opt/node_modules/playwright-core/lib/helper.js:80:31)",

**Code Snippet**

```javascript
 await page.goto(
    "https://file-examples.com/index.php/sample-documents-download/sample-xls-download/"
  );

  const handles = await page.$$("#table-files .file-link");

  for (let num of handles) {
    const [download] = await Promise.all([
      page.waitForEvent("download"), // wait for download to start
      num.click("a.btn"),
    ]);
    const path = await download.path();
}
```

**Comment by mxschmitt** [comment] 2020-09-05 13:28
Since num is a ElementHandle, the click method does not accept a new selector. You have to use `$` to get the new element to click on it.

Example:

```js
// @ts-check
const playwright = require("playwright");

(async () => {
  const browser = await playwright.chromium.launch()
  const context = await browser.newContext({
    acceptDownloads: true
  })
  const page = await context.newPage()
  await page.goto(
    "https://file-examples.com/index.php/sample-documents-download/sample-xls-download/"
  );

  const handles = await page.$$("#table-files .file-link");

  for (let num of handles) {
    const [download] = await Promise.all([
      page.waitForEvent("download"), // wait for download to start
      (await num.$("a.btn")).click(),
    ]);
    const path = await download.path();
    console.log(path)
  }
  await browser.close();
})();
```

Interactive: https://try.playwright.tech/?s=gd4r9

**Comment by osmenia** [comment] 2020-09-07 11:44
Hi Max, 

Thanks you very much for your help. 

I tried you solution, it did not work on aws lambda with playwright-core 1.3.0, but with PLW 1.0.2 works fine. 

@mxschmitt  is it possible to test playwright-core local?

**Comment by dgozman** [comment] 2020-10-01 07:38
Have you tried running with `DEBUG=pw:api,pw:browser*` environment variable and post the logs here? This seems like an AWS lambda specific issue.

**Comment by osmenia** [comment] 2020-10-01 14:02
@dgozman 
To be honest, i do not know how to run `DEBUG=pw:api,pw:browser*` on aws.

**Comment by dgozman** [comment] 2020-10-01 14:25
> @dgozman
> To be honest, i do not know how to run `DEBUG=pw:api,pw:browser*` on aws.

I think this should be possible directly in Node, if you use javascript lambda:

```js
// Set the env variable.
process.env.DEBUG = 'pw:api,pw:browser*';
// Use playwright.
const browser = await require('playwright').chromium.launch({});
```

**Comment by jknooks583** [comment] 2020-10-01 19:15
@osmenia Just out of curiosity, is this working fine locally and just not working with AWB lambda?

**Comment by osmenia** [comment] 2020-10-01 19:22
@jknooks583 

Yes, Code works locally fine. all good 
Code also works fine on AWS Lambda with playwright-code 1.0.2 but with playwright-code 1.3.0 does not (TimeoutError). It is the same code. 

I did not test with playwright-code 1.4

**Comment by jknooks583** [comment] 2020-10-01 21:05
@osmenia Hey just wanted to let you know that I tested with playwright 1.4 and it is working for me if you want to try that out

**Comment by osmenia** [comment] 2020-10-03 20:08
@jknooks583 How did you do test? For me does not work :(

Here ist code:

```
const playwright = require('playwright-aws-lambda');

exports.handler = async(event, context) => {
  let browser = null;

  try {
    const browser = await playwright.launchChromium();
    const context = await browser.newContext({ acceptDownloads: true });
    const page = await context.newPage();

    await page.goto(
      "https://file-examples.com/index.php/sample-documents-download/sample-xls-download/"
    );
    const handles = await page.$$("#table-files .file-link");

    for (let num of handles) {
      const [download] = await Promise.all([
        page.waitForEvent("download"), // wait for download to start
        num.click("a.btn"),
      ]);
      const path = await download.path();
      console.log(path);
    }
  }
  catch (error) {
    throw error;
  }
  finally {
    if (browser !== null) {
      await browser.close();
    }
  }
};

```
**I create Layer with Playwright 1.0.2**

```
package.json
 "author": "",
  "license": "ISC",
  "dependencies": {
    "playwright-aws-lambda": "^0.6.0",
    "playwright-core": "^1.0.2"
  }
```
This is  result:
see Working Download.log file
```

START RequestId: 9c809345-8fa0-492f-8246- Version: $LATEST
2020-10-03T14:48:10.382Z	-8fa0-492f-8246-	INFO	/tmp/playwright_downloads-dcZRq6/f6f9961c-7b52-4250-830d-e0cf49e9f838
2020-10-03T14:48:10.667Z	-8fa0-492f-8246-	INFO	/tmp/playwright_downloads-dcZRq6/48d9a174-8574-4069-8a2b-2ff0ab1182cc
2020-10-03T14:48:10.862Z	-8fa0-492f-8246-	INFO	/tmp/playwright_downloads-dcZRq6/648e89ec-e534-4fce-b093-994031a92004
2020-10-03T14:48:11.249Z	-8fa0-492f-8246-	INFO	/tmp/playwright_downloads-dcZRq6/da7f8dd3-0ad8-496e-b5ff-74e26fa92df1
2020-10-03T14:48:11.422Z	-8fa0-492f-8246-	INFO	/tmp/playwright_downloads-dcZRq6/9cd62ad0-5e38-4740-8e81-dc9e0c2eff90
2020-10-03T14:48:11.598Z	-8fa0-492f-8246-	INFO	/tmp/playwright_downloads-dcZRq6/11f48922-4704-4ff7-9ebe-d8d981e02a0d
2020-10-03T14:48:11.770Z	-8fa0-492f-8246-	INFO	/tmp/playwright_downloads-dcZRq6/1551df6c-10cb-4d8c-83f5-1638ea70b58e
2020-10-03T14:48:11.922Z	-8fa0-492f-8246-	INFO	/tmp/playwright_downloads-dcZRq6/aac320bf-0fd7-461d-9c74-de104cf0382c
2020-10-03T14:48:12.088Z	-8fa0-492f-8246-	INFO	/tmp/playwright_downloads-dcZRq6/2d5f03ce-bb21-4f06-9877-af1d50243abd
2020-10-03T14:48:12.261Z	-8fa0-492f-8246-	INFO	/tmp/playwright_downloads-dcZRq6/c625ad80-f8be-472e-9b39-8bea07fcef11

```
Files are downloaded with playwright 1.0.2. Download works all good.

**I createt Layer with Playwright 1.3.0** 
```
package.json
 "author": "",
  "license": "ISC",
  "dependencies": {
    "playwright-aws-lambda": "^0.6.0",
    "playwright-core": "^1.3.0"
  }
```
  
 **I am getting Error:** 
```
{
  "errorType": "TimeoutError",
  "errorMessage": "page.waitForEvent: Timeout 30000ms exceeded.\nNote: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.",
  "trace": [
    "TimeoutError: page.waitForEvent: Timeout 30000ms exceeded.",
    "Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.",
    "    at ProgressController.run (/opt/nodejs/node_modules/playwright-core/lib/progress.js:71:30)",
    "    at Page.waitForEvent (/opt/nodejs/node_modules/playwright-core/lib/page.js:243:35)",
    "    at Page.waitForEvent (/opt/nodejs/node_modules/playwright-core/lib/helper.js:80:31)",
    "    at Runtime.exports.handler (/var/task/index.js:19:14)"
  ]
}
```
**This is layer with plawright 1.4.0**

```
package.json
 "author": "",
  "license": "ISC",
  "dependencies": {
    "playwright-aws-lambda": "^0.6.0",
    "playwright-core": "^1.4.0"
  }
```
  
`  Error Message:`
```
{
  "errorType": "Error",
  "errorMessage": "elementHandle.click: : expected object, got string",
  "trace": [
    "elementHandle.click: : expected object, got string",
    "    at ElementHandle._wrapApiCall (/opt/nodejs/node_modules/playwright-core/lib/client/channelOwner.js:76:15)",
    "    at ElementHandle.click (/opt/nodejs/node_modules/playwright-core/lib/client/elementHandle.js:89:21)",
    "    at Runtime.exports.handler (/var/task/index.js:20:13)",
    "    at runMicrotasks (<anonymous>)",
    "    at runNextTicks (internal/process/task_queues.js:62:5)",
    "    at processImmediate (internal/timers.js:429:9)"
  ]
}
```

**I replaced "`num.click("a.btn"),`" with "`(await num.$("a.btn")).click(),`" Thanks @mxschmitt **

**Then I got this Error:**

```
{
  "errorType": "TimeoutError",
  "errorMessage": "Timeout while waiting for event \"download\"\nNote: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.",
  "trace": [
    "TimeoutError: Timeout while waiting for event \"download\"",
    "Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.",
    "    at /opt/nodejs/node_modules/playwright-core/lib/client/waiter.js:40:51",
    "    at async Waiter.waitForPromise (/opt/nodejs/node_modules/playwright-core/lib/client/waiter.js:48:28)",
    "    at async Page.waitForEvent (/opt/nodejs/node_modules/playwright-core/lib/client/page.js:285:24)",
    "    at async Promise.all (index 0)",
    "    at async Runtime.exports.handler (/var/task/index.js:18:26)"
  ]
}
```
Please find attached Log Files. @dgozman @mxschmitt
Working Download.log is Log file from plw 1.0.2
Error_Download.log is Log file from plw 1.4.0  
[Working Download.log](https://github.com/microsoft/playwright/files/5322260/Working.Download.log)
[Error_Download.log](https://github.com/microsoft/playwright/files/5322261/Error_Download.log)

**Comment by dgozman** [comment] 2020-11-09 23:30
Sorry for the slow response 😞 I have looked at the logs, and unfortunately I don't see where the problem comes from.

Two ideas:
- Variable `browser` is declared twice (once with `let`, another with `const`), so the `browser.close()` code is never executed. Not sure whether not closing a browser is a problem with AWS lambda.
- Perhaps the site is blocking your IP from repeated access? Some kind of anti-bot protection?
- Maybe more detailed logs would help us, if you are willing to run again with `process.env.DEBUG = 'pw:api,pw:browser*,pw:protocol*';`.

**Comment by dgozman** [comment] 2020-11-23 22:20
Closing because we cannot reproduce and there is no additional information to make progress.

**Closed by dgozman** 2020-11-23 22:20 UTC

**Comment by osmenia** [comment] 2020-11-24 09:47
> Sorry for the slow response 😞 I have looked at the logs, and unfortunately I don't see where the problem comes from.
> 
> Two ideas:
> 
> * Variable `browser` is declared twice (once with `let`, another with `const`), so the `browser.close()` code is never executed. Not sure whether not closing a browser is a problem with AWS lambda.
> * Perhaps the site is blocking your IP from repeated access? Some kind of anti-bot protection?
> * Maybe more detailed logs would help us, if you are willing to run again with `process.env.DEBUG = 'pw:api,pw:browser*,pw:protocol*';`.

Hi Gozman, 
thnx very much
i will test it

**Comment by osmenia** [comment] 2021-01-03 10:10
Hi Team,

first of all I would like to wish you a happy new year!

I am runing code on aws lambda.
Here is code:

```
const playwright = require('playwright-aws-lambda');
 exports.handler = async(event, context) => {
  
  try {
    console.log("Start here -> debug");
    const browser = await playwright.launchChromium();
    const context = await browser.newContext({ acceptDownloads: true });
    const page = await context.newPage();
    await page.goto(
      "https://file-examples.com/index.php/sample-documents-download/sample-xls-download/"
    );
    const handles = await page.$$("#table-files .file-link");
    for (let num of handles) {
      console.log("This is num output ", num);
      const [download] = await Promise.all([
        page.waitForEvent("download"), // wait for download to start
        (await num.$("a.btn")).click(),
      ]);
      const path = await download.path();
      console.log("This is file path: ",path);
    }
    await browser.close();
  }
  catch (error) {
    throw error;
  }
};
```

Config:
```

  "dependencies": {
    "playwright-aws-lambda": "^0.6.0",
    "playwright-core": "^1.7.1"
  }
```
**run with param: process.env.DEBUG = 'pw:api,pw:browser*,pw:protocol*'**

Error: 

`{
  "errorType": "TimeoutError",
  "errorMessage": "Timeout while waiting for event \"download\"\nNote: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.",
  "trace": [
    "TimeoutError: Timeout while waiting for event \"download\"",
    "Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.",
    "    at /opt/nodejs/node_modules/playwright-core/lib/client/waiter.js:40:51",
    "    at async Waiter.waitForPromise (/opt/nodejs/node_modules/playwright-core/lib/client/waiter.js:48:28)",
    "    at async Page.waitForEvent (/opt/nodejs/node_modules/playwright-core/lib/client/page.js:306:24)",
    "    at async Promise.all (index 0)",
    "    at async Runtime.exports.handler (/var/task/index.js:21:26)"
  ]
}`


Please find attached log file.
[Log_AWS_03012021.zip](https://github.com/microsoft/playwright/files/5761426/Log_AWS_03012021.zip)

I tried also with another page with download, did not work on aws. Local works fine.  
```
  await page.goto("https://speed.hetzner.de/");
  const [download] = await Promise.all([
    page.waitForEvent("download"), // wait for download to start
    page.click("body > p:nth-child(2) > a"),
  ]);   const path = await download.path();
  console.log(path);
```
Can you pls help
@dgozman @mxschmitt

**Comment by dgozman** [comment] 2021-01-04 20:59
@osmenia I do not know much about aws lambda environment, but it seems that playwright-aws-lambda does some unzipping of Chromium binary to `/tmp/chromium`. Perhaps you should pass [`downloadsPath`](https://playwright.dev/docs/api/class-browsertype/?_highlight=downloadspath#browsertypelaunchoptions) pointing somewhere in `/tmp`?

**Comment by imhashir** [comment] 2021-01-21 06:12
Any progress here? I am getting the same error. Code is working fine when running locally but not when deployed via `serverless deploy`:
![image](https://user-images.githubusercontent.com/10235172/105286789-c7517500-5bd8-11eb-9131-c9dfe21c90e1.png)

**Comment by imhashir** [comment] 2021-01-22 21:08
@dgozman 
I tried enabling the logs as you suggested above and turns out, the event is not firing up in lambda. I can see the download logs and network activity logs as below:
![image](https://user-images.githubusercontent.com/10235172/105546360-15709080-5d1f-11eb-8fd4-bfdfd104dd80.png)

The download was completed but I did not receive the completion callback. I used two approaches:

- **1st Approach**: 
```
  const [download] = await Promise.all([
    page.waitForEvent('download'),
    page.click(`#${BTN_ID}`),
  ]);
  const downloadStream = await download.createReadStream();
```
Received timeout error

- **2nd Approach**:
```
const downloadFile = async (page, element) => {
  return new Promise((resolve, reject) => {
    page.on('download', (download) => {
      console.log('File downloaded!');
      resolve(download);
    });
    return page.click(element);
  });
};
const download = await downloadFile(page, `#${BTN_ID}`);
```
Did not receive any timeout error and the lambda function kept running, and ultimately, timed out.

I came up with the second approach to check if the on download event is emitted, which isn't. So something's up with the events on lambda. I have a project due, _very soon_, so any urgent help would be really appreciated.

**Comment by dgozman** [comment] 2021-01-26 02:54
@imhashir Thank you for digging into this issue. Looking at `playwright-aws-lambda`'s [built-in chromium](https://github.com/JupiterOne/playwright-aws-lambda/tree/master/src/bin), it seems to be 8 months old. It is quite possible that recent Playwright does not work with downloads of 8-months old Chromium, because the project is quickly evolving. What is your Playwright version?

**Comment by osmenia** [comment] 2021-01-26 08:07
@imhashir 
Try with Playwright Version 1.0.2

**Comment by imhashir** [comment] 2021-01-26 22:13
@dgozman 
Yeah, I suspected that as well. My playwright-core version is `1.8.0`.

@osmenia 
You are legend! Thanks man. I just downgraded to 1.0.2 and it worked both locally and on lambda. I've been stuck at it for days, so glad it worked. I'll try the solution provided on that issuecomment as well, but I'll have to look a bit deeper into docker-lambda thing.

Now the only issue with downgrade approach is that the `suggestedFilename` function is not in `1.0.2`. Is there any workaround for that at the moment?

**Comment by osmenia** [comment] 2021-01-27 05:34
@imhashir 

maybe this can help:

```
.....
  const path = await download.path();

  var data = fs.readFileSync(path);
 
 fs.writeFileSync('../data/helloworld${uuid}.xls', data);
```

**Comment by TheAPIguys** [comment] 2022-11-20 00:04
Hello Guys, 

I having the timeout error as below:
{
  "errorType": "TimeoutError",
  "errorMessage": "page.waitForEvent: Timeout 30000ms exceeded while waiting for event \"download\"\n=========================== logs ===========================\nwaiting for event \"download\"\n============================================================",
  "trace": [
    "page.waitForEvent: Timeout 30000ms exceeded while waiting for event \"download\"",
    "=========================== logs ===========================",
    "waiting for event \"download\"",
    "============================================================",
    "    at Runtime.exports.handler (/var/task/index.js:54:11)"
  ]
}

my version is as follows:
"dependencies": {
        "playwright-aws-lambda": "^0.9.0",
        "playwright-core": "^1.28.0"
      }


there is any way to solve this issue?
