### ISSUE TITLE
[BUG] Difference in behavior for ```page.keyboard.press('Enter')``` depending on how the code is ran. (Javascript with Node.js)

### ISSUE THREAD

**Issue by ReinforcedKnowledge** [microsoft/playwright#26451] opened 2023-08-13 15:15 UTC
Hi!

I have noticed that on two different laptops there is a difference in the behavior of ```page.keyboard.press('Enter')``` depending on how the code is executed. If I execute the code using ```node index.js``` I get a different behaviour,  I get a line break (the wrong one) compared to when I execute the code using the Code Runner extension on VS Code, which submits a form e.g. (the correct behaviour).

The setup that I did:
```
mkdir try_playwright
cd try_playwright
npm init -y
```
Added in the ```package.json```: ```"type": "module"```
Then:
```npm install playwright```

I go to VS Code, create a file ```index.js``` and try this bit of code:
```
import { chromium } from 'playwright';

const browser = await chromium.launch({ headless: false });

const page = await browser.newPage();

await page.goto('https://google.com/');

await page.click('button:has-text("I agree")');

await page.type('textarea[title="Search"]', 'hello world');

await page.keyboard.press('Enter');

await page.waitForTimeout(10000);
await browser.close();
```

So I have tried this on two configurations:
- **macOS Ventura 13.4.1**, Apple M1. **Node**: v20.5.1. **NPM**: 9.8.0
- **Windows 11 64 bits** (10.0, build 22621). **Node**: v18.17.0. **NPM**: 9.8.1

Recap of the behaviours:
- Run with Code Runner extension on VS Code: does exactly what is expected.
- Run with ```node index.js``` command on terminal: types "hello world" in the search bar and then goes to a new line.

Notes:
- ```await page.click('button:has-text("I agree")');``` is only useful is you're in EU. If your browser is in a different language, you should change the "I agree".
- The "Search" title of the text area search bar in Google will vary depending on your browser's language too.
- I have also tried clicking on the text area before entering the "hello world" and pressing "Enter", didn't change the difference in behaviors.

**Comment by mxschmitt** [comment] 2023-08-17 11:43
This looks like a bug on Google rather than a bug in Playwright. If you add a small delay before the Enter, it works. So their even handling can't handle our quick events. So being a very fast user ends up in that bad state.

```ts
import { chromium } from 'playwright';

(async () => {
  const browser = await chromium.launch({
    headless: false
  });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://www.google.com/');
  await page.getByRole('button', { name: 'Alle akzeptieren' }).click();
  await page.getByLabel('Suche', { exact: true }).click();
  await page.getByLabel('Suche', { exact: true }).fill('hallo welt');
  await page.waitForTimeout(500);
  await page.keyboard.press('Enter');
  await page.waitForTimeout(50000);

  // ---------------------
  await context.close();
  await browser.close();
})();
```

**Comment by mxschmitt** [comment] 2023-08-20 12:04
Closing as per above. Since google.com is a rather complex example, we can't act on it. (Looks like google.com is interpreting the keyboard events incorrectly, maybe due to hydration. If you have a self-contained reproducible, please re-file, thanks!

**Closed by mxschmitt** 2023-08-20 12:04 UTC
Labels: triaging
