### ISSUE TITLE
[Feature]: Add option to disable AudioContext autoplay

### ISSUE THREAD

**Issue by andy-fillebrown** [microsoft/playwright#33590] opened 2024-11-13 21:20 UTC
### 🚀 Feature Request

When creating a new `AudioContext`, its initial `state` is `"running"`, which is good for testing audio, but does not reflect the initial state encountered by users of a website, which is `"suspended"` and requires a user interaction for the `AudioContext.resume()` promise to resolve.

If possible, please add an option that makes `AudioContext`'s initial state `"suspended"`, and require a user interaction for the `AudioContext.resume()` promise to resolve.

### Motivation

This would make it possible to test the user interaction requirements for autoplay implemented by browsers. See https://developer.chrome.com/blog/autoplay for more info on Chrome's requirements. Webkit's requirements are similar.

**Comment by pavelfeldman** [comment] 2024-11-13 21:41
Could you provide a full repro case and example of proposed API?

**Comment by andy-fillebrown** [comment] 2024-11-13 22:07
It may not be possible without changing the browser build settings. See [bootstrap.diff:23122](https://github.com/microsoft/playwright/blob/d1ae5f6ac4de84490310b83c0e071a7c13b0ede1/browser_patches/webkit/patches/bootstrap.diff#L23122) for the webkit build for example.

I assume there's something similar for the chromium build. It might be better to leave the autoplay build settings alone so autoplay is disabled by default, and then add CLI flags for each browser to enable it. So for chromium the flag to set would be `--autoplay-policy=no-user-gesture-required". I'm not sure if there are Firefox and Webkit equivalents.

If it were done that way then `ignoreDefaultArgs` could be used to disable autoplay: https://playwright.dev/docs/api/class-browsertype#browser-type-launch-option-ignore-default-args.

**Comment by hpatel292-seneca** [comment] 2024-11-16 20:00
@pavelfeldman Could you please assign it to me? I can work on it.

**Comment by yury-s** [comment] 2024-11-18 19:29
@andy-fillebrown can you share a repro where the behavior differs from the stock browsers?

**Comment by yury-s** [comment] 2024-11-18 20:24
The following test passes in all 3 browsers on macOS for me:

```js
import { test, expect } from '@playwright/test';

test("context audio", async ({ page }) => {
  await page.route("**/*", async (route) => {
    console.log('server response');
    route.fulfill({
      status: 200,
      contentType: 'text/html',
      body: `<script> 
function onLoad() {
  const log = document.getElementById('log');
  const audio = new AudioContext();
  log.innerHTML = 'State: ' + audio.state;
}
</script>
<body onload="onLoad()">
  <div id="log"></div>
</body>`,
    });
  });
  await page.goto("http://127.0.0.1:8080/audio.html");
  await expect(page.locator('#log')).toHaveText('State: suspended', { timeout: 1000 });
});
```

**Comment by andy-fillebrown** [comment] 2024-11-19 02:26
> The following test passes in all 3 browsers on macOS for me:
> 
> import { test, expect } from '@playwright/test';
> 
> test("context audio", async ({ page }) => {
>   await page.route("**/*", async (route) => {
>     console.log('server response');
>     route.fulfill({
>       status: 200,
>       contentType: 'text/html',
>       body: `<script> 
> function onLoad() {
>   const log = document.getElementById('log');
>   const audio = new AudioContext();
>   log.innerHTML = 'State: ' + audio.state;
> }
> </script>
> <body onload="onLoad()">
>   <div id="log"></div>
> </body>`,
>     });
>   });
>   await page.goto("http://127.0.0.1:8080/audio.html");
>   await expect(page.locator('#log')).toHaveText('State: suspended', { timeout: 1000 });
> });

Changing that test to make it start a sound makes it pass for chromium and firefox, but fail for webkit on macOS for me:
```JavaScript
test("context audio", async ({ page }) => {
    await page.route("**/*", async (route) => {
        console.log("server response");
        route.fulfill({
            status: 200,
            contentType: "text/html",
            body: `<script>
async function onLoad() {
  const log = document.getElementById('log');
  const audioContext = new AudioContext();
  const gainNode = new GainNode(audioContext);
  gainNode.connect(audioContext.destination);
  gainNode.gain.value = 0.025;
  const sineNode = new OscillatorNode(audioContext);
  sineNode.connect(gainNode);
  sineNode.start();
  await new Promise((resolve) => setTimeout(resolve, 2000));
  log.innerHTML = 'State: ' + audioContext.state;
}
</script>
<body onload="onLoad()">
  <div id="log"></div>
</body>`,
        });
    });
    await page.goto("http://127.0.0.1:8080/audio.html");
    await expect(page.locator("#log")).toHaveText("State: suspended", { timeout: 5000 });
});
```

And doing it more simply with `page.evaluate` makes it fail for chromium, webkit, and firefox on macOS for me:
```TypeScript
test("AudioContext should stay suspended", async ({ page }) => {
    const audioContextState = await page.evaluate(async () => {
        const audioContext = new AudioContext();
        const gainNode = new GainNode(audioContext);
        gainNode.connect(audioContext.destination);
        gainNode.gain.value = 0.025;
        const sineNode = new OscillatorNode(audioContext);
        sineNode.connect(gainNode);
        sineNode.start();
        await new Promise<void>((resolve) => setTimeout(resolve, 5000));
        return audioContext.state;
    });
    expect(audioContextState).toBe("suspended");
});
```

**Comment by yury-s** [comment] 2024-11-19 19:15
> Changing that test to make it start a sound makes it pass for chromium and firefox, but fail for webkit on macOS for me:

Thanks, I can reproduce it.

> And doing it more simply with page.evaluate makes it fail for chromium, webkit, and firefox on macOS for me:

This is probably because each `page.evaluate` is marked as "User gesture" evaluate in the browser, the behavior is similar to that when the code is called from say `onclick` handler and is consistent with that.

**Comment by andy-fillebrown** [comment] 2024-11-19 19:29
> > Changing that test to make it start a sound makes it pass for chromium and firefox, but fail for webkit on macOS for me:
> 
> Thanks, I can reproduce it.
> 
> > And doing it more simply with page.evaluate makes it fail for chromium, webkit, and firefox on macOS for me:
> 
> This is probably because each `page.evaluate` is marked as "User gesture" evaluate in the browser, the behavior is similar to that when the code is called from say `onclick` handler and is consistent with that.

Ok, thanks for the info. Is there a way to prevent `page.evaluate` from being marked as a user gesture? The test you posted earlier is good assuming the webkit difference is resolved, but audio tests would be cleaner if a `page.evaluate` option was available that prevents it from being marked as a user gesture.

**Comment by yury-s** [comment] 2024-11-19 23:19
> Changing that test to make it start a sound makes it pass for chromium and firefox, but fail for webkit on macOS for me:

The test is actually consistent with vendor browsers behavior. Safari also creates the context in 'running' state on my macOS machine, so it seems to be working as intended.


> Is there a way to prevent page.evaluate from being marked as a user gesture? 

No. But you can probably trigger the code with intermediate setTimeout .

**Comment by yury-s** [comment] 2024-11-20 18:01
> How are you determining this?

I open this page in Safari:

```html
<script>
async function onLoad() {
  const log = document.getElementById('log');
  const audioContext = new AudioContext();
  const gainNode = new GainNode(audioContext);
  gainNode.connect(audioContext.destination);
  gainNode.gain.value = 0.025;
  const sineNode = new OscillatorNode(audioContext);
  sineNode.connect(gainNode);
  sineNode.start();
  await new Promise((resolve) => setTimeout(resolve, 2000));
  log.innerHTML = 'State: ' + audioContext.state;
}
</script>
<body onload="onLoad()">
  <div id="log"></div>
</body>
```

**Comment by mxschmitt** [comment] 2024-11-20 18:03
I ran this on my Mac with the following results:

Chrome: suspended
Safari: running

**Comment by andy-fillebrown** [comment] 2024-11-20 18:13
> > How are you determining this?
> 
> I open this page in Safari:
> 
> <script>
> async function onLoad() {
>   const log = document.getElementById('log');
>   const audioContext = new AudioContext();
>   const gainNode = new GainNode(audioContext);
>   gainNode.connect(audioContext.destination);
>   gainNode.gain.value = 0.025;
>   const sineNode = new OscillatorNode(audioContext);
>   sineNode.connect(gainNode);
>   sineNode.start();
>   await new Promise((resolve) => setTimeout(resolve, 2000));
>   log.innerHTML = 'State: ' + audioContext.state;
> }
> </script>
> <body onload="onLoad()">
>   <div id="log"></div>
> </body>

Right, but how are you serving the page and what URL are you pointing Safari to?

**Comment by yury-s** [comment] 2024-11-20 18:14
Just http://127.0.0.1:8081/audio.html

**Comment by andy-fillebrown** [comment] 2024-11-20 18:46
> Just http://127.0.0.1:8081/audio.html, serving with `npx http-server . `

Thanks. Doing exactly that with the same html on my machine shows `State: suspended`, and again; this is exactly what I expect to see and matches what a user would see when trying to start audio without a user gesture.

Can you check your autoplay preferences in Safari and make sure 127.0.0.1 is set to "Stop Media with Sound"?
You can find this setting in `Safari -> Preferences -> Websites -> Auto-Play`.

**Comment by yury-s** [comment] 2024-11-20 18:57
Yeah, I'd expect it to be suspended as well, but for some reason it is not. Here is the settings window:

![Image](https://github.com/user-attachments/assets/0e13a1eb-1d12-48aa-ac77-e23505203563)

**Comment by docEdub** [comment] 2024-11-20 20:39
> Yeah, I'd expect it to be suspended as well, but for some reason it is not. Here is the settings window:
> 
> ![Image](https://github.com/user-attachments/assets/0e13a1eb-1d12-48aa-ac77-e23505203563)

Maybe autoplay gets a free pas

**Comment by andy-fillebrown** [comment] 2024-11-20 20:49
On my machine the "Auto-Play" websites list is empty until I actually go to `127.0.0.1:8080/audio.html`. Going back into the auto-play settings while that page is loaded shows it in the websites list with it set to "Stop Media with Sound". When I change it to "Allow All Auto-Play", I get the audio context `State: running` that you're getting. Can you verify your "Auto-Play" settings with `127.0.0.1:8080/audio.html` loaded and see if it's set to "Allow All Auto-Play", too?

**Comment by yury-s** [comment] 2024-11-20 20:58
This is what I see when opening the settings while the page is loaded:

![Image](https://github.com/user-attachments/assets/d4d5d915-ed8a-4112-92c1-2b9be2e203a0)

**Comment by andy-fillebrown** [comment] 2024-11-20 21:03
Interesting. What version of Safari and macOS is this? I'm on Sonoma 14.7 running Safari 17.6 (19618.3.11.11.5)

**Comment by yury-s** [comment] 2024-11-20 21:11
Looks like it only starts in the "running" state when I paste the URL after Safari's cold start (e.g. after the computer's reboot), if I repeat the same action later the context starts in a suspended state! The settings look exactly the same in both cases.

**Comment by yury-s** [comment] 2024-11-20 21:15
> Interesting. What version of Safari and macOS is this? I'm on Sonoma 14.7 running Safari 17.6 (19618.3.11.11.5)

Sequoia 15.1 Safari 18.1 (20619.2.8.11.10). But I believe this is just a race as described above, it might be that it starts in `running` state before the browser settings are fully loaded or something like that.

**Comment by andy-fillebrown** [comment] 2024-11-20 21:24
> > Interesting. What version of Safari and macOS is this? I'm on Sonoma 14.7 running Safari 17.6 (19618.3.11.11.5)
> 
> Sequoia 15.1 Safari 18.1 (20619.2.8.11.10). But I believe this is just a race as described above, it might be that it starts in `running` state before the browser settings are fully loaded or something like that.

Yes, this repros on my machine, too. Nice find!

**Comment by andy-fillebrown** [comment] 2024-11-20 21:27
I'm thinking the Playwright webkit browser is giving localhost a free pass on autoplay, but chromium and firefox are not. I'll try testing with a non-localhost server next to see if that changes things for webkit.

**Comment by andy-fillebrown** [comment] 2024-11-20 21:36
> I'm thinking the Playwright webkit browser is giving localhost a free pass on autoplay, but chromium and firefox are not. I'll try testing with a non-localhost server next to see if that changes things for webkit.

Nope, this gives the same result. AFIACT the Playwright webkit browser always allows autoplay, so this feature request is only needed for the webkit browser.

**Closed** 2024-11-22 22:53 UTC
Labels: v1.50
