### ISSUE TITLE
[BUG] Tests failing on Webkit / Webkit Mobile browsers in a Docker container

### ISSUE THREAD

**Issue by filipwkania** [microsoft/playwright#13875] opened 2022-05-02 14:48 UTC
**Context:**
- Playwright Version: 1.21
- Operating System: ms playwright docker 1.21.0-focal
- Node.js version: [e.g. 12.22, 14.6]
- Browser: WebKit
- Extra: running in Docker container

**Code Snippet** 
just example code (it happens randomly for different tests)

```javascript
test('Test document', async ({ page }) => {
    await page.goto('some page here');

    await expect(page.locator('.header-controls .header-controls__download')).not.toBeVisible();
});
```
```
...
        {
            name: 'webkit',
            use: { ...devices['Desktop Safari'] },
        },
        {
            name: 'webkit mobile',
            use: { ...devices['iPhone 12'] },
        },
...
```

**Describe the bug**

One or more tests fail constantly on the webkit/webkit mobile browser only when run in a docker container. I have no idea why, as it seems the tests are not even ran (perhaps it fails before browser is started). Tests fail in the Before Hooks and take <300ms to fail.
Tests pass normally when ran outside docker (macOS).

```
  2 failed
    [webkit] › find.spec.ts:3:1 › Find text in document and navigate between results ===============
    [webkit mobile] › find.spec.ts:3:1 › Find text in document and navigate between results ========
  12 skipped
  43 passed (3m)
make: *** [docker-ci-playwright] Error 1
```
```
browser.newContext: Browser closed.
==================== Browser output: ====================
<launching> /ms-playwright/webkit-1630/pw_run.sh --inspector-pipe --headless --no-startup-window
<launched> pid=6278
[pid=6278][err] /ms-playwright/webkit-1630/pw_run.sh: line 21:  6326 Segmentation fault      (core dumped) WEBKIT_FORCE_COMPLEX_TEXT="1" "$MINIBROWSER" "$@"
[pid=6278] <process did exit: exitCode=139, signal=null>
[pid=6278] starting temporary directories cleanup
[pid=6278] finished temporary directories cleanup
```
```
browser.newContext: Browser closed.
==================== Browser output: ====================
<launching> /ms-playwright/webkit-1630/pw_run.sh --inspector-pipe --headless --no-startup-window
<launched> pid=9432
[pid=9432][err] WARNING: trying to load platform resource 'missingImage'
[pid=9432][err] /ms-playwright/webkit-1630/pw_run.sh: line 21:  9442 Segmentation fault      (core dumped) WEBKIT_FORCE_COMPLEX_TEXT="1" "$MINIBROWSER" "$@"
```

Maybe you have some ideas what we could do to stop them from failing randomly in Docker? We want to use PW in our CI pipeline but this is stopping us.

**Comment by timgreen** [comment] 2022-05-04 06:24
I can confirm the same issue happens on an aarch64 instance.

**Comment by mxschmitt** [comment] 2022-05-06 12:11
Are you able to share with us a full [repro](https://stackoverflow.com/help/minimal-reproducible-example) which we can run locally?

Also setting the following env might yield to more output: `DEBUG=pw:browser`

**Comment by timgreen** [comment] 2022-05-06 12:36
https://asciinema.org/a/492608

```
uname -a
docker run -it --rm --ipc=host mcr.microsoft.com/playwright:v1.21.0-focal /bin/bash
# then run 
DEBUG=pw:browser npx playwright screenshot -b wk --timeout 100000 https://www.google.com /dev/shm/g.png
DEBUG=pw:browser npx playwright screenshot --timeout 100000 https://www.google.com /dev/shm/g.png
DEBUG=pw:browser npx playwright screenshot -b ff --timeout 100000 https://www.google.com /dev/shm/g.png
```

**Comment by aslushnikov** [comment] 2022-05-11 12:58
@timgreen I tried this on both x86_64 Linux machine and Apple M1 - works for me, no crashes.

**Comment by timgreen** [comment] 2022-05-11 13:09
@aslushnikov my instance causes is running on [Oracle Ampere A1 Compute instances](https://www.oracle.com/au/cloud/compute/arm/).

**Comment by chenshy39** [comment] 2022-05-13 03:08
> Oracle Ampere A1 Compute instances



> **Context:**
> 
> * Playwright Version: 1.21
> * Operating System: ms playwright docker 1.21.0-focal
> * Node.js version: [e.g. 12.22, 14.6]
> * Browser: WebKit
> * Extra: running in Docker container
> 
> **Code Snippet** just example code (it happens randomly for different tests)
> 
> ```js
> test('Test document', async ({ page }) => {
>     await page.goto('some page here');
> 
>     await expect(page.locator('.header-controls .header-controls__download')).not.toBeVisible();
> });
> ```
> 
> ```
> ...
>         {
>             name: 'webkit',
>             use: { ...devices['Desktop Safari'] },
>         },
>         {
>             name: 'webkit mobile',
>             use: { ...devices['iPhone 12'] },
>         },
> ...
> ```
> 
> **Describe the bug**
> 
> One or more tests fail constantly on the webkit/webkit mobile browser only when run in a docker container. I have no idea why, as it seems the tests are not even ran (perhaps it fails before browser is started). Tests fail in the Before Hooks and take <300ms to fail. Tests pass normally when ran outside docker (macOS).
> 
> ```
>   2 failed
>     [webkit] › find.spec.ts:3:1 › Find text in document and navigate between results ===============
>     [webkit mobile] › find.spec.ts:3:1 › Find text in document and navigate between results ========
>   12 skipped
>   43 passed (3m)
> make: *** [docker-ci-playwright] Error 1
> ```
> 
> ```
> browser.newContext: Browser closed.
> ==================== Browser output: ====================
> <launching> /ms-playwright/webkit-1630/pw_run.sh --inspector-pipe --headless --no-startup-window
> <launched> pid=6278
> [pid=6278][err] /ms-playwright/webkit-1630/pw_run.sh: line 21:  6326 Segmentation fault      (core dumped) WEBKIT_FORCE_COMPLEX_TEXT="1" "$MINIBROWSER" "$@"
> [pid=6278] <process did exit: exitCode=139, signal=null>
> [pid=6278] starting temporary directories cleanup
> [pid=6278] finished temporary directories cleanup
> ```
> 
> ```
> browser.newContext: Browser closed.
> ==================== Browser output: ====================
> <launching> /ms-playwright/webkit-1630/pw_run.sh --inspector-pipe --headless --no-startup-window
> <launched> pid=9432
> [pid=9432][err] WARNING: trying to load platform resource 'missingImage'
> [pid=9432][err] /ms-playwright/webkit-1630/pw_run.sh: line 21:  9442 Segmentation fault      (core dumped) WEBKIT_FORCE_COMPLEX_TEXT="1" "$MINIBROWSER" "$@"
> ```
> 
> Maybe you have some ideas what we could do to stop them from failing randomly in Docker? We want to use PW in our CI pipeline but this is stopping us.

Is that can be something about your machine ran out of CPU caused? I also have this problem which is CPU issue, resolve by allocate more CPU cores in docker.

**Comment by mxschmitt** [comment] 2022-05-18 10:07
Closing since we can't repro, please file a new issue with clear repro details.

**Closed by mxschmitt** 2022-05-18 10:07 UTC
Labels: triaging

**Comment by pradeipp** [comment] 2022-12-21 10:07
I'm getting the same error in gitlab... did anyone find any solution to this?

**Comment by sakshivishnoi681** [comment] 2023-05-25 06:29
> I'm getting a similar issue in gitlab... the mobile safari tests are all failing right at the url navigation stage in the beginning. `page.goto: Timeout 60000ms exceeded.` The tests are passing for all other devices(3 web browsers and mobile chromium view)
> 
> I tried both 1.29.0 and 1.28.1 versions of playwright and the corresponding official docker image.

Did you get any solution? I am also facing same issue

**Comment by pradeipp** [comment] 2023-05-25 15:00
@sakshivishnoi681 Increasing the test timeout helped. But mobile safari was so flaky we just disabled it completely.

**Comment by mxschmitt** [comment] 2023-09-04 11:51
@magwo please file a new issue with a reproduction, more than happy to take a look / to fix it. Thanks!

**Comment by magwo** [comment] 2023-09-04 13:47
Will try! Internal code so kinda hard to make a repro. A clue can be that these tests are fairly long-running - like 30 seconds. They are multi-step form interfaces including a multi-step setup.
