### ISSUE TITLE
[BUG] Exact=true in GetByRole AriaRole.Link option

### ISSUE THREAD

**Issue by bengohkiandra** [microsoft/playwright#19537] opened 2022-12-17 08:30 UTC
**Context:**
- Playwright Version: 1.27
- Operating System: Windows .NET
- Node.js version: 
- Browser: All, 
- Extra: 

These are the lines I have in my script
**Code Snippet**

page.GetByRole(AriaRole.Link, new() { Exact=true, NameString="Subscription" }).ClickAsync()

The web page has the following code: 
   ... 
<span class="menu-title ng-star-inserted">Subscriptions</span>
 ... 

Playwright cannot locate the element
The  Exact=true option is working in AriaRole.TreeItem when I can use the exact spelling 

I removed the Exact=true option on the link, and it works. But I ran into other issues with the regular expression, where the locator can't tell the difference between "Subscriptions" and "Webhook Subscriptions".

**Comment by mxschmitt** [comment] 2022-12-19 10:04
If I understand you correctly, the issue is that `Exact` works great if you pass a `string` for name, but not if you pass a regular expression?

This is expected as of today, see here (or in the docs): 
![image](https://user-images.githubusercontent.com/17984549/208399994-ea565126-30c3-4adf-a3aa-bddb4027d11c.png)

**Comment by bengohkiandra** [comment] 2022-12-19 10:15
No, the option doesn't work if I use Exact=True, for AriaRole.Link, when I pass in the string matching the element on the page.
`page.GetByRole(AriaRole.Link, new() {Exact=True, NameString="Administration"}); `
Playwright cannot locate the element. It works when I removed the Exact option. But then failed further because that's another  "Link" element that is called "WebHook Administration" as Playwright issues it found 2 elements.

**Comment by mxschmitt** [comment] 2022-12-19 10:38
Can you show us the HTML of the element you want to locate?

**Comment by bengohkiandra** [comment] 2022-12-19 11:39
Here's the code
 `<a href="javascript:;" class="menu-link menu-toggle ng-star-inserted"><span class="menu-item-here ng-star-inserted"></span><span class="menu-icon ng-star-inserted"><i class="flaticon-interface-8"></i></span><!----><span class="menu-title ng-star-inserted">Administration</span><!----><!----><!----><!----><span class="menu-arrow ng-star-inserted"></span><!----><!----></a>`

**Comment by pavelfeldman** [comment] 2022-12-19 17:31
Could you try using codegen to generate the selector? It might be that `Administration` is not the exact match of the text for that node.

**Comment by pavelfeldman** [comment] 2022-12-23 16:52
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Closed by pavelfeldman** 2022-12-23 16:52 UTC
Labels: triaging
