### ISSUE TITLE
[Bug]: Font kerning and font weight problems 

### ISSUE THREAD

**Issue by nsbarsukov** [microsoft/playwright#30785] opened 2024-05-14 11:43 UTC
### Version

1.44.0

### Steps to reproduce

Use our repository of Open Source project – https://github.com/taiga-family/taiga-ui
Approximately 3 weeks ago (mid-April) our screenshot tests became too flaky.

The main problem – font rendering.
See some examples:

![image](https://github.com/microsoft/playwright/assets/35179038/5e713787-5a64-4d20-9b8a-b5ed51425ac1)

![image](https://github.com/microsoft/playwright/assets/35179038/a73707ee-514a-4e9c-a008-aeff99c20352)

![image](https://github.com/microsoft/playwright/assets/35179038/09e03e53-0baa-4590-9f0a-253f68c4f698)

1. Sometimes it **incorrectly** applies the **font-weight**
    (probably, relates to https://github.com/microsoft/playwright/issues/22429)
2. **Flaky font-kerning** 
    (probably, relates to https://github.com/microsoft/playwright/issues/20203)

More examples see in this PR:
* https://github.com/taiga-family/taiga-ui/pull/7419#issuecomment-2109889087

### Expected behavior

Font renders in the same way for the same OS every time.

### Actual behavior

Flaky render of fonts

### Additional context

We've already:

1. [Used](https://github.com/taiga-family/taiga-ui/blob/7fed3565cb19e0b2526e3ca9c2d57e9967d0b601/projects/demo-playwright/utils/wait-for-fonts.ts#L4-L12 ) auto-retried assertions to wait font:
```ts
export async function tuiWaitForFonts(page: Page): Promise<void> {
    await expect(async () => {
        expect(await page.evaluate(() => (document as any).fonts.size)).toBeGreaterThan(
            0,
        );
        expect(await page.evaluate(() => (document as any).fonts.ready)).toBeTruthy();
        expect(await page.evaluate(() => (document as any).fonts.status)).toBe('loaded');
    }).toPass({timeout: 30_000});
}
```

2. [Mocked](https://github.com/taiga-family/taiga-ui/blob/7fed3565cb19e0b2526e3ca9c2d57e9967d0b601/projects/demo-playwright/utils/goto.ts#L53-L55) fonts
```ts
await page.route('https://fonts.gstatic.com/**/*.ttf', async route =>
        route.fulfill({path: `${__dirname}/../stubs/manrope-fonts.ttf`}),
);
```

3. Tried to revert to previous version of playwright (`1.44.0` => `1.38.0`)
    https://github.com/taiga-family/taiga-ui/pull/7413

The problems still persist :(

### Environment

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (4) x64 AMD EPYC 7763 64-Core Processor
    Memory: 14.32 GB / 15.61 GB
    Container: Yes
Binaries:
    Node: 20.12.2 - /opt/hostedtoolcache/node/20.12.2/x64/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.5.0 - /opt/hostedtoolcache/node/20.12.2/x64/bin/npm
Languages:
    Bash: 5.1.16 - /usr/bin/bash
```

**Comment by mxschmitt** [comment] 2024-05-14 17:22
Would it be possible to provide a more minimal reproduction which we can run locally?

Ideally without cloning/building the entire project.

> Approximately 3 weeks ago (mid-April) our screenshot tests became too flaky.

Are you able to track it down which latest GitHub Action run was good and when it first started failing? Since from a quick look you are using package-lock.json - that doesn't seem like a Playwright bug, and the underlying host OS might have changed instead and causing these kind of issues.

**Comment by nsbarsukov** [comment] 2024-05-15 10:05
> Would it be possible to provide a more minimal reproduction

Unfortunately, it's the most minimum reproduction I have at the present time :(
I will continue my attempts to detect reason of these issues – I will write about any updates.

**Comment by nsbarsukov** [comment] 2024-05-15 10:10
We've tried to switch browser (`Chrome` => `Firefox`):
- https://github.com/taiga-family/taiga-ui/pull/7424

The problem still persists((
![01-native-select-value diff](https://github.com/microsoft/playwright/assets/35179038/1f1444e4-f48d-453a-9680-dd06c142a82b)

---

![01-character-with-descenders-inside-placeholder diff](https://github.com/microsoft/playwright/assets/35179038/b6dc4746-f429-4bcf-b50a-ca7ecc8caaa7)

(see letter `f` in the word `textfield`)

**Comment by mxschmitt** [comment] 2024-05-16 19:19
I'll close the issue for now, since we have not enough information to act on it. In theory, browser screenshots should be reproducible, if they get created on the same Host (os/arch/version) and the DOM is stable.

I recommend looking at build pipeline logs, maybe that will yield something, maybe the underlying OS version has changed etc.

Feel free to re-file if you found out more and have evidence that its a bug on Playwright side. Thanks for understanding.

**Closed by mxschmitt** 2024-05-16 19:19 UTC

**Comment by waterplea** [comment] 2024-05-17 07:08
Were about to close it ourselves 🙂 we figured it out — seems like for some reason critical CSS and fonts inlining in Angular worked differently in 2 environments being compared and we ended up loading `woff` font in one case and `ttf` in another which rendered slightly differently. We mocked both paths for testing and it stabilized. Maybe it would be helpful to anyone else who will face a similar issue.

**Comment by StanislavGrishaev** [comment] 2024-05-17 07:18
> We mocked both paths for testing and it stabilized.

@waterplea hi there, I have a fairly similar problem on one of the projects, can you please provide an example of the code (you can directly link to your repository) how did you do it?

**Comment by nsbarsukov** [comment] 2024-05-17 07:39
@StanislavGrishaev Hi!

Add these lines to your custom `goto` utility:
```ts
await page.route('https://fonts.gstatic.com/**', async route =>
    route.fulfill({path: `${__dirname}/../stubs/manrope-fonts.ttf`}),
);
```
Explore our custom [tuiGoto](https://github.com/taiga-family/taiga-ui/blob/2b7f26336bd50fdbb219ac90f6dbff79959dc96f/projects/demo-playwright/utils/goto.ts#L53-L55) utility to get more details.

**Comment by StanislavGrishaev** [comment] 2024-05-17 07:41
@nsbarsukov thanks, appreciate it !

**Comment by StanislavGrishaev** [comment] 2024-05-17 12:23
@nsbarsukov I just want to make sure that the type of request you are replacing (https://fonts.gstatic.com/**) is a fetch/document request? Because I’m trying to replace fonts in my project and I see in dev tools that their request type is fonts (on screenshot), I have a suspicion that in this case `route.fulfill` does not work (because I don’t see any changes on the page when replacing), but I don’t sure...
![image](https://github.com/microsoft/playwright/assets/115224622/6ca333e3-2997-4a13-b16c-25133c215898)

**Comment by nsbarsukov** [comment] 2024-05-17 12:51
> @nsbarsukov I just want to make sure that the type of request you are replacing (https://fonts.gstatic.com/**) is a fetch/document request? Because I’m trying to replace fonts in my project and I see in dev tools that their request type is fonts (on screenshot), I have a suspicion that in this case `route.fulfill` does not work (because I don’t see any changes on the page when replacing, even if i try `route.abort()` for my fonts route) , but I don’t sure... ![image](https://private-user-images.githubusercontent.com/115224622/331593730-f23565a5-4077-4b62-80c1-20bd59a84d73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTAzNDEsIm5iZiI6MTcxNTk1MDA0MSwicGF0aCI6Ii8xMTUyMjQ2MjIvMzMxNTkzNzMwLWYyMzU2NWE1LTQwNzctNGI2Mi04MGMxLTIwYmQ1OWE4NGQ3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxMjQ3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDllM2UzYWJmYmVmYTc2NTkyOGQ0NmNlOWUzMmI1MGJkYmNlOWI1OGJhYzA3MGQ3NjQwOTQxYzY5NjFjNDJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sfj12_sha69bl3rFy1eEShDFTssF4oJpbSPiMRoYjrE)

Use playwright UI mode (not browser dev tools) to check it:
https://playwright.dev/docs/test-ui-mode#network

As for my case, it works – see body's decscription of the following PR:
* https://github.com/taiga-family/taiga-ui/pull/7451
