### ISSUE TITLE
[BUG]    slice: (buf, start, end) => buf.utf8Slice(start, end),

### ISSUE THREAD

**Issue by wanghaisheng** [microsoft/playwright#15121] opened 2022-06-25 10:07 UTC
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: [e.g. Windows, Linux or Mac]
- Node.js version: [e.g. 12.22, 14.6]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
  // Please include a snippet of HTML that shows an example of the content
  // you are testing.
  await page.setContent(`
    <div>
      …
    </div>
  `);
  // Alternatively, if you are testing a public application, include the URL:
  // await page.goto('https://example.com/')
  
  await page.locator(…);
})();
```

**Describe the bug**

I am using python client to run playwright, but encounter this weired  situation,it seems filename in Korean brokes

```
DEBUG: Found YouTube upload Dialog Modal
DEBUG: Trying to upload "Z:/CINEMATIC-STOCK2/2022_시네마틱아카이브_WO_지역별 업로드/제주/upload 6월 업로드 테스트 벌크\매빅3씨네,드론영상소스,DJI_0124_0001 제주특별자치도 제주시 애월읍 광령리 광령가든,선빌리지 제주지점,[힐타운호텔.mp](http://xn--zo5bt7pzmaq5ncyb.mp/)4" to YouTube...
node:buffer:593
    slice: (buf, start, end) => buf.utf8Slice(start, end),
                                    ^

Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:593:37)
    at Buffer.toString (node:buffer:811:14)
    at Immediate.<anonymous> (C:\Users\M2e 1F\Videos\autovideo_enV[2022-0620](http://2022-0620/)\autovideo_en\playwright\driver\package\lib\protocol\transport.js:89:52)
    at processImmediate (node:internal/timers:464:21) {
  code: 'ERR_STRING_TOO_LONG'
}
```

**Comment by rwoll** [comment] 2022-06-30 01:39
Hi, @wanghaisheng! Thanks for your report!

I created the following repository in an attempt to reproduce the issue reported here: https://github.com/rwoll/playwright-repro-string-too-long-issue-15121

However, I was unsuccessful. When I run the example in that repository, the file is successfully uploaded and no error is observed.

Can you clone and try the instructions in https://github.com/rwoll/playwright-repro-string-too-long-issue-15121, and let me know if you observe the error you originally reported? If not, can you try modifying the repository and such that it reproduces the error you've reported. When you write back, please also share which browser you're testing, and which version of Playwright, and any other details you might have. Thanks!

Sorry this error is happening, and thanks for your patience and help!

**Comment by wanghaisheng** [comment] 2022-06-30 01:45
yes 
thank for your work

**Comment by rwoll** [comment] 2022-07-04 19:11
Happy to help! As part of weekly triage, I'm going to close this issue since we are unable to reproduce so far and have not yet received other reports. However, if you are able to change the attempted repro in https://github.com/microsoft/playwright/issues/15121#issuecomment-1170657646 in a way where it reproduces for you, then please comment and re-open so we can help figure out what's going on. Thanks!

**Closed by rwoll** 2022-07-04 19:11 UTC
Labels: triaging
