### ISSUE TITLE
locator().screenshot() isn't working as expected.

### ISSUE THREAD

**Issue by pateljay1397** [microsoft/playwright#23845] opened 2023-06-21 21:21 UTC
### System info
- Playwright Version: "^1.34.0"
- Operating System: Windows 11
- Browser: Chromium
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

```
  test("Sample visual testing", async ({ page }) => {
    await page.goto(`siteurl`, { waitUntil: "domcontentloaded" });
    await page.waitForTimeout(10000);
    const shot = await page.getByTestId('data-testid-value').screenshot();
    expect(shot).toMatchSnapshot("sampletest.png", {maxDiffPixels: 1000});
  });
```

PLease run provided test method with any of the sample test you have (website)

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Steps**
- [Run the test]
- [...]

**Expected**
It should take a screenshot of specific element located by locator and match it with existing screenshot
**Actual**
Screenshot() method is not taking any screenshot as it gets stuck and doesn't move to next step.

**Comment by dgozman** [comment] 2023-06-21 23:09
@pateljay1397 Could you please provide the page url and the actual locator? Without a repro that we can run locally, we won't be able to help you.

**Comment by pateljay1397** [comment] 2023-06-22 02:19
Hi, our product is for house use only so I can't actually provide the page URL but here the purpose of the issue is about the method screenshot(). as in following syntax, we are locating an element by testid await page.getByTestId('data-testid-value').screenshot(); on page and we want to take screenshot of that selected element but in this case it get stuck at this line in test provided test method.
If you want to reproduce it, you can refer any static page on your local machine and select the element using locator or data-testid to take a screenshot of it.

**Comment by dgozman** [comment] 2023-06-22 15:51
@pateljay1397 Well, I tried calling `screenshot()` on various elements, and it definitely works. We have tests for that. I suspect the problem is specific to your page. Without a repro that we can run locally, we won't be able to help you.

For the reference, the following works just fine:

```ts
import { test, expect } from '@playwright/test';

test('screenshot getByTestId', async ({ page }) => {
  await page.goto('https://demo.playwright.dev/todomvc/');
  await page.getByPlaceholder('What needs to be done?').fill('hello');
  await page.getByPlaceholder('What needs to be done?').press('Enter');
  const shot = await page.getByTestId('todo-count').screenshot();
  expect(shot).toMatchSnapshot("sampletest.png", { maxDiffPixels: 1000 });
});
```

**Comment by pateljay1397** [comment] 2023-06-22 16:05
Thank you @dgozman for acknowledging the issue. I think in our case the element is hidden at the bottom which might be the root cause because with data-testid, it can identify the targeted element on the page but it gets stuck when it has to take a screenshot of that element.

**Comment by dgozman** [comment] 2023-06-22 16:24
@pateljay1397 Is there an error message? Perhaps the element is not visible? If so, it's expected that Playwright will wait for the element to become visible.

**Comment by pateljay1397** [comment] 2023-06-22 16:28
@dgozman element is visible but some of the bottom portion is hidden in page, so I think that could be the reason why it is unable to take a screenshot.
Is there a way that we can add an option to take screenshot of a full element as we do for the page like this.
await page.screenshot({ path: 'screenshot.png', fullPage: true });

**Comment by dgozman** [comment] 2023-06-22 16:32
> Is there a way that we can add an option to take screenshot of a full element as we do for the page

No, that is not possible, because it requires changing your page's layout.

**Comment by dgozman** [comment] 2023-06-22 17:36
> If the selected element is partially hidden then we can't take a screenshot of that element as the element must need to be visible to take a screenshot correct?

Correct.

> I hope the playwright will introduce such features like this for selected element: await page.screenshot({ path: 'screenshot.png', fullElement: true });

As I said above, Playwright will not be able to force the element to be fully visible, sorry.

Let me close this issue, since there seems no action item for Playwright here. Thank you for filing!

**Closed by dgozman** 2023-06-22 17:36 UTC
Labels: triaging
