### ISSUE TITLE
[Feature]: WaitForEvent and events on the Frame object

### ISSUE THREAD

**Issue by LeanSaucecode** [microsoft/playwright#7927] opened 2021-07-30 06:47 UTC
### Playwright version

1.9.1

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

## Node Version 
14.17.0

### What happened? / Describe the bug

We are trying to download a file on click using playwright, so it works well when the download link is not inside of an iframe. Here is the link to your docs of the function we are using. [docs](https://playwright.dev/docs/events/#waiting-for-event)

We are getting the frames before attempting to register the event and clicking on the link. 

### Code snippet to reproduce your bug

```shell
// Get the iframe context
const getPageContext = z.fn((t) => async (ctx, data) => {
  if (t.or(t.isNil(data.iframe), t.noLen(data.iframe || ''))) {
    return ctx.page
  }
  const frameHandle = await ctx.page.$(data.iframe)
  return await frameHandle.contentFrame()
})

const pageCtx = await getPageContext(ctx, node.data)
 
// Register download event and click on the link to trigger the event       
const [download] = await Promise.all([
          pageCtx.waitForEvent('download'), // wait for download to start
          pageCtx.click(selector),
        ])
```

### Relevant log output

<details>

```shell
_request: [Request]
      },
      'Response@9d4a90638a7e6522ca51cd478955ac4c' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@9d4a90638a7e6522ca51cd478955ac4c',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@8624d630767ae1a7a39fe4bcdb7696a1' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@8624d630767ae1a7a39fe4bcdb7696a1',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@2658f711f4c85afc3ac85d690017ac66' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@2658f711f4c85afc3ac85d690017ac66',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@acdbaa8f6f88f120f2a00ed6a18b1165' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@acdbaa8f6f88f120f2a00ed6a18b1165',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@f5ad966d9de5ad4ac1745b52d0e1f017' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@f5ad966d9de5ad4ac1745b52d0e1f017',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@464e297cf93fb77ae36d3571330df50e' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@464e297cf93fb77ae36d3571330df50e',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@c49f671a5e0bf399515674a609243fcc' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@c49f671a5e0bf399515674a609243fcc',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@89df1b7347e01e50a92aeb8a866cab6b' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@89df1b7347e01e50a92aeb8a866cab6b',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@500eb23d7cf51f18b3004edd73f5dcc7' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@500eb23d7cf51f18b3004edd73f5dcc7',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@09a4d531ab12ad399c01c3c003add810' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@09a4d531ab12ad399c01c3c003add810',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@4290d1aafb4d70ba3305fdecf48df0f7' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@4290d1aafb4d70ba3305fdecf48df0f7',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@39781cfe8ea6dad2b0a284f53deab3cb' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@39781cfe8ea6dad2b0a284f53deab3cb',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@8485a9bfb4d249c84a99f11726650331' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@8485a9bfb4d249c84a99f11726650331',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@f086397f66a185548b9de79ebf8cffc3' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@f086397f66a185548b9de79ebf8cffc3',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@53c6c9774735fd68c47028069f01eb80' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@53c6c9774735fd68c47028069f01eb80',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@a7af1077e5ad6a09fb2a2720f1d5061a' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@a7af1077e5ad6a09fb2a2720f1d5061a',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@b2f710371970d75a3a56d3a5e9c67ae2' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@b2f710371970d75a3a56d3a5e9c67ae2',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@600ed5a4e4d43e5e2deaeb30a4cc8e20' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@600ed5a4e4d43e5e2deaeb30a4cc8e20',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@9cf95cb1e05915be0dc8bf57cec127ef' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@9cf95cb1e05915be0dc8bf57cec127ef',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@331ebdec89bb56d352430999b4275f25' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@331ebdec89bb56d352430999b4275f25',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      },
      'Response@3da4de393b7d181ea814e7ddc816de53' => Response {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Response',
        _guid: 'Response@3da4de393b7d181ea814e7ddc816de53',
        _parent: [Circular],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _headers: [Object],
        _request: [Request]
      }
    },
    _connection: Connection {
      _objects: Map {
        '' => [Root],
        'Browser@b61add0663c90e5aa6b77fa13b00c289' => [ChromiumBrowser],
        'Selectors@25fcc5f11d52e77ae461db7e7587b51c' => [SelectorsOwner],
        'remoteBrowser' => [RemoteBrowser],
        'BrowserContext@17038b07009edb20dc99dfb192c30b7a' => [ChromiumBrowserContext],
        'Frame@e520b5a72088586b18afff431da8400a' => [Frame],
        'Page@800de9d999e3d3866d420ac6da05e88b' => [Circular],
        'Request@03ac30a56bfd125fd4036f50a27a8c76' => [Request],
        'Response@70dd89f528710e9261e14b18d9ce86e1' => [Response],
        'Request@f4dfb9f9bc5b4197ae574f2fa76b0292' => [Request],
        'Request@3c712298c495bdaff080eede7eda1edd' => [Request],
        'Request@283261aed3c37dbf9bf0d9f63b9aa084' => [Request],
        'Request@3097ba2feec82ab7fa7c392cc25b1a55' => [Request],
        'Request@688ab484a21c6a238e2fbb4f836a0603' => [Request],
        'Request@1836b6b03c676eb07d316e93ec672257' => [Request],
        'Request@96b78e53a857d48383df4a97a6d1cc73' => [Request],
        'Request@659e911bd95603bc66cdf9c644fb1b84' => [Request],
        'Request@af2c08798c33e2570bc930afe9cd3ed9' => [Request],
        'Request@8838e1419cb74d9817eaa3331ed3c5c5' => [Request],
        'Response@b317e399aa6b60d818a4b4cfb1515130' => [Response],
        'Response@313dde76fdf9e66fab8ee19ebb31040c' => [Response],
        'Response@df090244005a056a94ebd1b0c8a9b621' => [Response],
        'Response@ae0dbaaa79707299453565df52d3aade' => [Response],
        'Response@d8660cd0d61da57bb8f493d13d6dd2bb' => [Response],
        'Response@9d4a8a0863ee7667f227c8c8e8aa5e64' => [Response],
        'Response@543515df27398f5390a4ae59bdf03b3a' => [Response],
        'Response@335138890ae1c6c5ad31f0cf756ee2d1' => [Response],
        'Response@f18fa5cf407fb6dce35fce4d454e6d82' => [Response],
        'Response@eb6f0b75980cf7d3e2b522da77e6de87' => [Response],
        'Request@75046eab60e41399822b3183d545dc91' => [Request],
        'Request@6033eff16576ea1c6ceafc8c486eefaa' => [Request],
        'Request@1a67352eed6398940a746d25d91c3bc2' => [Request],
        'Request@743d952b5c036faae029b11080aac8df' => [Request],
        'Request@5ee73998ea3a662384208d5473ae15b2' => [Request],
        'Request@996d4bce911ac0c61b2dc7744826981f' => [Request],
        'Request@ffe10755679f10137b81d847ab784fd9' => [Request],
        'Request@05e3557e66aae379fbf2b863916bf777' => [Request],
        'Request@85a7bf89a38b73c3053f2c81dec9a643' => [Request],
        'Request@43fe06a02bf6aa93058606210706764b' => [Request],
        'Request@2ccf5893fe498f2c033582de6f270983' => [Request],
        'Request@a794737e74c23d7aaa61edfa7645cde4' => [Request],
        'Request@982cc60c0d9046408771b2e2211d3454' => [Request],
        'Request@4f5bfe416aede630354817875153be10' => [Request],
        'Request@4be771d880bf157da72749f2b1628f94' => [Request],
        'Request@d0208ac30be7cffa284374b5d856ddaf' => [Request],
        'Request@8fe624b42de51fb2b14f8a0faa6bc650' => [Request],
        'Request@8af257ef9a062e11e5d596e848468d1c' => [Request],
        'Request@d41294dcf6b49204a4df2c391017b804' => [Request],
        'Request@e5dbd7e83c9ca54a4c63bc865da39d73' => [Request],
        'Request@03617765fe20a5f3b6f937dd126fc985' => [Request],
        'Request@b7d35285d1bdfe582a2c2456826074cc' => [Request],
        'Request@1c8ed18bc34e402afe0269e1c9d8a3b3' => [Request],
        'Request@613210c75301ffa7abd142643cc1d253' => [Request],
        'Request@7f4ab4368272d438e17f943b5d9684e1' => [Request],
        'Request@a7259003a80e5d8c254c2ead64dad22d' => [Request],
        'Request@2f4fb807e0649ce62fd72061cc767550' => [Request],
        'Request@628da877e6d502a528ffbe52a0a6eb45' => [Request],
        'Request@3c76b721834ae2881ce0fc2c6e813d2b' => [Request],
        'Request@619f0134530ed2772adc72fcc08c4d1b' => [Request],
        'Request@20954069abd08f982e9aee1e39c025d0' => [Request],
        'Request@cd951401044c32ad51ac2914e5aa8207' => [Request],
        'Response@a6016184cb7ab77154105bac29677b6c' => [Response],
        'Response@fac027edc30d42e3ad82b79a1a3d32e8' => [Response],
        'Response@c8b0c79309086b95599e1fd385bd44b0' => [Response],
        'Response@17a56bf4c46a5e68d8725a5c0baa3773' => [Response],
        'Response@16fbd6ca013118594751fcb14789194c' => [Response],
        'Response@2d0d87f63d2f89f8873781e68db0a084' => [Response],
        'Response@34ca56d77a1a560ac543ada5bcccbfae' => [Response],
        'Response@a0dd4cbf2ecc01224588fc3bb3757b7a' => [Response],
        'Response@07ac542aa66e14198d82bdf4ab5ca5c0' => [Response],
        'Response@aea966112a0b778f1b4a879c73e9a7ff' => [Response],
        'Response@c9940c3fe257ee679b2b8e93cf58f4a3' => [Response],
        'Response@9d4a90638a7e6522ca51cd478955ac4c' => [Response],
        'Response@8624d630767ae1a7a39fe4bcdb7696a1' => [Response],
        'Response@2658f711f4c85afc3ac85d690017ac66' => [Response],
        'Response@acdbaa8f6f88f120f2a00ed6a18b1165' => [Response],
        'Response@f5ad966d9de5ad4ac1745b52d0e1f017' => [Response],
        'Response@464e297cf93fb77ae36d3571330df50e' => [Response],
        'Response@c49f671a5e0bf399515674a609243fcc' => [Response],
        'Response@89df1b7347e01e50a92aeb8a866cab6b' => [Response],
        'Response@500eb23d7cf51f18b3004edd73f5dcc7' => [Response],
        'Response@09a4d531ab12ad399c01c3c003add810' => [Response],
        'Response@4290d1aafb4d70ba3305fdecf48df0f7' => [Response],
        'Response@39781cfe8ea6dad2b0a284f53deab3cb' => [Response],
        'Response@8485a9bfb4d249c84a99f11726650331' => [Response],
        'Response@f086397f66a185548b9de79ebf8cffc3' => [Response],
        'Response@53c6c9774735fd68c47028069f01eb80' => [Response],
        'Response@a7af1077e5ad6a09fb2a2720f1d5061a' => [Response],
        'Response@b2f710371970d75a3a56d3a5e9c67ae2' => [Response],
        'Response@600ed5a4e4d43e5e2deaeb30a4cc8e20' => [Response],
        'Response@9cf95cb1e05915be0dc8bf57cec127ef' => [Response],
        'Response@331ebdec89bb56d352430999b4275f25' => [Response],
        'Response@3da4de393b7d181ea814e7ddc816de53' => [Response]
      },
      _waitingForObject: Map {},
      onmessage: [Function],
      _lastId: 6,
      _callbacks: Map { 6 => [Object] },
      _rootObject: Root {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: [Map],
        _connection: [Circular],
        _type: '',
        _guid: '',
        _parent: undefined,
        _channel: [EventEmitter],
        _initializer: {}
      }
    },
    _type: 'Page',
    _guid: 'Page@800de9d999e3d3866d420ac6da05e88b',
    _parent: ChromiumBrowserContext {
      _events: [Object: null prototype] { close: [Function] },
      _eventsCount: 1,
      _maxListeners: 0,
      _objects: Map {
        'Frame@e520b5a72088586b18afff431da8400a' => [Frame],
        'Page@800de9d999e3d3866d420ac6da05e88b' => [Circular]
      },
      _connection: Connection {
        _objects: [Map],
        _waitingForObject: Map {},
        onmessage: [Function],
        _lastId: 6,
        _callbacks: [Map],
        _rootObject: [Root]
      },
      _type: 'BrowserContext',
      _guid: 'BrowserContext@17038b07009edb20dc99dfb192c30b7a',
      _parent: ChromiumBrowser {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: 0,
        _objects: [Map],
        _connection: [Connection],
        _type: 'Browser',
        _guid: 'Browser@b61add0663c90e5aa6b77fa13b00c289',
        _parent: [Root],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _contexts: [Set],
        _isConnected: true,
        _isRemote: true,
        _closedPromise: [Promise]
      },
      _logger: undefined,
      _channel: EventEmitter {
        _events: [Object: null prototype],
        _eventsCount: 6,
        _maxListeners: undefined,
        _object: [Circular]
      },
      _initializer: { isChromium: true },
      _pages: Set { [Circular] },
      _routes: [],
      _browser: ChromiumBrowser {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: 0,
        _objects: [Map],
        _connection: [Connection],
        _type: 'Browser',
        _guid: 'Browser@b61add0663c90e5aa6b77fa13b00c289',
        _parent: [Root],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _contexts: [Set],
        _isConnected: true,
        _isRemote: true,
        _closedPromise: [Promise]
      },
      _bindings: Map {},
      _timeoutSettings: TimeoutSettings {
        _defaultTimeout: null,
        _defaultNavigationTimeout: null,
        _parent: undefined
      },
      _options: {
        sdkLanguage: 'javascript',
        acceptDownloads: true,
        viewport: undefined,
        noDefaultViewport: false,
        extraHTTPHeaders: undefined,
        storageState: undefined
      },
      _closedPromise: Promise { <pending> },
      _backgroundPages: Set {},
      _serviceWorkers: Set {},
      _isChromium: true,
      _ownerPage: [Circular]
    },
    _logger: undefined,
    _channel: EventEmitter {
      _events: [Object: null prototype] {
        bindingCall: [Function],
        close: [Function],
        console: [Function],
        crash: [Function],
        dialog: [Function],
        domcontentloaded: [Function],
        download: [Function],
        fileChooser: [Function],
        frameAttached: [Function],
        frameDetached: [Function],
        load: [Function],
        pageError: [Function],
        popup: [Function],
        request: [Function],
        requestFailed: [Function],
        requestFinished: [Function],
        response: [Function],
        route: [Function],
        video: [Function],
        webSocket: [Function],
        worker: [Function]
      },
      _eventsCount: 21,
      _maxListeners: undefined,
      _object: [Circular]
    },
    _initializer: {
      mainFrame: EventEmitter {
        _events: [Object: null prototype],
        _eventsCount: 2,
        _maxListeners: undefined,
        _object: [Frame]
      },
      viewportSize: { width: 1280, height: 720 },
      isClosed: false
    },
    _frames: Set {
      Frame {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0,
        _objects: Map {},
        _connection: [Connection],
        _type: 'Frame',
        _guid: 'Frame@e520b5a72088586b18afff431da8400a',
        _parent: [ChromiumBrowserContext],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _parentFrame: null,
        _url: 'https://spacepencil.co.uk/',
        _name: '',
        _detached: false,
        _childFrames: Set {},
        _eventEmitter: [EventEmitter],
        _loadStates: [Set],
        _page: [Circular]
      }
    },
    _workers: Set {},
    _closed: false,
    _routes: [],
    coverage: ChromiumCoverage {
      _channel: EventEmitter {
        _events: [Object: null prototype],
        _eventsCount: 21,
        _maxListeners: undefined,
        _object: [Circular]
      }
    },
    _bindings: Map {},
    _isPageCall: false,
    _video: null,
    _browserContext: ChromiumBrowserContext {
      _events: [Object: null prototype] { close: [Function] },
      _eventsCount: 1,
      _maxListeners: 0,
      _objects: Map {
        'Frame@e520b5a72088586b18afff431da8400a' => [Frame],
        'Page@800de9d999e3d3866d420ac6da05e88b' => [Circular]
      },
      _connection: Connection {
        _objects: [Map],
        _waitingForObject: Map {},
        onmessage: [Function],
        _lastId: 6,
        _callbacks: [Map],
        _rootObject: [Root]
      },
      _type: 'BrowserContext',
      _guid: 'BrowserContext@17038b07009edb20dc99dfb192c30b7a',
      _parent: ChromiumBrowser {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: 0,
        _objects: [Map],
        _connection: [Connection],
        _type: 'Browser',
        _guid: 'Browser@b61add0663c90e5aa6b77fa13b00c289',
        _parent: [Root],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _contexts: [Set],
        _isConnected: true,
        _isRemote: true,
        _closedPromise: [Promise]
      },
      _logger: undefined,
      _channel: EventEmitter {
        _events: [Object: null prototype],
        _eventsCount: 6,
        _maxListeners: undefined,
        _object: [Circular]
      },
      _initializer: { isChromium: true },
      _pages: Set { [Circular] },
      _routes: [],
      _browser: ChromiumBrowser {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: 0,
        _objects: [Map],
        _connection: [Connection],
        _type: 'Browser',
        _guid: 'Browser@b61add0663c90e5aa6b77fa13b00c289',
        _parent: [Root],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _contexts: [Set],
        _isConnected: true,
        _isRemote: true,
        _closedPromise: [Promise]
      },
      _bindings: Map {},
      _timeoutSettings: TimeoutSettings {
        _defaultTimeout: null,
        _defaultNavigationTimeout: null,
        _parent: undefined
      },
      _options: {
        sdkLanguage: 'javascript',
        acceptDownloads: true,
        viewport: undefined,
        noDefaultViewport: false,
        extraHTTPHeaders: undefined,
        storageState: undefined
      },
      _closedPromise: Promise { <pending> },
      _backgroundPages: Set {},
      _serviceWorkers: Set {},
      _isChromium: true,
      _ownerPage: [Circular]
    },
    _timeoutSettings: TimeoutSettings {
      _defaultTimeout: null,
      _defaultNavigationTimeout: null,
      _parent: TimeoutSettings {
        _defaultTimeout: null,
        _defaultNavigationTimeout: null,
        _parent: undefined
      }
    },
    accessibility: Accessibility {
      _channel: EventEmitter {
        _events: [Object: null prototype],
        _eventsCount: 21,
        _maxListeners: undefined,
        _object: [Circular]
      }
    },
    keyboard: Keyboard {
      _channel: EventEmitter {
        _events: [Object: null prototype],
        _eventsCount: 21,
        _maxListeners: undefined,
        _object: [Circular]
      }
    },
    mouse: Mouse {
      _channel: EventEmitter {
        _events: [Object: null prototype],
        _eventsCount: 21,
        _maxListeners: undefined,
        _object: [Circular]
      }
    },
    touchscreen: Touchscreen {
      _channel: EventEmitter {
        _events: [Object: null prototype],
        _eventsCount: 21,
        _maxListeners: undefined,
        _object: [Circular]
      }
    },
    _mainFrame: Frame {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: 0,
      _objects: Map {},
      _connection: Connection {
        _objects: [Map],
        _waitingForObject: Map {},
        onmessage: [Function],
        _lastId: 6,
        _callbacks: [Map],
        _rootObject: [Root]
      },
      _type: 'Frame',
      _guid: 'Frame@e520b5a72088586b18afff431da8400a',
      _parent: ChromiumBrowserContext {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: 0,
        _objects: [Map],
        _connection: [Connection],
        _type: 'BrowserContext',
        _guid: 'BrowserContext@17038b07009edb20dc99dfb192c30b7a',
        _parent: [ChromiumBrowser],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _pages: [Set],
        _routes: [],
        _browser: [ChromiumBrowser],
        _bindings: Map {},
        _timeoutSettings: [TimeoutSettings],
        _options: [Object],
        _closedPromise: [Promise],
        _backgroundPages: Set {},
        _serviceWorkers: Set {},
        _isChromium: true,
        _ownerPage: [Circular]
      },
      _logger: undefined,
      _channel: EventEmitter {
        _events: [Object: null prototype],
        _eventsCount: 2,
        _maxListeners: undefined,
        _object: [Circular]
      },
      _initializer: { url: 'about:blank', name: '', loadStates: [Array] },
      _parentFrame: null,
      _url: 'https://spacepencil.co.uk/',
      _name: '',
      _detached: false,
      _childFrames: Set {},
      _eventEmitter: EventEmitter {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: 0
      },
      _loadStates: Set { 'domcontentloaded', 'load' },
      _page: [Circular]
    },
    _viewportSize: { width: 1024, height: 768 },
    pdf: [Function],
    _ownedContext: ChromiumBrowserContext {
      _events: [Object: null prototype] { close: [Function] },
      _eventsCount: 1,
      _maxListeners: 0,
      _objects: Map {
        'Frame@e520b5a72088586b18afff431da8400a' => [Frame],
        'Page@800de9d999e3d3866d420ac6da05e88b' => [Circular]
      },
      _connection: Connection {
        _objects: [Map],
        _waitingForObject: Map {},
        onmessage: [Function],
        _lastId: 6,
        _callbacks: [Map],
        _rootObject: [Root]
      },
      _type: 'BrowserContext',
      _guid: 'BrowserContext@17038b07009edb20dc99dfb192c30b7a',
      _parent: ChromiumBrowser {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: 0,
        _objects: [Map],
        _connection: [Connection],
        _type: 'Browser',
        _guid: 'Browser@b61add0663c90e5aa6b77fa13b00c289',
        _parent: [Root],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _contexts: [Set],
        _isConnected: true,
        _isRemote: true,
        _closedPromise: [Promise]
      },
      _logger: undefined,
      _channel: EventEmitter {
        _events: [Object: null prototype],
        _eventsCount: 6,
        _maxListeners: undefined,
        _object: [Circular]
      },
      _initializer: { isChromium: true },
      _pages: Set { [Circular] },
      _routes: [],
      _browser: ChromiumBrowser {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: 0,
        _objects: [Map],
        _connection: [Connection],
        _type: 'Browser',
        _guid: 'Browser@b61add0663c90e5aa6b77fa13b00c289',
        _parent: [Root],
        _logger: undefined,
        _channel: [EventEmitter],
        _initializer: [Object],
        _contexts: [Set],
        _isConnected: true,
        _isRemote: true,
        _closedPromise: [Promise]
      },
      _bindings: Map {},
      _timeoutSettings: TimeoutSettings {
        _defaultTimeout: null,
        _defaultNavigationTimeout: null,
        _parent: undefined
      },
      _options: {
        sdkLanguage: 'javascript',
        acceptDownloads: true,
        viewport: undefined,
        noDefaultViewport: false,
        extraHTTPHeaders: undefined,
        storageState: undefined
      },
      _closedPromise: Promise { <pending> },
      _backgroundPages: Set {},
      _serviceWorkers: Set {},
      _isChromium: true,
      _ownerPage: [Circular]
    }
  }
```
</details>

**Comment by dgozman** [comment] 2021-07-30 13:57
@LeanSaucecode Thank you for the issue. Unfortunately, I cannot understand what the problem is. I see a very limited snippet, so I cannot just run it and reproduce the issue myself. But what do you expect to happen and what happens instead? Does Playwright throw any errors? Please describe the issue in more detaiils.

**Comment by LeanSaucecode** [comment] 2021-07-30 14:11
Is it possible to register an Event within the scope of an Iframe?

Here is a use case that does not work for me.
1. Open this website using playwright.
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_a_download
2. Target the iframe on the right hand side inside the website *Selector*
: #iframeResult
3. Register a download event using the page.waitForEvent function
4. Click on the w3Schools logo. *Selector*: body > p:nth-child(3) > a

I get the following error. *pageCtx.waitForEvent is not a function*

Kind Regards,
[image: SauceCode] <https://saucecode.tech/>
Lean van der merwe
Developer

E: ***@***.*** | W: saucecode.tech
The company accepts no liability for the content of this email, or for the
consequences of any actions taken on the basis of the information provided,
unless that information is subsequently confirmed in writing. If you are
not the intended recipient you are notified that disclosing, copying,
distributing or taking any action in reliance on the contents of this
information is strictly prohibited.

**Comment by LeanSaucecode** [comment] 2021-07-30 14:12
Is it possible to register an Event within the scope of an Iframe? 

Here is a use case that does not work for me.
1. Open this website using playwright.  https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_a_download
2. Target the iframe on the right hand side inside the website **Selector**: `#iframeResult`
3. Register a download event using the page.waitForEvent function 
4. Click on the w3Schools logo. **Selector**: `body > p:nth-child(3) > a`

I get the following error. `pageCtx.waitForEvent is not a function`

**Comment by dgozman** [comment] 2021-07-30 15:25
@LeanSaucecode Thank you for the details, now this is clear to me. There is no way to register an event listener in the scope of a frame. Sounds like a reasonable feature!

**Comment by pavelfeldman** [comment] 2022-01-01 23:41
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-01-01 23:41 UTC
Labels: P3-collecting-feedback
