### ISSUE TITLE
Cookie issue while trying to navigate and causing session timeout

### ISSUE THREAD

**Issue by Neha-test-dev** [microsoft/playwright#18163] opened 2022-10-18 21:42 UTC
**What is your Scenario?**
The test has to navigate to purchase template and navigate to a different page to view the purchase. The page displays a session timeout issue after navigating successfully. It seems to be that the Playwright tool is probably not retaining the cookies.
**What is your public website URL?** 
https://mailchimp.com/login
**What is your Playwright test code?**
```js
test.beforeEach(async ({ page, context }) => {
    account = await internalAPIClient.createInternalAccount();
   await internalAPIClient.applyPrimaryPlan('standard_monthly_plan_v0', 500);
});

test('Verify user can purchase an email template on Marketplace page', async ({
    page,context
  }) => {
    await page.goto('https://mailchimp.com/marketplace/');
    // Navigate to Marketplace Page
    await marketPlacePage.selectCategory('Email Templates');
    await marketPlacePage.searchText('welcome');
    await expect(templatesPage.pageHeading).toContainText(
      'Premium Email Templates',
    );
   await templatesPage.selectTemplate();
    await expect(templatesPage.purchasePageHeading).toContainText(
      'A Personal Welcome Email',
    );
    await templatesPage.purchaseTemplate();
    await page.goto('/');
    await context.addCookies(cookies);
    await page.goto('/');
    loginPage = new LoginPage(page);
    await loginPage.login(account.username, account.password);
    await context.addCookies(cookies);
    await productsPage.paywall.enterCVVOnly();
    await productsPage.paywall.clickPayNow();
    await productsPage.paywall.waitForPaymentToProcess();
    await templatesPage.viewTemplatePurchaseOption();
    await templatesPage.verifyTemplatePurchase();
  });
});
```

**Steps to Reproduce**
Pre- steps: Log in (I'm unable to provide you with an account, but you can create free accounts)
1. Launch the marketplace url as mentioned in the code
2. Search of an email template 
3.  Select a template
4. Purchase the template
5. Enter cvv for purchasing
6. Click on "View Templates"
7. Click on "Purchased" Tab to verify purchase

**Playwright version :**
 "^1.23.4"

**Node.js version**
14.17.2

**Browser name(s) and version(s)**
Chromium Version 104.0.5112.20

**Platform(s) and version(s)**
macOS 11.7

Note - This flow works fine when done manually or with another automation tool

**Screenshot and Zip file of the Playwright trace:**
<img width="1431" alt="Screen Shot 2022-10-18 at 5 34 38 PM" src="https://user-images.githubusercontent.com/69609898/196549435-4e04a9dd-d6ee-46bc-907e-19314f9027d9.png">
7bd9a50f015360ab2d10e3ac9fb7e9ed8aecbef4.zip
6d6da856dd12f48b73c3239f6d9f2c95127859a6.zip
07efbdd0049ea2a46217e341bf1af381c88f9938.zip
0f8c796c1bc9d1e5b66b42dedf19b6c75def0309.zip
4101b3734eb08ccb2922d1a1d0e494474252620b.zip
8ee0215c953dbf30f3d05ed087d2d3026b3c0a5e.zip

**Comment by dgozman** [comment] 2022-10-19 22:01
@Neha-test-dev Unfortunately, I cannot run repro scenario that requires purchasing a template. If you could create a publicly accessible repro that does not require purchasing templates, we will look into it.

**Comment by Vivek-Kini** [comment] 2022-10-21 14:04
I have a similar issue which happens only on `chromium` where the context (session cookie) is lost when navigating from one page to other page (because of a click event). My scenario is working fine on Firefox using Playwright. Trying to provide a scenario (reproducible steps) to share here to further assess.

**Comment by Neha-test-dev** [comment] 2022-10-21 16:17
So the session timeout page is displayed only in the flow where one makes a purchase. I have tried to use a free template and with this flow, the tool is unable to recognize the element after navigating to the Templates page. It throws a timeout message -"Timeout of 180000ms exceeded." though the element is present.

**Comment by mxschmitt** [comment] 2022-10-26 20:55
Closing since we need a minimal repro to act on it. Please re-file an issue with a repro which does not require a login or complex setup to run. Optimal would be a single file.

**Closed by mxschmitt** 2022-10-26 20:55 UTC
Labels: triaging
