### ISSUE TITLE
[BUG] JUnit reporters use wrong path for screenshot attachment

### ISSUE THREAD

**Issue by alexprey** [microsoft/playwright#24322] opened 2023-07-20 11:21 UTC
### System info
- Playwright Version: [v1.36.1]
- Operating System: [Windows 10]
- Browser: [All]
- Other info:

### Source code

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
    reporter: [
        ['html'],
        ['junit', { outputFile: './junit-report.xml' }],
        [process.env.CI ? 'dot' : 'list'],
    ],
    use: {
        /* Base URL to use in actions like `await page.goto('/')`. */
        // baseURL: 'http://127.0.0.1:3000',
        baseURL: baseUrl,

        /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
        trace: 'on-first-retry',
        screenshot: 'only-on-failure',
    },
});
```

**JUnit report**

```xml
<system-out>
<![CDATA[
[[ATTACHMENT|..\test-results\partner-auth-Partner-AuthPage-When-page-opened-then-Submit-button-should-be-disabled-chromium\test-failed-1.png]]

[[ATTACHMENT|..\test-results\partner-auth-Partner-AuthPage-When-page-opened-then-Submit-button-should-be-disabled-chromium\test-failed-2.png]]
]]>
</system-out>
```

**Steps**
- Run test that fails
- Open result JUnit file and check attachment path

**Expected**

- File with junit stored at `junit-report.xml`
- Screenshots stored at `test-results/*`
- Attahment path in JUNIT are relative and targets to `/test-results`

I expect relative path to screenshot based on actual path to junit-report file. I need relative path without back navigation `../` to correct usage it with gitlab

**Actual**

- File with junit stored at `junit-report.xml`
- Screenshots stored at `test-results/*`
- Attahment path in JUNIT are relative and targets to `../test-results`

**Comment by aslushnikov** [comment] 2023-07-20 14:14
@alexprey I cannot reproduce this.

I have the following config:

```ts
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  reporter: [
    ['html'],
    ['junit', { outputFile: './junit-report.xml' }],
    [process.env.CI ? 'dot' : 'list'],
  ],
});
```

and the following test:

```ts
// a.spec.ts
import { test } from '@playwright/test';

test('should work', async ({ }) => {
  await test.info().attach('foobar', { path: __filename, contentType: 'text/plain' });
});
```

And this yields me the following report:

```xml
<testsuites id="" name="" tests="1" failures="0" skipped="0" errors="0" time="0.38604800003767015">
<testsuite name="a.spec.ts" timestamp="2023-07-20T14:12:30.804Z" hostname="" tests="1" failures="0" skipped="0" time="0.015" errors="0">
<testcase name="should work" classname="a.spec.ts" time="0.015">
<system-out>
<![CDATA[
[[ATTACHMENT|test-results/a-should-work/attachments/foobar-2ef80c1e751e132d3c50c7ad6597250531cf314c.ts]]
]]>
</system-out>
</testcase>
</testsuite>
</testsuites>
```

Can you try this and see if it works? How do I reproduce your issue?

**Comment by alexprey** [comment] 2023-07-21 05:16
@aslushnikov I mean the case when test fails, and screenshots created automatically by playwright. I'm not attach any info or screenshots manually.

**Comment by jgreffe** [comment] 2023-09-11 13:31
Seems related to this: https://github.com/microsoft/playwright/blob/main/packages/playwright/src/reporters/junit.ts#L193C54-L193C54
Is there any way to manually configure `this.config.rootDir` ?

**Comment by dgozman** [comment] 2023-09-22 21:20
Fixed by #27024.

**Closed by dgozman** 2023-09-22 21:20 UTC
Labels: v1.39

**Comment by jgreffe** [comment] 2023-10-30 15:21
With last changes https://github.com/microsoft/playwright/pull/27024, is there any way to get the path from `this.config.configFile` ?

We now have relative paths in `ATTACHMENT`:

```
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  //testDir: 'tests', // do not use if junit reporter and attachments paths needed
  testMatch: 'tests/**/*.spec.ts', // rather use this glob declaration,
  outputDir: 'target/test-reports',
  reporter: ['junit', { outputFile: 'target/test-reports/report.xml }
});
```
And junit report has:
```
<system-out>
<![CDATA[
[[ATTACHMENT|the-test/test-failed-1.png]]
]]>
</system-out>
```

I would expect junit report to be:
```
<system-out>
<![CDATA[
[[ATTACHMENT|target/test-reports/the-test/test-failed-1.png]]
]]>
</system-out>
```

**Comment by jgreffe** [comment] 2023-10-31 08:07
cc @dgozman 🙏🏼

**Comment by dgozman** [comment] 2023-11-02 20:51
@jgreffe This is not possible today, please file a feature request.

**Comment by mathiasarens** [comment] 2024-09-23 12:00
@jgreffe Did you create a feature request?

**Comment by mathiasarens** [comment] 2024-09-23 12:02
@jgreffe Did you file a feature request?
