### ISSUE TITLE
[BUG] Object with guid ${arg.guid} was not bound in the connection

### ISSUE THREAD

**Issue by regseb** [microsoft/playwright#21210] opened 2023-02-26 10:05 UTC
**Context:**
- Playwright Version: 1.31.1
- Operating System: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
- Node.js version: 18.14.2
- Browser: chromium, firefox, webkit

**Code Snippet**

```JSON
{
    "name": "testcase",
    "version": "1.0.0",
    "type": "module",
    "dependencies": {
        "@cliqz/adblocker-playwright": "1.26.0",
        "playwright": "1.31.1"
    }
}
```

```javascript
import playwright from "playwright";
import { PlaywrightBlocker } from "@cliqz/adblocker-playwright";

for (let i = 0; i < 10; ++i) {
    console.log(i);
    console.log("playwright.chromium.launch");
    const browser = await playwright.chromium.launch({ slowMo: 250 });
    console.log("browser.newContext");
    const context = await browser.newContext();
    console.log("context.newPage");
    const page = await context.newPage();
    console.log("PlaywrightBlocker.fromPrebuiltAdsAndTracking");
    const blocker = await PlaywrightBlocker.fromPrebuiltAdsAndTracking(fetch);
    console.log("blocker.enableBlockingInPage");
    blocker.enableBlockingInPage(page);
    console.log("page.goto");
    await page.goto("https://playwright.dev/docs/api/class-browser");
    console.log("page.locator");
    await page.locator(`.table-of-contents a[href="#browser-version"]`).click();
    console.log("context.close");
    await context.close();
    console.log("browser.close");
    await browser.close();
}
```

**To reproduce**

```Shell
$ DEBUG=pw:browser* node index.js
```

```
0
playwright.chromium.launch
  pw:browser <launching> /home/regseb/.cache/ms-playwright/chromium-1048/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-ujpdI6 --remote-debugging-pipe --no-startup-window +0ms
  pw:browser <launched> pid=8608 +5ms
  pw:browser [pid=8608][err] [0226/110959.711135:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable. +139ms
browser.newContext
context.newPage
  pw:browser [pid=8608][err] [0226/110959.800062:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process. +86ms
PlaywrightBlocker.fromPrebuiltAdsAndTracking
blocker.enableBlockingInPage
page.goto
page.locator
context.close
browser.close
  pw:browser [pid=8608] <gracefully close start> +4s
  pw:browser [pid=8608] <process did exit: exitCode=0, signal=null> +24ms
  pw:browser [pid=8608] starting temporary directories cleanup +0ms
  pw:browser [pid=8608] finished temporary directories cleanup +5ms
  pw:browser [pid=8608] <gracefully close end> +0ms
1
playwright.chromium.launch
/home/regseb/dev/testcase/pw/node_modules/playwright-core/lib/client/connection.js:194
      if (!object) throw new Error(`Object with guid ${arg.guid} was not bound in the connection`);
                   ^

Error: Object with guid handle@5a97df632694a35736e115ea417364df was not bound in the connection
    at Connection._tChannelImplFromWire (/home/regseb/dev/testcase/pw/node_modules/playwright-core/lib/client/connection.js:194:26)
    at /home/regseb/dev/testcase/pw/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:129:20
    at /home/regseb/dev/testcase/pw/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:108:21
    at Connection.dispatch (/home/regseb/dev/testcase/pw/node_modules/playwright-core/lib/client/connection.js:153:26)
    at Immediate.<anonymous> (/home/regseb/dev/testcase/pw/node_modules/playwright-core/lib/inProcessFactory.js:46:83)
    at process.processImmediate (node:internal/timers:476:21)

Node.js v18.14.2
```

**Describe the bug**

When I was writing a test case to reproduce the problem, I had a more complex snippet and the error was coming to the `context.close()` of the first iteration. Then by simplifying the snippet, the error would arrive at the `browser.close()` still at the first iteration. Simplifying again, it now arrives at the `chromium.launch()` of the second iteration. If I remove `slowMo` or the `locator()`, there is no more error on the 10 iterations.

With Firefox, the error happens at the `browser.close()` of the second iteration.

**Related issue**

- https://github.com/microsoft/playwright/issues/20023

**Comment by pavelfeldman** [comment] 2023-02-27 16:32
We can only help with something we can reproduce locally, please send a short snippet that demonstrates the problem and we will help.

**Comment by pavelfeldman** [comment] 2023-02-28 20:08
I would assume this is due to the use of @cliqz/adblocker-playwright, you should raise this issue with them!

**Comment by pavelfeldman** [comment] 2023-03-02 18:34
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2023-03-02 18:34 UTC
Labels: triaging

**Comment by Tallyb** [comment] 2023-03-21 13:29
@pavelfeldman we do not use the blocker, and we still get it. 
tracing.start: Error: Object with guid page@8803b6570b83d4dc34d5eaafa7306fe9 was not bound in the connection

This occurs when running in VScode tests that contain loops such as 
```
for (const platform of ['web', 'mobile']) {
test(...)
```

A single test would run fine, but when running (green arrow) multiple tests this error occurs after 1 tests is passed. 
Macos Ventura 13.2.1
Node 18.15. 
Latest VSCode. 
PW 1.31.2

(note: some people at my team has encountered the same).

**Comment by MarkusJLechner** [comment] 2023-04-13 13:21
I get the same error without the `@cliqz/adblocker-playwright` package. I think it is misleading to point to the https://github.com/ghostery/adblocker/issues/3090#issuecomment-1505260086 issue.

```
Internal error: fixture integrity at serviceWorkers
Internal error: fixture integrity at timezoneId
Trace: Error thrown in fixture BookingSettingsPage.create()
    at Function.create (file:///home/p/fixtures/BasePage.ts:364:15)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:447:9)
    at Object.fn (file:///home/p/fixtures/baseFixtures.ts:80:18)

Error: Object with guid handle@f4e552575d14a0c84cca8b152a4069f7 was not bound in the connection

  1) [chromium] › test

    Error: Object with guid handle@f4e552575d14a0c84cca8b152a4069f7 was not bound in the connection
```

Maybe not related, but lately i also get a `Internal error` :thinking:

**Comment by regseb** [comment] 2023-12-21 10:59
I no longer have this bug since playwright [`v1.33.0`](https://github.com/microsoft/playwright/releases/tag/v1.33.0). See https://github.com/microsoft/playwright/issues/22210#issuecomment-1866045256

**Comment by felipeleonardobarm** [comment] 2024-01-10 14:29
Got this error in playwright v1.40.1, it happens consistently in my application every time I run it for a certain ammount of time

**Comment by mxschmitt** [comment] 2024-01-10 14:30
It should be fixed in Canary: https://playwright.dev/docs/canary-releases

**Comment by LucaDotti** [comment] 2024-01-10 22:05
Confirm the error in playwright v1.40.1 after it runs for some time. Will try the canary release and report here. Thanks!

**Comment by Thomega35** [comment] 2024-04-05 15:13
I just got it in playwright": {"version": "1.42.1"} hope a fix is comming soon
