### ISSUE TITLE
Playwright Test for VSCode doesn't work on mac

### ISSUE THREAD

**Issue by Yeya9742** [microsoft/playwright#23244] opened 2023-05-23 16:49 UTC
<img width="799" alt="Screen Shot 2023-05-24 at 4 48 56 AM" src="https://github.com/microsoft/playwright-vscode/assets/134428762/2cd67922-357e-4ac8-9adf-9aa0366f614d">
<img width="814" alt="Screen Shot 2023-05-24 at 4 49 09 AM" src="https://github.com/microsoft/playwright-vscode/assets/134428762/fb077b21-8784-473e-b250-a6c3443b70a4">

Node : v18.16.0
NPM: 9.5.1
Vs code version: Version: 1.78.2 
OS Monterrey

**Comment by dgozman** [comment] 2023-05-24 02:03
@Yeya9742  What is your Playwright version?

**Comment by dgozman** [comment] 2023-05-25 14:55
@williamzhuang Any chance you could share an example repository where this issue happens? That would greatly increase the chances of it being fixed.

**Comment by williamzhuang** [comment] 2023-05-26 19:19
@dgozman  Here's an example repository, I think the issue is that the extension won't find any tests when the directory structure is `packages/playwright-tests`. It seems to find them without issue when `playwright-tests` is not in a `packages` directory or when it isn't named `playwright-tests`. 

This seems like an unlucky coincidence on my part because it was named `packages/playwright-tests` in my monorepo. Notably, this naming used to work with the extension. For now, we can workaround by just renaming the package.

**Comment by kkruk1** [comment] 2023-05-31 11:39
It happens to me from time to time, usually the refresh button helps to load tests:
![image](https://github.com/microsoft/playwright/assets/23309692/e2abbb3e-1587-4719-866a-85f350d56184)

**Comment by mxschmitt** [comment] 2023-05-31 12:20
> @dgozman Here's an [example repository](https://github.com/williamzhuang/playwright-bug-demo), I think the issue is that the extension won't find any tests when the directory structure is `packages/playwright-tests`. It seems to find them without issue when `playwright-tests` is not in a `packages` directory or when it isn't named `playwright-tests`. This is shown via the example repo where only the `packages/some-other-tests` package works but `packages/playwright-tests` does not appear. <img alt="Screenshot 2023-05-26 at 12 20 06 PM" width="358" src="https://user-images.githubusercontent.com/17490376/241305387-357d82a6-aa9f-4bfd-bcb4-fe0eb56c8d9d.png">
> 
> This seems like an unlucky coincidence on my part because it was named `packages/playwright-tests` in my monorepo. Notably, this naming used to work with the extension. For now, we can workaround by just renaming the package.

Your issue is different, in your case we think we are the playwright repository and try to apply our dog fooding logic. As a workaround you can just rename playwright-tests to `playwright-e2e-tests`, I'll fix it in the next version.

**Comment by mxschmitt** [comment] 2023-05-31 15:24
Since the original bug reporter did not provide more details, I'm closing it for now. Please re-file with more information if you experience more bugs.

@williamzhuang you can use a dev version here with a fix for you: https://github.com/microsoft/playwright-vscode/wiki#installation-beta-version

**Closed by mxschmitt** 2023-05-31 15:24 UTC
Labels: triaging
