### ISSUE TITLE
[BUG] Getting "Please install @playwright/test package..." after upgrading from 1.34.0 to 1.34.1

### ISSUE THREAD

**Issue by mauricesnip** [microsoft/playwright#23228] opened 2023-05-23 08:20 UTC
### System info
- Playwright Version: v1.34.1
- Operating System: macOS 13.2.1
- Browser: N/A
- Other info: Terminal, CLI, Node 18.16.0 LTS

### Source code

**Config file**

```js
// playwright.config.js
const { defineConfig } = require('@playwright/test');

module.exports = defineConfig({
    preserveOutput: 'failures-only',
    snapshotPathTemplate: '{testDir}/__snapshots__/{testFilePath}/{arg}{ext}',
    testDir: './assets',
    use: {
        viewport: {
            width: 1440,
            height: 900,
        },
    },
});
```

**Test file (self-contained)**

Simple tests like:

```js
test('builds CSS correctly', () => {
    expect(fs.readFileSync(`${PUBLIC_PATH}${MANIFEST['build/app/app.css']}`, 'utf-8')).toMatchSnapshot();
});

test('renders homepage correctly', async ({ page }) => {
    await page.goto('<REMOVED_URL>');
    await expect(page).toHaveScreenshot({ fullPage: true });
});

// Etc...
```

**Steps**
- Run `npx playwright test` (executed by `yarn test`)

**Expected**

To start running tests by executing `npx playwright test`, like it did in previous versions (`1.34.0` and down).

**Actual**

Getting the following message:

```sh
➜ yarn test
Please install @playwright/test package to use Playwright Test.
  npm install -D @playwright/test
```

**Already rules out a few things**

1. Reinstalling `@playwright/test`
2. Completely removing `node_modules` and reinstalling with `yarn`
3. Works with `yarn add @playwright/test@1.34.0 -D`
4. Package `playwright` is not installed

**Comment by rothsandro** [comment] 2023-05-23 08:59
Duplicate of #23225

**Comment by dgozman** [comment] 2023-05-24 02:08
@mauricesnip Could you please share a repository where this happens? We believe this issue has been fixed in `v1.34.1` and `v1.34.2`, but you say it has regressed instead. It would be great to see the setup that leads to this!

**Comment by JoshuaKGoldberg** [comment] 2023-05-24 06:43
https://github.com/dylans/halfstackconf-next/tree/6f4f208b4e2e172fd7bd47e6543bcf50feed512f -> shows this issue https://github.com/dylans/halfstackconf-next/actions/runs/5065467209/jobs/9094073764:

```plaintext
> halfstackconf-next@0.1.0 test:ci /home/runner/work/halfstackconf-next/halfstackconf-next
> playwright test

Please install @playwright/test package to use Playwright Test.
  npm install -D @playwright/test
 ELIFECYCLE  Command failed with exit code 1.
```

...then uninstalling the `playwright` package fixed it: [dylans/halfstackconf-next@`e466ac7` (#65)](https://github.com/dylans/halfstackconf-next/pull/65/commits/e466ac7cb4548cb1912a2634faaf3b1bdf4abdff) -> https://github.com/dylans/halfstackconf-next/actions/runs/5065495755/jobs/9094128846?pr=65 ✅ 

```shell
# For npm users: npm rm playwright
pnpm rm playwright`
```

@cyrilletuzi's https://github.com/Microsoft/playwright/issues/6981#issuecomment-857499483 was what fixed it. Thanks!

**Comment by mauricesnip** [comment] 2023-05-24 08:22
> @mauricesnip Could you please share a repository where this happens? We believe this issue has been fixed in `v1.34.1` and `v1.34.2`, but you say it has regressed instead. It would be great to see the setup that leads to this!

@dgozman Sure thing! In my case, the issue actually started from `1.34.1` and up. I've added a reduced test case which is using `1.34.2`. See README for details: https://github.com/mauricesnip/23228-playwright-test-case

**Comment by sarink** [comment] 2023-05-24 18:38
👍 also seeing this issue

**Comment by aslushnikov** [comment] 2023-05-25 00:13
Hey all, please update to 1.34.3 release that fixes this!

**Closed by aslushnikov** 2023-05-25 00:13 UTC
Labels: P1-resolve-asap, v1.34

**Comment by gaaliche** [comment] 2023-05-25 11:18
The issue is still there
```sh
❯ y test:Chrome                                                                                                           
yarn run v1.22.19                                                                                                         
$ playwright test --project='Desktop Chrome'                                                                              
Please install @playwright/test package to use Playwright Test.
  npm install -D @playwright/test
```
the package was updated to the latest
```sh
❯ y list --pattern @playwright/test                                                                                       
yarn list v1.22.19                                                                                                        
└─ @playwright/test@1.34.3  
```

**Comment by thekp** [comment] 2023-05-25 11:58
Hi, I'm also still facing this issue.

```
$ node -v
v19.4.0

$ yarn -v
1.22.19

$ yarn list --pattern @playwright/test
yarn list v1.22.19
└─ @playwright/test@1.34.3
```

Also, I tried using an older version of `@playwright/test` and `playwright` at version `1.33.0` but I still got the same error when trying to run `playwright test` locally:
```
Please install @playwright/test package to use Playwright Test.
  npm install -D @playwright/test
```

**Comment by aslushnikov** [comment] 2023-05-25 16:36
@gaaliche @thekp could you please file separately? It might be something else is going on; a repro would go a long way!

**Comment by zgordan-vv** [comment] 2023-06-04 08:51
Upgrading to @playwright/test@1.34.3 didn't help as well. Playwright is not installed, only @playwright-chromium@1.34.3.
`yarn -v
1.22.19
node -v
v16.20.0`

**Comment by voodoocreation** [comment] 2023-06-19 23:35
What seemed to fix this for me was to ensure that `@playwright/test` was installed, plus ensuring that `playwright` was removed from the project's direct dependencies - I think having both packages installed may have been the cause in my case.

**Comment by RonyFluk-checksum** [comment] 2023-08-14 08:47
Getting this error as well.
What about projects that use both the `playwright/test` and the `playwright` packages?
