### ISSUE TITLE
[BUG] Playwright crashes in Docker container on Mac with Intel processor

### ISSUE THREAD

**Issue by eliaslm** [microsoft/playwright#28900] opened 2024-01-05 14:40 UTC
### System info
- Playwright Version: v1.40.0
- Operating System: macOS 14.2.1
- Browser: Chromium
- Other info: Docker version 24.0.6, build ed223bc

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto("http://playwright.dev")
    print(page.title())
    browser.close()
```

**Steps**
- I'm on a Mac with an Intel i5 processor (no GPU). I then start a docker container based on the official Playwright Python image:

  ```
  docker run -it --rm --ipc=host mcr.microsoft.com/playwright/python:v1.40.0-jammy /bin/bash
  ```
- Install playwright: `pip install playwright==1.40.0`
- Then run the [get started example](https://playwright.dev/python/docs/library#usage) (in the test file above)

**Expected**

I expect it to print the title of the "http://playwright.dev" page.

**Actual**

It crashes, with error message:
```
Traceback (most recent call last):
  File "//get_started.py", line 5, in <module>
    page = browser.new_page()
  File "/usr/local/lib/python3.10/dist-packages/playwright/sync_api/_generated.py", line 14510, in new_page
    self._sync(
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_browser.py", line 178, in new_page
    return await self._connection.wrap_api_call(inner)
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_connection.py", line 492, in wrap_api_call
    return await cb()
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_browser.py", line 173, in inner
    page = await context.new_page()
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_browser_context.py", line 286, in new_page
    return from_channel(await self._channel.send("newPage"))
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_connection.py", line 62, in send
    return await self._connection.wrap_api_call(
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_connection.py", line 487, in wrap_api_call
    return await cb()
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_connection.py", line 100, in inner_send
    result = next(iter(done)).result()
playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed
```
Occasionally (not exactly sure why or when it appears), I get the browser logs:
```
TargetClosedError: Target page, context or browser has been closed
Browser logs:

<launching> /ms-playwright/chromium-1091/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-hjseJo --remote-debugging-pipe --no-startup-window
<launched> pid=138
[pid=138][err] Received signal 11Received signal  <unknown> 559122749008
[pid=138][err] 11 <unknown> 555d33950008
[pid=138][err] #0 0x555d2cb87572 #0 0x55911b980572 base::debug::CollectStackTrace()base::debug::CollectStackTrace()
[pid=138][err] #
[pid=138][err] 1#1 0x 555d2cb73f43 0x55911b96cf43 base::debug::StackTrace::StackTrace()base::debug::StackTrace::StackTrace()
[pid=138][err] #
[pid=138][err] 2# 20x 55911b97ff910x555d2cb86f91  base::debug::(anonymous namespace)::StackDumpSignalHandler()
[pid=138][err] microsoft/playwright-python#3 0x7fac04ad4520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
[pid=138][err] microsoft/playwright-python#4 0x55911ad1e2ab base::debug::(anonymous namespace)::StackDumpSignalHandler()
[pid=138][err] microsoft/playwright-python#3 0x7fce0105d520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
[pid=138][err] microsoft/playwright-python#4 0x555d2bf252ab content::RunContentProcess()
[pid=138][err] microsoft/playwright-python#5 0x55911ad1e64d content::RunContentProcess()
[pid=138][err] microsoft/playwright-python#5 0x555d2bf2564d content::ContentMain()content::ContentMain()
[pid=138][err] 
[pid=138][err] ##6 60x 55911b3c28fa0x 555d2c5c98fa headless::HeadlessShellMain()
[pid=138][err] microsoft/playwright-python#7 0x55911710a25a headless::HeadlessShellMain()
[pid=138][err] microsoft/playwright-python#7 0x555d2831125a ChromeMain
[pid=138][err] microsoft/playwright-python#8 0x7fce01044d90 ChromeMain
[pid=138][err] microsoft/playwright-python#8 0x7fac04abbd90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
[pid=138][err] microsoft/playwright-python#9 0x7fce01044e40 __libc_start_main
[pid=138][err] microsoft/playwright-python#10 0x555d2831102a (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
[pid=138][err] microsoft/playwright-python#9 0x7fac04abbe40 __libc_start_main
[pid=138][err] microsoft/playwright-python#10 0x55911710a02a _start
[pid=138][err]   r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000000 r11: 0000000000000202
[pid=138][err]  r12: 00007ffdd0d58eb0 r13: 000055911710a0f0 r14: 00000000ffffffff r15: 00007ffdd0d58ea8
[pid=138][err]   di: 0000000000000000  si: 00007ffdd0d58c10  bp: 00007ffdd0d58f00  bx: 0000034800264000
[pid=138][err]   dx: 0000000000000000  ax: 0000000000000000  cx: 0000559122749000  sp: 00007ffdd0d58c60
[pid=138][err]   ip: 000055911ad1e2ab efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000025
[pid=138][err]  trp: 000000000000000e msk: 0000000000000000 cr2: 0000559122749008
[pid=138][err] _start
[pid=138][err]   r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000000 r11: 0000000000000206
[pid=138][err]  r12: 00007ffcc07e7370 r13: 0000555d283110f0 r14: 00000000ffffffff r15: 00007ffcc07e7368
[pid=138][err]   di: 0000000000000000  si: 00007ffcc07e70d0  bp: 00007ffcc07e73c0  bx: 00003d9000264000
[pid=138][err]   dx: 0000000000000000  ax: 0000000000000000  cx: 0000555d33950000  sp: 00007ffcc07e7120
[pid=138][err]   ip: 0000555d2bf252ab efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000025
[pid=138][err]  trp: 000000000000000e msk: 0000000000000000 cr2: 0000555d33950008
[pid=138][err] [end of stack trace]
[pid=138][err] [end of stack trace]
[pid=138][err] [0104/144351.911903:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[pid=138][err] [0104/144352.160077:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[pid=138][err] [0104/144352.160154:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[pid=138][err] [0104/144352.255611:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[pid=138][err] [0104/144352.255905:ERROR:gpu_process_host.cc(986)] GPU process launch failed: error_code=1002
[pid=138][err] [0104/144352.255920:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 1 time(s)
[pid=138][err] [0104/144352.266439:ERROR:gpu_process_host.cc(986)] GPU process launch failed: error_code=1002
[pid=138][err] [0104/144352.266461:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 2 time(s)
[pid=138][err] [0104/144352.269951:ERROR:gpu_process_host.cc(986)] GPU process launch failed: error_code=1002
[pid=138][err] [0104/144352.270018:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 3 time(s)
[pid=138][err] [0104/144352.274497:ERROR:gpu_process_host.cc(986)] GPU process launch failed: error_code=1002
[pid=138][err] [0104/144352.274571:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 4 time(s)
[pid=138][err] [0104/144352.276468:ERROR:gpu_process_host.cc(986)] GPU process launch failed: error_code=1002
[pid=138][err] [0104/144352.276516:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 5 time(s)
[pid=138][err] [0104/144352.277493:ERROR:gpu_process_host.cc(986)] GPU process launch failed: error_code=1002
[pid=138][err] [0104/144352.277569:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 6 time(s)
[pid=138][err] [0104/144352.279756:ERROR:gpu_process_host.cc(986)] GPU process launch failed: error_code=1002
[pid=138][err] [0104/144352.279844:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 7 time(s)
[pid=138][err] [0104/144352.281083:ERROR:gpu_process_host.cc(986)] GPU process launch failed: error_code=1002
[pid=138][err] [0104/144352.281110:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 8 time(s)
[pid=138][err] [0104/144352.282591:ERROR:gpu_process_host.cc(986)] GPU process launch failed: error_code=1002
[pid=138][err] [0104/144352.282667:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 9 time(s)
[pid=138][err] [0104/144352.282686:FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.
[pid=138][err] #0 0x55904a8b0572 base::debug::CollectStackTrace()
[pid=138][err] microsoft/playwright-python#1 0x55904a89cf43 base::debug::StackTrace::StackTrace()
[pid=138][err] microsoft/playwright-python#2 0x55904a7f5eb3 logging::LogMessage::~LogMessage()
[pid=138][err] microsoft/playwright-python#3 0x5590488702fa content::(anonymous namespace)::IntentionallyCrashBrowserForUnusableGpuProcess()
[pid=138][err] microsoft/playwright-python#4 0x55904886cf41 content::GpuDataManagerImplPrivate::FallBackToNextGpuMode()
[pid=138][err] microsoft/playwright-python#5 0x55904886baab content::GpuDataManagerImpl::FallBackToNextGpuMode()
[pid=138][err] microsoft/playwright-python#6 0x5590488786e3 content::GpuProcessHost::RecordProcessCrash()
[pid=138][err] microsoft/playwright-python#7 0x559048879d67 content::GpuProcessHost::OnProcessLaunchFailed()
[pid=138][err] microsoft/playwright-python#8 0x559048663d31 content::BrowserChildProcessHostImpl::OnProcessLaunchFailed()
[pid=138][err] microsoft/playwright-python#9 0x5590486e05f2 content::internal::ChildProcessLauncherHelper::PostLaunchOnClientThread()
[pid=138][err] microsoft/playwright-python#10 0x5590486e093c base::internal::Invoker<>::RunOnce()
[pid=138][err] microsoft/playwright-python#11 0x55904a844b0a base::TaskAnnotator::RunTaskImpl()
[pid=138][err] microsoft/playwright-python#12 0x55904a85dfcc base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
[pid=138][err] microsoft/playwright-python#13 0x55904a85d9eb base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
[pid=138][err] microsoft/playwright-python#14 0x55904a85e475 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
[pid=138][err] microsoft/playwright-python#15 0x55904a8c2fbe base::MessagePumpGlib::Run()
[pid=138][err] microsoft/playwright-python#16 0x55904a85e969 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
[pid=138][err] microsoft/playwright-python#17 0x55904a825d7a base::RunLoop::Run()
[pid=138][err] microsoft/playwright-python#18 0x5590486822aa content::BrowserMainLoop::RunMainMessageLoop()
[pid=138][err] microsoft/playwright-python#19 0x559048683e72 content::BrowserMainRunnerImpl::Run()
[pid=138][err] microsoft/playwright-python#20 0x559050dc088d headless::HeadlessContentMainDelegate::RunProcess()
[pid=138][err] microsoft/playwright-python#21 0x559049c4f6b7 content::RunBrowserProcessMain()
[pid=138][err] microsoft/playwright-python#22 0x559049c50fa0 content::ContentMainRunnerImpl::RunBrowser()
[pid=138][err] microsoft/playwright-python#23 0x559049c50d6c content::ContentMainRunnerImpl::Run()
[pid=138][err] microsoft/playwright-python#24 0x559049c4e428 content::RunContentProcess()
[pid=138][err] microsoft/playwright-python#25 0x559049c4e64d content::ContentMain()
[pid=138][err] microsoft/playwright-python#26 0x55904a2f27c5 headless::HeadlessShellMain()
[pid=138][err] microsoft/playwright-python#27 0x55904603a25a ChromeMain
[pid=138][err] microsoft/playwright-python#28 0x7f4353909d90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
[pid=138][err] microsoft/playwright-python#29 0x7f4353909e40 __libc_start_main
[pid=138][err] microsoft/playwright-python#30 0x55904603a02a _start
[pid=138][err] Task trace:
[pid=138][err] #0 0x5590486e0461 content::internal::ChildProcessLauncherHelper::PostLaunchOnLauncherThread()
[pid=138][err] microsoft/playwright-python#1 0x5590486dfc78 content::internal::ChildProcessLauncherHelper::StartLaunchOnClientThread()
[pid=138][err] microsoft/playwright-python#2 0x55904b255c38 mojo::SimpleWatcher::Context::Notify()
[pid=138][err] microsoft/playwright-python#3 0x55904b255c38 mojo::SimpleWatcher::Context::Notify()
[pid=138][err] microsoft/playwright-python#4 0x55904b255c38 mojo::SimpleWatcher::Context::Notify()
[pid=138][err] Task trace buffer limit hit, update PendingTask::kTaskBacktraceLength to increase.
[pid=138][err]
```
Based on this, it seemed like a GPU issue, so I've tried adding the `--disable-gpu` flag to the chromium launch:
```python
from playwright.sync_api import sync_playwright

args = [
    "--disable-gpu",
]

with sync_playwright() as p:
    browser = p.chromium.launch(args=args)
    page = browser.new_page()
    page.goto("http://playwright.dev")
    print(page.title())
    browser.close()
```
but this doesn't seem to help. However, what does work (which I found after some random experimentation), is to use the `--single-process` flag:
```python
from playwright.sync_api import sync_playwright

args = [
    "--single-process",
]

with sync_playwright() as p:
    browser = p.chromium.launch(args=args)
    page = browser.new_page()
    page.goto("http://playwright.dev")
    print(page.title())
    browser.close()
```

### Additional information

- Everything seems to be working fine if I run the same script on my machine outside of Docker
- It also seems to work in a Docker container on a Mac with an M1 chip
- The same issues appear (on the Intel Mac) if I create my own docker image based on the official Python image, e.g.:
```Dockerfile
FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Install playwright dependencies
RUN playwright install-deps
RUN playwright install
ENV DEBUG=pw:api

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
```

**Comment by mxschmitt** [comment] 2024-01-08 19:38
I tried reproducing with the [official Docker image](https://playwright.dev/python/docs/docker) and didn't run in that issue.

Could you confirm this reproduces on your machine in the official image as well?

Does this reproduce without uvicorn?

**Comment by eliaslm** [comment] 2024-01-09 15:24
Yes, it happens when I run a container with
```bash
docker run -it --rm --ipc=host mcr.microsoft.com/playwright/python:v1.40.0-jammy /bin/bash
```
and follow the other steps as described above, i.e. without uvicorn.

**Comment by mxschmitt** [comment] 2024-01-11 13:52
Which exact Mac do you have? I tested in on a MacBook Pro, 16-inch 2019, 2,6 GHz 6-Core Intel Core i7 Mac with a Intel UHD Graphics 630. I also tested it on a 2018 MacMini (same graphics card).

Unfortunately I don't have access to a Mac without a graphics card - so I guess your workaround is a great workaround due to the nature that the environment is not that common and Chromium is then not able to launch. Its either related to the graphics card issue or due to some other issue which makes you use --single-process.

**Comment by eliaslm** [comment] 2024-01-11 15:03
Sorry, I might have been a bit unclear. I do have a graphics card, I just don't have a discrete GPU. Specifically, I'm on a 13-inch, 2020 MacBook Pro with a 2 GHz Quad-Core Intel Core i5 processor and a Intel Iris Plus Graphics 1536 MB graphics card.

**Comment by mxschmitt** [comment] 2024-01-11 17:10
Thanks for clarifying. This is then unfortunately not actionable for us since we can't repro. Closing by that.

**Closed** 2024-01-11 17:10 UTC

**Comment by nkov** [comment] 2025-09-18 09:09
In case it helps anyone, I have experienced this issue on an M1 pro when inadvertently running playwright both on the host directly and within Docker simultaneously.
