### ISSUE TITLE
[BUG] Error "file already exist" when using `snapshotPathTemplate` project setting

### ISSUE THREAD

**Issue by nikolay-yavorovskiy** [microsoft/playwright#21326] opened 2023-03-02 05:20 UTC
### System info
- Playwright Version: v1.30.0
- Operating System: macOS 13.2.1
- Browser: All

### Source code

// playwright.config.js

```js
const { defineConfig } = require('@playwright/test');

module.exports = defineConfig({
  snapshotPathTemplate: 'tests/{testFilePath}/{arg}{ext}'
});
```

-------------

// component.spec.js

```js
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();

  await page.setContent(`
    <div class="my-component">
       <br>
    </div>
  `);

  await expect(page.locator('.my-component')).toHaveScreenshot();
  await browser.close();
})();
```

-------------

directory structure:

- 📁 project
- - 📁 tests
- - - 📁 component
- - - - 📁 model
- - - - - 📃 component-model.js
- - - - 📁 tests
- - - - - 📃 component.spec.js
- - - - - 📁 component.spec.js
- 📃 playwright.config.js

-------------

- [x] I provided exact source code that allows reproducing the issue locally.

**Steps**
- npx playwright test

**Expected**

test successfully passed

**Actual**

Error: EEXIST: file already exists, mkdir '/users/username/project/tests/component/tests/component.spec.js'

looks like the problem happens because directory has the same name as spec file

![image](https://user-images.githubusercontent.com/89914399/222337445-746c19fd-ed71-4de4-b4a3-2834773a7def.png)

**Comment by aslushnikov** [comment] 2023-03-02 17:03
@nikolay-yavorovskiy I tried reproducing this, but works for me.

Here's the repo built according to your instuctions: https://github.com/aslushnikov/repro-for-issue-21326

The following works fine for me:

```sh
$ git clone https://github.com/aslushnikov/repro-for-issue-21326
$ cd repro-for-issue-21326
$ npm i && npx playwright test

Running 1 test using 1 worker

  ✓  1 tests/component/tests/component.spec.js:3:1 › PageConfig (469ms)

  1 passed (1.1s)
```

Can you try running this and see if it works? If it doesn't can you provide a similar repo that illustrates the issue?

**Comment by nikolay-yavorovskiy** [comment] 2023-03-03 03:19
> ```shell
> npx playwright test
> ```

yeah, I'm sorry, snapshotPathTemplate should be a little different
try
`snapshotPathTemplate: '{testFilePath}/{arg}{ext}'` and you'll see the issue
![image](https://user-images.githubusercontent.com/89914399/222622923-96c7eb74-3bfd-4e0c-8555-05b4188d94f8.png)

**Comment by dgozman** [comment] 2023-03-09 21:48
@nikolay-yavorovskiy It looks like you want to put your screenshots for `tests/component.spec.js` test file into `tests/component.spec.js/screenshot.png` files. This means you need `component.spec.js` to be both a file and directory. I don't think this is going to work, at least it does not work on my mac.

Did you mean something else? Or did I misunderstand the issue?

**Comment by dgozman** [comment] 2023-03-13 16:10
Closing per above. If you still encounter problems, please file a new issue with a repro and link to this one.

**Closed by dgozman** 2023-03-13 16:10 UTC
Labels: v1.32

**Comment by nikolay-yavorovskiy** [comment] 2023-03-20 10:48
> @nikolay-yavorovskiy It looks like you want to put your screenshots for `tests/component.spec.js` test file into `tests/component.spec.js/screenshot.png` files. This means you need `component.spec.js` to be both a file and directory. I don't think this is going to work, at least it does not work on my mac.
> 
> Did you mean something else? Or did I misunderstand the issue?

why is this won't work?
by default if I do not snapshotPathTemplate manually playwright does the same exact thing - creates new folder with the same name as the spec and everything works
