### ISSUE TITLE
[Feature] Complete silent install via the command line

### ISSUE THREAD

**Issue by fuglyducky** [microsoft/playwright#16616] opened 2022-08-17 14:26 UTC
Unless I completely missed something on the documentation, I cannot install playwright without some manual input. Namely choosing typescript vs javascript, et al.

To make the lives of our CI team easier, and not require continual updates to our machine images, we would like to be able to install playwright on the fly without any user intervention.

**Comment by aslushnikov** [comment] 2022-08-17 17:06
@fuglyducky So why do you want to run `npm init playwright` on CI? This should never be the case unless you do some meta-automation!

**Comment by aslushnikov** [comment] 2022-08-22 19:45
@fuglyducky usually this is solved by [`package-lock.json`](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json/). It will pin all the packages to proper versions and install them and their dependencies, giving you reproducible builds!

**Comment by aslushnikov** [comment] 2022-08-22 19:46
Since my rotation is over, let me close this for now. If you do think that `package-lock.json` is not suitable for some reason for you, please feel free to open a new issue! :)

**Closed by aslushnikov** 2022-08-22 19:46 UTC
Labels: triaging

**Comment by QAscoop** [comment] 2023-11-07 01:37
I do need to accomplish this by specifying JavaScript instead of TypeScript for my dockerized setup
