### ISSUE TITLE
[BUG] UI mode not working with storageState enabled (?)

### ISSUE THREAD

**Issue by clundstedt-m** [microsoft/playwright#21922] opened 2023-03-23 13:47 UTC
### System info
- Playwright Version: [v1.32]
- Operating System: [macOS 13.2]
- Browser: [All]
- Other info: Storage State / Authentication state enabled through globalSetup

**Config file**

```ts
// playwright.config.ts
 globalSetup: require.resolve("./src/e2e/tests/global-setup"),
    storageState: './src/e2e/tests/state.json',
    actionTimeout: 0,
    screenshot: 'only-on-failure',
    trace: 'on-first-retry',
  },
```

**Test file (self-contained)**

```js
test.beforeEach(async ({ page }) => {
  // Runs before each test and signs in each page.
  const assetsPage = new AnyPage(page);
  const loginPage = new LoginPage(page);
  await loginPage.visit()
  await assetsPage.menuTopNavComponent.clickAnyMenuItemNav(); 
  });

test('Creating an Element - Any Type', async ({ page }) => {
  const anyPage = new AnyPage(page);
  await anyPage.anyGridLoads()
  await anyPage.createElementAnyType();
});
```
**Pre-condition**
- Having Storage state enabled and being used to sign in during the beforeEach hook

**Steps**
- Run the test with the new flag --ui
- npx playwright test --ui

**Expected**

UI Should be displayed as per the new feature is intended to work

**Actual**

After executing the command with the new flag --ui, terminal  shows the following error:
```
/Users/clundstedt/Documents/zf-playwright/node_modules/@playwright/test/lib/runner/uiMode.js:159
    this._page.mainFrame().evaluateExpression(dispatchFuncSource, true, message).catch(e => this._originalStderr(String(e)));
               ^

TypeError: Cannot read properties of undefined (reading 'mainFrame')
    at UIMode._dispatchEvent (/Users/clundstedt/Documents/zf-playwright/node_modules/@playwright/test/lib/runner/uiMode.js:159:16)
    at Timeout._onTimeout (/Users/clundstedt/Documents/zf-playwright/node_modules/@playwright/test/lib/runner/uiMode.js:69:14)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)

Node.js v19.4.0
```

**Comment by pavelfeldman** [comment] 2023-03-23 16:16
Dupe of https://github.com/microsoft/playwright/issues/21897

**Closed by pavelfeldman** 2023-03-23 16:16 UTC
Labels: feature-ui-mode
