### ISSUE TITLE
[BUG] Firefox: background of elements is not visible since certain page height

### ISSUE THREAD

**Issue by Ser-Gen** [microsoft/playwright#8710] opened 2021-09-04 12:24 UTC
## System:
 - OS: Windows 10 10.0.19042
 - Memory: 10.08 GB / 15.96 GB
## Binaries:
 - Node: 14.16.1 - D:\Program Files\nodejs\node.EXE
 - npm: 6.14.12 - D:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 4.4.19 - C:\WINDOWS\system32\bash.EXE
## npmPackages:
 - playwright: 1.14.1 => 1.14.1

## Bug description

Firefox do not renders a background of elements from length of document equals `16383px`.
Looks like this problem is exists from version `1.13.0`.

Also a linear gradient is cutting on the same page height since version `1.0.0`.

It happens with elements with background and border-radius.
If element has border with defined color then it's background is fully visible. The `border-width` must be wider than `border-radius`.

## Screenshot of the bug

<details>
	<summary>Huge image, <code>16398px</code> tall</summary>
<img src="https://user-images.githubusercontent.com/1856145/132094080-905ff04d-291a-40c0-8a09-8bfeb3244d59.png">
</details>

Part of this screenshot that illustrates a bug:

![example-cut](https://user-images.githubusercontent.com/1856145/132094163-3408724b-67bb-4cfc-9e5f-be65f46a4283.png)

### Test assets

```javascript
'use strict';

const {firefox} = require('playwright');
const process = require('process');
const cwd = process.cwd().replace(/\\/g, '/');

(async () => {
	const browser = await firefox.launch();
	const page = await browser.newPage();
	
	await page.goto('file://'+ cwd +'/index.html');
	await page.screenshot({
		path: 'example.png',
		fullPage: true,
	});

	await browser.close();
})();
```

```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Test</title>
	<style>
		body {
			margin: 0;
		}
		.offset {
			height: 16372px;
		}
		
		.test {

			/* just to make them inline */
			display: inline-block;
			vertical-align: middle;

			border-radius: 3px;
			background-color: #f00;
		}
		.test--linear-gradient {
			background-image: linear-gradient(#f00, #0f0);
		}
		.test--border {
			border: 4px solid;
		}
		.test--border-color {
			border-color: #0f0;
		}
	</style>
</head>
<body>
	<div class="offset"></div>

	<div class="test">Text</div>
	<div class="test test--linear-gradient">Text</div>
	<div class="test test--border">Text</div>
	<div class="test test--border test--border-color">Text</div>
	<div class="test test--linear-gradient test--border test--border-color">Text</div>
</body>
</html>
```

**Comment by mxschmitt** [comment] 2021-09-06 11:42
This looks like a Firefox bug, so please create an issue in their in their issue tracker: https://bugzilla.mozilla.org/enter_bug.cgi

This reproducible helped a lot! So its reproducible via:

1. Open your html file in Firefox
2. Right click on the page and click "Take Screenshot" and then "Save full page"
3. Observe that the background images are cropped, see this screenshot:

![image](https://user-images.githubusercontent.com/17984549/132212058-67215419-149f-409b-9c3d-e929396cfac4.png)

The left side is the actual rendered page and the right one is from the screenshot.

Expected: They should be the same.

**Comment by Ser-Gen** [comment] 2021-09-06 12:33
Created an issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1729293

**Comment by Ser-Gen** [comment] 2021-11-06 11:24
Workaround is to capture page by small parts, by `15000px` and join them together.

@mxschmitt does playwright have an option to capture `imageData` instead of `png`?
Right now I need to decode parts and encode full screenshot through outer library.

**Comment by pavelfeldman** [comment] 2022-10-20 03:04
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-10-20 03:04 UTC
Labels: upstream, browser-firefox
