### ISSUE TITLE
[Feature] Support CentOS

### ISSUE THREAD

**Issue by gkushang** [microsoft/playwright#9241] opened 2021-09-30 17:21 UTC
We use CentOS in our Jenkins CI environment. We see a lot of challenges using Playwright from version 1.15.0 since it needs `GLIBC_2.18` which is not available in CentOS.

Related thread for this feature request > https://github.com/microsoft/playwright/issues/9194#issuecomment-929480889

This is blocking us to upgrade the Playwright, and having support for CentOS7 would be great!

**Comment by mxschmitt** [comment] 2021-09-30 17:25
Closing as a duplicate of https://github.com/microsoft/playwright/issues/9199

We recommend to use Docker for now or one of the officially supported linux distributions.

**Closed by mxschmitt** 2021-09-30 17:25 UTC
