### ISSUE TITLE
puppeteer-extra-plugin-stealth compatible palywright. but palywright-python

### ISSUE THREAD

**Issue by dly667** [microsoft/playwright#20490] opened 2023-01-30 09:38 UTC
hello,
puppeteer-extra-plugin-stealth compatible palywright. but palywright-python Install puppeteer-extra-plugin-stealth

**Comment by mxschmitt** [comment] 2023-01-30 13:49
Duplicate of https://github.com/microsoft/playwright-python/issues/1744.

**Closed by mxschmitt** 2023-01-30 13:49 UTC
