### ISSUE TITLE
[BUG]  await this.page.locator("").press('Enter') produces inconsistent results

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#20461] opened 2023-01-27 23:30 UTC
**Context:**
- "playwright": "^1.28.1",
- Operating System: Mac
- Browser: [e.g. All, Chromium, Firefox, WebKit]

**Code Snippet**

```javascript
await crewIFPlannerActor.attemptsTo(Fill.with().text("search-employeeId","5050"));
        await this.page.locator('[data-testid="search-employeeId"]').press('Enter')
        await page.mouse.click(1000, 1000);

        let biddingAccrualTable = await crewIFPlannerActor.attemptsTo(FetchAllRowsByTable.byId('paged-table-IFVacationCrewMemberVacationAccruals'))
        let biddingAccrualTableNoOfRows = await biddingAccrualTable.count();

        console.log("count:" + biddingAccrualTableNoOfRows)
        await expect(biddingAccrualTableNoOfRows).toEqual(1);  --> but instead of one row, it loads all different employee no records -rows.
```

**Describe the bug**

await this.page.locator("").press('Enter'). --> for some reason, after pressing enter, the page keeps loading, I expected to search for employee no in the text box and press enter, that should just return me just 1 row that matches the employee no i search. and it works fine when i test manually. However when i do press("Enter") via playwright, it works once fine, but rest of the times, it keeps loading all the other rows that have different employee nos on them.

Attached is the screenshot.

Before entering- searching for employee no

<img width="1400" alt="Screen Shot 2023-01-27 at 5 26 46 PM" src="https://user-images.githubusercontent.com/113629123/215224771-51410b20-ef9e-47f0-b115-53867aef19be.png">

After searching for the employee no and entering

<img width="1400" alt="Screen Shot 2023-01-27 at 5 26 55 PM" src="https://user-images.githubusercontent.com/113629123/215224801-2632ed77-b0fb-406b-99d4-95b35d67dee8.png">

**Comment by pavelfeldman** [comment] 2023-01-28 01:49
Playwright is a super-fast user, if you do the same manually while emulating Slow 3G using Chrome DevTools (google how to), you'll most likely see that your page has a bug and it keeps loading if the user quickly enters the filter.

**Comment by InduKrish** [comment] 2023-01-29 06:34
ok, will test using Slow 3G using Chrome DevTools(never heard of it before) and keep you posted, so are you suspecting that it is an issue with our application? Can you please confirm?

**Comment by pavelfeldman** [comment] 2023-01-30 17:02
Yes, I suspect that the issue is with the application.

**Comment by dgozman** [comment] 2023-02-02 17:05
Closing per above. If you still encounter problems, please file a new issue with a repro and link to this one.

**Closed by dgozman** 2023-02-02 17:05 UTC
Labels: triaging
