### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by agadzhiev** [microsoft/playwright#28213] opened 2023-11-17 08:56 UTC
### System info
- Playwright Version: [v1.24]
- Operating System: [Linux]
- Browser: [Firefox]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
     projects: [
        {
            name: "auth",
            use: { ...devices["Desktop Chrome"] },
            testMatch: /auth.spec.ts/,
            retries: 3,
        },
        {
            name: "desktop",
            use: { ...devices["Desktop Chrome"] },
            testMatch: /.*desktop.spec.ts/,
            retries: 3,
        },
        {
            name: "desktop-ff",
            use: { ...devices["Desktop Firefox"] },
            testMatch: /.*desktop.spec.ts/,
            retries: 3,
        },
```

**Test file (self-contained)**

```ts
await frame!.locator(report.selector).waitFor({ state: "visible", timeout: 45000 });
await waitForReport(page, report.loaderSelector, frameLocator);
await expect(frame!.locator(report.selector)).toHaveScreenshot(`{report.name}.png`, matchParams);
```

**Steps**
- [Run the test]

**Actual**

Localy everything is ok. I get an expected results. But when I run test in CI, Firefox cases failed with this
Screenshot comparison failed:
7487 pixels (ratio 0.02 of all image pixels) are different
OR 
 Expected an image 1056px by 2557px, received 1056px by 2619px. 
OR
 Expected an image 1056px by 678px, received 1056px by 679px. 

The screenshots look the same visually. I'll repeat that the same tests pass locally without errors, but the errors only occur when running on CI. The environment is the same: Linux, Firefox.

I've seen similar issues discussed here before, but I haven't found a solution that works for me.

**Comment by mxschmitt** [comment] 2023-11-17 18:09
Do you run your tests on the same exact machine which you also use to generate the screenshots?

Without that, browsers might produce different expectations.

Since this bug does not contain a self-contained reproduction, I'm going to close it for now since we can't act on it, thanks for your understanding!

**Closed by mxschmitt** 2023-11-17 18:09 UTC
