### ISSUE TITLE
[Question] Webkit test cases fail on Jenkins, but chromium and firefox works fine

### ISSUE THREAD

**Issue by jatin-karla11** [microsoft/playwright#14477] opened 2022-05-30 09:47 UTC
**Context:**
- Playwright Version: 1.19
- Browser: WebKit

Tests run fine on local on all the browsers, but when made run on jenkins on webkit then the following error occurs-
browser.newPage: Browser closed.

**Comment by mxschmitt** [comment] 2022-05-30 13:05
Do you have code which you can share? Usually the reason for that is a missing await or missing dependencies.

Make sure to have all the dependencies installed, see here: https://playwright.dev/docs/cli#install-system-dependencies

Also setting the `DEBUG=pw:browser` env should yield to more verbose output.

**Comment by jatin-karla11** [comment] 2022-05-30 13:30
https://github.com/microsoft/playwright/issues/13875

this is the same kind of error that I am getting, difference is I am running on jenkins.

**Comment by aslushnikov** [comment] 2022-05-31 10:01
@jatin-karla11 Do you run on linux? What's your linux distribution?

**Comment by jatin-karla11** [comment] 2022-06-01 06:26
@aslushnikov os :- ubuntu 18:04
configuration: 8vCpu 16Gb memory

**Comment by aslushnikov** [comment] 2022-06-01 10:55
@jatin-karla11 Weird! Can you build a docker image that reproduces the failure? This seems to be the only way I'll be able to debug & help.

**Comment by jatin-karla11** [comment] 2022-06-03 12:36
I don't have knowledge w.r.t. docker image since I run on Jenkins. 
https://github.com/microsoft/playwright/issues/13875

this is the same kind of error that I am getting, can you check this?

**Comment by aslushnikov** [comment] 2022-06-03 12:45
@jatin-karla11 That one I already tried and was not able to repro. :( I hoped you can shed more light on what's going on there!

**Comment by jatin-karla11** [comment] 2022-06-06 10:58
this is the basic structure of our test files-

import test, { expect } from '../../../fixtures/basePages';
// a lot more imports

const authPath = `xyz.json`

test.beforeEach(async ({ loginPage, page }) => {
  await page.goto('/', { waitUntil: 'networkidle' });
  await SkipLoginHelper.login(page, loginPage);
});

test.describe('Basic autopay tests', () => {

  test.use({ storageState: authPath });

  test('Investigate if user is able to add autopay only for verified banks @sanity @regression’, async ({ profileHeaderPage, autoPayPage, bankPage, page }) => {

    await ……;
	// and further code
  });

});

test.afterEach(async ({ page }) => {
  // await page.close();
});

The execution of suite starts from logging accounts in global setup and then storing auth files in auth folders, and then using those auth files in our tests to skip the login part.
Is there any mistake at any point in test file code?..
Again everything works fine when I run on local, but on jenkins randomly tests start failing on webkit with the below error-
browser.newPage: Browser closed.

what all things can I share w.r.t code so that you can better understand?.. (I can't send the trace)
@aslushnikov

**Comment by pavelfeldman** [comment] 2022-06-06 20:57
`networkidle` is non-deterministic, you should never use it for testing, just for scraping.

Usually, if everything works locally and fails on CI, it is one of two things:
- CI does not have dependencies installed to run browsers
- Test is sensitive to the timing and slower CIs surface the issues

Your snippet does not tell us much, if you manage to create a reproduction we can try, we are happy to follow up. Otherwise it is not actionable on our side...

**Comment by pavelfeldman** [comment] 2022-06-06 22:11
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2022-06-06 22:11 UTC
Labels: triaging
