### ISSUE TITLE
[BUG] Unable to open and view the PW Inspector

### ISSUE THREAD

**Issue by snehalk20** [microsoft/playwright#6614] opened 2021-05-17 13:09 UTC
**Context:**
- Playwright Version: [1.10.0]
- Operating System: [Windows]
- Node.js version: [v14.15.3]
- Browser: [All]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```
npx playwright codegen wikipedia.org
```

**Describe the bug**
Playwright inspector is not opening. I see a new tab in the tool bar at the bottom but when I click and try to open it, it does not do anything. Also the ode generated cannot be viewed. So in a nutshell cannot open, view the PW inspector.
![PW inspector](https://user-images.githubusercontent.com/83778331/118494540-e358c380-b73f-11eb-8f62-bc9df88d315c.jpg)

**Comment by mxschmitt** [comment] 2021-05-17 13:15
Seems like a duplicate of https://github.com/microsoft/playwright/issues/5696 to me.

**Comment by JoelEinbinder** [comment] 2021-05-18 00:36
Closing as duplicate of #5696

**Closed by JoelEinbinder** 2021-05-18 00:36 UTC
