### ISSUE TITLE
[Bug]: Drag and drop doesn't work with Playwright Inspector

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#8022] opened 2021-08-05 21:48 UTC
### Playwright version

1.13.1

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### Other information

Node: 14.17.0

### What happened? / Describe the bug

Drag and drop doesn't work with Playwright Inspector.

I tested in my application and in this site as well. When Playwright Inspector is running, unable to perform drag and drop.

Steps to Reproduce:

1. Run this command npx playwright codegen https://www.seleniumeasy.com/test/drag-and-drop-demo.html
2. Try to drag '**Draggabble1**' and drop here '**Drop here**' 

**Issue:** Unable to perform drag and drop

Noticed the same behavior in plawright@next

### Code snippet to reproduce your bug

```shell
n/a
```

### Relevant log output

```shell
n/a
```

**Comment by mxschmitt** [comment] 2021-08-06 12:29
I can repro, thanks for the reproducible!

**Comment by marshzhao** [comment] 2021-08-22 15:57
I can't repro.I have installed the npx package using pip command, but When I execute the command npx playwright codegen https://www.seleniumeasy.com/test/drag-and-drop-demo.html,The terminal prompts that “bash: npx: command not found”.Not only me have the problem, my friend also appeared the problem.The os is Mac OS.

**Comment by pavelfeldman** [comment] 2022-01-01 23:50
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-01-01 23:50 UTC
Labels: P3-collecting-feedback
