### ISSUE TITLE
[BUG] playwright: not found  script returned exit code 127

### ISSUE THREAD

**Issue by Smrtnyk** [microsoft/playwright#14541] opened 2022-06-01 11:41 UTC
**Context:**
- Playwright Version: 1.22.2
- Operating System: Linux
- Node.js version: [e.g. 12.22, 14.6]
- Browser: Firefox
- Extra: it runs in CI in jenkins instance

```jenkinsfile
 stage('playwright-shard-2') {
                    steps {
                        sh "chmod -R 777 ./"
                        container('playwright') {
                            sh "npm run test:playwright-two-unstable" -> runs normally
                        }

                        container('playwright') {
                            sh "npm run test:playwright-two-stable" -> complains that playwright is not found even though a step above ran playwright successfuly
                        }
                    }
                }
```
When running shard that starts firefox we have two jenkins steps
one is for tests that can have retries (flaky ones)
and second step runs tests that should be stable (0 retries)
Sometimes happens that after first step runs playwright successfuly, the second step complains that playwright is not found.
I have tried moving second step into first container declaration like
```jenkinsfile
stage('playwright-shard-2') {
                    steps {
                        sh "chmod -R 777 ./"
                        container('playwright') {
                            sh "npm run test:playwright-two-unstable" 
                            sh "npm run test:playwright-two-stable"
                        }
                    }
                }
```
but same happens sometimes
playwright config for stable step
```ts
const config: PlaywrightTestConfig<DtTestOptions> = {
    fullyParallel: true,
    outputDir: "../test-results/playwright",
    timeout: 60 * 1000,
    testDir: "../source/playwright-tests/tests/stable",
    testMatch: "**/*.spec.ts",
    globalSetup: require.resolve("../source/playwright-tests/utils/setup.ts"),
    quiet: true,
    preserveOutput: "failures-only",
    projects: [
        {
            name: "chromium",
            use: { browserName: "chromium" }
        },
        {
            name: "firefox",
            use: {
                browserName: "firefox",
                recordHar: "off"
            }
        },
        {
            name: "webkit",
            use: { browserName: "webkit" }
        }
    ],
    use: {
        beacons: "retain-on-failure",
        recordHar: "retain-on-failure",
        ignoreHTTPSErrors: true
    }
};

export default config;
```

playwright image is specified as
```yaml
- name: playwright
      image: mcr.microsoft.com/playwright:v1.22.2-focal
      imagePullPolicy: Always
      command:
        - cat
      tty: true
```
in our jenkins.yaml file

error in jenkins console is
```
[2022-06-01T11:34:15.214Z] + npm run test:playwright-two-stable

[2022-06-01T11:34:15.515Z] 

[2022-06-01T11:34:15.516Z] > project@0.0.0 test:playwright-two-stable

[2022-06-01T11:34:15.516Z] > playwright test -c config/playwright-stable.config.ts --shard=2/3

[2022-06-01T11:34:15.516Z] 

[2022-06-01T11:34:15.516Z] sh: 1: playwright: not found

script returned exit code 127
```

**Comment by aslushnikov** [comment] 2022-06-02 12:24
> sh: 1: playwright: not found

@Smrtnyk so this message somehow says that `npx` didn't find Playwright. I don't follow what can cause this message; maybe the installation step is missing occasionally?

Overall, this looks like a CI misconfiguration to me rather than a Playwright problem. Unfortunately, I'm not familiar with Jenkins that much, so I won't be of much help here.

**Comment by Smrtnyk** [comment] 2022-06-02 12:32
It is installed
the step before executed playwright tests successfully
the second step then couldn't find playwright

its weird that one run finds it and then the second run doesn't see it anymore

**Comment by aslushnikov** [comment] 2022-06-03 11:05
> its weird that one run finds it and then the second run doesn't see it anymore

@Smrtnyk I do agree it's weird! Maybe the CWD is different between the runs / affected sporadically by something?

**Comment by pavelfeldman** [comment] 2022-06-06 21:23
I'll close it because it does not seem to be Playwright-related. Please provide a reproduction script that demonstrates the issue, that way we can quickly resolve it.

**Closed by pavelfeldman** 2022-06-06 21:23 UTC
Labels: triaging
