### ISSUE TITLE
[BUG] IResponse.BodyAsync() occasionally throws an exception

### ISSUE THREAD

**Issue by RenderMichael** [microsoft/playwright#21029] opened 2023-02-09 17:11 UTC
**Context:**
- Playwright Version: 1.30.0
- Operating System: Windows
- .NET version: .NET 7
- Browser: Happens on Chromium, webkit, and firefox

**Code Snippet**

```cs
using Microsoft.Playwright;
using Microsoft.Playwright.NUnit;

using NUnit.Framework;

using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace PlaywrightTests;

[Parallelizable(ParallelScope.Self)]
[TestFixture]
public class MyTest : PageTest
{
    [Test]
    public async Task TestNetworkScanning()
    {
        var responses = new List<IResponse>();

        Page.Response += AddToResponseList;
        
        await Page.GotoAsync("https://www.google.com/");
        await Task.Delay(1000);

        Page.Response -= AddToResponseList;

        var list = new List<NetworkLog>(responses.Count);
        foreach (IResponse response in responses)
        {
            ResponseServerAddrResult? serverInfo = await response.ServerAddrAsync().ConfigureAwait(false);
            ResponseSecurityDetailsResult? security = await response.SecurityDetailsAsync().ConfigureAwait(false);
            var request = new Request(response.Request.Url, response.Request.Headers, response.Request.Method, response.Request.PostData);
            var headers = await response.AllHeadersAsync().ConfigureAwait(false);
            byte[] body = await response.BodyAsync().ConfigureAwait(false); // Exception thrown here
            string encodedBody = Encoding.UTF8.GetString(body);
            var responseLog = new Response(response.Url, headers, response.Status, encodedBody)
            {
                FromServiceWorker = response.FromServiceWorker,
                RemoteIPAddress = serverInfo?.IpAddress,
                RemotePort = serverInfo?.Port,
                StatusText = response.StatusText,
                SecurityDetails = security is null ? null : new SecurityDetails(security.Issuer, security.Protocol, security.SubjectName, security.ValidFrom, security.ValidTo),
            };
            var type = response.Request.ResourceType;
            var log = new NetworkLog(Request: request, Response: responseLog, Type: type)
            {
                FrameId = response.Frame.Name,
                Duration = response.Request.Timing.ResponseEnd - response.Request.Timing.StartTime,
            };
            list.Add(log);
        }

        void AddToResponseList(object? _, IResponse e) => responses.Add(e);
    }
}

public sealed record NetworkLog(Request Request, Response Response, string? Type)
{
    public string? FrameId { get; set; }

    public double? Duration { get; set; }
}

public sealed record Request(string Url, IReadOnlyDictionary<string, string> Headers, string Method, string? PostData);

public sealed record Response(string Url, IReadOnlyDictionary<string, string> Headers, long Status, string? Body)
{
    public string? StatusText { get; set; }

    public string? RemoteIPAddress { get; set; }

    public long? RemotePort { get; set; }

    public bool? FromServiceWorker { get; set; }

    public SecurityDetails? SecurityDetails { get; set; }
}

public sealed record SecurityDetails(string? Issuer, string? Protocol, string? SubjectName, double? ValidFrom, double? ValidTo);

```

**Describe the bug**

Occasionally, the call to BodyAsync() throws an exception on each browser type (a slightly different one on each type).

Exception on Chromium:
``` csharp
Microsoft.Playwright.PlaywrightException
  HResult=0x80131500
  Message=Protocol error (Network.getResponseBody): No data found for resource with given identifier
  Source=Microsoft.Playwright
  StackTrace:
   at Microsoft.Playwright.Transport.Connection.<InnerSendMessageToServerAsync>d__34`1.MoveNext()
   at Microsoft.Playwright.Transport.Connection.<WrapApiCallAsync>d__44`1.MoveNext()
   at Microsoft.Playwright.Transport.Channels.ResponseChannel.<GetBodyAsync>d__1.MoveNext()
   at PlaywrightTests.MyTest.<ScanNetworkAsync>d__1.MoveNext() in C:\Users\rende\source\repos\PlaywrightRepro\PlaywrightRepro\MyTest.cs:line 44

  This exception was originally thrown at this call stack:
    Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync<T>(string, string, System.Collections.Generic.Dictionary<string, object>)
    Microsoft.Playwright.Transport.Connection.WrapApiCallAsync<T>(System.Func<System.Threading.Tasks.Task<T>>, bool)
    Microsoft.Playwright.Transport.Channels.ResponseChannel.GetBodyAsync()
    PlaywrightTests.MyTest.ScanNetworkAsync(Microsoft.Playwright.IPage, System.Action) in MyTest.cs
```

Exception on WebKit:
``` csharp
Microsoft.Playwright.PlaywrightException
  HResult=0x80131500
  Message=Protocol error (Network.getResponseBody): Missing content of resource for given requestId [{"code":-32000,"message":"Missing content of resource for given requestId"}]
  Source=Microsoft.Playwright
  StackTrace:
   at Microsoft.Playwright.Transport.Connection.<InnerSendMessageToServerAsync>d__34`1.MoveNext()
   at Microsoft.Playwright.Transport.Connection.<WrapApiCallAsync>d__44`1.MoveNext()
   at Microsoft.Playwright.Transport.Channels.ResponseChannel.<GetBodyAsync>d__1.MoveNext()
  at PlaywrightTests.MyTest.<ScanNetworkAsync>d__1.MoveNext() in C:\Users\rende\source\repos\PlaywrightRepro\PlaywrightRepro\MyTest.cs:line 44

  This exception was originally thrown at this call stack:
    Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync<T>(string, string, System.Collections.Generic.Dictionary<string, object>)
    Microsoft.Playwright.Transport.Connection.WrapApiCallAsync<T>(System.Func<System.Threading.Tasks.Task<T>>, bool)
    Microsoft.Playwright.Transport.Channels.ResponseChannel.GetBodyAsync()
    PlaywrightTests.MyTest.ScanNetworkAsync(Microsoft.Playwright.IPage, System.Action) in MyTest.cs
```

Exception on firefox:
``` csharp
Microsoft.Playwright.PlaywrightException
  HResult=0x80131500
  Message=Response body is unavailable for redirect responses
  Source=Microsoft.Playwright
  StackTrace:
   at Microsoft.Playwright.Transport.Connection.<InnerSendMessageToServerAsync>d__34`1.MoveNext()
   at Microsoft.Playwright.Transport.Connection.<WrapApiCallAsync>d__44`1.MoveNext()
   at Microsoft.Playwright.Transport.Channels.ResponseChannel.<GetBodyAsync>d__1.MoveNext()
   at PlaywrightTests.MyTest.<ScanNetworkAsync>d__2.MoveNext() in C:\Users\rende\source\repos\PlaywrightRepro\PlaywrightRepro\MyTest.cs:line 44

  This exception was originally thrown at this call stack:
    Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync<T>(string, string, System.Collections.Generic.Dictionary<string, object>)
    Microsoft.Playwright.Transport.Connection.WrapApiCallAsync<T>(System.Func<System.Threading.Tasks.Task<T>>, bool)
    Microsoft.Playwright.Transport.Channels.ResponseChannel.GetBodyAsync()
    PlaywrightTests.MyTest.ScanNetworkAsync(Microsoft.Playwright.IPage, System.Action) in MyTest.cs
```

edit: same thing happened on firefox

edit: simplified repro

**Comment by yury-s** [comment] 2023-02-22 19:19
Response body may be pruned from the browser cache on navigation or due to resource pressure. Make sure you read the body before navigating away from the page. I was not able to reproduce the error with the example you shared, also I don't see any redirects when navigating to that URL so it seems that the error might be from a different URL. Which response URL is causing the problem in Chromium? Note that google will serve different content depending on many factors. We need a repro with a page that we could run reliably locally. Can you share one? We cannot act on this otherwise.

**Comment by yury-s** [comment] 2023-02-27 21:47
Closing per the response above, feel free to open a new issue if it doesn't work.

**Closed by yury-s** 2023-02-27 21:47 UTC
Labels: triaging
