### ISSUE TITLE
[BUG] could not screenshot big html fully

### ISSUE THREAD

**Issue by CaoGaorong** [microsoft/playwright#11054] opened 2021-12-22 02:45 UTC
**Context:**
- Playwright Version: 1.17.1
- Operating System: macOS 10.15.7
- Node.js version: v12.22.7
- Browser: Chromium
- Extra: [any specific details about your environment]

**Describe the bug**

I need to convert a rich text to an image. My previous solution is using puppeteer. But I found Playwright-node is faster than Puppeteer, so I am going to migrate my project from puppeteer to playwright.

But I get some problems.

I loaded a html text from my disk, and use playwright-node-chromium to render and screenshot a specific element.
It works good when the html file was small, but works not good if the html file too big.  
Puppeteer works all good whenever the html file how big, so I consider it is a bug of playwright.

**My code and result**
Here is my code: <a href="https://github.com/CaoGaorong/PlaywrightTesting/blob/master/capture_element.js">My Code To Screenshot</a>
Here is the html text that I need to taking a screenshot: <a href="https://github.com/CaoGaorong/PlaywrightTesting/blob/master/richText.html">richText.html</a>
Here is my result after executing the code above: <a href="https://github.com/CaoGaorong/PlaywrightTesting/blob/master/longImage.jpeg">image screenshot</a>

Or you can clone my git repository to execute  my code:  https://github.com/CaoGaorong/PlaywrightTesting.git

As you can see, the image produced by the code is not good, it only capture the rich text partially. 
![image](https://user-images.githubusercontent.com/48762164/147026259-dd49be62-b1ec-4646-a2aa-b341444afd1d.png)

So there is any solution to solve this? 

Sorry for my pool English. Thank you If you could reply or help.

**Comment by yury-s** [comment] 2021-12-22 19:26
Thanks for providing good repro! I tried it locally and the image rendered fine without any gaps. However, the image file is too large, it takes about a minute to render in a Chrome tab for me and default image viewer on linux just fails to open it. We've seen such problems with screenshots in the past (e.g. [this one](https://github.com/microsoft/playwright-java/issues/436)) and they seemed to be hardware-related. Sometimes giving the browser more time may result in all tiles being rendered but sometimes it won't be sufficient either as there is not enough gpu memory or something else. There is not much we can do on the Playwright end as this is handled inside Chromium. You are saying though that it generates correctly in puppeteer, so the problem must be in the timing as both projects use same CDP commands to communicate with the browser. Can you show the pptr script that produces full image?

**Comment by yury-s** [comment] 2021-12-22 20:07
I can reproduce the problem on Mac but only in headless mode, sometimes it renders full image but most of the time part of the image will be blank similar to your screenshot. As I mentioned there is not much we can do on the Playwright end about the rendering, as a workaround you can try running in headful mode.

**Comment by CaoGaorong** [comment] 2021-12-23 09:26
> Thanks for providing good repro! I tried it locally and the image rendered fine without any gaps. However, the image file is too large, it takes about a minute to render in a Chrome tab for me and default image viewer on linux just fails to open it. We've seen such problems with screenshots in the past (e.g. [this one](https://github.com/microsoft/playwright-java/issues/436)) and they seemed to be hardware-related. Sometimes giving the browser more time may result in all tiles being rendered but sometimes it won't be sufficient either as there is not enough gpu memory or something else. There is not much we can do on the Playwright end as this is handled inside Chromium. You are saying though that it generates correctly in puppeteer, so the problem must be in the timing as both projects use same CDP commands to communicate with the browser. Can you show the pptr script that produces full image?

Thank you for your reply! I have add puppeter script that works correctly to my git repository :  https://github.com/CaoGaorong/PlaywrightTesting.git (same as above). 

And I've test my script for thousands of times(using a python script) in my computer: 
- Image generated by Playwright, the accurate rate was 64%.
- Image generated by Puppeteer, the accurate rate was 100%
So I thought the difference  may not caused by timing.

**Comment by CaoGaorong** [comment] 2021-12-23 09:28
> I can reproduce the problem on Mac but only in headless mode, sometimes it renders full image but most of the time part of the image will be blank similar to your screenshot. As I mentioned there is not much we can do on the Playwright end about the rendering, as a workaround you can try running in headful mode.

Yes, you are right! This problem won't accur in headful mode. But my script will run in a backend linux server without GUI, so I thought it may not work, lol.

**Comment by CaoGaorong** [comment] 2021-12-23 09:41
In addition, my requirement is:
- receive an rich text (will be converted to html source code)
- convert the html to image (whatever technology, I choose playwrigh)
- save the image
It can help me a lot  if you can give some advices about how to speed up the process above. Such as some playwright trick ? Or some technology to speed up converting html to image in backend server.
I'd appreciate your help. (It is OK to ignore it if you are busy).  
At last, thank you again for your reply. (It is my first time to communicate programming using English, so I am sorry for my pool English)

**Comment by yury-s** [comment] 2021-12-23 18:49
> Thank you for your reply! I have add puppeter script that works correctly to my git repository : https://github.com/CaoGaorong/PlaywrightTesting.git (same as above).

Thank you. Looking at the code there should be no discrepancies in the output. I suspect we may start browser with different command line options which affects the rendering behavior, I'll look into that.

> Yes, you are right! This problem won't accur in headful mode. But my script will run in a backend linux server without GUI, so I thought it may not work, lol.

Note that the behavior varies from machine to machine, I was not able to reproduce the problem on my linux box.

**Comment by yury-s** [comment] 2021-12-23 19:23
> I suspect we may start browser with different command line options which affects the rendering behavior, I'll look into that.

Starting with the same flags doesn't make any difference.

Also when launching with `DEBUG=pw:browser` there is a number of errors:

```
[pid=40565][err] [1223/111918.480565:ERROR:tile_manager.cc(821)] WARNING: tile memory limits exceeded, some content may not draw
```
which basically means that you are pushing the browser over the limits and it may fail any moment which is what happening with the screenshot.

**Comment by yury-s** [comment] 2021-12-23 19:59
Looks like it was fixed by https://github.com/microsoft/playwright/pull/10606 and is now working in playwright@next, I cannot reproduce it on mac anymore.

**Closed by yury-s** 2021-12-23 19:59 UTC
Labels: triaging
