### ISSUE TITLE
[Bug]: User is not able to start browser in debug mode

### ISSUE THREAD

**Issue by Vestrivian** [microsoft/playwright#30787] opened 2024-05-14 12:03 UTC
### Version

v1.1.1

### Steps to reproduce

1. Open repo with playwright config
2. View Test Explorer
3. Attempt to start test with debug mode 

### Expected behavior

Browser opens, test is executed. 

### Actual behavior

Loading loop, browser does not start. 

### Additional context

Issue does not occure for "Run Test" just for "Debug Test"

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 5.39 GB / 15.80 GB
  Binaries:
    Node: 20.10.0 - \nodejs\node.EXE
    npm: 10.2.3 - \nodejs\npm.CMD
  IDEs:
    VSCode: 1.89.1 -\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
```

**Comment by mxschmitt** [comment] 2024-05-14 12:47
Looks like a duplicate of https://github.com/microsoft/playwright/issues/30743

**Closed** 2024-05-14 16:28 UTC
