### ISSUE TITLE
[BUG] Test failures and rendering issues in the latests chromium versions

### ISSUE THREAD

**Issue by dartyuhov** [microsoft/playwright#11743] opened 2022-01-31 08:11 UTC
**Context:**
- Playwright Version: reproduced on 1.17.1
- Operating System:  Windows, Linux, Mac
- Node.js version: v14.15.5
- Browser: Chromium, [build example](https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F962965%2Fchrome-linux.zip?alt=media) (linux)
- Extra: only reproduced on latest versions of chromium.

**Code Snippet**

```javascript
//test.spec.ts
import { test, expect } from '@playwright/test';

test('focus this test', async ({ page }) => {
  await page.goto('https://www.microsoft.com/en-us', {
    timeout: 10000,
    waitUntil: 'networkidle',
  });
  await expect(page.locator('#uhfLogo')).toBeVisible();
  await page.screenshot({ fullPage: true, path: 'ms.png' });
});

//playwright.config.ts
const config: PlaywrightTestConfig = {
  use: {
    channel: 'chrome',
    headless: true,
    viewport: { width: 1920, height: 1080 },
    ignoreHTTPSErrors: true,
    launchOptions: {
      executablePath: 'path_to_executable_from_description_above',
    },
  },
};

})();
```

**Describe the bug**

We use the latest versions of Chromium browser from official [repo](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux/).

After launching the snippet above in HEADLESS mode (this is importnant, headfull is ok), we see unexpected rendering issues, according to trace viewer. Also test fails on the 'await page.screenshot({ fullPage: true, path: 'ms.png' });' step.

![image](https://user-images.githubusercontent.com/30840813/151758715-1eb80259-1288-4540-83ae-c226048f81dd.png)

Probably this is upcoming versions chromium issue.

**Comment by yury-s** [comment] 2022-02-01 03:13
Looks like something is/was broken upstream. The build you refer to is from r962965, we are currently rolling to r965416. Once it lands let's see if the problem is reproducible there.

**Comment by dartyuhov** [comment] 2022-02-01 09:04
@yury-s, Thanks for reply. From your point of view, is it playwright or chromium issue?

**Comment by dartyuhov** [comment] 2022-02-01 11:49
seems like chromium issue 
I reproduced it in wdio with same version of chromium
![image](https://user-images.githubusercontent.com/30840813/151963388-7ef8a9e9-5d8f-400e-be83-8b23aabd0b93.png)

**Comment by yury-s** [comment] 2022-02-01 19:54
> @yury-s, Thanks for reply. From your point of view, is it playwright or chromium issue?

It's definitely an upstream issue.

**Comment by aslushnikov** [comment] 2022-02-08 22:44
Tentatively closing this; it should be fixed upstream! Feel free to re-file if it still doesn't work for you

**Closed by aslushnikov** 2022-02-08 22:44 UTC
Labels: browser-chromium, v1.19
