### ISSUE TITLE
[BUG] `Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>?` for svelte component testing

### ISSUE THREAD

**Issue by aidvai-sp** [microsoft/playwright#23086] opened 2023-05-17 09:36 UTC
Hi, when using playwright to create and execute component testing, I get this error: `Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>?`. It looks like playwright is trying to test my component as it was react component?

To add component testing to SvelteKit project, I used command from the docs of the playwright: `npm init playwright@latest -- --ct`. The project itself was created using SvelteKit creation command: `npm create svelte@latest playwright-bug`

### System info
- Playwright Version: playwright/test: ^1.28.1, playwright/experimental-ct-svelte: ^1.33.0 (copied from `package.json`)
- Operating System: Windows 10
- Browser: All
- Other info: SvelteKit version: ^1.5.0, Svelte version: 3.54.0, vite version: 4.3.0

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.
https://github.com/aidvai-sp/playwright-bug

**Steps**
- Run `npm run test-ct`

**Expected**
Tests are run and their results are given back

**Actual**
Got error `Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>?`, which is meant for react so it doesn't work here.

Edit: I found that these tests are working on my other computer, but all I did was clone the repository, do `npm install` (browsers are already install from before) and run them using `npm run test-ct`

**Comment by aidvai-sp** [comment] 2023-05-18 04:59
This works for react, but I use svelte

**Comment by dgozman** [comment] 2023-05-18 18:36
@aidvai-sp I managed to reproduce the issue with `@playwright/experimental-ct-svelte@1.33`, but not with `@playwright/experimental-ct-svelte@next`, so it seems to be fixed in the recent release. I'd recommend to try a [canary release](https://playwright.dev/docs/canary-releases) for now to see whether it fixes the issue for you.

**Comment by dgozman** [comment] 2023-05-18 23:19
@aidvai-sp Not sure how to help you here. There's probably something wrong with your setup, but I am not sure what. 

- Maybe you have a globally installed playwright somewhere? Run `npm -g ls` to check that.
- Maybe you have some cached files stuck somewhere? Run `rm -rf playwright/.cache` and try removing temporary folders on your computer.
- Try to checkout your sample repo to a different folder and follow the repro steps. Does it repro again?

**Comment by aidvai-sp** [comment] 2023-05-19 07:59
I tried all of these, nothing worked. Maybe there is some way I could see some more logs from playwright? Maybe it would help find what's wrong with it

**Comment by dgozman** [comment] 2023-05-23 15:54
We have to reproduce this issue locally to be able to debug it. Unfortunately, the issue seems very specific to your setup. If you gather new information that could help us figure out the problem, please file a new issue and link to this one.

**Closed by dgozman** 2023-05-23 15:54 UTC
Labels: triaging

**Comment by Thevetat** [comment] 2023-06-05 05:15
```
> playwright test -c testing/playwright/component.config.ts


SyntaxError: /home/dean/Git/Vite/nBase/src/App.vue: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>? (5:0)

  3 | </template>
  4 |
> 5 | <script setup lang="ts">
    | ^
  6 | </script>
  7 |


   at component/App.spec.ts:5

  3 |
  4 | test.use({ viewport: { width: 500, height: 500 } })
> 5 |
  6 | test('should work', async ({ mount }) => {
  7 |   const component = await mount(App)
  8 |   await expect(component).toContainText('Vite + Vue')

```

this is my App.vue
```vue
<template>
  <RouterView />
</template>

<script setup lang="ts">
</script>

```

This is the test:

```ts
import { expect, test } from '@playwright/experimental-ct-vue'
import App from '../../../src/App.vue'

test.use({ viewport: { width: 500, height: 500 } })

test('should work', async ({ mount }) => {
  const component = await mount(App)
  await expect(component).toContainText('Vite + Vue')
})
```

Same error as in the svelte file, not sure how to diagnose.

**Comment by Feroks** [comment] 2023-06-06 08:40
I am having the same issue. @aidvai-sp did you find a solution?

**Comment by YoloClin** [comment] 2023-09-06 02:43
I was able to trigger this bug with the above sample repo within a docker container using `docker run -it -v $(pwd):/sync --entrypoint bash node:latest` - I have a similar issue running npm on my host (23.04) when attempting to use a `svelte:component` entity:

```
<svelte:component this={component} ... />
```

```
import Test from './test-components/Test.svelte';

test.use({ viewport: { width: 500, height: 500 } });

test('should work', async ({ mount }) => {
  //  const component = await mount(Test, {});
  let test = "Test";
  const component = await mount(App, {
    props: {
      component: Test,
    }
  });
```

```
> playwright test -c playwright-ct.config.ts
SyntaxError: .../components/src/lib/test-components/Test.svelte: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>? (5:0)

  3 | </script>
  4 |
> 5 | <h1>Hello World</h1>
```

Please let me know if a more complete sample is required.

**Comment by markjaquith** [comment] 2023-09-11 17:19
I've been having this issue too. The last stable version of `@playwright/experimental-ct-svelte` for me was `1.29.2`... everything after that has been broken.

**Comment by nickpalmer** [comment] 2024-10-30 17:42
Why is this issue closed with no comment on how it was resolved?
I upgraded to 1.47.1 and have exactly this problem.

**Comment by CraigglesO** [comment] 2025-04-16 18:29
I was having this problem forever and it was driving me INSANE, so hopefully I can help some people:

1) I could not get vue in my case working until I upgraded all the @playwright/* packages to [1.52.0-beta-1744820742000](https://www.npmjs.com/package/@playwright/test/v/1.52.0-beta-1744820742000). In my case:
```
"devDependencies": {
    "@happy-dom/global-registrator": "^17.4.4",
    "@maplibre/maplibre-gl-style-spec": "^23.1.0",
    "@nuxt/eslint": "^1.3.0",
    "@playwright/experimental-ct-vue": "1.52.0-beta-1744820742000",
    "@playwright/test": "1.52.0-beta-1744820742000",
    ...
}
```

1.51 does NOT work.

Next, I put the whole playwright structure in its own folder, then ran `tsc --init` to ensure it has a basic tsconfig that works for it exclusively.

That's it. Should work at this point.

I think this was a me unique problem but `components.d.ts` actually stored my component files wrong (it's auto generated), and when I adjusted the path that also helped some type linting issues.
