### ISSUE TITLE
[BUG] Firefox: ASRouterNewTabHook.jsm, line 61: TypeError: this._router is null

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#5355] opened 2021-02-08 17:30 UTC
Reported:

- https://github.com/microsoft/playwright-sharp/issues/1101
- https://github.com/microsoft/playwright-python/issues/477#issuecomment-774386406
- https://github.com/microsoft/playwright-python/issues/509 - with the normal JS variant

~Upstream issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1690231~

The issue itself causes a full defect of Firefox for some users.

**Comment by aslushnikov** [comment] 2021-02-16 05:38
We get this error on every browser launch, yet only some clients report that Firefox fails to start... it doesn't look like this error is at fault here.

**Comment by aslushnikov** [comment] 2021-02-19 17:12
I checked and the mentioned upstream patch doesn't change things for me.

We also *think* this is a dupe of https://github.com/microsoft/playwright/issues/4660, so speculatively merging there.

**Closed by aslushnikov** 2021-02-19 17:12 UTC
Labels: P1-resolve-asap
