### ISSUE TITLE
[Feature]: Hide / remove sensitive data from trace and any report with a new method or new attribute

### ISSUE THREAD

**Issue by marcosvfranco** [microsoft/playwright#31728] opened 2024-07-17 13:11 UTC
### 🚀 Feature Request

As described on [this issue](https://github.com/microsoft/playwright/issues/19992), we need a feature that can hide all secrets we use in our tests, using any kind of methods that put values into fields, lile `locator.fill()` or `elementHandle.fill()`

This will prevent any sensitive info to be logged into the reports and also on the trace
![image](https://github.com/user-attachments/assets/80f251bf-2bd7-4c67-aa71-b447661a2450)

Regards

### Example

An idea of a name for this method could be `fillSecure()` or add an additional parameter into the `fill()` method like `{ maskSecrets: true }`
Also, Playwright could have a boolean config to scrub logs and traces before they are saved on disk, or emitted to std.

### Motivation

We need to prevent leaks of sensitive data on our CI's , principally, and be able to not register data we dont want to share in any logs.
We have some statements from people that had problem with this also [here](https://github.com/microsoft/playwright/issues/19992) 

Besides, other frameworks have features that can solve this problem like in Cypress (a good article [here](https://dev.to/walmyrlimaesilv/how-to-protect-sensitive-data-with-cypress-44d3)) or in Log4J

**Comment by dgozman** [comment] 2024-07-17 17:54
As explained in https://github.com/microsoft/playwright/issues/19992#issuecomment-2035689947, we won't be able to provide a comprehensive way to hide all sensitive information from the report/trace, and so we don't want to implement a feature that will promise something unattainable.

If you'd like to implement the "scrubbing of logs and traces", it seems like a standalone package that will postprocess any information produced by Playwright would be as useful as anything built-in.

I'll close this issue as a duplicate of #19992.

**Closed by dgozman** 2024-07-17 17:54 UTC
