### ISSUE TITLE
[BUG] 1.38.1 trace EPERM: operation not permitted, rename 'C:\...'

### ISSUE THREAD

**Issue by daniavander** [microsoft/playwright#27525] opened 2023-10-10 13:31 UTC
I use 1.38 version, but if i create trace I get an error: EPERM: operation not permitted, rename 'C:\...'  (the test pass but the suite fail due to this error)

If i downgrade to 1.37 version with the same options everything is ok, pass the test 

### System info
- Playwright Version: [v1.38.1, v1.37.1]
- Operating System: win 11
- Browser: All

### Source code

**Config file**

```

import { defineConfig, devices } from '@playwright/test';
export default defineConfig({
use: {
    launchOptions: {
      slowMo: 300
   },
    headless: false,
    acceptDownloads: true,
    permissions: [ 'notifications', 'geolocation' ],
    trace: process.env.CI ? 'retain-on-failure' : 'on',
    screenshot: 'on'
 },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Comment by dgozman** [comment] 2023-10-10 16:49
We need more information to act on this issue. Adding as much details as you can would be helpful. Could you please provide a repro that we can run locally?

**Comment by daniavander** [comment] 2023-10-13 07:51
i run same test with v1.38or 1.39 i get an error: Error: EPERM: operation not permitted, rename 'C:\...trace.zip' -> 'C:...trace.zip'

when wun with 1.37 version the same test will pass

**Comment by dgozman** [comment] 2023-10-16 19:29
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.

**Comment by nzacca** [comment] 2023-10-16 19:33
@dgozman 

I have a minimal reproduction but I'm not sure if this is the same situation as the OP.

```ts
import { BrowserContext, expect, Page, test as baseTest } from "@playwright/test";

let pg: Page;
let context: BrowserContext;

const test = baseTest.extend({
	page: async ({}, use) => {
		await use(pg);
	},
	context: async ({}, use) => {
		await use(context);
	},
});

test.beforeAll(async ({ browser }) => {
	context = await browser.newContext();
	pg = await context.newPage();
});

test.beforeAll(async ({ page }) => {
	await page.goto("https://playwright.dev");
});

test.afterAll(async () => {
	await context.close();
});

test("foo", async ({ page }) => {
	await expect(page.locator("h1")).toContainText("Playwright");
});
```

Config:
```ts
import { defineConfig } from "@playwright/test";

export default defineConfig({
	use: {
		trace: "on",
		video: "on",
	},
});
```

Some notes:
* This was working in 1.37.1 but broke in 1.38
* If we comment the entire `afterAll` block, test passes.
* If we comment just the `context.close()` but leave the empty `afterAll` block, the EPERM error presents itself.
* The actual assertion passes and everything works based on the trace/video that is produced but it fails when trying to move the trace file.
* We are using Windows 11 like the OP.
* If we turn off `trace`, the test passes since there's no file to move (as expected).

**Comment by nzacca** [comment] 2023-10-16 19:34
@dgozman 

Oh no! I'm too late! 😄

**Comment by nzacca** [comment] 2023-10-16 19:43
@dgozman 

Thank you for reopening! I made a small edit to the example by changing the `context` variable. I noticed that I was not referencing it properly in the `afterAll` but this did not affect the outcome. Same issue is present.

**Comment by mxschmitt** [comment] 2023-10-18 12:45
I can reproduce on Windows with the repro above.

```
  2) [firefox] › example.spec.ts:28:1 › foo ────────────────────────────────────────────────────────

    Error: EPERM: operation not permitted, rename 'C:\Users\maxschmitt\Desktop\projects\testproject\test-results\example-foo-firefox\trace.zip' -> 'C:\Users\maxschmitt\Desktop\projects\testproject\test-results\example-foo-firefox\trace.zip.tmp'
```

**Comment by yury-s** [comment] 2023-10-18 23:43
Folding into https://github.com/microsoft/playwright/issues/27286

**Closed by yury-s** 2023-10-18 23:43 UTC
Labels: v1.40

**Comment by KronosTriton** [comment] 2023-11-13 06:44
EPERM error on Windows 2016...
This issue got repro'ed just today when using Playwright v1.39...exact repro steps need to be determined.
Crashdump is yet to be captured. Will share if I can.

Error shown:

Error in reporter [Error: EPERM: operation not permitted, copyfile 'D:\projects\VScode\playwright-demo\node_modules\playwright-core\lib\vite\htmlReport\index.
html' -> 'D:\projects\VScode\playwright-demo\playwright-report\index.html'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'copyfile',
  path: 'D:\\projects\\VScode\\playwright-demo\\node_modules\\playwright-core\\lib\\vite\\htmlReport\\index.html',
  dest: 'D:\\projects\\VScode\\playwright-demo\\playwright-report\\index.html'
}

**Comment by nzacca** [comment] 2023-11-13 19:32
@KronosTriton The commit that fixes this is not released yet. You can try updating to the prerelease version to test if that fixes your scenario while we wait for the next release. 

https://www.npmjs.com/package/@playwright/test/v/1.40.0-alpha-oct-20-2023

**Comment by surajsahu8** [comment] 2023-11-23 11:47
Is this published? I'm seeing same in v1.40.0

**Comment by dgozman** [comment] 2023-11-23 18:21
@surajsahu8 Please file a new issue with a repro by filling in the "Bug Report" template.
