### ISSUE TITLE
[BUG] UI mode not recognize tests

### ISSUE THREAD

**Issue by szamacz** [microsoft/playwright#21946] opened 2023-03-24 06:53 UTC
### System info
- Playwright Version: 1.32
- Operating System:Win 10
- Browser: All
- Node version: 16.10.0

We have custom apitest and uitest attributes that extends base test attribute
```
export const uitest = base.extend<{
  somePage: SomePage;
}>({
  somePage: async ({ page }, use) => {
    await use(new SomePage(page));
  },
 
  storageState: getSessionStorage(),
});
```
Tests are recognizable by vscode test runner (Playwirght Trest for VS Code) but UI mode shows no tests.
![image](https://user-images.githubusercontent.com/25122771/227447134-5e0a7fbf-1ab9-4422-b1e8-8472b8a0b708.png)

![image](https://user-images.githubusercontent.com/25122771/227446894-659ef90f-d756-4249-9ea0-5eac36f6aeae.png)

**Comment by aslushnikov** [comment] 2023-03-24 07:03
@szamacz can you please share a small repro that we can run locally to reproduce this?

**Comment by michallbanas** [comment] 2023-03-24 07:47
@aslushnikov I think it has something to do with naming your tests. I quickly created a simple repo for it: https://github.com/michallbanas/pwTestRepo

But you can also see it on screenshot here. 
- there are 3 tests in VS Code: example.spec.js, test.js, hp.js
- but you can see only example.spec.js and test.js in UI
![pwTest](https://user-images.githubusercontent.com/63734693/227456815-2c06139c-0fc6-450b-9bae-d143e30c3c7a.png)

**Comment by aslushnikov** [comment] 2023-03-24 07:59
@michallbanas works for me on MacOS; maybe it's windows-specific.

@mxschmitt could you please try to reproduce on win?

**Comment by michallbanas** [comment] 2023-03-24 08:01
@aslushnikov I'm on macOS and can't see all the test 👀

**Comment by aslushnikov** [comment] 2023-03-24 08:07
@michallbanas so, actually your VSCode has only 2 test files: `test.js` and `example.spec.js`, while the `hp.js` is not considered to be a test file, since it doesn't end on `test.js` or `spec.js`.

If you open the file in VSCode, you won't see the "green triangles" next to tests as well:

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/746130/227461393-c7dc1332-67dd-407b-9289-df0b5b3cb3eb.png">

So it does look like UI mode matches the VSCode

**Comment by michallbanas** [comment] 2023-03-24 08:12
@aslushnikov oh, I should have noticed it, so apologize then and thanks for explaining 🙏

**Comment by aslushnikov** [comment] 2023-03-24 08:23
Sweet, closing then!

**Closed by aslushnikov** 2023-03-24 08:23 UTC
Labels: triaging, feature-ui-mode
