### ISSUE TITLE
[BUG] Drag and Drop working but test execution is then stuck

### ISSUE THREAD

**Issue by AlixBarreaux** [microsoft/playwright#21621] opened 2023-03-13 12:25 UTC
Hello everyone, I tried to use the dragTo() method on some websites and it did work, but not on the React app I'm testing.

## Context
Here is the app setup:
- A drawer on the left where the draggable elements are contained.
- A "drop zone" where these elements are dragged into: The "window" (div) on the right.
- Only one draggable element can be dragged at a time.

**Screenshot:**
![drag_and_drop_issue](https://user-images.githubusercontent.com/71342682/224677047-e6474ffc-96ac-43d0-abae-f4764bd6239e.png)

When I use dragTo() on the app (we're testing on Firefox only, the other browsers are not supported by the app) though everything works, the dragged element is dropped and I can see it in the drop zone.
Technically it's there and it worked. But Playwright is stuck and doesn't go through the rest of the code.

**Playwright inspector report:**
`npx playwright test tests/draggable-fields/shortText.spec.ts --project="firefox" --debug`

```
.dragTo()
waiting for getByText('Short text')
locator resolved to <span title="Short text" class="Item__label--q7H3F">Short text</span>
attempting move and down action
waiting for element to be visible and stable
element is visible and stable
scrolling into view if needed
done scrolling
performing move and down action
move and down action done
waiting for scheduled navigations to finish
navigations have finished
waiting for getByRole('main').locator('div').nth(2)
locator resolved to <div class="Grid--17ofs WYSIWYGGridPage--1Iqx8">…</div>
attempting move and up action
waiting for element to be visible and stable
element is visible and stable
scrolling into view if needed
done scrolling
performing move and up action
```
-> Stuck there

### What I tried
I did try to mess with many other workarounds like using mouse.move() and mouse.down() IIRC and the problem _seems_ to be occurring when a mouse up action is performed.

So I went on the app and executed some JS in the console in order to know what's going on with mouse events:
```
  document.onmousedown = (event) => {
    console.log("mouse down event", event.x, event.y);
  }


  document.onmouseup = (event) => {
    console.log("mouse up event", event.x, event.y);
  }
```

Thanks to this I figured out:

- The _mousedown_ and _mouseup_ events are detected when I left click, move anywhere in the left drawer and release left click on a draggable element.
- The _mousedown_ and _mouseup_ events are detected when I left click, move and release left click inside the drop zone. (without dragging any element)
- Once a draggable element is inside the drop zone, the _mousedown_ and _mouseup_ events are detected when I left click, move and release left click **inside the draggable element (without moving outside of the draggable element)** contained in the drop zone.
- When a draggable element is inside the drawer, the _mousedown_ and _mouseup_ events are detected when I left click, move and release left click **inside the draggable element (without moving outside of the draggable element)** contained in drop zone.
- **Now possibly the culprit:** The _mousedown_ event is detected but NOT _mouseup_ when I left click on a draggable element inside the drawer, move it to the drop zone and release left click inside the drop zone.

### Bug Reproduction
I can't share the app here but I can try to ask my team to do so. I also didn't make this app myself.

An information which could be very useful though is that this app uses this package:

App's package.json:
```
"react-dnd": "11.1.3",
"react-dnd-html5-backend": "11.1.3",
```
https://www.npmjs.com/package/react-dnd

I suspect it to be the cause of this issue.

### System info
- Playwright Version: [v1.31.1]
- Operating System: [Windows 10 Pro]
- Browser: [Firefox]
- Other info:   IDE: VSCode 

### Source code
```
import { test, expect, Page } from '@playwright/test';
test(`Drag and Drop`, async ({ page }: any): Promise<void> => {
  const dropZone = await page.getByRole('main').locator('div').nth(2);
  await page.getByText('Short text').dragTo(dropZone);
});
```

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
    testDir: './tests',
    timeout: 15 * 1000,
    expect: {
        timeout: 5000
    },
    fullyParallel: true,
    forbidOnly: !!process.env.CI,
    retries: process.env.CI ? 2 : 0,
    workers: process.env.CI ? 1 : undefined,
    reporter: 'html',
    use: {
        actionTimeout: 0,
        trace: 'on-first-retry',
    },

    projects: [
        {
            name: 'firefox',
            use: { ...devices['Desktop Firefox'] },
        },
        {
            name: 'Microsoft Edge',
            use: { channel: 'msedge' },
        },
        {
            name: 'Google Chrome',
            use: { channel: 'chrome' },
        },
    ]
});
```

**Comment by dgozman** [comment] 2023-03-13 21:19
@AlixBarreaux Great analysis! Unfortunately, we still need a repro to tackle this issue. Perhaps you could arrange to share the app? Or maybe check some `react-dnd` examples - perhaps there is a publicly available example that exhibits this issue?

**Comment by AlixBarreaux** [comment] 2023-03-14 10:16
@dgozman Thanks! I'll ask them to provide access to it.
However the good news is it _might_ not be necessary since I do have some kind of repro based on an online example I have found which seems to confirm my observations:

1. Go to this example: https://codesandbox.io/s/react-dnd-example-try06
2. On the right window click on "Console"
3. Enter the following code in this new console (at the very bottom to the ">") :
```
document.onmousedown = (event) => {
  console.log("mouse down event:", event);
}

document.onmouseup = (event) => {
  console.log("mouse up event:", event);
}
```
4. Drag and drop an Item to an empty slot and watch carefully what's going on in the console at each mouse input. See what I mentioned above in the section **What I tried**

**Comment by dgozman** [comment] 2023-03-15 22:08
@AlixBarreaux I was not able to reproduce the issue, unfortunately. I copied this example project from codesandbox, and created the following test file:

```ts
// dnd.spec.ts
import { test, expect } from '@playwright/test';

test('dnd', async ({ page }) => {
  await page.goto('http://localhost:3000/');

  await page.waitForTimeout(3000);

  const from = page.getByText('Item 1');
  const to = page.getByText('In Progress');
  await from.dragTo(to);

  await page.waitForTimeout(3000);
});
```

Running it all like this:
```bash
npm i
npm i @playwright/test
npm start

# another terminal
npx playwright test --headed
```

In this setup, `Item 1` is successfully dragged over to `In Progress`.

---

Unfortunately, I will have to close the issue if we do not come up with a repro. Let me know if you have anything else to share.

**Comment by AlixBarreaux** [comment] 2023-03-17 09:40
## Good news:
My team granted you access to the app.

## Repro:
The authentication part doesn't seem relevant to put here to me but I can do it if you still need it. It'll be done manually in this repro.
I just prefer to keep the code simple and straight to the point. **Remember the project works on Firefox Only!**

### Here are the steps to reproduce the problem:

Run this command in your playwright project to launch the test file with these arguments:
`npx playwright test tests/dragAndDrop.spec.ts --debug --project="firefox"`

**Do not do anything with Codegen, do this before you launch the next code step!**

Go to: http://cd-v5-demo.wirk.io/
Under Logger section, make sure you have: "User not logged in"
Click on "Login" link
You should be redirected to the authentication url
Enter the username: alt.z2-5oilod4b@yopmail.com
Enter the password: Password,123456
Click on "Login" button
You should be redirected to the initial url and in the Logger section you should have "User logged in. Access token: xxxx"
Click on the link "Link to Form Builder"
You should be redirected to the app

Now in Codegen click on the resume button to run the drag and drop test code.

```
import { test } from '@playwright/test';
//import { authenticateUserAndGoToFormBuilder } from '../macros/authenticateUser.macro';

test('Login on test page and do stuff on Form)', async ({ page }: any): Promise<void> => {
  // This method bellow is basically doing everything you've done manually
  //authenticateUserAndGoToFormBuilder(page);
  await page.pause();
  await page.getByText('Short text').dragTo( page.locator('.Grid--17ofs'));
  console.log("Instructions after drag and drop executing...");
})
```

The console.log will not be executed.

**Comment by michaelmarzouk** [comment] 2023-03-20 08:49
any update on this issue?

**Comment by unickq** [comment] 2023-03-20 16:54
@AlixBarreaux 

Your example with https://codesandbox.io/s/react-dnd-example-try06 works for me:

```ts
import { test } from "@playwright/test";

test("Drag an Drop W3School - dragTo", async ({ page }) => {
  await page.goto("https://codesandbox.io/s/react-dnd-example-try06");

  const iframe = page.frameLocator('iframe[title="react-dnd-example"]');
  const draggableItem = iframe.getByText("Item 1");
  const dropZone = iframe.locator(".in-progress-column");

  await draggableItem.dragTo(dropZone);
});

```
for chrome
![image](https://user-images.githubusercontent.com/6696821/226411512-90996829-17f5-4a2c-8ecf-17abbee70697.png)
and ff
![image](https://user-images.githubusercontent.com/6696821/226412055-6b97c6b3-3a69-442a-a975-91335ca521ba.png)


But I can't test your app http://cd-v5-demo.wirk.io/, since creds doesn't work

**Comment by AlixBarreaux** [comment] 2023-03-21 10:07
@unickq Hmm I tried my own example based on codesandbox again and it works on firefox and chrome indeed. Nevermind!

In order to access the app, make sure you use Firefox only since other browsers are not be supported. It might be the issue.

**Comment by eugeniuszG** [comment] 2023-03-22 19:03
This is not the issue of Playwrghit I guess. This is just because the draggable element getting destroyed from the Html DOM and thus mouse.up() will never happen.

@dgozman I was debugging this issue but couldn't find the answer. So my question is: if we destroy `elementToDrag` from the DOM, what kind of behavior we will get?

**Closed** 2023-04-05 18:39 UTC
Labels: v1.33
