### ISSUE TITLE
[Bug]: Playwright inspector was not visible with screen size 14 Inches

### ISSUE THREAD

**Issue by Lakshmi-Yaswanth** [microsoft/playwright#7825] opened 2021-07-24 07:41 UTC
### Playwright version

1.13.0

### Operating system

Windows

### Other information

Playwright inspector

### What happened? / Describe the bug

When running playwright code generator chromium page was open but playwright inspector was opened but cant able to see in the screen. But when we are using laptop with more screen we can able to view it.
For your reference: video url
https://user-images.githubusercontent.com/61179075/126861280-159115f1-3b4d-4d4a-8c9e-4b980b58ad19.mp4

And expectation was it should support for laptop with small screen also. Thank you in advance

**Comment by mxschmitt** [comment] 2021-07-25 20:25
Seems like a duplicate of #5696 to me, please upvote it there.

**Comment by dgozman** [comment] 2021-07-26 22:30
Closing in favor of #5696.

**Closed by dgozman** 2021-07-26 22:30 UTC
Labels: triaging
