### ISSUE TITLE
[Bug]: Cant run tests from the terminal

### ISSUE THREAD

**Issue by YenovSegal** [microsoft/playwright#32519] opened 2024-09-09 13:26 UTC
### Version

v1.47.0

### Steps to reproduce

1. Write Parameterize tests
2. Run the whole test from the terminal

### Expected behavior

tests run from the terminal

### Actual behavior

tests not run from the terminal

### Additional context

![image](https://github.com/user-attachments/assets/1ed9d1c1-6176-4064-8e2e-e1926023be89)

### Environment

```shell
os_platform - win32
os_release - 10.0.22631
os_version - Windows 11 Pro
node_version - v20.16.0
chrome_version - 128.0.6613.120
```

**Comment by marshmn** [comment] 2024-09-09 18:05
I would assume that wherever `userNameTwo` and `userNameThree` are coming from, they are undefined. Hence you're ending up with two tests with the same name as stated in the error message (e.g. "Set the user name to undefined").

Playwright requires that names be unique for each test, and the fact that these variables are undefined is breaking that rule.

**Comment by marshmn** [comment] 2024-09-09 19:18
Also, appears to be a duplicate of #32462

**Comment by YenovSegal** [comment] 2024-09-09 20:08
> I would assume that wherever `userNameTwo` and `userNameThree` are coming from, they are undefined. Hence you're ending up with two tests with the same name as stated in the error message (e.g. `Set the user name to undefined`).
> 
> Playwright requires that names be unique for each test, and the fact that these variables are undefined is breaking that rule.

The variables `userNameTwo` and `userNameThree` come from the ENV file and are definitely defined there

**Comment by marshmn** [comment] 2024-09-09 21:19
The error messages suggest they are not defined. I would suggest adding some debug output to see for yourself.

**Comment by YenovSegal** [comment] 2024-09-10 07:35
> The error messages suggest they are not defined. I would suggest adding some debug output to see for yourself.

It works for me when I run the extension and it gives me the usernames, but when I run it from the terminal it doesn't work and says it's undefined.

this is my code:

![image](https://github.com/user-attachments/assets/b87951b5-834b-4c95-bfe1-cbeffe6a23bc)
![image](https://github.com/user-attachments/assets/f43e7d4f-ed08-4a68-a80d-d5e8ac9d5c91)

**Comment by dgozman** [comment] 2024-09-10 08:08
@YenovSegal Could you please provide a repro that we can run locally? Otherwise, we won't be able to help.

**Comment by YenovSegal** [comment] 2024-09-11 10:23
> @YenovSegal Could you please provide a repro that we can run locally? Otherwise, we won't be able to help.

I can't share the repo this is of the company

**Comment by dgozman** [comment] 2024-09-11 10:30
@YenovSegal Well, we do test Playwright with parameterized tests, so it works. The problem is in your specific setup. If you won't be able to share a repro, we won't be able to help you.

**Comment by YenovSegal** [comment] 2024-09-11 10:40
> @YenovSegal Well, we do test Playwright with parameterized tests, so it works. The problem is in your specific setup. If you won't be able to share a repro, we won't be able to help you.

I discovered something.

If I directly define the variables from the file like this, it works : [{ newUserName: **process.env.USER_NAME_TWO!** },{ newUserName: **process.env.USER_NAME_THREE!** }].forEach(({ newUserName }) => {

But if I define the variables indirectly like this, it doesn't work: 
![image](https://github.com/user-attachments/assets/b87951b5-834b-4c95-bfe1-cbeffe6a23bc)
![image](https://github.com/user-attachments/assets/f43e7d4f-ed08-4a68-a80d-d5e8ac9d5c91)

**Comment by dgozman** [comment] 2024-09-11 11:25
@YenovSegal Well, most likely nothing reads them from the `.env` file into environment.

**Comment by YenovSegal** [comment] 2024-09-11 13:38
> @YenovSegal Well, most likely nothing reads them from the `.env` file into environment.

So its bug?

**Comment by dgozman** [comment] 2024-09-11 13:49
@YenovSegal Did you follow [the documentation](https://playwright.dev/docs/test-parameterize#env-files)? Since you are not sharing a repro, I cannot check whether there is a bug. We can only fix a bug once we have a repro that we can run locally.

**Comment by dgozman** [comment] 2024-09-13 09:58
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.

**Closed by dgozman** 2024-09-13 09:58 UTC
