### ISSUE TITLE
[BUG] No way to prevent unhandled promise rejection in interception of requests - race condition

### ISSUE THREAD

**Issue by jazoom** [microsoft/playwright#6317] opened 2021-04-26 03:37 UTC
**Context:**
- Playwright Version: 1.10.0
- Operating System: Linux
- Node.js version: official docker image
- Browser: Chromium

when intercepting requests like this:

```
  await page.route('**/*', (route, request) => {
      // block certain domains
      if (hostsBlacklist[request.url()]) {
        return route.abort();
      }
      // block certain resources
      if (blockResources.includes(request.resourceType())) {
        return route.abort();
      }
      route.continue();
    });
```

I frequently get errors like this:

```
name: 'Error',
message: 'route.abort: Target page, context or browser has been closed'
```

and this:

```
name: 'Error',
message: 'route.continue: Target page, context or browser has been closed'
```

I think this is a race condition, where the context is closed after the request has commenced but before the intercept code has completed.

In my code, once the required data has been extracted from a web page the context is closed like this

```
    await delay(2000); // adding a timeout here prevents the errors - the longer the timeout, the fewer the errors
    context && await context.close();
```

I have tried using `try/catch`, but that doesn't prevent these unhandled promise rejection errors.

I have also tried checking for the existence of `page && context` prior to calling `route.abort()` or `route.continue()`, but the errors still happen.

This seems like a pretty basic issue, so it's possible I'm doing something wrong. I have only just switched from Puppeteer and never saw this error in Puppeteer with very similar code. I didn't use any kind of hacky 'delay' previously either.

**Comment by mxschmitt** [comment] 2021-04-27 09:23
Thanks for reporting this issue and the detailed explanation! A similar related issue was fixed in #5729 IIRC. Are you able to reproduce it on your end and create maybe a minimal reproducible? Also testing it on the latest dev version `npm install playwright@next` would be awesome, so we can verify that its still persistent there.

**Comment by pavelfeldman** [comment] 2021-04-29 19:19
`return route.abort();` does not await anything, you just return a promise from an event handler. It then rejects and becomes unhandled. You should say `route.abort().catch(() => {})`

**Comment by jazoom** [comment] 2021-04-30 23:42
> Thanks for reporting this issue and the detailed explanation! A similar related issue was fixed in #5729 IIRC. Are you able to reproduce it on your end and create maybe a minimal reproducible? Also testing it on the latest dev version `npm install playwright@next` would be awesome, so we can verify that its still persistent there.

This problem is perfectly reproducible with my setup. It happens consistently on both the current stable version and the @next version.

I spent a bit of time trying to make the reproduction minimal but I realised I was essentially just going to re-create a basic crawler that quickly jumps between pages while doing some intercepting, which I'm sure you already have tests for anyway. On thinking about it, perhaps I'm seeing this error and you're not because the crawling code is separate to the Playwright server (`const browserServer = await chromium.launchServer()`)? I changed both the application and the server to playwright@next to test it.

**Comment by jazoom** [comment] 2021-04-30 23:43
> `return route.abort();` does not await anything, you just return a promise from an event handler. It then rejects and becomes unhandled. You should say `route.abort().catch(() => {})`

Thanks. This fixes the problem for now.

**Comment by mxschmitt** [comment] 2021-05-05 21:18
Closed for now since it seems fixed on the user-land.

**Closed by mxschmitt** 2021-05-05 21:18 UTC
Labels: triaging

**Comment by ww-9** [comment] 2021-06-08 11:31
> `return route.abort();` does not await anything, you just return a promise from an event handler. It then rejects and becomes unhandled. You should say `route.abort().catch(() => {})`

How to proceed in case of python?
