### ISSUE TITLE
[Regression] Font has been changed inside of Docker from 1.16

### ISSUE THREAD

**Issue by xuanzhaopeng** [microsoft/playwright#10330] opened 2021-11-15 21:06 UTC
**The issue:** 
the font has been changed

**The reason:**  
following line has been introduced from 1.16.x . I build my own docker image and install x11vnc, I can also reproduce this issue. 
```
RUN apt-get update && apt-get install -y x11vnc
```

**How to reproduce:**
Take screenshot in docker 1.15.2 and docker image 1.16.x 

Use this locator: `xpath=(//body/div)[1]`

```
<!DOCTYPE html>
<html>
	<head>
		<title>Example Domain</title>

		<meta charset="utf-8" />
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<style type="text/css">
			body {
				background-color: #f0f0f2;
				margin: 0;
				padding: 0;
				font-family: -apple-system, system-ui, BlinkMacSystemFont, 'Segoe UI', 'Open Sans', 'Helvetica Neue', Helvetica,
					Arial, sans-serif;
			}
			div {
				width: 600px;
				margin: 5em auto;
				padding: 2em;
				background-color: #fdfdff;
				border-radius: 0.5em;
				box-shadow: 2px 3px 7px 2px rgba(0, 0, 0, 0.02);
			}
			a:link,
			a:visited {
				color: #38488f;
				text-decoration: none;
			}
			@media (max-width: 700px) {
				div {
					margin: 0 auto;
					width: auto;
				}
			}
		</style>
	</head>

	<body>
		<div>
			<h1>Example Domain</h1>
			<p>
				This domain is for use in illustrative examples in documents. You may use this domain in literature without
				prior coordination or asking for permission.
			</p>
			<p><a href="https://www.iana.org/domains/example">More information...</a></p>
		</div>
	</body>
</html>

```

**Comment by xuanzhaopeng** [comment] 2021-11-15 21:08
link to https://github.com/microsoft/playwright/issues/9975

cc: @aslushnikov

**Comment by aslushnikov** [comment] 2021-11-16 00:41
@xuanzhaopeng we no longer install VNC in docker - should be good in 1.17, but I'll investigate why did fonts change!

**Comment by xuanzhaopeng** [comment] 2021-11-16 17:45
Hey @aslushnikov  sorry for annoying question, you mentioned should be good in 1.17 but you add 1.18 tag?

**Comment by aslushnikov** [comment] 2021-11-18 01:55
@xuanzhaopeng yep, in 1.17.0-rc1 it is already good; check it out.

I added the 1.18 tag for myself to investigate what's going on here for the next release. We do want to add VNC in here eventually.

**Comment by xuanzhaopeng** [comment] 2021-11-23 00:13
Hey @aslushnikov ,  thanks a lot for your quick reply. 

seriously I really wanna have 2 separated docker image, one like playwright-slim,  another one can have anything we want.

Due we may run Playwright among a lot of machines, this VNC cannot help us but it will consume more resources in CI

Hopefully you could consider this

**Comment by ssams** [comment] 2021-12-07 11:16
I think I'm seeing the same issue if I read the title of this issue correctly - default fonts in Firefox seemingly have changed after upgrading from 1.16.3 to 1.17.0.

In our project I've got screenshots which were created with Firefox in the image `mcr.microsoft.com/playwright:v1.6.3`. When running these again with `mcr.microsoft.com/playwright:v1.17.0`, differences on texts on native/unstyled `button` and `input` elements are reported (not sure about other texts at the moment, for sure have seen it on these elements).

**Comment by ssams** [comment] 2021-12-07 11:38
hm, available fonts within the containers seem to be really different according to the output of the `fc-list` command. "Terminus" and "DejaVuSans" are present in 1.16.3, but not in 1.17.0 - isn't especially the latter one the usual default font used by Firefox on most systems?
```
❯ docker run --rm -it mcr.microsoft.com/playwright:v1.16.3 fc-list | grep DejaVu
/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf: DejaVu Serif:style=Bold
/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf: DejaVu Sans Mono:style=Book
/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf: DejaVu Sans:style=Book
/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf: DejaVu Sans:style=Bold
/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf: DejaVu Sans Mono:style=Bold
/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf: DejaVu Serif:style=Book
```
```
❯ docker run --rm -it mcr.microsoft.com/playwright:v1.17.0 fc-list | grep DejaVu

```

**Comment by ssams** [comment] 2021-12-07 12:09
Did some more tests with the failing screenshots in my project, installing the package `fonts-dejavu-core` in the 1.17 container before running the tests solves the problem (no other modifications), the snapshot tests succeeded without errors again.

When comparing packages installed in the containers, the difference seems to be due to the removal of the `fluxbox` package, which [was installed in 1.16.3](https://github.com/microsoft/playwright/blob/v1.16.3/utils/docker/Dockerfile.focal#L36) but isn't anymore in [1.17.0](https://github.com/microsoft/playwright/blob/v1.17.0/utils/docker/Dockerfile.focal). Dependencies of fluxbox (`> libfontconfig1 > fontconfig-config > fonts-dejavu-core`) then triggered automatic installation of the font, which apparently is selected when available by Firefox.

Maybe consider installing at least the specific font package in the official Dockerfile again to restore the old behavior?

**Comment by aslushnikov** [comment] 2021-12-10 02:55
> I think I'm seeing the same issue if I read the title of this issue correctly - default fonts in Firefox seemingly have changed after upgrading from 1.16.3 to 1.17.0.

@ssams The original issue is vice versa: @xuanzhaopeng updated to 1.16.3 and noticed different fonts.

> When comparing packages installed in the containers, the difference seems to be due to the removal of the fluxbox package, which was installed in 1.16.3 but isn't anymore in 1.17.0. Dependencies of fluxbox (> libfontconfig1 > fontconfig-config > fonts-dejavu-core) then triggered automatic installation of the font, which apparently is selected when available by Firefox.

That's great investigation, thank you! It indeed looks like Firefox defaults to deja vu fonts by default if they are available.

Up until now, we didn't look closely into Visual Regression Testing, so we weren't very accurate with fonts in the container. Sorry for the inconvenience!

As we're focusing on this domain, we'll figure out if we need to add any missing fonts and keep them intact as the time goes.

Action items for me:
- [ ] do we have a separate container that we treat with extra care for VRT?
- [ ] do we add Deja Vu & Terminus fonts in the container? (these come with vnc image)
- [ ] make sure to fix list of fonts inside container (using `fc-list`)

**Comment by pengpengzx** [comment] 2022-01-10 11:14
Hi👋,  I have the same issue between Docker v1.12.3-focal and github action [ubuntu-20.04](https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20211219.1)

When I added this code, the problem was solved.
```css
font-family: Arial, Helvetica, Liberation Sans,
```
[Font-family and compatibility between Linux, Windows, MacOS X](http://rigaux.org/font-family-compatibility-between-linux-.html)

The problem seems to be that Docker v1.12.3-focal  only have Liberation Font
```bash
/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Italic.ttf: Liberation Sans Narrow:style=Italic
/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf: Liberation Sans:style=Regular
/usr/share/fonts/truetype/liberation/LiberationMono-BoldItalic.ttf: Liberation Mono:style=Bold Italic
/usr/share/fonts/truetype/liberation/LiberationSerif-Italic.ttf: Liberation Serif:style=Italic
/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf: Liberation Mono:style=Bold
/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Regular.ttf: Liberation Sans Narrow:style=Regular
/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf: Liberation Serif:style=Bold
/usr/share/fonts/truetype/unifont/unifont.ttf: Unifont:style=Medium
/usr/share/fonts/truetype/unifont/unifont_upper.ttf: Unifont Upper:style=Medium
/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf: Liberation Mono:style=Regular
/usr/share/fonts/truetype/liberation/LiberationSans-Italic.ttf: Liberation Sans:style=Italic
/usr/share/fonts/truetype/liberation/LiberationSerif-BoldItalic.ttf: Liberation Serif:style=Bold Italic
/usr/share/fonts/truetype/liberation/LiberationSansNarrow-BoldItalic.ttf: Liberation Sans Narrow:style=Bold Italic
/usr/share/fonts/truetype/liberation/LiberationMono-Italic.ttf: Liberation Mono:style=Italic
/usr/share/fonts/truetype/liberation/LiberationSans-BoldItalic.ttf: Liberation Sans:style=Bold Italic
/usr/share/fonts/truetype/unifont/unifont_csur.ttf: Unifont CSUR:style=Medium
/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf: Liberation Serif:style=Regular
/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Bold.ttf: Liberation Sans Narrow:style=Bold
/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf: Liberation Sans:style=Bold
/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf: Noto Color Emoji:style=Regular
```

These are github ubuntu font lists:
```bash
/usr/share/fonts/truetype/lato/Lato-Medium.ttf: Lato,Lato Medium:style=Medium,Regular
/usr/share/fonts/truetype/lato/Lato-SemiboldItalic.ttf: Lato,Lato Semibold:style=Semibold Italic,Italic
/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf: DejaVu Serif:style=Bold
/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf: DejaVu Sans Mono:style=Book
/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-Oblique.ttf: DejaVu Sans,DejaVu Sans Condensed:style=Condensed Oblique,Oblique
/usr/share/fonts/truetype/lato/Lato-LightItalic.ttf: Lato,Lato Light:style=Light Italic,Italic
/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Italic.ttf: Liberation Sans Narrow:style=Italic
/usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed-BoldItalic.ttf: DejaVu Serif,DejaVu Serif Condensed:style=Condensed Bold Italic,Bold Italic
/usr/share/fonts/truetype/dejavu/DejaVuSans-ExtraLight.ttf: DejaVu Sans,DejaVu Sans Light:style=ExtraLight
/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf: DejaVu Sans:style=Book
/usr/share/fonts/truetype/lato/Lato-Italic.ttf: Lato:style=Italic
/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf: Liberation Sans:style=Regular
/usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed.ttf: DejaVu Serif,DejaVu Serif Condensed:style=Condensed,Book
/usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed-Italic.ttf: DejaVu Serif,DejaVu Serif Condensed:style=Condensed Italic,Italic
/usr/share/fonts/truetype/liberation/LiberationMono-BoldItalic.ttf: Liberation Mono:style=Bold Italic
/usr/share/fonts/truetype/liberation/LiberationSerif-Italic.ttf: Liberation Serif:style=Italic
/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf: Liberation Mono:style=Bold
/usr/share/fonts/truetype/lato/Lato-MediumItalic.ttf: Lato,Lato Medium:style=Medium Italic,Italic
/usr/share/fonts/truetype/lato/Lato-Black.ttf: Lato,Lato Black:style=Black,Regular
/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Regular.ttf: Liberation Sans Narrow:style=Regular
/usr/share/fonts/truetype/dejavu/DejaVuSerif-BoldItalic.ttf: DejaVu Serif:style=Bold Italic
/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Oblique.ttf: DejaVu Sans Mono:style=Oblique
/usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed-Bold.ttf: DejaVu Serif,DejaVu Serif Condensed:style=Condensed Bold,Bold
/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf: DejaVu Sans:style=Bold
/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf: Liberation Serif:style=Bold
/usr/share/fonts/truetype/dejavu/DejaVuSansMono-BoldOblique.ttf: DejaVu Sans Mono:style=Bold Oblique
/usr/share/fonts/truetype/lato/Lato-Light.ttf: Lato,Lato Light:style=Light,Regular
/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf: Liberation Mono:style=Regular
/usr/share/fonts/truetype/lato/Lato-Regular.ttf: Lato:style=Regular
/usr/share/fonts/truetype/dejavu/DejaVuMathTeXGyre.ttf: DejaVu Math TeX Gyre:style=Regular
/usr/share/fonts/truetype/liberation/LiberationSans-Italic.ttf: Liberation Sans:style=Italic
/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-BoldOblique.ttf: DejaVu Sans,DejaVu Sans Condensed:style=Condensed Bold Oblique,Bold Oblique
/usr/share/fonts/truetype/lato/Lato-ThinItalic.ttf: Lato,Lato Thin:style=Thin Italic,Italic
/usr/share/fonts/truetype/liberation/LiberationSerif-BoldItalic.ttf: Liberation Serif:style=Bold Italic
/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed.ttf: DejaVu Sans,DejaVu Sans Condensed:style=Condensed,Book
/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-Bold.ttf: DejaVu Sans,DejaVu Sans Condensed:style=Condensed Bold,Bold
/usr/share/fonts/truetype/liberation/LiberationSansNarrow-BoldItalic.ttf: Liberation Sans Narrow:style=Bold Italic
/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf: DejaVu Sans Mono:style=Bold
/usr/share/fonts/truetype/dejavu/DejaVuSans-Oblique.ttf: DejaVu Sans:style=Oblique
/usr/share/fonts/truetype/liberation/LiberationMono-Italic.ttf: Liberation Mono:style=Italic
/usr/share/fonts/truetype/liberation/LiberationSans-BoldItalic.ttf: Liberation Sans:style=Bold Italic
/usr/share/fonts/truetype/lato/Lato-HairlineItalic.ttf: Lato,Lato Hairline:style=Hairline Italic,Italic
/usr/share/fonts/truetype/lato/Lato-Thin.ttf: Lato,Lato Thin:style=Thin,Regular
/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf: Liberation Serif:style=Regular
/usr/share/fonts/truetype/lato/Lato-BoldItalic.ttf: Lato:style=Bold Italic
/usr/share/fonts/truetype/dejavu/DejaVuSerif-Italic.ttf: DejaVu Serif:style=Italic
/usr/share/fonts/truetype/lato/Lato-Bold.ttf: Lato:style=Bold
/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Bold.ttf: Liberation Sans Narrow:style=Bold
/usr/share/fonts/truetype/lato/Lato-Heavy.ttf: Lato,Lato Heavy:style=Heavy,Regular
/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf: Liberation Sans:style=Bold
/usr/share/fonts/truetype/lato/Lato-Semibold.ttf: Lato,Lato Semibold:style=Semibold,Regular
/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf: Noto Color Emoji:style=Regular
/usr/share/fonts/truetype/lato/Lato-HeavyItalic.ttf: Lato,Lato Heavy:style=Heavy Italic,Italic
/usr/share/fonts/truetype/lato/Lato-BlackItalic.ttf: Lato,Lato Black:style=Black Italic,Italic
/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf: DejaVu Serif:style=Book
/usr/share/fonts/truetype/lato/Lato-Hairline.ttf: Lato,Lato Hairline:style=Hairline,Regular
/usr/share/fonts/truetype/dejavu/DejaVuSans-BoldOblique.ttf: DejaVu Sans:style=Bold Oblique
```

**docker image screenshot**:
![image](https://user-images.githubusercontent.com/29626358/148757093-ab9a1437-dd8a-4c7e-8599-2023f90cb35b.png)

**github action screenshot**:
![image](https://user-images.githubusercontent.com/29626358/148757174-b01600ee-07fe-4cda-9d02-ef3dfdb2c4d3.png)

**diff**:
![image](https://user-images.githubusercontent.com/29626358/148757233-4942355c-d1cd-4eff-8b34-cb5f79386154.png)

**Comment by aslushnikov** [comment] 2022-03-28 23:37
For the record: docker integration depends on global fixtures, so moving them forward.

**Comment by pavelfeldman** [comment] 2022-10-20 06:27
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-10-20 06:27 UTC
Labels: feature-visual-regression-testing
