### ISSUE TITLE
[BUG] Cookies received from auth response in 'set-cookie' header not sent back on request

### ISSUE THREAD

**Issue by Mozenn** [microsoft/playwright#29212] opened 2024-01-28 06:20 UTC
### System info
- Playwright Version: v1.40.1
- Operating System: Ubuntu 22 with WSL2 on Windows 11
- Browser: All

### Source code

auth.spec.ts
```
import { test as setup, expect } from "@playwright/test";

const authFile = "tests/.auth/state.json";

setup("authenticate", async ({ page, browser }) => {
  await page.goto("/auth/login");
  await expect(page.getByText("Log In")).toBeVisible();
  await page.getByTestId("emailOrUsername").fill("user");
  await page.getByTestId("password").fill("password");
  await page.getByRole("button", { name: "Log In" }).click();

  await expect(page.getByTestId("logo")).toBeVisible();

  // End of authentication steps.

  // Here, context.cookies is empty even though response with 'set-cookie' has been received

  await page.context().storageState({ path: authFile });
});
```

e2e.spec.ts
```
import { test, expect } from "@playwright/test";

test.use({ storageState: "./tests/.auth/state.json" });

test("collect", async ({ page }) => {
  await page.goto("/collect");

  await expect(page.getByText("Collect")).toBeVisible();
});
```

Persisted stateStorage state.json
```
{
  "cookies": [], // no cookies persisted
  "origins": [
    {
      "origin": "http://127.0.0.1:3002",
      "localStorage": [ // local storage set on login response received
        {
          "name": "authId",
          "value": "1"
        }
      ]
    }
  ]
}
```

playwright.config.ts
```
import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: "./tests",
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: "html",
  use: {
    baseURL: "http://127.0.0.1:3002",
    trace: "on-first-retry",
  },

  projects: [
    { name: "setup", testMatch: /.*\.setup\.ts/ },
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
        storageState: "tests/.auth/state.json",
      },
      dependencies: ["setup"],
    },

    {
      name: "firefox",
      use: {
        ...devices["Desktop Firefox"],
        storageState: "tests/.auth/state.json",
      },
      dependencies: ["setup"],
    },

    {
      name: "webkit",
      use: {
        ...devices["Desktop Safari"],
        storageState: "tests/.auth/state.json",
      },
      dependencies: ["setup"],
    },

    {
      name: "Mobile Chrome",
      use: {
        ...devices["Pixel 5"],

        storageState: "tests/.auth/state.json",
      },
      dependencies: ["setup"],
    },
  ],
});
```

**Steps**
- Have a login form with user and password fields that send a login HTTP request to a backend for authentication. Response should contain a set-cookie header such as this one 
```
set-cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcwNjQyMDQxMSwiZXhwIjoxNzA2NDI0MDExfQ.p-t76JxQ_EaPeKKezVWv9jh9s1Y_J9ZqP6EYSi2B14o; HttpOnly; Path=/; Max-Age=3600
```
- Have a test suite that first runs the auth setup by using the login form, and once authenticated, sends another request that should contain the authentication token cookie
- Run the test with `npx playwright test e2e.spec.ts`

**Expected**

Outside of Playwright, the authentication token cookie from the set-cookie header from the login response is saved on the browser and sent back on following requests for authentication. It should be the same when running with playwright.

**Actual**

When running tests with Playwright, the cookie from the set-cookie header from the login response is not saved on the browser context, and the following request fails with a 401 error.

**Comment by Mozenn** [comment] 2024-01-30 06:01
Thank you for the tips about the path.

Here is the auth.spec.ts now

```
import { test as setup, expect } from "@playwright/test";
import path from "path";

const authFile = path.resolve(__dirname, "..", "tests/.auth/state.json");

setup("authenticate", async ({ page, browser }) => {
  await page.goto("/auth/login");
  await expect(page.getByText("Log In to One Day One Plant")).toBeVisible();
  await page.getByTestId("emailOrUsername").fill("user1");
  await page.getByTestId("password").fill("Password1*");
  await page.getByRole("button", { name: "Log In" }).click();

  await expect(page.getByTestId("logo")).toBeVisible();

  const cookies = await page.context().cookies();
  console.log("cookies", cookies);
  cookies.forEach((c) => console.log("cookie", c.name, c.value));

  // End of authentication steps.

  await page.context().storageState({ path: authFile });
});
```

I have also added a print of the response headers in client code.

This is the Playwright logs 

![logs1](https://github.com/microsoft/playwright/assets/41834659/4ac04d22-398e-4de8-a742-f9b61bc991af)

And the response headers in Playwright 

![response-headers](https://github.com/microsoft/playwright/assets/41834659/d5565ee1-a274-47e1-9d6b-a3acdfa351fe)

Here are the logs when doing the same flow outside Playwright 

![logs-browser](https://github.com/microsoft/playwright/assets/41834659/f77c48db-3ddf-49fa-a42e-033693fcb4bf)

And the response headers 

![response-headers-browser](https://github.com/microsoft/playwright/assets/41834659/268a9181-01f1-4fc8-b2c4-d52e6576ab82)

The set-cookie header is not logged, but I think this is expected because it's an http-only header.
But I don't see any differences between the two except the cookie not being sent after login with Playwright.

**Comment by pavelfeldman** [comment] 2024-01-30 17:00
Unfortunately, I can't reproduce this. This kind of auth is working for our users and this is the first time we are seeing the request like this. If you could provide a self-contained repro scenario, we would be able to act on it.

**Comment by pavelfeldman** [comment] 2024-02-02 20:17
Closing as non-actionable due to the lack of repro. Please open a new bug if you manage to create a repro we can use.

**Closed by pavelfeldman** 2024-02-02 20:17 UTC

**Comment by sriram-siv** [comment] 2024-03-08 14:45
I was experiencing the same issue. I found that if you create a new context then the cookies will be set correctly.

```
function login(browser: Browser) {
  const context = await browser.newContext();

  await context.request.post("login_url", {
    data: { ...credentials },
  });

  // context.cookies has been set
}
```

**Comment by rostislav-simonik-plc** [comment] 2024-09-19 05:55
I think it's race condition and we  are experiencing it as well, it happens to us spodarically. we try to create reproducible scenario within docker container and infinite loop of logins, to eventually reproduce the failute.
