### ISSUE TITLE
[BUG] Google Cloud Function error (deploy)

### ISSUE THREAD

**Issue by MaiaVinicius** [microsoft/playwright#2321] opened 2020-05-21 03:12 UTC
**Context:**
- Operating System: Linux
- Node version: Node.js 10
- Browser: Webkit
- Extra: [any specific details about your environment]

**Code Snippet**

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
      const browser = await webkit.launch({ headless: true });
      const context = await browser.newContext();
      const page = await context.newPage();
})();
```

**Describe the bug**

I'm trying to deploy my playwright application in Google Cloud Functions. It seems like there is a problem to spawn the browser.

```
Error: function terminated. Recommended action: inspect logs for termination reason. Details:
Failed to launch browser: Error: spawn /root/.cache/ms-playwright/chromium-764964/chrome-linux/chrome ENOENT
```

**Comment by aslushnikov** [comment] 2020-05-21 07:25
@MaiaVinicius Google Cloud Functions environment is missing the needed libraries for webkit. And IIRC there's no way to add missing dependencies to Google Cloud from the user land :( The only hope is to submit a feature request to google cloud and hope they'll fix them. 

If you end up filing this to Google, please post a link to the filed bug here for the future reference.

**Comment by aslushnikov** [comment] 2020-05-21 07:27
Oh, wait!

> Browser: Webkit

@MaiaVinicius I see you try launching webkit, but your error log is mentioning `chrome`:

> Failed to launch browser: Error: spawn /root/.cache/ms-playwright/chromium-764964/chrome-linux/chrome ENOENT

Is this log correct?

**Comment by MaiaVinicius** [comment] 2020-05-21 12:49
Actually, I have tried all 3 drivers (chrome, firefox and webkit). All returned the same error.

Thank you for the feedback.

**Comment by gluck** [comment] 2020-07-17 10:53
Got this issue as well, I'm assuming that either firebase doesn't run install scripts, or doesn't wait for it to finish (install script is async, but nothing's waiting for it AFAICT).
Got it working by either:
- executing `installBrowsersWithProgressBar` within the function (and waiting for it), but it'll consume function bandwidth $$$
- using [chrome-aws-lambda](https://github.com/alixaxel/chrome-aws-lambda) package, which bundles chrome linux binary in the npm package itself, and tricking playwright into using it

Although both of these are far from ideal :crying_cat_face:

**Comment by aslushnikov** [comment] 2020-08-21 07:40
> Got this issue as well, I'm assuming that either firebase doesn't run install scripts, or doesn't wait for it to finish (install script is async, but nothing's waiting for it AFAICT).

@gluck 🤷‍♂️ we're not very familiar with firebase, unfortunately...

I'll close this since it's unclear how we can help here.

**Closed by aslushnikov** 2020-08-21 07:40 UTC

**Comment by billfeng** [comment] 2021-03-28 18:49
I'm getting this issue as well. Is it possible to add an option to bundle the browser being used as a part of the NPM package, instead of using the browser on-device?

**Comment by gluck** [comment] 2021-03-29 09:38
Hi @billfeng, since my comment the situation has improved (a bit) and you can use the package 'playwright-core' to avoid downloading the browsers and `chrome-aws-lambda` package can be used to get a npm-packaged-chromium.
Two drawbacks with that approach:
- you need to match playwright version with chrome-aws-lambda so that chromium version is the expected one
- chrome-aws-lambda only works on cloud, and running locally won't work

Now that playwright has already tons of packaged ways (`playwright-core`, `playwright-chromium` ...), having another one like `playwright-chromium-cloud` would be ideal indeed.

**Comment by billfeng** [comment] 2021-03-29 21:00
Hi @gluck, thanks for the info, this is very helpful! I will try the method you described. Quick questions -
- Do the chromium versions have to match exactly? The latest from `chrome-aws-lambda` is `856583`, but the one that playwright installs is a close but different number, and there isn't a `chrome-aws-lambda` release with the exact match.
- How did you get playwright-core to use the chromium binary from `chrome-aws-lambda`?

Also, I made some interesting hacky progress with a different method. By forcing Firebase cloud functions to install the browser binaries locally through running `PLAYWRIGHT_BROWSERS_PATH=0 npm i playwright` as a postinstall script, and then setting `executablePath` to the browser binaries in `node_modules`, it seems to almost work, except then I get this different error:
```
error while loading shared libraries: libharfbuzz-icu.so.0: cannot open shared object file: No such file or directory
```
I'm guessing playwright or the browser binary it installed needs this `libharfbuzz-icu.so.0` thing? Is this a Linux package that the Ubuntu container of Firebase functions is missing? If this looks familiar to you at all or if you have any suggestions on how to get around this, that would be much appreciated too. I feel like I'm so close to getting it to work!

**Comment by gluck** [comment] 2021-03-30 08:28
I'm currently using:
- playwright 1.6.2 (chromium 88.0.4324.0)
- chrome-aws-lambda 5.5.0 (chromium 88.0.4298.0)

Without issues (I had issues when the major version was different).

Pseudo code:
```
import { chromium } from 'playwright-core';
import * as bundledChromium from 'chrome-aws-lambda';

....
  const browser = await Promise.resolve(bundledChromium.executablePath).then(
      (executablePath) => {
        if (!executablePath) {
          // local execution
          return chromium.launch({});
        }
        return chromium.launch({ executablePath });
      }
    );
```

Your approach seems promising as well, not sure why the shared library is missing.

**Comment by tverilytt** [comment] 2021-06-18 12:45
This seems to work well now (I have only tested with playwright-chromium).

Only initial issue was that the launch method did not find the executable:

browserType.launch: Failed to launch chromium because executable doesn't exist at /root/.cache/ms-playwright/chromium-888113/chrome-linux/chrome

Setting the environment variable PLAYWRIGHT_BROWSERS_PATH=0 resolved this, and I can now use playwright-chromium in Google Cloud Function to e.g. generate pdf  😃

Cheers
-jo

BTW - had to raise memory limit to 1 GB to avoid running out of memory...

**Comment by pawelmhm** [comment] 2021-09-24 12:08
For some reasons just using PLAYWRIGHT_BROWSERS_PATH=0 didn't work for me here. 

What worked for me when deploying Playwright to Google Cloud Function.

1. Passing executablePath option to browser.launch, example

```javascript
 // tmp is folder where browser binary should be found, 1295 is browser version and it can change
  const context = await browser.newContext({"executablePath":  "tmp/firefox-1295/firefox/firefox"})
```

2. Passing environment variable to GCF PLAYWRIGHT_BROWSERS_PATH=<some_folder>, in my case this was tmp, passed from gcloud: --set-build-env-vars=PLAYWRIGHT_BROWSERS_PATH=tmp but it can also bet set via Web interface.

**Comment by tverilytt** [comment] 2021-09-24 12:20
HI! Hm, ok. I set PLAYWRIGHT_BROWSERS_PATH for both build and runtime environment, e.g. for gcloud CLI:

--set-build-env-vars="PLAYWRIGHT_BROWSERS_PATH=0"  --set-env-vars="PLAYWRIGHT_BROWSERS_PATH=0"

**Comment by pawelmhm** [comment] 2021-09-24 12:26
thanks for info, I'll double check it again and verify

**Comment by jeremypatrickdahan** [comment] 2021-11-11 17:14
> I'm currently using:
> 
>     * playwright 1.6.2 (chromium 88.0.4324.0)
> 
>     * chrome-aws-lambda 5.5.0 (chromium 88.0.4298.0)
> 
> 
> Without issues (I had issues when the major version was different).
> 
> Pseudo code:
> 
> ```
> import { chromium } from 'playwright-core';
> import * as bundledChromium from 'chrome-aws-lambda';
> 
> ....
>   const browser = await Promise.resolve(bundledChromium.executablePath).then(
>       (executablePath) => {
>         if (!executablePath) {
>           // local execution
>           return chromium.launch({});
>         }
>         return chromium.launch({ executablePath });
>       }
>     );
> ```
> 
> Your approach seems promising as well, not sure why the shared library is missing.

I can confirm that the above solution works well. Thank you for sharing this !

Here is a complete example that returns a screenshot of google when queried.
(Using NodeJS 14, 2GB RAM)

`package.json`
```json
{
  "dependencies": {
    "playwright-core" : "1.6.2",
    "chrome-aws-lambda" : "5.5.0"
  }
}
```


`index.js`
```js
const { chromium } = require('playwright-core');
const bundledChromium = require('chrome-aws-lambda');

module.exports.screenshot = async function (req, res) {
    const url = "https://google.com/";
    
  const browser = await Promise.resolve(bundledChromium.executablePath).then(
      (executablePath) => {
        if (!executablePath) {
          // local execution
          return chromium.launch({});
        }
        return chromium.launch({ executablePath });
      }
    );
    const page = await browser.newPage();
    await page.goto(url);
    const screenshotBuffer = await page.screenshot({ fullPage: true });
    await browser.close();
    res.set("Content-Type", "image/png");
    res.status(500).send(screenshotBuffer)        
};

```

**Comment by akshaymattoo** [comment] 2022-05-25 20:02
I get this error when the above code
```⚠  functions: browserType.launch: Protocol error (Browser.getVersion): Target closed.
=========================== logs ===========================
<launching> /var/folders/g0/00c8fy2x6fl0r7s6xmxdk3ww0000gn/T/chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=/var/folders/g0/00c8fy2x6fl0r7s6xmxdk3ww0000gn/T/playwright_chromiumdev_profile-N0KLTG --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-startup-window
<launched> pid=58487
[err] /var/folders/g0/00c8fy2x6fl0r7s6xmxdk3ww0000gn/T/chromium: /var/folders/g0/00c8fy2x6fl0r7s6xmxdk3ww0000gn/T/chromium: cannot execute binary file
<process did exit: exitCode=126, signal=null>
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Connection.sendMessageToServer (/Users/amattoo@us.ibm.com/akshay/scraping/cinco-functions/functions/node_modules/playwright-core/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/Users/amattoo@us.ibm.com/akshay/scraping/cinco-functions/functions/node_modules/playwright-core/lib/client/channelOwner.js:54:53)
    at /Users/amattoo@us.ibm.com/akshay/scraping/cinco-functions/functions/node_modules/playwright-core/lib/client/browserType.js:61:73
    at BrowserType._wrapApiCall (/Users/amattoo@us.ibm.com/akshay/scraping/cinco-functions/functions/node_modules/playwright-core/lib/client/channelOwner.js:80:34)
    at BrowserType.launch (/Users/amattoo@us.ibm.com/akshay/scraping/cinco-functions/functions/node_modules/playwright-core/lib/client/browserType.js:52:21)
    at /Users/amattoo@us.ibm.com/akshay/scraping/cinco-functions/functions/index.js:28:25
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /Users/amattoo@us.ibm.com/akshay/scraping/cinco-functions/functions/index.js:22:21
    at async runFunction (/Users/amattoo@us.ibm.com/.nvm/versions/node/v16.3.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:564:9)
    at async runHTTPS (/Users/amattoo@us.ibm.com/.nvm/versions/node/v16.3.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:590:5)
⚠  Your function was killed because it raised an unhandled error.
```

**Comment by mcm-gr** [comment] 2022-10-28 13:45
Could you also run this setup in the local firebase function emulator? Best, MM

**Comment by MuhammadM1998** [comment] 2022-11-23 21:12
I've tried to do what @jdexyz suggested and got the following error when deploying to vercel

```
Function Status:None
Edge Status:500
Duration:4192.94 ms
Init Duration: 203.07 ms
Memory Used:395 MB
ID:fra1::492zm-1669237027500-ae64064b9704
User Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0

2022-11-23T20:57:07.432Z 92669855-d7cc-4fc3-942d-5d1f2ba718d5	ERROR Unhandled Promise Rejection
{ 
  "errorType":"Runtime.UnhandledPromiseRejection",
  "errorMessage":"Error: Page closed",
  "reason": {
  "errorType":"Error",
  "errorMessage":"Page closed",
  "stack":["Error: Page closed",
  "at CRSession.<anonymous> (/var/task/node_modules/playwright-core/lib/server/chromium/crPage.js:445:54)",
  "at Object.onceWrapper (events.js:519:28)",
  "at CRSession.emit (events.js:412:35)",
  "at /var/task/node_modules/playwright-core/lib/server/chromium/crConnection.js:248:39"]},
  "promise":{},
  "stack":[
  "Runtime.UnhandledPromiseRejection: Error: Page closed",
  "at process.<anonymous> (/var/runtime/index.js:35:15)",
  "at process.emit (events.js:412:35)",
  "at processEmit [as emit] (/var/task/node_modules/signal-exit/index.js:199:34)",
  "at processPromiseRejections (internal/process/promises.js:245:33)",
  at processTicksAndRejections (internal/process/task_queues.js:96:32)"
]}

Unknown application error occurred
Runtime.Unknown
```

**Comment by 2dareis2do** [comment] 2024-06-15 17:05
I had a similar issue with running playwright python. I was wondering why I could run from the command line but it was failing when running as a web user process. 

Turns out the path for browsers are stored in ~/.cache folder when running playwright install command

For me the solution was to make sure that I ran playwright install command as the web user.
