### ISSUE TITLE
[BUG] Starting with Playwright 1.25.0 my application keeps flickering in Webkit

### ISSUE THREAD

**Issue by testgitdl** [microsoft/playwright#17614] opened 2022-09-27 07:20 UTC
**Context:**
- Playwright Version: 1.25.0
- Operating System: Windows 10
- Node.js version: 16.15.0
- Browser: Webkit 1699 (also reproduces on Webkit 1715 delivered with Playwright 1.26.0
- Extra: Works on Webkit 1641

**Describe the bug**

I am unable to run my playwright tests on Webkit. Everything works on Playwright 1.22.0 (webkit 1641) but it fails on later versions.
The web elements in my app keep flickering as in the recording - when I run and also if I try to record by opening npx playwright wk http://localhost:4200
![2022-09-27 10-09-10](https://user-images.githubusercontent.com/33279646/192459926-a51e9339-bfb1-488e-a8bb-751164b2e23a.gif)

**Comment by mxschmitt** [comment] 2022-09-28 08:45
I tried to repro by navigating to youtube.com and webkit.org but for me it was working as expected. Does it happen on every website you visit? If not, would it be possible to share which website you were navigating to?

Does it only happen if you enable Playwright recording?

**Comment by testgitdl** [comment] 2022-09-30 05:45
Hello! I cannot share the application but it does work on Webkit 1641. I tried another Angular 14 app but did not reproduce. Any idea how to approach this? Why it is happening? It reproduces with and without recording. Thank you!

**Comment by aslushnikov** [comment] 2022-09-30 15:58
> Any idea how to approach this? Why it is happening?

Unfortunately we cannot debug & fix this unless we can reproduce this locally. If you have time to build a repo that illustrates the issue, we'll be happy to dive into it!

I'll close this for now since its not actionable, but please do not hesitate to file a new issue once you have a repro for us to debug!

**Closed by aslushnikov** 2022-09-30 15:58 UTC
Labels: triaging

**Comment by theDavidBarton** [comment] 2022-10-03 08:35
most probably related to: https://github.com/microsoft/playwright/issues/17766

can be reproduced on Delta Air Lines website: https://www.delta.com/eu/en (built with Angular also)
