### ISSUE TITLE
[BUG] preserveOutput 'always' seems to be no longer working

### ISSUE THREAD

**Issue by Seyrior** [microsoft/playwright#23879] opened 2023-06-23 15:15 UTC
I run tests on read only file system, and after update from v1.30 to v1.35 I faced with some issue when playwright creates some empty folders during execution, like `/test-results/.playwright-artifacts-0` resulting in: 

```
      ENOENT: no such file or directory, mkdir '/app/test-results/.playwright-artifacts-3'
      Error: ENOENT: no such file or directory, mkdir '/app/test-results/.playwright-artifacts-3'
```

I don't have anything in the config that requires creation any test outputs:

```
module.exports = {
  workers: 5,
  retries: 3,
  timeout: 90000
};
```

I did try explicitly set `preserveOutput: 'always'` and it did not help
 

### System info
- Playwright Version: [v1.35]
- Operating System: [All]
- Browser: [All?]

**Comment by dgozman** [comment] 2023-06-24 21:35
@Seyrior Playwright creates temporary artifact directories in the output folder. I guess you have your playwright config in the `/app/playwright.config.ts` and since it does not set `outputDir`, it defaults to `/app/test-results`. For some reason there is an error creating `/app/test-results/.playwright-artifacts-3`, perhaps it's related to file system permissions?

Not sure how else to help you. This seems specific to your setup, so I doubt we will be able to reproduce it locally. Perhaps paste as much information including error messages that you could? Also, try running with `PWDEBUGIMPL=1 npx playwright test` so that we can see full stack traces.

**Comment by Seyrior** [comment] 2023-06-25 10:43
@dgozman it is related to file system permissions, I use read-only file system, and it works fine with v1.30 but on v1.35 it attempts to create temp folders (empty folders), in my understanding `preserveOutput: 'always'` is designed to prevent any file/folders creation during test execution. If you changed something between v1.30 and v1.35 and now it is not possible to prevent making temp folders, I'll probably just use v1.30 for as long as it runs without issues

**Comment by dgozman** [comment] 2023-06-30 23:08
@Seyrior There was indeed a change in v1.34 that started to create different temporary folders. We'll see whether we can undo that. That said, we do not expect Playwright to be run on the read-only file system, that's not really common.

> in my understanding `preserveOutput: 'always'` is designed to prevent any file/folders creation during test execution.

`preserveOutput` has a different purpose - it controls whether any test output created in the `test-results` directory should be preserved or removed at the end. It does not prevent any output from being written in the first place.

Since we do not plan any changes, I'll close the issue. Thank you for filing!

**Closed by dgozman** 2023-06-30 23:08 UTC
Labels: triaging
