### ISSUE TITLE
[BUG] Phone Call automation in playwright, Calls are getting disconnected immediately 

### ISSUE THREAD

**Issue by Echo-bot80** [microsoft/playwright#22652] opened 2023-04-26 13:52 UTC
### System info
- Playwright Version: [v1.8.1]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:
When we initiate Phone call using skype, those are getting disconnected immediately after accepting the call. 
 
### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by mxschmitt** [comment] 2023-04-26 17:57
We need a clear reproduction to be able to act on. A small script which we can execute, preferable without any external websites involved.

Closing for now, since none is provided. Feel free to re-file with more information and follow our bug template.

**Closed by mxschmitt** 2023-04-26 17:57 UTC
