### ISSUE TITLE
[BUG] The "file" argument must be of type string. Received an instance of Object

### ISSUE THREAD

**Issue by myhrmans** [microsoft/playwright#10128] opened 2021-11-08 12:33 UTC
**Context:**
## System:
 - OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
 - Memory: 1.16 GB / 31.28 GB
 - Container: Yes
## Binaries:
 - Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
 - Yarn: 1.22.10 - /usr/bin/yarn
 - npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash
## npmPackages:
 - playwright: ^1.16.3 => 1.16.3 

```javascript
const { _electron } = require('playwright');
const path = require('path');

(async () => {
  // Launch Electron app.
  const electronApp = await _electron.launch({ args: ['main.js'] });

  // Evaluation expression in the Electron context.
  const appPath = await electronApp.evaluate(async ({ app }) => {
    // This runs in the main Electron process, parameter here is always
    // the result of the require('electron') in the main app script.
    return app.getAppPath();
  });
  console.log(appPath);

  // Get the first window that the app opens, wait if necessary.
  const window = await electronApp.firstWindow();
  // Print the title.
  console.log(await window.title());
  // Capture a screenshot.
  await window.screenshot({ path: 'intro.png' });
  // Direct Electron console to Node terminal.
  window.on('console', console.log);
  // Click button.
  await window.click('text=Click me');
  // Exit app.
  await electronApp.close();
})();
```

Follow the example in https://playwright.dev/docs/api/class-electronapplication/ will result in the following error:

`(node:501983) UnhandledPromiseRejectionWarning: electron.launch: The "file" argument must be of type string. Received an instance of Object`

**Comment by mxschmitt** [comment] 2021-11-16 11:45
I was not able to reproduce this. Could you create a small Git repository for us with a full minimal setup?

**Comment by aslushnikov** [comment] 2021-11-18 17:56
Let me speculatively close this; @myhrmans please feel free to re-file with a repro with a minimal github repository!

**Closed by aslushnikov** 2021-11-18 17:56 UTC
Labels: triaging
