### ISSUE TITLE
[BUG] Inconsistent behaviour in Chromium relating to window.matchMedia() use

### ISSUE THREAD

**Issue by jpveooys** [microsoft/playwright#18919] opened 2022-11-18 18:10 UTC
**Context:**
- Playwright Version: 1.28.0
- Operating System: Ubuntu 22.04
- Node.js version: 18.12.1
- Browser: Chromium using Pixel 5 device configuration
- Extra: n/a

**Code Snippet**

I have created a simplified reproduction at https://github.com/jpveooys/playwright-repro

(Also includes a GitHub Actions workflow demonstrating the problem.)

**Describe the bug**

To reproduce:

1. Clone the repo
2. Run `npm install`
3. Run `npm test`

You should see that the test fails about half of the time when running as configured (using the Pixel 5 device preset).

The screenshots always show the correct state (red square). The incorrect state (blue square) can be seen in the traces.

The inconsistent behaviour is stemming from a use of `window.matchMedia()` browser-side. I'm unclear if it's an upstream problem in Chromium. Uncommenting [this line](https://github.com/jpveooys/playwright-repro/blob/2486f8a4ef5bd8048a6ed84df93df0eed8a5b2be/site/lib.js#L7) makes the problem go away.

**Comment by jpveooys** [comment] 2022-11-21 09:28
Running it headed or with `--debug`, everything is smaller initially and in the cases where it fails. My best guess therefore is there is a delay in deviceScaleFactor being applied.

**Comment by jpveooys** [comment] 2022-11-21 12:08
Adding `<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">` (which was missing) to `<head>` tag in `site/index.html` seems to fix this and restore consistent behaviour (blue square, rather than red). So this is probably a non-issue in the real world (as a similar viewport meta tag would normally be in use). Will test further and reply if I have any other findings.

**Comment by dgozman** [comment] 2022-11-21 19:24
I can repro this on Chromium, but not on WebKit. Most likely, the issue is related to this Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1285532.

> Running it headed or with --debug, everything is smaller initially and in the cases where it fails. It looks like is there is a delay in deviceScaleFactor being applied.

Could you please elaborate on this issue? I was running your repro in headed mode, and haven't noticed anything being smaller initially. Perhaps, there is a second bug here?

**Comment by jpveooys** [comment] 2022-11-21 20:25
> Most likely, the issue is related to this Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1285532.

The odd thing is, I'm not sure that the change event is being triggered in either case.

> Could you please elaborate on this issue? I was running your repro in headed mode, and haven't noticed anything being smaller initially. Perhaps, there is a second bug here?

It's not the easiest thing to record, but you can just about see it here (VP8-encoded, from 7 seconds in particular):

[playwright.webm](https://user-images.githubusercontent.com/66470099/203148684-fbbab84c-34a0-4c50-a91a-4b92b053c27e.webm)

You can see the two differently sized squares.

That goes away if screenshots are turned off. It is also still visible if `<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">` is added in and the tests are deliberately left with the wrong (failing) expectation.

Perhaps it's an artefact of how screenshots are taken?

**Comment by dgozman** [comment] 2022-11-21 21:34
@jpveooys Interesting... I see the big red and small blue, and think that perhaps [default 980px viewport](https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag#background) was not applied by Chromium. But that should be totally fixed by adding a `<meta name=viewport>` tag. Could you please double-check?

I also see the blue square blinking with a different size during the screenshot. This is related to `devicePixelRatio` of your host system not being equal to `devicePixelRatio` of the emulated mobile device. That's how Chromium takes such screenshots, and I don't think we'll fix anything here.

**Comment by jpveooys** [comment] 2022-11-21 22:07
@dgozman Yes, I can confirm the meta tag fixes the original problem. So it's a non-issue for me now – up to you how important the case without a similar viewport meta tag is.

**Comment by dgozman** [comment] 2022-11-21 22:23
@jpveooys Thanks for confirming! I'll leave this open for prioritization now.

**Comment by pavelfeldman** [comment] 2023-06-30 20:10
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Closed by pavelfeldman** 2023-06-30 20:10 UTC
Labels: P3-collecting-feedback
