### ISSUE TITLE
[BUG] : InnerText/innerHTML are not returning in locale when running in headless mode

### ISSUE THREAD

**Issue by nitin-nazare-incontact** [microsoft/playwright#12410] opened 2022-02-28 17:32 UTC
**Context:**
- Playwright Version: 1.15.2
- Operating System: Windows
- Node.js version: 14.17.6
- Browser: Chromium

**Code Snippet**

```typescript
import { Browser, chromium, Page } from "playwright";

(async () => {
 browser = await chromium.launch({
            channel: 'chrome',
            slowMo:500,
           headless: true
        });
        const context = await browser.newContext({
           locale: 'fr-FR' 
        });        
        context.clearCookies();        
        page = await context.newPage();
})();
```

**Describe the bug**
Running Test for Locale validation, but observed that when running in headless mode FALSE, Can see innerText/innerHTML property value returned correctly in locale. However, when running in headless mode as TRUE, property value returned in english instead of locale provided.

**Comment by aslushnikov** [comment] 2022-03-01 00:05
> Running Test for Locale validation, but observed that when running in headless mode FALSE, Can see innerText/innerHTML property value returned correctly in locale. However, when running in headless mode as TRUE, property value returned in english instead of locale provided.

@nitin-nazare-incontact can you please share a script that I can run locally to reproduce this?

**Comment by nitin-nazare-incontact** [comment] 2022-03-01 07:32
@aslushnikov I am not able to share internal code where I am facing issue. It's basically inside Frame where texts are in locale.
I tired check with simple code, but facing different timeout isue with below code.

`import test, { expect } from "@playwright/test";
import config from './../playwright.config';

test.describe('Locale Test', () => {

test.use(config);

test("Home page should be in German Locale", async ({page}) => {
    await page.goto("https://www.google.com",{ waitUntil: "load"});
    var ele = 'a.gb_1.gb_2.gb_6d.gb_6c';  
    await page.waitForSelector(ele);
    await page.click(ele);
    await page.waitForNavigation();
    await page.waitForSelector('h1.ahT6S')
    var actualText = await page.innerText('h1.ahT6S');
    expect(actualText).toBe("Anmelden");
  })
});`

playwright.config.ts ->
`import { PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
  use: {
    headless: true,
    viewport: { width: 1280, height: 720 },
    ignoreHTTPSErrors: true,
    locale: 'de-DE',
    navigationTimeout : 180000
  },
};
export default config;`

Getting below error -

x  src\locale.test.ts:9:1 › Locale Test › Home page should be in German Locale (30s)


  1) src\locale.test.ts:9:1 › Locale Test › Home page should be in German Locale ===================

    Timeout of 30000ms exceeded.

    page.waitForNavigation: Navigation failed because page was closed!
    =========================== logs ===========================
    waiting for navigation until "load"
    ============================================================

      13 |     await page.click(ele);
      14 |     await page.waitForNavigation();
    > 15 |     await page.waitForSelector('h1.ahT6S')
         |                ^
      16 |     var actualText = await page.innerText('h1.ahT6S');
      17 |     expect(actualText).toBe("Anmelden");
      18 |   })

**Comment by pavelfeldman** [comment] 2022-10-20 06:12
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-10-20 06:12 UTC
Labels: P3-collecting-feedback
