### ISSUE TITLE
[BUG] PW says radio button hasn't changed its state but it has

### ISSUE THREAD

**Issue by azad-derakhshani-GS** [microsoft/playwright#17559] opened 2022-09-23 20:26 UTC
**Context:**
- Playwright Version: 1.25.2
- Operating System: Manjaro Linux
- Node.js version: 16.16.0
- Browser: Chromium

**Code Snippet**
```
await this.radioButtons.nth(1).check();
```

**Describe the bug**

Playwright successfully checks the radio button, but wrongfully claims that it hasn't changed its state and therefore fails the test:

```
locator.check: Clicking the checkbox did not change its state
    =========================== logs ===========================
    waiting for selector "data-testid=Label-label >> nth=1"
      selector resolved to visible <label for="noShow" class="item" data-testid="Label-lab…>…</label>
    attempting click action
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      performing click action
      click action done
      waiting for scheduled navigations to finish
      navigations have finished
    ============================================================
```

See the screenshots from the traces, the second radio button is the one it is supposed to click and it does:

Before
![image](https://user-images.githubusercontent.com/98180468/192051568-bcbfa22c-4b02-4f29-8a69-dcc6dd742148.png)

After
![image](https://user-images.githubusercontent.com/98180468/192051680-f1b49189-eb28-43c8-af34-51872dc236b1.png)

**Workaround**
It works fine with a simple `click()` action, but this seems like a Playwright bug to me and it would be preferable to use the dedicated `check()` functionality instead of the click.

The element is an actual radio button, so the `check()` action should work on it:
```
<label for="noShow" class="item" data-testid="Label-label"> 
<input type="radio" id="noShow" class="" value="noShow">
```

**Comment by aslushnikov** [comment] 2022-09-27 06:41
@azad-derakhshani-GS does look like a bug to me as well. Could you please build a simple website that would reproduce this issue? This way we'd be able to debug it & fix it!

**Comment by aslushnikov** [comment] 2022-09-30 15:54
I'll close this since there's no repro and we can't do much without it. Please re-file with a repro!

**Closed by aslushnikov** 2022-09-30 15:54 UTC
Labels: triaging

**Comment by karanbhatia507** [comment] 2022-10-13 15:16
I am facing same issue. I can see on on chromium that it changes the state(radio button works fine) but it still throws this error. Any solution to that?

**Comment by azad-derakhshani-GS** [comment] 2022-10-13 16:38
> I am facing same issue. I can see on on chromium that it changes the state(radio button works fine) but it still throws this error. Any solution to that?

The only existing solution is to use `click()` instead of `check()` since this bug won't be fixed.
At this point I think it's generally advisable to only use `click()` for everything, since `check()` has other limitations as well.
