### ISSUE TITLE
[Question] Communication between the Playwright team and the community

### ISSUE THREAD

**Issue by brunojbarros** [microsoft/playwright#27501] opened 2023-10-08 13:25 UTC
Hi everyone!

First of all, thank you for the effort you dedicate to the project and for always being open to suggestions from the community.

I was reviewing the issues that were open under the P3-collecting-feedback tag, I noticed that there are issues that have been open for a long time despite being the most voted, some of them are being worked on (they even have an experimental mode) and others are not .

This leads me to question the following:

1. How does the Playwright team prioritize issues?
2. Is there a public roadmap that can be consulted? Currently, it is only possible to see through the tags which issues will be involved in the next two releases (1.39 and 1.40).
3. I wrote these questions previously in [Discussions](https://github.com/microsoft/playwright/discussions/27378), but it went unnoticed. Perhaps it is better to completely deprecate the "Discussions" section considering that it is little used and only use "Issues" and the discord channel. Reducing communication channels will make communication more effective, what do you think?

**Comment by dgozman** [comment] 2023-10-09 19:26
@brunojbarros Thank you for the question!

> How does the Playwright team prioritize issues?

We prioritize based on the popularity of the issue, the amount of work required, the amount of complexity introduced, whether it fits nicely into Playwright's scope and other similar factors. We also try to adhere to zero regressions policy, so regressions are usually fixed right away.

> Is there a public roadmap that can be consulted? Currently, it is only possible to see through the tags which issues will be involved in the next two releases (1.39 and 1.40).

There is no roadmap. We label issues that are targeted for the next two releases, as you have noted. That does not always mean these will be resolved in the targeted release, but rather that we'll go over them and usually make some progress. Most of the time though, simpler issues are fixed in the target release.

I'd recommend to engage in issues you are actually interested in - this also helps us prioritize the issues that are actively requested.

> Perhaps it is better to completely deprecate the "Discussions" section

Indeed, let us close the "Discussions". [This page](https://playwright.dev/community/welcome) explains our preferred communication channels. The team actively monitors issues, while other channels are more community-oriented.

**Comment by deviantintegral** [comment] 2023-10-11 16:34
@dgozman did you or someone else close discussions? Unfortunately this breaks references to all sorts of user support threads from external search engines or added as notes in source code comments. For example, I went to reference https://github.com/microsoft/playwright/discussions/20986 and it now 404s.

I think it's totally fine if the team wants to push this type of communication elsewhere, but it would be better to lock all open discussions with a comment pointing users to the new home and prevent creation of new discussions.

**Comment by dgozman** [comment] 2023-10-11 18:22
@deviantintegral Thank you for bringing this to our attention. Let us see whether more people run into this issue. If this turns out to be a common problem, we will try to follow your suggestion and make a read-only discussion archive.

**Comment by StasGrishaevTutu** [comment] 2023-10-13 14:43
@dgozman hi there, I’m also another person who, while looking for data on the issue of monitoring console errors in PW, came across a link in Google to a discussion, but I don’t have the opportunity to read it (404), I suspect that perhaps there was quite valuable information there.
Perhaps we should open the discussions back to read-only mode?

**Comment by alinabronevich** [comment] 2023-10-20 19:10
Same here. I have saved a link to discussions with potential solution to my issue 3 weeks ago and cant open it now - https://github.com/microsoft/playwright/discussions/10830

**Comment by jaktestowac** [comment] 2023-10-27 05:00
Here the same - saved some discussion for code examples
https://github.com/microsoft/playwright/discussions/14688

**Comment by Nav-2d** [comment] 2023-11-01 23:36
Facing the same issue. I had some discussions bookmarked for code examples. Please consider read-only discussions. Thanks!

**Comment by kevinboosten** [comment] 2023-11-03 14:15
Here as well

https://github.com/microsoft/playwright/discussions/10715#discussioncomment-1904812

Referenced from: https://github.com/microsoft/playwright/issues/11164

**Closed** 2023-11-03 21:18 UTC
Labels: triaging

**Comment by alexkuc** [comment] 2023-11-14 16:08
Would it be possible to make discussions read-only? All existing links including those from search engines like Google return now 404 but those discussions contain valuable "how-to" information, ideas, suggested patterns, etc.
