### ISSUE TITLE
[BUG] Browsers stopped opening on test and codegen start

### ISSUE THREAD

**Issue by KrFreeFly** [microsoft/playwright#24075] opened 2023-07-06 16:52 UTC
### System info
- Playwright Version: [v1.32.0]
- Operating System: [Windows 10]
- Browser: [Al]
- Other info:

Playwright installed both globally and in the project via npm

**Steps**
- playwright test
or
- playwright codegen

**Expected**

Browser opens, test or codegen starts

**Actual**

See screenshot
![Playwright](https://github.com/microsoft/playwright/assets/91471297/df4ece35-b64f-465f-996a-c9d8a906499b)

**Comment by pavelfeldman** [comment] 2023-07-06 19:24
I can't reproduce this, but you should not install playwright globally and should use the latest version (1.35!)

**Comment by KrFreeFly** [comment] 2023-07-07 06:08
> I can't reproduce this, but you should not install playwright globally and should use the latest version (1.35!)

Thanks for suggestion. I've uninstalled global and updated projest playwright to 1.35.1, but the problem persists. Nothing chsnged. Is there a way to debug it?

**Comment by KrFreeFly** [comment] 2023-07-07 06:34
I've tried to launch chrome.exe from cmd with the same options that playwright uses. If i exclude --no-startup-window it launches normally. How do i remove it from codegen?

**Comment by KrFreeFly** [comment] 2023-07-07 06:42
I've tried to launch chrome.exe manually the same way as playwright does.

This works:
chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=C:\Users\MAGORB~1\AppData\Local\Temp\playwright_chromiumdev_profile-3BC2XO --remote-debugging-pipe

If i add --no-startup-window it doesn't

**Comment by pavelfeldman** [comment] 2023-07-08 17:13
It does not help much unfortunately, we need to be able to repro.

**Comment by mxschmitt** [comment] 2023-07-13 17:38
Closing as per above. Please re-file with more details so we can repro, thanks!

**Closed by mxschmitt** 2023-07-13 17:38 UTC
Labels: triaging
