### ISSUE TITLE
[Question] - Page.click fails 

### ISSUE THREAD

**Issue by josephkim583** [microsoft/playwright#5753] opened 2021-03-08 17:38 UTC
The page.click fails for me even after waiting for the selector before performing the page.click.

```
await page.waitForSelector(selector);
await page.click(selector);
```
Below are the logs: 

```
Failed to submit: page.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "button#submit"
  selector resolved to visible <button type="button" role="button" tabindex="-1" id="bt…>Submit</button>
attempting click action
  waiting for element to be visible, enabled and not moving
  element is visible, enabled and does not move
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (1013.28,440.7)
  element does receive pointer events
  performing click action
============================================================
```

**Comment by pavelfeldman** [comment] 2021-03-08 23:09
Did you manually set a small timeout? You don't need to wait before click, it'll do it on its own. What is the OS?

**Comment by josephkim583** [comment] 2021-03-08 23:30
I believe it is linux

**Comment by yury-s** [comment] 2021-03-10 01:12
Is it possible for you to share the page and failing code snippet (with the selector etc) so that we could reproduce it?

**Comment by aslushnikov** [comment] 2021-05-07 21:54
I'll close the issue since the discussion has stalled. Please feel free to resubmit once there's a repro!

**Closed by aslushnikov** 2021-05-07 21:54 UTC
