### ISSUE TITLE
[BUG]Full-page screenshot in headful mode is cropped in Playwright.

### ISSUE THREAD

**Issue by anhtumai** [microsoft/playwright#7465] opened 2021-07-05 13:14 UTC
**Context:**
- Playwright Version: 1.12.3
- Operating System: Windows
- Node.js version: 14.17
- Browser: Chromium, Firefox
- Extra:

**Code Snippet**

The code sample generates full page screenshots for both headful and headless modes.

```javascript
import { chromium, firefox, Browser } from "playwright";

async function takeScreenshot(browser: Browser, screenshotPath: string) {
    const test_website = "https://playwright.dev/docs/screenshots#full-page-screenshots"
    const page = await browser.newPage()

    await page.goto(test_website)

    await page.screenshot({ path: screenshotPath, fullPage: true })

    await page.close()
    await browser.close()
}

(async () => {
    const headfullBrowser = await chromium.launch({
        headless: false,
        slowMo: 1000,
    })

    await takeScreenshot(headfullBrowser, 'output/headfull-screenshot.png')

    const headlessBrowser = await chromium.launch({
        headless: true,
        slowMo: 1000,
    })

    await takeScreenshot(headlessBrowser, 'output/headless-screenshot.png')

})();
```
Additional info: tsconfig.json

```json
{
    "compilerOptions": {
        "target": "es6", 
        "module": "commonjs", 
        "outDir": "./build", 
        "rootDir": "./src",
        "strict": true, 
        "moduleResolution": "node",
        "esModuleInterop": true, 
        "skipLibCheck": true, 
        "forceConsistentCasingInFileNames": true 
    },
    "exclude": [
        "tests"
    ]
}
```

**Describe the bug**

The screenshot generated in headful mode does not cover the full page like in headless mode. As you can see, the first screenshot ( the one generated in headful mode), is cropped compared to the second one.

Headful mode          |  Headless mode
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/32799668/124476866-07359e80-ddac-11eb-9fcb-357db8d99a27.png)  |  ![](https://user-images.githubusercontent.com/32799668/124476882-0ac92580-ddac-11eb-82b3-c00b00703c92.png)

**Comment by mxschmitt** [comment] 2021-08-02 08:09
Closing as a duplicate of #6188

**Closed by mxschmitt** 2021-08-02 08:09 UTC
Labels: triaging
