### ISSUE TITLE
[BUG] Screenshot comparison failing in firefox

### ISSUE THREAD

**Issue by edumserrano** [microsoft/playwright#28511] opened 2023-12-06 02:28 UTC
### System info
- Playwright Version: [v1.40.1]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

### Source code

1) Clone the tag `temp-1` from my [playwright-adventures repo](https://github.com/edumserrano/playwright-adventures/tree/temp-1).
2) With your favourite editor go to [./demos/code-coverage-with-monocart-reporter/src/app/app.component.css](https://github.com/edumserrano/playwright-adventures/blob/temp-1/demos/code-coverage-with-monocart-reporter/src/app/app.component.css) and change the line 2 from `color: green;` to `color: var(--gray-700);`.
3) Use your favourite shell to go to `./demos/code-coverage-with-monocart-reporter`.
4) Run `npm i` to install all required npm packages.
5) Run `npm run test` to run the playwright tests.

**Expected**

3 tests should fail. The [screenshot test](https://github.com/edumserrano/playwright-adventures/blob/d8d2b88acac6c5be8d830dfb3c8d0ca23d434025/demos/code-coverage-with-monocart-reporter/tests/example.spec.ts#L3) should fail on all three browsers.

**Actual**

Only 2 tests fail. The [screenshot test](https://github.com/edumserrano/playwright-adventures/blob/d8d2b88acac6c5be8d830dfb3c8d0ca23d434025/demos/code-coverage-with-monocart-reporter/tests/example.spec.ts#L3) doesn't fail on firefox.

![image](https://github.com/microsoft/playwright/assets/15857357/7abe2a72-3715-43ed-88ab-c8b053a6fe4f)

### Further notes

1) Even on `chromium` and `webkit` browsers where the test is failing, the pixel differences flagged are very small. Perhaps that's due to the pixel difference between the `color: green` and `color: var(--gray-700)`, I only get about 14 pixels diff. If I change the CSS to `color: red` I get a much higher pixel difference, above 360 pixels, and the test also fails on firefox as expected.

**Comment by dgozman** [comment] 2023-12-08 21:08
This is probably due to default `threshold` being `0.2`. Take a look at the [available comparator options](https://playwright.dev/docs/api/class-testproject#test-project-expect). If you need stricter matching, adjust values from their defaults. Also, take a look at our [generic guide](https://playwright.dev/docs/test-snapshots).

Let me know whether this helps or you have any other questions about screenshot comparisons.

**Comment by edumserrano** [comment] 2023-12-09 01:44
Good links to the documentation. I must say I didn't notice there was a default `threshold` but I can see why it makes sense to have one.

The default threshold explains the very small pixel difference between the `color: green` and `color: var(--gray-700)`. However it doesn't explain why that small pixel difference is flagged in both `chromium` and `webkit` but not on `firefox` right?

If you guys believe that `firefox` isn't flagging in a similar fashion because of some current limitations on that browser then feel free to close this issue.

**Comment by mxschmitt** [comment] 2023-12-13 01:22
This is most likely caused by a difference in how browsers are rendering elements on the page. We recommend having a more strict threshold then.

Closing as per above.

**Closed by mxschmitt** 2023-12-13 01:22 UTC
