### ISSUE TITLE
[BUG] Firefox new page opens as new window instead of tab.

### ISSUE THREAD

**Issue by shirshak55** [microsoft/playwright#4123] opened 2020-10-13 12:01 UTC
```
import { firefox, chromium } from "playwright"

async function main() {
  let browser = await firefox.launch({ headless: false })

  let context = await browser.newContext()

  let page = await context.newPage()
  let page1 = await context.newPage()

  await page.goto("https://microsoft.com")
  await page1.goto("https://microsoft.com")
}

async function main2() {
  let browser = await chromium.launch({ headless: false })

  let context = await browser.newContext()

  let page = await context.newPage()
  let page1 = await context.newPage()

  await page.goto("https://microsoft.com")
  await page1.goto("https://microsoft.com")
}

main().catch((e) => {
  console.error(e)
})

main2().catch((e) => {
  console.error(e)
})

```

Here is screenshot . Clearly code is nearly same with firefox and chromium replaced. But the behavior is weird firefox spawns window which is supposed to be tab. And Chrome behaves properly.

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/8097377/95857685-faf34800-0d29-11eb-86d8-c920345750b9.png">

Plus this following code shows 2 window now in past it used to show 1 window with 2 tabs.
```
  let browser = await chromium.launch({ headless: false })
  let page = await context.newPage()
  let page1 = await context.newPage()
```

Discovered while upgrading the plugin.

Thanks.

**Comment by mxschmitt** [comment] 2020-10-13 13:58
Hey, seems to be a duplicate of #3696

**Comment by shirshak55** [comment] 2020-10-13 14:25
nope its not a duplicate. In chrome there is no issue and in firefox there is issue. That 3696 doesn't mention this.

**Comment by pavelfeldman** [comment] 2020-10-20 14:57
I think it is a dupe, let's keep discussion in a single place. #3696

**Closed by pavelfeldman** 2020-10-20 14:57 UTC
