### ISSUE TITLE
Error: Protocol error (Overlay.highlightNode): Could not find object with given id

### ISSUE THREAD

**Issue by phileba** [microsoft/playwright#2704] opened 2020-06-25 02:42 UTC
Sorry for re-post this issue cause the last one was closed and I can not reopen, I have the context:
* Playwright
```ts
const browser = await chromium.launch();
const page = await browser.newPage();
await page.goto('https://amazon.com')
const context = (await page.context()) as ChromiumBrowserContext
const client = await context.newCDPSession(page)
const element = await page.$('h1,h2,h3,p');
const objectId = element['_objectId']
await client.send('Overlay.highlightNode', {
    highlightConfig: {
        showInfo: true,
        borderColor: {
            r: 76,
            g: 175,
            b: 80,
            a: 1
        },
        contentColor: {
            r: 76,
            g: 175,
            b: 80,
            a: 0.24
        },
        shapeColor: {
            r: 76,
            g: 175,
            b: 80,
            a: 0.24
        },
    },
    objectId,
})
```
the `objectId` has value `{"injectedScriptId":3,"id":1}` but I got the error: `Error: Protocol error (Overlay.highlightNode): Could not find object with given id`.

I can do this action on Puppeteer as the following:
```ts
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('https://amazon.com')
  const element = await page.$('h1,h2,h3,p');
  const client = element['_client']
  const objectId = element['_remoteObject']['objectId']
  await client.send('Overlay.highlightNode', {
    highlightConfig: {
        showInfo: true,
        borderColor: {
            r: 76,
            g: 175,
            b: 80,
            a: 1
        },
        contentColor: {
            r: 76,
            g: 175,
            b: 80,
            a: 0.24
        },
        shapeColor: {
            r: 76,
            g: 175,
            b: 80,
            a: 0.24
        },
    },
    objectId,
})
```
So I'm not sure how to do this on playwright?

**Comment by pavelfeldman** [comment] 2020-06-25 23:03
`const client = await context.newCDPSession(page)` gave you a dedicated session. That session does not share object ids with Playwright's session. You can't pass object ids from one to another. Could you share more about your use case?

**Comment by phileba** [comment] 2020-06-26 07:11
@pavelfeldman I just want to navigate to `https://amazon.com` then highlight some element likes this image below:
![image](https://user-images.githubusercontent.com/44990652/85830485-e14be600-b7b6-11ea-8d8b-bc67694d8961.png)
It used to work on puppeteer but I'm not sure how to make it work on playwright?

**Comment by pavelfeldman** [comment] 2020-06-28 16:23
In Puppeteer, you were reaching out to a private property to get a hold of the session that Puppeteer itself used. You can do the same in Playwright, it is just harder to find and abuse it here.

But I would encourage you to think in the browser-neutral way since that's what we want for Playwright in the end of the day and request a feature where you can trigger inspector (or any other) highlight. Something like `handle.inspext()` that would highlight and reveal in devtools if those are opened. Would that work for you?

**Comment by phileba** [comment] 2020-06-29 02:11
that's sounds good

**Comment by aslushnikov** [comment] 2020-08-21 07:23
I'll close this as a dupe of https://github.com/microsoft/playwright/issues/2747

**Closed by aslushnikov** 2020-08-21 07:23 UTC
