### ISSUE TITLE
[BUG] VSCode, pnpm, turbo, and playwright don't want to play together

### ISSUE THREAD

**Issue by Mrashes** [microsoft/playwright#24575] opened 2023-08-02 21:11 UTC
### System info
- Playwright Version: [v1.XX] Extension - 1.0.15, @playwright/test - ^1.36.2
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.] MacOS 13.4.1
- Browser: [All, Chromium, Firefox, WebKit] VsCode
- Other info: 

Background - Our repo recently migrated to a monorepo (turbo and pnpm to make that happen) and since then I'm no longer able to use the vscode plugin.  It used to be one of my favorite parts of playwright development, is there any remedy to this?

From searching the issues with yarn pnp seem to be the closest to this [issue](https://github.com/microsoft/playwright/issues/23924) but as I'm not using pnp I was unsure if this is documented anywhere.

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**
https://github.com/Mrashes/pnpm-vscode-test
Note: This is an example repo I just set up but I am seeing the same issues in this repo as our production one

**Steps**
- Navigate to test explorer in vscode
- Refresh
- Be prompted that you need to install playwright

**Expected**

[Describe expected behavior]
Test Explorer shows all tests within given repo.

**Actual**

[Describe actual behavior]
No tests shown in Test Explorer

Image of the problem seen
<img width="1904" alt="Screenshot 2023-08-02 at 4 06 43 PM" src="https://github.com/microsoft/playwright/assets/16417115/c8b2472b-6f05-4681-8114-9c7a32d6e120">

**Comment by yury-s** [comment] 2023-08-02 22:14
I cannot reproduce it on a fresh checkout. I ran:

```bash
git clone git@github.com:Mrashes/pnpm-vscode-test.git
CI=true pnpm i
code .
```
and this is what I see in the test explorer:

![image](https://github.com/microsoft/playwright/assets/9798949/7365f92c-0379-496d-9f39-d3090c3512aa)

Can you reproduce it with a fresh checkout?

**Comment by Mrashes** [comment] 2023-08-03 13:55
If thats the case, I assume my issue is with vscode as fresh checkout had the same results.  Attached is my extension list, I'll try to uninstall all extensions and only have playwright on.

christian-kohler.npm-intellisense
dbaeumer.vscode-eslint
dsznajder.es7-react-js-snippets
ecmel.vscode-html-css
esbenp.prettier-vscode
GitHub.vscode-pull-request-github
HookyQR.JSDocTagComplete
Jacano.vscode-pnpm
jock.svg
mhutchie.git-graph
ms-azuretools.vscode-docker
ms-kubernetes-tools.vscode-kubernetes-tools
ms-playwright.playwright
ms-python.isort
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
ms-vscode-remote.remote-containers
ms-vscode.vscode-typescript-next
ms-vsliveshare.vsliveshare
naumovs.color-highlight
oouo-diogo-perdigao.docthis
Orta.vscode-jest
redhat.vscode-yaml
rvest.vs-code-prettier-eslint
ryu1kn.partial-diff
stevencl.addDocComments
streetsidesoftware.code-spell-checker
waderyan.gitblame
yzhang.markdown-all-in-one
znck.grammarly

**Comment by Mrashes** [comment] 2023-08-03 13:57
With only Playwright installed on vscode i'm getting the same results.

**Comment by dgozman** [comment] 2023-08-07 22:41
@Mrashes Not sure how to help you in this case. Perhaps search in VSCode issues? Closing for now. If you believe we can do something meaningful, please file a new issue and link to this one. However, it's unlikely we'll be able to help without being able to reproduce this issue locally.

**Closed by dgozman** 2023-08-07 22:41 UTC
Labels: triaging
