### ISSUE TITLE
[BUG] Route feature not working in headless mode

### ISSUE THREAD

**Issue by habin-163** [microsoft/playwright#28617] opened 2023-12-13 08:30 UTC
### System info
- Playwright Version: [v1.40.0]
- Operating System: [Ubuntu 20, macOS 13.2, etc.]
- Browser: [Chromium]
- Other info: Pytest

I am trying to log the network calls during a web automation. In headed mode the calls are getting logged but in headless mode the calls are not logged. Tried with debug as well

page.route("","")

**Steps**
- [Run any test in headed mode and log the calls]
- [Run any test in headless mode and check if log calls works]

**Expected**

Similar behaviour in headed and headless mode

**Actual**

The route option is not called

**Comment by mxschmitt** [comment] 2023-12-13 16:44
Closing since this issue does not contain clear reproduction steps. Most likely the website behaves different when running in headless vs. running in headed. (e.g. bot protection). For that you could set a different user agent see [here](https://playwright.dev/python/docs/test-runners#fixtures).

**Closed by mxschmitt** 2023-12-13 16:44 UTC
