### ISSUE TITLE
[BUG] Dispatch even not working

### ISSUE THREAD

**Issue by macroking** [microsoft/playwright#11934] opened 2022-02-08 14:05 UTC
**Context:**
- Playwright Version: 1.18.1
- Operating System: Windows
- Node.js version: 14.17.0
- Browser: Chrome 97.x

**Code Snippet**

Unable to send dispatch event. I tried to use dispatch event using elementhandle and also page, neither of them worked. For example:

```javascript
        let taskName = 'Dummy';
        await page.selectOption('xpath=//select', {label: taskName});
        await page.dispatchEvent('xpath=//select', 'input');
        await page.dispatchEvent('xpath=//select', 'change');
```

**Describe the bug**

Oracle Cloud application, where in I need to select an option from a `select` box. After selection, the application loads  a set of links related to the selected value. 
The problem I am facing is even though the exact value was selected, the related links were not loaded.

Here is what I tried in the Chrome developer console, and it worked. I don't how I can get the dispatchevent to work in Playwright
```js
$x('//select')[0].dispatchEvent(new Event('input', { bubbles: true }))
$x('//select')[0].dispatchEvent(new Event('change', { bubbles: true }))
```

**Comment by pavelfeldman** [comment] 2022-02-08 16:15
You don't need to dispatch anything, `await page.selectOption` will simulate user action in full. The reason behind the problem is that you page has a bug - it installs listeners (hydrates the page) too late, after you clicked. But before you get a chance to use DevTools, so running it from console works!

**Comment by pavelfeldman** [comment] 2022-02-11 20:25
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2022-02-11 20:25 UTC
Labels: triaging
