### ISSUE TITLE
[Question] axe-core(web accessibility testing plugin) support for Playwright Java?

### ISSUE THREAD

**Issue by KSingla15** [microsoft/playwright#15871] opened 2022-07-22 06:46 UTC
Is there any plan to extend axe-core(https://www.deque.com/axe/) support for Playwright Java?

I am currently using Playwright Java for functional automation testing and realized that there is no support for accessibility testing in Playwright java. However, it's there with Playwright Node.js.

**Comment by dgozman** [comment] 2022-07-22 19:48
Duplicate of #15872.

**Closed by dgozman** 2022-07-22 19:48 UTC
