### ISSUE TITLE
[BUG] `ERR_FS_FILE_TOO_LARGE` when trying to upload a file bigger than 2GB

### ISSUE THREAD

**Issue by italodeandra** [microsoft/playwright#11738] opened 2022-01-30 02:29 UTC
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows 11
- Node.js version: 16.13.0
- Browser: Chromium

**Code Snippet**

```javascript
const {chromium} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();

  await context.clearCookies();
  await context.addCookies(cookies);

  const page = await context.newPage();

  await page.goto("https://www.youtube.com/channel_switcher");

  await page.click(`text=${channel.youtubeChannelName}`);

  await page.goto("https://studio.youtube.com/");

  await page.click('ytcp-button[role="button"]:has-text("Create")');
  await page.click("text=Upload videos");

  await page.click('ytcp-button[role="button"]:has-text("Select files")');

  await page.setInputFiles(
    'ytcp-button[role="button"]:has-text("Select files")',
    videoToUpload
  ); // triggers error
})();
```

**Describe the bug**

The following error appears:

```
page.setInputFiles: File size (5935778423) is greater than 2 GB
```

**Alternative that also doesn't work**

I also tested like this and I get the same error:

```js
const [fileChooser] = await Promise.all([
  page.waitForEvent("filechooser"),
  page.click('ytcp-button[role="button"]:has-text("Select files")'),
]);
await fileChooser.setFiles(videoToUpload);
```

**My own investigation**

This error only happens when I use the code from playwright for uploading. But if I use a `await page.pause()` and select the file manually on the File Chooser, the upload works.

From what I understand from the error, is that Playwright will load the file on Node memory (notice `FS` on the error code) and try to send it to the File Chooser from a Buffer or something similar. But why can't I just send a path to the File Chooser instead of loading it on the memory?

**Comment by italodeandra** [comment] 2022-01-30 20:15
The same code on Puppeteer (or at least the most similar I could make it) works though. Here's the part where I use the File Chooser.

```ts
const [fileChooser] = await Promise.all([
    page.waitForFileChooser(),
    selectBtn[0].click()
])
await fileChooser.accept([pathToFile])
```

How different is the implementation of the File Chooser on Playwright to Puppeteer?

**Comment by Nav-2d** [comment] 2022-01-31 04:45
Related #3768

**Comment by italodeandra** [comment] 2022-01-31 04:49
> Related #3768

Hi @Nav-2d, thanks for looking into it. I hope you don't close my issue just because it's similar to that other one. I actually already looked into the mentioned issue but they don't give that much information like I'm trying to do here so the issue became kind of forgotten in time.

Please let me know if you need more information about the problem.

**Comment by aslushnikov** [comment] 2022-01-31 18:14
@italodeandra this is actually a dupe of #3768. And good news, #3768 is now prioritized! 

So I'll close this as a dupe.

**Closed by aslushnikov** 2022-01-31 18:14 UTC

**Comment by laviniaSer07** [comment] 2022-05-03 08:06
Hello! I'm still getting this error when I am trying to upload a file grater then 2 GB `RangeError [ERR_FS_FILE_TOO_LARGE]: File size (3235260344) is greater than 2 GB`. Is there any update for the files that are larger than 2GB ?
