### ISSUE TITLE
[Regression]: A wheel event does not scroll the window

### ISSUE THREAD

**Issue by IliaVerem** [microsoft/playwright#32804] opened 2024-09-25 14:02 UTC
### Last Good Version

1.44

### First Bad Version

1.45

### Steps to reproduce

1. Run the code below in the **headless Chromium** browser (If necessary, add additional timeouts).

```
import { expect, test } from "@playwright/test";

test.beforeEach(async ({ page }) => {
  test.slow();
  // Login
  await page.goto("https://dev.alloyservice.com");
  await page.getByLabel("User name", { exact: true }).fill("playwright@example.com");
  await page.getByLabel("Password", { exact: true }).fill("playwright");
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page.getByRole("heading", { name: "AlloyScan" })).toBeVisible({ timeout: 15_000 });
});

test("Test", async ({ page }) => {
  // Go to software grid and open filter
  await page.getByRole("link", { name: "Software", exact: true }).click();
  await page.getByRole("columnheader").filter({ hasText: "Product name" }).getByRole("button", { name: "Filter by" }).click();
  // Scroll to value
  const value = page.getByRole("button", { name: "zlib", exact: true });
  let iteration = 0;
  await page.getByRole("tooltip").hover();
  while (await value.isHidden()) {
    await page.mouse.wheel(0, 300);
    if (iteration == 300) throw new Error("Button not found.");
    iteration++;
  }
  await expect(value).toBeVisible();
});
```

### Expected behavior

The last element of the filter window should be visible. Test should pass.

### Actual behavior

Scrolling hangs somewhere in the middle. Test fails.

### Additional context

- Scrolling works fine in the headed Chromium browser or in the Firefox browser (both headless and headed).
- Decreasing the speed (deltaY) does not help.

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 2700 Eight-Core Processor
    Memory: 8.28 GB / 15.94 GB
  Binaries:
    Node: 20.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.3 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.93.1 - C:\Users\iliav\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.47.2 => 1.47.2
```

**Comment by IliaVerem** [comment] 2024-09-27 12:43
> The test passes for me locally with Playwright 1.47.2 in headless mode 10 times out of 10, looks like you have a race condition.

@yury-s

Hmm, that's strange 🤔
The tests never pass 10 out of 10 for me - there are always at least three failures. However, with version 1.44, it never fails.
I don’t think a race condition is the issue; I tried running it in isolation with one worker, and it always passed with 1.44 but failed with the latest versions.

**Comment by yury-s** [comment] 2024-09-27 19:07
Try recording a trace and debug where it is failing. Could be some [hydration](https://playwright.dev/docs/navigations#hydration) issue. Closing this report as we cannot reproduce it locally and cannot take any meaningful action on it. Feel free to open a new bug if you can extract relevant bits from https://dev.alloyservice.com into a self-contained reliable repro.

**Closed by yury-s** 2024-09-27 19:07 UTC

**Comment by IliaVerem** [comment] 2024-10-01 12:16
In case someone else encounters the same issue.

I found a workaround that works for me.
I simply added a brief backward movement before each iteration, something like this:
```ts
while (await value.isHidden()) {
    await page.mouse.wheel(0, -5);
    await page.mouse.wheel(0, 300);
    if (iteration == 300) throw new Error("Button not found.");
    iteration++;
  }
```
