### ISSUE TITLE
[BUG] Different behaviour of click action when target clear button is not visible for headless, headful and in docker. #MaterialUI #Chromium

### ISSUE THREAD

**Issue by DJ-Glock** [microsoft/playwright#3285] opened 2020-08-04 12:42 UTC
Hi all.
Found pretty urgent issue but not sure if it's a PW or Chromium issue.

**Context:**
Playwright Version: 1.2.1-chromium
Operating System: Windows 10, Ubuntu Bionic (docker image)
Node version: 12.16.2 (win) / 12.18.0 (ubuntu) 
Browser: (bundled in pw) 85.0.4182.0
Extra: Material UI element https://material-ui.com/components/autocomplete/

**Repro steps:**
1. Open a webpage.
2. Choose any value in autocomplete field.
3. Click somewhere to remove focus from the field.
4. Click clear button.

**Expected result:**
Field is cleared.
<img width="340" alt="image" src="https://user-images.githubusercontent.com/26511191/89292307-d82b2000-d664-11ea-897e-80bf488bb41e.png">

**Actual result:**
Behaviour is different depending on environment and browser mode (headful, headless (win10), headless in Docker (ubuntu)).

Code sample below will allow to you reproduce the following cases:
Headful mode - **OK**, field is cleared.
<img width="340" alt="image" src="https://user-images.githubusercontent.com/26511191/89292307-d82b2000-d664-11ea-897e-80bf488bb41e.png">
Headless mode - **FAIL**, click failed. Force flag does not help.
<img width="727" alt="image" src="https://user-images.githubusercontent.com/26511191/89292853-a9617980-d665-11ea-8d9b-51fe1b6a78d2.png">

Headless mode in Docker - **FAIL**, click succeeded, but field is not cleared:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/26511191/89292710-761eea80-d665-11ea-8435-b1873174b14f.png">

**Code samples and configs**
I attached my sample project. 
[sampleForPW.zip](https://github.com/microsoft/playwright/files/5022104/sampleForPW.zip)

And just in case putting sample code here:
**Test.ts**

```
// @ts-check
const playwright = require("playwright-chromium");
const path = require("path");

(async () => {
  const browser = await playwright.chromium.launch({
    // Change it according your needs
    headless: true,
    slowMo: 100,
    args: [
      '--start-maximized',
      '--window-size=1920,1080',
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--enable-logging',
    ]
  });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://material-ui.com/components/autocomplete/');
  await page.waitForTimeout(3000);

  await page.type('#combo-box-demo', 'Snatch');
  await page.click('#combo-box-demo-option-0');
  await page.waitForTimeout(2000);

  // Click another hidden button to remove focus from input field
  await page.click('button[aria-label="A generic container that is programmatically focused to test keyboard navigation of our components."]', { force: true });
  await page.waitForTimeout(2000);

  // Uncomment the following line and it will fail in headless mode
  // await page.waitForSelector('button[title="Clear"]', { state: 'attached' });

  const before = path.format({
    dir: './screenshots/',
    name: 'before',
    ext: '.png',
  });
  await page.screenshot({ path: before });

  // Expected behavior: text is cleared after clicking clear button
  await page.click('button[title="Clear"]', { force: true });
  const after = path.format({
    dir: './screenshots/',
    name: 'after',
    ext: '.png',
  });
  await page.waitForTimeout(2000);
  await page.screenshot({ path: after });

  await browser.close();
})();
```

**Dockerfile:**
```
# https://hub.docker.com/_/microsoft-playwright
# https://github.com/microsoft/playwright/blob/v1.2.1/docs/docker/Dockerfile.bionic

FROM mcr.microsoft.com/playwright:bionic

USER root

RUN  apt-get update \
	 && apt-get install -y sudo \
	 && usermod -aG sudo pwuser \
	 && echo "pwuser ALL=(ALL) NOPASSWD: ALL" | tee -a /etc/sudoers \
     && apt-get install -y gnupg2 \
     && apt-get install -y wget --no-install-recommends \
     && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
	 && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
	 && apt update \
	 && apt install yarn \
     && yarn add playwright-chromium@1.2.1

USER root
```

**docker-compose.yml:**
```
version: "3.7"
services:
  pw_sample:
    image: pw_sample
    network_mode: host
    build:
      context: .
    volumes:
      - ./src:/src
      - ./screenshots:/screenshots
    environment:
      DEBUG: pw:api
      IS_DOCKER: 1
    command: /bin/sh -c "node ./src/Test.ts"
```

**package.json:**
```
{
  "devDependencies": {
    "fs": "^0.0.1-security",
    "path": "^0.12.7",
    "playwright-chromium": "^1.2.1",
    "ts-node": "^8.3.0",
    "tslib": "^1.10.0",
    "typescript": "^3.6.2"
  }
}
```

**Launching**
Win 10 launching command:
`node src/Test.ts
`
Run in Docker: 
`docker-compose up --build --abort-on-container-exit --exit-code-from pw_sample`

**Possible workarounds**
Possible workaround for Docker case is the second click depending on fact that it's run via Docker:

```
// Expected behavior: text is cleared after clicking clear button
await page.click('button[title="Clear"]', { force: true });
if (process.env.IS_DOCKER) {
  await page.click('button[title="Clear"]', { force: true });
}
```

**Comment by DJ-Glock** [comment] 2020-09-14 07:43
Hey,
Did you have any chance to look into this issue?

**Comment by mxschmitt** [comment] 2020-09-14 08:09
We could you try to use the latest playwright version? And keep in mind, you don't have to install fs/path manually in your package.json.

**Comment by DJ-Glock** [comment] 2020-09-14 15:27
Checked with the latest PW version - still the same.

**Comment by dgozman** [comment] 2020-09-14 17:05
This works for me locally in both headless and headful on mac, with Playwright 1.4.0.

Some thoughts:
- Docker difference might have to do something with the screen size. Try using `const context = await browser.newContext({viewport:{width:1920,height:1080}});` instead of the `--window-size` argument.
- The clear button has `visibility: hidden` unless you hover the combo box, at least in headful. Instead of using `force` I'd suggest to first hover the combo box: `await page.hover('#combo-box-demo')`, and then just click the clear button.

**Comment by DJ-Glock** [comment] 2020-09-14 17:10
@dgozman 
I will try changing resolution, but not sure if it will change something.

Regarding visibility - it's true. And I tried hover and click. Hover failed with the same errors. Any chance to check the same on Windows and NodeJS 12.16.*?

**Comment by DJ-Glock** [comment] 2020-09-15 07:23
Some time before I tried to hover the hidden button. Now I tried to do hover combobox and click:
`await page.hover('#combo-box-demo')
  await page.click('button[title="Clear"]');`
And click failed in headless mode again.

I replaced window-size with viewport, nothing changed. So issue is still actual for me.

I believe that it's OS related issue.

**Comment by DJ-Glock** [comment] 2020-11-17 14:49
Hi
I reproduced the issue with the latest version of Playwright (1.6.1) on my Mac (MacOs BugSur, NodeJS: v14.15.0).
Here you are some results and attached project to reproduce the issue.

The same code (change only headless flag):
1. Headful mode - hover (or click) fails:
```
  pw:api => page.hover started +1ms
  pw:api waiting for selector "button[title="Clear"]" +0ms
  pw:api <= page.hover failed +30s
(node:6645) UnhandledPromiseRejectionWarning: page.hover: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "button[title="Clear"]"
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Connection.sendMessageToServer (/Users/dj-glock/Documents/repos/3285-issue/node_modules/playwright-chromium/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/Users/dj-glock/Documents/repos/3285-issue/node_modules/playwright-chromium/lib/client/channelOwner.js:54:53)
    at /Users/dj-glock/Documents/repos/3285-issue/node_modules/playwright-chromium/lib/client/frame.js:304:33
    at Frame._wrapApiCall (/Users/dj-glock/Documents/repos/3285-issue/node_modules/playwright-chromium/lib/client/channelOwner.js:80:34)
    at Frame.hover (/Users/dj-glock/Documents/repos/3285-issue/node_modules/playwright-chromium/lib/client/frame.js:303:21)
    at /Users/dj-glock/Documents/repos/3285-issue/node_modules/playwright-chromium/lib/client/page.js:430:60
    at Page._attributeToPage (/Users/dj-glock/Documents/repos/3285-issue/node_modules/playwright-chromium/lib/client/page.js:202:20)
    at Page.hover (/Users/dj-glock/Documents/repos/3285-issue/node_modules/playwright-chromium/lib/client/page.js:430:21)
    at /Users/dj-glock/Documents/repos/3285-issue/Test.ts:43:14
(Use `node --trace-warnings ...` to show where the warning was created)
```

2. Headless mode / Headless mode with Docker - no issues.


So there are three places where code may fail:

```
  // ATTENTION! The following line will fail in headful mode.
  // await page.waitForSelector('button[title="Clear"]', { state: 'attached' });

  const before = path.format({
    dir: './screenshots/',
    name: 'before',
    ext: '.png',
  });
  await page.screenshot({ path: before });

  // Expected behavior: text is cleared after clicking clear button
  // Use: Hover + Click or Force Click.

  // ATTENTION! The following line will fail in headful mode
  await page.hover('button[title="Clear"]', { force: true });
  await page.click('button[title="Clear"]');

  // ATTENTION! The following line will fail in headful mode
  // await page.click('button[title="Clear"]', { force: true });
```
[3285-issue.zip](https://github.com/microsoft/playwright/files/5554188/3285-issue.zip)

**Comment by dgozman** [comment] 2020-12-03 23:56
Hi @DJ-Glock. I am being unlucky with reproducing this, today `https://material-ui.com/components/autocomplete/` is just broken for me both under Playwright, and in my regular browser. DevTools shows that some main.js script does not load. I'll give it another try in a while.

**Comment by pavelfeldman** [comment] 2022-01-01 23:09
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-01-01 23:09 UTC
Labels: P2-bug, os-windows

**Comment by bressanmarcos** [comment] 2025-01-25 19:58
My tip: forget chromium. It behaves weirdly when headless vs headful. Firefox in all my tests seems to be more reliable.
