### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by chiran1729** [microsoft/playwright#23852] opened 2023-06-22 08:46 UTC
### System info
- Playwright Version: [v1.35]
- Operating System: [LINUX]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**
This is my config file
```js
 projects: [
    {
      name: `Chrome`,
      use: {
        browserName: `chromium`,
        channel: `chromium`,
        headless: false,
        viewport: { width: 1500, height: 800 },
        ignoreHTTPSErrors: true,
        acceptDownloads: true,
        screenshot: `only-on-failure`,
        trace: `retain-on-failure`,
        timezoneId: `Asia/Calcutta`, // Adding timezone as on Jenkins it takes UTC
        launchOptions: {
          slowMo: 0
        }
      }
    }
  ]
```

**Steps**
- When run through VM (Which is being run on Linux), when I open trace it is coming as blank. 

**Expected**
Trace should show just like when it runs locally. 

**Actual**
It shows as blank: 

<img width="961" alt="image" src="https://github.com/microsoft/playwright/assets/66296424/6c22a789-abba-4b17-aef3-20b6b5ae50aa">

**Comment by dgozman** [comment] 2023-06-22 16:03
@chiran1729 Without a repro that we can run locally, we won't be able to help you. Could you please provide a test that reproduces this issue?

**Comment by dgozman** [comment] 2023-06-26 16:09
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.

**Closed by dgozman** 2023-06-26 16:09 UTC
Labels: triaging
