### ISSUE TITLE
[BUG] - Text not being copied to clipboard

### ISSUE THREAD

**Issue by IgorKoryapin** [microsoft/playwright#19797] opened 2022-12-30 10:15 UTC
**Context:**
- Playwright Version: [1.23.3]
- Operating System: [Linux]
- Node.js version: [18.12.1]
- Browser: [WebKit]
- Extra: [-]

**Code Snippet**

**Describe the bug**

In my test I do the following steps:
1. I press the button "Copy text"
2. I press the key combination on the keyboard "Control + M"

I expect that I will paste the copied text into the field, but I get a void or what was previously on the clipboard.

When running the same test in the Chrome or Firefox browser, the defect is not reproduced.
And also if I do the steps with my hands (without autotests) in the Safari browser, then the defect is not reproduced.

Add any other details about the problem here.

**Comment by aslushnikov** [comment] 2022-12-30 22:57
This seems to be a dupe of https://github.com/microsoft/playwright/issues/18901

**Closed by aslushnikov** 2022-12-30 22:57 UTC
