### ISSUE TITLE
[BUG] Browser context is closing too long

### ISSUE THREAD

**Issue by viraxslot** [microsoft/playwright#5051] opened 2021-01-19 13:15 UTC
**Context:**
- Playwright Version: ^1.8.0-next-1611032356000
- Operating System: MacOS 10.15.7
- Node.js version: v12.18.3
- Browser: Chromium

**Describe the bug**
Hi, guys! I’ve added video recording to my tests as described in the documentation. Between tests I want to close all contexts except one, because I need sometimes 2, sometimes 1 context (I use approach 1 context = 1 page, because it’s easier to maintain for my application).

So, the problem is: when I’m closing context after 2-contexts test I see:
```
  pw:api => browserContext.close started +1ms
  pw:api <= browserContext.close succeeded +51s
```
It takes 50-60 seconds, so it's too long. I have a lot of such "switches".
I can provide additional logs if you tell me what to do. Could you please help? Maybe I'm doing something wrong.

Thanks in advance!

**Code Snippet**

```javascript
// how I create context and page
let parameters = {};
if (config.get('recordFailedTestVideo')) {
    parameters = {
        recordVideo: {
            dir: config.get('videosDir'),
        },
    };
}

const ctx = await this._instance.newContext(parameters);
this._contexts.push({
    ctx: ctx,
    occupied: true,
});

const page = await ctx.newPage();
page.setDefaultTimeout(Timeouts.FifteenSecondsTimeout);
this._pages.push({
    page: page,
    occupied: true,
});

// how I close contexts
for (let i = 1; i < this._contexts.length; i++) {
      await this._contexts[i].ctx.close(); // here is the problem
      this._contexts.splice(i, 1);
      this._pages.splice(i, 1);
}
```

**Update:** here is repo to reproduce: https://github.com/viraxslot/close-context-problem.git
Hope it'll help.

**Comment by LanderBeeuwsaert** [comment] 2021-01-20 11:36
In essence, it's what this item is about as well :):
https://github.com/microsoft/playwright/issues/4821

**Comment by pavelfeldman** [comment] 2021-01-27 16:24
This one is a regression from 1.7.

Note that you should never recycle contexts, discard all of them after each test.

**Comment by pavelfeldman** [comment] 2021-01-27 17:08
Not seeing this as a regression:

```
    ✓ 1 create and close context without video recording (2355ms)
    ✓ 2 create and close context WITH video recording (4393ms)
    ✓ 3 create and close context WITH video recording (6687ms)
    ✓ 4 create and close context without video recording (860ms) -- sometimes fails as a timeout due to a flaky test
```

1.8.0
```
    ✓ 1 create and close context without video recording (2159ms)
    ✓ 2 create and close context WITH video recording (3887ms)
    ✓ 3 create and close context WITH video recording (6037ms)
    ✓ 4 create and close context without video recording (705ms) -- sometimes fails as a timeout due to a flaky test
```

**Comment by pavelfeldman** [comment] 2021-01-27 17:10
I think the issue is in your test - you don't close the contexts after each test and as a result, closing all the contexts in the end of the suite. This results in a minute of the video that needs to be processed. You should close context after each test. We do that in http://github.com/microsoft/playwright-test, maybe it works for you.

**Closed** 2021-02-08 18:59 UTC
Labels: P2-bug, v1.9
