### ISSUE TITLE
Support Multimedia keys for page.keyboard.press [Feature]

### ISSUE THREAD

**Issue by Visual-Dawg** [microsoft/playwright#20277] opened 2023-01-21 17:48 UTC
Currently it is not possible to test `MediaSession` event handlers as they cannot be triggered.

Supporting the [Multimedia keyset](https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#multimedia_keys) would solve this.

When such a key is run with `page.keyboard.press` the following error occurs: `Error: keyboard.press: Unknown key: "Media*"`

**Comment by pavelfeldman** [comment] 2023-01-23 15:42
Would you be interested in contributing a patch for this one? Otherwise it's priority is going to be low and we won't be resolving it immediately.

**Comment by Visual-Dawg** [comment] 2023-01-25 17:05
I did some testing and it seems that programmatically dispatching a `Multimedia key` `keydown` event does not trigger registered `MediaSession` handler.
I am not sure if this is because the event is marked as untrusted and/or if the browser is only reacting to the OS signaling a media change, as media keys can trigger `MediaSession handlers` even if the page is not in focus.

So only adding the ability to press `Multimedia keys` is not enough.

**Comment by mastrzyz** [comment] 2023-08-17 21:35
Taking a look!

**Comment by mastrzyz** [comment] 2023-08-17 22:20
I think the problem is with using the regular native audio/video element , it isn't able to listen to any of the multimedia keys I press -> 
<img width="757" alt="image" src="https://github.com/microsoft/playwright/assets/37447884/ff145f75-96c8-4ad5-9f8d-e996256ee223">

**Comment by mastrzyz** [comment] 2023-08-17 23:53
Maybe we need to invoke this via `nativeVirtualKeyCode` ->


https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchKeyEvent

**Comment by pavelfeldman** [comment] 2024-04-22 17:56
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Closed by pavelfeldman** 2024-04-22 17:56 UTC
Labels: P3-collecting-feedback, open-to-a-pull-request
