### ISSUE TITLE
[Question] granting permissions is not working anymore

### ISSUE THREAD

**Issue by cschandra** [microsoft/playwright#13285] opened 2022-04-04 07:40 UTC
i am automating videochat application in which i have to give camera and mic permissions. To resolve this i used await context.grantPermissions(['camera', 'microphone']) previously (before a day) it was working but now i have to give permission manually. can you please help? Sharing snippet in comment.

```ts
import { test, expect, Page } from '@playwright/test'

let page : Page

test.describe("before tests", () => {

   

    test.beforeAll(async ({ browser }) => {
        page = await browser.newPage()

        const context = await browser.newContext();
        await context.grantPermissions(['camera', 'microphone'])
        
        await page.goto('/')
       
        context.clearPermissions();

    })

    test.afterAll(async ({ browser}) =>{

        const context = await browser.newContext();     
    })


    test("Click on Mute button", async() => {

        const audioMuteButton=  page.locator('button:has-text("Mic")')
        await audioMuteButton.click({force:true})
        await expect(audioMuteButton).toHaveAttribute('name', 'mic-off-outline')

    })
    
})
```

**Comment by mxschmitt** [comment] 2022-04-04 21:04
If it was working a day ago and now its not working anymore, there has to be some difference somewhere. :) Either you have upgraded a package, a peer dependency has updated, a Chromium channel has a new version, or the website you are testing is now different.

Is there a repro you can share? Otherwise it's hard for us to dig into it. Also the platform and browser you are using would help.

**Comment by cschandra** [comment] 2022-04-05 05:09
HI @mxschmitt , 
Thanks for the reply. I cannot share repo as it is private. I can only share the snippet at this time. I am using chromium with Version 101.0.4929.0

**Comment by cschandra** [comment] 2022-04-06 13:44
@mxschmitt  also tried with giving permission from the config file.

**Comment by mxschmitt** [comment] 2022-04-07 18:47
Without a repro we can't suggest. As per above, if it was working and now its not working anymore, then the issue is most likely the website which you are automating rather than Playwright itself which didn't update automatically.

**Comment by lsingh23** [comment] 2022-04-08 23:31
Hi @cschandra were you able to resolve your issue? I am struggling with the same thing. 
@mxschmitt grantPermissions is not at all working for me even when I am passing the website url like this :
   `await context.grantPermissions(['camera', 'microphone'], {origin: "https://example.com"})`

**Comment by cschandra** [comment] 2022-04-11 02:49
@lsingh23 No not yet.

**Comment by mxschmitt** [comment] 2022-04-14 11:35
Closing as per above. If it was working and then at some point it's not working anymore, then something has be different since things don't change randomly. Probably the website or the Playwright version if you don't pin it / not use any NPM lockfiles.

If you are able to pinpoint any specific issue/difference and have a repro, then we're happy to take a look.

**Closed by mxschmitt** 2022-04-14 11:35 UTC
Labels: triaging
