### ISSUE TITLE
[BUG]fileChooser.setFiles may lose the propertise of path

### ISSUE THREAD

**Issue by XYZ204720310** [microsoft/playwright#20811] opened 2023-02-10 07:50 UTC
**Context:**
- Playwright Version: [1.30.0]
- Operating System: [e.g. Windows]
- Node.js version: [e.g. 12.22, 14.6]
- Browser: [Chromium]
- Extra: [electron test]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const fileChooserPromise = window.waitForEvent('filechooser');
await window.getByText('click to select file').click();
const fileChooser = await fileChooserPromise;
await fileChooser.setFiles(`./devices.xlsx`);
```

**Describe the bug**
If file is too large(more than 50M), it will choose large files mode ,the browser will get the file object containing path, such as {name: "devices. xlsx", row: {name: "devices. xlsx", path: "xxxx/devices. xlsx"...}...},else the browser will get the file object with the path properties is empty, such as {name: "devices. xlsx", row: {name: "devices. xlsx", path: ""...}...}

**Comment by mxschmitt** [comment] 2023-02-10 10:57
Looks like a duplicate of https://github.com/microsoft/playwright/issues/10527 to me.

**Closed** 2023-02-10 19:37 UTC
Labels: triaging
