### ISSUE TITLE
ScreenSize Option set but not resolved correctly (regarding firefox) 

### ISSUE THREAD

**Issue by JMitsos** [microsoft/playwright#18226] opened 2022-10-13 08:16 UTC
Hello, I was performing some simple tests and stumbled upon something that did not seem to behave as expected....
I wanted to set the window screen size different (bigger) than the viewport but when I evaluated screen.height I always got the viewport's height.
I tried setting ScreenSize in the context but also in a new page (check Snippet below), but both behaved the same way...
I always set the ScreenSize along with ViewportSize, as documentation suggests, so that did not seem to be the case.
Then it came to my mind to check the behavior of the other browsers as well. I tested Chromium & WebKit and they both work as expected!

So, I guess it's a firefox issue and it's probably a bug rather than feature... although, I cannot tell if it occurs also on the Playwright or it was introduced in the dotnet port.

Snippet to reproduce:

```csharp
var width = 1920;
var height = 1200;

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Firefox.LaunchAsync(new() { Headless = false});

await using var context = await browser.NewContextAsync(new()
{
      ScreenSize = new ScreenSize  { Width = width, Height = height },
      ViewportSize = new ViewportSize { Width = width, Height = 1080}  //let's set something different in Viewport height
}) ;

var page = await context.NewPageAsync();
var altpage = await browser.NewPageAsync(new()
            {
                ScreenSize = new ScreenSize { Width = width, Height = height }, 
                ViewportSize = new ViewportSize { Width = width, Height = 1080 } //let's set something different in Viewport height
            }) ;

var screenheight = await page.EvaluateAsync<string>("screen.height"); // for firefox this value will be 1080 (ViewportSize Height )
var altscreenheight = await altpage.EvaluateAsync<string>("screen.height"); // for firefox this value will be 1080 (ViewportSize Height )
```

**Comment by mxschmitt** [comment] 2022-10-20 20:24
Looks like its this test which is marked as fixme in Firefox: https://github.com/microsoft/playwright/blob/c4d417e04a27090354078cdb80e9ed5ec7145a0a/tests/library/browsercontext-viewport.spec.ts#L109-L120

**Comment by dgozman** [comment] 2022-10-20 21:35
Duplicate of #9519. Thanks for filing!

**Closed by dgozman** 2022-10-20 21:35 UTC
