### ISSUE TITLE
[BUG] Timeout on WSL2, works fine in Windows Powershell

### ISSUE THREAD

**Issue by ShawnTalbert** [microsoft/playwright#18255] opened 2022-10-21 20:12 UTC
**Context:**
 
I'm just trying to get the basic example working using `playwright`  via WSL bash prompt.

- Playwright Version: 1.27.1
- Operating System: Windows and WSL
- Node.js version: 16
- Browser:  Chromium, Firefox, WebKit

# for 'native' windows
## System:
 - OS: Windows 10 10.0.19044
 - Memory: 22.89 GB / 63.73 GB
## Binaries:
 - Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
 - npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE

# for WSL
## System:
 - OS: Linux 5.10 Ubuntu 20.04.5 LTS (Focal Fossa)
 - Memory: 48.22 GB / 49.99 GB
 - Container: Yes
## Binaries:
 - Node: 16.15.0 - /usr/local/bin/node
 - npm: 8.19.2 - ~/node_modules/.bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash

**Describe the bug**
Initial test scaffold times out on WSL2, but executes fine in native Windows. I _really_ would like to stick with WSL for running commandline tests!

Starting from `npm init playwright@latest` then running `npx playwright test` on Windows Powershell results in:

```bash
    npx playwright test

      Running 3 tests using 3 workers

    3 passed (8s)

To open last HTML report run:

  npx playwright show-report
```

Running the sample project on WSL (with `pw:browser` debugging enabled):

```
 npx playwright test

Running 3 tests using 3 workers
[chromium] › example.spec.ts:3:1 › homepage has Playwright in title and get started link linking to the intro page
  pw:browser <launching> /home/stalbert/.cache/ms-playwright/chromium-1028/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-backgroun
d-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disab
le-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateT
ransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-bac
kgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute
-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-6SIstE --remote-debugging-pipe --no-startup-window +0ms  
  pw:browser <launched> pid=5382 +4ms
  pw:browser [pid=5382][err] [1021/130747.090479:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory +61ms
  pw:browser [pid=5382][err] [1021/130747.090607:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory +0ms
  pw:browser [pid=5382][err] [1021/130747.138225:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable. +47ms
[firefox] › example.spec.ts:3:1 › homepage has Playwright in title and get started link linking to the intro page                                                                           
  pw:browser <launching> /home/stalbert/.cache/ms-playwright/firefox-1357/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-skiju0 -juggler-pipe -silent +0ms
  pw:browser <launched> pid=5516 +3ms
  pw:browser [pid=5516][err] *** You are running in headless mode. +17ms
[webkit] › example.spec.ts:3:1 › homepage has Playwright in title and get started link linking to the intro page
  pw:browser <launching> /home/stalbert/.cache/ms-playwright/webkit-1724/pw_run.sh --inspector-pipe --headless --no-startup-window +0ms
  pw:browser <launched> pid=5978 +2ms
[chromium] › example.spec.ts:3:1 › homepage has Playwright in title and get started link linking to the intro page
  pw:browser [pid=5382] <gracefully close start> +30s                                                             
  pw:browser [pid=5382] <process did exit: exitCode=0, signal=null> +59ms
  pw:browser [pid=5382] starting temporary directories cleanup +0ms
  pw:browser [pid=5382] finished temporary directories cleanup +3ms
  pw:browser [pid=5382] <gracefully close end> +0ms
  1) [chromium] › example.spec.ts:3:1 › homepage has Playwright in title and get started link linking to the intro page 

    Test timeout of 30000ms exceeded while setting up "page".

    browserContext.newPage: Target closed




    Pending operations:
      - browserContext.newPage


  2) [webkit] › example.spec.ts:3:1 › homepage has Playwright in title and get started link linking to the intro page 

    Test timeout of 30000ms exceeded while setting up "page".

Worker teardown timeout of 30000ms exceeded while tearing down "context".

Failed worker ran 1 test:
[webkit] › tests/example.spec.ts:3:1 › homepage has Playwright in title and get started link linking to the intro page

  pw:browser [pid=5978] <kill> +2m
  pw:browser [pid=5978] <will force kill> +0ms
  pw:browser [pid=5978] starting temporary directories cleanup +0ms
  pw:browser [pid=5978] finished temporary directories cleanup +110ms

```

Note writing a simple test using `request`  seems to work (in WSL):

```javascript
test('homepage has Playwright in title and get started link linking to the intro page', async ({ request}) => {

  const resp = await request.get('https://playwright.dev')

  console.log((await resp.body()).toString())
})
```

results in:

```
 npx playwright test

Running 1 test using 1 worker
[chromium] › example.spec.ts:3:1 › homepage has Playwright in title and get started link linking to the intro page
<!doctype html>                                                                                                   
<html lang="en" dir="ltr" class="plugin-pages plugin-id-default">
<head>
<meta charset="UTF-8">
<meta name="generator" content="Docusaurus v2.1.0">...
```

**Comment by mxschmitt** [comment] 2022-10-25 16:49
Can you try Ubuntu 22 in WSL? As per above you are using Ubuntu 20?

From what's above it seems it does not work in all 3 browsers?

I'd recommend the following:

1. Try Ubuntu 22
2. If it does not work, then try to set `DEBUG=pw:protocol` and `--project=Chromium` to see browser by browser which protocol calls are not resolving - there you can just forward them to us and send them in the issue so we can take a look.

I remember Playwright does work in WSL2, you can even install an xserver there and launch the browsers headed.

**Comment by ShawnTalbert** [comment] 2022-10-25 21:49
Hmmm, thanks @mxschmitt - I installed a fresh Ubuntu22 and indeed the sample generated test runs. I wonder if there are known issues with Ubuntu 20 or perhaps it's something about my particular configuration of WSL/Ubuntu20?

I'll take the leap and attempt to upgrade my existing Ubuntu20 WSL instance to 22. I'll report my results here should it survive :)

**Comment by mxschmitt** [comment] 2022-10-26 16:07
Cool closing then in the meantime!

There are no known issues, but often it's because of missing ca-certificates or not having all dependencies installed.

**Comment by ShawnTalbert** [comment] 2022-10-26 22:26
It now seems to succeed for all but `webkit`. All the dependencies appear to have installed (i.e. `npx playwright install-deps` runs without error and everything is already on the newest version).

 Is there a way to uninstall/reinstall the dependencies or is there another suggestion regarding webkit funkiness?
Notably [nativeDeps.ts](https://github.com/microsoft/playwright/blob/1cedd805ed08600e87bf8a1a37f8d11ac38c9630/packages/playwright-core/src/server/registry/nativeDeps.ts) mentions `libwebp6` for Ubuntu 20 but doesn't list it for Ubuntu 22 as far as I can see?

Here is the output I get now - not sure why the odd trailing `\` and newline:

browserType.launch: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Please install them with the following command:      ║
║                                                      ║
║     sudo npx playwright install-deps                 ║
║                                                      ║
║ Alternatively, use apt:                              ║
║     sudo apt-get install libicu70\                   ║
║         libwebp6                                     ║
║                                                      ║
║ <3 Playwright Team                                   ║
╚══════════════════════════════════════════════════════╝

Note that my now upgraded Ubuntu 22 does not have `libwebp6` - it has `libwebp7` so I'm not sure why it's suggesting `libwebp6` is a missing dependency? Also `libicu70` is already installed.

 npx envinfo --preset playwright --markdown

## System:
 - OS: Linux 5.10 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
 - Memory: 49.28 GB / 49.99 GB
 - Container: Yes
## Binaries:
 - Node: 18.12.0 - /usr/local/bin/node
 - npm: 8.19.2 - ~/node_modules/.bin/npm
## Languages:
 - Bash: 5.1.16 - /usr/bin/bash

**Comment by mxschmitt** [comment] 2022-10-26 23:00
could be a bug on our side! You can try modifying the nativeDeps.js and replace the suggested deps or set the PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS env var to 1 to skip the deps check.

(Might be an issue on very minimal ubuntu22 machines tho.)

**Comment by ShawnTalbert** [comment] 2022-10-27 16:45
I wonder if this may be an artifact of _upgrading_  Ubuntu 20 to 22 vs starting with a fresh Ubuntu22 install?

A fresh Ubuntu22 installed from the store works with webkit.

I tried setting the environment variable you mention but then it complains about missing libicu66 (and of course, upgraded Ubuntu22 has libicu70).

How/where does PlayWright do OS version detection? I'm wondering if it thinks my upgraded WSL is still Ubuntu 20?

**Comment by mxschmitt** [comment] 2022-10-27 17:19
That could totally be! Maybe your installation has still some old libraries left. We do it [via /etc/os-release](https://cs.github.com/microsoft/playwright/blob/3e112193a68175afc78210c0102b60c9e1bea12a/packages/playwright-core/src/utils/linuxUtils.ts?q=os-release#L26).

**Comment by kedevked** [comment] 2022-10-28 09:01
I will also add that without xlaunch configured even chromium and firefox would not pass for me using wsl with ubuntu 22 and windows 10.
As for webkit it is failing regardless

**Comment by mxschmitt** [comment] 2022-10-31 00:56
Since the original issue is solved by a clean Ubuntu installation, I'm closing it for now. If it does not work with a clean Ubuntu WSL installation, please let us know!

kedevked please file a separate issue.

**Closed by mxschmitt** 2022-10-31 00:56 UTC
Labels: triaging

**Comment by samuliasmala** [comment] 2023-02-21 08:45
I just found out that if you have `DISPLAY` environment variable set the Playwright test will timeout unless you have X Server running. This happens even if you're using a headless mode and doesn't really need the X Server. I have WSL2 with Ubuntu 20.04 but the issue is probably not limited to those.

One easy solution is to clear the `DISPLAY` environment variable when starting the test, e.g., by modifying the `package.json` script to
```
"test:e2e": "DISPLAY= playwright test"`.
```

**Comment by ofton-kleftikon** [comment] 2023-03-19 08:43
Removing the DISPLAY variable did it for me, this also explains why it worked for [ShawnTalbert](https://github.com/ShawnTalbert) when using a clean Ubuntu install.

**Comment by samuliasmala** [comment] 2023-07-21 04:31
> > I just found out that if you have `DISPLAY` environment variable set the Playwright test will timeout unless you have X Server running. This happens even if you're using a headless mode and doesn't really need the X Server. I have WSL2 with Ubuntu 20.04 but the issue is probably not limited to those.
> > One easy solution is to clear the `DISPLAY` environment variable when starting the test, e.g., by modifying the `package.json` script to
> > ```
> > "test:e2e": "DISPLAY= playwright test"
> > ```
> 
> This works, but I guess no headed tests for us then, right?

For headed tests you need to start X Server, set proper value to `DISPLAY` environment variable and then give `--headed` parameter to playwright, e.g.

```
"test:e2e:headed": "DISPLAY=172.20.16.1:0.0 playwright test --headed"
```

However usually the `DISPLAY` env variable is set in `.bashrc` or similar file. I use the following command to set it in WSL:
```bash
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0
```
