### ISSUE TITLE
[BUG] Azure html viewer do not work with 1.25

### ISSUE THREAD

**Issue by daniavander** [microsoft/playwright#16822] opened 2022-08-25 07:49 UTC
**Context:**
- Playwright Version: 1.25.0
- Operating System: windows latest
- Node.js version: '14.x'
- Browser: chromium
hi 

I run a build under azure cicd
but when i update to @playwright/test": "^1.25.1", the html viewer does not work well

but when i use "@playwright/test": "^1.23.3"
I get a pretty html report:
![image](https://user-images.githubusercontent.com/99256716/186606214-3481691b-1a97-42bf-b29e-020e1ae65a5c.png)

**Comment by yury-s** [comment] 2022-08-25 15:50
What error do you see? Please share an example which we could debug otherwise it's difficult to understand what the problem is.

**Comment by Wilhop** [comment] 2022-08-26 08:39
@daniavander Isn't that more an Azure DevOps problem with HTML-viewer extension? I'm using the same Playwright version but instead of using an extension I publish the html report, where the html is just fine. This way you're not depending on an extension.

In Azure Pipelines we publish the report that Playwright creates (the same that you are trying to view) as an Artifact, which can be downloaded.

This is the .yaml part that is performed at the end of the .yaml.

      # Publish the playwright-report folder as an Artifact belonging to the Job
      # Note that once a job artifact has been published, it cannot be modified so eg. re-running the same job results in failed publishing
      # Whether tests succeed or not, Playwright creates a html-report of the test run in a separate folder and we need to publish it to access it from the virtual server
    - publish: $(System.DefaultWorkingDirectory)/playwright-report
      displayName: 'Publish the test report folder /playwright-report'
      artifact: playwright-report
      # By default the publish will not happen if a test fails, but we need the fail report, so we need to tell the job to run it on success and failure
      condition: succeededOrFailed()

Then you can view the Artifact(s) in the Pipeline:
![image](https://user-images.githubusercontent.com/38150366/186859935-0401c13d-4d82-44b8-b084-47c81bb2a05e.png)

**Comment by daniavander** [comment] 2022-08-26 13:00
hi @Wilhop I also publish atrifacts it work well, just i would like to see easier mode with html publisher

@yury-s I do not tell more, just in main branch i use 1.23.3 version and the html viewer work wll, on the other branch i use the latest version and does not work this plugin

**Comment by yury-s** [comment] 2022-08-26 22:30
Since the report opens fine locally, it looks like a problem with Azure DevOps as noted above and the plugin that tries to embed the html report. You should address this question to HTML-viewer extension. I'm closing this bug but feel free to open a new one if there is something we can change in Playwright to help that extension work better.

**Closed by yury-s** 2022-08-26 22:30 UTC
Labels: triaging
