### ISSUE TITLE
[BUG]: Visual Image comparison giving false failure for pixel ratio difference

### ISSUE THREAD

**Issue by goyalshweta017** [microsoft/playwright#13466] opened 2022-04-11 07:30 UTC
**Context:**
- Playwright Version: 1.20
- Operating System: Win
- Node.js version: 16.14.0
- Browser: Chromium

**Code Snippet**
Playwright Cong File
```javascript
import * as path from 'path';
import {
  adjustPath,
} from '@otter/testing/tools';
import {
  PlaywrightTestConfig,
} from '@playwright/test';


adjustPath('playwright');

const TIMEOUT = 1_000 * 60 * 5;

// Allure report only supports changing the output folder via an env variable
process.env.ALLURE_RESULTS_DIR = path.join(__dirname, '..', 'playwright-report', 'allure-results');
process.env.baseURL = 'https://dev.digital.airline.amadeus.com/1a/refx-booking-6-1-0-rc';

const config: PlaywrightTestConfig = {
  testDir: path.join(__dirname, '..', 'dist-e2e-playwright', 'e2e-playwright', 'scenarios'),
  // testDir: '../dist-e2e-playwright/e2e-playwright/scenarios',
  testMatch: /.*\.e2e-playwright-spec.js$/,
  reporter: [
    ['list'],
    ['junit', {outputFile: './playwright-report/junit/reporter.xml'}],
    ['html', {open: 'always', outputFolder: './playwright-report/html'}],
    ['allure-playwright', {outputFolder: './playwright-report/html'}]],
  forbidOnly: process.env.CI ? true : false,
  expect: {
    timeout: 10000,
    toMatchSnapshot: {
      threshold: 0.2,
      maxDiffPixels: 80,
      maxDiffPixelRatio: 0.2
    }
  },
  globalTimeout: process.env.CI ? 60 * 60 * 1000 : undefined,
  // retries: 1,
  workers: 4,
  timeout: TIMEOUT,
  use: {
    screenshot: 'only-on-failure',
    trace: 'retain-on-failure',
    browserName: 'chromium',
    headless: false
  }
};

export default config;
```
 
In my scenario file, i have added 
```javascript
 expect(await this.page.screenshot(
        { animations: 'disabled',
          mask: [this.page.locator('.selected-date'), this.page.locator('.depart-date'), this.page.locator('.cell-content-bottom')] }))
        .toMatchSnapshot('Availablity_page.png');
```

I have captured base screenshot with same script but while comparing the screenshot, its always give below error -

    **Error: Screenshot comparison failed:

      4563 pixels (ratio 0.01 of all image pixels) are different**

Above issue is like false failure which is not handing with DiffPixel/DiffPixelRatio, Can you please help how can we handle this false failure for visual comparison.
threshold: 0.2,
      maxDiffPixels: 80,
      maxDiffPixelRatio: 0.2

**Comment by aslushnikov** [comment] 2022-04-12 00:49
@goyalshweta017 can you share the diff it produces? Also, a snippet that I can run locally to reproduce this would help a lot!

**Comment by goyalshweta017** [comment] 2022-04-14 09:14
Hello @[aslushnikov]

I have give some more trial and found that when i have changed below configuration its works for some pages but for few pages its giving below error now -
" 2093 pixels (ratio 0.01 of all image pixels) are different"

playwright-conf.ts
  expect: {
    timeout: 10000,
    toMatchSnapshot: {
      threshold: 0.2,
      maxDiffPixels: **1602,**
      maxDiffPixelRatio: 0.2
    }
  },

I have few queries -
1. How can we define max pixel difference? is it recommended to have such huge pixel difference?
2. Is there any other way to handle it?

As its secured application, it will be difficult to reduced other than secured network.

please find attached screenshot for difference if you can suggest some solution?


![Payment-page-actual](https://user-images.githubusercontent.com/66407620/163353858-40e4e631-24ed-4cec-94c6-f6791a94d12d.png)
![Payment-page-expected](https://user-images.githubusercontent.com/66407620/163353879-c84a3434-73fd-4e6d-bdab-adb2e2717453.png)

![Payment-page-diff](https://user-images.githubusercontent.com/66407620/163353868-f29d3922-2ce6-4425-9f27-3ac8bdacc40e.png)
![Payment-page-expected](https://user-images.githubusercontent.com/66407620/163353869-d8357616-88c0-47c9-9b95-4f053dd9b9f8.png)
![Payment-page-diff](https://user-images.githubusercontent.com/66407620/163353898-1987e03e-48ce-4339-828e-e90828881a69.png)

**Comment by aslushnikov** [comment] 2022-04-14 22:10
@goyalshweta017 it looks like fonts rendering is different. Does your website use webfonts?

Any chance you can give us something that we can run locally to reproduce this? Otherwise, I can only speculate.

**Comment by goyalshweta017** [comment] 2022-04-18 12:19
Hello @[aslushnikov](https://github.com/aslushnikov)

I think this font rendering is coming with browser not with application. because for application when we running on same browser it should be use same font .

How can we handle this font rendering in chrome? 
In Visual Documentation -
"chromium-darwin - the browser name and the platform. Screenshots differ between browsers and platforms due to different rendering, fonts and more, so you will need different snapshots for them. If you use multiple projects in your [configuration file](https://playwright.dev/docs/next/test-configuration), project name will be used instead of chromium."

Can you please help me to resolve how can be browser font rendering can resolve? 

Thanks,
Shweta

**Comment by aslushnikov** [comment] 2022-04-18 22:46
@goyalshweta017 can you try add the following before you capture screenshot and tell me if it works?

```js
await page.evaluate(() => document.fonts.ready);
```

This should ensure that web fonts are loaded before screenshot is taken.

**Comment by goyalshweta017** [comment] 2022-04-19 08:17
Hello,

I have done below changes in config

> playwright-conf.ts
> expect: {
> timeout: 10000,
> toMatchSnapshot: {
> threshold: **0.3,**
> maxDiffPixels: 1602,
> maxDiffPixelRatio: 0.2
> }
> },

and added your suggestion before taking screenshot.
>await page.evaluate(() => document.fonts.ready);

with above changes at moment its giving the result, but i have some basic query as below -

1. how much threshold should be ideal/ expected? as we can not add this threshold randomly?
2. how much maxDiffPixels: should we keep? is there some define limit?

**Comment by aslushnikov** [comment] 2022-04-19 14:09
> with above changes at moment its giving the result

@goyalshweta017 Yay!

> how much threshold should be ideal/ expected? as we can not add this threshold randomly?

I'd recommend to keep the default.

> how much maxDiffPixels: should we keep? is there some define limit?

Most of the time, 0 should be fine. Occasionally you might have anti-aliasing artifacts that are not canceled
by comparison algorithm that will yield a few pixels diff. In this case, bumping `maxDiffPixels` would help.

> So if display resolution is matter, is there way to ignore?

It should not matter unless you set `viewport` to `null` in your config.

**Comment by goyalshweta017** [comment] 2022-04-20 05:31
@[aslushnikov](https://github.com/aslushnikov)
>await page.evaluate(() => document.fonts.ready);
above solution is not giving result consistently, i still have issue with error  **1727 pixels (ratio 0.01 of all image pixels) are different**

i have done some changes like now i am comparing full page screenshot.
**configuration -**
```
toMatchSnapshot: {
      threshold: 0.2,
      maxDiffPixels: 100,
      maxDiffPixelRatio: 0.2
    }
```
**Test**
```
  await this.page.evaluate(() => document.fonts.ready);
  expect(await this.page.screenshot(
        {
          mask: [this.page.locator('.selected-date'), this.page.locator('.depart-date'), this.page.locator('.cell- 
           content-bottom')],
          fullPage: true
        })).toMatchSnapshot('Availablity_page.png');
```

result have difference in screenshot with error -
>**1727 pixels (ratio 0.01 of all image pixels) are different**

**diff image**]

![image](https://user-images.githubusercontent.com/66407620/164156688-0a5c45b2-ec77-44d8-bfca-a12eded626dc.png)
 
Is it because of full page? or some other cause?
I see Visual comparison is bit unstable, is there something to change from Playwright side?

Thanks,
Shweta

**Comment by aslushnikov** [comment] 2022-04-20 21:54
@goyalshweta017 interesting! Any chance you can share the page URL so that I can experience this locally for myself?

**Comment by goyalshweta017** [comment] 2022-04-21 11:37
Hello [aslushnikov](https://github.com/aslushnikov),

Page URL can not access out side the VPN hence you will not be able to access from your local.

I have here some more finding -
>Usecase 1: Capture and compare the screenshot on same Window system gives below image difference (after handling font rendering)

![image](https://user-images.githubusercontent.com/66407620/164449461-3c471c45-5064-488a-9acc-4bc5b0a22d2f.png)

> Usecase 2: Capture the screenshot on one WIndow System and comparison done on another Window system 
>i have captured the screenshot on Window System having below display resolution-
![image](https://user-images.githubusercontent.com/66407620/164448518-d0730d7f-3b55-4b11-8b89-9f0e9114636c.png)
>When i am running on another window System which having below display resolution-
![image](https://user-images.githubusercontent.com/66407620/164448712-4722a24f-e7fe-42d9-bdb8-b9a80b7b1ac8.png)
>i am getting the diff in image comparison -
![image](https://user-images.githubusercontent.com/66407620/164449015-6638f54e-90ec-4cdd-8768-7875e21a4fab.png)

so have you seen this issue with any other application as well? Can you suggest something towards above 2 Use cases?

**Comment by aslushnikov** [comment] 2022-05-03 04:40
> Usecase 1: Capture and compare the screenshot on same Window system gives below image difference (after handling font rendering)

@goyalshweta017 it looks like website is not done rendering at the point of time when the screenshot is taken; thus the difference. It hard to say more than this!

> Usecase 2: Capture the screenshot on one Window System and comparison done on another Window system

I don't think we have much to recommend in this case. It looks like chromium does depend on screen settings when doing rendering!

**Comment by aslushnikov** [comment] 2022-05-04 05:43
Closing this since it seems we can't help much with this!

**Closed by aslushnikov** 2022-05-04 05:43 UTC
Labels: v1.22

**Comment by rkmsnc** [comment] 2024-09-19 15:10
This could help https://github.com/microsoft/playwright/issues/31592#issuecomment-2361010102
