### ISSUE TITLE
[Feature] Ability to search elements in trace viewer

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#11388] opened 2022-01-14 04:23 UTC
Sometimes I'll get an element selector error and will be unsure why it's wrong, and will need to re-run the test, using `page.pause` before the failing step.

Would be nice to have the ability to just directly search the page on the failed step instead of needing to re-run the test with a pause.

**Comment by dgozman** [comment] 2022-01-14 18:09
Closing as a duplicate of #7853.

**Closed** 2022-01-14 18:10 UTC
