### ISSUE TITLE
How to add visual effects to the click and other operation events of plyawright, such as adding a mouse icon

### ISSUE THREAD

**Issue by fj201314** [microsoft/playwright#18144] opened 2022-10-18 09:56 UTC
Now the automated interface is not displayed with mouse like icons. It is difficult to understand what you are doing if you have not seen it yourself

**Comment by fj201314** [comment] 2022-10-18 09:57
Now the automatic interface does not display any mouse icon. Except the owner of the use case, it is difficult for others to keep up with what the page is doing

**Comment by dgozman** [comment] 2022-10-18 14:31
Duplicate of #1374.

**Closed by dgozman** 2022-10-18 14:31 UTC
