### ISSUE TITLE
[BUG] browserContext userAgent seems not working in playwright webkit

### ISSUE THREAD

**Issue by Kingkhan14** [microsoft/playwright#22684] opened 2023-04-27 12:19 UTC
### System info
- Playwright Version: [v1.32]
- Operating System: [Windows 11]
- Browser: [WebKit]
- Other info:

i set userAgent in browsercontext using launchPersistentContext as 
`Mozilla/5.0 (iPhone; CPU iPhone OS 16_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Mobile/15E148 Safari/604.1`

but when checking in webkits console its showing as 
`Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/605.1.15 (KHTML, like Gecko)`

![image](https://user-images.githubusercontent.com/108714133/234859842-f9e9a570-71a0-4a17-bfda-546e79533228.png)

**Comment by mxschmitt** [comment] 2023-04-27 14:05
Looks like a duplicate of https://github.com/microsoft/playwright/issues/22274.

Should be fixed in Playwright v1.33.0.

**Comment by Kingkhan14** [comment] 2023-04-27 14:09
oh wow thanks thought im doing something wrong

**Comment by Kingkhan14** [comment] 2023-05-05 14:57
still getting same error after 1.33 update!

**Comment by yury-s** [comment] 2023-05-06 00:32
You are running with device emulation, running `node ua.mjs` in this [project](https://github.com/yury-s/bug-22684) works just fine. Please file a new bug with a reproducible example if this still happens for you.

**Closed by yury-s** 2023-05-06 00:32 UTC
