### ISSUE TITLE
[Bug]: Browser.new_page: Target page, context or browser has been closed

### ISSUE THREAD

**Issue by shriyashfinov8** [microsoft/playwright#31929] opened 2024-07-31 11:57 UTC
### Version

1.43.0

### Steps to reproduce

This is very hard to reproduce as the function runs perfectly fine for my local machine as well as in docker container spinned up locally.
Basically what we are trying to acheive is invoke a lambda multiple functions on aws which will initiate a browser launch with specified url and perform the further operations

Following is the code which initializes the browser and the page

         async with async_playwright() as playwright:
            browser_path = find_chromium_path()
            executable_path = f"{browser_path}/chrome-linux/chrome"
            # Local development
            if not os.path.exists(executable_path):
                executable_path = None

            proxy_details = None
            if college_url.startswith(os.getenv('PROXY_WEBSITE')):
                proxy_details = get_proxy_details()

            browser = await playwright.chromium.launch(headless=True,
                                                       proxy=proxy_details,
                                                       executable_path=executable_path,
                                                       args=[
                                                           "--no-sandbox",
                                                           "--disable-setuid-sandbox",
                                                           "--disable-dev-shm-usage",
                                                           "--disable-accelerated-2d-canvas",
                                                           "--disable-gpu",
                                                           # "--single-process",
                                                           "--no-zygote",
                                                           "--disable-audio-output",
                                                           "--disable-software-rasterizer",
                                                           "--disable-webgl",
                                                           "--disable-web-security",
                                                           "--disable-features=LazyFrameLoading",
                                                           "--disable-features=IsolateOrigins",
                                                           "--disable-background-networking"
                                                       ]
                                                       )
            page = await browser.new_page()
            
            

### Expected behavior

I expect page to open as it does locally

### Actual behavior

playwright._impl._errors.TargetClosedError: Browser.new_page: Target page, context or browser has been closed

### Additional context

Tried the page launch procedure, by creating new context and then initiating a page
but was unsuccessful as many of the lambda function failed due to following errors
playwright._impl._errors.Error: Page.goto: net::ERR_CONNECTION_RESET &
playwright._impl._errors.Error: Page.goto: net::ERR_HTTP2_PROTOCOL_ERROR

### Environment

```shell
System:                                                                                                                  
    OS: Debian GNU/Linux 12 (bookworm)                                                        
CPU: (16) x86_64 – 64-bit x86                                                                                           
    Memory: 4096MB                                                                                           
    Container: Yes                                                                                                                                                                                                  
python libraries:                                                                                                             
    playwright==1.43.0
```

**Comment by shriyashfinov8** [comment] 2024-08-01 07:18
Is the latest version of playwright stable?
Cause after navigating to page, I dont see any content loaded and we have functionality to get the lazy loaded images from the website by performing element click to render lazy loaded images which seems to be a problem now due to version change

            player_image_link_element = await player_element.query_selector("img")
            player_class_level = await player_element.query_selector(selector_config["playerElementClick"])
            await player_class_level.click()

            # Time delay of 0.3 seconds to add interval between element clicks to get correct image links
            time.sleep(0.3)
            print("Element clicked")
            player_image_link = await player_image_link_element.get_attribute("src")
            player["playerImageLink"] = player_image_link
            print(player_image_link)

The images are not loaded as a result i am getting values like
data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7

![image](https://github.com/user-attachments/assets/2233bf86-da70-4102-b82d-1e139e541d30)

**Comment by mxschmitt** [comment] 2024-08-01 07:23
Yes, every recent Playwright version is considered stable.

I see you are using time.sleep which has side effects, see here: https://playwright.dev/python/docs/library#timesleep-leads-to-outdated-state. Never wait for time, since it causes flakiness. Wait for elements using wait_for instead.

Also query_selector is discouraged, see here: https://playwright.dev/python/docs/api/class-page#page-query-selector

We need something which we can run locally, otherwise we can't act on it.

**Comment by mxschmitt** [comment] 2024-08-01 08:29
This script is not self-contained. Several variables like players_data are missing. Please provide us something which we can run locally. Thanks!

**Comment by shriyashfinov8** [comment] 2024-08-01 08:50
Following is the script for you to run locally,
Fortunately or unfortunately the script runs fine and gives me the image urls
but fails to do so in my main codebase which i can't share with you for security reasons
I dont exactly know what the issue is but after navigating to url with ?view=table

the images are not displayed as shown in the image i provided above




from playwright.async_api import async_playwright
import time
import asyncio

async def main():
    async with async_playwright() as playwright:
        
            browser = await playwright.chromium.launch(headless=False,
                                                    args=[
                                                        "--no-sandbox",
                                                        "--disable-setuid-sandbox",
                                                        "--disable-dev-shm-usage",
                                                        "--disable-accelerated-2d-canvas",
                                                        "--disable-gpu",
                                                        # "--single-process",
                                                        "--no-zygote",
                                                        "--disable-audio-output",
                                                        "--disable-software-rasterizer",
                                                        "--disable-webgl",
                                                        "--disable-web-security",
                                                        "--disable-features=LazyFrameLoading",
                                                        "--disable-features=IsolateOrigins",
                                                        "--disable-background-networking"
                                                    ]
                                                    )
            page = await _setup_page_properties(browser)
            
            await page.goto("https://gopsusports.com/sports/football/roster?view=list")
            
            await page.wait_for_load_state('domcontentloaded')

            player_elements = page.locator(".roster-players-list .player-list-item")
            count = await player_elements.count()

            for i in range(count):
                player_element = player_elements.nth(i)
                player_image_link_element = player_element.locator("img")
                player_class_level = player_element.locator(".player-list-item__profile-fields").first
                await player_class_level.click()
                time.sleep(0.3)
                player_image_link = await player_image_link_element.get_attribute("src")
                print(player_image_link)

async def _setup_page_properties(browser):
    page = await browser.new_page()
    page.set_default_navigation_timeout(60000)
    blocked_types = ["image", "media", "adservice.google.com", "doubleclick.net"]

    async def block_requests(route, request):
        if route.request.resource_type in blocked_types:
            # logger.info(f"Blocking {route.request.resource_type} request: {request.url}")
            await route.abort()
        else:
            await route.continue_()
        await page.route("**/*", block_requests)
    return page


asyncio.run(main())

**Comment by shriyashfinov8** [comment] 2024-08-01 08:54
I plan to keep the old version of playwright=1.43.0 as that is the one working for my prod environment.
As for the main issue
with use of browser : 
 Browser.new_page: Target page, context or browser has been closed

with use of context : 
playwright._impl._errors.Error: Page.goto: net::ERR_CONNECTION_RESET &
playwright._impl._errors.Error: Page.goto: net::ERR_HTTP2_PROTOCOL_ERROR

while launching the page from 
context = await browser.new_context()
page = await context.new_page()

can you suggest any workaround this?
as the implementation was working fine until a few days ago

**Comment by mxschmitt** [comment] 2024-08-01 13:12
> as the implementation was working fine until a few days ago

This suggests, that the webserver of the site has changed and might not be compatible with recent Chrome.

I'll close it for now since we need a reproduction, the one you shared works for you and me, so it seems all working as expected. Don't hesitate to re-file if you have something you can share with actual/expected outcome. Thank you for your understanding!

**Closed by mxschmitt** 2024-08-01 13:12 UTC

**Comment by mxschmitt** [comment] 2024-08-01 17:55
Might be a Chromium bug - but as per above, we need a reproduction in order to look into issues like this. Most likely the website's webserver is miss-behaving with h2.

**Comment by shriyashfinov8** [comment] 2024-08-02 08:50
Now moved backed to playwright 1.43.0 and hoping not to get any issues related to browser.new_page()

**Image content issue**
The image src not loading related to the use of playwright_stealth in the code
https://github.com/AtuboDad/playwright_stealth/issues/31

As for playwright 1.45.1 in the production consumed the entire timeout of lambda function, which will cost us huge amounts.
So keeping the older version running for now.
