### ISSUE TITLE
[QUESTION] Http authentication not working as expected on BrowsertStack

### ISSUE THREAD

**Issue by duartmig** [microsoft/playwright#20611] opened 2023-02-03 11:32 UTC
**Context:**
- Playwright Version: [1.27.1]
- Operating System: [Mac]
- Node.js version: [16.14.2]
- Browser: [Chromium, WebKit]
- Extra: BrowsertStack

**Code Snippet**

Ex 1 
test.beforeEach(async ({ browser, request }) => {
    var context = await browser.newContext({
      httpCredentials: {
        username: 'user',
        password: 'pass',
      },
    });

Ex 2

Test file: 

let page;

  test.beforeEach(async ({ context, request }) => {
    //Isolated Page instance, created for each test
    page = await context.newPage();
}

Config file:
use: {
    httpCredentials:{
      username:"user",
      password:"pass"
    },

**Describe the bug**

We are using Http credentials as an authentication method using the above snippet which is working fine for local browsers but if we try to run on browsesrtack by creating fixtures we see flakiness with authentication (often giving 401). Adding the credentials in config files (Ex 2) does not solve the issue

**Comment by dgozman** [comment] 2023-02-03 17:08
@duartmig If everything works locally, but fails on BrowserStack, I am inclined to believe the issue is on the BrowserStack side. In this case, I'd recommend filing an issues against BrowserStack project instead. Sorry for not being of much help!

**Comment by duartmig** [comment] 2023-02-06 10:41
Thanks for your response! We will check with the browserstack team as well. Could it possibly be the case that playwright is too fast for the browserstack fixtures to be able to accept the http auth?In any case we will check with BrowserStack team as well to find a solution

**Comment by dgozman** [comment] 2023-02-06 19:37
> Could it possibly be the case that playwright is too fast for the browserstack fixtures to be able to accept the http auth?

That's unlikely, as long as BrowserStack uses public Playwright APIs.

Let me close this issue for now. If you get more information that indicates a Playwright bug, ideally with a repro we can run locally, please open a new issue and link to this one.

**Closed by dgozman** 2023-02-06 19:37 UTC
Labels: triaging
