### ISSUE TITLE
[Feature] Slider comparison when images do not have matching height

### ISSUE THREAD

**Issue by NVolcz** [microsoft/playwright#18936] opened 2022-11-19 21:56 UTC
The slider comparison is awesome for visual regression tests but the height of the websites often changes which causes the slider comparison to be disabled. Would it be possible to have it available even if the height are different? Maybe we could add an option to pad images that are different heights?

**Comment by dgozman** [comment] 2022-11-21 21:07
Seems to be a duplicate of #15802.

**Closed by dgozman** 2022-11-21 21:07 UTC

**Comment by NVolcz** [comment] 2022-11-22 07:09
I agree, it is a duplicate 👍
