### ISSUE TITLE
[Question] IS THERE DYNAMICALLY GENERATING TESTS OPTION?

### ISSUE THREAD

**Issue by vito2005** [microsoft/playwright#9916] opened 2021-11-01 08:48 UTC
Hi! Is there any way to generate tests dynamically? Like in mocha: 
https://mochajs.org/#dynamically-generating-tests

For example:

```
    test.describe.serial('Dynamic tests', () => {
	    const asyncData = test.preloadData()
    
	    test('Check testData', () => {
		    ok(asyncData?.length)
	    })
    
	    asyncData.forEach(item => {
    
		    test(`Test for ${item}`, async () => {
			    ....
		    })
	    })
    })
```

**Comment by mxschmitt** [comment] 2021-11-01 16:00
You can do it on test and on project level currently, see here: https://playwright.dev/docs/test-parameterize

Seems like a duplicate of https://github.com/microsoft/playwright/issues/7036 to me.

**Comment by vito2005** [comment] 2021-11-01 16:20
> You can do it on test and on project level currently, see here: https://playwright.dev/docs/test-parameterize
> 
> Seems like a duplicate of #7036 to me.

@mxschmitt , yes you are right. But my problem is that  I need to perform asynchronous operations before any of suites are run. My tests(count of tests) depend on data from the testing page.

**Comment by vito2005** [comment] 2021-11-02 08:14
Hi! I found the solution! 
`test.step() `helped.

There is an approximate example:
```

test.describe.serial('test suite', () => {
	let someDataForTest
	test.beforeAll(async ({ page }) => {
		.....
		await page.goto('https//yoursite')
		const resultHandle = await page.evaluateHandle(() => window.someData)
		 someDataForTest = await resultHandle.jsonValue()

	})

	test('checkdata', () => {
		ok(someDataForTest?.length)
	})

	test('Main test', async () => {

		for (let item of someDataForTest) {

			await test.step(`test step for ${item}`, async () => {
				.....
				ok(item)
			})

		}
	})
})
 
```

**Closed** 2021-11-02 08:14 UTC
Labels: triaging

**Comment by mbrodala** [comment] 2025-06-02 07:49
Unfortunately `test.step` has its downsides:

- no parallelism
- cannot retry a step, only the whole test
