### ISSUE TITLE
[BUG] local Chromium revision will be removed on Yarn after installing another dependency

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#1242] opened 2020-03-05 14:59 UTC
**Context:**
- Playwright Version: 0.11.1
- Operating System: macOS
- Extra: Yarn 1.22

**Code Snippet**

Minimal reproducible example in a new empty directory:

```bash
yarn init -y
yarn add playwright-chromium
ls -la node_modules/playwright-core/.local-chromium/mac-740847/chrome-mac
# Chromium revision is locally existing 🙂
yarn add -D @testing-library/react # example library
ls -la node_modules/playwright-core/.local-chromium/mac-740847/chrome-mac
# -> No such file or directory
# Chromium revision is not existing anymore.
```

Workaround

```bash
yarn install -f
```

**Describe the bug**

See the code above, for any questions feel free to ask. I'm experiencing this issue on various of repositories in which I'm working on locally in combination with Playwright.

**Comment by haikyuu** [comment] 2020-03-05 20:11
This is a duplicate of https://github.com/microsoft/playwright/issues/1085. It has been fixed but not yet published

**Comment by mxschmitt** [comment] 2020-03-05 20:20
Super, thanks!

**Closed** 2020-03-05 20:21 UTC
