### ISSUE TITLE
[Question]: Is it possible to minify playwright._impl._api_types.TimeoutError?

### ISSUE THREAD

**Issue by MaksimKravchuk** [microsoft/playwright#19067] opened 2022-11-23 11:41 UTC
### Your question

Playwright 1.28.0
Chrome 
Async mode

When I'm trying to click on the element not on the page (because of bug in our app), Playwright returns a 300+ lines error message. This error makes the report hardly understandable. Can I make this error smaller? Without information about all retries?
```

tests/test_directory/test_file.py:89: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pages/some_page.py:56: in some_method
    await self.locator.click()
/usr/local/lib/python3.10/site-packages/playwright/async_api/_generated.py:12214: in click
    await self._impl_obj.click(
/usr/local/lib/python3.10/site-packages/playwright/_impl/_locator.py:143: in click
    return await self._frame.click(self._selector, strict=True, **params)
/usr/local/lib/python3.10/site-packages/playwright/_impl/_frame.py:474: in click
    await self._channel.send("click", locals_to_params(locals()))
/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py:43: in send
    return await self._connection.wrap_api_call(
/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py:369: in wrap_api_call
    return await cb()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <playwright._impl._connection.Channel object at 0x7f9213f18130>
method = 'click'
params = {'selector': '[data-test="technology-name"]', 'strict': True}
return_as_dict = False

    async def inner_send(
        self, method: str, params: Optional[Dict], return_as_dict: bool
    ) -> Any:
        if params is None:
            params = {}
        callback = self._connection._send_message_to_server(self._guid, method, params)
        if self._connection._error:
            error = self._connection._error
            self._connection._error = None
            raise error
        done, _ = await asyncio.wait(
            {
                self._connection._transport.on_error_future,
                callback.future,
            },
            return_when=asyncio.FIRST_COMPLETED,
        )
        if not callback.future.done():
            callback.future.cancel()
>       result = next(iter(done)).result()
E       playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
E       =========================== logs ===========================
E       waiting for selector "[data-test="technology-name"]"
E         selector resolved to visible <h3d-card cardtype="link" iconname="technology" _ngcontent…>…</h3d-card>
E       attempting click action
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#1
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#2
E         waiting 20ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#3
E         waiting 100ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#4
E         waiting 100ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#5
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#6
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#7
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#8
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#9
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#10
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#11
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#12
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#13
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#14
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#15
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#16
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#17
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#18
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#19
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#20
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#21
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#22
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#23
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#24
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#25
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#26
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#27
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#28
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#29
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#30
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#31
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#32
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#33
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#34
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#35
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#36
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#37
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#38
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#39
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#40
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#41
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#42
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         <div _ngcontent-dih-c563="" class="wide-technology-se…>…</div> intercepts pointer events
E       retrying click action, attempt microsoft/playwright-python#43
E         waiting 500ms
E       ============================================================

/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py:78: TimeoutError
```

**Comment by aslushnikov** [comment] 2022-12-14 22:58
Dupe of https://github.com/microsoft/playwright/issues/19204

**Closed by aslushnikov** 2022-12-14 22:58 UTC
Labels: v1.29
