### ISSUE TITLE
[Bug]: Playwright codegen is not recording user actions performed on Freshservice Agent Portal.

### ISSUE THREAD

**Issue by ketanbharadwaj** [microsoft/playwright#31773] opened 2024-07-19 10:33 UTC
### Version

v1.45.1

### Steps to reproduce

1. Signup for a free Freshservice trial account https://www.freshworks.com/freshservice/signup/
2. Login to Freshservice Agent portal
3. Launch playwright codegen to record a test
4. Click gets disabled and user actions don't record.

### Expected behavior

I expect Playwright to record user actions performed on Freshservice's Agent portal.

### Actual behavior

Click doesn't work and test steps are not getting recorded. I don't see any errors in the recorder as well as in Browser console.
![image](https://github.com/user-attachments/assets/f36062b9-ea57-4e66-9d35-cb7f25340621)

### Additional context

I am using Chrome Browser for recording tests.

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.14 GB / 16.00 GB
  Binaries:
    Node: 18.18.2 - /usr/local/Cellar/fdk/64/custom_node_location/bin/node
    npm: 9.8.1 - /usr/local/Cellar/fdk/64/custom_node_location/bin/npm
  IDEs:
    VSCode: 1.91.1 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by dgozman** [comment] 2024-07-22 07:05
@ketanbharadwaj Unfortunately, I cannot reproduce, because I do not have an account on the Freshservice Agent portal, and I don't think I should sign up.

That said, `TypeError: serializedArgs.map` is not a function could mean that the page is messing with `Array.prototype.map` or something similar, and Playwright cannot call `.map()` when recording an action.

**Comment by ketanbharadwaj** [comment] 2024-07-22 12:23
> @ketanbharadwaj Unfortunately, I cannot reproduce, because I do not have an account on the Freshservice Agent portal, and I don't think I should sign up.
> 
> That said, `TypeError: serializedArgs.map` is not a function could mean that the page is messing with `Array.prototype.map` or something similar, and Playwright cannot call `.map()` when recording an action.

@dgozman Is there any workaround available to fix this issue?

**Comment by dgozman** [comment] 2024-07-22 12:36
> @dgozman Is there any workaround available to fix this issue?

I am not aware of any, sorry.

**Comment by pavelfeldman** [comment] 2024-07-28 21:10
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2024-07-28 21:10 UTC
