### ISSUE TITLE
[BUG] context.close() doesn't close stray onbeforeunload dialog in chromium

### ISSUE THREAD

**Issue by dwt** [microsoft/playwright#11581] opened 2022-01-21 19:12 UTC
**Context:**
- Playwright Version: 1.17.2
- Operating System: Mac
- Python version: Python 3.9.10
- Browser: All

**Code Snippet**

```python
from playwright.sync_api import sync_playwright

import pytest

HEADLESS = True
HEADLESS = False

WAIT = 5000

@pytest.fixture(scope='session', params=('firefox', 'chromium', 'webkit'))
def browser_vendor(request):
    yield request.param

@pytest.fixture(scope='session')
def browser(browser_vendor):
    with sync_playwright() as playwright:
        browser = getattr(playwright, browser_vendor)
        instance = browser.launch(headless=HEADLESS)
        yield instance
        instance.close()

@pytest.fixture
def context(browser):
    context = browser.new_context()
    yield context
    context.close()

@pytest.fixture
def page(context):
    page = context.new_page()
    page.set_default_timeout(WAIT)
    yield page
    page.close()

html = '''
<form>
    <label for=input_id id=label>input_label</label>
    <input id=input_id class=input_class name=input_name value=input_value 
        title=input_title placeholder=input_placeholder aria-label=input_aria_label>
    <div id=div_id>div_text</div>
</form>
'''

ask_to_leave_script = '''
// interestingly Firefox webdriver doesn't show thes dialogs at all, even though this code works in normal Firefox
window.addEventListener('beforeunload', function (e) {
    // Cancel the event
    e.preventDefault(); // mozilla will now always show dialog
    // Chrome requires returnValue to be set
    e.returnValue = 'Fnord';
});
'''

def test_before_unload(page):
    # delay unload
    page.set_content(html)

    page.evaluate(ask_to_leave_script)
    # page needs a change otherwise the onbeforeunload doesn't trigger
    page.fill('text=input_label', value='fnord')
    
    page.click("body")

    with page.expect_event("dialog") as dialog_info:
        page.close(run_before_unload=True)
    dialog = dialog_info.value
    assert dialog.type == "beforeunload"

    # with page.expect_event("close"):
    #     dialog.accept()
    
    context = page.context
    context.close()
    # browser = context.browser
    # browser.close()
```

**Describe the bug**

When dealing with stray leftover dialogs in (often background windows) Chromium doesn't behave the same as the other browsers, in that it hangs forever in `context.close()` while Safari and FF close the context just fine. 

It is my understanding that context.close() is what should give test isolation and is what should happen between tests. In any case, the three browsers should behave the same way.

The workaround of course, is to just close the dialog programmatically. But this is still annoying.

**Comment by aslushnikov** [comment] 2022-01-24 22:26
Indeed, I can repro this with Chromium in headful mode.

```js
// a.mjs
import { chromium } from '@playwright/test';

const browser = await chromium.launch({headless: false});
const context = await browser.newContext();
const page = await context.newPage();
await page.setContent(`
  <form>
      <label for=input_id id=label>input_label</label>
      <input id=input_id class=input_class name=input_name value=input_value
          title=input_title placeholder=input_placeholder aria-label=input_aria_label>
      <div id=div_id>div_text</div>
  </form>
`);
await page.evaluate(() => {
  // interestingly Firefox webdriver doesn't show thes dialogs at all, even though this code works in normal Firefox
  window.addEventListener('beforeunload', function (e) {
      // Cancel the event
      e.preventDefault(); // mozilla will now always show dialog
      // Chrome requires returnValue to be set
      e.returnValue = 'Fnord';
  });
});

await page.fill('text=input_label', 'fnord');
await page.click('body');
const [dialog] = await Promise.all([
  page.waitForEvent('dialog'),
  page.close({ runBeforeUnload: true }),
]);

await context.close();
await browser.close();
```

**Comment by aslushnikov** [comment] 2022-01-24 23:03
Seems to be a dupe of https://github.com/microsoft/playwright/issues/10476

**Closed** 2022-01-25 21:52 UTC
Labels: v1.19

**Comment by dwt** [comment] 2022-02-23 18:43
👍🎉
