### ISSUE TITLE
[Question] drag and drop

### ISSUE THREAD

**Issue by Whooolia** [microsoft/playwright#4317] opened 2020-11-03 02:52 UTC
what's the best way to test drag and drop with playwright?

I don't think that they have implemented `drag` functionality yet, so is there any workaround? 

any helps would be appreciated!

**Comment by extrasalt** [comment] 2020-11-03 06:32
You can use page.mouse.down(), .move() and .up() to simulate a drag drop

https://playwright.dev/#version=v1.5.2&path=docs%2Fapi.md&q=class-mouse

**Comment by mxschmitt** [comment] 2020-11-03 09:20
Closed as duplicate of #1094. It's not implemented yet but might be planned for the future since a few users requested it already. I saw an workaround implementation by CodeceptJS, maybe it works for your use case to extract it into your codebase: 

https://github.com/codeceptjs/CodeceptJS/blob/e815d82af028e904051b5b6c70873164e1df1bfd/lib/helper/Playwright.js#L2289-L2307e

**Closed by mxschmitt** 2020-11-03 09:20 UTC
