### ISSUE TITLE
followup to #16982

### ISSUE THREAD

**Issue by lrstanley** [microsoft/playwright#17028] opened 2022-09-02 02:37 UTC
> @lrstanley we don't monitor closed issues, please file a separate issue with a repro repo and we are happy to take a look!
> 
> _Originally posted by @mxschmitt in https://github.com/microsoft/playwright/issues/16982#issuecomment-1234687679_

Not sure why this was immediately dismissed, and why I need to submit a new issue to get clarification on a message. I wasn't saying the issue was still occurring, I was simply asking for clarification why the issue was immediately closed, as the provided reason wasn't clear to me. Is there a reason why I have to file a separate issue to get clarification on a response that was posted within the same 24h?

**Comment by pavelfeldman** [comment] 2022-09-02 13:55
That's our triaging process. We manage dozens of incoming issues a day and have a triaging rotations to process the incoming feedback flow. When we close an issue, we ask our users to verify it, and if the problem is still happening, to file a new issue.

**Comment by pavelfeldman** [comment] 2022-09-02 18:22
Closing as non-actionable.

**Closed by pavelfeldman** 2022-09-02 18:22 UTC

**Comment by lrstanley** [comment] 2022-09-02 23:58
1. Close issue with very unclear reasons.
2. When asked for clarification, close issue, saying to open a new issue, rather than just clarifying (what was mentioned isn't part of the "triaging" process, as there wasn't anything to "triage").
3. Open a new issue asking for clarification, as directed.
4. Close issue without clarifying, again, suggesting that the directions provided are incorrect.

Trying to be understandable, but... am I just missing something obvious here? Am I not allowed to ask for clarification? This whole thing seems rather obtuse when two or three sentences could clarify things.

I still have no idea what is being said here despite reading it 20 times:

> New VSCode introduced a smartness that runs the project selected file belongs to even if this project is not selected to be a part of the active configuration in the Run/Debug dropdown.
