### ISSUE TITLE
[BUG] page.on('request') is not capturing data URI

### ISSUE THREAD

**Issue by sohaib17** [microsoft/playwright#7280] opened 2021-06-23 10:53 UTC
**Context:**

- Playwright Version: playwright-1.12.1
- Operating System: Ubuntu 18.04
- Python Version: 3.8
- Browser: chromium v888113

**Code Snippet**

```
import os
import asyncio
from playwright.async_api import async_playwright

os.environ['PLAYWRIGHT_BROWSERS_PATH'] = '/local/browsers'


async def request(request):
    print('request %s' % request.url)


async def coroutine():
    async with async_playwright() as playwright:
        # Launch browser
        binary = playwright.chromium
        browser = await binary.launch(headless=True)
        page = await browser.new_page()
        page.on('request', request)
        await page.goto("file:///home/sohaib/demo-data-uri.html")
        await browser.close()


asyncio.run(coroutine())
```

**Describe the bug**

While working with playwright we noticed that `page.on('request')` is not being emitted for data URIs. Upon enabling `*protocol*` logs, we can see that CDP is sending data URI event but playwright is not capturing it. How can we capture these data URI requests?

Demo file used for above script is also attached. When we rendered this file in puppeteer, it captured the data URI successfully.

Debug logs with `*protocol*` are also attached:

```
  pw:protocol ◀ RECV {"method":"Page.frameNavigated","params":{"frame":{"id":"D46B478D9A737B67F89574F659AF8C39","loaderId":"C5D6EFE0B08B719268941788F66C6B3D","url":"file:///home/sohaib/demo-data-uri.html","domainAndRegistry":"","securityOrigin":"file://","mimeType":"text/html","adFrameType":"none","secureContextType":"Secure","crossOriginIsolatedContextType":"NotIsolated","gatedAPIFeatures":[]},"type":"Navigation"},"sessionId":"36FE82049E809A53923093287D10AAB1"} +0ms
  pw:protocol ◀ RECV {"method":"Runtime.executionContextCreated","params":{"context":{"id":3,"origin":"file://","name":"","uniqueId":"-1656522015342016875.8306272802146753124","auxData":{"isDefault":true,"type":"default","frameId":"D46B478D9A737B67F89574F659AF8C39"}}},"sessionId":"36FE82049E809A53923093287D10AAB1"} +1ms
  pw:protocol ◀ RECV {"method":"Runtime.executionContextCreated","params":{"context":{"id":4,"origin":"://","name":"__playwright_utility_world__","uniqueId":"-4018626186181131788.-2675179064777549429","auxData":{"isDefault":false,"type":"isolated","frameId":"D46B478D9A737B67F89574F659AF8C39"}}},"sessionId":"36FE82049E809A53923093287D10AAB1"} +0ms
  pw:protocol ◀ RECV {"method":"Network.dataReceived","params":{"requestId":"C5D6EFE0B08B719268941788F66C6B3D","timestamp":19529.841777,"dataLength":19387,"encodedDataLength":0},"sessionId":"36FE82049E809A53923093287D10AAB1"} +0ms
  pw:protocol ◀ RECV {"method":"Network.loadingFinished","params":{"requestId":"C5D6EFE0B08B719268941788F66C6B3D","timestamp":19529.836115,"encodedDataLength":19387,"shouldReportCorbBlocking":false},"sessionId":"36FE82049E809A53923093287D10AAB1"} +0ms
  pw:protocol ◀ RECV {"method":"Network.requestWillBeSent","params":{"requestId":"26373.2","loaderId":"C5D6EFE0B08B719268941788F66C6B3D","documentURL":"file:///home/sohaib/demo-data-uri.html","request":{"url":"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/4gxYSUNDX1BST0ZJTEUAAQEAAAxITGlubwIQAABtbnRyUkdCIFhZWiAHzgACAAkABgAxAABhY3NwTVNGVAAAAABJRUMgc1JHQgAAAAAAAAAAAQAAAAAA9tYAAQAAAADTLUhQICAAAAAAAAAAAAA
```
[demo-data-uri.txt](https://github.com/microsoft/playwright-python/files/6701311/demo-data-uri.txt)
[debug-logs.txt](https://github.com/microsoft/playwright-python/files/6701313/debug-logs.txt)

**Comment by aslushnikov** [comment] 2021-06-24 01:30
> While working with playwright we noticed that page.on('request') is not being emitted for data URIs.

@sohaib17 that's intentional; data URLs do not hit network so we don't show them. 

> Upon enabling *protocol* logs, we can see that CDP is sending data URI event but playwright is not capturing it.

Technically, while CDP does expose data URL requests, their treatment is still very special in CDP, e.g. it's not possible to intercept them. 

Would you mind sharing why do you want to trace data URLs?

**Comment by sohaib17** [comment] 2021-06-24 07:35
> Technically, while CDP does expose data URL requests, their treatment is still very special in CDP, e.g. it's not possible to intercept them.

Yes, we noticed that `Fetch.enable` with `requestStage` set to `Request` and `Response` was not capturing it either. Any idea how we can do it through CDP if playwright is not going to show them? We just want to capture them, not mutate them in any way.

> Would you mind sharing why do you want to trace data URLs?

Part of our research deals with analyzing requests originating from web pages to detect Phishing attacks. In some cases, attackers hide brand logos and other information in data URIs so capturing them separately allows us to better analyze them.

**Comment by mxschmitt** [comment] 2021-07-07 11:44
Closing as part of the triage since this is currently working as intended. If you want to interact with CDP directly, you can use a CDPSession, see [here](https://playwright.dev/docs/api/class-cdpsession).

For other requests, feel free to open a feature request.

**Closed by mxschmitt** 2021-07-07 11:44 UTC
Labels: triaging
