### ISSUE TITLE
[BUG] screenshot() captures blank, white image after 'Site can't be reached' error in Chromium

### ISSUE THREAD

**Issue by c-wilcox** [microsoft/playwright#23632] opened 2023-06-10 00:34 UTC
### System info
- Playwright Version: 1.35.0
- Operating System: Windows 10 (Windows NT 6.2)
- Browser: Chromium

### Source code
<pre>
    async executeStrategy() {
        try {
            const fedAdminHomePage = new FedAdminHomePage(this.page, this.siteUrl);
            await fedAdminHomePage.goto();  //IF THIS FAILS DUE TO BAD URL, PW Captures blank screen in Chromium; FireFox works fine
            
            await fedAdminHomePage.IAmAFedAdminHomePage();
            this.logger.passed(`${this.logger.buildPassFailMessage(this.linkText, this.siteUrl, this.getName(), this.viaPortal)}`);
        }
        catch (error) {
            this.logger.details(`${this.logger.buildSiteDownMessage(this.linkText, this.siteUrl, this.getName(), this.viaPortal, error.message)}`);
            this.logger.failed(`${this.logger.buildPassFailMessage(this.linkText, this.siteUrl, this.getName(), this.viaPortal)}`);
            await this.page.screenshot({ path: `./ScreenShots/${this.linkText}.png`, fullPage: true });  //BLANK PAGE captured in Chromium
        }
    }
</pre>

### Summary
- **Running headed Chromium via VS Code Debugger it works fine**
- Running headless **Chromium** from Git-Bash Command Line, PW fails to capture the browser contents; **just a white, blank image**
- Running headless **FireFox** from Git-Bash Command Line **works fine**

![image](https://github.com/microsoft/playwright/assets/50146974/0c424692-73d7-4b98-868d-d3353673d1f7)

**Comment by c-wilcox** [comment] 2023-06-10 10:46
After further tests and experiments I have come to the conclusion that failures to capture browser screen contents do not discriminate between chromium and firefox nor between headed and headless.

I suspect that **_something is failing too fast on DNS errors_** and portal.goto() is returning before the DNS error content can get in to a readable state.

**Comment by yury-s** [comment] 2023-06-13 00:45
Looks like there is a DNS failure which causes the navigation failure. Closing as this is not a bug in playwright and we can't do much about it. Feel free to file another bug with a self-contained repro if you believe the problem is caused by playwright.

**Closed by yury-s** 2023-06-13 00:45 UTC
Labels: triaging
