### ISSUE TITLE
[BUG] Trace viewer filmstrip is confused/confusing when page was created in beforeAll

### ISSUE THREAD

**Issue by eveltman-twinfield** [microsoft/playwright#10938] opened 2021-12-15 13:47 UTC
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows
- Node.js version: 17.0.1
- Browser: Chromium

**Describe the bug**
A first step for migrating our Protractor tests most likely will be to migrate them 1:1.
Lengthy tests depending on the previous tests, also doing UI-based login and some other setup steps in beforeAll blocks. So not nearly as isolated as we'd like.

I noticed the tracing behaves a bit odd for when the [page was created in the beforeAll like this](https://playwright.dev/docs/test-auth#reuse-the-signed-in-page-in-multiple-tests).

I've attached [playwright-beforeall-trace-strangeness.zip](https://github.com/microsoft/playwright/files/7719514/playwright-beforeall-trace-strangeness.zip) with source code and html report with traces.

When viewing the report and navigating to the traces:
* The filmstrips for both test 1 and test 2 are mostly dominated by the beforeAll step.
* The first action of the actual test (page.goto) occupies a large part of the timeline bar. 
But the filmstrip for the same time period shows only screenshots of the beforeAll step.
* Further to the right, the timeline bars are also out of sync with the film strip.
* The actions pane is showing only the actual test actions (nothing from the beforeAll). 

(Hard to describe, but hope it's clear like this)

My preferred fix would be one of:
* beforeAll and first test combined in one trace, but with also the beforeAll actions shown, and timeline bars and filmstrip properly aligned/in sync.
* a separate trace for beforeAll (ideally also with a separate beforeAll item in the report).

**Comment by dgozman** [comment] 2021-12-15 18:28
Thank you for the issue, you explained everything very well! The attached zip helps as well, and the problem is clear.

- The issue with screenshots from `beforeAll` messing up with the trace should be fixed by #10862, and will go into the next release.

- #10440 tracks the "separate trace for beforeAll" feature. We plan to address it in the next release as well.

Given the above, I'll close this issue as a duplicate. Thanks for filing!

**Closed by dgozman** 2021-12-15 18:29 UTC
Labels: v1.18
