### ISSUE TITLE
[BUG] The list of tests is not sorted according to the selected category: passed, failed, flaky

### ISSUE THREAD

**Issue by sqanatoliy** [microsoft/playwright#10672] opened 2021-12-02 15:19 UTC
**Context:**
- Playwright Version: [1.17.0-rc1]
- Operating System: [Windows 11]
- Node.js version: [v14.17.5]
- Browser: [ All]
- Extra: [the same problems I get using Gitlab CI]

The list of tests is not sorted according to the selected category: passed, failed, flaky
To see the tests of the selected category, you need to reload the page

https://user-images.githubusercontent.com/22426754/144450389-897b0b9b-7268-4351-ae52-4e23b4fbbd44.mp4

**Comment by pavelfeldman** [comment] 2021-12-02 17:13
I can't repro it, could you open DevTools and paste errors from it here?

**Comment by dgozman** [comment] 2021-12-08 19:27
Closing since we cannot reproduce the issue. Please file a new issue with a repro if you have one.

**Closed by dgozman** 2021-12-08 19:27 UTC
Labels: triaging
