### ISSUE TITLE
[BUG] Running Playwright on Firefox inside a Docker container always hangs forever

### ISSUE THREAD

**Issue by eduter** [microsoft/playwright#16491] opened 2022-08-12 09:08 UTC
**Context:**
- Playwright Version: 1.25.0 (but I tried on 1.24.2 and I get the same behavior)
- Operating System: Ubuntu inside WSL 2 (Win 10)
- Node.js version: v16.16.0
- Browser: Firefox

**Code Snippet**

I've created a repo for reproducing the bug:
https://github.com/eduter/playwright-firefox-docker

**Describe the bug**

It starts the container and tries to run the example test on Firefox, but then just hangs forever like this:
```
playwright-ff  | > playwright test example --project=firefox
playwright-ff  |
playwright-ff  | 
playwright-ff  | Running 1 test using 1 worker
playwright-ff  |
                 [1/1] [firefox] › example.spec.ts:3:1 › homepage has Playwright
 in title and get started link linking to the intro page
```

**Comment by rwoll** [comment] 2022-08-12 17:14
Thanks for the repro. I'm able to also reproduce on Docker for Linux in a default GitHub Codespace.

I cleaned up some of the Docker bits in the repro, and the issue looks to be narrowed down to permission-related when using a volume mount.

With `DEBUG` set to `pw:browser`, the relevant error looks to be: `pw:browser [pid=256][err] Error: Access was denied while trying to open files in your profile directory. `

This only occurs if the commented out volume mount is used (https://github.com/rwoll/user-repro-playwright-firefox-docker)

@aslushnikov Do you know what constraints there are on using docker volume mounts and FF?

/cc @eatonjl in case this ends up being helpful in your investigation of https://github.com/microsoft/playwright/issues/16099

**Comment by mxschmitt** [comment] 2022-08-12 17:29
Assigning to 1.26 so we file it upstream or look into it.

**Comment by hex0cter** [comment] 2022-10-31 07:42
I got it on `mcr.microsoft.com/playwright:v1.25.0-focal` too. Is it still a problem on the latest version?

**Comment by aslushnikov** [comment] 2022-11-02 20:19
@hex0cter the issue with firefox misbehaving with mounts in docker should be filed upstream to Firefox; I'll appreciate if someone will build a small repro and file it to Mozilla folks for them to take a look.

**Comment by stevebaxter** [comment] 2023-01-16 18:10
Ah, I suspect it's the same as this issue #13716. It looks like Jenkins, Docker and FireFox really can't mix.

**Comment by aslushnikov** [comment] 2023-01-18 04:30
This should be reported upstream to Firefox bug tracker. Closing since there's no action item for Playwright team here.

**Closed by aslushnikov** 2023-01-18 04:30 UTC
Labels: P3-collecting-feedback, browser-firefox

**Comment by stevebaxter** [comment] 2023-01-18 09:23
@aslushnikov - is there an argument to set up the Playwright Docker image to make sure this works though?

**Comment by andrehil** [comment] 2023-08-10 21:06
@aslushnikov I'm having the same issue when running v1.36.2-focal in OCP.
I agree with @stevebaxter  that it should work out of the box.
