### ISSUE TITLE
[Bug]: error while running ci

### ISSUE THREAD

**Issue by suedar** [microsoft/playwright#7812] opened 2021-07-23 03:31 UTC
### Playwright version

1.13.0 

### Operating system

MacOS, Linux

### What browsers are you seeing the problem on?

Chromium, Firefox

### What happened? / Describe the bug

Here is my gitlab-ci.yml
``` yml
build:
  stage: build
  image: mcr.microsoft.com/playwright:focal
  cache:
    paths: 
      - node_modules
  script:
    - /etc/init.d/dbus start
    - node -v & npm -v
    - yarn install --force
    - npx playwright install chrome
    - yarn ci-test
```

This error exist whit `yarn install --force`
<img width="1060" alt="截屏2021-07-23 上午11 25 58" src="https://user-images.githubusercontent.com/18492953/126734427-74796d42-37cd-4a77-9082-7f1b4e6eaf4c.png">

**Comment by pavelfeldman** [comment] 2021-07-23 03:51
Looks like Azure outage, does it reproduce?

**Comment by dgozman** [comment] 2021-07-27 04:19
Closing because this look like a network outage. If you believe there is another cause, please comment and we'll reopen.

**Closed by dgozman** 2021-07-27 04:19 UTC
Labels: triaging
