### ISSUE TITLE
[BUG] Unable to launch browser with channel "chrome" inside docker even installed chrome

### ISSUE THREAD

**Issue by luckhiem** [microsoft/playwright#17395] opened 2022-09-16 13:39 UTC
**Context:**
- Playwright Version: `^1.25.0`
- Operating System: Docker
- Node.js version: [e.g. 12.22, 14.6]
- Browser: Chrome

**Code Snippet**
```javascript
const { devices, chromium } = require('playwright');
const iPhone = devices['iPhone 11 Pro'];

(async () => {
    const browser = await chromium.launch({
        channel: 'chrome',
    });
    const context = await browser.newContext({
        ...iPhone,
    });
    const page = await context.newPage();
    console.log(page)
})();
```

```javascript
# Get the base image of Node version 16
FROM node:16

# Get the latest version of Playwright
FROM mcr.microsoft.com/playwright:latest
 
# Set the work directory for the application
WORKDIR /app
 
# Set the environment path to node_modules/.bin
ENV PATH /app/node_modules/.bin:$PATH

# COPY the needed files to the app folder in Docker image
COPY . /app/

RUN apt-get update && apt-get install -y \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libwayland-client0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxkbcommon0 \
    libxrandr2 \
    xdg-utils \
    libu2f-udev \
    libvulkan1

RUN apt install -y wget unzip
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y tzdata

# Chrome instalation 
RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb
RUN apt -f install -y
RUN echo "Chrome: " && google-chrome --version

# Install the dependencies in Node environment
RUN npm install
```

**Describe the bug**
Unable to run browser channel "chrome" in docker even installed chrome
```
VError: a BeforeAll hook errored, process exiting: src/support/Hooks.ts:9: browserType.launch: Browser closed.
==================== Browser output: ====================
<launching> /opt/google/chrome/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --disable-web-security --allow-insecure-localhost --ignore-certificate-errors --no-user-gesture-required --user-data-dir=/tmp/playwright_chromiumdev_profile-8zABfN --remote-debugging-pipe --no-startup-window
<launched> pid=2561
[pid=2561][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[pid=2561][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[pid=2561][err] [0916/133515.464284:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Function not implemented (38)
[pid=2561][err] Assertion failed: p_rcu_reader->depth != 0 (/qemu/include/qemu/rcu.h: rcu_read_unlock: 101)
=========================== logs ===========================
<launching> /opt/google/chrome/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --disable-web-security --allow-insecure-localhost --ignore-certificate-errors --no-user-gesture-required --user-data-dir=/tmp/playwright_chromiumdev_profile-8zABfN --remote-debugging-pipe --no-startup-window
<launched> pid=2561
[pid=2561][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[pid=2561][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[pid=2561][err] [0916/133515.464284:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Function not implemented (38)
[pid=2561][err] Assertion failed: p_rcu_reader->depth != 0 (/qemu/include/qemu/rcu.h: rcu_read_unlock: 101)
============================================================
    at Runtime.runTestRunHooks (/work/node_modules/@cucumber/cucumber/src/runtime/run_test_run_hooks.ts:32:19)
    at Runtime.start (/work/node_modules/@cucumber/cucumber/src/runtime/index.ts:108:5)
    at runCucumber (/work/node_modules/@cucumber/cucumber/src/api/run_cucumber.ts:118:19)
    at Cli.run (/work/node_modules/@cucumber/cucumber/src/cli/index.ts:76:25)
    at Object.run [as default] (/work/node_modules/@cucumber/cucumber/src/cli/run.ts:38:14)
caused by: browserType.launch: Browser closed.
==================== Browser output: ====================
<launching> /opt/google/chrome/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --disable-web-security --allow-insecure-localhost --ignore-certificate-errors --no-user-gesture-required --user-data-dir=/tmp/playwright_chromiumdev_profile-8zABfN --remote-debugging-pipe --no-startup-window
<launched> pid=2561
[pid=2561][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[pid=2561][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[pid=2561][err] [0916/133515.464284:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Function not implemented (38)
[pid=2561][err] Assertion failed: p_rcu_reader->depth != 0 (/qemu/include/qemu/rcu.h: rcu_read_unlock: 101)
=========================== logs ===========================
<launching> /opt/google/chrome/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --disable-web-security --allow-insecure-localhost --ignore-certificate-errors --no-user-gesture-required --user-data-dir=/tmp/playwright_chromiumdev_profile-8zABfN --remote-debugging-pipe --no-startup-window
<launched> pid=2561
[pid=2561][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[pid=2561][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[pid=2561][err] [0916/133515.464284:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Function not implemented (38)
[pid=2561][err] Assertion failed: p_rcu_reader->depth != 0 (/qemu/include/qemu/rcu.h: rcu_read_unlock: 101)
============================================================
    at /work/src/support/Hooks.ts:26:56
    at /work/src/support/Hooks.ts:8:71
    at __awaiter (/work/src/support/Hooks.ts:4:12)
    at /work/src/support/Hooks.ts:17:12
```
Add any other details about the problem here.
<img width="1311" alt="Screen Shot 2022-09-16 at 20 49 37" src="https://user-images.githubusercontent.com/41050460/190654481-c97756e1-8813-408b-9c71-6f87b22d1b6a.png">

**Comment by mxschmitt** [comment] 2022-09-19 10:16
The cause for that is that you try to emulate Google Chrome amd64 with Docker on your arm64 system. See here: https://github.com/puppeteer/puppeteer/issues/7752#issuecomment-1197826110

Since Google Chrome is only available for amd64, we recommend using Chromium since its available for arm64 as well.

Closing since this is not a Playwright issue and more a Docker setup issue.

**Closed by mxschmitt** 2022-09-19 10:16 UTC

**Comment by zhoukekestar** [comment] 2025-04-01 06:43
Same issue here when using docker on M1 Mac. I use colima to run docker instance, and the command `colima start colima-x86 --arch x86_64` solved my issues.
