### ISSUE TITLE
[BUG] Trace viewer crashed after select a source file

### ISSUE THREAD

**Issue by Ellery0924** [microsoft/playwright#21023] opened 2023-02-20 06:30 UTC
**Context:**
- Playwright Version: 1.30.0
- Operating System: Windows 11
- Node.js version: 16.15.0
- Browser: Chrome
- Extra: N/A

Hello

I am trying to onboard playwright to our E2E automation test framework. I tried the trace viewer today with "sources=true" and successfully generated a "trace.zip" in my local. However the trace viewer crashed for multiple times while selecting different source files. In addition, I also found some style issues in the source tab.

Below is the trace.zip I was viewing
[trace.zip](https://github.com/microsoft/playwright/files/10780234/trace.zip)

Repro steps:
1. Open the trace file via `playwright show-trace ./trace.zip`.
2. Select a step in the left panel, then click "Source" tab:
![image](https://user-images.githubusercontent.com/9380692/220029022-3f9df59f-4a1a-4ec7-bf7a-665f8439aaf4.png)
You may find there were style issues here:
![image](https://user-images.githubusercontent.com/9380692/220029164-f3d2dbe7-40ce-4128-bd75-69185cb52564.png)
3. Switch selected files in the call stack:
![image](https://user-images.githubusercontent.com/9380692/220029406-bda86e73-d3c9-4fab-a96f-4840596a1ec3.png)
![image](https://user-images.githubusercontent.com/9380692/220029450-c078a44f-981c-41c0-b239-e45b4ae51525.png)
4. You will find the page goes blank, and I can see errors in the console like this:
![image](https://user-images.githubusercontent.com/9380692/220029580-3cf74fba-2122-4f1c-b231-7a045bea6508.png)

**Comment by mxschmitt** [comment] 2023-02-21 11:02
I can repro.

**Comment by mxschmitt** [comment] 2023-02-28 10:47
Discussed offline, next steps are trying it out on tip-of-tree, since giving access / creating small repro is not feasible. Based on the new trace we'll then try again to create a test out of it.

**Comment by mxschmitt** [comment] 2023-03-06 20:50
@Ellery0924 can you try testing it out with our [canary release](https://playwright.dev/docs/canary-releases)?

If so, then please provide a new trace file or a smaller minimal reproducible, otherwise we can't act on it, thanks!

**Comment by mxschmitt** [comment] 2023-03-08 08:12
User reported that the issue is fixed on Canary.

**Closed by mxschmitt** 2023-03-08 08:12 UTC
Labels: v1.32
