### ISSUE TITLE
[Bug]: Open chrome without having been configured 'chrome://flags/#unsafely-treat-insecure-origin-as-secure' by playwright

### ISSUE THREAD

**Issue by CoolXi** [microsoft/playwright#31230] opened 2024-06-06 12:51 UTC
### Version

1.44.0

### Steps to reproduce

1. I have configured chrome://flags/#unsafely-treat-insecure-origin-as-secure on chrome and added http://modev-k3cloud:8000.
2. I can see this configuration by manually opening chrome.
3. But the browser I run through playwright is empty.
4. Here's my code:
`
from playwright.sync_api import sync_playwright

def upload_license_files():
    play = sync_playwright().start()
    browser = play.chromium.launch(headless=False, channel='chrome', args=['--start-maximized'], slow_mo=1000)
    context = browser.new_context(no_viewport=True)
    page = context.new_page()
    page.set_default_timeout(10000)

    page.goto('http://modev-k3cloud:8000')

upload_license_files()
`

### Expected behavior

playwright runs through a browser whose chrome://flags/# unsafe-treat-insecure -origin-as-secure value is http://modev-k3cloud:8000

### Actual behavior

For browsers running through playwright, its chrome://flags/# unsafe-treat-insecure -origin-as-secure value is empty

### Additional context

![playwright](https://github.com/microsoft/playwright-python/assets/62935521/7b7d525d-b17b-4970-a261-8121ad39f3d9)

### Environment

```Text
- Operating System: [windows 10]
- CPU: [arm64]
- Browser: [Chromium]
- Python Version: [3.9.8]
- Other info:
```

**Comment by yury-s** [comment] 2024-06-10 22:47
It probably has something to do with enterprise browser [policy](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge) on your machine. I can't reproduce it locally, the following code passes just fine.

```js
const { chromium, expect } = require('@playwright/test');
 
(async () => {
  const browser = await chromium.launchPersistentContext('./chromium-data', {headless: false, channel: 'chrome'});
  const page = await browser.newPage();
  await page.goto('chrome://flags/#unsafely-treat-insecure-origin-as-secure');
  await expect(await page.getByRole('textbox', { name: 'Insecure origins treated as' }).evaluate(e => e.value)).toBe('http://modev-k3cloud:8000');
  await browser.close();
})();

```

**Comment by yury-s** [comment] 2024-06-17 17:47
Closing per the response above, we cannot take any actions on our side based on the provided information and without a reproduction. Feel free to open a new issue if you discover additional details that could help us to reproduce the problem.

**Closed by yury-s** 2024-06-17 17:47 UTC
