### ISSUE TITLE
[Question] - remove certicate popup

### ISSUE THREAD

**Issue by BredSt** [microsoft/playwright#3350] opened 2020-08-07 21:28 UTC
I use the following [blog][1] to use the playwright lib. 
my app use login page, using the headless false 
when the chromium  is opened it ask to provide **certificate  popup** (my user) and when I click on cancel it open the user password screen and the test proceed and pass, any idea how to avoid the certificate popup?
as it sometimes ask for it and sometimes not which a bit tricky
and this is my certificate which should be used on test.

    (async () => {
      const browser = await chromium.launch({ headless: false });
      const page = await browser.newPage();
      await page.goto('https://app.com');
      await page.fill('input[type="text"]', 'user@test.com');
      await page.fill('input[type="password"]', 'Abcd1234!');
      page.click('button[id="logOnFormSubmit"]');
    }
    )();

additional  question, in case I want to run this test for 10 users, is there an helpers which can help 
or just to wrap it in async function and pass everytime diffrent user 

![image](https://user-images.githubusercontent.com/69369419/89709635-ca88d980-d987-11ea-9795-22b4553822ed.png)

[![enter image description here][2]][2]

  [1]: https://www.martinmcgee.dev/starting-microsoft-playwright/

**Comment by BredSt** [comment] 2020-08-11 14:11
HI, any idea how it can be resolved ?

**Comment by mxschmitt** [comment] 2020-08-11 15:41
Probably a duplicate of #1799 not implemented so far.

**Comment by aslushnikov** [comment] 2020-08-21 08:22
Thanks Max; duping to #1799

**Closed by aslushnikov** 2020-08-21 08:22 UTC
