### ISSUE TITLE
[Question]Many ldd processes are started by @playwright/test

### ISSUE THREAD

**Issue by chenshy39** [microsoft/playwright#14128] opened 2022-05-12 15:57 UTC
Context:

Playwright Version: playwright@1.19.1
Operating System: Ubuntu 18
Node.js version: 16.14.0
Browser: chromium

Command: `npx playright test --workers 9`

Use `top`，show:
```
top - 15:56:11 up 43 days,  5:49,  0 users,  load average: 10.59, 26.44, 34.85
Tasks:  40 total,  13 running,  16 sleeping,   0 stopped,  11 zombie
%Cpu(s): 44.5 us,  1.6 sy,  0.0 ni, 53.7 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
MiB Mem : 257348.7 total, 207679.7 free,   9938.9 used,  39730.2 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used. 244057.7 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND  
 18738 root      20   0   10.7g  93724  33236 R 100.3   0.0   0:05.52 node     
  18715 root      20   0   10.7g  93672  33212 R  99.7   0.0   0:05.42 node     
  18670 root      20   0   10.7g  84964  33120 R  98.7   0.0   0:05.53 node     
  17708 root      20   0   10.9g  98748  35444 R  97.7   0.0   0:31.12 node     
  18589 root      20   0   14440  12308   1452 R  97.3   0.0   0:12.44 ldd      
  18631 root      20   0   14448  12268   1412 R  95.7   0.0   0:11.39 ldd      
  18782 root      20   0   14176  13284   2788 S  67.1   0.0   0:02.02 ldd      
  18758 root      20   0   14176  13308   2812 S  61.1   0.0   0:02.80 ldd      
  18786 root      20   0   14180  11936   1388 R  52.2   0.0   0:01.57 ldd      
  18760 root      20   0  604248  56288  31676 S  48.2   0.0   0:01.82 node     
  18749 root      20   0   14176  13204   2708 S  44.2   0.0   0:03.34 ldd      
  18789 root      20   0   14180  12000   1448 R  34.9   0.0   0:01.05 ldd      
  18790 root      20   0  598468  50544  31264 R  33.6   0.0   0:01.01 node     
  17761 root      20   0   10.7g  85332  33208 S  31.9   0.0   0:55.87 node     
  18798 root      20   0   12608  11428   2680 R  14.0   0.0   0:00.42 ldd      
  18799 root      20   0   12612  11436   2688 R  13.3   0.0   0:00.40 ldd      
  18802 root      20   0   14180  12056   1504 R   2.0   0.0   0:00.06 ldd  
```

It seems the `ldd` command cause the most of %CPU, but Why?

**Comment by chenshy39** [comment] 2022-05-14 04:08
Any answers? 😐

**Comment by chenshy39** [comment] 2022-05-14 04:43
More Infomations:
only use one worker to start: `npx playwright test --workers 1`, get about 4or5 ldd to check the dependencies of chrome
```
# ps x
    PID TTY      STAT   TIME COMMAND
      1 ?        Ss     0:01 /bin/sh -c npm start
      7 ?        Sl     0:04 npm start
     18 ?        S      0:00 sh -c mug start --title=mug-server-fe-test-runner -
     19 ?        Sl     0:08 node /appops/node_modules/.bin/mug start --title=mu
     30 ?        Sl     0:27 node --no-deprecation --trace-warnings --require /a
     37 ?        Sl     0:15 /usr/bin/node --no-deprecation --trace-warnings --r
     48 ?        Sl     1:14 /usr/bin/node --no-deprecation --trace-warnings --r
  11540 pts/0    Ss+    0:01 sh
  11546 pts/1    Ss     0:01 sh
  11561 pts/1    S+     0:00 tail -f fe-test-runner.log
  11602 pts/2    Ss+    0:01 sh
  11798 pts/3    Ss+    0:01 sh
  12322 pts/4    Ss+    0:02 sh
  13655 pts/5    Ss     0:02 sh
  13741 pts/5    S+     0:23 top
  16992 pts/6    Ss     0:01 sh
  17015 pts/7    Ss     0:01 sh
  18259 pts/8    Ss+    0:01 sh
  18714 pts/6    Sl+    0:04 npm exec playwright test
  18725 pts/6    S+     0:00 sh -c playwright "test"
  18726 pts/6    Sl+    0:03 node /appops/node_modules/.bin/playwright test
  18738 pts/6    Rl+    0:16 /usr/bin/node /appops/node_modules/@playwright/test
  18749 pts/6    Z+     0:01 [ldd] <defunct>
  18754 pts/6    Z+     0:01 [ldd] <defunct>
  18760 pts/6    Z+     0:01 [ldd] <defunct>
  18765 pts/6    Z+     0:01 [ldd] <defunct>
  18770 pts/6    Z+     0:01 [ldd] <defunct>
  18774 pts/6    S+     0:01 /bin/bash /usr/bin/ldd /ms-playwright/chromium-9654
  18780 pts/6    Z+     0:01 [ldd] <defunct>
  18782 pts/6    S+     0:00 /bin/bash /usr/bin/ldd /ms-playwright/chromium-9654
  18783 pts/6    R+     0:01 /bin/bash /usr/bin/ldd /ms-playwright/chromium-9654
  18787 pts/6    S+     0:01 /bin/bash /usr/bin/ldd /ms-playwright/chromium-9654
  18791 pts/6    R+     0:00 /bin/bash /usr/bin/ldd /ms-playwright/chromium-9654
  18792 pts/6    R+     0:00 /bin/bash /usr/bin/ldd /ms-playwright/chromium-9654
  18793 pts/7    R+     0:00 ps x
```

**Comment by mxschmitt** [comment] 2022-05-15 10:12
Do you launch the browser manually or how does the test look like?

**Comment by chenshy39** [comment] 2022-05-15 13:00
> Do you launch the browser manually  

Nope. I lanuch my test by `npx playwright test`, and I found they are Timeout in causal(BeforeAll hooks state). use the `top` command to figure out why, then I found there are a lot of `ldd` command start by playwright test which occupied the most of CPU.
There is casualty Timeout error log:
```
Timeout of 60000ms exceeded in beforeAll hook.

    at /appops/testFiles/record-1489/test-607.spec.mjs:35:6
``` 
There is the simplest test file can repro:
```
import { test, expect } from '@playwright/test';

test.use({
    baseURL: 'https://mywebsitehost.com/musician/artist/manage/album/nalbum/songupload',
    storageState: {
        cookies: [],
        origins: [
            {
                origin: "",
                localStorage: [],
            },
        ],
    },
    viewport: {
        width: 1560,
        height: 1080
    }
});

test.describe.configure({ mode: 'serial' });

let page;

test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
});


const listenRequest = async ({ page }) => {
    const result = {};
    page.on('request', async (request) => {
        if (request.method() !== 'POST') return;
        const url = new URL(request.url());
        const { pathname } = url;
        if (!result[pathname]) {
            result[pathname] = [];
        }
        result[pathname].push({
            url: pathname,
            fullUrl: url,
            request: {
                postData: request.postDataJSON()
            }
        });
    });
    return result;
};

test('A Test', async () => {
    const apiResult = listenRequest({ page });
    await test.step('open page', async () => {
        const pageResponse = await page.goto(
            'https://mywebsitehost.com/musician/artist/manage/album/nalbum/songupload'
            , {
                timeout: 60000
            });

        expect(pageResponse.status()).toBe(200);
    });
});

test.afterAll(async () => {
    await page.close();
});
```
Moreover, my remote machine(OP Linux Debian, use Docker) can reproduce, but not in my Mac(@10.15.7).

**Comment by mxschmitt** [comment] 2022-05-19 09:29
I tried to reproduce but was not able to. I used the official Docker image, could you try using the same, since Debian is officially not supported.

See here for the official Docker image: https://playwright.dev/docs/next/docker

(I inspected it using top,htop,ps like you did, no dangling / defunct ldd processes)

**Comment by chenshy39** [comment] 2022-05-19 10:28
It’s wired...mine docker use your official docker image, too. The only thing that separates me from you is the host, my host machine is Debian.
But fortunately, since ldd only use to show the dependencies. I tried to remove it by using `rm ldd` and my test also runs well :) 
Thanks for your answer!

**Comment by sebinsua** [comment] 2022-05-19 14:59
@chenshy39 I noticed in videos that my tests were running very slowly because the browser was struggling to render in time for my expectations to pass. I'm not sure what my host machine is though, but in our case the Docker container is Debian based.

I'm wondering if we're experiencing something similar, and how you debugged this? Is deleting `ldd` safe? It seems kind of strange.

**Comment by yury-s** [comment] 2022-05-25 23:56
We run ldd before launching browser to validate that all its dependencies exist in the system, if you run 9 workers in parallel it may increase the number of concurrent ldd by 9x. Normally the process is super-fast as all the library paths are in the cache but in some cases it may be slower and it may be one of those moments when you saw them in top. They should eventually finish and disappear.

> But fortunately, since ldd only use to show the dependencies. I tried to remove it by using `rm ldd` and my test also runs well :)

Note that removing ldd from the system is unsafe. 

Closing this issues as there is no action to be taken.

**Closed by yury-s** 2022-05-25 23:56 UTC
Labels: triaging
