### ISSUE TITLE
[Bug]: Tests with "webkit" fails with Headless mode

### ISSUE THREAD

**Issue by apuatcfbd** [microsoft/playwright#32429] opened 2024-09-03 15:24 UTC
### Version

1.46.1

### Steps to reproduce

1. Clone repo [from here](https://github.com/Ar1f007/playwright-test-with-ui-flag-issue) & install deps (`pnpm i`)
2. Run `pnpm exec playwright test` that'll fail
3. Run `pnpm exec playwright test --headed`  that'll succeed

### Expected behavior

The test should pass like `--headed` mode

### Actual behavior

In headless mode, tests are failing

### Additional context

To pass in headed mode need following block in the test, otherwise headed mode also fails, However other browsers (chromium, firefox) pass without this block.
```ts
            if (browserName == 'webkit') {
                /**
                 * NOTE : ---------------------------------
                 * Turning off the following makes the test fail with headed mode also.
                 * This is only required with "webkit" browsers.
                 */
                await page.waitForLoadState("networkidle")
            }
```
Tests also fail with `pnpm exec playwright test --ui`
When tests fail, recorded video has issues, it's size is very small & doesn't play.

### Environment

```shell
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (8) x64 Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz
    Memory: 12.62 GB / 23.33 GB
    Container: Yes
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
    pnpm: 9.5.0 - ~/.nvm/versions/node/v20.15.1/bin/pnpm
  IDEs:
    VSCode: 1.92.2 - /snap/bin/code
  Languages:
    Bash: 5.2.21 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.46.1 => 1.46.1
```

**Comment by pavelfeldman** [comment] 2024-09-03 16:54
When you say tests are failing, what do you mean? The fact that the use of `waitForLoadState("networkidle")` fixes things suggests that your page has a hydration bug: https://playwright.dev/docs/navigations#hydration. Please provide a reduced use case we can reproduce locally if you think this is a Playwright issue.

**Comment by apudiu** [comment] 2024-09-04 03:56
Hi, I have the example in my machine, experiencing the same thing. I think the provided example is fairly simple. That's a Next.js project with one page. If you want to debug it, you can.

It is possible that the page has hydration issue. but the point is this happens only for **webkit**. & `waitForLoadState("networkidle")` doesn't helps in headless mode. It also fails to record the video for failing tests.
With all this things I think playwright might have something to fix/ improve.

**Comment by pavelfeldman** [comment] 2024-09-04 04:23
We always have something to fix and improve, but we need a reduced test case that demonstrates the bug to get started.

**Comment by apudiu** [comment] 2024-09-04 05:35
I didn't understand what you meant by "reduced test case". did you run the example repo? did that fail to produce the reported issue?

**Comment by pavelfeldman** [comment] 2024-09-04 05:58
Reduced test case is a minimal reproducible test case that demonstrates the issue, stripped from the stray details. We don't have capacity to look for the bugs in users' tests or web pages, so we ask users to file minimal issues we can reproduce. I did not run your example as it is too large - it should be a minimal web page and a single test that clearly demonstrates the issue.

**Comment by apudiu** [comment] 2024-09-04 06:18
To get started with **playwright** we need to initiate a node project. The provided repo is exactly that. Next.js and some other libraries are installed. Those are only for making that single web page. everything is configured there.
You don't need to look at anything unrelated to the issue. Just clone the repo, install deps & run the tests. It reproduces the issue very well. 
As we're facing the issue in the Next.js project. I think adding that to the repo makes sense. I request you to run the repo & do your stuff to find out if this is not a bug of **playwright**. We're not asking to debug our project issue. Just make sure playwright has no issue in that repo.
Like, what prevented playwright from recording the video?

If we change the project where we're facing the issue, then that sample repo stays no longer relevant. I hope you understand.

**Comment by apuatcfbd** [comment] 2024-09-04 15:39
Ok then you don't have to do this.

**Comment by apuatcfbd** [comment] 2024-09-04 15:43
When we've docker, VMs & windows sandbox, why do you need to verify deps? I think you're not capable of handling this scenario. You can handle cases where the example has only one dependency which is playwright & a single HTML page.
Can you please ask someone else to look after this issue?

**Comment by pavelfeldman** [comment] 2024-09-04 16:23
I understand that your report formally satisfies our BUG template, but I could not act on the issue due to the stray dependencies in the repo. I just updated our template to include this requirement:

*Please make sure you only include the code and the dependencies absolutely necessary for your repro. Due to the security considerations, we can only run the code we trust. Major web frameworks are Ok to use, but smaller convenience libraries are not.*

Please consider updating your repository to satisfy this requirement!

**Comment by apudiu** [comment] 2024-09-04 17:38
We understand that the way you run code is not safe, so you can't execute all packages. 
Doing any change to the sample repo makes it different than our setup. In that context it really don't reflect our scenario. So I think changing the sample repo is not an option.

_One thing I want to clarify is -_
We do create issues by investing our time to improve the lib in subject. Here we wanted to contribute to the improvement of the great tool **playwright**. 
We've invested our time to create the sample repo that reproduces the issues in subject.
Now it's your turn to checkout the bugs from our repo or leave it, if you don't need/ want to fix the issues then that's fine. 
As you're concerned with security, it's something you need to figure out on how to run this code securely. If you don't have time for that then I recommend you close the issue.

**Comment by pavelfeldman** [comment] 2024-09-04 17:45
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2024-09-04 17:45 UTC

**Comment by pavelfeldman** [comment] 2024-09-04 17:55
Playwright is a free and open source tool. We hope that Playwright users are ready to invest time to give back and help other users. Playwright team is small and needs to triage and prioritize a constant flow of incoming issues from hundreds of thousands of its users. Not being able to safely reproduce an issue positions it below the fold in terms of prioritization.

**Comment by apudiu** [comment] 2024-09-04 19:56
I'm seeing: "[pavelfeldman](https://github.com/pavelfeldman) closed this as [completed](https://github.com/microsoft/playwright/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) 2 hours ago"
This is not **completed**, can you close this like "Cancelled" or something like it? Because here you didn't talked about anything about the issue or the solution. The focus was in the `package.json` having many packages.
