### ISSUE TITLE
[BUG] Firefox iFrame frame.type transient error

### ISSUE THREAD

**Issue by curiousercreative** [microsoft/playwright#7186] opened 2021-06-16 22:09 UTC
## Context
- Playwright Version: 1.12.2
- Operating System: Linux Pop!_OS 20.10
- Node.js version: [14.16.0]
- Browser: [Firefox]

### System:
 - OS: Linux 5.11 Pop!_OS 20.10
 - Memory: 8.96 GB / 31.21 GB
 - Container: Yes
### Binaries:
 - Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
 - npm: 7.11.1 - ~/.nvm/versions/node/v14.16.0/bin/npm
### Languages:
 - Bash: 5.0.17 - /usr/bin/bash

## Code Snippet
```javascript
import { test, expect } from '@playwright/test';

test('iFrame input should accept keyboard input', async ({ page }) => {
  async function typeIframe (frameSelector, inputSelector, text) {
    const handle = await page.waitForSelector(frameSelector);
    const frame = await handle.contentFrame();
    await frame.waitForSelector(inputSelector);
    await frame.focus(inputSelector);
    await frame.type(inputSelector, text, { delay: 100 });
  }

  await page.goto('https://stripe.com/payments/elements');

  await typeIframe(
    'iframe[title="Secure card payment input frame"]',
    'input[placeholder="Card number"]',
    '4242 4242 4242 4242'.replace('/\s/g', ''),
  );
});
```

## Describe the bug
Transient failure with error. Unfortunately, the above snippet doesn't actually reproduce the error, so perhaps nothing can be done
```
frame.type: Protocol error (Page.dispatchKeyEvent): error in channel "content::page": exception while running method "dispatchKeyEvent" in namespace "page": Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsITextInputProcessor.keydown] _dispatchKeyEvent@chrome://juggler/content/content/PageAgent.js:563:13
    _onMessage@chrome://juggler/content/SimpleChannel.js:165:37
    receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
     _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
    receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42

    =========================== logs ===========================
    waiting for selector "input[placeholder="Card Number"]"
      selector resolved to visible <input value="" type="tel" autocorrect="off" name="card…/>
    elementHandle.type("4242424242424242")
```

**Comment by aslushnikov** [comment] 2021-06-17 05:39
This is a dupe of #5460. This bug has been reported multiple times, yet we have no repro to debug :(

> Unfortunately, the above snippet doesn't actually reproduce the error, so perhaps nothing can be done

@curiousercreative I'll be very happy if by any chance you can share repro with me privately! My corp e-mail is [here](https://github.com/microsoft/playwright/issues/5460#issuecomment-855526122). 

Closing this issue in favor of #5460 - let's continue discussion there.

**Closed by aslushnikov** 2021-06-17 05:39 UTC

**Comment by curiousercreative** [comment] 2021-06-17 17:32
@aslushnikov I'll send you something if I can get it to reproduce. Today, it hasn't reproduced so far.
