### ISSUE TITLE
[BUG] Issue with waitFor() in Playwright 1.38.1

### ISSUE THREAD

**Issue by tomoyachen** [microsoft/playwright#27507] opened 2023-10-09 09:12 UTC
### System info
- Playwright Version: [v1.38.1]
- Operating System: [macOS 12.0.1]
- Browser: [Chromium]
- Other info:
  - I have not tried it recently, but in the past, this code worked well in version 1.30.1.

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**utils file**

```js
// utils.ts
export async function locatorExists(locator: Locator, timeout = 3000): Promise<boolean> {

  const __locatorExists = async (__locator: Locator) =>
    !((await __locator.waitFor({ timeout: timeout }).catch((e: Error) => e)) instanceof Error)
  const exists = await __locatorExists(locator)

  return exists
}

export async function locatorLength(locator: Locator, timeout = 3000): Promise<number> {
  if (await locatorExists(locator, timeout)) {
    return await locator.count()
  }
  
  return 0
}
```

**testcase file**

```js
// demo.sepc.ts
import { expect, test } from '@playwright/test'
import * as utils from '~tests/utils'

test.describe('Try it', () => {
  test('my case', async ({ page }) => {
    await page.goto('https://github.com/microsoft/playwright/issues')
    const issues = page.locator('[aria-label="Issues"][role=group] > div > div > div > a')

    // In Playwright 1.38.1, it seems that the `locatorLength` method is not working as expected.
    // When `locatorLength` internally calls `locatorExists`, the `waitFor` function immediately returns `false`.
    // Even if I wait for a fixed amount of time and visually confirm the presence of the element, it still returns `false`.
    expect(await utils.locatorLength(issues)).toBeGreaterThan(10)

    // However, when using the `locatorExists` function directly, it works as expected.
    // if (await utils.locatorExists(issues)) {
    //     expect(await issues.count()).toBeGreaterThan(10)
    // }

  })
})


```

**Steps**
- [Run the test]

**Expected**

waitFor() returns true and the assertion passes.

**Actual**

waitFor() returns false and the assertion fails.

**Comment by dgozman** [comment] 2023-10-09 16:31
@tomoyachen I have tried to reproduce the issue, and it behaves the same on v1.37.1 and v1.38.1. There are many elements matching your locator, so you get the `strict mode violation` error, something like this:

```
locator.waitFor: Error: strict mode violation: locator('[aria-label="Issues"][role=group] > div > div > div > a') resolved to 25 elements:
    1) <a href="/microsoft/playwright/issues/27509" data-t…></a> aka getByLabel('Link to Issue. [Feature] `export` the `MountResult` interface so that it can be used in Page Object Models')
    2) <a href="/microsoft/playwright/issues/27507" data-t…></a> aka getByLabel('Link to Issue. [BUG] Issue with waitFor() in Playwright 1.38.1')
    3) <a href="/microsoft/playwright/issues/27504" data-t…></a> aka getByLabel('Link to Issue. [BUG] \'noscript\' sections always invisible in ui-mode')
```

I'd recommend to use built-in expect methods instead:

```ts
await expect.poll(() => locator.count()).toBeGreaterThan(10);
```

**Comment by tomoyachen** [comment] 2023-10-10 02:54
> @tomoyachen I have tried to reproduce the issue, and it behaves the same on v1.37.1 and v1.38.1. There are many elements matching your locator, so you get the `strict mode violation` error, something like this:
> 
> ```
> locator.waitFor: Error: strict mode violation: locator('[aria-label="Issues"][role=group] > div > div > div > a') resolved to 25 elements:
>     1) <a href="/microsoft/playwright/issues/27509" data-t…></a> aka getByLabel('Link to Issue. [Feature] `export` the `MountResult` interface so that it can be used in Page Object Models')
>     2) <a href="/microsoft/playwright/issues/27507" data-t…></a> aka getByLabel('Link to Issue. [BUG] Issue with waitFor() in Playwright 1.38.1')
>     3) <a href="/microsoft/playwright/issues/27504" data-t…></a> aka getByLabel('Link to Issue. [BUG] \'noscript\' sections always invisible in ui-mode')
> ```
> 
> I'd recommend to use built-in expect methods instead:
> 
> ```ts
> await expect.poll(() => locator.count()).toBeGreaterThan(10);
> ```

Thanks. 🙏 
The `expect.poll` works great. I can't believe I didn't realize this method before.

**Comment by tomoyachen** [comment] 2023-10-10 03:19
Perhaps in previous versions, waitFor() could match multiple elements, but it has now been confirmed that it cannot.

<img width="1511" alt="image" src="https://github.com/microsoft/playwright/assets/42526054/a3c179a7-0ecf-4d29-a932-f23f970e7c1b">

**Comment by dgozman** [comment] 2023-10-10 17:06
@tomoyachen Hmm... That's a strange statement about lists, because `waitFor` was always strict from the start. Anyway, I think we can close the issue since it looks resolved.

**Closed by dgozman** 2023-10-10 17:06 UTC
Labels: triaging
