### ISSUE TITLE
[Feature]: Support `expect.assertions(number)`

### ISSUE THREAD

**Issue by Barbapapazes** [microsoft/playwright#31732] opened 2024-07-17 15:11 UTC
### 🚀 Feature Request

Hello 👋,

I'm writing e2e test that check if the request is well formatted. To do so, I add some expect in a `page.route` function.

```
  test('should track file downloads', async ({ page }) => {
    await page.route('**/api/event', async (route) => {
      if (route.request().method() !== 'POST')
        throw new Error('Expected a POST request')

      const data = route.request().postData()

      if (!data)
        throw new Error('Expected a POST body')

      const parsedData = JSON.parse(data)

      expect(parsedData.n).toBe('File Download')
      expect(parsedData.u).toBe('http://localhost:5173/file-downloads-tracking')
      expect(parsedData.d).toBe('localhost')
      expect(parsedData.p).toBe('{"url":"/file.svg"}')

      await route.fulfill()
    })

    await page.goto('http://localhost:5173/file-downloads-tracking')
  })
```

This test pass but it nothing it `/api/event`, the test will not fail but expect are never triggered.

### Motivation

 Having [`expect.assertions` like Jest](https://jestjs.io/docs/expect#expectassertionsnumber), could make the test fail if not every assert has been called.

**Comment by mxschmitt** [comment] 2024-07-18 06:32
Responded in https://x.com/mx_schmitt/status/1813700158212723127?s=61&t=GD3LZiEyMSTcmWZeXhTGgQ

**Comment by mrmckeb** [comment] 2024-07-18 07:27
This seems to be a duplicate of #23422.

**Closed** 2024-07-18 07:30 UTC
