### ISSUE TITLE
[Bug]: launch_persistent_context hangs when started with record_video_dir outside of test

### ISSUE THREAD

**Issue by develorer** [microsoft/playwright#31769] opened 2024-07-19 08:19 UTC
### Version

1.45.0

### Steps to reproduce

1. run the following script
```
from playwright.sync_api import sync_playwright
import time

sync_playwright_started = sync_playwright().start()
binary_path = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
context = sync_playwright_started.chromium.launch_persistent_context(headless=True,
                                                                     executable_path=binary_path,
                                                                     record_video_dir='video',
                                                                     user_data_dir=SPECIFY_YOUR_DATA_DIR
                                                                     )

```

2. Notice it hangs forever
3. Run the same script above, having remove the `record_video_dir` option
4. Notice it does not hang

### Expected behavior

I expect to be able to record a video outside a test.

### Actual behavior

The program execution hangs

### Additional context

This [issue](https://github.com/microsoft/playwright/issues/8428) makes me think that playwright intentionally does not support recording video outside a test context?

If so, I respect the design choice, but would be grateful for pointers as to how to make it work for me, outside the test context (I am happy with a messy solution).

### Environment

```shell
MacOS
```

**Comment by mxschmitt** [comment] 2024-07-21 10:02
I was not able to reproduce, I tried the following:

```python
from playwright.sync_api import sync_playwright

sync_playwright_started = sync_playwright().start()
binary_path = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
context = sync_playwright_started.chromium.launch_persistent_context(
    headless=True,
    executable_path=binary_path,
    record_video_dir="/Users/maxschmitt/videos",
    user_data_dir="user-data-dir",
)

page = context.pages[0]
page.goto("https://example.com")
page.goto("https://github.com")
page.goto("https://example.com")
context.close()

```

make sure to not use [time.sleep](https://playwright.dev/python/docs/library#timesleep-leads-to-outdated-state), see here, that might example unwanted behavior.

**Comment by develorer** [comment] 2024-07-21 14:44
Hmm, ok, that means it's specific to my environment. I'll do some more investigations on my end.

(it is hanging directly at the time of `launch_persistent_context`, so not an issue with `time.sleep`).

**Comment by pavelfeldman** [comment] 2024-07-22 23:10
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2024-07-22 23:10 UTC

**Comment by develorer** [comment] 2024-07-23 07:11
Understood. I still have not been able to pinpoint what the issue is on my end, but have confirmed indeed that it is specific to the system I was testing on (it is working correctly on other systems). Thank you

**Comment by yxswjtu** [comment] 2024-10-10 17:09
is this fixed？i got the same problem on windows x64.(python 3.11.0，playwright 1.46.0，use async_playwright)
