### ISSUE TITLE
I'm trying to assert using Except in Playwright with C#,However the testcase will alwyas in the pass mode 

### ISSUE THREAD

**Issue by dinaRodeny** [microsoft/playwright#28315] opened 2023-11-23 14:44 UTC
await Expect(indexclausesTable(row)).ToHaveTextAsync(expected: indexclauses);
Although the locator returns null, the test case will pass. The comparison is completely incorrect, and it should fail, despite the timeout resulting in the test case passing. Any help?

**Comment by mxschmitt** [comment] 2023-11-23 15:15
We need a self-contained minimal reproducible, since this is not following the issue template, we'll close it for now. Feel free to re-file.

**Closed by mxschmitt** 2023-11-23 15:15 UTC
