### ISSUE TITLE
[BUG] - Failed to download Chromium 102.0.5005.40 (playwright build v1005)

### ISSUE THREAD

**Issue by KingsonSamuel** [microsoft/playwright#14616] opened 2022-06-03 07:53 UTC
**Context:**
- Playwright Version: [v1.22.0]
- Operating System: [Windows]
- Java version: ["1.8.0_121"]
- Browser: [ Chromium]
- Extra: [Executing from a company or enterprise]

**Code Snippet**

Playwright playwright = Playwright.create();
		
		LaunchOptions launchOption = new LaunchOptions();
		launchOption.setChannel("chrome");
		launchOption.setHeadless(false);
		Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setProxy(new Proxy("xxxxxxxxxxx").setUsername("xxx").setPassword("xxxx")));
		Page page = browser.newPage();
		page.navigate("xxxxxxxxxxxxxxxxxx");
		String title = page.title();
		System.out.println("Page title is :" + title);
		browser.close();
		playwright.close();
  
  //Error Message

Downloading Chromium 102.0.5005.40 (playwright build v1005)...
Downloading Chromium 102.0.5005.40 (playwright build v1005)...
Downloading Chromium 102.0.5005.40 (playwright build v1005)...
Failed to install browsers
Error: Failed to download Chromium 102.0.5005.40 (playwright build v1005), caused by
Error: connect ETIMEDOUT 13.107.227.58:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
Exception in thread "main" java.lang.RuntimeException: Failed to create driver
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:61)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:40)
	at com.microsoft.playwright.Playwright.create(Playwright.java:96)
	at com.microsoft.playwright.Playwright.create(Playwright.java:100)
	at POC_Playwright.POC_Playwright.NuxeoInvokeApp.main(NuxeoInvokeApp.java:15)
Caused by: java.lang.RuntimeException: Failed to install browsers, exit code: 1
	at com.microsoft.playwright.impl.DriverJar.installBrowsers(DriverJar.java:76)
	at com.microsoft.playwright.impl.DriverJar.initialize(DriverJar.java:48)
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:57)
	... 4 more
 

**Describe the bug**

While executing the script using Playwright tool , it is failed to download chromium browser.

Note : Tried downloading using Command line tools still we get same error . Tried using Proxy server still getting same error.

**Comment by KingsonSamuel** [comment] 2022-06-03 07:54
Please help me with this issue asap as we are having less timeline to evaluate a tool for automating an Application. Thanks!

**Comment by KingsonSamuel** [comment] 2022-06-03 09:00
@aslushnikov Hey I could able to download Chromium-win64.zip file by clicking on the link you shared.

**Comment by KingsonSamuel** [comment] 2022-06-03 09:06
But I cannot able to navigate to the URL- 
i.e - When I try to access 

**URL**  https://playwright.azureedge.net/builds/chromium/1005/ 
 I get below error 
<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:e39b2268-601e-002f-6928-777568000000 Time:2022-06-03T09:03:01.4926854Z</Message>
</Error>

Also

**URL**  https://playwright.azureedge.net
I get below error :

<Error>
<Code>InvalidQueryParameterValue</Code>
<Message>Value for one of the query parameters specified in the request URI is invalid. RequestId:49ca1455-f01e-0080-4229-7757f8000000 Time:2022-06-03T09:05:08.5721694Z</Message>
<QueryParameterName>comp</QueryParameterName>
<QueryParameterValue/>
<Reason/>
</Error>

**Comment by aslushnikov** [comment] 2022-06-03 10:28
> Hey I could able to download Chromium-win64.zip file by clicking on the link you shared.

@KingsonSamuel Can you also download it via powershell?

**Comment by aslushnikov** [comment] 2022-06-06 09:00
@KingsonSamuel hmm, all pointers are that the URL is accessible and downloadable.

Does it take long to download it? Could you please try one more time with Playwright? I see from your logs, that Playwright actually starts browser download, but something interrupts it later on.

**Comment by pavelfeldman** [comment] 2022-06-09 18:35
The issue seems to be localized to a single user (connectivity issues on the users end). Closing as not actionable on the Playwright side.

**Closed by pavelfeldman** 2022-06-09 18:35 UTC
Labels: triaging

**Comment by Mr-Nobody-li** [comment] 2022-08-18 03:44
> The issue seems to be localized to a single user (connectivity issues on the users end). Closing as not actionable on the Playwright side.

I don't think this problem only happens to a single user. In fact, I have encountered this problem recently, and the detection methods mentioned above are normal. Here is my error message
```
throw new Error(`Failed to download ${title}, caused by\n${e.stack}`);
│             ^
│ Error: Failed to download Chromium 104.0.5112.48 (playwright build v1015), caused by
│ Error: unable to verify the first certificate
│     at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
│     at TLSSocket.emit (node:events:526:28)
│     at TLSSocket._finishInit (node:_tls_wrap:944:8)
│     at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)
│     at D:\document\vue\ANALYSIS\vite\node_modules\.pnpm\playwright-core@1.24.0\node_modules\playwrig  
│     at async Registry._downloadExecutable (D:\document\vue\ANALYSIS\vite\node_modules\.pnpm\playwrig  
│     at async Registry.install (D:\document\vue\ANALYSIS\vite\node_modules\.pnpm\playwright-core@1.24  
│     at async installBrowsersForNpmInstall (D:\document\vue\ANALYSIS\vite\node_modules\.pnpm\playwrig  
```
I encountered this error when using vite. I opened a Discussions in [vite](https://github.com/vitejs/vite/discussions/9677)

**Comment by surfmuggle** [comment] 2023-02-09 11:17
Just to chime in 
 - i believe a enterprise proxy often plays a role
 - ssl trouble may play a role too

In my case i am facing download issues as well

```
C:\dev\playwright>npm install @playwright/test
npm notice Beginning October 4, 2021, all connections to the npm registry 
              - including for package installation 
              - must use TLS 1.2 or higher. 

You are currently using plaintext http to connect. 
Please visit the GitHub blog for more information: 
     https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/

     npm WARN saveError ENOENT: no such file or directory, open 'C:\dev\playwright\package.json'
     npm notice created a lockfile as package-lock.json. You should commit this file.
     npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\playwright\package.json'
     npm WARN playwright No description
     npm WARN playwright No repository field.
     npm WARN playwright No README data
     npm WARN playwright No license field.

     + @playwright/test@1.30.0
     added 3 packages from 43 contributors in 1.924s


C:\dev\playwright>npx playwright install


Downloading Chromium 110.0.5481.38 (playwright build v1045) 

     from https://playwright.azureedge.net/builds/chromium/1045/chromium-win64.zip
     Error: write EPROTO 24956:error:1408F10B:SSL routines:ssl3_get_record:wrong version      
     number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16) {
            errno: -4046,
            code: 'EPROTO',
            syscall: 'write'
}
```

npm [will no longer support TLS 1.0 or TLS 1.1 ](https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/) You can test if your setup is able to use TLS 1.2 with 

```
npm install -g https://tls-test.npmjs.com/tls-test-1.0.0.tgz
```
If it fails it may look something like this

![image](https://user-images.githubusercontent.com/1271555/217795956-93d6b2c5-9bc3-4c28-b789-5cd74938d30e.png)

**Comment by MaheshGooner** [comment] 2023-02-09 15:15
Same error as @surfmuggle @KingsonSamuel 
`pwsh .\bin\Debug\net6.0\playwright.ps1 install      
Warning: Ignoring extra certs from `C:\certs\root.crt`, load failed: error:02001003:system library:fopen:No such process
Downloading Chromium 110.0.5481.38 (playwright build v1045) from https://playwright.azureedge.net/builds/chromium/1045/chromium-win64.zip
Warning: Ignoring extra certs from `C:\certs\root.crt`, load failed: error:02001003:system library:fopen:No such process
Error: write EPROTO 32896:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
  errno: -4046,
  code: 'EPROTO',
  syscall: 'write'
}
Downloading Chromium 110.0.5481.38 (playwright build v1045) from https://playwright-akamai.azureedge.net/builds/chromium/1045/chromium-win64.zip
Warning: Ignoring extra certs from `C:\certs\root.crt`, load failed: error:02001003:system library:fopen:No such process`

**Comment by Ennissay** [comment] 2023-05-02 10:02
Good news, it is possible to manually install the browser. Download the file https://playwright.azureedge.net/builds/chromium/1005/chromium-win64.zip and extract it (which will be installed manually).

For your information, when trying to run the test (with pytest in this case), I received the following error message: 

``playwright._impl._api_types.Error: Executable doesn't exist at C:\Users....\AppData\Local\ms-playwright\chromium-1055\chrome-win\chrome.exe.`
`
After opening the previously downloaded zip file, there is a chrome-win\chrome.exe file. So, I went to C:\Users....\AppData\Local\ms-playwright, created the directory chromium-1055, and copied and pasted the \chrome-win file from the zip. And magically, the test worked.

**Comment by teegalarajender77** [comment] 2023-07-29 01:37
Hi, I am seeing this error while running the playwright test. Please help

 Error: Failed to download Chromium 115.0.5790.75 (playwright build v1071), caused by
npm ERR! Error: Download failure, code=1
npm ERR!     at ChildProcess.<anonymous> (D:\Projects\ps-online-servicing-web-app\node_modules\playwright-core\lib\server\registry\browserFetcher.js:88:16)
npm ERR!     at ChildProcess.emit (node:events:513:28)
npm ERR!     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR!     at D:\Projects\ps-online-servicing-web-app\node_modules\playwright-core\lib\server\registry\index.js:694:13
npm ERR!     at async Registry._downloadExecutable (D:\Projects\ps-online-servicing-web-app\node_modules\playwright-core\lib\server\registry\index.js:693:5)
npm ERR!     at async Registry.install (D:\Projects\ps-online-servicing-web-app\node_modules\playwright-core\lib\server\registry\index.js:642:9)
npm ERR!     at async installBrowsersForNpmInstall (D:\Projects\ps-online-servicing-web-app\node_modules\playwright-core\lib\server\registry\index.js:832:3)
npm ERR!
npm ERR! Node.js v18.14.2
