### ISSUE TITLE
[Question] how to change the browser viewport to fullscreen while using page fixture

### ISSUE THREAD

**Issue by ShanmukhaGajula** [microsoft/playwright#12212] opened 2022-02-18 09:53 UTC
Hi, below is the code I am using, POM along with fixtures. Please suggest the best way that I can change the viewport to fullscreen

//basepage.fixtures.ts
import MicrosoftLoginPage from '../pages/microsoftlogin.page'
import {test as basetest} from '@playwright/test'
import SBReactAppLoginPage from '../pages/SBReactApp/login.page';
import SBReactAppHomePage from '../pages/SBReactApp/Home.page';

const test = basetest.extend<{
    microsoftLoginPage : MicrosoftLoginPage;
    sbReactAppLoginPage : SBReactAppLoginPage;
    sbReactAppHomePage :SBReactAppHomePage;
}>({
    
    microsoftLoginPage:async ({page},use) => {
        
        await use(new MicrosoftLoginPage(page));
    },
    sbReactAppLoginPage:async ({page},use) => {
        await use(new SBReactAppLoginPage(page));
    },
    sbReactAppHomePage:async ({page},use) => {
        await use(new SBReactAppHomePage(page));
    }

})

export default test;
export const expect = test

//microsoftlogin.page.ts
import {expect, Locator, Page} from '@playwright/test'

export default class MicrosoftLoginPage{
    private page: Page;
    btnSBlogin: Locator ;
    txtusername: Locator;
    txtpassword: Locator;
    btnnext: Locator;
    btnsignin: Locator;
    btnNo: Locator;
    constructor(page: Page) {
        this.page=page;
        this.btnSBlogin= this.page.locator('[data-testid="loginbtn"]')
        this.txtusername =this.page.locator('[aria-label="someone\\@example\\.com"]')
        this.txtpassword = this.page.locator('[placeholder="Password"]')
        this.btnnext = this.page.locator('text=Next')
        this.btnsignin =this.page.locator('text=Sign in')
        this.btnNo = this.page.locator('text=No')
    }
   
    public async PerformLogin(username: string, password: string){     
        //await this.btnSBlogin.click();    
        await this.txtusername.fill(username);  
        expect.soft(this.txtusername).toBeVisible();
        await this.btnnext.click();
        await this.txtpassword.click();
        await this.txtpassword.fill(await password);
        await this.btnsignin.click();
        await this.btnNo.click()
    }

}

//uivalidations.cons.spec.ts
import test, { expect } from "../../../fixtures/basepage.fixtures"
test.describe('Salesbeacon app UI validation2 with consolidated user',()=>{
  test.beforeEach(async({microsoftLoginPage,page,sbReactAppLoginPage,sbReactAppHomePage})=>{   
    await sbReactAppLoginPage.login(microsoftLoginPage,page,sbReactAppLoginPage,sbReactAppHomePage);
  })
  test.only('Dashboard Validation @smoke',async ({page,sbReactAppHomePage})=>{
    await test.step('Validation of landing page',async()=>{
      expect.soft(page.url(),'Landing Page URL validation').toEqual('https://www.xyz.com/');
      await sbReactAppHomePage.selectRollcall('Aug-FY21');
    });
    await test.step('validation of visual page',async ()=>{
      expect.soft( await page.screenshot({fullPage:true}),'Visual comparision of Dashboard with full page').toMatchSnapshot('landingpage.png',{threshold:0.3});
    });
  })
});

Thanks in advance.

**Comment by dgozman** [comment] 2022-02-18 18:06
Closing as a duplicate of #1086.

**Closed by dgozman** 2022-02-18 18:06 UTC
