### ISSUE TITLE
[Feature] support 'private mode' In Firefox

### ISSUE THREAD

**Issue by cerebrl** [microsoft/playwright#1639] opened 2020-04-02 15:50 UTC
Hello all,

First, we've been using Playwright to test all three supported browser platforms, and it's been working well. I did discover something with Firefox though that was a bit confusing and believe warrants a question.

I have a project utilizing `indexedDB` and was testing it with Playwright using `newContext`. All tests passed without issue. But, we had a reported bug that our project failed in Firefox's "private mode". After some debugging, it seems accessing `indexedDB` in Firefox's private mode is denied, causing our code to fail.

Since we were running our tests with `firefox.newContext()`, we believed it was running the tests against the browser's version of private mode or "incognito" (since the API docs hint at this). But, that doesn't seem to be entirely accurate as our Firefox tests passed in Playwright with `newContext`, but failed in manual testing in Firefox's private mode.

**Question**: Is it true that `newContext` is similar to, but not actually, private mode/incognito?

**Comment by pavelfeldman** [comment] 2020-04-03 17:31
Yes, that is true! Also, a great discovery.

The idea behind the `newContext` is that it gives you a fresh isolated browser profile. But it aims at simulating a regular profile behavior, not an incognito one. Support for the `browserType.newContext({private: true})` would be a fair feature request. Not saying that we will rush into implementing it while there are enough things to fix in the regular profile, but if it gets enough traction, we'll definitely look at it.

**Comment by pavelfeldman** [comment] 2020-05-26 19:34
We can recycle this issue. Not saying we are going to do it, but let it be on file.

**Comment by aslushnikov** [comment] 2020-07-01 00:36
IIRC there were technical challenges in using "private mode" in firefox - we couldn't make multiple private mode windows that don't share any state between each other.

I'll close this issue for now since we don't have any plans to support private mode in firefox. This, however, can all change, if there's a strong demand for this to be implemented :-)

**Closed by aslushnikov** 2020-07-01 00:36 UTC

**Comment by flunderpero** [comment] 2022-04-14 22:47
We are moving most of our tests from WebdriverIO to Playwright. Testing with FF private mode is really important to us. We regularly catch regressions because of the strict behaviour of FF in private mode. As long as Playwright does not support this, we cannot turn off our WebdriverIO suite and have to maintain it.

Is there any kind of hack or workaround? It would be ok for us  if we were unable to run tests in parallel.

**Comment by gokaybiz** [comment] 2024-01-21 23:38
BUMP
