### ISSUE TITLE
[BUG] Viewport is getting set in the inner web page but the browser window is not getting resized.

### ISSUE THREAD

**Issue by shravanvh** [microsoft/playwright#21064] opened 2023-02-21 15:56 UTC
**Context:**
- Playwright Version: 1.30.0
- Operating System: Windows
- Node.js version: 18.13.0
- Browser: Chromium
- Extra: Test is run locally on the user machine

## System:
 - OS: Windows 10 10.0.19045
 - Memory: 4.25 GB / 15.78 GB
## Binaries:
 - Node: 16.17.1 - C:\Program Files\nodejs\node-v16.17.1-win-x64\node.EXE
 - npm: 8.15.0 - C:\Program Files\nodejs\node-v16.17.1-win-x64\npm.CMD

**Code Snippet**

```ts
// @ts-check
const { test, expect } = require('@playwright/test');
test.use({viewport:{width: 1280, height:1024}})

test('has title', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});

test('get started link', async ({ page }) => {

  await page.goto('https://playwright.dev/');

  // Click the get started link.
  await page.getByRole('link', { name: 'Get started' }).click();

  // Expects the URL to contain intro.
  await expect(page).toHaveURL(/.*intro/);
});


test.use({viewport:{width: 1280, height:1024}})

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], 
      viewport: { width: 1280, height: 1024},
     },
      
    },

```
**Describe the bug**

I have tried setting the view port in the playwright.config.js and locally as well with the above provided configuration. But if you see the screenshot below, the chromium window is not getting resized according to the viewport:

![image](https://user-images.githubusercontent.com/2868853/220393921-30a40c7c-31df-473e-b19b-c9a217018bbc.png)

**Comment by yury-s** [comment] 2023-02-22 23:58
We were not able to reproduce it on macOS and on Windows. Each time the window is created with the initial viewport size. Can you share the project where it's happening?

**Comment by yury-s** [comment] 2023-02-27 21:40
Closing as part of the triage process. We need to be able to reproduce the problem to make this report actionable. Please create a new issue with a detailed reproducible if you still face the issue.

**Closed by yury-s** 2023-02-27 21:40 UTC
Labels: triaging
