### ISSUE TITLE
[BUG] Playwright 1.30/1.31.1 is not able to open firefox on windows container 

### ISSUE THREAD

**Issue by sauravlikhar** [microsoft/playwright#21179] opened 2023-02-24 09:12 UTC
**Context:**
- Playwright Version: 1.30
- Operating System: Windows
- Node.js version: 14.17.3
- Browser: Firefox

**Describe the bug**

We created one windows docker container with the image that only starts playwright server with all the dependencies installed in it. When we connected to that container from our local client test for firefox browser, it got timeout. This issue comes only first time connection. All subsequent tests pass after first failure.

Here are the container logs - 
```
2023-02-24T09:07:33.491Z pw:server [id=1] serving connection: /
2023-02-24T09:07:33.757Z pw:server [id=1] engaged launch mode for "firefox"
2023-02-24T09:07:33.757Z pw:proxy Starting socks proxy server on port 49158
2023-02-24T09:07:33.757Z pw:server [id=1] started socks proxy on port 49158
2023-02-24T09:07:36.273Z pw:browser <launching> C:\Users\ContainerAdministrator\AppData\Local\ms-playwright\firefox-1372\firefox\firefox.exe -no-remote -headless -profile C:\Users\ContainerAdministrator\AppData\Local\Temp\playwright_firefoxdev_profile-gejPlh -juggler-pipe -silent
2023-02-24T09:07:36.273Z pw:browser <launched> pid=2156
2023-02-24T09:07:37.867Z pw:browser [pid=2156][err] *** You are running in headless mode.
2023-02-24T09:07:38.992Z pw:browser [pid=2156][out] 
2023-02-24T09:07:38.992Z pw:browser [pid=2156][out] Juggler listening to the pipe
2023-02-24T09:07:38.992Z pw:protocol SEND ► {"id":1,"method":"Browser.enable","params":{"attachToDefaultContext":false}}
2023-02-24T09:07:38.992Z pw:protocol SEND ► {"id":2,"method":"Browser.getInfo"}
2023-02-24T09:07:38.992Z pw:protocol SEND ► {"id":3,"method":"Browser.setBrowserProxy","params":{"type":"socks","bypass":[],"host":"127.0.0.1","port":49158}}
2023-02-24T09:07:39.164Z pw:protocol ◀ RECV {"id":1}
2023-02-24T09:07:39.164Z pw:protocol ◀ RECV {"id":2,"result":{"version":"Firefox/108.0.2","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"}}
2023-02-24T09:07:39.164Z pw:protocol ◀ RECV {"id":3}
2023-02-24T09:07:39.594Z pw:browser [pid=2156][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt (t=32.655) [GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
2023-02-24T09:07:39.688Z pw:protocol SEND ► {"id":4,"method":"Browser.createBrowserContext","params":{"removeOnDetach":true}}
2023-02-24T09:07:39.891Z pw:protocol ◀ RECV {"id":4,"result":{"browserContextId":"2be0e955-3782-4c1b-951a-db88f76ee078"}}
2023-02-24T09:07:39.891Z pw:protocol SEND ► {"id":5,"method":"Browser.setDownloadOptions","params":{"browserContextId":"2be0e955-3782-4c1b-951a-db88f76ee078","downloadOptions":{"behavior":"saveToDisk","downloadsDir":"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\playwright-artifacts-PlDz2G"}}}
2023-02-24T09:07:39.891Z pw:protocol SEND ► {"id":6,"method":"Browser.setDefaultViewport","params":{"browserContextId":"2be0e955-3782-4c1b-951a-db88f76ee078","viewport":{"viewportSize":{"width":1280,"height":720},"deviceScaleFactor":1}}}
2023-02-24T09:07:39.891Z pw:protocol SEND ► {"id":7,"method":"Browser.setLocaleOverride","params":{"browserContextId":"2be0e955-3782-4c1b-951a-db88f76ee078","locale":"en-US"}}
2023-02-24T09:07:39.891Z pw:protocol SEND ► {"id":8,"method":"Browser.setExtraHTTPHeaders","params":{"browserContextId":"2be0e955-3782-4c1b-951a-db88f76ee078","headers":[{"name":"Accept-Language","value":"en-US"}]}}
2023-02-24T09:07:39.891Z pw:protocol SEND ► {"id":9,"method":"Browser.setColorScheme","params":{"browserContextId":"2be0e955-3782-4c1b-951a-db88f76ee078","colorScheme":"light"}}
2023-02-24T09:07:39.891Z pw:protocol SEND ► {"id":10,"method":"Browser.setReducedMotion","params":{"browserContextId":"2be0e955-3782-4c1b-951a-db88f76ee078","reducedMotion":"no-preference"}}
2023-02-24T09:07:39.891Z pw:protocol SEND ► {"id":11,"method":"Browser.setForcedColors","params":{"browserContextId":"2be0e955-3782-4c1b-951a-db88f76ee078","forcedColors":"none"}}
2023-02-24T09:07:39.969Z pw:protocol ◀ RECV {"id":5}
2023-02-24T09:07:39.985Z pw:protocol ◀ RECV {"id":6}
2023-02-24T09:07:39.985Z pw:protocol ◀ RECV {"id":7}
2023-02-24T09:07:39.985Z pw:protocol ◀ RECV {"id":8}
2023-02-24T09:07:39.985Z pw:protocol ◀ RECV {"id":9}
2023-02-24T09:07:39.985Z pw:protocol ◀ RECV {"id":10}
2023-02-24T09:07:39.985Z pw:protocol ◀ RECV {"id":11}
2023-02-24T09:07:40.251Z pw:protocol SEND ► {"id":12,"method":"Browser.newPage","params":{"browserContextId":"2be0e955-3782-4c1b-951a-db88f76ee078"}}
2023-02-24T09:07:46.094Z pw:protocol ◀ RECV {"method":"Browser.attachedToTarget","params":{"sessionId":"65e3a260-9b14-4408-846a-0df0cb09ef69","targetInfo":{"targetId":"6b1ab5a2-7871-426b-8752-eac220cb2dc5","type":"page","browserContextId":"2be0e955-3782-4c1b-951a-db88f76ee078"}}}
2023-02-24T09:07:46.094Z pw:protocol SEND ► {"method":"Page.setInitScripts","params":{"scripts":[{"script":"","worldName":"__playwright_utility_world__"}]},"id":13,"sessionId":"65e3a260-9b14-4408-846a-0df0cb09ef69"}
2023-02-24T09:07:47.501Z pw:protocol ◀ RECV {"id":12,"result":{"targetId":"6b1ab5a2-7871-426b-8752-eac220cb2dc5"}}
2023-02-24T09:07:47.501Z pw:browser [pid=2156][err] JavaScript error: resource://gre/modules/URIFixup.sys.mjs, line 302: NS_ERROR_FAILURE: Should pass a non-null uri
2023-02-24T09:07:47.516Z pw:browser [pid=2156][out] console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\playwright_firefoxdev_profile-gejPlh\\search.json.mozlz4", (void 0)))
2023-02-24T09:08:33.245Z pw:server [id=1] disconnected. error: undefined
2023-02-24T09:08:33.245Z pw:protocol SEND ► {"id":14,"method":"Browser.setRequestInterception","params":{"browserContextId":"2be0e955-3782-4c1b-951a-db88f76ee078","enabled":false}}
2023-02-24T09:08:33.245Z pw:server [id=1] starting cleanup
2023-02-24T09:08:33.245Z pw:browser [pid=2156] <gracefully close start>
2023-02-24T09:08:43.412Z pw:browser [pid=2156][out] WARNING: At least one completion condition is taking too long to complete. Conditions: [{"name":"Extension shutdown: webcompat@mozilla.org","state":{"state":"Startup: Run manifest, asyncEmitManifestEntry(\"background\")"},"filename":"resource://gre/modules/addons/XPIProvider.jsm","lineNumber":2629,"stack":["resource://gre/modules/addons/XPIProvider.jsm:startup/<:2629","resource://gre/modules/AsyncShutdown.jsm:observe:560","chrome://juggler/content/protocol/BrowserHandler.js:Browser.close:140"]},{"name":"Extension shutdown: webcompat-reporter@mozilla.org","state":{"state":"Startup: Run manifest, asyncEmitManifestEntry(\"background\")"},"filename":"resource://gre/modules/addons/XPIProvider.jsm","lineNumber":2629,"stack":["resource://gre/modules/addons/XPIProvider.jsm:startup/<:2629","resource://gre/modules/AsyncShutdown.jsm:observe:560","chrome://juggler/content/protocol/BrowserHandler.js:Browser.close:140"]},{"name":"Extension shutdown: pictureinpicture@mozilla.org","state":{"state":"Startup: Run manifest, asyncEmitManifestEntry(\"background\")"},"filename":"resource://gre/modules/addons/XPIProvider.jsm","lineNumber":2629,"stack":["resource://gre/modules/addons/XPIProvider.jsm:startup/<:2629","resource://gre/modules/AsyncShutdown.jsm:observe:560","chrome://juggler/content/protocol/BrowserHandler.js:Browser.close:140"]},{"name":"Extension shutdown: formautofill@mozilla.org","state":{"state":"Startup: Run manifest, asyncEmitManifestEntry(\"background\")"},"filename":"resource://gre/modules/addons/XPIProvider.jsm","lineNumber":2629,"stack":["resource://gre/modules/addons/XPIProvider.jsm:startup/<:2629","resource://gre/modules/AsyncShutdown.jsm:observe:560","chrome://juggler/content/protocol/BrowserHandler.js:Browser.close:140"]},{"name":"Extension shutdown: addons-search-detection@mozilla.com","state":{"state":"Startup: Run manifest, asyncEmitManifestEntry(\"background\")"},"filename":"resource://gre/modules/addons/XPIProvider.jsm","lineNumber":2629,"stack":["resource://gre/modules/addons/XPIProvider.jsm:startup/<:2629","resource://gre/modules/AsyncShutdown.jsm:observe:560","chrome://juggler/content/protocol/BrowserHandler.js:Browser.close:140"]}] Barrier: profile-change-teardown
2023-02-24T09:09:03.257Z pw:browser [pid=2156] <kill>
2023-02-24T09:09:03.257Z pw:browser [pid=2156] <will force kill>
2023-02-24T09:09:03.579Z pw:browser [pid=2156] taskkill stdout: SUCCESS: The process with PID 2968 (child process of PID 2220) has been terminated.
SUCCESS: The process with PID 2220 (child process of PID 2156) has been terminated.
SUCCESS: The process with PID 2156 (child process of PID 1988) has been terminated.

2023-02-24T09:09:03.579Z pw:browser [pid=2156] <process did exit: exitCode=1, signal=null>
2023-02-24T09:09:03.579Z pw:browser [pid=2156] starting temporary directories cleanup
2023-02-24T09:09:03.720Z pw:browser [pid=2156] finished temporary directories cleanup
2023-02-24T09:09:03.720Z pw:browser [pid=2156] <gracefully close end>
2023-02-24T09:09:03.720Z pw:server [id=1] finished cleanup
```

**Comment by yury-s** [comment] 2023-02-25 00:02
Does it fail with playwright 1.31.1?

**Comment by sauravlikhar** [comment] 2023-02-25 09:37
I ran the basic test which opens just a single page. Below is the detail about the test -
```
const runSimplePageTest = async (browser: Browser): Promise<string> => {
  const page = await browser.newPage();
  try {
    await page.setContent('<button>Submit</button>');
    await page.locator('button').click();
    return await page.evaluate(() => navigator.userAgent);
  } finally {
    await page.close();
  }
};
test(`should be able to run test on firefox`, async ({ connect, targetOs }) => {
  const browser = await connect('firefox');
  const userAgent = await runSimplePageTest(browser);
  expect(userAgent).toContain('Firefox');
  expect(userAgent.toLowerCase()).toContain(targetOs);
});
```
These are the client side debug logs-
```
 pw:api => selectors.setTestIdAttribute started +0ms
  pw:api => browserType.connect started +28ms
  pw:api <= selectors.setTestIdAttribute succeeded +41ms
  pw:api <= browserType.connect succeeded +11s
  pw:api => browser.newPage started +9ms
  pw:api <= browser.newPage succeeded +832ms
  pw:api => browser.newPage started +20ms
  pw:api => browser.close started +48s
  pw:api <= browser.newPage failed +1ms
  pw:api =>  started +9ms
  pw:api =>  started +4ms
  pw:api <= browser.close succeeded +10ms
  pw:api <=  failed +4ms
  pw:api <=  failed +0ms
```

With 1.31.1, the similar behavior of timeout on first time connection found in the client side. 
The ACI logs are as below in case of 1.31.1-
```
2023-02-25T09:31:10.769Z pw:server [id=1] serving connection: /
2023-02-25T09:31:11.092Z pw:server [id=1] engaged launch mode for "firefox"
2023-02-25T09:31:11.092Z pw:proxy Starting socks proxy server on port 49158
2023-02-25T09:31:11.092Z pw:server [id=1] started socks proxy on port 49158
2023-02-25T09:31:13.471Z pw:browser <launching> C:\Users\ContainerAdministrator\AppData\Local\ms-playwright\firefox-1378\firefox\firefox.exe -no-remote -headless -profile C:\Users\ContainerAdministrator\AppData\Local\Temp\playwright_firefoxdev_profile-KHassQ -juggler-pipe -silent
2023-02-25T09:31:13.471Z pw:browser <launched> pid=3060
2023-02-25T09:31:15.326Z pw:browser [pid=3060][err] *** You are running in headless mode.
2023-02-25T09:31:19.256Z pw:browser [pid=3060][out] 
2023-02-25T09:31:19.272Z pw:browser [pid=3060][out] Juggler listening to the pipe
2023-02-25T09:31:19.272Z pw:protocol SEND ► {"id":1,"method":"Browser.enable","params":{"attachToDefaultContext":false}}
2023-02-25T09:31:19.272Z pw:protocol SEND ► {"id":2,"method":"Browser.getInfo"}
2023-02-25T09:31:19.272Z pw:protocol SEND ► {"id":3,"method":"Browser.setBrowserProxy","params":{"type":"socks","bypass":[],"host":"127.0.0.1","port":49158}}
2023-02-25T09:31:20.725Z pw:protocol ◀ RECV {"id":1}
2023-02-25T09:31:20.725Z pw:protocol ◀ RECV {"id":2,"result":{"version":"Firefox/109.0","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0"}}
2023-02-25T09:31:20.725Z pw:protocol ◀ RECV {"id":3}
2023-02-25T09:31:21.444Z pw:protocol SEND ► {"id":4,"method":"Browser.createBrowserContext","params":{"removeOnDetach":true}}
2023-02-25T09:31:21.553Z pw:protocol ◀ RECV {"id":4,"result":{"browserContextId":"1cf11957-4132-4934-9bd0-219da91e2546"}}
2023-02-25T09:31:21.553Z pw:protocol SEND ► {"id":5,"method":"Browser.setDownloadOptions","params":{"browserContextId":"1cf11957-4132-4934-9bd0-219da91e2546","downloadOptions":{"behavior":"saveToDisk","downloadsDir":"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\playwright-artifacts-vejcL1"}}}
2023-02-25T09:31:21.553Z pw:protocol SEND ► {"id":6,"method":"Browser.setDefaultViewport","params":{"browserContextId":"1cf11957-4132-4934-9bd0-219da91e2546","viewport":{"viewportSize":{"width":1280,"height":720},"deviceScaleFactor":1}}}
2023-02-25T09:31:21.553Z pw:protocol SEND ► {"id":7,"method":"Browser.setLocaleOverride","params":{"browserContextId":"1cf11957-4132-4934-9bd0-219da91e2546","locale":"en-US"}}
2023-02-25T09:31:21.553Z pw:protocol SEND ► {"id":8,"method":"Browser.setExtraHTTPHeaders","params":{"browserContextId":"1cf11957-4132-4934-9bd0-219da91e2546","headers":[{"name":"Accept-Language","value":"en-US"}]}}
2023-02-25T09:31:21.553Z pw:protocol SEND ► {"id":9,"method":"Browser.setColorScheme","params":{"browserContextId":"1cf11957-4132-4934-9bd0-219da91e2546","colorScheme":"light"}}
2023-02-25T09:31:21.553Z pw:protocol SEND ► {"id":10,"method":"Browser.setReducedMotion","params":{"browserContextId":"1cf11957-4132-4934-9bd0-219da91e2546","reducedMotion":"no-preference"}}
2023-02-25T09:31:21.553Z pw:protocol SEND ► {"id":11,"method":"Browser.setForcedColors","params":{"browserContextId":"1cf11957-4132-4934-9bd0-219da91e2546","forcedColors":"none"}}
2023-02-25T09:31:21.600Z pw:browser [pid=3060][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt (t=80.5285) [GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
2023-02-25T09:31:21.881Z pw:protocol ◀ RECV {"id":5}
2023-02-25T09:31:21.881Z pw:protocol ◀ RECV {"id":6}
2023-02-25T09:31:21.959Z pw:protocol ◀ RECV {"id":7}
2023-02-25T09:31:21.959Z pw:protocol ◀ RECV {"id":8}
2023-02-25T09:31:21.959Z pw:protocol ◀ RECV {"id":9}
2023-02-25T09:31:21.959Z pw:protocol ◀ RECV {"id":10}
2023-02-25T09:31:21.959Z pw:protocol ◀ RECV {"id":11}
2023-02-25T09:31:21.959Z pw:browser [pid=3060][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
2023-02-25T09:31:22.381Z pw:protocol SEND ► {"id":12,"method":"Browser.newPage","params":{"browserContextId":"1cf11957-4132-4934-9bd0-219da91e2546"}}
2023-02-25T09:31:28.256Z pw:protocol ◀ RECV {"method":"Browser.attachedToTarget","params":{"sessionId":"66b9d8e0-cd54-4433-b851-4077078c05a8","targetInfo":{"targetId":"1f69bc0f-c4a9-40c9-8318-7e23833f20d0","type":"page","browserContextId":"1cf11957-4132-4934-9bd0-219da91e2546"}}}
2023-02-25T09:31:28.256Z pw:protocol SEND ► {"method":"Page.setInitScripts","params":{"scripts":[{"script":"","worldName":"__playwright_utility_world__"}]},"id":13,"sessionId":"66b9d8e0-cd54-4433-b851-4077078c05a8"}
2023-02-25T09:31:30.397Z pw:browser [pid=3060][out] console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\playwright_firefoxdev_profile-KHassQ\\search.json.mozlz4", (void 0)))
2023-02-25T09:31:30.397Z pw:protocol ◀ RECV {"id":12,"result":{"targetId":"1f69bc0f-c4a9-40c9-8318-7e23833f20d0"}}
2023-02-25T09:31:30.475Z pw:browser [pid=3060][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
2023-02-25T09:31:30.475Z pw:browser [pid=3060][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
2023-02-25T09:31:30.475Z pw:browser [pid=3060][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
2023-02-25T09:31:31.225Z pw:browser [pid=3060][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
2023-02-25T09:31:31.272Z pw:browser [pid=3060][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
2023-02-25T09:31:31.397Z pw:browser [pid=3060][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
2023-02-25T09:31:31.412Z pw:browser [pid=3060][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
2023-02-25T09:31:31.428Z pw:browser [pid=3060][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
2023-02-25T09:31:31.428Z pw:browser [pid=3060][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
2023-02-25T09:31:31.522Z pw:browser [pid=3060][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
2023-02-25T09:32:10.421Z pw:server [id=1] disconnected. error: undefined
2023-02-25T09:32:10.421Z pw:protocol SEND ► {"id":14,"method":"Browser.setRequestInterception","params":{"browserContextId":"1cf11957-4132-4934-9bd0-219da91e2546","enabled":false}}
2023-02-25T09:32:10.421Z pw:server [id=1] starting cleanup
2023-02-25T09:32:10.421Z pw:browser [pid=3060] <gracefully close start>
2023-02-25T09:32:20.567Z pw:browser [pid=3060][out] WARNING: At least one completion condition is taking too long to complete. Conditions: [{"name":"Extension shutdown: webcompat@mozilla.org","state":{"state":"Startup: Run manifest, asyncEmitManifestEntry(\"background\")"},"filename":"resource://gre/modules/addons/XPIProvider.jsm","lineNumber":2629,"stack":["resource://gre/modules/addons/XPIProvider.jsm:startup/<:2629","resource://gre/modules/AsyncShutdown.jsm:observe:572","chrome://juggler/content/protocol/BrowserHandler.js:Browser.close:140"]},{"name":"Extension shutdown: webcompat-reporter@mozilla.org","state":{"state":"Startup: Run manifest, asyncEmitManifestEntry(\"background\")"},"filename":"resource://gre/modules/addons/XPIProvider.jsm","lineNumber":2629,"stack":["resource://gre/modules/addons/XPIProvider.jsm:startup/<:2629","resource://gre/modules/AsyncShutdown.jsm:observe:572","chrome://juggler/content/protocol/BrowserHandler.js:Browser.close:140"]},{"name":"Extension shutdown: pictureinpicture@mozilla.org","state":{"state":"Startup: Run manifest, asyncEmitManifestEntry(\"background\")"},"filename":"resource://gre/modules/addons/XPIProvider.jsm","lineNumber":2629,"stack":["resource://gre/modules/addons/XPIProvider.jsm:startup/<:2629","resource://gre/modules/AsyncShutdown.jsm:observe:572","chrome://juggler/content/protocol/BrowserHandler.js:Browser.close:140"]},{"name":"Extension shutdown: formautofill@mozilla.org","state":{"state":"Startup: Run manifest, asyncEmitManifestEntry(\"background\")"},"filename":"resource://gre/modules/addons/XPIProvider.jsm","lineNumber":2629,"stack":["resource://gre/modules/addons/XPIProvider.jsm:startup/<:2629","resource://gre/modules/AsyncShutdown.jsm:observe:572","chrome://juggler/content/protocol/BrowserHandler.js:Browser.close:140"]},{"name":"Extension shutdown: addons-search-detection@mozilla.com","state":{"state":"Startup: Run manifest, asyncEmitManifestEntry(\"background\")"},"filename":"resource://gre/modules/addons/XPIProvider.jsm","lineNumber":2629,"stack":["resource://gre/modules/addons/XPIProvider.jsm:startup/<:2629","resource://gre/modules/AsyncShutdown.jsm:observe:572","chrome://juggler/content/protocol/BrowserHandler.js:Browser.close:140"]}] Barrier: profile-change-teardown
2023-02-25T09:32:40.426Z pw:browser [pid=3060] <kill>
2023-02-25T09:32:40.426Z pw:browser [pid=3060] <will force kill>
2023-02-25T09:32:40.987Z pw:browser [pid=3060] taskkill stdout: SUCCESS: The process with PID 560 (child process of PID 3060) has been terminated.
SUCCESS: The process with PID 3060 (child process of PID 1552) has been terminated.

2023-02-25T09:32:40.987Z pw:browser [pid=3060] <process did exit: exitCode=1, signal=null>
2023-02-25T09:32:40.987Z pw:browser [pid=3060] starting temporary directories cleanup
2023-02-25T09:32:41.127Z pw:browser [pid=3060] finished temporary directories cleanup
2023-02-25T09:32:41.127Z pw:browser [pid=3060] <gracefully close end>
2023-02-25T09:32:41.127Z pw:server [id=1] finished cleanup
```

**Comment by mxschmitt** [comment] 2023-02-27 18:24
Can you provide us your Dockerfile / your Docker base image?

This looks like a duplicate of https://github.com/microsoft/playwright/issues/13679 so lets re-open this one instead and continue the discussion there?

**Comment by sauravlikhar** [comment] 2023-02-28 06:19
This is the Dockerfile - 
```
FROM mcr.microsoft.com/windows:1809

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ADD https://aka.ms/downloadazcopy-v10-windows C:/setup/azcopy.zip
RUN cd C:/ ; \
    mkdir usr\bin; \
    Expand-Archive C:/setup/azcopy.zip -DestinationPath C:\ ; \
    $filename = (Get-ChildItem azcopy_windows_amd64_*).Name; \
    Copy-Item -Path C:\$filename\azcopy.exe -Destination C:usr\bin\ -verbose;

ENV NODE_VERSION 14.17.3

RUN Invoke-WebRequest -OutFile 'node.zip' -UseBasicParsing "https://nodejs.org/dist/v14.17.3/node-v14.17.3-win-x64.zip"; \
    Expand-Archive node.zip -DestinationPath C:\ ; \
    Rename-Item -Path 'C:\node-v14.17.3-win-x64' -NewName 'C:\nodejs'

USER ContainerAdministrator
RUN [Environment]::SetEnvironmentVariable('Path', $env:Path + ';C:\nodejs', 'Machine')

ADD https://aka.ms/vs/16/release/vc_redist.x64.exe C:/setup/vc_redist.x64.exe
RUN C:/setup/vc_redist.x64.exe /install /quiet /norestart

WORKDIR /usr/src/app

RUN npm init -y
RUN npm install playwright@1.31.1
RUN Set-ExecutionPolicy -ExecutionPolicy Unrestricted

RUN npx playwright install-deps
RUN npx playwright install-deps chromium
RUN npx playwright install-deps firefox
RUN npx playwright install-deps webkit

RUN Set-ExecutionPolicy -ExecutionPolicy Restricted

ENV DEBUG "pw:*"
CMD npx playwright run-server --port 8090 --max-clients 1
```

**Comment by mxschmitt** [comment] 2023-02-28 09:20
As per offline discussion:

> This image is working mcr.microsoft.com/windows/server:ltsc2022

**Comment by mxschmitt** [comment] 2023-03-01 14:36
As per offline discussion, the team migrated to the image above, so the issue is resolved by that.

**Closed by mxschmitt** 2023-03-01 14:36 UTC
Labels: browser-firefox, v1.32
