### ISSUE TITLE
[BUG] Getting distorted page in headless mode in chromium

### ISSUE THREAD

**Issue by pavannadgir** [microsoft/playwright#20910] opened 2023-02-15 07:11 UTC
**Context:**
- Playwright Version: 1.30.0
- Operating System: Windows
- Node.js version: 16.6.0
- Browser: Chromium
- Extra: NextJS 13

I am trying to upgrade nextJS from 12 to 13.For some of the e2e tests, the page is getting distorted and are failing with a timeout. This is happening only in chrome and in headless mode. Same tests work fine in headed mode in chrome. Tests work fine in firefox and webkit in both headed and headless mode. Tried downgrading playwright from 1.30.0 to 1.27.0 but getting the same results.

![test-failed-2](https://user-images.githubusercontent.com/17080266/218952565-ced09a47-ac88-441d-a287-c68461f4f57b.png)

**Comment by aslushnikov** [comment] 2023-02-15 18:18
@pavannadgir does it reproduce 100% of times for you? Can you do a minimal repro that reproduces this behavior?

**Comment by pavannadgir** [comment] 2023-02-16 10:21
@aslushnikov I am seeing this issue for one specific page at the moment and I am able to reproduce it 100% of times for that page. The page breaks as soon as we navigate using `goto()`.However, `goto()` is working fine at all the other places that its used. Here's a the test case code:

```
it('filters by brand and deletes facet', async ({ page, pom }) => {
  await pom.navbar.bypassLocation()
  await pom.srp.goto('water')
  //page breaks after navigation to the search results page(srp) because of which anything added after goto fails with a timeout
})

//goto method
async goto(
    term = 'water',
    focus:
      | 'products'
      | 'buildingblocks'
      | 'genes'
      | 'papers'
      | 'documents'
      | 'sitecontent' = 'products',
    pageNo = 1
  ) {
    let type: 'product' | 'gene' | 'citation_search' | 'site_content'
    switch (focus) {
      case 'products':
        type = 'product'
        break
      case 'buildingblocks':
        type = 'product'
        break
      case 'genes':
        type = 'gene'
        break
      case 'papers':
        type = 'citation_search'
        break
      case 'documents':
        type = 'site_content'
        break
      case 'sitecontent':
        type = 'site_content'
        break
      default:
        type = 'product'
    }

    const url = `/search/${term}?focus=${focus}&page=${pageNo}&perPage=30&sort=relevance&term=${term}&type=${type}`
    await this.page.goto(url)
  }
```

**Comment by aslushnikov** [comment] 2023-02-17 16:40
@pavannadgir unfortunately your code snippet doesn't tell much; and I cannot run it locally to try reproducing. Any chance you can provide an actual repro?

But overall, this looks like a chromium bug. Does it repro on newer / older chromium versions?

**Comment by aslushnikov** [comment] 2023-02-21 15:57
Overall, it doesn't look like there's an action item for Playwright team to do here, so I'll close this issue.

However, please do not hesitate to file a new issue if you think we still can be helpful!

**Closed by aslushnikov** 2023-02-21 15:57 UTC
Labels: triaging
