### ISSUE TITLE
[Question] How to configure tsconfig.json to check the ts files and prevent test run in case we have compilation error

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#13719] opened 2022-04-24 16:31 UTC
Hi there,

I would like to ask if there is an option to configure the **tsconfig.json** to check the ts files and prevent a test run in case we have a compilation error. 
When I worked with JAVA + SELENIUM, in case of any compilation error, I have been noticed the compilation error and until it wasn't fixed - the run of the tests was not possible. 
In my current case with Typescript and Playwright - I have a compilation error/s, but the run is starting as well (see the attached video).

https://user-images.githubusercontent.com/52656401/164986447-cb7fa93a-b4f2-40ce-ac21-e3f765285a1b.mp4

My tsconfig.json has the following content:

```javascript
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "sourceMap": true,
    "resolveJsonModule": true,
    "strict": true
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by rwoll** [comment] 2022-04-24 23:11
This is by design. Playwright Test will transform your TS to JS to run it, but it won't enforce the typechecking. If you want to perform a typecheck, run `tsc --no-emit …` before you run your test.

You could change `"test"` script in your package.json to be something like `tsc --no-emit … && playwright test …`.

**Comment by AlexKomanov** [comment] 2022-04-25 05:48
Thanks, @rwoll!
Is this the only one option to enable this check? 
Can I configure something similar in the `tsconfig.json` file?

**Comment by pavelfeldman** [comment] 2022-04-27 21:22
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2022-04-27 21:22 UTC
Labels: triaging
