### ISSUE TITLE
[BUG] Firefox seems to do nothing and eventually times out

### ISSUE THREAD

**Issue by jrieken** [microsoft/playwright#842] opened 2020-02-05 10:42 UTC
**Context:**
- Playwright Version: 0.10.0
- Operating System: Mac

**Code Snippet**

We are now using playwright to run a subset of our VSCode unit tests inside different browser types. The "steps" are this

* clone vscode from `https://github.com/microsoft/vscode` and run `yarn`
* run `node test/browser/index.js --browser chromium` and see how tests success and fail
* run `node test/browser/index.js --browser firefox` and nothing happens...

At the heard of this we load mocha inside a webpage which gets our AMD loader and other things ready (this page loads without issues inside firefox). Then we use [`page.evaluate`](https://github.com/microsoft/vscode/blob/2ce6f5115e7fdb83c11e267566b60b8f1cf4ea00/test/browser/index.js#L111) to tell the page what modules to load and to start tests. Tests communicate back to the node-process via [`page.exposeFunction`](https://github.com/microsoft/vscode/blob/2ce6f5115e7fdb83c11e267566b60b8f1cf4ea00/test/browser/index.js#L99)-ed function using a special mocha reporter [implementation](https://github.com/microsoft/vscode/blob/874f759bbe6f591a176bee851f345911fe16b4eb/test/browser/renderer.html#L92).

**Describe the bug**

All of the above works fine in webkit and chromium but does seemingly nothing in firefox...

**Comment by enjikaka** [comment] 2020-02-05 17:44
Also seeing Firefox just freezing here. However I also get a yellow notification on the top saying that Firefox is installing components to play audio and video. (Widevine)

**Comment by pavelfeldman** [comment] 2020-02-05 18:55
@jrieken :wave:

This looks like a dupe of https://github.com/microsoft/playwright/issues/822

We assume tests are serving from the localhost to use fetch and other web features. We'll be addressing #822, but for now if you have a way to serve your test, it would mitigate it.

**Closed by pavelfeldman** 2020-02-05 18:55 UTC

**Comment by jrieken** [comment] 2020-02-06 09:28
Yeah, that's exactly it: https://github.com/microsoft/vscode/blob/93379d00b1a42ae2e00215fd3075dfe9e915da78/test/browser/index.js#L100
