### ISSUE TITLE
[BUG] Playwright Chrome Instance is working very slow in MAC

### ISSUE THREAD

**Issue by Santhosh-kumar21** [microsoft/playwright#23914] opened 2023-06-27 07:10 UTC
### System info
- Playwright Version: [v1.34] 
- Programming Language: Java
- Operating System: Mac os 12.2
- Browser: Chromium 114.0.5735.133 (Official Build) (arm64)
- Other info: 

**Steps**
- Launch the Chromium instance through playwright
- Launch any site(google.com) or open Developer Tools 

**Expected**
Launched Site or Developer Tools should open quickly as like as opening in normal chrome browser

**Actual**
Compared to normal chrome instance. Page load time is 5X slower in playwright chromium instance and also developer tools takes so much time to load.

Note: We are facing this issue only in MAC. Working fine in Windows and LINUX 
**Steps Already checked** 
I have deleted the old ms.playwright folder from caches folder and updated the playwright version to 1.34. With the new driver also facing the same slowness

**Comment by mxschmitt** [comment] 2023-06-27 14:16
Could you execute the following command and provide us the output to make sure you have the arm Chromium installed?

```
file /Users/$USER/Library/Caches/ms-playwright/chromium-*/chrome-mac/Chromium.app/Contents/MacOS/Chromium
```

Also

```
java -version
```

might be helpful, to see which Java you have installed, and if its emulated with Rosetta or not.

**Comment by Santhosh-kumar21** [comment] 2023-06-28 06:25
<img width="1045" alt="image" src="https://github.com/microsoft/playwright/assets/55554896/b5563d5a-60c0-4db8-8e1b-623350559b40">
<img width="905" alt="image" src="https://github.com/microsoft/playwright/assets/55554896/ede44309-26aa-4164-9616-c9ee3a976edb">
I have attached the screenshot of the commands which you have asked and my laptop chip is Apple M1 Pro, so i'm not using Rosetta.

**Comment by mxschmitt** [comment] 2023-06-28 08:09
With Rosetta I meant Rosetta emulated. Apple Silicon chips are able to execute x64 binaries by emulating them. This is slow but works and would explain your performance regressions.

It looks like that your Java is either a universal or x64 binary, you can check it by executing `file $(which java)`. Chromium in your case looks good, its arm64.

In my case I have OpenJDK and `-version` ends up this, you could try out the following too (just to make sure the issues are not coming from Java):

```
➜  playwright-nested git:(main) ✗ java -version
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Zulu 8.68.0.21-CA-macos-aarch64) (build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (Zulu 8.68.0.21-CA-macos-aarch64) (build 25.362-b09, mixed mode)
```

So the next steps I recommend are:
- Make sure its not caused by the Java, so I'd try it with OpenJDK
- Try to upgrade to Playwright 1.35, seems like you are using 1.34.
- Can you try to launch the browser directly without Playwright, so just double click `/Users/sohaib.baig/Library/Caches/ms-playwright/chromium-1064` so we can make sure its not a Java issue.
- You can also execute `sysctl -n sysctl.proc_translated` inside your terminal. If its 0, its native, and 1 its Rosetta (see [here](https://stackoverflow.com/a/67690510/6512681))

**Comment by Santhosh-kumar21** [comment] 2023-06-28 09:25
Sure, I will check those items. meantime i have launched chrome from the below path without using code

**Library/Caches/ms-playwright/chromium-1064** , here i don't find any slowness in the browser, so i have commented out the setChannel('chrome') from my code and executed the tests. After the channel change i don't see any slowness with the Chromium instance in the test automation.

**Comment by mxschmitt** [comment] 2023-06-28 10:00
Oh then there was a miss-understanding. So its not about our Chromium, its about using Google Chrome.

Then thats most likely not caused by us, since we just re-use the official Google Chrome which gets shipped as a universal binary: `file /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome`

universal binary = a single executable which contains the binary for both architectures

```
➜  playwright-nested git:(main) ✗ file /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome 
/Applications/Google Chrome.app/Contents/MacOS/Google Chrome: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
/Applications/Google Chrome.app/Contents/MacOS/Google Chrome (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Applications/Google Chrome.app/Contents/MacOS/Google Chrome (for architecture arm64):	Mach-O 64-bit executable arm64
```

See how the output looks like here for me. Also you can verify that Google Chrome runs correctly by navigating to `chrome://version/`. In the first line at the end it should say: arm64.

**Comment by Santhosh-kumar21** [comment] 2023-06-28 10:39
Got it. I have checked the binary arch of chrome and the version of chrome opened through playwright (Screenshots are attached) . The opened chrome instance version is x86_64 and i believe that's the reason for slowness. 
Do you suggest any way to switch it to the arm64 ? 
<img width="1447" alt="image" src="https://github.com/microsoft/playwright/assets/55554896/625f447c-8666-405e-be30-9fb91387b525">
<img width="1286" alt="image" src="https://github.com/microsoft/playwright/assets/55554896/aa69a5a3-e892-44b3-b811-83c9f0f08487">

**Comment by mxschmitt** [comment] 2023-06-28 11:16
> The opened chrome instance version is x86_64 and i believe that's the reason for slowness.

That sounds very plausible.

So what I recommend now are the following things:

1. Check if your Terminal is Rosetta emulated by running `sysctl -n sysctl.proc_translated`. 0 = not, 1 is yes.
2. Make sure that Google Chrome has not set the "Emulate using Rosetta" flag in the File info (for that go to Applications, Google Chrome, right click and make sure its unchecked the checkbox, or not there at all) see [here](https://forums.macrumors.com/threads/chrome-keeps-reverting-from-arm64-to-x86_64-translated-on-m1-macbook-pro.2302626/)
3. If none of that works, I'd recommend trying a native arm64 build instead, e.g. the [Zulu Java builds from Azul](https://www.azul.com/downloads/?os=macos&architecture=arm-64-bit&package=jdk#zulu) which we recommend. [Microsoft's Build of OpenJDK](https://learn.microsoft.com/en-us/java/openjdk/download) should probably also work.

**Comment by aslushnikov** [comment] 2023-07-03 14:23
Looks like the issue is solved; closing as per discussion above.

**Closed by aslushnikov** 2023-07-03 14:23 UTC
Labels: triaging
