### ISSUE TITLE
[BUG] use webkit add a proxy got an error

### ISSUE THREAD

**Issue by Faye-dirzzle** [microsoft/playwright#22184] opened 2023-04-04 09:29 UTC
**Context:**
- Playwright Version: 1.32.1
- Operating System: Windows
- Python version: 3.7
- Browser: WebKit

**Code Snippet**

```python
from playwright.sync_api import sync_playwright
import time


def run(pw):
    webkit = pw.webkit
    browser = webkit.launch(
        headless=False,
        proxy={'server': 'xxxxx', 'username': 'xxxxx', 'password': 'xxxxx'},
    )
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://www.google.com", timeout=1000 * 30)
    print('===================================================================================')


with sync_playwright() as pw:
    run(pw)
    time.sleep(1000)
```

**Describe the bug**

use webkit add a proxy got an error(navigating to "https://www.google.com", waiting until "load"),
but chromium is ok，help！！！

**Comment by pavelfeldman** [comment] 2023-04-04 15:31
We need exact steps to perform in order to reproduce this problem locally.

**Comment by Faye-dirzzle** [comment] 2023-04-05 02:53
> Looks like your proxy is not functioning or google.com does not like the proxy.
Proxy is works and this problem occurs with all sites

**Comment by Faye-dirzzle** [comment] 2023-04-05 02:55
> We need exact steps to perform in order to reproduce this problem locally.
Mount the proxy, open the browser and back off in seconds, you can use the environment I described, and then try another proxy.

**Comment by mxschmitt** [comment] 2023-04-05 08:42
We don't have a proxy to test with, so we can't reproduce ourselves. Can you provide us a proxy which works in Chrome and Firefox but does not work with WebKit?

**Comment by pavelfeldman** [comment] 2023-04-07 22:34
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Closed by pavelfeldman** 2023-04-07 22:34 UTC
Labels: triaging

**Comment by Faye-dirzzle** [comment] 2023-07-24 12:53
> I suppose this might be an upstream bug ticket: https://bugs.webkit.org/show_bug.cgi?id=257705

It's also possible
