### ISSUE TITLE
[BUG] fullPage chromium screenshot / missing elements at page end

### ISSUE THREAD

**Issue by aheissenberger** [microsoft/playwright#5487] opened 2021-02-17 22:44 UTC
**Context:**
- Playwright Version: 1.8.1
- Operating System: Docker Desktop MacOS / mcr.microsoft.com/playwright:focal
- Browser: Chromium

**System:**
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
    Memory: 982.02 MB / 2.93 GB
    Container: Yes
**Binaries:**
    Node: 14.15.5 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.5.4 - /usr/bin/npm
**Languages:**
    Bash: 5.0.17 - /usr/bin/bash
**npmPackages:**
    playwright: ^1.8.1 => 1.8.1 

**Problem**
* fullPage screen shots with chromium will miss elements at page end when viewport `width <= 800 px` (attache screenshot `chromium_w800px_broken.png` and `chromium_w801px_ok.png`)
* the problem exists when using devices e.g. iPhone for context setup
* there is **no problem with firefox and webkit** (attache screenshot `firefox_w800px_ok.png`)
* there is no problem when screenshot is done per command line 
   `npx playwright screenshot --full-page --device="iPhone 6"  https://www.ichkoche.at/ ichkocheat.png`
* I tried `mcr.microsoft.com/playwright:focal` but no improvement

**Screens:**
<table>
<tr>
<td>chromium_w800px_broken.png<br/><img src="https://user-images.githubusercontent.com/200095/108276654-70f43980-7178-11eb-84e2-e165c44d96a5.png" width="100" height="100"></td>
<td>chromium_w801px_OK.png<br/><img src="https://user-images.githubusercontent.com/200095/108276659-72bdfd00-7178-11eb-8ba8-c16aa22acaac.png" width="100" height="100"></td>
<td>firefox_w800px_ok<br/><img src="https://user-images.githubusercontent.com/200095/108276662-73569380-7178-11eb-87a1-a3206c20b49a.png" width="100" height="100"></td>
</tr>
</table>

```javascript
const { chromium, devices } = require('playwright');

(async () => {
    const browser = await chromium.launch();
    const context = await browser.newContext()
    const page = await context.newPage();
    await page.setViewportSize({ width:800, height: 800 })

    await page.route('**/gdpr-liveramp.js', (route) => {
        return route.abort()
    })

    await page.goto('https://www.ichkoche.at/');

    await page.screenshot({ fullPage: true, path: `chromium_w800px_broken.png` });
    await browser.close();
})();
```
width to `await page.setViewportSize({ width:801, height: 800 })` or using `firefox.launch()` produces a valid result.

**Comment by aslushnikov** [comment] 2021-02-18 22:26
@aheissenberger This is an upstream chromium issue. Taking a full page screenshot using Chrome Developer Tools gives me the same screenshot with blank footer. I filed this upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=1179898

An interesting observation is that's a 50em media query in the CSS style that doesnt' apply once you change width to 801px. It seems to be somehow connected to the behavior, but I didn't find anything strange about the CSS rules it applies to the footer. 🤷‍♂️

**Comment by dgozman** [comment] 2021-03-02 21:01
@aheissenberger I played with this particular issue. It seems like `https://www.ichkoche.at/` insists on the footer being under the fold, no matter how large you resize the window. You can try for yourself by opening Chrome DevTools, toggling device toolbar and setting something like 800x6000. Unfortunately, resizing is how we take fullPage screenshots in Chromium, so I do not expect this to be fixed in the near future.

**Comment by aheissenberger** [comment] 2021-03-04 09:03
> @aheissenberger I played with this particular issue. It seems like `https://www.ichkoche.at/` insists on the footer being under the fold, no matter how large you resize the window. You can try for yourself by opening Chrome DevTools, toggling device toolbar and setting something like 800x6000. Unfortunately, resizing is how we take fullPage screenshots in Chromium, so I do not expect this to be fixed in the near future.

@dgozman your are right - it is the `page_wrap` container before the `page_footer` container which is set to `min-height: 100%` which is pushing the footer container always outside the viewport. Combined with the media query 800px and smaller this explains the result

**Closed** 2021-03-04 09:03 UTC
Labels: P2-bug, browser-chromium, upstream

**Comment by sqandrew** [comment] 2022-02-11 13:07
the same issue reproduced in the last release (we updated the playwright feb 09 2022)

iPhone 12 (< 800 px height) - full screen is not full
iPhone X (> 800 px height) - full screen is OK
