### ISSUE TITLE
[Bug]: Annotations are showed (html report) only for last retry (test.info().annotations.push)

### ISSUE THREAD

**Issue by OlegsHanins** [microsoft/playwright#32411] opened 2024-09-02 09:55 UTC
### Version

1.46.0

### Steps to reproduce

Push to annotations fixture

```javascript
export const test = base.extend<UserFixtures>({

  user: async ({}, use) => {
    const user = new ProductUser();

    test.info().annotations.push({
      type: `Test client data (#${test.info().retry})`,
      description: `Document ID:  ${user.documentId}; Phone number: ${user.phoneNumber}`
    });

    await use(user);
  }
});

type User = {
  user: ProductUser;
};
```

When playwright configured to have retries.

```
retries: 1
```

In html report I see only what is pushed with last retry.

First run fails

![Screenshot 2024-09-02 at 12 36 45](https://github.com/user-attachments/assets/9f3b2fa1-f920-48a0-a784-a171b14151e1)

Second run passed

![Screenshot 2024-09-02 at 12 36 24](https://github.com/user-attachments/assets/6f424f64-6377-4398-9c0e-872842903118)

But I still see only annotations from last test execution

### Expected behavior

I expect to see annotation from each retry

### Actual behavior

Create fixture for example above
Push to annotations

```
    test.info().annotations.push({
      type: `Test annotation type (#${test.info().retry})`,
      description: `Test annotation description (#${test.info().retry})`
    });
```

Call the fixture in test

Make sure your test fails several and you have enabled retries.

See html report only includes annotation from last retry

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 81.73 MB / 16.00 GB
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
  IDEs:
    VSCode: 1.92.2 - /opt/homebrew/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.46.0 => 1.46.0
```

**Comment by dgozman** [comment] 2024-09-03 07:13
Duplicate of #30188. We recommend to use annotations for static data and attachments for anything that changes from run to run.

**Closed by dgozman** 2024-09-03 07:13 UTC
