### ISSUE TITLE
[Bug]: Playwright Test for VSCode endlessly spawning 'node' subprocesses and overloading system memory on MacOS

### ISSUE THREAD

**Issue by bdugg-91** [microsoft/playwright#32688] opened 2024-09-18 14:24 UTC
### Version

latest

### Steps to reproduce

1. Install Playwright Test for VSCode
2. Restart VSCode
3. Open MacOS Activity Monitor
4. Observe 'node' processes spawning and slowly filling system memory until crash

### Expected behavior

Unnecessary `node` processes do not spawn, and system does not crash.

### Actual behavior

`node` processes infinitely spawn and begin filling all available memory until system crashes

![memory-overload](https://github.com/user-attachments/assets/c8098636-a570-44bb-b2dc-fcffe628d386)

### Environment

```shell
System:
    OS: macOS 14.7
    Memory: 212.03 MB / 16.00 GB
  Binaries:
    Node: 16.11.0 - ~/.nvm/versions/node/v16.11.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v16.11.0/bin/yarn
    npm: 10.8.3 - ~/code/syndio/admincenter-fe/node_modules/.bin/npm
  Languages:
    Bash: 5.2.26 - /opt/homebrew/bin/bash
```

**Comment by makker** [comment] 2024-09-21 13:48
I'm experiencing the same issue. This started when I yesterday wanted to try out Playwright. Installed the NPM package with `npm init playwright@latest` and installed the VS extension (Playwright Test for VSCode v1.1.7). After few minutes Mac OS (Sonoma v.14.5) told that system is running out of application memory and I should close apps. Closing the applications doesn't help. OS will crash in few minutes and reboot and this starts again.

What seems to originally start the spawning of node processes is opening the Playwright Test for VSCode `Test Explorer`. Not sure if relevant, but the "loading..." status just stays there in the Test Explorer . See screen cap:
<img width="361" alt="Näyttökuva 2024-09-21 kello 16 25 17" src="https://github.com/user-attachments/assets/f6f39a78-6c00-44bd-9887-303ffb334e57">

I noticed that after system reboots I don't even need to start VS Code to reproduce the problem. 

Finally I was able to kill all the node processes by remove the playwright config or the `node_modules` folder from the project. This removes the issue, but isn't of course permanent solution if i'd like to use Playwright. To reproduce the issue again just need to return the removed Playwright config and the node processes keep spawning and crash the system in minutes. The issue doesn't reproduce if I disable the extension before returning the files. But disabling extension doesn't help, if the processes have already started to spawn.

**Comment by bdugg-91** [comment] 2024-09-24 18:58
That's interesting, I might try it again with an updated node environment. That's convenient if that fixes it as we're currently in the process of updating our project from node 16 to node 20 anyways.

**Comment by mxschmitt** [comment] 2024-09-24 19:05
Playwright does not support Node.js 16 anymore as per https://playwright.dev/docs/intro#system-requirements.

@bdugg-91 can you reproduce this on a [fresh project](https://playwright.dev/docs/intro)? We need something which we can run locally or reproduction steps in order to act on it.

**Comment by mxschmitt** [comment] 2024-10-01 14:35
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.

**Closed by mxschmitt** 2024-10-01 14:35 UTC

**Comment by bdugg-91** [comment] 2024-10-02 21:05
My apologies for the delayed response. It's fine to close, it was definitely related to using node 16 and the issue was resolved by using a newer node version.

**Comment by makker** [comment] 2024-10-03 07:39
So, users can't have Node.js version 16 as their NVM default if they want to use Playwright? Otherwise their OS (Mac) will keep crashing? How come Playwright gets to direct the user's default Node version? 
I understand that Playwright is not supported by Node 16, but is quite extreme letting systems crash without warning.
How about preventing playwright running with unsupported node version and showing an error?
Did you try reproducing the issue by having Node 16 as the NVM default?

**Comment by bdugg-91** [comment] 2024-10-03 17:47
I believe they can still use Playwright with Node 16, the issue just seems to be with the VSCode Extension for what it's worth.

**Comment by Pausejo** [comment] 2024-12-11 12:15
Hi there,

I’m also experiencing this issue with Node 20 and @playwright/test version 1.43.1.

At first, I thought it was a problem with Playwright itself. However, after uninstalling the extension, everything seems to work fine.

You can reproduce this having the extension and cloning this template i found: https://github.com/Mnigos/nuxt3-template, but important, @playwright/test package must be updated to 1.43.1. 

I hope this helps!

**Comment by AimenKhalidArbisoft** [comment] 2024-12-13 11:15
I was having the same issue. I uninstalled the extension 2 days ago. The issue appeared again today and I don't have the extension installed. I used the command `ps -p pid -o command` with the pid of one of the node processes and got this:

`/Users/name/.nvm/versions/node/v16.0.0/bin/node --no-warnings --experimental-loader=file:///Users/name/Documents/project/e2e/node_modules/playwright/lib/transform/esmLoader.js --no-warnings --experimental-loader`

**Comment by Aimen-Khalid** [comment] 2024-12-13 11:16
I was having the same issue. I uninstalled the extension 2 days ago. The issue appeared again today and I don't have the extension installed. I used the command `ps -p pid -o command` with the pid of one of the node processes and got this:

`/Users/name/.nvm/versions/node/v16.0.0/bin/node --no-warnings --experimental-loader=file:///Users/name/Documents/project/e2e/node_modules/playwright/lib/transform/esmLoader.js --no-warnings --experimental-loader`

**Comment by mxschmitt** [comment] 2024-12-13 14:19
> I was having the same issue. I uninstalled the extension 2 days ago. The issue appeared again today and I don't have the extension installed. I used the command `ps -p pid -o command` with the pid of one of the node processes and got this:
> 
> `/Users/name/.nvm/versions/node/v16.0.0/bin/node --no-warnings --experimental-loader=file:///Users/name/Documents/project/e2e/node_modules/playwright/lib/transform/esmLoader.js --no-warnings --experimental-loader`

Make sure to use latest Node.js 22.X and latest Playwright. Then things should work

**Comment by mxschmitt** [comment] 2024-12-16 15:18
> Same issue here with node 18, @playwright/test 1.49.1 and the latest version of the vscode playwright extension. Uninstalling the extension fixes the issues. Could this issue be reopened?

Could you file a new issue with reproduction steps? Ideally you start with our [Getting Started](https://playwright.dev/docs/intro) and see if it reproduces there. Thank you! We usually don't monitor closed issues.

**Comment by Cporter97** [comment] 2025-01-29 12:54
@mxschmitt was a new issue opened?
