### ISSUE TITLE
[Bug]: Downloading to a specific location was working before the Chrome update, but now it's showing a download popup.

### ISSUE THREAD

**Issue by mani9786** [microsoft/playwright#31065] opened 2024-05-29 12:16 UTC
### Version

1.41.1

### Steps to reproduce

Download download = page.waitForDownload(() -> {
    // Perform the action that initiates download
    page.getByText("Download file").click();
});

// Wait for the download process to complete and save the downloaded file somewhere
download.saveAs(Paths.get("/path/to/save/at/", download.suggestedFilename()));

### Expected behavior

it's should download on particular locations where user specified.

### Actual behavior

Download popup is showing 

### Environment

```shell
Window's OS system :  Windows 11 Enterprise


Chrome Version : Version 125.0.6422.78

Playwright Version : playwright-1.40.0
```

**Comment by dgozman** [comment] 2024-05-29 15:32
@mani9786 Could you please share the full repro that we can run locally? We need to be able to reproduce the issue in order to fix it.

**Comment by mani9786** [comment] 2024-05-30 03:57
On the UI page, I have an attachment that I need to download to a specific location on my local system, for example, D:/Documents. This is the expected behavior. However, after clicking on the download icon, a Windows download popup is shown. I have attached the screenshot. 

I have used download the  below code for location specific

download.saveAs(Paths.get("/path/to/save/at/", download.suggestedFilename()));

![Downloadimage](https://github.com/microsoft/playwright/assets/17089075/14f32eb9-8a8d-472b-acd2-6603a3cbdd11)

**Comment by dgozman** [comment] 2024-05-30 15:31
@mani9786 I understand the problem you are facing, but we still need a full repro. A single line of code is not a repro - I cannot just run that line to reproduce the issue. We need a full source code that has this problem to be able to debug it.

**Comment by mani9786** [comment] 2024-05-31 06:42
Hi @dgozman I have attached the sample code to navigate to Outlook email and click on the download button for an attachment. I am unable to share the repository with you; sorry for the inconvenience. You can use this code to download the attachment. If you need anything else, please let me know.
[Sample_Code.txt](https://github.com/user-attachments/files/15509406/Sample_Code.txt)

**Comment by dgozman** [comment] 2024-05-31 15:26
@mani9786 Unfortunately, I cannot run this sample code to reproduce the issue. It looks like the snippet uses something else in addition to Playwright, like `By.xpath()` and other utilities. I don't think we'll be able to help without a repro, sorry.

**Comment by dgozman** [comment] 2024-06-03 16:00
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.

**Closed by dgozman** 2024-06-03 16:00 UTC
