### ISSUE TITLE
[BUG] Right-click not executing on locator for Firefox

### ISSUE THREAD

**Issue by AlanJereb** [microsoft/playwright#24482] opened 2023-07-28 08:03 UTC
### System info
- Playwright Version: [v1.36.2]
- Operating System: [Windows 10]
- Browser: [Firefox]

### Source code

```js
  rightClick = (e: React.MouseEvent) => {
    if (this._contextMenuToggler && !e.ctrlKey && !e.shiftKey) {
      e.preventDefault();
      e.stopPropagation();
      this._contextMenuToggler(true);
    }
  }

 <div className="table-header-cell" onContextMenu={this.rightClick}>
      {/* Context menu, text values, etc. */}
 </div>
```

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
    workers: "70%",
    retries: 0,
    testDir: "../..",
    testMatch: [ "**/__e2e-tests__/**/*.[jt]s?(x)", "**/?(*.)+(e2etest).[jt]s?(x)" ],
    timeout: 1 * 60 * 1000, // ms
    webServer: {
        command: 'set PORT=3007  set DEBUG=pw:webserver && npm run mock  --port 3007',
        timeout: 120 * 1000,
        url: "http://localhost:3007/",
    },
    projects: [
        {
            name: "Chrome",
            use: {
                ...devices["Desktop Chrome"],
                baseURL: 'http://localhost:3007/',
                headless: true,
                screenshot: "only-on-failure",
                trace: "retain-on-failure",
            },
        },
        {
            name: "Firefox",
            use: {
                ...devices["Desktop Firefox"],
                baseURL: 'http://localhost:3007/',
                headless: true,
                screenshot: "only-on-failure",
                trace: "retain-on-failure",
            }
        },
    ]
});
```

**Test file (self-contained)**

```js
const openTableHeaderFilter = async (columnTitle = "Name") => {
  const iconFilterXpath = "css=.table-header-cell-filter .icon-filter";
  await page.locator("//label[contains(., '" + columnTitle + "')]").first().click({button: "right", force: true});
  await waitForVisible(iconFilterXpath); // Never visible in Firefox, as right-click above does nothing
 ...
};

test.describe("Table column filter shortcut", () => {
  test("Can filter on column", async () => {
    // Open filter and apply "Box" with right-click
    let input = await openTableHeaderFilter();
    ...
  });
});
```

**Steps**
Run the test with `npx playwright test --config playwright.config.ts --retries=10`

**Expected**

Right-click should be registered in Firefox.

**Actual**

```
retrying click action, attempt #56
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      performing click action
      <div class="table-header-cell">…</div> intercepts pointer events
```

It is registered only in Chrome. 

If I open Firefox with Playwright debugger, when it stalls, I can right-click manually on the targeted field, and the test proceeds and completes as expected.

**Comment by pavelfeldman** [comment] 2023-07-28 16:38
This is covered with the test https://github.com/microsoft/playwright/blob/c6a0e5d02c91952bd02e4cdf1c7cc5a707d4b997/tests/page/page-click.spec.ts#L317.

If you could provide a snippet where we could reproduce it locally, we would be able to act on it.

**Comment by AlanJereb** [comment] 2023-07-31 10:42
> This is covered with the test
> 
> https://github.com/microsoft/playwright/blob/c6a0e5d02c91952bd02e4cdf1c7cc5a707d4b997/tests/page/page-click.spec.ts#L317
> .
> 
> If you could provide a snippet where we could reproduce it locally, we would be able to act on it.

I've created a minimal repo.
You can find it here: [https://codesandbox.io/s/react-typescript-forked-lx8jkn?file=/src/App.tsx:781-789](https://codesandbox.io/s/react-typescript-forked-lx8jkn?file=/src/App.tsx:781-789)

**Comment by AlanJereb** [comment] 2023-07-31 11:48
Edit:

Testing element right-click with such code works in Firefox, but it doesn't work in Chrome anymore:
```
  const columnTarget = await page.locator("//label[contains(., 'Name') and contains(@class, 'sortable')]").first();
  const coords = await columnTarget.boundingBox();
  await page.mouse.move(coords?.x || 0, coords?.y || 0);
  await page.mouse.down({button: "right"});
```

**Comment by yury-s** [comment] 2023-08-01 01:06
> I've created a minimal repo.
> You can find it here: https://codesandbox.io/p/sandbox/react-typescript-forked-lx8jkn?file=%2Ftsconfig.json%3A11%2C1

Can you export it into a github repository so that we could run it locally?

**Comment by AlanJereb** [comment] 2023-08-01 08:01
> > I've created a minimal repo.
> > You can find it here: https://codesandbox.io/p/sandbox/react-typescript-forked-lx8jkn?file=%2Ftsconfig.json%3A11%2C1
> 
> I don't see an option to download the project, can you export it into a github repository so that we could run it locally?

I've made a GitHub repo, but you can disregard it, as I've found out we had some custom `mousedown` and `mouseup` event listeners on the dropdown, that didn't work as expected in Firefox.
[https://github.com/AlanJereb/playwrightTestMinimalRepo](https://github.com/AlanJereb/playwrightTestMinimalRepo)

**Comment by yury-s** [comment] 2023-08-01 16:47
> I've made a GitHub repo, but you can disregard it, as I've found out we had some custom mousedown and mouseup event listeners on the dropdown, that didn't work as expected in Firefox.

In this case it sounds like you caught a real bug which is caused by differences in the browser implementations. I'm going to close this issue as it seems to be working as intended. Feel free to file a new bug if you face further problems.

**Closed by yury-s** 2023-08-01 16:47 UTC
Labels: triaging

**Comment by AlanJereb** [comment] 2023-08-03 08:37
> > I've made a GitHub repo, but you can disregard it, as I've found out we had some custom mousedown and mouseup event listeners on the dropdown, that didn't work as expected in Firefox.
> 
> In this case it sounds like you caught a real bug which is caused by differences in the browser implementations. I'm going to close this issue as it seems to be working as intended. Feel free to file a new bug if you face further problems.

I did some more debugging and decided to update the above repo, so that it matches our use-case exactly. The problem reappeared, and the test doesn't pass. 

You can try it out.
[https://github.com/AlanJereb/playwrightTestMinimalRepo](https://github.com/AlanJereb/playwrightTestMinimalRepo)
