### ISSUE TITLE
[BUG] Code executes 6 times slower in headless mode vs headfull mode when all requests are intercepted

### ISSUE THREAD

**Issue by hdorgeval** [microsoft/playwright#6798] opened 2021-05-30 00:17 UTC
**Context:**
- Playwright Version: [1.11.1]
- Operating System: [Linux, Mac, Windows]
- Node.js version: [v14.15.1]
- Browser: [Chromium]
- Extra: []

**Context**
Hi, I am the developer of the [playwright-fluent](https://github.com/hdorgeval/playwright-fluent) library.
I am currently implementing a new feature that consist of loading a web site from a HAR file. To do this, every request is intercepted and if a corresponding HAR entry is found for a request then the request is fulfilled with the response coming from the HAR file.

The code for request interceptions can be seen [here](https://github.com/hdorgeval/playwright-fluent/blob/master/src/actions/page-actions/on-request-to-respond-from-har/on-request-to-respond-from-har.ts)

To test this functionality I have setup an integration test:

[on-request-to-respond-from-har.chromium.test.ts](https://github.com/hdorgeval/playwright-fluent/blob/master/src/fluent-api/tests/on-request-to-respond-from-har/on-request-to-respond-from-har.chromium.test.ts)
```ts
const harFile = path.join(__dirname, 'github.com.har');
await p
    .withBrowser('chromium')
    .withOptions({ headless: false })
    .withCursor()
    .onRequestTo('/')
    .respondFromHar([harFile], options);

await p.navigateTo('https://github.com/');

// Then
const signupButton = p.selector('button').withText('Sign up for GitHub');
await p
    // .hover(signupButton)
    // .expectThat(signupButton)
    // .isVisible()
    .expectThat(signupButton)
    .isEnabled();
```

**Describe the bug**

When headless is false, the test executes in about 13s.
When headless is true, the test executes in about 77s.

Following is the debug trace in headless and in headfull mode:

[pw:api in headfull mode.txt](https://github.com/microsoft/playwright/files/6565450/pw.api.in.headfull.mode.txt)
[pw:api in headless mode.txt](https://github.com/microsoft/playwright/files/6565451/pw.api.in.headless.mode.txt)

In headfull mode, I have noticed those figures which correspond to the Assertion part of the test:

```sh
pw:api => page.$$ started +99ms
pw:api <= page.$$ succeeded +116ms
```

In headless mode the same part of the trace becomes:
```sh
pw:api => page.$$ started +82ms
pw:api <= page.$$ succeeded +8s
```

To reproduce the problem:

```sh
git clone https://github.com/hdorgeval/playwright-fluent
cd playwright-fluent
npm install
npm run install-peers
```
Open the repo with VS Code, open file `src/fluent-api/tests/on-request-to-respond-from-har/on-request-to-respond-from-har.chromium.test.ts`  and in the debug panel select the  `jest-current-file` launch option.

Thanks

**Comment by pavelfeldman** [comment] 2021-06-01 18:39
I can reproduce this, I can see how rafs are throttled in the headless mode and take 1.6s instead of 16ms.

**Comment by hdorgeval** [comment] 2021-06-01 20:15
Thanks :)

**Comment by pavelfeldman** [comment] 2022-01-01 23:29
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-01-01 23:29 UTC
Labels: P3-collecting-feedback
