### ISSUE TITLE
[BUG] Unknown file extension ".ts" when using `"type": "module"` and `cap_net_bind_service=+ep`

### ISSUE THREAD

**Issue by beck-peterson** [microsoft/playwright#21067] opened 2023-02-21 16:55 UTC
This is my first bug report, so if I'm missing information please be patient with me. In researching this issue I came across https://github.com/microsoft/playwright/issues/18282 which presumably describes the same issue, so I'm using that as a template.

### Context:

- Operating system: Ubuntu 16
- Playwright version: 1.30.0
- Node version: 16.19.0
- Bash version: 4.3.48

### Bug:

In a newly created directory I ran `npm init playwright@latest`, and chose
```
✔ Do you want to use TypeScript or JavaScript? · TypeScript
✔ Where to put your end-to-end tests? · tests
✔ Add a GitHub Actions workflow? (y/N) · false
✔ Install Playwright browsers (can be done manually via 'npx playwright install')? (Y/n) · false
✔ Install Playwright operating system dependencies (requires sudo / root - can be done manually via 'sudo npx playwright install-deps')? (y/N) · false
```
I added `"type": "module"` to my package.json.
I ran `sudo setcap -r $(which node)` to clear my capabilities.
I ran `npx playwright test` and everything ran correctly.

I ran `sudo setcap cap_net_bind_service=+ep $(which node)` to allow node to bind to port 80.
I ran `npx playwright test` and received this error
```
TypeError: Unknown file extension ".ts" for /home/my-name/repo/playwright-bug/playwright.config.ts
```

**Comment by beck-peterson** [comment] 2023-02-21 19:01
I'm currently using `sudo setcap -r $(which node) ; npx playwright test ; sudo setcap cap_net_bind_service=+ep $(which node)` as a work around for now. This unfortunately prevents me from using my existing infrastructure for running a web server along side my playwright tests, but I'm using another work around for that.

**Comment by dgcole** [comment] 2023-02-21 19:37
I can confirm that I am experiencing this same issue on Ubuntu 20.04 using the exact commands specified in the original issue.

**Comment by yury-s** [comment] 2023-02-21 21:15
Does it reproduce if you simply add/remove "type": "module" without calling setcap?

**Comment by yury-s** [comment] 2023-02-24 02:00
To avoid any confusion, this is what I did:

```sh
npm init playwright@latest
# added "type": "module" to package.json
npx playwright test
sudo setcap cap_net_bind_service=+ep $(which node)
npx playwright test
sudo setcap -r $(which node)
npx playwright test
# removed "type": "module" to package.json
npx playwright test
sudo setcap cap_net_bind_service=+ep $(which node)
npx playwright test
```
all steps ran without any issues.

Can you reproduce it in Ubuntu 20.04  docker   `docker run -it --rm --ipc=host mcr.microsoft.com/playwright:v1.30.0-focal /bin/bash` ?

**Comment by beck-peterson** [comment] 2023-02-24 13:58
Unfortunately I don't currently have cycles to upgrade my OS or get docker setup on my workstation, but I'll try to see if I can get someone to run through those steps that meets both of those requirements to see if we are still having issues.

Also, if you were to have experienced the same bug as me, I would only have expectd the second time you ran `npx playwright test` to have the issue. The others have been behaving properly on my end.

**Comment by yury-s** [comment] 2023-02-27 19:02
I finally managed to reproduce it with docker image `mcr.microsoft.com/playwright:v1.30.0-focal` running it under pwuser (`docker run -it --rm --ipc=host -u pwuser mcr.microsoft.com/playwright:v1.30.0-focal /bin/bash`):

```
$ npx playwright test
TypeError: Unknown file extension ".ts" for /home/pwuser/foo/playwright.config.ts
    at new NodeError (node:internal/errors:387:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:75:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:117:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at requireOrImport (/home/pwuser/foo/node_modules/@playwright/test/lib/transform.js:191:26) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```
it doesn't happen with 1.31 image (`mcr.microsoft.com/playwright:v1.31.0-focal`). The difference between the two is that we updated Node version from 16 to 18 which seems to address this issue. Can you please confirm that the issue is gone if you use Node 18+ (e.g. with our 1.31 image)?

**Comment by pavelfeldman** [comment] 2023-03-02 18:38
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2023-03-02 18:38 UTC
Labels: triaging
