### ISSUE TITLE
[BUG] Inspector is running despite of `PWDEBUG`=0

### ISSUE THREAD

**Issue by dariusz-wozniak** [microsoft/playwright#11350] opened 2022-01-12 13:39 UTC
**Context:**
- Playwright Version:
   - NuGet: 1.17.3 (installed in the project)
   - microsoft.playwright.cli: 1.2.2 (from `dotnet tool list -g`)
   - Installed on machine: 1.17.1 (`playwright -V`)
- Operating System: Windows
- .NET version: .NET 6
- Browser: All

**Describe the bug**

When `PWDEBUG` is set to 0, Playwright Inspector appears when tests are ran [incorrect behaviour, I believe].

When set to an empty string (PowerShell: `$env:PWDEBUG=''`, then Inspector is not running [correct behaviour].

Solution:
- Disable running Inspector when `PWDEBUG` environment variable is set to 0.
- Update [documentation](https://playwright.dev/dotnet/docs/inspector).

**Comment by pavelfeldman** [comment] 2022-01-25 18:42
Already fixes, thanks!

**Comment by mxschmitt** [comment] 2022-01-25 18:43
Fixed in #11611
Duplicate of #11606

**Closed by pavelfeldman** 2022-01-25 18:42 UTC
Labels: v1.19, inner-loop
