### ISSUE TITLE
[BUG] screenshot rotateY transform is not worked on webkit

### ISSUE THREAD

**Issue by ArrayZoneYour** [microsoft/playwright#23917] opened 2023-06-27 10:12 UTC
### System info
- Playwright Version: [v1.34.2]
- Operating System: [macOS 13.2]
- Browser: [WebKit]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/ArrayZoneYour/playwright-screenshot

**Steps**
- pnpm install
- npm run test
- npm run test:ui

**Expected**

[Describe expected behavior]

webkit screenshot is the same as it display under ui mode

![image](https://github.com/microsoft/playwright/assets/21001457/5038668f-c9fa-4319-8b08-161fe2657a03)

**Actual**

[Describe actual behavior]

webkit screenshot rotateY is not worked as expected

![](https://github.com/ArrayZoneYour/playwright-screenshot/blob/main/webkit.png?raw=true)

**Comment by mxschmitt** [comment] 2023-06-27 13:31
Was able to repro it with the repo above. Tried to make a minimal reproducible out of it, but was not able to (seems like more things are involved there). Looks like it renders it correctly (since when looking at it with --headed, its there), only our snapshot function ignores it for some reason.

Just to confirm, we are talking about the right part of the screen right? 
![image](https://github.com/microsoft/playwright/assets/17984549/186087c8-42c0-4a55-9b94-26b4c95bc1ce)

**Comment by ArrayZoneYour** [comment] 2023-06-28 05:12
> Just to confirm, we are talking about the right part of the screen right?

Yes, the right part in snapshot render result is different.

**Comment by mxschmitt** [comment] 2023-06-29 10:37
Little bit smaller reproduction but was not able to create a repro without the Swiper JS library.

```ts
import { webkit, devices } from '@playwright/test';

(async () => {
  const browser = await webkit.launch({
    headless: false,
  });
  const context = await browser.newContext({ ...devices["iPhone 12 Pro"] });
  const page = await context.newPage();
  await page.route('https://example.com/', route => {
    return route.fulfill({
      body: `<!DOCTYPE html>
      <html lang="en">
        <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <title>Document</title>
          <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"
          />
          <style>
            .swiper {
              height: 150px;
              width: 100%;
              background-color: #ff9800;
              display: linear;
            }
      
            .swiper-slide {
              height: 100%;
              border: 5px solid black;
              background-color: #1890ff;
              box-sizing: border-box;
            }
          </style>
          <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
        </head>
        <body>
          <!-- Slider main container -->
          <div class="swiper">
            <!-- Additional required wrapper -->
            <div class="swiper-wrapper">
              <!-- Slides -->
              <div class="swiper-slide">Slide 1</div>
              <div class="swiper-slide">Slide 2</div>
              <div class="swiper-slide">Slide 3</div>
              ...
            </div>
            <!-- If we need pagination -->
            <div class="swiper-pagination"></div>
      
            <!-- If we need navigation buttons -->
            <div class="swiper-button-prev"></div>
            <div class="swiper-button-next"></div>
      
            <!-- If we need scrollbar -->
            <div class="swiper-scrollbar"></div>
          </div>
      
          <script>
            const swiper = new Swiper(".swiper", {
              // Optional parameters
              loop: true,
      
              effect: "coverflow",
      
              // If we need pagination
              pagination: {
                el: ".swiper-pagination",
              },
      
              // Navigation arrows
              navigation: {
                nextEl: ".swiper-button-next",
                prevEl: ".swiper-button-prev",
              },
      
              width: 300,
      
              // And if we need scrollbar
              scrollbar: {
                el: ".swiper-scrollbar",
              },
              coverflowEffect: {
                rotate: 50,
                stretch: 0,
                depth: 100,
                scale: 1,
                modifier: 1,
                slideShadows: false,
              },
            });
          </script>
        </body>
      </html>`,
      contentType: 'text/html',
    })
  })
  await page.goto('https://example.com');
  await page.screenshot({ path: `example.png` });
})()
```

**Comment by ArrayZoneYour** [comment] 2023-06-29 12:29
Yes, I also tried to repro it without swiper lib and feel confused before open this issue. 
Use some transform style (translate3d, rotateY) but it works, maybe it was raised by dynamic inline style update but I haven't tried yet.

**Comment by aslushnikov** [comment] 2023-07-07 17:27
This is a dupe of https://github.com/microsoft/playwright/issues/21620

**Closed by aslushnikov** 2023-07-07 17:27 UTC
Labels: browser-webkit, v1.36
