### ISSUE TITLE
[Question] How do I set test.fail if element does not exist and the hope is that in the allure/monocart report the test also fails (red marked),  but the test still continues. 

### ISSUE THREAD

**Issue by learnqa-nf** [microsoft/playwright#29331] opened 2024-02-03 00:41 UTC
How do I set test.fail if element does not exist and the hope is that in the allure/monocart report the test also fails (red marked), 
but the test still continues. 
I have used the trycatch test and it continues, but the report shows a green marked. If I don't use trycatch the test will stop.
Please advise.

This is a simple example, just multiple test cases that are the same, one of the locators I made doesn't match
![image](https://github.com/microsoft/playwright/assets/89567416/fe83ec59-c614-4c9e-aa40-3d9a06bbdb27)

**Comment by pavelfeldman** [comment] 2024-02-03 02:31
Closing as not a bug report and not a feature request.

**Closed** 2024-02-03 02:31 UTC
