### ISSUE TITLE
[BUG] Error at show HTML report

### ISSUE THREAD

**Issue by radekBednarik** [microsoft/playwright#10010] opened 2021-11-03 13:23 UTC
**Context:**
- Playwright Version: playwright/test 1.16.3
- Operating System: Windows
- Node.js version: 16.13
- Browser: All
- Extra: [any specific details about your environment]

**Code Snippet**

```shell
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::9323
    at Server.setupListenHandle [as _listen2] (node:net:1334:16)
    at listenInCluster (node:net:1382:12)
    at Server.listen (node:net:1469:7)
    at HttpServer.start (D:\Software Testing\Projects\SA_repos\TRACKING_automated_regression_tests\node_modules\playwright-core\lib\utils\httpServer.js:85:18)
    at showHTMLReport (D:\Software Testing\Projects\SA_repos\TRACKING_automated_regression_tests\node_modules\@playwright\test\lib\reporters\html.js:103:28)
    at HtmlReporter.onEnd (D:\Software Testing\Projects\SA_repos\TRACKING_automated_regression_tests\node_modules\@playwright\test\lib\reporters\html.js:72:15)
    at Multiplexer.onEnd (D:\Software Testing\Projects\SA_repos\TRACKING_automated_regression_tests\node_modules\@playwright\test\lib\reporters\multiplexer.js:73:7)
    at Runner._run (D:\Software Testing\Projects\SA_repos\TRACKING_automated_regression_tests\node_modules\@playwright\test\lib\runner.js:400:7)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1361:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 9323
}
```

**Describe the bug**

After test finishes and html report is to be auto served, the error displayed above is thrown.
When I try to open http://localhost:9323, the HTML report is shown, although it is not fully functional - for example clicking on the failed test case to show details will open only blank page.

**Comment by mxschmitt** [comment] 2021-11-03 22:24
Could it be that you have the HTML report open in another Terminal? I tried to reproduce it on Windows, but was not able to, for me it shutdown always correctly and a new HTML report was successfully opened.

**Comment by radekBednarik** [comment] 2021-11-04 06:56
@mxschmitt  okej, I tried to reproduce it, and it seems like this will happen, if:

- enable `retries:2` in playwright.config.js
- after first fail and during retry execution - interrupt by CTRL+C -> HTML report will be served, as it should
- close the process by CTRL+C
- run the test again and this time let it finish with retries
- the `EADDRINUSE` error should be thrown now and from now on after each test execution

**Comment by mxschmitt** [comment] 2021-11-04 12:21
I tried a bunch of times to repro it, but was unfortunately not able to. What kind of Terminal are you using? (Powershell, cmd.exe, VSCode?)

**Comment by radekBednarik** [comment] 2021-11-04 12:24
Powershell, 7.1.5

**Comment by mxschmitt** [comment] 2021-11-04 12:24
Update: I was able to repro!

**Comment by mxschmitt** [comment] 2021-11-07 16:52
Could it be that you close the HTML report with CTRL + C and press then by accident `N`?

I was only to reproduce it when doing that, when I pressed `Y`, it was working all the time.

**Comment by radekBednarik** [comment] 2021-11-08 07:05
Unfortunately, no. I am doing, what I described in repro steps, no accidental key pressing.
I can also provide my (slightly modified to run without headless and only one test in one project) `playwright.config.js`, if that helps:

```javascript
const { join } = require("path");
const { cpus } = require("os");

require("dotenv").config();

const GLOBAL_SETUP_PATH = join(process.cwd(), "common/globals/globalSetup.js");
const JUNIT_RESULTS_PATH = join(process.cwd(), "results.xml");
const TOUCHPOINT = process.env.TOUCHPOINT;

module.exports = {
  // setup for all browsers
  use: {
    headless: true,
    viewport: { width: 1920, height: 1080 },
    ignoreHTTPSErrors: true,
    trace: "on-first-retry",
    // screenshot: "only-on-failure",
    // video: "retain-on-failure",
    // options for worker scoped context
    wContextOptions: {
      viewport: { width: 1920, height: 1080 },
      ignoreHTTPSErrors: true,
      // screenshot: "only-on-failure",
      // video: "retain-on-failure",
    },
  },
  timeout: 60000,
  globalSetup: GLOBAL_SETUP_PATH,
  testMatch: `**/${TOUCHPOINT}/spec/configurationStarted/cz.spec.js`,
  workers: process.env.CI ? 8 : cpus().length / 2,
  reportSlowTests: null,
  retries: 2,
  reporter: [["dot"], ["junit", { outputFile: JUNIT_RESULTS_PATH }], ["html"]],
  projects: [
    {
      name: "Chromium",
      use: {
        browserName: "chromium",
      },
    },
    // {
    //   name: "WebKit",
    //   use: {
    //     browserName: "webkit",
    //   },
    // },
  ],
};

```

**Comment by pavelfeldman** [comment] 2021-11-09 16:27
The issue is that there is a process running on your system that keeps the 9223 port open. You should find the process that keeps the port open and kill it!

**Comment by radekBednarik** [comment] 2021-11-09 16:37
@pavelfeldman yes, I get that, but isn't the core issue here, that the process is left hanging in first place under some circumstances (described above)?

**Comment by mstepin** [comment] 2021-11-11 04:29
This error happens by simply having the new { open: 'never' } opt out option enabled in the playwright config. No processes keeping port 9223 open. Happens every time. On the bright side the browser and reports are no longer auto-opened.

**Comment by mxschmitt** [comment] 2021-11-11 11:18
Reopening, was able to repro on a Mac.

**Comment by mxschmitt** [comment] 2021-11-12 16:34
A provisional fix related to this bug got landed, it will be a part of 1.17, let us know if you still encounter related issues!

**Closed by mxschmitt** 2021-11-12 16:34 UTC
Labels: v1.17

**Comment by geoffreyhale** [comment] 2022-07-21 19:53
Able to reproduce the same issue when adding only the following line:

<img width="871" alt="image" src="https://user-images.githubusercontent.com/3221283/180303488-a930e9e0-83e6-44a2-865e-e07bc0ad1c71.png">

**Comment by matrs** [comment] 2024-02-07 15:00
Sometimes happens to me. Still, if you're  on linux you can do :
```sh
# get the PID
lsof -i@localhost | grep 'PORT_NUMBER_IN_USE'
kill -9 PID
```
