### ISSUE TITLE
[BUG] Failed worker - Error: ENOENT: no such file or directory ...

### ISSUE THREAD

**Issue by joerg1985** [microsoft/playwright#23387] opened 2023-05-31 07:53 UTC
### System info
- Playwright Version: v1.34.0
- Operating System: Ubuntu 22
- Browser: WebKit
- Other info: 

### Source code

I can not provide code, this is only to see if you have a guess what could have happened here.
Or to find other playwright users with the same issue.

The CI failed with, while all tests did pass:

```
  ✓  15 [webkit] › one_of_my_tests.spec.ts:51:7 › One of my tests (15.9s)
Error: ENOENT: no such file or directory, open '/home/vsts/work/1/s/test-results/.playwright-artifacts-2/traces/e69fa91c7a5aeb5562f4-a3b0bd93b675913377a5-3.network'

Failed worker ran 5 tests:
[webkit] › src/tests/....spec.ts:13:7 › Another test
[webkit] › src/tests/....spec.ts:99:7 › Another test
[webkit] › src/tests/....spec.ts:8:5 › Another test
[webkit] › src/tests/one_of_my_tests.spec.ts:14:7 › Another test
[webkit] › src/tests/one_of_my_tests.spec.ts:51:7 › One of my tests
```

The last statement of the last test did inspect the networking via
```
const response = await page.waitForResponse(`${process.env.BASE_URL}/deep/link`)
const responseBody = JSON.parse(await response.text())
expect(response.status()).toBe(200)
```
Could the not found '.network' be a temporary file of inspecting the network?
Or could you tell what the '.network' files are good for to narrow down the problem?

**Comment by mxschmitt** [comment] 2023-05-31 10:25
Might be the same as https://github.com/microsoft/playwright/issues/23379, let me ping you when we merged the fix for it, and release a canary version for you, so you can test it out on canary right away if then things work as expected.

**Comment by mxschmitt** [comment] 2023-06-06 09:33
Would it be to share a self contained reproducible with us? Even if we need to run it a lot and it will end up in the error, it would help.

**Comment by joerg1985** [comment] 2023-06-06 11:18
I have seen this only in the CI and could not reproduce it locally. Would it help to improve the logging in the CI and wait for it to happen?

I am new to typescript, i would think about something like adding 'console.error = console.trace' to the `playwright.config.ts`.
This might be total none sense, but there might be a way to get more infos logged?

**Comment by ikoral** [comment] 2023-06-06 11:36
I can see similar errors on our CI (Jenkins) and I cannot reproduce that error on my local machine.

```
 [12/13] [chromium] › integration/..... Should give me currentUser

[2023-06-06T09:23:54.365Z] [2023-06-06T09:23:54.365Z] Error: ENOENT: no such file or directory, open '/home/pwuser/app/test-results/.playwright-artifacts-0/traces/fa1d6d46b985066ccc8e-3adb4c924fdb19aa9dd8-67.network'

Failed worker ran 6 tests:
```

The latest statements:
2023-06-06T09:23:56.825Z] [2023-06-06T09:23:56.825Z]   13 passed (4.9m)

[2023-06-06T09:23:56.825Z] [2023-06-06T09:23:56.825Z]   1 error was not a part of any test, see above for details

**Comment by aslushnikov** [comment] 2023-06-07 18:56
We glanced over some relevant parts of the code, but nothing stroke us as wrong there. So it doesn't look like we can act on this unless we have a repro.

Closing this. Please do not hesitate to re-file once you have a repro we can run locally to investigate!

**Comment by Anber** [comment] 2023-06-15 18:21
I have the similar error but in my case Playwright freezes immediately after `ENOENT: no such file or directory`.
The strangest part is that `test-results` folder doesn't have anything that looks like `.playwright-artifacts-`.

Last moments in logs:
```
  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;202;1mpw:channel:response \u001b[0m{ id: \u001b[33m246\u001b[39m } \u001b[38;5;202m+10ms\u0
  pw:channel:response { id: 246 } +10ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;33;1mpw:channel:command \u001b[0m{\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m  id: \u001b[33m249\u001b[39m,\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m  guid: \u001b[32m'browser-context@bc6bd815c4ba273c5dea28517b1b32b4'\u001b[39m,\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m  method: \u001b[32m'close'\u001b[39m,\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m  params: \u001b[90mundefined\u001b[39m\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m} \u001b[38;5;33m+10ms\u001b[0
  pw:channel:command {
  pw:channel:command   id: 249,
  pw:channel:command   guid: 'browser-context@bc6bd815c4ba273c5dea28517b1b32b4',
  pw:channel:command   method: 'close',
  pw:channel:command   params: undefined
  pw:channel:command } +10ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;34;1mpw:protocol \u001b[0mSEND ► {\"id\":922,\"method\":\"Target.disposeBrowserContext\",\"
  pw:protocol SEND ► {"id":922,"method":"Target.disposeBrowserContext","params":{"browserContextId":"C9EC6A29BC0B60A97AAC2862EFA9280E"}} +16ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;34;1mpw:protocol \u001b[0m◀ RECV {\"id\":922,\"result\":{}} \u001b[38;5;34m+1ms\u001b[0m\n"
  pw:protocol ◀ RECV {"id":922,"result":{}} +1ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;207;1mpw:channel:event \u001b[0m{\n  \u001b[38;5;207;1mpw:channel:event \u001b[0m  guid: \u001b[32m'browser-context@bc6bd815c4ba273c5dea28517b1b32b4'\u001b[39m,\n  \u001b[38;5;207;1mpw:channel:event \u001b[0m  method: \u001b[32m'close'\u001b[39m,\n  \u001b[38;5;207;1mpw:channel:event \u001b[0
  pw:channel:event {
  pw:channel:event   guid: 'browser-context@bc6bd815c4ba273c5dea28517b1b32b4',
  pw:channel:event   method: 'close',
  pw:channel:event   params: undefined
  pw:channel:event } +20ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;207;1mpw:channel:event \u001b[0m{\n  \u001b[38;5;207;1mpw:channel:event \u001b[0m  guid: \u001b[32m'browser-context@bc6bd815c4ba273c5dea28517b1b32b4'\u001b[39m,\n  \u001b[38;5;207;1mpw:channel:event \u001b[0m  method: \u001b[32m'__dispose__'\u001b[39m,\n  \u001b[38;5;207;1mpw:channel:event \u
  pw:channel:event {
  pw:channel:event   guid: 'browser-context@bc6bd815c4ba273c5dea28517b1b32b4',
  pw:channel:event   method: '__dispose__',
  pw:channel:event   params: {}
  pw:channel:event } +0ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;202;1mpw:channel:response \u001b[0m{ id: \u001b[33m249\u001b[39m } \u001b[38;5;202m+2ms\u00
  pw:channel:response { id: 249 } +2ms

  pw:test teardown _reuseContext +24ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;197;1mpw:test \u001b[0mteardown _setupContextOptions \u001b[38;5;197m+0ms\u001b[0m\n"}}} +0
  pw:test teardown _setupContextOptions +0ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;197;1mpw:test \u001b[0mteardown _combinedContextOptions \u001b[38;5;197m+0ms\u001b[0m\n"}}}
  pw:test teardown _combinedContextOptions +0ms

  pw:test teardown serviceWorkers +0ms

  pw:test teardown timezoneId +0ms

  pw:test teardown storageState +0ms

  pw:test teardown proxy +0ms

  pw:test teardown permissions +0ms

  pw:test teardown offline +0ms

  pw:test teardown locale +0ms

  pw:test teardown javaScriptEnabled +0ms

  pw:test teardown ignoreHTTPSErrors +0ms

  pw:test teardown httpCredentials +0ms

  pw:test teardown geolocation +0ms

  pw:test teardown extraHTTPHeaders +0ms

  pw:test teardown colorScheme +0ms

  pw:test teardown bypassCSP +0ms

  pw:test teardown acceptDownloads +0ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;197;1mpw:test \u001b[0mtearing down test scope finished \u001b[38;5;197m+0ms\u001b[0m\n"}}}
  pw:test tearing down test scope finished +0ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;197;1mpw:test \u001b[0mtearing down worker scope started \u001b[38;5;197m+1ms\u001b[0m\n"}}
  pw:test tearing down worker scope started +1ms

  pw:test teardown browser +0ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stepBegin","params":{"testId":"85b3cc1667c06e9efc8f-f7dbf111fcd3e82c7dff","stepId":"fixture@fixture: browser@132","parentStepId":"hook@After Hooks@124","title":"fixture: browser","category":"fixture","wallTime":1686852761658}}} +0ms
  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;33;1mpw:channel:command \u001b[0m{\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m  id: \u001b[33m250\u001b[39m,\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m  guid: \u001b[32m'browser@4675f009ddd92c28a0d84250126c57e6'\u001b[39m,\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m  method: \u001b[32m'close'\u001b[39m,\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m  params: \u001b[90mundefined\u001b[39m\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m} \u001b[38;5;33m+2ms\u001b[0m\n"}}} +
  pw:channel:command {
  pw:channel:command   id: 250,
  pw:channel:command   guid: 'browser@4675f009ddd92c28a0d84250126c57e6',
  pw:channel:command   method: 'close',
  pw:channel:command   params: undefined
  pw:channel:command } +2ms

  pw:browser [pid=31653] <gracefully close start> +10s

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;34;1mpw:protocol \u001b[0m◀ RECV {\"id\":-9999,\"result\":{}} \u001b[38;5;34m+1ms\u001b[0m\
  pw:protocol ◀ RECV {"id":-9999,"result":{}} +1ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;207;1mpw:channel:event \u001b[0m{\n  \u001b[38;5;207;1mpw:channel:event \u001b[0m  guid: \u001b[32m'browser-context@125a487d62a33efa14d0b92327df5384'\u001b[39m,\n  \u001b[38;5;207;1mpw:channel:event \u001b[0m  method: \u001b[32m'close'\u001b[39m,\n  \u001b[38;5;207;1mpw:channel:event \u001b[0
  pw:channel:event {
  pw:channel:event   guid: 'browser-context@125a487d62a33efa14d0b92327df5384',
  pw:channel:event   method: 'close',
  pw:channel:event   params: undefined
  pw:channel:event } +3ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;207;1mpw:channel:event \u001b[0m{\n  \u001b[38;5;207;1mpw:channel:event \u001b[0m  guid: \u001b[32m'browser-context@125a487d62a33efa14d0b92327df5384'\u001b[39m,\n  \u001b[38;5;207;1mpw:channel:event \u001b[0m  method: \u001b[32m'__dispose__'\u001b[39m,\n  \u001b[38;5;207;1mpw:channel:event \u
  pw:channel:event {
  pw:channel:event   guid: 'browser-context@125a487d62a33efa14d0b92327df5384',
  pw:channel:event   method: '__dispose__',
  pw:channel:event   params: {}
  pw:channel:event } +0ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;207;1mpw:channel:event \u001b[0m{\n  \u001b[38;5;207;1mpw:channel:event \u001b[0m  guid: \u001b[32m'browser@4675f009ddd92c28a0d84250126c57e6'\u001b[39m,\n  \u001b[38;5;207;1mpw:channel:event \u001b[0m  method: \u001b[32m'close'\u001b[39m,\n  \u001b[38;5;207;1mpw:channel:event \u001b[0m  param
  pw:channel:event {
  pw:channel:event   guid: 'browser@4675f009ddd92c28a0d84250126c57e6',
  pw:channel:event   method: 'close',
  pw:channel:event   params: undefined
  pw:channel:event } +0ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;207;1mpw:channel:event \u001b[0m{\n  \u001b[38;5;207;1mpw:channel:event \u001b[0m  guid: \u001b[32m'browser@4675f009ddd92c28a0d84250126c57e6'\u001b[39m,\n  \u001b[38;5;207;1mpw:channel:event \u001b[0m  method: \u001b[32m'__dispose__'\u001b[39m,\n  \u001b[38;5;207;1mpw:channel:event \u001b[0m
  pw:channel:event {
  pw:channel:event   guid: 'browser@4675f009ddd92c28a0d84250126c57e6',
  pw:channel:event   method: '__dispose__',
  pw:channel:event   params: {}
  pw:channel:event } +0ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[30;1mpw:browser \u001b[0m[pid=31653] <process did exit: exitCode=0, signal=null> \u001b[30m+16ms
  pw:browser [pid=31653] <process did exit: exitCode=0, signal=null> +16ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[30;1mpw:browser \u001b[0m[pid=31653] starting temporary directories cleanup \u001b[30m+0ms\u001b
  pw:browser [pid=31653] starting temporary directories cleanup +0ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[30;1mpw:browser \u001b[0m[pid=31653] finished temporary directories cleanup \u001b[30m+1ms\u001b
  pw:browser [pid=31653] finished temporary directories cleanup +1ms

  pw:browser [pid=31653] <gracefully close end> +0ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;202;1mpw:channel:response \u001b[0m{ id: \u001b[33m250\u001b[39m } \u001b[38;5;202m+18ms\u0
  pw:channel:response { id: 250 } +18ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stepEnd","params":{"testId":"85b3cc1667c06e9efc8f-f7dbf111fcd3e82c7dff","stepId":"fixture@fixture: browser@132","wallTime":1686852761675}}} +0ms
  pw:test teardown browserName +17ms

  pw:test teardown registerSelectors +0ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stepBegin","params":{"testId":"85b3cc1667c06e9efc8f-f7dbf111fcd3e82c7dff","stepId":"fixture@fixture: registerSelectors@133","parentStepId":"hook@After Hooks@124","title":"fixture: registerSelectors","category":"fixture","wallTime":1686852761675,"location":{"file":"…/packages/e2e-gherkin/src/test.ts","line":34,"column":6}}}} +0ms
  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stepEnd","params":{"testId":"85b3cc1667c06e9efc8f-f7dbf111fcd3e82c7dff","stepId":"fixture@fixture: registerSelectors@133","wallTime":1686852761675}}} +0ms
  pw:test teardown _setupArtifacts +0ms

  pw:test teardown _browserOptions +115ms

  pw:test teardown _artifactsDir +0ms

  pw:test teardown connectOptions +18ms

  pw:test teardown channel +0ms

  pw:test teardown headless +0ms

  pw:test teardown playwright +0ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;197;1mpw:test \u001b[0mtearing down worker scope finished \u001b[38;5;197m+0ms\u001b[0m\n"}
  pw:test tearing down worker scope finished +0ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stepEnd","params":{"testId":"85b3cc1667c06e9efc8f-f7dbf111fcd3e82c7dff","stepId":"hook@After Hooks@124","wallTime":1686852761808,"error":{"message":"end of central directory record signature not found","stack":"Error: end of central directory record signature not found\n"}}}} +0ms
  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;202;1mpw:channel:response \u001b[0m{\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m  id: \u001b[33m248\u001b[39m,\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m  error: {\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m    error: {\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m      message: \u001b[32m\"ENOENT: no such file or directory, open '…/e2e/test-results/.playwright-artifacts-7/traces/resources/page@89f61a56ae88316bf09c177cd1e78ed5-1686852757.473029.jpeg'\"\u001b[39m,\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m      stack: \u001b[32m\"Error: ENOENT: no such file or directory, open '…/e2e/test-results/.playwright-artifacts-7/traces/resources/page@89f61a56ae88316bf09c177cd1e78ed5-1686852757.473029.jpeg'\"\u001b[39m,\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m      name: \u001b[32m'Error'\u001b[39m\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m    }\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m  }\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m
  pw:channel:response {
  pw:channel:response   id: 248,
  pw:channel:response   error: {
  pw:channel:response     error: {
  pw:channel:response       message: "ENOENT: no such file or directory, open '…/e2e/test-results/.playwright-artifacts-7/traces/resources/page@89f61a56ae88316bf09c177cd1e78ed5-1686852757.473029.jpeg'",
  pw:channel:response       stack: "Error: ENOENT: no such file or directory, open '…/e2e/test-results/.playwright-artifacts-7/traces/resources/page@89f61a56ae88316bf09c177cd1e78ed5-1686852757.473029.jpeg'",
  pw:channel:response       name: 'Error'
  pw:channel:response     }
  pw:channel:response   }
  pw:channel:response } +134ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stepEnd","params":{"testId":"85b3cc1667c06e9efc8f-f7dbf111fcd3e82c7dff","stepId":"hook@afterEach hook@125","wallTime":1686852761809,"error":{"message":"ENOENT: no such file or directory, open '…/e2e/test-results/.playwright-artifacts-7/traces/resources/page@89f61a56ae88316bf09c177cd1e78ed5-1686852757.473029.jpeg'","stack":"Error: ENOENT: no such file or directory, open '…/e2e/test-results/.playwright-artifacts-7/traces/resources/page@89f61a56ae88316bf09c177cd1e78ed5-1686852757.473029.jpeg'\n    at …/packages/e2e-gherkin/src/runner.ts:545:25\n    at fulfilled (…/packages/e2e-gherkin/build/runner.js:12:24)"}}}} +0ms
  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;197;1mpw:test \u001b[0mtearing down test scope started \u001b[38;5;197m+1ms\u001b[0m\n"}}}
  pw:test tearing down test scope started +1ms

  pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;197;1mpw:test \u001b[0mtearing down test scope finished \u001b[38;5;197m+0ms\u001b[0m\n"}}}
  pw:test tearing down test scope finished +0ms
```

Logs after ctrl+C:
```
^C  pw:test:task "teardown for start workers" started +0ms
  pw:test:protocol SEND ► {"method":"__stop__"} +0ms
  pw:test:protocol ◀ RECV {"method":"__env_produced__","params":[["TEST_WORKER_INDEX","7"],["TEST_PARALLEL_INDEX","0"]]} +0ms
 ELIFECYCLE  Command failed.
```

Logs that appears in terminal in few seconds after killing process with ctrl+c:
```
pw:test:task "teardown for start workers" finished +0ms
  pw:test:task "teardown for report begin" started +0ms
  pw:test:task "test suite" finished +0ms
  pw:test:task "teardown for report begin" finished +0ms
  pw:test:task "teardown for global setup" started +0ms
  1 skipped
  13 passed (5.4m)
```

**Comment by admmasters** [comment] 2023-06-18 11:20
This is occurring for me as well, only in CI on Jenkins with the same error:

Test passed but then the following error message breaks the test

`Error: ENOENT: no such file or directory, open '/home/jenkins/agent/workspace/<project_name>_PR-1/test-results/.playwright-artifacts-0/traces/843f88e1fda41d8e559e-2994db754a0a9a3a89af.trace'`

**Comment by mboiman** [comment] 2023-07-04 11:15
have the same problem. is there a workaround until v1.36?

**Comment by joerg1985** [comment] 2023-07-10 06:53
@aslushnikov is there a plan to improve logging when the filtered stacktrace is not set or empty?

**Comment by mboiman** [comment] 2023-07-10 06:59
i had the problems in github-actions, i set playwright back to 1.33, its working now.

**Comment by kLjubomir** [comment] 2023-07-10 09:12
I also have the same issue on CI/CD, but does not reproduce locally, this needs to be fixed it's causing bad test reports that can not be verified.

**Comment by jan-osch** [comment] 2023-07-10 14:26
I'm trying to reproduce this issue but without luck. Does anyone have a snippet of PWT code that reliably produces this issue?

**Comment by aslushnikov** [comment] 2023-07-31 17:56
We landed a few fixes, but we cannot validate since there's no repro. Thus i'll close this now.

Please file a new issue if/once you have a repro for us for this! Thanks.

**Closed by aslushnikov** 2023-07-31 17:56 UTC
Labels: v1.37

**Comment by felixaMSFT** [comment] 2023-07-31 23:17
Hi there, we are new to using Playwright. how long until we can get the bug fixes? Do you have a version number?

**Comment by mxschmitt** [comment] 2023-08-01 07:34
Bug fixes get released in new minor versions. We release new minor versions every 3-5 weeks. If you want to use the latest version before, you can use Canary: https://playwright.dev/docs/canary-releases

**Comment by InduKrish** [comment] 2023-08-02 16:46
Hi , I face the same issue as well, the tests is done executing, but the test marked failed because of the following error..what is the cause of the following error? and there is no trace file or screenshot.. can you please explain?
Error: tracing.stopChunk: ENOENT: no such file or directory, open ‘/Users/x273092/Documents/integration/cbna-test-integration-cbna/test-ui/playwright/test-results/.playwright-artifacts-0/traces/8032a828622df5d17c8e-d6742c2daf0cb4f09899.trace’

**Comment by InduKrish** [comment] 2023-08-02 17:33
please advise which playwright needs to be used? should i use 1.37.0?

**Comment by hat5u** [comment] 2023-09-04 10:37
Not sure if this helps,

I upgraded from 1.32.2 to 1.37.1 and then I got `Error: end of central directory record signature not found` and `Error: ENOENT: no such file or directory, open '/my-test/test-results/.playwright-artifacts-2/8ecfe60c5012dcb08b07f04e2a41444d.zip'` only when using `--trace=on` (everything OK in 1.32.2), and I found that it happened only on a test file not all tests.

So I was looking what's different between them, I saw that the errors always appear after the steps in `beforeAll` finish, and found that I had a `beforeAll` like this:
```
test.beforeAll(async ({ browser }) => {
  const context = await browser.newContext();
  const page = await context.newPage();
  const page2 = await context.newPage();
  // do something
  context.close();
});
```
 Thus I added `await` on `context.close();`:
```
test.beforeAll(async ({ browser }) => {
  const context = await browser.newContext();
  const page = await context.newPage();
  const page2 = await context.newPage();
  // do something
  await context.close();
});
```
Then the errors have gone after I added the `await` !

**Comment by szagi3891** [comment] 2023-10-23 11:36
```
Error: ENOENT: no such file or directory, open '/var/folders/ln/vb7mq1fj1wq5c10gkggbs61r0000gn/T/playwright-transform-cache-501/59/Amount_59df9d9491b12aca3b5695934d31420e50f20dd6.js'
```

Something is clearly broken with this cache.
I and a colleague locally are experiencing this problem

**Comment by szagi3891** [comment] 2023-10-23 11:51
Is there a command to clear this broken cache ?

**Comment by sarah-gelt** [comment] 2023-10-24 09:47
@szagi3891 See here:
https://github.com/microsoft/playwright/issues/27756

**Comment by szagi3891** [comment] 2023-10-24 10:09
@sarah-gelt - thanks for the link

**Comment by jerry-flam** [comment] 2023-10-24 18:13
> Is there a command to clear this broken cache ?

Couldn't find a command in the documentation, so I just deleted the folder and it worked.
```shell
$ cd /var/folders/yt/x1lbgn513w7cpfxc585w_z500000gn/T
$ rm -rf playwright-transform-cache-501
```

**Comment by tikolakin** [comment] 2023-11-10 19:20
I also noticed that there is an issue with the cache. Removing the cache folder helped.
I suspect it could be an issue when `npx playwright` is used at some places. So I just use `yarn playwright` instead ...

**Comment by irahul** [comment] 2023-12-05 06:46
> I also noticed that there is an issue with the cache. Removing the cache folder helped. I suspect it could be an issue when `npx playwright` is used at some places. So I just use `yarn playwright` instead ...

This helped me too and clearing the cache resolved the Error 'ENOENT: no such file or directory'

**Comment by tgrisley** [comment] 2024-01-16 10:45
I am on 1.39 and still get this occasionally - only way around is to manually clear cache

<img width="1335" alt="Screenshot 2024-01-16 at 10 45 16" src="https://github.com/microsoft/playwright/assets/126177701/a656f1d8-1e38-454a-83b0-87f18752153c">

**Comment by nitzanashi** [comment] 2024-01-18 09:20
Also on 1.39 and had the same issue, the only way was to clear the cache manually.


I believe it would be easy to reproduce if the playwright team would go to these caches and remove one of the folders in the cache that is being used.

I would expect that if the cache is not found, Playwright should just ignore it and run a test cacheless, but the error is def not expected.

**Comment by mxschmitt** [comment] 2024-01-18 09:21
I'm going to lock the issue for now, since we don't monitor closed issues. In order to triage this efficiently, I recommend trying our latest version and if you still encounter issues there, file a new bug report, thanks!
