### ISSUE TITLE
[BUG] Jenkins JUnit compatibility

### ISSUE THREAD

**Issue by klassm** [microsoft/playwright#12344] opened 2022-02-24 17:04 UTC
**Context:**
- Playwright Version: 1.19.1
- Operating System: Linux, Mac
- Node.js version: 16
- Browser: Chromium

**Describe the bug**

First of all thank you so much for this great testing tool. It is so much better than testcafé or cypress, which we used before.

After the migration from testcafé we now noted a problem with jenkins. It will fail to parse the generated JUnit output with:

```
16:23:23  INFO: [JUnit] - 1 test report file(s) were found with the pattern '**//test-report-gui.xml' relative to '/home/jenkins/workspace/rowebapps_myapp_develop' for the testing framework 'JUnit'.
16:23:23  WARNING: The file '/home/jenkins/workspace/rowebapps_myapp_develop/test-report-gui.xml' is an invalid file.
16:23:23  WARNING: At line 1 of file:/home/jenkins/workspace/rowebapps_myapp_develop/test-report-gui.xml:cvc-complex-type.3.2.2: Attribute 'id' is not allowed to appear in element 'testsuites'.
16:23:23  WARNING: At line 1 of file:/home/jenkins/workspace/rowebapps_myapp_develop/test-report-gui.xml:cvc-complex-type.3.2.2: Attribute 'skipped' is not allowed to appear in element 'testsuites'.
16:23:23  WARNING: The result file '/home/jenkins/workspace/rowebapps_myapp_develop/test-report-gui.xml' for the metric 'JUnit' is not valid. The result file has been skipped.
```

I could not yet find an open issue for this problem, but to me it looks like the reporter is generating attributes that should actually not be there. Now the Jenkins parser is known to be strict, but still it would be great if we could use Jenkins without a custom xsl transformation.

An example xml file looks like this:
```
<testsuites id="" name="" tests="32" failures="0" skipped="29" errors="0" time="13.353">
    <testsuite name="autocomplete.gui.spec.ts" timestamp="1645616455044" hostname="" tests="3" failures="0" skipped="0" time="7.259" errors="0">
        <testcase name="some description" classname="[chromium] › autocomplete.gui.spec.ts:61:3" time="2.882">
            <system-out>
                ...
            </system-out>
        </testcase>
    </testsuite>
</testsuites>
```

Thank you so much!

**Comment by mxschmitt** [comment] 2022-02-25 10:45
Are you using this plugin? https://plugins.jenkins.io/junit/

**Comment by klassm** [comment] 2022-02-25 10:47
Thanks for the quick response. We are using the xUnit plugin: https://plugins.jenkins.io/xunit/

**Comment by klassm** [comment] 2022-02-25 10:48
An example call in the pipeline looks like this:
`
                                    xunit(
                                            thresholds: [skipped(failureThreshold: '0'), failed(failureThreshold: '0')],
                                            tools: [JUnit(pattern: '**/junit*.xml')]
                                    )
`

**Comment by mxschmitt** [comment] 2022-02-25 12:12
I'd recommend to file an issue against [their issue tracker](https://issues.jenkins.io/issues/?jql=resolution%20is%20EMPTY%20and%20component%3D15636), since this is not a bug on our side.

`testsuites>id` is a valid property, see [here](https://www.ibm.com/docs/en/developer-for-zos/9.1.1?topic=formats-junit-xml-format).
`testsuites>skipped` is a valid property, see [here](https://llg.cubic.org/docs/junit/).

[This](https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd) is the file against which they are validating, so probably just raise a PR there and adding these two properties, then it should work.

**Comment by klassm** [comment] 2022-02-25 12:13
Thanks!

**Comment by mxschmitt** [comment] 2022-02-25 12:14
Closing for now then.

**Comment by klassm** [comment] 2022-02-25 13:50
So now - unfortunately they won't add support for this :-(
"As per documentation the XSD is compliant with Ant/Surefire (Maven). No other attributes of any software will be supported/added. There are a couple of JIRA issue in which we discuss this."

So it looks like playwright cannot be used with Jenkins, or at least without various workarounds like writing an own xsl transformation ...

**Comment by dgozman** [comment] 2022-02-25 18:06
@klassm I don't think we can/should fix this issue in Playwright. We would like to support not just Jenkins, but many other systems, and all of them have their own extensions to the bare-bones junit xml format. Therefore, we'd assume that adding more properties should just work, and Jenkins should ignore any properties they do not recognize.

Looking at Jenkins issues, there are many tools that add more stuff to junit xml, and none of them works. That's unfortunate 😞 

> So it looks like playwright cannot be used with Jenkins, or at least without various workarounds like writing an own xsl transformation ..

Perhaps [this xsl](https://github.com/jenkinsci/xunit-plugin/blob/master/docs/files/input.xsl) recommended on `xunit-plugin` github page would work? If not, I'd ask them for an xsl that just strips all unknown elements/attributes. It seems like that would be a very common solution.

**Closed by dgozman** 2022-02-25 18:06 UTC
Labels: P3-collecting-feedback, feature-test-runner

**Comment by klassm** [comment] 2022-02-28 11:35
Yes I totally get your point. I actually found a simple workaround, that might fit everyone, so I also want to put it here. You don't need the xunit Plugin. When just using the normal junit plugin, it simply works out of the box, without any xsl transformations.

**Comment by smehdux** [comment] 2023-03-21 09:02
Hello,

I'm facing a similar problem with Jenkins when it calls Sonarqube, the XML report couldn't be parsed because of the mismatching XSD definition as described by sonarqube => https://docs.sonarqube.org/latest/analyzing-source-code/test-coverage/generic-test-data/

**Example of a valid Sonarqube execution report:**

`<testExecutions version="1">
  <file path="testx/ClassOneTest.xoo">
	<testCase name="test1" duration="5"/>
	<testCase name="test2" duration="500">
	  <skipped/>
	</testCase>
	<testCase name="test3" duration="100">
	  <failure/>
	</testCase>
	<testCase name="test4" duration="500">
	  <error/>
	</testCase>
  </file>
</testExecutions>` 


I got this error with **sonarqube-scanner** for a Node.JS project

`
12:18:33  12:18:33.288 ERROR: Error during SonarScanner execution
12:18:33  12:18:33.288 ERROR: Error during parsing of generic test execution report '/opt/jenkins/home/workspace/blanche-v2-demo-poc/ws-blanche-v2-demo3-build-pipeline-with-sharedLib/test-report.xml'. Look at the SonarQube documentation to know the expected XML format.
12:18:33  12:18:33.288 ERROR: Caused by: Unknown XML node, expected "testExecutions" but got "testsuites" at line 1
12:18:33  12:18:33.288 ERROR: `

And this is my configuration in Jenkins pipeline : file named ci-analyse.js 
`const scanner = require("sonarqube-scanner");

scanner({
        options: {
            "sonar.projectVersion": "__PROJECT_VERSION__",
            "sonar.sources": "src/tests",
            "sonar.tests": "src",
            "sonar.typescript.lcov.reportPaths": "coverage/lcov.info",
            //"sonar.testExecutionReportPaths": "test-report.xml",
            "sonar.testExecutionReportPaths": "coverage/lcov.info",
            "sonar.exclusions": "src/main.ts,src/**/*.spec.ts,src/**/*.css,src/environments/environment*.ts,src/app/core/security/keycloak.service.ts,ci-karma.conf.js,karma.conf.js,src/test.ts",
            "sonar.cpd.exclusions": "src/main.ts,src/**/*.spec.ts,**/*.module.ts",
            "sonar.coverage.exclusions": "src/main.ts,src/**/*.spec.ts,**/*.module.ts,src/environments/environment*.ts",
            "sonar.log.level": "DEBUG"
        },
    },
    () => {
        // callback is required
    }
);`

Any help !? I got struggling with that and no idea comes to my mind to find a workaround.
