### ISSUE TITLE
[Question] No console.log output in GitLab CI

### ISSUE THREAD

**Issue by temp2612** [microsoft/playwright#16581] opened 2022-08-16 15:03 UTC
I am using Playwright 1.22 with the recommended Docker image and I don't see the output of the `console.log()` statements of my tests (not in browser context but in Playwright context). I have set `DEBUG=pw:api,pw:webserver` and I see the colorful output from Playwright itself in the GitLab CI log but not my own logging output. This works fine locally. What should I do?

**Comment by aslushnikov** [comment] 2022-08-16 16:02
@temp2612 try gradually debugging the issue, starting with running a simple node.js snippet on your GitLab CI and see if it works for you:

```js
// test.js
console.log('this is STDOUT');
console.error(this is STDERR');
```

if you don't see some of the statements, then something's off with your gitlab CI setup. Otherwise, try gradually adding stuff to this snippet and see what exactly breaks the output.

**Comment by temp2612** [comment] 2022-08-16 23:49
The test was failing anyhow. Now I finally fixed it and it seems nothing is printed unless the test succeeds. Maybe some buffering issue? The output from PW is much more voluminous and thus might not be affected. I'll test that theory tomorrow.

**Comment by aslushnikov** [comment] 2022-08-17 06:50
@temp2612 ok, so this per se is not actionable unless we have a good simple repro that demonstrates the issue. Let me close this for now, but please do not hesitate to file a new issue if you have a good repro and you think the issue is on the playwright side!

Thanks!

**Closed by aslushnikov** 2022-08-17 06:50 UTC
Labels: triaging
