### ISSUE TITLE
[BUG] locator.hover({ force: true }) results browserContext.close failed - only on CI

### ISSUE THREAD

**Issue by IuliiaBondarieva** [microsoft/playwright#11173] opened 2022-01-04 17:11 UTC
**Context:**
- Playwright Version: playwright/test@1.17.1
- Operating System: Mac
- Node.js version: v14.17.4
- Browser: Chromium

**Code Snippet**

```javascript
    ...
    await expect(tooltip).not.toBeVisible();
    await infoIcon.hover({ force: true });
    await expect(tooltip).toBeVisible();
```

**Describe the bug**

```javascript
pw:api   scrolling into view if needed
pw:api   done scrolling
pw:api   performing hover action
pw:api   "networkidle" event fired
pw:api   hover action done
pw:api   waiting for scheduled navigations to finish
pw:api   navigations have finished
pw:api <= locator.hover succeeded
pw:api => expect.toBeVisible started
pw:api waiting for selector ".Tooltip"
pw:api   selector resolved to <div class="Tooltip …>…</div>
pw:api <= expect.toBeVisible succeeded
pw:api => browserContext.close started
pw:api => browser.close started
pw:api <= browserContext.close failed
pw:api <= browser.close succeeded

✘  [Chrome Stable] › src/basic.test.ts:7:1 › Basic (10s)
```

Add any other details about the problem here.
It happens only on CI (Jenkins)

I wanted to try option noWaitAfter from locator.hover([options])​ but it's not implemented, even so in docs you can find:
"Wait for initiated navigations to either succeed or fail, unless noWaitAfter option is set."

**Comment by IuliiaBondarieva** [comment] 2022-01-04 17:12
`page.close()` at the end did a trick, but it's still a BUG.

**Comment by pavelfeldman** [comment] 2022-01-04 21:07
It looks like the test failed and the browser was closed. Could you show the test output (console or html)? It is likely to be telling you what failed and why. The log you are showing is for low level debugging.

**Comment by IuliiaBondarieva** [comment] 2022-01-05 10:26
The only output was `Timeout of 10000ms exceeded` and all `expect` were green. It's an exact reason why I decided to look at low-level debugging.

**Comment by IuliiaBondarieva** [comment] 2022-01-05 10:51
The strange thing was that without using the `force: true` option the test also did not work on CI, but because it was waiting for the readiness of the component to hover. Locally everything worked fine.
We are very often confronted with the problem of a different response locally and on the CI system.

```
Timeout of 10000ms exceeded.

Pending operations:
- locator.hover at e2e/src/basicProfileViewPage.test.ts:45:30
locator.hover: Target closed

 =========================== logs ===========================

waiting for selector ".InfoIcon"
selector resolved to visible <div qa-regression-tag="tooltip" aria-label="Erklärun…></div>
attempting hover action
waiting for element to be visible and stable

============================================================
await expect(financing.infoIcon).toBeVisible();
await expect(financing.tooltip).not.toBeVisible();
await infoIcon.hover();
                 ^
await expect(tooltip).toBeVisible();
```

**Comment by pavelfeldman** [comment] 2022-01-07 00:45
That does not sound great. Is this something we could we could reproduce locally?

**Comment by IuliiaBondarieva** [comment] 2022-01-07 14:55
No, it was only by Jenkins :(

**Comment by aslushnikov** [comment] 2022-01-10 12:52
Unfortunately, I don't think we can fix this unless there's a good repro :( Please re-file if there's a repro; I'll close this meanwhile!

**Closed by aslushnikov** 2022-01-10 12:52 UTC
Labels: triaging

**Comment by IuliiaBondarieva** [comment] 2022-01-12 16:37
It's very sad. 'cause it is very important for us to be able to automate our tests.

**Comment by IuliiaBondarieva** [comment] 2022-01-12 16:40
The problem was solved after we added another test case after this one and we don't use `page.close()` as a fix. There seems to be a problem with closing browserContext at the end of the test.

**Comment by vivek1729** [comment] 2022-01-22 01:19
@IuliiaBondarieva, I think we might be running into a similar issue on our setup as well where hover tests don't pass reliably. 
I am not sure if I understood the fix fully. Essentially, did you remove `page.close` after this test case? Wasn't sure about the point of adding another test case too.

It would be great if you could elaborate on the mitigation that worked for you. An updated code snippet/ pseudo code would be super helpful to other folks in the community as well who might be running into the same issue.

**Comment by qk0106** [comment] 2022-02-10 01:01
My tests are randomly failing in CI only too.

The test is as simple as page.goto(), but constanly getting error "page.goto: Navigation failed because page was closed!"
