### ISSUE TITLE
[Bug]: Can't login into application in Webkit after update to 1.48.0

### ISSUE THREAD

**Issue by JanLechvar** [microsoft/playwright#33088] opened 2024-10-14 10:50 UTC
### Version

1.48.0

### Steps to reproduce

I'm not sure how to provide you with reproduction steps. 
Up until the latest version, I had no problems testing our application in the WebKit browser. 
However, since the update to 1.48.0, after filling in credentials and hitting the Login button, I am stuck on the login screen with an infinite loading animation. 
In the browser console, there is a timeout error after a couple of minutes: "Failed to load resource: Timeout was reached."

Please let me know what kind of information needs to be provided. I installed Playwright 1.48.0 alongside the browsers. All browsers behave properly except for WebKit.

The application worked fine in previous Playwright versions.

### Expected behavior

I expect to be able to login to the application, just like in previous versions of Playwright.

### Actual behavior

 Stuck on the login screen with an infinite loading animation after proceeding to log in.

![Image](https://github.com/user-attachments/assets/6531e087-dfe7-4f8c-9144-6a4f13dc04e7)

devDependencies": {
    "@playwright/test": "^1.48.0",
    "@types/node": "^22.0.0",
    "playwright": "^1.48.0",
    "typescript": "^5.5.4",
  },

### Environment

Windows 10 10.0.19045 Build 19045
node 20.15.0
npm 10.8.2
Playwright 1.48.0
Playwright/test 1.48.0

**Comment by dgozman** [comment] 2024-10-14 15:30
We need more information to act on this issue. Could you please provide a repro that we can run locally?

**Comment by bbchuoo** [comment] 2024-10-21 01:43
I'm experiencing the same issue where using WebKit with
page.goto
results in "Failed to load resource: Timeout was reached." It takes over 20 seconds to open the page, but it works fine in other browsers. This is very frustrating. Please fix it, thank you.

**Comment by bbchuoo** [comment] 2024-10-21 07:48
> We need more information to act on this issue. Could you please provide a repro that we can run locally?

I'm experiencing the same issue where using WebKit with
page.goto
results in "Failed to load resource: Timeout was reached." It takes over 20 seconds to open the page, but it works fine in other browsers. This is very frustrating. Please fix it, thank you.

Can you use WebKit to open any webpage and perform a click on the screen?
```
await page.goto(OOO);
await page.getByRole('button', { name: 'OOO' }).click();
```

In the --ui mode, you can see that await page.goto(OOO); results in a console message "Failed to load resource: Timeout was reached" and it gets stuck for about 20 seconds. In other browsers, page.goto only takes about 2 seconds.

**Comment by dgozman** [comment] 2024-10-21 07:56
@bbchuoo A repro would be very helpful. Unfortunately, running `page.goto(OOO)` does not work as a repro 😄

**Comment by bbchuoo** [comment] 2024-10-21 09:20
> [@bbchuoo](https://github.com/bbchuoo) A repro would be very helpful. Unfortunately, running `page.goto(OOO)` does not work as a repro 😄

Sorry, it's inconvenient to provide the URL for page.goto.
I tested using `await page.goto('https://playwright.dev');` and couldn't reproduce the error. 
Could you please try with a URL that requires a proxy setting to see if the issue can be reproduced? 
My playwright.config.ts has a proxy configured, and when I connect to any URL allowed by the proxy, I encounter "Failed to load resource: Timeout was reached".

**Comment by mxschmitt** [comment] 2024-10-21 17:01
I'll close it for now since this issue lacks a reproduction. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!

**Closed by mxschmitt** 2024-10-21 17:01 UTC

**Comment by JonasUnderscore** [comment] 2024-10-25 04:34
```
import { test } from "@playwright/test";

test("a", async ({ page }) => {
  await page.goto("https://github.com/");
  await page.evaluate(() =>
    fetch("https://api.githubcopilot.com/models", {
      method: "GET",
      headers: [["X-HeaderToTriggerPreflight", ""]],
    })
  );
});
```
The `fetch` times out (60s) on webkit-2083 (current).
It works on webkit-2095 (playwright beta) and on previous 17.x versions.
Running the bundled browser standalone and triggering a similar request also hangs, and the dev console crashes on reload.
Fetching from the dev console doesn't work either.

Using an older version or the beta version of playwright fixes the issue.
