### ISSUE TITLE
[BUG]  await page.click on empty div only chromium

### ISSUE THREAD

**Issue by Radli007** [microsoft/playwright#11745] opened 2022-01-31 09:18 UTC
**Context:**
- Playwright Version: 1.18.1
- Operating System: Windows 10
- Node.js version: v13.7.0
- Browser: Chromium
- Extra: - 

problem if div is empty 
`<span id="printMain.sex" />`
`  await page.click('[id="printMain\\.sex"]');`  - ERROR

if it is not empty, then there is no problem
`<div id="printMain.sex">man</div>`
`  await page.click('[id="printMain\\.sex"]');`  - THAT'S OK

```typescript
const test_url = 'https://t0wwp.csb.app/';

test('editSelect', async ({ page }) => {
  const def_sex = {"value": "Мужской", "key": "1" };
  await page.goto(test_url);

  await page.click('[id="docEdit"]');
  await page.click('label[role="radio"]:has-text("Администратор")');

  await page.waitForSelector('[id="printMain\\.sex"]')
  await page.click('[id="printMain\\.sex"]');
  await page.waitForTimeout(1000);
  await page.click('text='+def_sex.value);

  await page.click('[id="docJson"]');

  const jsontext = await page.evaluate(el => el.innerText, await page.$('#jsontext'))
  const js = JSON.parse(jsontext);
  await expect(js['sex'].key).toMatch(def_sex.key);

  await page.waitForTimeout(100);
});
```

error:

```
Timeout of 30000ms exceeded.
Pending operations:
  - page.click at tests\example.spec.ts:36:14

page.click: Target closed
=========================== logs ===========================
waiting for selector "[id="printMain\.sex"]"
  selector resolved to visible <span id="printMain.sex" contenteditable="true"> </span>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  element is not visible
retrying click action, attempt #1
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  element is not visible
  ...
```

But, That's OK:

```typescript
const test_url = 'https://t0wwp.csb.app/';

test('editDIV', async ({ page }) => {
  const def_fio = 'ABCDEF';

  await page.goto(test_url);

  await page.click('[id="docEdit"]');
  await page.click('label[role="radio"]:has-text("Администратор")');

  await page.waitForSelector('[id="printMain\\.fio"]')
  await page.click('[id="printMain\\.fio"]');
  await page.keyboard.type(def_fio);
  await page.waitForTimeout(1000);

  await page.click('[id="docJson"]');

  const jsontext = await page.evaluate(el => el.innerText, await page.$('#jsontext'))
  const js = JSON.parse(jsontext);
  await expect(js['fio']).toBe(def_fio);

  await page.waitForTimeout(100);
});
```

printMain\\.sex isn't visible after click anymore but another element with the same id (printMain\\.sex) becomes visible

Tests: https://gitlab.com/komtek-front/form-doc-test/-/blob/main/tests/example.spec.ts
Components: https://gitlab.com/komtek-front/form-doc

**Comment by yury-s** [comment] 2022-01-31 23:41
I can reproduce this. It fails only in Chromium, you can set the content to a space as workaround for now.

**Comment by pavelfeldman** [comment] 2022-10-20 03:14
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-10-20 03:14 UTC
Labels: browser-chromium, P3-collecting-feedback
