### ISSUE TITLE
[Feature] extension message passing in non-persistent context

### ISSUE THREAD

**Issue by leonardodino** [microsoft/playwright#4441] opened 2020-11-15 00:14 UTC
**Context:**
- Playwright Version: 1.5.1, 1.6.1
- Operating System: Mac (local) Linux (via CI)
- Node.js version: 14.x
- Browser: Chromium
- Extra: non-headless

**Code Snippet**

`chrome.tabs.sendMessage` fails on fails on `chromium.launch`, but not on `chromium.launchPersistentContext`

```javascript
// @filename content.js
chrome.runtime.sendMessage(undefined, message)


// @filename background.js
chrome.runtime.onMessage.addListener((message, sender) => {
  if (typeof sender?.tab?.id !== 'number') return
  chrome.tabs.sendMessage(sender.tab.id, message, { frameId: 0 }) // 💥
})
```
> 💥 `"Could not establish connection. Receiving end does not exist."`

**Describe the bug**

I've created a [repo](https://github.com/leonardodino/playwright-extension-bug) to further describe and isolate this bug.

the only dependencies are `node` and `playwright` itself.

the log on [GitHub Actions](https://github.com/leonardodino/playwright-extension-bug/actions?query=workflow%3ATest) help with visualising the mismatch between the persistent context and the default ones.

I wasn't able to reproduce it on a Chromium Incognito window locally. 🤔

**Comment by aslushnikov** [comment] 2020-11-17 08:23
> I wasn't able to reproduce it on a Chromium Incognito window locally. 🤔

@leonardodino by default, extensions don't run in incognito windows in Chromium (so they don't run for you in the Playwright default context). I tried with your extension, and it doesn't run in incognito as well. Could it be that you explicitly enable it in extension settings? 

![image](https://user-images.githubusercontent.com/746130/99364638-0e368d80-286b-11eb-98e4-f8133ae6435c.png)

**Comment by leonardodino** [comment] 2020-11-17 12:52
Hey there @aslushnikov thanks for the quick turn around!

sorry! I indeed wrote it a bit weird 😅
I was able to get it working on chrome+chromium install, after enabling this flag.

The extension fails when running on playwright (and puppeteer) in a way that I'm not able to reproduce on regular browsers:

<table>
<tr>
	<td>browser
	<td>persistent
	<td>incognito
<tr>
	<td>chrome
	<td><img width="1084" alt="Screen Shot 2020-11-17 at 12 39 38" src="https://user-images.githubusercontent.com/8649362/99391976-e4b14c80-28d2-11eb-93e7-aa9c9ff2c970.png">
	<td><img width="1084" alt="Screen Shot 2020-11-17 at 12 39 33" src="https://user-images.githubusercontent.com/8649362/99391997-eaa72d80-28d2-11eb-8214-0892a1c9d347.png">
<tr>
	<td>chromium
	<td><img width="1233" alt="Screen Shot 2020-11-17 at 12 47 35" src="https://user-images.githubusercontent.com/8649362/99392106-17f3db80-28d3-11eb-8a87-f11251c32cff.png">
	<td><img width="1233" alt="Screen Shot 2020-11-17 at 12 47 39" src="https://user-images.githubusercontent.com/8649362/99392117-1cb88f80-28d3-11eb-8439-c95254363a79.png">
<tr>
	<td><b>playwright</b>
	<td><img width="1394" alt="Screen Shot 2020-11-17 at 12 41 33" src="https://user-images.githubusercontent.com/8649362/99392167-322db980-28d3-11eb-965f-ef995d4c5c85.png">
	<td><img width="1394" alt="Screen Shot 2020-11-17 at 12 41 40" src="https://user-images.githubusercontent.com/8649362/99392191-3c4fb800-28d3-11eb-9ae8-41be199fa0af.png">
</table>

---

I'm also enabling the ["run in incognito" on the plawright run](https://github.com/leonardodino/playwright-extension-bug/blob/main/test.js#L39-L41). 😄

([the first `console.log`](https://github.com/leonardodino/playwright-extension-bug/blob/main/test.js#L18) certifies that the extension is actually running and has injected a `div`)


```
$ node .
==== persistent ====
DOM insertion: true
clock updated: true
==== inconigto ====
DOM insertion: true
clock updated: false 
```

**Comment by pavelfeldman** [comment] 2020-11-19 17:11
> chrome.tabs.sendMessage fails on fails on chromium.launch, but not on chromium.launchPersistentContext

This is by design. At this point, support for extensions in Playwright is in the best effort mode. We focus on the cross-browser web testing instead. In order to test extensions, you should run Playwright in a mode that is as close to the regular execution as possible, in this case it means running it as `chromium.launchPersistentContext` and specifying the user data dir.

**Comment by leonardodino** [comment] 2020-11-19 23:38
Hey, thanks again for the support (:

> This is by design. At this point, support for extensions in Playwright is in the best effort mode. We focus on the cross-browser web testing instead.

Fully understand and support this decision! 🙌 extensions are indeed an edge-case.
and I'm happy they are supported, even if by chance! 😄 

> running it as `chromium.launchPersistentContext` and specifying the user data dir.

yep, using it currently, together with `jest-playwright` and everything works. 💯 

just wanted to report because it took me a good while to understand why it was failing 😅
hopefully can save some minutes/hours for the next one.

**Comment by pavelfeldman** [comment] 2021-03-02 19:47
Thank you for reporting this issue and providing comments to those that might be facing a similar problem. I am now closing this as a part of the triage, please feel free to file a new issue with additional details. Given the limited resource and a lot of requests, we need to fulfill most popular requests and at the same time keep our issue database manageable.

**Closed by pavelfeldman** 2021-03-02 19:47 UTC
Labels: P3-collecting-feedback
