### ISSUE TITLE
[BUG] UI Mode errors tab

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#26965] opened 2023-09-08 19:20 UTC
### System info
- Playwright Version: [^1.38.0-alpha-sep-8-2023]
- Operating System: [Mac]
- Browser: [Chromium]
- Other info:

### Source code

- [ yes] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```js
test('get started link', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Click the get started link.
  await page.getByRole('link', { name: 'Get started' }).click();
  
  // Expects the URL to contain intro.
  await expect(page.getByRole('heading', { name: 'Debbie' })).toBeVisible();
  await page.getByRole('link', { name: 'Debbie' }).click();
});
```

**Steps**
- [Run the test in ui mode or with trace on]

**Expected**

there are 2 errors in my test so it should show 2

**Actual**

Errors tab has a red circle with 1 in it which is misleading as there are more than 1 errors.

Using `soft` it will show both errors and this is something we can document to help users however I still feel it is misleading a little as it kinda says hey you only have 1 error but its actually you only have 1 error up until the time the test failed. Yet we never really state this.

Maybe in the errors tab we could add a message to state this and to say run your test with `.soft` if you would like to see all errors for your test or something along those lines.

**Comment by pavelfeldman** [comment] 2023-09-08 19:48
Closing as working as intended as per offline discussion.

**Closed by pavelfeldman** 2023-09-08 19:48 UTC
