### ISSUE TITLE
[Bug]: Webkit (Safari desktop and mobile) fail random

### ISSUE THREAD

**Issue by Piero87** [microsoft/playwright#30428] opened 2024-04-19 12:59 UTC
### Version

1.43.1

### Steps to reproduce

I have random crash with webkit browser mobile and desktop, I execute test inside a docker image builded with this:

https://github.com/microsoft/playwright/blob/v1.43.1/utils/docker/build.sh

CI/CD use Gitlab CI and Kubernets execution, and when it fail we don't any error on our system.

this is I think the important part of the code:

playwright.config.ts

```
import { TEST_ID_ATTRIBUTE } from '@mop/constants';
import type { PlaywrightTestConfig, ReporterDescription } from '@playwright/test';
import { devices } from '@playwright/test';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */

require('dotenv').config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
const config: PlaywrightTestConfig = {
  testDir: './tests',
  // TODO: timeout aumentato da 30s a 60s a causa della clone_instance che impiega dai 13 ai 17 secondi. Possiamo ridurre a 30 se lato BE si
  // riuscirà ad ottimizzare la clone.
  /* Maximum time one test can run for. */
  timeout: 60 * 1000,
  expect: {
    /**
     * Maximum time expect() should wait for the condition to be met.
     * For example in `await expect(locator).toHaveText();`
     */
    timeout: 5000
  },
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 1 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : 1,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: process.env.CI ?
    [['blob', { fileName: `report-${process.env.PROJECT}.zip` }],]
    :
    [['html', { open: 'never' }]]
  ,
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    // headless: false,
    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    actionTimeout: 0,
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://localhost:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: "retain-on-failure",
    // video: 'on-first-retry',
    // screenshot: 'on',
    testIdAttribute: TEST_ID_ATTRIBUTE,
    ignoreHTTPSErrors: true,
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },

    // /* Test against mobile viewports. */
    {
      name: 'mobile-chrome',
      use: { ...devices['Galaxy S8'] },
    },
    {
      name: 'mobile-safari',
      use: { ...devices['iPhone 13'] },
    },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { ...devices['Desktop Chrome'], channel: 'chrome' },
    // },
  ],

  /* Folder for test artifacts such as screenshots, videos, traces, etc. */
  outputDir: 'test-results/',

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   port: 3000,
  // },
};

export default config;
```

I use playwright fixture

```
import { test as base } from '@playwright/test';
import { cloneDb, onTestEnd } from './api/api';
import { MopInstance } from './pom/mop-instance';
import { MopPage } from './pom/mop-page';
import { Page } from './types/mopPage';
import { User } from './types/user';
import { checkSkip } from './skipped';

type TestFixtures = {
  dbName: string;
  lang: string;
  user: User
  MOP: any
  route?: Page
};

export const test = base.extend<TestFixtures>({
  dbName: "",
  lang: "",
  user: {
    username: "",
    password: "",
    id: ""
  },
  route: null,
  // Override default "page" fixture.
  MOP: async ({ browser, dbName, user, lang, route }, use, testInfo) => {
    
    if (checkSkip(testInfo.titlePath[0], testInfo.project.name)) test.skip();

    const _clonedDb = await cloneDb(dbName);
    if (!_clonedDb) throw new Error('Cloned Db is undefined.');
    const instance = await MopInstance.create({ lang, dbName: _clonedDb})
    const _MopPage = await MopPage.create({browser, lang, dbName: _clonedDb, user, configs: instance.configs})
    
    // Apriamo il mop
    await _MopPage.goto(route)

    await use({ instance, page: _MopPage.page, MopPage: _MopPage });
  },
});

test.afterEach(async ({ MOP: { instance } }) => {
  if (!instance) return
  await onTestEnd({ dbName: instance.dbName })
})

export { expect } from '@playwright/test';
```

```
import { getAPIHostname, getBaseHostname, isDetached } from "@mop/utils";
import { Browser, expect, Locator, Page } from "@playwright/test";

export class MopPage {
  page: Page
  lang: string
  dbName: string
  user: User
  configs: {[key:string]: any}
  Header: Header
  Login: Login
  Search: Search
  Availabilities: Availabilities
  Profile: Profile
  Reservation: Reservation
  Payment: Payment
  Dossier: Dossier

  constructor(page: Page, lang: string, dbName: string, user: User, configs: MopConfigs) {
    this.page = page
    this.lang = lang
    this.user = user
    this.configs = configs
    // Per questa riga del dbName leggere README nella parte dello sviluppo locale (punto 3)
    this.dbName = dbName

    // POM
    this.Header = new Header(this)
    this.Login = new Login(this)
    this.Reservation = new Reservation(this)
    this.Search = new Search(this)
    this.Availabilities = new Availabilities(this)
    this.Profile = new Profile(this)
    this.Payment = new Payment(this)
    this.Dossier = new Dossier(this)
  }

  static async create(
    { browser, lang, dbName, user, configs }: { browser: Browser, lang: string, dbName: string, user: User, configs: MopConfigs }
  ) {
    try {
      const context = await browser.newContext();
      const page = await context.newPage();
      if (isDetached()) {
        await context.addInitScript(({ dbName, hostname }) => {

          if (window.location.href.indexOf('mop/index.php') !== -1) {
            window.e2e = true;
            window.dbNameTestE2E = dbName;
            window.hostnameTestE2E = hostname;
          }
        }, { dbName, hostname: getAPIHostname() });
      }

      return new MopPage(page, lang, dbName, user, configs);

    } catch (error) {
      console.log("Playwright page creation error:", error);
    }
  }

  async goto(route?: PageName) {
    const _route = route ? `#${route}` : '';
    const dbName = isDetached() ? process.env.DUMMY_DBNAME : this.dbName;
    const query = qs.stringify({ lang: this.lang, dbName }, { skipNulls: true });

    /**
     * Questo è stato fatto per risolvere quei casi in cui alla login vogliamo recuperare l'id dell'utente loggato
     * a causa di un limite dei browser (principalmente sembra di chrome) non era possibile leggere la risposta dal network
     * utilizzando la waitForResponse, per questa ragione utilizzando la route leggo tutte le chiamate api che passano e prendo quello che mi interessa
     * quindi il flusso viene bloccato fino a che non viene fatto il continue o il fullfill della risposta che si vuole leggere
     *  
     * */    
    await this.page.route(
      '**/*',
      async (route) => {
        try {
          // Make the original request
          const url = route.request().url();
          if (url.indexOf("fn=login") !== -1) {
            const response = await route.fetch();

            if (response.status() === 200) {
              const data = await response.json();
              this.setUserId(data.return.userid)
            }
            route.fulfill({ response });

          } else {
            route.continue()
          }
        } catch (error) {
          console.log(error);
        }

      }
    );

    return this.page.goto(`${getBaseHostname()}/mop/index.php?${query}${_route}`);
  }
}
```

The error that I receive from playwright in webkit execution are these:

```
Error: locator.click: Target page, context or browser has been closed
Browser logs:
<launching> /ms-playwright/webkit-1992/pw_run.sh --inspector-pipe --headless --no-startup-window
<launched> pid=1900
[pid=1900][err]
[pid=1900][err] (MiniBrowser:1906): GStreamer-WARNING **: 08:47:16.018: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.
[pid=1900][err]
[pid=1900][err] (MiniBrowser:1906): GStreamer-WARNING **: 08:47:16.055: Failed to load plugin '/ms-playwright/webkit-1992/minibrowser-wpe/sys/lib/gst/libgstfdkaac.so': libfdk-aac.so.1: cannot open shared object file: No such file or directory
[pid=1900][err]
[pid=1900][err] (MiniBrowser:1906): GStreamer-WARNING **: 08:47:16.078: Failed to load plugin '/ms-playwright/webkit-1992/minibrowser-wpe/sys/lib/gst/libgstkate.so': libkate.so.1: cannot open shared object file: No such file or directory
[pid=1900][err]
[pid=1900][err] (MiniBrowser:1906): GStreamer-WARNING **: 08:47:16.216: Failed to load plugin '/ms-playwright/webkit-1992/minibrowser-wpe/sys/lib/gst/libgstopenexr.so': libIlmImf-2_3.so.24: cannot open shared object file: No such file or directory
[pid=1900][err]
[pid=1900][err] (MiniBrowser:1906): GStreamer-WARNING **: 08:47:16.262: Failed to load plugin '/ms-playwright/webkit-1992/minibrowser-wpe/sys/lib/gst/libgstvideo4linux2.so': libv4l2.so.0: cannot open shared object file: No such file or directory
[pid=1900][err] EGLDisplay Initialization failed: EGL_NOT_INITIALIZED
[pid=1900][err] Could not determine the accessibility bus address
[pid=1900][err] /ms-playwright/webkit-1992/pw_run.sh: line 24:  1906 Killed                  WEBKIT_FORCE_COMPLEX_TEXT="1" "$MINIBROWSER" "$@"
[pid=1900] <process did exit: exitCode=137, signal=null>
[pid=1900] starting temporary directories cleanup
[pid=1900] finished temporary directories cleanup
Call log:
  - waiting for getByTestId('menu-bottom-bar')
   at ../src/pom/mop-page.ts:136
  134 |   async click(element: string | Locator, options = {}) {
  135 |     if (typeof element === "string") {
> 136 |       await this.page.getByTestId(element).click(options)
      |                                            ^
  137 |     } else {
  138 |       await element.click(options)
  139 |     }
    at MopPage.click (/builds/-Cnf8Ebd/4/tuotempo/trunk/mop/tests-e2e/packages/mop/src/pom/mop-page.ts:136:44)
    at Header.openMobileSideMenu (/builds/-Cnf8Ebd/4/tuotempo/trunk/mop/tests-e2e/packages/mop/src/pom/header.ts:97:24)
    at Header.goToProfile (/builds/-Cnf8Ebd/4/tuotempo/trunk/mop/tests-e2e/packages/mop/src/pom/header.ts:37:64)
    at /builds/-Cnf8Ebd/4/tuotempo/trunk/mop/tests-e2e/packages/mop/tests/efaf157e64dd47e8ac1b914d82b365ce.spec.ts:11:28
    at /builds/-Cnf8Ebd/4/tuotempo/trunk/mop/tests-e2e/packages/mop/tests/efaf157e64dd47e8ac1b914d82b365ce.spec.ts:9:14

```

I don't have any problems with other browser.

I see others issues related to this problem like these:

https://github.com/microsoft/playwright/issues/27615
https://github.com/microsoft/playwright/issues/27855

In one of those you suggest to install manunally the packages that fail, we have also tried that, but the browser still fail only with less errors

### Expected behavior

That webkit browser works without error

### Actual behavior

In my test suite of 20 tests random everytime fail some tests

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 13.34 GB / 15.36 GB
    Container: Yes
  Binaries:
    Node: 20.11.1 - /usr/bin/node
    npm: 10.2.4 - /usr/bin/npm
    pnpm: 8.11.0 - /usr/bin/pnpm
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1
    playwright-slack-report: ^1.1.58 => 1.1.58
```

**Comment by yury-s** [comment] 2024-04-19 16:29
Can you share a self-contained example that triggers the crash, so that we could run it locally?

**Comment by yury-s** [comment] 2024-04-19 17:34
> [pid=1900] <process did exit: exitCode=137, signal=null>

The process was apparently killed with SIGKILL (9), which might happen in Kubernetes if the process starts taking too much memory. Could it be that the browser gets killed on the CI because it taking more memory that it is allowed to?

**Comment by Piero87** [comment] 2024-04-22 09:12
> 
> [pid=1900]
> 
> The process was apparently killed with SIGKILL (9), which might happen in Kubernetes if the process starts taking too much memory. Could it be that the browser gets killed on the CI because it taking more memory that it is allowed to?


Kubernetes doesn't kill the CI Pod because it reached memory limits, we already checked this point before open the issue, is not present an event of OOM Killed also the CI Pod have completed correctly the Job because playwright continues it's job after webkit process die

>  Can you share a self-contained example that triggers the crash, so that we could run it locally?

we have to understand how can you test it because the url is private, what you need?

**Comment by yury-s** [comment] 2024-04-22 16:10
> we have to understand how can you test it because the url is private, what you need?

We need a project that we could run locally to reproduce the issue. Hopefully you can extract relevant part to a reproduction that does not expose any sensitive bits of the private project.

**Comment by pavelfeldman** [comment] 2024-04-26 21:50
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Closed by pavelfeldman** 2024-04-26 21:50 UTC
