### ISSUE TITLE
[BUG] generator sometimes recording part of test outside test block

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#18808] opened 2022-11-15 07:11 UTC
**Context:**
- Playwright Version: 1.29.0-alpha-nov-15-2022
- Operating System: Mac
- Node.js version: [e.g. 12.22, 14.6]
- Visual Studio Code version: v0.2.16 
- Playwright for VSCode extension version: [e.g. 1.2.3]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

Open codegen from vs code extension and write a test then click on the page in vscode and then continue generating your test

**Describe the bug**

when generating tests in codegen it starts to write part of the tests outside the codeblock when you click over in VS code. Its as if the record from cursor then takes over and as the cursor is automatically at the end of the test it then continues to write the rest of the test outside of the test block. 

it should only record at cursor if I specifically click record at cursor and I should be able to go tp vs code to inspect what was generated and then continue generating.

<img width="1018" alt="Screenshot 2022-11-15 at 07 58 56" src="https://user-images.githubusercontent.com/13063165/201852707-53683187-6378-4747-9b93-ebe9a0e05447.png">

https://user-images.githubusercontent.com/13063165/201852754-94632756-85f9-4622-b622-0e55cb175da7.mov

**Comment by aslushnikov** [comment] 2022-11-15 20:25
We think it works as intended; closing as per discussion on the team meeting!

**Closed by aslushnikov** 2022-11-15 20:25 UTC
Labels: v1.28
