### ISSUE TITLE
[BUG] Playwright refuses to load some pages via proxy in Firefox

### ISSUE THREAD

**Issue by brettneese** [microsoft/playwright#10095] opened 2021-11-05 19:43 UTC
**Context:**

### System:
 - OS: macOS 12.0.1
 - Memory: 7.83 GB / 64.00 GB
 
### Binaries:
 - Node: 16.11.1 - ~/.asdf/installs/nodejs/16.11.1/bin/node
 - Yarn: 1.22.17 - /usr/local/bin/yarn
 - npm: 8.0.0 - ~/.asdf/plugins/nodejs/shims/npm

### Languages:
 - Bash: 3.2.57 - /bin/bash
 
### npmPackages:
 - playwright: ^1.16.3 => 1.16.3 
 
**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript

const { chromium, webkit, firefox } = require("playwright");

(async function () {
  const browser = await firefox.launch({
    headless: false,
    ignoreHTTPSErrors: true,
    proxy: {
      server: "$SERVER",
      username: "$UN",
      password: "$PWD",
    },
  });

  const page = await browser.newPage();

  let response = await page.goto(
    "https://www.github.com"
  );
})();

```

**Describe the bug**

For some pages using the Firefox engine, Playwright will not load them at all when given a proxy -- it'll just spin until it gets a timeout error. For example, https://www.github.com: http://recordit.co/cXjdMkOG1X

Other pages work just fine. For example, Reddit: https://recordit.co/WFKZB0b0sG

The Chromium engine does not have this problem, and I have tried multiple HTTP proxies, so it's not an issue with the specific proxy or the site. Playwright loads sites just fine without the proxy. 

(I'm using https://brightdata.com proxies, if you'd like to test this on your own).

**Comment by rfleuryleveso** [comment] 2021-11-05 21:39
I have the exact same issue.
From experimentations, it looks like:

- That doesn't seem related to HTTP Version.
- I'm using another proxy provider, and I have the same issue, so it's not tied to the proxy provider.
- This doesn't happen with local mitmproxy.
- it only happens after a few redirections (3, in my case, with different domains). But that could be only in my case.

**Comment by mxschmitt** [comment] 2021-11-07 16:32
Would it be possible to make a reproducible out of this without the need for us to subscribe to an external SaaS proxy reseller? Usually we use squid proxy when testing / reproducing proxy issues across browsers.

**Comment by mxschmitt** [comment] 2021-11-09 17:16
Would it be possible that you provide us the squid server configuration or docker run command so we can reproduce?

I tried with squid proxy configured + navigating to github.com which works for me in Firefox.

**Comment by brettneese** [comment] 2021-11-15 17:15
@mxschmitt Seems to be related to authentication, as I suspected. I was using one of our production proxies, so I can't share that, but I was able to replicate the problem locally/with Docker with this: https://gist.github.com/brettneese/42d2203ff1348ca45323ecd2319acfab

(which I based on your `mxschmitt/try-playwright` repo)

**Comment by aslushnikov** [comment] 2021-12-16 07:34
This is fixed on tip-of-tree now. The fix will be available tomorrow at @next channel: `npm i @playwright/test@next`

**Closed by aslushnikov** 2021-12-16 07:34 UTC
Labels: v1.18

**Comment by brettneese** [comment] 2021-12-28 16:00
@aslushnikov I was away for the holidays, but thanks!!! I'm glad I wasn't hallucinating or doing something wrong.
