### ISSUE TITLE
[BUG] page.waitForResponse -doesn't display all network calls that are listed on the browser(network tab) and it keeps waiting for the response.

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#27901] opened 2023-11-01 13:29 UTC
### System info
- Playwright Version: 1.36.2
- Operating System: Mac
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

page.waitForResponse keeps waiting for the response, When i manually click on the button, browser displays all network calls including the one **/crew-member-accruals?base=**&page=2&size=20&sort=baseSeniority,asc that i expect playwright to wait and proceed.

however when i try to log both the request and responses, it doesn't list /crew-member-accruals?base=**&page=2&size=20&sort=baseSeniority,asc  on the console(command prompt), but i see them on the browser. Attached is the screenshot of both the browser and the console. Can you pleaser advise what is causing playwright to wait for ever and what is causing the network logs not to display on the console, when i can see them on the browser when i click on the button manually?

both these urls are missing in the log , (browser displays them however under network tabs). tried two different approaches as mentioned in the code snippet below 
/crew-member-accruals?base=ATL&page=1&size=20&sort=baseSeniority,asc
/crew-member-accruals?base=ATL&page=2&size=20&sort=baseSeniority,asc

```javascript
 page.on('request', request => {
            console.log('>>', request.method(), request.url())
        });

        page.on('response', response => {
            console.log('>>', response.status(), response.request().url())
        });

const crewMemberAccrualPromise = page.waitForResponse('**/crew-member-accruals?base=**&page=2&size=20&sort=baseSeniority,asc');
        await page.getByTestid('accruals').click();
        await crewMemberAccrualPromise;
```

```javascript
 const [crewMemberAccrualPromise] = await Promise.all([
 page.waitForResponse('**/crew-member-accruals?base=**&page=2&size=20&sort=baseSeniority,asc'),
     //  page.waitForResponse(res => res.url().includes('/crew-member-accruals?base=ATL&page=2&size=20&sort=baseSeniority,asc')),
      page.getByTestid('accruals').click();
         ])
   await crewMemberAccrualPromise;
```

<img width="1582" alt="Screen Shot 2023-11-01 at 8 17 01 AM" src="https://github.com/microsoft/playwright/assets/113629123/698f3944-da08-4618-9d54-676fef405f9f">

<img width="1674" alt="Screen Shot 2023-11-01 at 9 03 12 AM" src="https://github.com/microsoft/playwright/assets/113629123/166fb658-cb56-4b5d-b9a5-b33a7e473b2d">

**and when i manually load network calls on the browser launched by playwright, this is how it looks like, it is not loading /crew-member-accruals?base=ATL&page=1&size=20&sort=baseSeniority,asc
/crew-member-accruals?base=ATL&page=2&size=20&sort=baseSeniority,asc
on the UI launched by playwright.**

base-options is the last call i see, and /crew-member-accruals?base=ATL&page=1&size=20&sort=baseSeniority,asc i snot listed,
<img width="978" alt="Screen Shot 2023-11-01 at 9 41 54 AM" src="https://github.com/microsoft/playwright/assets/113629123/105ffcf0-f4f3-4571-8abb-d7981f86fea7">

**Comment by pavelfeldman** [comment] 2023-11-01 17:52
We would need a local repro to be able to act on this issue.

**Comment by InduKrish** [comment] 2023-11-01 18:11
for security reasons, we are unable to share the repo, but can you please advise what is causing the issue in general, why page.waitforResponse is not able to list all the requests that i see on the browser when i manually test... is there any rule/flag in playwright that blocks certain requests? when i reload the page on the UI launched by playwright, i don't find the urls there either.. why playwright UI is not loading all the URI that the browser is loading when we test manually?  Please advise if there are any rule in playwright that we should be aware of in order to capture all network requests/responses.

**Comment by pavelfeldman** [comment] 2023-11-02 19:33
I won't be able to tell without being able to reproduce.

**Comment by InduKrish** [comment] 2023-11-02 22:44
reports/awards-alpha?base=AUS&round=5  ---> 1 st url
reports/awards-alpha?round=5&base=AUS&page=1&size=20.  -> 2nd url
reports/awards-alpha?round=5&base=AUS&page=2&size=20. ---> 3 rd url
i do have three urls loaded after i select the value from the dropdown, i am interested to capture only 2nd and 3rd
 page.on('request', request => {
            console.log('>>', request.method(), request.url())
        });

        page.on('response', response => {
            console.log('>>', response.status(), response.request().url())
        });


const [awardsAlphabeticalAUSPage1, awardsAlphabeticalAUSPage2, awardsAlphabeticalAUSPage3] = await Promise.all([
   
    page.waitForResponse('**/reports/awards-alpha?round=5&base=DAL&page=1&size=20'),
    page.waitForResponse('**/reports/awards-alpha?round=5&base=DAL&page=2&size=20'),
 
    page.getByTestid('a').click();
])
it does not load second and third urls on the console. am wondering it is because the first url also starts with /reports/awards-alpha? ---> is it blocked there thinking the URL doesnt match?

**Comment by pavelfeldman** [comment] 2023-11-05 22:04
I'll close it as non-actionable since I've requested a local repro twice w/ no result.

**Closed by pavelfeldman** 2023-11-05 22:04 UTC
Labels: triaging

**Comment by athiele** [comment] 2024-05-07 14:16
Hi,

we are experiencing the same problem on linux. Unfortunately, it is difficult to reproduce on publicly available websites, and I cannot share our application.

If we execute this code, in around 10% of the executions, the "waitForResponse" times out:
```typescript
  await page.goto("<redacted>");

  // here the occasional timeout occurs
  const response = await page.waitForResponse(
    (resp) => {
      return resp.url().includes("/graphql") && resp.status() === 200;
    }
  );
```
The reason seems to be that in these cases, no response matching "/graphql" is being captured, even though the /graphql call was definitely fired on the website.

Luckily enough, I found a workaround. It is not obvious to me why it works, but I am running the tests in a loop for an hour in a row without error, so it definitely works for us.

The workaround is:
```typescript
 // workaround start; you need to do it before the page.goto();
 page.on("response", async (response) => {
    if (response.url().includes("/graphql")) {
      await new Promise((resolve) => setTimeout(resolve, 10));
    }
  });
  // workaround end

  await page.goto("<redacted>");

  const response = await page.waitForResponse(
    (resp) => {
      return resp.url().includes("/graphql") && resp.status() === 200;
    }
  );

```

For us, now the "waitForResponse" never runs into a timeout again.
Hope that helps.
