### ISSUE TITLE
[Bug]: `ignore_https_errors` sometimes does not take effect

### ISSUE THREAD

**Issue by harlansgs** [microsoft/playwright#32801] opened 2024-09-24 18:29 UTC
### Version

1.47.0

### Steps to reproduce

```
from playwright.async_api import async_playwright
import asyncio
import tempfile


async def main():
    async with async_playwright() as p:
        with tempfile.TemporaryDirectory() as profile1, \
             tempfile.TemporaryDirectory() as profile2:
            # Launch first persistent context
            browser1 = await p.chromium.launch_persistent_context(user_data_dir=profile1, ignore_https_errors=False)
            page1 = await browser1.new_page()
            await page1.goto('https://example.com')

            # Launch second persistent context
            browser2 = await p.chromium.launch_persistent_context(user_data_dir=profile2, ignore_https_errors=True)
            page2 = await browser2.new_page()

            # In rare cases: ignore_https_errors will fail, throwing the error
            await page2.goto('https://untrusted-root.badssl.com/')

            await browser1.close()
            await browser2.close()
```

### Expected behavior

Second browser context with `ignore_https_errors=True` should navigate to the target page without error.

### Actual behavior

In very rare cases, we see the second browser context's `ignore_https_errors` flag fail. This results in an `ERROR: unable to verify the first certificate`.

### Additional context

We had been using Playwright 1.36.0 for quite some time, and recently updated to 1.47.0. We are now seeing this bug (very rarely) with the new default Chromium version `129.0.6668.29`. As described in the reproduction example, we are using the async Playwright bindings and launching two persistent Chromium contexts. This is not a major issue for us, so just wanted to check in here and see if there might have been some known change here for certificate parsing in Chromium/Playwright?

### Environment

```Text
- Operating System: [Ubuntu 22.04]
- CPU: [x86]
- Browser: [Chromium]
- Python Version: [3.9]
- Other info:
```

**Comment by mxschmitt** [comment] 2024-10-01 07:42
I'll close it for now since we can't reproduce as part of the triage process. Maybe a loop helps? Don't hesitate to re-file with more details. Thanks!

**Closed by mxschmitt** 2024-10-01 07:42 UTC
