### ISSUE TITLE
[BUG] Assertion Error 

### ISSUE THREAD

**Issue by aidan-pf** [microsoft/playwright#23638] opened 2023-06-10 17:47 UTC
### System info
- Playwright Version: v1.34.0 and v1.32.0
- Operating System: Ubuntu 22.04, Ubuntu 20.04
- Browser: Firefox
- Other info: Running in Docker

### Source code

```
if (!value) throw new Error(message || 'Assertion error');

Error: Assertion error
    at assert (/usr/local/lib/python3.8/dist-packages/playwright/driver/package/lib/utils/debug.js:29:21)
    at FrameManager.frameAttached (/usr/local/lib/python3.8/dist-packages/playwright/driver/package/lib/server/frames.js:103:25)
    at FFPage._onFrameAttached (/usr/local/lib/python3.8/dist-packages/playwright/driver/package/lib/server/firefox/ffPage.js:174:30)
    at FFSession.emit (node:events:513:28)
    at /usr/local/lib/python3.8/dist-packages/playwright/driver/package/lib/server/firefox/ffConnection.js:204:41

Node.js v18.15.0
```
**Link to the GitHub repository with the repro**
https://github.com/aidan-pf/playwrightbug

**Other's who mentioned this same issue:**
https://github.com/microsoft/playwright/issues/22315

**Steps**
Every few hundred requests, playwright will throw the error described above.
To reproduce the results, I provided a link to a GH repo w/ Dockerfile, Playwright setup, etc. to reproduce the issue.

**Comment by aslushnikov** [comment] 2023-07-05 15:21
@aidan-pf I tried to reproduce this on 1.35.1, but this doesn't happen for me anymore. Could you please check if this works for you too?

**Comment by aslushnikov** [comment] 2023-07-10 12:59
Closing this since we can no longer repro. Please feel free to file a new issue if this still reproes for you on new Playwright version!

**Closed by aslushnikov** 2023-07-10 12:59 UTC
Labels: browser-firefox, v1.36

**Comment by Darshan972** [comment] 2026-05-02 10:32
Is this issue solved?
