### ISSUE TITLE
[BUG] Playwright takes long time to close browser

### ISSUE THREAD

**Issue by kingyue737** [microsoft/playwright#27679] opened 2023-10-18 11:20 UTC
### System info
- Playwright Version: [v1.39]
- Operating System: [Windows 11 22631.2428]
- Browser: [Windows Built-in Edge]
- Other info: edge 117.0.2045.60

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/kingyue737/playwright-test

or

**Config file**

```js
// playwright.config.ts
import type { PlaywrightTestConfig } from "@playwright/test";
import { devices } from "@playwright/test";

const config: PlaywrightTestConfig = {
  testDir: "./e2e",
  timeout: 30 * 1000,
  expect: {
    timeout: 5000,
  },
  use: {
    actionTimeout: 0,
    headless: false,
  },
  reporter: "html",
  projects: [
    {
      name: "Microsoft",
      use: {
        ...devices["Desktop Edge"],
        channel: "msedge",
      },
    },
  ],
};

export default config;
```

**Test file (self-contained)**

"visit google" test
```js
test("example", async ({ page }) => {
  await page.goto("https://www.google.com");
});
```

"visit baidu" test
```js
test("example", async ({ page }) => {
  await page.goto("https://www.baidu.com");
});
```

**Steps**
- Run each test

**Expected**

Playwright should finish immediately after the test has passed.

**Actual**

It takes long time for Playwright to exit. And the duration varies from test to test. "visit google" takes 3 seconds while "visit baidu" takes 8 seconds.

log with `DEBUG=pw:browser*`
"visit google":

```
Running 1 test using 1 worker
[Microsoft] › google.spec.ts:3:5 › example
  pw:browser <launching> C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --no-sandbox --user-data-dir=C:\Users\yueji\AppData\Local\Temp\playwright_chromiumdev_profile-6SI2Ok --remote-debugging-pipe --no-startup-window +0ms
  pw:browser <launched> pid=32548 +12ms                                                                                                                                                                            
  pw:browser [pid=32548][err] [32548:8096:1017/181752.575:ERROR:assistance_home_client.cc(32)] File path C:\Users\yueji\AppData\Local\Temp\playwright_chromiumdev_profile-6SI2Ok\Default +22ms
  pw:browser [pid=32548] <gracefully close start> +3s
  pw:browser [pid=32548] <process did exit: exitCode=0, signal=null> +215ms
  pw:browser [pid=32548] starting temporary directories cleanup +0ms
  pw:browser [pid=32548] finished temporary directories cleanup +17ms
  pw:browser [pid=32548] <gracefully close end> +0ms
  1 passed (4.3s)

```

"visit baidu":
```
Running 1 test using 1 worker
[Microsoft] › baidu.spec.ts:3:6 › example
  pw:browser <launching> C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --no-sandbox --user-data-dir=C:\Users\yueji\AppData\Local\Temp\playwright_chromiumdev_profile-kUjLpa --remote-debugging-pipe --no-startup-window +0ms
  pw:browser <launched> pid=12760 +11ms                                                                                                                                                                            
  pw:browser [pid=12760][err] [12760:31008:1017/181140.355:ERROR:policy_logger.cc(154)] :components\enterprise\browser\controller\chrome_browser_cloud_management_controller.cc(163) Cloud management controller initialization aborted as CBCM is not enabled. +120ms
  pw:browser [pid=12760][err] [12760:31008:1017/181140.377:ERROR:assistance_home_client.cc(32)] File path C:\Users\yueji\AppData\Local\Temp\playwright_chromiumdev_profile-kUjLpa\Default +21ms                    
  pw:browser [pid=12760] <gracefully close start> +2s
  pw:browser [pid=12760] <process did exit: exitCode=0, signal=null> +6s
  pw:browser [pid=12760] starting temporary directories cleanup +0ms                                                                                                                                               
  pw:browser [pid=12760] exception while removing C:\Users\yueji\AppData\Local\Temp\playwright_chromiumdev_profile-kUjLpa: Error: EPERM: operation not permitted, unlink 'C:\Users\yueji\AppData\Local\Temp\playwright_chromiumdev_profile-kUjLpa\CrashpadMetrics-active.pma' +8ms
  pw:browser [pid=12760] finished temporary directories cleanup +0ms                                                                                                                                               
  pw:browser [pid=12760] <gracefully close end> +0ms                                                                                                                                                               
  1 passed (9.0s)
```

**Comment by kingyue737** [comment] 2023-10-19 08:49
I've tried Chromium which is much faster with 0 teardown time. Thanks. But I don't think my organization uses enterprise policies. How do I check it? And why the teardown duration varies from test to test. Some of my tests finish immediately while some others need 10s to teardown.

**Comment by mxschmitt** [comment] 2023-10-19 09:16
You can check by opening Microsoft Edge manually and navigating to `edge://policy/`. 

I was not able to reproduce the long close issue, for me it closed in ~0s.

> And why the teardown duration varies from test to test.

Here we can only speculate, probably something takes sometimes more time.

**Comment by yury-s** [comment] 2023-10-28 01:25
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Closed by yury-s** 2023-10-28 01:25 UTC
Labels: triaging
