### ISSUE TITLE
[Bug]: Fixture with scope: 'worker' is triggered twice without beforeAll in test and once with

### ISSUE THREAD

**Issue by udarrr** [microsoft/playwright#32682] opened 2024-09-18 12:32 UTC
### Version

1.47.1

### Steps to reproduce

```
import {test as base, Browser} from '@playwright/test';
 
const test = base.extend<{pageHelper: Browser}, {beforeAllWorker: Browser}>({
    beforeAllWorker: [
        async ({}, use) => {
            throw new Error('error from beforeAllWorker');
            await use({} as any);
        },
        {scope: 'worker', auto: true},
    ],
});
 
test.afterEach(async () => {
    console.log('afterEach');
});

test('test1 @test', async () => {
    console.log('test1');
});
 
test('test2 @test', async () => {
    console.log('test2');
});
```

### Expected behavior

beforeAllWorker - will be triggered once
test suite - will be failed

### Actual behavior

beforeAllWorker executed twice along with afterEach in next order

beforeAllWorker -> afterEach (test1)
beforeAllWorker -> afterEach (test2)

### Additional context

When to the example above add simple beforeAll
test.beforeAll(async () => {
    console.log('beforeAll');
});
behavior will be changed to
beforeAllWorker - will be executed once and then whole suite is failed as expected

```
import {test as base, Browser} from '@playwright/test';
 
const test = base.extend<{pageHelper: Browser}, {beforeAllWorker: Browser}>({
    beforeAllWorker: [
        async ({}, use) => {
            throw new Error('error from beforeAllWorker');
            await use({} as any);
        },
        {scope: 'worker', auto: true},
    ],
});

test.beforeAll(async () => {
    console.log('beforeAll');
});
 
test.afterEach(async () => {
    console.log('afterEach');
});

test('test1 @test', async () => {
    console.log('test1');
});
 
test('test2 @test', async () => {
    console.log('test2');
});
```

### Environment

```shell
playwright 1.47.1
```

**Comment by mxschmitt** [comment] 2024-09-18 13:09
When using Playwright, we give you a new Worker if a test is failing, see [here](https://playwright.dev/docs/test-parallel#worker-processes). Each worker will run a worker fixture once, this is why it runs twice in your case, because you have two failing tests.

**Comment by udarrr** [comment] 2024-09-18 18:28
i wonder why then after adding simple beforeAll hook behavior is changed to 'serial'-like

**Comment by mxschmitt** [comment] 2024-09-19 14:40
Note: After running the code above with `--workers=1` I also experience the behaviour change.

**Comment by mxschmitt** [comment] 2024-09-19 15:08
After speaking to the team this seems to work as expected.
We have a logic in place which won't run tests in the file if an error is happening inside `beforeAll`. This is because when something happens in `beforeAll`, it most likely is something fatal which would fail again. When you put an empty `beforeAll` there, it triggers the `worker` fixtures and causes this logic to trigger.

Closing as working as intended.

**Closed by mxschmitt** 2024-09-19 15:08 UTC
Labels: v1.48
