### ISSUE TITLE
[BUG] Tests are failing on hover() step in Linux Firefox and Safari

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#27969] opened 2023-11-04 00:10 UTC
### System info
- Playwright Version: 1.39.0
- Operating System: Ubuntu 20
- Browser: Firefox
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
   {
      name: "Desktop Firefox",
      use: {
        ...devices["Desktop Firefox"],
      },
    },
    {
        name: "Desktop Safari",
        use: {
           ...devices["Desktop Safari"],
       },
    },
  ]
});
```

**Test file (self-contained)**

```js
it('hover should show ... dot icon', async ({ page }) => {
    await this.page.getByTestId("card-1").hover();
    await this.page.getByTestId("card-1").getByTestId("more-options").click();
});
```

**Steps**
- Run the test on Linux locally with --repeat-each=20 or in a docker container using `npx playwright test`

**Expected**

The test should pass always

**Actual**

The test is failing on hover() step.

Notes: The test involves hovering on a card which should show `...` icon and clicking the `...` shows a context menu. The test fails because the `...` dot is not shown on hover. 

So far, this is reproducible with Firefox and Safari on docker `FROM mcr.microsoft.com/playwright:v1.39.0-focal` and running tests locally on linux. (PW version 1.39)

Test pass on mac os locally.

Manually if we navigate to the webpage we see the `...` icon all the time on linux and mac.

I can share the reproducible test / trace file private to help debug (since it involves login details).

**Comment by Nav-2d** [comment] 2023-11-08 18:31
Sorry to bother again. Is there a place I can send the test file/trace file to replicate the issue?

**Comment by dgozman** [comment] 2023-11-09 20:48
@Nav-2d Thank you for the issue! I've added a test for this scenario, and it seems to work reliably on Chromium/WebKit so far, but fails on Firefox.

I guess we'll need a repro after all. Unfortunately, we receive a lot of issues now, and do not have bandwidth to run non-public reproductions. If you could come up with a self-contained repro, that would be great!

**Comment by Nav-2d** [comment] 2023-11-09 20:56
@dgozman - thanks for looking into it. So, just to confirm again you are able to reproduce the issues with firefox right? Do you still need the repro steps? (since you already got it failing?)

**Comment by dgozman** [comment] 2023-11-09 22:10
@Nav-2d There is an issue with Firefox when running multiple browsers at the same time. I am not sure whether that's the same issue that you have or a different one. If you can make a simple repro, we can double check that and act accordingly. Otherwise, we can only hope that it's the same thing 😄

**Comment by mxschmitt** [comment] 2023-11-16 19:29
Closing as per above. Feel free to re-file if you have a smaller repro.

**Closed by mxschmitt** 2023-11-16 19:29 UTC
Labels: triaging

**Comment by msdoege** [comment] 2025-08-26 12:26
Not sure if this applies to this specific issue but I found this thread because of a similar issue with `hover()` in Firefox.
In my case, the problem was solved by **first focusing the element** I wanted to hover over.
```ts
await myLocator.focus();
await myLocator.hover();
```
