### ISSUE TITLE
[BUG] No Diff file if image size is different

### ISSUE THREAD

**Issue by atlowl** [microsoft/playwright#18005] opened 2022-10-11 21:03 UTC
**Context:**
- Playwright Version: v1.27.0
- Operating System: Linux
- Node.js version: 16.17.1
- Browser: Chromium

**Code Snippet**
My basic test.

```javascript
const {chromium, webkit, firefox} = require('playwright');
// my config is in a different file, but this line is relevant. 
const config = { use: { viewPort: { width: 1280, height: 4462 }};

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
  await expect(page).toHaveScreenshot({
     maxDiffPixelRatio: 0.03,
     fullPage: true,
     animations: "disabled",
  });
})();
```

**Describe the bug**

Occasionally my tests seem to fail where the height of the page is incorrect, however, playwright does not generate a diff file, i think because the compared and expected images are the wrong height. I get the following output

```
    Error: Screenshot comparison failed:

      Expected an image 1280px by 6061px, received 1280px by 6068px. 

    Call log:
      - expect.toHaveScreenshot with timeout 5000ms
      -   verifying given screenshot expectation
      - taking page screenshot
      -   disabled all CSS animations
      - Expected an image 1280px by 6061px, received 1280px by 6068px. 
      - waiting 100ms before taking screenshot
      - taking page screenshot
      -   disabled all CSS animations
      - captured a stable screenshot
      - Expected an image 1280px by 6061px, received 1280px by 6068px.

```

But no diff file.

**Comment by jfgreffier** [comment] 2022-10-13 08:09
pixelmatch can't compare images of different size, and anyway I don't think it really makes sense for Playwright. So it's probably best to fail in this way AND display the diff, even it may not be meaningful.

If the images are different size, it might look like these examples

![image](https://user-images.githubusercontent.com/12395973/195538048-fbd6b1ae-5d36-4673-af14-2a654e89286d.png)
**Cropped at the bottom**

---

![image](https://user-images.githubusercontent.com/12395973/195538092-e6457cac-63bd-487a-ae1c-9f6ccd0eb6be.png)
**Cropped at the top**


See the report made with rapid prototyping [playwright-report.zip](https://github.com/microsoft/playwright/files/9772289/playwright-report.zip)
What do you think ?

**Comment by jameskip** [comment] 2022-10-13 16:07
I think the exclusion of a diff file is [intentional](https://github.com/jameskip/playwright/blob/a60073d6640d826c1f37d09e4eb70e93177b16b3/tests/playwright-test/to-have-screenshot.spec.ts#L942). I'm not aware of a scenario where if the dimensions of the window are incorrect a diff would be useful.

**Comment by jfgreffier** [comment] 2022-10-13 16:14
It is totally intentional, so maybe this should be changed as a feature request. Or closed.

The thing is, some users might find it useful to see the actual and expected images anyway. And maybe also the diff image ?

**Comment by jfgreffier** [comment] 2022-10-13 16:23
@atlowl How about having the same error with the `Actual` and `Expected` tabs in HTML report ?

![image](https://user-images.githubusercontent.com/12395973/195651972-7457805d-6cac-4ce3-a31f-4abb7c9e2e27.png)

**Comment by atlowl** [comment] 2022-10-16 19:35
@jfgreffier, yep - i do actually like that. 
I see your point about being intentional not to provide a diff file when they are different sizes. I used a fixed view port to try and get around that issue.
Guess i can close this as being worked on?

**Comment by jfgreffier** [comment] 2022-10-17 07:05
Yes, feel free to close it since you have a workaround. In addition, this is not a bug as it works as intended.

**Comment by pavelfeldman** [comment] 2023-06-30 19:57
Should be fixed.

**Closed by pavelfeldman** 2023-06-30 19:57 UTC
Labels: P3-collecting-feedback, good first issue
