### ISSUE TITLE
File chooser API not working with electron

### ISSUE THREAD

**Issue by ptc-aramachandra** [microsoft/playwright#14569] opened 2022-06-02 04:28 UTC
Using the following https://playwright.dev/docs/api/class-filechooser to achieve handling of file chooser.

scenario: I have a browse button which will open a file chooser and i have to select a directory here. 

As mentioned in the above API, I used `this.page.waitForEvent('filechooser'),` and it fails for me with a timeout saying not able to find the event `page.waitForEvent: Timeout 30000ms exceeded while waiting for event "filechooser"`

Any idea why this is not working ?

**Comment by aslushnikov** [comment] 2022-06-02 08:19
Looks like a dupe of #8278

**Closed by aslushnikov** 2022-06-02 08:19 UTC

**Comment by ptc-aramachandra** [comment] 2022-06-02 14:48
Is there a solution for this ? Or is this a feature to include in the future ?

**Comment by aslushnikov** [comment] 2022-06-03 11:06
I don't think there's a solution; feel free to upvote the #8278 to get notified on the updates there!
