### ISSUE TITLE
[BUG] In debug mode chromium launch with messy colors

### ISSUE THREAD

**Issue by WaliAblikim** [microsoft/playwright#9122] opened 2021-09-24 05:42 UTC
**Context:**
- Playwright Version: [1.14.1]
- Operating System: [Linux]
- Node.js version: [14.17.6]
- Browser: [Chromium -907428]

    

**Describe the bug**
In this morning everything is works well , problem happened after upgrade   

I was using chromium-888113, playwright 1.12.3, today just  upgrade my browser to 907428 ,playwright to 1.14.1 and cause this problem .
![image](https://user-images.githubusercontent.com/78089343/134624033-e7beb7c1-a6d0-45bd-b6c9-de0ca4f617b5.png)

**Comment by mxschmitt** [comment] 2021-09-24 15:20
Could you try to upgrade to Playwright 1.15? This looks like an upstream Chromium bug or temporary system failure on your OS side. 

If this does also not help, try `npm i playwright@next`

**Comment by WaliAblikim** [comment] 2021-09-28 02:05
Sorry for late response,  @mxschmitt 
I have upgrade to 1.15.0
but problem not solved 
also tried npm i playwright@next   

waiting for your reply, thanks

**Comment by aslushnikov** [comment] 2021-09-28 15:29
@WaliAblikim does the same happen with the stoke Chrome? Can you please try installing Google Chrome Beta of Dev channels from [here](https://www.chromium.org/getting-involved/dev-channel) and see if the colors are still bad?

**Comment by WaliAblikim** [comment] 2021-09-30 01:54
@aslushnikov  thanks for your suggestion
I have tried on chromium  Beta version 95.0.4638.17 colors are still bad 
and one more information  in previous version  stable 93.0.4577.82  color are bad only when I run case,
 but this beta version  color are bad when I run case and launch chromium for simple searching 
 
![image](https://user-images.githubusercontent.com/78089343/135372813-d3786b73-2cc2-4914-ac15-0414b1a6f248.png)

**Comment by WaliAblikim** [comment] 2021-09-30 02:43
@aslushnikov    one more cases 
I tried Firefox with playwright 1.15.0
Firefox works with normal color, but playwright inspector color is bad

**Comment by thernstig** [comment] 2021-10-05 12:47
I can confirm this also happens with the same setup as WaliAblikim. Playwright Inspector also suffers from this (probably due to using Chromium).

**Comment by mxschmitt** [comment] 2021-10-05 12:50
Since this is also reproducible with the official Chrome builds, I'm closing this issue here. Please open an upstream issue at https://crbug.com/ so the Chromium folks can take a more detailed look. It's expected that Playwright Inspector suffers from it, since its also using Chromium under the hood.

**Closed by mxschmitt** 2021-10-05 12:50 UTC
Labels: triaging

**Comment by thernstig** [comment] 2021-10-05 13:48
> @aslushnikov thanks for your suggestion I have tried on chromium Beta version 95.0.4638.17 colors are still bad and one more information in previous version stable 93.0.4577.82 color are bad only when I run case, but this beta version color are bad when I run case and launch chromium for simple searching
> 

I am not sure I understood this part correctly. Are you saying you see this color distortion even if just launching Chromium, without using Playwright?

I tried to search for Chromium bugs related to this but could find none, but it might be that my search-fuu for Chromium bugs is not up to par.

**Comment by mxschmitt** [comment] 2021-10-05 13:50
Yeah since WaliAblikim wrote he is also able to reproduce it with Chrome Beta.

**Comment by thernstig** [comment] 2021-10-05 13:53
Ok, I was not entirely sure that is what he said from his text, but good to know that was the case 😃
