### ISSUE TITLE
[BUG] mouse move in Firefox not working

### ISSUE THREAD

**Issue by godjira-homless** [microsoft/playwright#9354] opened 2021-10-07 06:43 UTC
**Context:**
- Playwright Version: 1.15.1
- Operating System: Linux
- Node.js version: v14.17.0
- Browser: Firefox

```javascript
import { test } from '@playwright/test';

test("jqx mouse test", async ({ page })=>{
    Promise.all([
        await page.goto("http://shaker.umh.es/jqwidgets-v3.8.0/demos/jqxgrid/spreadsheet.htm"),
        await page.waitForLoadState("networkidle")
    ]);
    const sideBar = page.locator("#jqxScrollThumbverticalScrollBarjqxgrid");
    const pos = await sideBar.boundingBox();
    await page.mouse.move(pos.x, pos.y);
    await page.mouse.down({button: "left"});
    await page.mouse.move(pos.x, pos.y+150);
    await page.mouse.up({button: "left"});
});
```
**Describe the bug**

I have to move the sidebar down in a jqxgrid. The above code snippet works in chromium and webkit as well, but firefox do nothing.
The point is this different operation, not how many ways I can solve the down movement!

**Comment by HMaker** [comment] 2021-11-29 22:23
I can move mouse in playwright 1.15.3 but the speed is different, though the move code being the same, when switching from chrome to firefox. In firefox mouse move is very fast.

**Comment by godjira-homless** [comment] 2021-12-22 09:02
I found the solution. Under Firefox if I set the move position to center, than will work.

`import { test } from '@playwright/test';

test("jqx mouse test", async ({ page })=>{
    Promise.all([
        await page.goto("http://shaker.umh.es/jqwidgets-v3.8.0/demos/jqxgrid/spreadsheet.htm"),
        await page.waitForLoadState("networkidle")
    ]);
    const sideBar = page.locator("#jqxScrollThumbverticalScrollBarjqxgrid");
    const pos = await sideBar.boundingBox();
    await page.mouse.move(pos.x + pos.width / 2, pos.y + pos.height / 2);
    await page.mouse.down({button: "left"});
    await page.mouse.move(pos.x, pos.y+150);
    await page.mouse.up({button: "left"});
});`

**Comment by yury-s** [comment] 2021-12-22 20:46
Ok, the problem is the actual difference between the browsers in how they handle clicks on the elements that have rounded corners. In this case the scroller has `border-radius: 3px`:
![image](https://user-images.githubusercontent.com/9798949/147152520-0831b83b-f316-48af-9148-73d32f0f4fb5.png)

When you click at the top left corner of the bounding box, it is formally outside the border of the element. Looks like Firefox is more pedantic than the other browsers. If you remove border-radius style from the element the code above will work too:

```js
  const sideBar = page.locator("#jqxScrollThumbverticalScrollBarjqxgrid");
  await sideBar.evaluate(s => s.classList.remove('jqx-rc-all'));
  const pos = await sideBar.boundingBox();
```
So your solution of clicking at the middle is the most robust. Closing this bug as it is an actual difference between the browser implementations.

**Closed by yury-s** 2021-12-22 20:46 UTC
Labels: P2-bug, browser-firefox
