### ISSUE TITLE
[Question] storageState initialized by globalSetup in config not available in instances of Page Object Models?

### ISSUE THREAD

**Issue by jaredbash** [microsoft/playwright#19724] opened 2022-12-27 17:13 UTC
I am developing tests for a website that requires login for the whole page. This website uses Google Sign-In for authentication. All of the Google accounts used for authentication require two-factor authentication.

This means to test one part of the website, the test suite needs to sign in for each test three times - which eventually leads to problems with authentication requiring human interaction, or even requiring extra steps to authenticate.

To resolve this problem, I followed the [Reuse Signed-In State](https://playwright.dev/docs/auth#reuse-signed-in-state) part of the Playwright documentation so that sign in would happen once and then saved and shared among the tests.

This works fine for just normal tests. However, I also started using Page Object Models to describe my pages and allow for easier maintenance of the test suite. For some reason, in tests that create new instances of Page Object Model classes, the tests do not make use of the saved state and thus are not logged in.

How can this saved state be passed onto a POM instance in Playwright so that signed-in state can be reused? Perhaps I've missed something simple? 

Used a global-setup.ts file to declare login:

```
async function globalSetup(config: FullConfig) {
  const browser = await chromium.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto("http://localhost:8000/login");
  await page.getByRole("button", { name: "Connexion" }).click();
  await page.getByRole("button", { name: "Continue with Google" }).click();
  await page.getByRole("textbox", { name: "Adresse e-mail ou numéro de téléphone" }).fill(process.env.USERNAME);
  await page.getByRole("textbox", { name: "Adresse e-mail ou numéro de téléphone" }).press("Enter");
  await page.getByRole("textbox", { name: "Saisissez votre mot de passe" }).fill(process.env.PASSWORD);
  await page.locator("#passwordNext").click();
  await page.goto("http://localhost:8000");
  // Save signed-in state to 'storageState.json'.
  await page.context().storageState({ path: "storageState.json" });
  await browser.close();
}
```

I also added this to the playwright.config.ts file:

```
const config: PlaywrightTestConfig = {
  globalSetup: require.resolve('./global-setup'),
  use: {
    storageState: 'storageState.json'
  }
};

```
Here is an example of a test making use of the POM, which then doesn't use the state created in global setup. The login still happens, but then the new browser opened doesn't have the state and thus gets stuck on the login page:

```
test("apply a filter", async ({ page }) => {
  const dashboardHome = new DashboardHome(page);
  await new LoginPage(page).login();
  await dashboardHome.bookingLink.waitFor();
  await dashboardHome.bookingLink.click();
  const reservationsPage = new ReservationsPage(page);
  await reservationsPage.orderNumberFilter.waitFor();
  reservationsPage.filter({ orderID: "22222" });
  await expect(page).toHaveURL("http://localhost:8000/booking/22222");
});
```

**Comment by dgozman** [comment] 2022-12-28 17:31
@jaredbash Storage state should work with or without POMs. You code looks great, and I think everything should just work. Perhaps you could share your POM sources - maybe the issue is there?

**Comment by jaredbash** [comment] 2023-01-04 10:25
Sorry for the delay, holidays and all! Here's an example of a POM:
`
// playwright-dev-page.ts
import { expect, Locator, Page } from "@playwright/test";

import { BookingStatus } from "@/test/types";

export default class PageName {
  readonly page: Page;
  readonly bookButton: Locator;
  readonly loadingSpinner: Locator;

  readonly searchInput: Locator;
  readonly statusFilter: Locator;
  readonly statusOptions: Locator;
  readonly statusChips: Locator;

  readonly dateRangeFilter: Locator;
  readonly dateRangeFirstCalendar: Locator;
  readonly dateRangeSecondCalendar: Locator;

  constructor(page: Page) {
    this.page = page;

    this.bookButton = page.getByRole("button", { name: "Planifier une commande" });
    this.searchInput = page.getByPlaceholder("Rechercher...");
    this.loadingSpinner = page.locator(".ant-spin-dot");

    this.statusFilter = page.getByRole("combobox").first();
    this.statusOptions = page.getByRole("listbox").getByRole("option");
    this.statusChips = this.page
      .getByRole("row")
      .getByRole("cell")
      .filter({ has: this.page.locator("span") });

    this.dateRangeFilter = page.getByPlaceholder("Début");
    this.dateRangeFirstCalendar = page.locator(".ant-calendar-body").first();
    this.dateRangeSecondCalendar = page.locator(".ant-calendar-body").nth(1);
  }

  /**
   * Will go to create booking page by the button and check the URL
   */
  async goToCreateBooking() {
    await this.bookButton.click();
    await expect(this.page).toHaveURL(/.*orderthis/);
  }

  /**
   * Uses the general search text to perform a query.
   * @param query (string) Reservation number, internal reference, or address.
   */
  async search(query: string) {
    await this.searchInput.click();
    await this.searchInput.fill(query);
    await this.searchInput.press("Enter");
  }

  /**
   * Filters the bookings table by status and then verifies that all returned results
   * on the page match the status filter.
   * @param status (BookingStatus)
   */
  async filterByStatus(status: BookingStatus) {
    await this.loadingSpinner.waitFor({ state: "visible" });
    await this.loadingSpinner.waitFor({ state: "hidden" });
    await this.statusFilter.click();
    await this.statusOptions.filter({ hasText: statusOptionText[status] }).click();
    await this.loadingSpinner.waitFor({ state: "visible" });
    await this.loadingSpinner.waitFor({ state: "hidden" });
    await expect(this.statusFilter).toContainText(statusOptionText[status]);
    // eslint-disable-next-line no-restricted-syntax
    for (const chip of await this.statusChips.all()) {
      await expect(chip).toHaveText(statusOptionText[status]);
    }
  }

  async open() {
    await this.page.goto("http://localhost:8081/mes-commandes");
  }
}
`

**Comment by mxschmitt** [comment] 2023-01-04 16:26
The POM file also looks great, I think the best would be if you can share a full minimal repro with us to triage this further.

**Comment by mxschmitt** [comment] 2023-01-09 10:50
Closing for now since if it works with normal Playwright code but not with POMs, you most likely forget to click some buttons, fill wrong input into it or forget to wait for elements. I recommend to run your global Setup headed to see what it is doing, maybe enable tracing there and run your tests headed as well.

**Closed by mxschmitt** 2023-01-09 10:50 UTC
Labels: triaging

**Comment by GeGerardo** [comment] 2023-02-04 12:58
I am having the same issue as him. I double checked everything. What I noticed is: Using POM and storageState or beforeAll or even beforeEach, Playwright always open 2 different page instances and does not share the state. I never had that issue before because I was using POM but based on fixtures.

Ex:

With custom fixture (Works fine)
```ts
test.describe(() => {
    test.use({ storageState: `state/${loginState}.json` });

    test("For users:", async ({ ahvPage }) => {
        await ahvPage.navigateToLibrary();
        const modal = await ahvPage.addVessel();
        await expect(modal).toBeVisible();
        ...
```

```ts


The fixture I created using the same inheritance organization as the POM.

So something is not being shared when we use POM. Checking the storageState.json the cookies configuration is normal

**Comment by jaredbash** [comment] 2023-02-04 13:19
Sorry, I didn't have the bandwidth to share a minimal reproduction at the time due to exams. Plus the code I was working on is proprietary.

I'll try to get something together this week, but I really do believe it's a bug because the same code for login functioned otherwise when not used in globalSetup.

**Comment by GeGerardo** [comment] 2023-02-04 14:03
@jaredbash I think it would be better to open a new one as a bug and mention that ticket. I have a feeling that maybe it is a bug

**Comment by GeGerardo** [comment] 2023-02-05 14:08
@jaredbash I created a ticket. If you want to give your input this is the link: https://github.com/microsoft/playwright/issues/20638
