### ISSUE TITLE
[Feature] how to get file by  route  request Intercept  when form file upload

### ISSUE THREAD

**Issue by nappinglady** [microsoft/playwright#16579] opened 2022-08-16 14:26 UTC
how to get file by  route  request Intercept  when form file upload？
cant frind in  request method

**Comment by aslushnikov** [comment] 2022-08-16 16:08
@nappinglady I don't think I follow the question. What exactly do you want to do?

**Comment by nappinglady** [comment] 2022-08-16 16:08
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by nappinglady** [comment] 2022-08-17 01:31
> @nappinglady I don't think I follow the question. What exactly do you want to do?

for example  i have a upload file form
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,height=device-height">
    <title>test playwright intercept file</title>
    <style>::-webkit-scrollbar{display:none;}html,body{overflow:hidden;height:100%;margin:0;}</style>
</head>
<body>
  <form enctype="multipart/form-data" action="http://localhost:8004/Upload/Upload"  method="post">
    <input type="file" name="file"/>
    <input type="text" name="name"/>
    <input type="submit" value="上传"/>
  </form>
</body>
</html>
`
--------------------------------------
then i want to get file by intercept like this
`test.describe('lpp', async () => {
    await test('lpp',async ({ page }) => {
       await page.goto("file:///E:/study/antv/uploadfile.html");
       page.route(/.*localhost.*/g,async(route,request)=>{
            console.log(request)
            console.log(route)
            console.log(request.postData());     
            console.log(await request.headersArray());     
            console.log(request.postDataBuffer());     
           await route.continue();
           console.log(await (await request.response())?.json());
       })
       await page.waitForTimeout(100000);
    });
});
`

-------------------------------
i cant get file by request or  route

**Comment by nappinglady** [comment] 2022-08-17 01:44
> @nappinglady I don't think I follow the question. What exactly do you want to do?
@aslushnikov   or   how to get file and redirect my new request url ,   and  New URL has different protocol with original 
https://playwright.dev/docs/next/api/class-route#route-continue

**Comment by aslushnikov** [comment] 2022-08-17 15:30
Ah! This is a dupe of https://github.com/microsoft/playwright/issues/6479

Merging this one; please upvote #6479 to receive updates!

**Closed by aslushnikov** 2022-08-17 15:30 UTC
Labels: triaging
