### ISSUE TITLE
[Bug]: wait_for_function method raise error

### ISSUE THREAD

**Issue by cjydayang** [microsoft/playwright#11013] opened 2021-12-18 07:53 UTC
### Playwright version

1.17.2

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

Follow the examples in the documentation：[page.wait_for_function](https://playwright.dev/python/docs/api/class-page#page-wait-for-function)

my test script throw an error

### Code snippet to reproduce your bug

```shell
from playwright.sync_api import sync_playwright
import time

def run(playwright):
    chromium = playwright.chromium
    browser = chromium.launch(headless=False)
    page = browser.new_page(ignore_https_errors=True)
    url = "https://****"
    page.goto(url + "/login")
    page.fill("input[name=\"username\"]", 'admin')
    page.fill("input[name=\"password\"]", 'abcdefg')
    page.click("#loginBtn")
    with page.expect_response("*/api/user/column/acclist*") as response_info:
        page.goto(url + "/#/users/list;page=0")
    page.locator('"Add User"').first.click()
    page.locator('"Next"').first.click()
    page.locator('span[title="native"]').click()
    page.locator('span[title="native-radius"]').click()
    page.evaluate("window.x = 0; setTimeout(() => { window.x = 100 }, 5000);")
    page.wait_for_function("() => window.x > 0")
    time.sleep(5)
    browser.close()

with sync_playwright() as playwright:
    run(playwright)
```

### Relevant log output

```shell
C:\dev\AutomationTestBase\PlaywrightAutomation\venv\Scripts\python.exe C:/dev/AutomationTestBase/PlaywrightAutomation/demo.py
Traceback (most recent call last):
  File "C:/dev/AutomationTestBase/PlaywrightAutomation/demo.py", line 34, in <module>
    run(playwright)
  File "C:/dev/AutomationTestBase/PlaywrightAutomation/demo.py", line 29, in run
    page.wait_for_function("window.scrollY === 0")
  File "C:\dev\AutomationTestBase\PlaywrightAutomation\venv\lib\site-packages\playwright\sync_api\_generated.py", line 9078, in wait_for_function
    polling=polling,
  File "C:\dev\AutomationTestBase\PlaywrightAutomation\venv\lib\site-packages\playwright\_impl\_sync_base.py", line 111, in _sync
    return task.result()
  File "C:\dev\AutomationTestBase\PlaywrightAutomation\venv\lib\site-packages\playwright\_impl\_page.py", line 814, in wait_for_function
    return await self._main_frame.wait_for_function(**locals_to_params(locals()))
  File "C:\dev\AutomationTestBase\PlaywrightAutomation\venv\lib\site-packages\playwright\_impl\_frame.py", line 660, in wait_for_function
    return from_channel(await self._channel.send("waitForFunction", params))
  File "C:\dev\AutomationTestBase\PlaywrightAutomation\venv\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\dev\AutomationTestBase\PlaywrightAutomation\venv\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: TypeError: t.finally is not a function
    at Object.run (<anonymous>:3:53281)
    at eval (eval at evaluate (:3:2389), <anonymous>:1:14)
    at t.default.evaluate (<anonymous>:3:2412)
    at t.default.<anonymous> (<anonymous>:1:44)

Process finished with exit code 1
```

**Comment by cjydayang** [comment] 2021-12-19 11:10
@mxschmitt Sorry this is a privatized web applications so i can't provide a URL. Would it help you analyze the problem if I upload the playwright trace file？

**Comment by cjydayang** [comment] 2021-12-20 02:04
[trace.zip](https://github.com/microsoft/playwright/files/7742144/trace.zip)
@mxschmitt This is the trace file

**Comment by yury-s** [comment] 2021-12-22 00:04
It's unclear from the trace why wait_for_function threw. Since the application can't be shared, could you provide a reduced repro that we can run? As Max mentioned most likely the problem is that some fishy library overrides intrinsic objects (like Promise) breaks our instrumentation.

**Comment by cjydayang** [comment] 2021-12-22 01:28
@yury-s Thank you for your reply
I know what you mean. I need some time to think about how to provide a repro

**Comment by aslushnikov** [comment] 2021-12-27 23:50
@cjydayang please feel free to file a new issue with a repro! I'll close this meanwhile.

**Closed by aslushnikov** 2021-12-27 23:50 UTC
Labels: triaging
