### ISSUE TITLE
[Question] how to implement comparing two screenshots (before and after) in one test

### ISSUE THREAD

**Issue by lukaMis** [microsoft/playwright#19388] opened 2022-12-09 20:33 UTC
Hi
I am very new to playwright and i have a problem.
I am trying to implement comparing two screenshots (before and after) in one test.
this is what i want to achieve:
1. navigate to webpage
2. take screenshot (before.png)
3. do some stuff, state changes, etc
4. take screenshot (after.png)
5. compare before.png to after.png (if they are the same test should pass, otherwise test fails)

something like this:
![image](https://user-images.githubusercontent.com/1482793/206791193-f5b5ff83-e033-4145-b268-e1d44ff86c9e.png)

but it does not work like this. :disappointed:
Any ideas/suggestions how can i achieve this?
Help would be greatly appreciated
tnx

**Comment by aslushnikov** [comment] 2022-12-09 23:15
This is a dupe of https://github.com/microsoft/playwright/issues/18937

**Closed by aslushnikov** 2022-12-09 23:15 UTC
