### ISSUE TITLE
[BUG] Sometimes the Flaky test does not show the step at which the test failed and does not show the steps to repeat the test

### ISSUE THREAD

**Issue by sqanatoliy** [microsoft/playwright#10673] opened 2021-12-02 15:30 UTC
Context:

Playwright Version: [1.17.0-rc1]
Operating System: [Windows 11]
Node.js version: [v14.17.5]
Browser: [ All]
Extra: [the same problems I get using Gitlab CI]

https://user-images.githubusercontent.com/22426754/144452223-1f92656f-2ff7-4c04-8059-4e47c50dc7fa.mp4

Sometimes the Flaky test does not show the step at which the test failed and does not show the steps to repeat the test

**Comment by pavelfeldman** [comment] 2021-12-02 17:15
Same story here, it looks like reporter failed, could you paste errors from DevTools here?

**Comment by dgozman** [comment] 2021-12-08 19:27
Closing since we cannot reproduce the issue. Please file a new issue with a repro if you have one.

**Closed by dgozman** 2021-12-08 19:27 UTC
Labels: triaging
