### ISSUE TITLE
[Docs]: how to record a new test using `webkit`

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/playwright#31575] opened 2024-07-05 23:29 UTC
### Page(s)

https://playwright.dev/docs/codegen#record-using-custom-setup

### Description

I have a test that runs just fine using Firefox, but not with `webkit`.

I thought I might be able to rewrite the test in a way that succeeds on `webkit` if I could record a test using it, as opposed to, say, `chromium`.

**Comment by hamirmahal** [comment] 2024-07-05 23:32
I tried using

```ts
import { webkit } from "@playwright/test";

(async () => {
  // Make sure to run headed.
  const browser = await webkit.launch({ headless: false });

  // Setup context however you like.
  const context = await browser.newContext({
    /* pass any options */
  });
  await context.route("**/*", (route) => route.continue());

  // Pause the page, and start recording manually.
  const page = await context.newPage();
  await page.pause();
  await page.goto('http://localhost:3000/authenticate');
})().catch(console.error);
```

to record a custom test using `webkit`, but that failed.

**Comment by chimurai** [comment] 2024-07-06 10:45
Did you install webkit? With the following command:

```shell
# download browser binaries and their dependencies:
npx playwright install --with-deps
```

https://playwright.dev/docs/intro#updating-playwright
https://playwright.dev/docs/ci#introduction

**Comment by mxschmitt** [comment] 2024-07-07 15:43
> I have a test that runs just fine using Firefox, but not with webkit.

This could be a Playwright bug or a bug in your site. Would it be possible to share a reproduction so we can look into it further?

You can start WebKit codegen via `npx playwright codegen --browser webkit`

**Comment by hamirmahal** [comment] 2024-07-09 06:14
> > I have a test that runs just fine using Firefox, but not with webkit.
> 
> This could be a Playwright bug or a bug in your site. Would it be possible to share a reproduction so we can look into it further?

I think this is related to using VSCode snap, like you mentioned in https://github.com/microsoft/playwright/issues/31558#issuecomment-2210497800.

When I do `npx playwright test` in a non-VSCode terminal, all tests pass.

```
$  npx playwright test 

Running 6 tests using 4 workers
…spec.ts:3:12 › the page redirects to http://localhost:3000/test/reporting/packages after logging in
…spec.ts:3:12 › the page redirects to http://localhost:3000/test/reporting/packages after logging in
…spec.ts:3:12 › the page redirects to http://localhost:3000/test/reporting/packages after logging in
…spec.ts:3:12 › the page redirects to http://localhost:3000/test/reporting/packages after logging in
…spec.ts:3:12 › the page redirects to http://localhost:3000/test/reporting/packages after logging in
…spec.ts:3:12 › the page redirects to http://localhost:3000/test/reporting/packages after logging in
  Slow test file: [firefox] › authentication.spec.ts (21.1s)
  Slow test file: [webkit] › authentication.spec.ts (20.1s)
  Consider splitting slow test files to speed up parallel execution
  6 passed (27.0s)
```

But if I do `npx playwright test` in a VSCode integrated terminal, the `webkit` test fails, maybe because I installed VSCode through `snap`. That isn't clear to the end-user, though.

```
$  npx playwright test

Running 6 tests using 4 workers
[Mobile Chrome] › authentication.spec.ts:3:12 › the page redirects to http://localhost:3000/test/reporting/packages after logging in
[chromium] › authentication.spec.ts:3:12 › the page redirects to http://localhost:3000/test/reporting/packages after logging in
[firefox] › authentication.spec.ts:3:12 › the page redirects to http://localhost:3000/test/reporting/packages after logging in
[Microsoft Edge] › authentication.spec.ts:3:12 › the page redirects to http://localhost:3000/test/reporting/packages after logging in
[Google Chrome] › authentication.spec.ts:3:12 › the page redirects to http://localhost:3000/test/reporting/packages after logging in
  1) [webkit] › authentication.spec.ts:3:12 › the page redirects to http://localhost:3000/test/reporting/packages after logging in 

    Test timeout of 30000ms exceeded.

    Error: locator.click: Test timeout of 30000ms exceeded.
    Call log:
      - waiting for getByLabel('Email or phone')


       6 |     await page.goto("http://localhost:3000/authenticate");
       7 |     await page.getByRole("button", { name: "Continue with Google" }).click();
    >  8 |     await page.getByLabel("Email or phone").click();
         |                                             ^
       9 |     await page
      10 |       .getByLabel("Email or phone")

    attachment #1: trace (application/zip) ─────────────────────────────────────────────────────────
    test-results/authentication-the-page-re-32050-g-packages-after-logging-in-webkit/trace.zip
    Usage:

        npx playwright show-trace test-results/authentication-the-page-re-32050-g-packages-after-logging-in-webkit/trace.zip

    ────────────────────────────────────────────────────────────────────────────────────────────────

  Slow test file: [webkit] › authentication.spec.ts (30.0s)
  Slow test file: [firefox] › authentication.spec.ts (18.5s)
  Slow test file: [chromium] › authentication.spec.ts (15.5s)
  Consider splitting slow test files to speed up parallel execution
  1 failed
    [webkit] › authentication.spec.ts:3:12 › the page redirects to http://localhost:3000/test/reporting/packages after logging in 
  5 passed (31.2s)
```

**Comment by hamirmahal** [comment] 2024-07-09 06:17
> You can start WebKit codegen via `npx playwright codegen --browser webkit`

The `webkit` test seems to work fine in a standard, non-VSCode OS terminal.

In a VSCode integrated terminal, running this command resulted in this error.

```
$  npx playwright codegen --browser webkit
Error: t.parse: Target page, context or browser has been closed
Browser logs:

<launching> /home/hamir/.cache/ms-playwright/webkit-2035/pw_run.sh --inspector-pipe --no-startup-window
<launched> pid=171249
[pid=171249][err] /home/hamir/.cache/ms-playwright/webkit-2035/minibrowser-gtk/bin/MiniBrowser: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
Call log:
  - <launching> /home/hamir/.cache/ms-playwright/webkit-2035/pw_run.sh --inspector-pipe --no-startup-window
  - <launched> pid=171249
  - [pid=171249][err] /home/hamir/.cache/ms-playwright/webkit-2035/minibrowser-gtk/bin/MiniBrowser: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
```

**Comment by mxschmitt** [comment] 2024-07-09 07:16
Yeah this is a duplicate of https://github.com/microsoft/playwright/issues/31558. I'll discuss it with the team, but I think we should file it against VSCode, since their Terminal gets invoked with the wrong PATH/LD_PRELOAD.

**Comment by mxschmitt** [comment] 2024-07-09 07:24
Looks like https://github.com/microsoft/vscode/issues/179274 which they folded into https://github.com/microsoft/vscode/issues/179086. I recommend to reach out to them if needed.

**Closed by mxschmitt** 2024-07-09 07:24 UTC
