### ISSUE TITLE
[BUG] default timeout doesn't work when inspector is open

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#10312] opened 2021-11-15 02:33 UTC
**Context:**
- Playwright Version: 1.16.1
- Operating System: windows 10
- Node.js version: 16.9.1
- Browser: chromium
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage()
  await page.goto('https://google.com/')
  await page.click('asdfsdfasdf')
})();
```

**Describe the bug**

when the inspector is open, it just hangs forever waiting for the element instead of hitting the default timeout (which should be 30s)

however it works when you specify a custom timeout in `page.click` or `page.setDefaultTimeout`

**Comment by JoelEinbinder** [comment] 2021-11-19 19:32
You are talking about the playwright inspector? This the intended behavior so you can see whats going on instead of closing the page.

**Closed** 2021-11-19 19:33 UTC

**Comment by DetachHead** [comment] 2021-11-20 02:32
@JoelEinbinder in that case how come it doesn't behave like this when you've changed the timeout?

**Comment by DetachHead** [comment] 2021-11-20 02:36
I think it should at least throw an error when the timeout is reached. But then keep the inspector and the browser open so you can investigate

**Comment by DetachHead** [comment] 2022-07-01 06:11
@JoelEinbinder this behavior is still extremely annoying. when debugging tests i often go afk while they're running and when i come back to it hanging like this and an expired session on the site i'm testing i have no way to see what happened.

at the very least can there be a button to trigger the timeout so the test at least fails and i can get the trace file?
