### ISSUE TITLE
[BUG] Changing type to module in package.json results in test error

### ISSUE THREAD

**Issue by subhero24** [microsoft/playwright#28732] opened 2023-12-20 05:17 UTC
I have set up a project following the guide in the docs "Components (experimental): How to get started" (choosing plain javascript and react 18). 

Everything works fine, but when I change my package.json to use ES modules, by adding "type":"module", and changing the `playwright-ct.config.js` to an ESModule, my test errors with 

```
Object mount notation is not supported
```

Any idea how to get the tests running in a "module" project?

### System info
- Playwright Version: [1.40.1]
- Operating System: [macOS 14.1.2]

**Comment by yury-s** [comment] 2023-12-20 20:34
I was not able to reproduce it following your steps. If you believe this is not working due to a bug in Playwright please share a minimal repro that we could run locally to see the problem.

**Comment by subhero24** [comment] 2023-12-20 20:43
You can find the minimal repro here: https://github.com/subhero24/playwright-issue28732

running `npm run test-ct` to start the tests and get the error

**Comment by yury-s** [comment] 2023-12-21 00:46
Hmm, I just ran it without any issues:

<img width="707" alt="image" src="https://github.com/microsoft/playwright/assets/9798949/6936f445-1ab9-4a01-8d4b-c5385905af66">

Maybe some caches got messed up, try `rm -rf playwright/.cache` and run the tests again? Does it reproduce on a fresh checkout for you?

**Comment by mxschmitt** [comment] 2023-12-21 08:37
Which Node.js version are you using? Make sure to use a recent one like 18+.

**Comment by subhero24** [comment] 2023-12-21 09:01
@yury-s It still occurs on a fresh checkout of that repo

@mxschmitt My node version is v21.3.0

**Comment by mxschmitt** [comment] 2023-12-21 09:16
I believe this is https://github.com/microsoft/playwright/issues/28524 related, could you try Node.js 20?

**Comment by subhero24** [comment] 2023-12-21 14:36
That's it! It works under Node v20, and doesn't under Node v21

**Comment by yury-s** [comment] 2023-12-21 17:29
This should be fixed by https://github.com/microsoft/playwright/pull/28526 which we decided not to land for now as it is associated with a high risk of breaking someone. Please use Node LTS for now to overcome this, we'll fix it by the time Node.js 22 LTS is out.

**Closed** 2023-12-22 00:57 UTC
Labels: v1.42
