### ISSUE TITLE
[BUG] Codegen crashes 1 minute into recording and debugging tests also

### ISSUE THREAD

**Issue by momothefirst** [microsoft/playwright#12982] opened 2022-03-23 12:31 UTC
Context:

**System:**
2020 Macbook 13"
OS: macOS Monterey 12.0.1
Memory: 12.2 GB / 16 GB LPDDR4X
CPU: 2 GHz Intel Core i5 Quad-core

**Binaries:**
Node: 14.17.5
npm: 6.14.14

**npmPackages:**
playwright: ^1.20.0 => 1.20.0

**Describe the bug**

Running "npx playwright codegen google.com" and doing no further actions will stay up for around 1 minute each time and then crash the debugger and the test browser window, I've done about 5 consecutive tests with a timer to check this. I've asked colleagues (they have a basically same specced mac) to do the same with the same results. I've noticed this issue while doing some initial setup on our locally ran application, but to debug the issue further I tested this on google.com and the behavior is the same.

Also noticed after checking other issue previously reported that using debug mode on the tests also crashes after 1 minute.

All of this on chromium.

**Comment by mxschmitt** [comment] 2022-03-23 13:52
This looks like a duplicate of https://github.com/microsoft/playwright/issues/12974. Could you try `npm i -D @playwright/test@next` (or just `playwright` depends on your setup)?

**Comment by alimtunc** [comment] 2022-03-23 13:59
> This looks like a duplicate of #12974. Could you try `npm i -D @playwright/test@next` (or just `playwright` depends on your setup)?

I had the same issue and running `npm i -D @playwright/test@next` worked for me, looks like 1.20.0 making it crash.. 
Thank's for your help 💯

**Comment by mxschmitt** [comment] 2022-03-23 13:59
Folding into https://github.com/microsoft/playwright/issues/12974

**Closed by mxschmitt** 2022-03-23 13:59 UTC
Labels: triaging

**Comment by momothefirst** [comment] 2022-03-23 14:41
Can confirm updating to `@playwright/test@next` worked! Thanks for the quick reply 😊
