### ISSUE TITLE
[Bug]: Cannot run Playwright UI

### ISSUE THREAD

**Issue by sholtby-yilu** [microsoft/playwright#32182] opened 2024-08-15 14:55 UTC
### Version

1.46

### Steps to reproduce

1. Create the playwright test example via `yarn create playwright`
2. Attempt to run `yarn playwright test --ui`

### Expected behavior

Playwright UI should appear

### Actual behavior

The terminal error `ProtocolError: Protocol error (Page.navigate): Cannot navigate to invalid URL` is retuned. 

### Additional context

This error is happening on existing projects as well. I assume it's something to do with Chromium but unsure what. **Running Playwright without UI works as expected.**

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.95 GB / 32.00 GB
  Binaries:
    Node: 18.0.0 - ~/.nvm/versions/node/v18.0.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.6.0 - ~/.nvm/versions/node/v18.0.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.46.0 => 1.46.0
```

**Comment by pavelfeldman** [comment] 2024-08-15 15:36
Works for me, also on the same 14.6.1.

**Comment by Skn0tt** [comment] 2024-08-19 08:51
We can't reproduce, closing. If you find a way of making this reproducible, please file another issue.

**Closed by Skn0tt** 2024-08-19 08:51 UTC

**Comment by i5id0r4** [comment] 2024-11-05 10:20
@sholtby-yilu did you ever figure this out? I have the same issue. 2021 M1 Macbook Pro, OS 14.5

**Comment by sholtby-yilu** [comment] 2024-11-05 11:53
> @sholtby-yilu did you ever figure this out? I have the same issue. 2021 M1 Macbook Pro, OS 14.5. Other people on my team are able to run the same code just fine.

I wasn't able to figure out the root cause of it. However, deleting the browsers that are cashed on your Mac and also reinstalling playwright sync to do the trick.

**Comment by i5id0r4** [comment] 2024-11-12 15:03
this didn't work for me.

**Comment by RERepos** [comment] 2025-01-01 04:06
I have the same issue. Following the instructions on the installation page (https://playwright.dev/docs/intro).

npm init playwright@latest
npx playwright test                        - works fine
npx playwright show-report          - works fine
npx playwright test --ui                 - does not work

Errors:
ProtocolError: Protocol error (Page.navigate): Cannot navigate to invalid URL
    at /home/rerozak/rozak_app_foundry/pls-playwright-fromScratch/node_modules/playwright-core/lib/server/chromium/crConnection.js:135:16
    at new Promise (<anonymous>)
    at CRSession.send (/home/rerozak/rozak_app_foundry/pls-playwright-fromScratch/node_modules/playwright-core/lib/server/chromium/crConnection.js:131:12)
    at FrameSession._navigate (/home/rerozak/rozak_app_foundry/pls-playwright-fromScratch/node_modules/playwright-core/lib/server/chromium/crPage.js:506:41)
    at CRPage.navigateFrame (/home/rerozak/rozak_app_foundry/pls-playwright-fromScratch/node_modules/playwright-core/lib/server/chromium/crPage.js:166:41)
    at Frame._gotoAction (/home/rerozak/rozak_app_foundry/pls-playwright-fromScratch/node_modules/playwright-core/lib/server/frames.js:540:55)
    at /home/rerozak/rozak_app_foundry/pls-playwright-fromScratch/node_modules/playwright-core/lib/server/frames.js:524:74
    at Frame.raceNavigationAction (/home/rerozak/rozak_app_foundry/pls-playwright-fromScratch/node_modules/playwright-core/lib/server/frames.js:496:95)
    at Frame._goto (/home/rerozak/rozak_app_foundry/pls-playwright-fromScratch/node_modules/playwright-core/lib/server/frames.js:524:17)
    at /home/rerozak/rozak_app_foundry/pls-playwright-fromScratch/node_modules/playwright-core/lib/server/frames.js:521:44 {
  type: 'error',
  method: 'Page.navigate',
  logs: undefined
}

My Info:
Windows 11, wsl2
Ubuntu-20.04
node v18
  "devDependencies": {
    "@playwright/test": "^1.49.1",
    "@types/node": "^22.10.2"
  }

I also tried:
- Another clean install using the JS instead of TS option.
- Restart computer.

Nothing works ... I'm stuck ...

**Comment by RERepos** [comment] 2025-01-01 16:42
I also just tried this on a brand new dell laptop. Only difference is using Ubuntu 22.04.5.  npx playwright test --ui still not working.
