### ISSUE TITLE
storageState not restored when running tests with "Show & reuse browser" set

### ISSUE THREAD

**Issue by jkells** [microsoft/playwright#16954] opened 2022-08-23 05:46 UTC
I have some authentication state stored in storageState.json.

I place `test.use({ storageState: "storageState.json" });` at either the top of my test file OR within a test.describe block to restore the state.

Running the test with Show and re-use browser ticked works fine the first run.

On subsequent runs the state isn't restored, cookies and local storage are empty.

**Comment by dgozman** [comment] 2022-08-31 18:40
@jkells I cannot reproduce this issue. I am running with extension v0.2.10 and playwright v1.25.1. Could you please share a repro?

----

Example that I am trying to reproduce with:

`example.spec.ts`
```ts
import { test, expect } from "@playwright/test";

test.use({ storageState: 'storage.json' });

test("failing test", async ({ page }) => {
  await page.goto('https://demo.playwright.dev/todomvc');
  expect(await page.evaluate('localStorage.foobar')).toBe('qux');
});
```


`storage.json`
```json
{
  "cookies": [],
  "origins": [
    {
      "origin": "https://demo.playwright.dev",
      "localStorage": [
        {
          "name": "foobar",
          "value": "qux"
        }
      ]
    }
  ]
}
```

**Comment by pavelfeldman** [comment] 2022-09-06 22:17
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Closed by pavelfeldman** 2022-09-06 22:17 UTC
Labels: P1-resolve-asap, v1.25
