### ISSUE TITLE
[BUG] Locator.click -> subtree intercepts pointer events since version 1.17.0

### ISSUE THREAD

**Issue by Kremliovskyi** [microsoft/playwright#10638] opened 2021-12-01 11:28 UTC
**Context:**
- Playwright Version: [1.17.0]
- Operating System: [Windows, Linux]
- Node.js version: [v16.13.0]
- Browser: [Chromium]

**Describe the bug**
![image](https://user-images.githubusercontent.com/12884831/144224672-dfce17dd-95f2-47d6-8dd0-815501749c2f.png)
I am clicking on this div with  data-test-id="Purpose" to open
![image](https://user-images.githubusercontent.com/12884831/144226121-3a1ac481-61be-4133-b203-d1798b64871f.png)
this dropdown
![image](https://user-images.githubusercontent.com/12884831/144226149-bf10cb35-a7d3-406d-9f8b-e357e32482eb.png)
![image](https://user-images.githubusercontent.com/12884831/144227561-f7d71236-e4e8-4e35-80db-639ed04d3498.png)

I am using Locator by data-test-id and pure click without any options.

Since playuwright version 1.17.0 I am receiving error <li tabindex="0" role="option" data-value="1" aria-s…>…</li> from <div id="menu-" role="presentation" class="MuiPopover…>…</div> subtree intercepts pointer events

![image](https://user-images.githubusercontent.com/12884831/144225887-1e772cfd-e2de-4e57-9927-073076cf184c.png)

Click succeeds, dropdown is opened but error saying that the dropdown intercepts pointer events appear. 

NOTE: Playwright 1.16.3 does not have such issue!

**Comment by dshaplyko** [comment] 2021-12-01 11:50
I'm having almost the same issue starting from version 1.17.0.
Previously I used 1.17.0-next-alpha-nov-5-2021 and everything was correct.

![Screenshot 2021-12-01 at 14 47 43](https://user-images.githubusercontent.com/4024495/144229389-04159b78-eb60-4a74-8d47-fe4dec5ba8c6.png)

**Comment by dgozman** [comment] 2021-12-01 15:06
@Kremliovskyi Could you please share a trace file with us? You can send it to dgozman [at] microsoft [dot] com if you'd like. Here are instructions to record a trace: https://playwright.dev/docs/trace-viewer#recording-a-trace.

**Comment by Kremliovskyi** [comment] 2021-12-01 16:40
@dgozman I have sent you an email with trace file.

**Comment by pavelfeldman** [comment] 2021-12-01 16:46
@Kremliovskyi could you confirm that running the test with the following environment variable `PLAYWRIGHT_NO_LAYOUT_SHIFT_CHECK=1` resolves the issue?

**Comment by pavelfeldman** [comment] 2021-12-01 17:06
We will bake 1.17.1 with this mode `off` right away.

**Comment by Kremliovskyi** [comment] 2021-12-01 17:22
Really appreciate your dedication and speed.

**Comment by dgozman** [comment] 2021-12-01 22:53
Thank you, this will be fixed in v1.17.1 by #10653.

**Closed by dgozman** 2021-12-01 22:53 UTC
Labels: P1-resolve-asap, v1.17

**Comment by AndyGBC** [comment] 2021-12-02 10:15
This also appears to have fixed our very similar issue, thanks :)

**Comment by dgozman** [comment] 2021-12-02 15:42
@AndyGBC If you could share a repro for the issue you had, that would be great! We'll be able to prevent similar breakages in the future.

**Comment by mariyaerokhina** [comment] 2022-02-17 16:36
I'm having the same issue on Playwright version 1.19.1
- Operating System: [Windows]
- Node.js version: [v14.17.6]
- Browser: [Chromium]

![Screenshot_323](https://user-images.githubusercontent.com/92377962/154523400-473ff5e5-1432-4f20-bcc6-6387db08e761.png)

I am clicking on this div with data-loc="icon-menu" (collapse option)
![Screenshot_324](https://user-images.githubusercontent.com/92377962/154524083-7310539f-06ea-49d9-b059-3f310fc0ef98.png)

I'm receiving error:
`<div class="styled__ActionIconButton-sc-1gymt07-0 cKg…>…</div> intercepts pointer events`

![Screenshot_325](https://user-images.githubusercontent.com/92377962/154524418-266172aa-7abf-4c52-b823-838279a126ee.png)

And the click doesn't work.
I've sent the trace to dgozman [at] microsoft [dot] com

**Comment by dgozman** [comment] 2022-02-19 04:24
@mariyaerokhina Thank you for the trace. Unfortunately, it was not enough to figure out the issue. Could you please run your test with `PLAYWRIGHT_NO_LAYOUT_SHIFT_CHECK=1` environment variable to see whether it fixes the problem?

**Comment by mariyaerokhina** [comment] 2022-02-22 10:35
@dgozman Thank you for the answer. I've tried - `PLAYWRIGHT_NO_LAYOUT_SHIFT_CHECK=1` environment variable hasn't fixed the problem.

**Comment by dgozman** [comment] 2022-02-22 20:33
@mariyaerokhina It does not matter where the env variable is set. Here is an easy example with the config:

```ts
// playwright.config.ts

process.env.PLAYWRIGHT_NO_LAYOUT_SHIFT_CHECK = '1';
const config = {
  // ...
};
export default config;
```

If this env variable does not help, that means the issue is a different one. If you could share a minimal repro, please file a new issue and we'll try to debug it.

**Comment by regnou** [comment] 2022-06-29 15:33
Hi,
I have a bug there : 
https://stackoverflow.com/questions/72795146/how-to-inject-a-script-using-playwright-that-will-create-an-unique-attribute-o
It is related to the 'pointer intercept' error... the click does not happen. I cannot get a trace because the click instruction loops. 

"playwright": "^1.22.2",
