### ISSUE TITLE
[BUG] Dropdown displayed abnormally (out of the browser window)

### ISSUE THREAD

**Issue by shuyanzhou** [microsoft/playwright#27142] opened 2023-09-17 23:03 UTC
### System info
- Playwright Version: [v1.37.0]
- Operating System: [ macOS 12.4]
- Browser: [Chromium]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

```python
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://russmaxdesign.github.io/exercise/")
    page.get_by_label("Favourite mammal").click()
    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)

```

**Steps**
- Run the code. 

**Expected**
The dropdown menu is displayed normally
<img width="500" alt="image" src="https://github.com/microsoft/playwright/assets/29911200/0d680868-9b2c-452b-b26b-008daa0e511a">

**Actual**
The dropdown menu is displayed in an irregular size, even out of the browser
<img width="500" alt="image" src="https://github.com/microsoft/playwright/assets/29911200/335098a1-9724-41a8-b404-5ca1bee7bd0c">

**Comment by mxschmitt** [comment] 2023-09-18 09:06
How is this affecting your end-to-end tests? The automation should not be affected by that.

**Comment by shuyanzhou** [comment] 2023-09-18 15:14
Thanks! I am using `playwright` for web automation purposes. For example, given a natural language command of "Tell me what are in the dropdown menu", my model clicks the dropdown and reads from the screen (or the HTML) to list all the items. However, due to this display bug right now, these items are not visible.

**Comment by aslushnikov** [comment] 2023-09-25 15:10
@shuyanzhou this kind of use case falls outside of the testing scope, so I'll close this issue as a "Won't Fix".

**Closed by aslushnikov** 2023-09-25 15:10 UTC
Labels: triaging

**Comment by rob-smallshire** [comment] 2023-11-17 14:39
We have a similar browser-automation non-testing use case and ran into the same problem. Noting that the dropdown was displayed at both the wrong scale and location we reasoned that the problem might be caused by not configuring our Playwright browser context with the appropriate `device_scale_factor` when calling `Browser.new_context`. This parameter defaults to 1.0, and the problem manifests when running on a display with some other device pixel ratio, such as a MacBook Retina display. which uses a value of 2.0.

Solution:

    context = browser.new_context(
        device_scale_factor=2.0,  # Appropriate for Retina. Determine as appropriate for your display
    )
