### ISSUE TITLE
[BUG] Firefox on getting response body

### ISSUE THREAD

**Issue by shirshak55** [microsoft/playwright#4153] opened 2020-10-15 13:13 UTC
The code looks similar to this

```
let cllback = async (response: Response) => {
    if (
      response.url().includes(`link_expected`)
    ) {
      const status = response.status()
      try {
        await response.finished()

        let json: any = await response.text()

        if (json) {
          let jjj = JSON.parse(json)
        }
      } catch (e) {
        console.log("error", e)
      }
    }
  }
  page.on("response", cllback)

```

This code has no issue on chromium. But when i use firefox it sometimes says Response is not available for redirection. I confirmed in firefox devtool there was json response. So I think this is either a firefox issue or there is some problem with playwright patch.

Took like whole day to figure out :(

**Comment by pavelfeldman** [comment] 2020-10-15 22:30
Could it be that Firefox is going through an extra redirect? - that would explain it. You might need to follow the redirect chain and only get the text from the last one.

**Comment by shirshak55** [comment] 2020-10-16 05:04
@pavelfeldman in devtool i don't see it creating new request (So I don't know if it ). But the issue is it works in chromium but not in firefox. Firefox do sees the request but it stops saying there is redirection .

**Comment by pavelfeldman** [comment] 2020-10-19 06:15
Is there a sample page where you can observe it? I'm still not sure what is happening vs what is expected. Following the bug file template would help!

**Comment by shirshak55** [comment] 2020-10-19 07:07
if you don't mind i would like to share this detail in private? Because I don't know if other website send similar response?

**Comment by pavelfeldman** [comment] 2020-10-20 00:48
If you can't reproduce it on a simple page / test case, it'll be hard for us to fix it and provide a test for the fix.

**Comment by pavelfeldman** [comment] 2020-10-23 04:49
Closing as per above.

**Closed by pavelfeldman** 2020-10-23 04:49 UTC
