### ISSUE TITLE
[Question]I want to remotely manage browsers on multiple servers. Is there a better solution?

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright#11262] opened 2022-01-08 10:20 UTC
Do you need to write your own logic to manage multiple server browsers? Or is there any existing scheme?

**Comment by aslushnikov** [comment] 2022-01-10 11:10
Dupe of https://github.com/microsoft/playwright/issues/11263

**Closed by aslushnikov** 2022-01-10 11:10 UTC
