### ISSUE TITLE
[Question]  Why does response.json fail in chromium scenario

### ISSUE THREAD

**Issue by nicoandmee** [microsoft/playwright#11553] opened 2022-01-21 17:41 UTC
Previous related issue: https://github.com/microsoft/playwright/issues/7831
I had previously (last year) opened an issue asking for advice on how to debug `response.json()` which was throwing an error along the lines of `No resource with given identifier found`. I've now determined that the problem only occurs with chromium-based browser, and appears to be related to a particular site doing redirection stuff while requests are in progress (or something along those lines, I'm not sure exactly, which is why I'm asking here). When I switched to firefox, I no longer encounter this issue and am able to read the `response.json()` just fine. The request whose response I want to read is part of a login `POST`. 

Clearly, the request was sent and a response received, so why can't chromium access it? Where can I learn more about the internals of how CDT handles cases such as this, and why does firefox implementation work but chrome does not.

Thank you!!

**Comment by mxschmitt** [comment] 2022-01-21 22:39
> only occurs with chromium-based browser

This error is coming from CDP, so yes its Chromium specific.

Would it be possible that you provide us a repro for it? Otherwise we can't debug it. It would help to to have a minimal one, you can also share it with us privately if needed.

**Comment by nicoandmee** [comment] 2022-01-21 22:58
Sure, here's the copy/paste from the original issue:
*Context*: I have some code that is using playwright to perform some basic automation (logging into a website). The cookies are pre-set and the process basically boils down to load a page, click sign in button (if present), intercept some XHR responses as json. I think clicking the sign in btn triggers a navigation.

*My problem*: Occasionally I encounter an error where the `interceptedResp.json()` is undefined. When debugging it locally I found this error produced on the CDP level: `No resource with given identifier found`. Researching this led me to [this](https://github.com/puppeteer/puppeteer/issues/2258) where I learned at least with puppeteer `resources get dumped after page commits navigation`. 

In my case I am doing 
```js
context.on('response', async (response) => {
      const url = response.url();

      if (url.includes(respURL1) && response.status() === 200) {
        respBody = await response.json();
      }

      if (url.includes(respURL2) && response.status() === 200) {
        headers = response.request().headers();
      }
    });
```

And clicking the btn like this:
```js
if (visible) {
await Promise.all([
 page.waitForResponse(response => response.url().includes(respURL1) && response.status() === 200),
 page.waitForResponse(response => response.url().includes(respURL2) && response.status() === 200),
 page.click('#SIGNINBTN')
 ]);
}
```
Destructuring the responses directly from the above wasn't an option because sometimes the sign in btn doesn't appear, and in that case I wanted to still intercept the responses. Strangely the above promise also resolves (so I know the response was there) but `respBody` is still undefined.

^ Last year when I posted the above, @dgozman mentioned that this feature (assuming he means response interception) is implemented differently in firefox. And as he suggested everything works fine when I switch out chrome for firefox. So I'm wondering:
- Is there a strategy to handle such a case where `response.json()` is called nearly at the same time as a redirect/navigation is processing (in chrome, that is)? 
- Any suggested resources to understand internally how/why this situation occurs?

AFAIK this is the same situation mentioned here as well: https://github.com/microsoft/playwright/issues/8584

**Comment by aslushnikov** [comment] 2022-01-28 00:43
> Sure, here's the copy/paste from the original issue:
Context: I have some code that is using playwright to perform some basic automation (logging into a website). The cookies are pre-set and the process basically boils down to load a page, click sign in button (if present), intercept some XHR responses as json. I think clicking the sign in btn triggers a navigation.

@nicoandmee the details you share are not enough for us to reproduce the issue. Ideally we have something that we can run locally and debug it. Otherwise, it's not actionable!

> Any suggested resources to understand internally how/why this situation occurs?

Since both Playwright and Chromium are open source, you can build them and debug what's going on, but that might be challenging. It'd be much easier if you can come up with a good repro so that we can debug it ourselves!

**Comment by nicoandmee** [comment] 2022-02-06 00:21
@aslushnikov Is there a secure means I could privately share something reproducible? It involves logging in to a certain website and I'm not comfortable sharing here.

**Comment by pavelfeldman** [comment] 2022-02-09 05:39
This error is due to the response.json() being called after page navigated to a new URL. You can only retrieve response content while you are on the same page.

**Comment by pavelfeldman** [comment] 2022-02-11 20:24
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2022-02-11 20:24 UTC
Labels: triaging
