### ISSUE TITLE
[Feature] introduce `missing-no-fail` mode for `updateSnapshots` option

### ISSUE THREAD

**Issue by jquinterot** [microsoft/playwright#27217] opened 2023-09-20 17:19 UTC
Good day first I want to say thanks for the awesome work!

I only have two suggestions or desired features.

1. The first one is that in order to provide more order to our tests and provide a better architecture and organization, it would be great to have a way to run our tests matching a test pattern, for example inside the tests folder I could have other folders like `component1/test.ts` and other like `component2/test.ts` having this would be great that playwright can run the tests located on these folders by something like `tests/**/*.ts` or a pattern that recognize the tests on the folders. Having this we can organize our tests even better that have all the tests on the tests folder and start looking what is doing everyone.
2. The other will be about the visual comparison, to have a way to recognize that if there is no base image create it but not fail, just say base line created and if there is already an image just do the comparison, having this the tests wont fail on a ci/cd pipeline each time and id there is already images will just do the comparison

Well this is the only thing I can think so far, thank you for reading this and hope the test match can be a reality some day due to test runners like jest and mocha have it but is sad to try to use other runners losing awesome features like the UI mode, code gen and all useful things from playwright runner.

Thank you again and have a nice day 🗡️

**Comment by aslushnikov** [comment] 2023-09-20 20:02
Hey @jquinterot,

> The first one is that in order to provide more order to our tests and provide a better architecture and organization, it would be great to have a way to run our tests matching a test pattern, for example inside the tests folder I could have other folders like component1/test.ts and other like component2/test.ts having this would be great that playwright can run the tests located on these folders by something like tests/**/*.ts or a pattern that recognize the tests on the folders. Having this we can organize our tests even better that have all the tests on the tests folder and start looking what is doing everyone.

This is already implemented using the [`testMatch`](https://playwright.dev/docs/api/class-testproject#test-project-test-match) config option: https://playwright.dev/docs/api/class-testproject#test-project-test-match

> The other will be about the visual comparison, to have a way to recognize that if there is no base image create it but not fail, just say base line created and if there is already an image just do the comparison, having this the tests wont fail on a ci/cd pipeline each time and id there is already images will just do the comparison

This sounds like a valid feature request.

**Comment by jquinterot** [comment] 2023-09-21 04:56
@aslushnikov thank you so much for reading my message and take it into account, it is like an honor and a dream come true to me just having this interaction haha, I always follow your releases and work 👍👍

**Comment by CyriacBr** [comment] 2023-09-26 10:29
This is a duplicate of https://github.com/microsoft/playwright/issues/23502#issuecomment-1735247372

**Comment by aslushnikov** [comment] 2023-09-26 22:08
@CyriacBr thank you for pointing out! I remembered we had something filed for this, but was unable to find it.

Merging this to https://github.com/microsoft/playwright/issues/23502 then!

**Closed by aslushnikov** 2023-09-26 22:08 UTC
Labels: P3-collecting-feedback
