### ISSUE TITLE
[Question] - storageState - only working in 1 of 3 browsers 

### ISSUE THREAD

**Issue by jlee-vouch** [microsoft/playwright#16556] opened 2022-08-15 20:36 UTC
I originally posted this as a discussion before I saw that the api docs link to issues/questions for questions, so here it is:
https://github.com/microsoft/playwright/discussions/16548

I am new to playwright so I assume I am doing something wrong.  I am trying to use storageState with Auth0.  

My global-setup.js has the following:
```javascript
const auth0StorageState = './auth/UATAuth0AgentAuth.json'
  browser = await chromium.launchPersistentContext('', { headless: true })
  page = await browser.newPage()
  await auth0LoginPage.login(page)
  await page.context().storageState({
    path: auth0StorageState,
  })
```
  
  My test has this:
```javascript
  test.describe('UI Tests for new UI', () => {
  test.use({ storageState: './auth/UATAuth0AgentAuth.json' })
  
  test('Should bypass log in page', async ({ page }) => {
  await page.goto('https://<<myURL>>/')
  ```
  
 This is what I am seeing, if I run one browser, chromium, firefox, safari, it works just fine, due to getting creds and storing them in global-setup, the login page is bypassed.  
  
  IF I run all three browsers, only one of the 3 will bypass the login page, it is as if the other two aren't picking up or using the storageState correctly.  
  
  Any idea what I am doing wrong?
  
  Right now I am running in chromium only by doing this
```javascript
  test.describe('UI Tests for new UI', () => {
  test.skip(({ browserName }) => browserName !== 'chromium', 'Chromium only!')
  test.use({ storageState: './auth/UATAuth0AgentAuth.json' })
  ```
  
  My playwright-config.js browser setup:
  ```javascript
    projects: [
    {
      name: 'firefox',
      use: {
        ...devices['Desktop Firefox'],
      },
    },
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
    {
      name: 'webkit',
      use: {
        ...devices['Desktop Safari'],
      },
    }
  ```

**Comment by aslushnikov** [comment] 2022-08-16 08:43
@jlee-vouch could you please try running these all with `--workers 1` and see if it passes? It might be that auth0 is actually unhappy with multiple simultaneous sessions from the same user.

**Comment by jlee-vouch** [comment] 2022-08-16 13:40
> @jlee-vouch could you please try running these all with `--workers 1` and see if it passes? It might be that auth0 is actually unhappy with multiple simultaneous sessions from the same user.

That didn't fix it, I ran with this config:
` --headed --project=chromium --project=firefox --project=webkit --repeat-each 1 --retries 0 --timeout 0 --workers 1`

Same results, once it hits the second and third browser, it goes to the auth0 login screen vs using the stored creds.  I ran each browser in debug mode, one at a time and they all worked but all in the same run, only the first one works.

**Comment by aslushnikov** [comment] 2022-08-16 17:00
@jlee-vouch could you please share a snippet that I can run locally to reproduce this? It could be that something is overwriting the storage state and runs multiple times.

**Comment by jlee-vouch** [comment] 2022-08-16 23:42
> @jlee-vouch could you please share a snippet that I can run locally to reproduce this? It could be that something is overwriting the storage state and runs multiple times. 

I will see what I can come up with. Most of the code is above. I am not sure if I can publish anything around the auth0 auth stuff since it requires a company app and usernames and passwords. 

I did put breakpoints in the code and I verified the json file with the cookies for auth do not change after the first successful use and the failing second and third. 

Is there a way to look at any variables or browser data in the runs to ensure it properly loaded?  It for sure is in the first run/browser it launches.

**Comment by aslushnikov** [comment] 2022-08-17 14:22
> Is there a way to look at any variables or browser data in the runs to ensure it properly loaded? It for sure is in the first run/browser it launches.

@jlee-vouch  Browser DevTools can show you localstorage state, for example.

> I did put breakpoints in the code and I verified the json file with the cookies for auth do not change after the first successful use and the failing second and third.

Well, something should change, otherwise things would work! Hard to say what's going on though.

> I will see what I can come up with.

We'll appreciate if you can come up with any repro that demonstrates the issue. I'll close this for now since it's not actionable on our side, but please do not hesitate to file another issue if you have a repro we can run locally & debug!

**Closed by aslushnikov** 2022-08-17 14:22 UTC
Labels: triaging

**Comment by jlee-vouch** [comment] 2022-08-17 21:19
@aslushnikov I figured out what the problem was.  I spend most of the day making a new auth0 app, a test express app etc and sharing the auth0 creds worked.... 

So I looked at the app that isn't working and this stuck out:
<img width="996" alt="Screen Shot 2022-08-17 at 4 11 05 PM" src="https://user-images.githubusercontent.com/100603241/185244274-fb92e109-60f1-4b8d-a603-2c26896b026e.png">

Refresh Token Rotation was enabled in Auth0.

So in my test, after every navigation to my site that does an auth0 check, I wait for the redirect to happen back to our site and I write the new keys/values back to my json file

```javascript
test.describe('UI Tests for MYSITE', () => {
  test.use({ storageState: './auth/UATAuth0AgentAuth.json' })


test('NAV TO MY SITE', async ({ page }) => {
  await page.goto('https://mysite.com/')
  await page.locator('text=Log In').click()
  await page.waitForSelector('text=Welcome',{timeout:25000})
  const auth0StorageState = './auth/UATAuth0AgentAuth.json'
  await page.context().storageState({
    path: auth0StorageState,
  })
```

The downsides are it seems like I would have to run with just 1 worker but it is OK for now.

Thanks for your help

**Comment by ksvvandana** [comment] 2024-09-11 08:48
> @aslushnikov I figured out what the problem was. I spend most of the day making a new auth0 app, a test express app etc and sharing the auth0 creds worked....
> 
> So I looked at the app that isn't working and this stuck out: <img alt="Screen Shot 2022-08-17 at 4 11 05 PM" width="996" src="https://user-images.githubusercontent.com/100603241/185244274-fb92e109-60f1-4b8d-a603-2c26896b026e.png">
> 
> Refresh Token Rotation was enabled in Auth0.
> 
> So in my test, after every navigation to my site that does an auth0 check, I wait for the redirect to happen back to our site and I write the new keys/values back to my json file
> 
> ```js
> test.describe('UI Tests for MYSITE', () => {
>   test.use({ storageState: './auth/UATAuth0AgentAuth.json' })
> 
> 
> test('NAV TO MY SITE', async ({ page }) => {
>   await page.goto('https://mysite.com/')
>   await page.locator('text=Log In').click()
>   await page.waitForSelector('text=Welcome',{timeout:25000})
>   const auth0StorageState = './auth/UATAuth0AgentAuth.json'
>   await page.context().storageState({
>     path: auth0StorageState,
>   })
> ```
> 
> The downsides are it seems like I would have to run with just 1 worker but it is OK for now.
> 
> Thanks for your help

Our application also has the refresh token rotation turned ON, I am able to use the storage state only for one test and the next test is prompting me to login, any pointers?
