### ISSUE TITLE
[BUG] Webkit Flaky & Slow tests when attempting to click/check/etc elements in a form (unstable elements, change of viewport, etc)

### ISSUE THREAD

**Issue by garciallorente-fer** [microsoft/playwright#12370] opened 2022-02-25 18:01 UTC
**Context:**
- Playwright Version: 1.19.2 (It has been happening since 1.15)
- Operating System: Windows
- Node.js version: 16
- Browser: WebKit

**Code Snippet**

1. Navigate to https://github.com/garciallorente-fer/webkit-unstable-playwright and clone the project locally & run it (or check the report html or trace)
2. Notice how elements in webkit are unstable at first (using the trace viewer)
3. Notice how it sometimes fails to check elements (flaky) (not only with checkboxes, this is just an example)
5. Check the uploaded reports and images proving that

```
locator.setChecked: Clicking the checkbox did not change its state
=========================== logs ===========================
waiting for selector "input[type=radio][id=CheckboxYes3] ~ span"
  selector resolved to visible <span class="c-radio-group__text">Yes</span>
attempting click action
  waiting for element to be visible, enabled and stable
    element is not stable - waiting...
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  element is outside of the viewport
retrying click action, attempt #1
  waiting for element to be visible, enabled and stable
    element is not stable - waiting...
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  click action done
  waiting for scheduled navigations to finish
  navigations have finished
```

**Describe the bug**

Webkit is very flaky and takes long time, has to change constantly the viewport in search for elements before performing the action, and also waits for elements to be stable (only in webkit). This is just a little example of code, in some of the larger tests I run it is much slower and very flaky (it sometimes does not check the elements or it does not click on them) with larger forms and webpages, only when running it with webkit, and has been happening for months (to this specific project/pages)

**Comment by aslushnikov** [comment] 2022-03-04 09:35
Repro summary:

```bash
cd /tmp
git clone https://github.com/garciallorente-fer/webkit-unstable-playwright
cd webkit-unstable-playwright
npm i
npx playwright test
```

Doesn't repro for me on MacOS though; @yury-s could you please check on Windows?

**Comment by davidglezz** [comment] 2022-03-04 17:52
@garciallorente-fer You mean this?

Chrome and Firefox shows uniform step times and the same log in the trace:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/194784/156814142-c4686fce-7281-418e-8286-f49c827a78f7.png">
```
waiting for selector "input[type=radio][id=CheckboxYes4] ~ span"
selector resolved to visible <span class="c-radio-group__text">Yes</span>
attempting click action
waiting for element to be visible, enabled and stable
element is visible, enabled and stable
scrolling into view if needed
done scrolling
performing click action
click action done
waiting for scheduled navigations to finish
navigations have finished
```
But webkit, we can see that some tests take more time and the logs report several waits to be stable...
<img width="445" alt="image" src="https://user-images.githubusercontent.com/194784/156815269-3d80860e-7038-40c1-8fa6-3e80f6e80b9d.png">


```
waiting for selector "input[type=radio][id=CheckboxYes4] ~ span"
selector resolved to visible <span class="c-radio-group__text">Yes</span>
attempting click action
waiting for element to be visible, enabled and stable
element is not stable - waiting...
element is visible, enabled and stable
scrolling into view if needed
done scrolling
element is outside of the viewport
retrying click action, attempt #1
waiting for element to be visible, enabled and stable
element is not stable - waiting...
element is visible, enabled and stable
scrolling into view if needed
done scrolling
performing click action
click action done
waiting for scheduled navigations to finish
navigations have finished
```

**Comment by garciallorente-fer** [comment] 2022-03-04 21:16
> Repro summary:
> 
> ```shell
> cd /tmp
> git clone https://github.com/garciallorente-fer/webkit-unstable-playwright
> cd webkit-unstable-playwright
> npm i
> npx playwright test
> ```
> 
> Doesn't repro for me on MacOS though; @yury-s could you please check on Windows?

Hello @aslushnikov , as the @davidglezz explained in his comment, the issue of Webkit being flaky is not about passing the test or not, but about being much slower to do actions with the elements in the DOM always, and sometimes leading that to a failure of the test. Both in Windows and MacOS

**Comment by yury-s** [comment] 2022-03-08 01:51
If the test is slower in webkit and sometimes times out you can increase [timeout](https://playwright.dev/docs/api/class-testconfig#test-config-timeout) in that particular project.

I managed to reproduce this error on Linux:
```
Running 3 tests using 3 workers                          
  1) [Webkit] › webkit-unstable.test.ts:4:1 › Wbkit unstable elements out of viewport ==============

    locator.setChecked: Clicking the checkbox did not change its state
    =========================== logs ===========================
```
It means that there is a race condition in the page, playwright clicked on the checkbox and after that validated that it actually changed its state, the latter check did fail. Most likely some js logic was not ready by the time playwright clicked on the element,  I don't know why it's specific to webkit maybe just timing issue maybe it's some browser specific implementation. Normally this indicates a bug in the page as if a human clicked on the element quickly enough the checkbox wouldn't be checked either. E.g. adding the following before failing line fixes the flakiness for me locally:

```js
  await page.locator('input[type=radio][id=CheckboxYes3] ~ span').scrollIntoViewIfNeeded();
  await page.waitForTimeout(100);
```

**Comment by davidglezz** [comment] 2022-03-08 08:23
@yury-s Could it be a Playwright race condition?, since this test doesn't contain JS, just plain html+css.

**Comment by garciallorente-fer** [comment] 2022-03-12 17:18
Thanks for your reponse @yury-s , after adding `.scrollIntoViewIfNeeded()` before each of the actions of the example, I can see that the Trace Logs do not show anymore the error "element is outside of the viewport" and therefore the test stops becoming flaky, but the error "_element is not stable - waiting..._" is still happening, and that "solution" would still not explain why are those errors happening only in Webkit.

I would not think that a good solution would be adding `scrollintoviewifneeded()` to all the actions of all the tests only for the webkit tests, would not solve the "_element is not stable - waiting..._", and this is only an example code that is really small with minimum html & css, with just checkbox elements, that comes from a much bigger project with many more actions and elements, in each of with I would have to add an extra step only for Webkit and where I would still have some delays and unstable elements.
As @davidglezz mentioned this example does not contain JS code

Here I leave 2 screenshots from the traces ,to see the difference between chromium and webkit timing, and the LOGS for each of them
Chromium:
![chromium](https://user-images.githubusercontent.com/55386160/158027657-26d0cbe5-3a45-4d0e-b0d4-e52f27a32783.jpg)

Webkit:
<img width="812" alt="image" src="https://user-images.githubusercontent.com/55386160/158027654-a757453e-f991-4293-a102-5e8841d15e76.png">

**Comment by pavelfeldman** [comment] 2022-03-14 20:41
My triaging shift started and I'm going over the bugs marked as 'triaging'. Unfortunately, there is too much context for me to be able to grasp and to be helpful. If you could narrow down the problem to something that we could reproduce, it would make this issue actionable on our side. We need a snippet of code reproducing the issue along with the expectations and actual results. That way we can prioritize the fix. Please open a new issue if you manage to create something we can reproduce and link this issue there for context.

**Comment by davidglezz** [comment] 2022-03-14 21:43
If you read the description above you can see that the author has created a repository with a snippet that reproduces the issue.
@pavelfeldman Please reopen

**Comment by garciallorente-fer** [comment] 2022-03-14 22:35
@pavelfeldman in the description you have clearly all the minimum information to check and/or reproduce the issue.

1. Navigate to **_https://github.com/garciallorente-fer/webkit-unstable-playwright_** and clone the project locally & run it (or just check the report html or trace)

2. Notice how elements in webkit are unstable at first (using the trace viewer)
![image](https://user-images.githubusercontent.com/55386160/158271557-b5e36111-1964-462e-9cf2-37a138a0775d.png)

Notice how it sometimes fails to check elements (flaky) &  (not only with checkboxes, this is just an example), & even if it does not fail checking the trace you can see clearly all the issues that makes it slower and having to retry actions or wait for unstable elements, only in webkit "element is not stable - waiting..." "retrying.."

Please **reopen** @aslushnikov , @pavelfeldman , @yury-s , this is an issue that makes bigger automation projects similar to this example (with this html & css) (not javascript) be really flaky and taking too much time only in webkit.

**Comment by pavelfeldman** [comment] 2022-03-14 23:50
I can repro. As a workaround, you can add this for now:

```js
await page.addStyleTag({ content: 'html { scroll-behavior: initial; }' });
```

**Comment by dgozman** [comment] 2022-03-14 23:54
@yury-s Chromium has `--disable-smooth-scrolling` to disable this completely.

**Comment by Zoltanpetrik** [comment] 2022-04-12 20:34
I have the same issue where I cannot reliably check a checkbox with the check() function in Firefox.

Unfortunately the codebase I'm working on is proprietary and I have no time to create a POC.

Tried .focus()-ing on the checkbox first, or using "forced" true, but neither of them helps.

The workaround also does not help.

using v1.21

How can I gather information which could help in investigating this?

**Comment by AmanDaharwal** [comment] 2022-04-13 06:49
I am also the same with webkit. The same tests works fine with chromium and firefox, but in case of webkit, the tests are unable to locate element or perform actions( click, select, check, etc, etc). 
Most common observations are - waiting for selector, element is outside the viewport, element is not stable. etc

**Comment by yury-s** [comment] 2022-05-02 21:49
> ```js
> await page.addStyleTag({ content: 'html { scroll-behavior: initial; }' });
> ```

Can you try the following instead, it should fix the problem in webkit:
```js
await page.addStyleTag({ content: 'html { scroll-behavior: initial !important; }' });
```
The issue is caused by this [CSS style rule](https://github.com/garciallorente-fer/webkit-unstable-playwright/blob/cc0b846a850637666fb02f2b1f441048cf9b8fa9/webkit-unstable.css#L814) in your project, we should probably always disable this smooth scrolling bahavior during automation.

**Comment by garciallorente-fer** [comment] 2022-05-04 16:49
> > ```js
> > await page.addStyleTag({ content: 'html { scroll-behavior: initial; }' });
> > ```
> 
> Can you try the following instead, it should fix the problem in webkit:
> 
> ```js
> await page.addStyleTag({ content: 'html { scroll-behavior: initial !important; }' });
> ```
> 
> The issue is caused by this [CSS style rule](https://github.com/garciallorente-fer/webkit-unstable-playwright/blob/cc0b846a850637666fb02f2b1f441048cf9b8fa9/webkit-unstable.css#L814) in your project, we should probably always disable this smooth scrolling behavior during automation.

Hello @yury-s , thanks a lot for your response, I can confirm that using that line of code makes it work perfectly again, like in Chromium & Firefox. :)
Would there be a fix in future releases where that line wont be needed anymore?

**Comment by yury-s** [comment] 2022-05-04 23:42
> Would there be a fix in future releases where that line wont be needed anymore?

Yes, it will be fixed in the next release and the workaround won't be needed.

**Closed** 2022-05-05 16:49 UTC
Labels: v1.22
