### ISSUE TITLE
[Bug]: Assertion with frames results in unhandledRejection

### ISSUE THREAD

**Issue by Mango88Boba** [microsoft/playwright#7979] opened 2021-08-04 06:20 UTC
### Playwright version

1.12.3

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

Note that I earlier reported this issue as "UnhandledRejection error during page.click with navigation #7527" and thanks for noticing my issue with using await inside Promise.all statement.  I have since corrected that error and I still am seeing unhandledRejection error.  Please see the attached code and playwright log.  My log shows a working and failing sequence for your review.  
```
Excerpt from the failing sequence here:
  pw:api attempting click action +4ms
  pw:api   waiting for element to be visible, enabled and stable +1ms
  pw:api   element is visible, enabled and stable +45ms
  pw:api   scrolling into view if needed +1ms
  pw:api   done scrolling +2ms
  pw:api   checking that element receives pointer events at (355,571) +3ms
  pw:api   element does receive pointer events +7ms
  pw:api   performing click action +0ms
  pw:api   navigated to "link3" +31ms
  pw:api   "domcontentloaded" event fired +3ms
  pw:api   click action done +28ms
  pw:api   waiting for scheduled navigations to finish +0ms
  pw:api   navigations have finished +35ms
  pw:api <= page.click succeeded +1ms
  pw:api   navigated to "link8" +94ms
  pw:api   navigated to "link8" +4ms
**unhandledRejection: Error
    at Object.assert (C:\Users\TTNUC01\Desktop\podapp-e2e.711\node_modules\playwright\lib\utils\utils.js:194:15)
    at FrameManager.frameAttached (C:\Users\TTNUC01\Desktop\podapp-e2e.711\node_modules\playwright\lib\server\frames.js:96:21)
    at FrameSession._onFrameAttached (C:\Users\TTNUC01\Desktop\podapp-e2e.711\node_modules\playwright\lib\server\chromium\crPage.js:531:34)
    at CRSession.<anonymous> (C:\Users\TTNUC01\Desktop\podapp-e2e.711\node_modules\playwright\lib\server\chromium\crPage.js:351:96)
    at CRSession.emit (events.js:315:20)
    at C:\Users\TTNUC01\Desktop\podapp-e2e.711\node_modules\playwright\lib\server\chromium\crConnection.js:158:22**
  pw:api   navigated to "about:blank" +53ms
  pw:api   "domcontentloaded" event fired +1ms
  pw:api   "domcontentloaded" event fired +3ms
  pw:api   "load" event fired +34ms
  pw:api <= page.waitForNavigation succeeded +9ms
  pw:api => page.waitForTimeout started +1ms
  pw:api   "load" event fired +1ms
  pw:api <= page.waitForTimeout succeeded +5s
  pw:api => browser.close started +2ms
  pw:api <= browser.close succeeded +376ms
```

[rejection.zip](https://github.com/microsoft/playwright/files/6929031/rejection.zip)

**Comment by Mango88Boba** [comment] 2021-08-05 02:21
I changed to Playwright 1.13.1 and it is still failing with attached log.  How can I get the reproducible data to you?  Unfortunately, we cannot give you a login to this site, but I can run whatever is needed to gather data for you.  I can also log in and set up a some remote debugging session with your developer.  What do you suggest?

[pw_0804.log](https://github.com/microsoft/playwright/files/6935463/pw_0804.log)

**Comment by pavelfeldman** [comment] 2021-08-05 03:52
@JoelEinbinder was fixing it a long time ago and it stopped bothering us since then. At least that's what I thought.

**Comment by JoelEinbinder** [comment] 2021-08-09 13:41
The easiest way for me to debug this is to get a protocol log via `DEBUG=pw:protocol`. This will be a much larger log which might contain some more sensitive information though. You should do a find/replace on it for any URLs/passwords that you don't want me to see. I am interested in the relative order of the frameAttached and frameNavigated events. Feel free to send it to me via email JoelEinbinder (at) microsoft.com.

**Comment by Mango88Boba** [comment] 2021-08-10 19:50
Just emailed the protocol log directly to Joel.

**Comment by JoelEinbinder** [comment] 2021-08-23 23:57
I received the protocol look and was looking into it. It's definitely a bug, but I am unable to create a test for it so far.

**Comment by Mango88Boba** [comment] 2021-08-24 05:55
I can help test a possible fix on our internal site, if needed.

**Comment by Mango88Boba** [comment] 2021-09-28 01:43
Just tried on playwright 1.15.0 and it still crashes with this error:  

    Assertion error

      at assert (node_modules/playwright/lib/utils/utils.js:255:21)
      at FrameManager.frameAttached (node_modules/playwright/lib/server/frames.js:111:25)
      at FrameSession._onFrameAttached (node_modules/playwright/lib/server/chromium/crPage.js:662:30)
      at CRSession.<anonymous> (node_modules/playwright/lib/server/chromium/crPage.js:454:373)
      at node_modules/playwright/lib/server/chromium/crConnection.js:225:14
          at runMicrotasks (<anonymous>)

**Comment by mxschmitt** [comment] 2021-09-28 09:23
@Mango88Boba do you have a reproducible for that or some code which you can share?

**Comment by Mango88Boba** [comment] 2021-09-30 06:33
[log.zip](https://github.com/microsoft/playwright/files/7257205/log.zip)
Attached is source code that can produce issue on our internal site.  Unfortunately, we can grant access to the internal site.  The log file using the DEBUG=pw:protocol is also attached.

**Comment by unlikelyzero** [comment] 2021-11-17 23:28
This has been a blocker for us as well. Interestingly, when we run raw node.js (outside of playwright/test or jest) we do not experience this issue

**Comment by unlikelyzero** [comment] 2021-11-18 00:04
I believe this is also related https://github.com/microsoft/playwright/issues/9231

**Comment by Mango88Boba** [comment] 2022-01-13 02:45
This assertion error is still occurring me with 1.17.2 using the same sample code that I previously submitted.

**Comment by pavelfeldman** [comment] 2022-10-20 03:10
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-10-20 03:10 UTC
Labels: P3-collecting-feedback
