### ISSUE TITLE
[BUG] Webkit throws an "Object with guid response@<hash> was not bound in the connection" error when more than 1 test run 

### ISSUE THREAD

**Issue by wahreChrist** [microsoft/playwright#28214] opened 2023-11-17 09:00 UTC
### System info
- Playwright Version: [v1.38 - 1.39]
- Operating System: Ubuntu 22.04
- Browser: [WebKit]
- Other info:

After updating playwright to versions 1.38/1.39 I started experiencing this problem that when I`m running more than 1 webkit test, or a bunch of tests for all 3 browsers, webkit tests always fail with "Object with guid response@<hash> was not bound in the connection" error in a first few seconds. Tried the same tests, with the same setup on 1.37 - everything works fine. In general, I would say that even when I run a single webkit test now, its significantly slower in execution than before, especially with video recording "on", 45+ seconds against 10-15 seconds for the same test on 1.37. Any ideas why it might be happening?

### Source code

- [-] I provided the exact source code that allows reproducing the issue locally.

I am not providing any code because the issue happens regardless of the test.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: "./tests",
    timeout: 70 * 1000,
    expect: {
        timeout: 7000,
    },
    fullyParallel: false,
    forbidOnly: !!process.env.CI,
    retries: process.env.CI ? 2 : 0,
    workers: 1,
    reporter: [["list"], ["html"]],
    use: {
        actionTimeout: 0,
        baseURL: process.env.DEV
            ? process.env.DEV_URL
            : "http://127.0.0.1:4343",
        ignoreHTTPSErrors: true,
        trace: "on",
        video: "off",
    },
    projects: [{
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    }],
    outputDir: "test-results/",
});
```

**Steps**
- Run any 2+ webkit tests

**Expected**

Expected tests to be run without issues like when I run them individually

**Actual**

90% of tests fail in the first few seconds with an "Object with guid response@<hash> was not bound in the connection" error if run in a bunch/sequentially instead of individually.

Here are debug logs from API and browser:
```
pw:api=>selectors.setTestIdAttribute started+0ms
pw:api<=selectors.setTestIdAttribute succeeded+6ms
pw:api=>selectors.setTestIdAttribute started+76ms
pw:api=>browserType.launch started+9ms
pw:api<=selectors.setTestIdAttribute succeeded+8ms
pw:api<=browserType.launch succeeded+920ms
pw:api=>browser.newContext started+4ms
pw:api<=browser.newContext succeeded+8ms
pw:api=>browserContext.newPage started+47ms
pw:api<=browserContext.newPage succeeded+250ms
pw:api=>page.unroute started+12ms
pw:api<=page.unroute succeeded+22ms
pw:api=>page.routeFromHAR started+17ms
pw:api=>page.route started+9ms
pw:api<=page.routeFromHAR succeeded+46ms
pw:api<=page.route succeeded+5ms
pw:api=>page.goto started+7ms
pw:api navigating to "https://localhost:4343/home2/serve/ad-e2e/#tabs_overview", waiting until "load"+60ms
pw:api "commit" event fired+216ms
pw:api navigated to "https://localhost:4343/home2/serve/ad-e2e/#tabs_overview"+0ms
pw:api=> started+1s
pw:api=> started+3ms
pw:api<= succeeded+3ms
pw:api=> started+1ms
pw:api=> started+1ms
pw:api "domcontentloaded" event fired+1ms
pw:api<= succeeded+2ms
pw:api<= succeeded+2ms
pw:api<= succeeded+2ms
pw:api=> started+37ms
pw:api=> started+37ms
pw:api=> started+13ms
pw:api=> started+13ms
pw:api "load" event fired+776ms
pw:api<= succeeded+11ms
pw:api<= succeeded+0ms
pw:api<= succeeded+0ms
pw:api<= succeeded+1ms
```
Browser:
```
 pw:browser <launching> /home/alev/.cache/ms-playwright/webkit-1921/pw_run.sh --inspector-pipe --headless --no-startup-window +0ms
  pw:browser <launched> pid=141892 +26ms
  pw:browser [pid=141892][err] /home/alev/.cache/ms-playwright/webkit-1921/pw_run.sh: line 24: 141898 Killed                  WEBKIT_FORCE_COMPLEX_TEXT="1" "$MINIBROWSER" "$@" +3s
  pw:browser [pid=141892] <process did exit: exitCode=137, signal=null> +1ms
  pw:browser [pid=141892] starting temporary directories cleanup +1ms
  pw:browser [pid=141892] finished temporary directories cleanup +44ms
```

**Comment by mxschmitt** [comment] 2023-11-17 09:46
Since this issue is not following the bug template and does not contain a self-contained reproducible, we unfortunately need to close it.

Feel free to re-file with more information which help us to reproduce this bug locally, thanks for your understanding!

**Closed by mxschmitt** 2023-11-17 09:46 UTC
