### ISSUE TITLE
[Feature]: Add ability to mask sensitive data by regex in page.goto() method

### ISSUE THREAD

**Issue by KaterynaBuhaichuk** [microsoft/playwright#32545] opened 2024-09-10 15:21 UTC
### 🚀 Feature Request

Add ability to mask sensitive data by regex in [page.goto() method ](https://playwright.dev/docs/api/class-frame#frame-goto)

### Example

page.goto('https://example.somedomain.com/?jwt=********') 

### Motivation

Increase security, decrease the probability of data leakage

**Comment by Kranael** [comment] 2024-09-11 07:23
Just use env data here? So process.env.jwt for example. Not possible?

**Comment by VolodymyrTysovskyi13** [comment] 2024-09-11 07:45
> Just use env data here? So process.env.jwt for example. Not possible?

would this prevent the JWT to be logged in a unmasked type?

**Comment by dgozman** [comment] 2024-09-11 08:24
Duplicate of #31728.

**Closed by dgozman** 2024-09-11 08:24 UTC
