### ISSUE TITLE
[Feature] Simulate mouse movements so you can visually see what is being clicked during a test run

### ISSUE THREAD

**Issue by umaar** [microsoft/playwright#2718] opened 2020-06-25 21:38 UTC
Just a small feature suggestion. In TestCafe, a test automation tool, I remember they had a giant simulated mouse which you can see in [this video](https://youtu.be/EufdahOSJIc?t=1368). Benefits:

- Easy to see what the test is doing without having to refer to the code
- Good for visual demonstrations to other people 
- When looking at a video of your test run, it's very helpful for debugging

Not having such a feature means, when watching a test run, even if you slow the tests down, it's not always obvious what is occurring - pages can just appear to 'flash' from one to another.

Appreciate this is a cosmetic thing and maybe not the most important thing to do.

**Comment by pavelfeldman** [comment] 2020-06-25 22:48
I believe @JoelEinbinder has it implemented and @dgozman has a mode where we can enable it.

**Comment by aslushnikov** [comment] 2020-08-21 06:49
Dupe of #1374. Will be addressed shortly by https://github.com/microsoft/playwright/pull/3526

**Closed by aslushnikov** 2020-08-21 06:49 UTC
