### ISSUE TITLE
[BUG] Cookies for other domain not present in Chromium or Firefox DevTools after using addCookies

### ISSUE THREAD

**Issue by mwallace72** [microsoft/playwright#2795] opened 2020-07-01 18:34 UTC
**Context:**
- Playwright Version: 1.1.1
- Operating System: Mac
- Node version: v12.14.1
- Browser: Chromium & Firefox (untested with Webkit)
- Extra: 

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const json = JSON.parse(rawJson)
    Object.keys(json).forEach(url => {
      Object.keys(json[url]).forEach(urlExt => {
        Object.keys(json[url][urlExt]).forEach(cookieName => {
          if (json[url][urlExt][cookieName].value) {
            const cookie = {
              name: cookieName,
              ...json[url][urlExt][cookieName],
            }
            // Firefox doesn't like the following cookie keys
            delete cookie.key
            delete cookie.maxAge
            delete cookie.extensions
            delete cookie.creation
            delete cookie.hostOnly
            delete cookie.lastAccessed
            // Fix cookie dates for Playwright
            if (cookie.expires) {
              cookie.expires = new Date(cookie.expires).getTime() / 1000
            }
            cookies.push(cookie)
          }
        })
      })
    })
    await this.context.addCookies(cookies)
    let browserCookies = await this.context.cookies()
    console.log(browserCookies.length) // ==> logs 8 (as expected)
```

**Describe the bug**

The above code does not generate an error - further, the log of cookies does indeed display cookies present (by length) for browser context. However, upon inspection of the browsers opened (the "Application" tab of Dev options in Chrome, and the "Storage" tab of Dev options in Firefox), there are no existing cookies shown.

Apologies for some of the cookie processing mess, we're acquiring the cookies from a separate tool and some transform was needed before the cookies were accepted by Playwright, and specifically Firefox.

An additional note: on a previous version of playwright, using the same code, we were able to observe cookies in Firefox "Storage" tab as expected.

**Comment by aslushnikov** [comment] 2020-07-02 00:44
@mwallace72 so do I understand correctly that even though Playwright reports cookies via its API, you don't actually see them in DevTools?

**Comment by mwallace72** [comment] 2020-07-02 13:51
> @mwallace72 so do I understand correctly that even though Playwright reports cookies via its API, you don't actually see them in DevTools?

@aslushnikov Yes, that is accurate.

**Comment by pavelfeldman** [comment] 2020-07-02 14:34
@mwallace72 how do you test those cookies? You would need to run this code with `headless: false`, open a page in this browser context programmatically and then navigate it to the url where some of the cookies would match it, all that without restarting the browser and closing the context. Is that how who test it?

**Comment by mwallace72** [comment] 2020-07-02 15:34
> @mwallace72 how do you test those cookies? You would need to run this code with `headless: false`, open a page in this browser context programmatically and then navigate it to the url where some of the cookies would match it, all that without restarting the browser and closing the context. Is that how who test it?

Yes, to confirm, my automation is running `headless: false` at this time. After assigning the cookies to `this.context` (an instance of `BrowserContext`; as shown above), I use `const page = this.context.newPage()` and then use the `page` variable for my automation & browser navigation. 

I can verify during my test phase that the Playwright context object is aware of the cookies, but if I pause the automation after confirming the cookie presence in the Playwright context object, I cannnot see them in the browser that pops up.

**Comment by pavelfeldman** [comment] 2020-07-03 00:13
> I cannnot see them in the browser that pops up

Are you checking it in the DevTools on the exact page that your test opened? Sorry for asking all these questions, but the symptoms suggest that you open DevTools on another browser context that has no cookies, hence all the questions.

**Comment by mwallace72** [comment] 2020-07-07 17:12
> > I cannnot see them in the browser that pops up
> 
> Are you checking it in the DevTools on the exact page that your test opened? Sorry for asking all these questions, but the symptoms suggest that you open DevTools on another browser context that has no cookies, hence all the questions.

I believe it is the same browser context - the window that opens when the test process begins is the one I check the cookies on, by opening DevTools

**Comment by aslushnikov** [comment] 2020-07-07 23:59
@mwallace72 I spend some time trying to reproduce this with no luck.

Any chance you can come up with a repro that we can run locally to reproduce the behavior?

Here's what I tried:

```js
 const {chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({headless: false,});
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto("https://example.com");
  await context.addCookies([
    { name: 'cookie1', value: 'value1', url: 'https://example.com', },
    { name: 'cookie2', value: 'value2', url: 'https://example.com', },
  ]);
  // open devtools here and check cookies
})();
```

I ended up with cookies in the DevTools:

![image](https://user-images.githubusercontent.com/746130/86857301-17b91900-c073-11ea-98d2-ec080a3dfb95.png)

Same with firefox.

**Comment by mwallace72** [comment] 2020-07-08 13:36
Will work on this! @aslushnikov

**Comment by mwallace72** [comment] 2020-07-08 14:06
OK so I believe I can confirm now that what is truly happening is I am trying to set cookies for a different URL than the current (intentionally).
My test application runs at `http://localhost:3000`, and the cookies I need to set belong to a different domain. 
I can confirm that setting a meaningless cookie `{name: 'cookie1', value: 'value1', url: 'http://localhost:3000/'}` (belonging to the domain of the test application) _does_ show in the DevTools upon inspection.
Despite all this, the Playwright `context.cookies()` does have *all* cookies I need, I simply can't see the ones in DevTools that don't belong to the test app domain.

**Comment by aslushnikov** [comment] 2020-07-08 15:17
@mwallace72 ah, this explains it! 

> I can verify this by additionally setting a cookie {name: 'cookie1', value: 'value1', url: 'http://google.com/'} and this cookie does not show in DevTools.

DevTools only show cookies for the currently-open page, so only cookies for the particular URL. I *thought* there was an option to display all cookies for all URLs in DevTools, but I no longer can find one...

> Despite all this, the Playwright context.cookies() does have all cookies I need

Playwright cookies API work on the context level, so  that you can introspect all cookies in the context for all the URLs.
So it looks like Playwright is doing a good job here, but browsers devtools aren't there yet. 🤷‍♂️

**Closed** 2020-07-08 18:01 UTC

**Comment by Billy-** [comment] 2022-06-08 07:01
> DevTools only show cookies for the currently-open page, so only cookies for the particular URL

In the application I am currently working on, it is served from localhost but API calls are made to a different domain. I can see requests to those domains pick up an authentication cookie which is stored against that domain but these cookies are present on localhost but with the domain value matching the API server. I can see cookies for both localhost _and_ the API server when inspecting cookies on local host via dev tools.

I am trying to now add those cookies to the browser context in my playwright tests, but as the original issue here states, those cookies with a different domain do not appear when the localhost page loads. I do believe this is an issue, could we re-open this?

**Comment by bhargavcp** [comment] 2023-05-19 00:41
I am experiencing the same issue, as mentioned here by @Billy- . I don't see the cookies for a different domain under localhost. I then read @aslushnikov 's comment that maybe it's the browser not showing those cookies, but when inspecting the network request, I don't see those cookies being sent in the request.

**Comment by saewitz** [comment] 2024-01-06 08:43
This is probably not a playwright bug. Some browsers have a security feature to not allow setting a cookie for a third-party domain https://stackoverflow.com/questions/6761415/how-to-set-a-cookie-for-another-domain
