### ISSUE TITLE
[Question] Drag and drop to a non input file type element inside iframe

### ISSUE THREAD

**Issue by AshisRaj** [microsoft/playwright#15762] opened 2022-07-18 17:51 UTC
Hi, back again after resolving the issue https://github.com/microsoft/playwright/issues/15619.
Here is another automation use case for the application we are evaluating with Playwright.

I tried to find out the solution on internet, but many of them are either duplicate of issue as mentioned below or are just incomplete. I saw the solution provided here but could not figure out how to provide the complete selector string to the dispatchEvent function.

`await page.dispatchEvent('YOUR_TARGET_SELECTOR', 'drop', { dataTransfer });`

https://github.com/microsoft/playwright/issues/10667

I tried with my below code snippet but it did not work. It does not give me any error but nothing happened on the page.

![DragandDrop](https://user-images.githubusercontent.com/32839577/179572163-7db8f895-752d-4339-b4cf-8cf2d628c3dd.PNG)

```
<iframe id="legacy-app" src="//admin.xyz.asdf.com/xyz/zxy/12341a8ab651df98b842df40?vp=bulkproduct" data-test="legacy-app">
	<div class="dropzone single dropBox" __playwright_target__="after@call@28"></div>
</iframe>
```
```
    const dropBox = await page.frameLocator('[data-test="legacy-app"]').locator('[class="dropzone single dropBox"]');
    await expect(dropBox).toBeVisible();
    
    // Read your file into a buffer.
    const filePath ='./test-data/sheets/UU-24074-C202362.xlsx';
    const buffer = fs.readFileSync(filePath);

    // Create the DataTransfer and File
    const dataTransfer = await dropBox.evaluateHandle((data) => {
        const dt = new DataTransfer();
        // Convert the buffer to a hex array
        const file = new File([data.toString('hex')], 'UU-24074-C202362.xlsx', { type: 'application/xlsx' });
        dt.items.add(file);
        return dt;
    }, buffer);

    await dropBox.dispatchEvent('drop', { dataTransfer });

```

**Comment by dgozman** [comment] 2022-07-19 00:37
Most likely, the problem is that `buffer` is not transferred through the `evaluate` correctly. There is an issue #13364 that has the same cause.

Take a look at [this comment](https://github.com/microsoft/playwright/issues/13364#issuecomment-1156288428) for a manual workaround. Let me know if that works for you.

**Comment by AshisRaj** [comment] 2022-07-19 01:40
> 
Thanks. But the 1st problem for me is to how to pass on the selector as string here for an element which is inside an iframe.
as the dispatchEvent function takes selector as string only. 

`page.dispatchEvent(selector, 'drop', { dataTransfer });`

Is there a way that I can pass on selector as an object as I can only find the element with this code.

`const dropBox = await page.frameLocator('[data-test="legacy-app"]').locator('[class="dropzone single dropBox"]');`

**Comment by AshisRaj** [comment] 2022-07-19 02:08
Also, my current implementation is using `locator.evaluateHandle((data) {});` as below instead of `page..evaluateHandle((data) {});` I hope this is correct way to do so.

```
const dataTransfer = await dropBox.evaluateHandle((data) {

});
```

**Comment by AshisRaj** [comment] 2022-07-20 04:03
> dispatchEvent

No, you are reading correctly. I see the focus shifts to the drobox but nothing happens on UI and no error on terminal and in the html test report too. What else can I try to debug further?

**Comment by dgozman** [comment] 2022-07-20 15:52
Try using our [debug tools](https://playwright.dev/docs/debug). Alternatively, if you believe there might be a bug in Playwright, you can share a repro that we can run locally, and we'll take a look.

**Comment by AshisRaj** [comment] 2022-07-21 13:24
I will try with debug tools. Creating a repro will be challenging as it requires React code too to listen and handle the events.

**Comment by dgozman** [comment] 2022-07-24 19:58
@AshisRaj If you come up with a repro that we can run locally, please file a new issue with it and link to this one.

**Closed by dgozman** 2022-07-24 19:58 UTC
Labels: triaging

**Comment by danielmicko** [comment] 2024-03-06 12:15
Hey guys, is there any progress on this? I am trying to devise a solution to drag and drop video progress bar so I can skip the video to a certain point. The video player is in an iframe. Any ideas?
