### ISSUE TITLE
[Feature]: Ability to create a Playwright test runner instance for better control

### ISSUE THREAD

**Issue by sanjithkumar017** [microsoft/playwright#31659] opened 2024-07-12 11:26 UTC
### 🚀 Feature Request

Allow for creation of test runner with custom configuration. Similar to what Testcafe's `e [createTestCafe](https://testcafe.io/documentation/402662/reference/testcafe-api/global/createtestcafe)`  

### Motivation

This will allow us to move away from the common config and provider better developer control on the instantiation and lifecycle of the test.

**Comment by yury-s** [comment] 2024-07-12 16:23
Can you elaborate on the details of the use case that you want to address and what kind of API you have in mind?

**Comment by dgozman** [comment] 2024-07-16 13:11
This sounds like a duplicate of #7275, please continue the discussion there.

**Closed by dgozman** 2024-07-16 13:11 UTC
