### ISSUE TITLE
[Bug]: New install "Internal error: unable to connect to the test serverplaywright" 

### ISSUE THREAD

**Issue by mchequer** [microsoft/playwright#31277] opened 2024-06-12 13:29 UTC
### Version

1.41.1

### Steps to reproduce

playwright@1.0.0 C:\Code\playwright
+-- @playwright/test@1.44.1
`-- @types/node@20.14.2

1) Create a new folder
2) install the playwright extension
3) Add playwright to the project and i get the error in the file playwright.config.js 
[{
	"resource": "/c:/Code/playwright/playwright.config.js",
	"owner": "pw.testErrors.diagnostic",
	"severity": 8,
	"message": "Internal error: unable to connect to the test server",
	"source": "playwright",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]

### Expected behavior

installation works. Clearly it's some kind of issue with my environment, but i have no error messages or information to try to figure out why. Tried it on a new system install and no problem, so somehow my system is affecting the install. 

System is Windows 11, with MySQL, Visual Studio (C#) and a number of other products installed

### Actual behavior

[{
	"resource": "/c:/Code/playwright/playwright.config.js",
	"owner": "pw.testErrors.diagnostic",
	"severity": 8,
	"message": "Internal error: unable to connect to the test server",
	"source": "playwright",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]

### Environment

```shell
System is Windows 11, with MySQL, Visual Studio (C#) and a number of other products installed
```

**Comment by yury-s** [comment] 2024-06-12 16:06
Does it reproduce if you open VS Code in a project created via `npm init playwright new_project` ?

**Comment by mchequer** [comment] 2024-06-12 17:21
Same error. When I enter  "npm init playwright newplaywright" I am prompted to install  create-playwright (which i did). But i still get the same error.

[cid:d30be892-0435-4669-b914-ef3287fc327f]
________________________________

**Comment by yury-s** [comment] 2024-06-12 17:56
Hmm, this I can't reproduce. Just to double check, are you doing exact following steps?

1. `npm init playwright newplaywright`
2. `cd  newplaywright`
3. `code .`
4. Click on green triangle on one of the test's gutter to run it.

**Comment by mchequer** [comment] 2024-06-12 21:11
those commands produce the same error. On other machines it's fine, there is something about this machine and it's setup. It's used for a lot of other development things (Visual Code, MySQL +++ ), so probably something there is affecting it. I've checked event logs, rebooted, disabled all kinds of stuff, as much as i can to see what could be the issue. I will probably just reinstall the machine and start over.
Thank you for lookingBest,Mark

    On Wednesday, June 12, 2024 at 10:57:13 AM PDT, Yury Semikhatsky ***@***.***> wrote:  
 
 


Hmm, this I can't reproduce. Just to double check, are you doing exact following steps?
   
   - npm init playwright newplaywright
   - cd newplaywright
   - code .
   - Click on green triangle on one of the test's gutter to run it.

**Comment by yury-s** [comment] 2024-06-12 21:23
Closing this report for now. Feel free to file another issue if reinstalling doesn't help or you discover something that could help us reproduce it locally.

**Closed by yury-s** 2024-06-12 21:23 UTC

**Comment by 3cognito** [comment] 2024-06-22 10:19
Faced the same issue today: unresolved.

**Comment by kalmigs** [comment] 2024-06-22 18:49
Same here, new install and got this error

**Comment by eustachi0** [comment] 2024-06-24 13:58
I have encountered this issue on my Windows 10 pc. It works fine if you are using WSL. 
I have a laptop that runs Windows 11, VS Code 1.90.2 and WSL2 -> Playwright works fine.

I have a pc that runs Windows 10, VS Code 1.90.2 without WSL2, when I create a new fresh Playwright install, the playwright config file throws an error saying "unable to connect to the test server". This happens on any new projects.

**Comment by Ksingh22** [comment] 2024-06-28 02:30
I had the same issue. I renamed the file from Playwright.config.js to Playwright.configs.js and it worked. Not getting "Internal error: unable to connect to the test serverplaywright"

**Comment by kalmigs** [comment] 2024-06-28 14:02
Fixed my issue by using the latest node version (previously was on v20.6.0).

**Comment by kalmigs** [comment] 2024-06-28 14:05
> I had the same issue. I renamed the file from Playwright.config.js to Playwright.configs.js and it worked. Not getting "Internal error: unable to connect to the test serverplaywright"

This will not fix the issue, as playwright will not be able to see your config (which is the correct filename is `playwright.config.ts` or `playwright.config.js`.

Just checked, the `test tab` will not display your tests and will ignore your config with Playwright.**configs**.js

**Comment by danaoairuike** [comment] 2024-06-28 18:23
> I had the same issue. I renamed the file from Playwright.config.js to Playwright.configs.js and it worked. Not getting "Internal error: unable to connect to the test serverplaywright"

It works for me. But why ?

**Comment by Ksingh22** [comment] 2024-06-29 01:41
> > I had the same issue. I renamed the file from Playwright.config.js to Playwright.configs.js and it worked. Not getting "Internal error: unable to connect to the test serverplaywright"
> 
> It works for me. But why ?



> > I had the same issue. I renamed the file from Playwright.config.js to Playwright.configs.js and it worked. Not getting "Internal error: unable to connect to the test serverplaywright"
> 
> This will not fix the issue, as playwright will not be able to see your config (which the correct filename is `playwright.config.ts` or `playwright.config.js`.
> 
> Just checked, the `test tab` will not display your tests and will ignore your config with playwright.**configs**.js

I have another extension of test runner installed, so that's why test tab was not missing. However you are correct, I have updated the node version and that error is not happening. 
Thanks!

**Comment by raymondseahwc** [comment] 2024-08-19 09:45
Hi, may i check which node version you are on that resolve this issue? 

without having the need to rename the "playwright.config.ts" to "playwright.configs.ts"

**Comment by crixtm** [comment] 2024-08-22 13:23
> Fixed my issue by using the latest node version (previously was on v20.6.0).

This method fixed on my side properly also. I reproduced to switch back to 20.6.0 and it turned to be erroneous again

**Comment by crixtm** [comment] 2024-08-22 13:24
> Hi, may i check which node version you are on that resolve this issue?
> 
> without having the need to rename the "playwright.config.ts" to "playwright.configs.ts"

20.12.1

**Comment by Ksingh22** [comment] 2024-08-22 13:50
> Hi, may i check which node version you are on that resolve this issue?
> 
> without having the need to rename the "playwright.config.ts" to "playwright.configs.ts"

v22.3.0

**Comment by JonrGull** [comment] 2024-10-21 14:03
I hate to bring this up again but I can't figure this problem out. I am using node 23.0.0 and vite with React/T, and WSL2.

I still get  `Internal error: unable to connect to the test serverplaywright` in my config file.

**Comment by d-tsu** [comment] 2024-11-03 17:11
I encountered the same issue. I am using fnm and have Node.js v23.1.0 installed.

In my case, the issue was resolved when I uninstalled the older version of Node.js (v16.13.0) that had been installed using the .msi installer.

I hope this information is helpful!

**Comment by jeremysfrench** [comment] 2025-01-02 18:11
I encountered this same issue, banged my head against it for a week or more, and then finally accidentally discovered it was related to working in a symliinked directory.  Switching to the same project via it's fully qualified path solved the issue:  
[Related bug report](https://github.com/microsoft/playwright/issues/33317)
