### ISSUE TITLE
[BUG] install fail

### ISSUE THREAD

**Issue by bluelovers** [microsoft/playwright#1992] opened 2020-04-27 12:52 UTC
**Context:**
- Playwright Version: 0.15.0
- Operating System: windows 10
- Extra: 
  - nodejs 14.0.0
  - npm 6.14.4 
  - yarn 1.22.4

**Describe the bug**

install by npm/yarn both all failed, also try run `node install.js` for download but still lost files

file is missing

![image](https://user-images.githubusercontent.com/167966/80373880-5474d100-88c8-11ea-974a-a1549b2f64e5.png)

> Error: Failed to launch browser: Error: spawn node_modules\playwright\.local-browsers\chromium\chrome-win\chrome.exe ENOENT

**Comment by pavelfeldman** [comment] 2020-04-27 15:35
Looks like a duplicate of https://github.com/microsoft/playwright/issues/1988

**Closed by pavelfeldman** 2020-04-27 15:35 UTC
