### ISSUE TITLE
[Question] TypeError: the promise constructor cannot be invoked directly

### ISSUE THREAD

**Issue by nicoandmee** [microsoft/playwright#9782] opened 2021-10-26 11:29 UTC
I am working on a project that has overridden the global Promise to Bluebird's promise like this:
```js
Promise = require('bluebird');
```
It is currently using playwright@1.14.0 but I'd like to update it to the latest version. However, when I do this, I get a `TypeError: the promise constructor cannot be invoked directly` which I surmise is because of Bluebird (https://github.com/poppinss/indicative/issues/174). I'm curious what changed in the playwright release that would cause this? And is there a way to continue using Bluebird promise while still being able to use latest playwright?

**Comment by dgozman** [comment] 2021-10-31 18:28
Closing because we cannot reproduce the issue. Let us know if you have a repro script, and we'll take a look.

**Closed by dgozman** 2021-10-31 18:28 UTC
Labels: triaging

**Comment by kbrownlees** [comment] 2023-06-27 00:05
@dgozman I just hit this on our install. I can reproduce from node directly:

```
global.Promise = require('bluebird')
pc = require('playwright-core')
await pc.chromium.launch()
```

```
Uncaught:
browserType.launch: the promise constructor cannot be invoked directly

    See http://goo.gl/MqrFmX

    at REPL5:1:51
    at REPL5:2:4 {
  name: 'TypeError'
}
```

**Comment by kbrownlees** [comment] 2023-06-27 00:31
The culprit is `ManualPromise`, it would seem that bluebird doesn't like being extended like the native promise does.
