### ISSUE TITLE
[BUG] api doc for `browser.newContext` does not match the code

### ISSUE THREAD

**Issue by canstand** [microsoft/playwright#26456] opened 2023-08-14 04:55 UTC
### System info
- Playwright Version: [v1.37]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

According to https://github.com/microsoft/playwright/blob/04b71bf660dbd5c4259058bd3941dcf4c1686c77/packages/playwright-core/src/client/types.ts#L56, the optional parameter StorageState of `browser.newContext` uses `SetNetworkCookie`.
https://github.com/microsoft/playwright/blob/04b71bf660dbd5c4259058bd3941dcf4c1686c77/packages/protocol/src/protocol.yml#L922

 But https://github.com/microsoft/playwright/blob/04b71bf660dbd5c4259058bd3941dcf4c1686c77/docs/src/api/class-browser.md?plain=1#L278 link to 
https://github.com/microsoft/playwright/blob/04b71bf660dbd5c4259058bd3941dcf4c1686c77/docs/src/api/params.md?plain=1#L240, which refers to `NetworkCookie`.
https://github.com/microsoft/playwright/blob/04b71bf660dbd5c4259058bd3941dcf4c1686c77/packages/protocol/src/protocol.yml#L194

playwright-python follows the API doc to generate references to parameters [playwright/_impl/_browser.py](https://github.com/microsoft/playwright-python/blob/8838e31a6f4836c47416b1504a2cba1a48f6112d/playwright/_impl/_browser.py#L118C13-L118C13)
, does this cause an error?

**Comment by canstand** [comment] 2023-08-14 15:24
Just found this issue while working on playwright-go generated-structs, there is a difference in the structure of the `StorageState` type between the `nodejs`/`dotnet` client and the `python` client.

No error cases encountered.

The main difference is that `SetNetworkCookie` has an extra `url` field, maybe someone can investigate what it does.

**Comment by mxschmitt** [comment] 2023-08-14 15:32
Ah gotcha, if you set the `url` field, the domain and pathname gets automatically populated: https://playwright.dev/docs/api/class-browsercontext#browser-context-add-cookies-option-cookies

**Comment by canstand** [comment] 2023-08-14 15:52
Got it. It's just easier to construct input data so it doesn't lead to errors.

**Comment by mxschmitt** [comment] 2023-08-17 16:33
Closing then since its not a bug and working as intended.

**Closed by mxschmitt** 2023-08-17 16:33 UTC
Labels: triaging
