### ISSUE TITLE
[Question] Glue42 / Electron: Only first test passes.

### ISSUE THREAD

**Issue by charlotte-hayes** [microsoft/playwright#24247] opened 2023-07-15 10:36 UTC
Hi All, 

I am struggling to get my automated test cases to pass when trying to run them in sequence. All tests pass individually but, when run in sequence, only the first one passes with any subsequent ones failing with this message: _Error: electron.launch: Process failed to launch!_

I created a fixture, based on the Glue 42 test example, below:

```
import { test as base, expect } from "@playwright/test";
import { _electron as electron } from '@playwright/test';
import { envConfig } from '../envVars';
import { waitForAppToLoad } from "../uilities/helpers";

export const test = base.extend({
    electronApp: async ({ }, use) => {
        const electronApp = await electron.launch({
            executablePath: envConfig.gdExePath,
            cwd: envConfig.gdDir,
            env: { ...process.env, NODE_ENV: 'development' }
        })
        await use(electronApp)
    },

    abcFixture: async ({ }, use) => {
        const electronApp = await electron.launch({
            executablePath: envConfig.gdExePath,
            cwd: envConfig.gdDir,
            env: { ...process.env, NODE_ENV: 'development' }
        })
        const launcher = await waitForAppToLoad("glue42-launchpad", electronApp);
        await launcher.waitForSelector('.form-control')
        await launcher.type(`.form-control`, `abc app`);
        await launcher.click(`data-testid=rendered-app >> nth=0 `)
        const xx = await waitForAppToLoad('abcappi', electronApp)
        const appName = await xx.title()
        expect(appName).toBe('abcapp)
        await use(xx)
    }
});
export { expect } from '@playwright/test';
```

An example of the tests using it is here:

```

test('launch abc app from the launchpad and verify that it has loaded correctly', async ({ electronApp }) => {
  const launcher = await waitForAppToLoad("glue42-launchpad", electronApp);
  await launcher.waitForSelector('.form-control')
  await launcher.type(`.form-control`, `abc app`);
  await launcher.click(`data-testid=rendered-app >> nth=0 `)
  const abcapp = await waitForAppToLoad('abcapp', electronApp);
  const appName = await abcapp.title()
  expect(appName).toBe('abc app')
});

test('verify that headers are displayed in the correct order in appabc', async ({ abcFixture,page }) => {
  const abcPage = new ABCPageObject(abcFixture);
  await expect(abcPage.xxx_header).toHaveText('FOO BAR');
});

```

It goes without saying that the app names have been anonymised so please ignore any that don't match! I am wondering if this is because the application has not fully closed between test one and test two running?

I would really appreciate some help!

**Comment by mxschmitt** [comment] 2023-07-15 12:10
I see that you are not closing your app, put an `await electronApp.close()` after your `await use(electronApp)`. This will then execute once the test has finished aka. the fixture will teardown. That might be the cause.

(General feedback for the rest but not related to that, I'd recommend to use [web-first selectors](https://playwright.dev/docs/test-assertions) which will automatically retry etc. in particular toHaveTitle or no need for waitForSelector since click waits)

**Comment by charlotte-hayes** [comment] 2023-07-17 08:45
I have amended the fixture as follows but an 'are you sure you want to close the app' dialog is causing it to hang on the electronApp.close() line and time out. I think I might be impacted by this: https://github.com/microsoft/playwright/issues/21432
````
export const test = base.extend({
    electronApp: async ({ }, use) => {
        const electronApp = await electron.launch({
            executablePath: envConfig.gdExePath,
            cwd: envConfig.gdDir,
        })
        await use(electronApp)
        await electronApp.close();

        if (appProcess){
            await new  Promise<void>( resolve => {
                appProcess!.on('exit', () => {
                    appProcess = null;
                    resolve();
                });
                appProcess!.kill('SIGTERM');
            });
        }
    },`

I tried listening for an event and dismissing the dialog but that didn't work.

**Comment by aslushnikov** [comment] 2023-07-18 11:38
@charlotte-hayes if you can't gracefully close your electron application, you can always fore kill [its process](https://playwright.dev/docs/api/class-electronapplication#electron-application-process) instead.

However, I'd recommend adding hooks to gracefully close your application under test. Hope this helps!

**Closed by aslushnikov** 2023-07-18 11:38 UTC
