### ISSUE TITLE
[Feature] please help add zoom in and zoom out feature in beforeAll and beforeEach hook 

### ISSUE THREAD

**Issue by ajaygoutham1995** [microsoft/playwright#23357] opened 2023-05-30 06:13 UTC
[Feature] please help add zoom in and zoom out feature in beforeAll and beforeEach hook 

Observation : as per the observation at this point of time we could able to zoom in and out on particular page but i could not find any option to set the zoom level of browser in before hooks, if possible please help provide the option 

it would be more helpful

**Comment by aslushnikov** [comment] 2023-05-30 23:29
Dupe of https://github.com/microsoft/playwright/issues/2497

**Closed by aslushnikov** 2023-05-30 23:29 UTC

**Comment by ajaygoutham1995** [comment] 2023-06-01 04:02
HI @aslushnikov 
any update on this feature request like when this can be done ?

**Comment by aslushnikov** [comment] 2023-06-01 20:31
@ajaygoutham1995 there's no ETA on it, and it's not in the works currently.
