### ISSUE TITLE
[BUG] ElementHandle API: dispatcher[method] is not a function

### ISSUE THREAD

**Issue by honglax** [microsoft/playwright#4985] opened 2021-01-12 07:24 UTC
**Context:**
- Playwright Version: 1.7.1
- Operating System: MacOS 10.15 Catalina
- Node.js version: 12.18.4
- Browser: Chromium
- Extra: None

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch()
  const page = await browser.newPage()
  const URL = 'https://the-internet.herokuapp.com/key_presses'
  await page.goto(URL)

  const handles = await page.evaluateHandle(() => document.querySelectorAll('input'))

  if (handles) {
    const properties = await handles.getProperties()
    for (const property of properties.values()) {
      const elementHandle = property.asElement()
      if (elementHandle) {
        await elementHandle.focus()
      }
    }
    handles.dispose()
  }

  await browser.close()
})();
```

**Describe the bug**
When I get the array of ElementHandle by `page.evaluateHandle()` and call any API of each ElementHandle (focus() for an example), an error `elementHandle.focus(): dispatcher[method] is not a function` is thrown. Reproducible example here: [https://try.playwright.tech/?s=i1th62g](https://try.playwright.tech/?s=i1th62g)

**Comment by mxschmitt** [comment] 2021-01-12 11:04
It's probably a duplicate of #4872 and is already fixed. You can try it out locally with `npm install playwright@next`, Thanks!

**Comment by honglax** [comment] 2021-01-12 11:57
It works with `playwright@next`. Thank you for your information.

**Closed** 2021-01-12 12:00 UTC
