### ISSUE TITLE
[BUG]Wait for navigation with url and wait until network idle fail to respond and time out

### ISSUE THREAD

**Issue by vrknetha** [microsoft/playwright#2526] opened 2020-06-10 15:38 UTC
**Context:**
- Playwright Version: [1.0.2]
- Operating System: [Windows]
- Node version: [12]
- Browser: [Chromium]
- Extra: [Jest]

****

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
await this.page.waitForNavigation({
			url: 'https://localhost:4200/group-admin/settings#moderators',
			timeout: 10000,
			waitUntil: 'networkidle'
		});
```

**Describe the bug**

Our application has a lot of page redirections and I made this method for the page to end for navigation on that page with no network calls in the background. It fails to respond even after the page navigation and no network calls in the background.

**Comment by vrknetha** [comment] 2020-06-15 07:48
Thank you. I will implement that

**Comment by vrknetha** [comment] 2020-06-30 11:03
![image](https://user-images.githubusercontent.com/20596261/86118950-3bb6b080-baef-11ea-910d-066da544691d.png)

Check the above screenshot. As waiting for navigation times out all the time. I have used a try-catch and print the URL. The URL is the same but method unable to detect it.

**Comment by aslushnikov** [comment] 2020-06-30 18:32
@vrknetha would you mind sharing a script that we can use to reproduce it locally?

**Comment by vrknetha** [comment] 2020-06-30 18:39
I will share the repo.

**Comment by aslushnikov** [comment] 2020-08-21 07:10
(looks like this has stalled - closing for now. Summer cleanup!)

**Closed by aslushnikov** 2020-08-21 07:10 UTC

**Comment by romainbessugesmeusy** [comment] 2022-04-15 17:57
We had the same problem and it was caused by trailing slashes in the urls : 
Current page was `https://google.com` and we tried to do `https://google.com/` (note the slash at the end of the latter)
Hope it helps
