### ISSUE TITLE
[Feature] Add support for --allow-releaseinfo-change flag or the option to skip apt-get update

### ISSUE THREAD

**Issue by enagy27** [microsoft/playwright#28298] opened 2023-11-22 19:12 UTC
## System info
Playwright Version: [v1.40]
Operating System: [Ubuntu]
Browser: [Chromium]
Other info: Running on a self-hosted agent

## Context
My team and I use self-hosted agents with our own docker image in order to run Playwright tests. I switched over to these recently from Github Actions because most of our build infrastructure is on CircleCI running on these self-hosted machines.

In this process I found that I needed to update our image because of the `apt-get update` performed during Playwright browser installation which surfaced a mismatch between release info. I then attempted to point Playwright to our existing Chromium installation but luckily saw the warnings in the docs against doing non-hermetic browser installations.

I can, of course, update our image and this is what I'm currently doing to fix the issue. However, I'm wondering if it's appropriate to also offer the option to do either of the following:

- Skip updating and use the current agent info
- Apply the `--allow-releaseinfo-change` flag

Any guidance is appreciated! Thanks

**Comment by enagy27** [comment] 2023-11-22 19:12
Relates to: https://github.com/microsoft/playwright/issues/28251

**Comment by yury-s** [comment] 2023-11-22 19:35
> In this process I found that I needed to update our image because of the `apt-get update` performed during Playwright browser installation which surfaced a mismatch between release info.

`apt-get update` is only performed if you call install with `--with-deps` option. If you omit that you won't see the error. Will that work for you?

> I can, of course, update our image and this is what I'm currently doing to fix the issue.

This sounds like right approach. Also, if you build your own image you can bake the browsers and their dependencies into it once similar to how Playwright does it with the official [docker images](https://playwright.dev/docs/docker). I assume due to some requirements you cannot use our docker images that already have all browser dependencies preinstalled.

> However, I'm wondering if it's appropriate to also offer the option to do either of the following:
> Skip updating and use the current agent info

If you have playwright browsers preinstalled you should skip the update step, otherwise I don't see how you are going to run the tests without browsers fully installed. Cab you elaborate?

> Apply the --allow-releaseinfo-change flag

What would the option do? The error was thrown by `apt` due to a temporary mirror problem. It may occur for other reasons too, such network problems or remote repository misconfiguration.

**Comment by mxschmitt** [comment] 2023-11-27 17:45
Closing as per above since this is not actionable by us. The issue is about the apt mirror which behaves incorrectly.

**Closed by mxschmitt** 2023-11-27 17:45 UTC
Labels: triaging

**Comment by enagy27** [comment] 2023-11-27 18:58
Thanks for getting back! As evidenced by my ticket, I'm outside of my comfort zone on this one and not quite sure what does what. That is very helpful advice though with avoiding `--with-deps`— I'll try both updating my image and possibly switching away from using that flag and see where I can get to. Appreciate the guidance!
