### ISSUE TITLE
[firefox] › page/page-screenshot.spec.ts:279:5 › page screenshot › should capture canvas changes 

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#20825] opened 2023-02-10 18:08 UTC
https://github.com/microsoft/playwright/actions/runs/4140938840/jobs/7160064946

**Comment by aslushnikov** [comment] 2023-02-13 18:37
Dupe of https://github.com/microsoft/playwright/issues/20522

**Closed by aslushnikov** 2023-02-13 18:37 UTC
Labels: v1.31
