### ISSUE TITLE
[Question] How to record video of tests with custom file name as test method name in playwright java?

### ISSUE THREAD

**Issue by rajeevdixit05** [microsoft/playwright#19962] opened 2023-01-09 15:54 UTC
**My requirement is-**

1. Record video of test with testMethod name
2. Only keep video of the failed tests
3. Retry with video for the failed tests in Playwright java sdk

**Comment by aslushnikov** [comment] 2023-01-10 04:49
Closing as a dupe of https://github.com/microsoft/playwright/issues/19963

**Closed by aslushnikov** 2023-01-10 04:49 UTC
