### ISSUE TITLE
Type/Fill Randomly Freezing in GitHub Actions

### ISSUE THREAD

**Issue by Wakeful-Cloud** [microsoft/playwright#24061] opened 2023-07-06 05:03 UTC
### System info
- Playwright Version: `1.35.1`
- Operating System: GitHub Actions runner [Ubuntu 22.04](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230625.1)
- Browser: Chromium `115.0.5790.24` (playwright build `v1067`)
- Other info:
  - Mantine: `6.0.14`

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Config file**

```ts
import {Config, defineConfig} from "@playwright/test";
import {dirname, join} from "node:path";
import {fileURLToPath} from "node:URL";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CI = process.env.CI !== undefined;

const reportsPath = join(__dirname, "tests/playwright/reports");
const reporters: Config["reporter"] = [
  [
    "html",
    {
      open: "never",
      outputFolder: join(reportsPath, "html")
    }
  ],
  ["list"]

];

if (CI) {
  reporters.push(["github"]);
}

export default defineConfig({
  projects: [
    {
      name: "tests",
      testDir: join(__dirname, "tests/playwright/tests"),
      testMatch: "**/*.spec.ts"
    }
  ],
  outputDir: join(__dirname, "tests/playwright/output"),
  use: {
    video: "on",
    trace: "on"
  },
  timeout: 1000 * 60 * 5,
  //CI will be true
  maxFailures: CI ? 1 : 0,
  reporter: reporters,
  retries: CI ? 2 : 0,
  workers: CI ? 8 : 1
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  //...

  /* Note that running with force: true seems to slightly decrease the frequency of the issue,
  but it still occurs >50% of the time. The issue also occurs with the `.type` method (at about
  the same frequency as the stock `.fill` method, like below). */
  await page.getByLabel("Email").fill("beta@example.com");
  await page.getByLabel("Password").first().fill("[REDACTED]");
  await page.getByRole("button", {
    name: /Log in|Sign up/
  }).click();

  //...
});
```

**React Component**

```tsx
//Based on https://mantine.dev/form/use-form/#getinputprops
const form = useForm({
  initialValues: {
    email: "",
    password: "",
    confirmPassword: "",
    terms: false
  },
  clearInputErrorOnChange: false,
  validate: //Validation logic is ran immediately after any input
});

//...

<TextInput
  {...form.getInputProps("email")}
  icon={<IconMail />}
  label="Email"
  placeholder="example@example.com"
  radius="md"
  type="email"
  withAsterisk
/>
<PasswordInput
  icon={<IconKey />}
  label="Password"
  radius="md"
  {...form.getInputProps("password")}
  visibilityToggleIcon={visibilityToggle}
  withAsterisk
/>

//...
```

**Steps**

- Run the tests in GitHub Actions

**Expected**

- Playwright reliably types into the input fields (See the screen recordings)

**Actual**

- Playwright non-deterministically fails to type into the input fields and the test times out
  - Occurs <5% of the time on my computer (Also Ubuntu 22.04), even when I manually set `CI` to `true` or when I run in [Act](https://github.com/nektos/act)
  - Occurs >80% of the time in GitHub Actions
  - Does not consistently freeze up at the same place in the email/password input

**Logs**

```
locator.type: Target closed
=========================== logs ===========================
waiting for getByLabel('Email')
  locator resolved to <input value="" type="email" aria-invalid="false" data-…/>
elementHandle.type("beta@example.com")
============================================================
```
*Note: this is for `fail-1`, with `type`.*

---

```
locator.fill: Target page, context or browser has been closed
```
*Note: this is for `fail-2` with `fill`.*

---

```
locator.fill: Target closed
=========================== logs ===========================
waiting for getByLabel('Email')
  locator resolved to <input value="" type="email" aria-invalid="false" data-…/>
elementHandle.fill("beta@example.com")
  waiting for element to be visible, enabled and editable
    forcing action
  element is visible, enabled and editable
============================================================
```
*Note: this is for `fail-3`, with `force: true`.*

**Screen Recordings**
https://github.com/microsoft/playwright/assets/38930607/039da15f-4fb6-429b-91b0-426a41706f00 (Fail 1)
https://github.com/microsoft/playwright/assets/38930607/a6a76fa1-3a47-4d76-b9a6-b46e8e474158 (Fail 2)
https://github.com/microsoft/playwright/assets/38930607/f6b4a7a8-12d0-4764-bb40-86554a5b43cb (Fail 3)
https://github.com/microsoft/playwright/assets/38930607/5560b607-9708-455e-80a8-84ad9be2689f (Pass)

**Comment by pavelfeldman** [comment] 2023-07-06 19:35
The video suggests that you are entering an infinite update loop in your component, I'd recommend opening DevTools and hitting Pause or staring the timeline profiler when that happens.

**Comment by Wakeful-Cloud** [comment] 2023-07-07 04:41
Thanks for your response! While I wasn't able to attach a debugger given the nature of GitHub actions, I did insert a `console.log` in every function in the React component and didn't see any loops. I also tried `type` with a `100 ms` delay and it still didn't pass. Is there a way to view what specific conditions (on the element) Playwright/Chromium was expecting/waiting for?

**Comment by pavelfeldman** [comment] 2023-07-08 17:10
https://playwright.dev/docs/debug#trace-viewer would be the easiest given that it does not reproduce every time.

**Comment by pavelfeldman** [comment] 2023-07-08 17:11
If the page is live and typing stops half way, it could also be due to a component update the steals the focus. In either case, it is likely that this would happen to the real user as well.

**Comment by Wakeful-Cloud** [comment] 2023-07-19 05:08
Apologies for the delay - the above logs came from the trace viewer and there wasn't much else in them. I also added a `setInterval` to log the `document.activeElement` and the loop just stops when Playwright stops typing. Is there anything that would cause the browser to spontaneously freeze up?

**Comment by aslushnikov** [comment] 2023-07-19 13:12
@Wakeful-Cloud it looks like the best way forward here would be for us to be able to reproduce this behavior locally. Any chance you can build a repro for us?

**Comment by Wakeful-Cloud** [comment] 2023-07-20 01:43
@aslushnikov I'll see what I can do

**Comment by aslushnikov** [comment] 2023-07-20 05:38
@Wakeful-Cloud let me close this for now. Please, do not hesitate to file a new issue with a repro once you have one!

**Closed by aslushnikov** 2023-07-20 05:38 UTC
Labels: triaging
