### ISSUE TITLE
[BUG] Display contents makes element not visible

### ISSUE THREAD

**Issue by gamesterr** [microsoft/playwright#15034] opened 2022-06-22 09:20 UTC
**Context:**
- Playwright Version: 1.22.2
- Operating System: Mac
- Node.js version: v16.13.0
- Browser: Chromium

When an element has `display: contents` in CSS, playwright doesn't interact with the element.

Example page:
```html
<div>
  Example text, and button here:
  <button style="display: contents">click me</button>
</div>
```

Playwright code:
```js
await page.locator('button:has-text("click me")').click();
```

Actual result:
Element is not visible by the playwright, and the test fails.

**Comment by ville-nvt** [comment] 2022-06-22 12:55
```
<div>
  Example text, and button here:
  <button style="display: contents">click me</button>
</div>

await page.locator('button:has-text("login")').click();
```

html doesn't seem to contain button with text login. Either change button from "click me" to "login" or change locator to page.locator('button:has-text("click me")')

**Comment by gamesterr** [comment] 2022-06-22 13:03
Yeah, that's my mistake in a bug report, because I referred to my test, not this example
It's `page.locator('button:has-text("click me")')` not working in this case.
Updated issue

**Comment by mxschmitt** [comment] 2022-06-23 15:37
I was able to repro:

```js
// @ts-check
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({
    devtools: true,
  });
  // Create pages, interact with UI elements, assert values
  const page = await browser.newPage();
  await page.setContent(`
  <div>
    Example text, and button here:
    <button style="display: contents">click me</button>
  </div>`);
  await page.locator('button:has-text("click me")').click({
    timeout: 0,
  });
  await browser.close();
})();
```

I found two issues:

a) https://github.com/microsoft/playwright/blob/3dfecff2d530f84f8c2927322acc7f7f4809f5ed/packages/playwright-core/src/server/dom.ts#L414-L417
this can never be true.
b) https://github.com/microsoft/playwright/blob/3dfecff2d530f84f8c2927322acc7f7f4809f5ed/packages/playwright-core/src/server/dom.ts#L421-L423 this returns `'error:notvisible'`.

seems indeed a Playwright issue!

**Comment by dgozman** [comment] 2022-08-08 23:05
Should be fixed in the next release with #16356.

**Closed by dgozman** 2022-08-08 23:05 UTC
Labels: v1.25

**Comment by mnataraj17** [comment] 2022-11-18 14:00
Hi all, element hidden error showing up when **display: block** as well. 
Any workarounds for this? 
Thanks!

**Comment by olivierbeaulieu** [comment] 2023-03-28 17:33
I believe there is a regression on this bug in Playwright 1.32.0.

I'm running into this bug, which I'm not able to reproduce with the same code in 1.29.0

**Comment by dgozman** [comment] 2023-03-28 17:58
@olivierbeaulieu Could you please file a new issue by filling in the "Bug Report" template?

**Comment by davidbarton** [comment] 2023-06-05 13:47
Reported here https://github.com/microsoft/playwright/issues/23521
