### ISSUE TITLE
[BUG] browserType.launch: Timeout 30000ms exceeded

### ISSUE THREAD

**Issue by mohitkhatri88** [microsoft/playwright#16110] opened 2022-08-01 19:21 UTC
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.24.1
- Operating System: [e.g. Windows, Linux or Mac] Ubuntu 22.04
- Node.js version: [e.g. 12.22, 14.6] 16.15.1
- Browser: [e.g. All, Chromium, Firefox, WebKit] Webkit
- Extra: [any specific details about your environment] I am running a ubuntu 22 docker image and have playwright and nodejs installed. I am able to launch chrome browser but launching webkit constantly fails.

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:
```typescript
import { chromium, webkit, firefox, Browser, LaunchOptions, BrowserContext } from 'playwright';

let browserLaunchOptions = {
      headless: false,
      slowMo:  0,
      timeout: 30 * 1000
    };
let browserContext = await webkit.launch(browserLaunchOptions);
```

**Describe the bug**
My environment: docker image(ubuntu 22.04) running playwright(v1.24.1) and nodejs(16.15.1). I am having trouble running tests against webkit. It fails each time with the following error:

```
browserType.launch: Timeout 30000ms exceeded.
=========================== logs ===========================
<launching> /home/<username>/.cache/ms-playwright/webkit-1683/pw_run.sh --inspector-pipe --headless --no-startup-window
<launched> pid=25328
============================================================
browserType.launch: Timeout 30000ms exceeded.
=========================== logs ===========================
<launching> /home/<username>/.cache/ms-playwright/webkit-1683/pw_run.sh --inspector-pipe --headless --no-startup-window
<launched> pid=25328
```

Add any other details about the problem here.

**Comment by mxschmitt** [comment] 2022-08-01 20:25
Most likely you don't have the Playwright [operating system dependencies](https://playwright.dev/docs/cli#install-browsers) installed. We recommend if you use Docker, to use the [official image](https://playwright.dev/docs/docker) as well, which is tested and guaranteed to work.

**Comment by mohitkhatri88** [comment] 2022-08-01 20:59
Let me confirm.

**Comment by jetwiwo** [comment] 2022-08-02 02:55
I am experience a similar issue, but ONLY when running in GitHub Actions. It works fine when running inside Docker Desktop on Windows 10.

https://github.com/jetwiwo/playwright-jammy-webkit-freeze/actions/runs/2779274141 reproduces this issue using the official Docker image. It works fine in the focal image, but not in the jammy image.

Also note that when I reproduce this issue Playwright never times out on its own. If I did not add a timeout on the GitHub Action, it would keep running forever.

**Comment by mxschmitt** [comment] 2022-08-04 08:24
Did you install the dependencies via `npx playwright install --with-deps`?

@jetwiwo please file a separate issue.

**Comment by jetwiwo** [comment] 2022-08-05 01:26
Created https://github.com/microsoft/playwright/issues/16279

**Comment by mxschmitt** [comment] 2022-08-05 07:31
@mohitkhatri88 what is your host operating system? Is it ubuntu 20? If so, then its most likely a duplicate of https://github.com/microsoft/playwright/issues/15764.

**Comment by rwoll** [comment] 2022-08-11 20:47
Closing as part of triage—please re-file if this is still an issue. We recently released an official jammy Docker image. However, for now, it must be run on an Ubuntu Jammy host. Follow https://github.com/microsoft/playwright/issues/15764 for updates.

**Closed by rwoll** 2022-08-11 20:47 UTC
Labels: triaging
