### ISSUE TITLE
Issue with Playwright: Scroll Function Behaving Unexpectedly

### ISSUE THREAD

**Issue by carolinapanther1** [microsoft/playwright#27223] opened 2023-09-21 04:13 UTC
I'm using Playwright for automated testing, and I have a function scrollDownAndUpOnboarding designed to scroll down and then up on a web page. However, it seems to scroll down even when there's no scrollbar present on the page. Assertions within the function also pass regardless of the scrollbar's presence.

My goal is to evaluate scrolling behavior only when a scrollbar exists. How can I modify my code to achieve this effectively?

Any insights or suggestions would be appreciated.

Environment Details:

Playwright Version: v1.37
Operating System: Windows 11
Browser: Chromium

The function I'm using:

```
async scrollDownAndUpOnboarding() {
    // Get the initial vertical scroll position
    const initialScrollY = await this.page.evaluate(() => {
      return window.scrollY;
    });
    // Scroll to the bottom of the page
    await this.page.evaluate(() => {
      window.scrollTo(15, document.body.scrollHeight);
    });
    // Wait for a brief moment to allow the scrolling to take effect
    await this.page.waitForTimeout(1000); // Adjust the delay as needed
    // Check if the element is visible after scrolling down
    const isVisibleAfterScrollDown = await this.membershipLabel.isVisible();
    if (isVisibleAfterScrollDown) {
      console.log('Membership label is visible after scrolling down.');
    } else {
      console.log('Membership label is not visible after scrolling down.');
    }
    // Scroll back up to the top of the page
    await this.page.evaluate(() => {
      window.scrollTo(0, 40);
    });
    // Wait for a brief moment to allow scrolling to take effect
    await this.page.waitForTimeout(1000); // Adjust the delay as needed
  }
```

**Comment by yury-s** [comment] 2023-09-26 01:15
Playwright just evaluates the script and scrolls the page the same way as its own javascript could do, which means the content is scrollable and the user would be able to scroll it too (e.g. with mouse wheel) even if the scrollbars are hidden. Detecting if a scrollbar is visible is outside of playwright's scope, you can try searching stackoverflow.com for possible solutions.

Closing as this is working as intended.

**Closed by yury-s** 2023-09-26 01:15 UTC
