### ISSUE TITLE
[BUG] Trace Viewer cannot be visited as a service

### ISSUE THREAD

**Issue by jiawen94** [microsoft/playwright#27771] opened 2023-10-24 09:45 UTC
### System info
- Playwright Version: [v1.36.0]
- Operating System: [Windows 11,Debian 11]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [yes ] I provided exact source code that allows reproducing the issue locally.

1.  My service ip` 192.168.80.93`
run trace viewer in my serivce
```
root@performance:~# playwright show-trace  -p 15000 -h 0.0.0.0

Listening on http://0.0.0.0:15000
```

2. Use my PC,go to `192.168.80.93:15000`, empty
![image](https://github.com/microsoft/playwright/assets/29114225/8e109a65-19a4-4257-be0f-5975521207f0)

but I can visit this port via` localhost:15000`  locally

**Expected**
192.168.80.93:15000 should be like
![image](https://github.com/microsoft/playwright/assets/29114225/342ae5fd-7b2a-4da3-a6c2-d2fb085a4765)

**Actual**
website is empty

![image](https://github.com/microsoft/playwright/assets/29114225/586b5831-4fbf-4574-a242-96692de77af4)

**Comment by mxschmitt** [comment] 2023-10-24 10:18
Could you go to the Console tab? If the Service Worker is not able to register successfully, then its a duplicate of https://github.com/microsoft/playwright/issues/27655#issuecomment-1766826632.

**Comment by jiawen94** [comment] 2023-10-24 15:19
> Could you go to the Console tab? If the Service Worker is not able to register successfully, then its a duplicate of [#27655 (comment)](https://github.com/microsoft/playwright/issues/27655#issuecomment-1766826632).

It seems to be the same problem.Maybe it should be visited over HTTPS?
error log:

<img width="743" alt="2023-10-24 23 13 43" src="https://github.com/microsoft/playwright/assets/29114225/cfe98fff-9354-45c0-8599-ddeee1ff7abe">

 My environment is intranet. https It costs more. Is there any way to access it directly via http?

**Comment by jiawen94** [comment] 2023-10-24 16:09
I'm using playwright python version.How to edit file in order to ignore this http error?

**Comment by yury-s** [comment] 2023-10-24 16:11
> It seems to be the same problem.Maybe it should be visited over HTTPS?

Yes, if it's not local host, you need to use HTTPS. According [to MDN](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API): "Service workers only run over HTTPS, for security reasons. ".

> My environment is intranet. https It costs more. Is there any way to access it directly via http?

Only workaround is to run it from localhost.

**Closed by yury-s** 2023-10-24 16:11 UTC
