### ISSUE TITLE
[BUG] filechooser not being intercepted when the a new url is opened in the page

### ISSUE THREAD

**Issue by niranjan94** [microsoft/playwright#11375] opened 2022-01-13 12:20 UTC
**Context:**
- Playwright Version: `1.17.2`
- Operating System: Mac
- Node.js version: `16.13.0`
- Browser: Chromium & WebKit

**Code Snippet**

```typescript
import { chromium } from 'playwright';

async function main() {
  const browser = await chromium.launch({
    headless: false,
  });
  const context = await browser.newContext({});
  const page = await context.newPage();
  page.on('filechooser', (fileChooser) => {
    console.log('file chooser has been triggered');
    fileChooser.setFiles([]);
  });
  await page.goto('https://www.w3schools.com/howto/howto_html_file_upload_button.asp');
  await page.waitForLoadState('load');
  await page.goto('https://uppy.io/examples/xhrupload/');
}

main();
```

**Describe the bug**

- The `filechooser` event no longer works once the page is navigated away from the initially loaded page. 
	  - On the first w3schools page, the file-chooser is intercepted correctly.
	  - But once we navigate away from it, no other file choosers are intercepted.
- This issue seems to be only on chrome & webkit. Unable to reproduce it on Firefox.

**Comment by niranjan94** [comment] 2022-01-13 16:58
**Update:**

I'm able to make it work by `setFileChooserInterceptedNoReply` on the private channel on any navigation within the page.

```typescript
page.on('framenavigated', async (frame) => {
	page._channel.setFileChooserInterceptedNoReply({ intercepted: true });
});
```

But, I'd say this isn't ideal as I'm having to use a private API.

**Comment by yury-s** [comment] 2022-01-15 00:32
Chromium fix upstream: https://chromium-review.googlesource.com/c/chromium/src/+/3390638

**Comment by yury-s** [comment] 2022-01-26 19:17
> Chromium fix upstream: https://chromium-review.googlesource.com/c/chromium/src/+/3390638

This has been rolled to playwright now meaning that the problem is fixed in the tip-of-tree version. I'm going to close this bug but it will take some time for this change to reach Chrome beta and stable.

**Closed** 2022-01-26 20:39 UTC
Labels: v1.19

**Comment by niranjan94** [comment] 2022-01-27 12:46
Thanks for the quick resolution @yury-s 😄
