### ISSUE TITLE
[Feature]: Handle browser tabs/windows navigations

### ISSUE THREAD

**Issue by sudgarre** [microsoft/playwright#33505] opened 2024-11-08 07:25 UTC
### 🚀 Feature Request

We need to have a option do the following

1. Get the current active tab in browserContext
2. Have option to switch between tabs based on the URLs/reference. 
3. Close all tabs except active tab so that it is easy to automate tests where 

### Motivation

Many websites have links where clicking on icons, hyperlinks take us to new tabs & handling them in test automation is a need

**Comment by yury-s** [comment] 2024-11-08 16:49
> 1. Get the current active tab in browserContext

There is no such notion in Playwright as 'active tab', every page behaves as if it was a foreground page by design. Your testing code can chose which page to consider "active" there are no constraints on that. See also somewhat related issue: https://github.com/microsoft/playwright/issues/3570

> 3. Have option to switch between tabs based on the URLs/reference.

Same as above, you can iterate over [pages](https://playwright.dev/docs/api/class-browsercontext#browser-context-pages) in the context and do what you want based on [page.url()](https://playwright.dev/docs/api/class-page#page-url).

> 5. Close all tabs except active tab so that it is easy to automate tests where

You can iterate over [context.pages](https://playwright.dev/docs/api/class-browsercontext#browser-context-pages) and close some of them as you go.

> Many websites have links where clicking on icons, hyperlinks take us to new tabs & handling them in test automation is a need

Each new page is reported via ["page"](https://playwright.dev/docs/api/class-browsercontext#browser-context-event-page) event on the context and "popup" event on the parent page. See [this doc](https://playwright.dev/docs/pages#handling-popups).

Closing this issue as not planned.

**Closed by yury-s** 2024-11-08 16:49 UTC
