### ISSUE TITLE
[BUG] Invalid execution of class inheritance by Test runner

### ISSUE THREAD

**Issue by J-Sek** [microsoft/playwright#21119] opened 2023-02-22 22:49 UTC
**Context:**
- Playwright Version: 1.31.0
- Operating System: Linux
- Node.js version: 16.17.0
- Browser: Chromium

**Command**: `playwright test`

**Code Snippet**

```ts
import { test, expect } from "@playwright/test";

interface IModel {
  id: number;
}

class Model implements IModel {
  id!: number;

  constructor(data?: IModel) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }
}

interface IDemoA {
  id: number;
  name: string | null;
}

class DemoA extends Model implements IDemoA {
  name!: string | null;

  constructor(data?: IDemoA) {
    super(data);
  }
}

test("Minimal repro", () => {
  const a = new DemoA({
    id: 5,
    name: "My name",
  });

  console.log(a); // DemoA { id: 5, name: undefined }
  expect(a.name).toBe("My name");
});
```

**Describe the bug**

Code above consists mostly of classes and interfaces generated by NSwag. Wherever is `extends` the fields are set on `this` in `super` but are not exposed after we exit `Model` constructor.

This is especially weird because `ts-node`, TS REPL (and `node` for compiled JavaScript code) are executing the code without issues. The `a.name` contains expected value.

**Comment by yury-s** [comment] 2023-02-22 23:29
I can reproduce it.

**Comment by yury-s** [comment] 2023-02-22 23:35
Playwright transforms DemoA into this:
```js
class DemoA extends Model {
  constructor(data) {
    super(data);
    this.name = void 0;
  }
}
```

**Comment by J-Sek** [comment] 2023-02-23 08:55
@yury-s My tsconfig.json is configured for `"target": "es2015",` and the output in `dist` is plain and simple.

![image](https://user-images.githubusercontent.com/20162853/220860882-b19f0097-f4d0-467e-ae9f-35e0014fc2dc.png)

Where can I inspect this code with `= void 0`?

And maybe by any chance you know whether it is described in docs or how to control this behavior?

**Comment by dgozman** [comment] 2023-02-28 21:39
Turns out, this is a long-known issue between TypeScript and Babel. For example, see this issue: https://github.com/babel/babel/issues/14291.

TypeScript introduced the `useDefineForClassFields` flag that makes it compatible with the newest spec, [see details here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier).

We can probably allow `declare` modifiers, as outlined in the TypeScript release notes above. In this case a workaround would be `declare name!: string | null` that avoids generating `this.name = void 0`.

**Comment by dgozman** [comment] 2023-03-02 00:44
With #21281, the workaround now is to use `declare name: string`. See comment above for details.

**Comment by mxschmitt** [comment] 2023-03-20 15:37
Fix got reverted since it regressed other behaviour. Keeping it open until a new fix is merged.

**Comment by mxschmitt** [comment] 2023-03-31 07:51
I filed https://github.com/babel/babel/issues/15530 for it, since it looks like an upstream bug.

**Comment by J-Sek** [comment] 2023-03-31 16:33
Thanks, I will keep track of the upstream issue.

Unfortunately the workaround is not going to work for me (even if would be merged) as NSwag does not give the possiblity to generate TS with `declare` keyword in front of the field name. At least I can't see it in their configuration. And I would rather not write post-processing on generated 70 KLOC.

**Comment by pavelfeldman** [comment] 2023-11-17 00:22
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Closed by pavelfeldman** 2023-11-17 00:22 UTC
Labels: P3-collecting-feedback
