### ISSUE TITLE
[BUG] Headed run resolves "page.locator('iframe').nth(0)" to Playwright's iframe

### ISSUE THREAD

**Issue by Evilweed** [microsoft/playwright#10804] opened 2021-12-08 19:51 UTC
**Context:**
- Playwright Version: 1.17.1
- Operating System: Mac
- Node.js version: 16.14
- Browser: Chromium

```
## System:
 - OS: macOS 11.6
 - Memory: 43.74 MB / 16.00 GB
## Binaries:
 - Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
 - Yarn: 1.22.17 - /usr/local/bin/yarn
 - npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
 ```

**Code Snippet**
```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  const iframe = page.locator("iframe").nth(0);
  // if run in Headed mode, iframe that was found is the Playwright debug iframe
})();
```

**Describe the bug**

Debug iframe that Playwright adds in Headed mode is being found while using `page.locator("iframe").nth(0);`. Couple of our developers, not yet with mastery debugging skills in playwright ran into this issue, and couldn't find the source of the problem. We are rewriting tests from TestCafe which solved this issue and Selectors omit the framework's debug iframe.

**Comment by dgozman** [comment] 2021-12-08 23:22
@Evilweed Playwright does not add any debug iframe. Do you have a full repro script that shows the issue?

**Comment by dgozman** [comment] 2021-12-11 22:12
Closing because we cannot reproduce the issue. If you have a repro that we can run, please open a new bug.

**Closed by dgozman** 2021-12-11 22:12 UTC
Labels: triaging
