### ISSUE TITLE
[Question] Failed to launch electron app when passing environment variable to options

### ISSUE THREAD

**Issue by shaokaichris** [microsoft/playwright#11705] opened 2022-01-27 22:01 UTC
> const options = {
>    env: {
>      ELECTRON_ENV: process.env.ELECTRON_ENV,
>    },
>   args: [path.join(__dirname, "../..")],
> }
> electronApp = await electron.launch(options);

Run `export ELECTRON_ENV=test && ./node_modules/.bin/cucumber-js --require cucumber.js`. Electron app doesn't launch.

**Comment by yury-s** [comment] 2022-02-01 03:59
The problem is that you override $DISPLAY  environment variable, as a workaround you can do the following:

```js
const options = {
  env: 
    ELECTRON_ENV: process.env.ELECTRON_ENV,
    DISPLAY: process.env.DISPLAY
  },
  args: [path.join(__dirname, "../..")],
}
```

**Comment by shaokaichris** [comment] 2022-02-01 21:52
Thanks yury-s. I can start the app with your workaround.

**Comment by yury-s** [comment] 2022-02-01 22:44
Ok, closing this issue as there is workaround and we don't have immediate plans on providing a more generic fix.

**Closed by yury-s** 2022-02-01 22:44 UTC
Labels: P3-collecting-feedback, electron
