### ISSUE TITLE
[BUG] Documentation API Reference doesn't match typings

### ISSUE THREAD

**Issue by dilame** [microsoft/playwright#6120] opened 2021-04-07 14:05 UTC
**Context:**
- Playwright Version: 1.10.0

**Describe the bug**

Your [API reference](https://playwright.dev/docs/api/class-page) declares all your API entities as classes, but your [types.d.ts](https://github.com/microsoft/playwright/blob/master/types/types.d.ts#L74) declares the same entities as interfaces.

**Comment by JoelEinbinder** [comment] 2021-04-08 17:47
Duplicate of #3978

**Closed by JoelEinbinder** 2021-04-08 17:47 UTC
