### ISSUE TITLE
[Feature] Emulate current time

### ISSUE THREAD

**Issue by anfruiz** [microsoft/playwright#10142] opened 2021-11-08 19:18 UTC
For some tests I would like to simulate the current time because my web app have some functionalities that active depends of the time. 

For example, if the time is between 20hrs and 6hrs the app have to show a maintenance page. This feature will be awesome because I can execute my test in any time of the day, I wouldn’t have to wait for a time to run it.

**Comment by mxschmitt** [comment] 2021-11-08 19:47
Sounds like a duplicate of #6347

**Closed by mxschmitt** 2021-11-08 19:47 UTC
