### ISSUE TITLE
[REGRESSION]: Calling reload() and then goBack() doesn't work in Firefox since 1.32.0

### ISSUE THREAD

**Issue by chris13524** [microsoft/playwright#23210] opened 2023-05-22 21:48 UTC
**Context:**
- GOOD Playwright Version: 1.31.2
- BAD Playwright Version: 1.32.0, 1.34.0, 1.35.0-alpha-may-22-2023
- Operating System: Mac 13.3.1 (a)

**Code Snippet**

```javascript
import { test, expect } from '@playwright/test';

test('goBack works', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  await expect(page.locator("h1")).toHaveText(/enables reliable/);

  await page.getByRole('link', { name: 'Get started' }).click();
  await expect(page.locator("h1")).toHaveText(/Installation/);

  await page.reload(); // comment out to fix Firefox test
  await expect(page.locator("h1")).toHaveText(/Installation/);

  await page.goBack();
  await expect(page.locator("h1")).toHaveText(/enables reliable/);
});
```

**Describe the bug**

On latest versions of Playwright, calling `page.goBack()` after calling `page.reload()` does not work in Firefox.

**Reproduction steps**

Here is an example repo: https://github.com/chris13524/playwright-goback-firefox-regression

```bash
npm install
npx playwright install
npx playwright test # will fail

nano package.json # set to 1.31.2
npm install
npx playwright install
npx playwright test # will pass

nano package.json # set to 1.34.0
npm install
npx playwright install
nano tests/test.spec.ts # comment out `await page.reload()`
npx playwright test # will pass
```

**Comment by aslushnikov** [comment] 2023-05-23 03:06
@chris13524 I'm pretty sure this is a dupe of https://github.com/microsoft/playwright/issues/22640

The issue is filed upstream to firefox repo; let me know if the mentioned workaround works for you!

**Closed by aslushnikov** 2023-05-23 03:06 UTC

**Comment by chris13524** [comment] 2023-05-23 03:44
Thank you, the workaround there fixed the issue for me!

I updated the Firefox in my `projects` in `playwright.config.ts` to this:

```
{
  name: "firefox",
  use: {
    ...devices["Desktop Firefox"],
    launchOptions: {
      firefoxUserPrefs: {
        "fission.webContentIsolationStrategy": 1,
      },
    },
  },
}
```

**Comment by jrmuizel** [comment] 2025-02-06 16:06
@chris13524 does this workaround still work for you? The `fission.webContentIsolationStrategy` pref doesn't seem to be getting applied for me.

**Comment by chris13524** [comment] 2025-02-07 14:23
@jrmuizel sorry I'm not sure. Not sure where I needed this!

**Comment by jrmuizel** [comment] 2025-02-07 14:47
I actually figured out that I wasn't properly setting the `fission.webContentIsolationStrategy` pref. The workaround does work when I set it properly.
