### ISSUE TITLE
[BUG] Stored Auth State Object not utilised in Chromium

### ISSUE THREAD

**Issue by sahyrlelyaams** [microsoft/playwright#27872] opened 2023-10-31 01:25 UTC
### System info
- Playwright Version: [v1.39.0]
- Operating System: [macOS Sonoma 14.0 (ARM)]
- Browser: [Chromium]

### Source code

**Config file**

```js
// playwright.config.js

// @ts-check
const { defineConfig, devices } = require('@playwright/test');

module.exports = defineConfig({
  testDir: './tests/ui',
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Timeout */
  timeout: 60000,
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: 'http://localhost',

    /* Max timeout */
    navigationTimeout: 60000,

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'setup',
      use: {
        ...devices['Desktop Firefox'],
      },
      testMatch: /.*\.setup\.js/,
    },
    {
      name: 'chromium',
      use: { 
        ...devices['Desktop Chrome'],
        storageState: './tests/ui/.auth/auth.json'
      },
      dependencies: ['setup'],
    },
  ],
});

```

**Setup File**

```js
// auth.setup.js

import { test as setup, expect } from '@playwright/test';
import { existsSync } from 'fs';
import { resolve } from 'path';

setup('Authenticate', async ({ page }) => { // Google Auth via Firefox & storing auth state.
  let authExists = existsSync(resolve('./tests/ui/.auth/auth.json'));
  if(!authExists) {
    await page.goto('/login');
    const page1Promise = page.waitForEvent('popup');

    await expect(page.getByRole('button', { name: 'Sign in with Google' })).toBeAttached({ timeout: 20000 });
    await page.getByRole('button', { name: 'Sign in with Google' }).click();
    const page1 = await page1Promise;

    await page1.waitForEvent('domcontentloaded');

    await expect(page1.getByLabel('Email or phone')).toBeAttached({ timeout: 60000 });
    await page1.getByLabel('Email or phone').fill(String(process.env.USER_NAME));
    await expect(page1.getByRole('button', { name: 'Next' })).toBeAttached();
    await page1.getByRole('button', { name: 'Next' }).click();

    await expect(page1.locator('input[type="password"]')).toBeAttached({ timeout: 20000 });
    await page1.locator('input[type="password"]').fill(String(process.env.USER_PWD));
    await page1.locator('#passwordNext').click();

    await expect(page.getByRole('button', { name: 'Sign in with Google' })).toBeHidden({ timeout: 20000 });

    await page.context().storageState({ path: './tests/ui/.auth/auth.json' });
  }
});

```

**Directory Structure**

```
playwright.config.js
tests/
| ----- ui/
| ---------- .auth/ 
| ---------- auth.setup.js
| ---------- any-test.spec.js
```

**Steps**
- Run any test of your liking with the above .setup.js file for storing Auth state.

**Expected**

Chromium accepts the storageState JSON Object & the tests run in an authenticated state.

**Actual**

Chromium doesn't accept the storageState JSON Object & is redirected to Login screen.

**Comment by pavelfeldman** [comment] 2023-10-31 03:40
We can't act on this issue because we can't reproduce it locally. You have shared the config and the test file, but we don't have the app you are testing.

Your project structure look fine, I would guess that what is happening is that `'./tests/ui/.auth/auth.json'` is resolved relative to different locations. It is always better to use `path.resolve` relative to `__dirname` to make sure you are pointing to the right location.

**Comment by pavelfeldman** [comment] 2023-11-02 19:27
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Closed by pavelfeldman** 2023-11-02 19:27 UTC
Labels: triaging
