### ISSUE TITLE
[BUG] Request body is always empty in Chromium

### ISSUE THREAD

**Issue by alex-vukov** [microsoft/playwright#21951] opened 2023-03-24 10:25 UTC
### System info
- Playwright Version: [v1.32.0]
- Operating System: [macOS 13.2]
- Browser: [Chromium]
- Other info:

### Source code
The following test breaks only in Chromium because `body` is empty:

```ts
test('user is able to login', async ({ page }) => {
    const email = 'test_email@abcd.com';
    const password = 'test_password';

    await page.route('**/signin', async (route, request) => {
        const body = JSON.parse(request.postData() || '{}'); // Always empty in Chromium. Works with all other browsers.
        await Promise.all([expect(body.email).toEqual(email), expect(body.password).toEqual(password)]);
        const json = require('./fixtures/signin_successful.json');
        await route.fulfill({ json });
    });

    await page.goto('/');
    const emailInput = page.getByTestId('email');
    const passwordInput = page.getByTestId('password');
    const loginButton = page.getByTestId('login');
    await emailInput.fill(email);
    await passwordInput.fill(password);
    await expect(loginButton).toBeEnabled();
    await Promise.all([loginButton.click(), page.waitForResponse('**/signin')]);
});
```

**Comment by aslushnikov** [comment] 2023-03-24 20:22
@alex-vukov I was not able to reproduce; the following prints correct postData for me:

```ts
import {test, expect } from '@playwright/test';

test('should have postData in intercepted request', async ({ page }) => {
  await page.goto('https://example.com');
  let postData;
  await page.route('**/*', async route => {
    postData = await route.request().postData();
    route.abort();
  });
  await page.evaluate(() => {
    fetch('/submit', {
      method: 'POST',
      body: '"foo"',
      headers: {
        'Content-Type': 'application/json'
      },
    });
  });
  await expect.poll(() => postData).toBe('"foo"');
});
```

Could you please run this and see if it works for you? If it does, could you please change the test so that it reproduces the issue?

**Comment by alex-vukov** [comment] 2023-03-27 19:35
Thank you for the example @aslushnikov! For some reason your example test works in all browsers and mine breaks only on Chromium. I will debug some more and try to upload an example tomorrow which reproduces the issue

**Comment by alex-vukov** [comment] 2023-03-28 06:14
This was a nightmare to reproduce. The issue happens only when the following conditions are met:
1. The request is triggered from the `onsubmit`event of an html `form`.
2. The `onsubmit` handler executes `fetch` asynchronously with a non-zero delay.

Here is a repo with the rerpoduction of the issue https://github.com/alex-vukov/playwright-bug
You can run `npm test` and see that the test breaks in Chromium but not in Firefox.

**Comment by aslushnikov** [comment] 2023-03-28 23:32
@alex-vukov in your example, if you just navigate to the `index.html` page, open devtools, and hit the `click me` button, then you'll notice that Chrome doesn't actually send any `/login` request at all: it gets overriden with the navigation from the `submit` action.

I've sent a PR to your repo that fixes the HTML page so that it works in Chrome as expected: https://github.com/alex-vukov/playwright-bug/pull/1

Overall, looks like it works as expected!

**Comment by yury-s** [comment] 2023-03-31 22:43
Closing as part of the triage process. Please file a new report with a reproducible example and link to this one if you still face the issue.

**Closed by yury-s** 2023-03-31 22:43 UTC
Labels: triaging
