### ISSUE TITLE
[BUG] E2E Tests getting slow after upgrading to the latest version of playwright

### ISSUE THREAD

**Issue by shahabkhan12342** [microsoft/playwright#13498] opened 2022-04-12 06:10 UTC
**Context:**
- Playwright Version: [1.21.0]
- Operating System: [Windows]
- Node.js version: [14.17.3]
- Browser: [Chrome]
- Chrome version: [Version 100.0.4896.75]

I am facing this problem, tests are running very slow since we have migrated to latest version of chrome and due to this our End to End Automation's results are getting effected because when multiple tests runs at the time then it gets more slow 
 It's because of the latest version of Chrome because when we installed old version of chrome then tests were running perfectly in this old manner but in the latest version of chrome [100.0.4896.75] it is vert slow as you can see in below video.
[0063a869-1f75-4a90-a27a-d4bbbb7a1b0b.zip](https://github.com/microsoft/playwright/files/8469948/0063a869-1f75-4a90-a27a-d4bbbb7a1b0b.zip)
 
Also it's working fine on Firefox browser, Firefox's video is also attached below:
[f82e504a-2f3f-48ac-a883-6272d50bb5c0.zip](https://github.com/microsoft/playwright/files/8470006/f82e504a-2f3f-48ac-a883-6272d50bb5c0.zip)

**Comment by Nhc007** [comment] 2022-04-13 06:05
We are also facing the same issue even i've upgraded to latest version of playwright[1.21.0]. We have diagnosed it that the latest version of chrome is being problematic. Once downgraded to Chrome[95-0-4638-54] it worked same as before. please guide and fix this so things can be back to business.

**Comment by aslushnikov** [comment] 2022-04-14 23:48
@shahabkhan12342 You mentioned that you run Chrome Version 100.0.4896.75. Do you run against the stable Chrome browser channel?

@Nhc007 what's your Chrome version?

**Comment by Nhc007** [comment] 2022-04-15 05:30
@aslushnikov We are using latest official release of Chrome[100.0.4896.88], it gets so slow that test timeouts.  We have to forcefully use the older version. Plus there is an other unusual behavior happening, In CI pipeline, the tests are getting flaky due to following errors:
1.     (frame.isVisible: Target page, context or browser has been closed)
2.     (  browserContext.newPage: Target closed)

**Comment by aslushnikov** [comment] 2022-04-15 06:02
@Nhc007 Could you share a code snippet that I can run locally to see this by myself?

**Comment by shahabkhan12342** [comment] 2022-04-18 08:34
@aslushnikov  here is the snippet code, this is a demo scenario of our application. 

Playwright Version: [1.21.0]
Operating System: [Windows]
Node.js version: [14.17.3]
Browser: [Chrome]
Chrome version: [Version 100.0.4896.127]

`import { test } from '@playwright/test';

        test('Demo Test Scenario:', async ({ page }) => {        
          
         await page.goto('http://kimdshgm.automation.beta.vidizmo.com');
         await page.waitForSelector('[data-e2e-span="vidizmo-app"]', { state :  "attached" });
         await page.click('[data-e2e-link="LoginSignInButton"]');
         await page.fill('[data-e2e-input="emailAddress"]', 'kimdshgm-admin@sharklasers.com');
         await page.fill('[data-e2e-input="Password"]', 'Admin@123');
          await page.click('[data-e2e-btn="signIn"]');
          await page.waitForTimeout(1000)
          await page.waitForSelector('[data-e2e-link="selectMenuBar"]');
          await page.click('[data-e2e-link="selectMenuBar"]');
          await page.click('[data-e2e-link="AboutUs"]');
          await page.waitForSelector('[data-e2e-link="selectMenuBar"]');
          await page.click('[data-e2e-link="selectMenuBar"]');
           await page.click('[data-e2e-link="MediaManager"]');
           await page.waitForSelector('[data-e2e-page="mediaManagerPublished"]');
           await page.click('[data-e2e-btn="toggleFilters"]');
  
        });    
        
    `

**Comment by pavelfeldman** [comment] 2022-04-25 20:21
Pasting my stats here:
- Ubuntu: 15s on both 1.20.2 and 1.21.1

**Comment by pavelfeldman** [comment] 2022-04-25 20:35
It looks like Chrome 100 is slower in your particular environment and this could be due to either enterprise settings (in your corp environment) or your local network devices (home environment). Did you notice the same slowdown in any managed infrastructure like CI/CD?

**Comment by pavelfeldman** [comment] 2022-04-30 02:35
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2022-04-30 02:35 UTC
Labels: triaging

**Comment by FahadRS** [comment] 2022-05-09 15:56
@pavelfeldman we diagnosed this issue more in detail and we were able to know this problem only happens when the user turn on the trace in the configuration

Sample Code

    import { test, expect, Page } from '@playwright/test';
    
    test('Demo Test Scenario:', async ({ page }) => { 
      await page.goto('https://usk.enterprisetube.com/');     
      await page.waitForSelector('[data-e2e-span="vidizmo-app"]', { state :  "attached" });     
      await page.click('[data-e2e-link="LoginSignInButton"]');     
      await page.fill('[data-e2e-input="emailAddress"]', 'fahad@sharklasers.com');     
      await page.fill('[data-e2e-input="Password"]', 'Admin@123');     
      await page.click('[data-e2e-btn="signIn"]');     
      await page.waitForSelector('[data-e2e-heading="MashupsMostMostRecent"]')               
      await page.click('[data-e2e-link="selectMenuBar"]');     
      await page.click('[data-e2e-link="MediaManager"]');          
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
    
    });  

Chrome Version : Version 101.0.4951.54 

Trace **On** Configuration 
takes 30-40 Seconds

Trace **off** Configuration 
takes 7 Seconds

Chrome Version : Version 95

Trace **On** Configuration 
takes 7 Seconds

Trace **off** Configuration 
takes 7-8 Seconds

This is entire trace config file which we are using

    const config: PlaywrightTestConfig = {
      testDir: './tests',
      timeout: 30 * 1000,
      expect: {
        timeout: 5000
      },
      forbidOnly: !!process.env.CI,  
      workers: process.env.CI ? 1 : undefined,
      reporter: 'html',
      use: {
        actionTimeout: 0,
        channel : "chrome",
        trace: 'off',
      },
    };  
    export default config;

I can also provide you sample project in which this problem can be reproduced if there is a need
