### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by PiyushGulhane-05** [microsoft/playwright#17738] opened 2022-09-30 12:41 UTC
Hello all, I and my team are using C# with playwright. 

**my 1st question:** 

We have nearly 100 test cases, and more to come in future. What happens is that,

1st Scenario:  when we run (all) tests, some of them, lets say, 90 of them pass and 10 fails. Then we run the failed tests again, and all failed tests pass, don't know what is the reason this happens.

2nd Scenario: some times, we run all 100, now lets say, 98 pass and 2 failed (not running failed ones this time). Now in fresh run, we run all 100 tests again, this time, the 2 tests that failed earlier, they pass and 2 new tests fail. Why does this happen?  

3rd Scenario: Sometimes, we run it from console, then we get a a message on console, what to do for this? (following is the message): 
        (node:71336) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 SIGINT listeners added to 
        [process]. Use emitter.setMaxListeners() to increase limit
        (Use `node --trace-warnings ...` to show where the warning was created)
        (node:71336) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 SIGTERM listeners added to 
        [process]. Use emitter.setMaxListeners() to increase limit
        (node:71336) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 SIGHUP listeners added to 
        [process]. Use emitter.setMaxListeners() to increase limit

**my 2nd question:** 

Playwright recommends not use hard waits, what to use instead? For e.g., a dropdown button has 3 options, I go, select an option, but it is not selected, then test fails (with whatever default time out there is for that). What to do here? As the dropdown button's state is changing, not navigating anywhere, happening in same DOM, and there is no waiting provision like WaitUntilStateChange(), so what to do?

**my 3rd question:** 

When we run our tests locally they pass, but in Azure pipelines they fail, is there a particular reason for that? Does it need specific configuration of machine, like 16GB RAM and 4 cores CPU or something?

**my 4th question:** 

Sometimes Element/Locators are visible but sometimes it is not, even though we have taken the best possible attribute, don't generally take class or ID as I had read somewhere, that we should try to avoid it, whenever possible, so what to do in that case?

**Comment by yury-s** [comment] 2022-10-03 22:59
> my 1st question:

Looks like the tests are flaky. There many reasons why it may happen (like a UI element doesn't appear when you expect it etc) and it depends on your app. We can provide you better assistance if you give us a minimal reproducible example which we can run locally and tell us what errors you see.

> my 2nd question:
> Playwright recommends not use hard waits, what to use instead? 

Most of the time Platwright will [auto-wait](https://playwright.dev/dotnet/docs/actionability) for an element to become actionable. We also recommend using our [web assertions](https://playwright.dev/dotnet/docs/test-assertions) which will wait for a condition to be met with a configurable timeout.

> my 3rd question:
>
> When we run our tests locally they pass, but in Azure pipelines they fail, is there a particular reason for that?

Depends on the difference in  the local and CI configurations, what's the error message you get?

> my 4th question:
>
> Sometimes Element/Locators are visible but sometimes it is not, even though we have taken the best possible attribute,
> don't generally take class or ID as I had read somewhere, that we should try to avoid it, whenever possible, so what to do in
> that case?

[Web assertions](https://playwright.dev/dotnet/docs/test-assertions) should help you wait for the elements to become stable. You should make sure that you pick right condition that guarantees that the element should be visible. You can try to use our [code generator](https://playwright.dev/dotnet/docs/codegen-intro) which can help pick better selectors.

**Comment by yury-s** [comment] 2022-10-07 23:55
Closing per the response above. Feel free to file a new issue and link to this one if you need further help.

**Closed by yury-s** 2022-10-07 23:55 UTC
Labels: triaging
