### ISSUE TITLE
[Bug]: using extraHTTPHeaders breaks pre flight requests in chrome

### ISSUE THREAD

**Issue by felipebn** [microsoft/playwright#31709] opened 2024-07-16 17:11 UTC
### Version

1.45.0

### Steps to reproduce

The example below allows to easily reproduce it with a live app.

Just ran it with `webkit` and `chrome` to get different results.

```ts
import {test} from "@playwright/test";

/**
 * using this firebase demo page as it is a public page
 * and represents the exactly scenario where this was identified
 * in our codebase.
 * 
 * @param page 
 */
const openFacebookPopup = async (page) => {
    await page.goto('https://fir-ui-demo-84a6c.firebaseapp.com/');
    const popup = page.waitForEvent('popup');
    await page.locator('text=Sign in with Facebook').click();
    const fbPopup = await popup;
    await fbPopup.waitForLoadState('domcontentloaded');
};

test.describe('Firebase', () => {
    /**
     * This test will inject the extra header only
     */
    test('with extra header only', async ({ browser }) => {
        const ctx = await browser.newContext({
            extraHTTPHeaders: {
                'X-My-Header': 'my-header',
            },
        });
        const page = await ctx.newPage();
        await openFacebookPopup(page);
    });

    /**
     * This test is the same as the above but in addition it will create a catch
     * all route that will just continue the request.
     * Somehow this changes behaviors and the test will pass.
     */
    test('with extra header and route', async ({ browser }) => {
        const ctx = await browser.newContext({
            extraHTTPHeaders: {
                'X-My-Header': 'my-header',
            },
        });
        await ctx.route('**/*', (route) => {
            route.continue();
        });
        const page = await ctx.newPage();
        await openFacebookPopup(page);
    });
});
```

### Expected behavior

Tests to behave equally in both browsers likely without having to fully disable web security in chrome.

### Actual behavior

In `webkit` the preflight request is not modified so it passes without issues, in `chrome` the preflight request has the `access-control-request-headers` modified including the extra headers.

**Webkit request:**

![image](https://github.com/user-attachments/assets/b31fc50f-4608-46a6-b994-5e5ec39f823a)

**Chrome request:**

![image](https://github.com/user-attachments/assets/ee977807-d53e-4e02-b29e-00471c51e421)

### Additional context

This seems related with:

https://github.com/microsoft/playwright/issues/19904 

https://github.com/microsoft/playwright/issues/21811

### Environment

```shell
System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 60.39 MB / 36.00 GB
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 9.1.3 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.45.0 => 1.45.0
```

**Comment by dgozman** [comment] 2024-07-17 15:32
@felipebn This is actually working as intended in Chromium. You are adding a header, and browser issues a preflight because there is a non-exempt header. See #19904 for a similar discussion.

When you route a request, Playwright automatically fulfills the CORS preflight to simplify the routing API. This means that you can only test the CORS behavior of your server without routing. See #27339 for a similar discussion.

I'll close this issue as a duplicate. Thank you for filing!

**Closed by dgozman** 2024-07-17 15:32 UTC
