### ISSUE TITLE
[BUG] WebKit doesn't work in official docker image on Apple M1

### ISSUE THREAD

**Issue by gaainf** [microsoft/playwright#14458] opened 2022-05-28 08:44 UTC
**Context:**
- Playwright Version: 1.22.2
- Operating System: Mac OS Monterey 12.2.1
- Node.js version: 16.15.0
- Browser: WebKit 

**Description**
WebKit doesn't work in official docker image on Apple M1 (arm64). 
*Details:* the same test worked on WebKit with amd64 platform.

**Actions:**
1. pull and run official docker image 
```bash
docker run -it --rm --ipc=host -v `pwd`:/usr/src/app mcr.microsoft.com/playwright:v1.22.0-focal /bin/bash
```
3. install playwright
```bash
yarn install
```
- package.json:
```json
{
  "devDependencies": {
    "@playwright/test": "^1.20.0",
    "chai": "^4.3.6",
    "chai-files": "^1.4.0",
    "playwright": "^1.20.0"
  }
}
```
4. run test on chromium, firefox and webkit 
```bash
npx playwright test test.spec.js
```
- test.spec.js
```js
const { test, expect } = require('@playwright/test');
const chai = require('chai');
const chaiFiles = require('chai-files');

chai.use(chaiFiles);
test.use({ viewport: { width: 1280, height: 1024 } });

test('Base test', async ({ page, browserName }) => {
    await page.goto('https://example.com');
    await expect(page).toHaveTitle(/Example/);
    console.log(await page.evaluate(() => navigator.userAgent));
    await page.screenshot({ path: `example_${browserName}.png` });
    chai.expect(chaiFiles.file(`example_${browserName}.png`)).to.exist;
});
```
- playwright.config.js
```js
const { devices } = require('@playwright/test');

/** @type {import('@playwright/test').PlaywrightTestConfig} */
const config = {
  timeout: 60000,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  use: {
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],
};

module.exports = config;
```

**Expected:** 
Playwright with all browsers should work correct

**Actual:** 
Test failed on WebKit
```bash
$ docker run -it --rm --ipc=host -v `pwd`:/usr/src/app mcr.microsoft.com/playwright:v1.22.0-focal /bin/bash

$ root@936e1152693b:/# ls /ms-playwright/
chromium-1005  ffmpeg-1007  firefox-1323  webkit-1641

$ root@936e1152693b:/# npx playwright test test.spec.js

Running 3 tests using 2 workers

  ✓  [chromium] › test.spec.js:8:1 › Base test (931ms)
  ✓  [firefox] › test.spec.js:8:1 › Base test (3s)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.40 Safari/537.36
  ✘  [webkit] › test.spec.js:8:1 › Base test (2s)
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0.1) Gecko/20100101 Firefox/99.0.1


  1) [webkit] › test.spec.js:8:1 › Base test =======================================================

    page.goto: WebKit encountered an internal error
    =========================== logs ===========================
    navigating to "https://example.com/", waiting until "load"
    ============================================================

       7 |
       8 | test('Base test', async ({ page, browserName }) => {
    >  9 |     await page.goto('https://example.com');
         |                ^
      10 |     await expect(page).toHaveTitle(/Example/);
      11 |     console.log(await page.evaluate(() => navigator.userAgent));
      12 |     await page.screenshot({ path: `example_${browserName}.png` });

        at /usr/src/app/test.spec.js:9:16


  1 failed
    [webkit] › test.spec.js:8:1 › Base test ========================================================
  2 passed (6s)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by yury-s** [comment] 2022-05-29 16:50
> ```json
>    "@playwright/test": "^1.20.0",
> ```

You use @playwright/test@1.20  inside container which is built for playwright 1.22. Try upgrading to playwright @1.22 and check if the error still occurs.

**Comment by Linux249** [comment] 2022-06-01 12:11
I have the same problem after switching to a M1 mac. 
Could reproduce it with: 
"@playwright/test": "^1.22.0"
mcr.microsoft.com/playwright:v1.22.0-focal
And:
"@playwright/test": "^1.22.2"
mcr.microsoft.com/playwright:v1.22.2-focal

I use a MacBook Pro (14", 2021) with a Apple M1 Pro chip

**Comment by aslushnikov** [comment] 2022-06-01 13:01
@Linux249 I just tried and a simple test worked for me. We also run a subset of our tests in Docker on M1 mac and they all pass.

So can you please help me reproduce this? What exactly do you run and what fails for you?

**Comment by jkilada** [comment] 2022-06-03 17:19
Experiencing the same issue here. Test suite works on all browsers in linux CI env but fails for webkit when running on M1 mac.

**Comment by aslushnikov** [comment] 2022-06-06 08:36
I managed to repro. Turns out this is a dupe of https://github.com/microsoft/playwright/issues/14236

**Closed by aslushnikov** 2022-06-06 08:36 UTC
Labels: browser-webkit, P1-resolve-asap
