### ISSUE TITLE
[BUG] Evaluate return partial object

### ISSUE THREAD

**Issue by mattveraldi** [microsoft/playwright#22418] opened 2023-04-14 23:05 UTC
### System info
- Playwright Version: [v1.32.3]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info: GoJS e2e testing

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
import { defineConfig, devices } from '@playwright/test';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  testDir: './tests',
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://127.0.0.1:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },

    // {
    //   name: 'firefox',
    //   use: { ...devices['Desktop Firefox'] },
    // },

    // {
    //   name: 'webkit',
    //   use: { ...devices['Desktop Safari'] },
    // },

    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: { ...devices['Pixel 5'] },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: { ...devices['iPhone 12'] },
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { ..devices['Desktop Chrome'], channel: 'chrome' },
    // },
  ],

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   url: 'http://127.0.0.1:3000',
  //   reuseExistingServer: !process.env.CI,
  // },
});

```

**Test file (self-contained)**

```js
it('smoke test', async ({ page }) => {
  await page.goto('https://gojs.net/latest/samples/orgChartStatic.html');
  const diagram = await page.locator("#myDiagramDiv");
  let node = await diagram.evaluate((diagramWrapper) => diagramWrapper["goDiagram"].findNodeForKey(1));
  console.warn(node); // it works giving me a partial representation
  console.warn(node.data); // is undefined, but it shouldn't
  let nodeData = await diagram.evaluate((diagramWrapper) => diagramWrapper["goDiagram"].findNodeForKey(1)?.data);
  console.warn(nodeData) // it works
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

`node.data` should work outside of the evaluate context as well as inside it. 

**Actual**

`node.data` is undefined when accessed outside the evaluate context, but it has other properties.

**Comment by mxschmitt** [comment] 2023-04-16 20:07
**Investigation notes**: Reason for this is because this libray does some prototype hacking internally, which can be tracked down to this minimal reproducible, imagine this below is what we do internally:

```ts
const myTest = {}
// without __proto__ it works as expected.
Object.defineProperties(myTest.__proto__, {
    data: {
        get: () => 42,
        set: () => {},
    }
})
// What we do internally to serialise results.
console.log(Object.getOwnPropertyDescriptors(myTest), Object.keys(Object.keys(myTest)))
```

**Comment by mattveraldi** [comment] 2023-04-16 20:42
> **Investigation notes**: Reason for this is because this libray does some prototype hacking internally, which can be tracked down to this minimal reproducible, imagine this below is what we do internally:
> 
> ```ts
> const myTest = {}
> // without __proto__ it works as expected.
> Object.defineProperties(myTest.__proto__, {
>     data: {
>         get: () => 42,
>         set: () => {},
>     }
> })
> // What we do internally to serialise results.
> console.log(Object.getOwnPropertyDescriptors(myTest), Object.keys(Object.keys(myTest)))
> ```
> 
> I recommend for now to access the 'data' property manually directly. Would that work for you?

I see the problem now... What I am doing at the moment is adding "data" manually in the return statement of the `evaluate` method, but that means that I have to do it for each "getter" in order to have a generic utility function for gojs nodes...
Is there any possible workaround to this?

**Comment by mxschmitt** [comment] 2023-04-17 09:12
There is unfortunately no easy way around this problem. Keep in mind that the JavaScript inside the page gets serialised with the Node.js runtime, see here: https://playwright.dev/docs/evaluating

So we do a best effort which fails in case of deep prototype getters.

Closing by that for now, since a workaround for this would be to return a property explicitly.

**Closed by mxschmitt** 2023-04-17 09:12 UTC
Labels: triaging

**Comment by mxschmitt** [comment] 2023-04-17 09:16
The prototype hacking with the getters is done with this gojs library. I didn't find their source online, but internally they do things like `ma.Object.defineProperties(W.prototype, {` (minified source). And we internally serialise using [this](https://github.com/microsoft/playwright/blob/1fecc20238f0a1a5d942726f246decf6fdfab8de/packages/playwright-core/src/protocol/serializers.ts#L163-L169) while Object.keys does not work for this library.

**Comment by mattveraldi** [comment] 2023-04-17 10:10
Thank you!
