### ISSUE TITLE
[BUG] Playwright android script getting stuck on creating new browser page

### ISSUE THREAD

**Issue by ankur-lt** [microsoft/playwright#21510] opened 2023-03-09 06:09 UTC
### System info
- Playwright Version: 1.29.2
- Operating System: MacOS Ventura
- Browser: Chrome
- NodeJS version: v16.16.0
- Other info: Running the android server for Pixel 4 and Nexus 5X with Android 11. Issue exists on real device as well as emulator. 

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Server script**

```js
async function launchAndroidServer() {
  const browserServer = await _android.launchServer({
    port: 5555,
    wsPath: "ws",
  });

  const wsEndpoint = browserServer.wsEndpoint();
  console.log("wsEndpoint:: ", wsEndpoint);
}

launchAndroidServer();
```

Client Script
```js
const { _android } = require('playwright');

(async () => {
  const device = await _android.connect(
      'ws://127.0.0.1:5555/ws'
  );

  console.log(`Model :: ${device.model()}, serial:: ${device.serial()}`)

  await device.shell('am force-stop com.android.chrome');
  const context = await device.launchBrowser();

  const page = await context.newPage();
  await page.goto('https://playwright.dev/');

  await page.close();
  await context.close();
})();

```

**Steps**
- Run the server script
- Run the client script

**Expected**
New browser page should be opened and test should get executed.

**Actual**
The client script execution doesn't proceed after the `await context.newPage()` command. The new chrome browser page is opened with the URL as `about:blank` and the test does not proceed.

Client and server logs added below:
[pw_android_client.log](https://github.com/microsoft/playwright/files/10928374/pw_android_client.log)
[pw_android_server.log](https://github.com/microsoft/playwright/files/10928375/pw_android_server.log)

**Comment by mxschmitt** [comment] 2023-03-09 13:11
We run all our tests on the emulator for every commit using https://github.com/microsoft/playwright/blob/main/utils/avd_recreate.sh and https://github.com/microsoft/playwright/blob/main/utils/avd_start.sh. Could you help us which emulator configuration you are using to reproduce this error?

**Comment by mxschmitt** [comment] 2023-03-09 16:09
I tried to reproduce it but was not able to by changing it to Android 10 and 11, see this diff:

```diff
diff --git a/utils/avd_recreate.sh b/utils/avd_recreate.sh
index f0724f5be..ef1ee0fe2 100755
--- a/utils/avd_recreate.sh
+++ b/utils/avd_recreate.sh
@@ -15,7 +15,7 @@ if [[ "$(uname -m)" == "arm64" ]]; then
     ANDROID_ARCH="arm64-v8a"
 fi
 
-${ANDROID_HOME}/tools/bin/avdmanager delete avd --name android33 || true
-echo "y" | ${ANDROID_HOME}/tools/bin/sdkmanager --install "system-images;android-33;google_apis;$ANDROID_ARCH"
-echo "no" | ${ANDROID_HOME}/tools/bin/avdmanager create avd --force --name android33 --device "Nexus 5X" --package "system-images;android-33;google_apis;$ANDROID_ARCH"
+${ANDROID_HOME}/tools/bin/avdmanager delete avd --name android30 || true
+echo "y" | ${ANDROID_HOME}/tools/bin/sdkmanager --install "system-images;android-30;google_apis;$ANDROID_ARCH"
+echo "no" | ${ANDROID_HOME}/tools/bin/avdmanager create avd --force --name android30 --device "pixel_4" --package "system-images;android-30;google_apis;$ANDROID_ARCH"
 ${ANDROID_HOME}/emulator/emulator -list-avds
diff --git a/utils/avd_start.sh b/utils/avd_start.sh
index a1b9bf61f..98d8dad14 100755
--- a/utils/avd_start.sh
+++ b/utils/avd_start.sh
@@ -11,7 +11,7 @@ fi
 bash $PWD/utils/avd_stop.sh
 
 echo "Starting emulator"
-nohup ${ANDROID_HOME}/emulator/emulator -avd android33 -no-audio -no-window -no-boot-anim -no-snapshot &
+nohup ${ANDROID_HOME}/emulator/emulator -avd android30 -no-audio -no-boot-anim -no-snapshot &
 ${ANDROID_HOME}/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
 ${ANDROID_HOME}/platform-tools/adb devices
 echo "Emulator started"
```

and

```diff
diff --git a/utils/avd_recreate.sh b/utils/avd_recreate.sh
index f0724f5be..e19ef4661 100755
--- a/utils/avd_recreate.sh
+++ b/utils/avd_recreate.sh
@@ -15,7 +15,7 @@ if [[ "$(uname -m)" == "arm64" ]]; then
     ANDROID_ARCH="arm64-v8a"
 fi
 
-${ANDROID_HOME}/tools/bin/avdmanager delete avd --name android33 || true
-echo "y" | ${ANDROID_HOME}/tools/bin/sdkmanager --install "system-images;android-33;google_apis;$ANDROID_ARCH"
-echo "no" | ${ANDROID_HOME}/tools/bin/avdmanager create avd --force --name android33 --device "Nexus 5X" --package "system-images;android-33;google_apis;$ANDROID_ARCH"
+${ANDROID_HOME}/tools/bin/avdmanager delete avd --name android29 || true
+echo "y" | ${ANDROID_HOME}/tools/bin/sdkmanager --install "system-images;android-29;google_apis;$ANDROID_ARCH"
+echo "no" | ${ANDROID_HOME}/tools/bin/avdmanager create avd --force --name android29 --device "pixel_4" --package "system-images;android-29;google_apis;$ANDROID_ARCH"
 ${ANDROID_HOME}/emulator/emulator -list-avds
diff --git a/utils/avd_start.sh b/utils/avd_start.sh
index a1b9bf61f..4426e190e 100755
--- a/utils/avd_start.sh
+++ b/utils/avd_start.sh
@@ -11,7 +11,7 @@ fi
 bash $PWD/utils/avd_stop.sh
 
 echo "Starting emulator"
-nohup ${ANDROID_HOME}/emulator/emulator -avd android33 -no-audio -no-window -no-boot-anim -no-snapshot &
+nohup ${ANDROID_HOME}/emulator/emulator -avd android29 -no-audio -no-boot-anim -no-snapshot &
 ${ANDROID_HOME}/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
 ${ANDROID_HOME}/platform-tools/adb devices
 echo "Emulator started"

```

1. Apply diff
2. `./utils/avd_install.sh`
3. `./utils/avd_recreate.sh`
4. `./utils/avd_start`
5. `npm run atest page-basic`

**Comment by mxschmitt** [comment] 2023-03-14 12:00
Closing as per above, since we were not able to reproduce. Please re-file for further questions.

**Closed by mxschmitt** 2023-03-14 12:00 UTC
Labels: triaging

**Comment by ankur-lt** [comment] 2023-03-23 06:17
Thanks @mxschmitt ! I hadn't enabled the flag `Enable command line on non-rooted devices` on the newer device, because of which the response of launchBrowser() was not being received. The issue is resolved now.
