### ISSUE TITLE
[Bug]: Video is not captured for chromium browser/devices on test failures when workers are set to greater than 1

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#7898] opened 2021-07-29 00:47 UTC
### Playwright version

1.13.0

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

I have a config file with workers set to 2 and I am using two projects: Chromium + Pixel 5. The video artifact is set to `on`.  When the test times out waiting for an element on the page, the video is not captured. Please use the snippet to reproduce the bug.

Works fine with iPhone 12 and webkit irrespective of no. of workers (for the snippet attached)
Works fine with Chromium and Pixel 5 when no. of workers = 1 (for the snippet attached)

### Code snippet to reproduce your bug

```shell
// foo.spec.js
const { test } = require('@playwright/test');

test('test', async ({ page }) => {
  await page.goto("https://playwright.dev/");
  await page.waitForSelector(".navbar__title1");
});

// playwright.config.js
const { devices } = require('playwright');
const path = require('path');
module.exports = {
  timeout: 25000,
  retries: 0,
  workers: 2,
  testDir: 'tests',
  use: {
    headless: false,
    video: 'on',
    trace: 'on',
  },

  projects: [
    {
      name: 'Desktop Chrome',
      use: { browserName: 'chromium' },
    },
    {
      name: 'Mobile Chrome',
      use: devices['Pixel 5'],
    },
  ],
};
```

**Comment by mxschmitt** [comment] 2021-08-08 18:01
Sorry for the late reply! I tried to reproduce with 1.13.0, 1.13.1 and `@next` but was not able to. The correct files were produced in all three cases:
![image](https://user-images.githubusercontent.com/17984549/128641254-5a63e1bc-bd78-48f9-8405-0fe32ff033e7.png)

Are you still encountering this?

**Comment by Nav-2d** [comment] 2021-08-08 18:39
Hi @mxschmitt I am still able to reproduce on `1.13.0` and `1.13.1`. Did you use the same files I have provided above? Is there anything else I can provide to help debug this?

**Comment by mxschmitt** [comment] 2021-08-08 20:07
Yes I did, if you could create a small Git repository, that would be the best. We are talking about that its expected that the video is there but its not there in your case if I understood it correctly right?

**Comment by Nav-2d** [comment] 2021-08-08 21:15
Here is a repo to reproduce the issue - https://github.com/Nav-2d/video-bug

Yes, the expected is that the video is saved. 
**Note**: I am using MacOS

**Comment by mxschmitt** [comment] 2021-08-08 21:29
Thank you for your repro! I was able to reproduce it and can confirm that its fixed in the development version which gets released in 1-2 weeks. You can try it today via `npm install @playwright/test@next`. Let us know if it works for you, thanks!

**Comment by Nav-2d** [comment] 2021-08-08 22:11
I am still facing the issue with the `next` version. I deleted `node_modules` folder and re-installed the packages as well. 

Updated the repo: https://github.com/Nav-2d/video-bug with the latest versions.

**Comment by aslushnikov** [comment] 2021-08-12 10:41
@Nav-2d I just tried and it worked just fine - i got both videos. 

```sh
$ cd ~/repros
$ git clone  https://github.com/Nav-2d/video-bug 
$ cd video-bug
$ npm i
$ npx playwright test
$ ls test-results/foo-test-Desktop-Chrome/
8a99be6060e2686cd846066d853faff4.webm  trace.zip
$ ls test-results/foo-test-Mobile-Chrome/
4e01ce0f3845c7bc39c3ee7fca0e7098.webm  trace.zip
```

So it does produce video files for me; and there are videos indeed. Can you post a terminal recording for us or something with these steps? Maybe it'll help us see why things don't work for you.

Also, we can setup a simple Github Actions job running on mac to see if it create these videos there.

**Comment by aslushnikov** [comment] 2021-08-12 13:32
@viart just to make sure: do you run on intel macbook?

**Comment by viart** [comment] 2021-08-12 14:24
Intel, but pretty old one - Late 2013. If it helps:
```
pw:error Protocol error (Runtime.runIfWaitingForDebugger): Target closed.Error
  pw:error     at /private/tmp/video-bug/node_modules/@playwright/test/lib/server/chromium/crConnection.js:202:16
  pw:error     at new Promise (<anonymous>)
  pw:error     at CRSession.send (/private/tmp/video-bug/node_modules/@playwright/test/lib/server/chromium/crConnection.js:198:12)
  pw:error     at CRSession._sendMayFail (/private/tmp/video-bug/node_modules/@playwright/test/lib/server/chromium/crConnection.js:209:17)
  pw:error     at FrameSession._onAttachedToTarget (/private/tmp/video-bug/node_modules/@playwright/test/lib/server/chromium/crPage.js:736:15)
  pw:error     at CRSession.<anonymous> (/private/tmp/video-bug/node_modules/@playwright/test/lib/server/chromium/crPage.js:454:2226)
  pw:error     at CRSession.emit (node:events:394:28)
  pw:error     at /private/tmp/video-bug/node_modules/@playwright/test/lib/server/chromium/crConnection.js:223:14
  pw:error     at runNextTicks (node:internal/process/task_queues:61:5)
  pw:error     at processImmediate (node:internal/timers:437:9) +1s
  pw:protocol SEND ► {"id":123,"method":"Target.detachFromTarget","params":{"sessionId":"6401A980948767212ECEEEA36230FB55"},"sessionId":"EE6FBE1EFDB7F0FAB283C20C152B20BF"} +5ms
  pw:protocol ◀ RECV {"method":"Target.detachedFromTarget","params":{"sessionId":"EE6FBE1EFDB7F0FAB283C20C152B20BF","targetId":"F9BD2C7F183EC5F6EA6FBE651BE33BE1"}} +0ms
  pw:error Protocol error (Target.detachFromTarget): Target closed.Error
  pw:error     at /private/tmp/video-bug/node_modules/@playwright/test/lib/server/chromium/crConnection.js:202:16
  pw:error     at new Promise (<anonymous>)
  pw:error     at CRSession.send (/private/tmp/video-bug/node_modules/@playwright/test/lib/server/chromium/crConnection.js:198:12)
  pw:error     at CRSession._sendMayFail (/private/tmp/video-bug/node_modules/@playwright/test/lib/server/chromium/crConnection.js:209:17)
  pw:error     at /private/tmp/video-bug/node_modules/@playwright/test/lib/server/chromium/crPage.js:737:22
  pw:error     at runNextTicks (node:internal/process/task_queues:61:5)
  pw:error     at processImmediate (node:internal/timers:437:9) +2ms
  pw:error Error: Protocol error (Page.stopScreencast): Session closed. Most likely the page has been closed.
  pw:error     at CRSession.send (/private/tmp/video-bug/node_modules/@playwright/test/lib/server/chromium/crConnection.js:194:34)
  pw:error     at CRSession._sendMayFail (/private/tmp/video-bug/node_modules/@playwright/test/lib/server/chromium/crConnection.js:209:17)
  pw:error     at FrameSession._stopScreencast (/private/tmp/video-bug/node_modules/@playwright/test/lib/server/chromium/crPage.js:1011:59)
  pw:error     at FrameSession._stopVideoRecording (/private/tmp/video-bug/node_modules/@playwright/test/lib/server/chromium/crPage.js:993:16)
  pw:error     at Page.<anonymous> (/private/tmp/video-bug/node_modules/@playwright/test/lib/server/chromium/crPage.js:972:57)
  pw:error     at Object.onceWrapper (node:events:513:28)
  ✘  2) [Mobile Chrome] › foo.spec.js:3:1 › test (7s)
  pw:error     at Page._didClose (/private/tmp/video-bug/node_modules/@playwright/test/lib/server/page.js:167:10)
  pw:error     at CRPage.didClose (/private/tmp/video-bug/node_modules/@playwright/test/lib/server/chromium/crPage.js:197:16)
  pw:error     at CRBrowser._onDetachedFromTarget (/private/tmp/video-bug/node_modules/@playwright/test/lib/server/chromium/crBrowser.js:221:14)
  pw:error     at CRSession.emit (node:events:394:28)
  pw:error     at /private/tmp/video-bug/node_modules/@playwright/test/lib/server/chromium/crConnection.js:223:14 +0ms
```

**Comment by aslushnikov** [comment] 2021-08-12 14:28
@viart interesting. It might be that video encoding is crazy slow there; any chance you can triple or maybe quadruple timeouts and see if it passes?

**Comment by viart** [comment] 2021-08-12 14:58
@aslushnikov it's indeed related to timeouts vs slow encoding, `timeout: 5000` in the config and a lower value timeout in the selector gave me video
```
await page.waitForSelector(".navbar__title1", { timeout: 1000 });
```

**Comment by aslushnikov** [comment] 2021-08-16 10:01
@viart so so far video encoding is counted towards test timeout; so if you use video encoding, you might need to bump test timeout a bit. 

@dgozman: this is an example where fixtures tear down might require a separate timeout

**Comment by aslushnikov** [comment] 2021-08-16 10:01
I'll close this for now since it seems to be solved.

**Closed by aslushnikov** 2021-08-16 10:01 UTC
Labels: test-runner

**Comment by viart** [comment] 2021-08-16 10:30
@aslushnikov not sure that bumping timeouts is a "reliable" solution here, since it requires the test timeout to be > sum of all queries timeouts of that test (will be quite hard to come up with "non-flaky" numbers)

```
page.waitForSelector: Protocol error (Runtime.callFunctionOn): Target closed.
```
In addition, I can see this error in GH CI setup sometimes (even though the video is present), which I naively interpret as a sign of a race condition (browser is closed already but some internal playwright flow is not done yet).

**Comment by dgozman** [comment] 2021-08-19 17:44
@viart It seems like encoding video is just too slow on your machine. How many virtual CPUs do you have? I see that you pass `workers: 2`, but perhaps two workers is too much? Each worker runs a browser that has multiple processes and a video encoder, so be careful with multiple workers.

Also it might be a good idea to try tracing instead of the video. It gives you so much more and is more efficient. Here are the docs: https://playwright.dev/docs/test-configuration#record-test-trace.
