### ISSUE TITLE
[Question] Skipped tests mark as failed

### ISSUE THREAD

**Issue by judithhartmann** [microsoft/playwright#18544] opened 2022-11-03 14:14 UTC
Hey,
we have some tests that we skip conditionally, therefore the `beforeEach` and the `beforeAll` are run before these tests.
If playwright detects an error in these steps, it will fail this test. So far so good.

We have retries enabled, so when the retry of the test makes it to the `test.skip` it skips the test
In the end the test is marked as FAILED in the final results, even though it was 1 failure run, 1 skip run (success kinda).
Is this the desired behaviour? I feel like it should be marked as skipped.

**Comment by aslushnikov** [comment] 2022-11-04 10:56
This is a dupe of https://github.com/microsoft/playwright/issues/17652

**Closed by aslushnikov** 2022-11-04 10:56 UTC
