### ISSUE TITLE
[BUG] Playwright UI ignores the test.fail() call

### ISSUE THREAD

**Issue by silvenon** [microsoft/playwright#22441] opened 2023-04-17 19:55 UTC
### System info
- Playwright Version: v1.32.3
- Operating System: macOS 13.3.1
- Browser: Chromium

### Source code

- [x] I provided exact source code that allows reproducing the issue locally

**Link to the GitHub repository with the repro**

[https://github.com/silvenon/repro at 379b04a1bf5111d99caf8f86e404100d77d086aa](https://github.com/silvenon/repro/tree/379b04a1bf5111d99caf8f86e404100d77d086aa)

**Test file (self-contained)**

```js
test('has title', async ({ page }) => {
  test.fail()
  await page.goto('https://playwright.dev/');
  await expect(page).toHaveTitle(/Cypress/);
});
```

Everything is as installed by Playwright itself, no changes to the configuration.

**Steps**
- run `npx playwright test --ui`
- run the test

**Expected**

Even though the test fails, it should be marked as successful.

**Actual**

It's marked as failed. All other forms of running Playwright tests consider this test successful:

- clicking on the test using VS Code extension
- running `npx playwright test`
- even using the debug mode

But UI doesn't seem to recognize the `test.fail()` in any way (might be the same with `test.skip()` and others, I didn't try).

I'm aware that UI it's experimental, I just really like the `test.fail()` feature. 🥰

**Comment by dgozman** [comment] 2023-04-18 04:08
Looks like a duplicate of #22096.

**Closed by dgozman** 2023-04-18 04:08 UTC

**Comment by lantern-wilson** [comment] 2023-11-13 14:59
So whats the solution?

**Comment by silvenon** [comment] 2023-11-15 15:39
@lantern-wilson it's fixed, not sure in which version exactly.
