### ISSUE TITLE
[BUG] Imported variables aren't available in component tests

### ISSUE THREAD

**Issue by avendiart** [microsoft/playwright#15076] opened 2022-06-23 15:13 UTC
**Context:**
- Playwright Version: 1.24.0-alpha-jun-23-2022
- Operating System: Linux
- Node.js version: 16.14
- Browser: All

**Code Snippet**

```typescript
// theme.tsx
import { createContext, PropsWithChildren, useContext } from "react";

export type Theme = {
  colors: {
    primary: string;
  };
};

export const themeA = {
  colors: {
    primary: "blue",
  },
};

export const themeB = {
  colors: {
    primary: "grey",
  },
};

const ThemeContext = createContext<Theme | null>(null);

export const Provider = ({
  children,
  theme,
}: PropsWithChildren<{ theme: Theme }>) => (
  <ThemeContext.Provider value={theme}>{children}</ThemeContext.Provider>
);

export const useTheme = () => useContext(ThemeContext);

```

```typescript
// button.tsx
import { PropsWithChildren } from "react";
import { useTheme } from "./theme";

export const Button = ({ children }: PropsWithChildren<unknown>) => {
  const theme = useTheme();
  return (
    <button
      style={{
        background: theme?.colors.primary,
      }}
    >
      {children}
    </button>
  );
};

```

```typescript
// button.spec.tsx
import { test, expect } from "@playwright/experimental-ct-react";
import { Button } from "./button";
import { Provider, themeA, themeB } from "./theme";

test("button with theme A", async ({ mount }) => {
  const component = await mount(
    <Provider theme={themeA}>
      <Button>Test</Button>
    </Provider>
  );

  expect(await component.screenshot()).toMatchSnapshot({});
});

test("button with theme B", async ({ mount }) => {
  const component = await mount(
    <Provider theme={themeB}>
      <Button>Test</Button>
    </Provider>
  );

  expect(await component.screenshot()).toMatchSnapshot({});
});

```

**Describe the bug**
This is a very condensed example, in the real project the setup is a bit more complicated and I'm getting a different error, but I think those might be related. Expected output: both tests pass and produce valid screenshots, real output:
```
1) [chromium] › src/button.spec.tsx:5:1 › button with theme A ====================================

    ReferenceError: themeA is not defined

       5 | test("button with theme A", async ({ mount }) => {
       6 |   const component = await mount(
    >  7 |     <Provider theme={themeA}>
         |                      ^
       8 |       <Button>Test</Button>
       9 |     </Provider>
      10 |   );
```

**Comment by rwoll** [comment] 2022-06-29 18:21
Debug notes to self:

- if run on CLI, see the error:
   ```
    }) => <ThemeContext.Provider value={{
          ^

    SyntaxError: Unexpected token '<'
   ```
- if replace `<ThemeContext.Provider value={theme}>{children}</ThemeContext.Provider>` with `<div value={theme}>{children}</div>` the error goes away
- repros on 1.23 and 1.22, so does not look like a regression at the moment

**Comment by rwoll** [comment] 2022-06-29 18:26
It looks like there is a bug here based on local repro. Tentatively assigning 1.24 to investigate further. See debug notes above https://github.com/microsoft/playwright/issues/15076#issuecomment-1170338753.

**Comment by rwoll** [comment] 2022-06-29 18:29
@avendiart I narrowed it down to `ThemeContext.Provider` looking like it's breaking something within Playwright's wrapping/transforming/mapping logic. I don't have a fix or workaround at the moment. Sorry!

**Comment by yue4u** [comment] 2022-07-03 12:34
I'm also seeing `Maximum call stack size exceeded` for wrapping react component with context providers in component tests

**Comment by rwoll** [comment] 2022-07-03 16:32
See https://github.com/microsoft/playwright/issues/15325#issuecomment-1172969732 for a possible workaround.

**Comment by pavelfeldman** [comment] 2022-07-11 20:18
@avendiart 

tl/dr is that Playwright can only import components from the TSX/JSX files. It ignores everything else. So to work around this issue, one would extract code that is reused by both components and tests into a separate TS file:


```ts
// theme.ts

export type Theme = {
  colors: {
    primary: string;
  };
};

export const themeA = {
  colors: {
    primary: "blue",
  },
};

export const themeB = {
  colors: {
    primary: "grey",
  },
};
```

```tsx
// themeProvider.tsx
import { createContext, PropsWithChildren, useContext } from "react";
import type { Theme } from "./theme";

const ThemeContext = createContext<Theme | null>(null);

export const Provider = ({
  children,
  theme,
}: PropsWithChildren<{ theme: Theme }>) => (
  <ThemeContext.Provider value={theme}>{children}</ThemeContext.Provider>
);

export const useTheme = () => useContext(ThemeContext);
```

with the mixed files out of the way, it should work.

**Comment by pavelfeldman** [comment] 2022-07-26 22:45
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2022-07-26 22:45 UTC
Labels: feature-components, v1.25
