### ISSUE TITLE
[question] Font family not applied in snapshots when using Ladle and Tailwind CSS

### ISSUE THREAD

**Issue by takahashi-ukyo-lvgs** [microsoft/playwright#31591] opened 2024-07-08 11:09 UTC
## Description:
I'm experiencing an issue where the font family specified in my Tailwind CSS configuration is not being applied correctly when taking snapshots with Playwright.

### Environment:

Playwright version: 1.45.1
Ladle version: 4.1.0
Browser: Chromium, webkit
OS: macOS Ventura 13.6.6
### Steps to reproduce:

1. Set up a Ladle project with Tailwind CSS.
2. Define a custom font family in tailwind.config.ts:
``` tailwind.config.ts
fontFamily: {
  'sans': ['Noto Sans JP', 'Asap Condensed'],
},
```

3. Apply the font family globally in globals.css:
``` globals.css
html, body {
  @apply font-sans;
}
```
4. add launchOptions in playwright.config.ts:
```
use: {
  launchOptions: {
    args: ["--font-rendering-mode=font-display"],
  },
}
```

5. Run pnpm ladle serve to start the Ladle development server.
6. Run npx playwright test -u to update snapshots.
### Expected behavior:

Snapshots should be taken with the specified font family (Noto Sans JP in this case) applied.

### Actual behavior:

Snapshots are taken with a default font family, as if the custom font family is not being loaded or applied.

### Additional information:

- The font family is applied correctly when viewing the Ladle stories in the browser.
- I have tried the following solutions without success:
  - Using page.waitForFunction to wait for the font to load.
  - Using page.waitForLoadState('networkidle') to wait for the page to fully load.
  - Adding an explicit wait time with page.waitForTimeout.
  - Clearing the browser cache and Ladle development server cache.
- My test code is based on the example provided in the Ladle documentation: https://ladle.dev/blog/visual-snapshots/
### Possible causes:

- Playwright might be taking the snapshot before the font has fully loaded and rendered.
- There might be an issue with how Ladle or Tailwind CSS is handling font loading in the context of Playwright tests.

I would appreciate any help in resolving this issue.

**Comment by mxschmitt** [comment] 2024-07-08 14:15
I'm not familiar with Ladle or Tailwind. Would it be possible to share a repository which we can clone with expected and actual outcomes?

**Comment by takahashi-ukyo-lvgs** [comment] 2024-07-09 02:38
@mxschmitt
> I'm not familiar with Ladle or Tailwind. Would it be possible to share a repository which we can clone with expected and actual outcomes?



Thanks for your comment!

Here is the sample repository:
https://github.com/takahashi-ukyo-lvgs/sample-playwright/tree/main

Please let me know if you have any questions.

**Comment by yury-s** [comment] 2024-07-10 21:09
I can't reproduce it locally, perhaps there is a race. The screenshot that the test produces matches what is rendered in the browser (and does not match the expectation), i.e. `font-family "Noto Sans JP", "Asap Condensed"`.

> Playwright might be taking the snapshot before the font has fully loaded and rendered.
> There might be an issue with how Ladle or Tailwind CSS is handling font loading in the context of Playwright tests.

Try extracting relevant pieces of the web page and CSS styles into a simple test to eliminate potential problems with landle and tailwind.

**Comment by yury-s** [comment] 2024-07-15 19:27
Closing as we cannot act on this without a reliable repro. Feel free to open a new issue if you can extract a minimal example that doesn't depend on Ladle/Tailwind.

**Closed by yury-s** 2024-07-15 19:27 UTC
