### ISSUE TITLE
[Question] Error: Error: elementHandle.evaluate: TypeError: Map is not a constructor at parseEvaluationResultValue2 

### ISSUE THREAD

**Issue by nelypetrova** [microsoft/playwright#16041] opened 2022-07-29 06:21 UTC
Hi guys, 
After an update, I have an issue with some tests that I am pretty sure they were written correctly and they successfully passed. Now, I don't know what I did but when I run the tests they failed with an error Error: Error: elementHandle.evaluate: TypeError: Map is not a constructor
    at parseEvaluationResultValue2 (<anonymous>:48:84)
   It happened on expect state. Here's the test:
   
![image](https://user-images.githubusercontent.com/78469204/181695324-2ae15a74-9df0-4174-94b2-8ef8ab05ccbc.png)
![image](https://user-images.githubusercontent.com/78469204/181695756-761ab4e8-348f-45a7-844a-221c55bd4540.png)

Even the tests from playwright 1.24.1 failed:
![image](https://user-images.githubusercontent.com/78469204/181698780-04daa5cb-90c1-4195-bc41-9b320a3e9ad1.png)

**Comment by pavelfeldman** [comment] 2022-07-29 16:24
The site that you are testing is overwriting the built-in `Map` class.

**Comment by nelypetrova** [comment] 2022-07-29 17:01
Thank you for the answer! 
I think the developers didn't make changes in this page. The tests passed successfully not long time ago. Sadly, even your demo example tests failed. Am I missing something to install?
![image](https://user-images.githubusercontent.com/78469204/181808556-9c9a215b-9818-455f-9f30-5393d6eb3f5e.png)

**Comment by pavelfeldman** [comment] 2022-07-29 18:39
Those seem to be unrelated. In the first case, Map object is overwritten. This is bad, because it would break the page itself should it be using Maps, so you can consider that page having a bug. A developer can evaluate 'Map' in console and see what's going on there.

The second one seems unrelated, I can't reproduce it, I'd need exact steps to repro. Most likely you need to run `npx playwright install` after you've update Playwright.

**Comment by nelipetrova32** [comment] 2022-08-01 08:44
Thank you very, very much! <3

**Comment by pavelfeldman** [comment] 2022-08-04 17:40
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2022-08-04 17:40 UTC
Labels: v1.25
