### ISSUE TITLE
[Question]Playwright codegen is not recording the steps with iframe web app

### ISSUE THREAD

**Issue by helapw** [microsoft/playwright#20642] opened 2023-02-05 19:56 UTC
Hi, I have a web app that is using frame on the login page, after login it will show the page with 3 iframes which has top page iframe, left side navigation iframe and right side iframe. I used playwright codegen to record the steps, it is able to record the login steps, but it is not recoding anything after logged in. Below is the code that playwright codegen records for the login steps only.

import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://url);
  await page.frameLocator('#authFrm').locator('#userName').fill('admin');
  await page.frameLocator('#authFrm').locator('#userName').press('Tab');
  await page.frameLocator('#authFrm').locator('input[name="pwd"]').fill('password');
  await page.frameLocator('#authFrm').locator('input[name="pwd"]').press('Enter');
});

Also the playwright browser is not responding after logged in. I clicked the left side navigation link but the right side page is not loading that link. If I stop recording then the right side page is loading the link from the left side navigation link.
Anybody know why codegen is not recording the steps?

**Comment by mxschmitt** [comment] 2023-02-06 15:52
Can you share reproduction steps which demonstrate the issue? What you expect and whats actually happening? This would help a ton, otherwise we cannot act on it.

**Comment by HinaSharma16** [comment] 2023-02-09 03:45
HI Team, 
Am facing the same issue. 
Steps : 
1. Started codegen using "playwright codegen" 
2. In the browser window that opened, entered the url and proceeded with the next steps.  
3. Playwright inspector is recording all the steps till here. 
4. Once I am logged in , I try to click the elements on the page which are in iframe. 
5.Expected Result : Playwright inspector should record these clicks , fills as well. i.e. auto locate the iframe and its elements therein. 
Actual Result : There are no steps recorded on Inspector for the elements being acted upon which are in iframe. 

The application can only be accessed within my organization therefore cannot share the url.  Please do let me know if you need any further information.

**Comment by mxschmitt** [comment] 2023-02-09 10:36
Without a repro we cannot act on it unfortunately, sorry! This also sounds like a different issue.

**Comment by HinaSharma16** [comment] 2023-02-09 12:37
Thanks a lot for your response. 
I feel the issue is the same as codegen fails to record anything once iframe is on the page. 
Would you be able to please provide a demo video or some link to documentation where the webpage has iframe and codegen is recording the tests. 
Test Generator documentation does not have example for iframe.

**Comment by HinaSharma16** [comment] 2023-02-09 18:34
HI @mxschmitt , luckily I was able to reproduce the same on https://the-internet.herokuapp.com/iframe. as well. 
Any text entered in the input box / or a click on the input box is not recorded in the inspector window. 

Please note, I am using Mac device. Below are the playwright with Python. 
Please let me know if any logs are required.  Also, if you feel my concern is not related to the original issue of the ticket,  I can create a new one. 

Do let me know if we can connect over zoom/webex - so that I can show you the problem.

**Comment by mxschmitt** [comment] 2023-02-10 19:33
Works for me, maybe you are on some special enterprise environment which some policies configured? I'm also on a mac. for me it recorded the following:

```ts
  test('test', async ({ page }) => {
    await page.goto('https://the-internet.herokuapp.com/iframe');
    await page.frameLocator('iframe[title="Rich Text Area"]').getByText('Your content goes here.').click();
    await page.frameLocator('iframe[title="Rich Text Area"]').locator('#tinymce').fill('Hello its me and I was wondering who I would like to be.');
    await page.frameLocator('iframe[title="Rich Text Area"]').locator('#tinymce').press('Enter');
    await page.frameLocator('iframe[title="Rich Text Area"]').locator('#tinymce').fill('Hello its me and I was wondering who I would like to be.\n\nHi and again.');
  });
```

**Comment by aslushnikov** [comment] 2023-02-14 16:17
Looks like we failed to repro this, so there's no way we can act upon this. I'll speculatively close this. 

If you have a better repro, or you think we still can be somehow helpful to you, then please do not hesitate to create a new issue.

**Closed by aslushnikov** 2023-02-14 16:17 UTC
Labels: triaging

**Comment by VINTX2** [comment] 2023-08-02 16:36
I can reproduce this like explained [above](https://github.com/microsoft/playwright/issues/20642#issuecomment-1423580091).
But only in Playwright Firefox. Chromium works.

**Comment by nikulk2992-jpg** [comment] 2026-04-15 00:13
I ran into this issue with an enterprise application that embeds Sigma Computing workbooks in cross-origin iframes. Codegen couldn't record any interactions inside the iframe.

I documented a working workaround that uses `page.evaluate()` to inject a custom recording overlay into all frames (including iframes). Key techniques:

- Poll all pages and frames, inject recorder via `page.evaluate()` (bypasses CSP)
- Track which frame each action belongs to using frame paths
- MutationObserver to detect floating menus (context menus, dropdowns) inside iframes
- Replay uses frame path resolution to navigate into the correct iframe
- Use Locators instead of ElementHandles to avoid stale references in dynamic iframes

Full writeup with code examples: https://github.com/nikulk2992-jpg/playwright-iframe-recorder

Tested with Playwright 1.59+ on Sigma Computing embeds, multi-tab navigation, and context menus with submenus inside iframes.
