### ISSUE TITLE
[BUG]: [component-testing]Cannot find module 'playwright-core/cli'

### ISSUE THREAD

**Issue by theniceangel** [microsoft/playwright#21088] opened 2023-02-22 05:01 UTC
**Context:**
- Playwright Version: [1.31.0]
- Operating System: [Mac]
- Node.js version: [v14.21.2]

System:
    OS: macOS 12.6.2
    Memory: 30.52 MB / 16.00 GB
  Binaries:
    Node: 14.21.2 - ~/.nvm/versions/node/v14.21.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.21.2/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.21.2/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash

**Describe the bug**

Bump `@playwright/experimental-ct-vue` to `v1.31.0`, run `playwright install`, 
Error occurs: 'Cannot find module 'playwright-core/cli',
I guess `@playwright/experimental-ct-vue` add a 'cli.js' file which has a conflict with 'cli.js' in `@playwright/test`, causing the location of `@playwright/test` is nested into `node_modules` of `@playwright/experimental-ct-vue`, not in the root of the project.

<img width="480" alt="image" src="https://user-images.githubusercontent.com/25956811/220526404-0cb59644-b74c-439c-b075-4a26ebc8ec62.png">

**Comment by theniceangel** [comment] 2023-02-22 05:04
As the steps of [install-playwright-test-for-components](https://playwright.dev/docs/test-components#step-1-install-playwright-test-for-components-for-your-respective-framework) in the official docs, `Cannot find module 'playwright-core/cli'` error occured

**Comment by mxschmitt** [comment] 2023-02-22 12:03
I was not able to reproduce this when creating a new project. Do you create it inside an existing project?

Can you check your package manager's lock file that no different versions of `@playwright/test` `@playwright/experimental-ct-vue` or `playwright-core` are installed? The project itself should just have `@playwright/experimental-ct-vue` as a dependency.

**Comment by yury-s** [comment] 2023-02-22 23:45
I cannot reproduce it either. Can you share the project where it is failing?

**Comment by theniceangel** [comment] 2023-02-23 01:21
I create the project just follow the step of [install-playwright-test-for-components](https://playwright.dev/docs/test-components#step-1-install-playwright-test-for-components-for-your-respective-framework), I can upload `package-lock.json` which created in the process of initialising the repo. There is no versions conflict of `@playwright/test` and `playwright-core`.
[package-lock.json.zip](https://github.com/microsoft/playwright/files/10809548/package-lock.json.zip)

**Comment by theniceangel** [comment] 2023-02-23 01:25
At the `line 161`, the dependencies created by npm is so werid.
<img width="782" alt="image" src="https://user-images.githubusercontent.com/25956811/220801383-1be54042-b43f-4d30-9d03-de0b16bd2398.png">
`@playwright/test` and `playwright-core` are not installed in the root of node_modules, although there is no other versions collision of both

**Comment by theniceangel** [comment] 2023-02-23 01:30
[package.json.zip](https://github.com/microsoft/playwright/files/10809569/package.json.zip)
This is the package.json created by guidance

**Comment by theniceangel** [comment] 2023-02-23 01:30
<img width="270" alt="image" src="https://user-images.githubusercontent.com/25956811/220802100-b4e1fae2-33bc-4c53-836c-52946dfb6485.png">

**Comment by yury-s** [comment] 2023-02-24 01:19
> npm: 6.14.17 - ~/.nvm/versions/node/v14.21.2/bin/npm

Can you update to the latest npm (9.5.1) and try creating a new project following [install-playwright-test-for-components](https://playwright.dev/docs/test-components#step-1-install-playwright-test-for-components-for-your-respective-framework)?

**Comment by theniceangel** [comment] 2023-02-24 02:01
> > npm: 6.14.17 - ~/.nvm/versions/node/v14.21.2/bin/npm
> 
> Can you update to the latest npm (9.5.1) and try creating a new project following [install-playwright-test-for-components](https://playwright.dev/docs/test-components#step-1-install-playwright-test-for-components-for-your-respective-framework)?

It works now when bumping npm(9.5.0), I told my teammate to create a new project using node14.20.1, it also fails, so npm issues?

**Comment by yury-s** [comment] 2023-02-24 02:16
Yes, playwright won't work with npm earlier than 7 (if I recall correctly it has to do with peer dependencies support). So make sure you use recent npm.

**Comment by theniceangel** [comment] 2023-02-24 06:40
> Yes, playwright won't work with npm earlier than 7 (if I recall correctly it has to do with peer dependencies support). So make sure you use recent npm.

For some legacy reasons, I can not bump node versions, since node 14.20.1 use npm 6, and the playwright claim supporting node >= 14
<img width="487" alt="image" src="https://user-images.githubusercontent.com/25956811/221109840-31870a22-b860-430a-88af-956affc6e53a.png">
Is there any other solutions?

**Comment by yury-s** [comment] 2023-02-27 19:15
You can manually update npm via `npm i -g npm@latest`. Will that work?

**Comment by yury-s** [comment] 2023-03-01 18:00
We can reproduce it with npm 6:

```
Downloading browsers (npx playwright install)…
Cannot find module 'playwright-core/cli'
Require stack:
- /Users/yurys/sandbox/nnn/node_modules/@playwright/experimental-ct-vue/cli.js
Error: Command failed: npx playwright install
    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at executeCommands (/Users/yurys/.npm/_npx/83466/lib/node_modules/create-playwright/lib/index.js:4519:39)
    at Generator.run (/Users/yurys/.npm/_npx/83466/lib/node_modules/create-playwright/lib/index.js:4670:5)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /Users/yurys/.npm/_npx/83466/lib/node_modules/create-playwright/lib/index.js:4938:3 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 83486,
  stdout: null,
  stderr: null
}

```

**Comment by mxschmitt** [comment] 2024-09-16 08:50
This seems to be not relevant anymore with modern Node.js / NPM versions. Closing for now. Feel free to re-file if you still encounter bugs.

**Closed by mxschmitt** 2024-09-16 08:50 UTC
Labels: v1.31
