### ISSUE TITLE
[BUG] Chaning CSS locators causing DOM exception "not a valid selector" when parent

### ISSUE THREAD

**Issue by nikolay-yavorovskiy** [microsoft/playwright#14488] opened 2022-05-30 22:21 UTC
**Context:**
- Playwright Version: 1.20.2
- Operating System: Windows 7, Mac OS Monterey
- Node.js version: v16.6.2
- Browser: Chromium

**Code Snippet**

```javascript
const {chromium} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
  await page.setContent(`
    <div class="modal-class">
        <div class="table height:8">
            <div class="table-column-header" />
            <div class="table-body" />
        </div>
    </div>
  `);
  
  const MODAL_CLASS = 'modal-class'
  const TABLE_CLASS = 'table'
  const TABLE_COLUMN_HEADER_CLASS = 'table-column-header'
  const TABLE_BODY_CLASS = 'table-body'
  
  await page.locator(`.${MODAL_CLASS}`).locator(`.${TABLE_BODY_CLASS}`).waitFor({ state: 'visible' }); // throws exception "Unexpected token "8" while parsing a selector"
})();
```

**Describe the bug**

Chaning one CSS locator after another causing DOM exception "not a valid selector" if a parent of the second locator has some not allowed characters like `:`. Probably some string sanitazing should be done under the hood to prevent this error from happening,

Please, help with this issue, it's quite critical for our application tests.

**Comment by pavelfeldman** [comment] 2022-05-31 05:48
I can't reproduce this failure. Your snippet seems to be wrong - self-closing divs will result in zero-size elements, so they are invisible, hence it'll stuck. But when I add content to the table-body div it works fine. Note that you don't close the browser in the end, so the script will keep hanging.

**Comment by pavelfeldman** [comment] 2022-06-06 21:20
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by nikolay-yavorovskiy** [comment] 2022-06-12 13:46
Yeah. example was a bit incorrect, i wrote it without checking.
But the issue still exists.
There's an example from the trace.
Selector that I'm trying to find is correct.
`.slim-table[data-test-id="profile-layout-table"] >> .slim-table-body`
![image](https://user-images.githubusercontent.com/89914399/173236261-7aa99d40-6329-4535-bd98-d04c02d1c7b9.png)

**Closed** 2022-06-12 16:39 UTC
Labels: v1.23
