### ISSUE TITLE
[BUG] Screenshots for Allure not attached

### ISSUE THREAD

**Issue by AndreyMelnichenko** [microsoft/playwright#9109] opened 2021-09-23 13:47 UTC
**Context:**
- Playwright Version: [1.15]
- Operating System: [Ubuntu 20.04 LTS]
- Node.js version: [14.17.6]
- Browser: [Chromium, Firefox, WebKit]
- Extra: I am using Playwright + native test runner + Allure + Moon

**Here is short snapshot of project**

https://github.com/AndreyMelnichenko/playwright-test-ts

**Describe the bug**

For Moon test execution Allure or Playwright can't create screenshot and attach into report
For local run all works fine
See source code
https://github.com/AndreyMelnichenko/playwright-test-ts

**Comment by mxschmitt** [comment] 2021-09-23 13:49
This seems a duplicate of #8379. Its currently not yet officially supported to connect to an external Playwright Server instance. So using Allure etc. might be incompatible and result in not expected behaviour.

**Comment by AndreyMelnichenko** [comment] 2021-09-23 13:53
@mxschmitt 
In this case why if I am execute locally all works fine with same reporter
screen and trace attached as expected

**Comment by mxschmitt** [comment] 2021-09-23 14:00
Are we talking about the options in the config
```
        screenshot: 'only-on-failure',
        trace: 'retain-on-failure',
```
or about this?

https://github.com/AndreyMelnichenko/playwright-test-ts/blob/bfc6218bac4e2152d8b36c1f8227b59ffea1fe97/test/e2e/Moon/SetupBrowsers.spec.ts#L9

**Comment by AndreyMelnichenko** [comment] 2021-09-23 14:18
@mxschmitt 
about config settings of course)
buy the way in previous project I've used Java+Selenium+Allure I could attach screen in any step I want

**Comment by mxschmitt** [comment] 2021-09-23 14:42
Yeah this is not supported with a custom setup for now. Merging into https://github.com/microsoft/playwright/issues/8379

**Closed by mxschmitt** 2021-09-23 14:42 UTC
Labels: triaging
