### ISSUE TITLE
[BUG] [WSL2] page.goto: Navigation failed because page crashed! (basic test, Getting Started)

### ISSUE THREAD

**Issue by immilev** [microsoft/playwright#10213] opened 2021-11-10 12:36 UTC
**Context:**

Following the Gettting Started steps results in failed tests.

- Playwright Version:  @playwright/test@1.16.3
- Operating System: Ubuntu 20.04.2 LTS 
- Node.js version: v16.13.0 (LTS)
- Browser: Chromium, WebKit
- Extra: WSL2, Windows 10.0.19043 N/A Build 19043

## System:
 - OS: Linux 4.4 Ubuntu 20.04.2 LTS (Focal Fossa)
 - Memory: 6.41 GB / 15.91 GB
 - Container: Yes
## Binaries:
 - Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
 - npm: 8.1.3 - ~/.nvm/versions/node/v16.13.0/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash

**Code Snippet**

```javascript
const { test, expect } = require('@playwright/test');

test('basic test', async ({ page }) => {
      await page.goto('https://playwright.dev/');
      const title = page.locator('.navbar__inner .navbar__title');
      await expect(title).toHaveText('Playwright');
});
```

**Describe the bug**

The test succeed in Firefox and fail in Chromium and WebKit.

npx playwright test --browser=all

Running 3 tests using 2 workers

  ✘  [chromium] › tests/foo.spec.js:3:1 › basic test (14s)
  ✓  [firefox] › tests/foo.spec.js:3:1 › basic test (7s)
  ✘  [webkit] › tests/foo.spec.js:3:1 › basic test (3s)

  1) [chromium] › tests/foo.spec.js:3:1 › basic test ===============================================

    page.goto: Navigation failed because page crashed!
    =========================== logs ===========================
    navigating to "https://playwright.dev/", waiting until "load"
    ============================================================

      2 |
      3 | test('basic test', async ({ page }) => {
    > 4 |       await page.goto('https://playwright.dev/');
        |                  ^
      5 |       const title = page.locator('.navbar__inner .navbar__title');
      6 |       await expect(title).toHaveText('Playwright');
      7 | });

        at /mnt/c/imilev/accountconnect/tests/foo.spec.js:4:18

  2) [webkit] › tests/foo.spec.js:3:1 › basic test =================================================

    page.goto: Unacceptable TLS certificate
    =========================== logs ===========================
    navigating to "https://playwright.dev/", waiting until "load"
    ============================================================

      2 |
      3 | test('basic test', async ({ page }) => {
    > 4 |       await page.goto('https://playwright.dev/');
        |                  ^
      5 |       const title = page.locator('.navbar__inner .navbar__title');
      6 |       await expect(title).toHaveText('Playwright');
      7 | });

        at /mnt/c/imilev/accountconnect/tests/foo.spec.js:4:18

  2 failed
    [chromium] › tests/foo.spec.js:3:1 › basic test ================================================
    [webkit] › tests/foo.spec.js:3:1 › basic test ==================================================
  1 passed (15s)

$ curl -k -v https://playwright.dev -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 185.199.109.153:443...
* TCP_NODELAY set
* Connected to playwright.dev (185.199.109.153) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [4047 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=playwright.dev
*  start date: Sep 28 23:01:58 2021 GMT
*  expire date: Dec 27 23:01:57 2021 GMT
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x7fffd78f7820)
} [5 bytes data]
> GET / HTTP/2
> Host: playwright.dev
> user-agent: curl/7.68.0
> accept: */*
>
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [177 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
} [5 bytes data]
< HTTP/2 200
< server: GitHub.com
< content-type: text/html; charset=utf-8
< last-modified: Tue, 09 Nov 2021 22:17:47 GMT
< access-control-allow-origin: *
< etag: "618af38b-37bf"
< expires: Wed, 10 Nov 2021 12:26:04 GMT
< cache-control: max-age=600
< x-proxy-cache: MISS
< x-github-request-id: 2A30:DCD4:1DD47A:21542B:618BB804
< accept-ranges: bytes
< date: Wed, 10 Nov 2021 12:38:59 GMT
< via: 1.1 varnish
< age: 89
< x-served-by: cache-lon4251-LON
< x-cache: HIT
< x-cache-hits: 1
< x-timer: S1636547939.240390,VS0,VE0
< vary: Accept-Encoding
< x-fastly-request-id: c101f8725abb0c0e62b8e5f822c2afb6dd14f948
< content-length: 14271
<
{ [1008 bytes data]
100 14271  100 14271    0     0  75507      0 --:--:-- --:--:-- --:--:-- 75507
* Connection #0 to host playwright.dev left intact

**Comment by aslushnikov** [comment] 2021-11-11 09:58
@immilev can you please run with `DEBUG=*browser*` environment variable?

```bash
DEBUG=*browser* npx playwright test --browser all
```

**Comment by immilev** [comment] 2021-11-15 10:59
Please find the output attached.

Cheers!

**Comment by immilev** [comment] 2021-11-15 11:03
[browser.all.out.zip](https://github.com/microsoft/playwright/files/7538135/browser.all.out.zip)

**Comment by JoelEinbinder** [comment] 2021-11-18 20:55
Looks like this check fails in chromium: https://source.chromium.org/chromium/chromium/src/+/main:base/memory/platform_shared_memory_region_posix.cc;l=99

Some kind of permissions issue in your container?

**Comment by dgozman** [comment] 2021-11-24 17:37
@immilev Unfortunately, logs did not help much. There is a crash in Chromium, hopefully it will be fixed upstream. WebKit complain about display, perhaps you could try running with `xvfb-run`? For example,
```bash
xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npx playwright test
```

**Comment by pavelfeldman** [comment] 2021-11-29 17:07
I don't think we've confirmed any of that working under WSL2. Is there a reason you don't use windows native version?

**Comment by pavelfeldman** [comment] 2022-01-04 18:25
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Closed by pavelfeldman** 2022-01-04 18:25 UTC
Labels: v1.18
