### ISSUE TITLE
[REGRESSION]: WebKit 16.4 is very slow

### ISSUE THREAD

**Issue by creage** [microsoft/playwright#19108] opened 2022-11-28 11:15 UTC
**Context:**
- GOOD Playwright Version: v1.27.1
- BAD Playwright Version: v1.28, v1.28.1
- Operating System: Windows
- Extra: WebKit only

**Describe the bug**
We see huge performance degradation on WebKit 16.4 comparing to 16.0, which was released with Playwright 1.28.

Tests are executing much slower - page actions like clicks, typing, mouse moves are very slow, leading to most of our tests fail due to timeouts. We don't have such issues on Playwright 1.27.1, which uses WebKit 16.0.

**Comment by fujii** [comment] 2022-11-28 19:55
FWIW, upstream WebKit WinCairo port is observing performance drop for text rendering caused by Cairo 1.17.6. https://bugs.webkit.org/show_bug.cgi?id=248299

**Comment by creage** [comment] 2022-12-22 08:25
Any news on this issue?

**Comment by Kane-Go** [comment] 2023-01-23 06:07
> Any news on this issue?

**Comment by sizmos** [comment] 2023-01-24 23:48
Mine aren't failing, though execution times are doubling, going from ~1 min per test to ~2 min per test, have reverted to 1.27.1 from 1.29

**Comment by mxschmitt** [comment] 2023-01-25 17:16
Not aware of any other Playwright bug reports. @fujii do you know if there is an upstream WebKit bug for it?

**Comment by fujii** [comment] 2023-01-26 06:26
No idea. I've observed no performance regression in upstream WebKit side.

**Comment by sizmos** [comment] 2023-01-26 23:43
Just to note, the slowness is when running against the docker image: mcr.microsoft.com/playwright:v1.29-focal,
running locally on mac takes ~20 seconds, 1.27.1: ~1 min, 1.29: ~2min.
All of the above times are in headless mode

**Comment by yury-s** [comment] 2023-02-03 18:24
Please attach a test case where this performance degradation happens so that we can run it locally.

**Comment by mxschmitt** [comment] 2023-02-09 10:33
We'll close it for now since we don't have a clear repro. If you are affected by it, and have a codebase which runs in some Playwright version e.g. 30 seconds and in a more recent version 1:30min, then feel free to file a new issue, so we can take a look and find the cause. Happy to dig into it.

**Closed by mxschmitt** 2023-02-09 10:33 UTC
Labels: triaging
