### ISSUE TITLE
[BUG]: Page object is stale after website action doing window.location.reload

### ISSUE THREAD

**Issue by thnk2wn** [microsoft/playwright#22276] opened 2023-04-07 20:47 UTC
### System info
- Playwright Version: 1.32.1
- Operating System: MacOS Ventura 13.3 (22E252) local, Linux CI
- Browser: Chrome 112.0.5615.49 (Official Build) (x86_64) locally

### Source code
I'll try to create a sample app repo, deployed website, and sample app test repos though that'll be a lot of work. In the meantime, here's the gist of the reproduction. A test uses a [page object model](https://playwright.dev/docs/pom) to click a website link and that link triggers a `window.location.reload` where the state on the page is different afterwards. The trace shows everything fine within the POM during and just after the reload but back at the test the state of the page object is the stale version prior to the reload.

The test looks like this. It uses a [page object model](https://playwright.dev/docs/pom) to click on a website link that ends up doing a `window.location.reload()`.

```typescript
test.describe('impersonate', () => {
  test.use({storageState: AdminAuthState});

  test('impersonate profile set correctly @impersonate', async ({
    page,
  }, testInfo) => {
    const impersonateName = 'Craig';

    const navMenu = new NavMenu(page);
    const result = await navMenu.impersonate(impersonateName);

    // These all pass fine:
    expect(result).toBeTruthy();
    expect(result.name).toBeTruthy();
    expect(result.name).toContain(impersonateName);

    // Page is often stale at this point, regardless of how we access it (original page, navMenu.page etc.)
    // There's page.reload() but the web app already did that.
    // We just want Playwright's page object to be refreshed with the current state of the DOM.
    const page2 = result.page;

    // Take action on the page to verify impersonation, pulling up profile:
    await page2.locator(header.profile.accessor).scrollIntoViewIfNeeded();
    await page2.locator(header.profile.accessor).click({timeout: 5000});

    // Fails because the page state is stale as it was before the page was reloaded
    await page2
      .locator(header.profile.userDisplayName)
      .getByText(result.name)
      .waitFor({timeout: 10000});
  });
});
```

The page object model looks like this:

```typescript
/* eslint-disable node/no-unpublished-import */
import {Page, Locator} from '@playwright/test';
import {BasePage} from '../base-page';
import {logInfo} from '@support/util/log';

export interface ImpersonateResult {
  name: string;

  page: Page;
}

export class NavMenu extends BasePage {
  private readonly impersonateLink: Locator;

  constructor(page: Page) {
    super(page);
    this.impersonateLink = page.locator('some-nav-selector');
  }

  async impersonate(name: string): Promise<ImpersonateResult> {
    logInfo('Clicking impersonate nav menu link');
    await this.impersonateLink.click();

    const popover = this.page.locator('some-popover-selector');
    await popover.waitFor();

    const memberContainer = popover.locator('some-container-selector');
    await memberContainer.waitFor();

    const member = memberContainer.locator('input[type="text"]');
    await member.waitFor();
    await member.focus();

    logInfo(`Searching for member '${name}'`);
    await member.fill(name);

    logInfo(`Waiting for results for '${name}'`);
    const toClick = memberContainer.locator('some-item-selector').first();

    const toImpName = await toClick.locator('member-name').first().innerText();
    logInfo(`Selecting the option '${toImpName}'`);

    await toClick.scrollIntoViewIfNeeded();

    // This triggers a window.location.reload() in the web app under test:
    await toClick.click();

    logInfo(`Waiting for reload of ${this.page.url()} for '${toImpName}'`);
    this.waitForReload();

    return {
      name: toImpName,
      page: this.page,
    };
  }

  private async waitForReload() {
    const start = performance.now();

    try {
      // We can't use waitForEvent or waitForLoadState because the load state has already happened on original page.
      // Even though the page was reloaded, we can't seem to wait for those events to happen again on the page.
      // eslint-disable-next-line playwright/no-wait-for-timeout
      await this.page.waitForTimeout(6000);
    } catch (e) {
      logInfo(e);
    }

    const duration = performance.now() - start;
    logInfo(`Page reload took ${duration} ms`);
  }
}
```

**Steps**
- Run the test that triggers a website action via a POM resulting in `window.location.reload` that modifies state on the page

The POM may be irrelevant and just a larger issue/question around how to test a page that was reloaded outside PW.

**Expected**
After the POM action the calling test DOM state and screenshots in trace file show the state of the page after it was reloaded.

**Actual**
Often (but not always), the screenshots in trace and the state back in the test show the state as it was before the page was reloaded by the website under test. This results in the test failing as expectations fail with the old state. This tends to happen more in headless mode when run via CI.

The screenshot and state within the POM show the correct state leading up to, during, and just after the action that triggered the reload.

## Questions
- Should this work? 
- How to test a reload scenario?
- Does the page object needed to be recreated or refreshed "manually" and if so, how?

**Comment by pavelfeldman** [comment] 2023-04-07 22:32
> Often (but not always), the screenshots in trace and the state back in the test show the state as it was before the page was reloaded by the website under test

What do you mean by 'state back in the test'?

There is nothing special about reload in Playwright, you can keep using your page and there is no need to recreate the pom. It looks like your page is not reloaded as a result of your operation, so maybe there is a race condition in the test or a bug in the page.

**Comment by thnk2wn** [comment] 2023-04-10 14:44
The page is reloaded and the screenshots, state, and assertions in the POM all indicate that in the trace and output, and app logs.

After the POM triggers the action resulting in a reload, the screenshots, state, and assertions back in the test all have the page state as it was prior to the reload.

If there's somewhere private I can upload the trace, I can send that if it helps. 

A redacted repro will take some time with website source, deployed public website, and test source but can try to put together when time permits.

**Comment by pavelfeldman** [comment] 2023-04-12 12:33
> The page is reloaded and the screenshots, state, and assertions in the POM all indicate that in the trace and output, and app logs.

> After the POM triggers the action resulting in a reload, the screenshots, state, and assertions back in the test all have the page state as it was prior to the reload.

I'm reading those two as directly contradicting. One one hand you say page is reloaded and screenshots reflect that, on the other you are saying they are as they were before reload (not sure if expected or unexpected). Also still not sure what "state" you are talking about as Playwright locators are not stateful.

Is your expectation that we do something to your POMs on reload? Playwright test is just a program, we don't chanfe user objects at will, it would be hard to manage. This thread is now long and I still am not sure what the problem is. Please allow me to close it and please file a new issue following the template that we can repeat locally to make sure we are on the same page.

**Closed by pavelfeldman** 2023-04-12 12:33 UTC
Labels: triaging
