### ISSUE TITLE
[BUG?] Missing trace info for failed/flaky tests

### ISSUE THREAD

**Issue by alex-vungle** [microsoft/playwright#23248] opened 2023-05-24 01:38 UTC
### System info
- Playwright Version: v1.34.1, v1.34.2
- Operating System: macOS
- Browser: Chromium
- Other info:

### Repro Steps:

1. Run a failed case locally with this command: `npx playwright test --workers 1 --trace on`
2. Open the trace file with the Trace viewer;

**Expected**
1. The trace viewer should be able to show detailed step and related page screenshots;

**Actual**
1. Can't find any page screenshots/detailed steps in the trace view;
![Screenshot 2023-05-24 at 09 42 44](https://github.com/microsoft/playwright/assets/42924996/2cf4a645-b6cd-41f4-a69d-1aed9eb25877)

This issue is reproducible reproducible since Playwright version to v1.34.1. It's not reproducible on v1.33.0. Pls check the trace files I attached in below(Same failed case on different Playwright version):

[trace_v1.34.1.zip](https://github.com/microsoft/playwright/files/11549611/trace_v1.34.1.zip)
[trace_v1.33.0.zip](https://github.com/microsoft/playwright/files/11549612/trace_v1.33.0.zip)

**Comment by aslushnikov** [comment] 2023-05-24 22:02
This seems to be a duplicate of https://github.com/microsoft/playwright/issues/23220 - let's merge it there.

Could you please also post a script that generates a broken trace for 1.34 and non-broken trace in 1.33?

**Closed by aslushnikov** 2023-05-24 22:02 UTC
