### ISSUE TITLE
[Question] How to debug `Internal error: worker process exited unexpectedly (code=null, signal=SIGSEGV)`

### ISSUE THREAD

**Issue by oa-bcbs** [microsoft/playwright#27210] opened 2023-09-20 15:15 UTC
Hi,
The tests run seamlessly in local. 
I'm trying to run tests in azure pipeline in Linux build agent, but multiple tests are failing with ` Internal error: worker process exited unexpectedly (code=null, signal=SIGSEGV)`. I cannot see anything else in logs. I understand that reason might be many things, but I have to identify the reason and change built or pipeline if needed. **What are the recommended ways to debug this issue?** 
PS: Wrapping with try catch didn't give any additional information.
There's no unhandled errors but Even if there're unhandled errors, I can see them in logs in local
![image](https://github.com/microsoft/playwright/assets/144924260/6319c818-264d-4558-ac77-a8b368fb4898)

**Comment by aslushnikov** [comment] 2023-09-21 00:36
@oa-bcbs  it looks like node.js process is actually crashing; from the top of my head, here are a few things to try debug this further:

- Do you use any native dependencies? If yes, they might have a bug that causes the crash; try dropping them and see if it helps.
- There's also [some helper node.js module that can help](https://www.npmjs.com/package/segfault-handler) - i'd try using it
- The other option would be to download (or compile?) a debug build of node.js and run tests with it
- I would try to build a smaller reproducible and file it to the node.js repository

I'll close this since there's no action from the Playwright team here, but please feel free to file new issues if you think we can still be helpful!

**Closed by aslushnikov** 2023-09-21 00:36 UTC
