### ISSUE TITLE
[Question] Screenshot timeouts on background tab when using Chrome headful

### ISSUE THREAD

**Issue by DonMcNamara** [microsoft/playwright#16307] opened 2022-08-05 15:19 UTC
While automating some headful functional tests with Chrome, I'm seeing some screenshots (on tabs in the background) timeout. I suspect this is a Chrome issue caused by some sort of throttling, but I thought I would start here to see if someone else has additional ideas. Headful mode is required for proxy PAC usage.

Environment:
Chrome on Linux.
Using Playwright to control the browser in headful mode.

What I'm seeing:
When Playwright sends a CDP `Page.captureSnapshot` message to a tab in the background, the browser response sometimes takes tens of seconds, sometimes it times out after two minutes.

What I'm expecting:

- A screenshot response in a reasonable amount of time for a tab in the background. For the front-most tab, screenshots take on the order of ~100ms.
- A Chromium command line argument to disable throttling of background tabs.

What I've tried:
I have tried using several command line arguments that sound promising but the problem persists. I have tried:
--disable-background-timer-throttling
--disable-background-media-suspend
--disable-backgrounding-occluded-windows
--disable-renderer-backgrounding

Things I have noticed:

- User-triggered events on the front tab seem to influence the timing of the screenshot on the background tab. For example, clicking or double-clicking on the front tab will usually cause the background screenshot to complete. Resizing the window will cause the background tab screenshot to complete. It almost feels like the event loop is being throttled.

- Opening a dev tools pane in the front tab will cause the background tab screenshots to complete faster and consistently (around ~500ms)

- Pulling the tab into a new window will cause screenshot to execute quickly.

I suspect some sort of throttling of the CPU or possibly the event loop is causing unpredictable response times. I'm hoping someone can point me to a possible solution or at least something that might help me understand the problem a bit more.

Has anyone else hit this? Any suggestions or ideas would be appreciated.

**Comment by rwoll** [comment] 2022-08-08 18:08
Can you elaborate on your use case? How are the screenshots used and how are they being triggered?

If you want screenshots across all tabs for the duration of the test run, we recommend enabling tracing which will have the screenshots: https://playwright.dev/docs/trace-viewer#recording-a-trace

**Comment by DonMcNamara** [comment] 2022-08-11 00:13
Thank you for the reply.

The use case is custom automation of web app tests taking screenshots along the way. For some reason, occasionally the screenshots for some tests will start timing out. There seems to be some timing aspect to it. Also, it seems to be related to multiple tabs being opened.

Please note, I do *not* think this is a bug in Playwright. It feels like some part of Chromium is throttling the background tabs, but I'm having trouble following that idea and was hoping someone else had hit something similar.

Thank you for mentioning tracing. I tried that and just the act of enabling tracing makes the screenshot perform well -- do you have any ideas why that might be the case? Is there anything about enabling tracing that might influence Chromium's behavior?

I've pushed a contrived example that illustrates the issue here: https://github.com/DonMcNamara/screenshot-issue

With tracing off, the background tab screenshots timeout:
```
npx playwright test --project=chromium --headed

Running 1 test using 1 worker
[chromium] › example.spec.ts:7:1 › Take a bunch of screenshots
Loop 1
Foreground tab screenshot took: 174ms
Background tab screenshot took: 152ms
Loop 2
Foreground tab screenshot took: 142ms
Background tab screenshot took: 3607ms  <------- NOTE: long screenshot. Then the next one times out
Loop 3
Foreground tab screenshot took: 98ms
  1) [chromium] › example.spec.ts:7:1 › Take a bunch of screenshots ================================

    Test timeout of 30000ms exceeded.
```

Just by enabling tracing, the screenshots perform well:
```
npx playwright test --project=chromium --headed

Running 1 test using 1 worker
[chromium] › example.spec.ts:7:1 › Take a bunch of screenshots
Loop 1
Foreground tab screenshot took: 138ms
Background tab screenshot took: 168ms
Loop 2
Foreground tab screenshot took: 132ms
Background tab screenshot took: 110ms
Loop 3
Foreground tab screenshot took: 148ms
Background tab screenshot took: 155ms
Loop 4
Foreground tab screenshot took: 124ms
Background tab screenshot took: 155ms
Loop 5
Foreground tab screenshot took: 128ms
Background tab screenshot took: 159ms
Loop 6
Foreground tab screenshot took: 137ms
Background tab screenshot took: 146ms
Loop 7
Foreground tab screenshot took: 148ms
Background tab screenshot took: 118ms
Loop 8
Foreground tab screenshot took: 110ms
Background tab screenshot took: 133ms
Loop 9
Foreground tab screenshot took: 155ms
Background tab screenshot took: 150ms
Loop 10
Foreground tab screenshot took: 138ms
Background tab screenshot took: 131ms

  1 passed (4s)
```

**Comment by rwoll** [comment] 2022-08-11 01:09
My best guess on why it works with tracing on: when tracing is enabled, Playwright tells CR to send screencasts of all its pages so it's maybe already hitting a rendering hotpath when you go to take the screenshot manually regardless of the page. (I haven't confirmed in the CR source, though, and it's likely out of scope for me to do so.)

See notes below and a suggested workaround.

---

I tried running your repro both on an M1 Mac (lots of cores and mem) and GitHub Linux Codespace (4-core, 8 GB RAM).

On M1, there's no difference in timing between trace on vs. off (and there are no timeouts). Took about 41ms for screenshot.
On Codespace, with trace off it's not consistent:

```
Running 1 test using 1 worker
[chromium] › example.spec.ts:7:1 › Take a bunch of screenshots
Loop 1
Foreground tab screenshot took: 116ms
Background tab screenshot took: 99ms
Loop 2
Foreground tab screenshot took: 97ms
Background tab screenshot took: 3638ms
Loop 3
Foreground tab screenshot took: 96ms
  1) [chromium] › example.spec.ts:7:1 › Take a bunch of screenshots
```

i.e. sometime's the "background" was faster, sometimes the "foreground", sometimes the timeout.

However, if I add the following as the first line of your test case:

```ts
  context.on('page', async page => {
    const cdp = await context.newCDPSession(page);
    cdp.on("Page.screencastFrame", async params => {
      await cdp.send("Page.screencastFrameAck", { sessionId: params.sessionId }).catch(() => {});
    })
    await cdp.send("Page.startScreencast", { });
  });
```

and leave tracing off, GH Codespace starts working consistently. (The snippet above tells CR to stream all frames across all pages to PW.)

---

@aslushnikov Is there anything actionable here for Playwright itself? Part of me thinks this is extenuating use case, the other part of me wonders if all manual screenshots without tracing/screencasting enabled are much slower than they could be for all users—including when we do web-first screenshot expectations. (Although, I'm sure there is memory or perf penalty for enabling screencasting when not needed.)

I'm going to close for now since it's not clear what action Playwright would take and there is a supplied workaround for your use case.

**Closed by rwoll** 2022-08-11 01:09 UTC
Labels: triaging

**Comment by DonMcNamara** [comment] 2022-08-11 01:48
Amazing! Thank you Ross!
