### ISSUE TITLE
[Feature]: Make it possible to store pw:debug output to a file

### ISSUE THREAD

**Issue by TiagoMAGarcia** [microsoft/playwright#29799] opened 2024-03-04 16:07 UTC
### 🚀 Feature Request

I'm trying to store the DEBUG=pw:api output to a file, ideally stored in the test-results, however I'm not having any success with this:
![image](https://github.com/microsoft/playwright/assets/73131074/6fa9dbc6-3413-4162-b9ec-ea9927f70070)

Would it be possible to add support (like a flag) to store the pw debug output to a file, in the test results along with other artifacts? 
To not clutter the console output in the CI.

### Motivation

It would enable easy access to the pw debug logs, saved in the desired folder, while simultaneously having acess to the normal CI logs.

**Comment by dgozman** [comment] 2024-03-04 20:41
@TiagoMAGarcia What are you looking for in the logs? We would much prefer to improve reporters and/or tracing instead of debug logs. Let us know what are you missing in your regular workflow that you find useful in the logs, so that we can improve the overall experience.

**Comment by TiagoMAGarcia** [comment] 2024-03-05 09:20
@dgozman We create our own pages on the "beforeAll" and regularly we have timeouts on this "beforeAll" (as shown on the screenshot bellow). We want to understand why this is happening and the logs were a way to get more information.

Screenshot of the pipeline:
![image](https://github.com/microsoft/playwright/assets/73131074/374d61d2-051b-4b46-95d4-8d1a2887dedc)

**Comment by dgozman** [comment] 2024-03-05 17:23
@TiagoMAGarcia For this, we recommend [recording a trace](https://playwright.dev/docs/trace-viewer-intro) and then exploring it in the trace viewer. It has more information than debug logs. Let me know whether that works for you.

**Comment by LanderBeeuwsaert** [comment] 2024-03-05 17:27
@dgozman Hi I'm from the same team as @TiagoMAGarcia . 
We already create & save traces. The trace file for when this happens is just a few milliseconds long & shows a blank page. Nothing is really loaded. We can't find the cause based on the trace file

**Comment by dgozman** [comment] 2024-03-05 19:04
@LanderBeeuwsaert That's unexpected. The trace should contain `beforeAll` and all the actions inside, including all the logs. If you could share a self-contained repro, we would love to fix that.

**Comment by TiagoMAGarcia** [comment] 2024-03-07 10:22
Unfortunately a repro is not possible right now. 
We enabled the `DEBUG=pw:api` logs however it seems that just by doing this the pipeline crashes consistently. 
Here's a raw log: [Raw log.txt](https://github.com/microsoft/playwright/files/14522550/Raw.log.txt) . 
We have not been able to understand the reason for the crash through the logs, and I would like to ask you if you notice anything on the logs that would explain the crashes.

**Comment by dgozman** [comment] 2024-03-07 17:12
@TiagoMAGarcia I've skimmed through the logs, and nothing stands out to me. I also noticed that you upload `test-results` directory somewhere. We usually recommend [uploading the html report](https://playwright.dev/docs/ci-intro#html-report) instead, because it should contain exactly the information you'd want.

Regarding this issue, if there is some specific information missing in the report/trace, please let us know. I believe we include much more than what's available through `DEBUG=pw:api` there, so if that's not the case, we'll need a repro to be able to debug it.

**Comment by dgozman** [comment] 2024-03-08 15:06
@TiagoMAGarcia If the test times out, it does not exactly guarantee that `newContext()` or `newPage()` is going to throw, so perhaps that's why you don't see the logs from the `catch` block. I will still recommend [recording a trace](https://playwright.dev/docs/trace-viewer-intro) so that you get logs for each command that failed.

It could be that you are just overbooking your CPU by running too many parallel tests at once. Try [disabling parallelism](https://playwright.dev/docs/test-parallel#disable-parallelism) to see whether it helps.

**Comment by LanderBeeuwsaert** [comment] 2024-03-10 14:30
Hi @dgozman , we've been continuing to work on this, and tried quite a lot of things, but didn't find the root cause yet.
However, some things we found out in the meantime:
[trace.zip](https://github.com/microsoft/playwright/files/14550504/trace.zip)
[pipeline run.txt](https://github.com/microsoft/playwright/files/14550506/pipeline.run.txt)

We also adapted the code for creating the pages:
<img width="1201" alt="image" src="https://github.com/microsoft/playwright/assets/1098243/b86a08d2-3a93-442a-abd8-3a7a4b24fcc3">

1. In the pipeline run you can find one test that failed because of a failure in creating the page in 40s:
playwright-test-testsuites\create-member-testsuite.spec.ts:162:5 › Create Member Testsuite › Tests that need to open the create member dialog › Check appearance of the dialog
(there are some other failures but these are normal flakies, those we're fixing)
You can see that the context is created however:
<img width="631" alt="image" src="https://github.com/microsoft/playwright/assets/1098243/b845b110-5e09-4399-8c3e-8f045622cd47">
Also if you search on "Page creation success" then you can see that all other pages get created in something like 1 second. So that a page can't get created in 40seconds is improbable.
But if you look at the trace you can indeed see it's taking 40 seconds.

2. something only half related is that we tried to create a retry mechanism as a workaround with the Promise.race and sleep. But weird thing is that the sleep doesn't trigger; so something is for sure off because this should be outside of playwright/page creation issues.
<img width="499" alt="image" src="https://github.com/microsoft/playwright/assets/1098243/ade1f521-2f1b-4e88-b30f-fd4413f79a09">

any ideas what we can try as a next step?

**Comment by dgozman** [comment] 2024-03-11 18:17
@LanderBeeuwsaert Let me zoom out a bit. Trying to debug issues without a repro by looking at logs is not very efficient, so we prefer to focus on other issues that have the most chances to be fixed and have a larger impact for our users.

Something is definitely off in your setup, but there is no way for me to tell what exactly. Perhaps you can try your luck with [Playwright community](https://playwright.dev/community/welcome) or manage to create a repro for us, so we can actually look into it.

Given that we did not gather the usecases for the original feature request about pw:debug logs, I am going to close this issue. Feel free to open a new one focused on the pw:debug topic, if you think there is a compelling usecase for it over recording the trace.

**Closed by dgozman** 2024-03-11 18:17 UTC

**Comment by theIYD** [comment] 2025-05-06 03:28
@dgozman I have a use-case where I am using Playwright as a library to connect over CDP to an automated browser. (Note: This browser is not launched by Playwright but another tool). To debug errors thrown by Playwright, we don't have logs which we can go through for knowing the causes. 

My ask is to have a way to pipe the output from `DEBUG` to a normal text file.
