### ISSUE TITLE
[BUG] Unable to connect to Dolphin Anty

### ISSUE THREAD

**Issue by ESPodmov** [microsoft/playwright#18935] opened 2022-11-19 21:55 UTC
```
import asyncio
import requests
from playwright.async_api import async_playwright
import DolphinController


async def run(playwright):
    session = requests.session()
    auth_token = DolphinController.authentication("login", "password")
    headers = {
        "Authorization": f"Bearer {auth_token}",
        "Content-Type": "application/json"
    }
    session.headers = headers
    current_profile_id = DolphinController.create_profile_and_send_id(session)
    automation_json = DolphinController.start_automation(session, profile_id=current_profile_id)
    dolphin_port = automation_json["automation"]["port"]
    dolphin_ws_endpoint = automation_json["automation"]["wsEndpoint"]
    chromium = playwright.chromium
    browser = await chromium.connect_over_cdp(f"ws://127.0.0.1:{dolphin_port}{dolphin_ws_endpoint}")
    context = browser.contexts[0]
    await context.close()
    context = await browser.new_context()
    page = context.pages[0]
    await page.goto("http://google.com")
    # other actions...
    await browser.close()


async def main():
    async with async_playwright() as playwright:
        await run(playwright)


asyncio.run(main())

```
Unable to connect to the Dolphin Anty using playwright.chromium.connect_over_cdp() function
All that turned out to be found out is that in order for automation to go as it should, you need to open a new tab and close the start one
DolphinController class just opens new instance of Dolphin browser
P.S. 
DolphinController working correctly
P.P.S.
I tested this class with another library

**Comment by dgozman** [comment] 2022-11-21 21:06
@ESPodmov
- Could you please share the `DolphinController` source? We need a repro that we can run locally in order to help you.
- You mention "Dolphin browser". There is no official support for this browser. We might be able to help if the problem is trivial, but there are no guarantees.

**Comment by dgozman** [comment] 2022-11-28 00:39
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue with it, and link to this one.

**Closed by dgozman** 2022-11-28 00:39 UTC
Labels: triaging
