### ISSUE TITLE
[BUG] Playwright prevents electron app from relaunching or quitAndInstall with electron-updater

### ISSUE THREAD

**Issue by xupea** [microsoft/playwright#13133] opened 2022-03-28 17:07 UTC
**Context:**
- Playwright Version: 1.20.1
- Operating System: Mac
- Node.js version: 16.0
- Browser: Electron

**Code Snippet**
```
import { test, expect, _electron as electron } from '@playwright/test';

test('basic test', async () => {
  const electronApp = await electron.launch({
    executablePath:
      '/Applications/ElectronReact.app/Contents/MacOS/ElectronReact',
  });

  // Evaluation expression in the Electron context.
  const appPath = await electronApp.evaluate(async ({ app }) => {
    // This runs in the main Electron process, parameter here is always
    // the result of the require('electron') in the main app script.
    return app.getAppPath();
  });
  console.log(appPath);

  // Get the first window that the app opens, wait if necessary.
  const window = await electronApp.firstWindow();
  // Print the title.
  console.log(await window.title());
  // Capture a screenshot.
  await window.screenshot({ path: 'intro.png' });
  // Direct Electron console to Node terminal.
  window.on('console', console.log);
  // Click button and Relaunch.
  await window.click('text=Read our docs');
  // Verify app relaunched.
  await new Promise((resolve) => setTimeout(resolve, 15000));
  // 
  // await electronApp.close();

  expect(1).toBe(1);
});

```
After button is clicked, electron app seems no respond instead of relaunch:
<img width="258" alt="image" src="https://user-images.githubusercontent.com/4531660/160450718-f9112829-d94b-41ea-8202-dc77f54a950a.png">

**Comment by pavelfeldman** [comment] 2022-04-05 03:16
Could you specify the steps to reproduce along with the expectations and actual behavior?

**Comment by pavelfeldman** [comment] 2022-10-20 06:22
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by pavelfeldman** [comment] 2023-11-16 04:43
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Closed by pavelfeldman** 2023-11-16 04:43 UTC
Labels: P3-collecting-feedback, feature-electron
