### ISSUE TITLE
[BUG] npx playwright test --debug is not working from Gitlab CI

### ISSUE THREAD

**Issue by adarshTS** [microsoft/playwright#20436] opened 2023-01-27 10:31 UTC
**Context:**
- Playwright Version: 1.27.1
- Operating System: Mac
- Node.js version: 18.11.9
- Browser: chrome
- Extra: Im trying to setup a Gitlab pipeline and running my tests from Gitlab CI

**Code Snippet**

This is how my pipeline configuration in Gitlab looks like:

```
stages:         
  - test

tests:       
  stage: test
  image: mcr.microsoft.com/playwright:v1.27.1-focal
  script:
    - curl -sL https://deb.nodesource.com/setup_18.x | bash -
    - apt-get install -y nodejs
    - npm i
    - npx playwright install chrome
    - npx playwright test --debug
```

**This is the log that i see in Gitlab:**

```
browserType.connect: Browser has been closed
      17 |
      18 | test('firstTest',async () => {
    > 19 |   const browser = await chromium.connect({
         |                                  ^
      20 |     wsEndpoint: `wss://cdp.browserstack.com/playwright?caps=${encodeURIComponent(JSON.stringify(caps))}`});
      21 |   const page = await browser.newPage();
      22 |   await page.goto("https://bstackdemo.com/");
        at /builds/adarshTS/playwright-browserstack-sample/tests/firstTest.spec.js:19:34
  1 failed
    firstTest.spec.js:18:1 › firstTest 
```

Im not able to find the entire stack trace, this works fine locally on my device. But fails on Gitlab.

**Comment by jnizet** [comment] 2023-01-27 12:51
The goal of `--debug` is top open a graphical debugger window ellowing to execute your test step by step. Why would you use that option on the CI, where nobody can possibly use the debugger?

**Comment by adarshTS** [comment] 2023-01-27 13:46
While I was trying to execute `npx playwright test` Im getting the above error, I tried diff ways to get a detailed log but I could not find the reason for such error(`browserType.connect: Browser has been closed`).

**Comment by pavelfeldman** [comment] 2023-01-27 16:00
As @jnizet explains, the problem is that you are trying to open a GUI application in the DISPLAY-less environment. --debug is serves different purposes in Playwright, it is running a GUI interactive tool.

**Comment by pavelfeldman** [comment] 2023-01-27 16:00
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2023-01-27 16:00 UTC
