### ISSUE TITLE
Playwright exception -com.microsoft.playwright.PlaywrightException: Error {   message='WebSocket error: socket hang up  selenium grid docker compose

### ISSUE THREAD

**Issue by MuraliRai2000** [microsoft/playwright#28957] opened 2024-01-11 19:00 UTC
### System info
- Playwright Version: [v1.37]
- Docker desktop on windows 10.
- Browser: [All, Chromium, Edge, Firefox, Chrome, WebKit]
- Other info:
Selenium grid: 4.16.1 (revision 9b4c83354e)

Am using Docker compose yml with selenium grid config
and this is config I was using 👍 

version: "3"
services:
  chrome:
    image: selenium/node-chrome:120.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_GRID_URL=http://localhost:4444/

  chromium:
    image: seleniarm/node-chromium:120.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_GRID_URL=http://localhost:4444/

  edge:
    image: selenium/node-edge:120.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_GRID_URL=http://localhost:4444/

  firefox:
    image: selenium/node-firefox:120.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_GRID_URL=http://localhost:4444/

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300

Issue: No browser interaction.

Error Log:

Am seeing this error -Playwright exception -com.microsoft.playwright.PlaywrightException: Error {   message='WebSocket error: socket hang up 

<selenium> connecting to http://localhost:4444/wd/hub/
<selenium> connected to sessionId=9b12acbd8b9d34d38c3a168410fdb91b
<selenium> using selenium v4
<selenium> retrieved endpoint ws://localhost:4444//session/9b12acbd8b9d34d38c3a168410fdb91b/se/cdp for sessionId=9b12acbd8b9d34d38c3a168410fdb91b
<ws connecting> ws://localhost:4444//session/9b12acbd8b9d34d38c3a168410fdb91b/se/cdp
<ws error> ws://localhost:4444//session/9b12acbd8b9d34d38c3a168410fdb91b/se/cdp error socket hang up
<ws connect error> ws://localhost:4444//session/9b12acbd8b9d34d38c3a168410fdb91b/se/cdp socket hang up
<ws disconnected> ws://localhost:4444//session/9b12acbd8b9d34d38c3a168410fdb91b/se/cdp code=1006 reason=
<selenium> disconnecting from sessionId=9b12acbd8b9d34d38c3a168410fdb91b
<selenium> disconnected from sessionId=9b12acbd8b9d34d38c3a168410fdb91b

Please look into this

Thanks

**Comment by dgozman** [comment] 2024-01-11 23:47
We need more information to act on this issue. Could you please provide a repro that we can run locally?

**Comment by MuraliRai2000** [comment] 2024-01-12 01:21
Am trying to execute playwright test cases parallelly in chrome edge using testng . In order to execute them I am using config in docker compose yaml file as mentioned above .Have installed docker desktop locally on windows machine .
Am using this below script to execute test cases from my workspace.
SELENIUM_REMOTE_URL=http://localhost:4444/wd/hub mvn test. Please check error log

**Comment by dgozman** [comment] 2024-01-12 16:57
@MuraliRai2000 Unfortunately, this is not enough for us to reproduce. Ideally, for such a complex scenario, it would be great to have a repository with all the necessary files and an instruction of how to reproduce the issue.

**Comment by dgozman** [comment] 2024-01-16 19:24
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.

**Closed by dgozman** 2024-01-16 19:24 UTC
