### ISSUE TITLE
[BUG] ConnectOverCDP does try to GET the WebSocket instead of connect when a HTTP URL was given

### ISSUE THREAD

**Issue by csxero** [microsoft/playwright#7094] opened 2021-06-14 04:15 UTC
**Context:**
- Playwright Version: => 1.11.0
- Operating System: WSL within Windows 
- Node.js version: 14.6.1
- Browser: chromium

**Code Snippet**

```javascript
 do {
    defaultLog().warn(`Waiting for queue to complete..`);
    const { data } = await Internet.get(
      `${TestInfo.GRID_URL}/se/grid/newsessionqueuer/queue`
    );
    if (data["value"].length !== 0) {
      await new Promise((r) => setTimeout(r, 1000));
      count++;
    } else {
      queueExists = false;
    }
  } while (queueExists && count < 120);
```

**Describe the bug**

Our code block is trying to check for selenium queue within our grid. If the data value returns `[]` the tests blows up.

This is a blocker for us and we can't upgrade past 1.10.0.

Any help is greatly appreciated. It seems a bit similar to this issue that you had with firefox
https://github.com/microsoft/playwright/issues/7015

```
 TypeError: Cannot read property 'length' of undefined

      at Object.rewriteErrorMessage (node_modules/playwright/lib/utils/stackTrace.js:35:102)
      at BrowserType._wrapApiCall (node_modules/playwright/lib/client/channelOwner.js:83:26)
```

**Comment by mxschmitt** [comment] 2021-06-14 08:53
Hi, would it be possible that you could provide us a reproducible? Since the code snippet which you shared does not contain any Playwright related code.

The stack-trace is from Playwright, but it would be helpful to understand where it got thrown and with which values etc.

**Comment by csxero** [comment] 2021-06-16 20:52
```js
export const gridSetup = async (): Promise<ChromiumBrowser> => {
  let count = 0;
  let queueExists = true;
  do {
    defaultLog().warn(`Waiting for queue to complete..`);
    const { data } = await Internet.get(
      `${TestInfo.GRID_URL}/se/grid/newsessionqueuer/queue`
    );
    if (data["value"].length !== 0) {
      await new Promise((r) => setTimeout(r, 1000));
      count++;
    } else {
      queueExists = false;
    }
  } while (queueExists && count < 120);

  defaultLog().warn(`Queue is empty..`);

  const { data } = await Internet.post(`${TestInfo.GRID_URL}/wd/hub/session`, {
    desiredCapabilities: {
      browserName: "chrome",
      acceptInsecureCerts: true,
      "se:options": {
        "se:timeZone": "Pacific/Auckland",
        "se:recordVideo": "true",
      },
    },
  });

  sessionId = data["sessionId"];

  return await chromium.connectOverCDP({
    wsEndpoint: `${TestInfo.GRID_URL}/session/${sessionId}/se/cdp`,
    timeout: TestConfig.apiTimeout,
  });
};
```


This is first method that gets called when using the grid. You can see playwright isn't being called until the end but the failure happens at `if (data["value"].length !== 0) {` line

`Internet.get` & `Internet.post` are just wrappers for axios.

**Comment by mxschmitt** [comment] 2021-06-17 09:35
Yeah a small repro without other external code would be helpful. Because the place where its failing is not Playwright related.

**Comment by csxero** [comment] 2021-06-18 02:06
Yes, the code does not direclty playwright _but_ it once I update the playwright package version and docker tag it breaks with a stacktrace from playwright.

Here is a repo demonstrating the issue

https://github.com/csxero/playwright-grid-issue

**Comment by mxschmitt** [comment] 2021-06-19 14:58
Thanks for your reproducible, this was super helpful!

Investigation report:
- The behaviour was introduced in #6141
- For connecting to Playwright via CDP to Selenium Hub, such a URL gets used: `http://host.docker.internal:7777/session/be02549638b9cf5e63f5d9e7b99f12f9/se/cdp` which is set [here](https://github.com/csxero/playwright-grid-issue/blob/main/helpers/testingInfo.ts#L6).
- When changing the protocol from `http://` to `ws://` it works

Action items:
- It did not give a helpful error reporting, since [this](https://github.com/microsoft/playwright/blob/ec68b31dc4c525c1906ead22c3d5f4c7a350ea15/src/server/chromium/chromium.ts#L237) does does not verify if the return key `webSocketDebuggerUrl` exists.
- This resulted in that INVALID_URL was returned since the url was `undefined`
- I will follow up on that

General things which I saw:
- `jest-playwright-preset` was included but not configured with the endpoint URL
- deprecated `chromium.connectOverCDP` `wsEndpoint` was used instead of `endpointURL`. (Not important)

cc @JoelEinbinder

**Comment by csxero** [comment] 2021-06-20 23:26
awesome, that worked. Thanks @mxschmitt

**Comment by mxschmitt** [comment] 2021-06-29 08:00
We applied two fixes which should improve the behaviour:
- fixing the error reporting, that only undefined was shown: https://github.com/microsoft/playwright/pull/7251
- adding better error reporting when the given CDP endpoint resulted in 404 internally: https://github.com/microsoft/playwright/pull/7239

Its in the latest dev release (or 1.13 in the future): `npm install playwright@next`. So closing for now and thanks for the great repro!

**Closed by mxschmitt** 2021-06-29 08:00 UTC
Labels: P2-bug, browser-chromium
