### ISSUE TITLE
[BUG] Different values in content-length header and responseBodySize for http2/http3 requests

### ISSUE THREAD

**Issue by lonix1** [microsoft/playwright#28155] opened 2023-11-15 09:50 UTC
### System info
- Playwright Version: v1.39.0
- Operating System: ubuntu 22
- Browser: chromium
- Other info: c# code, but same idea for other language bindings

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

```cs
page.Request += (_, request) => {
  var response = await request.ResponseAsync();
  var headers = await response.AllHeadersAsync();
  var sizes  = await request.SizesAsync();
  Console.WriteLine(sizes.ResponseBodySize);                 // should be equal
  Console.WriteLine(headers["content-length"]);              // should be equal
};
```

**Steps**
- run above code

**Expected**

`Content-Length` value from playwright and from header should be equal.

**Actual**

Not equal:
- the Playwright number is usually slightly larger
- in all cases it's different to the value I get from `curl --head url`

**Comment by mxschmitt** [comment] 2023-11-15 12:54
Closing, since this does not contain a self contained reproduction. Please re-file with a repro, thanks for your understanding!

**Comment by mxschmitt** [comment] 2023-11-21 10:06
Investigation:
- Its a http2 request
- Network.responseReceivedExtraInfo > headerText is not available since not available for h2/quick as per [here](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-responseReceivedExtraInfo).

**Closed** 2024-04-22 17:56 UTC
Labels: P3-collecting-feedback
