### ISSUE TITLE
[Feature] Trace console logs for multiple browsers 

### ISSUE THREAD

**Issue by acanyasar** [microsoft/playwright#28479] opened 2023-12-04 12:10 UTC
I am using playwright to automate our 1-1 video/audio/chat call software. In my scenario there is a caller and callee, to initiate a "call". To main reason that I wanted to use playwright as an automation tool was the trace and capturing the console logs and network request. The problems that we are facing are generally happening there not in the UI.

However when I transfer my test cases to playwright, I have noticed that its only recording console logs and network request for a single browser instance. Like I mentioned I am using at least 2 browser instances for my tests. I would like to ask for a new feature so that both of the browsers logs can be capture in the trace. 

Here is the trace file that I have for you to examine: 
[trace (11).zip](https://github.com/microsoft/playwright/files/13545710/trace.11.zip)

**Comment by dgozman** [comment] 2023-12-04 19:05
@acanyasar Instead of launching multiple browser, you should create [multiple contexts](https://playwright.dev/docs/browser-contexts#multiple-contexts-in-a-single-test) in a single browser. This way, you should get all traces in a single place. If that does not work for you, we would need a repro to be able to debug the issue.

**Comment by acanyasar** [comment] 2023-12-05 07:52
This does not work for me, in my case I need to login as the person who receives a "call" and call that user as an anonymous user. So I need two browsers for my tests. 
Here is a sample call test that I have 
`let calleePage, callerPage, activeCallerPage;

  await test.step("Setup browsers and pages", async () => {
    const caller = await browser.newContext();
    const callee = await browser.newContext();

    callerPage = await caller.newPage();
    calleePage = await callee.newPage();
  });

  await test.step("Login and set callee status", async () => {
    const loginPage = new SignUpPage(calleePage);
    await loginPage.validLogin(USERNAME_VCONNECT, PASSWORD);
    await calleePage.waitForLoadState();

    const dashboardPage = new dashboard(calleePage);
    await dashboardPage.makeUserAvailable();
  });

  await test.step("Start a call as anonymous user", async () => {
    const callPage = new ProfilePage(callerPage);
    activeCallerPage = await callPage.startCall("ahmetcanyasar1", "videoCall"); //go to profile page @WEB-225
  });

  const [newCalleePage] = await Promise.all([calleePage.waitForEvent("popup"), calleePage.locator(".ctrl-answer-video").click()]);

  await test.step("Wait for call to establish", async () => {
    await newCalleePage.waitForLoadState();
    newCalleePage.on("dialog", async (dialog) => {
      console.log(dialog.message());
      await dialog.dismiss();
    });
  });
`
..... and so on

**Comment by dgozman** [comment] 2023-12-05 16:59
@acanyasar Unfortunately, I am not able to reproduce - I do see logs and network from two pages in the same trace. We need a full self-contained repro that we can run locally to be able to reproduce, otherwise I'll have to close the issue.

**Comment by dgozman** [comment] 2023-12-08 17:31
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.

**Closed by dgozman** 2023-12-08 17:31 UTC
