### ISSUE TITLE
[BUG] [WebKit] The browser is appearing and asking to allow 'website' to use your camera and microphone, after running it in headless mode.

### ISSUE THREAD

**Issue by elaichenkov** [microsoft/playwright#4959] opened 2021-01-10 16:13 UTC
**Context:**
- Playwright Version: [1.7.1]
- Operating System: [Mac]
- Node.js version: [12.18.3]
- Browser: [WebKit]
- Extra: [macOS Catalina 10.15.7]

```bash
  pw:api => browserType.launch started +0ms
  pw:api <= browserType.launch succeeded +118ms
  pw:api => browser.newContext started +0ms
  pw:api <= browser.newContext succeeded +24ms
  pw:api => browserContext.newPage started +0ms
  pw:api <= browserContext.newPage succeeded +155ms
  pw:api => page.goto started +0ms
  pw:api navigating to "https://appr.tc/", waiting until "load" +1ms
  pw:api   navigated to "https://appr.tc/" +304ms
  pw:api   "domcontentloaded" event fired +272ms
  pw:api   "load" event fired +131ms
  pw:api <= page.goto succeeded +0ms
  pw:api => page.click started +0ms
  pw:api waiting for selector "#join-button" +3ms
  pw:api   selector resolved to visible <button id="join-button">JOIN</button> +22ms
  pw:api attempting click action +2ms
  pw:api   waiting for element to be visible, enabled and not moving +0ms
  pw:api   element is visible, enabled and does not move +26ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +1ms
  pw:api   checking that element receives pointer events at (511.19,240.35) +2ms
  pw:api   element does receive pointer events +2ms
  pw:api   performing click action +0ms
  pw:api   click action done +348ms
  pw:api   waiting for scheduled navigations to finish +0ms
  pw:api   navigations have finished +0ms
  pw:api <= page.click succeeded +1ms
  pw:api   "networkidle" event fired +505ms
```
```bash
  System:
    OS: macOS 10.15.7
    Memory: 98.62 MB / 16.00 GB
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Code Snippet**
```js
const { webkit } = require('playwright');

(async () => {
    const browser = await webkit.launch();
    const page = await browser.newPage();

    await page.goto('https://appr.tc/');
    await page.click('#join-button');
})();
```

**Describe the bug**
The browser is appearing and asking to allow 'website' to use your camera and microphone, after running it in headless mode.

Here is the screenshot in headless mode
![image (1)](https://user-images.githubusercontent.com/29764053/104128091-3a075880-536e-11eb-8d02-f72725a7792f.png)

**NOTE:**
In headed mode, the browser doesn't ask you for these permissions and a fake video stream works by default without providing any arguments or granting permissions.

Here is the screenshot in headed mode
![image (2)](https://user-images.githubusercontent.com/29764053/104128068-20fea780-536e-11eb-9a97-50142dc88450.png)
 
[Slack conversation.](https://playwright.slack.com/archives/CSUHZPVLM/p1610229430291500)

**Comment by yury-s** [comment] 2021-01-11 19:58
Looks like it's macOS-specific, I can't reproduce it on Linux.

**Comment by yury-s** [comment] 2021-01-11 20:04
Can reproduce it on Mac, the headless window becomes visible and the dialog shows up on top of it.

**Comment by elaichenkov** [comment] 2021-01-14 11:40
Hey @yury-s 
Thanks for the reply!
Btw, can you see the generated video in the headed mode on Linux?

**Comment by yury-s** [comment] 2021-01-14 20:15
> Btw, can you see the generated video in the headed mode on Linux?

No, I also see `TypeError: undefined is not an object (evaluating 'navigator.mediaDevices.getUserMedia')` in the console.

**Comment by pavelfeldman** [comment] 2021-01-18 17:10
My understanding is that the bug is the opposite: it should query the permission in headed mode as well. And there should be a way to suppress the permission check via granting context user media permissions.

**Comment by yury-s** [comment] 2021-03-18 19:24
We currently don't support camera and microphone permissions in webkit. It's particularly hard in webkit because the implementation differs a lot between platforms (doesn't work on Windows for example) so we are not ready to add them at the moment. Without such permissions it's not clear what a meaningful fix for this bug would be, we could suppress the dialog and simply dismiss the dialog but that would fix just one step in the testing scenario and it still wouldn't be possible to test webrtc in a 
sensible way. Considering little value of just suppressing the dialog I'm leaving this issue open until we decide to work on a more comprehensive support for webrtc (tracked in #2973).

**Comment by akhil-kp-dasan** [comment] 2021-05-14 12:09
https://github.com/microsoft/playwright/blob/d7c6720ce72c243dee63f2a13dbe1e2b0d862ee7/src/server/webkit/wkPage.ts#L1018-L1029 
@yury-s I can see that there is map of permissions supported by Webkit . Would it be possible to get camera and microphone permissions working on Mac simply by adding those permissions to that map or is there more to it than that?

**Comment by pavelfeldman** [comment] 2022-01-01 23:17
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-01-01 23:17 UTC
Labels: browser-webkit, P3-collecting-feedback

**Comment by RichFlickstein** [comment] 2022-06-02 17:49
This is a blocker issue for us adopting Playwright. Can you consider re-opening this and addressing it?

**Comment by domme1908** [comment] 2022-09-22 09:06
Hi, is there any news on this issue?
