### ISSUE TITLE
[BUG] Firefox: `TypeError: Cannot read properties of undefined (reading 'childFrames')`

### ISSUE THREAD

**Issue by mhils** [microsoft/playwright#9840] opened 2021-10-28 08:21 UTC
**Preface:** I'm using playwright for large scale academic web measurements, which I know is not what playwright was built for. I've done a fair share of FOSS work myself, so you have my full sympathies if you consider hard-to-reproduce crashes from unsupported use-cases out of scope for the time being - I can easily work around them. That being said, I was originally about to report five different tracebacks here, just to notice that @dgozman fixed four of them in #9826 a few hours ago. 😄:cake: So my presumption is you may find this interesting, which is why I'm sharing the remaining one here.

-----

I've encountered the following crash with `1.16.0-next-alpha-oct-20-2021` running Firefox on Ubuntu 20.04. Unfortunately there are no good repros - this happens very rarely and seemingly at random. For reference, I've seen it five times during ~70k website visits made with Firefox. For comparison, this is about as often as the various context-is-undefined crashes fixed in #9826.

```
2021-10-23T02:32:29.114Z pw:browser [pid=1135] <kill>
2021-10-23T02:32:29.114Z pw:browser [pid=1135] <will force kill>
2021-10-23T02:32:29.121Z pw:browser [pid=1135] starting temporary directories cleanup
/root/node_modules/playwright-core/lib/server/frames.js:337
    for (const child of frame.childFrames()) this._removeFramesRecursively(child);
                              ^

TypeError: Cannot read properties of undefined (reading 'childFrames')
    at FrameManager.removeChildFramesRecursively (/root/node_modules/playwright-core/lib/server/frames.js:337:31)
    at FrameManager.frameCommittedNewDocumentNavigation (/root/node_modules/playwright-core/lib/server/frames.js:169:10)
    at FFPage._onNavigationCommitted (/root/node_modules/playwright-core/lib/server/firefox/ffPage.js:211:30)
    at FFSession.emit (node:events:390:28)
    at /root/node_modules/playwright-core/lib/server/firefox/ffConnection.js:247:41
```

I have also done about 70k website crawls with Chromium and Webkit each without observing a crash at this location, so this seems Firefox-specific.

**Comment by nbsoftware** [comment] 2022-01-17 17:17
I just experienced what it looks like the same crash with latest version of PW (1.17.2) and also using Firefox

```
...../node_modules/playwright-core/lib/server/frames.js:339
    for (const child of frame.childFrames()) this._removeFramesRecursively(child);
                              ^

TypeError: Cannot read properties of undefined (reading 'childFrames')
    at FrameManager.removeChildFramesRecursively (...../node_modules/playwright-core/lib/server/frames.js:339:31)
    at FrameManager.frameCommittedNewDocumentNavigation (...../node_modules/playwright-core/lib/server/frames.js:171:10)
    at FFPage._onNavigationCommitted (...../node_modules/playwright-core/lib/server/firefox/ffPage.js:212:30)
    at FFSession.emit (node:events:390:28)
    at ...../node_modules/playwright-core/lib/server/firefox/ffConnection.js:247:41
```

Trying to click on the accept button of some cookie consent overlay dialog box with:

```js
let ctxCookies = await ctx.cookies('https://www.pap.fr');
let consent = ctxCookies.find(x => x.name == 'euconsent-v2');
if (consent === undefined || !consent.value)
  await page.click(':nth-match(button:has-text("Tout accepter et continuer"), 2)', {timeout: 2000});      
```

**Comment by psa** [comment] 2022-02-22 11:51
I regularly run into this as well. I haven't been able to reproduce it as a single site (even hammering a site thousands of times with the shortest bit of code I can).

Is it possible to do a check for undefined here and have the system gracefully handle that case rather than just throwing a stack trace and dying?

Here's the stack trace from python:
```
/usr/local/lib/python3.8/dist-packages/playwright/driver/package/lib/server/frames.js:339
    for (const child of frame.childFrames()) this._removeFramesRecursively(child);
                              ^

TypeError: Cannot read properties of undefined (reading 'childFrames')
    at FrameManager.removeChildFramesRecursively (/usr/local/lib/python3.8/dist-packages/playwright/driver/package/lib/server/frames.js:339:31)
    at FrameManager.frameCommittedNewDocumentNavigation (/usr/local/lib/python3.8/dist-packages/playwright/driver/package/lib/server/frames.js:171:10)
    at FFPage._onNavigationCommitted (/usr/local/lib/python3.8/dist-packages/playwright/driver/package/lib/server/firefox/ffPage.js:212:30)
    at FFSession.emit (node:events:390:28)
    at /usr/local/lib/python3.8/dist-packages/playwright/driver/package/lib/server/firefox/ffConnection.js:247:41
```

**Comment by ninhlt** [comment] 2022-02-24 14:35
I got the same issue with Playwright Python 1.18 and 1.19.
The problem happen so happen 80%
`  for (const child of frame.childFrames()) this._removeFramesRecursively(child);
                              ^

TypeError: Cannot read properties of undefined (reading 'childFrames')
    at FrameManager.removeChildFramesRecursively (C:\REACT\PlaywrightBots\venv\Lib\site-packages\playwright\driver\package\lib\server\frames.js:339:31)
    at FrameManager.frameCommittedNewDocumentNavigation (C:\REACT\PlaywrightBots\venv\Lib\site-packages\playwright\driver\package\lib\server\frames.js:171:10)
    at FFPage._onNavigationCommitted (C:\REACT\PlaywrightBots\venv\Lib\site-packages\playwright\driver\package\lib\server\firefox\ffPage.js:212:30)
    at FFSession.emit (node:events:390:28)
    at C:\REACT\PlaywrightBots\venv\Lib\site-packages\playwright\driver\package\lib\server\firefox\ffConnection.js:247:41
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
Error occured in event listener
`

**Comment by mxschmitt** [comment] 2022-02-24 14:36
@ninhlt do you have a repro which you could share with us? Otherwise we can't dig into it and fix it.

**Comment by AIGeneratedUsername** [comment] 2022-04-20 10:58
I have no idea how someone may show a reproducible sample for an error that appears randomly for random URLs. But here is a full `DEBUG=pw:browser*,pw:protocol` log:

[error_log.tar.gz](https://github.com/microsoft/playwright/files/8520857/error_log.tar.gz)

Please review this file. I hope this will help to solve the bug.

The log obtained by requesting random URLs one by one:
```python
from playwright.async_api import async_playwright

async with async_playwright() as p:
        browser = await p.firefox.launch()
        page = await browser.new_page()
        for url in random_urls_list:
            await page.goto(url)
        await browser.close()
```

**Comment by cuihaoleo** [comment] 2022-04-27 03:20
@mxschmitt I believe I encountered the same bug. Here is the minimal reproducible example I can get:

The buggy webpage `test.html`:
```html
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <iframe src="http://www.foxyform.com/"></iframe>
    <script type="text/javascript" src="foo.js"></script>
  </body>
</html>
```

Sample code:
```py
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.firefox.launch()
    page = browser.new_page()
    page.set_viewport_size({"width": 1080, "height": 1920})
    page.goto("file:///data/test.html")
    browser.close()
```

I used docker image to reproduce the error:
```
$ docker run -v "$PWD:/data" -it --rm mcr.microsoft.com/playwright/python:v1.21.0-focal python /data/run.py
/usr/local/lib/python3.8/dist-packages/playwright/driver/package/lib/server/frames.js:339
    for (const child of frame.childFrames()) this._removeFramesRecursively(child);
                              ^

TypeError: Cannot read properties of undefined (reading 'childFrames')
    at FrameManager.removeChildFramesRecursively (/usr/local/lib/python3.8/dist-packages/playwright/driver/package/lib/server/frames.js:339:31)
    at FrameManager.frameCommittedNewDocumentNavigation (/usr/local/lib/python3.8/dist-packages/playwright/driver/package/lib/server/frames.js:171:10)
    at FFPage._onNavigationCommitted (/usr/local/lib/python3.8/dist-packages/playwright/driver/package/lib/server/firefox/ffPage.js:214:30)
    at FFSession.emit (node:events:390:28)
    at /usr/local/lib/python3.8/dist-packages/playwright/driver/package/lib/server/firefox/ffConnection.js:247:41
```

**Comment by JannisBush** [comment] 2022-04-27 17:31
@cuihaoleo Nice example case :)
Here is a list of other URLs that I could reproduce the issue with your example code: https://upwork.com, https://zerohedge.com, https://pusher.com, https://utah.edu

**Comment by aslushnikov** [comment] 2022-05-03 05:17
For the record: this bug happens due to Juggler failing to find parent frames for certain iframes. This fundamentally seems to be related to us tracking `docShell` hierarchies instead of more modern `browsingContext` trees. 

This should be fixed with our fission support.

**Comment by VBoB13** [comment] 2022-05-16 04:06
I get the very same error if I run my script in firefox, but get a different error in a slightly different context with roughly the same frequency when using chromium. Once this error popped up, it never went away - it just kept on popping up for each URL...
The error I get in chromium looks like this:
```py
Error occured in event listener
Traceback (most recent call last):
  File "/Users/wilbertung/Documents/GitHub/Lowi50/ric_venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 268, in dispatch
    g.switch(self._replace_guids_with_channels(params))
  File "/Users/wilbertung/Documents/GitHub/Lowi50/ric_venv/lib/python3.8/site-packages/playwright/_impl/_browser_context.py", line 140, in <lambda>
    from_nullable_channel(params["response"]),
KeyError: 'response'
```

**Comment by psa** [comment] 2022-05-16 05:01
> Once this error popped up, it never went away - it just kept on popping up for each URL... 

The error seems to be terminal. In my code I call `playwright.stop()` and then completely re-initialise playwright from the ground up if I catch any exception which I'm not handling in a different manner.

e.g.

```
# main()
try:
  page_data = await asyncio.wait_for(spider.fetch_page(url))
except Exception as e:
  await spider.new_browser()

# class Spider()
async def new_browser(self):
  self.pw.stop()
  self.pw = await async_playwright().start()
  self.browser = await self.pw.firefox.launch()
  self.context = await self.browser.new_context(viewport={'width': width, 'height': height})
  self.page = await self.context.new_page()
```

**Comment by mxschmitt** [comment] 2022-10-19 18:40
I can verify that this issue is fixed on `npm i -D @playwright/test@next` or wait for 1.28.

Please try to repro on `@next` or wait for 1.28.

**Closed by mxschmitt** 2022-10-19 18:40 UTC
Labels: P3-collecting-feedback, browser-firefox, fission

**Comment by eatonjl** [comment] 2022-10-28 18:22
So far I am still seeing this issue after using next 1.28

**Comment by mxschmitt** [comment] 2022-10-28 18:24
Can you file a separate issue with a repro?

**Comment by mkdobtc** [comment] 2022-11-15 15:17
Recebo o erro event listener assim como a maioria nao consigo fornecer um bloco para reproduzir o problema de forma direta mas fico feliz em fornecer uma copia do projeto que fiz para ajudar a resolver o problema mencionado 
`2022-11-15 10:26:03 • Guias Exception: Execution context was destroyed, most likely because of a navigation
2022-11-15 10:26:03 • Total Points: ['55']
2022-11-15 10:26:04 Error occurred in event listener
2022-11-15 10:26:04 Traceback (most recent call last):
2022-11-15 10:26:04   File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 333, in dispatch
2022-11-15 10:26:04     object._channel.emit(
2022-11-15 10:26:04   File "/usr/local/lib/python3.10/site-packages/pyee/_base.py", line 113, in emit
2022-11-15 10:26:04     handled = self._call_handlers(event, args, kwargs)
2022-11-15 10:26:04   File "/usr/local/lib/python3.10/site-packages/pyee/_base.py", line 96, in _call_handlers
2022-11-15 10:26:04     self._emit_run(f, args, kwargs)
2022-11-15 10:26:04   File "/usr/local/lib/python3.10/site-packages/pyee/_asyncio.py", line 42, in _emit_run
2022-11-15 10:26:04     self.emit('error', exc)
2022-11-15 10:26:04   File "/usr/local/lib/python3.10/site-packages/pyee/_base.py", line 116, in emit
2022-11-15 10:26:04     self._emit_handle_potential_error(event, args[0] if args else None)
2022-11-15 10:26:04   File "/usr/local/lib/python3.10/site-packages/pyee/_base.py", line 86, in _emit_handle_potential_error
2022-11-15 10:26:04     raise error
2022-11-15 10:26:04   File "/usr/local/lib/python3.10/site-packages/pyee/_asyncio.py", line 40, in _emit_run
2022-11-15 10:26:04     coro = f(*args, **kwargs)
2022-11-15 10:26:04   File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_page.py", line 186, in <lambda>
2022-11-15 10:26:04     lambda params: self._on_frame_detached(from_channel(params["frame"])),
2022-11-15 10:26:04   File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_page.py", line 233, in _on_frame_detached
2022-11-15 10:26:04     self._frames.remove(frame)
2022-11-15 10:26:04 ValueError: list.remove(x): x not in list
2022-11-15 10:26:05 /usr/local/lib/python3.10/site-packages/playwright/driver/package/lib/server/frames.js:392
2022-11-15 10:26:05     for (const child of frame.childFrames()) this._removeFramesRecursively(child);
2022-11-15 10:26:05                               ^
2022-11-15 10:26:05 
2022-11-15 10:26:05 TypeError: Cannot read properties of undefined (reading 'childFrames')
2022-11-15 10:26:05     at FrameManager.removeChildFramesRecursively (/usr/local/lib/python3.10/site-packages/playwright/driver/package/lib/server/frames.js:392:31)
2022-11-15 10:26:05     at FrameManager.frameCommittedNewDocumentNavigation (/usr/local/lib/python3.10/site-packages/playwright/driver/package/lib/server/frames.js:191:10)
2022-11-15 10:26:05     at FFPage._onNavigationCommitted (/usr/local/lib/python3.10/site-packages/playwright/driver/package/lib/server/firefox/ffPage.js:212:30)
2022-11-15 10:26:05     at FFSession.emit (node:events:513:28)
2022-11-15 10:26:05     at /usr/local/lib/python3.10/site-packages/playwright/driver/package/lib/server/firefox/ffConnection.js:248:41`

**Comment by ninhlt** [comment] 2022-11-23 15:12
Do you guy got any updated on this issue ?

**Comment by eatonjl** [comment] 2022-11-28 14:11
@ninhlt I opened [another issue](https://github.com/microsoft/playwright/issues/18415) about this and they are working on a fix.
