### ISSUE TITLE
[BUG] HTML will not load when webkit browser is being used.

### ISSUE THREAD

**Issue by brism17** [microsoft/playwright#6125] opened 2021-04-07 15:48 UTC
Context:
This issue was previously closed because you said you needed more information but I don't see what information you need in your response? You asked me to serve the file on the server instead but I don't see why thats necessary for only the webkit browser and not the firefox and chromium browsers. What is the log dump you wish me to include?

Playwright Version: 1.8.1
Operating System: Windows
Node.js version: 14.16.0
Browser: Webkit
Extra: [any specific details about your environment]
Code Snippet
await this.page.setContent(notebookPageContent);
private notebookPageContent(pageContentParams: INotebookPageContentParams) {
const { loadOptions, mode, notebookContent, snippets, iframeSandboxHostUrl } = pageContentParams;
const optionsJson = stringifyOptions(loadOptions);
const notebookContentJson = notebookContent ? JSON.stringify(notebookContent) : "undefined";
const snippetsJson = snippets ? JSON.stringify(snippets) : "undefined";
const headerScript = pageContentParams.headerScript || "";
const iframeSandboxHostUrlValue = iframeSandboxHostUrl ? "${iframeSandboxHostUrl}" : undefined;

return `
  <!DOCTYPE html>
  <html>
    <head>
      <link href="${this.componentBasePath}/aznb-bundle.css" rel="stylesheet" />
      <script type="text/javascript">${headerScript}</script>
      <script
        type="text/javascript"
        src="${this.componentBasePath}/aznb-bundle.js"
      ></script>
      <style>
        html,
        body,
        #${loadOptions.parentElementId} {
          margin: 0px;
          height: 100%;
        }
      </style>
    </head>
    <body>
      <div id="${loadOptions.parentElementId}"></div>
      <script>
         window.perfMark = window.perfMark||(()=>{});
         const mode = "${mode}";
         window.aznb = AzureNotebooks;

         console.log("Component version is " + AzureNotebooks.version);

         async function walkthrough() {
           window.aznberrors = [];
           document.getElementById("${
             loadOptions.parentElementId
           }").addEventListener("aznb-error", (error) => window.aznberrors.push(error));

           perfMark("init-begin");
           await AzureNotebooks.init({
             userHasGivenCookieConsent: true,
             features: {
               snippets: {
                 enableSnippets: ${snippets ? "true" : "false"}
                }
              },
             getResourceAccessToken: () =>
               Promise.resolve({
                 notebookResourceId: "<resourceId>",
                 accessToken: "<access_token>",
                 refreshToken: "<refresh_token>"
               }),
             resourceUrl: "${this.notebookService.serverUrl}",
             iframeSandboxHostUrl: ${iframeSandboxHostUrlValue}
           });
           perfMark("init-end");

           if (${snippetsJson}) {
            AzureNotebooks.intelliSense.snippets?.addRange("python", ${snippetsJson});
           }

           const options = ${optionsJson};

           if (mode === "create") {
             AzureNotebooks.onCreateNotebook(onNotebookRendered);

             let nbcontent = ${notebookContentJson};

             if(!nbcontent) {
                const contentResponse = await fetch(options.filePath);
                const content = await contentResponse.text();
                const model = JSON.parse(content);
                nbcontent = model.content || model;
             }

             perfMark("load-begin");
             window.nb = await AzureNotebooks.createNotebook(options, JSON.stringify(nbcontent));
           } else {
             AzureNotebooks.onLoadNotebook(onNotebookRendered);

             perfMark("load-begin");
             window.nb = await AzureNotebooks.loadNotebook(options);
           }
         }

         const onNotebookRendered = async (event) => { 
           setTimeout(()=>{
            perfMark("load-onloaded-event");
            window.notebookLoaded = true;
          }, 0);
         };

         walkthrough();
       </script>
    </body>
  </html>
`;

Was closed previously in issue 59756.  : https://github.com/microsoft/playwright/issues/5976

**Comment by JoelEinbinder** [comment] 2021-04-08 17:34
Webkit, Firefox, and Chromium all have slightly different security policies for `about:blank`, especially when it comes to iframes. So I wouldn't expect behavior here to be consistent. When you use `page.setContent`, the page url stays as `about:blank`. If you serve this file with a web server, the normal policies will apply and this will probably start working.

**Comment by brism17** [comment] 2021-04-08 18:07
ok i will look into serving with a webserver to see if we can get better results.

**Comment by dgozman** [comment] 2021-04-13 17:33
@brism17 Any chance you've tried serving the html with webserver?

**Comment by brism17** [comment] 2021-04-13 18:53
I haven't tried it yet. I was on pto but I plan on coming back to trying to fix this , this week .

**Comment by dgozman** [comment] 2021-04-19 18:15
@brism17 Any news? 😄

**Comment by dgozman** [comment] 2021-04-21 18:37
Closing this one as we are unable to reproduce. If you have a public repro, please comment here and we'll reopen.

**Closed by dgozman** 2021-04-21 18:37 UTC
Labels: triaging

**Comment by agrattan0820** [comment] 2023-08-22 17:28
For anyone that comes by here, I was following this presentation by Kat Kniotek for email testing/authentication, https://portal.gitnation.org/contents/testing-mail-service-with-playwright and she used:

```typescript
await page.route(`http://localhost:4000/email`, (route) => {
  route.fulfill({ body: email.html });
});
await page.goto(`http://localhost:4000/email`);
```

Now this code works, HOWEVER, it does not work with webkit! For it to work with webkit, we need to specify the content type like so:
```typescript
await page.route(`http://localhost:4000/email`, (route) => {
  route.fulfill({ body: email.html, contentType: `text/html` });
});
await page.goto(`http://localhost:4000/email`);
```
