### ISSUE TITLE
[Feature]: Emulating multiple present pointer input devices.

### ISSUE THREAD

**Issue by PuruVJ** [microsoft/playwright#34158] opened 2024-12-29 08:31 UTC
### 🚀 Feature Request

A feature with fine-grained pointer controls would be highly appreciated. Thanks

### Example

```ts
const p1 = new page.Pointer()
p1.down(x, y)
const p2 = new page.Pointer()
p2.down(x,y)
```

### Motivation

I am building a draggable library: [neodrag.dev](https://neodrag.dev), and it has a `ignoreMultitouch` option which stores the pointer IDs and acts accordingly. I am not able to test that currently.

**Comment by Skn0tt** [comment] 2024-12-30 08:57
Hi Puru! That's a really nice kitchen sink demo on your library page!

Please elaborate on your needs for this API, why what's currently available doesn't work, and how your proposed API solves that. Also, i'm surprised your example creates two separate pointers. As far as I know there's only one pointer to move around - is this about multi-touch?

**Comment by PuruVJ** [comment] 2024-12-30 09:04
Hi @Skn0tt, thanks for replying so fast! 

On mobile devices, using two fingers on the element causes it to switch to swipe or pan or other gestures at the OS level. `ignoreMultitouch` is there so while you are dragging the element, if you try to drag with two fingers(causing pinch or pan), the library calls `e.preventDefault()`, cancelling the native behavior.

I have tested this behavior on phone manually and ti works, but It would be nice if I could add it to my playwright test suite for future-safety.

Current api is `mouse.down()`. If I call it twice, it doesn't create two `Pointer` instances. Which is why it would be nice to have explicit control over the pointers.

Maybe could help with the experimental Android stuff as well.

Thanks
Puru

**Comment by Skn0tt** [comment] 2024-12-30 09:39
Thanks for elaborating, that makes sense!

**Comment by Skn0tt** [comment] 2024-12-30 16:56
After discussing with the rest of the team, it looks like this is a duplicate of https://github.com/microsoft/playwright/issues/2903. Closing.

**Closed by Skn0tt** 2024-12-30 16:56 UTC
Labels: P3-collecting-feedback

**Comment by Skn0tt** [comment] 2024-12-30 16:57
At the moment, your best bet is probably to use [`dispatchEvent`](https://playwright.dev/docs/api/class-locator#locator-dispatch-event) to dispatch pointer events.
