### ISSUE TITLE
[BUG] Recording is truncated

### ISSUE THREAD

**Issue by OLibutzki** [microsoft/playwright#15131] opened 2022-06-27 04:27 UTC
**Context:**
- Playwright Version: 1.22.0
- Operating System: Linux
- Java version: 11
- Browser: Chromium
- Extra: Executed on Jenkins via maven-surefire-plugin
I use the Docker image _browserless/chrome:1.53.0-chrome-stable_ and connect over cdp 

**Code Snippet**

```java
try ( Playwright playwright = Playwright.create( ) ) {
  final Browser browser = playwright.chromium( ).connectOverCDP( "ws://" + chromeContainer.getHost( ) + ":" + chromeContainer.getFirstMappedPort( ) );
  final String baseUrl = String.format( "http://%s:%s", hostname, port );
  try (
    BrowserContext browserContext = browser.newContext( new Browser.NewContextOptions( ).setRecordVideoDir( screenshotAndVideoPath ) );
    Page page = browserContext.newPage( ) ) {
    [...]
  }
}
```

**Describe the bug**

The recording is truncated at the rightas you can see in the attached [recording.zip](https://github.com/microsoft/playwright/files/8988669/recording.zip).

**Comment by rwoll** [comment] 2022-06-27 19:39
_truncated_ as in the end of the video is missing? If so, be sure to close your context via https://playwright.dev/java/docs/api/class-browsercontext#browser-context-close to ensure it's all flushed/drained. Does that help/work?

**Comment by OLibutzki** [comment] 2022-06-27 19:44
No, not the whole screen is visible. A part on the right side is missing. You can see it if you watch the attached recording.

**Comment by rwoll** [comment] 2022-06-27 20:23
Thanks—I will take a look. It will take me a bit to try to reproduce this as it involves multiple containers/pieces.

**Comment by rwoll** [comment] 2022-06-27 23:09
I can repro the issue you show in the video (see below). I ran the following code against (1) a chrome-stable via CLI, and (2) Browserless Docker container (`browserless/chrome:1.53.0-chrome-stable`):

```java
public class Example {
  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
      Browser browser = playwright.chromium().connectOverCDP(System.getenv("CDP_ADDRESS"));
      BrowserContext context = browser.newContext(new Browser.NewContextOptions().setRecordVideoDir(Paths.get("./video")));
      Page page = context.newPage();
      page.navigate("http://playwright.dev");
      context.close();
      browser.close();
      System.out.println("DONE!");
    }
  }
}
```
| -  |  |
| --- | -- |
| Default |  <img width="805" alt="Screen Shot 2022-06-27 at 4 02 17 PM" src="https://user-images.githubusercontent.com/11915034/176051086-217392f9-7982-4c6b-b669-e5b869c5d121.png"> |
| Browserlss | <img width="801" alt="Screen Shot 2022-06-27 at 4 02 40 PM" src="https://user-images.githubusercontent.com/11915034/176051093-fd4883ba-a8c1-4dae-a7f0-13117e918548.png"> |

It looks like it's working without Browserless, and since Browserless is a third-party product, **their support channels will likely be able to assist better in debugging.**

For the Browserless test, I launched a container via:

```bash
$ docker run -p 8080:3000 --restart always -d --name browserless browserless/chrome:1.53.0-chrome-stable
``` 

(matching the version in your description).

For the native default connectOverCDP test, I used the following command to get a WS address for the browser:

```bash
$ xvfb-run google-chrome-stable --user-data-dir="$(mktemp -d)" --remote-debugging-port=9222 --no-sandbox
```

**Comment by rwoll** [comment] 2022-06-27 23:44
I took a brief look at the Playwright code. Per the repro steps in https://github.com/microsoft/playwright/issues/15131#issuecomment-1168020894, since it looks like this only repro's with Browserless involved, and not when I launch a CDP session natively, I think the next best step would be to raise an issue with Browserless. (I took a brief look at how Browserless is launching the CR instances, but unfortunately, it's out of scope for me to debug.)

Please re-open this issue after raising with Browserless if you have more information, and we can re-triage/investigate as appropriate. Thanks for your patiences!

**Closed by rwoll** 2022-06-27 23:44 UTC
Labels: triaging

**Comment by OLibutzki** [comment] 2022-06-28 05:33
Hi @rwoll,

thanks for investigating the issue that quickly! I highly appreciate that.

I opened a browserless issue.

**Comment by MattHorrocksNetwealth** [comment] 2022-06-28 20:02
For future, I have been finding a very similar thing with Browserless https://github.com/browserless/chrome/issues/2497#issuecomment-1169170769
