### ISSUE TITLE
[Feature]  Provide some lifecycle id for controls to ensure they have changed.

### ISSUE THREAD

**Issue by ZooDoo4U** [microsoft/playwright#13941] opened 2022-05-04 18:18 UTC
I'm running into an issue where the app i'm testing runs very fast.  There places where i might drive the app faster than the app can respond.   Putting in sleeps, would like to avoid it.  When debugging code, will see (possibly from the old ElementHandle) there was a guid for the given element that seemed unique anytime it was updated, would like to get this if possible.  

My scenario i'll drive the client app, ensuring when selecting stuff will do the:

 ```
ILocator chapterItems = chapterCtrl.Locator("option");
await chapterCtrl.WaitForAsync( new LocatorWaitForOptions(){ State=WaitForSelectorState.Attached, Timeout=5000});            
int countChapters = await chapterItems.CountAsync();
```

While the **chapterCtrl** will update because another control was updated,  all awaited as needed.   Iterating 1000's of times on the same page and **WaitForSelectorState.Attached** isn't enough to help keep know when it's content was updated.  Need to be able to get a life cycle id or instance id for the control,  the only way i can see the control actually has been updated on the client.

Essentially it seems like a race condition, while looping and iterating through the chapters in my list,  the previous call that will update the chapter control finally completes and updates the list of chapters, when changing from a list of 30 to 14,  the countChapters is still 30, but only 14 are present... 

The other solution i have is put in Sleep() calls,  can get my test run, but  can take 25 minutes or more, while the couple of times i've been lucky the code ran all 18000 variation in 3 minutes.  

So it would be nice if we could get the guid, we see in the debugger for the control, then i can poll for a change in the instance/lifecycle value.

**Comment by ZooDoo4U** [comment] 2022-05-04 18:27
Might add started this of the PW Slack, 

https://app.slack.com/client/TSUHZPS85/threads/thread/CSUHZPVLM-1647133112.247759

**Comment by dgozman** [comment] 2022-05-06 10:21
@ZooDoo4U It seems like you need to find the right condition to wait for. Some ideas:

- `await Expect(locator).ToHaveCountAsync(14);` to wait for exactly 14 elements in the list. [Docs here](https://playwright.dev/dotnet/docs/test-assertions#locator-assertions-to-have-count).
- `await Expect(page.Locator("text=Last item in the list")).ToBeVisibleAsync();` to wait for some particular item to be visible. [Docs here](https://playwright.dev/dotnet/docs/test-assertions#locator-assertions-to-be-visible).
- More general, take a look at the list of [available assertions](https://playwright.dev/dotnet/docs/test-assertions).

In case I misunderstood the question, could you please provide a repro script that we can run locally, to see what's going on and how to help you best?

**Comment by ZooDoo4U** [comment] 2022-05-06 16:38
Thanks for the suggestions, for the controls on my form, there is no way to know there should be 'x' items and what their values should be, completely random.  Only thing of certainty,  what is present, that needs to be processed.   All the "PW Assertions .ToHave_XXXX_Async()" assume the control is 'current'?  In the scenario i'm encountering, really to know something has updated.  Call it my poor man's solution for a lock() or sync within a disconnected  async paradigm.  As with all UI testing #1 thing is ensuring the client and server are both in sync 100% of the time, if not, ensure they are again...  Right?  Thus the reason in my scenario, really need to know control 'x'  has actually updated.

Is there an issue?  Absolutely.  Is it a bug in Playwright?  Would argue no.  A bug in my client code? Again, no.  Are the two playing together nicely,  obviously not.  Might be i'm missing something obvious, but how can a disconnected client know it's request has been processed by a server,  best i can tell from the client checking has a control actually been updated.  Sure can put in blind nondeterministic waits, but really?  Just trading one issue for a less desirable one...?

**Comment by mxschmitt** [comment] 2022-05-13 15:05
> All the "PW Assertions .ToHave_XXXX_Async()" assume the control is 'current'?

What do you mean with that the control is current?

So you want to wait for an element to be different than it is when you start the Expect assertion? Sounds it might end up very racy if it's like that.

Having a repro for that would help us a lot, because it feels like we don't understand the underlying issue.

**Comment by ZooDoo4U** [comment] 2022-05-13 17:21
Below is a minimal repro that will cause the error to occur.  It is for my own little Bible reader to set the context of what i'm doing.  The problem is when going from one book to another, the number of chapters in it may change, could be more, less or the same.  The error is always when the number of chapters is less than the previous book, because we out paced the app.  All the existing asserts would pass, because the chapterCtrl (on screen) is valid from the previous iteration.  Only way without putting in code to see the control has changed would be to get the value for the control's lifecycle value or something like that?   Thus would be where i would like to know the lifecycle value changed,  then we know the chapters have updated and the count of values should be valid and okay to continue.  

Ah nothing fancy for the "IBrowser" passed in,  only thing my app will fire up the desired browser Chrome or Firefox, nothing fancy for headed/headless or video recording.  Just a simple IBrowser running headed in case you're wondering... 

    public static async Task PlaywrightBugRepro( IBrowser browser )
        {
            IPage page = await browser.NewPageAsync();
            await page.GotoAsync( "Ping me for ip... via PW Slack?" );

            ILocator versionCtrl= page.Locator("#versions");
            ILocator versionItems = versionCtrl.Locator("option");
                     
            await versionCtrl.WaitForAsync( new LocatorWaitForOptions(){ State=WaitForSelectorState.Attached , Timeout=5000});
            int countVerions = await versionItems.CountAsync();
            List<String> versions  = new List<string>();

            for( int idx = 0 ; idx <countVerions; idx++)
            {            
                versions.Add( await versionItems.Nth(idx).EvaluateAsync<string>("x => x.value"));
            }

            foreach( string version in versions ) 
            {
                await versionCtrl.SelectOptionAsync(  new SelectOptionValue{ Label = version} );    
                ILocator bookCtrl = page.Locator("#books");
                        
                await bookCtrl.WaitForAsync( new LocatorWaitForOptions(){ State=WaitForSelectorState.Attached, Timeout=5000});
                ILocator bookItems = bookCtrl.Locator("option");
                int countBooks = await bookItems.CountAsync();                  

                List<String> books = new List<string>();                
                for( int b = 0; b < countBooks; b++)
                {
                    books.Add( await bookItems.Nth(b).EvaluateAsync<string>("x => x.value"));
                }

                foreach( var book in books) 
                {
                    bookCtrl = page.Locator("#books");
                  
                    await bookCtrl.WaitForAsync( new LocatorWaitForOptions(){ State=WaitForSelectorState.Attached, Timeout=5000});
                    await bookCtrl.SelectOptionAsync( new SelectOptionValue{ Label = book} );
             
// here is where the bug will start to manifest.  chapterCtrl is valid (from the previous loop...
// but it not update and the Async() calls on it, sure PW will verify the operations happen...
// but there isn't a way to now it is pointing at the latest, and thus we will run into an error later if there is a race condition and there are fewer chapters...

                    ILocator chapterCtrl = page.Locator("#chapters");
                    
                    await chapterCtrl.WaitForAsync();                    
                    
                    ILocator chapterItems = chapterCtrl.Locator("option");
                    await chapterCtrl.WaitForAsync( new LocatorWaitForOptions(){ State=WaitForSelectorState.Attached, Timeout=5000});            
                    int countChpaters = await chapterItems.CountAsync();                                      
                    await chapterItems.Nth(countChpaters-1).WaitForAsync(new LocatorWaitForOptions(){State = WaitForSelectorState.Attached });
                     
                    for( int chIdx =0; chIdx < countChpaters; chIdx++)
                    {                                            
                        await chapterCtrl.WaitForAsync( new LocatorWaitForOptions(){ State=WaitForSelectorState.Attached, Timeout=5000});
                    
                        await  chapterCtrl.SelectOptionAsync(new SelectOptionValue{ Index =chIdx} );                          
                        ILocator versesTextContainerLocator =  page.Locator("div.verseReadingPane");
                        string verseText = await versesTextContainerLocator.InnerHTMLAsync();
                        
                        XmlDocument doc =new XmlDocument();
                        doc.LoadXml($"<root>{verseText.Replace("&nbsp;"," ")}</root>" );
                        XmlNodeList nodes = doc.SelectNodes("//span[@class='verseSpan']");
                        
                        foreach(XmlNode node in nodes)
                        {                        
                            var num = node.SelectSingleNode("span[@class='VerseNumber']").InnerText;
                            var txt = node.SelectSingleNode("span[@class='VerseText']").InnerText;                        
                        }
                    }                                        
                }
            }
        }

**Comment by mxschmitt** [comment] 2022-05-16 07:49
You can also negate the web-first assertions, by doing e.g. `await Expect(locator).Not.ToHaveCountAsync(14);`, would that work?

**Comment by ZooDoo4U** [comment] 2022-05-16 13:18
Would assert that would only work if one knew for sure what that count should be?  For any transition or update in the UI, the count of items in the list could be less, equal or greater,  how would anyone know for sure deterministically?  If the current iteration has 14 chapters, the next book could have the same number of chapters as well, thus asserting "count != 14" would fail because it rightfully should be 14?

**Comment by pavelfeldman** [comment] 2022-05-16 17:52
Let's try to turn this conversation into something actionable! It would be nice to see an exact use case (one use case) with the expected and actual behavior explained. Once we can see, we can assess it and either schedule it for implementation or close as won't fix.

**Comment by ZooDoo4U** [comment] 2022-05-16 23:44
You have the repro? But that said this more of a race condition, when it happens can't guess that,  but it will occur about 80 or 90% of the time when my tests run.  Sometimes it fails fast, first 100 or so iterations sometimes around the 16000th iteration. When it happens more often later in the run but normally will error out.

As requested/suggested before from a user perspective what would be great is exposing the internal  GUID one sees in the debugger,  could be wrong, but it appears to update anytime the control does,  expose that,  would assert I'd have what is needed.   Granted i'm making an assumption the GUID changes when the control is updated.  The GUID on the control changes just need to change the visibility of the property and make sure it is read only, done...?

**Comment by pavelfeldman** [comment] 2022-05-25 23:11
Closing as per my request above, we needed a minimal repro, expected behavior and actual behavior in order to be able to act on this request! Please feel free to file a new one and link this one.

**Closed by pavelfeldman** 2022-05-25 23:11 UTC
Labels: triaging

**Comment by ZooDoo4U** [comment] 2022-05-25 23:15
Ummm, you do have a minimal repro, just need to copy and paste the code, is that really so hard?
