### ISSUE TITLE
[BUG] `npx playwright install --with-deps` doesn't work with `"@playwright/test": "^1.36.0"`

### ISSUE THREAD

**Issue by alextreppass** [microsoft/playwright#24170] opened 2023-07-12 02:52 UTC
### System info
- Playwright Version: 1.36.0
- Operating System: OSX
- Browser: N/A
- Other info:

**package.json config file**

```json
"devDependencies": {
 "@playwright/test": "^1.36.0",
}
```

We do not have `playwright` as a dependency anywhere.

**Steps**
* Add `"@playwright/test": "^1.36.0",` to dev dependencies
* Run `npx playwright install --with-deps`

**Expected**

We get playwright 1.36.0 installed; I can see it's [a new release only recently available](https://github.com/microsoft/playwright/releases/tag/v1.36.0)

**Actual**

<pre>
╔════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Playwright Test integrity check failed:                                                                ║
║ You have @playwright/test version '1.36.0' and 'playwright' version '1.33.0' installed!                ║
║ You probably added 'playwright' into your package.json by accident, remove it and re-run 'npm install' ║
╚════════════════════════════════════════════════════════════════════════════════════════════════════════╝
</pre>

cc @aslushnikov

**Comment by mxschmitt** [comment] 2023-07-12 09:44
Can you share your package.json and the package-lock.json/yarn.lock file?

Most likely a dependency of yours depends on it.

**Comment by alextreppass** [comment] 2023-07-12 23:19
Thanks, [package.json](https://gist.github.com/alextreppass/aec4fa39cf258d01933d424b88acfa87) and [yarn.lock](https://gist.github.com/alextreppass/602e98630d76c302729952d87b7046aa)

**Comment by mxschmitt** [comment] 2023-07-13 09:24
Yeah `@storybook/test-runner@npm:^0.10.0":` depends on playwright ^1.14, I think regenerating the yarn.lock (delete and run yarn install again) should fix it.

Closing since this is not caused by Playwright.

**Closed by mxschmitt** 2023-07-13 09:24 UTC
Labels: triaging
