### ISSUE TITLE
[Question] Wait for image to be loaded

### ISSUE THREAD

**Issue by Pooort** [microsoft/playwright#6046] opened 2021-04-02 11:58 UTC
Hi.

I need to wait for a heavy image (6Mb) to be loaded.

I use: 

`await page.waitForResponse(src);`

as suggested in https://github.com/microsoft/playwright/issues/4782

But it doesn't work. Event fired at the start of loading. I see how it continue loading after this.

Thank you for help and for excellent product.

**Comment by pavelfeldman** [comment] 2021-04-02 14:16
You should do:

```js
const response = await page.waitForResponse(src);
await response.finished();
```

**Comment by Pooort** [comment] 2021-04-04 10:08
Unfortunately it doesn't work either. It waits endlessly.

**Comment by pavelfeldman** [comment] 2021-04-04 21:23
Could you provide a snippet with the reproduction?

**Comment by Sapkotaanish** [comment] 2021-04-06 03:55
`waitUntil: 'networkidle'`

This may work.

**Comment by Pooort** [comment] 2021-04-06 17:40
> Could you provide a snippet with the reproduction?

```
const response = await page.waitForResponse(src); // I've got response
await response.finished(); // but this part continue endlessly
console.log('loaded'); // this one never happened
```

**Comment by Pooort** [comment] 2021-04-06 17:41
> `waitUntil: 'networkidle'`
> 
> This may work.

Unfortunately it doesn't work either. It waits endlessly.

**Comment by Pooort** [comment] 2021-04-06 17:41
@pavelfeldman I'll try to make a test case with public image.

**Comment by dgozman** [comment] 2021-04-13 14:46
@Pooort Any luck with a public repro case?

**Comment by dgozman** [comment] 2021-04-19 18:12
Closing this one as we are unable to reproduce. Please comment here if you have a public repro case and we'll reopen.

**Closed by dgozman** 2021-04-19 18:12 UTC
Labels: triaging

**Comment by luixo** [comment] 2023-05-03 04:18
That doesn't seem to be working, actually.

```ts
const image = ... // image locator
const imageSrc = await image.getAttribute("src");
if (imageSrc) {
  const imageResponse = await page.waitForResponse(imageSrc);
  await imageResponse.finished();
  const imagesTuples = await page.evaluate(async () => {
    const selectors = Array.from(document.querySelectorAll("img"));
    return selectors.map((img) => [img.src, img.complete]);
  });
  console.log("Images", imagesTuples);
}
```

As a result I get
```
Images [ [ 'https://picsum.photos/id/1/320/240', false ] ]
```

Do you need a reproduction of that?

**Comment by DoomyTheFroomy** [comment] 2023-06-15 11:02
> That doesn't seem to be working, actually.
> 
> ```ts
> const image = ... // image locator
> const imageSrc = await image.getAttribute("src");
> if (imageSrc) {
>   const imageResponse = await page.waitForResponse(imageSrc);
>   await imageResponse.finished();
>   const imagesTuples = await page.evaluate(async () => {
>     const selectors = Array.from(document.querySelectorAll("img"));
>     return selectors.map((img) => [img.src, img.complete]);
>   });
>   console.log("Images", imagesTuples);
> }
> ```
> 
> As a result I get
> 
> ```
> Images [ [ 'https://picsum.photos/id/1/320/240', false ] ]
> ```
> 
> Do you need a reproduction of that?

I think you will have a race condition here. To use `waitForResponse` you will have to declare this before opening the page, otherwise it may have been already loaded. You may have to (re)load the page again after you got all your image sources

**Comment by luixo** [comment] 2023-06-15 23:09
> To use waitForResponse you will have to declare this before opening the page, otherwise it may have been already loaded.

I believe you assume whenever I get to my `console.log` the image is already loaded, right?
But why do I get `img.complete` as `false` in that case? Shouldn't it be `true` as image is already loaded?

**Comment by bonchuk** [comment] 2023-10-11 13:29
```typescript
  await page.waitForFunction(() => {
    const images = Array.from(document.querySelectorAll('img'));
    return images.every(img => img.complete);
  });
``` 

This is works for me

**Comment by karlhorky** [comment] 2023-11-06 12:26
The version that we're currently using tests for `naturalWidth`:

```js
expect(
  await (
    await page.locator('img').evaluateHandle(
      (element, elementProperty) => {
        return element[elementProperty];
      },
      'naturalWidth',
    )
  ).jsonValue(),
).toBeGreaterThan(0);
```

Can be abstracted to a function to make it a bit nicer:

```ts
import { Locator } from '@playwright/test';

export async function getLocatorProperty<Element extends HTMLElement>(
  locator: Locator,
  property: string & keyof Element,
) {
  return (
    await locator.evaluateHandle(
      (element: Element, elementProperty: string) => {
        return element[elementProperty as keyof Element];
      },
      property,
    )
  ).jsonValue();
}
```

Usage:

```
expect(
  await getLocatorProperty<HTMLImageElement>(
    page.locator('img'),
    'naturalWidth',
  ),
).toBeGreaterThan(0);
```

**Comment by karlhorky** [comment] 2023-11-06 12:30
@dgozman @pavelfeldman @mxschmitt what does the Playwright team think about paving the cowpaths on this one?

Eg finding the best, robust recommended solution in the list above (including the part of waiting for network requests to finish) and then doing one or the other of the following:

1. Creating a new first-party `expect()` assertion method like `expect(page.locator('img')).toBeLoaded()`
2. Creating a recommended official recipe for this in the docs

**Comment by dgozman** [comment] 2023-11-07 17:21
@karlhorky This depends on what exactly you would like to achieve. Something like `await expect(page.locator('img')).toBeLoaded()` is possible, but you might as well have a [custom matcher](https://playwright.dev/docs/test-configuration#add-custom-matchers-using-expectextend) for this, since we have not seen much interest in such an assertion yet.

**Comment by karlhorky** [comment] 2023-11-07 18:37
@dgozman interesting that there's not much uptake here. Maybe users don't know that they would want it?

Broken images can happen for a variety of reasons, including the one that I mentioned in the post above:

> To be clear, one statement of the value here is to test that programmatically-generated images are not broken in some way (which can easily happen silently, leaving them still "visible" and "in the viewport", but broken to website visitors)

Pretty common to create programmatically-created image paths (or even programmatically-generated image files themselves) these days, especially with things like [`next/image`](https://nextjs.org/docs/app/building-your-application/optimizing/images#usage).

Seems like a pretty big use case, and would be great if the Playwright team agrees that this common pattern is enough to justify a built-in matcher.

> you might as well have a [custom matcher](https://playwright.dev/docs/test-configuration#add-custom-matchers-using-expectextend) for this

I'm not against having custom recipe-style code for this (instead of a built-in matcher) - this was my option 2 I posted above:

2. Creating a recommended official recipe for this in the docs

But I would ask that the Playwright team comes up with their recommendation here with the least pitfalls and possibility for flaky tests.

**Comment by dgozman** [comment] 2023-11-07 19:00
@karlhorky Unfortunately, I cannot speak to what is the best approach here, without testing it on a variety of different sites.

[This solution](https://github.com/microsoft/playwright/issues/6046#issuecomment-1757704069) seems to be very straightforward, but it waits instead of expecting. Perhaps the following expect will be good for your usecase?

```ts
await expect(page.locator('img')).toHaveJSProperty('complete', true);
```

If `naturalWidth` is a better indicator, then I'd structure my code like this:

```ts
await expect(page.locator('img')).not.toHaveJSProperty('naturalWidth', 0);

// or

await expect.poll(() => page.locator('img').evaluate(img => img.naturalWidth)).toBeGreaterThan(0);
```

> Creating a recommended official recipe for this in the docs

Let's figure out the solution that works for most sites, and then we can definitely add it to the docs.

**Comment by karlhorky** [comment] 2023-11-07 20:56
Great, I'll try some different options and see what the detection, performance and robustness characteristics look like across multiple test runs and breakage scenarios.

**Comment by karlhorky** [comment] 2023-11-08 13:21
Started a demo for all of these test cases here:

https://github.com/karlhorky/playwright-image-loading-tests-with-next-js

Now just need to find the time to actually hammer out the page HTML and test cases

**Comment by ProchaLu** [comment] 2023-11-09 10:57
@dgozman @karlhorky  Here are the test results of the different scenarios:

### 1. Single image: image loads successfully

```js
<Image src="next.svg" alt="image" width="{300}" height="{300}" />
```

```
c: f nw: 0
c: t nw: 1+
c: t nw: 1+
...
```

Playwright test is successful.

```ts
await page.goto('/01-single-success');
await expect(page.locator('img')).toHaveJSProperty('complete', true);
await expect(page.locator('img')).not.toHaveJSProperty('naturalWidth', 0);
```

### 2. Single image: image loads successfully (slow - large image on 3G network speed)

```js
<Image src="next.svg" alt="image" width="{300}" height="{300}" />
```

```
c: f nw: 0
c: t nw: 1+
c: t nw: 1+
...
```

Playwright test is successful. For this test the network speed was throttled to 3G.

```ts
const client = await page.context().newCDPSession(page);

await client.send('Network.enable');

await client.send('Network.emulateNetworkConditions', {
  offline: false,
  downloadThroughput: ((500 * 1000) / 8) * 0.8,
  uploadThroughput: ((500 * 1000) / 8) * 0.8,
  latency: 70,
});
await page.goto('/02-single-success-slow');
await expect(page.locator('img')).toHaveJSProperty('complete', true);
await expect(page.locator('img')).not.toHaveJSProperty('naturalWidth', 0);
```

### 3. Single image: image loads unsuccessfully (404)

```js
<Image src="404.svg" alt="image" width={300} height={300} />
```

```
c: f nw: 0
c: t nw: 0
c: t nw: 0
...
```

The Playwright test below for for `img.naturalWidth` fails, because the is broken (404) but reports `img.complete = true`.

```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

```ts
await page.goto('/03-single-fail-404');
await expect(page.locator('img')).toHaveJSProperty('complete', true);
await expect(page.locator('img')).not.toHaveJSProperty('naturalWidth', 0);
```

### 4. Single image: image loads unsuccessfully (malformed image)

```js
<Image src="/malformed.svg" alt="image" width={300} height={300} />
```

```
c: f nw: 0
c: t nw: 0
c: t nw: 0
...
```

The Playwright test below for for `img.naturalWidth` fails, because the is broken (malformed) but reports `img.complete = true`.

```
Failed to load resource: the server responded with a status of 400 (Bad Request)
```

```ts
await page.goto('/04-single-fail-malformed');
await expect(page.locator('img')).toHaveJSProperty('complete', true);
await expect(page.locator('img')).not.toHaveJSProperty('naturalWidth', 0);
```

### 5. Single image: image loads unsuccessfully (host unreachable)

```js
<Image src="/image" alt="image" width={300} height={300} />
```

```
c: f nw: 0
c: t nw: 0
c: t nw: 0
...
```

The Playwright test below for for `img.naturalWidth` fails, because the is broken (host unreachable) but reports `img.complete = true`.

```
Failed to load resource: the server responded with a status of 400 (Bad Request)
```

```ts
await page.goto('/05-single-fail-unreachable');
await expect(page.locator('img')).toHaveJSProperty('complete', true);
await expect(page.locator('img')).not.toHaveJSProperty('naturalWidth', 0);
```

### 6. Multiple images: all images load successfully

```js
  <Image src="next.svg" alt="image" width={200} height={200} />
  <br />
  <Image src="next.svg" alt="image" width={200} height={200} />
  <br />
  <Image src="next.svg" alt="image" width={200} height={200} />
  <br />
  <Image src="next.svg" alt="image" width={200} height={200} />
  <br />
  <Image src="next.svg" alt="image" width={200} height={200} />
  <br />
  <Image src="next.svg" alt="image" width={200} height={200} />
  <br />
  <Image src="next.svg" alt="image" width={200} height={200} />
  <br />
```

```
c: f f f f f f f nw: 0 0 0 0 0 0 0
c: t t t t t t t nw: 1+ 1+ 1+ 1+ 1+ 1+ 1+
c: t t t t t t t nw: 1+ 1+ 1+ 1+ 1+ 1+ 1+
...
```

Playwright test is successful.

```ts
await page.goto('/06-multiple-success');
for (const img of await page.getByRole('img').all()) {
  await expect(img).toHaveJSProperty('complete', true);
  await expect(img).not.toHaveJSProperty('naturalWidth', 0);
}
```

### 7. Multiple images: all images load successfully (slow - large images on 3G network speed)

```js
  <Image src="/large.png" alt="image" width={1800} height={1000} />
  <br />
  <Image src="/large.png" alt="image" width={1800} height={1000} />
  <br />
  <Image src="/large.png" alt="image" width={1800} height={1000} />
  <br />
  <Image src="/large.png" alt="image" width={1800} height={1000} />
  <br />
  <Image src="/large.png" alt="image" width={1800} height={1000} />
  <br />
  <Image src="/large.png" alt="image" width={1800} height={1000} />
  <br />
  <Image src="/large.png" alt="image" width={1800} height={1000} />
```

```
c: f f f f f f f nw: 0 0 0 0 0 0 0
c: t t t f f f f nw: 1+ 1+ 1+ 0 0 0 0
c: t t t t f f f nw: 1+ 1+ 1+ 1+ 0 0 0
c: t t t t t f f nw: 1+ 1+ 1+ 1+ 1+ 0 0
c: t t t t t t f nw: 1+ 1+ 1+ 1+ 1+ 1+ 0
c: t t t t t t t nw: 1+ 1+ 1+ 1+ 1+ 1+ 1+
c: t t t t t t t nw: 1+ 1+ 1+ 1+ 1+ 1+ 1+
...
```

Playwright test is successful. For this test the network speed was throttled to 3G.

```ts
const client = await page.context().newCDPSession(page);

await client.send('Network.enable');

await client.send('Network.emulateNetworkConditions', {
  offline: false,
  downloadThroughput: ((500 * 1000) / 8) * 0.8,
  uploadThroughput: ((500 * 1000) / 8) * 0.8,
  latency: 70,
});
await page.goto('/07-multiple-success-slow');
for (const img of await page.getByRole('img').all()) {
  await expect(img).toHaveJSProperty('complete', true);
  await expect(img).not.toHaveJSProperty('naturalWidth', 0);
}
```

### 8. Multiple images: all images load successfully (lazy loading out of viewport)

```js
...
  <Image
    src="next.svg"
    alt="image"
    width={200}
    height={200}
    loading="lazy"
  />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <Image
    src="next.svg"
    alt="image"
    width={200}
    height={200}
    loading="lazy"
  />
...
```

```
c: f f f f f f f nw: 0 0 0 0 0 0 0
c: t t t t t t t nw: 1+ 1+ 1+ 1+ 1+ 1+ 1+
c: t t t t t t t nw: 1+ 1+ 1+ 1+ 1+ 1+ 1+
...
```

Playwright test is successful.

```ts
await page.goto('/08-multiple-success-lazy');
for (const img of await page.getByRole('img').all()) {
  await expect(img).toHaveJSProperty('complete', true);
  await expect(img).not.toHaveJSProperty('naturalWidth', 0);
}
```

### 9. Multiple images: 1st image loads unsuccessfully (404), rest load successfully

```js
  <Image src="404.svg" alt="image" width={300} height={300} />
  <br />
  <Image src="next.svg" alt="image" width={300} height={300} />
  <br />
  <Image src="next.svg" alt="image" width={300} height={300} />
  <br />
  <Image src="next.svg" alt="image" width={300} height={300} />
  <br />
  <Image src="next.svg" alt="image" width={300} height={300} />
  <br />
  <Image src="next.svg" alt="image" width={300} height={300} />
  <br />
  <Image src="next.svg" alt="image" width={300} height={300} />
```

```
c: f f f f f f f nw: 0 0 0 0 0 0 0
c: f t t t t t t nw: 0 1+ 1+ 1+ 1+ 1+ 1+
c: t t t t t t t nw: 0 1+ 1+ 1+ 1+ 1+ 1+
c: t t t t t t t nw: 0 1+ 1+ 1+ 1+ 1+ 1+
...
```

The Playwright test below for `img.loaded` fails, because the first image is broken (404) but reports `img.complete = 'true'`

```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

```ts
await page.goto('/09-multiple-1st-fail-rest-success');
for (const img of await page.getByRole('img').all()) {
  await expect(img).toHaveJSProperty('complete', true);
  await expect(img).not.toHaveJSProperty('naturalWidth', 0);
}
```

### 10. Multiple images: all images but last load successfully, last image loads unsuccessfully (404)

```js
  <Image src="next.svg" alt="image" width={300} height={300} />
  <br />
  <Image src="next.svg" alt="image" width={300} height={300} />
  <br />
  <Image src="next.svg" alt="image" width={300} height={300} />
  <br />
  <Image src="next.svg" alt="image" width={300} height={300} />
  <br />
  <Image src="next.svg" alt="image" width={300} height={300} />
  <br />
  <Image src="next.svg" alt="image" width={300} height={300} />
  <br />
  <Image src="404.svg" alt="image" width={300} height={300} />
```

```
c: f f f f f f f nw: 0 0 0 0 0 0 0
c: t t t t t t f nw: 1+ 1+ 1+ 1+ 1+ 1+ 0
c: t t t t t t t nw: 1+ 1+ 1+ 1+ 1+ 1+ 0
c: t t t t t t t nw: 1+ 1+ 1+ 1+ 1+ 1+ 0
...
```

The Playwright test below for `img.loaded` fails, because the last image is broken (404) but reports `img.complete = 'true'`

```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

```ts
await page.goto('/10-multiple-last-fail-rest-success');
for (const img of await page.getByRole('img').all()) {
  await expect(img).toHaveJSProperty('complete', true);
  await expect(img).not.toHaveJSProperty('naturalWidth', 0);
}
```

### 11. Multiple images: all images load unsuccessfully (404)

```js
  <Image src="404.svg" alt="image" width={300} height={300} />
  <br />
  <Image src="404.svg" alt="image" width={300} height={300} />
  <br />
  <Image src="404.svg" alt="image" width={300} height={300} />
  <br />
  <Image src="404.svg" alt="image" width={300} height={300} />
  <br />
  <Image src="404.svg" alt="image" width={300} height={300} />
  <br />
  <Image src="404.svg" alt="image" width={300} height={300} />
  <br />
  <Image src="404.svg" alt="image" width={300} height={300} />
```

```
c: f f f f f f f nw: 0 0 0 0 0 0 0
c: t t t t t t t nw: 0 0 0 0 0 0 0
c: t t t t t t t nw: 0 0 0 0 0 0 0
...
```

The Playwright test below for `img.loaded` fails, because all images are broken (404) but reports `img.complete = 'true'`

```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

```ts
await page.goto('/11-multiple-fail-404');
for (const img of await page.getByRole('img').all()) {
  await expect(img).toHaveJSProperty('complete', true);
  await expect(img).not.toHaveJSProperty('naturalWidth', 0);
}
```

### 12. Multiple images: all images load unsuccessfully (host unreachable)

```js
<div>
  <Image src="/image" alt="image" width={300} height={300} />
  <br />
  <Image src="/image" alt="image" width={300} height={300} />
  <br />
  <Image src="/image" alt="image" width={300} height={300} />
  <br />
  <Image src="/image" alt="image" width={300} height={300} />
  <br />
  <Image src="/image" alt="image" width={300} height={300} />
  <br />
  <Image src="/image" alt="image" width={300} height={300} />
  <br />
  <Image src="/image" alt="image" width={300} height={300} />
</div>
```

```
c: f f f f f f f nw: 0 0 0 0 0 0 0
c: t t t t t t t nw: 0 0 0 0 0 0 0
c: t t t t t t t nw: 0 0 0 0 0 0 0
...
```

The Playwright test below for `img.loaded` fails, because all images are broken (host unreachable) but reports `img.complete = 'true'`

```
Failed to load resource: the server responded with a status of 400 (Bad Request)
```

```ts
await page.goto('/12-multiple-fail-unreachable');
for (const img of await page.getByRole('img').all()) {
  await expect(img).toHaveJSProperty('complete', true);
  await expect(img).not.toHaveJSProperty('naturalWidth', 0);
}
```

**Comment by karlhorky** [comment] 2024-07-17 17:08
For waiting for all (visible) lazy-loaded images on the page to load, I wrote [a new trick](https://github.com/karlhorky/playwright-tricks#load-all-lazy-images) for this, which also [tests image loading with `naturalWidth`](https://github.com/microsoft/playwright/issues/6046#issuecomment-1803609118):

```ts
const lazyImages = await page.locator('img[loading="lazy"]:visible').all();

for (const lazyImage of lazyImages) {
  await lazyImage.scrollIntoViewIfNeeded();
  await expect(lazyImage).not.toHaveJSProperty('naturalWidth', 0);
}
```

Be aware, [using `.all()` can be problematic if new images are being added, removed, shown or hidden while the test code is running](https://github.com/microsoft/playwright/issues/31737).

One workaround for this is to assert the length of the `.all()` array (if you know it) to wait for it to stabilize:

```ts
const lazyImagesLocator = page.locator('img[loading="lazy"]:visible');

// Assert on length to wait for image visibility to stabilize
// after client-side JavaScript hides some images
// https://github.com/microsoft/playwright/issues/31737#issuecomment-2233775909
await expect(lazyImagesLocator).toHaveCount(13);

const lazyImages = await lazyImagesLocator.all();

for (const lazyImage of lazyImages) {
  await lazyImage.scrollIntoViewIfNeeded();
  await expect(lazyImage).not.toHaveJSProperty('naturalWidth', 0);
}
```

Source: https://github.com/karlhorky/playwright-tricks#load-all-lazy-images

**Comment by mitar** [comment] 2025-12-11 10:01
Based on suggestion above, we used:

```js
  for (const img of await page.getByRole("img").all()) {
    await expect(img).toHaveJSProperty("complete", true)
    await expect(img).not.toHaveJSProperty("naturalWidth", 0)
  }
```

But this proved flaky because images are queried once in `getByRole` but then in `expect` they are re-queried and the state might have changed in between.

Instead, we started using:

```js
  await page.waitForFunction(() => {
    return Array.from(document.querySelectorAll("img")).every((img) => img.complete && img.naturalWidth > 0)
  })
```
