### ISSUE TITLE
[Bug]: Video recordings are longer than the test execution

### ISSUE THREAD

**Issue by frvwfr2** [microsoft/playwright#11103] opened 2021-12-22 18:19 UTC
### Playwright version

Version 1.17.0-rc1

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

Python 3.7.3

### What happened? / Describe the bug

When recording videos, the video duration is about 1.5x as long as the run itself. In the sample code below, the total time to execute was around 42 seconds, but the video is 48 seconds.

This problem is exacerbated for longer runs, with some videos running nearly 2x as long as the run itself depending on workflow. (for ex, one run was 4m22s, but the video is 8m27s)

### Code snippet to reproduce your bug

```shell
from playwright.sync_api import sync_playwright
import logging

with sync_playwright() as p:
    logging.basicConfig(level=logging.getLevelName("DEBUG"), format='%(asctime)s %(levelname)6s %(message)s')
    browser = playwright.chromium.launch(headless=True)
    context = browser.new_context(ignore_https_errors=True, record_video_dir="Output")
    page = context.new_page()

    logging.debug("STARTING RUN")
    page.goto(f"http://www.google.com", wait_until="commit")
    page.wait_for_timeout(5000)
    logging.debug("LOOPING")
    page.goto(f"http://www.yahoo.com", wait_until="commit")
    page.wait_for_timeout(5000)
    logging.debug("LOOPING")
    page.goto(f"http://www.cnn.com", wait_until="commit")
    page.wait_for_timeout(5000)
    logging.debug("LOOPING")
    page.goto(f"http://www.reddit.com", wait_until="commit")
    page.wait_for_timeout(5000)
    logging.debug("LOOPING")
    page.goto(f"http://www.cbs.com", wait_until="commit")
    page.wait_for_timeout(10000)
    logging.debug("LOOPING")
    page.goto(f"http://www.espn.com", wait_until="commit")
    page.wait_for_timeout(10000)
    logging.debug("ENDING RUN")
```

### Relevant log output

```shell
2021-12-22 13:14:47,633  DEBUG STARTING RUN
2021-12-22 13:14:52,819  DEBUG LOOPING
2021-12-22 13:14:58,128  DEBUG LOOPING
2021-12-22 13:15:03,297  DEBUG LOOPING
2021-12-22 13:15:08,663  DEBUG LOOPING
2021-12-22 13:15:18,859  DEBUG LOOPING
2021-12-22 13:15:29,045  DEBUG ENDING RUN
```

**Comment by aslushnikov** [comment] 2022-01-03 16:05
I can reproduce this on tip-of-tree with the following snippet:

I get `automation: 51.477s` while the video itself is 63 seconds.

```javascript
// a.mjs

import { chromium } from '@playwright/test';

const browser = await chromium.launch();

console.time('automation');
const page = await browser.newPage({
  ignoreHTTPSErrors: true,
  recordVideo: {
    dir: 'output',
  }
});

for (const [url, delay] of [
  ['http://www.google.com', 5000],
  ['http://www.yahoo.com', 5000],
  ['http://www.cnn.com', 5000],
  ['http://www.reddit.com', 5000],
  ['http://www.cbs.com', 10000],
  ['http://www.espn.com', 10000],
]) {
  await page.goto(url, { waitUntil: 'commit' });
  await page.waitForTimeout(delay);
}

await browser.close();
console.timeEnd('automation');
```

**Comment by taievizi** [comment] 2022-01-19 08:18
Got the same issue using Playwright 1.16

**Comment by kgeis** [comment] 2022-07-20 19:30
Probably a duplicate of #9611.

**Comment by retroace** [comment] 2023-06-06 12:36
I am also facing the same issue. In my case I am generating captions during the playwright run. Doing this I wanted to mark some portions to slice off in final video. But I get the time between this and video a bit different.

**Comment by pavelfeldman** [comment] 2024-04-22 17:55
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Closed by pavelfeldman** 2024-04-22 17:55 UTC
Labels: P3-collecting-feedback, feature-video

**Comment by kozzza** [comment] 2024-11-10 06:05
I'm also running into this issue. Anyone have a fix?

**Comment by Ice-Hazymoon** [comment] 2024-12-28 19:37
Same issues

**Comment by kozzza** [comment] 2024-12-28 20:04
Solution I found was to scale the video recording time down to sync it with the test time.

Speed up the video: `video_time = video_time * test_time/video_time`

**Comment by Ice-Hazymoon** [comment] 2024-12-29 07:00
> Solution I found was to scale the video recording time down to sync it with the test time.
> 
> Speed up the video: `video_time = video_time * test_time/video_time`

This looks useful. but If you don't have scenarios that require using playwright, I recommend using puppeteer + [puppeteer-screen-recorder](https://www.npmjs.com/package/puppeteer-screen-recorder), which will give you better video quality, won't have timing misalignment issues, and directly outputs in mp4 format.

**Comment by DuhastMish** [comment] 2025-01-15 14:47
> Solution I found was to scale the video recording time down to sync it with the test time.
> 
> Speed up the video: `video_time = video_time * test_time/video_time`

Can you send an code example to change the video duration?

**Comment by DuhastMish** [comment] 2025-01-15 14:47
> Solution I found was to scale the video recording time down to sync it with the test time.
> 
> Speed up the video: `video_time = video_time * test_time/video_time`

@kozzza 
Can you send an code example to change the video duration?

**Comment by utro8am** [comment] 2025-04-23 17:18
Easy to check with JS timer on the screen. Just record the page for 3 minutes and you will see that in is exactly 3 minutes on the page timer, but recording is 10-20% longer duration. 

<img width="988" alt="Image" src="https://github.com/user-attachments/assets/f40956db-1d0b-4fa7-91eb-be8965edf642" />
