### ISSUE TITLE
[BUG] Firefox possibly Memory and CPU Leak

### ISSUE THREAD

**Issue by ledahosn** [microsoft/playwright#12464] opened 2022-03-02 16:59 UTC
**Context:**
- Playwright Version: 1.19.1
- Operating System: Windows
- Node.js version: v16.14
- Browser: Firefox
- Extra: Multiple Proxies (randomProxy Object) sometimes the Proxy fails to load the Site fast enough

```javascript
const playwright = require('playwright')

let browser = null

async function initPlaywright () {
  browser = await playwright.firefox.launch({
    headless: true,
    proxy   : { server: 'per-context' }
  })
}

async function fetchPage (url) {
  if (browser === null) {
    await initPlaywright()
  }

  const context = await browser.newContext({
    proxy: {
      server: `http://${randomProxy.ip}:${randomProxy.port}`,
      username: randomProxy.user,
      password: randomProxy.password
    }
  })

  const page = await context.newPage()
  try {
    await page.goto(url, {
      waitUntil: 'domcontentloaded',
      timeout  : 30000
    })
  } catch (e) {
    page.close()
    context.close()
    console.info(`Playwright: Couldn't fetch ${url} - closed Page`)
    throw e
  }

  let res = await page.innerText('body')

  await page.close()
  await context.close()

  return res
}

(async () => {
  let i = 1
  
  while (i++ < 1500) {
    await fetchPage('https://some-url.com')
  }
})()
```

**Describe the bug**

The Problem I have is that when I execute something like this the main firefox.exe Process has a Memory and CPU Leak.

~4-7GB RAM
~50% usage on a i5-10600K

Even if all Requests are finished and there is no Context Open I get at least 20% CPU and 3GB RAM Usage while doing nothing.

If I start a Browser for each Page its fixed - but that adds alot, really alot of CPU Usage and slows down the entire Program.

Only way I would know that I can fix it to implement a Queue that restarts the Browser every ~100-200 Requests.

Thank you very much!

**Comment by yury-s** [comment] 2022-03-07 23:52
I cannot reproduce it without proxy and with `https://playwright.dev/` as the url, the memory footprint doesn't grow above 1.5G, this is on Linux though. It may well be a bug in Firefox also it seems that it depends on the type of the content of the pages you load, can you provide actual urls where it reproduces and check if it fails without the proxy settings?

**Comment by yury-s** [comment] 2022-03-11 23:35
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by pavelfeldman** [comment] 2022-03-14 20:15
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2022-03-14 20:15 UTC
Labels: triaging, browser-firefox
