### ISSUE TITLE
[WebKit] Page.route() doesn't seem to work as expected on Linux.

### ISSUE THREAD

**Issue by Cai-Zhenhui** [microsoft/playwright#11937] opened 2022-02-08 01:27 UTC
**Context:**
- Playwright Version: 1.18.1
- Operating System: Linux(Ubuntu 20.04 LTS)
- Python version: 3.8.10
- Browser: WebKit
- Extra: 

**Code Snippet**
```python
import asyncio
from playwright.async_api import async_playwright, Route, Request


async def func(url):
    async with async_playwright() as p:
        _browser = await p.webkit.launch(proxy={"server": "socks5://127.0.0.1:10808"})
        _context = await _browser.new_context()
        page = await _context.new_page()

        async def _hook_request(route: Route, request: Request):
            new_headers = {
                **request.headers,
                'TEST': 'test123456789',
                'Cookie': 'AAAA=NBBBB; '
            }
            print(request.url)
            print(new_headers)
            await route.continue_(headers=new_headers)
            pass
        await page.route('*',_hook_request)
        await page.goto(url, wait_until='networkidle', timeout=5*60*1000)
        print(await page.inner_text('*'))
        await _context.close()
        await _browser.close()
        pass
    pass


async def main():
    await func('http://httpbin.org/get')
    pass


if __name__ == '__main__':
    asyncio.run(main())
    pass
```

**Describe the bug**

Execute the above code, the output is as follows:

```
http://httpbin.org/get
{'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'upgrade-insecure-requests': '1', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15', 'TEST': 'test123456789', 'Cookie': 'AAAA=NBBBB; '}
{
  "args": {}, 
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", 
    "Accept-Encoding": "gzip, deflate", 
    "Accept-Language": "en-US", 
    "Host": "httpbin.org", 
    "Test": "test123456789", 
    "Upgrade-Insecure-Requests": "1", 
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15", 
    "X-Amzn-Trace-Id": "Root=1-6201c3e4-5f3435bf320770fd1c183156"
  }, 
  "origin": "104.245.96.65", 
  "url": "http://httpbin.org/get"
}
```
Apparently the Hook request and then modifying the cookie fails.If I change my browser to Chromium it works as expected, but there are some other issues. By the way the same code works as expected under Windows.

**Comment by pavelfeldman** [comment] 2022-02-09 03:07
Where did you obtain the second object, I can't see it printed.

**Comment by Cai-Zhenhui** [comment] 2022-02-09 04:18
Thanks Reply.
The second object is output on line 23 `print(await page.inner_text('*'))` in the above code.

**Comment by pavelfeldman** [comment] 2022-02-09 06:16
Does it only happen when you are trying to modify request headers while connected over the proxy?

**Comment by Cai-Zhenhui** [comment] 2022-02-09 06:28
I just tried it again without the proxy and the result is the same.

**Comment by yury-s** [comment] 2022-02-09 21:11
The problem is in the format of `'AAAA=NBBBB; '`, it ends with the cookie [separator](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie) and webkit doesn't like it (other browsers are more tolerant to this). As a workaround you can pass `'AAAA=NBBBB'`

**Comment by yury-s** [comment] 2022-02-09 23:09
Hmm, in recent webkit event well formatted values are not sent.

**Comment by Cai-Zhenhui** [comment] 2022-02-10 02:08
Unfortunately it still doesn't seem to work.
```python
import asyncio
from playwright.async_api import async_playwright, Route, Request


async def func(url):
    async with async_playwright() as p:
        _browser = await p.webkit.launch(
                #proxy={"server": "socks5://127.0.0.1:10808"}
        )
        _context = await _browser.new_context()
        page = await _context.new_page()

        async def _hook_request(route: Route, request: Request):
            new_headers = {
                **request.headers,
                'TEST': 'test123456789',
                'Cookie': 'AAAA=NBBBB'
            }
            print(request.url)
            print(new_headers)
            await route.continue_(headers=new_headers)
            pass
        await page.route('*',_hook_request)
        await page.goto(url, wait_until='networkidle', timeout=5*60*1000)
        print(await page.inner_text('*'))
        await _context.close()
        await _browser.close()
        pass
    pass


async def main():
    await func('http://httpbin.org/get')
    pass


if __name__ == '__main__':
    asyncio.run(main())
    pass
```

The output is as follows:

```
http://httpbin.org/get
{'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'upgrade-insecure-requests': '1', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15', 'TEST': 'test123456789', 'Cookie': 'AAAA=NBBBB'}
{
  "args": {}, 
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", 
    "Accept-Encoding": "gzip, deflate", 
    "Accept-Language": "en-US", 
    "Host": "httpbin.org", 
    "Test": "test123456789", 
    "Upgrade-Insecure-Requests": "1", 
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15", 
    "X-Amzn-Trace-Id": "Root=1-62047204-5f80f74067f2c5b52fef1594"
  }, 
  "origin": "my ip", 
  "url": "http://httpbin.org/get"
}
```

**Comment by yury-s** [comment] 2022-02-10 02:23
Yeah, it doesn't work on webkit linux. I'm looking into it.

**Comment by Cai-Zhenhui** [comment] 2022-02-12 07:20
Thank you for your attention and look forward to the solution of the problem.

**Comment by pavelfeldman** [comment] 2022-10-20 06:11
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-10-20 06:11 UTC
Labels: browser-webkit, upstream

**Comment by lesha1201** [comment] 2022-10-24 11:18
I have a similar issue. I use [msw](https://mswjs.io/) and [playwright-msw](https://github.com/valendres/playwright-msw) which under the hood intercepts all requests using `page.route`. In my case, cookies are set in WebKit but in playwright intercepted requests don't have cookies in headers even though I can see that WebKit browser included them (I can see it from devtools). In other browsers, cookies are properly included in intercepted requests but for WebKit they aren't.

Can you please re-open this issue?

**Context:**
Playwright Version: 1.27.1
Operating System: WSL (Ubuntu 20.04)
Browser: WebKit 1724
