### ISSUE TITLE
[BUG]playwright install error：unable to verify the first certificate

### ISSUE THREAD

**Issue by bo-don** [microsoft/playwright#20590] opened 2023-02-02 12:31 UTC
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.30.0
- Operating System: [e.g. Windows, Linux or Mac] Windows
- Node.js version: [e.g. 12.22, 14.6]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```shell
playwright install
```

**Describe the bug**

![bug](https://user-images.githubusercontent.com/35206653/216325646-e5613213-24c0-4d60-8dba-edbe6425abae.png)

**Comment by dgozman** [comment] 2023-02-02 17:03
@bo-don Most likely, you have broken root certificates on your machine or there is a proxy that changes certificates, so Playwright cannot download over `https`. I don't think we'll be able to help.

**Comment by mxschmitt** [comment] 2023-02-06 10:11
Since this is a general Node.js exception, you need to make sure Node.js will like your custom certificate chain, maybe caused by proxies etc. Nothing we can act on our side, so closing for now.

**Closed by mxschmitt** 2023-02-06 10:11 UTC
Labels: triaging
