### ISSUE TITLE
[Bug]: `stylePath` parameter in `toHaveScreenshot` doesn't work

### ISSUE THREAD

**Issue by aidinabedi** [microsoft/playwright#29478] opened 2024-02-13 16:42 UTC
### Version

1.41.2

### Steps to reproduce

1. Clone my repo at https://github.com/aidinabedi/playwright-stylepath-bug
2. npm install
3. npm run test
4. Observe that the actual screenshot in the failing test doesn't contain any custom styling, even though the [`stylePath` parameter in `toHaveScreenshot`](https://github.com/aidinabedi/playwright-stylepath-bug/tree/main/tests/example.spec.ts#L8) is correctly assigned

### Expected behavior

The expected screenshot should contain custom styling (from [`tests/screenshot.css`](https://github.com/aidinabedi/playwright-stylepath-bug/tree/main/tests/screenshot.css)), to make it look like to:

![example-1-expected](https://github.com/microsoft/playwright/assets/255073/f834ad46-bdae-449b-b9ae-e0052ea6691a)

### Actual behavior

The actual screenshot doesn't contain any custom styling (from [`tests/screenshot.css`](https://github.com/aidinabedi/playwright-stylepath-bug/tree/main/tests/screenshot.css)), even though the [`stylePath` parameter in `toHaveScreenshot`](https://github.com/aidinabedi/playwright-stylepath-bug/tree/main/tests/example.spec.ts#L8) is correctly assigned:

![example-1-actual](https://github.com/microsoft/playwright/assets/255073/5569910e-e481-4e80-bcd7-9ff208030c16)

### Additional context

Please note that assigning `stylePath` via the [test config](https://playwright.dev/docs/api/class-testconfig#test-config-expect) does seem to work as expected. The bug seems to be isolated to passing `stylePath` as parameter when calling `toHaveScreenshot`, as shown in the [official documentation](https://playwright.dev/docs/test-snapshots#stylepath).

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (48) x64 AMD Ryzen Threadripper 3960X 24-Core Processor
    Memory: 36.69 GB / 71.88 GB
  Binaries:
    Node: 20.11.0 - ~\AppData\Local\Volta\tools\image\node\20.11.0\node.EXE
    npm: 10.2.4 - ~\AppData\Local\Volta\tools\image\node\20.11.0\npm.CMD
  IDEs:
    VSCode: 1.86.1 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.41.2 => 1.41.2
```

**Comment by mxschmitt** [comment] 2024-02-13 18:23
Looks like a duplicate of https://github.com/microsoft/playwright/issues/29249

Could you try on Canary? https://playwright.dev/docs/canary-releases

**Comment by mxschmitt** [comment] 2024-02-14 08:59
Thanks for the great repro! Can confirm that it works with `npm install @playwright/test@next` - which will be in v1.42.

**Closed by mxschmitt** 2024-02-14 08:59 UTC
