### ISSUE TITLE
[BUG] Playwright fails to locate element in docker 

### ISSUE THREAD

**Issue by tse-demo** [microsoft/playwright#19263] opened 2022-12-05 03:47 UTC
**Context:**
- Playwright Version: 1.28.0
- Operating System: Linux (Ubuntu Jammy)
- Node.js version: v14.20.0
- Browser: Chromium
- Extra: 
- Our test harness setup:
![Playwright - Test Harness](https://user-images.githubusercontent.com/59363255/205540705-e05ea00e-2de5-4e59-aece-48011c084f3e.jpg)
Playwright installations are done outside the browser instances.
```groovy
sh "npm install && npm install @playwright/test@${params.PLAYWRIGHT_VERSION} && npx playwright@${params.PLAYWRIGHT_VERSION} install"
```

- 

```bash
\Env Info: npx envinfo --preset playwright --markdown

## System:
 - OS: Linux 4.4 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
 - Memory: 5.26 GB / 6.00 GB
 - Container: Yes
## Binaries:
 - Node: 14.20.0 - /usr/local/scaligent/toolchain/local/bin/node
 - Yarn: 1.22.4 - /usr/local/scaligent/toolchain/local/bin/yarn
 - npm: 6.14.8 - /usr/local/scaligent/toolchain/local/bin/npm
## Languages:
 - Bash: 5.1.16 - /usr/bin/bash
## npmPackages:
 - playwright-har: ^0.1.1 => 0.1.1 
```
**Code Snippet**

```typescript
import { PlaywrightHar } from 'playwright-har';
import { test } from '../../fixtures/blink';

test.describe('Chart scenarios', () => {
  let playwrightHar = null;
  let title: string = '';

  test.beforeEach(async ({ page }) => {
    playwrightHar = new PlaywrightHar(page);
    await playwrightHar.start();
  });

  test.afterEach(async () => {
    await playwrightHar.stop(`./debug/${title}.har`);
    playwrightHar = null;
  });

  test('demo1 test1 should load a chart', async ({ navigationPage, dataPage }, testInfo) => {
    title = testInfo.title;
    await navigationPage.goToSearchPage(); //After the navigation step, everything else fails.
    await navigationPage.goToDataPage(); //After the navigation step, everything else fails.
    await dataPage.goToTable('WORKSHEET 1');
  });

  test('demo1 test2 should load a table', async ({ navigationPage, dataPage }, testInfo) => {
    title = testInfo.title;
    await navigationPage.goToSearchPage(); //After the navigation step, everything else fails.
    await navigationPage.goToDataPage(); //After the navigation step, everything else fails.
    await dataPage.goToTable('WORKSHEET 1');
  });
});

```

navigationPage.ts
```typescript
    async setDefaultFlags() {
    const myURL = new URL(config.BASE_URL);
    myURL.searchParams.set('onboarding', 'false');
    myURL.searchParams.set('userPersona', 'business_user');

    return myURL.toString();
    }

    async goToSearchPage() {
    await this.page.goto((await this.setDefaultFlags()) + '/#/search/', { timeout: 0 });
    }

    async goToDataPage() {
    await this.page.goto((await this.setDefaultFlags()) + '/#/data/', { timeout: 0 });
    }

```

dataPage.ts
```typescript
    async goToTable() {
      await this.page.locator(this.selectors.searchBar).click();
      await this.page.locator(this.selectors.searchBar).fill(tableName);
      await this.page.locator(this.selectors.tableName, { hasText: tableName }).first().waitFor();
      await this.page.locator(`[aria-label="${tableName}"]`).first().waitFor();
      await this.page.locator(`[aria-label="${tableName}"]`).first().click();
    }

```

**Describe the bug**
Even though you can clearly see the elements present in the trace, PW fails at the first step relating to finding elements on the page. Please let us know if you require further logs. Thanks

<img width="783" alt="Screenshot 2022-12-05 at 9 19 38 AM" src="https://user-images.githubusercontent.com/59363255/205545460-f4a4023d-2bd5-478c-9da0-993facb6b960.png">

**Comment by gauravgandhi1315** [comment] 2022-12-05 19:20
It happened to me once but adding `wait` or using different locator fixed the problem for me.

**Comment by tse-demo** [comment] 2022-12-06 02:03
I have tried multiple different locators and waittime, @gauravgandhi1315. It all fails at the first occurrence of finding an element

**Comment by aslushnikov** [comment] 2022-12-06 08:20
> Even though you can clearly see the elements present in the trace, PW fails at the first step relating to finding elements on the page.

@tse-demo how come you see the element? Do you see it in the DOM snapshot in the trace viewer? Can you send me the trace?

**Comment by tse-demo** [comment] 2022-12-06 08:52
> > Even though you can clearly see the elements present in the trace, PW fails at the first step relating to finding elements on the page.
> 
> @tse-demo how come you see the element? Do you see it in the DOM snapshot in the trace viewer? Can you send me the trace?

@aslushnikov yes, i can see it in the DOM snapshot in the trace. I have forwarded the trace file to your email. Thank you

**Comment by aslushnikov** [comment] 2022-12-06 09:30
@tse-demo hmm I don't see anything. Was is anlushni [at] microsoft [dot] com?

**Comment by tse-demo** [comment] 2022-12-06 09:47
> 
> @tse-demo hmm I don't see anything. Was is anlushni [at] microsoft [dot] com?
I got it from https://aslushnikov.com/. Its @gmail.com

**Comment by tse-demo** [comment] 2022-12-09 17:56
Absolutely @aslushnikov I just emailed you the link (to: anlushni@microsoft.com) Thank you!

**Comment by aslushnikov** [comment] 2022-12-10 00:10
(I requested permissions to access the file)

**Comment by tse-demo** [comment] 2022-12-10 02:05
> (I requested permissions to access the file)
Access granted for both emails @aslushnikov

**Comment by aslushnikov** [comment] 2022-12-11 10:13
@tse-demo ok I have access to the traces; I can see the element indeed. 

Does this repro outside of docker container? Can you share some access to the website under test and this repro so that we can debug this issue?

**Comment by aslushnikov** [comment] 2022-12-15 17:23
@tse-demo Discussion has staled here; I'll close the issue. However, please do re-file once there's a repro that we can run locally to reproduce!

**Closed by aslushnikov** 2022-12-15 17:23 UTC
Labels: triaging

**Comment by joel-blueberry** [comment] 2025-03-18 00:20
@aish-ts did you ever find a solution to this? I'm having the exact same issue where headless in docker can't find the locator, I've added waits and tried diff locators but nothing. Get By Role seems to behave normally though.
