### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by saravananpb** [microsoft/playwright#23890] opened 2023-06-25 22:06 UTC
I am passing data from CSV and trying to fill the web form which will also open another tab and click on final submit button.

as per test scenrio one test case acutally need to be passed and another test case need to be failed due to validation error will occur when click on submit button for test case 2, but playwright result show both test are pass and sometime it's showing correct result, how to resolve this inconsistency?

await page1.getByRole('button', { name: 'Submit' }).click();
            await page1.screenshot({ path: `example.png` });
            
            
        });
     }

**Comment by mxschmitt** [comment] 2023-06-26 07:36
We need a clear reproduction which we can run locally with expected and actual outcome. If you are not able to provide that, we unfortunately can't act on it. Sharing just the tests might also be helpful in some scenarios, to make sure you are following [best practises](https://playwright.dev/docs/best-practices). Thanks for your understanding.

**Comment by aslushnikov** [comment] 2023-07-03 14:16
@saravananpb I'll have to close this since it's not actionable without a repro, and the discussion has stalled. Please do not hesitate to file a new issue if you think we still can be helpful and you have a good repro for us!

**Closed by aslushnikov** 2023-07-03 14:16 UTC
Labels: triaging
