### ISSUE TITLE
[Question] I'm Unable to download browser binaries using Playwright in our organization

### ISSUE THREAD

**Issue by KingsonSamuel** [microsoft/playwright#14822] opened 2022-06-13 10:48 UTC
As per our previous analysis we found the below case :

Playwright Version: [v1.22.0]
Operating System: [Windows]
Java version: ["1.8.0_121"]
Browser: [ Chromium]
Extra: [Executing from a company or enterprise]

Error Description - On executing Playwright , script is failed to download browser binaries.

Error message :
 Failed to install browsers
Error: Failed to download chromium v978106, caused by
Error: connect ETIMEDOUT 13.107.219.51:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)

Debugging performed -

Able to access the below URL using powershell script as well as Manually

"https://playwright.azureedge.net/builds/chromium/1005/chromium-win64.zip"

Note - But PowerShell took some time to get response

For more Info - https://github.com/microsoft/playwright/issues/14616

Question - DO I have any chance of working on Playwright inside my organization ?

**Comment by KingsonSamuel** [comment] 2022-06-13 14:55
I could able to download webkit, firefox, ffmpeg. Only issue is with Chromium. Is there any way to download chromium manually

**Comment by dgozman** [comment] 2022-06-14 00:46
@KingsonSamuel I'm not sure how we can help here. Seems like network issues on your end. Perhaps chromium is the largest archive and it takes a while to download?

Note that you can download archives manually, host them somewhere locally inside your organization and tell Playwright to use it through `PLAYWRIGHT_DOWNLOAD_HOST`. Take a look [at the documentation](https://playwright.dev/docs/browsers#download-from-artifact-repository).

You can get the urls by running the following in PowerShell:
```poweshell
$env:DEBUG="pw:install"
npx playwright install
```

**Comment by AlexNaga** [comment] 2022-06-14 07:28
I'm also getting similar errors, both locally and in the Bitbucket pipeline.

`Failed to install browsers
Error: Failed to download chromium v956323, caused by
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
`

**Comment by dgozman** [comment] 2022-06-14 17:52
Temporary Azure outage has been resolved. See [here](https://status.azure.com/) for current status.

@KingsonSamuel @AlexNaga Do you still experience this issue?

**Comment by dgozman** [comment] 2022-06-20 04:04
Closing as per above.

**Closed by dgozman** 2022-06-20 04:04 UTC
Labels: triaging
