### ISSUE TITLE
[BUG] Memory increases when same context is used

### ISSUE THREAD

**Issue by Romain-P** [microsoft/playwright#6319] opened 2021-04-26 11:15 UTC
**Context:**
- Playwright Version: Latest (today is 26/044/2021)
- Operating System: Linux
- Node.js version: tested on both node.js version
- Browser: chromium

**Describe the bug**

I'm watching full-js apps (e.g react/angular websites). I initialize one instance, 1 browser and 1 page.
I keep the page in cache & retrieving content every 2 seconds.

After 1/2hours, the memory goes crazy. I tried to `reload()` the page every 30 minutes. It doesn't free the memory.
Only way to free the memory is closing the page and recreating a new one.

What could be the source of this memory leak? I suppose `reload()` frees the javascript-vm so it must be a leak internally to the page

**Comment by mxschmitt** [comment] 2021-04-26 14:19
Currently the objects for e.g. request/response/route get only flushed when a new context is created. For testing you typically create a new context for each test. I folded a few issues into this one of users who also faced into that, so we can better keep track of it and might find a workaround for it in the future.

**Comment by Romain-P** [comment] 2021-04-26 23:20
I am recreating the page every 1 hour this is the only work around I have found to keep the memory stable.
Why would recreating the context actually helps? I mean doing `page.close()` and the re-allocating a page using `page.newPage()` is fixing the issue

**Comment by mxschmitt** [comment] 2021-04-27 09:50
`browser.newPage` does internally also create a new context for you and close it once you close the page, so its basically a helper wrapper to simplify its usage.

**Comment by VikramTiwari** [comment] 2021-06-03 05:30
Hey @mxschmitt  Are there some other similar quirks that can be used to lower memory/CPU usage? I am starting to look into performance and parallelization of our tests and things like this would be helpful. Thanks!

**Comment by mxschmitt** [comment] 2021-06-03 08:54
The Playwright test runner gets released soon, stay tuned! It handels all that for you.
Headless requires mostly less cpu/memory than headed.

**Comment by LDubya** [comment] 2021-08-07 16:41
> Currently the objects for e.g. request/response/route get only flushed when a new context is created

Is this intended functionality? While testing is one use case for a headless browser, data science related activities such as scraping are another, and that field is growing. In those instances, you may not want to create an entirely new context, as the cookies may be important. But if you're retrieving content every two seconds, you can hit 1,800 requests in an hour, and that can easily amass to over 1GB of additional memory usage within an hour if all of their requests and responses are being stored. I think being able to have the page flush requests and responses when new ones are sent would be a useful feature. While headless browsers have their origins in browser testing, scraping is a major selling point for using headless browsers and this memory leak leads programs to break.

**Comment by gigitalz** [comment] 2021-09-04 17:44
If I make several requests per minute it leaks memory all over the place. I've tried closing pages, closing context, even closing the main playwright instance all the time, nothing works, it still leaks memory and at some point the GC thrashes completely with the CPU setting on fire. 

You should provide and/or document a way to fully release all resources so that we can clear it out every now and then. Don't just focus on testing, it's full of other use cases where playwright is needed to run long long times.

**Comment by gigitalz** [comment] 2021-09-04 17:52
This is taken with JProfiler. This is the experience of running this longer than 30 min...

**Comment by CookiesEason** [comment] 2021-09-07 06:30
![image](https://user-images.githubusercontent.com/25817954/132295230-2e1aded2-e158-4b6d-b19f-32980aff3eb5.png)
when I run job for a long time, the memory used too much.
![image](https://user-images.githubusercontent.com/25817954/132295377-6989904b-d322-4d4a-a732-67bac73b3b7f.png)

**Comment by gigitalz** [comment] 2021-09-10 19:58
Is there a way to properly dispose the whole thing without terminating the process launching it?

**Comment by rigwild** [comment] 2021-09-12 20:29
> I have a case where I make several requests per minute, it leaks memory all over the place. I've tried closing pages, closing contexts, closing browsers, catching all the onClose events and reclosing everything all together, even closing the main playwright instance all the time, nothing works, it still leaks memory and at some point the GC thrashes completely with the CPU setting on fire.
> 
> Please provide and/or document a way to fully release all resources so that we can clear it out every now and then. Please don't just focus on testing, it's full of other use cases where playwright is needed to run long long times.
> 
> ![jprofiler_R3kyHEskfF](https://user-images.githubusercontent.com/85067607/132104053-d2dfbd2f-e1ed-45a4-be27-0ffbb36865db.png)

I have the exact same issue. Use case: scrapping/botting.

Here is a ultra-simple repro:

```ts
import { chromium } from 'playwright'

const setup = async () => {
  const browser = await chromium.launch({ headless: false })
  let page = await browser.newPage()

  let i = 0
  while (true) {
    for (; i < 20; i++) {
      console.log(i)
      await page.goto('https://v3.vuejs.org/guide/introduction.html#declarative-rendering')
    }
    console.log('Trying to create a new context, does not fix the leak!')
    await page.close()
    page = await browser.newPage()
    i = 0
  }
}

setup()
```

Both this and https://github.com/microsoft/playwright/issues/8775 are probably duplicates. It shows that there is an issue with playwright itself and not with chromium or webkit.

For readers having the same issue, as a **temporary** workaround you might use [PM2](https://pm2.keymetrics.io/) with the [memory limit config](https://pm2.keymetrics.io/docs/usage/memory-limit/). It will restart the process when the limit is reached.
This is far from ideal though, but it will do the trick for now.

**Comment by LuizFelipeNeves** [comment] 2021-12-27 04:00
Something that can help if it hasn't already been done is optimizing requests, ignoring unnecessary things like images.

**Comment by LDubya** [comment] 2021-12-27 19:22
@LuizFelipeNeves images can be very important, depending on what you are doing. The project that I used playwright for needed to take screenshots of webpages, and the images mattered a whole lot. Automated browsers have lots of different use cases.

**Comment by LuizFelipeNeves** [comment] 2021-12-29 17:35
@LDubya you're right, in my case I managed to alleviate the situation by closing the pages, and opening new ones, re using context, instead of reloading and having a memory increase.

**Comment by liuyazhou1991** [comment] 2022-02-11 02:33
> The Playwright test runner gets released soon, stay tuned! It handels all that for you. Headless requires mostly less cpu/memory than headed.


@mxschmitt Can you tell us when you expect to solve this problem? I'm going to make a decision. This problem is very important to me.

**Comment by mxschmitt** [comment] 2022-02-11 03:03
@liuyazhou1991 it's called Playwright Test see here: https://playwright.dev/docs/intro

**Comment by AIGeneratedUsername** [comment] 2022-04-10 08:00
I've tried to call `page.close()` and `context.close()` and open a new context and page on every 100 `page.goto(url)` calls. I see that your statement that memory is cleaned on a context close is not correct. After ~8 hours of running and about 200,000 network requests (context and page is closed/opened on every 100 requested URLs), Playwright memory usage is about 10 Gigabytes.

In other words, while the bug is not fixed, the workaround is to close not only a browser context but also a whole browser (e.g. `await browser.close()`) on every N requests, depending on how many free RAM you have. I did not checked whether `browser.close()` cleans memory, maybe it will be also required to open/close a whole `async_playwright` context manager to flush memory.

**Comment by AIGeneratedUsername** [comment] 2022-04-28 20:14
> Maybe would be worth it to add this to the documentation since it would save other people time to avoid this use case.

I think it may be not to hard to make persistent logging optional (so a user may opt-out from any debugging) to reduce memory and CPU overhead.

I would like only to add to the documentation a note about how important is to do not forget to close browser pages. I think this may be a common gotcha: 
- a developer opens a browser page, then do some things with the page and leaves it open...
- then the developer opens a new browser page, etc.

@itepifanio Double-check that you close unnecessary pages (e.g., do not keep open thousands of browser pages).

**Comment by jvi-infare** [comment] 2022-05-06 09:12
Hi all,

I believe that I had very similar issue which I've resolved by modifiying lib\server\browserContext.js and removing context listener from instrumentation map.

I've noticed that when new a context is created, it's being inserted into instrumentation map (lib\server\instrumentation.js) by calling this.instrumentation.addListener(contextDebugger, this); but when it's closed, removeListener is never called (or at least that's happening it my case) so context stays in the map and memory won't get released.

I made some testing for ~12 hours by creating, utilizing and then closing thousands of contexts and they all left hanging in this map even though they were all closed and only "parent" browser was left opened. All the browser tabs were also closed, except for the "parent" one. NodeJS was consuming gygabytes of RAM and once I removed all the listeners, memory was flushed.

I can try to provide more details if you think that this might be the case.

**Comment by roy-k** [comment] 2022-05-21 17:28
I am using pageshot to save images, but the memory increased obvious~
when check code line by line, I find this: It seems pageshot method case a memory leak?

1. **the heap keeps even I didn't use the Buffer**
<img width="904" alt="image" src="https://user-images.githubusercontent.com/21359236/169662255-9313c956-c086-45cd-b2e1-7467c59de711.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/21359236/169662343-f44746ea-645c-4443-a455-2a1707f01a95.png">

2. **and when delete this code, the Retained Size clear**:
<img width="998" alt="image" src="https://user-images.githubusercontent.com/21359236/169662422-2a94f2fc-0380-44df-a710-716aa9a26847.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/21359236/169662452-48a6771e-6c29-425b-9ece-92b416356f5e.png">

**Comment by dgtlmoon** [comment] 2022-06-01 16:16
I can confirm the same, `1.22.0`, python

```
            browser = browser_type.connect_over_cdp(self.command_executor, timeout=timeout * 1000)

            context = browser.new_context(
                user_agent=request_headers['User-Agent'] if request_headers.get('User-Agent') else 'Mozilla/5.0',
                proxy=self.proxy,
                # This is needed to enable JavaScript execution on GitHub and others
                bypass_csp=True,
                # Should never be needed
                accept_downloads=False
            )

            page = context.new_page()
            response = page.goto(url, timeout=timeout * 1000, wait_until=None)
            page.screenshot(type='jpeg', clip={'x': 1.0, 'y': 1.0, 'width': 1280, 'height': 1024})

            context.close()
            browser.close()
 ```

I saw memory usage up to about 1.5Gb this morning, what is curious is that it's not _all_ URL/pages that cause this, I'll report more info

**Comment by vinismarques** [comment] 2022-06-05 13:18
I'm also facing this issue with Python.
Node.js JavaScript Runtime consumed more than 4 GB of RAM before crashing. My use case is scraping, so I only need to open one Browser, one Context, and one Page. After that, I should be able to navigate through the website without a problem. But what I'm actually seeing is that the RAM usage for Node.js JavaScript Runtime keeps growing.

**Comment by roniemartinez** [comment] 2022-06-07 09:46
Same here on Python. I got almost 6GB memory usage doing `page.goto()` on a few hundred URLs before crashing (this is just one page).

**Comment by z719893361** [comment] 2022-06-25 11:25
Have you solved it

**Comment by roniemartinez** [comment] 2022-06-25 14:00
@z719893361 For me, I did a workaround. But this is something that cannot be replicated with simple code.

Solution was to close the page for each `goto()`: https://github.com/roniemartinez/dude/pull/174

**Comment by limestackscode** [comment] 2022-07-04 04:12
when you `await response.body()` playwright caches the whole response in memory forever (closing the page does not free the memory for me `page.close()` and closing the browser does not free the memory for me `browser.close()`) causing node to use increasingly more memory.
after 24 hours node was using 13GB of memory!
example
```javascript
const { firefox } = require('playwright')
const path = require('path')
const fs = require('fs')

async function memoryLeak(page){
	page.on('requestfinished', request => {
		if(path.extname(request.url()) == '.ts'){
			if(request.postDataBuffer() == null){
				request.response().then(async (response) => {
					let header = response.headers()
					if(header['content-type'] == 'application/octet-stream'){
						if(header.hasOwnProperty('transfer-encoding')){
							await response.body()
						}
					}
				})
			}
		}
	})
}

(async () => {
	const browser = await firefox.launch({headless: true,firefoxUserPrefs: {'media.volume_scale': '0'}}) 
	const page = await browser.newPage()
	await page.goto('https://www.twitch.tv/relaxingfan')
	memoryLeak(page)
})();
```

some way to free cached responses and requests would be nice

**Comment by mxschmitt** [comment] 2022-07-04 08:14
@limestackscode Browser.newPage() does create a new context for you internally. You can re-create your context, and then it will release the memory accordingly.

**Comment by dgtlmoon** [comment] 2022-07-04 17:47
@mxschmitt yeah, I spun up a simple python script https://github.com/dgtlmoon/playwright-python-memleak-test/blob/master/README.md  , I know I can see the problem in another app (using Flask) but I can't reproduce it, I'm using `newPage()` and `page.close()` 

If I leave my other app running, it will balloon out to gigabytes

I hope my little repo can get us closer to the answer somehow

**Comment by limestackscode** [comment] 2022-07-04 21:25
@mxschmitt you're right i edited my comment but its weird that in my tests just closing the page doesnt clear the memory i had to close the page and open a new page

**Comment by jfp1992** [comment] 2022-07-29 14:53
Also having this issue, we need to run our tests linearly and I would save a lot of execution time keeping one browser session. But over time the memory leak gets too much and the CI environment locks up because it fills up the memory.

**Comment by arpowers** [comment] 2022-07-29 20:19
@aslushnikov whats the status of the memory leak fix? 

In our case, we get memory leaking on a per context basis even if we close context AND the browser itself. No clear way of restoring it to baseline, so we are triggering a health check fail. Super duper hacky trying to run Playwright in production ... 

 Seems like there is a fix though, has it been pushed? 

<img width="530" alt="Screen Shot 2022-07-29 at 1 17 19 PM" src="https://user-images.githubusercontent.com/308134/181837257-55f36894-471a-42b6-8810-30e38e4f3fb9.png">

**Comment by MattHorrocksNetwealth** [comment] 2022-08-01 19:17
We're finding the same thing @arpowers 


![image](https://user-images.githubusercontent.com/106080163/182228366-ccbc2c9e-90f3-4c0b-ad60-46d83e58effd.png)

We're closing the contexts, then the browser...

```
                foreach (var context in Browser.Contexts)
                {
                    logger.Info("Closing Context " + context);
                    await context.CloseAsync();
                }

                logger.Info("Closing Browser");
                await Browser.CloseAsync();
```

**Comment by MattHorrocksNetwealth** [comment] 2022-08-02 21:22
@mxschmitt 

Here's a very simple c# project which exhibits the memory leak, despite all pages, contexts and the browser being closed in the ```TearDown``` at the end of each test.

https://github.com/MattHorrocksNetwealth/playwright-leak

Using Visual Studio, select all the tests, then Debug run.

Notice the memory steadily increasing.

![image](https://user-images.githubusercontent.com/106080163/182475615-5fe725e7-8179-4f6f-b457-1cce07a7b54f.png)

**Comment by mxschmitt** [comment] 2022-08-02 21:32
> @mxschmitt
> 
> Here's a very simple c# project which exhibits the memory leak, despite all pages, contexts and the browser being closed in the `TearDown` at the end of each test.
> 
> https://github.com/MattHorrocksNetwealth/playwright-leak
> 
> Using Visual Studio, select all the tests, then Debug run.
> 
> Notice the memory steadily increasing.
> 
> ![image](https://user-images.githubusercontent.com/106080163/182475615-5fe725e7-8179-4f6f-b457-1cce07a7b54f.png)
> 
> Of course, I might be doing something incorrect here, but it seems to me that all resources should be freed.
> 
> Happy to pitch in to get this resolved.

You are not disposing the Playwright object, which would release the 60MB.

**Comment by MattHorrocksNetwealth** [comment] 2022-08-02 21:44
Damn, I just noticed that myself :D

What a doughnut.

**Comment by MattHorrocksNetwealth** [comment] 2022-08-02 22:03
I'll fix the example tomorrow and let you know how I get on. I'm sure in our main framework we do dispose of the playwright object correctly, and we still lose memory, though.

**Comment by VikramTiwari** [comment] 2022-08-03 17:48
Hey @mxschmitt, thanks for looking into this issue.

A quick question on this issue. Would the memory still be cleared if the new page was closed from something that's not PW? For example, an extension that creates and closes page while PW is connected. I understand that PW will see this page object and do all the necessary setup. However, would this page object be cleared from the browser context when it's closed by extension?

**Comment by Meemaw** [comment] 2022-08-24 13:22
We're facing the same issues trying to reuse browser context, and just creating a `newPage` for each request.

We are closing the pages, but Playwright seems to not dispose those references and the memory leak is quite server on a http server.

This is very easy to reproduce, I could prepare a reproducer if needed.

**Comment by LuohuaRain** [comment] 2022-08-24 15:21
> We're facing the same issues trying to reuse browser context, and just creating a `newPage` for each request.
> 
> We are closing the pages, but Playwright seems to not dispose those references and the memory leak is quite server on a http server.
> 
> This is very easy to reproduce, I could prepare a reproducer if needed.

Actually, I did all reproducers last year, but nothing feedback till now.

**Comment by nickdooley2016** [comment] 2022-08-24 21:15
Any solution? Why after a year there is still no fix? This problem hinders playwright's usability, coders will seek alternatives. There's nothing more annoying than wasting time integrating a third-party package to find out later that it's riddled with bugs and incompetent developers.

**Comment by thomasol** [comment] 2022-08-24 21:18
They have explained you must close the context and dispose of the playwright object. 
You can't keep the context alive for a long time. A stupid comment like that helps no one.

**Comment by nickdooley2016** [comment] 2022-08-24 21:23
> They have explained you must close the context and dispose of the playwright object. You can't keep the context alive for a long time. A stupid comment like that helps no one.

Do you close your browser every time you navigate to a new URL? I know you don't. This is not a solution to the problem.

**Comment by vinismarques** [comment] 2022-08-24 21:25
The need to close the context and dispose of the playwright object might not be possible/desirable when working with RPA or even scraping infinite scroll pages. It adds a considerable amount of code to work around the bug.

**Comment by rigwild** [comment] 2022-08-24 21:28
Please, can a maintainer lock this conversation? New comments just keep repeating each other. Everything has already been said. Closing the context does not fix the issue.

Repro provided at comment https://github.com/microsoft/playwright/issues/6319#issuecomment-917705023

**Comment by nickdooley2016** [comment] 2022-08-24 22:12
> Please, can a maintainer lock this conversation? New comments just keep repeating each other. Everything has already been said. Closing the context does not fix the issue.
> 
> Repro provided at comment [#6319 (comment)](https://github.com/microsoft/playwright/issues/6319#issuecomment-917705023)

And yet we still have no fix. I'll be digging into the source code later on to see if I can flush it or signal a flush somehow. Obviously developers won't be doing anything about this.

**Comment by nickdooley2016** [comment] 2022-08-25 15:16
I resolved my issue by doing the following.

1. Saved the browser's state (session, local storage, etc using after creating the browser/context and performing the actions required for my situation:
    `context.StorageState("state.json")`

1. Close browser and it's context every 30 minutes

2. Kill all node.exe processes (this is where the memory leak exists for me), if you don't kill them it will create a separate node.exe process and the previous one will remain in memory taking up space.

3. Create new browser/context and load in the saved state.. navigate back to where you need to be.
    `context, err := browser.NewContext(
		playwright.BrowserNewContextOptions{
			StorageStatePath: playwright.String("state_good.json"),
                })
    `

While this won't help with infinite scroll or other scenarios it might help some of you. A good example where this would work fine is creating a session with a QR code (for my situation) or after a simple login.

**Comment by dgtlmoon** [comment] 2022-08-30 13:54
Tip - I incorrectly blamed playwright for a memory leak in my app, I have a class which wraps playwright todo a little web-page IO, initially to me it looked like `page.evaluate()` and other calls were causing the memory to get used and never recycled/emptied
However strangely, when I tried the following, (from https://github.com/weblyzard/inscriptis/issues/65 ) it also resolved the issue where `page.evaluate(...)` used a lot of RAM and never returned it back to the system (it returns a very large JSON struct)

```
  import ctypes
  libc = ctypes.CDLL("libc.so.6")
  libc.malloc_trim(0)
```

My advice here - try to be sure that your own app is not doing something unexpected, be 100% sure that something like LXML's memory leak bug is not lurking around somewhere

**Comment by maximveksler** [comment] 2022-09-08 12:13
> I have a case where I make several requests per minute, it leaks memory all over the place. I've tried closing pages, closing contexts, closing browsers, catching all the onClose events and reclosing everything all together, even closing the main playwright instance all the time, nothing works, it still leaks memory and at some point the GC thrashes completely with the CPU setting on fire.
> 
> Please provide and/or document a way to fully release all resources so that we can clear it out every now and then. Please don't just focus on testing, it's full of other use cases where playwright is needed to run long long times.
> 
> ![jprofiler_R3kyHEskfF](https://user-images.githubusercontent.com/85067607/132104053-d2dfbd2f-e1ed-45a4-be27-0ffbb36865db.png)

Which utility was used to plot this graph? I would like to reproduce the experiment.

**Comment by gigitalz** [comment] 2022-10-01 11:41
> > I have a case where I make several requests per minute, it leaks memory all over the place. I've tried closing pages, closing contexts, closing browsers, catching all the onClose events and reclosing everything all together, even closing the main playwright instance all the time, nothing works, it still leaks memory and at some point the GC thrashes completely with the CPU setting on fire.
> > Please provide and/or document a way to fully release all resources so that we can clear it out every now and then. Please don't just focus on testing, it's full of other use cases where playwright is needed to run long long times.
> > ![jprofiler_R3kyHEskfF](https://user-images.githubusercontent.com/85067607/132104053-d2dfbd2f-e1ed-45a4-be27-0ffbb36865db.png)
> 
> Which utility was used to plot this graph? I would like to reproduce the experiment.
> 
> @rigwild :) ?

JProfile

This issue is still happening.

**Comment by gigitalz** [comment] 2022-10-01 18:44
> Any solution? Why after a year there is still no fix? This problem hinders playwright's usability. There's nothing more annoying than wasting time integrating a third-party package to find out later that it's riddled with bugs and incompetent developers.

I'll have to  ditch this tool very soon if this is not resolved, so annoying.

**Comment by dgtlmoon** [comment] 2022-10-01 18:50
@gigitalz 

> I'll have to ditch this tool very soon if this is not resolved, so annoying.

you can always ask for your money back :dancers:

**Comment by gigitalz** [comment] 2022-10-01 19:04
> I resolved my issue by doing the following.
> 
> 1. Saved the browser's state to a local file (session, local storage, etc) after creating the browser/context and performing the actions required to meet my needs:
>    `context.StorageState("state.json")`
> 2. Close browser, context and kill all node.exe processes every 30 minutes. (this is where the memory leak exists for me), if you don't kill them it creates a separate node.exe process every time. The previous process remains in memory taking up space.
> 3. Create new browser/context and load in the saved state.. navigate back to where you need to be.
>    `context, err := browser.NewContext( playwright.BrowserNewContextOptions{ StorageStatePath: playwright.String("state.json"), }) `
> 
> While this won't help with infinite scroll or other scenarios it might help some of you. A good example where this would work fine is creating a session with a QR code (for my situation) or after a simple login.

Kind of did the same thing, except I didn't have to save any state, just killed the whole playwright process tree and relooped to create a new spin of the same stuff. Cringe AF.

**Comment by gigitalz** [comment] 2022-10-01 19:05
> @gigitalz
> 
> > I'll have to ditch this tool very soon if this is not resolved, so annoying.
> 
> you can always ask for your money back 👯

Very funny, I can't because I can't go back in time, moron.

**Comment by ldexterldesign** [comment] 2022-10-01 22:25
👋 @gigitalz

Ignore @dgtlmoon - he's very opinionated about open source since he released his "paid hosted service"

The sooner someone with interpersonal skills forks his project the better

Regards

**Comment by jfp1992** [comment] 2022-10-03 07:02
Looks like they're not going to fix this https://github.com/microsoft/playwright/issues/17736

**Comment by Gin-Quin** [comment] 2023-02-07 10:39
I also encountered this memory that caused the server to crash every hour. I had no choice but to switch to Puppeteer, and not only the memory was stable, but the page loading was also faster.

Switching to Puppeteer is the best workaround to me. I used the following Dockerfile:

```dockerfile
FROM node:19.6.0-alpine

# Installs latest Chromium package.
RUN apk add --no-cache \
      chromium \
      nss \
      freetype \
      harfbuzz \
      ca-certificates \
      ttf-freefont \
      dumb-init

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

# Copy the files necessary for the build
# ... 

# Install and build
RUN npm install

RUN npm build

# Expose and run the server
EXPOSE 8080
CMD ["node", "build"]
```

**Comment by LeMoussel** [comment] 2023-02-24 12:06
With Node JS v16.17.1 & Playwright v1.26.1, this problem no longer seems to be an issue.
I run it about 60 minutes, 2000 pages loaded.
**Repro:**
```javascript
import { chromium } from 'playwright'

const setup = async () => {
  const browser = await chromium.launch({ headless: false })
  let page = await browser.newPage()

  let j = 0
  while (true) {
    for (let i = 0; i < 20; i++) {
      console.log(j, i)
      await page.goto('https://httpbin.org/delay/1')
    }

    j++;

    console.log('Trying to create a new context, does not fix the leak!')
    await page.close()
    page = await browser.newPage()
  }
}

setup()
```

![image](https://user-images.githubusercontent.com/1816573/221173607-a29a77ad-164c-4683-b63f-15d64bc610ba.png)

**Comment by CrazedCoderNate** [comment] 2023-03-09 14:58
@gigitalz 

I have the same issue. In my use case I am running 100+ Playwright instances every minute. I've tried closing the page, browser, browser context and Playwright instance. I've even tried nulling the objects for the GC to free up any resources. There is clearly a leak in playwright. My current solution is to force restart process every time it leaks but this is an awful hacky solution. Has anyone found a fix for this issue?

If one of the libraries does not have this leak, I would re-write my program in that language. Currently I am using Java's Playwright.

![image](https://user-images.githubusercontent.com/15204470/224063205-bb3fa3d2-b1fd-43e1-b9df-e87b9e766d71.png)

**Comment by Gin-Quin** [comment] 2023-03-09 16:14
I deactivated Javascript loading and execution and my memory leak seems to be gone. Or it is still here, but with very low numbers so it's fine. If Javascript is not important, you might want to deactivate it.

Resources on how to do it:

(deactivating Javascript execution)
https://stackoverflow.com/questions/65958243/disable-javascript-in-playwright

(blocking loading Javascript)
https://scrapingant.com/blog/block-requests-playwright

**Comment by CrazedCoderNate** [comment] 2023-03-13 15:56
I think it was user error. I ended up creating a bare bones pool where I created Browsers, Browser Pools, Contexts in a pool and cleared them each time I navigated to a new URL. Using a profiler, this is what my resource usage looks like: 
![image](https://user-images.githubusercontent.com/15204470/224756322-e4515a57-e49e-498d-b637-54967f549490.png)
If you have issues with these browsers, I recommend trying to build barebones architecture with multithreading, then porting over to larger use case. Cheers.

**Comment by LeMoussel** [comment] 2023-03-13 16:16
@CrazedCoderNate:
What tool do you use to see this?
Do you have some examples for creating a bare bones pool?

**Comment by CrazedCoderNate** [comment] 2023-03-13 16:56
@LeMoussel 

Sure thing!  I used [VisualVM](https://visualvm.github.io/). It is free and it works great for what I needed it for!

I uploaded [the project here](https://github.com/CrazedCoderNate/BrowserMemTest/tree/main) for this bare bones browser pool.

**Comment by hyytest** [comment] 2023-03-22 03:18
Why does using page.close() to close the browser process still exist? This is a very serious memory consumption, is there any solution?

**Comment by tzbo** [comment] 2023-07-02 22:04
Any update?

**Comment by vonkoff** [comment] 2023-07-03 05:02
I would love a solution as well. I am using ` const context = await browser.newContext();` and then ` const page = await context.newPage();` and still getting this. Trying to do infinite scroll for certain pages. Even after finishing that the memory usage just keeps increasing...

**Comment by jfp1992** [comment] 2023-07-03 06:56
> I would love a solution as well. I am using ` const context = await browser.newContext();` and then ` const page = await context.newPage();` and still getting this. Trying to do infinite scroll for certain pages. Even after finishing that the memory usage just keeps increasing...

I raised an issue for this, it got closed, then a dev responded somewhere for me to remake the ticket. I got lazy as I put time into it. 

Anyway, make a loop spamming about:blank and watch the memory usage for python / node (both increase pretty much in tandem). If you do it for a bigger page, like amazon.com it goes up much faster

A solution for this would be to allow us to clear the memory out. I tried garbage clear in python but nothing changes. 

If this would ruin the traces or something I'd understand, but we should still be able to manually clear it with a disclaimer on the method or something

**Comment by vonkoff** [comment] 2023-07-03 18:07
For anyone doing this in typescript/javascript you can use my code. I have my node app running in a docker container. So, to clear up chromium browsers that are left unopened I just run the code below if I get an error trying to open another browser and after everytime I close a browser in the for loop I have running a list of url's to scrape

```ts
import { exec } from 'child_process';

// Function to execute the killall node command
export function killAllNode() {
  exec('killall node', (error, stdout, stderr) => {
    if (error) {
      console.error(`Error executing killall node: ${error.message}`);
      return;
    }
    if (stderr) {
      console.error(`killall node stderr: ${stderr}`);
      return;
    }
    console.log(`killall node stdout: ${stdout}`);
  });
}
```

**Comment by vonkoff** [comment] 2023-07-03 18:18
> still same issue

Using the code I use in my project?

**Comment by tzbo** [comment] 2023-07-03 22:12
I think it's a stupid design in playwright. Any programmer will hate the memory problem and that is not in this control.

**Comment by LeMoussel** [comment] 2023-07-04 06:02
@vonkoff  It's not Windows compliant.

On Windows machine, to kill a Node.js server, and you don't have any other Node processes running, you can tell your machine to kill all processes named `node.exe`. That would look like this:

`taskkill /im node.exe`

And if the processes still persist, you can force the processes to terminate by adding the `/f` flag:

`taskkill /f /im node.exe`

**Comment by vinismarques** [comment] 2023-07-04 12:49
Besides not being a proper solution, I would just like to make it clear that restarting everything is just not feasible is some cases, like when you are working on a infinite scroll page. If you restart, you are doomed. 

Thought I would reiterate on this just so that no one thinks there is a good way to solve this issue. The bug should be fixed.

**Comment by dgtlmoon** [comment] 2023-07-04 12:57
> I think it's a stupid design in playwright. Any programmer will hate the memory problem and that is not in his control.

@tzbo tough comment, why dont you make something better?

**Comment by gigitalz** [comment] 2023-07-04 13:31
> @tzbo tough comment, why dont you make something better?

This is the usual dump f. take people come when they have zero priority to solve a ticket.

**Comment by tzbo** [comment] 2023-07-04 13:58
It's tough and it's a long time ticket. There is no better solution in two years to solve memory problem. Do you think it's a good design? Maybe the original intention is to simplify usage. Of courese it's more simple than puppeteer in some senario. But I think at least it should keep some release memory funtions which mean I call these funtions. I promise I will not use previouse response and ....  
context.close? no, it can not release memory. I used it at previous version. Another, I don't want to close it.So I migrate to pupppeter.
I wish playwright will be better soon. It supports more browsers.

**Comment by ldexterldesign** [comment] 2023-07-04 17:52
👋 @gigitalz,

dgtlmoon isn't well socialised

Ignoring is the only language he speaks

Regards

**Comment by lanyuer** [comment] 2023-07-08 10:04
This is also a very confusing issue for us. As long as we keep opening new pages within the loop, the memory keeps increasing continuously. We have encountered several OOM errors recently.

**Comment by pavelfeldman** [comment] 2023-07-08 17:19
We have all the feedback we need for this issue and it is currently pending due to prioritization. I'll disable the comments since they no longer add actionable details to the issue.

**Comment by pavelfeldman** [comment] 2023-09-26 23:29
Unbounded heap growth should be mitigated by https://github.com/microsoft/playwright/commit/ffd20f43f8ee1a7a016cd9b29c372e25ec685a62. The heap will still saturate to a certain size (10K handles per object type, ~50-100Mb on average), but will stop growing afterwards.

**Closed by pavelfeldman** 2023-09-26 23:29 UTC
Labels: P3-collecting-feedback

**Comment by adripo** [comment] 2023-10-03 10:59
@pavelfeldman will this fix be included in the next release?

**Comment by dgtlmoon** [comment] 2023-10-03 11:43
Apart from making demands to people I dont know like some previous commenters, I would like to thank Pavel for adding that heap stack test to npm, that's a super cool idea. And generally thank the maintainers for their incredible work here, it's a highly complex project!

**Comment by gauravkhuraana** [comment] 2023-11-23 12:01
I face this issue in Azure Dev Ops agent pipeline. Locally all test run fine.. we have 200+ test and 5-6 run in parallel at a time.. after 8 minutes of running build it fails with 

 <--- Last few GCs --->
 [12856:000002C6125D7660]      111 ms: Scavenge 7.9 (9.1) -> 7.6 (9.8) MB, 0.9 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure; 
 [12856:000002C6125D7660]      142 ms: Scavenge 8.4 (9.8) -> 8.0 (10.1) MB, 0.8 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure; 
 [12856:000002C6125D7660]      192 ms: Scavenge 8.7 (10.1) -> 8.2 (10.1) MB, 35.7 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure; 
 <--- JS stacktrace --->
 FATAL ERROR: NewSpace::Rebalance Allocation failed - JavaScript heap out of memory
  1: 00007FF621C4194F 
  2: 00007FF621BC6026 
  3: 00007FF621BC7D10 
  4: 00007FF6226721F4 
  5: 00007FF62265D582

**Comment by ludmilanesvitiy** [comment] 2023-11-27 13:02
After update from 1.29.1 to the latest 1.40.0, started to receive the error:
         _page.goto: The object has been collected to prevent unbounded heap growth._
And yes, I know that I'm not using page.close() to close the window after each test, because it's necessary to speedup tests. With  closing page after each test, the error about memory usage disappeared, but appearing another problems, which I do not need to solve.

So, for now decided to downgrade to prev version.
Any fix to the lib will be appreciated. Let me know if it's done in some new release. Thanks.

PS. I have about 800 scenarios, each of them has about 15 separate steps. In average, on the 300-350th test they become to fail.

**Comment by mxschmitt** [comment] 2023-11-27 13:09
We need unfortunately a reproduction case in order to debug issues like that. A small repository would be ideal. I'm going to lock this for now, so others can re-file and we can work on the missing scenarios, thanks!
