### ISSUE TITLE
[REGRESSION]: migrating from locator.type to locator.fill is a breaking change

### ISSUE THREAD

**Issue by bel0v** [microsoft/playwright#28920] opened 2024-01-09 18:03 UTC
`locator.type()` is marked as deprecated, with the suggestion `In most cases, you should use locator.fill(value[, options]) instead.`

`.type` focuses the input and puts in the text right **next to the previous value**.
`.fill` on the other hand **clears up the input** and fills it with new text, behaving like
```
await locator.clear()
await locator.type()
```
We have been using `.type` in our tests and thanks to that, found a bug in our codebase related to unwanted input. We would not have found it with using `.fill` — and thus not sure we should migrate to a less informative method.

**Comment by dgozman** [comment] 2024-01-10 02:39
@bel0v If you don't like the behavior of `fill`, feel free to not use it. There is a [`Locator.pressSequentially()` method](https://playwright.dev/docs/api/class-locator#locator-press-sequentially) that should work for you. Let me know if that's not the case.

**Comment by dgozman** [comment] 2024-01-15 17:05
Closing because there is not action item for Playwright here. If you still encounter problems, please file a new issue with a repro and link to this one.

**Closed by dgozman** 2024-01-15 17:05 UTC

**Comment by maksnester** [comment] 2024-06-21 10:28
Just confirming that [pressSequentially](https://playwright.dev/docs/api/class-locator#locator-press-sequentially) works for me the same way as type, while `fill` doesn't work. 

In my case, the issue is that fill doesn't find the input within a wrapper that contains test-id which I use as a locator e.g.

```
div[data-my-test-id]
  input
```
For this markup fill throws:

> locator.fill: Error: Element is not an <input>, <textarea> or [contenteditable] element

Which I think is inconsistent with `pressSequentially` and the deprecated `type` method.

I know that a label or name-based selector would be kinda better way to do it, but I'm working with what I have here.

**Comment by akwasin** [comment] 2025-01-28 13:50
> Just confirming that [pressSequentially](https://playwright.dev/docs/api/class-locator#locator-press-sequentially) works for me the same way as `type`, while `fill` doesn't work.
> 
> In my case, the issue is that `fill` doesn't find the input within a wrapper that contains test-id which I use as a locator e.g.
> 
> ```
> div[data-my-test-id]
>   input
> ```
> 
> For this markup `fill` throws:
> 
> > locator.fill: Error: Element is not an , <textarea> or [contenteditable] element
> 
> Which I think is inconsistent with `pressSequentially` and the deprecated `type` method.
> 
> I know that a label or name-based selector would be kinda better way to do it, but I'm working with what I have here.
> 
> > Closing because there is not action item for Playwright here
> 
> [@dgozman](https://github.com/dgozman) I think it would be nice to make `fill` work the same way as `type` and `pressSequentially` in terms of finding the input.

Not sure how accurate your description was but the correct way of input data would be
div[data-testid="my-test-id"] and therefore

```
await page.locator('div[data-testid="my-test-id"]).fill('text);
await page.locator('div[data-testid="my-test-id"]). pressSequentially('text', { delay: 100 });
```
