### ISSUE TITLE
[BUG] window.performance.memory serializes to {}

### ISSUE THREAD

**Issue by mastrzyz** [microsoft/playwright#22854] opened 2023-05-05 16:36 UTC
### System info
- Playwright Version: 1.33
- Operating System: Windows 11
- Browser: Edge
- Other info:

### Source code

WORKS -> returns {totalJSHeapSize:1337, usedJSHeapSize:0,jsHeapSizeLimit:0}
```
    const memScript = `
       return {
        totalJSHeapSize: window.performance.memory.totalJSHeapSize,
        usedJSHeapSize: window.performance.memory.usedJSHeapSize,
        jsHeapSizeLimit: window.performance.memory.jsHeapSizeLimit
      };
     `;
```

BAD -> returns {}
```
    const memScript = `return window.performance.memory;`;
```
- [x ] I provided exact source code that allows reproducing the issue locally.

**Steps**
- [Run the test]

Leveraging `window.performance.memory` I'd expect to get an object in return but I instead get `{}`.

`window.performance` itself returns an object without the memory key

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/37447884/236516077-935c11fc-ef17-4177-880f-235219171277.png">

*Note* running this in browser works correctly, I think there is a problem with the object serialization?

**Comment by dolezel** [comment] 2023-05-05 18:00
@mastrzyz I have feeling the issue is in browser itself
![image](https://user-images.githubusercontent.com/8746048/236533544-bc9e8430-a837-435c-af6b-55cdcc8a0e1d.png)

**Comment by Smrtnyk** [comment] 2023-05-05 18:31
Not sure this has something to do with playwright?

**Comment by mastrzyz** [comment] 2023-05-05 20:15
Well the same code : 

  const memScript = `return window.performance.memory;`;

returns an object in Selenium and returns {} in Playwright , hence my confusion here.

**Comment by yury-s** [comment] 2023-05-05 22:06
As pointed above performance.memory is not JSON-serializable by default in the browser and `JSON.stringify(window.performance.memory)` returns `{}`. Playwright behavior is consistent with that. You can manually serialize the object as you described. Closing the bug as this is working as intented.

**Closed by yury-s** 2023-05-05 22:06 UTC
