### ISSUE TITLE
[Feature]: add in the document section for input type=color;

### ISSUE THREAD

**Issue by aksinha214** [microsoft/playwright#31981] opened 2024-08-02 05:14 UTC
### 🚀 Feature Request

While testing website where input type is equal to color is not working while testing with playwright. I have tried by using all the methods or code in the playwright but got failed. I have using locator with Path and also index i have error in chromium, Firefox and also in web kit

### Motivation

Please add code for input type=color:-
await page.locator('//input[@id="color"]').click();   
// @ts-ignore
await page.locator('input[id="color"]').evaluate(function(element){element.value ='#fca8ac'});
await page.locator('//input[@id="color"]').press('Enter')

**Comment by mxschmitt** [comment] 2024-08-02 06:57
You can just use fill for that, see this small snippet:

```ts
  await page.setContent('<input type=color value="#e66465">');

  await page.locator('input').fill('#aaaaaa');

  // Assert that the color has been changed.
  expect(await page.$eval('input', input => input.value)).toBe('#aaaaaa');
```

**Comment by aksinha214** [comment] 2024-08-02 09:31
![image](https://github.com/user-attachments/assets/cf247eed-98e0-4d34-a648-84596441edd7)
i have this type of feild and your code isn't working.

**Comment by aksinha214** [comment] 2024-08-02 09:34
[image: image.png]
I have this type of UI and your code is not able to click the field and
select the color

**Comment by mxschmitt** [comment] 2024-08-02 09:36
We need something we can reproduce/ run locally otherwise we can't act on it. 

Are you able to share your html or a url with us?

**Comment by aksinha214** [comment] 2024-08-02 09:39
HTML code:-
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Multi-Input Form</title>
    <link href="
https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel=
"stylesheet">
    <style>
        body {
            padding: 20px;
            max-width: 650px;
            margin: auto;
        }
        table {
            margin-top: 20px;
            max-width: 700px;
        }
        #tableScroll{
            overflow: auto !important;
        }
        .errdiv {
        color: red;
        font-weight: bold;
      }
    </style>
</head>
<body>
    <div class="container">
        <h2 class="text-center">Js Multi-Input Form</h2>
        <form id="multiInputForm" class="needs-validation" novalidate>
            <div class="form-group">
                <label for="name">Name:<span class="errdiv"> *</span></label
>
                <input type="text" class="form-control" id="name" name=
"name" placeholder="Enter your name" required>
                <div class="invalid-feedback">Please enter your name.</div>
            </div>
            <div class="form-group">
                <label for="email">Email:<span class="errdiv"> *</span></
label>
                <input type="email" class="form-control" id="email" name=
"email" placeholder="Enter your email" required>
                <div class="invalid-feedback">Please enter a correct email.
</div>
            </div>
            <div class="form-group">
                <label for="password">Password:<span class="errdiv"> *</span
></label>
                <input type="password" class="form-control" id="password"
name="password" placeholder="Enter your password" required>
                <div class="invalid-feedback">Please enter a password.</div>
            </div>
            <div class="form-group">
                <label for="number">Contact Number:<span class="errdiv"> *</
span></label>
                <input type="number" class="form-control" id="number" name=
"number" placeholder="Enter your contact number" required>
                <div class="invalid-feedback">Please enter a number.</div>
            </div>
            <div class="form-group">
                <label for="date">Date of Birth:</label><br>
                <small>Select your DOB:<span class="errdiv"> *</span></small
>
                <input type="date" class="form-control" id="date" name=
"date" required>
                <div class="invalid-feedback">Please select a date.</div>
            </div>
            <div class="form-group">
                <label for="color">Favorite Color:</label><br>
                <small>Select your color:<span class="errdiv"> *</span></
small>
                <input type="color" class="form-control" id="color" name=
"color" required>
                <div class="invalid-feedback">Please select a color.</div>
            </div>
            <div class="form-group">
                <label>Gender:</label><br>
                <small>Select your gender:<span class="errdiv"> *</span></
small><br>
                <div class="form-check form-check-inline">
                    <input type="radio" class="form-check-input" id="male"
name="gender" value="male" required>
                    <label class="form-check-label" for="male">Male</label>
                </div>
                <div class="form-check form-check-inline">
                    <input type="radio" class="form-check-input" id="female"
name="gender" value="female" required>
                    <label class="form-check-label" for="female">Female</
label>
                </div>
                <div class="invalid-feedback">Please select your gender.</
div>
            </div>
            <div class="form-group">
                <label>Profession:</label><br>
                <small>Select your profession: <span class="errdiv"> *</span
></small>
                 <div class="form-check">
                    <input type="checkbox"  id="student" name="profession"
value="student">
                    <label class="form-check-label" for="student">Student</
label>
                </div>
                <div class="form-check">
                    <input type="checkbox"  id="employee" name="profession"
value="employee">
                    <label class="form-check-label" for="employee">Employee
</label>
                </div>
                <div class="form-check">
                    <input type="checkbox"  id="trainee" name="profession"
value="trainee">
                    <label class="form-check-label" for="trainee">Trainee</
label>
                </div>
                <div class="form-check">
                    <input type="checkbox"  id="professor" name="profession"
value="professor">
                    <label class="form-check-label" for="professor">
Professor</label>
                </div>
                <div class="invalid-feedback">Please select at least one
profession.</div>
            </div>
            <div class="form-group">
                <label for="country">Country:</label><br>
                <small>Select your country:<span class="errdiv"> *</span></
small>
                <select class="form-control" id="country" name="country"
required>
                    <option value="">Choose...</option>
                    <option value="Nepal">Nepal</option>
                    <option value="India">India</option>
                    <option value="Bangladesh">Bangladesh</option>
                    <option value="Sri Lanka">Sri Lanka</option>
                </select>
                <div class="invalid-feedback">Please select a country.</div>
            </div>
            <div class="form-group">
                <label for="textarea">Feedback message:<span class="errdiv">
*</span></label>
                <textarea class="form-control" id="textarea" name="textarea"
rows="3" placeholder="Enter your feedback:" required></textarea>
                <div class="invalid-feedback">Please enter a feedback
message.</div>
            </div>
            <div class="form-group">
                <label for="file">Upload File:</label>
                <small>Select any your file:<span class="errdiv"> *</span></
small>
                <input type="file" class="form-control-file" id="file" name=
"file"  data-filesize="5242880" data-filesize-error="Max 5MB" required>
            </div>
            <button type="submit" class="btn btn-info">Submit</button>
        </form>

        <h3 class="text-center">Data's from Local Storage:</h3>
        <table class="table table-bordered table-striped table-hover
table-responsive" id="tableScroll" >
            <thead class="table-success">
                <tr>
                    <th>Actions</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Password</th>
                    <th>Contact</th>
                    <th>DOB</th>
                    <th>F-Color</th>
                    <th>Gender</th>
                    <th>Profession</th>
                    <th>Country</th>
                    <th>Feedback</th>
                    <th>File</th>
                </tr>
            </thead>
            <tbody id="dataTable">
                
            </tbody>
        </table>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="script.js"></script>
</body>
</html>

**Comment by aksinha214** [comment] 2024-08-02 10:10
Any update??
If you cannot get answer then use these code:-
 await page.locator('//input[@id="color"]').click()
 // @ts-ignore
 await page.locator('input[id="color"]').evaluate(function(element){element.value ='#fca8ac'});
 await page.locator('//input[@id="color"]').press('Enter')

**Comment by aksinha214** [comment] 2024-08-02 10:15
Any update??
If you cannot get answer then use these code:-
await ***@***.*** <https://github.com/id>="color"]').click()
// @ts-ignore <https://github.com/ts-ignore>
await
page.locator('input[id="color"]').evaluate(function(element){element.value
='#fca8ac'});
await ***@***.*** <https://github.com/id>
="color"]').press('Enter')

**Comment by mxschmitt** [comment] 2024-08-02 11:39
Works for me:

```ts
import { test, expect } from '@playwright/test';
import path from 'path';
import url from 'url';

test('should be able to set a color', async ({ page }) => {
  await page.goto(url.pathToFileURL(path.resolve(__dirname, '../test.html')).href);
  await page.locator('input[type=color]').fill('#00ff00');
});
```

**Comment by aksinha214** [comment] 2024-08-02 12:12
Sorry sir,it again can't work
I give you whole HTML code , i just want to click on color input field and select another color but your code doesn't work

**Comment by mxschmitt** [comment] 2024-08-02 13:12
I used your HTML from https://github.com/microsoft/playwright/issues/31981#issuecomment-2264980028 and the test file in https://github.com/microsoft/playwright/issues/31981#issuecomment-2265175231 which was working for me. We need more information to act on bug reports like this. With exact expected and actual outcome etc.

**Comment by mxschmitt** [comment] 2024-08-02 15:02
I'll close it for now, please re-file with filling out the bug template, thanks!

**Closed by mxschmitt** 2024-08-02 15:02 UTC

**Comment by LeThiDzu** [comment] 2024-11-29 03:08
@aksinha214 Have you solved this issue yet? I've figured out how to handle it. Add "force" when inputting the color. 
Here's an example: `await myPageName.colorPicker.input_primary_color.fill(color_value, { force: true })`
Good luck!
