### ISSUE TITLE
[REGRESSION]: toHaveJSProperty failed with boolean

### ISSUE THREAD

**Issue by tmkx** [microsoft/playwright#14778] opened 2022-06-10 07:46 UTC
**Context:**
- GOOD Playwright Version: 1.15.0
- BAD Playwright Version: 1.16.0
- Operating System: macOS
- Extra: Node.js v16.15.0

**Code Snippet**

```ts
import { expect, test } from '@playwright/test';

test('toHaveJSProperty', async ({ page }) => {
  await page.setContent('<video muted />');

  const video = page.locator('video');

  await expect(video).toHaveJSProperty('muted', true); // ✅ passed
  await video.evaluate<unknown, HTMLVideoElement>((node) => (node.muted = false));
  await expect(video).toHaveJSProperty('muted', false); // ❌ failed
});
```

**Describe the bug**

The second assertion shows "expect.toHaveJSProperty: expectedValue: expected object, got boolean".

But if I change it to `expect(video).toHaveJSProperty('muted', {})`,\
the error became:
```
    Error: expect(received).toHaveJSProperty(expected) // deep equality

    Expected: {}
    Received: false
```

**Comment by mxschmitt** [comment] 2022-06-10 08:14
Sounds like a duplicate of https://github.com/microsoft/playwright/issues/14135 to me. Its already fixed in the code base and gets released in 1.23.

You can also consume the next via `npm install @playwright/test@next` to get the fix.

**Closed** 2022-06-10 08:16 UTC
