### ISSUE TITLE
[BUG] JavaScript heap out of memory with a lot of ConsoleMessages

### ISSUE THREAD

**Issue by JYangHe** [microsoft/playwright#22621] opened 2023-04-25 10:00 UTC
## System info
- Playwright Version: [v1.32.1]
- Operating System: [MacOS]
- Browser: [Chromium]

## Source code
```
import asyncio
from playwright.async_api import async_playwright


async def test():
    try:
        playwright = await async_playwright().start()
        browser = await playwright.chromium.launch(
            headless=False
        )
        context = await browser.new_context(
            locale='en-US',
            java_script_enabled=True
        )
        page = await context.new_page()
        try:
            await page.goto('https://zred-clothing.com/', timeout=30000)
        except Exception as e:
            print(e)
        await asyncio.sleep(10)
        title = await page.title()
        print(title)
        await page.close()
        await page.context.close()
        playwright.stop()
    except Exception as e:
        print(e)

asyncio.run(test())
```

##  Error
```
<--- Last few GCs --->

[11470:0x7f8c0394d000]   121147 ms: Mark-sweep 4022.8 (4141.2) -> 4012.4 (4144.0) MB, 2436.0 / 1.9 ms  (average mu = 0.286, current mu = 0.029) task; scavenge might not succeed
[11470:0x7f8c0394d000]   125350 ms: Mark-sweep 4025.5 (4144.0) -> 4015.2 (4147.0) MB, 4136.5 / 1.8 ms  (average mu = 0.133, current mu = 0.016) task; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10dd18fb5 node::Abort() (.cold.1) [/Users/jyanghe/opt/anaconda3/envs/py39/lib/python3.9/site-packages/playwright/driver/node]
 2: 0x10c799a29 node::Abort() [/Users/jyanghe/opt/anaconda3/envs/py39/lib/python3.9/site-packages/playwright/driver/node]
 3: 0x10c799c0e node::OOMErrorHandler(char const*, bool) [/Users/jyanghe/opt/anaconda3/envs/py39/lib/python3.9/site-packages/playwright/driver/node]
 4: 0x10c928cc3 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/jyanghe/opt/anaconda3/envs/py39/lib/python3.9/site-packages/playwright/driver/node]
 5: 0x10caf1975 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/jyanghe/opt/anaconda3/envs/py39/lib/python3.9/site-packages/playwright/driver/node]
 6: 0x10caf0352 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/jyanghe/opt/anaconda3/envs/py39/lib/python3.9/site-packages/playwright/driver/node]
 7: 0x10cb88161 v8::internal::ScavengeJob::Task::RunInternal() [/Users/jyanghe/opt/anaconda3/envs/py39/lib/python3.9/site-packages/playwright/driver/node]
 8: 0x10c80770e node::PerIsolatePlatformData::RunForegroundTask(std::__1::unique_ptr<v8::Task, std::__1::default_delete<v8::Task> >) [/Users/jyanghe/opt/anaconda3/envs/py39/lib/python3.9/site-packages/playwright/driver/node]
 9: 0x10c806157 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/Users/jyanghe/opt/anaconda3/envs/py39/lib/python3.9/site-packages/playwright/driver/node]
10: 0x10d253f5b uv__async_io [/Users/jyanghe/opt/anaconda3/envs/py39/lib/python3.9/site-packages/playwright/driver/node]
11: 0x10d2689fa uv__io_poll [/Users/jyanghe/opt/anaconda3/envs/py39/lib/python3.9/site-packages/playwright/driver/node]
12: 0x10d254528 uv_run [/Users/jyanghe/opt/anaconda3/envs/py39/lib/python3.9/site-packages/playwright/driver/node]
13: 0x10c6cd773 node::SpinEventLoop(node::Environment*) [/Users/jyanghe/opt/anaconda3/envs/py39/lib/python3.9/site-packages/playwright/driver/node]
14: 0x10c7deb56 node::NodeMainInstance::Run() [/Users/jyanghe/opt/anaconda3/envs/py39/lib/python3.9/site-packages/playwright/driver/node]
15: 0x10c75e48c node::LoadSnapshotDataAndRun(node::SnapshotData const**, node::InitializationResult const*) [/Users/jyanghe/opt/anaconda3/envs/py39/lib/python3.9/site-packages/playwright/driver/node]
16: 0x10c75e733 node::Start(int, char**) [/Users/jyanghe/opt/anaconda3/envs/py39/lib/python3.9/site-packages/playwright/driver/node]
17: 0x7fff2045af3d start [/usr/lib/system/libdyld.dylib]
/Users/jyanghe/opt/anaconda3/envs/py39/lib/python3.9/site-packages/playwright/driver/playwright.sh: line 6: 11470 Abort trap: 6           "$PLAYWRIGHT_NODEJS_PATH" "$SCRIPT_PATH/package/lib/cli/cli.js" "$@"
```

**Comment by mxschmitt** [comment] 2023-04-26 19:46
I can repro.

**Comment by mxschmitt** [comment] 2023-04-26 20:13
The issue is that in 10 seconds this website logs around 55k console messages which has a ~50 character memory footprint each.

Assigning it to this release to have lazy event listeners for console messages like we have for request/response etc.

**Closed** 2023-05-05 18:12 UTC
Labels: v1.34

**Comment by mxschmitt** [comment] 2023-05-06 08:48
Note to myself: works fine after this patch, CPU usage stays at 70% and memory does not grow.
