### ISSUE TITLE
[Bug]: Wait using a POM object 

### ISSUE THREAD

**Issue by CatalinCaila** [microsoft/playwright#29593] opened 2024-02-21 10:07 UTC
### Version

1.41.2

### Steps to reproduce

```js
test('Refuse Trip1', async ( pageSelectTrip,) => {
  const { apiUtils, tripLocatorsCollapse } = global.selectTrip;
 
  await tripLocatorsCollapse.TripCollapse.refuseTrip();
   
  const refuseReason = new TripRefuseReasonLocators(pageSelectTrip)
  await refuseReason.waitForLoadState('networkidle');  - is not waiting the element is not found 
  await refuseReason.TripRefuseReasonActions.closeRefuse()
  // refuseReason.saveTripReason()

  
  //apiUtils.deleteTrip();
});

Using this hardcoded code is working but I want to use it with POM

test.skip('Refuse trip hardcoded', async ({page}) => {
 
    await page.goto('http://localhost:4200/login');
    await page.getByLabel('Username').fill("daccaila@generixgroup.com");
    await page.getByLabel('Password').fill("adminA#12356");
    await page.getByRole('button', { name: 'Login' }).click();
    await page.getByTestId('trips-component-tripCollapsed').first().click();
    await page.getByRole('button', { name: 'Refuse' }).first().click();
    await page.waitForLoadState('networkidle');
    await page.getByTestId("trip-refuse-reason-button-close").click();

  
});
```
### Expected behavior

I expect to have the possibility to wait even if I am using a POM object. It looks like it don't have the page fixture capability. 
How to integrate {page} fixture into current test without creating a new page into browser?

### Actual behavior

The locator is not found because the running of script is to fast 
TypeError: page.getByTestId is not a function
    at TripRefuseReasonLocators (c:\Mobile PlayWrightAutomation\locators\TripRefuseReasonLocators.js:12:44)
    at tests\APITestUILogin.spec.js:62:24

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
    Memory: 2.39 GB / 15.61 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.2 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.86.2 - C:\Users\daccaila\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.41.2 => 1.41.2
    playwright: ^1.41.0 => 1.41.2
```

**Comment by RenanGreca** [comment] 2024-02-21 12:23
If you're working on a single browser window, you can send the `page` fixture to the POM as a construct parameter, as seen in [the documentation](https://playwright.dev/docs/pom#implementation).

**Comment by CatalinCaila** [comment] 2024-02-21 13:55
Is define in the constructor

export class TripRefuseReasonActions {
    constructor(page, locators) {
        this.page = page;
        this.locators = locators;
    }

    async closeRefuse() {
        const { button_closeTripReason } = this.locators;
        await button_closeTripReason.click();
    }

**Comment by yury-s** [comment] 2024-02-21 16:53
> How to integrate {page} fixture into current test without creating a new page into browser?

You need to make sure that the TripRefuseReasonActions is created with the same Page instance as the `page` fixture in the test provides.

Closing as it is not a bug in playwright.

**Closed by yury-s** 2024-02-21 16:53 UTC
