### ISSUE TITLE
Playwright `toMatchSnapshot` against absolute path image

### ISSUE THREAD

**Issue by tanishqkancharla** [microsoft/playwright#18897] opened 2022-11-17 22:41 UTC
Playwright has a utility `toMatchScreenshot` that will test a screenshot of something against a predefined image that is in it's snapshot directory. I would like for it to test against an image that is at an arbitrary absolute path. If I pass in an arbitrary path, it will coerce the path (replace the separators with hyphens) to a path inside the snapshot directory. 

Is there a way I can use playwright's snapshot matching abilities to match against an arbitrary image?

**Comment by dgozman** [comment] 2022-11-21 18:57
@tanishqkancharla `toMatchSnapshot` also handles updating the baseline for you, which is probably undesirable for an image with the absolute path.

If all you need is to compare two images, perhaps you'd better use a specific API for comparing images? For example, [`pixelmatch`](https://www.npmjs.com/package/pixelmatch) library is currently used by Playwright for this purpose.

If you have a different usecase in mind, please share more details of what you are trying to achieve, ideally with a specific example.

**Comment by tanishqkancharla** [comment] 2022-11-21 19:42
Yes that's pretty much what I want, but it's close enough to `toMatchSnapshot` that I think it would be really easy/simple for Playwright to provide this as well out of the box, b/c I know playwright has some abstractions over `pixelmatch` like converting different image formates to png, and maybe a few other things.

Really all I need is a `toMatchImage` matcher that will take a buffer or an (absolute) path to some image file.

**Comment by dgozman** [comment] 2022-11-21 21:13
I'll close this as a duplicate of #18937, let's continue the discussion there.

**Closed by dgozman** 2022-11-21 21:13 UTC
Labels: triaging
