### ISSUE TITLE
[Bug]: With setting Trace "ON" if Test Passes, the trace is not retaining browser logs and network calls 

### ISSUE THREAD

**Issue by rishabhjain-qait** [microsoft/playwright#32530] opened 2024-09-10 07:56 UTC
### Version

1.44.0

### Steps to reproduce

use: {
    trace: 'on',
    actionTimeout: 60 * 1000,
    navigationTimeout: 60 * 1000
  },

using above config.ts  file, the trace setting is on, 
but when the test is running, and getting passed, 
I don't see Browser logs and network calls getting retained, 
only retaining when the test is getting failed, 

There should be some setting with which i should be able to retain browser logs, and Network calls, 
Please help in letting me know if there's a setting for same.  

### Expected behavior

There should be some setting with which i should be able to retain browser logs, and Network calls within a trace of a PASSED test case as well

### Actual behavior

Currently the browser logs, and Network calls are not getting retained within a trace of a PASSED test case

### Environment

```shell
node --version
v22.1.0

npm --version
10.7.0
```

**Comment by dgozman** [comment] 2024-09-10 08:12
@rishabhjain-qait Where do you expect to see the browser logs and network calls? When you set `trace: 'on'`, these are present in the recorded trace. If that's not the case for you, please provide a full repro that we can run locally. Otherwise, we won't be able to help.

**Comment by dgozman** [comment] 2024-09-10 08:46
@rishabhjain-qait Thank you for the screenshot. Unfortunately, this is not a repro, since I cannot run it. Please provide the source code that we can run that exhibits the issue. We cannot help you by just looking at a screenshot.

**Comment by rishabhjain-qait** [comment] 2024-09-10 10:06
@dgozman 
https://github.com/rishabhjain-qait/playwright-automation

you can check using above repo, 

try running the test **google.spec.ts,** 
once passed, just look at the report, 

does not show up screenshot, 
does not show up network calls

**Comment by rishabhjain-qait** [comment] 2024-09-10 10:23
<img width="1157" alt="Screenshot 2024-09-10 at 3 53 30 PM" src="https://github.com/user-attachments/assets/d960e075-998b-41a5-bd0b-c9de516062ab">

**Comment by dgozman** [comment] 2024-09-10 11:30
@rishabhjain-qait Thank you for the repro. You are missing `await context.close()` before closing the browser, and so the browser trace is never retained. Let me know whether adding that call helps.

**Comment by rishabhjain-qait** [comment] 2024-09-10 16:34
thank you for this @dgozman, 

**seems to be working fine after adding above,** 

but if the context is not explicitly closed, and someone is closing the browser directly instead,
**it should have closed the context first and then close the browser,** 
if it is built this way, what are the possible reasons we have kept the context open even after closing the browser

**Comment by dgozman** [comment] 2024-09-10 18:58
@rishabhjain-qait This is by design. We make sure that `browser.close()` never stalls, and therefore it does not record traces/videos/etc. See also [documentation](https://playwright.dev/docs/api/class-browser#browser-new-context) that mentions this. I'll close this issue since there is no action item for Playwright.

**Closed by dgozman** 2024-09-10 18:58 UTC
