### ISSUE TITLE
[Feature] Codegen's "Pick a locator" or "UI mode" Locator improvement

### ISSUE THREAD

**Issue by AleksandrovAlex** [microsoft/playwright#23650] opened 2023-06-12 04:45 UTC
As a user, I would like to have multiple choices of locators in Codegen when I click on an element.

Will it be possible for me to select from a number of locators? Right now, for the site that I try using Playwright the selectors provided from the "Pick a Selector" tool are not the best options. So a user can pick from 3-4-5 different provided selectors? Or this will be done always manually?

**Comment by aslushnikov** [comment] 2023-06-12 19:52
Closing as a dupe of https://github.com/microsoft/playwright/issues/5178

**Closed by aslushnikov** 2023-06-12 19:52 UTC
