### ISSUE TITLE
[Question] Is there a way to get all test files that are about to run?

### ISSUE THREAD

**Issue by murraymichal** [microsoft/playwright#15805] opened 2022-07-20 08:19 UTC
Let's say I ran 

```
npx playwright test --grep=@test
```

Is there a way that I can programatically get names of all test files that are about to run, in e.g. `globalSetup`? Right now there's a way to do this with CLI 
```
npx playwright test --grep=@test --list
```
But can I get this list in code, like from env variable or something?

**Comment by dgozman** [comment] 2022-07-20 18:31
Duplicate of #12147.

**Closed by dgozman** 2022-07-20 18:31 UTC
