### ISSUE TITLE
[QUESTION] How to define 1 worker to run tests in 1 folder

### ISSUE THREAD

**Issue by yanjingtui** [microsoft/playwright#23307] opened 2023-05-26 15:34 UTC
Hi,
I am running tests in typescript. 
My tests folder:
```
tests
├─testBlog
│  ├─001-create-blog.spec.ts
│  ├─002-modify-blog.spec.ts
│  ├─003-delete-blog.spec.ts
├─testArticle
│  ├─001-create-article.spec.ts
│  ├─002-modify-article.spec.ts
│  ├─003-delete-article.spec.ts
└─testUser
   ├─001-create-user.spec.ts
   ├─002-modify-user.spec.ts
   ├─003-delete-user.spec.ts
```
How can I define 3 workers run in parallel and each workers run all 3 test files in 1 folder ? In this case, 1 worker runs tests in /testBlog, 1 work runs tests in /testArticle, 1 worker runs tests in /testUser.

**Comment by aslushnikov** [comment] 2023-05-26 22:20
@yanjingtui you can either:
- run three `npx playwright test --worker 1 testBlog/testArticle/testUser` processes in parallel
- (discouraged) use [test lists](https://playwright.dev/docs/next/test-parallel#use-a-test-list-file)

Out of curiosity, what is your usecase? Why can't you run things just in parallel?

**Comment by yanjingtui** [comment] 2023-05-29 08:43
@aslushnikov In most usecase, we can run tests in parallel, but there are some tests can't run in parallel. For example, I have 1 test file for modification article, and I have another test file for verifying the history of article. If we don't modify the article first, then i can't test the history of article. 
I know if i write test-modification and test-history in same test file will work, but they are two different functions and writing them in a single test file is not that reasonable. So I want to know if there is a way to run some test files in parallel and some test files in serial at the same time.

**Comment by aslushnikov** [comment] 2023-05-31 00:09
I see; looks like something like https://github.com/microsoft/playwright/issues/21970 would help you.

Closing as a dupe of that issue then!

**Closed by aslushnikov** 2023-05-31 00:09 UTC
Labels: triaging
