### ISSUE TITLE
[BUG] dynamic import of ESM results in ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by Janpot** [microsoft/playwright#17075] opened 2022-09-04 16:24 UTC
**Context:**
- Playwright Version: 1.25.1
- Operating System: MacOs
- Node.js version: v16.17.0

**Code Snippet**

```tsx
import { test } from "@playwright/test";

test("dynamic import of ESM", async ({}) => {
  const { default: getPort } = await import("get-port");
  console.log(await getPort());
});
```

**Describe the bug**

From the [node.js docs](https://nodejs.org/api/esm.html#import-expressions)

> [Dynamic import()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) is supported in both CommonJS and ES modules. In CommonJS modules it can be used to load ES modules.

Yet, trying to load an ESM only package like `get-port` with a dynamic import statement fails with the error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module .../node_modules/get-port/index.js from .../tests/example.spec.ts not supported.
    Instead change the require of index.js in .../tests/example.spec.ts to a dynamic import() which is available in all CommonJS modules.
```

It's complaining I'm trying to use `require` to load an ESM only module, but as can be seen in the snippet, it's an `import()`.

**Comment by ilanb1996** [comment] 2022-09-07 07:18
had a very similar issue, had to hardcode `"@playwright/test": "1.22.2",` in my `package.json`

**Comment by dgozman** [comment] 2022-09-07 23:11
@Janpot This indeed does not work. The workaround is to either not use dynamic imports, or set `"type": "module"` in your `package.json`. Perhaps in the future we'll make it work out of the box.

**Comment by frontsideair** [comment] 2023-02-08 17:53
I also suffer from this, many npm packages are moving to [ESM only](https://medium.com/sindre-sorhus/hello-modules-d1010b4e777b) and using `type: module` makes it very hard in my case, since I have some imports to my code and requires me to turn everything to ESM.

It would be very much appreciated if this worked out of the box, or there was a workaround to avoid transpilation (I'm assuming there must be), as I like Playwright a lot and have been using it happily for a long time.

**Comment by frontsideair** [comment] 2023-02-09 18:45
I have a pretty robust workaround, which might be helpful to others as well. The workaround uses esbuild, but could work with other tools.

1. Pull all ESM dependencies in a file like this.
```ts
// deps.ts
import findCacheDir from "find-cache-dir";
import getPort from "get-port";

export { findCacheDir, getPort };
```

2. Install esbuild and add a pretest script.
```json
"pretest": "esbuild --platform=node deps.ts --bundle --outfile=deps.bundle.js",
```

3. Depend on `deps.bundle` in tests.
```
import { findCacheDir, getPort } from "./deps.bundle";
```

If the dependencies get too large, you may get a warning like this and lose some Playwright features.
```
[BABEL] Note: The code generator has deoptimised the styling of /Users/fatih/Code/sweets/e2e/server.bundle.js as it exceeds the max of 500KB.
```

This is the best I could do given the circumstances, let me know if you have a better solution.

**Comment by D4N14L** [comment] 2023-05-07 20:49
@frontsideair curious what features are lost when that error appears? From what I understand, it's largely just a complaint from Babel that can be ignored.

**Comment by frontsideair** [comment] 2023-05-08 08:20
It's been a while, but IIRC you lose the nice error messages when a test fails, that shows the test code that failed as a snippet.

**Comment by olayway** [comment] 2024-04-14 23:50
I have the same issue

**Closed** 2024-06-13 13:18 UTC
Labels: feature-test-runner

**Comment by foxaltus** [comment] 2024-08-20 12:50
So what, does https://github.com/microsoft/playwright/pull/31285 fixes it in v1.45.0?

I just tried using Component Testing with v1.46.1 and got this error right away:

```
> playwright test -c playwright-ct.config.ts

Error: require() of ES Module [...]\node_modules\.pnpm\@mdx-js+react@2.3.0_react@18.2.0\node_modules\@mdx-js\react\index.js from [...]\node_modules\.pnpm\@theme-ui+mdx@0.14.7_@emotion+react@11.11.4_@types+react@18.0.28_react@18.2.0__@mdx-js+react@_mbpdk4bezv7srjm4c3ytb2koyi\node_modules\@theme-ui\mdx\dist\theme-ui-mdx.cjs.dev.js not supported.
Instead change the require of index.js in [...]\node_modules\.pnpm\@theme-ui+mdx@0.14.7_@emotion+react@11.11.4_@types+react@18.0.28_react@18.2.0__@mdx-js+react@_mbpdk4bezv7srjm4c3ytb2koyi\node_modules\@theme-ui\mdx\dist\theme-ui-mdx.cjs.dev.js to a dynamic import() which is available in all CommonJS modules.   
```

**Comment by rclmenezes** [comment] 2024-10-24 19:38
Hmmm I'm still getting this problem.

Here's a reproduction
https://github.com/rclmenezes/playwright-esm-poc

**Comment by dchenk** [comment] 2024-11-25 18:23
This is still a problem. Playwright appears to not support [`package.json` exports](https://nodejs.org/docs/latest-v22.x/api/packages.html#subpath-exports).
