### ISSUE TITLE
[Feature]: Publish webkit changelog

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright#29940] opened 2024-03-14 15:28 UTC
### 🚀 Feature Request

It would be great if we could get the changelog of the webkit updates.

### Motivation

Users don't have visibility on the changes made on Playwright's webkit unless it is tied to a playwright issue.
If a user has a known bug on webkit, e.g. I'm getting a segmentation fault webkit since 1.42 and  it's hard to reproduce in isolation, it would be great to see if the playwright team worked on some issue related to my problem.

**Comment by mxschmitt** [comment] 2024-03-14 16:30
Publishing WebKit change logs wouldn't help either, because usually these are commit ranges of 5-20 thousand commits. From previous experience it showed that most of the crashes are not caused by Playwright, and they are instead actual upstream browser bugs. I recommend filing an issue with a self-contained reproduction, which is needed for us in order to debug issues like this. 

Closing as a non-actionable.

**Closed by mxschmitt** 2024-03-14 16:30 UTC
