### ISSUE TITLE
Docker Run throws an error from node_modules

### ISSUE THREAD

**Issue by cmsqa** [microsoft/playwright#12367] opened 2022-02-25 15:13 UTC
This is docker file

# Prebuilt MS image
FROM mcr.microsoft.com/playwright:focal

WORKDIR /projectname

RUN yarn install --frozen-lockfile

COPY . .

CMD yarn "test:play"

Command to used to build and run
docker build . -f  /tests/e2e/playwright/utils/Dockerfile.e2e -t first-e2e
docker run --rm  first-e2e

while running it, i'm getting below error

this is errro
yarn run v1.22.17
$ yarn run playwright test /Users/usernamme/projectname/tests/e2e/playwright/tests/
$ /apollo1/node_modules/.bin/playwright test /Users/username/projectname/tests/e2e/playwright/tests/
/apollo1/node_modules/playwright-core/lib/cli/innerCli.js:241
    require(playwrightTestPackagePath).addListFilesCommand(_commander.program);
                                       ^

TypeError: require(...).addListFilesCommand is not a function
    at Object.<anonymous> (//node_modules/playwright-core/lib/cli/innerCli.js:241:40)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (//node_modules/playwright-core/lib/cli/cli.js:33:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (//node_modules/playwright-core/cli.js:17:18)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.

Please let me know what i'm missing to make it work

**Comment by mxschmitt** [comment] 2022-02-25 15:16
Looks like you are having different versions of Playwright installed. Only `@playwright/test@1.19.2` is required, no other playwright* packages.

Make sure to have a good node_modules folder, updated lock file and only the test-runner is inside the package.json.

**Comment by cmsqa** [comment] 2022-02-25 15:30
Thanks for getting back. 
I have playwright-test and playwright installed
"@playwright/test": "^1.18.1",
  "playwright": "^1.19.2",
  All the test are written using playwright test, so we will need playwright test

**Comment by mxschmitt** [comment] 2022-02-25 15:37
Yes this is not working, you need to either align the playwright version with the playwright test Version or drop the playwright package. npx playwright install is good enough.

**Comment by cmsqa** [comment] 2022-02-25 16:03
you mean just playwright/test is good enough and no need for playwright

**Comment by cmsqa** [comment] 2022-02-25 16:14
i have aligned both of them to 19.2 but still same issue, so which i need to drop playwright, right?

**Comment by mxschmitt** [comment] 2022-02-25 16:16
Yes, and do a clean installation afterwards (rm -rf node_modules && npm ci)

**Comment by jithinjosejacob** [comment] 2022-02-27 11:12
Try to change your step 3 and 4i in yourDocker file

**Comment by mxschmitt** [comment] 2022-02-28 10:52
This is 100% caused by multiple versions of Playwright which are installed with different versions. This is not supported. Make sure to have a good package.json file (only @playwright/test there), an updated lock file, a good Docker file etc.

Closing for now since this is not a Playwright issue.

**Closed by mxschmitt** 2022-02-28 10:52 UTC
Labels: triaging
