### ISSUE TITLE
[BUG] filechooser.setFiles will fail when filename includes Chinese character

### ISSUE THREAD

**Issue by xiefenga** [microsoft/playwright#28642] opened 2023-12-14 07:28 UTC
### System info
- Playwright Version: 1.40.1
- Operating System: mcr.microsoft.com/playwright:v1.40.0-jammy
- Browser: Chromium

### Source code

[here is reproduce repository](https://github.com/xiefenga/playwright-filechooser-bug-reproduce)

**Steps**
- pull playwright docker image
- run the tests in docker

**Expected**
pass the test

**Actual**
the filechooser.setFiles operation of the file which filename includes Chinese character will fail, then cause expect fail

difference between `filechooser.setFiles('trace.zip')` and `filechooser.setFiles('压缩文件.zip')`

![test---trace-1-chromium-linux](https://github.com/microsoft/playwright/assets/50828665/0d8076e4-8eaa-4768-841a-1d65322694d7)

![test---压缩文件-1-chromium-linux](https://github.com/microsoft/playwright/assets/50828665/790990f1-469c-48ed-99ed-db5f813b4fd2)

**Comment by xiefenga** [comment] 2023-12-14 07:30
but it work correctly in MacOS

**Comment by mxschmitt** [comment] 2023-12-14 22:19
The issue is that the Docker container has not the correct LANG options configured, after running it like this, it works:

```
docker run -it --rm -v .:/demo --ipc=host -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 mcr.microsoft.com/playwright:v1.40.0-jammy /bin/bash
```

**Comment by xiefenga** [comment] 2023-12-15 01:09
> The issue is that the Docker container has not the correct LANG options configured, after running it like this, it works:
> 
> ```
> docker run -it --rm -v .:/demo --ipc=host -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 mcr.microsoft.com/playwright:v1.40.0-jammy /bin/bash
> ```
> 
> I'll clarify with the team if we ant to add this env var by default.

thanks

**Comment by mxschmitt** [comment] 2023-12-15 19:16
Closing by that since it seems solved.

**Closed by mxschmitt** 2023-12-15 19:16 UTC
