### ISSUE TITLE
[BUG] - No images in trace

### ISSUE THREAD

**Issue by IgorKoryapin** [microsoft/playwright#23368] opened 2023-05-30 14:51 UTC
### System info
- Playwright Version: [v1.34.3]
- Operating System: [Ubuntu 20]
- Browser: [All]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```import { defineConfig, devices, TraceMode } from '@playwright/test';
import dotenv from 'dotenv';

require('./sentry')

dotenv.config();

export default defineConfig({

    globalSetup: require.resolve('./global-setup'),

    testDir: './tests',
    timeout: 70000,
    forbidOnly: !!process.env.CI,
    retries: process.env.CI ? 2 : 0,
    workers: process.env.CI ? 2 : undefined,
    reporter: [['html', { open: 'never' }], ['list']],

    expect: {
        timeout: 20000,
    },

    use: {
        headless: !!process.env.NLAB_APP_TESTS_HEADLESS,
        actionTimeout: process.env.NLAB_APP_TESTS_ACTIONTIMEOUT ? +process.env.NLAB_APP_TESTS_ACTIONTIMEOUT : 5000,
        baseURL: process.env.NLAB_APP_TESTS_CONTOUR,
        ignoreHTTPSErrors: !!process.env.NLAB_APP_TESTS_IGNOREHTTPSERRORS,
        screenshot: process.env.NLAB_APP_TESTS_SCREENSHOT as 'only-on-failure' || 'only-on-failure',
        video: process.env.NLAB_APP_TESTS_VIDEO as 'retain-on-failure' || 'retain-on-failure',
        storageState: 'state.json',
        trace: process.env.NLAB_APP_TESTS_TRACE as TraceMode || 'retain-on-failure',
    },

    projects: [

        process.env.NLAB_APP_TESTS_BROWSER === 'webkit' ? {
            name: 'webkit',
            use: {
                ...devices['Desktop Safari'],

                viewport: { width: 1800, height: 900 },
            },
        } :

            process.env.NLAB_APP_TESTS_BROWSER === 'firefox' ? {
                name: 'firefox',
                use: {
                    ...devices['Desktop Firefox'],
                    viewport: { width: 1800, height: 900 },
                },
            } :

                {
                    name: 'chromium',
                    use: {
                        ...devices['Desktop Chrome'],
                        contextOptions: {
                            permissions: ['clipboard-read', 'clipboard-write'],
                        },
                        viewport: { width: 1800, height: 900 },
                    },
                },
    ],
});
[playwright-report.zip](https://github.com/microsoft/playwright/files/11601331/playwright-report.zip)

```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by aslushnikov** [comment] 2023-05-30 23:58
Looks like a dupe of https://github.com/microsoft/playwright/issues/23220

**Closed by aslushnikov** 2023-05-30 23:58 UTC
