### ISSUE TITLE
[BUG] Webkit does not show the log-in form

### ISSUE THREAD

**Issue by eywrld** [microsoft/playwright#29032] opened 2024-01-18 02:30 UTC
### System info
- Playwright Version: [v1.41]
- Operating System: Windows 11 Enterprise
- Browser: [WebKit]
- Other info:

### Source code

```
import { TestInfo, Page, test } from '@playwright/test';
  test(`testing in webkit`, async ({page}) => {
    await page.goto('https://www.grundfos.com/');
    await page.getByRole('link', { name: 'Allow all cookies' }).click();
    await page.getByRole('link', { name: 'Sign in' }).click();
    await page.getByTitle('Sign in').click();
    await page.pause();
});
```

**Steps**
- [Run the test]

**Expected**
- Test should show the log-in form

**Actual**
- Test did not show the log-in form

[Describe actual behavior]
-Using Webkit, the log-in form is not showing while for Chromium and Firefox, they just work fine.

**Comment by viraxslot** [comment] 2024-01-18 06:36
@eywrld Hi, I've run the test on my local machine and it works just fine. Could you please provide error message of the failure and possibly the screenshot?

**Comment by mxschmitt** [comment] 2024-01-18 21:50
The `modulebox component-signin` div has a `display: none` while it has `display: block` in Chromium.

I cannot reproduce in Safari (`Version 17.2.1 (19617.1.17.11.12)`) but I can reproduce in Safari Technology Preview (`Release 185 (Safari 17.4, WebKit 19618.1.9.8`).

**Comment by mxschmitt** [comment] 2024-01-18 21:53
Since this is a bug in Safari, I'll close for now. You catched a browser bug before it reached the users! I recommend trying to make a smaller reproducible out of it and filing it at https://bugs.webkit.org/ so Apple can look into it.

**Comment by eywrld** [comment] 2024-01-21 07:17
Sorry, it took me a while to reply. Also, I'm just a college student trying my best to learn QA and playwright so please bear with me hahaha. So, what I understand is that WebKit works best on MacOS like what you said. Unfortunately, I'm only limited in using Windows 11. I tried finding other ways on to solve my problem and came up with using other WebKit browsers like the WinCairo port and it did fine when I used it on the said site above and it showed the log-in form. However, when I tried using the WinCairo minibrowser.exe on playwright, it did gave me an error.


```
Error: browserType.launch: Target page, context or browser has been closed
Browser logs:

<launching> ../bin64/MiniBrowser.exe --inspector-pipe --disable-accelerated-compositing --no-startup-window
<launched> pid=10688
[pid=10688] <process did exit: exitCode=0, signal=null>
[pid=10688] starting temporary directories cleanup
Call log:
  - <launching> ../bin64/MiniBrowser.exe --inspector-pipe --disable-accelerated-compositing --no-startup-window
  - <launched> pid=10688
  - [pid=10688] <process did exit: exitCode=0, signal=null>
  - [pid=10688] starting temporary directories cleanup
```
  
 I ran it using this project 
``` 
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'],
              launchOptions: { executablePath:'../bin64/MiniBrowser.exe' }  ,
              userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15",    
              defaultBrowserType: "webkit",
            },
    },
```
It navigates to --inspector-pipe. I tried solving and searching for it but no luck. :<

**Comment by mxschmitt** [comment] 2024-01-21 10:45
> I tried finding other ways on to solve my problem and came up with using other WebKit browsers like the WinCairo port and it did fine when I used it on the said site above and it showed the log-in form.

Which version of the WinCairo port did you use? Most likely the version was before the upstream WebKit bug was introduced.

> However, when I tried using the WinCairo minibrowser.exe on playwright, it did gave me an error.

This is not supported, since Playwright relies on custom patches. Only Playwright's WebKit is supported with Playwright.

Realistically speaking I strongly recommend filing a bug at https://bugs.webkit.org, since this bug means that your site will be unusable in Safari once they release a new version for all of your clients. Maybe there is already a bug filed, so narrowing down the problem is really crucial there in order to find it in their bug tracker. 

---

Playwright offers the great feature of giving you more recent browser versions (usually one version ahead of stable), so you can spot browser bugs before your users will run into it. This does not happen often, but is often a possibility to file it upstream so the browser vendors get notified about the regression they introduced and can fix it before it hits the actual users.

I hope that makes it a bit more clear for you!

**Comment by eywrld** [comment] 2024-01-21 17:30
> Which version of the WinCairo port did you use?

I think I used this **[WinCairo-64-bit-Release-Build/12669]** in trying to reach the log-in page.

> Only Playwright's WebKit is supported with Playwright.

Well, that's good to know. I really didn't know about this hahaha, I thought I could find an easy way by tinkering playwright and I just filled a bug and I hope it will be fixed as soon as possible.

> I cannot reproduce in Safari (Version 17.2.1 (19617.1.17.11.12))

I asked my friend to view the link using his Safari on Macbook with the same version and it did show the log-in form. Was it because of the modifications that I read from [here](https://fujii.github.io/2019/07/05/webkit-on-windows/)

> Playwright offers the great feature of giving you more recent browser versions (usually one version ahead of stable), so you can spot browser bugs before your users will run into it. This does not happen often, but is often a possibility to file it upstream so the browser vendors get notified about the regression they introduced and can fix it before it hits the actual users.
I hope that makes it a bit more clear for you!

Thank you, Max! I really do appreciate taking a time with a beginner like me :D

**Comment by eywrld** [comment] 2024-01-22 02:24
I just got a reply from [Webkit Bugzilla,](https://bugs.webkit.org/show_bug.cgi?id=267834) said that this might be on playwright webkit. Also, I forgot to specifically mention that I used playwright's webkit on Windows on this test.

**Comment by mxschmitt** [comment] 2024-01-22 11:25
I did some more testing and can confirm that this is a bug on our side. I apologise!

Whats happening: The site is executing this code pretty early on which is failing in our WebKit port:

```ts
var isSafari = (/constructor/i.test(window.HTMLElement) || (function detectSafari(p) { return p.toString() === "[object SafariRemoteNotification]"; })(!window['safari'] || (typeof safari !== 'undefined' && safari.pushNotification)))
```

Reason: `safari.pushNotification` is undefined which gets passed into `detectSafari` which will throw, since toString() can't be executed on `undefined`.

We should probably fully mock pushNotification, as we evaluated in the past. Assigning to Yury.

**Closed** 2024-01-22 23:44 UTC
Labels: browser-webkit, v1.42
