### ISSUE TITLE
[BUG] Webkit browser window bounds not set correctly

### ISSUE THREAD

**Issue by ankur-lt** [microsoft/playwright#21449] opened 2023-03-07 06:09 UTC
### System info
- Playwright Version: 1.29.2
- Operating System: All
- Browser: Webkit
- Other info: 

### Source code
```js
const {webkit} = require("playwright");

(async () => {
  const browser = await webkit.launch({
    headless: false
  });

  const context = await browser.newContext({
    viewport: { width: 1440, height: 900 },
  })

  const page = await context.newPage();

  await page.goto('https://whatismyviewport.com/')
  await page.waitForTimeout(2000);

  await browser.close();
})();
```

**Expected**
The webkit window's top left corner should be closer to the screen's top left corner.

**Actual**
The window opens up anywhere randomly.

While running the similar test with chromium, the playwright server sends the `Browser.setWindowBounds` CDP command to the browser to set the appropriate X and Y window bounds. The same isn't done by Playwright when running the test with Webkit. For webkit, the `Emulation.setDeviceMetricsOverride` CDP method is executed but it doesn't pass the `positionX` and `positionY` parameters. This leads to the window opening anywhere randomly and the window goes off the screen. Is there any command by Playwright to set the window bounds? I cannot set it by using `Browser.setWindowBounds` method as webkit browse does not support `newCDPSession`.

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/84451419/223335820-3c6ee792-0ae1-4496-8d93-203c91721fab.png">

**Comment by mxschmitt** [comment] 2023-03-07 07:48
Why is positioning the browser window import for your testing scenario?

**Comment by ankur-lt** [comment] 2023-03-07 07:54
@mxschmitt , the browser window positioning does not impact the tests in any way. The test execution works as expected. But to view the browser window while debugging the tests, I need to drag the window every time into the view.

**Comment by mxschmitt** [comment] 2023-03-07 11:54
If you use re-use browser in the vscode extension it should not be a problem since the window stays open?

We never designed the browsers to be launched at the top right of your screen. As of today this would be more a feature request rather than a bug.

**Comment by mxschmitt** [comment] 2023-03-07 23:13
Since this is as designed and re-use browser feature aka. show browser in vs code is exactly for that, I'm closing it for now.

**Closed by mxschmitt** 2023-03-07 23:13 UTC
