### ISSUE TITLE
[Question] Playwright + Firefox: How to disable download prompt and allows it to save by default?

### ISSUE THREAD

**Issue by xlphed** [microsoft/playwright#5151] opened 2021-01-26 01:32 UTC
Hi all,  I'm using Playwright + Firefox to automate downloading of a CSV file from firebase.

However, there's a popup prompt to download the file. What can I do to accept the download without the prompt? I can't be clicking on the prompt since I am automating it.

Please refer to the following Stackoverflow post, I have attached an image in there as well: https://stackoverflow.com/questions/65894688/playwright-firefox-how-to-disable-download-prompt-and-allows-it-to-save-by-de

Appreciate your help!

**Comment by pavelfeldman** [comment] 2021-01-26 07:39
https://playwright.dev/docs/downloads

**Comment by weisi94** [comment] 2021-01-26 08:38
> https://playwright.dev/docs/downloads

Hi, have tried that, but the prompt still persists.

**Comment by aslushnikov** [comment] 2021-01-27 05:53
@weisi94 this looks like a bug. How can we reproduce it locally to debug this? Any chance you can share your snippet / url? 

Also, what's the Playwright version?

**Comment by weisi94** [comment] 2021-01-27 06:39
@aslushnikov I'm afraid I don't have the snippet to share, as I have changed the code already. Currently, I am using persistent context, which saves the preference of where the file should be downloaded to permanently, hence solving the issue. However, you can reproduce it simply with any site that has something to download.

**Comment by aslushnikov** [comment] 2021-03-18 08:08
> However, you can reproduce it simply with any site that has something to download. 

@xlphed I still can't repro. What's the website that you use? There should be something specific that makes our download logic failing in Firefox. 

For the record, here's the snippet I tried to reproduce this:

```js
const pw = require('playwright');

(async () => {
  const browser = await pw.firefox.launch();
  const page = await browser.newPage();
  await page.goto('https://www.webfx.com/blog/images/assets/cdn.sixrevisions.com/0435-01_html5_download_attribute_demo/html5download-demo.html');
  const [download] = await Promise.all([
    page.waitForEvent('download'),
    page.click('text=DOWNLOAD HTML DOCUMENT'),
  ]);
  console.log(download.suggestedFilename());
  await browser.close();
})();
```

**Comment by aslushnikov** [comment] 2021-05-13 21:37
closing since this is not actionable without a repro. Please re-file if this still bothers you and there's a repro!

**Closed by aslushnikov** 2021-05-13 21:37 UTC
Labels: P2-bug
