### ISSUE TITLE
[BUG] Playwright doesn't work with GitHub codespaces out of the box

### ISSUE THREAD

**Issue by benjamingr** [microsoft/playwright#3921] opened 2020-09-18 17:43 UTC
**Context:**
- Playwright Version: [what Playwright version do you use?] latest
- Operating System: [e.g. Windows, Linux or Mac] Linux (GitHub codespaces)
- Node.js version: [e.g. 10.12, 10.14] v12.16.3
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chromium
- Extra: [any specific details about your environment] This bug is when trying to use Playwright in GitHub codespaces

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally.

I tried running the [most basic](https://github.com/testimio/root-cause/tree/main/integration-examples/launch-api) root cause example that doesn't use any test runner.

Launching playwright fails, launching puppeteer works:

```shell
codespace:~/workspace/root-cause/integration-examples/launch-api$ yarn example-playwright
Debugger listening on ws://127.0.0.1:32991/6b2e0f01-e5dd-4162-bc7f-7796a9800f68
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
yarn run v1.22.4
$ ts-node playwright-example-ts.ts
(node:4934) UnhandledPromiseRejectionWarning: browserType.launch: Failed to launch chromium because executable doesn't exist at /home/codespace/.cache/ms-playwright/chromium-799411/chrome-linux/chrome
Try re-installing playwright with "npm install playwright"
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.: 
    at BrowserType._wrapApiCall (/home/codespace/workspace/root-cause/integration-examples/launch-api/node_modules/playwright/lib/client/channelOwner.js:76:15)
    at BrowserType.launch (/home/codespace/workspace/root-cause/integration-examples/launch-api/node_modules/playwright/lib/client/browserType.js:48:21)
    at launchPlaywrightByOptions (/home/codespace/workspace/root-cause/integration-examples/launch-api/node_modules/@testim/root-cause-core/lib/launch.js:102:31)
    at launchImpl (/home/codespace/workspace/root-cause/integration-examples/launch-api/node_modules/@testim/root-cause-core/lib/launch.js:30:25)
(node:4934) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4934) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 5.84s.
Waiting for the debugger to disconnect...

# puppeteer (works)
codespace:~/workspace/root-cause/integration-examples/launch-api$ yarn example-puppeteer
Debugger listening on ws://127.0.0.1:35661/34eade25-1f25-4f47-97fd-2fde3b0502f6
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
yarn run v1.22.4
$ node puppeteer-example.js
Debugger listening on ws://127.0.0.1:37475/125e24ed-d575-4c82-a208-2a0f22ff896e
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Root Cause viewer: http://localhost:9876
Press any key to exit
```

**Comment by mxschmitt** [comment] 2020-09-18 18:05
Are you using some GitHub Codespace configuration? If not, since all the browser require additional dependencies, we recommend to use the official Docker image as a base image and won't work with the default Node.js image. Also WebKit headless currently won't work with Debian.

Example: https://github.com/microsoft/playwright/blob/master/.devcontainer/devcontainer.json

**Comment by benjamingr** [comment] 2020-09-18 21:11
> Are you using some GitHub Codespace configuration? 

I am using the default configuration (Ubuntu pre-loaded with a bunch of stuff I think?), which puppeteer seems to work with and installation seems to work with both puppeteer and playwright.

The failure in particular is in the difference between where playwright downloads chrome to (in the default codespace image) and where playwright expects to find it when `.launch` is called.

**Comment by mxschmitt** [comment] 2020-09-20 08:06
Would be awesome if you could provide us a minimum reproducible repository, then we can investigate into that. Thanks!

**Comment by benjamingr** [comment] 2020-09-21 07:15
Hey, literally any repository without setting the devcontainer.json would work, I used this code and this repo: https://github.com/testimio/root-cause/tree/main/integration-examples/launch-api

**Comment by benjamingr** [comment] 2020-09-21 08:15
Strange indeed, I will check later - the project indeed uses yarn workspaces (lerna wasn't used in the demo it's only used for publishing)

**Comment by pavelfeldman** [comment] 2020-10-20 05:01
Closing as a part of triage. Please feel free to reopen with additional details.

**Closed by pavelfeldman** 2020-10-20 05:01 UTC
