### ISSUE TITLE
[BUG] `playwright@1.19.2` is a lot slower for `content.tracing` with `snapshot: true`

### ISSUE THREAD

**Issue by bpasero** [microsoft/playwright#12400] opened 2022-02-28 12:40 UTC
**Context:**
- Playwright Version: 1.19.2
- Operating System: macOS
- Node.js version: 14.x
- Browser: Chromium
- Extra: CI environment (Azure Pipelines)

**Describe the bug**

I just recently wanted to update to the `1.19.x` release line for our tests in VSCode and now noticed how our smoke tests in web are almost 100% slower:

**OLD**

![image](https://user-images.githubusercontent.com/900690/155985004-d6649512-6dbb-48ba-aa06-69974efc6ad0.png)

**NEW**

![image](https://user-images.githubusercontent.com/900690/155985026-74025ea1-b3dd-4884-9112-b6ce71b7f8a8.png)

At first glance I could not find a single operation that would be slower, it seems like the entire run is slower, getting us closer to a 10 minute timeout we configured.

Starting an issue here to ask: has this been reported by others, how can we drill into this further?

**Comment by aslushnikov** [comment] 2022-03-01 00:43
> has this been reported by others?

@bpasero no, it hasn't been reported.

> how can we drill into this further

Time has to be spent somewhere. Can you get timing break-down between tests / actions and lines? Does it reproduce locally?

**Comment by pavelfeldman** [comment] 2022-03-01 03:10
It'd be really nice to be able to repro it. Test time did not change for our suite between 1.18 and 1.19, so I wonder if you are hitting a specific pattern that regressed in all of your tests.

**Comment by bpasero** [comment] 2022-03-01 09:38
We have a detailed log of what the test runner is doing with times:

[smoke-runner-logs.zip](https://github.com/microsoft/playwright/files/8160463/smoke-runner-logs.zip)

Glancing over it, I cannot really see a single thing that seems slower though...

**Comment by sleroq** [comment] 2022-03-03 12:24
I have the same problem

1.18.1:
![2022-03-03_15-19_1](https://user-images.githubusercontent.com/52239427/156563857-4423bf06-8279-47fd-8dd8-0e9dce1faa75.png)

1.19.2:
![2022-03-03_15-19_2](https://user-images.githubusercontent.com/52239427/156563900-7b458ab9-636f-41f4-8667-a64e3e9d0f8e.png)

**Context:**

    Playwright Version: 1.19.2
    Operating System: Arch Linux
    Node.js version: 16.14.0
    Browser: Chromium

**Comment by aslushnikov** [comment] 2022-03-08 18:53
@bpasero We see from your logs that `Cmd-Shift-P` actions takes waay slower. It might be that Chrome changed some rendering upstream.

Could you please try running Playwright v1.18 + stable chrome (using the `channel` option while launching browser) and check the timings:

```js
const { chromium } = require('playwright');
const browser = await chromium.launch({
  channel: 'chrome' // or 'msedge', 'chrome-beta', 'msedge-beta', 'msedge-dev', etc.
});
```

**Comment by bpasero** [comment] 2022-03-09 07:58
@aslushnikov yeah looks like that brings the number back down on macOS. 

However, on Linux I see this error now:

```
VSCode Smoke Tests (Web)
       Search
         "before all" hook for "has a tooltp with a keybinding":
     browserType.launch: Chromium distribution 'chrome' is not found at /opt/google/chrome/chrome
Run "npx playwright install chrome"
      at launchBrowser (/__w/1/s/test/automation/src/playwrightDriver.ts:263:62)
      at launch (/__w/1/s/test/automation/src/playwrightDriver.ts:205:43)
      at measureAndLog (/__w/1/s/test/automation/src/logger.ts:52:9)
      at launch (/__w/1/s/test/automation/src/code.ts:78:51)
      at Application.startApplication (/__w/1/s/test/automation/src/application.ts:127:29)
      at Application._start (/__w/1/s/test/automation/src/application.ts:83:16)
      at Application.start (/__w/1/s/test/automation/src/application.ts:70:3)
      at Context.<anonymous> (src/utils.ts:92:3)
```

**Comment by sleroq** [comment] 2022-03-09 08:10
@aslushnikov 

It didn't change anything for me

1.18.1 with chromium 99.0.4844.51 (Official Build) is still > 2 times faster

**Comment by sleroq** [comment] 2022-03-09 08:13
@bpasero 

>      browserType.launch: Chromium distribution 'chrome' is not found at /opt/google/chrome/chrome
> Run "npx playwright install chrome"

It looks like it can't find executable

**Comment by bpasero** [comment] 2022-03-09 08:47
To clarify, this only starts happening with this change: https://github.com/microsoft/vscode/commit/ded849f27ee71e8b6ddb7ad64bad336cd40ea722

**Comment by aslushnikov** [comment] 2022-03-11 09:38
> @aslushnikov yeah looks like that brings the number back down on macOS.

@bpasero looks like new versions of Chromium will regress performance of VSCode; Playwright 1.19 shipped Chromium 100, while your current stable is probably 99. Let's verify the stable version: could you please run:

```bash
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
```

> However, on Linux I see this error now:

@bpasero you'd need to run `npx playwright install chrome` as part of your CI to install stable chrome version.

> It didn't change anything for me

@sleroq could you please also dump your stable chrome version?

**Comment by bpasero** [comment] 2022-03-12 06:10
> could you please run

I don't follow. This is in our CI and the version should be constant depending on the version of `playwright` and the config, no? 

> you'd need to run npx playwright install chrome as part of your CI to install stable chrome version

We call `npm playwright-install` in our CI before running tests, that is not enough?

**Comment by pavelfeldman** [comment] 2022-03-14 20:36
@bpasero, my triaging shift starts, making sure I understand what's happening:

## Perf regression

So we now think that starting with Chrome v100, VS Code on macOS will be 2x slower for certain operations. We are deriving this from the fact that Playwright 1.19 (Chromium 100) is 2x slower than Playwright 1.19 (Chrome 99).

Since this is a very strong statement, I'd be more comfortable if you checked it with Playwright 1.19 (or Playwright 1.18, it does not matter) in two configurations:

channel: 'stable' (99 as per https://omahaproxy.appspot.com/ at the moment of writing)
channel: 'beta' (100 as per https://omahaproxy.appspot.com/ at the moment of writing)

This would check Chrome 99 vs Chrome 100, not Chromium. If this yields the difference, it will no longer be about Playwright, it'll be about the real browser regression. We already think this is the case, but it'd be nice to double-check.

Assuming, it is confirmed, there are two options:
a) This is a real user-observable regression. in this case you can safely roll to newer Playwright, this is now your new slow baseline until either Chromium or VS Code are fixed to be fast again.
b) this is an internal instrumentation regression in the code Playwright uses. This is possible, but we have not changed anything in the Chromium instrumentation lately, so it is less probable.

## Linux problem

`npx playwright install chrome` should be able to install branded Chrome on your Linux system. Assuming you have Ubuntu and the script has enough rights to install the browser. It seems like something went wrong here. It is not that important as long as perf regression that you observe is universal and happens on both Linux and Mac. Let's focus on confirming it first, once it is confirmed, you can safely roll to Playwright 1.19, no channel, it'll be our newer slower baseline.

**Comment by bpasero** [comment] 2022-03-15 19:30
I can only devote time in our debt week again, which is in early April. Will then get back here. Hopefully others can also chime in that see it.

**Comment by bpasero** [comment] 2022-03-25 08:48
@pavelfeldman 

* `playwright@1.18.0 channel: 'chrome' (Windows)`: 3m54s ([CI](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=163283&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=0699ae84-7245-5a45-5eee-80b086af2725))
* `playwright@1.18.0 channel: 'chrome-beta' (Windows)`: 6m45s ([CI](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=163284&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=0699ae84-7245-5a45-5eee-80b086af2725))

**Comment by sleroq** [comment] 2022-04-01 15:06
Hello,
This issue seems to be fixed in [v1.20.0](https://github.com/microsoft/playwright/releases/tag/v1.20.0) release!

Here is my test results:

playwright-chromium@1.18.1 - **13398 ms**
playwright-chromium@1.19.2 - **32433 ms**
playwright-chromium@1.20.0 - **13565 ms**

Test details: https://pastebin.com/pqQHtSUF

**Comment by bpasero** [comment] 2022-04-03 18:05
It turns out the underlying reason for this issue tracing! When I reduce tracing overhead and set `snapshot: false`, speed is back to normal. Since we only really care about screenshots currently, this is OK for us, but worth mentioning that `snapshot: true` in tracing makes test execution really slow. I can even see this visually.

**Comment by mxschmitt** [comment] 2022-10-20 17:13
This issue seems to be a duplicate of https://github.com/microsoft/playwright/issues/14037 and already fixed. Please let us know if you still reproduce it in the latest versions and re-file if needed, thanks!

**Closed by mxschmitt** 2022-10-20 17:13 UTC
Labels: P3-collecting-feedback
