### ISSUE TITLE
[BUG] PW1.29.2 - Playwright test for VS Code - Debugging -- page.goto: net::ERR_UNEXPECTED

### ISSUE THREAD

**Issue by RThuys** [microsoft/playwright#19961] opened 2023-01-09 15:22 UTC
- Playwright Version: 1.29.2
- Operating System: WINDOWS 10 10.0.19045
- Node.js version: v14.17.3
- Browser: Tested on Chrome
- Extra: Playwright Test for VS Code version v1.0.3

After updating from 1.28.1 to 1.29.* - 1.29.2, when I execute-debug my tests, I receive the following error:

```
page.goto: net::ERR_UNEXPECTED at MY_VALID_URL_WORKING_IN_1.28.1
    =========================== logs ===========================
    navigating to "MY_VALID_URL_WORKING_IN_1.28.1", waiting until "load"
    ============================================================
       at ..\services\auth.service.js:53
      51 |                     if (identityValue)
      52 |                         url = buildURL(identityValue);
    > 53 |                     return [4 /*yield*/, page.goto(url)];
         |                                               ^
      54 |                 case 1:
      55 |                     _b.sent();
      56 |                     return [2 /*return*/];
```

This error does not occur if I just click the green play button, the test finishes normally. 
Downgrading to 1.28.1 fixes the issues again.

I had to change my URL because it is an authenticating URL and I'm not sure if I can share it.

**Comment by aslushnikov** [comment] 2023-01-11 11:09
@RThuys So far via out of clues. Could you please provide us with a repro that would help us reproduce this?

**Comment by RThuys** [comment] 2023-01-11 15:09
@aslushnikov As this issue occurs on a dedicated Citrix environment, sharing a repo will not help you to reproduce the issue because it is not possible. 

However, I've been debugging the issue with colleagues , and one suggestion was the following:
Because the issue doesn't occur while running the tests normally and only when debugging, there is logging added that is not able to handle a Network Status code that isn't a number?

*info: The URL is a redirect URL, if more info needed, please ask

<img width="765" alt="image" src="https://user-images.githubusercontent.com/20083678/211841407-3ecc75f5-9267-4004-96d4-8bacd20303c1.png">

**Comment by aslushnikov** [comment] 2023-01-13 01:27
> Because the issue doesn't occur while running the tests normally and only when debugging, there is logging added that is not able to handle a Network Status code that isn't a number?

I'm not sure i follow this. If there's an internal error in Playwright, you'll see it in the terminal right away. 

You can also try running with the `DEBUG=*browser* npx playwright test` env variable to dump all the browser logs. Maybe you'll find something helpful in there?

**Comment by RThuys** [comment] 2023-01-13 07:29
@aslushnikov running `$env:PWDEBUG="chrome" npx playwright test` doesn't give any errors, the test passes... So... It only fails when I run it through the plugin as debug

**Comment by aslushnikov** [comment] 2023-01-13 07:45
@RThuys we discussed this on a team meeting. Unfortunately, there's no way we can start thinking about this unless we can reproduce this to debug this; I'll have to close this for now since it's not actionable.

However, we'd love to look into it if/when there's a repro! In this case, please do not hesitate to file a new issue to us!

**Closed by aslushnikov** 2023-01-13 07:45 UTC
Labels: triaging
