### ISSUE TITLE
[REGRESSION]: `TypeError [ERR_INVALID_ARG_TYPE]` when running playwrite with node 20.6.1

### ISSUE THREAD

**Issue by PatrickG** [microsoft/playwright#29253] opened 2024-01-31 09:22 UTC
**Context:**
- GOOD Playwright Version: `1.30.0`
- BAD Playwright Version: `1.41.0`
- Operating System: Linux
- Node version: `20.6.1`

**Describe the bug**
I'm getting this error when trying to run the tests in https://github.com/sveltejs/kit

```bash
TypeError [ERR_INVALID_ARG_TYPE]: The "parentURL" argument must be of type string or an instance of URL. Received an instance of Object
    at new NodeError (node:internal/errors:405:5)
    at throwIfInvalidParentURL (node:internal/modules/esm/resolve:937:11)
    at Hooks.resolve (node:internal/modules/esm/hooks:241:5)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:337:35)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:220:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:307:34)
    at Hooks.register (node:internal/modules/esm/hooks:138:51)
    at MessagePort.handleMessage (node:internal/modules/esm/worker:168:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

I guess the changes in #28526 are the source of this bug.

It works when upgrading to Node `21.6.1`.

**Comment by mxschmitt** [comment] 2024-01-31 13:48
Looks like this was about a bug which was fixed in a recent 20.x release, e.g. v20.11.0 (latest 20.x).

I was able to reproduce in v20.6.1 but not in v20.11.0.

**Closed** 2024-01-31 18:09 UTC

**Comment by RF2023** [comment] 2024-04-23 16:17
> v20.11.0.

Facing this issue with v20.10.0, anything we are missing?

**Comment by furqan-qadri** [comment] 2024-05-26 15:19
works for me with node v 20.9.0

you can install this node version and then use command `nvm use`

this works for me but only within the current shell

**Comment by ChristiansGithubID** [comment] 2024-07-22 22:29
I'm getting the same error with every node version I have tried.

TypeError [ERR_INVALID_ARG_TYPE]: The "parentURL" argument must be of type string or an instance of URL. Received an instance of Object
    at new NodeError (node:internal/errors:405:5)
    at throwIfInvalidParentURL (node:internal/modules/esm/resolve:937:11)
    at Hooks.resolve (node:internal/modules/esm/hooks:241:5)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:337:35)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:220:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:307:34)
    at Hooks.register (node:internal/modules/esm/hooks:138:51)
    at MessagePort.handleMessage (node:internal/modules/esm/worker:168:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by nalinikanta123** [comment] 2024-07-29 02:31
[ChristiansGithubID](https://github.com/ChristiansGithubID) : Is your issue resolved?

**Comment by oleksii-pi** [comment] 2024-08-04 16:25
Node v20.12.1 doesn't have this bug.

This comment helped me to fix it: https://github.com/microsoft/playwright/issues/30217#issuecomment-2047420753

I could reproduce it on v20.6.0 (over nvm)

**Comment by Pizle0210** [comment] 2024-10-28 16:57
I keep getting the same error

TypeError [ERR_INVALID_ARG_TYPE]: The "parentURL" argument must be of type string or an instance of URL. Received an instance of Object
at new NodeError (node:internal/errors:405:5)
    at throwIfInvalidParentURL (node:internal/modules/esm/resolve:937:11)
    at Hooks.resolve (node:internal/modules/esm/hooks:241:5)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:337:35)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:220:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:307:34)
    at Hooks.register (node:internal/modules/esm/hooks:138:51)
    at MessagePort.handleMessage (node:internal/modules/esm/worker:168:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'ERR_INVALID_ARG_TYPE'

**Comment by mxschmitt** [comment] 2024-10-28 17:17
@Pizle0210 we recommend updating to latest Node.js.

**Comment by Pizle0210** [comment] 2024-11-09 17:23
I have and it worked

**Comment by mailsondias** [comment] 2025-01-23 13:19
Yup. For me using version bellow 20.7... I had the same error, updated for v20.12.1 works fine.
