### ISSUE TITLE
[Feature]: Option to disable webgl in browser

### ISSUE THREAD

**Issue by strozzapreti** [microsoft/playwright#8626] opened 2021-09-01 16:02 UTC
### Feature request

It could be very helpful for us to have the ability to enable a browser mode where webgl is disabled. This could be a launch parameter, but it would also be great if this mode could be enabled on the playwright browser docker images as e.g. an environment variable, since our main usage of Playwright is connecting to the browser containers using browser_type.connect()

Use case:

We've been seeing a rare issue in our CircleCI pipeline where our context fixture crashes on `context.close()` because the browser seems to have crashed. All subsequent tests then fail attempting to create a new context because of the missing browser. This occurs maybe once a month (our UI tests run against the most current image in a once-daily cron) so perhaps 1/30 runs on average. This occurred both when we were running browsers within our test container directly using browser_type.launch and after we switched to separate browser containers using browser_type.connect()

Normally there isn't any additional information as to why the Browser is no longer up, but in at least a couple of instances we received a detailed stack trace that appeared to point to the browser crashing when attempting to use webgl in headless mode. See included trace below. According to our front-end teams, while none of our app UI makes use of webgl directly, there are apparently tons of references to it in the various frameworks used by the UI and it seems that a rare asset call or request will trigger this webgl attempt and cause the browser to crash. Since we have no need to validate anything related to webgl for our test cases, we would ideally like to be able to ignore it completely and avoid crashing the browser during our test runs.

Unfortunately, I can't claim to have the best understanding of this crash or why we don't always get Browser output, so if there's any other info I can provide or I've misattributed the issue, please let me know!

```
_ ERROR at teardown of test_item[firefox] _

browser = <Browser type=<BrowserType name=firefox executable_path=/root/.cache/ms-playwright/firefox-1238/firefox/firefox> version=87.0b10>
request = <SubRequest 'context' for <Function test_item[firefox]>>

    @fixture(scope='function')
    def context(browser: Browser, request) -> Generator[BrowserContext, None, None]:
        verify = not account_manager.config.verify_https  # Playwright args use the opposite syntax to Requests
        if vid_path := CONFIG['ui_artifacts_path']:
            vid_path = Path(vid_path) / request.node.name
        context_args = {'viewport': {"width": 1280, "height": 720},
                        'ignore_https_errors': verify,
                        'accept_downloads': True,
                        'record_video_dir': vid_path or None}
        context = browser.new_context(**context_args)
        context.set_default_timeout(20000)
        yield context
>       context.close()

tests/retail/ui_workflows/conftest.py:91: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.8/site-packages/playwright/sync_api/_generated.py:8257: in close
    self._sync("browser_context.close", self._impl_obj.close())
/usr/local/lib/python3.8/site-packages/playwright/_impl/_sync_base.py:103: in _sync
    return task.result()
/usr/local/lib/python3.8/site-packages/playwright/_impl/_browser_context.py:239: in close
    raise e
/usr/local/lib/python3.8/site-packages/playwright/_impl/_browser_context.py:236: in close
    await self._channel.send("close")
/usr/local/lib/python3.8/site-packages/playwright/_impl/_connection.py:36: in send
    return await self.inner_send(method, params, False)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <playwright._impl._connection.Channel object at 0x7f7280e49940>
method = 'close', params = {}, return_as_dict = False

    async def inner_send(
        self, method: str, params: Optional[Dict], return_as_dict: bool
    ) -> Any:
        if params is None:
            params = {}
        callback = self._connection._send_message_to_server(self._guid, method, params)
>       result = await callback.future
E       playwright._impl._api_types.Error: Protocol error (Browser.removeBrowserContext): Browser closed.
E       ==================== Browser output: ====================
E       [pid=26][err] 
E       [pid=26][err] (/home/pwuser/.cache/ms-playwright/firefox-1238/firefox/firefox:2000): GLib-GObject-CRITICAL **: 17:33:13.664: g_object_set: assertion 'G_IS_OBJECT (object)' failed
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: WebGL warning: <Create>: Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: Failed to create WebGL context: WebGL creation failed: 
E       [pid=26][err] * Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: WebGL warning: <Create>: Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: Failed to create WebGL context: WebGL creation failed: 
E       [pid=26][err] * Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] 
E       [pid=26][err] (/home/pwuser/.cache/ms-playwright/firefox-1238/firefox/firefox:2035): GLib-GObject-CRITICAL **: 17:33:22.112: g_object_set: assertion 'G_IS_OBJECT (object)' failed
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: WebGL warning: <Create>: Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: Failed to create WebGL context: WebGL creation failed: 
E       [pid=26][err] * Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: WebGL warning: <Create>: Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: Failed to create WebGL context: WebGL creation failed: 
E       [pid=26][err] * Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] 
E       [pid=26][err] (/home/pwuser/.cache/ms-playwright/firefox-1238/firefox/firefox:2067): GLib-GObject-CRITICAL **: 17:33:36.691: g_object_set: assertion 'G_IS_OBJECT (object)' failed
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: WebGL warning: <Create>: Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: Failed to create WebGL context: WebGL creation failed: 
E       [pid=26][err] * Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: WebGL warning: <Create>: Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: Failed to create WebGL context: WebGL creation failed: 
E       [pid=26][err] * Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] 
E       [pid=26][err] (/home/pwuser/.cache/ms-playwright/firefox-1238/firefox/firefox:2103): GLib-GObject-CRITICAL **: 17:33:49.064: g_object_set: assertion 'G_IS_OBJECT (object)' failed
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: WebGL warning: <Create>: Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: Failed to create WebGL context: WebGL creation failed: 
E       [pid=26][err] * Can't 
use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: WebGL warning: <Create>: Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: Failed to create WebGL context: WebGL creation failed: 
E       [pid=26][err] * Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] 
E       [pid=26][err] (/home/pwuser/.cache/ms-playwright/firefox-1238/firefox/firefox:2133): GLib-GObject-CRITICAL **: 17:34:02.432: g_object_set: assertion 'G_IS_OBJECT (object)' failed
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: WebGL warning: <Create>: Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: Failed to create WebGL context: WebGL creation failed: 
E       [pid=26][err] * Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: WebGL warning: <Create>: Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: Failed to create WebGL context: WebGL creation failed: 
E       [pid=26][err] * Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] 
E       [pid=26][err] (/home/pwuser/.cache/ms-playwright/firefox-1238/firefox/firefox:2165): GLib-GObject-CRITICAL **: 17:34:10.339: g_object_set: assertion 'G_IS_OBJECT (object)' failed
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: WebGL warning: <Create>: Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: Failed to create WebGL context: WebGL creation failed: 
E       [pid=26][err] * Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: WebGL warning: <Create>: Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] JavaScript warning: https://rad.localdev/dist/assets/lshash-e5a28b6/js/App-37d786cf-5-2ca3cd741089524bf416.js.gz, line 49298: Failed to create WebGL context: WebGL creation failed: 
E       [pid=26][err] * Can't use WebGL in headless mode (https://bugzil.la/1375585).
E       [pid=26][err] Exiting due to channel error.
E       [pid=26][err] Exiting due to channel error.

/usr/local/lib/python3.8/site-packages/playwright/_impl/_connection.py:47: Error
```

**Comment by yury-s** [comment] 2021-09-01 20:47
What playwright version are you using? I don't see this error message in the recent firefox versions and WebGL seems to now work in headless:
```ks
  await page.goto('https://get.webgl.org');
  await page.screenshot({path: '/tmp/s.png'});
```
1238 is quite old build of firefox, can you update to the most recent playwright and see if the issue persists?

As for disabling webgl, you can see if firefox has corresponding command line flag or a config option and pass it when launching the browser as an argument or via firefox_user_prefs.

**Comment by strozzapreti** [comment] 2021-09-01 22:24
Oh interesting. We're actually in the middle of transitioning to a new test container which allows us to upgrade to the latest version of playwright, but I believe this log was from a run in the old test container where we were stuck on v1.10. I have seen the context.close() finalizer fail once using the new container (v 1.14.1) but there was no browser output so it's possible that was due to a completely different issue. 

https://bugzil.la/1375585 Doesn't seem to be closed, so it's interesting to see that you found webgl was working in headless mode now. I wonder if it was patched via a completely separate ticket...

**Comment by yury-s** [comment] 2021-09-02 17:30
> https://bugzil.la/1375585 Doesn't seem to be closed, so it's interesting to see that you found webgl was working in headless mode now. I wonder if it was patched via a completely separate ticket...

I noticed that too. Not sure when exactly it was fixed but the test above is capturing webgl image. You also say that there is no such webgl related output anymore, so it's not clear-cut that the problem is caused by the webgl. Let's try to collect more logs from the failing browser, running it with `DEBUG=pw:browser` may reveal some useful information. Closing this bug as we are not planning to add an option for disabling webgl at the moment. Please file a new one or reopen this if you manage to collect more long from the new playwright or have a repro that we could run.

**Closed by yury-s** 2021-09-02 17:30 UTC
Labels: triaging
