### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by tmazumder** [microsoft/playwright#10320] opened 2021-11-15 12:13 UTC
How to maximize the page in playwright?

**Comment by casr** [comment] 2021-11-15 12:47
With `@playwright/test`, you can do:

```javascript
test.use({ viewport: { width: 1280, height: 720 } });
```

I realise this doesn't exactly answer your question but it is probably what you want to do otherwise you're dependent on each developer's screen size which'll make tests flaky.

See:
  - https://playwright.dev/docs/emulation#viewport

**Comment by tmazumder** [comment] 2021-11-15 13:03
Tried this but its not working
like in Selenium we have .maximize(), so de we have any such in playwright?

**Comment by mxschmitt** [comment] 2021-11-16 11:47
Not as of today, closing since its a duplicate of https://github.com/microsoft/playwright/issues/4046. Please add your use-case over there.

**Closed by mxschmitt** 2021-11-16 11:47 UTC
