### ISSUE TITLE
[Question] Finishing tests and opening html report in headed mode

### ISSUE THREAD

**Issue by natkashina** [microsoft/playwright#20051] opened 2023-01-11 20:20 UTC
Hey!
I noticed one strange thing... when I run the test in headless mode, it completes fine and immediately opens the html report, BUT when I run the tests in headed mode (just set headless: false in playwright.config.js), tests cannot complete correctly, the process hangs and the html reporter does not open.

In this regard, I need to set "ctrl + c" to close this process and start a new test, but already in headless mode, since everything is fine and quickly completed there and the reporter opens, but after starting in headless mode, I have two open reporter (look at sceenshot)...

It's stange and not convenient for work. Can someone explain why headed mode don't work as headless mode? 

I used version 1.29.0 and 1.29.2
![Screenshot_2](https://user-images.githubusercontent.com/48804710/211909077-c7aefe2a-811d-4d97-9202-ce9166acb0a3.png)

**Comment by natkashina** [comment] 2023-01-12 07:44
![55555](https://user-images.githubusercontent.com/48804710/212007415-eb24e2c9-9163-4fb2-9b12-cc64c1104d41.gif)

**Comment by natkashina** [comment] 2023-01-12 07:48
On the gif, the test is completed, but the report does not open, the process is frozen. 
I just recently started learning this framework. Yesterday I just installed playwright according to the instructions and tried to run the tests, but the result is the same.

I am using Windows 10 Pro, node 19.2.0 and 16.14.0

**Comment by natkashina** [comment] 2023-01-12 07:52
In headless mode it works fine
![555551](https://user-images.githubusercontent.com/48804710/212008886-ea684e51-18c8-4b8b-a6d2-5afd2bb81e3d.gif)

**Comment by aslushnikov** [comment] 2023-01-13 01:43
@natkashina so your test looks like this: 

```ts
import { test, expect } from "@playwright/test";

test("basic test", async ({ page }) => {
  await expect(page).toHaveTitle('foo');
});
```

Now, the default `page` is the `about:blank` page, so it naturally doesn't have the `'foo'` title. As a result, the test hangs, waiting for the condition. It should hang like this for 5 seconds and then timeout. 

Few things:
1. could you please change the test to the following:
    ```ts
    import { test, expect } from "@playwright/test";

    test("basic test", async ({ page }) => {
      await page.goto('https://example.com');
      await expect(page).toHaveTitle('Example Domain');
    });
    ```
2. could you please show your `playwright.config.ts`?

**Comment by natkashina** [comment] 2023-01-13 08:28
_As a result, the test hangs, waiting for the condition. It should hang like this for 5 seconds and then timeout._ - yeah, thanks! I forgot about it. Just when I run this test in headless mode in finish with error immediately but in headed mode I need wait this time.

Now its work fine. I'll be more attentive, sorry.
![5555511](https://user-images.githubusercontent.com/48804710/212273507-66574e92-1448-4a31-8b8e-c32bc3fe4f7e.gif)

It's my configs 
![image](https://user-images.githubusercontent.com/48804710/212273758-569b24b6-315a-4214-b05a-0d5b66d16864.png)

**Comment by aslushnikov** [comment] 2023-01-13 08:58
@natkashina looks like the issue is resolved then, closing!

**Closed by aslushnikov** 2023-01-13 08:58 UTC
Labels: triaging
