### ISSUE TITLE
[REGRESSION]: Playwright 1.28 unable to load the @js-temporal/polyfill library

### ISSUE THREAD

**Issue by thewilkybarkid** [microsoft/playwright#19045] opened 2022-11-24 09:34 UTC
**Context:**
- GOOD Playwright Version: 1.27.1
- BAD Playwright Version: 1.28.0, 1.28.1
- Operating System: Mac, and Docker
- Extra: https://github.com/PREreview/prereview.org/pull/461 https://github.com/PREreview/prereview.org/pull/477

**Code Snippet**

```typescript
import { Temporal } from '@js-temporal/polyfill'
[...]

import PlainDate = Temporal.PlainDate
```

([source](https://github.com/PREreview/prereview.org/blob/ab4d4b7ec41865eca1b672576d2d879f49e8aee0/src/infrastructure.ts#L50))

**Describe the bug**

Playwright fails

```
Running 0 tests using 0 workers

ReferenceError: Temporal is not defined

   at ../src/infrastructure.ts:50

  48 | import { NewPrereview } from './write-review'
  49 |
> 50 | import PlainDate = Temporal.PlainDate
```

In previous versions it successfully ran. This code is in my server with Playwright runs; TypeScript is able to compile the code and Node run it successfully.

**Comment by mxschmitt** [comment] 2022-11-24 22:17
Bisect: https://github.com/microsoft/playwright/compare/11eb719d13a832e53acf76bff360530c4ce81299...af38449f429258268e8b0edb5962eb8765b80a8f

bad 1.28.0-alpha-oct-20-2022
good 1.28.0-alpha-oct-19-2022

Most likely caused by https://github.com/microsoft/playwright/commit/9fe72a1da85b874569f1f43532ab688feadd7ffe.

**Comment by dgozman** [comment] 2022-11-28 20:21
This will be fixed by https://github.com/microsoft/playwright/pull/19026 in v1.29.

Babel issue: https://github.com/babel/babel/issues/14912, fixed in https://github.com/babel/babel/pull/14913, so bumping `@babel/plugin-transform-typescript` to `7.20.2` helped.

**Closed** 2022-11-28 20:21 UTC
Labels: v1.29
