### ISSUE TITLE
[BUG] Some config options are working only partially when using browser.newContext()

### ISSUE THREAD

**Issue by xrash** [microsoft/playwright#9002] opened 2021-09-18 03:08 UTC
**Context:**
- Playwright Version: 1.14.1
- Operating System: Linux
- Node.js version: v14.16.0
- Browser: chromium

**Code Snippet**

1. Clone this repo: https://github.com/xrash/pwt-config-issue-example
2. Run `yarn`
3. Run `npx playwright test`
4. The directory `test-results` will be created with partial output
5. Open `playwright.config.ts` and remove the `use` option altogether
6. Run `npx playwright test` again
7. The directory `test-results` won't even be created this time

**Describe the bug**

The fixture options under `use` at the config file are working _only partially_ when creating a new context manually (`browser.newContext()`).

For instance, `trace` and `screenshot` work, but `video` doesn't record any video at all. Also, `trace` doesn't fully work, as trace is recorded per test even when the context is created in `beforeAll` or in a worker-scoped fixture (desired behavior is to have the trace for the entire context session in one file). Also, the trace file seems buggy or incomplete.

If the fixture options under `use` in the config file aren't supposed to work when using `browser.newContext()`, then I'd expect it not to work at all, instead of having them to work only partially; and if it's supposed to work, then I'd expect it to work fully.

**Comment by dgozman** [comment] 2021-09-18 05:22
> For instance, `trace` and `screenshot` work, but `video` doesn't record any video at all.

Video does not work in this case, that's a known issue. Sorry for inconvenience.

> Also, `trace` doesn't fully work, as trace is recorded per test even when the context is created in `beforeAll` or in a worker-scoped fixture (desired behavior is to have the trace for the entire context session in one file).

This is by design. Each test gets a trace. If you would like a single trace for multiple tests, make a single test with multiple `test.step`s inside. Also note that sharing context between tests means non-isolated tests, and we do not recommend that.

> Also, the trace file seems buggy or incomplete.

Could you please attach the trace file so we can see the issue and fix it?

**Comment by xrash** [comment] 2021-09-18 07:31
> > For instance, `trace` and `screenshot` work, but `video` doesn't record any video at all.
> 
> Video does not work in this case, that's a known issue. Sorry for inconvenience.
> 
> > Also, `trace` doesn't fully work, as trace is recorded per test even when the context is created in `beforeAll` or in a worker-scoped fixture (desired behavior is to have the trace for the entire context session in one file).
> 
> This is by design. Each test gets a trace. If you would like a single trace for multiple tests, make a single test with multiple `test.step`s inside. Also note that sharing context between tests means non-isolated tests, and we do not recommend that.
> 
> > Also, the trace file seems buggy or incomplete.
> 
> Could you please attach the trace file so we can see the issue and fix it?

Thank you for your quick answer. I am attaching the `test-results` directory produced from the example I provided above.

`example.1.spec` produced `example.1-A/trace.zip` and `example.1-B/trace.zip`.
`example.2.spec` produced `example.2-A/trace.zip` and `example.2-B/trace.zip`. 

File `example.2-A/trace.zip` doesn't load correctly.
Files `example.1-B/trace.zip` and `example.2-B/trace.zip` don't display the thumbs below the horizontal timeline.

[test-results.tar.gz](https://github.com/microsoft/playwright/files/7189452/test-results.tar.gz)

Thank you!

**Comment by mxschmitt** [comment] 2021-09-21 12:22
Thank you for your report!

The underlying reason why the trace does not get shown correctly is probably https://github.com/microsoft/playwright/issues/9045. The test itself is only doing waitForTimeout which currently does not get reflected inside the trace-viewer. We'll fix this shortly.

Would be awesome if you could verify if its working as intended when you add more statements to it.

**Comment by A-ZC-Lau** [comment] 2021-09-23 05:28
> Video does not work in this case, that's a known issue. Sorry for inconvenience.

I'm guessing this will be fixed in the next release?

**Comment by xrash** [comment] 2021-10-04 00:43
> Thank you for your report!
> 
> The underlying reason why the trace does not get shown correctly is probably #9045. The test itself is only doing waitForTimeout which currently does not get reflected inside the trace-viewer. We'll fix this shortly.
> 
> Would be awesome if you could verify if its working as intended when you add more statements to it.

Just mentioning that I couldn't get it to work, and I find it weird that `example.2-A/trace.zip` is different from `example.1-A/trace.zip`, since both tests (1-A and 2-A) are the same, just written in patterns.

**Comment by dgozman** [comment] 2021-10-13 18:24
> Files example.1-B/trace.zip and example.2-B/trace.zip don't display the thumbs below the horizontal timeline.

That's  because nothing has happened on the page during these tests (they just wait for some timeout), and so no display frames were produced by the browser. Once you actually do something in the test (e.g. click), you should see the thumbnails.

> Just mentioning that I couldn't get it to work, and I find it weird that example.2-A/trace.zip is different from example.1-A/trace.zip, since both tests (1-A and 2-A) are the same, just written in different patterns.

Yeah, this is a bit surprising. The reason is that trace did record the `page.goto()` from the worker fixture, but not the `beforeAll`. I'd say it should not contain `page.goto()` from any of them, and only contain actions that happened during the test execution itself.

**Comment by onno-amsterdam** [comment] 2022-01-17 18:49
Hi all, I'm running into the same issue with video, this is my (simplified) scenario:

Using Playwright 1.17 with this config:
```typescript
const config: PlaywrightTestConfig = {
  use: {
    baseURL: 'https://playwright.dev',
    headless: false,
    viewport: { width: 1280, height: 720 },
    ignoreHTTPSErrors: true,
    video: "on-first-retry",
  },
  retries: 1,
  testDir: './tests',
};
export default config;
```

And these 2 tests:
```typescript
// Video of failed test IS saved in test-results
test('Test 1', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__inner .navbar__title');
  await expect(title).toHaveText('Play****wright');
});
```

```typescript
// Video of failed is NOT saved in test-results
test.describe('Test 2', () => {
    let context: BrowserContext;
    let page: Page;

    test.beforeAll(async ({ browser }) => {
        context = await browser.newContext();
        page = await context.newPage();
    });

    test('open Playwright page', async () => {
        await page.goto('https://playwright.dev/');
        const title = page.locator('.navbar__inner .navbar__title');
        await expect(title).toHaveText('Pl---aywright');
    });
});
```

The first test saves a video when failed, the second doesn't. 

In the second test, am I doing something I shouldn't do or a work around that I can try?
Is there any idea about if and when this will be fixed?

Thanks so much for your help!

**Comment by joe-safegraph** [comment] 2022-04-01 23:07
> > For instance, `trace` and `screenshot` work, but `video` doesn't record any video at all.
> 
> Video does not work in this case, that's a known issue. Sorry for inconvenience.
> 
> > Also, `trace` doesn't fully work, as trace is recorded per test even when the context is created in `beforeAll` or in a worker-scoped fixture (desired behavior is to have the trace for the entire context session in one file).
> 
> This is by design. Each test gets a trace. If you would like a single trace for multiple tests, make a single test with multiple `test.step`s inside. Also note that sharing context between tests means non-isolated tests, and we do not recommend that.
> 
> > Also, the trace file seems buggy or incomplete.
> 
> Could you please attach the trace file so we can see the issue and fix it?

I'm running the same issue and have resolved that by using `test.step`s instead. But the error messages I was getting from the `serial` approach were a lot nicer. If an error happened, I would see that it came from `Login Flow > Log In` or `Login Flow > Enter Password` for example. With `test.step`, it's again just `Login Flow`.

Could we get the same error logs with `test.step`?

**Comment by NagaAppariGlobal** [comment] 2022-05-05 10:11
We are facing the same issue . Has anyone found a work around to only record video on failure on newContext. Able record video by recordVideo Object on newContext .But I believe it has no association with config

**Comment by dgozman** [comment] 2022-06-14 00:24
@spaniardmaximus Tracing should work on per-test basis, even if you reuse a single context between tests. However, we do not recommend that, because that breaks test isolation.

**Comment by dgozman** [comment] 2022-06-14 00:25
Closing this issue since all config options except for the video should work in this scenario. #14813 is tracking the videos separately.

**Closed by dgozman** 2022-06-14 00:25 UTC
Labels: P3-collecting-feedback, feature-test-runner, feature-video

**Comment by dgozman** [comment] 2022-06-14 14:32
@spaniardmaximus Playwright Test starts a single browser per worker, shared by many tests, out of the box. However, creating a new `BrowserContext` per test is cheap and gives test isolation. I suggest to try the default way first before you hit any performance issues. You can read more about [contexts and isolation here](https://playwright.dev/docs/browser-contexts).
