### ISSUE TITLE
 beforeEach hook can only be called in a test file [BUG]

### ISSUE THREAD

**Issue by saivarma576** [microsoft/playwright#10616] opened 2021-11-30 19:39 UTC
**Context:**
- Playwright Version:  1.17.0
- Operating System: Windows,
 

**Code Snippet**
test.beforeEach(async ({ page }) => { await page.goto(Env.QAurl);  });

test.describe.serial('PO invoicing  --', () => {
  test("PO invoice submit", async ({ page }) => {
......

Hi can any one pls help me on this

****ISSUE# when I am trying to run in remote system CMD it saying as beforeEach hook can only be called in a test file****
![2021-12-01_0-49-58](https://user-images.githubusercontent.com/67151480/144115509-325d4322-88a9-4252-a45e-ed60c0ce34d2.png)

but in same system in under vs code test got executed with no errors 
![2021-12-01_0-48-32](https://user-images.githubusercontent.com/67151480/144115523-c6189204-6c78-4438-8ab0-0bf358248b09.png)

**Comment by pavelfeldman** [comment] 2021-12-01 01:53
This typically means that you have several (conflicting) versions of Playwright installed. Make sure that you only have one @playwright/test entry in your package.json and run `npm i`.

**Comment by saivarma576** [comment] 2021-12-01 12:05
- In my package.json I had only one @playwright/test and also I update with NPM i 

![image](https://user-images.githubusercontent.com/67151480/144231519-548d21aa-a3d9-4d99-ba80-85535fe6ba9d.png)
- global playwright also uptodated 
![image](https://user-images.githubusercontent.com/67151480/144231083-addebaf3-8fb2-4335-82e4-7dd84a7741ee.png)

**Comment by pavelfeldman** [comment] 2021-12-02 23:03
It could be that your cmd uses another version of Node, or resolves different Playwright via global node modules installation.

**Comment by dgozman** [comment] 2021-12-08 19:27
Closing since we cannot reproduce the issue. Please file a new issue with a repro if you have one.

**Closed by dgozman** 2021-12-08 19:27 UTC
Labels: triaging

**Comment by saivarma576** [comment] 2021-12-26 16:00
My bad, actually  It worked after running  cmd with admin privileges(same way I modified in Jenkins as well)

**Comment by bjn** [comment] 2022-01-18 07:14
@saivarma576 or you hade different casing on the folder. It seems to be case sensitive on windows. I had the same issue where I changed into a directory with a powershell function Set-Location "sources" and could not run any tests with the same error message. The directory is actually called "Sources", changing to that made playwright identify the test file correctly.
