### ISSUE TITLE
[BUG] HTML reporter doesn't use outputFile defined in config

### ISSUE THREAD

**Issue by jimpriest** [microsoft/playwright#11548] opened 2022-01-21 15:40 UTC
**Context:**
- Playwright Version: 1.18
- Operating System: Linux Ubuntu 20.04
- Node.js version: 16.13
- Browser: Chromium

**Code Snippet**
Within my config file I have this defined per the docs here https://playwright.dev/docs/test-reporters#html-reporter

```
reporter: [['line'], ['junit', { outputFile: 'test-results/results.xml' }], ['html', { outputFile: 'output/index.html' }]],
```
**Describe the bug**

The junit report is correctly written to /test-results but the HTML file always goes to /playwright-report even though I've defined it to go to /output

![playwright-html-issue](https://user-images.githubusercontent.com/197930/150555380-f0a2a8e6-4b3d-4f50-a82c-780d7916616f.png)

**Comment by vsravuri** [comment] 2022-01-21 16:27
For HTML Report, you need to specify outputFolder like this as per documentation. In your code snippet you are using outputFile

https://playwright.dev/docs/test-reporters#html-reporter

```javascript
const config = {
  reporter: [ ['html', { outputFolder: 'my-report' }] ],
};
```

**Comment by jimpriest** [comment] 2022-01-21 18:11
Doh - would it make sense to make those consistent and use one or the other between all the reporter options? I assume they are all doing the same thing?

**Comment by mxschmitt** [comment] 2022-01-21 22:44
junit's output is a folder and html report output is a file. So it's natural that these are called outputFile and outputFolder. Closing since this is as designed.

**Closed by mxschmitt** 2022-01-21 22:44 UTC
