### ISSUE TITLE
[BUG] Cannot QuerySelectorAsync  when the QuerySelectorAllAsync selector is a set of elements

### ISSUE THREAD

**Issue by DoubleSlashDesign2** [microsoft/playwright#10663] opened 2021-12-02 01:53 UTC
**Context:**
- Playwright Version: [1.17.0 and 1.17.1]
- Operating System: [Windows]
- Playwright .net CSharp C#
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [.net core 5, windows 11]

**Code Snippet**

You are always able to interact with the First item in the collection or as Array or even converting it using GetEnumerator().
I can see that there are 18+ results but can not access any item except item 0

Item 0 or the first item always returns an object.
Item 1 and all others will return null.

```c#
//--this would work - item 0 will always work
IReadOnlyList<IElementHandle> dataArray = await page.QuerySelectorAllAsync(selector);
var href = await dataArray[0].QuerySelectorAsync("h2.vehicle-card-title a");
await href.ClickAsync();


//--this would NOT work because it uses Item 1 - href  would be null
IReadOnlyList<IElementHandle> dataArray = await page.QuerySelectorAllAsync(selector);
var href = await dataArray[1].QuerySelectorAsync("h2.vehicle-card-title a");
await href.ClickAsync();
```

**Describe the bug**

Add any other details about the problem here.

**Comment by dgozman** [comment] 2021-12-06 22:43
@DoubleSlashDesign2 Perhaps there is no `"h2.vehicle-card-title a"` inside the second item? If you could provide a repro, we'll be able to debug the issue.

**Comment by dgozman** [comment] 2021-12-11 22:08
Closing because we cannot reproduce the issue. If you have a repro that we can run, please open a new bug.

**Closed by dgozman** 2021-12-11 22:08 UTC
Labels: triaging

**Comment by DoubleSlashDesign2** [comment] 2022-01-25 19:40
@dgozman sorry for the late reply. here you go

            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync(
                new BrowserTypeLaunchOptions
                {
                    Headless = false,
                    SlowMo = 30,
                    DownloadsPath = @"C:\temp"
                });

            var page = await browser.NewPageAsync();
            await page.GotoAsync("https://www.clintonfamilyford.com/all-inventory/index.htm?search=f-150");
            //await page.WaitForTimeoutAsync(350);

            var selector = "li div.vehicle-card-body div.vehicle-card-details-container";
            var i = 0;

            //var s = await page.QuerySelectorAllAsync(selector);
            IReadOnlyList<IElementHandle> s = await page.QuerySelectorAllAsync(selector);

            var e = s.GetEnumerator();

            while (e.MoveNext())
            {
                var hrefs = await e.Current.QuerySelectorAsync("h2.vehicle-card-title a");
                string stopherex = "";
                if (hrefs != null)   //---THIS WILL ERROR OUT ON 2ND LOOP - IT SHOULD NOT
                {
                    //await hrefs.ClickAsync();
                    string stopherex2 = "";
                    //await hrefs.DisposeAsync();
                    hrefs = null;
                }
            }

            await page.WaitForTimeoutAsync(10);

            await page.ScreenshotAsync(new PageScreenshotOptions { Path = @"C:\temp\screenshot.png" });

        }
