### ISSUE TITLE
[Feature] Ability to save a web page as HTML/MHTML

### ISSUE THREAD

**Issue by craysiii** [microsoft/playwright#13629] opened 2022-04-19 07:12 UTC
I am trying to save a webpage that is unusually large (roughly 445 pages when saved to a page with a standard page size). I would like to instead save this page as a single page, however, most PDF readers absolutely choke with page this large.

It would be nice instead if we were able to save the page to an HTML/MHTML file e.g. in Chromium, right click on the page and select "Save As". This would improve the rendering time when the page is opened greatly.

**Comment by pavelfeldman** [comment] 2022-10-20 17:10
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-10-20 17:10 UTC
Labels: P3-collecting-feedback

**Comment by fersarr** [comment] 2023-01-18 16:31
Yea this would be really useful. When there's an issue we usually take a screenshot + video but having the actual page in a single file (.mht) would be really helpful when trying to reproduce the issue.

**Comment by jackHedaya** [comment] 2023-02-28 01:19
@pavelfeldman Is there room for this to be reconsidered?

**Comment by jackHedaya** [comment] 2023-02-28 06:13
I would be happy to take a crack at a PR as well :)

**Comment by jackHedaya** [comment] 2023-02-28 07:00
For anyone that comes across this, saving a web page as HTML or MHTML is as easy as:

```
const session = await page.context().newCDPSession(page)

const doc = await session.send('Page.captureSnapshot', { format: 'mhtml' })
```

**Comment by 1049451037** [comment] 2023-10-13 11:12
Hi @jackHedaya , what language did you use? Is there any python version?
