### ISSUE TITLE
[Bug]: Cannot step into Typescript Playwright source code from within Visual Studio Code debugger

### ISSUE THREAD

**Issue by luckerby** [microsoft/playwright#33233] opened 2024-10-22 21:23 UTC
### Version

1.44.1

### Steps to reproduce

I cannot provide a repro as the project we have is within Microsoft, but I can provide all the details over IM/call

### Expected behavior

We have a Typescript project that uses Playwright for running tests. We want to be able to step into the source code for Playwright.

We set things up like this: after cloning the Playwright repo we build with sourcemaps using `yarn build --sourcemap`. Next we use `yarn link` against the `playwright` and the `playwright-core` packages so our project uses the build we've manually done earlier that includes the sourcemaps. Now we use VS.Code to set a breakpoint in one of our tests and start debugging. The breakpoint is hit and stepping into eventually lands us inside the Playwright code, however it's the JS files not the TS ones (first printscreen below).

However the sourcemaps do exist (2nd picture) and they do point to the right TS file (3rd picture). We even get to see the TS files getting accessed while the debugger runs (4th picture). Yet the debugger doesn't step inside the TS files.

Note that we're using the default JS debugger for VS.Code: `vscode-js-debug`.

![Image](https://github.com/user-attachments/assets/e01d5ca7-44b8-4683-81b2-01177084c716)

![Image](https://github.com/user-attachments/assets/20b486c4-326d-491b-a93b-01d7c8de9c38)

![Image](https://github.com/user-attachments/assets/438018ce-136a-4e83-a2f3-9285c0c35bd2)

![Image](https://github.com/user-attachments/assets/cc011da9-685e-4c11-9eee-d83c6d7c0e59)

### Actual behavior

We'd expect the debugger to land us in the Playwright TS code

### Environment

  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 33.61 GB / 63.95 GB
  Binaries:
    Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.94.2 - C:\Program Files\Microsoft VS Code\bin\code.CMD

**Comment by mxschmitt** [comment] 2024-10-22 21:39
> We want to be able to step into the source code for Playwright.

What are you trying to achieve?

Playwright is not using Yarn nor we support `yarn link`. I recommend to start with an actual bug report whats not working when you use the Playwright library etc. This helps us to understand the scenario better you are trying to fix.

**Comment by mxschmitt** [comment] 2024-10-22 22:05
I'll close it for now since this is not a bug in Playwright. When we develop internally, we usually change the `page-fill.spec.ts` and do `npm i && npm run watch` before. So we have never tested `npm/yarn link before` - so things might break there.

Feel free to keep this bug updated, so it helps others who are interested in it.

If you are interested in skipping the internal code when stepping into a `test.step` in the JS Debugger, please file a separate bug report, thanks!

**Closed by mxschmitt** 2024-10-22 22:05 UTC

**Comment by luckerby** [comment] 2024-10-24 17:48
Thanks to @mxschmitt I managed to find the solution. Full steps below.

1. Clone the Playwright repo from [here](https://github.com/microsoft/playwright)
2. Install the dependencies (`yarn` works ok)
3. Build with sourcemaps on: `yarn build --sourcemap`
4. Link the following 2 packages: run `yarn link ` inside _packages/playwright_ then `yarn link "playwright"` inside your project's root; then run `yarn link ` inside _packages/playwright-core_ then `yarn link "playwright-core"` inside your project's root
5. Clone the playwright-vscode repo [here](https://github.com/microsoft/playwright-vscode)
6. Add the following line to the configuration passed inside [this file](https://github.com/microsoft/playwright-vscode/blob/6284d0776c7dbe8e8dfb914bddd5bc752c9d6629/src/playwrightTestServer.ts#L274), making sure you replace the path to the Playwright repo cloned in the first step `outFiles: ['c:/src/playwright/packages/**/*.js']`
7. Install the dependencies (`yarn` works ok)
8. Build using: `npm run build`
9. Copy the _extension.js_ file generated in the _out_ folder over to the one in your locally stored extension, which you will find in : <Your-local-profile>\.vscode\extensions\ms-playwright.playwright-<version>\out\extension.js
10. Restart VS.Code


If all goes as expected you should end up in the TS code when stepping into:

![Image](https://github.com/user-attachments/assets/59b7f89f-6f99-4311-9257-44402c40d0d4)
