### ISSUE TITLE
Chaining filter has inconsistent results

### ISSUE THREAD

**Issue by jcrans13** [microsoft/playwright#28867] opened 2024-01-04 18:22 UTC
### System info
- Playwright Version: 1.40.1
- Operating System: Windows 10
- Browser: Chromium
- Other info: N/A

### Source code

[We will only be able to work on the issues that we can reproduce.]

[Please provide a self-contained example in a form of a snippet, archive or a repository.]

Code snippet:
`await page.locator('a').filter({ hasText: firstLast }).filter({ has: page.locator('//img[@src="assets/images/16x16/yellow.png"]')}).locator('a').click({ button: 'right' });`

[Repro scenario can't be large or have external dependencies.]

**Steps**
- In order to reproduce you will need a page with many elements of a certain parent type that contains 2 child elements that need to be referenced in the selector. In my example, I have a "link" that I need to select that contains a child element that contains a specific name and another child element that contains a specific image.

**Expected**

The selector should work 100% of the time or not at all

**Actual**

The results are inconsistent, working most of the time but not all the time

Error: locator.click: Error: strict mode violation: locator('a').filter({ has: locator('//img[@src="assets/images/16x16/yellow.png"]') }).locator('a') resolved to 30 elements:
    1) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    2) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    3) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    4) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    5) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    6) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    7) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    8) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    9) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    10) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    ...

Call log:
  - waiting for locator('a').filter({ has: locator('//img[@src="assets/images/16x16/yellow.png"]') }).locator('a')

**Comment by mxschmitt** [comment] 2024-01-05 08:48
Closing for now, since this issue does not contain clear reproduction details / following the issue template.

Feel free to re-file having exact steps, in order for us to reproduce the issue, thanks for your understanding.

**Closed by mxschmitt** 2024-01-05 08:48 UTC
