### ISSUE TITLE
[BUG] Webkit renders some fonts incorrectly on Windows

### ISSUE THREAD

**Issue by vladkrasn** [microsoft/playwright#16104] opened 2022-08-01 17:03 UTC
**Context:**
- Playwright Version: 1.24.2
- Operating System: Windows 11
- Node.js version: 16
- Browser: Webkit

This issue was raised here previously: https://github.com/microsoft/playwright/issues/7441 (also related to https://github.com/microsoft/playwright/issues/2626)
I don't think it was resolved, since the person who raised it fixed it on the end of their website, whereas the Webkit's issue is still present

An easy example would be https://nextjs.org/
Webkit:
<img width="1445" alt="image" src="https://user-images.githubusercontent.com/28753668/182203389-b43db3ec-da52-4268-b153-4a0fdcee4377.png">

Chrome: 
<img width="1445" alt="image" src="https://user-images.githubusercontent.com/28753668/182203647-a45e0547-0342-4794-bbae-73b7a7b42066.png">

**Comment by mxschmitt** [comment] 2022-08-01 20:35
Looks like https://github.com/microsoft/playwright/issues/7441#issuecomment-880384327 still applies. We recommend using macOS or Linux when testing with WebKit, since when using macOS its as close as it can get with font rastering / image rendering etc.

cc @fujii.

**Comment by fujii** [comment] 2022-08-02 00:29
WebKit WinCairo port is still using Cairo GDI font backend that doesn't support color fonts and variable fonts.
It should switch to DirectWrite. We have two choices, using Cairo DirectWrite font backend and replacing Cairo with Skia.
This is an upstream bug ticket to use Cairo DirectWrite font backend.
https://bugs.webkit.org/show_bug.cgi?id=215259
Someone is working on Skia integration in WebKit Slack.
If you're will to help, join WebKit Slack.
https://webkit.org/getting-started/#contribute

**Comment by mxschmitt** [comment] 2022-08-04 08:18
Closing as per's above answer.

Thanks @fujii 💯

**Closed by mxschmitt** 2022-08-04 08:18 UTC
Labels: triaging

**Comment by Th3S4mur41** [comment] 2023-08-11 10:45
I was facing the same issue while trying to reproduce a bug in webkit.
Good to know that this does not apply to Safari on MacOS/iOS
