### ISSUE TITLE
[BUG] (🐞) `evaluate` evaluates an object literal as a block statement

### ISSUE THREAD

**Issue by KotlinIsland** [microsoft/playwright#17865] opened 2022-10-06 03:57 UTC
**Context:**
- Playwright Version: [what Playwright version do you use?] playwright-python 1.26.1
- Operating System: [e.g. Windows, Linux or Mac] Windows
- Node.js version: [e.g. 12.22, 14.6] Python 1.10.7
- Browser: [e.g. All, Chromium, Firefox, WebKit] All

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```py
from playwright.sync_api import sync_playwright

with sync_playwright() as pw:
    page = pw.chromium.launch().new_page()
    print(page.evaluate("{a: 1}"))  # 1
    print(page.evaluate("{a: 1, b: 2}"))  # SyntaxError: Unexpected token ':'
```

**Describe the bug**
From `page.evaluate`:
> If it looks like a function declaration, it is interpreted as a function. Otherwise, evaluated as an expression.

This 'looks' like either an object literal or a block statement, yet instead of being evaluated as an expression, it's being evaluated as a statement.

# Workaround 
Wrap it in parenthesis:
```py
from playwright.sync_api import sync_playwright

with sync_playwright() as pw:
    page = pw.chromium.launch().new_page()
    print(page.evaluate("({a: 1})"))  # {'a': 1}
```

**Comment by yury-s** [comment] 2022-10-06 19:30
This is working as intended, if you ` eval("{a: 1, b: 2}")` in node.js it will throw the same error. You can disambiguate the meaning of {} by wrapping it in () as you described. Closing the issue as there is no planned action on playwright side.

**Closed by yury-s** 2022-10-06 19:30 UTC
