### ISSUE TITLE
[BUG] `playwright` package has `install` script but `@playwright/test` doesn't

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#11531] opened 2022-01-21 01:00 UTC
the `install` script [defined here](https://github.com/microsoft/playwright/blob/main/packages/playwright/package.json#L26) is useful because it [gets automatically run when you run `npm install playwright`](https://docs.npmjs.com/cli/v8/using-npm/scripts#npm-ci)

however `@playwright/test` doesn't seem to have an `install` script, meaning you have to manually run `playwright install` after installing the package, which is annoying

**Comment by mxschmitt** [comment] 2022-01-21 09:57
It's expected that when using @playwright/test the browsers do not get installed manually. The reason for that is that people often only want to test Chromium, or only Chrome and MSEdge and this allows them to never install the default browsers or install just a sub-set of the browsers.

**Comment by DetachHead** [comment] 2022-01-21 10:06
i considered that, but i'm confused as to why that concern would only apply to `@playwright/test` but not `playwright`

**Comment by mxschmitt** [comment] 2022-01-21 10:16
Because `@playwright/test` is a test-runner, which allows you to have a custom configurations for only some browsers while playwright is a library which ships by default with all 3 browsers.

If you want to have only some browsers in the library form, you can use `playwright-chromium`, `playwright-firefox` and `playwright-webkit` NPM packages. And for the test-runner you have to call `npx playwright install` or e.g. `npx playwright install webkit`

**Comment by mxschmitt** [comment] 2022-01-21 22:46
Closing since this is working as intended.

**Closed by mxschmitt** 2022-01-21 22:46 UTC
Labels: triaging

**Comment by DetachHead** [comment] 2022-01-21 23:12
Sounds backwards to me. The way I see it if you’re using playwright to run tests (`@playwright/test`) you’d be more likely to want to install all 3 browsers so you can test your application on all of them

whereas if you are just doing RPA (`playwright`) you have no need to use more than one browser so it doesn’t make sense to automatically install all 3
