### ISSUE TITLE
[BUG] chromium newContext should work as incognito mode on Windows 11

### ISSUE THREAD

**Issue by MaciekStrzelbicki** [microsoft/playwright#27991] opened 2023-11-06 15:05 UTC
### System info
- Playwright Version: [v^1.39.0]
- Operating System: [Windows 11]
- Browser: [ Chromium ]

### Source code

- [ v ] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: "./tests",
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: "html",
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
});

```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
    const browser = await chromium.launch();
    const context = await browser.newContext({
      recordVideo: {
        dir: "video/",
      },
    });
  await page.goto('https://testsite.com');
});
```

**Steps**
- run locally on windows, logged to testing site ('https://testsite.com') with SSO (login.onmicrosoft.com)

**Expected**
browser.newContext() on chromium should works as incognito mode, SSO (login.onmicrosoft.com) popup should ask for login and password on windows 11

**Actual**

- locally when I run `npx playwright test`, I see on video browser opens SSO popup, and recognize mine user, and tried login with otp, instead of ask for username and password. 
- When I use:
```
const browser = await firefox.launch();
```
everything works as it should.
chromium works on CI on ubuntu as it should too.

**Comment by dgozman** [comment] 2023-11-10 04:34
@MaciekStrzelbicki Could you please provide a full repro that we can run locally? `https://testsite.com` does not load for me, so I am not able to reproduce the issue. Also, if you could attach those videos that illustrate the problem, that would be really helpful.

**Comment by MaciekStrzelbicki** [comment] 2023-11-14 11:16
@dgozman here you have sample repo with video examples https://github.com/MaciekStrzelbicki/playwright-issue-example
I hope this clears it up

**Comment by mxschmitt** [comment] 2023-11-14 15:17
We unfortunately need to close this issue since its not actionable for us. We need a full reproduction which we can run locally in order to triage an issue. It should not depend on any third-party sites. Thanks for your understanding.

**Closed by mxschmitt** 2023-11-14 15:17 UTC
Labels: triaging
