### ISSUE TITLE
Using test.describe.configure and browser in the before all causes      TypeError: Cannot read properties of undefined (reading 'wsEndpoint') error

### ISSUE THREAD

**Issue by srikanthathikari** [microsoft/playwright#31258] opened 2024-06-11 20:24 UTC
### Version

1.44.1

### Steps to reproduce

I am trying to run my tests in same browser page and I am trying to use the way it has been shown in playwright documentation. 

import { test, type Page } from '@playwright/test';

test.describe.configure({ mode: 'serial' });

let page: Page;

test.beforeAll(async ({ browser }) => {
  page = await browser.newPage();
});

test('runs first', async () => {
  await page.goto('https://playwright.dev/');
});

test.afterAll(async () => {
  await page.close();
});

This throws a 
    TypeError: Cannot read properties of undefined (reading 'wsEndpoint')

However, when I remove test.describe.configure({ mode: 'serial' }); from line 1 and browser from before all the tests works with the configuration both in browserstack and local. 

### Expected behavior

I expect to see it working using describe.configure({mode:serial}) and have browser in the before all

### Actual behavior

Throws error 

    TypeError: Cannot read properties of undefined (reading 'wsEndpoint')

### Environment

```shell
Mac OS and cloud( browserstack)
```

**Comment by yury-s** [comment] 2024-06-11 22:06
It looks like your configuration also depends on a remote connection to a browser. Please share complete minimal example which we could run locally to debug the issue.

**Comment by srikanthathikari** [comment] 2024-06-12 01:48
Sure. I have created a repository with minimal example here. 
I have commented the browserstack credentials in the browserstack.yml file.
https://github.com/srikanthathikari/playwright-playground

**Comment by yury-s** [comment] 2024-06-12 15:43
This test passes just fine. Also it doesn't use wsEndpoint anywhere. The problem seems to be coming from the browserstack hooks into Playwright, in that case you should file this bug with them we cannot help with that. If you think this is a Playwright issue we need a self-contained reproduction that doesn't depend on external services such browserstack.

**Comment by yury-s** [comment] 2024-06-17 17:43
Closing per the response above, feel free to open a new issue if it doesn't work.

**Closed by yury-s** 2024-06-17 17:43 UTC
