### ISSUE TITLE
Playwright extension not "seeing" my playwright tests in my project - Part 2

### ISSUE THREAD

**Issue by alilland** [microsoft/playwright#20278] opened 2023-01-22 00:36 UTC
reopening https://github.com/microsoft/playwright/issues/20234

**Comment by pavelfeldman** [comment] 2023-01-23 15:47
Since we don't see anything like this reported by other clients, we would need exact steps to follow in order to reproduce this issue. Could you create a minimal repro we could clone or unzip so that we saw it not working?

**Comment by pavelfeldman** [comment] 2023-01-25 15:52
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2023-01-25 15:52 UTC
Labels: triaging
