### ISSUE TITLE
[BUG] Using Webkit browser cookies added to the context are not send on script loading

### ISSUE THREAD

**Issue by felipebn** [microsoft/playwright#28603] opened 2023-12-12 17:09 UTC
### System info
- Playwright Version: [v1.40.1]
- Operating System: [All]
- Browser: [WebKit]
- Other info:

### Source code

**Scenario:** set cookies for distinct domains, e.g. one for the main document domain and another for loading CDN assets.

**Issue:** In Webkit, the cookie for the CDN assets domain is not send in the request. Changing the `browserName` config to `chromium` for example works as expected.

This can be checked on a self contained example: https://github.com/felipebn/playwright-webkit-cookie-issue

**Steps**
- Setup a proxy (config is set to `localhost:8080`) to inspect the outbound requests
- Run tests as described in provided repo
- Inspect the requests

Test itself simply:
- sets cookies for 2 domains
- does a request to the main domain that will have script tags loading the second domain

**Expected**

Was expecting Webkit to behave as same as Chrome, with the cookie being sent when making requests to both domains.

**Actual**

For the second domain, that is used in script tags, the cookie is not set in the request.

On the images below, observe the line `3` , where the `my-test-cookie` is shown for Chrome but not for Webkit.

| Request with chrome (cookie is there)  | Request with webkit (cookie missing) |
| ------------- | ------------- |
| ![image](https://github.com/microsoft/playwright/assets/209101/3740fb84-38f5-40d8-842c-953b66e7e201)  | ![image](https://github.com/microsoft/playwright/assets/209101/63254385-26c7-4eae-9e66-2fbc6923753a)  |

**Comment by mxschmitt** [comment] 2023-12-13 04:39
I tried to reproduce it, but was not able to. I'm on Ubuntu 20 with Playwright 1.40 and using mitmproxy which should not make a diference:

<img width="880" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/69b14899-db2c-4a9b-a602-13b97d5894cd">

On which OS are you with which version?

**Comment by mxschmitt** [comment] 2023-12-14 01:03
I was setting the cookie in Safari (Technology Preview):

<img width="291" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/54cad089-e30c-48eb-b620-00cd4aa1797d">

and there it was also not adding the cookie:

<img width="725" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/39e9e680-c4e8-422b-8c96-74c3721c5801">

Most likely, this is because Safari ITP (Intelligent Tracking Prevention). So since we are behaving like Safari there, it looks like this is working as intended.

**Comment by felipebn** [comment] 2023-12-14 13:11
Yah seems like it is that. Is it possible to disable that somehow? 

Thanks for digging further !

**Comment by mxschmitt** [comment] 2023-12-14 13:17
Unfortunately not, since this aligns with Safari I'm closing as expected.

**Closed by mxschmitt** 2023-12-14 13:17 UTC

**Comment by mxschmitt** [comment] 2023-12-15 22:53
Linking https://github.com/microsoft/playwright/issues/17368 to it
