### ISSUE TITLE
[BUG] response url match is failing

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#23965] opened 2023-06-29 19:02 UTC
### System info
- Playwright Version: "^1.32.2"
- Operating System: MAC 
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

```
Hi All, i have 2 urls that matches https://service.east.dev.com/dev/order/submission/246r346
const [auctionResponse] = await Promise.all([
    page.waitForResponse(res =>
        res.status() == 200
        &&
        res.url().includes('/order/submission/')
    ),
 
]);
the other url has /order/submission/246r346/settings
sometimes it is reading the URL https://service.east.dev.com/dev/order/submission/246r346/settings and test failing, 
can you please advise how i can update the above code to exclude ’settings
instead of includes, is there anything else that can be used here to look for /order/submission/{orderId} (partial match)  excluding settings.

``

**Comment by Exoow** [comment] 2023-06-29 19:11
You could add` && !res.url().includes('settings')` or use regex... Definitely not a bug...

**Comment by pavelfeldman** [comment] 2023-07-03 20:02
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2023-07-03 20:02 UTC
