### ISSUE TITLE
[BUG] Residental proxies do not work with WebKit

### ISSUE THREAD

**Issue by hnkd** [microsoft/playwright#5321] opened 2021-02-05 01:04 UTC
**Context**
- Playwright Version: 1.8.0
- Operating System: Windows 10 10.0.18363
- Node.js version: 14.15.4
- Browser: WebKit 1423

**Code Snippet**

```javascript
const {webkit} = require('playwright-webkit');

(async () => {
	const browser = await webkit.launch({
		headless: false,
		proxy: {
			server: 'http://zproxy.lum-superproxy.io:22225',
			username: 'USERNAME',
			password: 'PASSWORD'
		}
	});
	
	const page = await browser.newPage();
	await page.goto('https://www.expressvpn.com/what-is-my-ip');
})();
```

**Describe the bug**

I am trying to use HTTP residental proxies with Playwright WebKit. This is the error I am getting: `UnhandledPromiseRejectionWarning: page.goto: Failure when receiving
 data from the peer`. I have tried passing `ignoreHTTPSErrors: true` to the browser options, and I am getting a timeout error: `UnhandledPromiseRejectionWarning: page.goto: Timeout 30000ms exceeded`.

These proxies work with Chromium and Firefox, so it's only happening with WebKit. I'm not sure if it's a bug with WebKit itself, or if it can be fixed in Playwright. Datacenter proxies work fine, so in order to reproduce the issue, you have to use residental proxies. I currently use [luminati.io](https://luminati.io). Residental proxies assign an IP address during the authentication, as the proxy server is just a domain name, unlike datacenter proxies that directly connect to a dedicated IP address. This is probably why WebKit can't connect to the proxy server.

**Comment by hnkd** [comment] 2021-02-15 14:58
Anything?

**Comment by fujii** [comment] 2021-02-17 01:30
Playwright WebKit Windows is using WebKit WinCairo port that is using libcurl for the network.
I have no Luminati account. Could you try the official curl.exe? You can get it from https://curl.se/windows/

> curl.exe --proxy http://zproxy.lum-superproxy.io:22225 --proxy-user USERNAME:PASSWORD https://www.expressvpn.com/what-is-my-ip

**Comment by hnkd** [comment] 2021-02-18 18:39
> Playwright WebKit Windows is using WebKit WinCairo port that is using libcurl for the network.
> I have no Luminati account. Could you try the official curl.exe? You can get it from https://curl.se/windows/
> 
> > curl.exe --proxy http://zproxy.lum-superproxy.io:22225 --proxy-user USERNAME:PASSWORD https://www.expressvpn.com/what-is-my-ip

Thank you for your answer. I just tried that and the proxies work perfectly fine with curl.exe, so I assume this is an issue with Playwright?

**Comment by fujii** [comment] 2021-02-19 01:27
Thank you.
I set up a proxy server on my localhost for testing.
If I set username and password in the proxy URL, it works.

~~~
  proxy: {
  	server: 'http://USERNAME:PASSWORD@localhost:8888'
  }
~~~

Or, if I set env vars and remove the proxy setting, it also works.

$env:http_proxy="http://USERNAME:PASSWORD@localhost:8888"
$env:https_proxy="http://USERNAME:PASSWORD@localhost:8888"

However, setting username&password as options doesn't work.

~~~
  proxy: {
  	server: 'http://localhost:8888',
        username: 'USERNAME',
        password: 'PASSWORD'
  }
~~~

I'm not a Playwright expert. I don't know how to fix.

**Comment by hnkd** [comment] 2021-02-19 20:15
That didn't work for me unfortunately. The issue is only happening when I use residental proxies (the ones with a domain name instead of an IP address). Normal datacenter proxies work fine, even if I set the username and password as options.

**Comment by mxschmitt** [comment] 2021-08-02 08:15
Closing for now as part of the triage process. Please reopen with a reproducible which we can use to test locally to enable WebKit support for such kind of proxies too. (Reproducible in Node.js is preferred since we can't subscribe to residentalproxies).

**Closed by mxschmitt** 2021-08-02 08:15 UTC
Labels: triaging
