### ISSUE TITLE
[BUG] Route method not intercepting HTTP requests in chromium but working with firefox.

### ISSUE THREAD

**Issue by Palash9088** [microsoft/playwright#23282] opened 2023-05-25 18:37 UTC
### System info
- Playwright Version: [v1.34.2]
- Operating System: [All]
- Browser: [Chromium,Firefox,Webkit]
- Other info:[Not working with Chromium & Webkit,  Working with Firefox]

### Source code
-
```typescript
test.only("verify Klaviyo integration Modified", async ({ page }) => {
  let help:string = "";
    await page.route(
    "https://a.klaviyo.com/api/track",
    async (route, request) => {
      const networkRequests:string = request.postData()!;
      help = networkRequests; 
      await route.continue();
    });
    await page.goto(
    "https://rohitgupta.wingified.com/klaviyo1.html?id=" + accountId,{
      waitUntil:'networkidle'
    }
  );
  console.log(help); //network request details
  const klaviyoCookies = await page.context().cookies();
  expect(JSON.stringify(klaviyoCookies)).toContain("_vis_opt_exp_35_combi");
  expect(help.includes('"Exp_name":"KLAVIYO - DO NOT DELETE"')).toBeTruthy();
  expect(help.includes('"Var_name"')).toBeTruthy();
});
``` 
**Config file**

```typescript
import baseConfig from "vwo-playwright-seed/lib/config/base.conf";

const config = baseConfig.config;
config["use"]["baseURL"] = process.env.BASE_URL || "https://app.vwo.com/";
config["projects"] = [
  {
    name: "Chrome",
    use: {
      browserName: "chromium",
    },
  },
  {
    name: "Firefox",
    use: {
      browserName: "firefox",
    },
  },
];
export default config;
``` 

**Steps**
- [Run the test]
- [npx playwright test specs/Integration.Spec.ts --project=Chrome]

**Expected**
```
-----------------------------18815464218261179702781698581
Content-Disposition: form-data; name="data"

{"event":"VWO","token":"TSR5n6","properties":{"Exp_name":"KLAVIYO - DO NOT DELETE","Var_name":"Variation-1","$use_ip":true,"$is_session_activity":true},"customer_properties":{"$exchange_id":"UKGnAHMG7opQKheXx_c9e6AApF9oEeD8PQQ_Yt1qyOJXWthcyBDClUET7ANQ3krL.TSR5n6","$referrer":{"ts":1685039184,"value":"","first_page":"https://rohitgupta.wingified.com/klaviyo1.html?id=541364"},"$last_referrer":{"ts":1685039184,"value":"","first_page":"https://rohitgupta.wingified.com/klaviyo1.html?id=541364"}}}
-----------------------------18815464218261179702781698581--

-----------------------------18815464218261179702781698581                                                                     
Content-Disposition: form-data; name="data"

{"event":"VWO","token":"TSR5n6","properties":{"Exp_name":"KLAVIYO - DO NOT DELETE","Var_name":"Variation-1","$use_ip":true,"$is_session_activity":true},"customer_properties":{"$exchange_id":"UKGnAHMG7opQKheXx_c9e6AApF9oEeD8PQQ_Yt1qyOJXWthcyBDClUET7ANQ3krL.TSR5n6","$referrer":{"ts":1685039184,"value":"","first_page":"https://rohitgupta.wingified.com/klaviyo1.html?id=541364"},"$last_referrer":{"ts":1685039184,"value":"","first_page":"https://rohitgupta.wingified.com/klaviyo1.html?id=541364"}}}
-----------------------------18815464218261179702781698581--
``` 
[Describe expected behavior]
**This should be expected behaviour & all assertion should get passed**
![image](https://github.com/microsoft/playwright/assets/44397045/dffaa737-cc7f-487e-9739-a78c6ff4c9aa)

![image](https://github.com/microsoft/playwright/assets/44397045/32a25549-2216-4f68-b3fb-86b40c4d37b3)
**This expected result is with firefox browser.**

**Actual**
Even request is not getting intercept in chrome browser same issue with the webkit.
[Describe actual behavior]
Assertions are getting failed as they are not intercepted with the route method with chromium.
![image](https://github.com/microsoft/playwright/assets/44397045/a1b12ddc-ff02-4d19-a4d2-d245baa539b0)
![image](https://github.com/microsoft/playwright/assets/44397045/640b9afd-926b-4701-a7e4-5fbea4310bfc)

**Comment by mxschmitt** [comment] 2023-05-30 10:29
PostData is empty to it looks like a duplicate of https://github.com/microsoft/playwright/issues/6479.

**Closed** 2023-05-30 10:29 UTC
