### ISSUE TITLE
[Feature]: more readable Enable/Disable cache for each request

### ISSUE THREAD

**Issue by LeMoussel** [microsoft/playwright#10414] opened 2021-11-18 13:13 UTC
### Feature request

To disable cache, you can use [cdp_session.send](https://playwright.dev/python/docs/api/class-cdpsession#cdp-session-send): 
```
cdp_session = page.context.new_cdp_session(page)
cdp_session.send('Network.setCacheDisabled', {'cacheDisabled': True})
```

To be more readable, we could have the method: `page.set_cache_enabled(enabled)`

- `enabled`: Boolean value, i.e. one of `True` or `False`. Set the `enabled` state of the cache.

**Comment by mxschmitt** [comment] 2021-11-18 15:55
This looks like related / a duplicate of #7220. Could you tell us in what kind of limitations you currently run into and why you need it? (feel free to comment directly in #7220 then we can merge these two issues).

**Closed** 2021-11-19 10:19 UTC
Labels: triaging
