### ISSUE TITLE
[Bug]: Headless mode doesn't not have the same behavior

### ISSUE THREAD

**Issue by CookieMonster70** [microsoft/playwright#30337] opened 2024-04-11 13:02 UTC
### Version

1.42.1, 1.43.0

### Steps to reproduce

If I start playwright in VSCode with the plugin then the test run is successfully.
If I start the test over npx playwright test --ui and I excute the test then it fails because, it doesn't load some how Javascript or Woff's, but I don't know why. 
I have no error or something like that. 
I set on the start up headless: false 
`  browser = await chromium.launch({headless: false});`
then it works also with npx playwright test and npx playwright test --ui, because it starts up the browser.

headless mode
![image](https://github.com/microsoft/playwright/assets/25148194/3e8d8ef3-7951-4472-b9a1-7fc85a80c466)

not in headless mode
![image](https://github.com/microsoft/playwright/assets/25148194/f16f5818-25aa-4e73-9ee6-bdefd7782af2)
the arrows on the left side are some characters. If they don't appear something is wrong, and the page can't be automated

I tryed several setting, with allow-javascript and so, but I wasn't successfully at all.

For e.g if I run the test form VS Code "Show Browser" with Chrome, Edge, Chromium it works, but Firefox has the same behavior the page will not be displayed correctly.

### Expected behavior

I expect to see the arrows also in the headless mode. The indicator for me that the page is loaded correctly. 

### Actual behavior

I see the arrows only in the headed mode

### Environment

```shell
System:
OS: Windows 10
Browser: Chrome Version 121.0.6167.185 (Official Build) (64-bit)
Playwright 1.42.1 and 1.43.0
node: 20.11
npx: 10.2.0
```

**Comment by mxschmitt** [comment] 2024-04-11 13:09
Probably similar to https://github.com/microsoft/playwright/issues/9173.

While the fonts are correctly loaded inside the headless shell, the trace / the right part of the UI Mode does not show it correctly.

Are these woff2 icon fonts?

**Comment by mxschmitt** [comment] 2024-04-11 13:40
Aren't you are saying here that UI Mode is broken as well?

> If I start the test over npx playwright test --ui and I excute the test then it fails because, it doesn't load some how Javascript or Woff's, but I don't know why.

"Show Browser" in VSCode is different, thats like a normal headed window.

**Comment by CookieMonster70** [comment] 2024-04-11 13:46
In VSCode "Show browser" it works.
But if I start npx playwright tests --ui not!
Only if I set headless to false then it works with npx playwright tests --ui but then I'm not able anymore to run the tests headless

**Comment by SrBrahma** [comment] 2024-04-12 11:37
I also have missing font on headless. All my screenshots are different due to that if I run with headless: true or false.

**Comment by mxschmitt** [comment] 2024-04-12 11:38
@SrBrahma could you provide us a repro or confirm the following things?

1. You are using a woff2 font
2. The issue reproduces in UI Mode or trace
3. The issue reproduces in VSCode / when running headed

**Comment by SrBrahma** [comment] 2024-04-12 13:26
Unfortunately, I can't provide a repro at the moment, so I will answer:

1) Yes, woff2 font.
2) No, it didn't happen in UI mode; the screenshots are unchanged.
3) Yes, it happens on VSCode / headed.

**Comment by mxschmitt** [comment] 2024-04-14 16:47
https://github.com/microsoft/playwright/issues/9173 is actually fixed, was not able to verify it anymore in v1.43.

We need a reproduction here in order to work on this issue. Would it be possible to provide a repository / script which we can run locally?

**Comment by CookieMonster70** [comment] 2024-04-15 13:09
@mxschmitt I found a page where you can repocude the behavior I have.
use the following script

`const page = await browser.newPage();
    await page.goto('https://scout.bsi-software.com/jswidgets/#tree');
    await page.waitForSelector('div[data-nodeid="ui15"]');
    await page.getByText('Welcome to the Scout JS Widgets ApplicationHere you will find a demonstration').focus();
    await page.locator('css=div[data-nodeid="ui15"]').click();
    await page.getByText('Image', { exact: true }).click();
    await page.locator('css=div[data-nodeid="ui35"]').click()
    await page.locator('css=div[data-nodeid="ui35"]').scrollIntoViewIfNeeded();
    await page.locator('css=div[data-nodeid="ui51"]').click()
    await page.locator('css=div[data-nodeid="ui51"]').scrollIntoViewIfNeeded();
    await page.locator('css=div[data-nodeid="ui68"]').click()
    await page.locator('css=div[data-nodeid="ui68"]').scrollIntoViewIfNeeded();
    await page.getByRole('treeitem', { name: ' Node #0' }).locator('div').click();`

if you let run the example above for e.g form intellij with npx playwright test --ui or in VSCode with "Show trace viewer"
Then the tree remains closed!
![image](https://github.com/microsoft/playwright/assets/25148194/4fe9fd94-fc36-419d-ac56-e71f681d0f95)

If you run the same example with VSCode "Show Browser" then tree is open.
![image](https://github.com/microsoft/playwright/assets/25148194/0e43f805-1ab2-46ac-8d7e-f1effd1c3837)

**Comment by mxschmitt** [comment] 2024-04-15 19:57
The reason for that is that Playwright is like a fast user. When it clicks, it records a snapshot immediately after it and then stops the test. Since no statements come after your last click. The application you are testing tho is slower, since they use animations to show the new page state (collapsed opened element). In Visual Studio Code the browser stays open, so you see the new page state. 

In this case to get the new page state recorded, you can use `await page.waitForTimeout(5_000)` - which will show that the new page state gets recorded and ends up as a snapshot in Trace Viewer. In real tests tho, we don't recommend that, since future Playwright API calls would record the new page state anyways.

**Comment by mxschmitt** [comment] 2024-04-16 14:27
What exact steps to you follow? Could you give us reproduction steps? I tried the following, which works for me:

```ts
test('test', async ({ page }) => {
  await page.goto('https://scout.bsi-software.com/contacts/?dl=outline-11770&i=contacts');
  await page.getByRole('treeitem', { name: ' Organizations' }).locator('div').click();
  await page.waitForTimeout(5_000);
});
```

**Comment by CookieMonster70** [comment] 2024-04-17 06:26
Hi tried exactly your steps and this is exactly my problem. It's not working if I let run the "Show Traceviewer or npx playwright tests --ui" I'm gettin the error.
``` log
Error: locator.click: Test timeout of 30000ms exceeded.
    Call log:
      - waiting for getByRole('treeitem', { name: ' Organizations' }).locator('div')


      20 | test('Github test', async ({ page }) => {
      21 |   await page.goto('https://scout.bsi-software.com/contacts/?dl=outline-11770&i=contacts');    
    > 22 |   await page.getByRole('treeitem', { name: ' Organizations' }).locator('div').click();
         |                                                                                ^
      23 |   await page.waitForTimeout(5_000);
      24 | });
```
If I let run them "Show in Browser it works. 
I setup a completly new Playwright Project and did the test again (Show Traceviewer), incl. playwright examples.
The playwright examples are running successfully on Chrome/Chromium but not the test above.

[trace.zip](https://github.com/microsoft/playwright/files/15006750/trace.zip)

**Comment by yury-s** [comment] 2024-04-18 01:09
That example gives different results in headed mode too for me, sometimes the tree item icon is just not there, e.g.:

<img width="622" alt="image" src="https://github.com/microsoft/playwright/assets/9798949/63d8e0f4-a461-479b-ba5f-5952c9b045da">

I also see this error in the devtools console:

<img width="547" alt="image" src="https://github.com/microsoft/playwright/assets/9798949/e4b89eb7-ff29-4ac4-a05e-f57f7e11e1fb">

If you think this is a bug in playwright, can you reduce it to a reliable example that we could run locally and be sure that it's not just server returning different results?

**Comment by yury-s** [comment] 2024-04-18 15:59
So far it looks like a bug in the web app which one can reproduce even manually. We don't have resources to debug large unfamiliar codebase like that, if you think this is a playwright bug, please reduce the example to a minimal reproduction and share with us, otherwise we can't act on this report.

I'm going to close this issue as this thread is getting too long without adding any new details to the original report. If you manage to extract a minimal repro, please file a new bug and upload it there.

**Closed by yury-s** 2024-04-18 15:59 UTC
