### ISSUE TITLE
[BUG] Playwright Runner Test filter doesn't work expected if ".map" comment present

### ISSUE THREAD

**Issue by mastrzyz** [microsoft/playwright#22123] opened 2023-03-31 17:08 UTC
### System info
- Playwright Version: 1.32.1
- Operating System: Windows 11
- Browser: All
- Other info: We leverage "Webpack" normally to package our test files but we are able to remove all of the "Webpackifying" except for the source map comment to repro this issue

### Source code

Create two test files in the same directory:
```js
// bad.playwright.ui.test.js
throw new Error("ERROR");
//# sourceMappingURL=bad.playwright.ui.test.js.map
```

```js
// good.playwright.ui.test.js
import { test, expect } from "@playwright/test";

test("has title", async ({ page }) => {
  await page.goto("https://playwright.dev/");
  await expect(page).toHaveTitle(/Playwright/);
});
```

//package.json
```json
{
  "name": "repro",
  "version": "1.0.0",
  "description": "repro",
  "main": "index.ts",
  "module": "index.ts",
  "private": true,
  "sideEffects": false,
  "license": "UNLICENSED",
  "dependencies": {
    "@playwright/test": "1.32.1",
    "playwright": "1.32.1"
  }
}
```

**Steps**
- `yarn install`
- `yarn playwright test good.playwright.ui.test`

**Expected**

I expect the `good.playwright.ui.test.ts` to execute and pass since it's the example test from Playwright

**Actual**
```
Error: ERROR

   at bad.playwright.ui.test.js:1

> 1 | throw new Error("ERROR");
    |       ^
  2 | //# sourceMappingURL=bad.playwright.ui.test.js.map
  3 |

    at Object.<anonymous> (C:\Users\...\Downloads\PortableCookie\bad.playwright.ui.test.js:1:7)

error Command failed with exit code 1.
```

For some reason the `bad` Playwright test gets executed, if I remove the `//# sourceMappingURL=bad.playwright.ui.test.js.map` comment it works fine .

This is very strange, I don't think this is by design.

For more context, we have "Jest" and "Playwright" test files side by side as we are migrating runners..

**Comment by yury-s** [comment] 2023-03-31 18:28
By default Playwright will read all files matching [`testMatch`](https://playwright.dev/docs/api/class-testproject#test-project-test-match) filter, if the file throws an error the test run will fail. You can either put playwright tests in a different folder then jest tests and point [testDir](https://playwright.dev/docs/api/class-testproject#test-project-test-dir) to that folder or you can adjust `testMatch` filter to match only playwright tests (perhaps add a suffix to the playwright test names?). Will that work for you?

**Comment by mastrzyz** [comment] 2023-03-31 18:30
@yury-s  something weird though this only reproduces on 1.32.

Also if I remove the `//# sourceMappingURL=bad.playwright.ui.test.js.map` it doesn't repro.


I'm a bit confused if I explicitly tell playwright only to look at `yarn playwright test good.playwright.ui.test` , shouldn't it only read that file? 


There are other usecases where test files could contain code which I don't want executed.

**Comment by mastrzyz** [comment] 2023-03-31 18:32
Here is an example : 

![image](https://user-images.githubusercontent.com/37447884/229201553-4de43e20-a35c-4795-9cce-a3775425218f.png)


![image](https://user-images.githubusercontent.com/37447884/229201598-9300fed1-9fe0-4cf0-99df-a62c753c6a53.png)

**Comment by mastrzyz** [comment] 2023-03-31 18:36
There could be an import with side-effects as well here.

**Comment by mastrzyz** [comment] 2023-03-31 18:41
Another issue we are seeing is , we have thousands of test files and a lot of them have big imports, this causes an OOM for us since they all get read here : 

![image](https://user-images.githubusercontent.com/37447884/229203600-f95d5ae4-4e75-4d1d-a3e9-e8bda5436046.png)

**Comment by yury-s** [comment] 2023-03-31 19:45
> @yury-s something weird though this only reproduces on 1.32.
> 
This is a side effect of improvement for source mapped files in 1.32, so it's expected to reproduce starting 1.32 only.

> Also if I remove the `//# sourceMappingURL=bad.playwright.ui.test.js.map` it doesn't repro.
> 
That's expected, playwright first reads the file to see if it contains source mapping url and will load it only there is a chance that it may map to another source which could match the filter.

> I'm a bit confused if I explicitly tell playwright only to look at `yarn playwright test good.playwright.ui.test` , shouldn't it only read that file?
> 
This is not the case, playwright can read the all files that satisfy testMatch filter but will only run the tests from the matching files. In this particular case we'll read the content of all matching files which contain sourceMappingURLs as they can be produced from the files matching the command line filter. See https://github.com/microsoft/playwright/issues/21204 for more details.

> This could lead to some hard to debug bugs , you don't expect all of the test files to start when you explicitly only specify one.

I agree that this may lead to some counter-intuitive behavior but this was a deliberate decision in favor of better support of source mappings (see the bug referenced above).

**Comment by yury-s** [comment] 2023-03-31 19:46
> Another issue we are seeing is , we have thousands of test files and a lot of them have big imports, this causes an OOM for us since they all get read here :

Please file a separate issue with a repro for that as it seems unrelated.

**Comment by mastrzyz** [comment] 2023-03-31 20:22
> > Another issue we are seeing is , we have thousands of test files and a lot of them have big imports, this causes an OOM for us since they all get read here :
> 
> Please file a separate issue with a repro for that as it seems unrelated.

I think it is related , we have some imports which have side effects and us running 1000 test files at once since they all have source maps causes us to get out of memory.



I'm not sure how this would scale, we have a giant repository and let's say we have 5k test spec files, we would need to potentially load all of them into memory just to run one spec file if I understand here?

**Comment by mastrzyz** [comment] 2023-03-31 20:26
I think we need a way to explicitly say ,  ` I only want these test files` , right?

**Comment by yury-s** [comment] 2023-03-31 20:56
> I'm not sure how this would scale, we have a giant repository and let's say we have 5k test spec files, we would need to potentially load all of them into memory just to run one spec file if I understand here?

If the tests run today, it should be no problem with playwright too. When you run the entire suite all of the matching files would have to be loaded anyway. When applying file name filter some of the file reads may be skipped but this is just an optimization, I'd discourage you from relying on that. If you have a real example where the memory footprint of a test harness becomes a bottleneck we can have a look. So far it sounds that it is caused by loading unrelated files and you can use the [aforementioned solution](https://github.com/microsoft/playwright/issues/22123#issuecomment-1492418933) to avoid loading unnecessary files into the playwright harness.

**Comment by mastrzyz** [comment] 2023-03-31 20:59
> > I'm not sure how this would scale, we have a giant repository and let's say we have 5k test spec files, we would need to potentially load all of them into memory just to run one spec file if I understand here?
> 
> If the tests run today, it should be no problem with playwright too. When you run the entire suite all of the matching files would have to be loaded anyway. When applying file name filter some of the file reads may be skipped but this is just an optimization, I'd discourage you from relying on that. If you have a real example where the memory footprint of a test harness becomes a bottleneck we can have a look. So far it sounds that it is caused by loading unrelated files and you can use the [aforementioned solution](https://github.com/microsoft/playwright/issues/22123#issuecomment-1492418933) to avoid loading unnecessary files into the playwright harness.

Let's ignore the jest issue, we have tests which call imports that have side effects and also call functions outside the of the test body.


Normally the tests are called one by one with `--workers=1` so the imports with side effects don't affect each other. Now they are all called at once and we have a large console spam from their logging as well as big memory usage.

**Comment by mastrzyz** [comment] 2023-03-31 21:01
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/37447884/229229224-ff94c023-ddd7-4438-af25-1388c5dc8d56.png">
The issue is also reproing if we have functions in the describe block itself.

**Comment by yury-s** [comment] 2023-03-31 22:39
Yes, currently test.describe's callback will be invoked when the test file is loaded. None of the tests will run though if they don't match the filter.

**Comment by mastrzyz** [comment] 2023-04-01 00:41
> Yes, currently test.describe's callback will be invoked when the test file is loaded. None of the tests will run though if they don't match the filter.

Any advice for what we can do ? We have the majority of our test having side effects in the describe block.

can this functionality be configurable for people trying to migrate from a other runner ? It’s going to be a large effort for us to remove all side effects so would prefer to first migrate runners then remove side effects

**Closed** 2023-04-04 02:49 UTC
Labels: v1.33

**Comment by mastrzyz** [comment] 2023-04-28 17:08
Confirmed working in 1.33
