### ISSUE TITLE
[Bug]: python add_locator_handler does not seem to work

### ISSUE THREAD

**Issue by 10tal** [microsoft/playwright#31312] opened 2024-06-14 06:55 UTC
### Version

1.44.0

### Steps to reproduce

This is a basic code example.

```
from time import sleep
from playwright.sync_api import sync_playwright


with sync_playwright() as playwright:
    browser = playwright.chromium.launch(headless=False)  # Set headless=False if you want to see the browser
    page = browser.new_context().new_page()
    page.goto('http://playwright.dev')

    def handler():
        page.get_by_role("link", name="GET STARTED").click()
    page.add_locator_handler(page.get_by_role("link", name="GET STARTED"), handler)
    # page.get_by_role("link", name="GET STARTED").click()
    sleep(5)
```

If I uncomment - page.get_by_role("link", name="GET STARTED").click(), the "GET STARTED" is being clicked, but when using only the add_locator_handler, nothing happens.

### Expected behavior

I expect to see the "GET STARTED" button being clicked and to be moved to other page - https://playwright.dev/python/docs/intro

### Actual behavior

Nothing happens

### Environment

```shell
System:
  OS: macOS 14.5
  CPU: (11) arm64 Apple M3 Pro
  Memory: 515.63 MB / 18.00 GB
Binaries:
  Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
  npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
Languages:
  Bash: 3.2.57 - /bin/bash
```

**Comment by mxschmitt** [comment] 2024-06-14 07:45
Most likely sleep is the issue, see here: https://playwright.dev/python/docs/library#timesleep-leads-to-outdated-state

**Comment by 10tal** [comment] 2024-06-14 08:01
> Most likely sleep is the issue, see here: https://playwright.dev/python/docs/library#timesleep-leads-to-outdated-state

I removed the sleep, added a print in the handler function and nothing is printed.

```
from playwright.sync_api import sync_playwright


with sync_playwright() as playwright:
    browser = playwright.chromium.launch(headless=False)  # Set headless=False if you want to see the browser
    page = browser.new_context().new_page()
    page.goto('http://playwright.dev')

    def handler():
        page.get_by_role("link", name="GET STARTED").click()
        print(page.title())
    page.add_locator_handler(page.get_by_role("link", name="GET STARTED"), handler)
    # page.get_by_role("link", name="GET STARTED").click()

```

**Comment by yury-s** [comment] 2024-06-14 16:56
The last snippet works as expected if you uncomment the click. Note that the handler is only invoked when you try to perform an action, so if the last line is commented out the handler will not be called either.

**Comment by yury-s** [comment] 2024-06-14 16:57
"Playwright checks for the overlay every time before executing or retrying an action that requires an [actionability check](https://playwright.dev/python/docs/actionability), or before performing an auto-waiting assertion check." - from [the documentation](https://playwright.dev/python/docs/api/class-page#page-add-locator-handler). Closing as it's working as intended.

**Closed by yury-s** 2024-06-14 16:57 UTC
