### ISSUE TITLE
[Bug]: Sharding not working as per playwright documentation

### ISSUE THREAD

**Issue by Shaun-Regan** [microsoft/playwright#33911] opened 2024-12-09 09:25 UTC
### Version

1.48.1

### Steps to reproduce

- Have multiple projects (we have 4 - chromium, Firefox, Edge and Chrome)
- Have multiple .spect.ts files with at least 2 tests per .spec.ts file
- In playwright.config.ts Set fullyParallel: false,
- In four different terminal windows set npx playwright test --shard=1/4, 2/4 etc
- Note that all 4 terminals start to execute the same test in the same .spec.ts file but in a different browsers.
- Playwright documentation states "Without fullyParallel: Tests are split at the file level, so to balance the shards, it's important to keep your test files small and evenly sized.
- The bug is that tests are not being split at file level as all 4 shards, in our example, are running tests in the same file
- Please don't close off again as 

"@[Skn0tt](https://github.com/Skn0tt)
Skn0tt
[4 days ago](https://github.com/microsoft/playwright/issues/33871#issuecomment-2520948502)
Member
From what you're outlining, everything works as expected here. If you believe there's a bug, please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!"

as my end user experience is not as per your own documentation.  I believe I had already provided self-contained reproduction steps but have elaborated above.  If not good enough then please advise what's missing and leave issue log open so that I can add/amend.  Just closing off and asking for issue to be relogged is very frustrating

No where, that I can find, do you state that shards will execute the same tests, in the same test files, in multiple browsers/projects at the same time.

Thanks

### Expected behavior

Playwright documentation states

Without fullyParallel: Tests are split at the file level, so to balance the shards, it's important to keep your test files small and evenly sized.

I'm expecting each shard to own the test file assigned, to not share a test file (as per documentation) and execute all tests, in all browsers before moving onto the next test file assigned to the shard.

### Actual behavior

Each shard executes the same test in the same test .spec.ts file at the same time but in a different browser. With fullyParallel: false, I would expect a shard to own a test file and execute all tests in all browsers. 

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 3.78 GB / 15.61 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.95.3 - C:\Users\shaun.regan\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.48.1 => 1.48.1
```

**Comment by yury-s** [comment] 2024-12-09 19:08
This is actually working as intended, let me explain. With 4 projects each test will run 4 times, current scheduling mechanism distributes the tests evenly across shards so that shard 1 runs entire suite for project 1, then shard 2 runs entire suite with project 2 etc. In the end each shard will run N tests from the suite which matches the documentation. Looks like you expect tests (by test I mean test case, which is test in a particular project) to be assigned to the shards differently. There is an open feature request for this https://github.com/microsoft/playwright/issues/33386 and also related https://github.com/microsoft/playwright/issues/9297.

Is there a particular reason why you want each test file to be assigned to a single shard as opposed to current behavior?

**Comment by Shaun-Regan** [comment] 2024-12-10 09:44
Hi

Thanks for the reply.

The section from the playwright documentation I'm referring to is below

"Without fullyParallel: **Tests are split at the file level**, so to balance the shards, it's important to keep your test files small and evenly sized."

how is what you've described above matching the documentation?  If exampletest.spec.ts is run multiple times by different shards how does that equate to multiple test files being split across shards?

The issue I have is with each shard running the same test case in the same test file at the same time, but in different browsers/projects, our functionality is causing issues with some information about the state a users leaves our app on close (as the same user is opening and closing tabs etc as part of the test case being executed, at exactly the same time in other browsers).  Are you advising that I currently can not configure the shards to Split test files across a shard automatically (as I though the documentation stated as **Without fullyParallel** would function?)

e.g.


testfile1.spec.ts (Multiple test cases in each file)
testfile2.spec.ts  (Multiple test cases in each file)
testfile3.spec.ts  (Multiple test cases in each file)
testfile4.spec.ts  (Multiple test cases in each file)
testfile5.spec.ts  (Multiple test cases in each file)
testfile6.spec.ts  (Multiple test cases in each file)
etc

shard 1/2 would be assigned a set of files to own completely  (e.g. testfile1.spec.ts, testfile2.spec.ts, testfile3.spec.ts ) including running the test cases in each file in each browser.

shard 2/2 would be assigned a set of files to own  (e.g. testfile4.spec.ts, testfile5.spec.ts, testfile6.spec.ts ) completely including running the test cases in each file as each browser.

The example outcome above is the expected outcome I would expect from reading "Without fullyParallel: **Tests are split at the file level**, so to balance the shards, it's important to keep your test files small and evenly sized." this line in your documentation.  

Should the playwright documentation read  **Test cases are split at the file level**?  and its extra configuration to force shards to run each browser/project sequentially (so not to cause issues with the same test case running in different browsers at exactly the same time)? 

Thanks

**Comment by yury-s** [comment] 2024-12-10 19:57
> The issue I have is with each shard running the same test case in the same test file at the same time, but in different browsers/projects, our functionality is causing issues with some information about the state a users leaves our app on close (as the same user is opening and closing tabs etc as part of the test case being executed, at exactly the same time in other browsers). Are you advising that I currently can not configure the shards to Split test files across a shard automatically (as I thought the documentation stated as Without fullyParallel would function?)

Yes, your understanding is correct. To address your problem, instead of using separate user account per file, we recommend using a user account per test worker process. It avoids concurrency issue when the same user account is used in several tests in parallel. See [this guide](https://playwright.dev/docs/auth#moderate-one-account-per-parallel-worker) for detailed explanation.

> The example outcome above is the expected outcome I would expect from reading "Without fullyParallel: Tests are split at the file level, so to balance the shards, it's important to keep your test files small and evenly sized." this line in your documentation.

I agree that we could improve documentation to make it less confusing in cases like yours.

**Closed** 2024-12-10 22:02 UTC
