### ISSUE TITLE
[BUG] SEC_ERROR_UNKNOWN_ISSUER on Firefox with Self Signed Certificates.

### ISSUE THREAD

**Issue by karanshah-browserstack** [microsoft/playwright#8272] opened 2021-08-18 05:50 UTC
**Context:**
- Playwright Version: 1.12
- Operating System: Mac
- Node.js version: 14.6
- Browser: Firefox
- Extra: NA

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {firefox} = require('playwright');

(async () => {
  const browser = await firefox.launch();
  const page = await browser.newPage("Page with SELF SIGNED certificate");
  // ...
})();
```

**Describe the bug**

We are facing issues with Self Signed Certificates on firefox and while doing browser.newPage() we are getting SEC_ERROR_UNKNOWN_ISSUER.
Can we allow please fix this behaviour for Self Signed Certificates on firefox?

**Comment by mxschmitt** [comment] 2021-08-18 06:09
https://playwright.dev/docs/api/class-browser#browser-new-context-option-ignore-https-errors

Pass`ignoreHTTPSErrors` when creating a context. You can also pass it to browser.newPage because it will create a context for you internally.

**Comment by karanshah-browserstack** [comment] 2021-08-18 09:53
@mxschmitt Is there a reason why it can't be supported by default on firefox browsers?

**Comment by mxschmitt** [comment] 2021-08-18 10:06
Because we want security by default.

Also its a duplicate of #8251.

**Closed by mxschmitt** 2021-08-18 10:07 UTC
Labels: triaging

**Comment by Mone71** [comment] 2021-08-18 10:08
Thanks
