### ISSUE TITLE
[BUG] SharedArrayBuffer is not enabled on Webkit

### ISSUE THREAD

**Issue by swissspidy** [microsoft/playwright#28513] opened 2023-12-06 09:17 UTC
### System info
- Playwright Version: v1.40.1
- Operating System: macOS
- Browser: WebKit
- Other info:

### Source code

See #8178 where the same thing was reported for Firefox before.

SharedArrayBuffer is not enabled on Playwright build of WebKit, where it has been natively available in Safari for a long time now.

```js
it.only('SharedArrayBuffer should work', async function({contextFactory, httpsServer, browserName}) {
  const context = await contextFactory({ ignoreHTTPSErrors: true });
  const page = await context.newPage();
  httpsServer.setRoute('/sharedarraybuffer', (req, res) => {
    res.setHeader('Cross-Origin-Opener-Policy', 'same-origin');
    res.setHeader('Cross-Origin-Embedder-Policy', 'require-corp');
    res.end();
  });
  await page.goto(httpsServer.PREFIX + '/sharedarraybuffer');
  // await page.goto(httpsServer.PREFIX + '/empty.html');
  // await page.goto(server.PREFIX + '/empty.html');
  expect(await page.evaluate(() => typeof SharedArrayBuffer)).toBe('function');
});
```

**Steps**

1. Open Playwright Build of WebKit
2. Open a cross-origin isolated website
3. Open Console and type in `typeof SharedArrayBuffer` (should be a function) or `window.crossOriginIsolated` (should be true, not undefined)

https://cross-origin-isolation.glitch.me/ can be used to test this.

**Expected**

Cross-origin isolation should work in the WebKit build and I should be able to use `SharedArrayBuffer`.

**Actual**

No cross-origin isolation, no SharedArrayBuffer :(

**Comment by mxschmitt** [comment] 2023-12-06 17:34
Looks like a duplicate of https://github.com/microsoft/playwright/issues/14043.

**Closed** 2023-12-08 18:50 UTC
