### ISSUE TITLE
[Bug]: blank screenshots for .toHaveScreenshot()

### ISSUE THREAD

**Issue by jpratt2** [microsoft/playwright#32040] opened 2024-08-06 22:53 UTC
### Version

1.45.3

### Steps to reproduce

I can duplicate the issue seen at https://github.com/microsoft/playwright/issues/21657 and solve it in the same way --using his static screenshot solution. I have a public page you can use to duplicate it: https://www.adobe.com

### Expected behavior

to see a screenshot

### Actual behavior

a blank screenshot is seen

### Additional context

 Sample code
```
const {test, expect} = require ('@playwright/test');

test('basic screenshot comparison', async ({ page }) => {
    await page.goto('https://www.adobe.com');
    await page.waitForTimeout(5000);
    await expect(page).toHaveScreenshot({fullPage: true });
})
```
Note: this doesn't have to be a full page screenshot, even a typical screenshot of just the marquee shows as a white screen

### Environment

```shell
Windows 11, Google Chrome
```

**Comment by yury-s** [comment] 2024-08-07 01:20
I can't reproduce it. I'm getting net::ERR_HTTP2_PROTOCOL_ERROR in headless when navigating to that page, in headed mode the test passes just fine. Do you have an example with a local page (which would be repeatable), as Adobe may well be serving different content based on the request source/headers etc?

**Comment by yury-s** [comment] 2024-08-12 18:10
Closing, as we need to be able to reproduce the problem to make this report actionable.

**Closed by yury-s** 2024-08-12 18:10 UTC

**Comment by PollySt** [comment] 2025-03-17 14:35
I'm facing the same issue, but only in CI (mcr.microsoft.com/playwright:v1.49.1-jammy) and only webkit (iPhone 13, iPad Mini). No issues locally, but in Github Actions it takes a blank white screenshot all the time. 

<img width="361" alt="Image" src="https://github.com/user-attachments/assets/412be18b-4181-4576-aae2-3aba3322114b" />

actual screenshot: 

![Image](https://github.com/user-attachments/assets/ca2bb45a-1f58-41c7-85e0-801c4343a6d0)

Unfortunately, I can't share a repo to reproduce, but I can share a code sample:
      const deviceConfig = devices['iPhone 13']
      browser = await playwright[deviceConfig.defaultBrowserType].launch()
      context = await browser.newContext({ ...deviceConfig })

      const page = await context.newPage()
      await page.goto(CUSTOMER_APP_ENDPOINTS.loginEmail)
      await page.getByAltText("background").waitFor()
      await page.waitForTimeout(2000)
      await expect(page).toHaveScreenshot(`${ENV}-default-login-page-iPhone-13.png`)

Do you have any idea how to solve it?
