### ISSUE TITLE
[Question]: How to use 'detached' in waitForSelector() function.

### ISSUE THREAD

**Issue by Lakshmi-Yaswanth** [microsoft/playwright#8034] opened 2021-08-06 11:38 UTC
### Your question

As we can see in the documentation 
`https://playwright.dev/docs/api/class-elementhandle#element-handle-wait-for-element-state`
We have WaitForSelector() has 
1.'attached' 
2.'detached' 
3.'visible' 
4.'hidden'
But while writing the script I can only view Visible and attached options only.
```
protected async invisiblity(ele) {
    const element = await this.page.$(ele);
    await element.waitForSelector(ele,{state:" "})
  }
```
is there any way we can use detached of a selector.
Thank u .

**Comment by mxschmitt** [comment] 2021-08-06 11:41
This looks like a duplicate of https://github.com/microsoft/playwright/issues/7263

**Comment by Lakshmi-Yaswanth** [comment] 2021-08-06 11:44
Thank u @mxschmitt for your quick response.

**Closed** 2021-08-06 11:53 UTC
Labels: triaging
