### ISSUE TITLE
[BUG] Serious performance degregation on 1.29

### ISSUE THREAD

**Issue by Tallyb** [microsoft/playwright#19946] opened 2023-01-08 18:21 UTC
**Context:**
- Playwright Version:1.29.2 
- Operating System: Mac & Linux (CI)
- Node.js version: 18.12
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chromium
- Extra: [any specific details about your environment]

Running a test against storybook. The test has 1000 rows of ag-grid. 
A very simple tests

```
      const { component, story } = await goToComponent('communicate-document-appdocumentspage--permissions-web');
      await component.locator('yoo-ag-grid >> yoo-context-menu').nth(4).click();
      await expect(story.locator('yoo-context-menu-dialog >> li:has-text("Download file")')).not.toBeVisible();
      await expect(story.locator('yoo-context-menu-dialog >> li:has-text("Email")')).not.toBeVisible();
      await expect(story.locator('yoo-context-menu-dialog >> li:has-text("Copy link")')).toBeVisible();
      await expect(story.locator('yoo-context-menu-dialog >> li:has-text("Insights")')).toBeVisible();
```
Running in 1.28: ~ 13 seconds per test. 
Running in 1.29 - 60 seconds causes timeout. 90 seconds pass. 

In general we see some performance degradation in PW 1.29, but this is a clear example.

**Comment by mxschmitt** [comment] 2023-01-09 11:25
Can you share a repro with us so we can debug it ourselves?

**Comment by AlexKomanov** [comment] 2023-01-09 18:27
Must upvote it. We also see some degradation in version 1.29.
Still don't have a repo (can't share the work;s repo), but I'll try to provide something

**Comment by aslushnikov** [comment] 2023-01-10 07:14
@Tallyb I tried to repro this somehow, but to no avail. So repro would be incredibly helpful!

Here's what I tried:
```html
<!-- index.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <script src="https://unpkg.com/ag-grid-community/dist/ag-grid-community.min.js"></script>
  <script src="main.js"></script>
</head>
<body>
  <div id="myGrid" style="height: 100vh; width:100vw;" class="ag-theme-alpine"></div>
</body>
</html>
```

```js
// main.js
var columnDefs = [
  {headerName: "Name", field: "name"},
  {headerName: "Value", field: "value"},
];

// specify the data
var rowData = [];

for (let i = 0; i < 1000; ++i)
  rowData.push({ name: 'name ' + i, value: 'value ' + i });

// let the grid know which columns and what data to use
var gridOptions = {
  columnDefs: columnDefs,
  rowData: rowData
};

// setup the grid after the page has finished loading
document.addEventListener('DOMContentLoaded', function() {
    var gridDiv = document.querySelector('#myGrid');
    new agGrid.Grid(gridDiv, gridOptions);
});
```

```ts
// a.spec.ts
import { test, expect } from '@playwright/test';

test('should work', async ({ page }) => {
  await page.goto('http://localhost:1234');
  for (let i = 0; i < 1000; ++i)
    await expect(page.getByText('name 0')).toBeVisible();
});
```

This is a pretty naive attempt to reproduce, but it didn't work: it takes only 2 seconds on my machine to complete.
So any help with repro'ing would go a long way!

**Comment by Tallyb** [comment] 2023-01-11 13:38
@aslushnikov - I will contact you privately to send you the problematic story

**Comment by aslushnikov** [comment] 2023-01-11 17:44
@Tallyb feel free to reach out on discord!

**Comment by aslushnikov** [comment] 2023-01-12 05:19
This is a Chromium regression; filed upstream as https://bugs.chromium.org/p/chromium/issues/detail?id=1406736

**Comment by aslushnikov** [comment] 2023-01-18 04:22
The regression is handled by the Chromium team; we reported this to StencilJS team as well and they might address it on their end: https://github.com/ionic-team/stencil/issues/3978

Closing this since no more actions are required from the Playwright team.

**Closed by aslushnikov** 2023-01-18 04:22 UTC
Labels: browser-chromium, upstream, v1.30
