### ISSUE TITLE
[BUG]  getByRole and getByText Locators Truncate Strings Over 29 Characters in Playwright 1.40.1

### ISSUE THREAD

**Issue by pakhilov** [microsoft/playwright#28586] opened 2023-12-11 23:28 UTC
### System info
- Playwright Version: [v1.40.1]
- Operating System: [All.]
- Browser: [Chromium]
There appears to be an unexpected truncation of strings over 29 characters long in Playwright's getByRole and getByText locators. This is causing issues when trying to select elements that have visible text exceeding this limit.

**Steps**
Install Playwright version 1.40.1.
Write a test using getByRole or getByText to locate an element with text content (for getByText or for option in getByRole) longer than 29 characters.
Execute the test and observe the behavior.

**Expected**

The getByRole and getByText locators should be able to match and select elements based on the full string provided, without any limitation on the length of the string.

**Actual**

When providing strings longer than 29 characters to getByRole and getByText, the locators seem to truncate the string, which leads to element selection failures.

![Screenshot 2023-12-11 153755](https://github.com/microsoft/playwright/assets/10390058/cdf207e3-c22a-4255-afd5-58bc76bdd599)

**Comment by pakhilov** [comment] 2023-12-11 23:39
![Screenshot 2023-12-11 153907](https://github.com/microsoft/playwright/assets/10390058/937c3018-1f07-4d08-a4c7-17cc25c0dce2)

**Comment by pakhilov** [comment] 2023-12-12 00:01
expected example generated with Playwright version 1.38
![Screenshot 2023-12-11 160050](https://github.com/microsoft/playwright/assets/10390058/a58ff34a-358e-4e3c-81bb-dcf14f5103e3)

**Comment by mxschmitt** [comment] 2023-12-12 00:13
Hey! This was an intentional change we made, we are curious why it does not work for you. What do you mean with:

> When providing strings longer than 29 characters to getByRole and getByText, the locators seem to truncate the string, **which leads to element selection failures**.

Thanks!

**Comment by pakhilov** [comment] 2023-12-12 00:21
Thanks for reaching out. Our test framework uses locators with strings longer than 29 characters, essential for accurate element identification. Since the update, these longer strings seem truncated, causing selection issues. Could you advise on handling longer string locators in the new Playwright version?

**Comment by mxschmitt** [comment] 2023-12-12 01:06
Do you mean with selection issues that old code is not working anymore or that codegen will produce different (shorter) locators compared to previous Playwright versions?

Having a self-contained reproducible or exact repro steps would help us a ton in order to debug this issue further, thanks!

**Comment by pakhilov** [comment] 2023-12-12 02:16
![Screenshot 2023-12-11 181235](https://github.com/microsoft/playwright/assets/10390058/e16accd5-1c9e-40b7-8786-bf2f10752c84)
You are right, the old code no longer works. We can wait to see how quickly this problem becomes popular here. What are the benefits of this change? There were some attempts to limit the screen reader to 145 symbols. Why did you choose 29?

**Comment by mxschmitt** [comment] 2023-12-12 02:41
Playwright code should continue to work, if it stops working, its clearly a regression on our side.

I tried to reproduce with the following, but was not able to. Could you help me to find out what I am doing differently?

```ts
test('has title', async ({ page }) => {
  await page.goto('https://example.com');
  await page.setContent(`
  <button>
    Is the word pneumonoultramicroscopicsilicovolcanoconiosis real?
  </button>`)
  await page.getByRole("button", {
    name: "Is the word pneumonoultramicroscopicsilicovolcanoconiosis real?",
    exact: true,
  }).click()
  // This click above should end up in a timeout error (accoridn gto
  await page.pause()
});
```

Just to verify: I observed that codegen generates shorter text while the old code (which the long text) continues to work. This seems expected, maybe I am testing something different or not running into your specific issue.

Thanks!

**Comment by pakhilov** [comment] 2023-12-12 02:59
Certainly. To reproduce the issue, you should have a combo box or an autocomplete dropdown with multiple options, where at least one option's name exceeds 29 characters.

You can use a function similar to the following in your Page Object Model (POM):
``` Javascript
async selectFromAutocompleteDropdown(inputValue: string): Promise<this> {
    await this._autocompleteDropdown.click(); // Activate the dropdown
    await this._autocompleteDropdown.fill(inputValue); // Fill in the input to filter options
    // Ensure the option is now in the DOM and can be selected
    await this._page.getByRole("option", { name: inputValue, exact: true }).click(); 
    return this;
}
```

This function, selectFromAutocompleteDropdown, demonstrates the process of selecting an option from an autocomplete dropdown, particularly when dealing with long option names.

**Comment by mxschmitt** [comment] 2023-12-12 03:27
I tried this as well, the code before the click should not matter:

```ts

test('has title', async ({ page }) => {
  await page.goto('https://example.com');
  await page.setContent(`
    <div role="listbox">
      <div role="option">Is the word pneumonoultramicroscopicsilicovolcanoconiosis real?</div>
    </div>
  `);
  await page.getByRole("option", {
    name: "Is the word pneumonoultramicroscopicsilicovolcanoconiosis real?",
    exact: true,
  }).click();
});
```

Could you adjust the HTML so it matches your scenario and provide it to us?

**Comment by pakhilov** [comment] 2023-12-12 07:14
I dedicated some time to finding a similar example:

```Javascript
test('dynamic combobox with filtering', async ({ page }) => {
  await page.goto(
    'https://vaadin.com/docs/latest/components/multi-select-combo-box',
  )

  //await page.locator('#toggleButton').click()
  await page.getByLabel('Countries').fill('south')
  const optionWithLong = page.getByRole('option', {
    name: 'South Georgia and the South Sandwich Islands',
    exact: true
  })
  await optionWithLong.click()
  
})
```

Interestingly, my website uses Material UI, and surprisingly, after switching back to Playwright version 1.40.1, I am unable to reproduce this issue

**Comment by mxschmitt** [comment] 2023-12-12 19:48
Its passing for me too. I'll keep it open for a few more days but otherwise would close it since there is no repro?

**Comment by pakhilov** [comment] 2023-12-12 19:49
Yes, I'm agree.

**Closed** 2023-12-13 16:38 UTC
