### ISSUE TITLE
[BUG] Electron app launches correctly, but await electron.launch is never resolved

### ISSUE THREAD

**Issue by Slapbox** [microsoft/playwright#19854] opened 2023-01-04 01:50 UTC
**Context:**
- Playwright Version: 1.29.1
- Operating System: Linux (Ubuntu 22.04)
- Node.js version: 16.17.0
- Browser: Electron 
- Extra: [any specific details about your environment]

**Code Snippet**

```javascript
import { _electron as electron } from 'playwright';

test.beforeAll(async () => {
  const electronApp = await electron.launch({
    args: ['ABSOLUTE_PATH/release/dev/linux-unpacked/resources/app.asar/app/dist/main.prod.js'],
    executablePath: 'ABSOLUTE_PATH/release/dev/linux-unpacked/resources/app.asar/app/dist/main.prod.js'
  });
})
```

**Describe the bug**

I adapted this code from [electron-playwright-example](https://github.com/spaceagetv/electron-playwright-example) and tested it with [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate) and [secure-electron-template](https://github.com/reZach/secure-electron-template) and it works in all three of those projects - but for our project (which is adapted from the latter two) it hangs indefinitely.

I tried to locate the code responsible for `electron.launch` to investigate possible causes.

Our Electron app is loaded via the `app:` protocol, disables `nodeIntegration` and enables a `preload` script - but all the same is true in `secure-electron-template` as well - so I can't figure out why it fails to resolve `await electron.launch(...)`

The strangest thing to me is that the app runs entirely correctly, the Playwright code appears to run correctly, but still we get stuck on the `await`.

**Comment by mxschmitt** [comment] 2023-01-04 14:04
Could you try the latest dev build? there we made a related fix:

```
npm i -D playwright@next
```

**Comment by Slapbox** [comment] 2023-01-05 21:48
Thanks very much for your reply @mxschmitt. Unfortunately `playwright@next` and `playwright/test@next` are now installed, but no difference.

**Comment by mbaer3000** [comment] 2023-01-06 10:20
We have had the exact same issue for a couple of months (so apparently no regression with 1.29.1). electron.launch not resolving while the app starts. It seems to depend on the type of build we derive our Electron app from; trying to find the cause, will post here in case we find it.

**Comment by Slapbox** [comment] 2023-01-06 23:16
Thanks so much @mbaer3000! I haven't given this a try yet, but I feel quite confident that that's the issue!

**Closed** 2023-01-07 00:05 UTC
Labels: triaging

**Comment by Slapbox** [comment] 2023-01-07 00:06
@mxschmitt this should maybe be added to the documentation but I wouldn't know where.

There's no way to run Playwright against the development environment version of the app, is there? That would be great to see in the future.

Thank you again for your help.

**Comment by Slapbox** [comment] 2023-01-10 20:53
I guess if we need to transpile our `index.js` or any downstream code that we'll still need to bundle it, right?

**Comment by mxschmitt** [comment] 2023-01-10 21:34
yes.

**Comment by SabFloki** [comment] 2023-02-21 05:48
> We have had the exact same issue for a couple of months (so apparently no regression with 1.29.1). electron.launch not resolving while the app starts. We have now determined that it's because of https://www.electronjs.org/docs/latest/tutorial/fuses#nodecliinspect set to "off":
> 
> Quote: "The nodeCliInspect fuse toggles whether the --inspect, --inspect-brk, etc. flags are respected or not. When disabled it also ensures that SIGUSR1 signal does not initialize the main process inspector. Most apps can safely disable this fuse." Well, apparently apps should rather not disable this fuse if they want to be run by Playwright.

Can you please tell how to set 'FuseV1Options.EnableNodeCliInspectArguments' true as I am facing electron.launch timeout in playwright?

**Comment by Slapbox** [comment] 2023-02-21 21:30
@SabFloki are you setting Electron Fuses? If you're not setting them, then that's not your issue because I don't believe any of them are set by default.
