### ISSUE TITLE
[BUG]Webkit doesn't launch

### ISSUE THREAD

**Issue by fawazahmed0** [microsoft/playwright#2840] opened 2020-07-05 00:08 UTC
**Context:**
- Playwright Version: 1.1.1
- Operating System: Windows 7
- Node version: 12.18.0
- Browser: Webkit

**Code Snippet**

```javascript
var { webkit } = require('playwright');

(async () => {
  const browser = await webkit.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto("https://www.example.com/")

  await browser.close();
})().catch(console.error);
```
**Error Output:**

      pw:api => webkit.launch started +0ms
      pw:api <= webkit.launch failed +30s
    TimeoutError: Timeout 30000ms exceeded during webkit.launch.
    ==================== webkit.launch logs ====================
    <launching> C:\Users\Nawaz\AppData\Local\ms-playwright\webkit-1269\Playwright.ex
    e --inspector-pipe --headless --no-startup-window
    <launched> pid=4628
    ============================================================
    Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs
    .
        at ProgressController.run (C:\Users\Nawaz\node_modules\playwright\lib\progre
    ss.js:72:30)
        at Object.runAbortableTask (C:\Users\Nawaz\node_modules\playwright\lib\progr
    ess.js:24:23)
        at WebKit.launch (C:\Users\Nawaz\node_modules\playwright\lib\server\browserT
    ype.js:61:42)
        at C:\Users\Nawaz\Downloads\qdb\scraping\injectscript.js:8:32
        at Object.<anonymous> (C:\Users\Nawaz\Downloads\qdb\scraping\injectscript.js
    :21:3)
        at Module._compile (internal/modules/cjs/loader.js:1138:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
        at Module.load (internal/modules/cjs/loader.js:986:32)
        at Function.Module._load (internal/modules/cjs/loader.js:879:14)
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js
    :71:12)
    

![-2020-jul-5-001](https://user-images.githubusercontent.com/20347013/86522856-b0884280-be81-11ea-9986-c499c136e8df.jpg)

**Comment by fujii** [comment] 2020-07-09 19:52
See also: https://github.com/microsoft/playwright/issues/2548

**Comment by aslushnikov** [comment] 2020-07-09 23:25
Close as dupe of #2548

**Closed by aslushnikov** 2020-07-09 23:25 UTC
