### ISSUE TITLE
[Feature]: Running the test is in live mode in ui mode("Small changes, big results.")

### ISSUE THREAD

**Issue by chensce** [microsoft/playwright#30812] opened 2024-05-15 01:34 UTC
### 🚀 Feature Request

Make the running test more live,
it is only updated the picture when the action comand excuted in the snapshot panel
if we could update the picture in the snapshot panel when the filmstrip add the snapshot.
reactive the snapshot panel from filmstrip panel.

### Example

<img width="881" alt="Screen Shot 2024-05-15 at 09 29 13" src="https://github.com/microsoft/playwright/assets/93559562/a916179e-4a14-425e-ad3c-bdaff00b8eea">

### Motivation

Make the running test more live

**Comment by yury-s** [comment] 2024-05-15 16:14
What problem does it solve? You can already run in haded mode and see what exactly is happening with the page.

**Comment by chensce** [comment] 2024-05-20 06:25
This can make the running live event in headless mode.
We can do it just update the picture in the snapshot panel when the filmstrip add the snapshot.

**Comment by pavelfeldman** [comment] 2024-05-20 15:53
> We can do it just update the picture in the snapshot panel when the filmstrip add the snapshot.

I'm sorry I don't follow what this means exactly.

**Comment by pavelfeldman** [comment] 2024-05-20 15:56
Dupe of https://github.com/microsoft/playwright/issues/30814

**Closed by pavelfeldman** 2024-05-20 15:56 UTC
