### ISSUE TITLE
Chrome headless (persistent) doesn't save/load cookies on windows

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#717] opened 2020-01-28 20:59 UTC
On Windows, headless chrome can't read cookies from a userdatadir. It is specific to cookies, localStorage works. The `Default\Cookies` file exists, and is a valid SQLite table, but it has no rows. Launching with headful, I can see the cookie in the SQLite file, but launching headless chrome afterwards clears the file again, and doesn't read the cookie.

Possibly related to, Puppeteer/Puppeteer#4111, but where that was flaky, this is consistently broken.

#680

**Comment by meotimdihia** [comment] 2020-02-27 04:38
Confirmed, my problem is the same. Take hours to figure this.

**Comment by emko** [comment] 2020-04-13 08:12
i though i was going crazy, i am on win10 same problem headless true cookies don't get restored with it false it works fine, is there a workaround?

**Comment by sameh81** [comment] 2020-06-20 00:56
We need a solution for this issue please

**Comment by kajojify** [comment] 2020-10-08 23:34
Hello guys. Still face it on Version 86.0.4240.75 (Official Build) (64-bit) for Windows 10.

**Comment by ctataryn** [comment] 2020-10-11 02:46
> Confirmed, my problem is the same. Take hours to figure this because it works fine on my Ubuntu machine.

@meotimdihia maybe you just got lucky on Ubuntu with an older version of Chromium installed? I cannot get cookies from my `—user-data-dir` on either Windows or Ubuntu to work when in headless mode.

**Comment by JackPoteYes** [comment] 2020-11-25 15:15
Same issue on headless Ubuntu Bionic, but with **Webkit**.
The browser context has no cookie, won't set them after receiving a Set-Cookie header response, and I can't set them manually neither.

**Comment by Proryanator** [comment] 2021-04-14 15:15
I'm also experiencing this and it's a bit frustrating :D

On Linux/MacOS, I do see that it stores session storage is created with headless mode.
However on Windows 10, there's like 1 file in the 'user-dir' folder I specify.

Not sure if anyone has a workaround, if I find one I'll try to post it here.

**Comment by rjzheng** [comment] 2021-07-15 11:39
Seeing the same issue but on MacOS. Most cookies persisted except for one. Everything runs fine with `headless: false`.

**Comment by sergioariveros** [comment] 2021-08-03 23:08
Same on MacOS

**Comment by pavelfeldman** [comment] 2022-01-06 18:18
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-01-06 18:18 UTC
Labels: browser-chromium, upstream, P3-collecting-feedback

**Comment by syedasadulhaq** [comment] 2022-01-13 12:50
I'm also facing same issue

**Comment by macrometa-yovko-yovkov** [comment] 2022-02-11 19:51
Still having the same issue on Mac with Chrome Version 98.0.4758.80 (Official Build) (x86_64)

**Comment by pawlarius** [comment] 2022-07-08 04:21
Cookies are missing when running playwright with headless mode enabled.
Happened at Chrome 103.0.5060.114 on macOS Big Sur Version 11.6 with M1 Chip.

**Comment by ethaniel** [comment] 2022-10-11 14:31
I confirm this very problem on Mac.

**Comment by AlizerUncaged** [comment] 2023-01-02 08:30
Any solutions to this? Still having the same problem, `set-cookies` header is missing on the response.

**Comment by SantiiRepair** [comment] 2024-11-02 17:11
Here, cookies do not load if the browser is in `--headless` mode.

**Comment by phuctm97** [comment] 2024-11-11 08:35
Same here, cookies do not load if browser is in `--headless` mode. We need a solution for this.
