### ISSUE TITLE
[BUG] Attach multiple instance of playwright to browser server

### ISSUE THREAD

**Issue by phileba** [microsoft/playwright#3405] opened 2020-08-12 04:45 UTC
The story is I want to do load test with the playwright, I've tried to simulate multiple users use the playwright to run the automation. 
- The first thing I create the browser server by 
```
const broserServer = playwright.chromium.launchServer({ headless: false })
const wsEndpoint = browserServer.wsEndpoint()
```

- Then I create multiple children thread, `postMessage` to each thread and send the `wsEndpoint` for the child thread connect to browser server:

```
...
async function runMethod(wsEndpoint: string) {
	const browser = await playwright.chromium.connect({ wsEndpoint })
	const page = await browser.newPage()
	await page.goto('https://google.com.vn')
	break
}
```
- So the result is if I try to run with 1 or 2 threads, it works fine but If if 4 or more threads, the instance can not connect to the browser server (status connecting). Do you have any idea?

**Comment by dgozman** [comment] 2020-08-13 18:07
Sounds like a bug, let me look into that.

**Comment by dgozman** [comment] 2020-08-14 16:22
I tried to repro with playwright v1.3.0 on my mac, but everything works for me. My setup is probably different, so repro script would be very much appreciated!

```js
const playwright = require('playwright');

(async () => {
  const browserServer = await playwright.chromium.launchServer({ headless: false });
  const promises = Array(20).fill(0).map(async () => {
    const browser = await playwright.chromium.connect({ wsEndpoint: browserServer.wsEndpoint() });
    const page = await browser.newPage();
    await page.goto('https://google.com.vn');
    console.log('connected one more');
    return browser;
  });
  const browsers = await Promise.all(promises);
  const closedPromises = browsers.map(browser => new Promise(f => {
    browser.once('disconnected', () => {
      console.log('closed one more');
      f();
    });
  }));
  await Promise.all([
    browserServer.close(),
    ...closedPromises
  ]);
})();
```

**Comment by phileba** [comment] 2020-08-17 08:32
Here is the script to repro:

#parent class:
```
const browserServer = await playwright.chromium.launchServer();
for (let i = 0; i < 20; i++) {
	const worker = new WorkerThread('child_file')
        worker.postMessage(browserServer.wsEndpoint())
}
```

#child class:
```
const messageListener = async (wsEndpoint) => {
        const browser = await playwright.chromium.connect({ wsEndpoint });
        const page = await browser.newPage();
        await page.goto('https://google.com.vn');
        console.log('connected one more');
}

if (parentPort) parentPort.on('message', messageListener)

This error appears sometimes on my machine
```
```
Timeout 30000ms exceeded during chromium.connect.
================== chromium.connect logs ==================
<ws connecting> ws://127.0.0.1:52949/bb0846224122de15d13af54888055652
<ws connected> ws://127.0.0.1:52949/bb0846224122de15d13af54888055652
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
```

**Comment by dgozman** [comment] 2020-08-19 21:51
Thank you for the repro! I tried reproducing this with [worker_threads](https://nodejs.org/api/worker_threads.html), but all 20 workers connect and navigate just fine, with playwright v1.3.0 and node v12.13.1.

```js
const playwright = require('playwright');
const { Worker, isMainThread, parentPort, workerData } = require('worker_threads');

(async () => {
  if (isMainThread) {
    const browserServer = await playwright.chromium.launchServer();
    const workers = [];
    for (let i = 0; i < 20; i++) {
      const worker = new Worker(__filename, { workerData: i });
      worker.postMessage(browserServer.wsEndpoint());
      workers.push(worker);
    }
  } else {
    const messageListener = async (wsEndpoint) => {
      const browser = await playwright.chromium.connect({ wsEndpoint });
      const page = await browser.newPage();
      await page.goto('https://google.com.vn');
      console.log('connected one more ' + workerData);
    }
    parentPort.on('message', messageListener);
  }
})();
```

**Comment by phileba** [comment] 2020-08-25 08:32
can you try to run in `headless: false`, 1 or 2 times it may appears

**Comment by dgozman** [comment] 2020-09-28 17:11
> can you try to run in `headless: false`, 1 or 2 times it may appears

Sorry, still cannot repro. Let me close this as I cannot reproduce it. Please reopen if you have a full script that does repro this.

**Closed by dgozman** 2020-09-28 17:11 UTC
Labels: v1.5
