### ISSUE TITLE
[BUG] Always launch 2 tabs or 2 windows

### ISSUE THREAD

**Issue by Elverslane** [microsoft/playwright#1078] opened 2020-02-21 09:26 UTC
**Context:**
- Playwright Version: [0.11.1]
- Operating System: [Mac Catalina]

**package.json**
`{
  "dependencies": {
    "playwright": "^0.11.1"
  }
}
`

**test.js**
`const playwright = require('playwright');`
`(async () => {`
`    for (const browserType of ['chromium', 'firefox', 'webkit']) {`
`        const browser = await playwright[browserType].launch({ headless: false });`
`        const context = await browser.newContext();`
`        const page = await context.newPage();`
`        await page.goto('http://whatsmyuseragent.org/');`
`        await page.screenshot({ path: `output/example-${browserType}.png` });`
`        await browser.close();`
`    }`
`})();`

With default settings and for any browser if launch tests with parameter `launch({ headless: false })` can see double window/tab. Its kinda strange

![Снимок экрана 2020-02-21 в 12 12 20](https://user-images.githubusercontent.com/17493900/75021402-60e24500-54a5-11ea-8acb-91ab3d169c2f.png)
![Снимок экрана 2020-02-21 в 12 12 23](https://user-images.githubusercontent.com/17493900/75021409-63449f00-54a5-11ea-876a-84d71c954003.png)

**Comment by pavelfeldman** [comment] 2020-02-21 13:03
Closing as a duplicate of https://github.com/microsoft/playwright/issues/981

**Closed by pavelfeldman** 2020-02-21 13:03 UTC
