### ISSUE TITLE
[BUG] unexpected browserContext close

### ISSUE THREAD

**Issue by IuliiaBondarieva** [microsoft/playwright#11352] opened 2022-01-12 16:07 UTC
**Context:**
- Playwright Version: @playwright/test@1.17.1
- Operating System: Linux
- Node.js version: 14.17.4
- Browser: Chromium

**Code Snippet**

```javascript
await this.page.goto('/admin', { waitUntil: 'networkidle' });
await this.deactivateProfileButton.waitFor();
await Promise.all([
      this.page.waitForResponse(
        (response) => response.url().includes('/profile/status') && response.status() === 200
      ),
      this.deactivateProfileButton.click(),
    ]);
```

When running on CI browserContext starts closing
```
pw:api <= page.goto succeeded
pw:api => locator.waitFor started
pw:api waiting for selector "button:has-text("Toggle local user")" to be visible
pw:api   selector resolved to visible <button qa-regression-tag="button" class="B_ObDmT7lQxprh…>Toggle local user</button>
pw:api <= locator.waitFor succeeded
pw:api => page.waitForResponse started
pw:api => locator.click started
pw:api waiting for selector "button:has-text("Deactivate profile")"
pw:api   selector resolved to visible <button qa-regression-tag="button" class="B_ObDmT7lQxprh…>Deactivate profile</button>
pw:api attempting click action
pw:api   waiting for element to be visible, enabled and stable
pw:api => browserContext.close started
pw:api <= page.waitForResponse failed
pw:api <= locator.click failed
pw:api <= browserContext.close succeeded
pw:api => browser.close started
```

If running locally element will be checked properly
```
waiting for selector "button:has-text("Deactivate profile")"
selector resolved to visible <button qa-regression-tag="button" class="B_ObDmT7lQxprh…>Deactivate profile</button>
attempting click action
waiting for element to be visible, enabled and stable
element is visible, enabled and stable
scrolling into view if needed
done scrolling
checking that element receives pointer events at (457.7,381.26)
element does receive pointer events
```

by trace is `Action was interrupted`

We had already problem with unexpected browserContext.close. It seems to happen if it's the end of the test. (no expect on the end)

**Comment by dgozman** [comment] 2022-01-12 17:34
@IuliiaBondarieva I assume that test times out and closes the context during cleanup - that's expected behavior. If you can share a repro or more details, we'll be able to better help.

**Comment by mxschmitt** [comment] 2022-01-19 13:13
Closing since we can't act on it without seeing a repro. Feel free to create a new issue and reference to this one if you are able to repro it.

**Closed by mxschmitt** 2022-01-19 13:13 UTC
Labels: triaging

**Comment by skysantoroa** [comment] 2022-08-19 10:25
Having the same issue, I'm using Playwright 1.23.1

**Comment by anastasiyamazheika** [comment] 2022-11-02 17:00
Noticed the same issue in 1.23.3
