### ISSUE TITLE
[BUG] expect.toPass() does not retries code blocks if it contains toHaveScreenshot

### ISSUE THREAD

**Issue by lucasbit** [microsoft/playwright#23653] opened 2023-06-12 07:53 UTC
### System info
- Playwright Version: 1.33.0
- Operating System: Windows
- Browser: Firefox
- Other info: Node: 18.16.0

### Source code

```
async runVisualChecksAfterProjectSave(headless) {
    if (headless) {
      // Start comparing snapshots on Custom tab
      await this.customTabBtn.click();
      await this.page.waitForLoadState("load", { timeout: 10 * 1000 });
      await expect(async () => {
        await expect(this.projectCard).toHaveScreenshot({
          mask: [this.projectNameInput, this.footerRegisterLabel],
        });
      }).toPass({ timeout: 10000, intervals: [1000, 2000, 3000] });
```

**Expected**

As described on this feature wish: https://github.com/microsoft/playwright/issues/20987

`expect.toPass()` should be walk around for image testing for pages that take bit more time to load content, goal is to reduce flaky tests. I would expect that toPass will retry toHaveScreenshot() for the timeout provided in `toPass()`. The default timeout for `expect()` is set for 5 sec.  But in our case, assertion fails after 403s

![image](https://github.com/microsoft/playwright/assets/29520131/bef5531c-150c-4c24-96b1-ebd5c07b5712)
![image](https://github.com/microsoft/playwright/assets/29520131/23049d31-870c-4da9-a9d4-f6bf527d477c)

**Actual**

Wrapping `toHaveScreenshot()` with `expect.toPass` should extend assertion timeout either for default timeout set for `expect()` or for timeout set inside `toPass()` and give us flexibility for visual testing.

**Comment by aslushnikov** [comment] 2023-06-12 21:00
@lucasbit you can actually use `toMatchSnapshot()` instead of `toHaveScreenshot()` inside of `toPass()` - this will yield the behavior described in https://github.com/microsoft/playwright/issues/20987.

Would it help?

**Comment by lucasbit** [comment] 2023-06-13 10:24
@aslushnikov I'm afraid no luck here as well, traces show that timeout has been ignored. There is a weird amount of time provided on test.step(10.2s on "After project is saved, run visual checks"), milliseconds from assertions don't sum up to 10,2 sec - but I guess that is another issue.
![image](https://github.com/microsoft/playwright/assets/29520131/d02abf9b-d071-4641-96e5-f0703c5338db)

Would it be possible to add **intervals** as an option (default: none/0) to **toHaveScreenshot()**?  Docs say: _"This function will wait until two consecutive page screenshots yield the same result, and then compare the last screenshot with the expectation."_ If we could set an interval between screenshots inside function, then we would have a tool to slow it down and make it less flaky.

**Comment by aslushnikov** [comment] 2023-07-06 19:09
> If we could set an interval between screenshots inside function, then we would have a tool to slow it down and make it less flaky.

@lucasbit first of all, this would be functionally similar to just waiting for certain time **before** calling the `toHaveScreenshot()` method. 

Secondly, I don't think this approach is robust enough. In general, it is convenient to think of a CI of something that doesn't have a reliable notion of time, meaning that if something takes 1 second locally, it might take 10 seconds or even a minute on some highly-saturated cloud VM that runs your tests. Thus any timeouts thrown into the tests will only mask the fundamental issue and burn more CPU time rather than fixing the root cause.

The only reliable way would be to come up with a criteria to wait for the desired page state **before** taking its screenshot. 

I'll close this for now since I don't think there's much we can do here, but please do not hesitate to file a new issue if you still thin we can be helpful.

**Closed by aslushnikov** 2023-07-06 19:09 UTC
Labels: v1.36
