### ISSUE TITLE
[Feature] Playwright tracks should collect requests that are still pending when the browser is closed 

### ISSUE THREAD

**Issue by CHHome** [microsoft/playwright#23252] opened 2023-05-24 07:12 UTC
I use playwright traces to collect requests on website.So that I can analyze the network situation.

This is my use case script：
```js
const { chromium } = require('playwright');

(async () => {
    const browser = await chromium.launch();
    const context = await browser.newContext();
    await context.tracing.start({ screenshots: true, snapshots: true });
    const page = await context.newPage();

    await page.goto('http://127.0.0.1:8080/hello.html');
    // other actions...

    try {
        await page.waitForLoadState('networkidle', {
            timeout: 5000,
        })
    } catch (error) {
        await page.close();
        await context.tracing.stop({ path: 'trace.zip' });
        await context.close();
        throw error
    }

    await page.close();
    await context.tracing.stop({ path: 'trace.zip' });
    await context.close();
})();
```
However, when the request exceeds 5 seconds and is still in a pending state, my automation script catches an exception and closes the browser.At this point, trace will not save the record of the request in the pending state

In another issue，@dgozman mentioned using the page.close, so all network request should be aborted, and then saves the trace. 
 **link:**  https://github.com/microsoft/playwright/issues/23045
But in the above use case script, trace still hasn't collected requests that are still pending when the browser is closed.

If page. close cannot solve this problem
Is playwright considering adding a method to the page object that can terminate all page requests

This is very meaningful as it allows for a complete analysis of the network situation. I think many people need

**Comment by yury-s** [comment] 2023-07-11 23:43
I cannot reproduce it with this code https://github.com/yury-s/bug-23252/ which is based on the information you provided. The XHR request is there in the trace file.

**Comment by aslushnikov** [comment] 2023-07-19 13:09
Closing as per above.

**Closed by aslushnikov** 2023-07-19 13:09 UTC
Labels: triaging
