### ISSUE TITLE
[URGENT] Not able to print images on calling page.pdf() using playwright

### ISSUE THREAD

**Issue by tushitaaggarwal** [microsoft/playwright#12994] opened 2022-03-21 18:31 UTC
Hi,

For a below sample html file, I am not able to view images in the final printed pdf, although they are present in the screenshot I take via page.screenshot API.  Could you please let me know why this might be happening? Are there any flags that might lead to omitting of the images while printing? 
Here are the details of what I have investigated:
1. This only happens in headless mode of chrome browser
2. The images are present if I take a screenshot of the page before printing indicating clearly that the images are getting loaded onto the page. Not able to understand why they are then getting omitted at the time of printing.
3. Happens in the case of <source> tag for html. If I replace it with< img> tag, the images can be seen in the printed pdf.
4. If I directly call the following command to print using chrome exe, I get correct pdf with all the images present:
          C:\Users\Tuaggarw\AppData\Local\ms-playwright\chromium-956323\chrome-win\chrome.exe --headless --disable-gpu --print-to-pdf=2_actual.pdf C:/testfiles/2/index.html     

 This is a blocker for us and request you to please look into it and let me know if there is any reason for the anomaly. I cannot share the whole code due to confidentiality reasons but let me know if you need it on a separate mail thread.

Please find a sample html file attached :
[2.zip](https://github.com/microsoft/playwright-java/files/8318278/2.zip)

**Comment by yury-s** [comment] 2022-03-23 18:20
Debugging notes. I tried to create a repro for Chromium bug but the issue is not reproducible in puppeteer with similar script:
```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({executablePath: '/home/yurys/.cache/ms-playwright/chromium-978106/chrome-linux/chrome'});
  const page = await browser.newPage();
  await page.setViewport({width: 1280, height: 960});
  console.log(JSON.stringify(page.viewport()));
  await page.setRequestInterception(true);
  page.on('request', (interceptedRequest) => {
    console.log(interceptedRequest.url());
    interceptedRequest.continue();
  });  
  await page.goto('http://127.0.0.1:9911/');
  await page.pdf({ path: '/tmp/test.pdf' });
  await page.screenshot({ path: '/tmp/test.png' });

  await browser.close();
})();

```
Aligning browser flags in playwright didn't help either:
```js
  const browser = await chromium.launch({
    ignoreDefaultArgs: [
      '--disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement',
      '--blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4',
      '--allow-pre-commit-input',
      '--no-sandbox',
    ],
    args: [
      '--enable-blink-features=IdleDetection',
    ]
  });
```

**Comment by tushitaaggarwal** [comment] 2022-03-24 11:02
Hi Yury, thank you for investigating the bug. Please let me know if there is any workaround for intercepting requests. Alternatively, since we are using playwright in our enterprise service, could you please share an ETA by when you can share your investigations and if possible a workaround for the same? This bug is critical for our workflow.

**Comment by pavelfeldman** [comment] 2022-10-20 06:18
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-10-20 06:18 UTC
Labels: P3-collecting-feedback
