### ISSUE TITLE
[BUG] Before Hook and After Hook in traces are not populated for every test

### ISSUE THREAD

**Issue by GuyQC** [microsoft/playwright#24494] opened 2023-07-28 16:14 UTC
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**
```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

const config: PlaywrightTestConfig = {
  use: {
    baseURL: configBaseUrl,
    ignoreHTTPSErrors: true,
    trace: "on",
    screenshot: "on",
    video: "on",
    headless: true,
  },
};
```

**Test file (self-contained)**

```js
test.describe("Test Group", () => {
  test.beforeAll(async ({ request }) => {
    // Make API Calls
    // GET to google.com for example
  });
  test("Test 1", ({}) => {
    expect(False).toEqual(True);
  });
  test("Test 2", ({}) => {
    expect(True).toEqual(False);
  });
});
```

**Steps**
- [Run the test]
- Open the trace file Test 1 and 2 with https://trace.playwright.dev/
- Try to go to before hooks for Test 1 - Observe you are able to and there are traces for the API call done in beforeAll
- Try to go to before Hooks for Test 2 - Observer you can't expand to see any details for the before hooks and that there are no traces for the API call in this test trace.

**Expected**

The Before hook and after hook exist for all tests inside the describe() block

**Actual**

The before Hooks are only populated for the first failed test inside the test.describe() block

**Comment by pavelfeldman** [comment] 2023-07-28 17:18
We only show beforeAll hooks as a part of the first test that this beforeAll ran for.

**Comment by pavelfeldman** [comment] 2023-07-28 20:39
I'll close it as non-actionable since this is by design at this point and we are not going to change it in the near term. I understand how UX might be not straightforward.

**Closed by pavelfeldman** 2023-07-28 20:39 UTC
Labels: triaging
