### ISSUE TITLE
[BUG] ~ 70% Higher memory usage when using playwright v1.40.1

### ISSUE THREAD

**Issue by DanielDornhardt** [microsoft/playwright#28942] opened 2024-01-11 08:56 UTC
### System info
- Playwright Version: v1.40.1
- Operating System: macOS 14 Sonoma
- Browser: Chromium

### Source code

Sorry, I don't have a simple reproduction ready; is there a simple E2E test repo with longer running playwright in it I could clone to demonstrate this?

**Steps**
1. Run playwright 1.39.0 for eg. your browser testing over a fixed time period (minutes), eg 5 minutes
  - Open your process manager and note the memory usage of the thread "Chromium Helper (GPU)"
2. Run playwright 1.40.1 for eg. your browser testing over the same fixed time period (minutes), eg 5 minutes
  - Open your process manager and note the memory usage of the thread "Chromium Helper (GPU)"
3. Compare the memory usage between 1. and 2.

**Expected**

Similar amounts of RAM being used between playwright 1.39.0 and 1.40.1

**Actual**

About 70% higher usage.

I'll add two screenshots after letting playwright running on our e2e test suite for 1 1/2 hours for a more clearly visible difference:

**with 1.39.0:**

![image](https://github.com/microsoft/playwright/assets/3845924/79971fea-bd5e-4672-ba84-e9c0d22e4ae9)

**with 1.40.1:**

![image](https://github.com/microsoft/playwright/assets/3845924/96d967f9-6b6b-4ba5-a1ef-6ac43c433cc9)

But the same happens after eg. 7 minutes in our smaller suite, where 1.39.0 used ~ 3.2 GB RAM afterwards and 1.40.1 ~ 5.4 GB RAM, for example.

This of course is an issue because it'll make tests more memory heavy, which can lead also to longer runtimes (more swapping / not enough ram for example) and resource exhaustion on testing servers.

**Finally**

Please let me know if there's a good demo repo somewhere from which I could construct a replication, otherwise I think it'd be enough to try it in an existing project by switching playwright versions and opening the task manager.

Thank you guys & keep rocking! 🥁🎸

**Comment by dgozman** [comment] 2024-01-11 21:46
@DanielDornhardt I think this problem is very specific to the page you are testing. For example, when testing `https://playwright.dev`, no matter how long the test runs, "Chromium Helper (GPU)" takes less than 120MB on my computer.

It looks like you have found a memory regression of your page in the newer Chrome version. You can try opening the page manually in Chrome Canary vs Chrome Stable and compare.

Overall, this does not look like a Playwright issue to me. However, if you still believe it is a Playwright issue, we would need a repro from you that would demonstrate the problem.

**Comment by unlikelyzero** [comment] 2024-01-12 21:09
The last time playwright had a performance regression, it ended up in https://github.com/krausest/js-framework-benchmark when chrome hit stable. @DanielDornhardt  you may want to go ahead and file a bug on the chromium issue tracker

**Comment by DeLaphante** [comment] 2024-01-15 08:25
I don't think this has anything to do with the website, page or chrome but Playwright's architecture of using websockets to maintain active connections. 
Unlike traditional HTTP, which is stateless, WebSockets are stateful. This means that Playwright needs to maintain the connection state for each browser or test, leading to increased memory usage and potential scalability challenges.

What happens if those connections drop for an unknown reason during a test run? What is the fallback mechanism? Does it have to establish a new connection again and how does it resume where it left off?

Websockets are great for real time communication between two or more entities but are websites or the browser going to be communicating every event back to playwright? If this is so then playwright has to store and remember every response until the connection is closed.

This issue happened previously but was closed without any resolution.

https://github.com/microsoft/playwright/issues/6319

**Comment by dgozman** [comment] 2024-01-16 19:22
Closing as per [this comment](https://github.com/microsoft/playwright/issues/28942#issuecomment-1888020247).
If you still believe there is a problem with Playwright and figure out a way to share a repro, please file a new issue and link to this one.

**Closed by dgozman** 2024-01-16 19:22 UTC
