### ISSUE TITLE
Can not get electron app when using AppImage [BUG]

### ISSUE THREAD

**Issue by dming4** [microsoft/playwright#14337] opened 2022-05-23 03:21 UTC
**Context:**
- Playwright Version: [1.20.1]
- Operating System: [Linux]
- Node.js version: [16.14.0]
- Browser: [Electron]
- Extra: [Electron app]

**Code Snippet**

```javascript
const electronApp = await electron.launch({ executablePath: ’xxx.AppImage‘ });
const winCount=electronApp.windows().length;
const window = await electronApp.firstWindow();
```

**Describe the bug**
Can't get the electron app when using AppImage, but launch electron main js file is ok

**Using main.js is ok**

The below code can start electron app normally and the window can return back normal.
```javascript
const electronApp = await electron.launch({ args: ['main.js'] });
const window = await electronApp.firstWindow();
```

**Comment by mxschmitt** [comment] 2022-05-23 17:30
Sounds like a duplicate of https://github.com/microsoft/playwright/issues/14088

**Closed** 2022-05-23 17:35 UTC
