### ISSUE TITLE
[BUG] Download event times out in WebKit

### ISSUE THREAD

**Issue by JeremieBourque1** [microsoft/playwright#15417] opened 2022-07-06 15:31 UTC
**Context:**
- Playwright Version: 1.21.1
- Operating System: Windows 10
- Node.js version: v16.15.0
- Browser: WebKit
- Extra: [any specific details about your environment]

```ts
import { test } from '@playwright/test';

DownloadTest.ts
test('Test download', async ({ page }) => {
    await page.goto('https://demo.borland.com/testsite/download_testpage.php');
    const lDownloadButton = page.locator('#downloadButton');
    const [download] = await Promise.all([page.waitForEvent('download', { timeout: 5000 }), lDownloadButton.click()]);
});
```
playwright.config.ts
```ts
import type { PlaywrightTestConfig } from '@playwright/test';
import { devices } from '@playwright/test';

const config: PlaywrightTestConfig = {
    webServer: {
        command: 'npm run build && npm run preview',
        port: 3000
    },
    testDir: './tests',
    testMatch: '*.*(ts|js)',
    forbidOnly: !!process.env.CI,
    retries: process.env.CI ? 2 : 0,
    workers: 1,
    use: {
        trace: 'retain-on-failure',
        baseURL: 'http://localhost:3000',
        video: 'retain-on-failure',
        screenshot: 'only-on-failure'
    },
    projects: [
        {
            name: 'chromium',
            use: { ...devices['Desktop Chrome'] }
        },
        {
            name: 'firefox',
            use: { ...devices['Desktop Firefox'] }
        },
        {
            name: 'webkit',
            use: { ...devices['Desktop Safari'] }
        }
    ]
};

export default config;
```

In WebKit, the download event is never triggered so the wait times out and the test fails. This is not a problem in Chromium or Firefox. I first encountered this bug while working on a project, but to make it easier to reproduce, I simplified the test to use a public browser download test page instead. I also tried using the default 30 seconds timeout but the problem persists.

Thanks!

**Comment by aslushnikov** [comment] 2022-07-07 13:55
@JeremieBourque1 the example snippet you provided with the https://demo.borland.com/testsite/download_testpage.php website doesn't issue a download since it doesn't set any `content-disposition` header to the response. Thus both Chromium and WebKit just navigate to the content inline instead of downloading it:

```js
import { chromium, firefox, webkit } from '@playwright/test';

const browser = await webkit.launch({ headless: false });
const page = await browser.newPage();
await page.goto('https://demo.borland.com/testsite/download_testpage.php');

// Uncomment the following to make snippet work!
// await page.click('[contentdisposition="attachment"]');

const downloadButton = page.locator('#downloadButton');
const [ download ] = await Promise.all([
  page.waitForEvent('download'),
  downloadButton.click(),
]);
console.log('here!');
await browser.close();
```

While if we uncomment the line to set the proper header, then everything works.

In other words, this doesn't look like a bug to me, but rather as an intended behavior.

**Comment by JeremieBourque1** [comment] 2022-07-07 21:14
Oh right so that's what was wrong in my snippet. In my project however, we are using the `download` attribute to make the button download the file. But in WebKit, the download event is never triggered while there is no problem in Chromium and Firefox.

Here is a snippet of how we handle downloads from the browser.

```ts
function exportFile(aFileName: string, aFileContent: string) {
    // create temporarily an invisible element
    let lElementToDownload = document.createElement('a');
    lElementToDownload.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(aFileContent));
    lElementToDownload.setAttribute('download', aFileName);
    lElementToDownload.click();
    lElementToDownload.remove();
}
```

Any idea where the problem could be coming from?
Thanks!

**Comment by JeremieBourque1** [comment] 2022-07-08 14:41
Interestingly, using the following implementation solved my problem.
```ts
function exportFile(aFileName: string, aFileContent: string) {
    // create temporarily an invisible element
    let lElementToDownload = document.createElement('a');
    const lFile = new File([aFileContent], aFileName, { type: 'text/plain'})
    const lUrl = URL.createObjectURL(lFile);
    lElementToDownload.setAttribute('href', lUrl);
    lElementToDownload.setAttribute('download', aFileName);
    lElementToDownload.click();
}
```
Though I'm still not sure why the first implementation didn't work with webkit

**Comment by aslushnikov** [comment] 2022-07-08 14:52
Might be some quirk of webkit-for-windows; the original approach works for me on Webkit-for-mac.

I'm happy it resolved though, so I'd close this without further investigation since it's not blocking any more! Please feel free to re-file if something's blocking you.

**Closed by aslushnikov** 2022-07-08 14:52 UTC
Labels: triaging
