### ISSUE TITLE
[BUG] page.route appears to break redirect

### ISSUE THREAD

**Issue by monkekode** [microsoft/playwright#13817] opened 2022-04-28 10:05 UTC
**Context:**
## System:
 - OS: macOS 11.6.5
 - Memory: 1.05 GB / 16.00 GB
## Binaries:
 - Node: 15.14.0 - /usr/local/bin/node
 - Yarn: 1.22.17 - /usr/local/bin/yarn
 - npm: 7.7.6 - /usr/local/bin/npm
## Languages:
 - Bash: 5.1.16 - /usr/local/bin/bash
## npmPackages:
 - playwright: ^1.21.0 => 1.21.0

**Code Snippet**

```javascript
import {chromium, Route} from "playwright";

const browser = await chromium.launch({
    headless: false,
});

const page = await browser.newPage();

await page.route(() => true, async (route: Route) => {
    const response = await page.request.fetch(route.request());
    await route.fulfill({response});
});

await page.goto('https://google.com');
await new Promise((res) => setTimeout(res, 100000));
await browser.close();
```

**Describe the bug**

It appears that when every route is handled by request.fetch and route.fulfill-ed, it should act exactly as not using .route at all. Instead if breaks some sites. For Google it breaks the redirect (stays at https://google.com instead of being redirected to https://www.google.com) and hence - the Google logo:

![Screenshot 2022-04-28 at 12 55 35](https://user-images.githubusercontent.com/84079248/165729109-ac1b4248-8fe2-4947-a05b-7ed8516cbc28.png)

Removing the page.route call fixes the issue.

**Comment by yury-s** [comment] 2022-05-02 20:32
I can't reproduce it, all the images load just fine. Do you have a reproducible example that we could run locally? It's hard to tell what could have caused that image load failure and not only the content they serve does depend on many things it also changes over time. We need a repro to act on this.

**Comment by monkekode** [comment] 2022-05-03 07:53
I've just reproduced it locally, the issue is that google normally redirects from https://google.com to https://www.google.com, and images work on the latter url, but not the former. When page.route is in use, there is no redirect, so the images break. Maybe this HAR will help you?
[google.com.har.zip](https://github.com/microsoft/playwright/files/8608999/google.com.har.zip)

**Comment by yury-s** [comment] 2022-05-03 21:28
This is working as expected, when you do:
```js
    const response = await page.request.fetch(route.request());
    await route.fulfill({response});
```
the browser doesn't know anything about the redirects and stays on the original URL (fulfilled with the redirected response). If the page breaks because it expects the url to be different you can navigate to that URL directly. Playwright does not allow intercepting redirected requests, this is a known limitation described in our docs.

Is there an actual test scenario that cannot be accomplished because of this?

**Comment by aslushnikov** [comment] 2022-05-06 18:06
Closing since it looks like it works as intended.

**Closed by aslushnikov** 2022-05-06 18:06 UTC
Labels: v1.22
