### ISSUE TITLE
[BUG]full screenshot of scrollable page did not work on specified website.

### ISSUE THREAD

**Issue by darcyc-chen** [microsoft/playwright#19198] opened 2022-12-01 08:31 UTC
**Context:**
- Playwright Version: 1.27.1
- Operating System: windows
- Node.js version:   python 3.10.0
- Browser: chromium

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    page = browser.new_page()
    page.goto("http://ufeelgreat.com", timeout=60000)
    page.screenshot(path="example.png", full_page=True)
    browser.close()
```

**Describe the bug**

I encountered the same issue with #18406 . Full screenshot generated incorrectly. As you cannot visit my web site that works incoreectly. reproduce this issue with page ufeelgreat.com.

**Comment by mxschmitt** [comment] 2022-12-01 18:35
This is working as intended as of today, by definition this site does not have a greater height than the viewport height is, see here:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/17984549/205132519-b3b98d30-a76b-45ab-8e44-3cfbd1cd5dd4.png">

Marking it as a feature request for now.

**Comment by hx0day** [comment] 2023-02-02 09:07
Context:

Playwright Version: 1.28.0
Operating System: macOS
Node.js version: python 3.9.6
Browser: all

```python
from playwright.sync_api import sync_playwright


def main():
    with sync_playwright() as p:
        for browser_type in [p.chromium, p.firefox, p.webkit]:
            browser = browser_type.launch()
            page = browser.new_page()
            page.goto('https://biz.mail.ru/')
            page.screenshot(path=f'example-{browser_type.name}.png', full_page=True)
            page.close()
            browser.close()


main()
```
Full screenshot generated incorrectly.

**Comment by antpingelli** [comment] 2023-07-20 14:15
@mxschmitt I am also running into this for my internal UI. I took a fullPage screenshot of https://playwright.dev/ and then compared the output of `document.documentElement.clientHeight` for both pages and they give back the same height. Is there a different reason this could be happening?

**Comment by chcorpmy** [comment] 2024-01-08 22:17
This continues to be an issue in 1.40.1. I'm unable to take a full page screenshot on multiple sites. This significantly reduces the usefulness of the screenshot, and visual comparison features in Playwright.

**Comment by pavelfeldman** [comment] 2024-04-22 17:55
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Closed by pavelfeldman** 2024-04-22 17:55 UTC
Labels: P3-collecting-feedback
