### ISSUE TITLE
Playwright not able to locate video element

### ISSUE THREAD

**Issue by craitose** [microsoft/playwright#29084] opened 2024-01-20 11:02 UTC
### System info
- Playwright Version: [v1.40.1]
- Operating System: [Windows 11]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

[<div id="video" class="video_page" overflow=hidden >
<div class="vidComponent_container"></div>
<video id="video-child-live" playsinline>...</video>
</div>]

[I have tried to access the properties of video-child-live by declaring the locator with: 
videoElem = () => this.page.locator('.video_page').locator('id=video-child-live');
&
videoElem = () => this.page.locator('id=video-child-live');
&
videoElem = () => this.page.locator('[id="video-child-live"]');
&
videoElem = () => this.page.locator('//*[@id="video-child-live"]');

.]

**Steps**
- [Run the test]
- [
- await videoElem().wait for();
- let vidProp = await this.videoElem().evaluate(e ()=> (e as HTMLVideoElement).volume);
-console.log(vidProp); ]

**Expected**

[Describe expected behavior]
Expect playwright to find the video element 

**Actual**

[Describe actual behavior]

Timed out waiting for locator('.video').locator('id=video-child-live'); to be visible

**Comment by mxschmitt** [comment] 2024-01-20 12:02
Closing for now since this issue is not following the issue template. We need clear reproduction steps / a small script which surfaces the problem with actual / expected results. Feel free to re-file. Thanks for your understanding!

**Closed by mxschmitt** 2024-01-20 12:02 UTC

**Comment by craitose** [comment] 2024-01-20 12:23
> Closing for now since this issue is not following the issue template. We need clear reproduction steps / a small script which surfaces the problem with actual / expected results. Feel free to re-file. Thanks for your understanding!

I don't understand, which steps am I missing? I have included the source code, test code, expected results, actual resulting error. You should advise on what's missing before closing as you are just causing the creation of duplicates for no logical reason

**Comment by mxschmitt** [comment] 2024-01-20 12:30
I tried the following and it was working for me:

```ts
import { chromium } from 'playwright';

(async () => {
  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext();
  const page = await context.newPage();

  await page.goto('https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_video');
  await page.frameLocator('iframe[name="iframeResult"]').locator('video').waitFor();
  await page.frameLocator('iframe[name="iframeResult"]').locator('video').evaluate((video) => video.volume = 0.3);
  await page.pause();

  await context.close();
  await browser.close();
})();
```

(This is what I meant with a full self-contained repro).

**Comment by mxschmitt** [comment] 2024-01-21 10:47
I'm using the latest version of Playwright - can you provide us a full self-contained code snippet which we can run locally to reproduce your issue?
