### ISSUE TITLE
Chromium crash on macos with PW 1.10.0[BUG]

### ISSUE THREAD

**Issue by Tallyb** [microsoft/playwright#6024] opened 2021-03-31 17:55 UTC
**Context:**
- Playwright Version: 1.10.0
- Operating System: Macos 11.2.3
- Node.js version: 14.16.0 and also on 14.15.4
- Browser: Chromium
- Extra: [any specific details about your environment]

  System:
    OS: macOS 11.2.3
    Memory: 13.24 GB / 64.00 GB
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    playwright-chromium: ^1.10.0 => 1.10.0

**Code Snippet**
Trying to create a snippet to reproduce. 

**Describe the bug**

Running a test with cucumber and playwright on 1.10.0 in HEADLESS mode crashes with the error bellow. 
Works ok 
 - locally In headful. 
 - Locally when downgrading to 1.9.2 
 - on CI (Ubuntu 20) 

```
page.waitForSelector: Protocol error (DOM.describeNode): Browser closed.
       ==================== Browser output: ====================
       <launching> /Users/me/Library/Caches/ms-playwright/chromium-857950/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=/var/folders/99/y2bb165n66q99tqwsv7bpt600000gn/T/playwright_chromiumdev_profile-vT6xKj --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --use-fake-ui-for-media-stream --use-fake-device-for-media-stream --no-startup-window
       <launched> pid=92589
       [pid=92589][err] Received signal 11 SEGV_MAPERR 000000000008
       [pid=92589][err]  [0x00011571dce9]
       [pid=92589][err]  [0x0001156730d3]
       [pid=92589][err]  [0x00011571db11]
       [pid=92589][err]  [0x7fff20668d7d]
       [pid=92589][err]  [0x000000000000]
       [pid=92589][err]  [0x000113b39920]
       [pid=92589][err]  [0x000113b395ca]
       [pid=92589][err]  [0x000113b324ea]
       [pid=92589][err]  [0x000113b32100]
       [pid=92589][err]  [0x000113b31fe7]
       [pid=92589][err]  [0x0001156d7ec8]
       [pid=92589][err]  [0x0001156eb351]
       [pid=92589][err]  [0x0001156eb02a]
       [pid=92589][err]  [0x0001157312b7]
       [pid=92589][err]  [0x00011572b5e2]
       [pid=92589][err]  [0x000115730cef]
       [pid=92589][err]  [0x7fff2071ca0c]
       [pid=92589][err]  [0x7fff2071c974]
       [pid=92589][err]  [0x7fff2071c6ef]
       [pid=92589][err]  [0x7fff2071b121]
       [pid=92589][err]  [0x7fff2071a6ce]
       [pid=92589][err]  [0x7fff214a7fa1]
       [pid=92589][err]  [0x000115731801]
       [pid=92589][err]  [0x00011573089c]
       [pid=92589][err]  [0x0001156eb99b]
       [pid=92589][err]  [0x0001156b61fb]
       [pid=92589][err]  [0x0001157081b8]
       [pid=92589][err]  [0x00011570837b]
       [pid=92589][err]  [0x000115727be8]
       [pid=92589][err]  [0x7fff20624950]
       [pid=92589][err]  [0x7fff2062047b]
       [pid=92589][err] [end of stack trace]
```

Add any other details about the problem here.

**Comment by Tallyb** [comment] 2021-03-31 18:54
Sadly this is a private code. I am trying to create a smaller repo, but with no luck so far. 
Is there a way to try and test ow 1.9.2 with chromium of 1.10.0 or vice versa to try and eliminate the issue?

**Comment by pavelfeldman** [comment] 2021-03-31 23:01
I wonder why we lack symbols on this crash.

**Comment by pavelfeldman** [comment] 2021-03-31 23:03
@Tallyb: could you try running it against stable Chrome 89? Pass `channel: 'chrome'` into launch?

**Comment by aslushnikov** [comment] 2021-03-31 23:25
@Tallyb alternatively, maybe you can share some code privately with us? E.g. via email at anlushni [at] microsoft [dot] com

**Comment by Tallyb** [comment] 2021-04-01 04:59
@pavelfeldman - I can confirm that running PW 1.10.0 against stable chrome (89) is ok.

**Comment by aslushnikov** [comment] 2021-04-01 05:38
> @pavelfeldman - I can confirm that running PW 1.10.0 against stable chrome (89) is ok.

@Tallyb can you please try running against [Chrome Canary](https://www.google.com/chrome/canary/)? You'll need to install it and then launch browser with an executable path like this:

```js
// ....
const browser = await chromium.launch({
  executablePath: `/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary`,
});
```

**Comment by Tallyb** [comment] 2021-04-01 07:34
Apparently, as an MS application, the old way works.
I just rebooted and now everything seems ok. 
As it happened to my colleague as well, I did not anticipate it. 
Apologies for the disturbing.

**Comment by Tallyb** [comment] 2021-04-01 10:52
@aslushnikov  - Running on chrome via channel or path is ok. running on canary via channel or path fails.

**Comment by pavelfeldman** [comment] 2021-04-01 16:47
> I just rebooted and now everything seems ok.

Are you saying after reboot stable chrome works or only canary? If you still have it happening with stable chrome and it fails with canary, we can try building a bisect tool for you that would help us identifying the culprit. It is likely the problem is upstream in Chrome, so we would bisect chromium builds. Sadly we can't do it locally since it is specific to your use case.

**Comment by pavelfeldman** [comment] 2021-04-02 05:00
Actually, I spoke too soon. I just got the same exact log on browser.close in Playwright 1.8. It looks like this crash has always been happening on macOS 11 on browser close. But it looks like it is happening mid-test for you. I filed a [chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1195291) that we'll fix, but there seems to be more to the problem. I'll keep digging.

**Comment by pavelfeldman** [comment] 2021-04-04 16:53
Thanks to @Tallyb we have a stack in https://bugs.chromium.org/p/chromium/issues/detail?id=1195664 now:

```
  Received signal 11 SEGV_MAPERR 000000000008 +9s
  0   Chromium Framework                  0x000000011a78aae9 base::debug::CollectStackTrace(void**, unsigned long) + 9 +111ms
  1   Chromium Framework                  0x000000011a6936d3 base::debug::StackTrace::StackTrace() + 19 +0ms
  2   Chromium Framework                  0x000000011a78a911 base::debug::(anonymous namespace)::StackDumpSignalHandler(int, __siginfo*, void*) + 1329 +0ms
  3   libsystem_platform.dylib            0x00007fff2067fd7d _sigtramp + 29 +0ms
  4   ???                                 0x0000000000000000 0x0 + 0 +0ms
  5   Chromium Framework                  0x0000000117a78b1c device::NetworkLocationProvider::NetworkLocationProvider(scoped_refptr<network::SharedURLLoaderFactory>, device::GeolocationSystemPermissionManager*, scoped_refptr<base::SingleThreadTaskRunner>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, device::PositionCache*) + 428 +0ms
  6   Chromium Framework                  0x0000000117a6fc07 device::LocationArbitrator::NewNetworkLocationProvider(scoped_refptr<network::SharedURLLoaderFactory>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 167 +1ms
  7   Chromium Framework                  0x0000000117a6f6d1 device::LocationArbitrator::RegisterProviders() + 97 +0ms
  8   Chromium Framework                  0x0000000117a6f656 device::LocationArbitrator::StartProvider(bool) + 38 +0ms
  9   Chromium Framework                  0x0000000117a6dd34 device::GeolocationProviderImpl::StartProviders(bool) + 148 +0ms
  10  Chromium Framework                  0x000000011a71dbdc base::TaskAnnotator::RunTask(char const*, base::PendingTask*) + 380 +0ms
  11  Chromium Framework                  0x000000011a742237 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*) + 1015 +0ms
  12  Chromium Framework                  0x000000011a741a4d base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() + 93 +0ms
  13  Chromium Framework                  0x000000011a7a6511 base::MessagePumpCFRunLoopBase::RunWork() + 65 +0ms
  14  Chromium Framework                  0x000000011a79d962 base::mac::CallWithEHFrame(void () block_pointer) + 10 +0ms
  15  Chromium Framework                  0x000000011a7a5f3f base::MessagePumpCFRunLoopBase::RunWorkSource(void*) + 63 +0ms
  16  CoreFoundation                      0x00007fff20733a0c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17 +0ms
  17  CoreFoundation                      0x00007fff20733974 __CFRunLoopDoSource0 + 180 +0ms
  18  CoreFoundation                      0x00007fff207336ef __CFRunLoopDoSources0 + 248 +0ms
  19  CoreFoundation                      0x00007fff20732121 __CFRunLoopRun + 890 +0ms
  20  CoreFoundation                      0x00007fff207316ce CFRunLoopRunSpecific + 563 +0ms
  21  Foundation                          0x00007fff214befa1 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212 +0ms
  22  Chromium Framework                  0x000000011a7a6b31 base::MessagePumpNSRunLoop::DoRun(base::MessagePump::Delegate*) + 113 +0ms
  23  Chromium Framework                  0x000000011a7a58ec base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*) + 140 +0ms
  24  Chromium Framework                  0x000000011a742da6 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) + 646 +1ms
  25  Chromium Framework                  0x000000011a6f4be5 base::RunLoop::Run(base::Location const&) + 885 +0ms
  26  Chromium Framework                  0x000000011a7704dd base::Thread::Run(base::RunLoop*) + 253 +0ms
  27  Chromium Framework                  0x000000011a7709ae base::Thread::ThreadMain() + 1214 +0ms
  28  Chromium Framework                  0x000000011a798a95 base::(anonymous namespace)::ThreadFunc(void*) + 117 +0ms
  29  libsystem_pthread.dylib             0x00007fff2063b950 _pthread_start + 224 +0ms
  30  libsystem_pthread.dylib             0x00007fff2063747b thread_start + 15 +0ms
  ```

**Comment by pavelfeldman** [comment] 2021-04-04 17:23
Here is a minimal repro:

```js
const { chromium } = require('playwright');

(async () => {
  process.env.DEBUG = 'pw:browser';
  const browser = await chromium.launch();
  const page = await browser.newPage({ permissions: ['geolocation'] });
  await page.goto('https://example.com');
  await page.evaluate(() =>
    new Promise(f => {
      navigator.geolocation.getCurrentPosition(f, f);
    })
  );
  await browser.close();
})();
```

**Comment by pavelfeldman** [comment] 2021-04-05 23:13
Fix landed upstream as [r869279](https://chromium-review.googlesource.com/c/chromium/src/+/2804753)

**Comment by pavelfeldman** [comment] 2021-04-19 17:14
This should be fixed now.

**Closed by pavelfeldman** 2021-04-19 17:14 UTC
Labels: P1-resolve-asap, v1.11
