### ISSUE TITLE
[BUG] Uploading executable file in firefox browser

### ISSUE THREAD

**Issue by Ank2503** [microsoft/playwright#5695] opened 2021-03-03 09:21 UTC
**Context:**
- Playwright Version: [1.9.1]
- Operating System: [Windows 10, 1909]
- Node.js version: [14.15.5]
- Browser: [Firefox]
- Extra: [only appears in firefox]

**Code Snippet**

```javascript
const { chromium, webkit, firefox, selectors } = require('playwright');
const { performance } = require('perf_hooks');
const fs = require('fs');
const { isContext } = require('vm');

(async () => {

    for(const browserType of [firefox]) {
  
      const browser = await browserType.launch({
        headless:false,
        slowMo: 250
    });
      const browserContext = await browser.newContext({acceptDownloads: true});
      const cookies = fs.readFileSync('./cookies.json', 'utf8');

      const deserializedCookies = JSON.parse(cookies);
      await browserContext.addCookies(deserializedCookies);

      const page = await browserContext.newPage();

      await page.goto(''); //url is hidden cause link is company domain

      const [fileChooser1] = await Promise.all([
        page.waitForEvent('filechooser'),
        page.click('#upload_source')
      ]);

        await fileChooser1.setFiles('./files/7z1900-x64.exe');
        await page.waitForLoadState('networkidle');
        await page.click("text=Next");

      await browser.close();
    
    }
  })();
```
Error log is:

```
[err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    [err] JavaScript error: URL HIDDENdist/js/bundle.min.js?v=1bqvm_eslJuB39xpQPCphgOFthM6cbIepO5GnibLxfI, line 1: RangeError: invalid date    
    [err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    [err] JavaScript error: URL HIDDENdist/js/bundle.min.js?v=1bqvm_eslJuB39xpQPCphgOFthM6cbIepO5GnibLxfI, line 1: RangeError: invalid date    
    [err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    [err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    [err] JavaScript error: URL HIDDENdist/js/bundle.min.js?v=1bqvm_eslJuB39xpQPCphgOFthM6cbIepO5GnibLxfI, line 1: RangeError: invalid date    
    [err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    [err] JavaScript error: URL HIDDENdist/js/bundle.min.js?v=1bqvm_eslJuB39xpQPCphgOFthM6cbIepO5GnibLxfI, line 1: RangeError: invalid date    
    [err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    [err] JavaScript error: URL HIDDENdist/js/bundle.min.js?v=1bqvm_eslJuB39xpQPCphgOFthM6cbIepO5GnibLxfI, line 1: RangeError: invalid date    
    [err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    [err] JavaScript error: URL HIDDENdist/js/bundle.min.js?v=1bqvm_eslJuB39xpQPCphgOFthM6cbIepO5GnibLxfI, line 1: RangeError: invalid date    
    [err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    [err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    [err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    [err] JavaScript error: URL HIDDENdist/js/bundle.min.js?v=1bqvm_eslJuB39xpQPCphgOFthM6cbIepO5GnibLxfI, line 1: RangeError: invalid date    
    [err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    [err] JavaScript error: URL HIDDENdist/js/bundle.min.js?v=1bqvm_eslJuB39xpQPCphgOFthM6cbIepO5GnibLxfI, line 1: RangeError: invalid date    
    [err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    [err] JavaScript error: URL HIDDENdist/js/bundle.min.js?v=1bqvm_eslJuB39xpQPCphgOFthM6cbIepO5GnibLxfI, line 1: RangeError: invalid date    
    [err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    [err] JavaScript error: URL HIDDENdist/js/bundle.min.js?v=1bqvm_eslJuB39xpQPCphgOFthM6cbIepO5GnibLxfI, line 1: RangeError: invalid date    
    [err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    [err] JavaScript error: URL HIDDENdist/js/bundle.min.js?v=1bqvm_eslJuB39xpQPCphgOFthM6cbIepO5GnibLxfI, line 1: RangeError: invalid date    
    [err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    [err] JavaScript error: URL HIDDENdist/js/bundle.min.js?v=1bqvm_eslJuB39xpQPCphgOFthM6cbIepO5GnibLxfI, line 1: RangeError: invalid date    
    [err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    [err] JavaScript error: URL HIDDENdist/js/bundle.min.js?v=1bqvm_eslJuB39xpQPCphgOFthM6cbIepO5GnibLxfI, line 1: RangeError: invalid date    
    [err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    [err] JavaScript error: URL HIDDENdist/js/bundle.min.js?v=1bqvm_eslJuB39xpQPCphgOFthM6cbIepO5GnibLxfI, line 1: RangeError: invalid date    
    [err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    [err] JavaScript error: URL HIDDENdist/js/bundle.min.js?v=1bqvm_eslJuB39xpQPCphgOFthM6cbIepO5GnibLxfI, line 1: RangeError: invalid date    
    [err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    [err] JavaScript error: URL HIDDENdist/js/bundle.min.js?v=1bqvm_eslJuB39xpQPCphgOFthM6cbIepO5GnibLxfI, line 1: RangeError: invalid date    
    [err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 771: NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISeekableStream.seek]
    <gracefully close start>
    [err] JavaScript error: jar:file:///C:/Users/a.kurochkin/AppData/Local/ms-playwright/firefox-1234/firefox/omni.ja!/components/juggler.js, line 102: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIRemoteDebuggingPipe.sendMessage]
    [err] JavaScript error: jar:file:///C:/Users/a.kurochkin/AppData/Local/ms-playwright/firefox-1234/firefox/omni.ja!/components/juggler.js, line 102: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIRemoteDebuggingPipe.sendMessage]
    [err] JavaScript error: jar:file:///C:/Users/a.kurochkin/AppData/Local/ms-playwright/firefox-1234/firefox/omni.ja!/components/juggler.js, line 102: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIRemoteDebuggingPipe.sendMessage]
    [err] JavaScript error: URL HIDDEN, line 6: NS_ERROR_NOT_INITIALIZED:       
    [err]
    [err] ###!!! [Child][MessageChannel] Error: (msgtype=0x6B0027,name=PNecko::Msg_RemoveRequestContext) Channel closing: too late to send/recv, messages will be lost
    [err]
    [err]
    [err] ###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
    [err]
    [err]
    [err] ###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
    [err]
    =========================== logs ===========================
    waiting for selector "text=Next"
```

**Describe the bug**

If I want to upload .exe files in firefox, it looks weird: there`s a progress bar on file uploading status and it goes like 10%-100%-20%-100%-30%-10%-40%... and keeps coming until timeout reach. This only occurs in firefox browser, tried different version (1.7.0,1.8.1,1.9.1), if i try to upload different extension (.jpg,.html etc) it works fine.

**Comment by Ank2503** [comment] 2021-03-26 09:50
I've make some research on this problem, and there`s something with "Upload?token" response: it keeps making responses until it reaches 200 status. 
![image](https://user-images.githubusercontent.com/59288723/112613966-625d0a00-8e29-11eb-8a28-212276c21c19.png).

**Comment by aslushnikov** [comment] 2021-05-13 21:19
@Ank2503 This was a dupe of https://github.com/microsoft/playwright/issues/4704 and should be fixed now on tip-of-tree!

**Closed by aslushnikov** 2021-05-13 21:19 UTC
Labels: P2-bug
