### ISSUE TITLE
FireFox browser in local tested good, but failed to open in IIS

### ISSUE THREAD

**Issue by kingsley967** [microsoft/playwright#12283] opened 2022-02-22 09:07 UTC
```Exception: 
System.TimeoutException: Timeout 30000ms exceeded.
=========================== logs ===========================
<launching> C:\Windows\system32\config\systemprofile\AppData\Local\ms-playwright\firefox-1304\firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Windows\TEMP\playwright_firefoxdev_profile-nGhAlE -juggler-pipe -silent
<launched> pid=25444
[pid=25444][err] Error: Access was denied while trying to open files in your profile directory.
[pid=25444][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[pid=25444][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[pid=25444][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[pid=25444][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[pid=25444][out] Crash Annotation GraphicsCriticalError: |[G0][GFX1-]: shader-cache: Shader disk cache is not supported (t=2.2087) [GFX1-]: shader-cache: Shader disk cache is not supported
[pid=25444][err] [2022-02-22T07:51:47Z ERROR webrender_bindings::program_cache] shader-cache: Shader disk cache is not supported
[pid=25444][out] Crash Annotation GraphicsCriticalError: |[G0][GFX1-]: shader-cache: Shader disk cache is not supported (t=2.2087) |[G1][GFX1-]: RcANGLE(no compositor window) (t=2.2087) [GFX1-]: RcANGLE(no compositor window)
[pid=25444][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Failed to connect WebRenderBridgeChild. (t=4.64253) [GFX1-]: Failed to connect WebRenderBridgeChild.
[pid=25444][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Failed to connect WebRenderBridgeChild. (t=4.64253) |[1][GFX1-]: Fallback WR to SW-WR + D3D11 (t=4.80253) [GFX1-]: Fallback WR to SW-WR + D3D11
[pid=25444][out] Crash Annotation GraphicsCriticalError: |[G0][GFX1-]: shader-cache: Shader disk cache is not supported (t=2.2087) |[G1][GFX1-]: RcANGLE(no compositor window) (t=2.2087) |[G2][GFX1-]: [D3D11] create swap chain failed: 0x887a0022, 0 (t=2.3687) [GFX1-]: [D3D11] create swap chain failed: 0x887a0022, 0
[pid=25444][out] Crash Annotation GraphicsCriticalError: |[G0][GFX1-]: shader-cache: Shader disk cache is not supported (t=2.2087) |[G1][GFX1-]: RcANGLE(no compositor window) (t=2.2087) |[G2][GFX1-]: [D3D11] create swap chain failed: 0x887a0022, 0 (t=2.3687) |[G3][GFX1-]: Failed to initialize CompositorD3D11 for SWGL: FEATURE_FAILURE_D3D11_SWAP_CHAIN (t=2.3687) [GFX1-]: Failed to initialize CompositorD3D11 for SWGL: FEATURE_FAILURE_D3D11_SWAP_CHAIN
[pid=25444][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
============================================================
   at Microsoft.Playwright.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args)
   at Microsoft.Playwright.Core.BrowserType.LaunchAsync(BrowserTypeLaunchOptions options)
   at SC.BankTransferMimic.Engine.Banks.BankBase.Initialize(String browser) in C:\SigmaCoders\SC.BankTransferMimic\SC.BankTransferMimic.Engine\Banks\BankBase.cs:line 43
   at SC.BankTransferMimic.Engine.Banks.Malaysia.CIMBBankFactory.NewBankAsync() in C:\SigmaCoders\SC.BankTransferMimic\SC.BankTransferMimic.Engine\Banks\Malaysia\CIMBBankFactory.cs:line 16
   at SC.BankTransferMimic.Engine.Banks.BankProvider.NewSessionAsync(String bankId, String merchantId) in C:\SigmaCoders\SC.BankTransferMimic\SC.BankTransferMimic.Engine\Banks\BankProvider.cs:line 52
   at Program.<>c.<<<Main>$>b__0_1>d.MoveNext() in C:\SigmaCoders\SC.BankTransferMimic\SC.BankTransferMimic.Engine\Program.cs:line 60
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass46_3.<<HandleRequestBodyAndCompileRequestDelegate>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)`

**Comment by mxschmitt** [comment] 2022-02-22 10:06
Duplicate of https://github.com/microsoft/playwright-dotnet/issues/2026

Please don't create multiple issues.

**Closed by mxschmitt** 2022-02-22 10:06 UTC
