### ISSUE TITLE
[BUG] SVG elements are always considered visible despite display:none

### ISSUE THREAD

**Issue by mwisniewski-psi** [microsoft/playwright#26701] opened 2023-08-25 10:18 UTC
### System info
- Playwright Version: [v1.37.1]
- Operating System: [Windows 10]
- Browser: [Chromium]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.
```js
const { test, expect } = require("@playwright/test");

test("should not show text", async ({ page }) => {
  const html = `
    <svg>
        <g display='none'>
            <text x='50' y='100' font-size='28' fill='#000000'>Test String</text>
        </g>
    </svg>
`;
  await page.goto("data:text/html," + encodeURIComponent(html));
  await page.waitForTimeout(1000);
  expect(page.locator("g")).toBeHidden();
  expect(page.getByText("Test String")).toBeHidden();
});
```

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Steps**
- [Run the test]
- [Test fails despite the <g> element and elements inside it to be hidden]

**Expected**

Test passes

**Actual**

Test fails
```
                                       
expect(received).toBeHidden()
Call log:
  - expect.toBeHidden with timeout 5000ms
  - waiting for locator('g')
  -   locator resolved to <g display="none">…</g>
  -   unexpected value "visible"
  -   locator resolved to <g display="none">…</g>
  -   unexpected value "visible"
14
  expect(page.getByText("Test String")).toBeHidden();
                                                     
expect(received).toBeHidden()
Call log:
  - expect.toBeHidden with timeout 5000ms
  - waiting for getByText('Test String')
  -   locator resolved to <text x="50" y="100" font-size="28" fill="#000000">Test String</text>
  -   unexpected value "visible"
  -   locator resolved to <text x="50" y="100" font-size="28" fill="#000000">Test String</text>
  -   unexpected value "visible"
```

**Comment by dgozman** [comment] 2023-08-25 22:29
I believe this is specific to svg `<text>` elements. Duplicate of #23300.

**Closed by dgozman** 2023-08-25 22:29 UTC
Labels: v1.38
