### ISSUE TITLE
feature: teach codegen to click off center of elements

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#13512] opened 2022-04-13 00:54 UTC
**Context:**
- Playwright Version:1.20.2
- Operating System: Mac
- Node.js version: 12.22
- Browser: Chromium
- Extra: [any specific details about your environment]

**Describe the bug**
Our site has an expandable accordion that has some text and a tooltip icon which displays info on hover. When we click the text on accordion to expand it, codegen keeps jumping around and highlights the icon every time. I think it is specific to the way our layout is with tooltip. Whenever someone triage this issue, please let me know I can share the video recorded for this issue and the url to reproduce it privately (via slack).

Thanks!

**Comment by aslushnikov** [comment] 2022-04-13 19:28
@Nav-2d hit me up on slack!

**Comment by Nav-2d** [comment] 2022-04-13 21:35
Done!

**Comment by aslushnikov** [comment] 2022-04-13 22:52
After a private discussion, I was able to reproduce this with the following demo page:

<img width="306" alt="image" src="https://user-images.githubusercontent.com/746130/163282465-a3e37c69-bba8-4483-ae31-99a4a792e1a8.png">

- Clicking anywhere on blue will toggle the button and make it red
- Clicking anywhere on grey will be consumed

<img width="306" alt="image" src="https://user-images.githubusercontent.com/746130/163282519-cab54a57-eaba-44a2-bc96-0bf74dff571a.png">

In our codegen, we always aim in the middle of the button, so we always click in the grey area. So it is impossible to actually
toggle the button with codegen.

try by yourself:

```bash
$ npx playwright codegen file://${PWD}/demo.html
```

Where `demo.html` is:


```html
<!DOCTYPE HTML>
<style>
  .box {
    box-sizing: border-box;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .button {
    cursor: pointer;
    width: 400px;
    height: 100px;
    background-color: blue;
    border: 5px solid black;
  }

  .button.toggled {
    background-color: red;
  }

  .event_swallower {
    width: 50px;
    height: 50px;
    background-color: grey;
    color: white;
    font-family: arial;
    font-size: 48px;
  }
</style>
<div class="box button">
  <div class="box event_swallower">∅</div>
</div>

<script>
  const btn = document.querySelector('.button');
  btn.addEventListener('click', () => btn.classList.toggle('toggled'), false);
  document.querySelector('.event_swallower').addEventListener('click', event => {
    event.stopPropagation();
    event.preventDefault();
  }, false);
</script>
```

**Comment by pavelfeldman** [comment] 2022-10-20 06:25
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-10-20 06:25 UTC
Labels: P3-collecting-feedback, feature-codegen
