### ISSUE TITLE
[BUG] Node 20: Test timeouts do not exit gracefully

### ISSUE THREAD

**Issue by gtm-nayan** [microsoft/playwright#22641] opened 2023-04-26 05:12 UTC
### System info
- Playwright Version: v1.32.3
- Operating System: Ubuntu 22
- Browser: Chromium, Firefox
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  webServer: {
    command: 'node webserver.js',
    port: 4173,
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

```js
// webserver.js
import { createServer } from 'node:http';
createServer((req, res) => {}).listen(4173);

```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await new Promise(r => setTimeout(r, 25000));
});
```

**Steps**
- Run the test

**Expected**
test failure is reported, webserver is closed

**Actual**
exits without any message, test remains unmarked, webserver remains open

**Comment by gtm-nayan** [comment] 2023-04-26 12:39
Narrowed it down to a node bug https://github.com/nodejs/node/issues/47566 that's been fixed in nightly with https://github.com/nodejs/node/pull/47620

Going to keep this issue open because 

https://github.com/microsoft/playwright/blob/44e56d24048017f77cbcc93a916939906188b722/packages/playwright-test/src/cli.ts#L265-L268

should likely be adjusted to make it easier to diagnose any similar regressions in the future and to exit any other child processes started by the cli (eg. webserver).

**Comment by dgozman** [comment] 2023-04-26 21:55
This specific place does not really spawn child processes like webserver or test worker. It restarts itself with some more options, and mirrors the exit. I don't see what should we do differently here.

@gtm-nayan Do you have a particular improvement in mind?

**Comment by aslushnikov** [comment] 2023-04-26 21:59
This is actually working as intended; if the inner process crashes here, than the program is in invalid state. Killing the whole process tree would only hide the behavior under the carpet. 

Since we already exit with a non-zero code, the error should be surfaced well-enough for us to debug later.

I'll close this since we believe the current behavior is optimal.

**Closed by aslushnikov** 2023-04-26 21:59 UTC
Labels: v1.34

**Comment by gtm-nayan** [comment] 2023-04-27 01:55
> This specific place does not really spawn child processes like webserver or test worker.

Ahh, sorry I have misunderstood that part then.

There's a race condition somewhere still, sometimes the worker process will receive a SIGKILL, it'll log that the worker process exited unexpectedly, the webserver will get cleaned up and that forked process will exit with a `1` code.

Other times, the forked process from the linked snippet will be closed before anything is logged. The close event handler receives a code of null and a SIGKILL signal. And in that case, the webserver will leak as well.

The setup with the loop from #22643 is a bit more reliable in reproducing that case.
