### ISSUE TITLE
[Bug]: Hydration issues when using httpCredentials

### ISSUE THREAD

**Issue by cyrus-afshari** [microsoft/playwright#32750] opened 2024-09-21 17:40 UTC
### Version

1.43.1

### Steps to reproduce

I cannot give out my company's test environment details where this is occurring, and wasn't able to find a public website on the internet that has both: basic authentication required, and input field forms. However, with that aside, the steps would be:

1. Provide httpCredentials in your test "use" object through testConfig.use or testProject.use
2. Write a test that uses those httpCredentials to provide basic auth to access a website
3. In the test, use the fill() method to populate text in an input field

sample playwright.config:
```
import { defineConfig, devices } from '@playwright/test';
export default defineConfig({
    projects: [
        {
            name: 'uat2',
            use: {
                ...devices['Desktop Chrome'],
                baseURL: '<redacted>',
                httpCredentials: {
                    username: 'myUser',
                    password: 'myPass',
                  },
                // extraHTTPHeaders: {     // commented out, including as a reference
                //     Authorization: `Basic ${btoa('myUser:myPass')}`
                // }
            }
        }
    ]})
```
sample test.spec.ts:
```
test('test using httpCredentials', async ({ page }) => {
        await page.goto('/');
        await page.getByTestId('signInBtn').click();
        await page.getByTestId('emailField').fill('customerEmail@abc.com');
        await page.getByTestId('passwordField').fill('customerPassword123');
        await page.getByTestId('submitBtn').click();
  });
```

### Expected behavior

The desired text is entered into the field and remains in the field

### Actual behavior

Seemingly, Playwright acts too quickly, and the text only is put in the field for a split second, or not at all - I have witnessed this by examining the timeline of the Trace. It very clearly seems to be identical to the symptoms described in Playwright's ["Hydration" documentation](https://playwright.dev/docs/navigations#hydration). 

### Additional context

This part is very important: **I can only reproduce this issue when I use httpCredentials.** Until now, I was using `extraHTTPHeaders` to provide my Basic Auth username and password to the website. I now need to use `httpCredentials` instead of `extraHTTPHeaders` to provide the website's basic auth credentials, because using extraHTTPHeaders is causing an issue where a certain endpoint that gets hit via the backend of the UI is supposed to take in the user's token (the application under test's login token, not the website's basic auth token), transform it to a token for their own system, and then make another call to their endpoint with their transformed token as an Authentication header - however that call is not including an Authorization header with their transformed token because Playwright is already including the Authorization header that I told it to provide via `extraHTTPHeaders`. 

I've run my entire regression (around 90 tests) many times, sometimes providing the Authorization header via `extraHTTPHeaders`, and other times via `httpCredentials`, to try to definitively isolate the issue. I **only** run into these hydration issues when I run using the `httpCredentials` instead of providing Authorization via `extraHTTPHeaders`. I don't change a single other thing when running the tests; just changing between the two ways of providing the auth. So I have almost definitively pinpointed it to `httpCredentials`.

From Playwright's "Hydration" documentation:
> A simple way to verify if your page suffers from a poor hydration is to open Chrome DevTools, pick "Slow 3G" network emulation in the Network panel and reload the page. Once you see the element of interest, interact with it. You'll see that the button clicks will be ignored and the entered text will be reset by the subsequent page load code. The right fix for this issue is to make sure that all the interactive controls are disabled until after the hydration, when the page is fully functional.

I tried this as well ^ used "3G" in Chrome DevTools, loaded the page fresh and tried to input text as quickly as I possibly could as a human, but couldn't reproduce the potentially-poor hydration that way. I can't point to poor hydration as the issue, because as mentioned when I use extraHTTPHeaders instead to provide the Authentication header, I have never had these issues, and I've been running these tests daily for 5 months now this way.

Seems similar to https://github.com/microsoft/playwright/issues/26331

One last piece of additional context that could be useful is that the other failure reason I see happen (on tests that don't happen to arbitrarily run into the aforementioned hydration issue), that is also specific to when I use `httpCredentials`, is a test timeout where I'm using `await this.page.waitForLoadState('networkidle');` I do see in the docs that 'networkidle' is discouraged, but I'm only using it in 1 specific place, and until now that I'm trying to use `httpCredentials`, it has worked without issue for me. 

### Environment

```shell
System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 2.59 GB / 36.00 GB
  Binaries:
    Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
    pnpm: 8.15.8 - /usr/local/bin/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.43.1 => 1.43.1
```

**Comment by yury-s** [comment] 2024-09-23 18:39
What is the exact request from Playwright? Sorry but I cannot figure it out from the description of the problem. If this is a hydration problem we recommend fixing it in the page or waiting for a particular app-specific signal before performing actions.

It may be a hydration issue or something else, we need a reproducible example to take an action on this report.

>  can only reproduce this issue when I use httpCredentials. Until now, I was using extraHTTPHeaders to provide my Basic Auth username and password to the website. 

If the problem doesn't reproduce with extraHTTPHeaders, you can try manually adding authorization header only to some requests via [route.continue()](https://playwright.dev/docs/network#modify-requests), this way you can control if they are added to the API requests.

**Comment by cyrus-afshari** [comment] 2024-09-23 19:41
> What is the exact request from Playwright? Sorry but I cannot figure it out from the description of the problem. 

The Playwright request which doesn't execute successfully (even though the step in the report shows as successful, and moves onto the rest of the script) is `await page.getByTestId('emailField').fill('customerEmail@abc.com');` Tests which rely on logging into the application fail, because the Submit button never becomes enabled, so the `.click()` on that element keeps trying that click until the test times out (since I didn't provide a timeout for the `.click()`). It's not always the same tests, or same amount of tests, it's just arbitrary.

> If the problem doesn't reproduce with extraHTTPHeaders, you can try manually adding authorization header only to some requests via [route.continue()](https://playwright.dev/docs/network#modify-requests), this way you can control if they are added to the API requests.

This project is wholly UI testing. Would this workaround still be possible?

**Comment by yury-s** [comment] 2024-09-23 22:46
> The Playwright request which doesn't execute successfully (even though the step in the report shows as successful, and moves onto the rest of the script) is await page.getByTestId('emailField').fill('customerEmail@abc.com'); Tests which rely on logging into the application fail, because the Submit button never becomes enabled, so the .click() on that element keeps trying that click until the test times out (since I didn't provide a timeout for the .click()). It's not always the same tests, or same amount of tests, it's just arbitrary.

As far as I understand, you consider result of `fill` a failure because the field is later cleared by some code in the page and the submit button doesn't work. If you think this is a bug on Playwright end, please provide a repro, otherwise follow our guidance for the hydration issues and try to fix the page or wait until a proper moment to fill out the form.


> This project is wholly UI testing. Would this workaround still be possible?

You can use url pattern to only intercept requests that you want to add headers to.

**Comment by cyrus-afshari** [comment] 2024-09-24 16:10
> If you think this is a bug on Playwright end, please provide a repro, otherwise follow our guidance for the hydration issues and try to fix the page or wait until a proper moment to fill out the form.
 
> You can use url pattern to only intercept requests that you want to add headers to.

Sadly I wouldn't be allowed to reveal my company's test environment details, so I can't give a reproducible project to run. I've isolated the issue to using httpCredentials though. If PW team won't investigate, I will just proceed to trying out the workaround you mentioned. Can you give some more details on "You can use url pattern to only intercept requests that you want to add headers to."?

**Comment by yury-s** [comment] 2024-09-24 18:04
> Sadly I wouldn't be allowed to reveal my company's test environment details, so I can't give a reproducible project to run. 

Unfortunately, we cannot debug the issue without a repro, so closing this report. Feel free to file a new issue if you manage to narrow down the test to a project that you could share with us.

>  Can you give some more details on "You can use url pattern to only intercept requests that you want to add headers to."?

See our docs for [page.route()](https://playwright.dev/docs/api/class-page#page-route) and network mocking [section](https://playwright.dev/docs/network).

**Closed by yury-s** 2024-09-24 18:04 UTC
