### ISSUE TITLE
Here is a [guide for launching a Chrome Extension](https://playwright.dev/docs/chrome-extensions). There is no built-in support for extension in Playwright Test Runner, so you'll have to launch the browser yourself.

### ISSUE THREAD

**Issue by raiajithkumarr** [microsoft/playwright#13918] opened 2022-05-04 05:45 UTC
Here is a [guide for launching a Chrome Extension](https://playwright.dev/docs/chrome-extensions). There is no built-in support for extension in Playwright Test Runner, so you'll have to launch the browser yourself.

_Originally posted by @dgozman in https://github.com/microsoft/playwright/issues/13869#issuecomment-1116097537_

**Comment by raiajithkumarr** [comment] 2022-05-04 05:45
Hi @dgozman
In that document they are taking about custom extension but for our scenario we required "Windows Accounts" extension to be installed while running test and how we can achieve this ?
Could you provide information related to it.

**Comment by dgozman** [comment] 2022-05-04 06:03
@raiajithkumarr Unfortunately, there is no special support for such extensions. Playwright runs Chromium browser by default that does not have any extensions, so you'll have to install the ones you are interested in, following the guide above. Does that answer your question?

**Comment by raiajithkumarr** [comment] 2022-05-04 09:06
In my Chrome I have already installed this extension and also enabled to run in private mode also but still it is not found by playwright chrome browser.

@dgozman as you mentioned, as per this document [my-extension](https://playwright.dev/docs/chrome-extensions) and https://github.com/microsoft/playwright/tree/5ba7903ba098586a13745e0d7ac894f1d55d47aa/tests/assets/simple-extension 

how to corelate above with this extension Windows Accounts, So that I can install and run test cases

**Comment by dgozman** [comment] 2022-05-04 09:11
@raiajithkumarr Playwright does not run your Google Chrome by default. You can [use a channel](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge) to run Google Chrome already installed on your computer. Then it should have all your pre-installed extensions.

**Comment by raiajithkumarr** [comment] 2022-05-04 09:32
Currently Playwright is in not identifying my installed Google chrome version with extension.
Did I miss any configuration please correct me.

Playwright.config.ts
import { PlaywrightTestConfig,devices  } from "@playwright/test";

const config: PlaywrightTestConfig = {
  globalSetup: require.resolve("./e2e/globalSetup"),
  retries: 1,
  testDir:"./e2e",
  workers: 3,
  timeout: 120000,
  use: {
    headless: false,
  
    baseURL:"https://testURI.com",
    storageState: './e2e/state.json',
    // Tell all tests to load signed-in state from 'storageState.json'.
    screenshot: "off", // this to be enabled later.
  }
  // ,
  // projects: [
  //   {
  //     name: 'Microsoft Edge',
  //     use: {
  //       // Supported Microsoft Edge channels are: msedge, msedge-beta, msedge-dev, msedge-canary
  //       channel: 'msedge',
  //     },
  //   }
  // ],
};
export default config;


========globalSetup.ts======



import { chromium } from '@playwright/test';
import { SignPage } from './sign-page-model';
async function globalSetup() {
  
  const browser = await chromium.launch({
    headless: false,
    channel: 'chrome',

});

const context = await browser.newContext();
const page = await context.newPage();
const sign = new SignPage(page);
await sign.login();
await context.storageState({ path: './e2e/state.json' });
await browser.close();
}
export default globalSetup;

**Comment by dgozman** [comment] 2022-05-04 09:39
@raiajithkumarr It is hard to tell what you are trying to achieve from your snippets. I see you pass `channel: 'chrome'` in global setup, but not in your `playwright.config.ts`. If you'd like your tests to run in Google Chrome, pass `channel` in the config (as explained in the documentation).

**Comment by raiajithkumarr** [comment] 2022-05-04 09:55
Yes update playwright.config.ts also still it is using Playwright chrome browser.

Here our main problem is Playwright launched Chrome browser doesn't have any extension( Windows Accounts ) required by my project.

Please let us know how can we achieve this ?

**Comment by dgozman** [comment] 2022-05-04 10:13
Let me take a step back and explain what I understood from this conversation.

1. You would like to run some tests that require "Windows Accounts" extension.
2. Our default solution is explained in [this guide](https://playwright.dev/docs/chrome-extensions). It requires you to have this extension unpacked and available, and also launch the browser yourself as explained. If you don't have that, it is not going to work.
3. As a workaround, you can use Google Chrome that you pre-configure however you'd like. This requires a few things:
    - Using `channel: 'chrome'` as describe in [this guide](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge).
    - Launching browser manually with [`chromium.launchPersistentContext()`](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context).
    - Figuring out the correct [`userDataDir`](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context-option-user-data-dir) that you have manually configured above.
    - Closing all existing Chrome windows before running Playwright, so that it is able to launch a new Chrome process.

> Yes update playwright.config.ts also still it is using Playwright chrome browser.

If you believe that `channel: 'chrome'` does not work, please file a separate issue with a repro. However, most likely the issue is in configuration, so I'd suggest to first double-check that you follow the guide closely.

**Comment by raiajithkumarr** [comment] 2022-05-04 10:18
As per point 2 : How to get this :  It requires you to have this extension unpacked 
We want these test cases should run as a part of CI/CD pipeline but as per my knowledge Point 3 doesn't support this feature.

**Comment by dgozman** [comment] 2022-05-04 10:45
> As per point 2 : How to get this : It requires you to have this extension unpacked

Since I don't know anything about your extension, I have no idea, sorry.

> We want these test cases should run as a part of CI/CD pipeline but as per my knowledge Point 3 doesn't support this feature.

Yeah, manual setup is not really compatible with CI/CD.

**Comment by raiajithkumarr** [comment] 2022-05-04 11:23
Okay @dgozman Thank you on this I will check with my team.
Is there anyway to open a browser in normal mode instead of private mode by using playwright config ?

**Comment by dgozman** [comment] 2022-05-04 11:26
> Is there anyway to open a browser in normal mode instead of private mode by using playwright config ?

Not today, but there is an open issue: #11833.

**Comment by mxschmitt** [comment] 2022-05-09 09:24
Closing as per above. For further issues please file new issues.

**Closed by mxschmitt** 2022-05-09 09:24 UTC
Labels: triaging
