### ISSUE TITLE
[BUG] isVisible returns false, although the web element is on the page

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#26502] opened 2023-08-16 17:08 UTC
### System info
- Playwright Version: 1.36.2
- Operating System: All
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

 Although the element is visible on the webpage it returns false.  can you please advise?

```javascript
//Login screen - username is visible like the screenshot below.
console.log("VALUE" + await page.locator('#username').isVisible())

 if (await page.locator('#username').isVisible()) {
            console.log("ReLogin")
//If username is visible, i want to relogin here.

              }
```

<img width="668" alt="Screen Shot 2023-08-16 at 12 07 43 PM" src="https://github.com/microsoft/playwright/assets/113629123/5ce15227-6604-41f8-ade4-2a4862c0124c">

**Comment by philipfong** [comment] 2023-08-16 22:08
Perhaps you might want to persist the value first instead of having the call to await within the `if` statement

```
const isUserNameFieldVisible: boolean = await page.locator('#username').isVisible()
if (isUserNameFieldVisible) {
  ..
}
```

**Comment by InduKrish** [comment] 2023-08-17 12:30
After i add page.waitforTimoeut(2000), it returned true, Shall i use any better wait instead of page.waitforTimeout ?can you please advise?

**Comment by mxschmitt** [comment] 2023-08-17 16:14
You can either use `waitForTimeout` if you want to wait `Xms` until you want to check if its visible or not or you use `locator.waitFor({ state: 'visible' })` if you want to wait until its visible, which would then wait forever (until the test times out), so its only helpful if you want to wait for the element to be visible.

**Comment by DanielSpindler** [comment] 2023-08-18 14:29
> await page.locator('#username').waitFor({state: 'attached'});
> console.log("VALUE" + await page.locator('#username').isVisible());
> 

to make sure it is in the DOM. fixxed values with "waitForTimeout" waste either time or dont wait long enough... waitForTimeout should always be a last resort.

**Comment by yury-s** [comment] 2023-08-22 01:00
Alternatively, you can call [expect.toBeVisible](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-be-visible) which will automatically wait until the element becomes visible. Closing this report as it is not a bug in playwright but rather an issue with the test.

**Closed by yury-s** 2023-08-22 01:00 UTC
Labels: triaging

**Comment by adam-eichelkrautctpg** [comment] 2024-12-12 14:18
For anyone else that runs into this issue, it turned out that I was just missing the `await` keyword at the beginning. See these two:
```typescript
// This didn't work
expect(page.getByText('Welcome')).toBeVisible()

// This worked
await expect(page.getByText('Welcome')).toBeVisible()
```

Highly suggest maybe adding a linting rule to your repo to ensure catching these easier :)
