### ISSUE TITLE
[BUG] Testing service worker code is flaky

### ISSUE THREAD

**Issue by gilles-yvetot** [microsoft/playwright#12103] opened 2022-02-15 01:01 UTC
**Context:**
- Playwright Version: 1.19
- Operating System: Mac
- Node.js version: 16.13.1
- Browser: Chromium

**Describe the bug**

My team and I start migrating our web extension to Manifest V3, because [Chrome will deprecate version 2 at some point](https://developer.chrome.com/blog/mv2-transition/). The philosophy of web extensions changes drastically and background scripts are now service workers that are spawn on-demand then "killed".  
We re-wrote our tests to be able to evaluate code within the service worker. And that is working fine most of the time. But sometimes, the service worker is shut down and is not able to be re-spawn when an event is thrown at it like it used to. Our guess is that maybe PW is keeping a reference of it somewhere?
We end up with flaky tests that fail randomly. I understand extension testing is not the main focus of this lib so I am more than willing to help to find a solution here and open PRs if needed.
I have not tested with service workers outside of the web extension scope but it is probably affected as well

**Code Snippet**

- launch chrome with the following flags: `--remote-debugging-port=46666 --load-extension=/path-to-extension`
- the following extension and script should show you a basic example of a service worker
- then to simulate the service worker being shut down, visit [chrome://serviceworker-internals](chrome://serviceworker-internals) and stop the associated service worker
- reload the page and try to click on the extension, it does not work anymore. It does work when not connected with Playwright though

`sw.js`
```javascript
chrome.action.onClicked.addListener((tab) => {
	chrome.scripting.executeScript({
		target: { tabId: tab.id },
		function: ()=>{
                    document.body.style.backgroundColor = "red"
                },
	});
})
```

`manifest.json`
```json
{
	"name": "Page Redder",
	"action": {},
	"manifest_version": 3,
	"version": "0.1",
	"description": "Turns the page red when you click the icon",
	"permissions": [
		"activeTab",
		"scripting"
	],
	"background": {
		"service_worker": "sw.js"
	}
}
```

```javascript
const { chromium } = require("playwright-core");
const endpoint = "http://localhost:46666";

(async () => {
	const browser = await chromium.connectOverCDP(endpoint);
	const [context] = await browser.contexts();
	// open google.com and click on the extension to to see background color to change to red
	const page = await context.newPage();
	await page.goto(`https://google.com`);
})()
```

**Comment by dgozman** [comment] 2022-02-15 04:39
@gilles-yvetot Thank you for the detailed issue! Unfortunately, as you've already said, this is not currently a priority for Playwright. Most likely, the issue is upstream in Chromium - there is a lot of trickery around service workers shutdown/restart interacting with debugging, not to mention special handling of extension service workers. I will leave this issue open, but it's unlikely this will be fixed soon.

**Comment by maustin** [comment] 2022-03-14 23:42
It appears the issue is having a CDP connection open with the extension's service worker.

We found a workaround by adding this patch to crBrowser `_onAttachedToTarget`:
```
if (targetInfo.type === `service_worker` && targetInfo.url.includes(SERVICE_WORKER_ID)) {
  session._sendMayFail('Runtime.runIfWaitingForDebugger').then(() => {
    this._session._sendMayFail('Target.detachFromTarget', {
      sessionId
    });
  });

  return
}
```

By immediately detaching from the worker, it appears Chrome is able to maintain its ability to stop and restart the worker.

**Closed** 2022-10-20 06:13 UTC
Labels: P3-collecting-feedback
