### ISSUE TITLE
WARNING: Timed out while waiting for driver process to exit

### ISSUE THREAD

**Issue by mridiniveni** [microsoft/playwright#18881] opened 2022-11-17 11:21 UTC
Hi, I am new to playwright and i see scripts are executing pretty fast but its taking time to close the browser after completion of script execution 
   i am using the maven dependency 
<dependency>
            <groupId>com.microsoft.playwright</groupId>
            <artifactId>playwright</artifactId>
            <version>1.27.1</version>
        </dependency>

**Comment by pavelfeldman** [comment] 2022-11-17 17:14
Which browser are you using? Do you use the browser channel?

**Comment by imartinflores** [comment] 2022-11-17 19:20
This is probably related to what happened to me as well? I raised it [here ](https://github.com/microsoft/playwright/issues/17869),  after trying it multiple times, I could see the problem was after the test when closing the browser. In my case I was waiting for a url redirection, the "expect" passed (validating the new url), but the browser remained opened loading the page and it was throwing this:

"Test timeout of 30000ms exceeded while tearing down "context"

**Comment by mridiniveni** [comment] 2022-11-21 09:21
> This is probably related to what happened to me as well? I raised it [here ](https://github.com/microsoft/playwright/issues/17869), after trying it multiple times, I could see the problem was after the test when closing the browser. In my case I was waiting for a url redirection, the "expect" passed (validating the new url), but the browser remained opened loading the page and it was throwing this:
> 
> "Test timeout of 30000ms exceeded while tearing down "context"
> 
> If it has nothing to do, ignore my message, thought to share in case it can help :)

**Comment by mridiniveni** [comment] 2022-11-21 09:22
Exactly similar issue i am facing  @imarntinflores

**Comment by mridiniveni** [comment] 2022-11-21 09:23
> Which browser are you using? Do you use the browser channel?

BrowserType browserType = playWright.chromium();
        browserContext = browserType.launch(new BrowserType.LaunchOptions().setChannel("chrome").setHeadless(false)).newContext();
        page = browserContext.newPage();

**Comment by imartinflores** [comment] 2022-11-21 10:50
hey @mridiniveni ! I was not using the channel, directly with chromium. Double-check if you don't have any unresolved/pending promises somewhere.
@pavelfeldman is it the correct behavior for WaitForUrl() to keep waiting till the page loads even if the URL has already changed?

**Comment by pavelfeldman** [comment] 2022-11-21 16:16
@imartinflores your issue seems to be different

@mridiniveni your company has an enterprise policy that enforces and changes the way Chrome works. It injects scripts and changes shutdown routines. It can't be worked around, you should not test using Chrome w/ this policy because that's not what users will get when they open your page. Chrome only respects this policy in headed mode when running branded browser, your exact use case.

**Comment by imartinflores** [comment] 2022-11-22 22:52
@pavelfeldman thanks. In that case, is it expected behaviour from Playwright to keep waiting until the page loads ?

I'm doing this just to double check we are redirected to a particular page:

`await page.waitForUrl('**/testing')`

However, I noticed that even the redirection is quick, it keeps waiting till the url is loaded completely, is there anyway to avoid that, or anyway to check the different behaviour in a different way ?

Thank you!

**Closed** 2022-11-28 17:16 UTC
Labels: triaging
