### ISSUE TITLE
[Question]: Playwright: apiRequestContext.post: self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by jesa1499** [microsoft/playwright#14440] opened 2022-05-27 09:24 UTC
### Your question

When trying to hit post api call, getting this error in Playwright (JavaScript). How can i resolve this error?

**Comment by mxschmitt** [comment] 2022-05-27 09:36
When creating a new request context, you can pass `ignoreHTTPSErrors : true`. If you are using Playwright Test, then you can pass `ignoreHTTPSErrors: true` inside your config under the `use: { ignoreHTTPSErrors: true }` block and it should work when using `page.request` or `context.request`.

**Comment by yury-s** [comment] 2022-05-27 16:24
Closing per the comment.

**Closed by yury-s** 2022-05-27 16:24 UTC

**Comment by Niemetz** [comment] 2022-11-25 17:46
Hi mxschmitt
  I need your help!
  I followed your instructions by set this **use: { ignoreHTTPSErrors: true }** in the config file but the execution still fails...
  The error message seems to say that the client is still trying to validate the SSL cert from the server side.
  Error message => "apiRequestContext.get: write EPROTO:17028:error:14094410: SSL..."
  Here is what my config file looks like:

  import { PlaywrightTestConfig " from "@playwright/test";
  const config: PlaywrightTestConfig  = {
   use: {
            baseURL: "<My base URL>",
            extraHTTPHeaders: {
                "Content-type": 'application.json; charset=UTF-8';
            },
           ignoreHTTPSErrors: true,
    }
}
export default config;
  
Did I do it right.. or I missed something here?!!
Thank you in advance for your help !

**Comment by LeiSurrre** [comment] 2024-01-29 07:19
I tried this and it solved the error for me
`const context = await request.newContext({ ignoreHTTPSErrors: true })
const response = await context.post("...")
`

**Comment by lgkula** [comment] 2024-01-31 12:17
> I tried this and it solved the error for me
> 
> ```
> const context = await request.newContext({ ignoreHTTPSErrors: true })
> ```
When trying to use:
await request.newContext({ ignoreHTTPSErrors: true })
I get the error: "TypeError: request.newContext is not a function" The "newContext" property does not exist in the type "APIRequestContext"

Anyone know what could be the cause?

**Comment by ilorwork** [comment] 2024-06-18 07:58
> When creating a new request context, you can pass `ignoreHTTPSErrors : true`. If you are using Playwright Test, then you can pass `ignoreHTTPSErrors: true` inside your config under the `use: { ignoreHTTPSErrors: true }` block and it should work when using `page.request` or `context.request`.

This indeed helped me. thanks a lot.
But could anyone have an explanation why this happened?
In my case it didn't happen at first - only after a couple CI execution...
