### ISSUE TITLE
[BUG] File uploads fail which are > 50 MB

### ISSUE THREAD

**Issue by adambbn** [microsoft/playwright#3768] opened 2020-09-04 09:03 UTC
**Context:**
- Playwright Version: 1.3.0
- Operating System: Windows
- Node.js version: 12.18.3
- Browser: Chromium

**Code Snippet**
```javascript
const { chromium } = require("playwright");

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.setContent(
    '<input type="file" name="fileToUpload" id="fileToUpload">'
  );
  await page.setInputFiles("input", "path/to/large/file.txt");
  await browser.close();
})();

```

**Describe the bug**
When uploading large file, about 100MB, `page.setInputFiles` fails. With Firefox and Webkit it takes some time but it works.
Log:
```
  pw:api => page.setContent started +0ms
  pw:api setting frame content, waiting until "load" [] +1ms
  pw:api <= page.setContent succeeded +79ms
  pw:api => page.setInputFiles started +2ms
  pw:api waiting for selector "input" [] +1ms
  pw:api   selector resolved to visible <input type="file" id="fileToUpload" name="fileToUpload"/> [] +26ms
  pw:api <= page.setInputFiles failed +1s
(node:19668) UnhandledPromiseRejectionWarning: page.setInputFiles: Protocol error (Runtime.callFunctionOn): Target closed.
=========================== logs ===========================
[api] waiting for selector "input"
[api]   selector resolved to visible <input type="file" id="fileToUpload" name="fileToUpload"/>
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.Error
    at C:\dev\playwright\node_modules\playwright\lib\chromium\crConnection.js:131:63
    at new Promise (<anonymous>)
    at CRSession.send (C:\dev\playwright\node_modules\playwright\lib\chromium\crConnection.js:130:16)
    at CRSession.send (C:\dev\playwright\node_modules\playwright\lib\helper.js:80:31)
    at CRExecutionContext.evaluateWithArguments (C:\dev\playwright\node_modules\playwright\lib\chromium\crExecutionContext.js:40:79)
    at evaluateExpression (C:\dev\playwright\node_modules\playwright\lib\javascript.js:164:40)
    at async FrameManager.waitForSignalsCreatedBy (C:\dev\playwright\node_modules\playwright\lib\frames.js:90:24)
    at async FrameExecutionContext.evaluateInternal (C:\dev\playwright\node_modules\playwright\lib\dom.js:36:16)
    at async CRPage.setInputFiles (C:\dev\playwright\node_modules\playwright\lib\chromium\crPage.js:210:9)
    at async C:\dev\playwright\node_modules\playwright\lib\dom.js:440:13
  -- ASYNC --
    at CRSession.send (C:\dev\playwright\node_modules\playwright\lib\helper.js:79:23)
    at CRExecutionContext.evaluateWithArguments (C:\dev\playwright\node_modules\playwright\lib\chromium\crExecutionContext.js:40:79)
    at evaluateExpression (C:\dev\playwright\node_modules\playwright\lib\javascript.js:164:40)
    at async FrameManager.waitForSignalsCreatedBy (C:\dev\playwright\node_modules\playwright\lib\frames.js:90:24)
    at async FrameExecutionContext.evaluateInternal (C:\dev\playwright\node_modules\playwright\lib\dom.js:36:16)
    at async CRPage.setInputFiles (C:\dev\playwright\node_modules\playwright\lib\chromium\crPage.js:210:9)
    at async C:\dev\playwright\node_modules\playwright\lib\dom.js:440:13
    at async FrameManager.waitForSignalsCreatedBy (C:\dev\playwright\node_modules\playwright\lib\frames.js:90:24)
    at async ElementHandle._setInputFiles (C:\dev\playwright\node_modules\playwright\lib\dom.js:438:9)
    at async C:\dev\playwright\node_modules\playwright\lib\frames.js:674:32
  -- ASYNC --
    at Frame.setInputFiles (C:\dev\playwright\node_modules\playwright\lib\helper.js:79:23)
    at C:\dev\playwright\node_modules\playwright\lib\page.js:407:61
    at Page._attributeToPage (C:\dev\playwright\node_modules\playwright\lib\page.js:370:20)
    at Page.setInputFiles (C:\dev\playwright\node_modules\playwright\lib\page.js:407:21)
    at Page.setInputFiles (C:\dev\playwright\node_modules\playwright\lib\helper.js:80:31)
    at C:\dev\playwright\upload.js:9:14
(node:19668) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:19668) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dgozman** [comment] 2020-09-14 17:34
This is what I get when running with `DEBUG=pw:browser*`:

```sh
pw:browser [err] [0914/103304.384699:ERROR:http_connection.cc(37)] Too large read data is pending: capacity=104857600, max_buffer_size=104857600, read=104857600 +2s
pw:browser [err] [0914/103304.384745:ERROR:devtools_pipe_handler.cc(278)] Connection closed, not enough capacity +0ms
```

**Comment by joel-s** [comment] 2021-03-17 16:40
For me, uploading a 320MB file crashes on all 3 browsers. The browser disappears and the test hangs. The same thing works without problems on all 3 browsers with a smaller file.

Can anyone recommend a workaround for this (in any browser, but Chromium would be best), considering we were planning to use Playwright to test a Web UI where a typical upload file size is 2-3GB? The 320MB file was created as a way to speed up some tests.

```js
/**
 * @fileOverview Sample to demonstrate crash when file size is large.
 */
const LARGE_TIMEOUT = 2 * 60 * 1000;

describe("Upload page", () => {
  it("should receive an upload", async () => {
    await page.goto("https://uppy.io/examples/xhrupload/");

    page.setDefaultTimeout(LARGE_TIMEOUT);

    await page.setInputFiles("input[type='file']", "/some/320mb/file", {
      timeout: LARGE_TIMEOUT,
    });
  });
});
```

**Comment by joel-s** [comment] 2021-03-17 19:17
On my system, the max upload size seems to be between 50 and 75 MB. I can upload a 50 MB file—it just takes a while. Trying to select a 75 MB file for upload crashes the browser (Chromium).

This is on MacOS 10.14.6 Mojave, Playwright 1.9.2

To create a tar file slightly larger than 75MB I am using the following bash commands:
```bash
$ dd if=/dev/zero of=75MB.file bs=1024 count=$((1024 * 75))
76800+0 records in
76800+0 records out
78643200 bytes transferred in 0.400591 secs (196317874 bytes/sec)
$ tar cpvf 75MB.tar 75MB.file
```

**Comment by maylme** [comment] 2021-03-26 13:08
> For me, uploading a 320MB file crashes on all 3 browsers. The browser disappears and the test hangs. The same thing works without problems on all 3 browsers with a smaller file.
> 
> Can anyone recommend a workaround for this (in any browser, but Chromium would be best), considering we were planning to use Playwright to test a Web UI where a typical upload file size is 2-3GB? The 320MB file was created as a way to speed up some tests.
> 
> ```js
> /**
>  * @fileOverview Sample to demonstrate crash when file size is large.
>  */
> const LARGE_TIMEOUT = 2 * 60 * 1000;
> 
> describe("Upload page", () => {
>   it("should receive an upload", async () => {
>     await page.goto("https://uppy.io/examples/xhrupload/");
> 
>     page.setDefaultTimeout(LARGE_TIMEOUT);
> 
>     await page.setInputFiles("input[type='file']", "/some/320mb/file", {
>       timeout: LARGE_TIMEOUT,
>     });
>   });
> });
> ```
> 
> This is on MacOS 10.14.6 Mojave, Playwright 1.9.2

Exactly same problem here. 
I had troubles with node memory when I uploaded multiples small files one after an other so I added `export NODE_OPTIONS=--max_old_space_size=4096` to force memory of node to 4gb. 

Then I realised that playwright didn't throw unused memory in a scenario If you don't manually reset the context of the browser. ( happened for me also by uploading many small files )

But now, I still have a problem when uploading a simple file of more than 300Mo... 
This is what I got as error (nothing in pw:browser) : 
![image](https://user-images.githubusercontent.com/5748164/112635535-3b5c0380-8e3c-11eb-98ac-8deab51f7e3a.png)

What I find curious is that I used Firefox as testing browser and it talks about chrome...

**Comment by Vanish404** [comment] 2021-11-01 08:09
hey, any updates?

**Comment by nikolaristicc** [comment] 2021-11-01 13:30
any updates?

**Comment by pavelfeldman** [comment] 2021-11-15 20:05
I'm trying to prioritize this, could you share what kind of testing scenario requires uploading 100Mb+ files?

**Comment by joel-s** [comment] 2021-11-15 20:21
At a high level, I'm working on a system that allows users to submit Docker images as .tar files and get feedback about how well those images work and how they compare to each other. All of our example images, using Python, were too large to upload... we have a workaround using a much smaller image written in Go, but we'd like to automate testing of some 100MB+ files, since that is more realistic: our customers will typically using languages like Python. We want to verify that this software works correctly in a classified environment without direct access to the internet.

**Comment by kadogo** [comment] 2021-11-15 22:05
In my case, I use it for automating steps on a cloud provider that doesn't give a way to upload on my OS other than by the browser. To make a big range of backup, it's easier with few lines of code than doing it manually.

**Comment by OPISGIT** [comment] 2021-11-16 01:25
> I'm trying to prioritize this, could you share what kind of testing scenario requires uploading 100Mb+ files?

The website (AI training purposes) allowed user to upload video files. In machine learning model, each video file minimally exceed 2GB.

**Comment by ivo-pupkin** [comment] 2021-11-16 04:57
In my case, I used playwright to upload video files to video hosting under test.

**Comment by Massukio** [comment] 2021-11-16 10:09
In my case, I am testing a vmware-like web app, which requires user to upload OS .iso file / VM .ova file which is usually larger than 1GB.

**Comment by adambbn** [comment] 2021-11-16 10:11
I'm testing validation that forbids files above 100 MB.

**Comment by vewald** [comment] 2021-11-16 10:56
In my case, I'm uploading some files which are 200 MB (firmware update and some patches inside). Currently this issue is blocking our Jenkins pipeline since all tests are failing. Any workaround?

**Comment by rai-gaurav** [comment] 2021-11-16 14:37
I have a orchestration system where a user can upload different size zip files (some are ~150MB and some ~250MB).
I am using playwright to test this.

**Comment by nikolaristicc** [comment] 2021-11-22 10:15
is this going to be solved?

**Comment by xylix** [comment] 2021-11-24 08:09
Large file uploads also seem to be slow. (30 seconds for 70 megabytes). I think it might be caused by this line.

https://github.com/microsoft/playwright/blob/06ab3c0fda2223ef6fd813c48373208b1b2c01b7/packages/playwright-core/src/server/injected/injectedScript.ts#L660

**Comment by maylme** [comment] 2021-11-24 09:08
@pavelfeldman we would like to use it for testing our in vitro diagnostic medical application. The crash appear during upload/download genomic and other medical files (170mo to 5go and bigger files).

**Comment by fawazahmed0** [comment] 2021-12-03 05:10
I have rewritten the upload logic to use [puppeteer](https://github.com/fawazahmed0/libgen-uploader/commit/174ff6a98d6a5d1ce0b88e512787b09afeb22b8e#diff-ae84bbb0e4aa7ab005d470f37ae65474fefd6b86369b9d152222127359b96879) to fix the issue for me , not sure how puppeteer handles the upload process

**Comment by nikolaristicc** [comment] 2021-12-03 06:04
It would be perfect if there is a way to change playwrights upload function with puppeteers one. Puppeteer has no limits when it comes to upload file size.

**Comment by nikolaristicc** [comment] 2021-12-03 20:47
this code is in JSHandle.js in puppeteer. Do you have any ideas if we can create a function for the Playwright that will upload files of any size based on this code?

`async uploadFile(...filePaths) {
        const isMultiple = await this.evaluate((element) => {
            if (!(element instanceof HTMLInputElement)) {
                throw new Error('uploadFile can only be called on an input element.');
            }
            return element.multiple;
        });
        assert(filePaths.length <= 1 || isMultiple, 'Multiple file uploads only work with <input type=file multiple>');
        if (!isNode) {
            throw new Error(`JSHandle#uploadFile can only be used in Node environments.`);
        }
        /*
         This import is only needed for `uploadFile`, so keep it scoped here to
         avoid paying the cost unnecessarily.
        */
        const path = await import('path');
        const fs = await helper.importFSModule();
        // Locate all files and confirm that they exist.
        const files = await Promise.all(filePaths.map(async (filePath) => {
            const resolvedPath = path.resolve(filePath);
            try {
                await fs.promises.access(resolvedPath, fs.constants.R_OK);
            }
            catch (error) {
                if (error.code === 'ENOENT')
                    throw new Error(`${filePath} does not exist or is not readable`);
            }
            return resolvedPath;
        }));
        const { objectId } = this._remoteObject;
        const { node } = await this._client.send('DOM.describeNode', { objectId });
        const { backendNodeId } = node;
        /*  The zero-length array is a special case, it seems that
            DOM.setFileInputFiles does not actually update the files in that case,
            so the solution is to eval the element value to a new FileList directly.
        */
        if (files.length === 0) {
            await this.evaluate((element) => {
                element.files = new DataTransfer().files;
                // Dispatch events for this case because it should behave akin to a user action.
                element.dispatchEvent(new Event('input', { bubbles: true }));
                element.dispatchEvent(new Event('change', { bubbles: true }));
            });
        }
        else {
            await this._client.send('DOM.setFileInputFiles', {
                objectId,
                files,
                backendNodeId,
            });
        }
    }`

**Comment by xylix** [comment] 2022-01-20 08:05
Hey, are there some blockers for prioritizing this bug? 

How much feedback / traffic is required for bumping it up from `p3-collecting-feedback`?

**Comment by kadogo** [comment] 2022-01-30 19:41
Hello @mxschmitt @pavelfeldman

Are there still blockers for this issue? Do you need additional information?

Cheers

**Comment by JCMais** [comment] 2022-02-02 19:30
This is also a bug when taking performance profiles using `browser.startTracing` (Chrome trace).

**Comment by yury-s** [comment] 2022-02-02 19:47
> This bug also affects taking performance profiles using `browser.startTracing` (Chrome trace).

Can you elaborate on how file upload behavior affects tracing?

**Comment by JCMais** [comment] 2022-02-02 19:51
I noticed that this other issue was marked as duplicate of this one: https://github.com/microsoft/playwright/issues/6266

The error message in there, `Cannot create a string longer than 0x1fffffe8 characters`, is the exact error message I got when trying to create a trace:
```
browser.stopTracing: Cannot create a string longer than 0x1fffffe8 characters
```

**Comment by yury-s** [comment] 2022-02-02 19:54
> the exact error message I got when trying to create a trace:

This is a different issue, the solution we have in mind for this bug will likely not solve it.

**Comment by JCMais** [comment] 2022-02-02 20:14
@yury-s got it, I have created another issue here https://github.com/microsoft/playwright/issues/11816

It is easily reproducible using the code in there.

**Comment by Uninen** [comment] 2022-02-09 19:27
One more use case that this seems to be a blocker to: I bumped into this when trying to automate creating `AudioContext` programatically by using `page.expect_file_chooser()` (with Python). Haven't figured out the actual limit but ~100Mb audio files don't seem to work with any browser.

**Comment by lovelyplanet2019** [comment] 2022-02-11 07:34
any plan and target fixed date?

**Comment by italodeandra** [comment] 2022-03-15 12:37
@lovelyplanet2019 We usually get one minor every month. We're currently at `1.20` that released yesterday so my guess would be in a month we might get this fixed, if they don't postpone it again.

**Comment by lovelyplanet2019** [comment] 2022-03-16 14:24
> @lovelyplanet2019 We usually get one minor every month. We're currently at `1.20` that released yesterday so my guess would be in a month we might get this fixed, if they don't postpone it again.

I see. The version is v1.21 now.

**Closed** 2022-03-25 20:26 UTC
Labels: v1.21

**Comment by laviniaSer07** [comment] 2022-05-03 08:06
Hello! I'm still getting this error when I am trying to upload a file grater then 2 GB `RangeError [ERR_FS_FILE_TOO_LARGE]: File size (3235260344) is greater than 2 GB`. Is there any update for the files that are larger than 2GB ?

**Comment by JeffreyCanisius04** [comment] 2022-09-02 18:48
Hello! I am still unable to upload files (500 mb and 2gb files) as the test would hang. It only works for small files.

Context:

Playwright Version: 1.25.2
Operating System: Mac OS 12.5.1
Python Version: 3.7.9
Browser: Chromium

**Comment by italodeandra** [comment] 2022-09-04 19:47
> Hello! I am still unable to upload files (500 mb and 2gb files) as the test would hang. It only works for small files.
> 
> Context:
> 
> Playwright Version: 1.25.2 Operating System: Mac OS 12.5.1 Python Version: 3.7.9 Browser: Chromium

Hi @JeffreyCanisius04,

From what I can see, the hanging would mean a problem on your application or other issue with Playwright instead of being related to this issue here. If you got the error message `ERR_FS_FILE_TOO_LARGE` then the problem would be the same.
