### ISSUE TITLE
[Question] How to use miragejs mocks with Playwright component tests?

### ISSUE THREAD

**Issue by VaasRamsay** [microsoft/playwright#16341] opened 2022-08-08 10:32 UTC
I've been playing around with Playwright Component tests, and am struggling to wire up `miragejs` mock server with the test suite. Is there a recommended approach/solution to this?

My frontend app uses CRA and has a `miragejs` [mock server ](https://miragejs.com/docs/testing/integration-and-unit-tests/)for testing. What's the right way to initialize this in Playwright component tests? 

Note: For comparison, this is how [Cypress wires it up](https://miragejs.com/quickstarts/cypress/). I've tried adding a proxy function like the one Cypress uses via `context.addInitScript` before the test begins. I can see the function being attached to the window object, but redirect from the app doesn't seem to work.

**Comment by rwoll** [comment] 2022-08-08 18:29
I'm not familiar with `miragejs`, but based on the Cypress example and the miragejs docs, it looks like an in-browser mocking library. Since it wants to run in the browser (as opposed to the node process), `context.addInitScript` is the correct approach.

Please share a minimal repro (i.e. a GitHub repository we can clone and run that exhibits the error you're seeing) so we can better understand what you're experiencing and how the wiring looks. Thanks!

**Comment by VaasRamsay** [comment] 2022-08-09 12:33
Thanks @rwoll for taking a look. Here's a [sample repo](https://github.com/VaasRamsay/cra-pw-comp-tests-sample) with Playwright component tests added. 

I'm setting up the proxy function [here ](https://github.com/VaasRamsay/cra-pw-comp-tests-sample/blob/7e3bc400bea06371ad5337600dcc8b2ef33f273f/src/components/Navigation/Navigation.spec.tsx#L11-L28) in the test beforeEach hook and forwarding network requests to it from the app [here](https://github.com/VaasRamsay/cra-pw-comp-tests-sample/blob/7e3bc400bea06371ad5337600dcc8b2ef33f273f/src/index.tsx#L10-L30). If you try to debug the test, you can see the network request being made (`miragejs` should ideally be intercepting the call and it shouldn't show up in the network tab).

**Comment by rwoll** [comment] 2022-08-09 22:49
Thanks @VaasRamsay—I was able to use that to better understand what's going on.

A key part of Playwright is, some code runs in Node other code runs in the Browser. `miragejs` [runs in the browser](https://miragejs.com/docs/getting-started/introduction/#how-it-works) to work properly, but it looks like [your code is creating the mirage server in Node](https://github.com/VaasRamsay/cra-pw-comp-tests-sample/blob/7e3bc400bea06371ad5337600dcc8b2ef33f273f/src/components/Navigation/Navigation.spec.tsx#L9)—the code inside `context.addInitScript` will run in the browser, but the other code in that file is running in Node.

To use miragejs, all of the mirage code must be run in the browser. You can achieve that one of a few ways, but the following does work: https://github.com/rwoll/playwright-miragejs-demo. For component tests, all code in `playwright/index.ts` will run in the browser.

Does this make sense? If you clone that repo, you can run the tests locally and they should pass!

NB: Playwright provides its own mocking/routing functions, so if you aren't already invested in miragejs, you might consider using those as we'll be able to assist better: https://playwright.dev/docs/network#handle-requests. (I don't recommend using multiple network mocking strategies at once (e.g. Playwright's page.route/context.route + miragejs + MSW) as it will likley have unexpected behavior.)

**Comment by VaasRamsay** [comment] 2022-08-11 13:50
Great, thanks @rwoll! Your example works fine with the latest update. I can use the hooks to setup the server before tests. 

However, is it possible to modify the mocks from the tests somehow? For example, I could setup a clean mock server before every test and then from test A seed a single item and from test B seed hundreds of items to test my component. How can I achieve this? [Jest](https://miragejs.com/quickstarts/react/test-a-component-with-react-testing-library/#step-2-create-a-server-within-a-test) and [Cypress](https://miragejs.com/quickstarts/cypress/#step-6-alter-your-mirage-server-to-test-different-server-states) tests are able to do this with miragejs, wondering how to achieve similar functionality with Playwright.

**Comment by rwoll** [comment] 2022-08-11 19:30
@VaasRamsay Thanks for your patience! It's possible to do this functionality, but in order to give you a better answer, we'll need some more time to play around.

I've assigned this out and marked to the next milestone so we can hopefully dedicate some time to it. (It hits on topics beyond just network mocking—e.g. running code in browser vs. in node—and what to do where when, so there's probs some more holistic education/docs we can add here.)

**Comment by pavelfeldman** [comment] 2022-08-20 00:28
@VaasRamsay 


```js
// playwright/index.ts
import { beforeMount } from '@playwright/experimental-ct-react/hooks';
import { createServer } from "miragejs"

beforeMount(async ({ hooksConfig }) => {
  createServer({
    routes() {
      this.get("/api/users", () => hooksConfig.users)
    },
  });
});
```

```js
src/Users.spec.tsx
import { test, expect } from "@playwright/experimental-ct-react";
import React from "react";
import { Users } from "./Users";

test("should work", async ({ mount }) => {
  const component = await mount(<Users />, {
    hooksConfig: {
      users: [
        { id: "1", name: "Luke" },
        { id: "2", name: "Leia" },
        { id: "3", name: "Anakin" },
      ]
    }
  });
  await expect(component.locator("li")).toContainText([
    "Luke",
    "Leia",
    "Anakin",
  ]);
});
```

**Comment by pavelfeldman** [comment] 2022-08-20 00:29
@VaasRamsay would you be open to contributing a docs page (markdown) providing this example?

**Comment by VaasRamsay** [comment] 2022-08-21 09:35
@pavelfeldman PTAL https://github.com/microsoft/playwright/pull/16706

**Comment by pavelfeldman** [comment] 2022-08-22 19:32
Closing with https://github.com/microsoft/playwright/pull/16706, thanks!

**Closed by pavelfeldman** 2022-08-22 19:32 UTC
Labels: v1.26
