### ISSUE TITLE
[BUG] error occur after page.reload 748 times in nested frame test

### ISSUE THREAD

**Issue by canstand** [microsoft/playwright#28915] opened 2024-01-09 13:07 UTC
### System info
- Playwright Version: [v1.40.1]
- Operating System: [macOS 14.1.2], may be all
- Browser: [Chromium, Firefox, WebKit]
- Other info:

### Source code

modify `tests/page/frame-hierarchy.spec.ts` like following, add timeout and page.reload 800times.

```ts
it('should handle nested frames @smoke', async ({ page, server, isAndroid }) => {
  it.skip(isAndroid, 'No cross-process on Android');
  // require to finish for loop
  it.setTimeout(500000);
  await page.goto(server.PREFIX + '/frames/nested-frames.html');
  expect(dumpFrames(page.mainFrame())).toEqual([
    'http://localhost:<PORT>/frames/nested-frames.html',
    '    http://localhost:<PORT>/frames/frame.html (aframe)',
    '    http://localhost:<PORT>/frames/two-frames.html (2frames)',
    '        http://localhost:<PORT>/frames/frame.html (dos)',
    '        http://localhost:<PORT>/frames/frame.html (uno)',
  ]);
  // for loop 800 times
  for (let i = 0; i < 800; ++i) {
    await page.reload();
    // sleep 100ms
    await new Promise(f => setTimeout(f, 100));
  }
});
```

**Steps**
- run test `npm run test -- --grep "should handle nested frames @smoke"`
- error occurs when reload 748 times in all browsers.

<img width="967" alt="error" src="https://github.com/microsoft/playwright/assets/70889873/5563969f-0151-4279-b225-514c599406cc">

**Comment by dgozman** [comment] 2024-01-10 02:17
Duplicate of #28320, should be fixed in the next release.

**Closed by dgozman** 2024-01-10 02:17 UTC
