### ISSUE TITLE
[BUG] Html and Junit reporters no longer generate output after updating to latest

### ISSUE THREAD

**Issue by bronumski** [microsoft/playwright#12840] opened 2022-03-17 02:21 UTC
**Context:**
- Playwright Version:1.20.0, 1.19.2 
- Operating System: Mac
- Node.js version: v15.4.0
- Browser: Chromium

**Code Snippet**

```typescript

const config: PlaywrightTestConfig = {
   ...
    reporter: [
        ['list'],
        ['html', { outputFolder: './build/e2e', open: 'never' }],
        ['junit', { outputFile: './build/e2e/test-results.xml' }]
    ],
    ...
}
```

**Describe the bug**

After updating to 1.20.0 the HTML and JUNIT test reporters are no longer generating the reports with my setup. I was running 1.17.2 and it was working fine. I have tested in 1.18.1 which also works but 1.20.0 and 1.19.2 did not generate the results nor did the html output which is normally sent to the console get generated:

```
To open last HTML report run:

  npx playwright show-report build/e2e
```

I was looking for a way to generate a trace or debug output but didn't see one. If someone could point me to that I can provide that as well.

**Comment by pavelfeldman** [comment] 2022-03-17 03:23
Is there a repro you could share? Do tests work and only reporters are not working?

**Comment by bronumski** [comment] 2022-03-17 03:50
@pavelfeldman - I cannot share a repo but maybe I could try and reproduce in a bare repo.

Tests work fine but reporters do not.

**Comment by bronumski** [comment] 2022-03-17 17:19
@pavelfeldman I have created a repo [here](https://github.com/bronumski/bronumski-playwright-12840) as best I can to emulate the actual project.

When running using 1.20.0 you get the following:

```
npx playwright install chromium

npx playwright test

Running 1 test using 1 worker

Starting dev server
... Webpack logging here ...
Dev server started
  ✓  [chromium] › test.spec.ts:3:1 › Some test (577ms)
Shutting down
99% end closing watch compilationShut down
```

There is no output shown from the html reporter in the console, no html file is generated in the `build/e2e` folder and there is no junit report either.

When switching to 1.18.1 you get the following:

```
npm i -D @playwright/test@v1.18.1

npx playwright install chromium

npx playwright test

Using config at /Users/mdavis/dev/Playground/playwright-bug/playwright.config.ts
Starting dev server
... Webpack logging here ...
Dev server started

Running 1 test using 1 worker

  ✓  [chromium] › test.spec.ts:3:1 › Some test (760ms)


  1 passed (1s)

To open last HTML report run:

  npx playwright show-report build/e2e

Shutting down
99% end closing watch compilationShut down
```

Here we get the count of passing tests, indication of the html report generation and both the junit and html reports are in the `build/e2e` folder. Also one thing I just noticed is that right at the very top we get the line indicating what config was being used which is not present in the other output. I don't know if that is relevant or not.

**Comment by pavelfeldman** [comment] 2022-03-17 18:54
These two are conflicting:

```
outputDir: './build/e2e/',
outputFolder: './build/e2e',
```

You should not store html report in the same folder as intermediate test results.

**Comment by bronumski** [comment] 2022-03-18 03:15
@pavelfeldman - I am not sure what the issue is there, all build artefacts need to be dropped into the build folder and it "appeared" to be working fine. Is the `outputDir` like a temp folder?

I have tried using the following config but I get the same results:

```
    reporter: [
        ['list'],
        ['html', { outputFolder: './foo', open: 'never' }],
        ['junit', { outputFile: './bar/test-results.xml' }]
    ],

    outputDir: './wibble',
```

**Comment by pavelfeldman** [comment] 2022-03-18 18:49
> Can you explain why that would be a problem? 

When you were pointing to the same folder, you were providing two independent system with the same output folder that they perceive as their own. As a result, they were fighting and erasing the results of each other. It would be like installing two programs into the same folder concurrently.

> I have tried using the following config but I get the same results:

I have no explanation to this one however, that's what most of our users do  routinely. I would be curious to see a minimum reproducible scenario.

**Comment by bronumski** [comment] 2022-03-19 20:41
@pavelfeldman - Did the repo I provide work for you? If you pull it then it should reproduce the issue that I am seeing.

**Comment by pavelfeldman** [comment] 2022-03-19 22:50
- I cloned https://github.com/bronumski/bronumski-playwright-12840
- I ran npm i
- I changed config for have
```
    reporter: [
        ['list'],
        ['html', { outputFolder: './foo', open: 'never' }],
        ['junit', { outputFile: './bar/test-results.xml' }]
    ],
    ...
    outputDir: './wibble',
```
- I got this:

<img width="276" alt="Screen Shot 2022-03-19 at 3 49 35 PM" src="https://user-images.githubusercontent.com/883973/159141061-78a2fd91-1f5c-4dd6-a4d5-6d6c3fc4484a.png">

What do I miss?

**Comment by bronumski** [comment] 2022-03-20 02:43
@pavelfeldman - My bad I pushed up the package.config with the version that works (1.18.1). Update to 1.20.0, that is where I have the issue.

**Comment by pavelfeldman** [comment] 2022-03-20 06:47
I can repro! It looks like there are a couple of bugs in the tear down that Playwright Test did not handle gracefully:

1) Your global teardown never finishes (`done` is not called)

```js
return async () => {
        await new Promise(done =>
            setTimeout(async () => {
                console.log("Shutting down");
                await devServer.stop(done);  // devServer.stop is async, it does not accept the callback
                console.log("Shut down");
            }, 5000));
    };
```

should be:

```js
return async () => {
  // await new Promise(f => setTimeout(f, 5000)); // - not sure why you need this.
  console.log("Shutting down");
  await devServer.stop();
  console.log("Shut down");
};
```

2) Calling `devServer.stop` schedules process exit.

I did not track this down to an actual call, but I can see that if I am just putting `await new Promise(() => {});` in the global teardown, we report the teardown timeout. However, if I run await `devServer.stop()` before that, entire runner process is scheduled to be killed.

All in all, I'd probably run dev server as a `webServer` [like in this example](https://github.com/microsoft/playwright/blob/main/examples/components-vue/playwright.config.ts#L12). It'll run in a subprocess, so stopping it won't harm the surroundings, it'll also wait for the URL to be available on its own, so no manual webpack hooks are necessary. If you still need to run dev server with hooks, you can always point `webServer` to your own scripts.

**Comment by bronumski** [comment] 2022-03-21 23:51
@pavelfeldman - I can confirm that works. As to why the web server was started this way was because the idea is not to give it a static port but let the dev server startup and return the port that was used and dynamically set the base url. Unfortunately we were unable to work out how to set the base url dynamically.

I can close this bug off as not a bug.

**Comment by pavelfeldman** [comment] 2022-03-22 00:18
Sounds good, closing it then!

**Closed by pavelfeldman** 2022-03-22 00:18 UTC
Labels: triaging

**Comment by shirshGit** [comment] 2022-08-17 12:46
Junit Reporter does not add the result at <testcase> level? If we have two test in one spec then how to understand the results individually for each test? 
Expecting the report to be something line: 
<testcase name="someTestName" assertions="4" time="9.279618" status="Passed" classname="someClassName">
			<system-out></system-out>
		</testcase>

Here status of the Test is coming as pass but playwright Junit Report is like 

<testcase name="someName" time="55.896"></testcase>

It does not have status for individual Test.
