### ISSUE TITLE
Dynamic tests fail under specific circumstances - test() can only be called in a test file

### ISSUE THREAD

**Issue by asdf23** [microsoft/playwright#11458] opened 2022-01-18 14:24 UTC
Hello,
I cannot get dynamic tests working. By "dynamic tests" I mean that the method `test(string, function)` is defined and called within a function.  This does work if I hard-code the data. But it does not work if the data _was_ pulled in through a function....?????   I'm totally stumped. 

Here is my tests/myTests.spec.ts file:

```
...snip...
test("These tests are all working", async({page}) => { ...snip } )
test("These tests are all working...", async({page}) => { ...snip } )

async function runMe() {
	let orders = await getData();  //  <--- this line seems to cause a failure below @ test("Dynamic test ..."
	//orders = [{MyData: "Not relevant", id: 1}];  //  <---- but using this line will work below
	console.log("orders:", JSON.stringify(orders)); //Yup my data is here 
	for(let i=0; i<orders.length; i++) {
		let someID = orders[i].id
 		console.log("Yup the id is present as expected", someID); //data looks good
		test(`Dynamic test ${someID}`, async()=>{                     // <--- crashes here
			console.log("Hello World");
		})
	}
}
runMe();

```

If  getData() was called then later  `test("Dynamic test ...")` will crash with the **test() can only be called in a test file** error

```

C:\dev\node_modules\@playwright\test\lib\util.js:159
  return new Error(`${formatLocation(location)}: ${message}`);
         ^

Error: tests\myTests.spec.ts:450:3: test() can only be called in a test file
    at errorWithLocation (C:\dev\node_modules\@playwright\test\lib\util.js:159:10)
    at TestTypeImpl._createTest (C:\dev\node_modules\@playwright\test\lib\testType.js:79:51)
    at C:\dev\node_modules\@playwright\test\lib\transform.js:132:12
    at abcv124 (C:\dev\tests\myTests.spec.ts:450:3)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processImmediate (internal/timers.js:434:9)

```

If I hard-code orders with the same values it works.

Before the test() method I can console.log out the data and in both cases I see the same data. I cannot see that how I get the data could possibly relevant as it is present before test() is executed. 

`getData()` looks like this:

```
async function getData() {
    return new Promise((resolve,reject) => {
         sqlConnection.connect().then(() => {
              ...snip...
         })
    })
}
```

getData() is working as expected in many other places so it's hard for me to believe that it's related to this problem at all.

**Comment by asdf23** [comment] 2022-01-18 21:38
The crash is coming from `testType.js`

```

  _createTest(type, location, title, fn) {
    throwIfRunningInsideJest();
    const suite = (0, _globals.currentlyLoadingFileSuite)();  <--- what is going on here? suite is not null yet throws on the next line
    if (!suite) throw (0, _util.errorWithLocation)(location, `test() can only be called in a test file`);

```

**Comment by mxschmitt** [comment] 2022-01-18 21:40
It is not supported to asynchronously create / call the test() function. If you need data beforehand, we recommend by doing e.g. `node getData.js && npx playwright test` and write your data into a file so you can read it afterwards.

Closing since this is not a bug.

**Closed by mxschmitt** 2022-01-18 21:40 UTC

**Comment by asdf23** [comment] 2022-01-18 21:53
Sorry I'm not following you. 
Lets say that there is a database call or even a file that contains 10 records. So I want to preform 10 tests.  Are you are saying that there is no way to make 10 tests?

Because I can do it, with something like the following code:

```

[1,2,3,4,5,6,7,8,0].forEach( f=> {  test(`test ${f}`, ()=>{
    console.log("a test")
}    )  } )

```

**Comment by mxschmitt** [comment] 2022-01-18 21:58
`let orders = await getData()` this is asynchronous due to the await. 

Doing it in a synchronous manner will work, but accessing a database e.g. is not synchronous.

See here for more information: https://playwright.dev/docs/test-parameterize
