### ISSUE TITLE
[Timeout for isVisible()] When trying to find out non-existing element using isVisible(), no option to set timeout

### ISSUE THREAD

**Issue by priyankaDamam31** [microsoft/playwright#26747] opened 2023-08-28 18:07 UTC
Playwright version - 1.32.0
Programming language - Java

I am checking for an element which does not exist and expecting isVisible() to return false immediately. But Playwright waits for default time-out set at global level (60 seconds) each time when it cannot find an element. 
There is no point in waiting for an element which does not exist. Either isVisible() should return the outcome immediately without waiting OR isVisible() method should allow setTimeout parameter to be configurable by the user just like the node.js isVisible() funciton.

**Comment by mxschmitt** [comment] 2023-08-29 08:14
I absolutely agree, isVisible should never wait for the element to appear. if you experience it doing so, then this sounds like a bug.

Would it be possible to share a minimal reproducible for us? This would help us to debug this issue further, thanks!

Which isVisible do you use? The one on [Locator](https://playwright.dev/docs/api/class-locator#locator-is-visible)?

**Comment by aslushnikov** [comment] 2023-09-05 16:11
It looks like the discussion has stalled; closing this.

Please file a new issue if you have a repro! Also, please make sure to fill in the issue template; this'll save us time. Thanks!

**Closed by aslushnikov** 2023-09-05 16:11 UTC
Labels: triaging

**Comment by NedWilbur** [comment] 2023-12-07 19:30
Stale conversation but something I think y'all are forgetting. If you just check `toBeHidden` and want it to continue as soon as it confirms it does not exist the first time, then this will instantly pass in most cases before the dom has a chance to render, causing a potential false pass. You need to ensure that the page is truly loaded, then check `toBeHidden`. 

The alternative to this, is for the `expect` call to check that it remains `toBeHidden` for the full timeout. I don't recall if PW does this, but based on this thread, it does, and this is common behavior with other testing frameworks.
