### ISSUE TITLE
[BUG] Reload pushes a new history entry on Firefox

### ISSUE THREAD

**Issue by gtm-nayan** [microsoft/playwright#22640] opened 2023-04-26 04:58 UTC
### System info
- Playwright Version: v1.32.3
- Operating System: Windows 10, Ubuntu 22
- Browser: Firefox
- Other info: The reload button is broken on older versions as well, specifically on 1.29.2, calling `await page.reload()` behaves as expected but manually pressing the reload button in debug mode causes a similar bug.

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'], },
    },
});
```

**Test file (self-contained)**

```js
it('should reload properly', async ({ page }) => {
	await page.goto('https://www.iana.org/domains/reserved');
	await page.mouse.wheel(0, 200);

	const history = await page.evaluate('history.length');
	await page.pause(); // back button disabled
	await page.reload(); 
	await page.pause(); // back button is enabled at this point 
	expect(await page.evaluate('history.length')).toBe(history); // new entry to the same page pushed

	expect(await page.evaluate('scrollY')).toBe(200); // scroll is reset to top
});
```

**Steps**
- Run the test

**Expected**
Scroll is restored, history remains same as in the consumer versions of firefox or other PW browsers.

**Actual**
New history entry with null state is pushed on. Scroll is reset to the top.

**Comment by aslushnikov** [comment] 2023-05-10 15:31
For the record: this is bisected to the `pref("fission.webContentIsolationStrategy", 0);` preference that we use today.

**Comment by aslushnikov** [comment] 2023-05-10 15:48
Filed upstream: https://bugzilla.mozilla.org/show_bug.cgi?id=1832341

**Comment by benmccann** [comment] 2023-05-11 02:42
Thanks for tracking that down! Would it be possible to remove the use of that preference until the issue is resolved upstream?

**Comment by aslushnikov** [comment] 2023-05-11 03:42
> Would it be possible to remove the use of that preference until the issue is resolved upstream?

@benmccann I don't think so: without this preference, we won't be able to interact with out-of-process iframes in firefox.

If you're sure you don't have any OOPIFs in your tests, you can try overriding this preference with another value using `firefoxUserPrefs` option in `firefox.launch()` method.

**Comment by benmccann** [comment] 2023-05-11 03:52
Thanks for the suggestion @aslushnikov. However, it looks like https://github.com/microsoft/playwright/issues/15405 probably needs to be addressed before that's a possibility.

Even if changing the preference breaks OOPIFs, it's possible that's the lesser of two evils. Something will be broken either way - it's either history/reloads or OOPIFs and I'd expect the former is more common.

**Comment by aslushnikov** [comment] 2023-05-12 20:07
@benmccann the https://github.com/microsoft/playwright/issues/15405 is fixed now, so you can pass `fission.webContentIsolationStrategy: 1` to opt-out in the default behavior. (starting from upcoming 1.34)

> Even if changing the preference breaks OOPIFs, it's possible that's the lesser of two evils.

We discussed this with the team, but decided to stick with the defaults for now. In the long run, either we fully support OOPIF's, or Firefox team will fix upstream behavior.

Closing this for now in favor of the upstream issue since there's nothing more to be done here.

**Closed by aslushnikov** 2023-05-12 20:07 UTC
Labels: browser-firefox, v1.34

**Comment by chris13524** [comment] 2023-05-23 21:21
It seems that when setting `fission.webContentIsolationStrategy: 1` [like this](https://github.com/microsoft/playwright/issues/23210#issuecomment-1558468250) that calling `page.reload()` after a navigation causes an error.

```javascript
import { test, expect } from '@playwright/test';

test('reload works', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  await page.getByRole('link', { name: 'Get started' }).click();
  await page.reload();
});
```

    Error: page.reload: NS_BINDING_ABORTED; maybe frame was detached?
    =========================== logs ===========================
    waiting for navigation until "load"
    ============================================================

      4 |   await page.goto('https://playwright.dev/');
      5 |   await page.getByRole('link', { name: 'Get started' }).click();
    > 6 |   await page.reload();
        |              ^
      7 | });

If I wait for a `networkidle` load state before reloading, then the test cases passes. However, my real-world code still errors for some reason so this workaround doesn't work for me.

```javascript
await page.getByRole('link', { name: 'Get started' }).click();
await page.waitForLoadState("networkidle");
await page.reload();
```
