### ISSUE TITLE
[BUG] Webkit does not support basic auth over websockets

### ISSUE THREAD

**Issue by unlikelyzero** [microsoft/playwright#10417] opened 2021-11-18 18:05 UTC
## Context
- Playwright Version: 1.14, 1.16.3, 1.18.0-alpha-nov-18-2021
- Operating System: mac
- Node.js version: 14
- Browser: webkit
- Extra: ~/Library/Caches/ms-playwright/webkit-1578

#### testcode
```javascript
test('my test', async ({ page }) => {
        try {
            await page.on('console', msg => console.log(msg.text()));
            await page.goto('<server with basic auth>');
            await page.waitForTimeout(3000);
        } catch (e){
            console.error({ error }, 'Something happened!');
        }
  });
});
```
#### plawright.config.js
```javascript
projects: [
...
{  
      name: "local-webkit",
      use: {
        headless: false,
        browserName: 'webkit',
        httpCredentials: {
            'username': process.env.E2E_USERNAME,
            'password': process.env.E2E_PASSWORD
        },
        ignoreHTTPSErrors: false,
      },
    }
]
```

#### console output
```
> npm run test:pw:local
DEBUG=pw:error npx playwright test --config=playwright.config.js --project local-webkit

Using config at ~/playwright.config.js

Running 1 test using 1 worker

  ✓  [local-webkit] › test1.spec.js:4:3 › feature foo › my test (19s)
WebSocket connection to '<server with basic auth>' failed: Unexpected response code: 401
Event
Websocket error, attempting reconnect...
Websocket closed. Attempting to reconnect...
WebSocket connection to '<server with basic auth>' failed: Unexpected response code: 401
Event
Websocket error, attempting reconnect...
Websocket closed. Attempting to reconnect...
WebSocket connection to '<server with basic auth>' failed: Unexpected response code: 401
Event
Websocket error, attempting reconnect...
Websocket closed. Attempting to reconnect...

  Slow test file: [local-webkit] › test1.spec.js (19s)
  Consider splitting slow test files to speed up parallel execution
```

## Describe the bug

This config works great with Chrome and Firefox. Does not work on webkit due to https://bugs.webkit.org/show_bug.cgi?id=80362

I just wanted to bring this up so that the playwright documentation can be updated with a warning OR the playwright community could be aware of this problem.

**Comment by JoelEinbinder** [comment] 2021-11-18 20:23
Interesting!

I don't think there is anything for us to do here, so I'll close this issue. Technically Playwright is working as intended by showing browser differences, but I can see how your e2e tests might require auth while your production does not.

Thanks for filing

**Closed by JoelEinbinder** 2021-11-18 20:23 UTC

**Comment by unlikelyzero** [comment] 2021-11-21 13:08
@JoelEinbinder apparently this bug has been fixed in Mac OS12.
