### ISSUE TITLE
[BUG] Since update to 1.31 response end of iframe too high

### ISSUE THREAD

**Issue by Smrtnyk** [microsoft/playwright#21185] opened 2023-02-24 12:54 UTC
**Context:**
- Playwright Version: 1.31.1
- Operating System: Windows
- Browser: Chromium

## System:
 - OS: Windows 10 10.0.22621
 - Memory: 34.09 GB / 63.69 GB
## Binaries:
 - Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
 - npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD

**Code Snippet**

Given this test

```typescript
import {
    expect,
    test
} from "@playwright/test";

test("iframe test", async ({ page }) => {
    await page.route("**/*", async (route, request) => {
        const response = await fetch(request.url());
        const body = await response.text();
        const headers = Object.fromEntries(response.headers.entries());
        return route.fulfill({ body, headers });
    });
    await page.goto("http://127.0.0.1:5500/main.html");
    const iframeTiming = await page.evaluate(() => {
        return performance
            .getEntriesByType("resource")
            .filter(entry => entry.initiatorType === "iframe")[0];
    });
    const frameTimings = await page.evaluate(() => {
        return window.frames[0].performance.getEntriesByType("resource").map(entry => entry.toJSON());
    });
    console.log(iframeTiming.responseEnd);
    console.log(frameTimings[0].responseEnd);
    expect(iframeTiming.responseEnd < frameTimings[0].responseEnd).toBe(true);
});

```
and main.html frame
```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Main frame</title>
</head>
<body>
<iframe width="1000" height="1000" src="/frame.html"></iframe>
</body>
</html>

```

and iframe
```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>IFRAME</title>
</head>
<body>
<h1>IFRAME</h1>
<img
width="1000"
height="1000"
src="https://images.unsplash.com/photo-1654078644513-29f003c0fcd4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=4000&q=80" />
</body>
</html>

```

Put main.html and iframe.html in the same dir.
Serve main.html using vs code live server.
Run the test on 1.30.0, it succeeds all the time
Update to 1.31.1 and it fails all the time.

**Describe the bug**
Since update to 1.31.1 responseEnd of iframe is always higher than responseEnd of iframe content, specifically long loading image in an iframe.
Prior to 1.31 version we used 1.30 and iframe responseEnd was very low, and always lower than responseEnd of long loading image located in an iframe.
We have quite sophisticated rum tests and two of them started failing after updated to 1.31.1.
This doesn't happen if you remove the block
```typescript
await page.route("**/*", async (route, request) => {
        const response = await fetch(request.url());
        const body = await response.text();
        const headers = Object.fromEntries(response.headers.entries());
        return route.fulfill({ body, headers });
    });
```
 from the test so that no interception happens.
This doesn't happen on firefox and webkit, just chromium.

**Comment by yury-s** [comment] 2023-02-24 21:58
This is caused by the following upstream change https://chromium-review.googlesource.com/c/chromium/src/+/4145963 , I filed upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1419548

**Comment by yury-s** [comment] 2023-03-02 18:32
Closing this report as there is nothing to do on the playwright end. This is an upstream issue, please follow the progress in the [upstream bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1419548).

**Closed by yury-s** 2023-03-02 18:32 UTC
Labels: browser-chromium, v1.32
