### ISSUE TITLE
[BUG] run test in  playwright docker in my mac  Error: browser.newContext: Target page, context or browser has been closed

### ISSUE THREAD

**Issue by sherlockfeng** [microsoft/playwright#28333] opened 2023-11-25 05:09 UTC
### System info
- Playwright Version: [v1..40.0]
- Operating System: [macOS 14.1]
- Browser: [Chromium]
- Other info:

### Source code
just run npm init playwright@latest

**Steps**
docker pull mcr.microsoft.com/playwright:v1.40.0-jammy
docker run -it --rm --ipc=host mcr.microsoft.com/playwright:v1.40.0-jammy /bin/bash
mkdir playwright-test
cd playwright-test
npm init playwright@latest
npx playwright test

**Expected**

running test success

**Actual**

Running 6 tests using 4 workers
  1) [chromium] › example.spec.ts:3:5 › has title ──────────────────────────────────────────────────

    Error: browser.newContext: Target page, context or browser has been closed
    Browser logs:

    <launching> /ms-playwright/chromium-1091/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-bR0wb6 --remote-debugging-pipe --no-startup-window
    <launched> pid=900
    [pid=900][err] Received signal Received signal 11 <unknown> 557fe6a0a008
    [pid=900][err] #0 0x557fdfc41572 11 <unknown> 5651f0f02008
    [pid=900][err] #0 0x5651ea139572 base::debug::CollectStackTrace()
    [pid=900][err] #1 0x557fdfc2df43 base::debug::CollectStackTrace()
    [pid=900][err] #1 0x5651ea125f43 base::debug::StackTrace::StackTrace()
    [pid=900][err] #2 0x557fdfc40f91 base::debug::StackTrace::StackTrace()
    [pid=900][err] #2 0x5651ea138f91 base::debug::(anonymous namespace)::StackDumpSignalHandler()
    [pid=900][err] #3 0x7f4620f93520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
    [pid=900][err] #4 0x557fdefdf2ab base::debug::(anonymous namespace)::StackDumpSignalHandler()
    [pid=900][err] #3 0x7f9698c15520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
    [pid=900][err] #4 0x5651e94d72ab content::RunContentProcess()
    [pid=900][err] #5 0x557fdefdf64d content::ContentMain()
    [pid=900][err] #6 0x557fdf6838fa content::RunContentProcess()
    [pid=900][err] #5 0x5651e94d764d content::ContentMain()
    [pid=900][err] #6 0x5651e9b7b8fa headless::HeadlessShellMain()
    [pid=900][err] #7 0x557fdb3cb25a headless::HeadlessShellMain()
    [pid=900][err] #7 0x5651e58c325a ChromeMain
    [pid=900][err] #8 0x7f4620f7ad90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    [pid=900][err] #9 0x7f4620f7ae40 __libc_start_main
    [pid=900][err] #10 0x557fdb3cb02a ChromeMain
    [pid=900][err] #8 0x7f9698bfcd90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    [pid=900][err] #9 0x7f9698bfce40 __libc_start_main
    [pid=900][err] #10 0x5651e58c302a _start
    [pid=900][err]   r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000000 r11: 0000000000000202
    [pid=900][err]  r12: 00007ffe6df36350 r13: 0000557fdb3cb0f0 r14: 00000000ffffffff r15: 00007ffe6df36348
    [pid=900][err]   di: 0000000000000000  si: 00007ffe6df360b0  bp: 00007ffe6df363a0  bx: 0000113400264000
    [pid=900][err]   dx: 0000000000000000  ax: 0000000000000000  cx: 0000557fe6a0a000  sp: 00007ffe6df36100
    [pid=900][err]   ip: 0000557fdefdf2ab efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000025
    [pid=900][err]  trp: 000000000000000e msk: 0000000000000000 cr2: 0000557fe6a0a008
    [pid=900][err] [end of stack trace]
    [pid=900][err] _start
    [pid=900][err]   r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000000 r11: 0000000000000206
    [pid=900][err]  r12: 00007ffee2c8f720 r13: 00005651e58c30f0 r14: 00000000ffffffff r15: 00007ffee2c8f718
    [pid=900][err]   di: 0000000000000000  si: 00007ffee2c8f480  bp: 00007ffee2c8f770  bx: 00000b7000264000
    [pid=900][err]   dx: 0000000000000000  ax: 0000000000000000  cx: 00005651f0f02000  sp: 00007ffee2c8f4d0
    [pid=900][err]   ip: 00005651e94d72ab efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000025
    [pid=900][err]  trp: 000000000000000e msk: 0000000000000000 cr2: 00005651f0f02008
    [pid=900][err] [end of stack trace]
    [pid=900][err] [1125/045944.649644:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
    [pid=900][err] [1125/045944.657995:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
    [pid=900][err] [1125/045944.658298:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
    [pid=900][err] [1125/045944.676228:ERROR:gpu_process_host.cc(986)] GPU process launch failed: error_code=1002
    [pid=900][err] [1125/045944.676292:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 1 time(s)
    [pid=900][err] [1125/045944.676564:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
    [pid=900][err] [1125/045944.684730:ERROR:gpu_process_host.cc(986)] GPU process launch failed: error_code=1002
    [pid=900][err] [1125/045944.684754:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 2 time(s)
    [pid=900][err] [1125/045944.690028:ERROR:gpu_process_host.cc(986)] GPU process launch failed: error_code=1002
    [pid=900][err] [1125/045944.690056:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 3 time(s)
    [pid=900][err] [1125/045944.692071:ERROR:gpu_process_host.cc(986)] GPU process launch failed: error_code=1002
    [pid=900][err] [1125/045944.692134:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 4 time(s)
    [pid=900][err] [1125/045944.693472:ERROR:gpu_process_host.cc(986)] GPU process launch failed: error_code=1002
    [pid=900][err] [1125/045944.693492:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 5 time(s)
    [pid=900][err] [1125/045944.695321:ERROR:gpu_process_host.cc(986)] GPU process launch failed: error_code=1002
    [pid=900][err] [1125/045944.695343:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 6 time(s)
    [pid=900][err] [1125/045944.697051:ERROR:gpu_process_host.cc(986)] GPU process launch failed: error_code=1002
    [pid=900][err] [1125/045944.697073:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 7 time(s)
    [pid=900][err] [1125/045944.697884:ERROR:gpu_process_host.cc(986)] GPU process launch failed: error_code=1002
    [pid=900][err] [1125/045944.697903:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 8 time(s)
    [pid=900][err] [1125/045944.698814:ERROR:gpu_process_host.cc(986)] GPU process launch failed: error_code=1002
    [pid=900][err] [1125/045944.698833:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 9 time(s)
    [pid=900][err] [1125/045944.698848:FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.
    [pid=900][err] #0 0x55f68ce7c572 base::debug::CollectStackTrace()
    [pid=900][err] #1 0x55f68ce68f43 base::debug::StackTrace::StackTrace()
    [pid=900][err] #2 0x55f68cdc1eb3 logging::LogMessage::~LogMessage()
    [pid=900][err] #3 0x55f68ae3c2fa content::(anonymous namespace)::IntentionallyCrashBrowserForUnusableGpuProcess()
    [pid=900][err] #4 0x55f68ae38f41 content::GpuDataManagerImplPrivate::FallBackToNextGpuMode()
    [pid=900][err] #5 0x55f68ae37aab content::GpuDataManagerImpl::FallBackToNextGpuMode()
    [pid=900][err] #6 0x55f68ae446e3 content::GpuProcessHost::RecordProcessCrash()
    [pid=900][err] #7 0x55f68ae45d67 content::GpuProcessHost::OnProcessLaunchFailed()
    [pid=900][err] #8 0x55f68ac2fd31 content::BrowserChildProcessHostImpl::OnProcessLaunchFailed()
    [pid=900][err] #9 0x55f68acac5f2 content::internal::ChildProcessLauncherHelper::PostLaunchOnClientThread()
    [pid=900][err] #10 0x55f68acac93c base::internal::Invoker<>::RunOnce()
    [pid=900][err] #11 0x55f68ce10b0a base::TaskAnnotator::RunTaskImpl()
    [pid=900][err] #12 0x55f68ce29fcc base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
    [pid=900][err] #13 0x55f68ce299eb base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
    [pid=900][err] #14 0x55f68ce2a475 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
    [pid=900][err] #15 0x55f68ce8edb1 base::MessagePumpGlib::HandleDispatch()
    [pid=900][err] #16 0x55f68ce8f6bd base::(anonymous namespace)::WorkSourceDispatch()
    [pid=900][err] #17 0x7eff86e81d3b g_main_context_dispatch
    [pid=900][err] #18 0x7eff86ed7258 (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.4+0xab257)
    [pid=900][err] #19 0x7eff86e7f3e3 g_main_context_iteration
    [pid=900][err] #20 0x55f68ce8ef4b base::MessagePumpGlib::Run()
    [pid=900][err] #21 0x55f68ce2a969 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
    [pid=900][err] #22 0x55f68cdf1d7a base::RunLoop::Run()
    [pid=900][err] #23 0x55f68ac4e2aa content::BrowserMainLoop::RunMainMessageLoop()
    [pid=900][err] #24 0x55f68ac4fe72 content::BrowserMainRunnerImpl::Run()
    [pid=900][err] #25 0x55f69338c88d headless::HeadlessContentMainDelegate::RunProcess()
    [pid=900][err] #26 0x55f68c21b6b7 content::RunBrowserProcessMain()
    [pid=900][err] #27 0x55f68c21cfa0 content::ContentMainRunnerImpl::RunBrowser()
    [pid=900][err] #28 0x55f68c21cd6c content::ContentMainRunnerImpl::Run()
    [pid=900][err] #29 0x55f68c21a428 content::RunContentProcess()
    [pid=900][err] #30 0x55f68c21a64d content::ContentMain()
    [pid=900][err] #31 0x55f68c8be7c5 headless::HeadlessShellMain()
    [pid=900][err] #32 0x55f68860625a ChromeMain
    [pid=900][err] #33 0x7eff86123d90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    [pid=900][err] #34 0x7eff86123e40 __libc_start_main
    [pid=900][err] #35 0x55f68860602a _start
    [pid=900][err] Task trace:
    [pid=900][err] #0 0x55f68acac461 content::internal::ChildProcessLauncherHelper::PostLaunchOnLauncherThread()
    [pid=900][err] #1 0x55f68acabc78 content::internal::ChildProcessLauncherHelper::StartLaunchOnClientThread()
    [pid=900][err] #2 0x55f68d821c38 mojo::SimpleWatcher::Context::Notify()
    [pid=900][err] #3 0x55f68d821c38 mojo::SimpleWatcher::Context::Notify()
    [pid=900][err] #4 0x55f68d821c38 mojo::SimpleWatcher::Context::Notify()
    [pid=900][err] Task trace buffer limit hit, update PendingTask::kTaskBacktraceLength to increase.
    [pid=900][err]

  2) [chromium] › example.spec.ts:10:5 › get started link ──────────────────────────────────────────

    Error: browserContext.newPage: Target page, context or browser has been closed

  2 failed
    [chromium] › example.spec.ts:3:5 › has title ───────────────────────────────────────────────────
    [chromium] › example.spec.ts:10:5 › get started link ───────────────────────────────────────────
  4 passed (8.4s)

**Comment by sherlockfeng** [comment] 2023-11-25 06:43
add --disable-gpu-sandbox   solved

**Comment by mxschmitt** [comment] 2023-11-26 11:06
Crashing in [IntentionallyCrashBrowserForUnusableGpuProcess](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/gpu/gpu_data_manager_impl_private.cc;l=447?q=IntentionallyCrashBrowserForUnusableGpuProcess&ss=chromium%2Fchromium%2Fsrc) since there is no usable GPU. Disabling the GPU or sandbox sounds like a plausible option. Since this is Chromium related we cannot do there much, I recommend filing a bug at crbug.com if needed.

**Comment by vaishalisoni1093** [comment] 2023-11-27 09:18
Even I am facing same issue from last week.

**Comment by mxschmitt** [comment] 2023-11-27 11:56
I tried to reproduce it on my M1 Linux but was unfortunately not able to. @vaishalisoni1093 how does your repro scenario look like? Are you also on M1 mac?

**Comment by richmar10** [comment] 2023-11-28 15:42
Hi,  When I updated to version 1.40, I started running into the same intermittent issue with a different setup.
`Error: Target page, context or browser has been closed`

Setup: 
- Windows 10, Node 18 & 20, PW 1.40,  VSCode:  "Show browser" = checked
- 5 Tests, run in serial.   Some tests open a second tab.

I noticed that there's timing issue if the chromium window is left open between tests.  The test fail fast, usually within 90 milliseconds.

Workaround:  Add `await page.close()` in between tests or in an afterEach function.
I'm happy to demo the issue if we're having trouble reproducing it.

**Comment by pavelfeldman** [comment] 2023-11-28 15:59
Does the same happen when you run tests locally? Is there a way for us to reproduce this issue locally? Sounds like it is specific to your tests logic.

**Comment by pavelfeldman** [comment] 2023-11-30 21:14
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Closed by pavelfeldman** 2023-11-30 21:14 UTC
Labels: triaging

**Comment by sherlockfeng** [comment] 2023-12-01 06:27
> Does the same happen when you run tests locally? Is there a way for us to reproduce this issue locally? Sounds like it is specific to your tests logic.

i have not write any local logic. Everthing are same as `npm init playwright@latest`

**Comment by cjhille** [comment] 2024-01-15 23:06
I'm encountering the same issue on 
- i5 mac
- Docker version 24.0.7, build afdd53b
- playwright 1.39.0 with chromium

**Comment by JKFSOM** [comment] 2024-02-25 08:16
I'm also experiencing issues on an M1 Mac running tests inside of Docker, in various browsers (including Chrome and Firefox). I don't experience any issues when running on my machine (rather than inside of a Docker container).

The resources Docker has access to are essentially unconstrained, and failures are inconsistent. On some runs I get `Target page, context or browser has been closed`, on others the test case(s) pass. It is never true that all tests - where there are multiple - fail, just a (seemingly random) selection.

For the avoidance of doubt, I've increased timeouts, experiment with a single and multiple workers, set `ipc=host` and `cap_add=SYS_ADMIN` (as per https://playwright.dev/docs/ci#docker).

Docker Engine: `v25.0.3`; Playwright image: `mcr.microsoft.com/playwright:v1.41.2`.

**Comment by jrpool** [comment] 2025-01-26 19:49
Similar issue. `await browserContext.newPage()` succeeds in a local installation, but, if I containerize that same installation locally and run the same procedure on the same host I get this error on that statement:

`browserContext.newPage: Target page, context or browser has been closed`

In this case I am using `webkit`.
