### ISSUE TITLE
[BUG] Page.click() hits the wrong menu item and throws no errors.

### ISSUE THREAD

**Issue by shtlrs** [microsoft/playwright#8183] opened 2021-08-13 13:32 UTC
**Context:**
- Playwright Version: [@playwright/test : ^1.13.0]
- Operating System: Windows 10
- Node.js version: [v14.17.2]
- Browser: [Chromium]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const { test, expect } = require('@playwright/test');

test('test', async ({ page }) => {

  await page.goto('https://www.expensya.com/');

  await page.goto('https://www.expensya.com/en/');

  await page.click('button[role="button"]:has-text("Accept")');

  await page.click(':nth-match(:text("Login"), 2)');
  expect(page.url()).toBe('https://app.expensya.com/Portal/#/Login?lang=en');

  await page.fill('[placeholder="Email"]', 'pwbug@yopmail.com');

  await page.click('[placeholder="Password"]');

  await page.fill('[placeholder="Password"]', 'pwbug@yopmail.comA');

  await Promise.all([
    page.waitForNavigation(/*{ url: 'https://app.expensya.com/Portal/#/Dashboard' }*/),
    page.click('button:has-text("Login")')
  ]);

  await page.click('text=Accepter');

  await Promise.all([
    page.waitForNavigation(/*{ url: 'https://app.expensya.com/Portal/#/Admin/CompanyEmployees?page=1' }*/),
    page.click('text=Administration')
  ]);

  await page.click('text=Dépenses et demandes');

  await Promise.all([
    page.waitForNavigation(/*{ url: 'https://app.expensya.com/Portal/#/Admin/Rules?page=1' }*/),
    page.click('text=Politiques de dépenses')
  ]);

await page.click("#addNewRule);
});
```

**Describe the bug**

We have a lot of accordion menus that collapse multiple items ( elements) when clicked on.
The collapsing of the menu is animated and it has ( 3 or more items)
When we try to click on element3, page.click() hits another item in the menu and doesn't throw an error.
PLus, no error is thrown and playwright thinks it clicked on the correct item.

**Comment by pavelfeldman** [comment] 2021-08-14 02:29
Looks like a regression to me.

**Comment by dgozman** [comment] 2021-08-16 18:45
@shtlrs Thank you for the great repro! I tried running it multiples times using `@playwright/test` v1.14 (the latest), and it works for me every time.

I'd suggest to record a trace using [`trace: 'on'` option](https://playwright.dev/docs/test-configuration#record-test-trace) and then use [Trace Viewer](https://playwright.dev/docs/trace-viewer) to inspect it. You can also attach the trace file here so I can take a look myself.

**Comment by shtlrs** [comment] 2021-08-17 08:50
Hi @dgozman,

ALright, thanks for the effort.
I'll have a run at it with the latest release and let you know.

**Comment by shtlrs** [comment] 2021-08-18 10:49
Hi again @dgozman ,

Unfortunately, i still reproduce it sometimes with the same scenario and the latest release (1.14.0)
Here's the trace like you asked
[trace.zip](https://github.com/microsoft/playwright/files/7006543/trace.zip)

**Comment by dgozman** [comment] 2021-09-08 20:56
@shtlrs Thank you for the trace! There is indeed a problem, and I think there was a race somewhere around clicking. Perhaps the element did jump while Playwright was clicking, or maybe Playwright did not detect the animation properly.

Unfortunately, I cannot reproduce this locally to even start debugging it. Just looking at the page and the code, I was not able to find the culprit. We often spend days on similar problems where it is very hard to understand what's going on. I will close this issue, but feel free to open a new one if you get a more reliable repro script.

**Closed by dgozman** 2021-09-08 20:56 UTC
Labels: v1.15
