### ISSUE TITLE
[Question]: how can i process all pages in one browser from firefox which look like when i use chromium

### ISSUE THREAD

**Issue by guguji12345** [microsoft/playwright#22574] opened 2023-04-23 07:57 UTC
### Your question

example: 
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-


import aiohttp, asyncio
from playwright.async_api import async_playwright


async def main(*args):
    async with async_playwright() as p:
        browser = await p.firefox.launch(headless=False)

        # browser = await p.chromium.launch(headless=False)
        context = await browser.new_context()
        [await context.new_page() for i in range(30)]
        breakpoint()

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```
**when i use chromium**:
![image](https://user-images.githubusercontent.com/51038039/233827093-3f633270-1cbc-45f2-9512-500b1b471f7b.png)

**when i use firefox**:
![image](https://user-images.githubusercontent.com/51038039/233827058-7a1c169d-f39d-4e8f-ade1-a9deedeef32d.png)

> Playwright version 1.27.0
> python version 3.8.5

**Comment by mxschmitt** [comment] 2023-04-24 07:38
Looks similar to https://github.com/microsoft/playwright/issues/3696.

**Comment by aslushnikov** [comment] 2023-04-25 05:21
Closing as dupe of https://github.com/microsoft/playwright/issues/3696

**Closed by aslushnikov** 2023-04-25 05:21 UTC
