### ISSUE TITLE
[BUG] elementHandle.scrollIntoViewIfNeeded doesn't work properly

### ISSUE THREAD

**Issue by VikramTiwari** [microsoft/playwright#4134] opened 2020-10-14 02:16 UTC
**Context:**
- Playwright Version: 1.4.2
- Operating System: Mac
- Node.js version: 12
- Browser: Chromium
- Extra: NA

**Describe the bug**
`elementHandle.scrollIntoViewIfNeeded` won't scroll if the element is partially visible. I think this might be unexpected behavior but I don't see any details about this method on [CDP](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-scrollIntoViewIfNeeded).

```
2020-10-14T02:00:16.457Z pw:api => elementHandle.scrollIntoViewIfNeeded started
2020-10-14T02:00:16.458Z pw:api   waiting for element to be visible and not moving
2020-10-14T02:00:16.481Z pw:api   element is visible and does not move
2020-10-14T02:00:16.482Z pw:api <= elementHandle.scrollIntoViewIfNeeded succeeded
```

Here's the page with selected element that I am trying to scroll into view

<img width="1358" alt="Screen Shot 2020-10-13 at 7 12 35 PM" src="https://user-images.githubusercontent.com/1330677/95935547-55bb8c80-0d88-11eb-80ee-1e2345671650.png">

**Comment by dgozman** [comment] 2020-10-14 09:43
Is it possible to share the url, or save the page as mhtml and attach here, or provide a sample page where this problem does reproduce? That would help greatly!

**Comment by VikramTiwari** [comment] 2020-10-15 00:11
Hey @dgozman, here's the [page](https://www.linkedin.com/sales/search/people?companyIncluded=Amazon%3A1586%2CApple%3A162479%2CMicrosoft%3A1035%2CFord%2520Motor%2520Company%3A1483&companyTimeScope=CURRENT&doFetchHeroCard=false&geoIncluded=103644278%2C101174742&logHistory=false&page=1&preserveScrollPosition=false&searchSessionId=jgVZmZQgToaoiiGBz9WCOQ%3D%3D&spellingCorrectionEnabled=false). However you need linkedin sales navigator to access that URL.

**Comment by dgozman** [comment] 2020-11-02 15:50
Sorry for the late response. I looked at this page, and there is a `position:fixed` header that covers the item, and we are not scrolling the item from under that header. Reduced repro:

```html
<style>
* {
  padding: 0;
  margin: 0;
}
li {
  height: 80px;
  border: 1px solid black;
}
ol {
  padding-top: 104px;
}
div.fixed {
  position: fixed;
  z-index: 1001;
  width: 100%;
  background: red;
  height: 104px;
}
</style>

<div class=fixed></div>

<ol>
<li>hi1</li><li>hi2</li><li>hi3</li><li>hi4</li><li>hi5</li><li>hi6</li><li>hi7</li><li>hi8</li><li>hi9</li><li>hi10</li><li>hi11</li><li>hi12</li><li>hi13</li><li>hi14</li>
</ol>

```

**Comment by dgozman** [comment] 2020-11-09 17:51
Duplicate of #3105.

**Closed by dgozman** 2020-11-09 17:51 UTC

**Comment by VikramTiwari** [comment] 2020-11-09 19:01
Oh nice! I am glad you were able to recreate it in a standalone manner and that this is a known bug. Thanks for following up on this. :)
