### ISSUE TITLE
[BUG] No docker image for Playwright v 1.17.2

### ISSUE THREAD

**Issue by cardinalX** [microsoft/playwright#11299] opened 2022-01-10 16:49 UTC
Context:

Playwright Version: 1.17.2
Operating System: Mac OS intel
Node.js version: 14.x

I retrieved playwright version from package.json which is 1.17.2 and download the docker image.

mcr.microsoft.com/playwright:v1.17.2-focal - Not exist
mcr.microsoft.com/playwright:v1.17.1-focal - Exist

**Comment by aslushnikov** [comment] 2022-01-10 17:04
dupe of https://github.com/microsoft/playwright/issues/11292

**Closed by aslushnikov** 2022-01-10 17:04 UTC
