### ISSUE TITLE
[Feature] allow client certificate selection and settings from Javascript ?

### ISSUE THREAD

**Issue by adsdiarySEO21** [microsoft/playwright#21609] opened 2023-03-13 05:34 UTC
Similarly to https://github.com/puppeteer/puppeteer/issues/540

Currently when navigating to a page that requires client certificates and client certificates are available a popup is shown in Firefox and Chrome which asks to select which certificate to use. It would be beneficial to provide an API to select the correct certificate to use (or use none). [Digital marketing in Lahore](https://Adsdiary.pk)

**Comment by dgozman** [comment] 2023-03-13 20:55
Duplicate of #1799.

**Closed by dgozman** 2023-03-13 20:55 UTC
