### ISSUE TITLE
[Bug]: resources get loaded in firfox while using route.abort()

### ISSUE THREAD

**Issue by zeyadkhaled1** [microsoft/playwright#33456] opened 2024-11-05 08:34 UTC
### Version

v1.48.0

### Code
```python
def main():
    with sync_playwright() as p:
        browser:Browser = p.firefox.launch(headless=True,slow_mo=1000,
            args=['--disable-blink-features=AutomationControlled','--start-maximized'])
        context:BrowserContext = browser.new_context(  locale="en-US",
            record_video_dir='videos',
            bypass_csp=True,
            color_scheme='dark',
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.18 Safari/537.36")
        page:Page = context.new_page()
        page.route("**/*", lambda route: route.abort() if route.request.resource_type in ['image', 'media'] else route.continue_())
        page.goto('https://www.asos.com/birkenstock/birkenstock-unisex-boston-clogs-in-faded-khaki-suede/prd/206781439')
        page.wait_for_selector('#variantSelector',timeout=30000)
        page.close()
        context.close()
        browser.close()
if __name__ == '__main__':
    main()
```

### Expected behavior

no images should load when visiting the webpage in header or headless mode

### Actual behavior

images are loaded in both header and headless mode only in firefox browser
_

### Environment

- Operating System: [Windows10 22H2 19045.5011]
- CPU: AMD Ryzen 5 PRO 2500U
- Browser: Firefox
- Python Version: [3.11.1]

**Comment by mxschmitt** [comment] 2024-11-05 14:28
Seems like a duplicate of https://github.com/microsoft/playwright/pull/33195 which should be fixed in v1.49.

As a workaround you can do:

    if route.request.resource_type in ['image', 'images', 'media']

**Closed** 2024-11-05 14:28 UTC
