### ISSUE TITLE
[Question] does playwright support lower version chrome? like chrome 50 or lower

### ISSUE THREAD

**Issue by saselovejulie** [microsoft/playwright#6265] opened 2021-04-22 09:19 UTC
our Linux server running with 500mb memory can't start chrome 90+.
if i download chrome 50 or lower and update execute path, does our API support it?
thanks

**Comment by aslushnikov** [comment] 2021-04-22 15:31
> if i download chrome 50 or lower and update execute path, does our API support it?

No, this won't work with Playwright. 

> our Linux server running with 500mb memory can't start chrome 90+.

How exactly does it fail? Do you start headless or headful?

**Comment by saselovejulie** [comment] 2021-04-23 09:31
> No, this won't work with Playwright.
thanks

> How exactly does it fail? Do you start headless or headful? 
after about two hour running server crashed.
cpu full memory full.
no response. only choice is restart server.
server is same level like amazon nano

**Comment by saselovejulie** [comment] 2021-04-23 09:31
> No, this won't work with Playwright.
thanks

> How exactly does it fail? Do you start headless or headful? 
after about two hour running server crashed.
cpu full memory full.
no response. only choice is restart server.
server is same level like amazon nano

**Comment by mxschmitt** [comment] 2021-04-26 22:01
Are you using the same page/context to interact there with your web page or navigate on it to different websites over and over again? If so, then its a duplicate of #6319. Currently only on creating/closing a new context the memory is released.

**Comment by dgozman** [comment] 2021-05-04 20:12
Closing since there is no action item here. Please comment here if we missed something, and we'll reopen.

**Closed by dgozman** 2021-05-04 20:12 UTC
Labels: triaging
