### ISSUE TITLE
[Bug]: Run error：[pid=969][err] [FATAL:partition_root.cc(952)] Check failed: (internal::SystemPageSize() == (size_t{1} << 12)) || (internal::SystemPageSize() == (size_t{1} << 14))

### ISSUE THREAD

**Issue by wm475390847** [microsoft/playwright#32607] opened 2024-09-13 10:24 UTC
### Version

1.42.0

### Steps to reproduce

  message='Timeout 180000ms exceeded.
  name='TimeoutError
  stack='TimeoutError: Timeout 180000ms exceeded.
    at ProgressController.run (/tmp/playwright-java-4784722190175374360/package/lib/server/progress.js:78:26)
    at Chromium.launch (/tmp/playwright-java-4784722190175374360/package/lib/server/browserType.js:61:38)
    at BrowserTypeDispatcher.launch (/tmp/playwright-java-4784722190175374360/package/lib/server/dispatchers/browserTypeDispatcher.js:35:40)
    at BrowserTypeDispatcher._handleCommand (/tmp/playwright-java-4784722190175374360/package/lib/server/dispatchers/dispatcher.js:94:40)
    at DispatcherConnection.dispatch (/tmp/playwright-java-4784722190175374360/package/lib/server/dispatchers/dispatcher.js:365:39)
}
Call log:
- <launching> /root/.cache/ms-playwright/chromium-1105/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-KwSWbE --remote-debugging-pipe --no-startup-window
- <launched> pid=969
- [pid=969][err] [FATAL:partition_root.cc(952)] Check failed: (internal::SystemPageSize() == (size_t{1} << 12)) || (internal::SystemPageSize() == (size_t{1} << 14)). 
]

### Expected behavior

Expected success, no timeout

### Actual behavior

element timeout

### Environment

```shell

machine
centos7-arm64

docker-container ·
Linux iZbp1epb0s7ssuvh1zduvuZ 4.18.0-348.20.1.el7.aarch64 #1 SMP Wed Apr 13 20:57:50 UTC 2022 aarch64 GNU/Linux
-----
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by dgozman** [comment] 2024-09-13 14:38
Duplicate of #26491.

**Closed by dgozman** 2024-09-13 14:38 UTC

**Comment by wm475390847** [comment] 2024-09-14 01:54
~~~~
