### ISSUE TITLE
[BUG]  HTML reporter shows "All tests passed" when there are failed tests

### ISSUE THREAD

**Issue by MartinP-Autopilot** [microsoft/playwright#10482] opened 2021-11-22 22:41 UTC
**Context:**
- Playwright Version:1.16.2
- Operating System: Windows and Linux
- Node.js version: 14.17.3
- Browser: All

**Describe the bug**
Refer the below screen shot - there are 3 failed tests but HTML reporter claims "All tests passed."

![image](https://user-images.githubusercontent.com/87287250/142945708-fd120678-8dc9-498f-a1b9-66b1736223cf.png)

**Comment by yury-s** [comment] 2021-11-22 23:51
@MartinP-Autopilot  Can you attach a repro?

**Comment by MartinP-Autopilot** [comment] 2021-11-23 04:02
@yury-s,

Here is our config - 

```
//// @ts-check
///** @type {import('@playwright/test').PlaywrightTestConfig} */

import {PlaywrightTestConfig} from '@playwright/test';

const config = {
  globalSetup: './playwright/playwright_global_setup.ts',
  testDir: 'tests',
  reporter: 'html',
  // Each test is given 4 minutes
  timeout: 240000,
  forbidOnly: true,
  use: {
    headless: true,
    viewport: {width: 1920, height: 1080},
    video: 'retain-on-failure',
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
  },
  reportSlowTests: {
    max: 10,
    threshold: 60000,
  },
};

module.exports = config;
```

and any test that fails will end up being reported in this way, so I would expect - 

```
import {test, expect} from '@playwright/test';
test.describe('describe', () => {
   test('test 1', () => {
      expect(false).toBeTruthy();
   })
});
```

to replicate the problem.

**Comment by JoelEinbinder** [comment] 2021-11-23 08:39
Looks like this was fixed via https://github.com/microsoft/playwright/pull/9889

**Comment by dgozman** [comment] 2021-11-23 22:49
I copied your config and test (had to comment out the `globalSetup`), and I cannot reproduce this one:

```
  Running 1 test using 1 worker

  1 failed
    test2.spec.ts:3:4 › describe › test 1 ==========================================================

  Serving HTML report at http://127.0.0.1:9323. Press Ctrl+C to quit.

```

**Comment by mxschmitt** [comment] 2021-11-26 10:31
@MartinP-Autopilot please try our latest version: `npm install @playwright/test@1.17.0-rc1` if you can still reproduce it, otherwise we would close it.

**Comment by pavelfeldman** [comment] 2021-11-30 23:19
Closing as we believe it has been fixed.

**Closed by pavelfeldman** 2021-11-30 23:19 UTC
Labels: triaging
