### ISSUE TITLE
[Bug]: Playwright VSCode plugin returns Error: Must start tracing before stopping on test completion

### ISSUE THREAD

**Issue by mattdoering-1159** [microsoft/playwright#33499] opened 2024-11-07 19:09 UTC
### Version

Playwright Version: v1.48.2  VSCode Plugin Version: v1.1.11

### Steps to reproduce

**VSCode Version:** 1.93.0
**PW Version:** v1.48.2
**PW Extension Version:** v1.1.11

1.  Run any single test using Playwright VSCode browser plugin (the green play button) 
   Projects: Chromium 
   Settings: Show Browser
2. Notice that after test completes and when results are being built user receives the following error message: 
 Error: Must start tracing before stopping on test completion

### Expected behavior

After completing the test, the results of the test should be displayed. 

### Actual behavior

User received the stated error. 

### Additional context

Please note that this only occurs when running with Show Browser enabled. We resolved the issue by reverting back to the last version of the VSCode plugin. Admittedly this is probably caused by not using the latest version of VSCode. But we are locked and unable to update our VSCode client. 

### Environment

We are running on a VM and the specifications of the machine are locked. So we are unable to provide this information

**Comment by yury-s** [comment] 2024-11-07 23:38
I can't reproduce it on a simple project. Can you try it with the latest VSCode in a local setup and if it still reproduces, share the project where it happens, so that we could run it locally?

**Comment by JanLechvar** [comment] 2024-11-11 14:50
Any chance it is connected to afterAll hook? 
It happens to me in tests where I use afterAll hook and I had to change it to afterEach for a workaround. Can't share details unfortunately. It was not happening in previous versions though.

**Comment by okobets** [comment] 2024-11-12 04:06
One of my team members has starting having this issue today. So far couldn't repro for myself or any other team member, but this is def back!

**Comment by mattdoering-1159** [comment] 2024-11-12 15:35
I can see if I can start a simple pro

> I can't reproduce it on a simple project. Can you try it with the latest VSCode in a local setup and if it still reproduces, share the project where it happens, so that we could run it locally?

Unfortunately I am unable to share the project or update VSCode as it is all client controlled and locked. I did try reproducing the issue locally with a new project and was unable to reproduce. But I also didn't have the time to setup a describe block, and an AfterEach block.

**Comment by pavelfeldman** [comment] 2024-11-12 19:07
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you find time to create the repro!

**Closed by pavelfeldman** 2024-11-12 19:07 UTC

**Comment by ch4r-ch4r** [comment] 2024-11-14 20:09
I'm also running into the same error when Show Browser is enabled. Working on a repro.
