### ISSUE TITLE
[BUG] The report is too verbose

### ISSUE THREAD

**Issue by kamelbou** [microsoft/playwright#27927] opened 2023-11-02 12:47 UTC
### System info
- Playwright Version: [v1.35]
- Operating System: macOS 13.4
- Browser: All
- Other info: N/A

### Source code

N/A

**Config file**

```js
// playwright.config.ts
import type { PlaywrightTestConfig } from '@playwright/test';
import { devices } from '@playwright/test';
import dotenv from 'dotenv';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
dotenv.config({override: false});
/**
 * See https://playwright.dev/docs/test-configuration.
 */

const config: PlaywrightTestConfig = {
  /* Maximum time one test can run for. */
  timeout: 30 * 1000,
  expect: {
    /**
     * Maximum time expect() should wait for the condition to be met.
     * For example in `await expect(locator).toHaveText();`
     */
    timeout: 5000
  },
  /* Run tests in files in parallel */
  fullyParallel: false,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 1 : 0,
  /* Run parallel tests on CI. */
  workers: 1,
  /* Test tags to exclude from the run */
  grepInvert: process.env.EXCLUDED_TESTS?.split(" ").map(tag => new RegExp(tag)),
  /* Test tags to run */
  grep: process.env.INCLUDED_TESTS?.split(" ").map(tag => new RegExp(tag)),
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [
    //[process.env.CI ? 'dot' : 'list'],
    ['html', {open: "never"}],
    ['json'],
    ['junit']
  ],
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    launchOptions: {},
    trace: 'retain-on-failure',
    ignoreHTTPSErrors: true,
    headless: true,
    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    actionTimeout: 0,
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://localhost:3000',
  },
  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 720 },
        // Add the next line:
        launchOptions: { args: ['--disable-gpu', '--single-process', '--no-sandbox'] }
      },
    },
    {
      name: 'firefox',
      use: {
        ...devices['Desktop Firefox'],
        viewport: { width: 1280, height: 720 },
      },
    },
    {
      name: 'webkit',
      use: {
        ...devices['Desktop Safari'],
        viewport: { width: 1280, height: 720 },
      },
    },
  ],
  /* Folder for test artifacts such as screenshots, videos, traces, etc. */
  // outputDir: 'test-results/',
};

export default config;
```

**Test file (self-contained)**

N/A

**Steps**
```js
test.beforeEach(async ({step, report, nfrFramework}) => {...
await test.step(`Content 1`, async () => {...
await test.step(`Content 2`, async () => {...
await test.step(`Content 3`, async () => {...
```

**Expected**

I'm expecting to have a report with only the content of test.step displayed. Here, as you can see, the report mentions more than the steps and it is unreadable.

<img width="168" alt="Screenshot 2023-11-02 at 13 28 21" src="https://github.com/microsoft/playwright/assets/37103602/7856ebf4-0826-4447-bf96-27236a3813b0">

**Actual**

See above

**Comment by pavelfeldman** [comment] 2023-11-02 15:41
I cannot reproduce your issue. Can you share the exact test that I can run to repro?

**Comment by pavelfeldman** [comment] 2023-11-03 20:58
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Closed by pavelfeldman** 2023-11-03 20:58 UTC
Labels: triaging
