### ISSUE TITLE
[BUG] Reporter does not display value of suite.title

### ISSUE THREAD

**Issue by PfrLisBerndt** [microsoft/playwright#8307] opened 2021-08-19 09:16 UTC
**Context:**
- Playwright Version: 1.14
- Operating System: Windows,
- Node.js version: 14.17.4
- Browser: All

```javascript
class MyReporter {
  onBegin(config, suite) {
      
      console.log(`Starting --${suite.title}-- with ${suite.allTests().length} tests`);
    }
...
}
```

```javascript
test.describe("testsuite-name", () => {...}
```

![image](https://user-images.githubusercontent.com/43057926/130041768-8f20e2a6-fe39-4603-9114-1cd2d5d602d8.png)

As you see I followed the instructions on [https://playwright.dev/docs/api/class-suite#suite-title](url) for group-suites, but the given title is not displayed.

**Comment by JoelEinbinder** [comment] 2021-08-19 16:33
The Suite here is the root Suite and its title is always blank.

**Comment by PfrLisBerndt** [comment] 2021-08-19 16:50
And how do I create a non-root-suite / child-suite? That´s not really clear in the docs...

**Comment by JoelEinbinder** [comment] 2021-08-19 16:52
One will be created for each file/describe.

**Comment by PfrLisBerndt** [comment] 2021-08-19 17:11
Debugging gives this:
![image](https://user-images.githubusercontent.com/43057926/130113124-21aaba1d-d3eb-45e8-b99d-9426f795233d.png)

**Comment by JoelEinbinder** [comment] 2021-08-20 02:05
> Debugging gives this:
> ![image](https://user-images.githubusercontent.com/43057926/130113124-21aaba1d-d3eb-45e8-b99d-9426f795233d.png)
> 
> Edit: Ok, I finally found the describe-suite and its title in the debugger. But it´s really nested deeply in the root-suite object. How am I supposed to adress this in the code? (I´m rather unfamiliar with JavaScript)

It's unclear what you are trying to do here. You have the suite object, it contains the child suites which contain the titles. It doesn't seem like there is a problem. Regardless the api here is working as intended so I'll close this issue.

**Closed by JoelEinbinder** 2021-08-20 02:05 UTC
