### ISSUE TITLE
[Feature]: recommended locators should pierce <slot>s.

### ISSUE THREAD

**Issue by jyasskin** [microsoft/playwright#29470] opened 2024-02-13 04:45 UTC
### 🚀 Feature Request

Right now, the primary locators like `getByRole()` [look through shadow roots](https://playwright.dev/docs/locators#locate-in-shadow-dom), but they don't traverse through `<slot>`s to the light-dom elements that were slotted into them. In order to ["prioritiz[e] user-facing attributes"](https://playwright.dev/docs/locators#locating-elements), these locators should continue through a `<slot>`.

### Example

I wrote an example in https://github.com/jyasskin/playwright-slot-piercing-test/blob/main/tests/slot-behavior.spec.ts that's based on a test I'd like to write for https://github.com/GoogleChrome/chromium-dashboard/pull/3654.

### Motivation

As discussed in https://playwright.dev/docs/locators#locate-by-role, tests are most resilient when they "reflect[] how users and assistive technology perceive the page". Pages are shown to users based on the [flat tree](https://drafts.csswg.org/css-scoping-1/#flat-tree), and if I write a test using Playwright's recommended locators, I'd like that test not to break if I refactor some bits of the UI into or out of shadow DOM. Unless I can use locators that follow the flat tree, my tests will break upon such a refactoring, and I'll have to use more-fragile DOM-based locators instead.

The argument against making CSS selectors pierce slots in https://github.com/microsoft/playwright/issues/29357#issuecomment-1927524607 is reasonable, since CSS selectors in the page don't pierce slots. (Although this is an equally good argument against the current behavior of piercing shadow roots...)  But the [user-facing locators](https://playwright.dev/docs/locators#locating-elements) don't have any such consistency constraints with another programming language, and they should reflect what users actually see.

**Comment by pavelfeldman** [comment] 2024-02-13 19:37
Looks like you should go one level up - `page.getByRole('group')` is still within the shadow. Playwright does not query on a flattened tree - it is a complicated concept that is hard to explain and follow. We prefer to keep the things simple:

- Find component that has text 'first' (in your case that is a div that has shadow shadow)
- In that component locate a link (which will be present in the light dom)

Does this make sense?

**Comment by jyasskin** [comment] 2024-02-14 19:12
I'm not sure exactly how to interpret your suggestion. If I stick to the recommended locators -- that is, not a CSS "div" selector -- it sounds like you're suggesting `getByText("first").getByRole("link")`. But the getByText("first") picks the `<summary>` element inside the shadow root, so that can't be what you meant.

But the alternative seems to be that you're recommending not using the recommended locators when shadow dom is involved, because they get stuck inside the shadow dom and can't get back out through slotted elements. That would imply that there's a documentation bug: that the docs should recommend against the locators in https://playwright.dev/docs/locators#quick-guide?

**Comment by pavelfeldman** [comment] 2024-02-14 21:43
>  If I stick to the recommended locators -- that is, not a CSS "div" selector -- it sounds like you're suggesting getByText("first").getByRole("link")

Not really. Here is what my recommendation was:

> Find component that has text 'first' (in your case that is a div that has shadow shadow)

So the first node of the locator chain should point to the component, and the second node should point to the link that belongs to that component. I understand now that you are lacking means of locating your component w/o using the CSS selectors. I would be working around that exact problem using either aria label (which makes your component accessible as a nice side effect), or adding data-testid (those don't need to be unique, our clients are using those to encode the 'class' or 'type' of the component). In the worst case, you could still use CSS classes.

> That would imply that there's a documentation bug: that the docs should recommend against the locators in https://playwright.dev/docs/locators#quick-guide?

Could you be more specific about the bug, happy to adjust the docs if that helps.

**Comment by jyasskin** [comment] 2024-02-14 23:36
There are definitely [ways](https://github.com/GoogleChrome/chromium-dashboard/blob/f26e2ec82e05578e739e97eb7b1db9081ee988d7/packages/playwright/tests/chromedash-report-spec-mentors-page_pwtest.js#L23-L24) to make my test work, but I think if Playwright changed its behavior (or, for backward compatibility, added a new spelling or option for the slotting-aware behavior), it would help a lot of people write less fragile tests without increasing the HTML they send to users. Looking at the two alternatives you've suggested:

> I would be working around that exact problem using either aria label (which makes your component accessible as a nice side effect), 

I'm far from an expert in accessibility, but in the structure `<details><summary>Label</summary>Content</details>`, https://www.w3.org/TR/html-aam-1.0/#summary-element-accessible-name-computation chooses to give the `<summary>` an accessible name, and leave the `<details>` without one. I assume they did that on purpose, and that it implies that having an accessible name on the outer element is worse for accessibility. Adding an `aria-label` to the element that wraps the `<details>` element (an [`<sl-details>`](https://shoelace.style/components/details) in my case), would have the same results for accessibility.

Of lesser importance, it would also force the light dom to include the same string in two attributes.  That's exactly the sort of thing one would want to use shadow dom to avoid, but a refactoring to generate the `aria-label` into shadow-dom would then break this test.

> or adding data-testid (those don't need to be unique, our clients are using those to encode the 'class' or 'type' of the component).

Test IDs are close, but they increase the size of the end-user HTML and are ["not user facing"](https://playwright.dev/docs/locators#locate-by-test-id). It'd be a tradeoff between the size increase and the increased fragility of using a CSS locator.

I don't really expect to get a new feature based on just me asking for it, but it'd be nice to keep an ear out for other developers who'd benefit from this sort of change.

**Comment by pavelfeldman** [comment] 2024-02-15 21:31
> There are definitely [ways](https://github.com/GoogleChrome/chromium-dashboard/blob/f26e2ec82e05578e739e97eb7b1db9081ee988d7/packages/playwright/tests/chromedash-report-spec-mentors-page_pwtest.js#L23-L24) to make my test work

```js
const expertLink = page.locator(
    'sl-details', { hasText: 'expert@example.com has mentored' }
).getByRole('link');
```

To me this looks perfect. Without additional attributes or aria labels, you are telling Playwright to locate your component and then find a link in it. It keeps things in the light dom and allows for the easiest explanation.

> I think if Playwright changed its behavior (or, for backward compatibility, added a new spelling or option for the slotting-aware behavior)

Could you elaborate on what has changed in behavior? Are you referring to some sort of regression?

**Comment by yury-s** [comment] 2024-02-21 00:47
Closing per the response above, feel free to open a new issue if it doesn't work.

**Closed by yury-s** 2024-02-21 00:47 UTC

**Comment by astearns** [comment] 2024-03-13 00:12
@jyasskin you might want to add a comment to https://github.com/microsoft/playwright/issues/29357 which is still open and tracking slot-piercing requests
