### ISSUE TITLE
[Feature]: Throw Turborepo and GH Action errors

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [microsoft/playwright#29006] opened 2024-01-16 15:53 UTC
As able to see here:
https://github.com/The-Creative-Programming-Group/Weather-App/actions/runs/7532866046/job/20504296786

If you run the playwright tests via Turborepo and GH Actions, the GH Action will not error if the tests fail.

I want to see that the GH Actions are failing if my tests are failing.

**Comment by mxschmitt** [comment] 2024-01-16 17:30
We are unfortunately not familiar with Turborepo. Since this does not reproduce without Turborepo, this is most likely an issue on their side or / how you are using Turborepo.

Closing as per above, since we can't act on that. I recommend filing an issue on their side.

**Closed by mxschmitt** 2024-01-16 17:30 UTC

**Comment by FleetAdmiralJakob** [comment] 2024-01-16 19:11
Ok, I created an error on Turborepo: https://github.com/vercel/turbo/issues/7014
