### ISSUE TITLE
Workflow for launching Playwright tests from a development machine

### ISSUE THREAD

**Issue by jasonkuhrt** [microsoft/playwright#11866] opened 2022-02-04 14:46 UTC
I've recently switched to a remote development machine to develop on our full stack application (I lead work on the [Prisma Data Platform](https://www.prisma.io/docs/concepts/components/prisma-data-platform)) for performance reasons. I use VSCode. VSCode makes things pretty seamless. For example port forwarding makes it feel like services running on my development machine are on my localhost.

We use playwright for our end to end tests. What I haven't figured out yet is how to run our e2e tests on my development machine. What I think my ideal is, is this:

- launch tests
- playwright library in my tests is running on my development machine (of course)
- playwright launches/scripts browsers on my development machine as if it were running on my development machine. If I use PW debug mode, then those debuggers open on my local machine too.

I would also accept (maybe even prefer) that Playwright experience can be totally used through VSCode: 

- tabs for browser windows
- tabs for debug windows

My current status is this PW error:

<img width="595" alt="CleanShot 2022-02-04 at 09 44 26@2x" src="https://user-images.githubusercontent.com/284476/152548468-1ef3ac64-1f90-4216-a393-6b93255037c7.png">

Which when I try leads to:

```
sudo: npx: command not found
```

So I drop `sudo` which leads to:
```
Installing Ubuntu dependencies...
Switching to root user to install dependencies...
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease                                                                                                                                                  
Hit:3 http://deb.debian.org/debian buster-updates InRelease                                                                                                                                          
Hit:4 https://download.docker.com/linux/debian buster InRelease                                                                                                                                      
Get:5 https://last-public-ovh-metrics.snap.mirrors.ovh.net/debian buster InRelease [4,911 B]                                                                
Get:6 https://last-public-ovh-rtm.snap.mirrors.ovh.net/debian buster InRelease [4,914 B]
Fetched 9,825 B in 1s (7,667 B/s)                                      
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libfontconfig1' instead of 'libfontconfig'
Package ttf-ubuntu-font-family is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libjpeg-turbo8 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ttf-ubuntu-font-family' has no installation candidate
E: Unable to locate package libicu66
E: Package 'libjpeg-turbo8' has no installation candidate
E: Unable to locate package libvpx6
```

(My machine is debian)

I've love to hear more about what is possible/planned by PW in this remote development workflow space. Thanks!

**Comment by yury-s** [comment] 2022-02-04 17:17
> (My machine is debian)

Only Ubunty is [officially supported](https://playwright.dev/docs/library#linux), the built-in command for installing deps works on Ubuntu only. With that said you may be able to figure out yourself what debian packages are needed for the browsers to launch (this are all browser dependency libraries). For reference here is [the list](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/utils/nativeDeps.ts) of the deps we install on Ubuntu.

> playwright launches/scripts browsers on my development machine as if it were running on my development machine. If I use PW debug mode, then those debuggers open on my local machine too.

I guess you meant that they open on the remote machine? (unless you have remote X session). In any case this doesn't seem to be root cause of the problem. As for the VSCode integration, the features sound interesting, we considered embedding trace viewer etc into vs code but so far not convinced this would be the best experience. Feel free to file separate feature request for the VSCode integrations you mentioned, we'll need to collect more feedback from the community.

Closing this bug as it is about not officially supported platform (Debian).

**Closed by yury-s** 2022-02-04 17:17 UTC

**Comment by jasonkuhrt** [comment] 2022-02-04 17:36
@yury-s noted about Debian not being supported.

That said, even if it was ubuntu, how is PW going to know to open browser and debug windows on my local machine rather than the one I'm ssh'd into developing? 

I think that's the main issue I'm facing probably, just need to work through the more superficial issue of Debian installation of deps.

**Comment by yury-s** [comment] 2022-02-04 17:40
> That said, even if it was ubuntu, how is PW going to know to open browser and debug windows on my local machine rather than the one I'm ssh'd into developing?

With today's implementation it would open them on the remote machine, you could connect with a remote X client and see those windows on your local machine. There is also a bunch of [connect](https://playwright.dev/docs/api/class-browsertype#browser-type-connect) methods that can be used to launch browsers remotely but that's probably not what you need.

**Comment by jasonkuhrt** [comment] 2022-02-04 21:58
Not sure what "remote X client" is?

**Comment by yury-s** [comment] 2022-02-04 23:02
Something [like this ](https://www.simplified.guide/ssh/run-gui-application).
