### ISSUE TITLE
[Question] Why memory can't free ?

### ISSUE THREAD

**Issue by GitCHQL** [microsoft/playwright#11037] opened 2021-12-21 07:51 UTC
Context:

1. Playwright Version: [Version 1.17.1]
2. Operating System: [Windows]
3. Node.js version: [v14.15.3]

```javascript
const { chromium } = require('playwright');
const express = require('express');
const app = express();
app.listen()
const remoteCDP = 'http://127.0.0.1:9222';
(async()=> {
    const cdp_browser = await chromium.connectOverCDP(remoteCDP)

    let cdp_context1 = await cdp_browser.newContext({
        storageState: './temp/state.json'
    })

    let page = await cdp_context1.newPage();
    for (let i = 0; i< 100 ; i++) {
        await page.goto('http://www.baidu.com/');
        console.log(cdp_context1._pages.size, i)
        //console.log(page);
    }
    setTimeout(async() => {
        console.log('clear');
        await cdp_context1.close();
        // global.gc();  i tried this but it not work
    }, 15*1000) // can't free memory memory used 98M

})();
```

```javascript
const { chromium } = require('playwright');
const express = require('express');
const app = express();
app.listen()
const remoteCDP = 'http://127.0.0.1:9222';
(async()=> {
    const cdp_browser = await chromium.connectOverCDP(remoteCDP)

    let cdp_context1 = await cdp_browser.newContext({
        storageState: './temp/state.json'
    })

    let page = await cdp_context1.newPage();
    for (let i = 0; i< 100 ; i++) {
        await page.goto('http://www.baidu.com/');
        console.log(cdp_context1._pages.size, i)
        //console.log(page);
    }
    setTimeout(async() => {
        console.log('clear');
        await cdp_context1.close();
    }, 1*1000) // just modify time ,I can free memory to 50M

})();
```

>I want to know why I can't free memory

**Comment by yury-s** [comment] 2021-12-21 18:22
V8 doesn't guarantee the memory to be released immediately. Once you close a context all resources associated with it will be eventually garbage collected. If you have an evidence that it doesn't happen please provide a repro.

**Comment by yury-s** [comment] 2021-12-22 18:16
Ok, this is specific to remote connection. The memory goes down after closing the contexts by about half but not to the original level. Once the browser connections are closed it drops to the original level.

**Comment by yury-s** [comment] 2021-12-22 18:27
It only happens when there are 2 remote connections, if there is only one everything works fine:
```js
const { chromium } = require('playwright');
const remoteCDP = 'http://127.0.0.1:8192';
(async () => {
    const browser = await chromium.connectOverCDP(remoteCDP)
    const browser2 = await chromium.connectOverCDP(remoteCDP)
    const context = await browser.newContext()
    const context2 = await browser2.newContext()    
    const page = await context.newPage();
    const page2 = await context2.newPage();
    for (let i = 0; i < 10; i++) {
        await page.goto('http://www.google.com/');
        await page2.goto('http://www.google.com/');
        console.log(`${i}) Heap size: ${heapSize()}`);
    }
    console.log('clear');
    await context.close();
    await context2.close();
    runGc();
    console.log(`Heap size after closing contexts: ${heapSize()}`);
    await browser.close();
    await browser2.close();
    runGc();
    console.log(`Heap size after closing connection: ${heapSize()}`);
})();

function runGc() {
    for (let i = 0; i < 10; i++)
      global.gc();
}

function heapSize() {
    const used = process.memoryUsage().heapUsed >> 20;
    return `${used} MB`;
}
```

**Comment by yury-s** [comment] 2022-01-04 02:49
The problem is that when a new page is created via one connection we auto attach to it in the other connection too. This happens because the second connection receives `Target.attachedToTarget` event for an unknown context which is expected to always be default (persistent) context but this invariant is not true when there are contexts created through different connections. This is a bug.

**Comment by pavelfeldman** [comment] 2023-06-30 17:28
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2023-06-30 17:28 UTC
Labels: P3-collecting-feedback
