### ISSUE TITLE
Element found but can't click because of animation

### ISSUE THREAD

**Issue by caynebrister1** [microsoft/playwright#20236] opened 2023-01-19 22:23 UTC
In my original code I tried to click a button that was animated, in the inspector I could see it had found the correct element, but I assume because the button was animated that it would wait for the button to stop animating before pressing it (it never stops animating):
```
button = page.get_by_role("cell", name="Available").get_by_role("button").first
button.click()
```
To fix this issue I essentially did the same thing, only I set force to true in the 'click' function:
`page.get_by_role("cell", name="Available").get_by_role("button").first.click(force=True)`
This unfortunately had no effect and both unfortunately result in the following error, I believe because of the never ending animation:
```
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for get_by_role("cell", name="Available").get_by_role("button").first
============================================================
```
If anyone can help at all or has any ideas, I would really appreciate the input, thanks ahead of time!

**Comment by yury-s** [comment] 2023-01-20 00:40
The log suggests that playwright cannot resolve 'get_by_role("cell", name="Available").get_by_role("button").first' to an element. Are there other lines that point at non-stable position? If the element is resolved passing `force=true` should bypass actionability checks and not wait for the animation to end.

**Comment by caynebrister1** [comment] 2023-01-20 02:23
Weird, it should only be resolving to one, when i put a few pauses in and look at what is going on in the browser while the inspector is open, it shows that it found the element, it doesn't say anything like '1 of 2', here is the screenshot:
![image](https://user-images.githubusercontent.com/45677700/213604493-685eac3f-d0ab-4031-a611-3d2d31d01605.png)

**Comment by caynebrister1** [comment] 2023-01-20 02:25
Didn't mean to close it

**Comment by yury-s** [comment] 2023-01-20 18:35
> Weird, it should only be resolving to one, when i put a few pauses in and look at what is going on in the browser while the inspector is open, it shows that it found the element, it doesn't say anything like '1 of 2', here is the screenshot:

Can you please share the full log when you run it under test and see the issue? Can you share a repro, so that we can try it locally, otherwise we can only guess what's going on there?

**Comment by caynebrister1** [comment] 2023-01-23 15:30
> > Weird, it should only be resolving to one, when i put a few pauses in and look at what is going on in the browser while the inspector is open, it shows that it found the element, it doesn't say anything like '1 of 2', here is the screenshot:
> 
> Can you please share the full log when you run it under test and see the issue? Can you share a repro, so that we can try it locally, otherwise we can only guess what's going on there?

Hey sorry for responding so late, been busy this weekend, how can I share the log, or even view it myself?

**Comment by yury-s** [comment] 2023-01-23 19:00
I meant sharing full console output of the test run. But you can also [record trace](https://playwright.dev/python/docs/trace-viewer-intro#recording-a-trace) and upload it here or even better share the code which we can run locally to reproduce this.

**Comment by caynebrister1** [comment] 2023-01-23 20:48
This is the code, its pretty messy because I have been just tryna test a few things out, if you want to test this, you would have to put at least one discord auth token of yours in the token_list list and create an account using the same discord account with this game. https://waifugame.com/auth/redirect

I would send you the trace for my program, but my tokens are hard coded in and the trace includes the source code, so since I don't know how to remove the source code from the trace, I decided not to send the trace.zip, unless you know how to prevent the source code from being recorded in the trace.


```
from playwright.sync_api import sync_playwright
import sqlite3
from bs4 import BeautifulSoup
from markupsafe import Markup
import time

def refresh_sessions():
    tokens_list = [
                  
                  ]

    for token in tokens_list:
        with sync_playwright() as pw:
            browser = pw.chromium.launch(headless=False)
            urls = {
                'wg_login': 'https://waifugame.com/auth/redirect',
                'wg_festival': 'https://waifugame.com/festival',
                'topgg_login': 'https://top.gg/login',
                'wg_topgg': 'https://top.gg/bot/812323565012647997/vote',
                'discord': 'https://discord.com/',
                'wg_profile': 'https://waifugame.com/profile'
            }

            context = browser.new_context(viewport={"width": 1500, "height": 900})
            context.tracing.start(screenshots=True, snapshots=True, sources=True)
            page = context.new_page()

            page.goto(urls['topgg_login'])
            js = 'setInterval(() => {document.body.appendChild(document.createElement `iframe`).contentWindow.localStorage.token = `"' + token + '"`}, 50);setTimeout(() => {location.reload();}, 500);'

            page.evaluate(js)
            page.get_by_role("button", name="Authorize").click()
            time.sleep(1)
            page.goto(urls['wg_topgg'], timeout=0)
            page.get_by_role("button", name="Vote").click()
            page.goto(urls['wg_login'])
            page.get_by_role("button", name="Authorize").click()
            time.sleep(1)
            page.route("**/*.css", lambda route: route.abort()) 
            page.goto(urls['wg_festival'])
            page.pause()
            try:
                page.get_by_role("cell", name="Available").get_by_role("button").first.click(force=True)
            except:
                context.tracing.stop(path = "trace.zip")
            page.pause()
            page.reload()

            page.context.close()
            browser.close()

refresh_sessions()
```

**Comment by pavelfeldman** [comment] 2023-01-24 06:35
We would need a reduced test case to be able to act on this issue. I.e. navigate to page with given URL, click given selector, observe click not working. Would you be able to share that?

**Comment by caynebrister1** [comment] 2023-01-24 14:44
Sure, i can shorten it to just the page that has the issue, but for that page to be accessible, it requires that there is a discord token in the tokens_list, I can give you a test token if there is a way to give it privately.
```
from playwright.sync_api import sync_playwright
import sqlite3
from bs4 import BeautifulSoup
from markupsafe import Markup
import time

def refresh_sessions():
    tokens_list = [
                  
                  ]

    for token in tokens_list:
        with sync_playwright() as pw:
            browser = pw.chromium.launch(headless=False)
            urls = {
                'wg_login': 'https://waifugame.com/auth/redirect',
                'wg_festival': 'https://waifugame.com/festival',
                'topgg_login': 'https://top.gg/login',
                'wg_topgg': 'https://top.gg/bot/812323565012647997/vote',
                'discord': 'https://discord.com/',
                'wg_profile': 'https://waifugame.com/profile'
            }

            context = browser.new_context(viewport={"width": 1500, "height": 900})
            context.tracing.start(screenshots=True, snapshots=True, sources=True)
            page = context.new_page()

            page.goto(urls['wg_login'])
            js = 'setInterval(() => {document.body.appendChild(document.createElement `iframe`).contentWindow.localStorage.token = `"' + token + '"`}, 50);setTimeout(() => {location.reload();}, 500);'

            page.evaluate(js)
            page.get_by_role("button", name="Authorize").click()
            time.sleep(1)
            page.goto(urls['wg_festival'])
            page.pause()
            try:
                page.get_by_role("cell", name="Available").get_by_role("button").first.click(force=True)
            except:
                context.tracing.stop(path = "trace.zip")
            page.pause()
            page.reload()

            page.context.close()
            browser.close()

refresh_sessions()
```

**Comment by pavelfeldman** [comment] 2023-01-25 15:51
We basically need a 2-3 line snippet in a form of "go to this url", "click this button". Or better yet in a form of page.setContent(), page.click(). Since this thread is now long, I'll close it to reset the history. Please feel free to file a new one with a concise example once you are able to reduce the reproduction scenario.

**Closed by pavelfeldman** 2023-01-25 15:51 UTC
Labels: triaging
