### ISSUE TITLE
[BUG] addInitScript is called too early before the Secure Context APIs are available

### ISSUE THREAD

**Issue by skyuplam** [microsoft/playwright#20550] opened 2023-02-01 08:38 UTC
**Context:**
- Playwright Version: 1.30.0
- Operating System: mcr.microsoft.com/playwright:v1.30.0-focal
- Node.js version: v16.19.0
- Browser: Chromium
- Extra: [any specific details about your environment]

Error [TypeError]: Object.defineProperties called on non-object
    at Function.defineProperties (<anonymous>)

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();

  await page.addInitScript({ content: 'Object.defineProperties(navigator.mediaDevices, {foo: {value: "bar"}});' })

  await page.goto('https://playwright.dev');
})();
```

**Describe the bug**

The script is called too early before the API is available (Secure Context APIs) and thus a `TypeError` is thrown. It seems that it only happens to Chromium browser.

`Object.defineProperties called on non-object`

**Comment by dgozman** [comment] 2023-02-02 18:47
@skyuplam I cannot reproduce this on v1.30.0, neither inside docker, nor on macOS. This is the test I run:

```js
test("addInitScript", async ({ page }) => {
  await page.addInitScript({ content: 'Object.defineProperties(navigator.mediaDevices, {foo: {value: "bar"}});' })
  await page.goto('https://playwright.dev');
  expect(await page.evaluate('navigator.mediaDevices.foo')).toBe('bar');
});
```

**Comment by dgozman** [comment] 2023-02-06 17:40
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue with it, and link to this one.

**Closed by dgozman** 2023-02-06 17:40 UTC
Labels: triaging
