### ISSUE TITLE
[BUG] incorrect focus behavior for webcomponents with delegate focus option

### ISSUE THREAD

**Issue by Oloompa** [microsoft/playwright#2510] opened 2020-06-09 10:55 UTC
**Context:**
- Playwright Version: 1.0.2
- Operating System: Linux
- Node version: 12.18.0
- Browser: Chromium

**Code Snippet**

```javascript
const { chromium } = require('playwright');

(async () => {
    const browser = await chromium.launch();
    const page = await browser.newPage();
    await page.goto('https://cdpn.io/kezako/debug/BajoMpp/dGkXWKBXRaKA');
    await page.focus("custom-element");
    await page.screenshot({ path: `example.png` });
    await browser.close();
})();

```

**Describe the bug**

We can use [delegatesFocus](https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow) to delegate focus on webcomponents.

If i manualy call `document.querySelector("custom-element").focus()` in console, the second span in shadowroot (with "tabindex=0") takes the focus. That's the correct behavior.

```javascript
setTimeout(() => { document.querySelector("custom-element").focus(); }, 2000);
```

But if i call `page.focus("custom-element")` with playwright, the first span in shadowroot (with "tabindex=-1") take the focus.

The webcomponent code is on [codepen](https://codepen.io/kezako/pen/BajoMpp)

**Comment by Oloompa** [comment] 2020-06-09 13:21
you need to update the url (debug view of codepen) to launch the test

**Comment by pavelfeldman** [comment] 2020-06-28 19:27
I don't observe that, [1] is getting focused for me when I run `document.querySelector("custom-element").focus();`. The discrepancy also does not make sense to me because `page.focus` actually calls DOM Element's focus in the end.

**Comment by dgozman** [comment] 2020-06-28 20:50
When I manually execute the following in Chrome 83 DevTools console, I get `<span contenteditable="true" tabindex="-1">1</span>`. This suggests that `delegatesFocus` is not focusing the second span. Am I doing something wrong?

```js
setTimeout(() => {
  document.querySelector("custom-element").focus();
  console.log(document.querySelector("custom-element").shadowRoot.activeElement);
}, 2000);
```

**Comment by dgozman** [comment] 2020-07-02 05:30
Closing this as we are unable to reproduce.

**Closed by dgozman** 2020-07-02 05:30 UTC
