### ISSUE TITLE
[Bug]: viewport size does not apply in  defineConfig.use.viewport

### ISSUE THREAD

**Issue by mr-anton-t** [microsoft/playwright#32413] opened 2024-09-02 15:33 UTC
### Version

1.46.1

### Steps to reproduce

Clone my repo  https://github.com/mr-anton-t/pw-test/tree/main  branch main
run test as ` npx playwright test`

### Expected behavior

viewport size should work as 

```js
// playwright.config.ts
import { defineConfig } from '@playwright/test';

export default defineConfig({
  use: {
    viewport: { width: 100, height: 100 },
  },
});
```

### Actual behavior

viewport size does not apply in defineConfig.use.viewport 

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (14) arm64 Apple M3 Max
    Memory: 57.11 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
```

**Comment by mxschmitt** [comment] 2024-09-03 07:04
The problem is that the "global use" is not able to override the "project use" since a device already contains a viewport. To fix this, you'd need to move it from the "global use" over to the "project use" like this:

```diff
diff --git a/playwright.config.ts b/playwright.config.ts
index 34778cf..36c323b 100644
--- a/playwright.config.ts
+++ b/playwright.config.ts
@@ -29,7 +29,6 @@ export default defineConfig({
 
 
     // check viewport in https://playwright.dev/docs/test-use-options#emulation-options
-    viewport: { width: 1400, height: 1300 },
 
     /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
     trace: 'on-first-retry',
@@ -39,7 +38,10 @@ export default defineConfig({
   projects: [
     {
       name: 'chromium',
-      use: { ...devices['Desktop Chrome'] },
+      use: {
+        ...devices['Desktop Chrome'],
+        viewport: { width: 1400, height: 1300 },
+       },
     },
```

**Comment by mr-anton-t** [comment] 2024-09-03 10:19
The documentation says that I can use it like this

https://github.com/microsoft/playwright/blob/221b77309c249bc7923ae58fcf285143abd87c7b/packages/playwright/types/test.d.ts#L5567

```   * **Usage**
   *
   * ```js
   * // playwright.config.ts
   * import { defineConfig } from '@playwright/test';
   *
   * export default defineConfig({
   *   use: {
   *     viewport: { width: 100, height: 100 },
   *   },
   * });
   * ```
```

According to the documentation, I updated it like this

https://github.com/mr-anton-t/pw-test/commit/ff6c724e6ffdde83cd88db9ffb128b5ca1d8d01c


and the issue is reproduced

**Comment by mr-anton-t** [comment] 2024-09-03 10:29
my test shows that this article does not work correctly:

https://playwright.dev/docs/test-use-options#explicit-context-creation-and-option-inheritance

**Comment by pavelfeldman** [comment] 2024-09-03 17:05
Closing as per https://github.com/microsoft/playwright/issues/32413#issuecomment-2325754019 that has a valid explanation. Your config has more lines than this example, and in these other lines you are overriding the viewport yourself. Please revisit the comment with the explanation.

**Closed by pavelfeldman** 2024-09-03 17:05 UTC
