### ISSUE TITLE
[BUG] No executable path is specified. Pass "executablePath" option directly" after update to Monterey 12.0.1

### ISSUE THREAD

**Issue by luad1234** [microsoft/playwright#10594] opened 2021-11-29 22:02 UTC
**Context:**
- Playwright Version: 1.9.1
- Operating System: Mac
- Browser: Chrome

**Describe the bug**

I'm currently scraping tiktok using this unofficial tiktok api which uses playwright https://github.com/davidteather/TikTok-Api. Today i updated my Mac to  Monterey and the script im running to scrape tiktok stopped working and throws out the error below. I've tried to reinstall all the packages and also reinstall playwright but cant get the script running again. 

Result

`Traceback (most recent call last):
  File "/Users/johndoe/Documents/tiktok/emails.py", line 16, in <module>
    api = TikTokApi.get_instance(custom_verifyFp=verifyFp, use_test_endpoints=True)
  File "/Users/johndoe/Documents/tiktok/.venv/lib/python3.9/site-packages/TikTokApi/tiktok.py", line 151, in get_instance
    TikTokApi(**kwargs)
  File "/Users/johndoe/Documents/tiktok/.venv/lib/python3.9/site-packages/TikTokApi/tiktok.py", line 63, in __init__
    self.browser = browser(**kwargs)
  File "/Users/johndoe/Documents/tiktok/.venv/lib/python3.9/site-packages/TikTokApi/browser_utilities/browser.py", line 84, in __init__
    raise e
  File "/Users/johndoe/Documents/tiktok/.venv/lib/python3.9/site-packages/TikTokApi/browser_utilities/browser.py", line 79, in __init__
    self.browser = get_playwright().webkit.launch(
  File "/Users/johndoe/Documents/tiktok/.venv/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 8915, in launch
    self._sync(
  File "/Users/johndoe/Documents/tiktok/.venv/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 103, in _sync
    return task.result()
  File "/Users/johndoe/Documents/tiktok/.venv/lib/python3.9/site-packages/playwright/_impl/_browser_type.py", line 74, in launch
    raise e
  File "/Users/johndoe/Documents/tiktok/.venv/lib/python3.9/site-packages/playwright/_impl/_browser_type.py", line 70, in launch
    return from_channel(await self._channel.send("launch", params))
  File "/Users/johndoe/Documents/tiktok/.venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/Users/johndoe/Documents/tiktok/.venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 47, in inner_send
    result = await callback.future
playwright._impl._api_types.Error: No executable path is specified. Pass "executablePath" option directly.`

**Comment by pavelfeldman** [comment] 2021-11-29 23:28
Your playwright is way too old. Try playwright@1.16.3 or playwright@1.17.0-rc1

**Comment by Yurii397** [comment] 2021-11-30 13:03
Yesterday updated my macOS to the new one - Monterey Version 12.0.1
and mentioned issue above with executablePath started to appear.

My current Playwright version - 1.16.1
I've tried to upgrade it to '1.18.0-next-alpha-nov-16-2021' but it doesn't help. I'm using Node js. reinstalling all node js modules doesn't help.

Would be thankful for any updates or suggestions!

**Comment by Yurii397** [comment] 2021-12-02 10:36
@mxschmitt  hey, 

Any ideas on how it can be fixed now? 

Thanks

**Comment by Yurii397** [comment] 2021-12-02 12:10
@mxschmitt @pavelfeldman, 

I put 'executablePath' into  lunch options 
![image](https://user-images.githubusercontent.com/46851143/144419366-4a333e96-eacf-41bb-bd1d-c6d93c435ad3.png)
but it looks crashes somewhere before/while initialization

**Comment by pavelfeldman** [comment] 2021-12-02 23:01
@Yurii397: It looks like original poster had a different problem than you. Could you file a new bug with the steps to reproduce your problem?

@luad1234: it looks like you are specifying invalid package version to pypi.

**Comment by Yurii397** [comment] 2021-12-03 08:35
> 'executablePath' into lunch options

sure, I thought the root problem is the same, decided to not create duplication. 

The new created one - https://github.com/microsoft/playwright/issues/10693

@pavelfeldman have a look plz

**Comment by dgozman** [comment] 2021-12-08 00:16
@luad1234 Use version 1.17.2 for playwright. You can always see the latest version at https://pypi.org/project/playwright/.

**Closed by dgozman** 2021-12-08 00:16 UTC
Labels: triaging
