### ISSUE TITLE
[BUG] Module '"@playwright/test"' has no exported member *

### ISSUE THREAD

**Issue by igorb-s** [microsoft/playwright#21058] opened 2023-02-21 14:02 UTC
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: [e.g. Windows, Linux or Mac]
- Node.js version: [e.g. 12.22, 14.6]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```sh
 next git:(SPD-522-smoke-e2e-test) pnpm dlx create-playwright
.../Library/pnpm/store/v3/tmp/dlx-62940  | Progress: resolved 1, reused 0, downloaded 0,.../Library/pnpm/store/v3/tmp/dlx-62940  |   +1 +
.../Library/pnpm/store/v3/tmp/dlx-62940  | Progress: resolved 1, reused 0, downloaded 0,.../Library/pnpm/store/v3/tmp/dlx-62940  | Progress: resolved 1, reused 1, downloaded 0, added 1, done
Getting started with writing end-to-end tests with Playwright:
Initializing project in '.'
✔ Where to put your end-to-end tests? · tests
✔ Add a GitHub Actions workflow? (y/N) · false
✔ Install Playwright browsers (can be done manually via 'pnpm exec playwright install')? (Y/n) · true

Installing Playwright Test (pnpm add --save-dev @playwright/test)…
../..                                    | Progress: resolved 0, reused 1, downloaded 0,../..                                    | Progress: resolved 45, reused 44, downloaded ../..                                    | Progress: resolved 119, reused 100, downloade../..                                    | Progress: resolved 262, reused 245, downloade../..                                    | Progress: resolved 447, reused 435, downloade../..                                    | Progress: resolved 624, reused 612, downloade../..                                    | Progress: resolved 827, reused 815, downloade../..                                    | Progress: resolved 832, reused 820, downloaded 0, added 0, done

devDependencies:
+ @playwright/test ^1.30.0

Done in 1.9s
Downloading browsers (pnpm exec playwright install)…
Writing playwright.config.ts.
Writing tests/example.spec.ts.
Writing tests-examples/demo-todo-app.spec.ts.
Writing package.json.
✔ Success! Created a Playwright Test project at /Users/_/code/web/apps/next

And check out the following files:
  - ./tests/example.spec.ts - Example end-to-end test
  - ./tests-examples/demo-todo-app.spec.ts - Demo Todo App end-to-end tests
  - ./playwright.config.ts - Playwright Test configuration

Visit https://playwright.dev/docs/intro for more information. ✨

Happy hacking! 🎭

```

```ts
Module '"@playwright/test"' has no exported member 'Page'. Did you mean to use 'import Page from "@playwright/test"' instead?ts(2614)
Module '"@playwright/test"' has no exported member 'devices'. Did you mean to use 'import devices from "@playwright/test"' instead?ts(2614)
```

<img width="903" alt="image" src="https://user-images.githubusercontent.com/109353027/220364225-c09ccb7d-8f99-4e03-af8e-8257eb6aee7e.png">
<img width="957" alt="image" src="https://user-images.githubusercontent.com/109353027/220364415-a62fae04-c9b6-460b-8c45-0554f86d22b5.png">

**Describe the bug**

After installing Playwright using `pnpm dlx create-playwright` in monorepo some types like `Page` or `devices` are not exported.

**Comment by yury-s** [comment] 2023-02-21 21:24
I cannot reproduce it with the following steps:
```bash
mkdir /tmp/ppp
cd /tmp/ppp
pnpm dlx create-playwright
code .
```
Can you share full project where it happens?

**Comment by yury-s** [comment] 2023-02-24 02:19
Do you have a clue why it didn't work without the exclude? It'd be nice to understand.

**Comment by igorb-s** [comment] 2023-02-24 09:26
> Do you have a clue why it didn't work without the exclude? It'd be nice to understand.

I have no idea. We use `pnpm` as a package manager in our monorepo and we have tsconfig in this particular `/app/next` 

```json
{
  "extends": "configs/nextjs.json",
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "types": ["cypress", "node"],
  "exclude": ["node_modules", "server.ts", "playwright.config.ts", "playwright"],
  "compilerOptions": {
    "isolatedModules": true
  }
}


{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Next.js",
  "extends": "./base.json",
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "incremental": true,
    "esModuleInterop": true,
    "module": "esnext",
    "resolveJsonModule": true,
    "isolatedModules": false,
    "jsx": "preserve",
    "preserveSymlinks": true
  },
  "include": ["src", "next-env.d.ts"],
  "exclude": ["node_modules"]
}


{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Default",
  "compilerOptions": {
    "composite": false,
    "declaration": false,
    "declarationMap": false,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "inlineSources": false,
    "isolatedModules": true,
    "moduleResolution": "node",
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "preserveWatchOutput": true,
    "skipLibCheck": true,
    "strict": true
  },
  "exclude": ["node_modules"]
}

```

File structure 

```
apps/next/playwright.config.ts
apps/next/package.json
// we don't have a lock file here since it's a monorepo and pnpm-lock.yaml is in root 
tests/
  example.spec.ts
apps/next/tsconfig.json
```

**Comment by yury-s** [comment] 2023-02-25 01:02
Yeah, not quite clear. We'll keep it in mind in case there are similar reports. I'm closing the issue as you have a workaround.

**Closed by yury-s** 2023-02-25 01:02 UTC
Labels: triaging

**Comment by spoorthykakarla28** [comment] 2023-08-08 17:54
I had the same issue with monorepo and it worked fine once I added the files in exclude as mentioned above. Any idea on why it it didn't work before would be helpful.

**Comment by MadaShindeInai** [comment] 2023-08-22 18:37
Same issue with pnpm on a way to monorepo migration

**Comment by sturoid** [comment] 2023-11-10 05:51
I'm getting the same thing using pnpm, playwright 1.26.1, and Node 18.18. If I install pnpm with npm the error stops.

<img width="848" alt="Screenshot 2023-11-09 at 10 50 52 PM" src="https://github.com/microsoft/playwright/assets/805554/10acb91e-ef96-4cbd-9307-6828b4ff872d">

**Comment by saranrapjs** [comment] 2024-06-27 15:22
I ran into this issue as well — it goes away if you're able to set `"preserveSymlinks": false`, or alternatively, if you import the `playwright` library directly (rather than indirectly via `@playwright/test`).

**Comment by parliament718** [comment] 2025-03-29 06:01
This happened to me because I had everything in a `playwright` directory at my root. `@playwright/test/index.d.ts` has the line `export * from 'playwright/test';` which was resolving to my local folder instead of node_modules/playwright.

I renamed my folder and it started working.
