### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by Bobbykumar706584** [microsoft/playwright#26674] opened 2023-08-24 04:25 UTC
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?
requirement a full setup from scratch using typescript with playwright and electron js application
and please update the document

**Comment by yury-s** [comment] 2023-08-24 15:43
Duplicate of https://github.com/microsoft/playwright/issues/26673

**Closed by yury-s** 2023-08-24 15:43 UTC
