### ISSUE TITLE
[BUG] mouse scroll is not awaited properly

### ISSUE THREAD

**Issue by YahangWu** [microsoft/playwright#10002] opened 2021-11-03 03:00 UTC
**Context:**
- Playwright Version: 1.15.2
- Operating System: Mac
- Node.js version: 12.16
- Browser: Chromium
- Extra: 

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
        await page.mouse.wheel(0, 1100);
        const bar = await page.$('text=hello');
        const barBound = await bar.boundingBox();
        console.log(barBound);
        await page.mouse.move(barBound.x, barBound.y);
        await page.mouse.down();
        await page.mouse.move(barBound.x + 100, barBound.y);
        await page.mouse.up();
        const newBarBound = await bar.boundingBox();
```

**Describe the bug**

The bar is located on the bottom of the page(need scrolling down to the page), so I added a mouse scroll to simulate the page scroll and then select the bar element, print out the bar box coordinate. Did some mouse click, the bar should still have the same Y value, but it doesn't.

**Comment by mxschmitt** [comment] 2021-11-04 10:52
Scroll is unfortunately not awaited currently, so it's working as intended. You could use e.g.

```js
    await page.mouse.wheel(0, 100)
    await page.waitForFunction(() => window.scrollY >= 100)
```

to wait until your page has scroll to the certain Y coordinate. Let us know if this works for you!

Also keep in mind, that using page.click etc. will automatically scroll to the element.

**Comment by mxschmitt** [comment] 2021-11-08 09:53
Closing since its answered.

**Closed by mxschmitt** 2021-11-08 09:53 UTC
Labels: triaging

**Comment by YahangWu** [comment] 2021-11-17 22:34
Thanks for the info @mxschmitt !

**Comment by akshaya-venkatesh8** [comment] 2023-03-10 18:25
@mxschmitt Is this still the case? Is scrolling still not awaited?
