### ISSUE TITLE
[Bug]: Fails to run in GitLab CI / mcr.microsoft.com/playwright:focal Docker image

### ISSUE THREAD

**Issue by Vinnl** [microsoft/playwright#7867] opened 2021-07-27 20:29 UTC
### Playwright version

1.13.0

### Operating system

Linux

### What browsers are you seeing the problem on?

Firefox

### Other information

It's running in GitLab CI/CD [using the `mcr.microsoft.com/playwright:focal` Docker image](https://gitlab.com/Vinnl/huizenfeed/-/blob/main/.gitlab-ci.yml#L3).

### What happened? / Describe the bug

Running a script that calls `playwright-firefox` terminates with the following error message:

```
Error: Cannot find module '/root/.npm/_npx/10/lib/node_modules/feed-me-up-scotty/node_modules/playwright-firefox/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

This has been happening in a job that runs a couple of times a day since Jul 22, 2021 7:05am GMT+0200 - the last job before that that ran successfully ran on Jul 21, 2021 3:25pm GMT+0200. Since version 1.13.0 of playwright-firefox was released on Jul 21, 2021 5:38pm GMT+0200, it seems likely that a change there caused this.

### Code snippet to reproduce your bug

If this doesn't ring a bell w.r.t. what the issue could be, let me know, and I can see if I can set up a minimal reproduction repository on GitLab.

**Comment by dgozman** [comment] 2021-07-27 21:42
The link to `gitlab-ci.yml` requires me to sign in. Could you please share something publicly accessible?

**Comment by Vinnl** [comment] 2021-07-28 06:34
Ah sorry, made it public, but essentially it's just this CI config that shows that I'm using the `mcr.microsoft.com/playwright:focal` Docker image.

```
pages:
  stage: deploy
  image: mcr.microsoft.com/playwright:focal
  script:
  - npx feed-me-up-scotty
  artifacts:
    paths:
    - public
    expire_in: 1 day
  only:
  - main
  retry:
    max: 2
    when: always
```

The script it's running (`npx feed-me-up-scotty`) is [this one](https://gitlab.com/vincenttunru/feed-me-up-scotty/-/blob/main/src/index.ts), if it's relevant.

**Comment by mxschmitt** [comment] 2021-07-28 23:06
I tried to reproduce it on my Mac and with the Docker image but was not able to. Maybe GitLab is doing some magic internally. We recommend also to pin the Docker images, so the browser does not need to get downloaded all the time: `mcr.microsoft.com/playwright:v1.13.0-focal`. Could you verify that you face the issue still with this Docker image?

**Comment by Vinnl** [comment] 2021-07-29 07:10
Unfortunately with the pinned Docker image [it still fails](https://gitlab.com/Vinnl/huizenfeed/-/jobs/1461119388). Pinning it to 1.12.3, as expected, _does_ work.

Unfortunately I'm not too familiar with Docker, so I'm not sure how to run that locally properly. If you could share the code you used to reproduce and the command to run I'd be happy to try to reproduce it myself though. Otherwise it indeed does seem likely that something in GitLab's environment is throwing a spanner into the works :/

**Comment by mxschmitt** [comment] 2021-07-29 07:21
[This](https://supportcenter.devexpress.com/ticket/details/t914123/the-error-cannot-find-module-root-npm-npx-3704-lib-node-modules-devextreme-cli-node) seems related, so using the pwuser user instead should fix it, not sure if its something which we can fix on our side. Since GitLab [does not support ](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2750)custom users via the config, you need to leverage "su" manually.

**Comment by mxschmitt** [comment] 2021-07-30 11:43
Closing since it works with the pwuser and its an upstream NPM bug, please upvote https://github.com/npm/cli/issues/3123.

**Closed by mxschmitt** 2021-07-30 11:43 UTC
Labels: triaging

**Comment by Vinnl** [comment] 2021-08-07 11:35
Unfortunately I'm getting the same error if I run `su pwuser` first. It's also curious that the problem disappears with Playwright 1.12.3, implying it might be the interaction with something Playwright has started doing that's causing the issue?
