### ISSUE TITLE
Record new from vscode extension loses the command bar

### ISSUE THREAD

**Issue by sys13** [microsoft/playwright#28339] opened 2023-11-25 17:28 UTC
**Context:**
- Playwright Version: 1.40.0
- Operating System: mac
- Node.js version: 20.3.1
- Visual Studio Code version: 1.84.2
- Playwright for VSCode extension version: v1.0.18
- Browser: Chromium

**Describe the bug**

When I click on Record New, it goes to about:blank. 
- I expect it to open the baseurl or port that I specified in playwright.config.ts
I navigate to localhost:3000 and can see my app. The command bar at the top disappears
- I expect the command bar to remain so that I can create expects from the recorder

**Comment by mxschmitt** [comment] 2023-11-26 10:54
Record New is not related to any project, we could address it with https://github.com/microsoft/playwright/issues/26777.

What do you mean with the following?

> I expect the command bar to remain so that I can create expects from the recorder

Its expected that the user manually navigates to some website on the browser which got opened. Which command bar do you mean?

**Comment by sys13** [comment] 2023-11-26 17:01
> Its expected that the user manually navigates to some website on the browser which got opened. Which command bar do you mean?
@mxschmitt referring to the bar with: red record button, 'pick locator', 'assert visibility', 'assert text', 'assert value'
<img width="988" alt="image" src="https://github.com/microsoft/playwright/assets/1377089/2d459f5b-984c-4494-ae91-744f51a86ecc">

It disappears after navigating to `localhost:3000` from the browser url bar

**Comment by mxschmitt** [comment] 2023-11-26 21:49
I tried to reproduce doing the following:

- Using v1.40.0
- Clicking Record New in VSCode
- Navigating to `localhost:3000` with the web server started before with `npx http-server --port 3000`

What do I do different?

Looks like we need to know more about your localhost:3000 web server in order to debug this issue further.

**Comment by pavelfeldman** [comment] 2023-11-29 20:45
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Closed by pavelfeldman** 2023-11-29 20:45 UTC
Labels: triaging
