### ISSUE TITLE
[Question] Getting 'locator.click: Target page, context or browser has been closed'

### ISSUE THREAD

**Issue by mayaknayak21** [microsoft/playwright#18448] opened 2022-10-31 14:54 UTC
Hi!

Our playwright tests have been failing frequently after being considerably stable for months due to the following errors logged in our telemetry: 

<html>
<body>

EventInfo_Time | name | result | severity | geo | runEnv | error | EventInfo_Name | run 
-- | -- | -- | -- | -- | -- | -- | -- | -- 
2022-10-22 14:21:39.7280000 | Process Advisor page test sharing a process > Case X : Process insights share recording | unexpected | S4 | US | PREVIEW | locator.click: Target page, context or browser has been closed | testresult | PPUX runner test 

</body>
</html>

Is this a known issue / is there a known workaround for the browser closing prematurely on a consistent basis? 

Any pointers would be greatly appreciated, thank you!

**Comment by aslushnikov** [comment] 2022-11-01 17:38
> Is this a known issue / is there a known workaround for the browser closing prematurely on a consistent basis?

@mayaknayak21 Usually this means there's a missing `await` statement somewhere in the test code. Unfortunately, I won't be able to help without further information; if you have a repro that we can run locally that would reproduce the issue, we'll have more to work with. 

I'll close this for now, but please feel free to file another issue if you think we can be helpful.

**Closed by aslushnikov** 2022-11-01 17:38 UTC

**Comment by coffewithmi1k** [comment] 2023-09-25 19:54
Hi, I also had this random flakiness in Chrome browser. Turns out I was trying to implement page object pattern in wrong way where in before each hook I initialised previously declared pages and then in test I was using them. Everything worked fine in headed mode or ui mode, but most of the case when I run it on ci or headless it fail. 
Solution for me is to wrap page objects in fixtures and now it looks stable after several runs.
 test('It verifies search', async({app}) => {
    await app.dashboardPage.clickSearchBtn();
    await app.page.waitForTimeout(3000);
    await app.dashboardPage.typeSearchValue('fixtures');
hopefully it will help someone :)

**Comment by czrvlla** [comment] 2024-07-26 12:43
Hi, I'm getting "Error: locator.click: Target page, context or browser has been closed". 

test.describe.configure({mode: 'serial'});
ExcelDataProvider.forEach(data =>{   
    test(`${data.TestCaseId}${data.TestCaseName}`, async ({ page }) => {
        await page.goto('/');
        await page.waitForURL('/');
        pm = pm || new PageManager(page);
        await pm.pomHelper.languageSelector('EN');
        await pm.pomHelper.acceptCookies();
    });
}

-----------------------------------------------------------------------------------
    async languageSelector(language: string){
        await this.page.locator('.language-dropdown-toggle').click();
        await this.page.locator(`.language-selector:has-text('${language}')`).click();
        await this.page.waitForLoadState('load');
    }

    async acceptCookies(){
        if(await this.page.locator('div[class="ot-sdk-container"]').isVisible()){
            await this.page.locator('button[id="onetrust-accept-btn-handler"]').click();
        }
    }

First iteration was running perfectly. But when running 2nd set of test data I got an error in "languageSelector" method. I have await for all the lines. Btw, I'm running this test as series.
