### ISSUE TITLE
Quick selection of a new reference screenshot

### ISSUE THREAD

**Issue by ivanqa2022** [microsoft/playwright#22489] opened 2023-04-19 15:08 UTC
We have huge volumes of runs in visual comparison. We often face the problem that it is necessary to assign a new screenshot as a reference. It will be very convenient to have a button in the report for reassigning a screenshot.

<img width="827" alt="image" src="https://user-images.githubusercontent.com/116289351/233119333-2144dc98-0668-4fac-840f-10f8bae5a817.png">

**Comment by dgozman** [comment] 2023-04-19 18:30
Duplicate of #14883.

**Closed by dgozman** 2023-04-19 18:30 UTC
