### ISSUE TITLE
[BUG] fn is not defined when evaluate async function

### ISSUE THREAD

**Issue by lingfei1999** [microsoft/playwright#23647] opened 2023-06-11 16:14 UTC
### System info
- Playwright Version: 1.35.0
- Operating System: Windows 11
- Browser: Chromium
- Other info:

```js
// playwright.config.ts
page.evaluate(async () => { console.log('should work') })
```

**Steps**
- [Run the code]

**Expected**
The function should output should work to console

[Describe expected behavior]

**Actual**

There is a bug: 
page.evaluate: ReferenceError: fn is not defined

More info: 
This actually worked before, now it doesn't work anymore. There might be recent changes that break the code.

**Comment by mxschmitt** [comment] 2023-06-12 10:23
Do you have a reproduction which you can share? Without that we unfortunately can't act on it.

**Comment by aslushnikov** [comment] 2023-06-12 19:50
@lingfei1999 I'll close this for now since there's definitely not enough information. Please re-file with a repro that we can run locally.

**Closed by aslushnikov** 2023-06-12 19:50 UTC

**Comment by lingfei1999** [comment] 2023-06-12 19:55
@aslushnikov Sorry, I didn't see the reply. To reproduce the case, just use this line of code in any part of the project: 

```
page.evaluate(async () => { console.log('should work') })
```

**Comment by felamaslen** [comment] 2025-03-14 18:17
I can also reproduce this.
