### ISSUE TITLE
[BUG] playwright-1.3.0 causing Unhandled Promise error in Node-12.18

### ISSUE THREAD

**Issue by amifunny** [microsoft/playwright#3435] opened 2020-08-13 15:02 UTC
**Context:**
- Playwright Version: 1.3.0
- Operating System: Windows
- Node.js version: 12.18.1
- Browser: All

**Code Snippet**
```
const playwright = require('playwright');
const browserType = 'chromium';

async function botfunc() {
	let browser = playwright[browserType].launch();
	const context = await browser.newContext();
	const page = await context.newPage();
	
	await page.goto("http://google.com");
}

botfunc();
```

**Describe the bug**
Error log -
```
UnhandledPromiseRejectionWarning: Error: browserType.launch: Host system is missing dependencies!
Full list of missing libraries:
   api-ms-win-core-winrt-error-l1-1-0.dll

```
It was solved when I used 1.0.2 version.

**Comment by mxschmitt** [comment] 2020-08-13 15:14
Hi, which exact version of Windows are you using? (you can find it in the Settings -> About)

**Comment by amifunny** [comment] 2020-08-13 15:38
@mxschmitt It is Windows7

**Comment by ruslanx3m** [comment] 2020-08-17 11:52
**playwright[browserType]**  must be **playwright**

const playwright = require('playwright');
const browserType = 'chromium';

async function botfunc() {
	let browser = playwright.launch();
	const context = await browser.newContext();
	const page = await context.newPage();
	
	await page.goto("http://google.com");
}

botfunc();

**Comment by aslushnikov** [comment] 2020-08-21 08:28
Dupe of https://github.com/microsoft/playwright/issues/3496

**Closed by aslushnikov** 2020-08-21 08:28 UTC
