### ISSUE TITLE
[BUG] Invalid option in transform() call: "jsxSideEffects"

### ISSUE THREAD

**Issue by lukaskoeller** [microsoft/playwright#22233] opened 2023-04-06 11:01 UTC
### System info
- Playwright Version: 1.32.2 (experimental-ct-react)
- Operating System: macOS Ventura 13.0
- Browser: All
- Other info: playwright uses `vite@2.8.6` to build for production (shown when running cmd in terminal). For the reproduction I added vite to `peerDependencies` using version `2.8.6` which is causing the error. This is not exactly how it is in the package of the repository where the error appeared first. There, playwright just uses another vite version that is used in some other package of the monorepo and remains using that version even if I update vite in that package and the particular version number `2.8.6` only remains appearing in the `pnpm-lock.yaml` for the whole monorepo. When I run `pnpm --filter "@*/components" test:units` so all packages use `4.2.1` playwright then also uses `4.2.1` and then everything works as expected

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[Github Reproduction](https://github.com/lukaskoeller/playwright-ct-vite-reproduction)

**Steps**

Using the [reproduction from github](https://github.com/lukaskoeller/playwright-ct-vite-reproduction)
- `pnpm i`
- `pnpm --filter "@ct/components" test:units`

Using your own repro
- Add `@playwright/experimental-ct-react17`
- Add `"vite": "^2.8.6"` to `peerDependencies`
- Run `pnpm i`
- Run test via `pnpm test-ct`
- Playwright will show `vite v2.8.6 building for production…`
- Test fails with `Invalid option in transform() call: "jsxSideEffects"`.

**Expected**

* All tests are running through
* or playwright exits with an error informing me that the vite version is not supported and shows min supported vite version
* or playwright just informs me that it is using another vite version to run the tests instead of the referenced version

**Actual**

Test run fails with error `Invalid option in transform() call: "jsxSideEffects"`.

**Comment by pavelfeldman** [comment] 2023-04-06 17:39
Please use the issue template to file something we can reproduce or to make sure we are fixing the problem you want fixed.

**Comment by lukaskoeller** [comment] 2023-04-11 13:44
@pavelfeldman I used the issue template and added a Github link (following the template comment `<!-- For larger cases, you can provide a GitHub repo you created for this issue -->`). Now I also added steps to manually reproduce the issue without using the repro provided.

Is there anything missing?

**Comment by pavelfeldman** [comment] 2023-04-16 22:57
@sand4rt looks like this is fixed with the playwright-ct-core as well as it'll strongly depend on vite and resolve it. Current bug is that we depend on vite from playwright-ct-react, but require it dynamically in @playwright/test. Did you start working on it? If not, I'll introduce it.

**Comment by sand4rt** [comment] 2023-04-17 04:30
@pavelfeldman was experimenting with it but wanted to merge this one first: https://github.com/microsoft/playwright/pull/20287#issuecomment-1501958139. If you want to add it that's fine too!

**Closed** 2023-04-17 23:19 UTC
Labels: v1.33
