### ISSUE TITLE
Custom Reporter error logs include ansi color codes

### ISSUE THREAD

**Issue by yuto89** [microsoft/playwright#18554] opened 2022-11-03 20:25 UTC
**Context:** TestResult.TestError.stack, TestResult.TestError.message, TestResult.TestError.value are returning strings with ansi color codes, making it difficult to export error logs to a third party reporter.

// sample.spec.ts
```
test('should fail', async ({ page }) => {
    await page.goto('https://playwright.dev')
    const getStartedBtn = await page.locator('.getStarted_Sjon')
    await expect(getStartedBtn).toHaveAttribute('href', '/doc/intro')
})
```

// my-reporter.ts
```
class MyReporter implements Reporter {
    onTestEnd(test, result) {
        console.log(result.error.stack);
        // console.log(result.error.message);
        // console.log(result.error.value);
    }
}

export default MyReporter;
```

**Output**

expected: 
```
    Error: expect(received).toHaveAttribute(expected)

    Expected string: "/doc/intro"
    Received string: "/docs/intro"
```

actual: 
```
'Error: \x1B[2mexpect(\x1B[22m\x1B[31mreceived\x1B[39m\x1B[2m).\x1B[22mtoHaveAttribute\x1B[2m(\x1B[22m\x1B[32mexpected\x1B[39m\x1B[2m)\x1B[22m\n' +
    '\n' +
    'Expected string: \x1B[32m"/doc/intro"\x1B[39m\n' +
    'Received string: \x1B[31m"/doc\x1B[7ms\x1B[27m/intro"\x1B[39m\n'
```

**Comment by aslushnikov** [comment] 2022-11-04 11:03
Looks like a dupe of https://github.com/microsoft/playwright/issues/13522

**Closed by aslushnikov** 2022-11-04 11:03 UTC
