### ISSUE TITLE
[BUG] Firefox hangs when returning all promises

### ISSUE THREAD

**Issue by mjgp2** [microsoft/playwright#9544] opened 2021-10-15 16:57 UTC
**Context:**

## System:
 - OS: macOS 11.2.3
 - Memory: 733.08 MB / 32.00 GB
## Binaries:
 - Node: 16.5.0 - /usr/local/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 7.19.1 - /usr/local/bin/npm
## Languages:
 - Bash: 5.0.18 - /usr/local/bin/bash
## npmPackages:
 - playwright: ^1.16.0-next-alpha-oct-15-2021 => 1.16.0-next-alpha-oct-15-2021 

**Code Snippet**

```javascript
const { firefox } = require('playwright');

(async () => {
  const browser = await firefox.launch();
  const page = await browser.newPage({ javaScriptEnabled: false });
  console.log(await page.evaluate(()=> 1));
  // this will hang
  console.log(await page.evaluate(async() => 2));
})().catch(e => console.error(e));

```

**Describe the bug**

Firefox hangs when returning all promises when `javaScriptEnabled` is set to `false`, even ones that are already resolved.

**Comment by yury-s** [comment] 2021-10-15 20:30
Can reproduce in WebKit and Firefox.

**Comment by pavelfeldman** [comment] 2022-10-20 03:00
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-10-20 03:00 UTC
Labels: browser-webkit, P3-collecting-feedback, browser-firefox
