### ISSUE TITLE
[BUG]: Submit button is not getting enabled after filling a login form.

### ISSUE THREAD

**Issue by TechieVats** [microsoft/playwright#27564] opened 2023-10-12 08:42 UTC
I am testing a login functionality where use need to fill two fields and then the login button enables for further process.
I am using the fill() command to perform the operation. Text has been entered by playwright correctly but it is not enabling the submit button.

If I clear the field manually within the same session and again type it , it enabled the button.

**Comment by MindaugasMateika** [comment] 2023-10-12 09:14
I think what you're describing is somewhat explained here https://playwright.dev/python/docs/navigations#hydration. This is not a Playwright issue but an issue with your application and that's where it needs to be fixed.

From tests side, you could try press with ~50 delay https://playwright.dev/python/docs/api/class-locator#locator-press but that might still produce flaky results.

**Comment by alexmalev** [comment] 2023-10-12 09:54
i've been scratching my head over tests starting to fail after last upgrade to `^1.39.0`.
we are running login to google test by clicking on a user in the user list  (pre logged in in the browser session) in the google login page.
it used to run flawlessly and now fails **always** with the click action beeing performed on the element but timeout throws 
we are running on firefox headless, so i suspect it maybe related to the firefox version upgrade in the new version, and maybe to some webGl changes introduces there, but still investigating

**Comment by dgozman** [comment] 2023-10-12 15:56
In addition to what @MindaugasMateika said, this looks like either a hydration issue, or wrong handling of input fields. You can try copying something in clipboard, right-clicking on the field and selecting "Paste" - there is a chance this does not work on the page you are testing.

In both cases, this is likely to be a bug in the page that you have just found!

If you don't think there is a bug in the page, please share a repro that we can run locally to be able to reproduce, and we'll take a look.

**Comment by dgozman** [comment] 2023-10-15 14:49
Closing as per above. If you still encounter problems, please file a new issue with a repro and link to this one.

**Closed by dgozman** 2023-10-15 14:49 UTC
Labels: triaging
