### ISSUE TITLE
[Feature]element.clickAndHold()

### ISSUE THREAD

**Issue by roughsoft** [microsoft/playwright#2168] opened 2020-05-09 13:51 UTC
Let us know what functionality you'd like to see in Playwright and what is your use case.
Do you think others might benefit from this as well?
the selenium support it 
Actions actions= new Actions(driver);
actions.moveToElement(webElement).clickAndHold().perform();

**Comment by roughsoft** [comment] 2020-05-09 13:52
maybe drop and drag

**Comment by mxschmitt** [comment] 2020-05-09 14:02
Probably a duplicate of #1094.

**Comment by aslushnikov** [comment] 2020-05-14 06:58
Closing as a dupe of #1094

**Closed by aslushnikov** 2020-05-14 06:58 UTC
