### ISSUE TITLE
[Question] Handling of layout-based selectors with or without CSS hints

### ISSUE THREAD

**Issue by klhex** [microsoft/playwright#5225] opened 2021-01-30 20:02 UTC
**Context:**
- Playwright Version: 1.8.0
- Operating System: MacOS 11.1
- Node.js version: 15.0.6
- Browser: Chromium

**Code Snippet**

```javascript
const {chromium} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://opengiro.ing.de/pub/girokonto-einzelkonto');
  await page.fill(
    ':below(:text("Prof.")):above(:text("Name")):right-of(:text("Vorname"))',
    "Test"
  );
  // alternatively
  // await page.fill(':right-of(:text("Vorname"))', "Test");
})();
```

![image](https://user-images.githubusercontent.com/71178731/106366374-b375e380-633b-11eb-97f5-952879e4e1c4.png)

```html
<div class="form-group" id="id31">
    <label class="form-group__label" for="id32"> Vorname </label>

    <span class="form-group__controls form-group__controls--l">
        <input class="input-field" type="text" value="" name="view:person1:form:vorname:vorname" id="id32"
            maxlength="17" minlength="2" />
        <span class="form-group__definition-container"> </span>
    </span>
</div>
````

**Describe the bug**

The first page.fill above leads to the following error message:
```
node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.fill: Element is not an <input>, <textarea> or [contenteditable] element
=========================== logs ===========================
waiting for selector ":below(:text("Prof.")):above(:text("Name")):right-of(:text("Vorname"))"
  selector resolved to visible <span class="form-group__controls form-group__controls…>…</span>
elementHandle.fill("Test")
  waiting for element to be visible, enabled and editable
============================================================
```

The second (alternative) page.fill similarly leads to the following error message:
```
node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.fill: Element is not an <input>, <textarea> or [contenteditable] element
=========================== logs ===========================
waiting for selector ":right-of(:text("Vorname"))"
  selector resolved to visible <span class="form-group__controls form-group__controls…>…</span>
elementHandle.fill("Test")
  waiting for element to be visible, enabled and editable
============================================================
```
However, if the CSS element type "input" is put before the first ":text" then the wanted input field is found and filled out correctly:
```javascript
(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://opengiro.ing.de/pub/girokonto-einzelkonto');
  await page.fill(
    ':below(input:text("Prof.")):above(:text("Name")):right-of(:text("Vorname"))',
    "Test"
  );
  // alternatively
  // await page.fill('input:right-of(:text("Vorname"))', "Test");
})();
```

**Expected behavior**

In both cases of page.fill in the first code snippet (i.e., w/o adding CSS "input" as hint), Playwright finds the right input field (the one with the cursor in it in the above screenshot) and fills it with "Test".

**Further information**

The corresponding Playwright [documentation](https://playwright.dev/docs/selectors#selecting-elements-based-on-layout) states: "Playwright can select elements based on the page layout. These _can_ be combined with regular CSS for better results" (my emphasis). However, at least in this case, I have not found a way to succeed w/o adding a CSS hint.

If Playwrights works as designed here, I'd be happy about an explanation on why and on the cases in which one generally has to provide a CSS hint in order to get the right element selected (if this can be described in a general way) so that I get a better feeling beforehand on when to add CSS and when I can leave it out.

**Comment by aslushnikov** [comment] 2021-02-01 16:55
> I'd be happy about an explanation on why and on the cases in which one generally has to provide a CSS hint in order to get the right element selected (if this can be described in a general way) so that I get a better feeling beforehand on when to add CSS and when I can leave it out.

@klhex I do think it works as designed. Let me also demonstrate you how to debug the selectors.

First thing I did - ran your snippet with the [`PWDEBUG`](https://playwright.dev/docs/debug?_highlight=pwdebug#run-in-debug-mode) environment variable and with the `page.fill` call commented out.

<details>
  <summary>code snippet</summary>

```js
const {chromium} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://opengiro.ing.de/pub/girokonto-einzelkonto');
  /*
  await page.fill(
    ':below(:text("Prof.")):above(:text("Name")):right-of(:text("Vorname"))',
    "Test"
  );
  */
})();
```

</details>

I saved the codesnippet as `a.js` and ran it like this:

```sh
$ PWDEBUG=1 node a.js
```

Now, the browser window got opened. I can not open DevTools, navigate to the `Console` tab, and use the `playwright` helper function available there to test selectors.

First, let's test the first selector: `:below(:text("Prof.")):above(:text("Name")):right-of(:text("Vorname"))`

![image](https://user-images.githubusercontent.com/746130/106490209-72302180-646a-11eb-9f2f-88fc1deeb561.png)

As you see, it selects a `<span>` element, not an input. The reason is that **there are multiple elements that satisfy given selector, and Playwright returns any of them that satisfies the condition**.

However, since you're looking for an input, you can explicitly tell Playwright to select `<input>` element. The easiest would be to start the whole selector with `input`: `input:below(:text("Prof.")):above(:text("Name")):right-of(:text("Vorname"))`

![image](https://user-images.githubusercontent.com/746130/106490778-07331a80-646b-11eb-870f-4b65fd105953.png)


Does this make things any clearer?

**Comment by klhex** [comment] 2021-02-01 20:24
@aslushnikov Thanks for your great explanation and the details about how to debug such issues in/with Playwright, very helpful! 👍  I understand your point and would also say now that it works as designed and it's not a bug. And I also understand now that it's not really possible to state in general when one would have to add a CSS hint and when not since it really depends on the elements of the page in question.

I think what got me irritated a bit was the fact the the used selector engine returned an element whose type is not compatible with page.fill and therefore made page.fill throw an error (but this is actually pretty common in the test automation tools I've played around with, as I realize). 

Would it be conceivable to add an option to Playwright which would make selector engines only return elements whose type are compatible to the API method they are returned to? In the case of page.fill that would only be elements of the type <input>, <textarea> or [contenteditable] according to the docs. If that's a feature you guys could potentially contemplate, I'd be happy to raise a corresponding feature request.

From my point of view this issue can be closed. However, since you assigned the label "triaging" to it, I leave it to you guys to close it. 😃

**Comment by dgozman** [comment] 2021-02-02 17:35
@klhex Thank you for the issue. We'll think about assisting with target elements for `fill`, as you suggest, although we should be careful. Closing this issue.

**Closed by dgozman** 2021-02-02 17:35 UTC
Labels: triaging

**Comment by klhex** [comment] 2021-02-02 19:15
@dgozman Thanks for thinking about the suggestion. However, if one is aware of the details described in this issue, it's fairly straightforward to prevent such errors from coming up.
