### ISSUE TITLE
[BUG] Video artefact isnt created while using reused page

### ISSUE THREAD

**Issue by dimkin-eu** [microsoft/playwright#18444] opened 2022-10-31 08:34 UTC
**Context:**
- Playwright Version: 1.27.1
- Operating System: Linux and Mac
- Node.js version: v16.17.0

```javascript
import {test, expect, Page} from '@playwright/test';

test.describe("Sample test", () => {
  let page: Page

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage()
  })

  test.afterAll(async () => {
    await page.close()
  })

  test('homepage has Playwright in title and get started link linking to the intro page', async () => {
    await page.goto('https://playwright.dev/');
    await expect(page).toHaveTitle(/Playwrights/);
  })
})
```

**Describe the bug**

such code ( note "shared" `page` used as mentioned [here](https://playwright.dev/docs/next/test-retries#reuse-single-page-between-tests) ) doesn't create a video ( also on failure ) - `video: 'retain-on-failure'` /  `video: 'on'` doesn't create a file

A shorter code (below) works well

```javascript
import { test, expect } from '@playwright/test';

test.describe("Sample test", () => {
  test('homepage has Playwright in title and get started link linking to the intro page', async ({page}) => {
    await page.goto('https://playwright.dev/');
    await expect(page).toHaveTitle(/Playwrights/);
  })
})
```

**Comment by aslushnikov** [comment] 2022-11-02 21:05
duplicate of https://github.com/microsoft/playwright/issues/14813

**Closed by aslushnikov** 2022-11-02 21:05 UTC
