### ISSUE TITLE
[BUG] APP stuck in electron.launch step

### ISSUE THREAD

**Issue by galak06** [microsoft/playwright#9786] opened 2021-10-26 13:37 UTC
**Context:**
- Playwright Version: 16
- Operating System: macOS Big Sur 11.6
- Node.js version: 16
- Extra: electron

**Code Snippet**
const electronApp = await electron.launch({
      args: ["index.js"],
    });

```javascript
const {chromium, webkit, firefox} = require('playwright');

**Describe the bug**
after the electron launch, the code stays in the launch scope and does not continue. 
also, i can't get const window = await electronApp.firstWindow();

Add any other details about the problem here.

**Comment by dgozman** [comment] 2021-10-31 18:27
Closing because we cannot reproduce the issue.

**Closed by dgozman** 2021-10-31 18:27 UTC
Labels: triaging
