### ISSUE TITLE
[BUG]record can not work in drag mouse event

### ISSUE THREAD

**Issue by chensce** [microsoft/playwright#23588] opened 2023-06-08 03:05 UTC
### System info
- Playwright Version: [v1.34]
- Operating System: [macOS 13.2]
- Browser: [Chromium]
- Other info:

the uta site is:

[https://github.com/your_profile/playwright_issue_title]](https://bonigarcia.dev/selenium-webdriver-java/drag-and-drop.html)

**Comment by aslushnikov** [comment] 2023-06-08 05:33
This is a dupe of https://github.com/microsoft/playwright/issues/19892

**Closed by aslushnikov** 2023-06-08 05:33 UTC
