### ISSUE TITLE
[BUG] firefox context.on seems not working

### ISSUE THREAD

**Issue by kingkhan1431** [microsoft/playwright#6189] opened 2021-04-13 05:30 UTC
**Context:**
- Playwright Version: 1.10
- Operating System: windows 10
- Node.js version: 15.14.0
- Browser:  Firefox, WebKit

**Code Snippet**
```javascript
  async function firefoxLauncher() {

    const browser = await firefox.launch(
      {
        headless: false,
        firefoxUserPrefs: {
          'intl.accept_languages'       : 'en-IN',
          'general.useragent.override'  : 'Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/87.0',
          'general.useragent.vendor'    : 'Firefox',
          'general.useragent.vendorSub' : '87.0'
        }
      }
    );

    const browserContext = await browser.newContext(
      {
        viewport: { width:1920, height:1080 }
      }
    );

    const iPage = await browserContext.newPage();
    await iPage.goto('url1');

    browserContext.on('page', async page => {
      await page.setViewportSize({ width:1920, height:1080 });

    })
}
```

**Describe the bug**

on manual new tab page it seems not working even setting viewport is not working at the same time chromium working flawlessly

**Comment by dgozman** [comment] 2021-04-13 18:10
@kingkhan1431 Are you running headed Firefox and using `Ctrl+N` or something similar to open a new window?
- If you do that, the new page does not belong to the `browserContext` you created, but instead belongs to a new context created by Firefox browser. In this case, I am not sure we'll be able to help in the near future. Why do you need this functionality?
- If you are doing something else, please describe in more details, so that we can reproduce it.

**Comment by kingkhan1431** [comment] 2021-04-13 19:38
ya am using headed firefox and just now learning automation.i was checking my website with playwright without automation when i checked with chrome it worked great.i can casually open up a new tab and check the update.but when i tried with firefox on the new tab page it not worked.
i was curious to know why its not worked.any explanation why its working with chrome not with firefox?

**Comment by dgozman** [comment] 2021-04-13 20:03
@kingkhan1431 Firefox and Chromium are different browsers and behave differently in this case.

I will close this issue, since the question was answered. If there is something that I missed, please reply here, and we'll reopen.

**Closed by dgozman** 2021-04-13 20:03 UTC
Labels: triaging

**Comment by kingkhan1431** [comment] 2021-04-13 20:14
all good thanks for the reply bro...

**Comment by kingkhan1431** [comment] 2021-04-14 01:01
@dgozman btw am not using CTRL+N. normal new tabs i was referring to like opening by clicking '+' mark in browser or CTRL+T
