### ISSUE TITLE
[Bug]: Devops Pipelines/Releases fail to run npx playwright test

### ISSUE THREAD

**Issue by wupaz** [microsoft/playwright#7587] opened 2021-07-13 19:13 UTC
### Playwright version

1.12.3

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

npm/6.14.13
node/v14.17.3 win32 x64

Azure Release : Agent.Version 2.188.4
Windows 2019

In package.json
"@playwright/test": "^1.12.3",
"playwright": "^1.12.3",

### What happened? / Describe the bug

When I try to run npx playwright test in a Pipelines/Releases I got this error 

If I run manually on same server same code (in release deploy directory) it work 

![2021-07-13_14-41-33](https://user-images.githubusercontent.com/14102653/125511324-513a8484-1b6e-4c2d-84b1-98d9abdd73e9.png)

### Code snippet to reproduce your bug

```shell
npx playwright test
```

### Relevant log output

```shell
021-07-13T17:35:20.4031005Z ##[section]Starting: Run Playwright Test 
2021-07-13T17:35:20.4155036Z ==============================================================================
2021-07-13T17:35:20.4155649Z Task         : Command Line
2021-07-13T17:35:20.4156001Z Description  : Run a command line with arguments
2021-07-13T17:35:20.4156302Z Version      : 1.1.3
2021-07-13T17:35:20.4156597Z Author       : Microsoft Corporation
2021-07-13T17:35:20.4157052Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
2021-07-13T17:35:20.4157535Z ==============================================================================
2021-07-13T17:35:20.4186740Z ##[debug]Working directory: 'C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e'
2021-07-13T17:35:20.4196097Z ##[debug]Fail on standard error: 'False'
2021-07-13T17:35:20.4196492Z ##[debug]Modify environment: 'False'
2021-07-13T17:35:20.4196878Z ##[debug]C:\windows\system32\cmd.exe /c "npx playwright test"
2021-07-13T17:35:20.4197250Z ##[command]npx playwright test
2021-07-13T17:35:22.5056679Z Error: Error while reading C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e\e2e\playwright\use-case\add-new-patient.uctest.spec.ts:
2021-07-13T17:35:22.5058090Z describe() can only be called in a test file
2021-07-13T17:35:22.5956884Z ##[error]Process completed with exit code 1.
```

**Comment by aslushnikov** [comment] 2021-07-13 22:24
@wupaz peculiar! Any chance you can share this `e2e\playwright\use-case\add-new-patient.uctest.spec.ts` file that has this error? What happens if you remove (fully comment) this file?

**Comment by wupaz** [comment] 2021-07-13 22:30
If I comment I got an error on second file, I got this same error for each file I have.

**Comment by wupaz** [comment] 2021-07-13 22:37
```

import { test, expect, Page } from '@playwright/test';
import { AdminPageObject } from "../app-component/administrator-admin.po";
import { EditPatienPageObject } from "../app-component/dialog-edit-patient.po";
import { HeaderPageObject } from "../app-component/header.po";
import { LoginPageObject } from "../app-component/login.po";
import { ProfilesDetailsPageObject } from "../app-component/profiles-details.po";
import { ProfilesListPageObject } from "../app-component/profiles-list.po";
import { HomePageObject } from "../app-component/home.po";
import { Global } from "../Helper/global";
import { navigationHelper } from "../Helper/navigation";
import { PatientHelper } from "../Helper/patient-helper";


test.describe('Test la creation de patient', () => {
    let adminPO: AdminPageObject;
    let headerPO: HeaderPageObject;
    let loginPO: LoginPageObject;
    let profileListPO: ProfilesListPageObject;
    let profileDetailPO: ProfilesDetailsPageObject;
    let homePagePO: HomePageObject;
    let editPatienPagePO: EditPatienPageObject;

    test.beforeAll(async () => {
    });



    test.beforeEach(({ page }) => {
        adminPO = new AdminPageObject(page);
        loginPO = new LoginPageObject(page);
        headerPO = new HeaderPageObject(page);
        profileListPO = new ProfilesListPageObject(page);
        profileDetailPO = new ProfilesDetailsPageObject(page);
        homePagePO = new HomePageObject(page);
        editPatienPagePO = new EditPatienPageObject(page);
    });


    test('Creation dun patient minimum spec', async ({ page }) => {
        await PatientHelper.addRandomPatient(page);
    });

    test('Valider que le nouveau patient creer se retrouve en haut de la liste des patient recent', async ({ page }) => {
        try {
            let newPatient = await PatientHelper.addRandomPatient(page);
            await navigationHelper.navigateBack(page);
            console.log(newPatient);
            let patientNameInCard = await homePagePO.getFirstPatientFullNameFromRecentPatientCard();
            console.log("? ->" + patientNameInCard);
            console.log("? ->" + newPatient.firstName);
            expect(patientNameInCard.search(newPatient.firstName)).toBeTruthy();
        }
        finally { }
    });

    test.afterEach(async () => {
    });

    test.afterAll(async ({ browser }) => {
    });

});

```

**Comment by wupaz** [comment] 2021-07-13 22:48
I try a another Pipelines/release Task  (Powershell inline) same error 

```
2021-07-13T21:05:30.4467965Z ##[debug]VstsTaskSdk 0.6.2 commit b4160c33da0010bd83279e9ffa9bbf13bcbd1ce2
2021-07-13T21:05:30.5070126Z ##[debug]Entering C:\AzurePiplinesAgent_Extension\_work\_tasks\InlinePowershell_31f040e5-e040-4336-878a-59a493355534\1.1.7\InlinePowershell.ps1.
2021-07-13T21:05:30.5252957Z ##[debug]Env:INPUT_SCRIPT: 'cd C:\AzurePiplinesAgent_Extension\_work\r4\a/GMaster\DevDrop/test_e2e
2021-07-13T21:05:30.5267119Z ##[debug]npx playwright test'
2021-07-13T21:05:30.5382869Z ##[debug]Env:INPUT_SCRIPTARGUMENTS (empty)
2021-07-13T21:05:30.5753446Z ##[command]& 'C:\windows\TEMP\tmp119A.ps1' 
2021-07-13T21:05:32.1518117Z ##[debug]Error record:
2021-07-13T21:05:32.2318698Z ##[debug]npx : Error: Error while reading C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e\e2e\playwright\use-case\add-new-patient.uctest.spec.ts:
2021-07-13T21:05:32.2321522Z ##[debug]At C:\windows\TEMP\tmp119A.ps1:2 char:1
2021-07-13T21:05:32.2336698Z ##[debug]+ npx playwright test
2021-07-13T21:05:32.2352948Z ##[debug]+ ~~~~~~~~~~~~~~~~~~~
2021-07-13T21:05:32.2381830Z ##[debug]    + CategoryInfo          : NotSpecified: (Error: Error wh...uctest.spec.ts::String) [], RemoteException
2021-07-13T21:05:32.2428411Z ##[debug]    + FullyQualifiedErrorId : NativeCommandError
2021-07-13T21:05:32.2430024Z ##[debug] 
2021-07-13T21:05:32.2450045Z ##[debug]Script stack trace:
2021-07-13T21:05:32.2483976Z ##[debug]at <ScriptBlock>, C:\windows\TEMP\tmp119A.ps1: line 2
2021-07-13T21:05:32.2515067Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-07-13T21:05:32.2531532Z ##[debug]at <ScriptBlock>, C:\AzurePiplinesAgent_Extension\_work\_tasks\InlinePowershell_31f040e5-e040-4336-878a-59a493355534\1.1.7\InlinePowershell.ps1: line 46
2021-07-13T21:05:32.2548591Z ##[debug]at <ScriptBlock>, C:\AzurePiplinesAgent_Extension\_work\_tasks\InlinePowershell_31f040e5-e040-4336-878a-59a493355534\1.1.7\InlinePowershell.ps1: line 42
2021-07-13T21:05:32.2552343Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-07-13T21:05:32.2567609Z ##[debug]at <ScriptBlock>, <No file>: line 22
2021-07-13T21:05:32.2582462Z ##[debug]at <ScriptBlock>, <No file>: line 18
2021-07-13T21:05:32.2600467Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-07-13T21:05:32.2624629Z ##[debug]Exception:
2021-07-13T21:05:32.2677501Z ##[debug]System.Management.Automation.RemoteException: Error: Error while reading C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e\e2e\playwright\use-case\add-new-patient.uctest.spec.ts:
2021-07-13T21:05:32.2948381Z ##[error]Error: Error while reading C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e\e2e\playwright\use-case\add-new-patient.uctest.spec.ts:
2021-07-13T21:05:32.2951699Z ##[debug]Processed: ##vso[task.logissue type=error]Error: Error while reading C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e\e2e\playwright\use-case\add-new-patient.uctest.spec.ts:
2021-07-13T21:05:32.2954160Z ##[debug]Processed: ##vso[task.complete result=Failed]
2021-07-13T21:05:32.2962283Z ##[debug]Error record:
2021-07-13T21:05:32.3020668Z ##[debug]describe() can only be called in a test file
2021-07-13T21:05:32.3085953Z ##[debug]Script stack trace:
2021-07-13T21:05:32.3087620Z ##[debug]at <ScriptBlock>, C:\windows\TEMP\tmp119A.ps1: line 2
2021-07-13T21:05:32.3106179Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-07-13T21:05:32.3125498Z ##[debug]at <ScriptBlock>, C:\AzurePiplinesAgent_Extension\_work\_tasks\InlinePowershell_31f040e5-e040-4336-878a-59a493355534\1.1.7\InlinePowershell.ps1: line 46
2021-07-13T21:05:32.3444443Z ##[debug]at <ScriptBlock>, C:\AzurePiplinesAgent_Extension\_work\_tasks\InlinePowershell_31f040e5-e040-4336-878a-59a493355534\1.1.7\InlinePowershell.ps1: line 42
2021-07-13T21:05:32.4073812Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-07-13T21:05:32.4406380Z ##[debug]at <ScriptBlock>, <No file>: line 22
2021-07-13T21:05:32.4423870Z ##[debug]at <ScriptBlock>, <No file>: line 18
2021-07-13T21:05:32.4454842Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-07-13T21:05:32.4478150Z ##[debug]Exception:
2021-07-13T21:05:32.4526533Z ##[debug]System.Management.Automation.RemoteException: describe() can only be called in a test file
2021-07-13T21:05:32.4533485Z ##[error]describe() can only be called in a test file
2021-07-13T21:05:32.4534612Z ##[debug]Processed: ##vso[task.logissue type=error]describe() can only be called in a test file
2021-07-13T21:05:32.4545005Z ##[debug]Processed: ##vso[task.complete result=Failed]
2021-07-13T21:05:32.4822655Z ##[section]Finishing: Run Playwright Test 
```

**Comment by pavelfeldman** [comment] 2021-07-19 22:23
It looks like your pipeline does not like `npx`. Try running `node_modules\.bin\playwright test` from the working folder instead. (Could be `.exe,.cmd,.bat`, not sure).

**Comment by wupaz** [comment] 2021-07-20 00:53
Maybe , but same test work fine on my pc and on deploy server when I run manually exact same code/test

**Comment by pavelfeldman** [comment] 2021-07-20 20:28
Max is suggesting that you are running Jest tests in fact. We don't really have enough information to address it. It works locally for you, so Playwright seems to be Ok.

**Comment by wupaz** [comment] 2021-07-21 14:07
Is it possible to active debug/verbose mode to get more information ?

**Comment by pavelfeldman** [comment] 2021-07-21 18:48
Sorry, no ideas. Given that it works both locally and on the server, it suggests something wrong is with your CI environment. Sorry, we can't help much. You can set `DEBUG=pw:browser` environment variable to see if the browsers fail to run on your CI.

**Comment by wupaz** [comment] 2021-07-21 20:10
Maybe this could help 

```
2021-07-21T20:08:48.4562701Z Error: describe() can only be called in a test file
2021-07-21T20:08:48.4569421Z     at TestTypeImpl._describe (C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e\node_modules\@playwright\test\lib\test\testType.js:83:23)
2021-07-21T20:08:48.4571552Z     at Function.describe (C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e\node_modules\@playwright\test\lib\test\transform.js:132:12)
2021-07-21T20:08:48.4577999Z     at Object.<anonymous> (C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e\e2e\playwright\use-case\add-new-patient.uctest.spec.ts:25:12)
2021-07-21T20:08:48.4579459Z     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2021-07-21T20:08:48.4584945Z     at Module._compile (C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\Test_e2e\node_modules\pirates\lib\index.js:99:24)
2021-07-21T20:08:48.4586122Z     at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2021-07-21T20:08:48.4588242Z     at Object.newLoader (C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\Test_e2e\node_modules\pirates\lib\index.js:104:7)
2021-07-21T20:08:48.4600487Z     at Module.load (internal/modules/cjs/loader.js:950:32)
2021-07-21T20:08:48.4601569Z     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
2021-07-21T20:08:48.4603000Z     at Module.require (internal/modules/cjs/loader.js:974:19)
2021-07-21T20:08:48.4603905Z     at require (internal/modules/cjs/helpers.js:92:18)
2021-07-21T20:08:48.4616835Z     at Loader._requireOrImport (C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\Test_e2e\node_modules\@playwright\test\lib\test\loader.js:211:18)
2021-07-21T20:08:48.4618388Z     at Loader.loadTestFile (C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\Test_e2e\node_modules\@playwright\test\lib\test\loader.js:130:18)
2021-07-21T20:08:48.4619820Z     at Runner._run (C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\Test_e2e\node_modules\@playwright\test\lib\test\runner.js:210:59)
```

**Comment by wupaz** [comment] 2021-07-22 15:06
Latest version 1.13.0 didn't work (Same error)

**Comment by mxschmitt** [comment] 2021-07-22 21:00
Could you try it via the latest development version? `npm install -D @playwright/test@next`. We might get a better reporting out of that to find out if it's Jest or not.

**Comment by wupaz** [comment] 2021-07-23 00:43
I try ... result is same ...

NPM Install log 
```
2021-07-23T00:22:33.8874147Z ##[debug]C:\windows\system32\cmd.exe /c "npm i"
2021-07-23T00:22:33.8875295Z ##[command]npm i
2021-07-23T00:25:25.5528060Z 
2021-07-23T00:25:25.5529050Z > @playwright/test@1.14.0-next-alpha-jul-22-2021 install C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e\node_modules\@playwright\test
2021-07-23T00:25:25.5529727Z > node install.js
2021-07-23T00:25:25.5529897Z 
2021-07-23T00:25:25.6594748Z 
2021-07-23T00:25:25.6596462Z > playwright@1.13.0 install C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e\node_modules\playwright
2021-07-23T00:25:25.6597390Z > node install.js
```

Test run Task result log
```
2021-07-23T00:25:37.0088710Z ##[command]npm run test
2021-07-23T00:25:37.9016537Z 
2021-07-23T00:25:37.9100141Z > gustav@1.0.0 test C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e
2021-07-23T00:25:37.9120322Z > npx playwright test
2021-07-23T00:25:37.9140729Z 
2021-07-23T00:25:39.8566197Z Error: describe() can only be called in a test file
2021-07-23T00:25:39.8567759Z     at TestTypeImpl._describe (C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e\node_modules\@playwright\test\lib\test\testType.js:83:23)
2021-07-23T00:25:39.8569381Z     at Function.describe (C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e\node_modules\@playwright\test\lib\test\transform.js:133:12)
2021-07-23T00:25:39.8571079Z     at Object.<anonymous> (C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e\e2e\playwright\use-case\add-new-patient.uctest.spec.ts:25:12)
2021-07-23T00:25:39.8572253Z     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2021-07-23T00:25:39.8573315Z     at Module._compile (C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\Test_e2e\node_modules\pirates\lib\index.js:99:24)
2021-07-23T00:25:39.8575130Z     at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2021-07-23T00:25:39.8576280Z     at Object.newLoader (C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\Test_e2e\node_modules\pirates\lib\index.js:104:7)
2021-07-23T00:25:39.8577451Z     at Module.load (internal/modules/cjs/loader.js:950:32)
2021-07-23T00:25:39.8578408Z     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
2021-07-23T00:25:39.8579245Z     at Module.require (internal/modules/cjs/loader.js:974:19)
2021-07-23T00:25:39.8580061Z     at require (internal/modules/cjs/helpers.js:92:18)
2021-07-23T00:25:39.8584330Z     at Loader._requireOrImport (C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\Test_e2e\node_modules\@playwright\test\lib\test\loader.js:211:18)
2021-07-23T00:25:39.8586159Z     at Loader.loadTestFile (C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\Test_e2e\node_modules\@playwright\test\lib\test\loader.js:130:18)
2021-07-23T00:25:39.8588036Z     at Runner._run (C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\Test_e2e\node_modules\@playwright\test\lib\test\runner.js:210:59)
2021-07-23T00:25:39.9869186Z npm ERR! code ELIFECYCLE
```

**Comment by wupaz** [comment] 2021-07-23 02:24
I don't know If this could help you, I try to use NPM Task instead of CMD Task in Pipeline/Release. And I got this 

```
2021-07-23T01:04:15.7662513Z 8 verbose lifecycle gustav@1.0.0~test: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e\node_modules\.bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Microsoft Network Monitor 3\;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Azure Data Studio\bin;C:\Program Files\nodejs\;C:\Program Files\PowerShell\7\;C:\windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;
2021-07-23T01:04:15.7665922Z 9 verbose lifecycle gustav@1.0.0~test: CWD: C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e
2021-07-23T01:04:15.7666736Z 10 silly lifecycle gustav@1.0.0~test: Args: [ '/d /s /c', 'npx playwright test' ]
2021-07-23T01:04:15.7667513Z 11 silly lifecycle gustav@1.0.0~test: Returned: code: 1  signal: null
2021-07-23T01:04:15.7668213Z 12 info lifecycle gustav@1.0.0~test: Failed to exec test script
2021-07-23T01:04:15.7668954Z 13 verbose stack Error: gustav@1.0.0 test: `npx playwright test`
2021-07-23T01:04:15.7669473Z 13 verbose stack Exit status 1
2021-07-23T01:04:15.7670216Z 13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
2021-07-23T01:04:15.7671072Z 13 verbose stack     at EventEmitter.emit (events.js:375:28)
2021-07-23T01:04:15.7671902Z 13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
2021-07-23T01:04:15.7672763Z 13 verbose stack     at ChildProcess.emit (events.js:375:28)
2021-07-23T01:04:15.7673416Z 13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
2021-07-23T01:04:15.7674073Z 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
2021-07-23T01:04:15.7675142Z 14 verbose pkgid gustav@1.0.0
2021-07-23T01:04:15.7675899Z 15 verbose cwd C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e
2021-07-23T01:04:15.7676537Z 16 verbose Windows_NT 10.0.17763
2021-07-23T01:04:15.7677366Z 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
2021-07-23T01:04:15.7678281Z 18 verbose node v14.17.3
2021-07-23T01:04:15.7678931Z 19 verbose npm  v6.14.13
2021-07-23T01:04:15.7679437Z 20 error code ELIFECYCLE
2021-07-23T01:04:15.7679778Z 21 error errno 1
2021-07-23T01:04:15.7680252Z 22 error gustav@1.0.0 test: `npx playwright test`
2021-07-23T01:04:15.7680716Z 22 error Exit status 1
```

**Comment by wupaz** [comment] 2021-07-23 14:46
Sorry for all dump of information :) ... I try to setup a quick and completely fresh server nothing than windows and basic app like chrome vscode etc ... and I got same error ...

I willing to try anything (beta/fork package) to diagnostic this error... thanks for your helps.

Anyones try to run test with Pipeline/release ?

```
2021-07-23T14:38:31.5245625Z ##[debug]C:\Windows\system32\cmd.exe /c "npm run test"
2021-07-23T14:38:31.5246029Z ##[command]npm run test
2021-07-23T14:38:32.4037786Z 
2021-07-23T14:38:32.4038762Z > gustav@1.0.0 test
2021-07-23T14:38:32.4039177Z > npx playwright test
2021-07-23T14:38:32.4039449Z 
2021-07-23T14:38:35.6209217Z Error: describe() can only be called in a test file
2021-07-23T14:38:35.6230413Z     at TestTypeImpl._describe (C:\azagent\A2\_work\r1\a\GMaster\DevDrop\test_e2e\node_modules\@playwright\test\lib\test\testType.js:83:23)
2021-07-23T14:38:35.6408988Z     at Function.describe (C:\azagent\A2\_work\r1\a\GMaster\DevDrop\test_e2e\node_modules\@playwright\test\lib\test\transform.js:133:12)
2021-07-23T14:38:35.6436081Z     at Object.<anonymous> (C:\azagent\A2\_work\r1\a\GMaster\DevDrop\test_e2e\e2e\playwright\use-case\add-new-patient.uctest.spec.ts:25:12)
2021-07-23T14:38:35.6466288Z     at Module._compile (node:internal/modules/cjs/loader:1095:14)
2021-07-23T14:38:35.6498002Z     at Module._compile (C:\azagent\A2\_work\r1\a\GMaster\DevDrop\Test_e2e\node_modules\pirates\lib\index.js:99:24)
2021-07-23T14:38:35.6501108Z     at Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
2021-07-23T14:38:35.6502885Z     at Object.newLoader (C:\azagent\A2\_work\r1\a\GMaster\DevDrop\Test_e2e\node_modules\pirates\lib\index.js:104:7)
2021-07-23T14:38:35.6507350Z     at Module.load (node:internal/modules/cjs/loader:975:32)
2021-07-23T14:38:35.6520838Z     at Function.Module._load (node:internal/modules/cjs/loader:816:12)
2021-07-23T14:38:35.6524501Z     at Module.require (node:internal/modules/cjs/loader:999:19)
2021-07-23T14:38:35.6537547Z     at require (node:internal/modules/cjs/helpers:93:18)
2021-07-23T14:38:35.6539045Z     at Loader._requireOrImport (C:\azagent\A2\_work\r1\a\GMaster\DevDrop\Test_e2e\node_modules\@playwright\test\lib\test\loader.js:211:18)
2021-07-23T14:38:35.6595489Z     at Loader.loadTestFile (C:\azagent\A2\_work\r1\a\GMaster\DevDrop\Test_e2e\node_modules\@playwright\test\lib\test\loader.js:130:18)
2021-07-23T14:38:35.6597546Z     at Runner._run (C:\azagent\A2\_work\r1\a\GMaster\DevDrop\Test_e2e\node_modules\@playwright\test\lib\test\runner.js:210:59)
2021-07-23T14:38:35.7065135Z ##[error]Process completed with exit code 1.
```

**Comment by ychaudhari** [comment] 2021-07-26 19:47
I am getting this error on my machine on this https://github.com/ychaudhari/playwright-runner-issue almost empty project (no jest involved) 

```
λ npm t                                                                                                           
> playwright-runner-test@1.0.0 test                                                                               
> playwright test                                                                                                 
Using config at C:\Users\ychaudhari\code\playwright-runner-test\playwright.config.ts                              
Error: describe() can only be called in a test file    
```

**Comment by ychaudhari** [comment] 2021-07-27 02:40
If it helps anyone, my issue was somehow related to the terminal I was using (Cmder)... Tests worked fine without any error using powershell, git bash or cmd.
Could not pinpoint the issue with Cmder (or the specific environment setup in Cmder) but was able to work with other terminals and updated Cmder version.

**Comment by wupaz** [comment] 2021-07-27 14:35
OMG Thanks @ychaudhari I try run "npm run test" with "Powershell" task instead of "Command Line" Task and now test work in Pipeline/Release ...... 

Really Command line task and/or Playwright/Test have a bug

**Comment by jharte-srcinc** [comment] 2021-07-28 18:34
> OMG Thanks @ychaudhari I try run "npm run test" with "Powershell" task instead of "Command Line" Task and now test work in Pipeline/Release ......
> 
> Really Command line task and/or Playwright/Test have a bug

I have the opposite problem:

Running "npx Playwright test" in Powershell results in "Error: test() can only be called in a test file"
Doing the same from command prompt works fine.

FYI, I 'm new to Playwright.  Just following the instructions here: https://playwright.dev/docs/intro (First Test section)

**Comment by mxschmitt** [comment] 2021-07-30 11:41
I will close it for now since the original issue seems solved or at least there is a workaround (by using a different shell).

For future users who face the issue, please create an issue with reproducible steps, because so far we were not able to reproduce it. This means:
OS/OS version/env vars of the shell/package.json (playwright related stuff, if there is Jest or mocha included) etc.

**Closed by mxschmitt** 2021-07-30 11:41 UTC
Labels: triaging
