### ISSUE TITLE
[Question] Waiting for page stabilization for visual regression

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#29071] opened 2024-01-19 19:26 UTC
So right now im using Playwright for visual regression and overall it's working well to check reports that basically consist of a lot of graphs/charts/etc..., im mocking and intercepting and a response to use the same data each time.

This seems to work ok for smaller reports but larger reports that take time to load I get very small pixel differences (like `.02` percent pixels typically). My guess is this happens do to the page adjusting as the final parts get loaded (CSS/chart libraries/etc...)

Right now im doing a waitforUrl and a waitFor on a specific element that is typically slow loading. Right now the waitForUrl is using the default "load" option.....but is there a better way to wait for "everything" to finish loading.

I know "networkidle" is considered not ideal to use.....but is it maybe a good idea here? Right now im just adding an extra hard `waitForTimeout` which is not preferred.

Curious what strategies are good for this.

**Comment by mxschmitt** [comment] 2024-01-19 21:57
networkidle is strongly discouraged, since it looks only at your network and the rendering issues seem most likely unrelated.

The strategy highly depends on the scenario - can you share a reproduction with us? This would help a ton in order to find a good waiting strategy for you!

**Comment by uchagani** [comment] 2024-01-21 14:27
my understanding is that networkIdle will return if there are no network requests for 500ms.  so if you have a request that is kicked off after that and loads something new then it won't work.  

waiting for certain elements is probably the most reliable.  another option is waiting for certain network requests to finish if there is a certain request that is causing slowness.

**Comment by msmith1114** [comment] 2024-01-22 03:43
Right now I don't think the issue is necessarily related to requests. I actually wait for the last request to fire so I *think* this may have to do with the charting library animations perhaps?

Unfortunately I can't share the specific report. But I can say scriptwise I am waiting for the last request and also waiting for "load" on the page itself.

Is there some way in chrome dev tools to see maybe animations or whatever the last  "animation" or "element" is?

**Comment by mxschmitt** [comment] 2024-01-23 11:39
> to fire so I think this may have to do with the charting library animations perhaps?

This sounds very plausible, if the charting library renders asynchronously, this would make a lot of sense. Maybe they have a "rendering done" hook?

> Is there some way in chrome dev tools to see maybe animations or whatever the last "animation" or "element" is?

This is unfortunately not a thing in the web-world. Closing for now then, since this is not actionable and its not about a specific bug / feature. Thanks for your understanding.

**Closed by mxschmitt** 2024-01-23 11:39 UTC
