### ISSUE TITLE
[Bug]: `Locator.click` & `Locator.focus` misbehaviour

### ISSUE THREAD

**Issue by dhsh-checkmk** [microsoft/playwright#31663] opened 2024-07-09 14:54 UTC
### Version

1.44

### Steps to reproduce

Please clone the repository [here](https://github.com/dhsh-checkmk/debug-playwright-focus), 
and follow the instructions mentioned within the `README` file. 

You would require a docker.io installation for setting up a debug environment.

Please reach out to me if there are any further queries.

### Expected behavior

* [Expected behavior-1](https://github.com/dhsh-checkmk/debug-playwright-focus/blob/10b78d7d3aab39e3311566654618ebbef492b7c5/test_debug.py#L66)
*  [Expected behavior-2](https://github.com/dhsh-checkmk/debug-playwright-focus/blob/10b78d7d3aab39e3311566654618ebbef492b7c5/test_debug.py#L69) 

### Actual behavior

* [Actual-behaviour-1](https://github.com/dhsh-checkmk/debug-playwright-focus/blob/10b78d7d3aab39e3311566654618ebbef492b7c5/test_debug.py#L67)
*  [Actual-behaviour-2](https://github.com/dhsh-checkmk/debug-playwright-focus/blob/10b78d7d3aab39e3311566654618ebbef492b7c5/test_debug.py#L70) 

### Additional context

This issue is reproduces an earlier [bug](https://github.com/microsoft/playwright-python/issues/2481).

### Environment

```Text
- Operating System: [Ubuntu 22.04]
- CPU: [amd64]
- Browser: [Chromium]
- Python Version: [3.12]
```

**Comment by yury-s** [comment] 2024-07-12 16:32
Please extract relevant parts of the web app, so that we can just run a simple self-contained test (without downloading and running third-party docker containers, fiddling with passwords etc). There might a bug in playwright or just bug in the app and the test, unfortunately we don't have resources to study a new big code base such as checkmk. Please provide a minimal reproduction.

**Comment by dhsh-checkmk** [comment] 2024-07-15 13:11
```
unfortunately we don't have resources to study a new big code base such as checkmk. Please provide a minimal reproduction.
```
I understand your concern. This is the `simplest`, if not minimal, reproduction from my side.

Some more context,
We are testing Checkmk GUI on our side continuously and this is the only case where test flakiness occurs.
My suspicion is that something related to [intersection observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) is leading to the misbehavior.

I would really appreciate it if you could spend some time-boxed effort here with the present reproduction resources.

In the meantime, I'll approach the dev teams and ask for a `minimal` reproduction. This will take time though and thus, my request for time-boxed effort.

**Comment by dgozman** [comment] 2024-07-16 12:21
@dhsh-checkmk Unfortunately, we won't be able to reproduce this due to the complexity of the repro.

However, I have some suspects from reading your test.

First of all, `focus` is not meant to scroll the page ever. It just focuses the element.

Also, `click` does not scroll the page as long as some clickable part of the target element is visible. In your case, it seems like the element is partially visible, and so Playwright clicks in the center of the visible part of the element. Perhaps, clicking there does not trigger the navigation as you'd expect?

I suspect there is an element **inside** the target that must be clicked for the navigation to happen, and Playwright clicks at the different part of the target thus not clicking the inner element. That's just an idea though.

Note that you can use `locator.scrollIntoViewIfNeeded()` to manually scroll the whole element into view. Let us know whether that helps.

**Comment by dgozman** [comment] 2024-07-17 15:26
> I'll focus on getting a `minimal` setup as soon as possible 🤞.

Looking forward to it!

> Although, I have observed [this](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#:~:text=By%20default%20the%20browser%20will%20scroll%20the%20element%20into%20view%20after%20focusing%20it) behavior when I have used `Locator.focus` .
> I always assumed `Locator.focus` wraps `HTMLElement.focus`, is this assumption wrong?

You are right, I didn't think of the built-in browser behavior. It does scroll the element into view in many cases.

**Comment by pavelfeldman** [comment] 2024-07-22 23:11
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Closed by pavelfeldman** 2024-07-22 23:11 UTC
