### ISSUE TITLE
[BUG] Playwright does not honor updated payload to a post request when using page.route

### ISSUE THREAD

**Issue by sfc-gh-pshah** [microsoft/playwright#27558] opened 2023-10-12 06:16 UTC
### System info
- Playwright Version: v1.38.1
- Operating System: macOD
- Browser: Chromium
- Other info:
**Steps**
```
await page.route('*/**/query?desc=show-mybases', async (route, request) => {
      const headers = {
        ...request.headers(),
        'X-test-Request-Id': '751562fe-89f1-4b78-9fd4-984b6d292b62',
      };

      const postData = { ...request.postDataJSON() };
      postData['requestId'] = '751562fe-89f1-4b78-9fd4-984b6d292b62';
      console.log('POSTDATA: ', postData);
      route.continue({ headers, postData });
    });

    await goToUrl(page, 'http://someurl.com/bases');
```

**Expected**
I would expect the request payload and headers to have the requestId passed in page.route

**Actual**
Only the request header has the hardcoded requestId, the payload has the new requestId generated by the application code (not the hardcoded one).

When I console.log the modified JSON, I do see the correct JSON being formed. Not sure what could wrong here. Appreciate any help. thank you

**Comment by dgozman** [comment] 2023-10-12 15:52
@sfc-gh-pshah According to [our tests](https://github.com/microsoft/playwright/blob/main/tests/page/page-request-continue.spec.ts#L164-L269), updating post data works. I've just tried it again with a snippet similar to yours, and it seems to work as expected.

Could you please share the full reproducible with us that we can run locally? How do you check that payload has the old requestId?

**Comment by sfc-gh-pshah** [comment] 2023-10-12 16:25
`myfixture.ts`
```
const test = base.extend<Pages>({
  myFixture: async ({ page }, use) => {
    await page.route('*/**/query?desc=show-mybases', async (route, request) => {
      const headers = {
        ...request.headers(),
        'X-test-Request-Id': '751562fe-89f1-4b78-9fd4-984b6d292b62',
      };

      const postData = { ...request.postDataJSON() };
      postData['requestId'] = '751562fe-89f1-4b78-9fd4-984b6d292b62';
      console.log('POSTDATA: ', postData);
      route.continue({ headers, postData });
    });

    await goToUrl(page, 'http://someurl.com/bases');
    await use(new someObject(page));
  },
});


demotest.spec.ts
test('Mocking post call', async ({ page, myFixture }) => {
  // make an assertion
});

I run the test with PWDEBUG=1 and once the browswer opens, I bring up the chrome dev tools and check the network tab. It is here where I see the api call having the hard-coded headers, but click on payload in the network displays the new requestId

Does this help? Thank you

**Comment by sfc-gh-pshah** [comment] 2023-10-12 18:15
hmm. So is this behavior different for post headers i.e. I see the updated post headers in the chrome tools, just not the post data.

**Comment by dgozman** [comment] 2023-10-12 18:29
> So is this behavior different for post headers i.e. I see the updated post headers in the chrome tools, just not the post data.

Yes, this is due to the implementation details of the Chrome DevTools Protocol.

**Comment by dgozman** [comment] 2023-10-15 14:50
Closing as per above. If you still encounter problems, please file a new issue with a repro and link to this one.

**Closed by dgozman** 2023-10-15 14:50 UTC
Labels: triaging

**Comment by sfc-gh-pshah** [comment] 2023-10-16 15:50
Will do. Thank you for the help.
