### ISSUE TITLE
[Bug]: CSS import throws SyntaxError

### ISSUE THREAD

**Issue by Thomas-Haider** [microsoft/playwright#31954] opened 2024-08-01 11:26 UTC
### Version

1.45.3

### Steps to reproduce

I created a small example where the issue can be reproduced.

1. download and unzip file
2. run `npm install` and `npx playwright install --with-deps`
3. run `npx playwright test example.spec.ts`

[demo-pw-css-error.zip](https://github.com/user-attachments/files/16455356/demo-pw-css-error.zip)

### Expected behavior

I would expect to have this import ignored as it does not add any value to the test itself and in my case we only stumpled on this error as we are reading some metadata from a app.config.ts file which includes and import to a file where an css file is imported.

### Actual behavior

throws the following error:

```typescript
SyntaxError: Unexpected token '.'

   at ../src/index.ts:1

> 1 | export const style = require('./style.css');
    |                      ^

    at Object.<anonymous> (/Users/thomas.haider/workspaces/projects/other/demo-pw/src/index.ts:1:22)
    at Object.<anonymous> (/Users/thomas.haider/workspaces/projects/other/demo-pw/app.config.ts:1:1)
    at Object.<anonymous> (/Users/thomas.haider/workspaces/projects/other/demo-pw/tests/example.spec.ts:3:16)
Error: No tests found.
```

### Additional context

Basically, our usecase is that we want to access some variables of a config file that teams have in their repo and there we found that some teams have imports to components libraries in their that contain .css imports which causes this error to be thrown. So ignoring such kind of imports would be sufficient for us. :) 

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Max
    Memory: 5.85 GB / 64.00 GB
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.1/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.1.1 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.45.3 => 1.45.3
```

**Comment by mxschmitt** [comment] 2024-08-01 13:01
Looks like working as intended to me:

     example.spec.ts -> app.config -> index.ts -> style.css

If you manually create a `test.js` and put:

```
const config = require('../app.config');

console.log(config)
```

inside it, and convert the relevant `.ts` files into `.js` - then it behaves the same.

I recommend to re-structure the project, so that the config does not require the `.css` files. Or make the imports conditional.

**Comment by Thomas-Haider** [comment] 2024-08-01 14:44
in our use-case the css file is imported already in npm package, so it is already converted to js. So you are saying, if i convert the app.config.ts to js before running the tests, it would solve the problem?

Could you explain to me, why this is not working with ts as i don't understand why this is not working? why is there a need to transpile it when i just simply wanna import a variable from a config file.

**Comment by pravintargaryen** [comment] 2024-08-01 16:56
I could reproudce the error
![Untitled](https://github.com/user-attachments/assets/e73bfe53-8f0d-4b2b-85e6-e6e73b2a80c5)

**Comment by mxschmitt** [comment] 2024-08-01 17:59
> So you are saying, if i convert the app.config.ts to js before running the tests, it would solve the problem?

With "converting" I didn't mean to transpile. My point was more to show that with Playwright it behaves the same compared to a normal Node.js environment. Playwright does not transpile css as of today.

So from the Playwright this is working as expected. I think we do some best-effort, if you have `css` imports from TypeScript but not if you import them via JavaScript. Looking at https://github.com/microsoft/playwright/issues/24580. (We don't do it for JS, since we don't run Babel over JS files.)

The workarounds would be:

- Import your css from TS instead
- Restructure the project, so that the config does not depend on `.css` files.

Would importing it from TS work for you?

**Comment by Thomas-Haider** [comment] 2024-08-02 05:41
- sadly importing it from TS will not work, since the import in our case comes directly from a npm package, which means it is javascript. :(
- Resturing the config to not contain the property is sadly also no option in this case since this import is quite crucial.

So I guess the only thing we are left to do is either don't use that config to obtain that information or try to implement a way where we read the file content via fs and parse out what we need. do you have any other ideas that I could try?

**Comment by mxschmitt** [comment] 2024-08-02 06:31
Unfortunately yes, that seems one of the only ways to workaround it. Since we don't have plans to transpile JS files esp. in node_modules due to performance / it was working the last few years, I'll close it for now.

**Closed by mxschmitt** 2024-08-02 06:31 UTC
