### ISSUE TITLE
[BUG] Playwright Test for VSCode: Playwright Inspector keeps opening Google Homepage

### ISSUE THREAD

**Issue by hoangngocanhskedulo** [microsoft/playwright#17387] opened 2022-09-16 08:41 UTC
**Context:**
- Playwright Version: Latest
- Operating System: Mac
- Node.js version: Latest
- Browser: Chromnium
- Extra: Playwright Test for VSCode v0.2.10

**Describe the bug**

Whenever I start using Playwright Inspector, it keeps opening Google Search webpage after I close and open the window.

Video is attached.

https://user-images.githubusercontent.com/110459758/190595837-8d7311f2-5bdf-4feb-b119-5ecfc7158011.mov

Please have a look at it. Thanks!

**Comment by mxschmitt** [comment] 2022-09-16 09:12
Duplicate of https://github.com/microsoft/playwright/issues/9434

**Closed by mxschmitt** 2022-09-16 09:12 UTC
