### ISSUE TITLE
[BUG]: Playwright Trace Viewer throws error

### ISSUE THREAD

**Issue by parichay28** [microsoft/playwright#27110] opened 2023-09-15 06:33 UTC
### System info
- Playwright Version: [v1.38]
- Operating System: [All]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [x] Source code should not be needed for this case.

**Expected**

Uploading trace file generated via v1.31 should work with trace.playwright.dev

**Actual**

<img width="612" alt="image" src="https://github.com/microsoft/playwright/assets/43565572/e96a1634-7ab0-48e7-ab5e-ea982787f7b7">
<img width="606" alt="image" src="https://github.com/microsoft/playwright/assets/43565572/e972aa5e-d4ef-4e4c-a222-ce3cb3f5586c">

This works fine till version 1.37.1. Verified via `npx playwright@1.37 show-trace trace.zip`

**Comment by mxschmitt** [comment] 2023-09-15 09:43
Looks like a duplicate of https://github.com/microsoft/playwright/issues/27072, should be fixed in https://trace.playwright.dev/next

**Closed** 2023-09-15 10:14 UTC
