### ISSUE TITLE
[BUG] Timeout issue when using Mount

### ISSUE THREAD

**Issue by maylortaylor** [microsoft/playwright#27961] opened 2023-11-03 16:36 UTC
### System info
- Playwright Version: v1.39.0
- Operating System: macOS 13.2
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

**Config file**

```js
// playwright-ct.config.ts
import { defineConfig, devices } from '@playwright/experimental-ct-react';

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  testDir: './tests',
	testMatch: '**/?(*.)+(spec|test).[tj]s?(x)',
  /* The base directory, relative to the config file, for snapshot files created with toMatchSnapshot and toHaveScreenshot. */
  snapshotDir: './__snapshots__',
  /* Maximum time one test can run for. */
  timeout: 10 * 1000,
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
	reporter: [
				[`html`, {
					outputFolder: 'html-report',
					// open: 'never'
				}],
	],
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',

    /* Port to use for Playwright component endpoint. */
    ctPort: 3109,
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],
});
```

**Test file (self-contained)**

```js
// shouldWork.spec.tsx
import { expect, test } from '@playwright/experimental-ct-react';
import React from 'react';

const MyComponent: React.FC<{name: string}> = ({name}) => <div>Hello {name}</div>;

test.describe('@Smoke MessagesUtilityListPage', () => {
	test('should work', async ({ mount }) => {
		const component = await mount(<MyComponent name="World" />);
		// the component should mount
		await expect(1).toBe(1);
	});
```

**Steps**
- run `npm run test-ct` script which calls `cross-env NODE_ENV=development npx playwright test -c ./playwright-ct.config.ts --grep @Smoke`
- 

**Expected**

The tests should mount my React component and then run the tests.

**Actual**

After running the `npm run test-ct` script, I get the following printout in my console
```
{"level":"info","message":"Test Case Started : should work"}
{"level":"info","message":"Test Case Started : should work"}
{"level":"info","message":"Test Case Started : should work"}
{"level":"info","message":"Test Case Completed : should work Status : timedOut"}
{"level":"info","message":"Test Case Completed : should work Status : timedOut"}
{"level":"info","message":"Test Case Completed : should work Status : timedOut"}
```

In the HTML view for playwright, I get a **Test Timeout of 10000ms exceeded**
with this error `    at mount (/Users/matttaylor/Documents/_dev/amver-ui/node_modules/@playwright/experimental-ct-core/lib/mount.js:49:35)`
<img width="1043" alt="image" src="https://github.com/microsoft/playwright/assets/7232060/e15387af-929d-4d07-81c5-167323299ebe">

**Comment by maylortaylor** [comment] 2023-11-03 19:49
I added the `--trace on` param to the test script to get better info and I got this error message in the trace view
`Cannot read properties of undefined (reading 'ReactCurrentDispatcher')`

**Comment by pavelfeldman** [comment] 2023-11-03 20:56
Did you create playwright folder with index.html / index.js? Please share a complete repro so that we could act on it.

**Comment by maylortaylor** [comment] 2023-11-03 21:12
> Did you create playwright folder with index.html / index.js? Please share a complete repro so that we could act on it.

Yes I have a `<root>/playwright` folder with `index.html` and a `index.tsx` inside the folder.
this is a company's repo, so I cant share that one but I will make a repo i can share soon.

**Comment by maylortaylor** [comment] 2023-11-03 21:28
> Did you create playwright folder with index.html / index.js? Please share a complete repro so that we could act on it.

okay here is a github repo where I am encountering this issue.
https://github.com/maylortaylor/playwright-issue

It happens when i run my `npm test` script..which is looking for tests inside the `./tests` folder

**Comment by pavelfeldman** [comment] 2023-11-06 01:07
> https://github.com/maylortaylor/playwright-issue

Your project looks too big for us to look at:

`Receiving objects:   1% (734/67730), 59.73 MiB`

We can't troubleshoot large projects, if you think there is a bug with Playwright, please share a self-contained project with a couple of files that we can try locally.

**Comment by maylortaylor** [comment] 2023-11-06 15:29
> > https://github.com/maylortaylor/playwright-issue
> 
> Your project looks too big for us to look at:
> 
> `Receiving objects: 1% (734/67730), 59.73 MiB`
> 
> We can't troubleshoot large projects, if you think there is a bug with Playwright, please share a self-contained project with a couple of files that we can try locally.

Okay i removed a lot of code/deadweight from that repo. So hopefully you can get the repo downloaded now.

**Comment by pavelfeldman** [comment] 2023-11-06 16:26
It is still hundreds of megabytes, could we get something aroung 10K? :shrug:

**Comment by dgozman** [comment] 2023-11-08 22:13
@maylortaylor Thank you for the repro. Unfortunately, I was not able to reproduce the timeout issue.

However, I see the following line in the test file:
```ts
const MyComponent: React.FC<{name: string}> = ({name}) => <div>Hello {name}</div>;
```

This is not supported. Playwright can only mount components that are defined in source files, not in test files. We recommend [creating "test stories"](https://playwright.dev/docs/test-components#test-stories) for this case. Let me know whether this helps.

**Comment by mxschmitt** [comment] 2023-11-15 19:56
Closing as per above, please re-file for further questions!

**Closed by mxschmitt** 2023-11-15 19:56 UTC
Labels: triaging
