### ISSUE TITLE
[BUG] M1 chip While running Visual regression tests on webkit, the page crashes and it wont take any screenshots

### ISSUE THREAD

**Issue by PascalvdHoek** [microsoft/playwright#13871] opened 2022-05-02 11:17 UTC
**Context:**
- Playwright Version: v1.2*.*
- Operating System: MacOs M1
- Node.js version: [e.g. 12.22, 14.6]
- Browser: WebKit
- Extra: docker image [mcr.microsoft.com/playwright:v1.21.1-focal](http://mcr.microsoft.com/playwright:v1.21.1-focal)

**Code Snippet**

```javascript
	test(`testing long label`, async ({ page }) => {
		await page.goto(
			`/iframe.html?id=forms-components-labels--label&args=labelText:hele%20hele%20hele%20hele%20lange%20label%20text%20voor%20het%20testen%20van%20de%20elipsis&viewMode=story`,
		);
		await page.addStyleTag({
			content: `*,
			  *::before,
			  *::after {
			  -moz-animation: none !important;
			  -moz-transition: none !important;
			  animation: none !important;
			  caret-color: transparent !important;
			  transition: none !important;
			  }`,
		});
		await page.waitForTimeout(1000);
		expect(await page.screenshot({ fullPage: true })).toMatchSnapshot(
			`long-labels.png`,
		);
	});
```

**Describe the bug**
When trying to run VR tests on webkit devices inside the docker container, the page crashes and it wont take any screenshot. It looks like this issue only occurs on my Macbook m1 chip. My other colleagues dont have any issues (who uses a older intel macbook). In earlier versions of playwright, v1.19.0 and lower, i never had this issue. It looks like the docker image, or webkit version isnt compatible with arm processor of the m1 macbook

Maybe someone can help me?

Related: 
https://github.com/microsoft/playwright/issues/13722  Closed issue of mine before (I dont know why it was closed) 
https://github.com/microsoft/playwright/issues/13868 Look simular

**Comment by dgozman** [comment] 2022-05-03 13:31
@PascalvdHoek How do you know that page crashes? Do you get any errors? Could you paste the errors here? Could you please provide a repro we can run locally? At minimum, we need the `baseURL`. Without any details, we cannot help you with the issue.

**Comment by pascal2310** [comment] 2022-05-03 18:14
![image](https://user-images.githubusercontent.com/17830564/166516432-029f82fc-2acc-48e3-ae3f-e013815968e0.png)
This is the error I get when trying to take screenshots on webkit. The repo is private unfortunately, I will try to get a reproducable repo for you tomorrow.

**Comment by PascalvdHoek** [comment] 2022-05-04 10:33
https://github.com/PascalvdHoek/angular-playwright-bug 
And here is a repo to reproduce it

**Comment by aslushnikov** [comment] 2022-05-17 09:25
I can repro this as well; a few hours of investigation didn't reveal what's going on. Will look further a little later.

**Comment by PascalvdHoek** [comment] 2022-06-02 13:00
@dgozman @aslushnikov any updates on this issue?

**Comment by aslushnikov** [comment] 2022-06-06 22:20
Looks like a dupe of https://github.com/microsoft/playwright/issues/14236 - merging in there.

**Closed by aslushnikov** 2022-06-06 22:20 UTC
Labels: browser-webkit, v1.23
