### ISSUE TITLE
[BUG] page.on("response", ..) is not emitted when response from network is not 200 status code?

### ISSUE THREAD

**Issue by epicwhale** [microsoft/playwright#29170] opened 2024-01-25 13:16 UTC
### System info
- Playwright Version: [v1.40.0]
- Operating System: macOS
- Browser: [Chromium]

When I register to listen to all network responses (using code below), I do not seem to see responses whose status code is not 200, more specifically 429. Is this working as expected?

```page.on("response", lambda response: print("<<", response.status, response.url))```

For more context, the request is being made is using a `fetch(..)` javascript call within page.evaluate(). Should this affect the behavior?

When the response status is 200, I do not face this issue.

**Comment by yury-s** [comment] 2024-01-25 17:26
The `response` event should be emitted regardless of the status code. The only reason it may be missing is a network failure, in which case 'requestfailed' is emitted instead. Can you share a repro where this happens?

**Comment by epicwhale** [comment] 2024-01-26 11:23
@yury-s thanks for the pointers. I retried with requestfailed, and it does appear there. However in the Chrome console, it appears as a "429 Response". How do I get access to the response object from within requestfailed so that I can filter for status code?

```page.on("requestfailed", lambda request: print(request.url + " " + repr(request.failure)))```

Output:

```https://foo... 'net::ERR_FAILED'```

<img width="508" alt="image" src="https://github.com/microsoft/playwright/assets/670655/9b6c6501-d656-4425-a113-32cb728d284e">

I would imagine a 429 response is something I could filter on in the "response" event 


_ps - I am still struggling to isolate this code example from a complicated repo as of now, will keep trying if you still think it's helpful._

**Comment by yury-s** [comment] 2024-01-27 03:55
> @yury-s thanks for the pointers. I retried with requestfailed, and it does appear there. However in the Chrome console, it appears as a "429 Response". How do I get access to the response object from within requestfailed so that I can filter for status code?

Well, if there is 429 response, then you should see 'response' event with that status. It may happen that the connection is interrupted after the response headers were sent, in that case you'll see both response and requestfailed events, e.g.:

```js
import { expect, test } from '@playwright/test';
import http from 'http';

const PORT = 3000;
test.beforeAll(async ({ }) => {
  const server = http.createServer(async (req, res) => {
    if (req.url === '/echo') {
      res.writeHead(429, { 'Content-Type': 'text/plain' });
      res.write('429 Too Many Requests');
      res.uncork();
      req.socket.destroy();
    } else {
      res.writeHead(200, { 'Content-Type': 'text/plain' });
      res.end('Hello!');
    }
  });  
  server.listen(PORT, () => {
    console.log(`Server running at http://localhost:${PORT}/`);
  });
});

test('requestfailed on status 429', async ({ page }) => {

  await page.goto(`http://localhost:${PORT}`);
  page.on('requestfailed', request => {
    console.log('requestfailed', request.url());
  });
  page.on('response', request => {
    console.log('response', request.url());
  });
  const responsePromise = page.waitForResponse('**/echo');
  await page.evaluate(async () => {
    const response = await fetch('/echo');
    return await response.text();
  }).catch(e => {});
  const response = await responsePromise;
  expect(response.status()).toBe(429);
});
```
If the connection is closed before the response headers are sent, you may only see requestfailed and there is no response status:

```js
import { expect, test } from '@playwright/test';
import http from 'http';

const PORT = 3000;
test.beforeAll(async ({ }) => {
  const server = http.createServer(async (req, res) => {
    if (req.url === '/echo') {
      res.writeHead(429, { 'Content-Type': 'text/plain' });
      res.uncork();
      req.socket.destroy();
    } else {
      res.writeHead(200, { 'Content-Type': 'text/plain' });
      res.end('Hello!');
    }
  });  
  server.listen(PORT, () => {
    console.log(`Server running at http://localhost:${PORT}/`);
  });
});

test('requestfailed on status 429', async ({ page }) => {

  await page.goto(`http://localhost:${PORT}`);
  page.on('requestfailed', request => {
    console.log('requestfailed', request.url());
  });
  page.on('response', request => {
    console.log('response', request.url());
  });
  const responsePromise = page.waitForResponse('**/echo');
  await page.evaluate(async () => {
    const response = await fetch('/echo');
    return await response.text();
  }).catch(e => {});
  const response = await responsePromise;
  expect(response.status()).toBe(429);
});
```

DevTools network panel will show 429 only in the former case. If you have a counterexample, please provide a repro that we could run locally to investigate.

**Comment by epicwhale** [comment] 2024-01-27 11:57
@yury-s thank you again for the elaboration - I was able to investigate this further and I think I have a loose guess on what's causing it, and how to repro it. 

It looks like the requests which are failing for me (with any 4xx code), **are behaving differently as they are also a CORS request**. The origin domain and the domain that the page is doing a fetch too aren't the same. So what I notice is for failed requests via CORS, the response event is never triggered - even if it shows in chrome developer tools. 

Reference code example:

```python
from playwright.async_api import async_playwright

p = await async_playwright().start()
browser = await p.chromium.launch(headless=False, devtools=True)
page = await browser.new_page()

page.on("response", lambda response: print(f"Response received: {response.status} {response.url}"))
page.on("requestfailed", lambda request: print(f"Request failed: {request.url}"))

# await page.goto("http://httpstat.us") # SAME origin <--- this works
await page.goto("https://httpbin.io")  # DIFFERENT origin <--- this fails to trigger page.on response events

# Execute JavaScript fetch on the page
response_text = await page.evaluate("""async () => {
    try { 
        const response = await fetch("http://httpstat.us/429");
        return response.statusText;
    } catch (e) {
        return e.message;                               
    }
}""")

print(f"Fetch Response: {response_text}")
```

Is there a way to handle / detect this failure / scenario? As the fetch simply throws a TypeError and I can't access the response status anywhere. So I can't differentiate if the failure is a 403, 429 or 4xx... related stackoverflow on CORS + fetch(..) TypeError https://stackoverflow.com/questions/59439345/catch-javascript-fetch-failing-with-cloudflare-429-missing-cors-header

Any tips / pointers deeply appreciated! Thanks again.

**Comment by yury-s** [comment] 2024-01-29 21:05
> Reference code example:

In you example you try to make https request from http page and Chromium throws an error, which you can see in the console: "Refused to connect to 'http://httpstat.us/429' because it violates the document's Content Security Policy.". There is no request sent, so there is no event either.

```js
import { expect, test } from '@playwright/test';

test('requestfailed on status 429', async ({ page }) => {
  
  // await page.goto("http://httpstat.us") // SAME origin <--- this works
  await page.goto("https://httpbin.io");  // DIFFERENT origin <--- this fails to trigger page.on response events
  
  page.on("response", response => console.log(`Response received: ${response.status()} ${response.url()}`));
  page.on("requestfailed", request => console.log(`Request failed: ${request.url()}`));
  // Execute JavaScript fetch on the page

  console.log(await page.evaluate(async () => {
      try { 
          const response = await fetch("http://httpstat.us/429");
          return response.statusText;
      } catch (e) {
          return e.message;                               
      }
  }));
  await new Promise(resolve => setTimeout(resolve, 1000));
});
```

> Is there a way to handle / detect this failure / scenario? As the fetch simply throws a TypeError and I can't access the response status anywhere. 

There is no network event as the request is never sent. You can listen for console messages and see if there is corresponding error: `  page.on('console', msg => console.log(`PAGE LOG: ${msg.text()}`));`.

Closing this issue as at this point all appears to work as intended. If you still think there is a bug in playwright, please file a new issue and attach a repro that we could run locally.

**Closed by yury-s** 2024-01-29 21:05 UTC
