### ISSUE TITLE
[Question] Implementing BDD Style test cases using playwright test runner

### ISSUE THREAD

**Issue by harir5** [microsoft/playwright#17296] opened 2022-09-13 14:19 UTC
I wanted to understand if we could create BDD Style tests similar to the ones that we'd create using cucumber with the playwright test runner.  we use the test runner extensively in our playwright automation framework (Visual regression is an example).

Kindly advise.

**Comment by mxschmitt** [comment] 2022-09-13 14:27
Duplicate of https://github.com/microsoft/playwright/issues/11975.

**Closed by mxschmitt** 2022-09-13 14:27 UTC
