### ISSUE TITLE
[Bug]: Replaying from .har file always chooses first call to an API endpoint

### ISSUE THREAD

**Issue by rmetel** [microsoft/playwright#32272] opened 2024-08-22 14:23 UTC
### Version

1.46.0

### Steps to reproduce

1) Create an App that makes multiple calls to the same API-endpoint like e.g.
   a) GET /api/tasks/:id
   b) PUT /api/tasks/:id
   c) GET /api/tasks/:id   (by now the content of task is different)
 
2) Create a playwright test that records the API-Calls into a HAR-File
 
3) Reexecute the test now replaying from the previously recorded HAR-file, using the  following  code:
     `await page.routeFromHAR(fullpath, {
        url: urlFilter,
        notFound: "abort",
        update: false,
      })`

### Expected behavior

API-calls to the same endpoint should be executed sequentially returning potentially different payloads.

### Actual behavior

Only the payload of the first API call (a) is returned in both calls to `GET /api/tasks/:id` (a & c)

### Environment

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 16.35 GB / 31.71 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.92.2 - C:\Users\01000982\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
```

**Comment by Skn0tt** [comment] 2024-08-23 06:56
Hi, thanks for reporting! I can reproduce it on our end with this test:

```ts
// tests/library/har.spec.ts

it('consecutive GET requests should both be recorded', { annotation: { type: 'issue', description: 'https://github.com/microsoft/playwright/issues/32272' } }, async ({ browserName, browser, contextFactory, server }, testInfo) => {
  let task = 'buy milk';
  server.setRoute('/api/task', async (req, res) => {
    if (req.method === 'PUT')
      task = (await req.postBody).toString();

    res.setHeader('Content-Type', 'text/plain');
    res.end(task);
  });
  server.setRoute('/repro', async (req, res) => {
    res.setHeader('Content-Type', 'text/html');
    res.end(`
      <script type="module">
      await fetch("/api/task").then(r => r.text()).then(console.log);
      await fetch("/api/task", { method: 'PUT', body: 'buy bread' }).then(r => r.text()).then(console.log);
      await fetch("/api/task").then(r => r.text()).then(console.log);
      </script>
    `);
  });
  const { page, getLog } = await pageWithHar(contextFactory, testInfo);
  await page.goto(server.PREFIX + '/repro');
  const log = await getLog();

  const secondGet = log.entries[3];
  expect(secondGet.request.method).toBe('GET');
  expect(secondGet.request.url).toBe(server.PREFIX + '/api/task');
  expect(secondGet.response.content).toBe({ text: 'buy bread' });
});
```

**Comment by Skn0tt** [comment] 2024-08-23 10:15
Update: I was looking at the test wrong. Here's a fixed test that shows we're recording correctly:

```ts
it('consecutive GET requests should both be recorded', { annotation: { type: 'issue', description: 'https://github.com/microsoft/playwright/issues/32272' } }, async ({ browserName, browser, contextFactory, server }, testInfo) => {
  let task = 'buy milk';
  server.setRoute('/api/task', async (req, res) => {
    if (req.method === 'PUT')
      task = (await req.postBody).toString();

    res.setHeader('Content-Type', 'text/plain');
    res.end(task);
  });
  server.setRoute('/repro', async (req, res) => {
    res.setHeader('Content-Type', 'text/html');
    res.end(`
      <script type="module">
      await fetch("/api/task").then(r => r.text()).then(console.log);
      await fetch("/api/task", { method: 'PUT', body: 'buy bread' }).then(r => r.text()).then(console.log);
      await fetch("/api/task").then(r => r.text()).then(console.log);
      </script>
    `);
  });
  const { page, getLog } = await pageWithHar(contextFactory, testInfo);
  let requestsFinished = 0;

  await Promise.all([
    page.waitForEvent('requestfinished', e => ++requestsFinished === 3),
    page.goto(server.PREFIX + '/repro')
  ]);

  const log = await getLog();

  const secondGet = log.entries[3];
  expect(secondGet.request.method).toBe('GET');
  expect(secondGet.request.url).toBe(server.PREFIX + '/api/task');
  expect(secondGet.response.content.text).toEqual('buy bread');
});
```

The problem seems to be in replaying, as you found. There's another issue about this: https://github.com/microsoft/playwright/issues/18288

I'll close this issue as a duplicate.

**Closed by Skn0tt** 2024-08-23 10:15 UTC
Labels: v1.48

**Comment by rmetel** [comment] 2024-08-23 10:19
thank you for fast response @Skn0tt, we gonna watch #18288 then.
