### ISSUE TITLE
[Bug]: Overridden browser fixture does not work as expected

### ISSUE THREAD

**Issue by mdmundo** [microsoft/playwright#30726] opened 2024-05-09 11:39 UTC
### Version

1.44.0

### Steps to reproduce

- Download and unzip [browser-fixture-override-bug.zip](https://github.com/microsoft/playwright/files/15261602/browser-fixture-override-bug.zip)
- Run `yarn -E --no-lockfile`
- Run `yarn playwright install chromium`
- Run `yarn playwright test`

### Expected behavior

Both browser windows are kept opened until you close them

### Actual behavior

The one that is using the overridden browser fixture closes after ~30s

### Additional context

Both fixtures share the following code:

```js
const browser = await playwright.chromium.launch({ headless: false });
await use(browser);
await expect(() => {
  expect(
    browser
      .contexts()
      .every((context) => context.pages().every((page) => page.isClosed()))
  ).toBe(true);
}).toPass({ intervals: [2_000] });
```

`expect.toPass` should prevent the browser from closing after being used in test, but it does not work if you are using the overridden browser fixture.

### Environment

```shell
lstat
ENOENT: no such file or directory, lstat
This is related to npm not being able to find a file.
```

**Comment by dgozman** [comment] 2024-05-13 20:10
@mdmundo Thank you for the repro, illustrates the question nicely!

The difference between the two fixtures is that `browser` is a [worker-scoped fixture](https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures), while `chromium` is a test-scoped fixture.

So, when using the `browser` fixture:
- Test successfully finishes.
- Test-scoped fixtures are successfully teared down.
- Playwright initiates worker termination, which includes tearing down the `browser` fixture.
- Playwright ensures a 30 seconds maximum limit on the worker teardown, and kills the worker process after that. The browser is forcefully closed. Note there is a similar issue #30504 that advocates for a customizable timeout for worker fixture teardown.

When using the `chromium` fixture:
- Test successfully finishes.
- Teardown for test-scoped fixtures is initiated, which includes tearing down the `chromium` fixture.
- Since `chromium` never finishes, Playwright does not consider the test to be finished. Given that you set `timeout: 0` in the config, Playwright waits indefinitely for the test to finish.

Given the above, it seems like things work as intended. Let me know what you think.

**Comment by dgozman** [comment] 2024-05-14 17:47
@mdmundo Yep, this should work once #30504 is fixed. I'll close this issue, since there is no action item for Playwright. Thank you for filing!

**Closed by dgozman** 2024-05-14 17:47 UTC
Labels: v1.45
