### ISSUE TITLE
[Bug]: Credential scanning tool flags shipped private key

### ISSUE THREAD

**Issue by Samat-Imamov** [microsoft/playwright#32146] opened 2024-08-13 18:08 UTC
### Version

1.46.0

### Steps to reproduce

Have credential scanning tool in a pipeline.

### Expected behavior

No issues with credential scanning tool.

### Actual behavior

Credential scanning tool flags key.pem as a file that contains a private secret.

### Environment

```shell
N/A
```

**Comment by pavelfeldman** [comment] 2024-08-13 18:19
I believe this is about https://github.com/microsoft/playwright/tree/main/packages/playwright-core/bin/socks-certs and the credential scanning tool is checking for accidental certificates.

**Comment by pavelfeldman** [comment] 2024-08-13 18:21
Certificates are a part of the package by design. Those are self-signed certificates for internal needs, so they should not be considered a secret. Please feel free to add them to the allow-list.

Having said that we understand this is could be an inconvenience to the users that are not interested in the feature that these certificates enable, so we'll consider removing them and offering users to generate certificates during the build process should they need them.

**Comment by Samat-Imamov** [comment] 2024-08-13 18:27
Thank you for your answer! Since they are intended to be shipped, we can add them to the allow-list.

**Comment by mxschmitt** [comment] 2024-08-16 20:45
This should be fixed in v1.46.1 by https://github.com/microsoft/playwright/pull/32192.

**Closed by mxschmitt** 2024-08-16 20:45 UTC
Labels: v1.47
