### ISSUE TITLE
[BUG] UI sometimes loses actions log when test finishes

### ISSUE THREAD

**Issue by dmcweeney** [microsoft/playwright#26835] opened 2023-09-01 09:50 UTC
### System info
- Playwright Version: [v1.37.1]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

### Source code

**Expected**

Should not lose the logs!

**Actual**

Sometimes but regularly when I run a test in the UI (npx playwright test --ui --headed) and the test fails, the test actions log and metadata disappear. They will be there and visible while the test is running but as soon as the test is finished they disappear.

I have no consistent way of reproducing this but seems to be generally when an action times out.

**Comment by dgozman** [comment] 2023-09-12 02:22
We need more information to act on this issue. Could you please provide a repro that we can run locally?

**Comment by dgozman** [comment] 2023-09-14 14:38
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.

**Closed by dgozman** 2023-09-14 14:38 UTC
Labels: triaging

**Comment by esaucuevas** [comment] 2023-09-15 23:08
Playwright Version: [v1.37.1]
Node: v18.17.1
Operating System: Mac M1
Browser: [Chromium, Chrome]
command: npx playwright test --ui

Still experimenting with Playwright but I've been encountering the same issue periodically as well.
The Actions and Metadata information disappears when test is finished "running"

**Comment by dmcweeney** [comment] 2023-09-18 10:01
If I was to make a wild guess I think it happens when there are orphaned Chromium processes left running on the system!

**Comment by anton-johansson** [comment] 2024-04-07 11:42
FYI: I noticed a similar issue when upgrading from 1.42.0 to 1.43.0. I have three projects, one for setting up stuff (`setup`), one for authenticated tests (`authenticated`) and one for non-authenticated tests (`unauthenticated`).

In the UI, if I filter by projects "authenticated" and "unauthenticated" (which is kind of what I want anyway), the issue goes away. But as soon as I have "setup" selected or "all", the results reset when the tests finish.

Anyway, I won't be trying to create a repo to reproduce it, I can live with the workaround to just filter by the projects I'm interesting. It was more of an FYI for people having the same issue.
