### ISSUE TITLE
[Playwright BUG]: Worker process exited unexpectedly

### ISSUE THREAD

**Issue by saurabh4888** [microsoft/playwright#14355] opened 2022-05-23 17:39 UTC
**Context:**
Playwright Version: [1.22]
Operating System: [Windows]
Node.js version: [v12.18.3]
Browser: [ Chrome v101.0.4951.67]

**Code Snippet**
```js
for (let executeNo = 0; executeNo < 480; executeNo++) {
    let describeName = `iterate  on loopEach block_${executeNo}`

    test.describe(describeName, () => {

        test.beforeEach(async ({ page }) => {

            await page.goto(`http://${argv.testServer}:5555`, { timeout: 60000 });


        });


        test.afterEach(async ({ page }) => {
            await page.close();

        });


        test('iterate  on loopEach block', async ({ page }) => {

         //Action Performed ""


        });
    }
```
**Conf File Details**

```
use: {
browserName: "chromium",
headless: false,
viewport: { width: 1920, height: 1080 },
ignoreHTTPSErrors: true,
trace: 'retain-on-failure',
screenshot: 'only-on-failure',
channel: "chrome",
video: 'retain-on-failure',

},
```
**Describe the bug**
   On running one Testcase in Loop (i.e 480)as described above  ,it breaks in between i.e till  371 times loops the testcase works fine 
   but rest all Testcase get skipped with below error 
 **Worker process exited unexpectedly**
 
  Please help here in understanding why this issue happening

**Comment by yury-s** [comment] 2022-05-23 20:12
Currently if the worker crashes while running the tests in a file it will skip remaining tests in the file (looks like this behavior was introduced in https://github.com/microsoft/playwright/pull/12417) which seems to be a bug as we can run remaining tests in a new worker.

> ```js
> 
>         test.afterEach(async ({ page }) => {
>             await page.close();
> 
>         });
> ```

Note that you don't need this code, the `page` fixture will close it automatically.

**Closed** 2022-06-03 04:13 UTC
Labels: feature-test-runner, v1.23

**Comment by aakash3771** [comment] 2022-11-28 09:24
I am getting this error while I run two contexts same time.
Worker process exited unexpectedly (code=null, signal=SIGABRT)

**Comment by tuzz** [comment] 2023-01-06 21:37
I'm getting this error when running Safari inside the `mcr.microsoft.com/playwright:v1.28.1-focal` Docker container.

Once the project I'm working on is open sourced (probably in a couple of months) I can share a reproduction that will hopefully allow someone to track down the source of the problem.

**Comment by tuzz** [comment] 2023-01-06 22:14
Never mind, I upgraded to `mcr.microsoft.com/playwright:v1.29.2-jammy` and that fixed it.
