### ISSUE TITLE
Playwright: ele.screenshot() - takes a image with shake/blink

### ISSUE THREAD

**Issue by Aishwarya-UR** [microsoft/playwright#6920] opened 2021-06-05 10:43 UTC
Hello,

We are trying to migrate cases from Protractor to Playwright to achieve more stability of the regression suite. And while we have many canvas elements that plots data and that has to be compared against baseline images we maintain & except for drastic differences in plotting - we would want the actual image & baseline to match & pass the testcase - just like a user's action will be replicated.
But the below from playwright - takes an image but there is a shake in the screen -is there a way to avoid it please? 

```
const timeLog = await page.$$("canvas")
const actual = await timeLog[0].screenshot({path:'time-actual.png'})
```

We had the same shake happening via protractor also & images used to fail at every step. 
But sadly that's exactly one of the problem we are trying to over come with playwright? :(

**Comment by mxschmitt** [comment] 2021-06-07 10:53
A reproducible for that would be helpful because so far we can only guess the origin of the shaking.

Using `reducedMotion: 'reduce'` in the context-options might help which gets released with version 1.12. (or via the dev release channel available today: `npm install playwright@next`).

**Comment by Aishwarya-UR** [comment] 2021-06-14 16:35
@mxschmitt - Nope - setting this attribute in package.json - under context options still does not help;
![image](https://user-images.githubusercontent.com/55271275/121927323-88c18000-cd5c-11eb-96ed-ed543e5570b8.png)

When the image is captured with ele.screenshot() - there is a shake/blink of the whole screen.

**Comment by sergioariveros** [comment] 2021-08-04 00:39
Maybe helps -- Not sure if is the same error that @rwoll post on the slack channel, where @pavelfeldman said: It flickers to align the emulation to physical pixels while screenshotting. Ensure your deviceScaleFactor matches the one on your host and flicker will go away.

**Comment by aslushnikov** [comment] 2022-02-09 07:40
@Aishwarya-UR the shake itself should not affect the resulting screenshot. If it does though - that's a bug! We'll appreciate if you can file an issue with a repro that we can debug locally.

I'll close this for now since there's not much activity.

**Closed by aslushnikov** 2022-02-09 07:40 UTC
Labels: P3-collecting-feedback, feature-visual-regression-testing
