### ISSUE TITLE
[BUG] Failed worker - 1 error was not a part of any test

### ISSUE THREAD

**Issue by philt-symphony** [microsoft/playwright#21840] opened 2023-03-21 16:26 UTC
### System info
- Playwright Version: 1.31.2
- Operating System: Linux (Jenkins)
- Browser: Chromium
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
const config: PlaywrightTestConfig = {
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  timeout: 3 * 60 * 1000,
  use: {
    screenshot: 'only-on-failure',
    video: 'off',
    trace: 'off',
    ignoreHTTPSErrors: true,
  },
  projects: [
    {
      name: 'chrome',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
  ],
  reporter: [
    ['list'],
    ['json', { outputFile: 'integration-test-results.json' }],
    ['html', { open: 'never' }],
    ['./reporter/status-reporter.ts', { outputFile: 'status-report.json' }],
  ],
  testDir: './src/tests',
  webServer: {
    command: 'yarn run start',
    cwd: '../..',
    port: 9090,
    timeout: 5 * 60 * 1000,
    reuseExistingServer: true,
  },
};
```

**Test file (self-contained)**

- No test are failing

**Steps**
- [Run the test]
- [...]

**Expected**

We are running a test suite containing 200~ tests. All the tests are passing, so we are expecting the run as green

**Actual**

The test run is returning an error stopping our pipeline, there is no test failure.

```
216 passed (6.0m)
  1 error was not a part of any test, see above for details
```

I run using 'DEBUG=pw:browser' but nothing specific is reported (a part from certificate errors)

```
[30;1mpw:browser [0m<launching> /home/jenkins/.cache/ms-playwright/chromium-1048/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-3LdjwX --remote-debugging-pipe --no-startup-window [30m+0ms[0m
  [30;1mpw:browser [0m<launched> pid=808 [30m+6ms[0m
```

**Comment by aslushnikov** [comment] 2023-03-22 08:50
>  1 error was not a part of any test, see above for details

@philt-symphony The error itself should be shown somewhere during the test run. Can you find it & paste it here?

**Comment by philt-symphony** [comment] 2023-03-22 10:23
thanks @aslushnikov , I can only find this error for now:
`[31mFailed worker ran 52 tests, last 10 tests were:[39m`

**Comment by aslushnikov** [comment] 2023-03-24 18:50
So looks like the issue is fixed now! Closing then.

**Closed by aslushnikov** 2023-03-24 18:50 UTC
Labels: triaging

**Comment by ZurabKV** [comment] 2023-10-11 12:07
Also encountered such issue. In my case It was also related to missing await (before calling `expect(...).toBeChecked()`)

**Comment by vladfilip23** [comment] 2024-09-04 07:40
I start to get same issue playwright electron "@playwright/test": "^1.46.1"
Error: Cannot find parent object browser-context@8195fe0b002ddd9ab8a27c1c831b6d08 to create artifact@cefcfea080dff2df7578f38cb57d691f
[31mFailed worker ran 38 tests, last 10 tests were:[39m

**Comment by KaiWissel** [comment] 2024-12-05 12:43
Had the same error message, but the reason was a lil different. 

We had a waitForResponse defined at the start of a function. The actual trigger for the request was "at the end" of the function. So there where some actions in between. When an error occured between definition of the waitForResponse promise and the resolvement of that promise we where faced with same error message. Even if the retry of the same test was successful.

So the solution was to place the definition of the promise close to the resolvement of the same promise.

```
const waitForPromise = page.waitForResponse(/.*foo/)
action1()
// more actions
actionThatFails()  
triggerRequest() // Call that will trigger the network request which will resolve the promise
await waitForResponse
```

**Comment by denkorz** [comment] 2025-01-30 07:43
@aslushnikov 

Is there a workaround for this issue?
In my case it happened because of the following code from your documentation.

```
downloadPromise = page.waitForEvent('download');
await somePage.someBtn.click(); // button wasn't there
const download = await downloadPromise;
```
So the test was green on the rerun since the test depend on not super stable env, and it merked as flacky, but whole build is not green and has this error with worker, that is not a part of any test.

Should I use old approach with Promise.all to handle downloads for cases like this one?
