### ISSUE TITLE
[Question]: Screenshot is missing, when Authenticating in UI mode failed using fixtures

### ISSUE THREAD

**Issue by AlexeyCL** [microsoft/playwright#30959] opened 2024-05-22 12:24 UTC
### Context
I copied the [fixture](https://playwright.dev/docs/auth) for Authenticating from the docs, and I added a failing step. I see a missing screenshot in the HTML report
Also, I found this issue https://github.com/microsoft/playwright/issues/14544, but I think we need to find any way to display screenshots or video

### Version

latest

### Steps to reproduce

1. Clone my repo https://github.com/AlexeyCL/playwright.git
2. npm install
3. npx playwright test 

### Expected behavior

I should see screenshota 

### Actual behavior

 In HTML report screenshot and video are missing 

### Additional context

I found this issue https://github.com/microsoft/playwright/issues/14544, but I think we need to find any way to display screenshot or video

### Environment

```shell
System:
All
```

**Comment by AlexeyCL** [comment] 2024-05-22 12:50
btw `trace: 'retain-on-failure',` shows trace as required

**Comment by dgozman** [comment] 2024-07-15 15:14
Reopening because the fix was reverted.

**Comment by dgozman** [comment] 2024-07-18 12:14
Duplicate of #30287, merging together.

**Closed by dgozman** 2024-07-18 12:14 UTC
Labels: v1.46
