### ISSUE TITLE
[Bug]: Trace report doesn't show up on report - Inconsistent behaviour.

### ISSUE THREAD

**Issue by siddharth2023** [microsoft/playwright#32490] opened 2024-09-06 15:20 UTC
### Version

v1.47

### Steps to reproduce

Sometimes trace reports show up on playwright report and sometimes they don't. Can't reproduce them all the time. My project runs multiple windows at a time but even for simple specs like below, the availability of trace report is not consistent.

`test.spec.ts`

```
import { expect, test } from 'playwright/test';

test.describe.configure({ mode: 'serial' });
test.describe('Describe block', () => {
    test('Validate ', async ({ page }) => {
        await page.goto('https://www.duck.com');
        const title = await page.title();
        expect(title).toBe('hello');
    });
});
```

`playwright.config.ts`

```
 use: {
        /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
        actionTimeout: 40 * 1000,
        /* Base URL to use in actions like `await page.goto('/')`. */

        /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
        trace: 'on',
        video: 'on',
        headless: process.env.CI ? true : false,
        viewport: null,
    },
```

I should have seen a trace report link here.

<img width="413" alt="Screenshot 2024-09-06 at 11 12 34 AM" src="https://github.com/user-attachments/assets/18c67b29-146a-42b1-8693-0aae873e43cd">

### Expected behavior

See a link to trace report like this and the actual trace report at the bottom on opening the failed test for logs and analysis.

<img width="224" alt="Screenshot 2024-09-06 at 11 15 18 AM" src="https://github.com/user-attachments/assets/bc4f1d76-f03d-4765-bfdf-80b1193a8063">

### Actual behavior

I should have seen a trace report link here and the actual trace report at the bottom on opening the failed test.

<img width="413" alt="Screenshot 2024-09-06 at 11 12 34 AM" src="https://github.com/user-attachments/assets/18c67b29-146a-42b1-8693-0aae873e43cd">

### Additional context

This has been going on for at least last 5-7 versions.

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 239.41 MB / 32.00 GB
  Binaries:
    Node: 21.7.1 - ~/.nvm/versions/node/v21.7.1/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v21.7.1/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.47.0 => 1.47.0 
    playwright: ^1.47.0 => 1.47.0
```

**Comment by pavelfeldman** [comment] 2024-09-06 17:04
Works for me, reliably and consistently. We need exact steps to reproduce the issue to act on it.

Make sure you have video: 'off' btw since it is discouraged, especially since you are capturing traces.

**Comment by dgozman** [comment] 2024-09-11 08:31
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.

**Closed by dgozman** 2024-09-11 08:31 UTC

**Comment by siddharth2023** [comment] 2024-09-11 13:32
video: 'off' seems to have fixed this.

**Comment by DavidVaness** [comment] 2024-11-20 15:08
> Works for me, reliably and consistently. We need exact steps to reproduce the issue to act on it.
> 
> Make sure you have video: 'off' btw since it is discouraged, especially since you are capturing traces.

also ran into this today and confirming this works
@pavelfeldman I didn't see this mentioned in the docs, possibly worth it to point out?
