### ISSUE TITLE
[BUG] Slight Vertical Variation in Playwright Screenshots

### ISSUE THREAD

**Issue by natalie-ly** [microsoft/playwright#28018] opened 2023-11-07 17:32 UTC
### System info
- Playwright Version: [v1.32.0]
- Operating System: [Linux] - We conduct our testing on different platforms, but we've kept the screenshots separate. The issue we've observed pertains to the Jenkins Linux instance, while the Mac system is primarily used for local testing purposes.
- Browser: [All, Chromium, Firefox, WebKit, Microsoft Edge]

### Source code

- [ yes] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { test, expect, chromium, BrowserContext, devices } from "@playwright/test";

let context: BrowserContext;

test(`Verify web vertical`, async ({ browser }) => {
  context = await browser.newContext({
    viewport: devices['iPhone 11'].viewport, // Set the viewport to match a mobile device
    userAgent: devices['iPhone 11'].userAgent, // Set the user agent to match a mobile device
  });
  const page = await context.newPage();
  const url = `https://www.startpage.com/search?q=running%20shoes`
  await page.goto(url, { waitUntil: "commit" });
  await page.waitForLoadState("load");
  await page.waitForTimeout(5000);

  await expect(page).toHaveScreenshot(
    `web-bing-english-running-shoes.png`,
    {
      animations: "disabled",
      maxDiffPixelRatio: 0.0005,
      scale: "css",
    }
  );
});
```

**Steps**
- [Run the test]
- [if test passes, run again - the snapshot for the full page have small difference vertically from time to time]

**Expected**
There should be no difference vertically between the actual and expected screenshot

**Actual**
There is a layout shift issue where from time to time, the screenshot of the full page has a small difference vertically between the actual and expected. The primary challenge we are currently encountering is that the screenshot occasionally exhibits a slight vertical variation in its position. Despite our attempts to mitigate this issue by implementing a 5-second waiting period, it appears that the problem persists.

Furthermore, it's important to note that the code we provided in the initial post does not precisely match what we used in our testing environment. This discrepancy arises because we employed mock data to maintain consistency in loading data, but the steps involved remain largely the same.

![280338687-0bc11e56-fa5d-4d14-a24d-ddf8d532e628](https://github.com/microsoft/playwright/assets/144157865/c95f5a8f-0ca8-4aa2-8102-8c0797c95958)

<img width="780" alt="Screen Shot 2023-11-02 at 8 43 18 PM" src="https://github.com/microsoft/playwright/assets/144157865/7f8c25a1-2ea5-497c-8c19-6c91602b0f84">

We are intrigued by the possibility of Playwright offering a function that can disregard vertical discrepancies while still allowing us to perform comparisons in the specific areas we intend to assess. We made an attempt to replace the full-page comparison with the comparison of specific main containers, but the outcome remains consistent – the screenshot continues to exhibit occasional vertical shifting.

**Comment by mxschmitt** [comment] 2023-11-14 18:43
It looks like the browser or page scrolled down for some reason. Since you didn't click, this most likely was invoked from the web page itself. You could try scrolling to the top before making a screenshot with something like this:

```ts
 await page.evaluate(() => window.scrollTo(0, 0))
 // do the screenshot here.
```

or debugging on your site why it did scroll down, maybe using [Playwright Trace Viewer](https://playwright.dev/docs/trace-viewer-intro) will help you finding out the reason.

**Comment by mxschmitt** [comment] 2023-11-21 20:44
Closing as per above. We need a reproducible in order to triage this. Once you have that, feel free to re-file.

**Closed by mxschmitt** 2023-11-21 20:44 UTC
Labels: triaging
