### ISSUE TITLE
[Question] Video logs for tests when page fixture is created in beforeAll

### ISSUE THREAD

**Issue by jithinjosejacob** [microsoft/playwright#14012] opened 2022-05-07 05:32 UTC
if i generate a page fixture in before all hook, and use the same page for all test blocks, i cant generate a video for failing tests, is there any workaround for this.

```
**before all**

const page = await browser.newPage()

const loginPage = new LoginPage(page)

**Tests**

const pageHeader = await loginPage.navigateToPage()
expect(pageHeader).toBe('React')

```

**Comment by dgozman** [comment] 2022-05-09 07:10
This is a duplicate of #9002.

**Closed by dgozman** 2022-05-09 07:10 UTC
