### ISSUE TITLE
[BUG] locale does not always set correct browser Intl locale for firefox

### ISSUE THREAD

**Issue by JohnnyCrazy** [microsoft/playwright#27802] opened 2023-10-25 20:14 UTC
### System info
- Playwright Version: 1.39.0
- Operating System: macOS Ventura 13.2.1 - M1
- Browser: Firefox
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
import { defineConfig, devices } from '@playwright/test';

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  testDir: './e2e',
  /* Run tests in files in parallel */
  fullyParallel: false,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: 1,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: 'http://localhost:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'on-first-retry',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
  ],
});
```

**Test file (self-contained)**

```
import test from '@playwright/test';

// eslint-disable-next-line no-console
console.log('Setting locale to:', process.env.LOCALE);
test.use({ locale: process.env.LOCALE });

test('localization test', async ({ page }) => {
  const browserLocale = await page.evaluate((num) => Intl.DateTimeFormat().resolvedOptions().locale);

  // eslint-disable-next-line no-console
  console.log('Browser locale:', browserLocale);
});
```

**Steps**
- Run `LOCALE=en-US pnpm exec playwright test --project=firefox e2e/testing.spec.ts`, observe output:

```
❯ LOCALE=en-US pnpm exec playwright test --project=firefox e2e/testing.spec.ts
Setting locale to: en-US

Running 1 test using 1 worker
Setting locale to: en-US
[firefox] › testing.spec.ts:7:1 › localization test
Browser locale: en-DE
  1 passed (3.6s)

To open last HTML report run:

  pnpm exec playwright show-report
```

**Expected**

Since the playwright locale is set to `en-US`, I expect the browser `Intl` locale to also be `en-US`. It works for other locale values (see example outputs below), just not for `en-US`. My system locale is `en_US`.

**Actual**

Browser reports `en-DE` as locale.

** More outputs **

```sh
❯ LOCALE=en-US pnpm exec playwright test --project=firefox e2e/testing.spec.ts
Setting locale to: en-US

Running 1 test using 1 worker
Setting locale to: en-US
[firefox] › testing.spec.ts:7:1 › localization test
Browser locale: en-DE
  1 passed (3.6s)

To open last HTML report run:

  pnpm exec playwright show-report

---

❯ LOCALE=de-DE pnpm exec playwright test --project=firefox e2e/testing.spec.ts
Setting locale to: de-DE

Running 1 test using 1 worker
Setting locale to: de-DE
[firefox] › testing.spec.ts:7:1 › localization test
Browser locale: de-DE
  1 passed (3.6s)

To open last HTML report run:

  pnpm exec playwright show-report

---

❯ LOCALE=en-CA pnpm exec playwright test --project=firefox e2e/testing.spec.ts
Setting locale to: en-CA

Running 1 test using 1 worker
Setting locale to: en-CA
[firefox] › testing.spec.ts:7:1 › localization test
Browser locale: en-CA
  1 passed (3.6s)

To open last HTML report run:

  pnpm exec playwright show-report

```

**Comment by yury-s** [comment] 2023-10-25 22:42
I cannot reproduce it on macOS 13.6.

> My system locale is en_US.

How do you change it?

**Comment by JohnnyCrazy** [comment] 2023-10-26 19:38
On the following settings screen you should be able to control the 2nd part of the locale: 
![image](https://github.com/microsoft/playwright/assets/3109892/d684c575-9cc6-48e3-851e-bb7fac5034e7)

I adapted the test a bit, the header is now:

```
if (process.env.LOCALE) {
  // eslint-disable-next-line no-console
  console.log('Setting locale to:', process.env.LOCALE);
  test.use({ locale: process.env.LOCALE });
}
```

When I set the region in macOS to germany (note that I have the language set to english):
```
❯ pnpm exec playwright test --project=firefox e2e/testing.spec.ts
...
Browser locale: en-DE
...

❯ LOCALE=en-US pnpm exec playwright test --project=firefox e2e/testing.spec.ts
...
Setting locale to: en-US
...
Browser locale: en-DE
...
```

After I change the region in macOS to United States (still have english as language):

```
❯ pnpm exec playwright test --project=firefox e2e/testing.spec.ts
...
Browser locale: en-US
...

❯ LOCALE=de-DE pnpm exec playwright test --project=firefox e2e/testing.spec.ts
...
Setting locale to: de-DE
...
Browser locale: de-DE
...
```

That is some very weird behaviour...

**Comment by yury-s** [comment] 2023-10-27 21:24
Hm, I still cannot reproduce it. I wonder if it might be caused by the minor OS version difference. @mxschmitt, can you try the example as you probably have similar configuration?

**Comment by mxschmitt** [comment] 2023-10-29 09:57
I can reproduce unexpected behaviour when running with this configuration:

<img width="482" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/37e37822-4998-454b-9325-46040f0ff356">

Where I'm getting `Browser locale: en-DE`. User OS configuration should not affect Playwright's locales.

```ts
import { firefox } from 'playwright';
(async () => {
  const browser = await firefox.launch();
  const context = await browser.newContext({
    locale: 'en-US'
  });
  const page = await context.newPage();
  const browserLocale = await page.evaluate(num => Intl.DateTimeFormat().resolvedOptions().locale);
  console.log('Browser locale:', browserLocale);
  await context.close();
  await browser.close();
})();
```

**Comment by mxschmitt** [comment] 2023-11-01 16:42
We fixed it on our side, should be land in this repository soon.

I still filed an upstream bug, since I was able to reproduce it in Stock Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1862469

**Comment by mxschmitt** [comment] 2023-11-02 09:48
Should be fixed in Canary in 1-2 days: https://playwright.dev/docs/canary-releases

**Closed by mxschmitt** 2023-11-02 09:48 UTC
Labels: browser-firefox, v1.40
