### ISSUE TITLE
[BUG] elementHandle.check: Unable to click checkbox

### ISSUE THREAD

**Issue by garciallorente-fer** [microsoft/playwright#5305] opened 2021-02-04 11:06 UTC
**Context:**
- Playwright Version: 1.8.0
- Operating System: Windows server 2016
- Node.js version: 14.15.3
- Browser: Chromium
- Extra: Error found in a Pipeline run (Azure DevOps)

Azure Devops Pipeline

jest-playwright-preset

**Code Snippet**

const element = await page.waitForSelector('input[type=checkbox][name=DontShowAgain]', { state: 'attached', timeout: 10000 })
await element.hover()
await element.check()

**Describe the bug**

elementHandle.check: Unable to click checkbox
    =========================== logs ===========================
    attempting click action
      waiting for element to be visible, enabled and not moving
      element is visible, enabled and does not move
      scrolling into view if needed
      done scrolling
      checking that element receives pointer events at (476,416.21)
      element does receive pointer events
      performing click action
      click action done
      waiting for scheduled navigations to finish
      navigations have finished
    ============================================================
    Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.:

      31 |         const element = await page.waitForSelector('input[type=checkbox][name=DontShowAgain]', { state: 'attached', timeout: 10000 })
      32 |         await element.hover()
    > 33 |         await element.check()
         |                       ^

      at Connection.sendMessageToServer (node_modules/playwright/lib/client/connection.js:69:15)
      at Proxy.<anonymous> (node_modules/playwright/lib/client/channelOwner.js:44:61)
      at node_modules/playwright/lib/client/elementHandle.js:171:47
      at ElementHandle._wrapApiCall (node_modules/playwright/lib/client/channelOwner.js:72:34)
      at ElementHandle.check (node_modules/playwright/lib/client/elementHandle.js:170:21)
      at RadioInput.<anonymous> (src/components/form/inputs/radio.ts:33:23)
      at fulfilled (src/components/form/inputs/radio.ts:5:58)

I just have had a random error that seems to not have any explanation (according to the logs) or any sign of how to be reproduced again.
I run my tests every night on Azure DevOps and I tonight I got the error specified above. But the logs doesn't say why the checkbox couldn't be clicked.

**Comment by dgozman** [comment] 2021-02-05 03:33
This error means that checkbox was unchecked, Playwright clicked it, and checkbox is still unchecked. Something went wrong, might be a bug in Playwright, or in the page. It's hard to say what's going on, do you have repro script by any chance?

We should improve the error message though.

**Comment by garciallorente-fer** [comment] 2021-02-09 17:34
Unfortunately it occured in a Microsoft Login Page, "stay signed in" checkbox, so I cannot provide repro script. I have not been able no reproduce it again myself.

**Comment by creage** [comment] 2021-02-16 19:30
I can confirm this issue happens on Firefox too. Apparently the issue is something _random_. And happens on radio buttons only.

**Comment by dgozman** [comment] 2021-03-02 00:40
In version v1.9 the error message has been changed to more descriptive `Clicking the checkbox did not change its state`. Closing this since we lack a reproducible scenario to investigate further.

**Closed by dgozman** 2021-03-02 00:40 UTC
Labels: P2-bug, v1.10

**Comment by paunovic** [comment] 2022-03-24 10:37
Can confirm this still happens in some of our tests, approximately 1/20 test runs fails with such error.

**Comment by machtyn** [comment] 2022-04-13 01:22
This is happening to me. I have a table of data, with each row having a checkbox. I wish to select two or more based on the id on the row. I'm using Version 1.20.2 in nodejs (javascript).

`
const test_data = { "users": [ {"id": "3845", "name": "Frank Smith"}, {"id": "4892", "name": "George Johnson"}];

await Promise.all(test_data.users.map( async (user) => {
   const subLocator = page.locator('td', {hasText: user.id});
   await page.locator('table tbody tr', {has: subLocator}).locator('input[type="checkbox"]').check();
});
`
It worked once in headed mode. Then it failed 3 times in a row. Then it failed another 4 times in a row in non-headed mode.

The table (for my example) is:

`
<table>
  <thead>
  <tr>
    <th></th>
    <th>ID</th>
    <th>Name</th>
  </thead>
  <tbody>
  <tr>
    <td><input type="checkbox" name="selectedId" /></td>
    <td>4892</td>
    <td>George Johnson</td>
  </tr>
  <tr>
    <td><input type="checkbox" name="selectedId" /></td>
    <td>3845</td>
    <td>Frank Smith</td>
  </tr>
  </tbody>
</table>
`

**Comment by dgozman** [comment] 2022-04-13 17:13
@machtyn That snippet is checking two checkboxes at the same time. That's like a user connecting two mice and trying to click two different checkboxes simultaneously - they will interfere with each other. To avoid this problem, replace `Promise.all` with a loop:

```js
const test_data = { "users": [ {"id": "3845", "name": "Frank Smith"}, {"id": "4892", "name": "George Johnson"}];

for (const user of test_data) {
   const subLocator = page.locator('td', {hasText: user.id});
   await page.locator('table tbody tr', {has: subLocator}).locator('input[type="checkbox"]').check();
}
```
