### ISSUE TITLE
当我上传文件过大，浏览器关闭

### ISSUE THREAD

**Issue by bing127** [microsoft/playwright#10660] opened 2021-12-02 01:27 UTC
当我上传文件过大，浏览器关闭，但是我这边测试上传10mb的文件却正常运行，这是什么问题呢

错误信息如下：
could not send message to server: Protocol error (Runtime.callFunctionOn): Target closed.

**Comment by pavelfeldman** [comment] 2021-12-02 01:45
Looks like a dupe of https://github.com/microsoft/playwright/issues/3768.

**Closed by pavelfeldman** 2021-12-02 01:45 UTC
