### ISSUE TITLE
[BUG] : Lock file is already being held

### ISSUE THREAD

**Issue by mahaveer0496** [microsoft/playwright#8621] opened 2021-09-01 14:22 UTC
**Context:**
- Playwright Version: 1.12.3
- Operating System: Mac OS Big Sur 11.5.2
- Node.js version: 16.8.0
- Browser: All
- Extra: Apple silicon M1

**Describe the bug**
Can't install `playwright` with yarn or npm on M1, works fine on WSL2 and Linux. Here's a repo to reproduce https://github.com/mahaveer0496/playwright-test
Tried reinstalling everything and also this solution https://github.com/microsoft/playwright/issues/4242#issuecomment-789529236, didn't work.

<img width="1080" alt="Screenshot 2021-09-01 at 7 50 11 PM" src="https://user-images.githubusercontent.com/23198481/131688213-a087f9e3-e7d5-4f69-bdb5-fed446dccabe.png">

package.json
```json
{
  "name": "playwright-test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@playwright/test": "^1.12.3",
    "playwright": "^1.12.3"
  },
  "scripts": {
    "test": "playwright test --workers=100"
  }
}

```

Thanks!

**Comment by yury-s** [comment] 2021-09-01 16:02
Could you try this with the latest playwright (1.14.1) and see if the issue is still there?

**Comment by yury-s** [comment] 2021-09-01 16:11
This is the output I get on a fresh clone of you repo:
```sh
% cd playwright-test 
% yarn
yarn install v1.22.11
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
✨  Done in 0.56s.
% uname -m
arm64
```

**Comment by mahaveer0496** [comment] 2021-09-01 16:12
With the latest playwright version?

**Comment by yury-s** [comment] 2021-09-01 16:17
From the error it looks like you have another installation process that is running concurrently.

> With the latest playwright version?

I tried with exact project you have. Shouldn't matter.

**Comment by mahaveer0496** [comment] 2021-09-01 16:18
So, I upgraded playwright packages to 1.14.1 and everything’s working now. Thanks for that :)
I'm not sure why the older version worked for you though, it's a fresh Mac, Node installation so it's highly unlikely that I had some other package/app/config that could be causing this issue.

> From the error it looks like you have another installation process that is running concurrently.

Nope, I triple-checked, I was only installing in that project.

**Comment by yury-s** [comment] 2021-09-01 16:22
> I'm not sure why the older version worked for you though, it's a fresh Mac, Node installation so it's highly unlikely that I had some other package/app/config that could be causing this issue.

It might be that previous installation was aborted for some reason and left the dir lock file (which would expire after some time), which is highly unlikely though. Just speculating.

Closing the issues since your problem was solved.

**Closed by yury-s** 2021-09-01 16:22 UTC
Labels: triaging

**Comment by olemaiwald** [comment] 2021-10-20 10:45
When I reinstall node with volta (previously via homebrew) it works well for me too. Interesting, thank you!

**Comment by dancon** [comment] 2021-11-24 09:49
@mahaveer0496  not work for me.

**Comment by wlsf82** [comment] 2022-04-19 10:30
I'm facing the same issue. I've already tried using node installed directly from https://nodejs.org/, using nvm, and volta, and I'm always getting the same error.

**Comment by samdenty** [comment] 2022-07-07 16:56
```
rm -rf /Users/samdenty/Library/Caches/ms-playwright/__dirlock
```
