### ISSUE TITLE
[Question] How can I run playwright in github-actions successfully?

### ISSUE THREAD

**Issue by danlin604** [microsoft/playwright#16906] opened 2022-08-29 23:14 UTC
I am trying to run E2E tests during github-actions but have been unsuccessful so far.

```
    - name: Run build and start
      run: |
        yarn build:e2e
        yarn start:e2e &
    - name: Run e2e
      run: |
        yarn e2e
```

I don't think the server is running when `playwright` runs because all the e2e tests end up failing.

**Run build and start**
```
Done in 192.91s.
yarn run v1.22.19
$ env-cmd -f environments/.env.e2e next start
ready - started server on 0.0.0.0:3000, url: ***
```

**Run e2e**
```
Test timeout of 270000ms exceeded while running "beforeEach" hook.
```

I am pretty certain that playwright cannot connect to `http://localhost:3000` from the previous step and that's why all the tests timeout.

**Comment by pavelfeldman** [comment] 2022-08-30 16:22
You can use Playwright's [web server](https://playwright.dev/docs/next/api/class-testconfig#test-config-web-server) option to run web server reliably.

**Comment by danlin604** [comment] 2022-08-30 19:18
This solution does not work so far for me. The job errors out and the server cannot be started. It's one of the reason I've started splitting the steps because for some reason the server fails to start eventhough locally e2e works fine.

```
webServer: {
  command: 'yarn dev:e2e',
  url: 'http://localhost:3000',
  timeout: 120 * 1000 * 5,
  reuseExistingServer: !process.env.CI,
},
```

Error:
```
Running 34 tests using 1 worker

[WebServer] error Command failed with exit code 1.
Error: Process from config.webServer was not able to start. Exit code: 1
```

**Comment by pavelfeldman** [comment] 2022-08-30 19:35
I suspect the problem is with `reuseExistingServer: !process.env.CI`. Things probably work locally because the server is already running. Are you using ESM? We recently fixed an issue with yarn web server command when using ESM (https://github.com/microsoft/playwright/pull/16733).

**Comment by danlin604** [comment] 2022-08-30 20:56
I don't think `reuseExistingServer` is the culprit here. Setting it to a default `false` has no impact locally. I've double checked to removing any running processes. The server would typically fail if nothing is running and e2e will only pass if `webServer` has been configured.

Running it locally with `reuseExistingServer: false`.
```
λ yarn e2e
yarn run v1.22.15
$ playwright test

Running 34 tests using 6 workers

[WebServer] Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps`
[WebServer] Read more: https://nextjs.org/docs/messages/opt-out-auto-static-optimization

  ok 1 …] › ...
``` 

The version that I am using is `"@playwright/test": "^1.25.1",`. Regarding ESM, my tsconfig is:
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "**/*.css"],
  "exclude": ["node_modules"],
  "typeRoots": ["./global.d.ts", "./node_modules/@types"]
}
```

**Comment by pavelfeldman** [comment] 2022-08-31 16:30
Your ESM mode is defined in package.json not tsconfig, but since you are using TypeScript, it is unlikely that you are in the ESM mode. So you are saying things are happy locally. You can try the CI mode locally via running

```
CI=true yarn e2e
```

That would run it exactly as you are running it on GHA. If that works, something else is wrong.

We are running 50+ workflows on GHA, so GHA on itself is unlikely the problem. We are not using yarn though, so maybe something is off with the yarn versions being used locally and on CI. I don't think I can help you further w/o being able to reproduce this.

**Comment by danlin604** [comment] 2022-09-01 15:20
CI doesn't seem related to the issue. Do you happen to know if there is a public project using gh-actions running playwright that I can look at? We may have to work from a working example to compare the differences. Otherwise we may need to deploy first and run CI against the deployed instance.

I've tried setting the config by running `SET CI=true & yarn e2e` and separately by hardcoding CI to true in the playwright config.

```
  webServer: {
    command: 'yarn build:e2e && yarn start:e2e',
    url: 'http://localhost:3000',
    timeout: 120 * 1000 * 5,
    reuseExistingServer: false,
  },
  use: {
    baseURL: 'http://localhost:3000',
    trace: 'on-first-retry',
  },
  timeout: 30000,
  globalTimeout: 600000,
  reporter: 'list',
  testDir: './e2e',
  forbidOnly: true,
  retries: 3,
```

**Comment by pavelfeldman** [comment] 2022-09-02 16:24
You can use `npm create playwright@latest` and say Yes when it offers to create a GHA workflow file. Your problem seems to rather be around ability to run your server on GHA and using yarn.

**Comment by dgozman** [comment] 2022-09-09 23:57
Closing as per above.

**Closed by dgozman** 2022-09-09 23:57 UTC
Labels: triaging

**Comment by shellscape** [comment] 2023-12-29 03:22
@dgozman I landed on this issue due to the same error that the OP experienced, after running `npm create playwright@latest`. this isn't the first issue I've run across that seems prematurely closed, without any triage from the team. the management of issues on this project seem to be dubious at best.

**Comment by dgozman** [comment] 2024-01-10 00:03
@shellscape Could you please file a new issue by filling in the "Bug Report" template? Thank you!

**Comment by shellscape** [comment] 2024-01-10 00:05
@dgozman I have little incentive to given how the repo is being managed

**Comment by christian1koch** [comment] 2024-04-01 23:59
I also seem to be having this issue

**Comment by christian1koch** [comment] 2024-04-02 00:16
I fixed this issue by building and then starting instead of running on the development server.
Check that your port is the correct after changing from dev server to building.

**Comment by Kaan-1** [comment] 2025-10-07 12:41
> I fixed this issue by building and then starting instead of running on the development server. Check that your port is the correct after changing from dev server to building.

This worked for me as well
