### ISSUE TITLE
[Question] "Cannot read property 'launch' of undefined"

### ISSUE THREAD

**Issue by osmenia** [microsoft/playwright#3084] opened 2020-07-22 09:55 UTC
Hi Team,

I am playing with AWS Lambda and Playwright. 

with "playwright-aws-lambda": "^0.5.2", "playwright-core": "^1.0.1", works fine 

but with "playwright-aws-lambda": "^0.5.2", "playwright-core": "^1.2.1", does not work. 

what could be a problem?

my Code:

```
const playwright = require('playwright-aws-lambda');

exports.handler = async (event, context) => {
  let result = null;
  let browser = null;

  try {
    const browser = await playwright.launchChromium();
    const context = await browser.newContext();

    const page = await context.newPage();
    await page.goto(event.url || 'https://google.com');

    console.log('Page title: ', await page.title());
  } catch (error) {
    throw error;
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }
};
```

**Error Message:**

```
{
  "errorType": "TypeError",
  "errorMessage": "Cannot read property 'launch' of undefined",
  "trace": [
    "TypeError: Cannot read property 'launch' of undefined",
    "    at Object.launchChromium (/opt/node_modules/playwright-aws-lambda/dist/src/chromium.js:90:47)",
    "    at async Runtime.exports.handler (/var/task/api/poc1/handler.js:8:21)"
  ]
}

```
tnx a lot

**Comment by mxschmitt** [comment] 2020-07-22 10:38
It seems like its caused by that issue: #2905 since they are using `playwright-core` internally to launch Chromium.

https://github.com/JupiterOne/playwright-aws-lambda/blob/537234f35a59f4e54445958fb508c45431d9276c/src/chromium.ts#L102-L107

**Comment by osmenia** [comment] 2020-07-22 11:48
Hi max

tnx a lot,

Is there any workaround to start aws lambda  with plw core 1.2.1

I am using plw core 1.0.2 and it works fine.

Max Schmitt <notifications@github.com> schrieb am Mi., 22. Juli 2020, 12:38:

**Comment by mxschmitt** [comment] 2020-07-22 12:37
I think if you add this to your `package.json` as a dependency it should work:

`"playwright-core": "npm:playwright-chromium@1.2.1",`

**Comment by osmenia** [comment] 2020-07-23 17:36
Hi Max,

I created new layer with:

**package.json**
....
  "license": "ISC",
  "dependencies": {
    "playwright-aws-lambda": "^0.5.2",
    "playwright-chromium": "^1.2.1",
    "playwright-core": "npm:playwright-chromium@1.2.1"
  }
} 

**Error**: 
{
  "errorType": "TypeError",
  "errorMessage": "Cannot read property 'launch' of undefined",
  "trace": [
    "TypeError: Cannot read property 'launch' of undefined",
    "    at Object.launchChromium (/opt/nodejs/node_modules/playwright-aws-lambda/dist/src/chromium.js:90:47)",
    "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "    at async Runtime.exports.handler (/var/task/index.js:8:21)"
  ]
}

an then i deleted  "playwright-chromium": "^1.2.1" from json file and uploaded new layer, 
with
  "dependencies": {
    "playwright-aws-lambda": "^0.5.2",
    "playwright-core": "npm:playwright-chromium@1.2.1"
  }

this does not help.

am i doing something wrong?

**Comment by aslushnikov** [comment] 2020-08-21 07:47
Closing as dupe of https://github.com/microsoft/playwright/issues/2905

**Closed by aslushnikov** 2020-08-21 07:47 UTC
