### ISSUE TITLE
[BUG] Can't drop element onto element outside the viewport

### ISSUE THREAD

**Issue by PinkChampagne17** [microsoft/playwright#17621] opened 2022-09-27 10:55 UTC
**Context:**
- Playwright Version: 1.25.2
- Operating System: Mac
- Browser: Chromium

**Describe the bug**

Playwright will always be waiting and do nothing if I drag an element to drop onto an element outside the viewport.

**Comment by aslushnikov** [comment] 2022-09-28 08:51
@PinkChampagne17 this is expected, users can't drop elements outside of viewport too! I'll close this as "works as intended", but please don't hesitate to file another issue and share your scenario to convince me that this is a bug :)

**Closed by aslushnikov** 2022-09-28 08:51 UTC

**Comment by PinkChampagne17** [comment] 2022-09-29 04:51
> @PinkChampagne17 this is expected, users can't drop elements outside of viewport too! I'll close this as "works as intended", but please don't hesitate to file another issue and share your scenario to convince me that this is a bug :)

Indeed, users cannot simply drop elements outside of the viewport. However, users can scroll the mouse wheel during dragging or drag the element to the edge of the browser window to trigger scrolling to let the target element into viewport. Can we simulate such behavior?
