### ISSUE TITLE
Use it with vue to report an error

### ISSUE THREAD

**Issue by 368573607** [microsoft/playwright#8805] opened 2021-09-09 13:53 UTC
**Context:**
- Playwright Version: latest
- Operating System: Mac
- Node.js version: 16.x
- Browser: Chromium
- Extra: none

**Describe the bug**

I tried to use playwright, electron and vue together, but got an error.

Like this:

![image](https://user-images.githubusercontent.com/60562136/132697952-d7d16531-2923-4486-98be-e073c5513090.png)

If I did not introduce playwright, there would be no error, everything is normal. But if I introduce it, I will get this error.

The same program, I run normally without using vue+electron, but once I use them, things get worse.

I know this may have something to do with vue, but I still created an issue here, I also asked the same question in vue, I hope to get an answer.

**Comment by 368573607** [comment] 2021-09-13 12:52
So do you support vite?

**Comment by dgozman** [comment] 2021-09-13 22:40
> So do you support vite?

Could you please be more specific? Are you talking about [this vite](https://vitejs.dev/)? If so, we did not do anything specific for it. What do you mean by "support vite"?

**Comment by 368573607** [comment] 2021-09-18 05:34
> > So do you support vite?
> 
> Could you please be more specific? Are you talking about [this vite](https://vitejs.dev/)? If so, we did not do anything specific for it. What do you mean by "support vite"?

The previous person said that playwright cannot be bound by webpack, so I want to ask if it can be bound with vite. If not, is there any solution?

**Comment by mxschmitt** [comment] 2021-09-20 15:45
It's different. Playwright itself is a Node.js library. This means, that you cannot bundle it with e.g. Webpack or other tools for the web. If you want to trigger Playwright based on a http call e.g. you need a backend API (e.g. serverless function).

If we are talking about end-to-end testing, then you can use Playwright since its framework independent, either directly via Node.js or via its [test-runner](https://playwright.dev/docs/intro) to run end-to-end tests on your application bundled with Vite.

Let us know if this makes it more clear.

**Comment by mxschmitt** [comment] 2021-09-22 14:08
Closing since the issue is answered.

**Closed by mxschmitt** 2021-09-22 14:08 UTC
Labels: triaging
