### ISSUE TITLE
[BUG] Why does a await page.screenshot abort with "Pending operations" error

### ISSUE THREAD

**Issue by alanbqs** [microsoft/playwright#12493] opened 2022-03-03 18:40 UTC
when I run a ts script that includes multiple ```                 await page.screenshot({ path: fn6, fullPage: true });``` type calls - one of them is identified as crrashing the script with a Pending operations error.

Why would this be?

```
    Timeout of 20000ms exceeded.

    Pending operations:
      - locator.waitFor at myProj\tests\test.spec.ts.datamerged.ts:9:98

    page.screenshot: Target page, context or browser has been closed

      101 |                  const fn6="myProj/tests/screenshots/test.spec.ts/" + workerInfo.project.name + "-6.png"; 
      102 |                  console.log("screenshot before filling in the new screen record-type select: <BR><file>"+fn6+"</file> <BR>...on "+page.url());
    > 103 |                  await page.screenshot({ path: fn6, fullPage: true });
          |                             ^
      104 |                  //#screenshot - end -------------
      105 |                  console.log("screenshot done");
      106 |                   const ddlb = await page.$('#RecordTypCd');
```

Interestingly, when run with --debug, then the crash does not occur.

**Comment by aslushnikov** [comment] 2022-03-04 10:05
@alanbqs hard to say; can you please build a small repro that reproduces this? Maybe this is a bug; we'll debug and fix it!

**Comment by shirshak55** [comment] 2022-03-04 11:54
Was  browser closed while screenshot was being taken? How long is the page (Just to understand if taking screenshot is long process for your website).

**Comment by alanbqs** [comment] 2022-03-05 16:20
I guess the screenshot is close to the end of the step. Is this a bug (i.e. tests finish before a screenshot is complete?)

I have packaged up a mockup screen that works with the following test script:

test.ts:
```
import { test, expect } from '@playwright/test';
test.describe('Test Group', async () => {

      const locatorExists = async (locator: Locator, timeout: number = 3000) => !((await locator.waitFor({ timeout }).catch((e: Error) => e)) instanceof Error);

      test("Test ListScreen for Tokyo", async ({ page }, workerInfo) => {

            await test.step('Step 1 - Tokyo list screen', async () => {
                  await page.goto('http://methodfish.com/list.html');
                  await locatorExists(page.locator("div[id='.preloader']", { hidden: true }));

                  const exists = await locatorExists(page.locator('.col_AccountNm', { hasText: 'Tokyo' }));
                  if (exists) {
                        await page.click('tr:has(td.col_AccountNm:has-text("Tokyo")) >> a:nth-child(2)');
                        await expect(page).toHaveURL(new RegExp("^http://methodfish.com/list_edit.html\\?RecN=")); 
                        await locatorExists(page.locator("div[id='.preloader']", { hidden: true }));


                        //#screenshot - start -------------
                        const fn1="tests/screenshots/methodfish_create_account.spec.ts/" + workerInfo.project.name + "-1.png";
                        console.log("screenshot checking we are editing the Tokyo record: <BR><file>"+fn1+"</file> <BR>...on "+page.url());
                        await page.screenshot({ path: fn1, fullPage: true });
                        //#screenshot - end -------------
                        console.log("screenshot " + workerInfo.project.name + " 1 done");
                        
			await expect(page.inputValue('#AccountNm')).toBe('Tokyo');
                        await page.click(".toolbar_delete");


                        await expect(page).toHaveURL(new RegExp("^http://methodfish.com/list_edit.html\\?RecN="));
                        await locatorExists(page.locator("div[id='.preloader']", { hidden: true }));
                        await locatorExists(page.locator("div[id='.inputs']", { hasText: 'Account Deleted' }));

                  }
                  await page.click(".toolbar_add"); 
            });



            await test.step('Step 2 - Adding new Tokyo record', async () => {

                  await expect(page).toHaveURL('http://methodfish.com/list_edit.html');
                  await locatorExists(page.locator("div[id='.preloader']", { hidden: true }));

                  //#screenshot - start -------------
                  const fn2="tests/screenshots/methodfish_create_account.spec.ts/" + workerInfo.project.name + "-2.png"; 
                  console.log("screenshot after preloader is removed  on the new screen: <BR><file>"+fn2+"</file> <BR>...on "+page.url());
                  await page.screenshot({ path: fn2, fullPage: true });
                  //#screenshot - end -------------
                  console.log("screenshot " + workerInfo.project.name + " 2 done");

                  await page.fill("input[name='AccountNm']", 'Tokyo');
                  await page.keyboard.press('Enter');
                  await expect('#ShortCd').not.toBe("");
                  await page.fill("input[name='URL']", 'www.japan.co.jp');
                  await locatorExists(page.locator("div[id='.hourglass']", { hidden: true }));


                  //#screenshot - start -------------
                  const fn3="tests/screenshots/methodfish_create_account.spec.ts/" + workerInfo.project.name + "-3.png";
                  console.log("screenshot before filling in the new screen account-type select: <BR><file>"+fn3+"</file> <BR>...on "+page.url());
                  await page.screenshot({ path: fn3, fullPage: true });
                  //#screenshot - end -------------
                  console.log("screenshot " + workerInfo.project.name + " 3 done");
				  
                  const ddlb = await page.$('#AccountTypeCd');
                  await ddlb?.selectOption('Client');


                  //#screenshot - start -------------
                  const fn4="tests/screenshots/methodfish_create_account.spec.ts/" + workerInfo.project.name + "-4.png"; 
                  console.log("screenshot after filling in the new screen account-type select: <BR><file>"+fn4+"</file> <BR>...on "+page.url());
                  await page.screenshot({ path: fn4, fullPage: true });
                  //#screenshot - end -------------
                  console.log("screenshot " + workerInfo.project.name + " 4 done");
				 
                  if ("" === "1") await page.check('#CheckedFg');
                  await page.click(".toolbar_save");
                  await expect(page).toHaveURL(new RegExp("^http://methodfish.com/list_edit.html\\?RecN="));
                  await locatorExists(page.locator('div', { hasText: 'New record saved' }));


                  //#screenshot - start -------------
                  const fn5="tests/screenshots/methodfish_create_account.spec.ts/" + workerInfo.project.name + "-5.png"; 
                  console.log("screenshot after save: <BR><file>"+fn5+"</file> <BR>...on "+page.url());
                  await page.screenshot({ path: fn5, fullPage: true });
                  //#screenshot - end -------------
                  console.log("screenshot " + workerInfo.project.name + " 5 done");


                  await page.goto('http://methodfish.com/list.html');
                  await locatorExists(page.locator("div[id='.preloader']", { hidden: true }));

                  //#screenshot - start -------------
                  const fn6="tests/screenshots/methodfish_create_account.spec.ts/" + workerInfo.project.name + "-6.png"; 
                  console.log("screenshot to look at list of accounts: <BR><file>"+fn6+"</file> <BR>...on "+page.url());
                  await page.screenshot({ path: fn6, fullPage: true });
                  //#screenshot - end -------------
                  console.log("screenshot " + workerInfo.project.name + " 6 done");


                  console.log('test done');
            });

      });
      /* dataloop end *//* dataloop start */
      test("Test ListScreen for Delhi", async ({ page }, workerInfo) => {

            await test.step('Step 1 - Delhi list screen', async () => {
                  await page.goto('http://methodfish.com/list.html');
                  await locatorExists(page.locator("div[id='.preloader']", { hidden: true }));

                  const exists = await locatorExists(page.locator('.col_AccountNm', { hasText: 'Delhi' }));
                  if (exists) {
                        await page.click('tr:has(td.col_AccountNm:has-text("Delhi")) >> a:nth-child(2)');
                        await expect(page).toHaveURL(new RegExp("^http://methodfish.com/list_edit.html\\?RecN=")); 
                        await locatorExists(page.locator("div[id='.preloader']", { hidden: true }));


                        //#screenshot - start -------------
                        const fn7="tests/screenshots/methodfish_create_account.spec.ts/" + workerInfo.project.name + "-7.png"; 
                        console.log("screenshot checking we are editing the Delhi record: <BR><file>"+fn7+"</file> <BR>...on "+page.url());
                        await page.screenshot({ path: fn7, fullPage: true });
                        //#screenshot - end -------------
                        console.log("screenshot " + workerInfo.project.name + " 7 done");
                        
			await expect(page.inputValue('#AccountNm')).toBe('Delhi');
                        await page.click(".toolbar_delete");


                        await expect(page).toHaveURL(new RegExp("^http://methodfish.com/list_edit.html\\?RecN="));
                        await locatorExists(page.locator("div[id='.preloader']", { hidden: true }));
                        await locatorExists(page.locator("div[id='.inputs']", { hasText: 'Account Deleted' }));

                  }
                  await page.click(".toolbar_add"); 
            });



            await test.step('Step 2 - Adding new Delhi record', async () => {

                  await expect(page).toHaveURL('http://methodfish.com/list_edit.html');
                  await locatorExists(page.locator("div[id='.preloader']", { hidden: true }));

                  //#screenshot - start -------------
                  const fn8="tests/screenshots/methodfish_create_account.spec.ts/" + workerInfo.project.name + "-8.png";
                  console.log("screenshot after preloader is removed  on the new screen: <BR><file>"+fn8+"</file> <BR>...on "+page.url());
                  await page.screenshot({ path: fn8, fullPage: true });
                  //#screenshot - end -------------
                  console.log("screenshot " + workerInfo.project.name + " 8 done");

                  await page.fill("input[name='AccountNm']", 'Delhi');
                  await page.keyboard.press('Enter');
                  await expect('#ShortCd').not.toBe("");
                  await page.fill("input[name='URL']", 'www.india.co.in');
                  await locatorExists(page.locator("div[id='.hourglass']", { hidden: true }));


                  //#screenshot - start -------------
                  const fn9="tests/screenshots/methodfish_create_account.spec.ts/" + workerInfo.project.name + "-9.png"; 
                  console.log("screenshot before filling in the new screen account-type select: <BR><file>"+fn9+"</file> <BR>...on "+page.url());
                  await page.screenshot({ path: fn9, fullPage: true });
                  //#screenshot - end -------------
                  console.log("screenshot " + workerInfo.project.name + " 9 done");
                  
		  const ddlb = await page.$('#AccountTypeCd');
                  await ddlb?.selectOption('Client');


                  //#screenshot - start -------------
                  const fn10="tests/screenshots/methodfish_create_account.spec.ts/" + workerInfo.project.name + "-10.png"; 
                  console.log("screenshot after filling in the new screen account-type select: <BR><file>"+fn10+"</file> <BR>...on "+page.url());
                  await page.screenshot({ path: fn10, fullPage: true });
                  //#screenshot - end -------------
                  console.log("screenshot " + workerInfo.project.name + " 10 done");
                  
                  if ("" === "1") await page.check('#CheckedFg');
                  await page.click(".toolbar_save");
                  await expect(page).toHaveURL(new RegExp("^http://methodfish.com/list_edit.html\\?RecN="));
                  await locatorExists(page.locator('div', { hasText: 'New record saved' }));


                  //#screenshot - start -------------
                  const fn11="tests/screenshots/methodfish_create_account.spec.ts/" + workerInfo.project.name + "-11.png";
                  console.log("screenshot after save: <BR><file>"+fn11+"</file> <BR>...on "+page.url());
                  await page.screenshot({ path: fn11, fullPage: true });
                  //#screenshot - end -------------
                  console.log("screenshot " + workerInfo.project.name + " 11 done");


                  await page.goto('http://methodfish.com/list.html');
                  await locatorExists(page.locator("div[id='.preloader']", { hidden: true }));

                  //#screenshot - start -------------
                  const fn12="tests/screenshots/methodfish_create_account.spec.ts/" + workerInfo.project.name + "-12.png"; 
                  console.log("screenshot to look at list of accounts: <BR><file>"+fn12+"</file> <BR>...on "+page.url());
                  await page.screenshot({ path: fn12, fullPage: true });
                  //#screenshot - end -------------
                  console.log("screenshot " + workerInfo.project.name + " 12 done");


                  console.log('test done');
            });

      });
      /* dataloop end *//* dataloop start */
      test("Test ListScreen for Shanghai", async ({ page }, workerInfo) => {

            await test.step('Step 1 - Shanghai list screen', async () => {
                  await page.goto('http://methodfish.com/list.html');
                  await locatorExists(page.locator("div[id='.preloader']", { hidden: true }));

                  const exists = await locatorExists(page.locator('.col_AccountNm', { hasText: 'Shanghai' }));
                  if (exists) {
                        await page.click('tr:has(td.col_AccountNm:has-text("Shanghai")) >> a:nth-child(2)');
                        await expect(page).toHaveURL(new RegExp("^http://methodfish.com/list_edit.html\\?RecN=")); 
                        await locatorExists(page.locator("div[id='.preloader']", { hidden: true }));


                        //#screenshot - start -------------
                        const fn13="tests/screenshots/methodfish_create_account.spec.ts/" + workerInfo.project.name + "-13.png";
                        console.log("screenshot checking we are editing the Shanghai record: <BR><file>"+fn13+"</file> <BR>...on "+page.url());
                        await page.screenshot({ path: fn13, fullPage: true });
                        //#screenshot - end -------------
                        console.log("screenshot " + workerInfo.project.name + " 13 done");
                        await expect(page.inputValue('#AccountNm')).toBe('Shanghai');
                        await page.click(".toolbar_delete");


                        await expect(page).toHaveURL(new RegExp("^http://methodfish.com/list_edit.html\\?RecN="));
                        await locatorExists(page.locator("div[id='.preloader']", { hidden: true }));
                        await locatorExists(page.locator("div[id='.inputs']", { hasText: 'Account Deleted' }));

                  }
                  await page.click(".toolbar_add"); 
            });



            await test.step('Step 2 - Adding new Shanghai record', async () => {

                  await expect(page).toHaveURL('http://methodfish.com/list_edit.html');
                  await locatorExists(page.locator("div[id='.preloader']", { hidden: true }));

                  //#screenshot - start -------------
                  const fn14="tests/screenshots/methodfish_create_account.spec.ts/" + workerInfo.project.name + "-14.png"; 
                  console.log("screenshot after preloader is removed  on the new screen: <BR><file>"+fn14+"</file> <BR>...on "+page.url());
                  await page.screenshot({ path: fn14, fullPage: true });
                  //#screenshot - end -------------
                  console.log("screenshot " + workerInfo.project.name + " 14 done");

                  await page.fill("input[name='AccountNm']", 'Shanghai');
                  await page.keyboard.press('Enter');
                  await expect('#ShortCd').not.toBe("");
                  await page.fill("input[name='URL']", 'www.china.co.cn');
                  await locatorExists(page.locator("div[id='.hourglass']", { hidden: true }));


                  //#screenshot - start -------------
                  const fn15="tests/screenshots/methodfish_create_account.spec.ts/" + workerInfo.project.name + "-15.png";
                  console.log("screenshot before filling in the new screen account-type select: <BR><file>"+fn15+"</file> <BR>...on "+page.url());
                  await page.screenshot({ path: fn15, fullPage: true });
                  //#screenshot - end -------------
                  console.log("screenshot " + workerInfo.project.name + " 15 done");
                  
		  const ddlb = await page.$('#AccountTypeCd');
                  await ddlb?.selectOption('Client');


                  //#screenshot - start -------------
                  const fn16="tests/screenshots/methodfish_create_account.spec.ts/" + workerInfo.project.name + "-16.png"; 
                  console.log("screenshot after filling in the new screen account-type select: <BR><file>"+fn16+"</file> <BR>...on "+page.url());
                  await page.screenshot({ path: fn16, fullPage: true });
                  //#screenshot - end -------------
                  console.log("screenshot " + workerInfo.project.name + " 16 done");
                  
                  if ("" === "1") await page.check('#CheckedFg');
                  await page.click(".toolbar_save");
                  await expect(page).toHaveURL(new RegExp("^http://methodfish.com/list_edit.html\\?RecN="));
                  await locatorExists(page.locator('div', { hasText: 'New record saved' }));


                  //#screenshot - start -------------
                  const fn17="tests/screenshots/methodfish_create_account.spec.ts/" + workerInfo.project.name + "-17.png"; 
                  console.log("screenshot after save: <BR><file>"+fn17+"</file> <BR>...on "+page.url());
                  await page.screenshot({ path: fn17, fullPage: true });
                  //#screenshot - end -------------
                  console.log("screenshot " + workerInfo.project.name + " 17 done");


                  await page.goto('http://methodfish.com/list.html');
                  await locatorExists(page.locator("div[id='.preloader']", { hidden: true }));

                  //#screenshot - start -------------
                  const fn18="tests/screenshots/methodfish_create_account.spec.ts/" + workerInfo.project.name + "-18.png"; 
                  console.log("screenshot to look at list of accounts: <BR><file>"+fn18+"</file> <BR>...on "+page.url());
                  await page.screenshot({ path: fn18, fullPage: true });
                  //#screenshot - end -------------
                  console.log("screenshot " + workerInfo.project.name + " 18 done");


                  console.log('test done');
            });

      });
      /* dataloop end */


      test("Step 99", async ({ page }, workerInfo) => {
            console.log('all done----------------------------------------------');
      });
});
```


which when run with a config with multiple browser projects, for example:
```
import type { PlaywrightTestConfig } from '@playwright/test';
import { devices } from '@playwright/test';
const config: PlaywrightTestConfig = {
      testDir: './tests',
      timeout: 20 * 1000,
      expect: {
            timeout: 5000
      },
      forbidOnly: !!process.env.CI,
      retries: process.env.CI ? 2 : 0,
      workers: process.env.CI ? 1 : undefined,
      reporter: './tests/myReporter.ts', 
      /*reporter: [
            ['html',
                  {
                        open: 'never'
                  }
            ]
      ],*/ 
      use: {
            actionTimeout: 0,
            trace: 'on-first-retry',
      },
      projects: [
            {
                  name: 'chromium',
                  /* Project-specific settings. */
                  use: {
                        ...devices['Desktop Chrome'],
                  },
            },
            {
                  name: 'firefox',
                  use: {
                        ...devices['Desktop Firefox'],
                  },
            },
            {
                  name: 'webkit',
                  use: {
                        ...devices['Desktop Safari'],
                  },
            },
            /* Test against mobile viewports. */
            {
                  name: 'Mobile Chrome',
                  use: {
                        ...devices['Pixel 5'],
                  },
            },
            {
                  name: 'Mobile Safari',
                  use: {
                        ...devices['iPhone 12'],
                  },
            },

      ],

};
export default config;
```

and run with the command: ```cd C:\....\playwright && npx playwright test test.spec.ts --reporter=dot``` then I see similar errors such as:

```
 11) [Mobile Safari] › test.ts:110:7 › Test Group › Test ListScreen for Delhi

    Timeout of 20000ms exceeded.

    Pending operations:
      - locator.waitFor at tests\test.ts:8:98



    page.screenshot: Target page, context or browser has been closed

      196 |                  const fn12="tests/screenshots/methodfish_create_account.spec.ts/" + workerInfo.project.name + "-12.png"; 
      197 |                  console.log("screenshot to look at list of accounts: <BR><file>"+fn12+"</file> <BR>...on "+page.url());
    > 198 |                  await page.screenshot({ path: fn12, fullPage: true });
          |                             ^
      199 |                  //#screenshot - end -------------
      200 |                  console.log("screenshot " + workerInfo.project.name + " 12 done");
      201 |

        at C:\wamp64\www\testman\playwright\tests\test.ts:198:29
        at C:\wamp64\www\testman\playwright\tests\test.ts:143:13

```

**Comment by pavelfeldman** [comment] 2022-03-14 20:09
To answer your question: 20 second timeout was exceeded (you probably configured it somewhere) and Playwright prints all the currently running operations, not just the one that timed out. In your case, locator.waitFor at myProj\tests\test.spec.ts.datamerged.ts:9:98 never finished and Playwright is still waiting for it. It is likely to be an independent issue, unrelated to your screenshot problem.

Unfortunately, your script is too big to explore, so if you manage to reduce it to a 5-liner that reproduced the issue, we would greatly appreciate it. I'll close this bug for now as something we can't reproduce, but please feel free to reopen a reproduction!

**Closed by pavelfeldman** 2022-03-14 20:09 UTC
Labels: triaging
