### ISSUE TITLE
[BUG] Unhandled promise rejection causes browser to close (Target page, context or browser has been closed)

### ISSUE THREAD

**Issue by calvintwr** [microsoft/playwright#27345] opened 2023-09-28 17:16 UTC
### System info
- Playwright Version: [v1.37..1]
- Operating System: macOS 12.6.5, Ubuntu 20
- Browser: Chromium
- Other info:

### Source code

Minimum reproducible code:

```js
    const browser = await chromium.launch()
    const p = new Promise((resolve, reject) => {
        setTimeout(() => reject(new Error('EERRRRORRR')), 100)
    })

    p.then()
    console.log('sleep')
    await new Promise(resolve => setTimeout(() => resolve(true), 1000))
    try {
        console.log('Crawling google')
        const page = await browser.newPage()
        console.log('Page created')
        await page.goto('https://google.com', { waitUntil: 'load' })
        console.log('Page crawled')
        const crawledContent = (await page.locator('body').allInnerTexts()).join('\n')
        console.log(crawledContent)
    } catch (err) {
        console.log(err)
    }
```

**Steps**
- Run the above code

**Expected**

`browser.newPage()` should be able to crawl successfully.

**Actual**

Error out with the following message:

```
browser.newPage: Target page, context or browser has been closed
```

**Comment by yury-s** [comment] 2023-09-28 19:48
This is by design, Playwright Test [will fail](https://github.com/microsoft/playwright/blob/28924678397cb01001096fa4c2df0d4b46b73dc3/packages/playwright/src/worker/workerMain.ts#L75) if there are unhandled promise rejections, you can add a catch block to the promise if you expect it to throw. If you need to use Playwright for scraping you can do it without the test runner and have full control over the unhandled rejections behavior, e.g with [this option](https://nodejs.org/api/process.html#event-unhandledrejection).

Closing as this is by design.

**Closed by yury-s** 2023-09-28 19:48 UTC
