### ISSUE TITLE
[BUG] Test fails for identical image during visual tests, diff does not correspond to the difference between actual and expected

### ISSUE THREAD

**Issue by FilipKubis** [microsoft/playwright#17356] opened 2022-09-15 12:26 UTC
**Context:**
- Playwright Version: 1.25.2
- Operating System: Mac
- Node.js version: 16 (GitHub macos-latest runner with node set up via actions/setup-node@v3 with node-version: 16)
- Browser: WebKit
- Extra: GitHub macos-latest runner

**Description**

We sometimes experience the following issue during visual testing with playwright:
- the expected and actual image are the same
- but the diff shows that the images are different and the test fails

Is there perhaps some delay between the time of the comparison (when the diff is generated) and the time when the _actual_ image is genrated.

We are using the . toHaveScreenshot() function.

**Snaphots**

Expected Image
<img src="https://user-images.githubusercontent.com/29176275/190401200-a0d796bf-b337-4404-91ef-05c612aa93d7.png" width="150">

Actual Image:
<img src="https://user-images.githubusercontent.com/29176275/190401192-e1575415-fcc6-442c-a432-56103f1fb2e9.png" width="150">

Diff Image:
<img src="https://user-images.githubusercontent.com/29176275/190401198-7cfddb3d-4aa4-48d7-9676-49d0e72f0b05.png" width="150">

**Comment by mxschmitt** [comment] 2022-09-15 12:53
Can you give us a hint if you are using toMatchSnapshot or toHaveScreenshot?

**Comment by FilipKubis** [comment] 2022-09-15 12:56
> Can you give us a hint if you are using toMatchSnapshot or toHaveScreenshot?
> 
> The latter one is the new one and recommended since it will retry internally until the condition is met.

Yes, we are using the toHaveScreenshot function (I've added it to the description)

**Comment by pavelfeldman** [comment] 2022-09-22 04:49
The images are clearly different (lower part has highlighted diff). Is there a way for us to reproduce the problem? Please check that your expectations are correct, it looks like a bug on your side (misplaced results from different test runs).

**Comment by aslushnikov** [comment] 2022-09-28 09:10
I'll close this for now since this is not actionable without a repro. Please do not hesitate to re-file if you have a repro that we can run locally & debug!

**Closed by aslushnikov** 2022-09-28 09:10 UTC
Labels: triaging
