### ISSUE TITLE
[Feature] Wrong setup project dependencies

### ISSUE THREAD

**Issue by hafnerpw** [microsoft/playwright#23541] opened 2023-06-05 06:23 UTC
Hello Playwright team,

I recently encountered an issue with Playwright's handling of setup projects when the setup project file is not located in the specified **testDir**.

In my case, the **auth.setup.ts** file was not located inside the **testDir** folder. However, when running my tests, Playwright did not provide any error messages or warnings indicating that the setup project file could not be found or that there was an issue with its location. This made it quite difficult to diagnose why my authentication state was not being correctly saved and reused.

I would like to suggest that Playwright provide more informative error messages or warnings in cases where setup project files are not found in the expected location. This could help users diagnose configuration or file system issues more quickly.

Additionally, it may be helpful to include in the [documentation](https://playwright.dev/docs/auth) a note emphasizing that setup project files should be placed inside the testDir folder.

Thank you for considering this request. Your work on Playwright is greatly appreciated!

**Comment by aslushnikov** [comment] 2023-06-07 05:12
@hafnerpw could you please build a small repo that illustrates the issue you had? This way it is way easier for us to debug and fix the problem.

**Comment by aslushnikov** [comment] 2023-06-12 21:33
The discussion has stalled; closing this. Please feel free to re-file if you have a good repro!

**Closed by aslushnikov** 2023-06-12 21:33 UTC
Labels: triaging

**Comment by lmiller1990** [comment] 2023-08-15 11:49
Hi! I'm trying out Playwright, I ran into this same issue. I'm looking for something like:

```js
Cypress.on("test:before:run" () => {
  // configure something to happen before each test
})
```

I think the idiomatic PW way is project dependencies. I followed the instructions here: https://playwright.dev/docs/test-global-setup-teardown#project-dependencies

I created a project using `npx playwright init`. I follow the docs, and I created `setup.global.ts` at the root of my project. I think this is the issue -  the docs reads like putting `setup.global.ts` at the root is correct, but it looks like it must be in `testsDir`, which is `tests` by default (or is this a bug)? 

Either way, my `setup` project would not run. I moved `setup.global.ts` into `tests` like this: `cp global.setup.ts tests`. Now it works.

It looks like PW was finding the `setup.global.ts` due to the regexp `/setup.global.ts`, but since it was not in the `tests` dir, which is the default:

```ts
export default defineConfig({
  testDir: "./tests",
  // ...
})
```

It was not actually running the code in setup.

Hopefully this helps someone! 

A potential improvement would be a warning, eg: "found project dependency `setup` but ignoring since it is not in the `testsDir`". Or, maybe it shouldn't need to be in the `testsDir`.

WDYT @aslushnikov? If you are unable to reproduce, happy to share a reproduction.
