### ISSUE TITLE
[BUG] Uses internal PDF viewer to view PDFs when Content-Disposition set to inline rather than downloading

### ISSUE THREAD

**Issue by waynerobinson** [microsoft/playwright#3365] opened 2020-08-09 05:44 UTC
**Context:**
- Playwright Version: 1.2.1
- Operating System: Mac
- Node.js version: 12.14
- Browser: Chromium

**Describe the bug**

When navigating to PDF that is delivered with the header `Content-Disposition: inline`, Playwright opens in a new page and uses the embedded Chromium PDF viewer.

From this point it's impossible to get the actual PDF content. Even when inspecting the `response` event, the actual `response` object's body only contains the HTML presenting the embedded viewer with an inline ID representing the PDF. 

Whilst I'm sure there are some situations that would warrant the in-browser PDF viewer being turned on, I would guess that having these download by default would be the more common use-case within Playwright.

**Comment by mxschmitt** [comment] 2020-09-06 16:07
Closed as duplicate of #3365

**Closed by mxschmitt** 2020-09-06 16:07 UTC

**Comment by balakumaran182** [comment] 2023-09-27 05:42
is there any update on above issue.. we are unable to download the pdf when i opened in default chrome viewer in browser
