### ISSUE TITLE
[Feature] Recorder - do not show password in generated test

### ISSUE THREAD

**Issue by dmcweeney** [microsoft/playwright#27179] opened 2023-09-19 11:21 UTC
When recording a test and going through the AAD login step the password is written to the generated test.
Please do not do this for input type=password fields - someone will invariable save this to source control and...

Thanks, Donal

**Comment by aslushnikov** [comment] 2023-09-20 14:06
I'll merge this as a dupe of https://github.com/microsoft/playwright/issues/19992

**Closed by aslushnikov** 2023-09-20 14:06 UTC

**Comment by aslushnikov** [comment] 2023-09-21 01:02
@dmcweeney ah, I see! Sorry for the confusion, this is not a dupe.

Thank you for bringing this up! I see your point. However, we fundamentally want codegen to generate code that one can instantly run and validate. Not writing in some details will make code non-runnable, so I'm inclined to keep this as closed since it works as expected.

**Comment by dmcweeney** [comment] 2023-09-21 09:20
@aslushnikov ok understood. 

Alternative suggestion - put a big ugly cannot miss comment on the line before saying something like:

// WARNING following line contains a password - please remove before saving to your source control system
