### ISSUE TITLE
[Feature] @playwright/test moduleNameMapper config option

### ISSUE THREAD

**Issue by benjimanbrandt** [microsoft/playwright#7081] opened 2021-06-12 00:16 UTC
#### Let us know what functionality you'd like to see in Playwright and what is your use case.

In my typescript config, I'm using path aliases. Like the following:

```typescript
// tsconfig.json

{
  "compilerOptions": {
    // other options
    "paths": {
      "@my-alias/*": ["./*"]
    },
  }
}
```

That means my typescript types show up just fine in VS Code, but `playwright/test` yells at me if I try to use them:

```bash
Error: Error while reading /Users/me/code/playwright-project/very/nested/folder/some-test.spec.ts:
Cannot find module '@my-alias/fixtures'
```

It'd be nice to have an option like Jest's [`moduleNameMapper`](https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring), so I can use path aliases. An example of what that looks like for jest is:

```json
// jest.config.json

"moduleNameMapper": {
    "^@my-alias/(.*)$": "<rootDir>/playwright-project/$1"
  },
```

#### Do you think others might benefit from this as well?

Yes. Path aliases are a common setting in typescript projects, and a nice way to avoid many nested layers of `../..` when using `import` statements.

**Comment by mxschmitt** [comment] 2021-06-12 00:25
Seems like a duplicate of #7066. Please upvote it there.

**Closed** 2021-06-12 01:06 UTC
