### ISSUE TITLE
[BUG] `playwright test` with `webkit` will only lead to `browserContext.newPage: Target closed` on macOS (M1, Apple Silicon)

### ISSUE THREAD

**Issue by imWildCat** [microsoft/playwright#10108] opened 2021-11-06 12:25 UTC
**Context:**
- Playwright Version: `1.16.3`
- Operating System: `macOS 12.0.1 (21A559)`
- Browser: WebKit
- Extra: ARM64

### System:
 - OS: macOS 11.6
 - Memory: 2.85 GB / 32.00 GB
### Binaries:
 - Node: 16.3.0 - /usr/local/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 7.7.6 - /usr/local/bin/npm
### Languages:
 - Bash: 5.1.4 - /usr/local/bin/bash

### Code Snippet

```ts
import { expect, test } from '@playwright/test';

async function delay(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
test('twitter', async ({page}) => {
  await page.goto('https://twitter.com/dan_abramov/status/1086215004808978434');

  await delay(5000);

  const title = await page.evaluate(() => document.title);
  const text = await page.evaluate(() => document.body.textContent);

  console.log('[trace] title:', title);
  expect(title.startsWith('Dan on Twitter')).toBeTruthy();
  console.log('[trace] text:', text);
});
```

**Describe the bug**

```
➜  demo_project yarn playwright test src/t.spec.ts --browser webkit
yarn run v1.22.11
$ /Users/username/Downloads/202111/temp/demo_project/node_modules/.bin/playwright test src/t.spec.ts --browser webkit

Running 1 test using 1 worker

  ✘  [webkit] › src/t.spec.ts:6:1 › twitter (5s)


  1) [webkit] › src/t.spec.ts:6:1 › twitter ========================================================

    browserContext.newPage: Target closed





  1 failed
    [webkit] › src/t.spec.ts:6:1 › twitter =========================================================
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  demo_project
```

Also tested both headless / non-headless webkit on Ubuntu 20.04 (amd64), it worked well.

**Comment by KenPrehoda** [comment] 2021-11-07 03:03
I'm seeing the same bug. When I try to run pw_run.sh in webkit-1564:

./pw_run.sh
Playwright[14659:4089449] WebContent process crashed; reloading

**Comment by dshaplyko** [comment] 2021-11-07 12:55
I'm having the same issue, but looks like it is not related to M1 since I have 1,4 GHz Quad-Core Intel Core i51,4 GHz Quad-Core Intel Core i5.
Maybe it is related to Operating System: macOS 12.0.1 (21A559)?

**Comment by mxschmitt** [comment] 2021-11-07 15:55
Closing as a duplicate of #9811.

You can fix it by `npm i @playwright/test@1.17.0-next-alpha-nov-5-2021` or wait for 1.17.0.

**Closed by mxschmitt** 2021-11-07 15:55 UTC

**Comment by imWildCat** [comment] 2021-11-08 01:25
Awesome! Thanks for the quick turnaround!

**Comment by TheRobBrennan** [comment] 2021-11-20 20:37
Thank you so much for this. I was about to ask the same question 🤓

**Comment by kiranmai-perili** [comment] 2022-12-05 11:24
Hi,
I am Getting a Context issue wrt to firefox browser in playwright, how to solve this issue using the global config in playwright?
![Screenshot (334)](https://user-images.githubusercontent.com/115471627/205625642-04ccbcc3-a99f-4997-8235-0f29d0218f9f.png)
