### ISSUE TITLE
[Bug]: Redirect after Azure Entra Login fails

### ISSUE THREAD

**Issue by 5p1k3md** [microsoft/playwright#29925] opened 2024-03-13 15:15 UTC
### Version

1.42.0

### Steps to reproduce

- Create a Blazor Server app with activated azure ad authentication as described [here](https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-blazor-server)
- Record a login
- On the step after _Don't show this again window successfully closed_ and click on yes await the redirect and it will fail with the message _ERR_INVALID_URL_
- On a page reload the page is served as expected

### Expected behavior

Redirect to the expected page like in version 1.41.2

### Actual behavior

Redirect fails with the message _ERR_INVALID_URL_

### Additional context

Videos of the behavior can be sent in private if helpful.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 32.90 GB / 63.72 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.87.0 - ~\Programs\Microsoft VS Code\bin\code.CMD
```

**Comment by MathieuDoyon** [comment] 2024-03-13 18:24
Look like an issue with the Chromium binary. It was working for me until I upgrade playwright and run `playwright install` command again. I saw the upgrade of the browsers binaries then it stop working.

I have a similar flow login with Auth0 instead of Azure.
after my e2e user login I'm getting redirected to my page and the browser crash with the same `ERR_INVALID_URL`

**Comment by MathieuDoyon** [comment] 2024-03-13 19:20
I was able to rollback to previous playwright version and make it work.

try to lock your version to `"@playwright/test": "1.41.2",`

First uninstall your current browser binaries
`yarn playwright uninstall`

remove your node_modules and reinstall everything

```bash
yarn

yarn playwright install
```

my binary got rollback too.

```bash
 du -hs ~/Library/Caches/ms-playwright/*
399M	/Users/mathieudoyon/Library/Caches/ms-playwright/chromium-1105

# To the old locked version of "@playwright/test": "1.41.2",
 du -hs ~/Library/Caches/ms-playwright/*
389M	/Users/mathieudoyon/Library/Caches/ms-playwright/chromium-1097
```

**Comment by 5p1k3md** [comment] 2024-03-13 19:50
Yes, I did the same today, except i'm on .NET. But for future releases it should be fixed to be able to stay up to date with all releases and patches.

**Comment by Robert-Ed-Smith** [comment] 2024-03-19 08:52
Same issue

Started happening after upgrade Playwright to 1.42.0

1. Login with Azure Entra with Microsoft Identity (from MVC application Net8)
2. Reach the 'Stay logged in' question, and click Yes
3. Receive from signin-oidc a net:ERR_INVALID_REDIRECT error, then net:ERR_INVALID_URL. 
4. (If you just refresh the agent page when not running headless, the page loads fine)

**Comment by 5p1k3md** [comment] 2024-03-19 09:21
Hello @mxschmitt, 

sorry for the delay, it took me some days to find the time to test it.
The results as following:

1. Try channel: "chrome-canary" 
    - Working
    - Version: Version 124.0.6367.0 (Offizieller Build) canary (64-Bit)
2. Try channel: "chrome-dev"
    - Working
    - Version: Version 124.0.6356.6 (Offizieller Build) dev (64-Bit)
3. Try channel: "chrome-beta"
    - Working
    - Version: Version 123.0.6312.46 (Offizieller Build) beta (64-Bit)
4. Try channel: "chrome"
    - Working
    - Version: Version 122.0.6261.129 (Offizieller Build) (64-Bit)
5. No Channel - Chromium
    - Not Working
    - Version: Version 123.0.6312.4 (Entwickler-Build) (64-Bit)

If you need additional informations let me know.

Best regards

Marcus

**Comment by mxschmitt** [comment] 2024-03-19 10:56
Thats already helpful! So it might be that it was fixed between `123.0.6312.4` and `123.0.6312.46`.

If you are using Node.js, you can try our [Beta](https://playwright.dev/docs/canary-releases) which contains `123.0.6312.22` - so a little bit newer as well. In the meantime I'd recommend using the chrome-beta channel or waiting for the next Playwright release which will contain Chromium 124.

**Comment by 5p1k3md** [comment] 2024-03-19 11:09
I will stay at version 0.14.2 and wait for an update to avoid installing of beta on the build server.
Is it possible to get an information if this should be fixed?
I would test it afterwards.

**Comment by mxschmitt** [comment] 2024-03-19 11:36
Would it be possible to share a reproduction which does not require setting up AD auth etc.? (feel free to ping me on Discord if you have something to share) - then we can find out which exact upstream patch broke it for future reference, otherwise we sit more in the dark. Thank you.

**Comment by 5p1k3md** [comment] 2024-03-19 11:41
I can't imagine how because the error seems to be azure ad authentication specific. :/

**Comment by mxschmitt** [comment] 2024-03-21 15:25
This might be fixed in the latest Canary, could you try reproducing it there? https://playwright.dev/docs/canary-releases

**Comment by 5p1k3md** [comment] 2024-03-21 15:41
How could i test it under .net?

**Comment by mxschmitt** [comment] 2024-03-21 22:09
Its a little bit more complex:

- Download https://playwright.azureedge.net/builds/chromium/1110/chromium-win64.zip
- Extract it somewhere
- Point the ExecutablePath when launching the Browser towards the `chrome.exe`
- If you are using Microsoft.Playwright.NUnit/MSTest, you can set:

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <Playwright>
    <BrowserName>chromium</BrowserName>
    <LaunchOptions>
      <ExecutablePath>...</ExecutablePath>
    </LaunchOptions>
  </Playwright>
</RunSettings>
```

**Comment by areriklq** [comment] 2024-03-25 12:51
@mxschmitt I had the same issues, using "Azure AD B2C" Playwright tests suddenly started to fail in my auth setup, when upgrading from 1.41.2 to 1.42.1, due to `Error: page.waitForNavigation: net::ERR_INVALID_URL` (yes, I will stop using `waitForNavigation` soon 😉) for **both** "Desktop Chrome" and "Desktop Firefox".

I can confirm that using `next` and specifically the below versions "fixes" the issue for me for both "Desktop Chrome" and "Desktop Firefox" :
```
 @playwright/test 1.43.0-alpha-2024-03-25
  playwright 1.43.0-alpha-2024-03-25
```

Due to the nature of auth, I am too unable to submit a programmatic reproduction. But what I am doing is something like this to setup/persist auth for the test suite:
```
 const browser = await chromium.launch();
  const page = await browser.newPage({ ignoreHTTPSErrors });

  await page.goto(baseURL!);
  await page.fill(
    "[placeholder='Email Address']",
    FOO_USER_EMAIL!,
  );
  await page.fill("[placeholder='Password']", FOO_USER_PASSWORD!);
  await Promise.all([
    page.waitForNavigation(), <--- FAIL LIVES HERE
    page.click("button:has-text('Sign in')"),
  ]);

  await page.context().storageState({ path: storageState as string });

  await browser.close();
```

**Comment by mxschmitt** [comment] 2024-03-25 13:50
Thanks for the confirmation! I'll close it for now, since we know that the issue has been fixed in our beta version and there is no action item on our side. This bugfix will get included in our next release. As a workaround for now we recommend the canary/beta release.

**Closed by mxschmitt** 2024-03-25 13:50 UTC
Labels: v1.43

**Comment by areriklq** [comment] 2024-03-25 20:10
Good to hear @max-schaefer 

Did you find a way to catch this in your own regression tests for PW?
Could you point me to what change in 1.43 that fixes this issue?

**Comment by lachlankrautz** [comment] 2024-04-02 03:40
Closing this ticket before the fix was out sure made this harder to figure out there is an ongoing issue with the latest version.

**Comment by gauravkhuraana** [comment] 2024-07-04 09:57
Faced this problem in version 1.44 in docker with dotnet where the page gets stuck after pressing the sign in button

The test scripts which only validate home page are working fine because B2C does not come in picture 

but rest all are failing as we press on sigg in button it redirects to Microsoft AAD / entra and blank screen comes 

looking at traces i can confirm problem is there with dotnet / docker / 1.44 version where redirection to B2C happens
