### ISSUE TITLE
[Feature] Seeking Guidance on Accessing Test Annotations in Azure DevOps Using 'azure-devops-node-api'

### ISSUE THREAD

**Issue by deepakkamboj** [microsoft/playwright#28256] opened 2023-11-20 22:21 UTC
I am currently working on a project where we utilize test annotations by adding our team name through a fixture, as demonstrated in the code snippet below:

```ts
function setTeam(team: Team) {
  const annotations = base.info().annotations;
  const teamAnnotation = annotations.find((a) => a.type === 'team');

  if (teamAnnotation) {
    teamAnnotation.description = team;
  } else {
    annotations.push({
      type: 'team',
      description: team,
    });
  }
}
```

These annotations are then incorporated into the JUnit test reporter, which presents them as properties in the test-results.xml file:

```xml
<testcase name="Sample Tests" classname="adminCenter/sample.spec.ts" time="23.24">
  <properties>
    <property name="team" value="MyTeam"></property>
  </properties>
</testcase>
```

To streamline our workflow, we are using the 'azure-devops-node-api' package to access build information, test runs, and test results in Azure DevOps. The code snippet below outlines our approach:

```ts
// ... (previous code)

// Get a reference to the BuildApi
const buildApi = await webApi.getBuildApi();
// Get a reference to the TestApi
const testApi = await webApi.getTestApi();

// Get all builds for the specified build definition
const builds = await buildApi.getBuilds(
  projectName,
  [buildDefinitionId]
);

console.log('Number of builds fetched: ', builds?.length);

// Iterate through the builds
for (const build of builds) {
  console.log('[##section] Getting Build Details for build: ', build.id);

  // ... (previous code)

  // Iterate through the test runs and print their details
  for (const testRun of testRuns) {
    console.log('[##section] Getting Test Runs for build: ', build.id);

    // ... (previous code)

    // Get all test cases for the test run
    const testCases = await testApi.getTestResults(projectId, testRun.id, ResultDetails.SubResults);

    // Iterate through the test cases
    for (const testCase of testCases) {
      testCaseList.push({
        // ... (previous code)
        testOwner: 'team', // This should be assigned through customFields,
                           // and all properties in test-results.xml should be available as customFields.
        // ... (previous code)
      });
    }
  }
}

// ... (rest of the code)

```

However, we are facing a challenge in accessing the test annotations we publish in the test results using the 'azure-devops-node-api' or any other npm package. We would greatly appreciate guidance or suggestions on how to achieve this.

Thank you for your time and assistance.

Best regards,
Deepak Kamboj

**Comment by yury-s** [comment] 2023-11-20 23:10
Sounds like a question that should be addressed to the maintainers of 'azure-devops-node-api' or azure devops. Playwright simply writes the annotations as name/value properties to the file. How this file is uploaded to azure devops and how the data is read from the junit report is beyond the scope of playwright.

Closing this report as it is not a bug in Playwright. Feel free to open another issue with a repro if you think it is a playwright bug.

**Closed by yury-s** 2023-11-20 23:10 UTC
