### ISSUE TITLE
[BUG] Closing the page in afterEach hook affects subsequent tests within test.describe group (only when the tests are run using Test Explorer in VSCode)

### ISSUE THREAD

**Issue by ovenal** [microsoft/playwright#24574] opened 2023-08-02 20:24 UTC
### System info
- Playwright Version: v1.36.2
- Operating System: Windows 11
- Browser: Chromium

### Source code

- [ x ] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
import { test } from "@playwright/test";

test.afterEach(async ({page}) => {
    await page.close();
});

test.describe("Demo", () => {
    test("test #1", async ({ page }) => {
        await doTest(page);
    });

    test("test #2", async ({ page }) => {
        await doTest(page);
    });

    async function doTest(page) {
        await page.goto("https://github.com/microsoft/playwright");
        await Promise.all([
            page.locator("#issues-tab").click(),
            page.waitForResponse(
                response => response.url().endsWith("/issues") && response.status() === 200
            )
        ]);
    }
});
```

**Steps**
- Run the tests from VSCode (using Test Explorer pane).

**Expected**

The tests are identical, so they both should be passed successfully.

**Actual**

The first test is passed, but the second test fails on `page.waitForResponse` step with the message saying that `Page closed`, the previous steps that use this page were normally performed. 
If these tests are run separately they both are passed. If the `test.afterEach` section is commented out, both tests are passed too. This problem is actual only when the tests are started from VSCode.

By default, Playwright leaves the browser opened when the tests are finished and I want to close it. I don't want to manage the browser manually; the only way I found is to close a page in the `afterEach` block. Based on the information in [this article](https://playwright.dev/docs/browser-contexts) `page` objects in different tests are unique and they must be isolated, but it seems that in the example above these tests affect each other.  

In a similar case in the working project with a bit more complex scenario (unfortunately can't share the code to reproduce) the second test can't catch the response (even though I see this request in the browser on the Network tab in Chrome DevTools).

**Comment by yury-s** [comment] 2023-08-03 00:57
I cannot reproduce it with playwright 1.36.2, both tests always pass.

> The first test is passed, but the second test fails on page.waitForResponse step with the message saying that Page closed, the previous steps that use this page were normally performed.

Can you share full log and a trace of such run?

> By default, Playwright leaves the browser opened when the tests are finished and I want to close it. Based on the information in [this article](https://playwright.dev/docs/browser-contexts) page objects in different tests are unique and they must be isolated, but it seems that in the example above these tests affect each other.

Each test does get a new page. Playwright will close the page automatically after the test is finished, you don't need to close it manually. The browser will stay open until the test worker finishes running. Perhaps waitForResponse fails because the test times out and the page gets closed?

**Comment by ovenal** [comment] 2023-08-03 08:38
I have rechecked and it seems that this problem occurs only when the tests are executed from VSCode (using Test Explorer), the tests are successfully passed if they are started using `npx playwright test` command or Playwright UI.

The bug title and the steps have been updated to highlight that it's actually only in case of running the tests from VSCode

**Closed** 2023-08-07 23:26 UTC
Labels: v1.38
