### ISSUE TITLE
VScode playwright test explorer randomly fails tests with Error: Target page, context or browser has been closed.

### ISSUE THREAD

**Issue by dgadhia** [microsoft/playwright#28412] opened 2023-11-30 00:56 UTC
Tests running fine from VScode extention until i did npm install -D @playwright/test@latest (version 40), i am expecting to run many tests from the extension (play all button in the extention)

I have tried npm init playwright@latest --yes -- --quiet --browser=chromium --browser=firefox --browser=webkit thinking it was something to do with the browser.

There is a work around for this meantime just add following line of code at the end of the test: await page.close(); 

	• Playwright Version: [40]
	• Operating System: [Windows]
	• Node.js version: [v18.16.0]
	• Visual Studio Code version: [1.84.2]
	• Playwright for VSCode extension version: [v1.0.18]
	• Browser: [Chromium]

When i Run the suite locally it skips some tests, browser remains at about:blank and returns the below message:

Error: Target page, context or browser has been closed

Call log:
navigating to "about:blank", waiting until "load"

![image](https://github.com/microsoft/playwright/assets/60907801/712069d0-1621-417e-b7ce-1e283a966a7d)
![Code_76pRsNDiIc](https://github.com/microsoft/playwright/assets/60907801/789a8b0f-5023-40fe-b7d2-053313431c00)

Please assist :) @mxschmitt @debs-obrien

**Comment by pavelfeldman** [comment] 2023-11-30 01:35
I can't reproduce this problem. After updating Playwright you should run `npx playwright install` to update the browsers, or use command palette and say "Install Playwright Browsers". You seem to be running on the latest versions of everything, so old extension should not be a problem.

**Comment by dgadhia** [comment] 2023-11-30 02:18
@pavelfeldman Thanks for Quick response. Tried both of the below:
command pallete : Install Playwright Browsers
terminal: npx playwright install

Neither of them worked.

**Comment by pavelfeldman** [comment] 2023-11-30 03:40
Do you have "Show browser" setting on or off? Does toggling it change the behavior?

Also does running from terminal work? 'npx playwright test'

**Comment by dgadhia** [comment] 2023-11-30 04:15
@pavelfeldman  I Have "Show browser" setting on. toggling it does NOT change the behavior.

running 'npx playwright test' from terminal works fine

**Comment by pavelfeldman** [comment] 2023-11-30 18:16
I see. I still can't repro it. Could you share a repo or a zip file that contains a faulty project that manifests this issue? Did you try re-creating this issue in a clean environment?

**Comment by eshaparenko** [comment] 2023-12-01 15:23
Have the same issue after updating from 1.39.1 to 1.40 or 1.40.1

In my case every second test of the .spec file failed with error:
Error: Target page, context or browser has been closed
Call log:
  - navigating to "about:blank", waiting until "load"

**Comment by pavelfeldman** [comment] 2023-12-04 17:23
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Closed by pavelfeldman** 2023-12-04 17:23 UTC

**Comment by xcrzx** [comment] 2023-12-04 18:49
I'm seeing the same error:

```
    Error: Target page, context or browser has been closed
    Call log:
      - navigating to "about:blank", waiting until "load"
```

This occurs every other test run in VS Code when the 'show browser' setting is enabled. The first run succeeds when the browser is initially closed, but the second run, which reuses the open browser, consistently fails. Then the next run succeeds and then the pattern repeats. It looks like this:

<img width="331" alt="image" src="https://github.com/microsoft/playwright/assets/1938181/1b003175-135a-4c68-bd76-764a4b03dd4f">


This issue began after updating to version `1.40.1`.

**Comment by dgadhia** [comment] 2023-12-11 01:16
@pavelfeldman, the issue is not resolved and therefore this bug is not closed :( . Please re-open the bug as I have messaged you on discord Aswell for a call to show you the code. However, no response from your end. Looking forward for a call. The contains confidential information. PLEASE! message me/call thanks.

**Comment by hananurrehman** [comment] 2024-02-01 13:52
Still having these issues. For me the web page goes blank on firefox
![image](https://github.com/microsoft/playwright/assets/16245934/b6105398-3168-4d40-a17c-416a36ab6c58)
