### ISSUE TITLE
[Bug]: Downloading to a specific location was working before the Chrome update, but now it's showing a download popup.

### ISSUE THREAD

**Issue by mani9786** [microsoft/playwright#31250] opened 2024-06-11 10:11 UTC
### Version

1.40.0

### Steps to reproduce

Version
1.41.1

Steps to reproduce
Download download = page.waitForDownload(() -> {
// Perform the action that initiates download
page.getByText("Download file").click();
});

// Wait for the download process to complete and save the downloaded file somewhere
download.saveAs(Paths.get("/path/to/save/at/", download.suggestedFilename()));

Expected behavior
it's should download on particular locations where user specified.

Actual behavior
Download popup is showing

Additional context
No response

Environment
Window's OS system :  Windows 11 Enterprise

Chrome Version : Version 125.0.6422.78

Playwright Version : playwright-1.40.0

repo link : [https://github.com/ortoniKC/playwright-java-2023/blob/master/src/test/java/day15/LearnDownload.java]

### Expected behavior

Expected to download on specific location

### Actual behavior

Window's download popup is showing 

### Additional context

Already created the issue plz have a look for your reference [https://github.com/microsoft/playwright/issues/31065]

### Environment

```shell
Window's OS system :  Windows 11 Enterpris
Chrome Version : Version 125.0.6422.78

Playwright Version : playwright-1.40.0
```

**Comment by yury-s** [comment] 2024-06-11 16:15
I tried this snippet https://github.com/ortoniKC/playwright-java-2023/blob/master/src/test/java/day15/LearnDownload.java and it works just fine with Playwright 1.44.0 - the file is downloaded as specified.

**Comment by mani9786** [comment] 2024-06-12 03:42
Thanks for your response. I appreciate your effort.

**Comment by RevaJak** [comment] 2024-06-12 13:08
I am also facing same issue. But intermittently it is working. Not sure how to resolve it.

**Comment by yury-s** [comment] 2024-06-12 15:27
We need to be able to reproduce the problem to make this report actionable. Could you share a minimal reproducible example which we could run locally?

**Comment by yury-s** [comment] 2024-06-12 15:29
Closing this report as we were not able to reproduce the problem and cannot act on it. 

@RevaJak feel free to open a new bug with a self-contained repro.

**Closed by yury-s** 2024-06-12 15:29 UTC
