### ISSUE TITLE
[BUG] Playwright codegen is not working on iPhone 13 device

### ISSUE THREAD

**Issue by zhengcling** [microsoft/playwright#23643] opened 2023-06-11 10:50 UTC
Context:

Playwright Version: 1.35.0
Operating System: windows x64
Node.js version:  16.15.0
Browser: All
Code Snippet

npx playwright codegen --device="iPhone 13" https://www.baidu.com

Describe the bug

[Error: Couldn't connect to server
=========================== logs ===========================
navigating to "https://www.baidu.com/", waiting until "load"
============================================================]

After the device configuration is removed, the operation is successful.

**Comment by aslushnikov** [comment] 2023-06-12 18:35
@zhengcling this doesn't reproduce for me locally. It also could be that baidu is employing bot-evasion techniques, thus the behavior.

Since this would fall outside of the scope of the project, I'll have to close this. If you think we still can be helpful, please re-file with an example that we can run locally and that doesn't use third-party internet properties!

**Closed by aslushnikov** 2023-06-12 18:35 UTC
