### ISSUE TITLE
[BUG]playwright._impl._api_types.Error: Browser closed.

### ISSUE THREAD

**Issue by jljdyc** [microsoft/playwright#23251] opened 2023-05-24 06:47 UTC
Who knows how to solve this issue?
If channel="chrome" remove will use chromium open browser is successful

from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(
        headless=False,
        channel="chrome"
    )
    page = browser.new_page()
    page.goto("https://www.playwright.dev/")
    print(page.title())

![1](https://github.com/microsoft/playwright/assets/44834375/b6c2f966-ffa9-4e9e-9a7f-e332f5f611af)
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> C:\Users\yc\AppData\Local\Google\Chrome\Application\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=C:\Users\yc\AppData\Local\Temp\playwright_chromiumdev_profile-aMfUHj --remote-debugging-pipe --no-startup-window
<launched> pid=9412
=========================== logs ===========================
<launching> C:\Users\yc\AppData\Local\Google\Chrome\Application\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCook

**Comment by dgozman** [comment] 2023-05-24 21:45
@jljdyc Browser is closing for some reason. Try running the command line from the logs yourself, does it work? Perhaps you have a policy or an extension that interferes with Playwright? See the [danger note here](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge), and [this paragraph](https://playwright.dev/docs/troubleshooting#incompatible-microsoft-edge--google-chrome-policy-settings).

**Comment by jljdyc** [comment] 2023-05-27 12:06
> @jljdyc Browser is closing for some reason. Try running the command line from the logs yourself, does it work? Perhaps you have a policy or an extension that interferes with Playwright? See the [danger note here](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge), and [this paragraph](https://playwright.dev/docs/troubleshooting#incompatible-microsoft-edge--google-chrome-policy-settings).

Yes,I will check it. thanks

**Comment by mxschmitt** [comment] 2023-06-02 19:54
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.

**Closed by mxschmitt** 2023-06-02 19:54 UTC
Labels: triaging
