### ISSUE TITLE
[UI] [VSCode] Exclude folders from lookup in monorepo settings

### ISSUE THREAD

**Issue by ennioVisco** [microsoft/playwright#26458] opened 2023-08-14 08:05 UTC
### System info
- Playwright Version: [v1.35.1]
- Other info: `ms-playwright.playwright@v1.0.15`

 

**Steps**
- Add playwright in a package called `e2e`
- Install the VS Code extension

**Expected**
Visualize in the Test Explorer a category called Playwright containing only the `e2e` package. 

**Actual**
<img width="208" alt="image" src="https://github.com/microsoft/playwright/assets/740025/d9f5dc92-183d-46f3-9b1c-13cff26739b1">

**Comment by mxschmitt** [comment] 2023-08-16 09:20
Hi! There should never be empty folders shown in the Testing Explorer. Do you mind sharing a minimal reproducible with us?

I tried to have an empty folder and a folder with a ts file in it which does not get used, but was unable to repro.

Do you want to hide it because of aesthetic reasons or because of performance reasons?

**Comment by mxschmitt** [comment] 2023-08-17 10:03
Thanks for looking into a repro, I tried it with the suggestions above, but wasn't able to repro.

**Comment by yury-s** [comment] 2023-08-22 00:56
Closing per the response above. We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a self-contained repro and link it to this one.

**Closed by yury-s** 2023-08-22 00:56 UTC
Labels: triaging

**Comment by ennioVisco** [comment] 2023-08-24 11:55
> Closing per the response above. We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a self-contained repro and link it to this one.

What kind of absurd policy is this?
I'll provide a repro when I have time, or it could be that someone else might jump in the issue and do that. That's how open source software works.

This opening/closing issues just because a week passed looks like unreasonable unneeded bureaucracy that helps no one.

**Comment by tinutmap** [comment] 2023-11-17 20:37
I landed here from the Google search as I had similar question, not really a big deal but wanted to upvote for the OP and to reopen the issue as I have similar request. Here's the screenshot. Sorry, can't share the repo as it's under NDA.

![image](https://github.com/microsoft/playwright/assets/58572508/094050a8-1e2c-484a-ad0a-5392190acce3)
