### ISSUE TITLE
[BUG]The screenshot results are inconsistent between headless and UI modes.

### ISSUE THREAD

**Issue by lujing-booker** [microsoft/playwright#27033] opened 2023-09-13 06:57 UTC
### System info
- Playwright Version: 1.37.1
- Operating System: macOS 11.2.1
- Browser: Chromium
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Test file (self-contained)**

```js
expect(page.locator('.ant-drawer-body')).toHaveScreenshot(`${name}.png`)
```

**Steps**
- [Run the test]

**Expected**
<img width="664" alt="image" src="https://github.com/microsoft/playwright/assets/143052434/4500ac31-a7ec-45a1-bfed-9348e27532b3">

**Actual**

<img width="666" alt="image" src="https://github.com/microsoft/playwright/assets/143052434/5dcd695d-8db1-49f7-90b4-d97e404f6ccc">

The text is not in bold style in headless mode

**Comment by dgozman** [comment] 2023-09-13 15:55
We need more information to act on this issue. Could you please provide a repro that we can run locally?

**Comment by 627668410** [comment] 2023-09-14 03:31
> We need more information to act on this issue. Could you please provide a repro that we can run locally?我们需要更多信息来解决这个问题。您能否提供我们可以在本地运行的重现？

I have provided my source code demo and test report in the repository https://github.com/627668410/playwright-test. The existing screenshots are saved in UI mode. You can run npm run report to see the difference between headless mode and UI mode. Looking forward to your feedback.

**Comment by dgozman** [comment] 2023-09-14 22:51
@627668410 Unfortunately, I was not able to reproduce:

```sh
npx playwright test -u      # update expectations on my machine
npx playwright test         # passes in headless mode
npx playwright test --ui    # run the test - passes in UI mode
```

Alternatively:
```sh
rm e2e/list.spec.ts-snapshots/list0-chromium-darwin.png
npx playwright test --ui    # run the test which updates expectation on my machine
npx playwright test --ui    # run the test again - passes in UI mode
npx playwright test         # passes in headless mode
```

**Comment by 627668410** [comment] 2023-09-15 05:50
> Unfortunately, I was not able to reproduce

That's unfortunate.
When I run it using Jenkins, I didn't encounter this issue on the Linux version. It's possible that only my OS version is having trouble. By the way, speaking of screenshots, is there a way to configure them to be OS-independent? I'd prefer to maintain a single image. Is that possible now?

**Comment by dgozman** [comment] 2023-09-15 15:35
> But the Chinese characters in the screenshot sometimes appear as squares.

This usually indicates font loading problems. Text rendering may fallback to the default font which is different on each OS. I'd recommend making sure the fonts you use covers all the characters you need.

> is there a way to configure them to be OS-independent

You can configure where screenshots are stored via [`snapshotPathTemplate`](https://playwright.dev/docs/api/class-testproject#test-project-snapshot-path-template). By default it includes OS component, but you can just put everything to a single place. That said, screenshots from different OSes rarely match, so be careful.

**Comment by dgozman** [comment] 2023-09-18 02:07
Closing as per above. If you still encounter problems, please file a new issue with a repro and link to this one.

**Closed by dgozman** 2023-09-18 02:07 UTC
Labels: triaging

**Comment by 627668410** [comment] 2023-09-18 02:24
> This usually indicates font loading problems. Text rendering may fallback to the default font which is different on each OS. I'd recommend making sure the fonts you use covers all the characters you need.

Thank you very much for your response. Regarding this issue, in my trace, the text rendering is normal, but in the screenshot, it appears as squares. Is this kind of inconsistency normal?

**Comment by dgozman** [comment] 2023-09-18 03:52
> Regarding this issue, in my trace, the text rendering is normal, but in the screenshot, it appears as squares. Is this kind of inconsistency normal?

That is probably because you record trace in headless and view it in headed browser. Or maybe you record on one OS, and view on a different OS. This is an expected inconsistency, although inconvenient sometimes.

**Comment by 627668410** [comment] 2023-09-18 05:44
> That is probably because you record trace in headless and view it in headed browser. Or maybe you record on one OS, and view on a different OS. This is an expected inconsistency, although inconvenient sometimes.

Thank you very much for your response. However, this inconsistency has indeed posed some challenges for troubleshooting.
