### ISSUE TITLE
[BUG] Playwright Firefox (nightly) and webkit won't open popup and stuck at about:blank

### ISSUE THREAD

**Issue by sanbornsen** [microsoft/playwright#23147] opened 2023-05-18 20:29 UTC
### System info
- Playwright Version: [v1.33.0]
- Operating System: [macOS 13.2, ]
- Browser: [All, Firefox, WebKit]
- Other info: It works fine on chromium but not on firefox or webkit. This started happening when I upgraded @playwright/test from `1.27.0` to `1.33.0`

### Source code

```
const [popup] = await Promise.all([page.waitForEvent('popup'), page.click(onClickSelector)]);

  let timeout = 0;
  while (!popup.url().includes('http') && timeout < 10) {
    console.log(popup.url());
    await popup.waitForTimeout(1000);
    timeout++;
  }
```
Where `popup.url()` is always `about:blank`.

- [ ] I provided exact source code that allows reproducing the issue locally.

**Comment by sanbornsen** [comment] 2023-05-18 21:03
It could a problem with Nightly version being used. I see for `@playwright/test` `1.27.1` the Nightly version is `105.0.1` but for `@playwright/test` `1.33.0` the Nightly version is `112.0`. Is there a way I can specify Nightly version in Playwright?

**Comment by dgozman** [comment] 2023-05-19 17:44
@sanbornsen Playwright only works with the [bundled Firefox version](https://playwright.dev/docs/browsers#firefox), so you cannot specify your own Nightly.

Unfortunately, I cannot reproduce the issue given the short snippet above, and so we cannot fix it. If you could provide a self-contained repro that we can just run, that would be great. Otherwise I'll have to close this issue.

**Comment by sanbornsen** [comment] 2023-05-19 18:29
Okay. I'll try to create a complete code example, give me a day.

**Comment by sanbornsen** [comment] 2023-05-19 19:09
I pushed it to GH in case you want to avoid setting up 

https://github.com/sanbornsen/playwright-test

**Comment by dgozman** [comment] 2023-05-22 15:22
@sanbornsen Thank you for the repro! There are known inconsistencies between browsers and headed/headless mode when opening/downloading PDFs. Merging into #7822.

**Closed by dgozman** 2023-05-22 15:22 UTC
Labels: triaging

**Comment by fabiogoshippo** [comment] 2023-05-25 15:17
@sanbornsen I have exactly the same issue for the same reason (migrating from 1.27 to the latest). Any suggestion on how to fix this? We open and download the pdf then give it to a npm pagage to extract the text and then assert its content

**Comment by fasatrix** [comment] 2023-05-25 17:21
> @sanbornsen I have exactly the same issue for the same reason (migrating from 1.27 to the latest). Any suggestion on how to fix this? We open and download the pdf then give it to a npm pagage to extract the text and then assert its content

+1 I would like to have a workaround at least for this. Moved to latest Playwright and got the4 problem

**Comment by sanbornsen** [comment] 2023-05-25 23:21
I tried listening on the 'response' even and that worked.

```
const [popup] = await Promise.all([page.waitForEvent('popup'), page.click('button-selector')]);
  let targetUrl = '';
 
  popup.on('response', (response) => {
    targetUrl = response.url();
  });

  let timeout = 0;
  while (!targetUrl && timeout < 10) {
    // Wait for the PDF to load into the popup window
    // eslint-disable-next-line no-await-in-loop
    await popup.waitForTimeout(1000);
    timeout++;
  }

  // Log out the URI to the PDF
  // eslint-disable-next-line no-console
  console.log(targetUrl);
  ```
