### ISSUE TITLE
[BUG] Chromium is not closed in headful mode

### ISSUE THREAD

**Issue by Kremliovskyi** [microsoft/playwright#6123] opened 2021-04-07 15:05 UTC
**Context:**
- Playwright Version: [1.10.0]
- Operating System: [Windows]
- Node.js version: [v15.14.0]
- Browser: [Chromium]
- Extra: [issue is not reproducible for firefox, webkit and headless chromium]

When I am just doing this 
```js
import playwright from 'playwright';

(async () => {
    const browser = await playwright.chromium.launch({
        headless: false,
        timeout: 120000,
        logger: {
            isEnabled: (name, severity) => name === 'browser',
            log: (name, severity, message, args) => console.log(`${name} ${severity} ${message}`)
        }
    });
    const context = await browser.newContext();
    const page = await context.newPage();

    await page.goto('some url');

    await page.fill("//input[@name='email']", "my username");
    await page.fill("//input[@name='password']", "my password");
    await page.click("//button[@class='primary']");

    await page.waitForSelector("table.generic-table.findings-list-table")

    await page.screenshot({
        path: "./screenshots/1.png",
        fullPage: true
    })

    console.log("here")
    await browser.close();
    console.log("after close")
})();
```

I am running into this error that appears after a minute playwright tries to close the browser. It happens every time when browser command close starts and is not reproducible for firefox and webkit or headless chromium. GUI is closed but the node process is still running. Task manager shows chromium running and consuming 20-30 percent of cpu.
```
[Error: EPERM: operation not permitted, unlink 'C:\Users\AKREML~1\AppData\Local\Temp\playwright_chromiumdev_profile-dhO1Xy\CrashpadMetrics-active.pma'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\AKREML~1\\AppData\\Local\\Temp\\playwright_chromiumdev_profile-dhO1Xy\\CrashpadMetrics-active.pma'
}
```

I can not share the url. Is there anything else I can share with you ?

**Comment by JoelEinbinder** [comment] 2021-04-08 17:46
We have trouble disabling crashpad in chromium, and sometimes if it is active when you are closing it prevents the close. That is a difficult to fix bug that I am looking into.

However, the fact that crashpad is active is probably a sign that something is indeed crashing inside Chromium. Can you try to run your command with the environment variable `DEBUG=pw:browser` and see what it prints? Thanks!

**Comment by Kremliovskyi** [comment] 2021-04-09 05:30
@JoelEinbinder I also noticed that this error starts to appear starting from second run of this script after I reboot PC. The first output is the same except for the error and the process never finishes.

```
set DEBUG=pw:browser&&node PlayWrightTest.js
  pw:browser <launching> C:\Users\akremlovskyi\AppData\Local\ms-playwright\chromium-857950\chrome-win\chrome.exe --disable-background-networking --enable-features=
NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phis
hing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=Translat
eUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup
-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-au
tomation --password-store=basic --use-mock-keychain --user-data-dir=C:\Users\AKREML~1\AppData\Local\Temp\playwright_chromiumdev_profile-LZBn06 --remote-debugging-p
ipe --no-sandbox --no-startup-window +0ms
  pw:browser <launched> pid=17224 +3ms
  pw:browser [pid=17224][err] [17224:16956:0409/081451.162:ERROR:device_event_log_impl.cc(214)] [08:14:51.161] USB: usb_device_handle_win.cc:1054 Failed to read de
scriptor from node connection: A device attached to the system is not functioning. (0x1F) +4s
  pw:browser [pid=17224][err] [17224:16956:0409/081451.164:ERROR:device_event_log_impl.cc(214)] [08:14:51.163] USB: usb_device_handle_win.cc:1054 Failed to read de
scriptor from node connection: A device attached to the system is not functioning. (0x1F) +3ms
here
  pw:browser [pid=17224] <gracefully close start> +27s
  pw:browser [pid=17224] <process did exit: exitCode=0, signal=null> +377ms
[Error: EPERM: operation not permitted, unlink 'C:\Users\AKREML~1\AppData\Local\Temp\playwright_chromiumdev_profile-LZBn06\CrashpadMetrics-active.pma'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\AKREML~1\\AppData\\Local\\Temp\\playwright_chromiumdev_profile-LZBn06\\CrashpadMetrics-active.pma'
}
  pw:browser [pid=17224] <gracefully close end> +1m
after close
```

**Comment by JoelEinbinder** [comment] 2021-04-09 05:34
Thanks for the extra logs. Unfortunately I don't see anything suspicious looking there. Hopefully we can land a change in chromium that lets unless completely disable the crash pad. Until then, you could try running playwright with a persistent context so that it doesn't delete the user data directory after every run. Or just catch and silence the error. Sorry that I don't have any better workarounds.

**Comment by yury-s** [comment] 2021-04-09 16:33
@Kremliovskyi could your you also pass a couple of extra args to Chromium for more detailed logs?
```js
    const browser = await chromium.launch({
        args: ["--enable-logging=stderr",  "--v=1"]
    });
```

The part of your log with `ERROR:device_event_log_impl.cc` is very similar to what we saw in https://github.com/microsoft/playwright-java/issues/347 where the browser also failed to close. I'm not sure if it's the cause of the problem or just a side effect. Let's see if verbose logs tell us anything interesting.

**Comment by Kremliovskyi** [comment] 2021-04-09 18:37
I added this arg and when the run started lots of terminal windows started to appear and disappear. At max there were 6 of them and when close started only one was left. Not sure if it is ok. I copied everything from the last window , substituted url to some-url and here it is 
[chromium-stderr.txt](https://github.com/microsoft/playwright/files/6287821/chromium-stderr.txt)

**Comment by Kremliovskyi** [comment] 2021-04-09 18:51
I tried different , public website to show what happens with screenshots.
When taking screenshot (in headful mode when this error appears) the website is shrinked horizontally but the website is fully visible while browser window remains the same. However in the screenshot it looks like

![1](https://user-images.githubusercontent.com/12884831/114227192-502cb100-997d-11eb-9f48-f0f7922f202b.png)

**Comment by dgozman** [comment] 2021-04-19 18:14
The screenshot issue is a separate one, see #6188.

@aslushnikov Let's try disabling crashpad on Windows.

**Comment by aslushnikov** [comment] 2021-05-18 21:47
Upstream bug & wip: https://crbug.com/1210598

**Comment by mxschmitt** [comment] 2021-05-22 17:08
Seems similar or a duplicate of https://github.com/microsoft/playwright/issues/5327 to me.

**Comment by aslushnikov** [comment] 2021-05-25 23:53
@Kremliovskyi does it repro for you reliably? Any chance you can help me reproduce this? The logs you posted are very peculiar - we don't see codepaths that would result in this behavior.

**Comment by Kremliovskyi** [comment] 2021-05-31 16:19
@aslushnikov I haven’t tried it for a while now but it did reproduce reliably, like 90% of times. I tried different scenarios and it just happens almost every test run

**Comment by aslushnikov** [comment] 2021-06-01 19:35
@Kremliovskyi  We added some more logging specifically for this problem. If by any chance you can try installing `playwright@next`, reproduce the problem and send the logs in like you did [in this comment](https://github.com/microsoft/playwright/issues/6123#issuecomment-816418605) - it'll be very helpful!

To clarify, we're talking about the "EPERM: operation is not permitted" problem with the `CrashpadMetrics-active.pma` file.

**Closed** 2021-07-16 16:03 UTC
Labels: P2-bug, os-windows, upstream, v1.14
