### ISSUE TITLE
[Bug]: Cannot read property '_object' of undefined

### ISSUE THREAD

**Issue by gilles-yvetot** [microsoft/playwright#7495] opened 2021-07-07 09:40 UTC
### Playwright version

1.12

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### Other information

Node 14.17
I am connecting to the browser thru CDP

### What happened? / Describe the bug

Sentry is reporting uncaught exceptions for me. It does not prevent my test from running (or at least I have not found a correlation).
I know where it is coming from but I could not find repro steps to reproduce that.

<img width="622" alt="Screen Shot 2021-07-07 at 11 39 03 AM" src="https://user-images.githubusercontent.com/4616013/124737102-f013bf80-df17-11eb-9453-749c19927442.png">

**Comment by mxschmitt** [comment] 2021-07-07 11:50
Does this happen for every test run? Are you using background pages? If you could trace-down the bug to a minimal reproducible, that would be awesome! (If you set the `DEBUG=pw:*` env var, it will give you very verbose logs to the stderr. These might also help but depend on your application be confidential, so if you can, you can send me them privately over to take a look. (maxschmitt[A T]microsoft[DOT]com))

Chromium version might be also helping to debug that further.

Thanks!

**Comment by gilles-yvetot** [comment] 2021-07-07 11:55
@mxschmitt thanks a lot for the quick answer. I do use background pages (I am testing an extension). They are no clear repro steps (yet) and sometimes it happens when I don't run tests. PW is still connected to the browser and I do something within the browser. I am gonna try to have better repro steps and will come back with a repo for you :)

**Comment by mxschmitt** [comment] 2021-08-18 13:43
Closing for now, since there is no repro. If you have a repro, feel free to reopen / create a new issue and reference to this one.

**Closed by mxschmitt** 2021-08-18 13:43 UTC
Labels: P3-collecting-feedback
