### ISSUE TITLE
[BUG] Locale is not correctly defined in headless mod

### ISSUE THREAD

**Issue by atemor** [microsoft/playwright#19781] opened 2022-12-29 13:57 UTC
**Context:**
- Playwright Version: **1.28.1**
- Operating System: **Mac**
- Node.js version: 16.14.0
- Browser: Chromium
- Extra: [any specific details about your environment]

I have a really odd issue encounter with my team.
It's related with the locale of the browser I use.

When I launch the command : `npm playwright test`, it's appears that it's take an 'en-EN' locale.
But when I launch `PWDEBUG=1 npm playwright test` it took the correct 'fr-FR' locale we set up on the `playwright.config.ts`

I take the correct locale only when the global-setup.ts is run headed.

Any one has a clue of what is happenin ?
It could be related to i18next

**Comment by aslushnikov** [comment] 2022-12-30 23:10
@atemor any chance you can help me reproduce this?

**Comment by atemor** [comment] 2023-01-02 10:00
Hello !
Unfortunally no.

But we find a work around.
In the global set up we set : 

`const browsers = await chromium.launch();
    const context = await browsers.newContext({
        locale: 'fr-Fr',
    });

    const page = await context.newPage();`
    
    But why does it not take the conf in the pw.config.ts ? : 

`    use: {
        /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
        actionTimeout: 0,
        locale: 'fr-FR',
        timezoneId: 'Europe/Paris',
        geolocation: { longitude: 48.858455, latitude: 2.294474 },
        /* Base URL to use in actions like `await page.goto('/')`. */
        baseURL: process.env.URL,
        /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
        storageState: './storage/admin.json',
    },
    globalSetup: require.resolve('./global-setup'),
    /* Configure projects for major browsers */
    projects: [
        {
            name: 'chromium',
            use: {
                locale: 'fr-FR',
                timezoneId: 'Europe/Paris',
                geolocation: { longitude: 48.858455, latitude: 2.294474 },
                ...devices['Desktop Chrome'],
            },
        },`

**Comment by mxschmitt** [comment] 2023-01-04 16:38
This is expected, globalSetup does not take the config into consideration. Since the globalSetup runs per whole test execution and not per project.

Closing as expected.

**Closed by mxschmitt** 2023-01-04 16:38 UTC
Labels: triaging
