### ISSUE TITLE
[BUG (or needs better documentation?)] `KEEP_ALIVE` + `PREBOOT_CHROME` doesn't store disk cache

### ISSUE THREAD

**Issue by dgtlmoon** [microsoft/playwright#17085] opened 2022-09-03 09:03 UTC
First, thanks for the amazing project!!!

**Context:**
- Playwright Version: 1.24.1
- Operating System: Linux
- Python version: 3.8
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

```python

# docker run --rm -e "PREBOOT_CHROME=true" -e "KEEP_ALIVE=true" -e "DEFAULT_USER_DATA_DIR=/tmp/my-profile" -p 3000:3000 --name browserless browserless/chrome

from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    for browser_type in [p.chromium]:
        browser = browser_type.connect_over_cdp('ws://127.0.0.1:3000')
        page = browser.new_page()
        page.goto('https://theguardian.co.uk/')
        browser.close()

```

Then after, disk cache files are non-present

```bash
$ docker exec -it browserless bash
blessuser@fff77fd5abb9:/usr/src/app$ find /tmp/my-profile/ -type f|grep -i cache
/tmp/my-profile/Default/Code Cache/wasm/index
/tmp/my-profile/Default/Code Cache/wasm/index-dir/the-real-index
/tmp/my-profile/Default/Code Cache/js/index
/tmp/my-profile/Default/Code Cache/js/index-dir/the-real-index
/tmp/my-profile/Default/GPUCache/data_1
/tmp/my-profile/Default/GPUCache/data_3
/tmp/my-profile/Default/GPUCache/data_2
/tmp/my-profile/Default/GPUCache/index
/tmp/my-profile/Default/GPUCache/data_0
```
**Describe the bug**

https://docs.browserless.io/docs/docker.html#keeping-chrome-alive
> When using KEEP_ALIVE Chrome will retain information about prior-sessions such as cookies and login contexts. You'll also need to replace browser.close() with browser.disconnect() in your puppeteer code.

Looks like there is no `browser.disconnect()` in playwright-python, so two questions I guess are

- Is `browser.disconnect()` something that can be added in the future? Should this issue be converted to [feature]?
- Is my assumption that `.disconnect()` will preserve disk cache data correct?

**What I'm really trying to solve**

Trying to find a way to make disk cache re-usable between browser contexts of the same connection URL that uses the same `--user-data-dir`

```
ws://127.0.0.1:3000?stealth=1&--disable-web-security=true&--user-data-dir=/tmp/test-user-1
```

(essentially, not having a reusable disk cache is starting to cost $ in BW :-(, I've tried solutions like grafting on `requests_cache` https://gist.github.com/dgtlmoon/6f306e321200af521f82843bd4bc9901, but that leads to other issues  )

**Comment by dgozman** [comment] 2022-09-06 21:39
@dgtlmoon If you use `connect_over_cdp`, method `browser.close()` should disconnect from the websocket and not close the underlying browser it was connected to.

I don't really know what `browser.disconnect()` those browserless docs refer to, so I am not sure how to help you. Perhaps, ask the same question on browserless issue tracker?

**Comment by dgozman** [comment] 2022-09-09 15:48
@dgtlmoon This should be easy enough to check on the side where you launch the browser, shouldn't it? Just run your snippet and see whether browser is still open? Also, connecting for the second time should fail if the browser is closed.

**Comment by dgtlmoon** [comment] 2022-09-09 16:13
@dgozman hmmmmm but that doesn't answer my question, should I expect the cache for the browser to still be in place? if not, can it be kept in place? (in other words, when the browser exits, how to retain the cache data?)

That's why I read the documents and wrote this in my report

https://docs.browserless.io/docs/docker.html#keeping-chrome-alive

> When using KEEP_ALIVE Chrome will retain information about prior-sessions such as cookies and login contexts. You'll also need to replace browser.close() with browser.disconnect() in your puppeteer code.

**Comment by dgtlmoon** [comment] 2022-09-09 16:14
In other words

I'm connecting with `--user-data-dir=/tmp/test-user-1` and have `KEEP_ALIVE` set, so why doesn't it retain the page cache information  when relaunching the browser?

Is it a documentation issue (ie, my assumption/expectations are wrong) or a bug?

**Comment by dgozman** [comment] 2022-09-09 16:20
@dgtlmoon I think we have a misunderstanding here. Playwright has no affiliation to browserless and their documentation. I don't know much about how browserless works, what `KEEP_ALIVE` means and the whole workflow you are using.

That said, I can help with browsers and Playwright. For example, if you launch Chrome and give it `--user-data-dir`, and then gracefully close Chrome without killing the process, it should retain all caches it deems important in the user data directory. I hope that helps!

**Comment by dgtlmoon** [comment] 2022-09-09 16:42
@dgozman thanks for the reply :) 

> if you launch Chrome and give it --user-data-dir, and then gracefully close Chrome without killing the process, it should retain all caches it deems important in the user data directory. I hope that helps!

Are you referring to not using headless right? like "launch Chrome" you mean locally, not via CDP headless to a browserless (https://hub.docker.com/r/browserless/chrome) server?

**Comment by dgtlmoon** [comment] 2022-09-09 16:43
Hmm I have a feeling this issue belongs on https://github.com/browserless/chrome/issues then

**Comment by dgtlmoon** [comment] 2022-09-09 16:47
Unless ofcourse https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context is related to this somehow?

**Comment by mxschmitt** [comment] 2022-09-10 14:29
I think the problem is that you create a page which includes a context (since its via browser.new_page) yourself: ` page = browser.new_page()`.

If you do this instead: `page = browser.contexts[0].pages[0]` it will use the default context and it's page and then it should work. 

It's right, that Chromium will close contexts which were created in CDP sessions by Playwright on disconnect, [code pointer](https://github.com/microsoft/playwright/blob/04ed32e53157c08c56cc4e5044ccedaec8379b68/packages/playwright-core/src/server/chromium/crBrowser.ts#L109).

**Comment by mxschmitt** [comment] 2022-09-15 09:20
Closing as per above which should work, if not, please re-file!

**Closed by mxschmitt** 2022-09-15 09:20 UTC
Labels: triaging

**Comment by dgtlmoon** [comment] 2022-09-15 09:35
@mxschmitt sorry low on time, but I will revisit this soon, thanks for your help as always!
