### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by waqas-glasswall** [microsoft/playwright#29020] opened 2024-01-17 13:08 UTC
### System info
- Playwright Version: [v1.39.0]
- Operating System: [Windows 10 Pro, macOS 13.4]
- Browser: [Desktop App - Electron]
- Other info: 

### Source code
/** 
 * End to end tests with Playwright script for Electron
 */

import { expect, test } from '@playwright/test'
import { ElectronApplication, Page, _electron as electron } from 'playwright'

let electronApp: ElectronApplication;
let page: Page;

test.beforeAll(async () => {
  const APP_EXECUTABLE_PATH = '/path';

  electronApp = await electron.launch({
    executablePath: APP_EXECUTABLE_PATH
  })

  const appPath = await electronApp.evaluate(async ({ app }) => {
    // This runs in the main Electron process, parameter here is always
    // the result of the require('electron') in the main app script.
    return app.getAppPath();
  });
  
  console.log(appPath);

  const windows = await electronApp.windows();
  console.log(windows);

  page = await electronApp.firstWindow({ timeout: 30000 });

})

test.afterAll(async () => {
  await electronApp.close()
})

test("on click of links on sidebar, relative pages should load", async () => {
  console.log('First test.');

  await page.waitForTimeout(2000);
});

  "devDependencies": {
    "@playwright/test": "^1.39.0",
    "electron": "^27.0.2",
    "electron-playwright-helpers": "^1.7.0",
    "path": "^0.12.7",
    "playwright": "^1.39.0",
    "playwright-core": "^1.39.0",
    "typescript": "^5.2.2"
  },

**Steps**
- npm run e2e

"scripts": {
    "e2e": "DEBUG=pw:api,pw:browser playwright test"
  }

**Expected**

App should launch but failing.

**Actual**
 pw:api <= electron.launch succeeded +1s
  pw:api => electronApplication.evaluate started +2ms
  pw:api <= electronApplication.evaluate succeeded +7ms
[]
  pw:api => electronApplication.firstWindow started +3ms
  pw:api <= electronApplication.firstWindow failed +30s
  pw:api => selectors.setTestIdAttribute started +30ms
  pw:api => electronApplication.close started +3ms
  pw:api <= selectors.setTestIdAttribute succeeded +4ms
  pw:browser [pid=4027][err] Waiting for the debugger to disconnect... +30s
  pw:browser <ws disconnecting> ws://127.0.0.1:51047/02781d7e-edb9-41d8-a74f-5c526658aab1 +0ms
  pw:browser <ws disconnected> ws://127.0.0.1:51047/02781d7e-edb9-41d8-a74f-5c526658aab1 code=1005 reason= +3ms
  pw:browser [pid=4027] <process did exit: exitCode=0, signal=null> +20ms
  pw:browser [pid=4027] starting temporary directories cleanup +0ms
  pw:browser <ws disconnected> ws://127.0.0.1:51049/devtools/browser/347278af-a5a3-4692-87a8-a944ab74e566 code=1006 reason= +1ms
  pw:api <= electronApplication.close failed +28ms
  pw:browser [pid=4027] finished temporary directories cleanup +5ms

  1) main.spec.ts:37:1 › on click of links on sidebar, relative pages should load ──────────────────

    TimeoutError: electronApplication.firstWindow: Timeout 30000ms exceeded while waiting for event "window"

      27 |   console.log(windows);
      28 |
    > 29 |   page = await electronApp.firstWindow({ timeout: 30000 });
         |                            ^
      30 |
      31 | })
      32 |

        at /Users/qbatch/meteor-e2etests/tests/main.spec.ts:29:28

It's failing on first Window. As can be seen fails to firstWindow.

**Comment by mxschmitt** [comment] 2024-01-17 15:54
duplicate of https://github.com/microsoft/playwright/issues/29021.

**Closed by mxschmitt** 2024-01-17 15:54 UTC

**Comment by waqas-glasswall** [comment] 2024-01-17 18:01
@mxschmitt

pw:api => electronApplication.firstWindow started +3ms
pw:api <= electronApplication.firstWindow failed +30s

Window opening getting timedout here.

What should i provide with to re produce this ?

**Comment by mxschmitt** [comment] 2024-01-17 18:03
A small self-contained reproduction which we can run locally.

**Comment by waqas-glasswall** [comment] 2024-01-17 18:09
Ok i am pushing as a repository shortly and linking here. I am like stuck on this for a whole day now on this.

**Comment by waqas-glasswall** [comment] 2024-01-17 18:28
@mxschmitt 

Git Repo: https://github.com/waqas-glasswall/test-playwright

Commands to reproduce in main directory:
```
npm i
npm run e2e
```

Make sure update the path to any test app developed with electron and installed in Mac:

APP_EXECUTABLE_PATH = '/Applications/MyApp.app/Contents/MacOS/MyApp';
