### ISSUE TITLE
[BUG] Local Run: viewport: {width: 1920, height: 1080} opens the browser window with deviation to right and down

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#8352] opened 2021-08-21 13:57 UTC
**Context:**
- Playwright Version: 1.14.0
- Operating System: Windows
- Node.js version: v 14.16.1
- Browser: Chromium (chrome)

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
import { PlaywrightTestConfig } from "@playwright/test";


const config: PlaywrightTestConfig = {
  retries: 1,
  timeout: 180000,
  globalTimeout: 300000,
  reporter: [["./my-reporter.ts"], ["list"], ["junit", { outputFile: "reports/test-results.xml" }]],
  use: {
    trace: 'on',
    screenshot: 'on',
    viewport: {width: 1920, height: 1080},
    video: {
      mode: "on",
      size: {
        width: 1920,
        height: 1080
      }
    },
    contextOptions: {
      viewport: {width: 1920, height: 1080}
    },
    // Browser options   
    launchOptions: {     
      channel: 'chrome', //Changed back to chromium due to the issue with chrome on CI
      headless: false,
      
      //args: ['--start-maximized']
    },
    //slowMo: 0,
  },
};

export default config;

```

**Describe the bug**

**Local Run:**
I try to open the browser window in the maximized resolution.
I tried to open via viewport (viewport: {width:1920, height: 1080} definition but it opens the browser window with deviations to right and down (can be seen in the attached screenshot)

![image](https://user-images.githubusercontent.com/52656401/130323904-e97898f3-38a4-4fdb-8cf7-1119f58e7696.png)

Does it an issue with the resolution calculation? Or something from my side?

**Comment by pavelfeldman** [comment] 2021-08-21 17:22
This is expected behavior. If you want full screen mode, you can upvote https://github.com/microsoft/playwright/issues/1086!

**Comment by AlexKomanov** [comment] 2021-08-22 05:14
@pavelfeldman 
Thanks. Will upvote with pleasure!

**Comment by pavelfeldman** [comment] 2021-08-22 17:30
Closing as a dupe of #1086

**Closed by pavelfeldman** 2021-08-22 17:30 UTC
