### ISSUE TITLE
[BUG]: Playwright VS Code extension doesn't works

### ISSUE THREAD

**Issue by EgonBolton** [microsoft/playwright#18070] opened 2022-10-13 19:05 UTC
# The Problem
I can use the command line to run tests.
I can also use the VS Code extension to run tests on an entire file in debug mode.

What I can't is:
- Display and view the individual tests of a file.
- Display the buttons to run tests inside the file.
- Run the tests in headless mode.

# Steps To Reproduce
For your reference, the project I am using it on is Lexical (version 0.5.0). So this would be the steps to reproduce the error:

1. `git clone https://github.com/facebook/lexical`
2. `cd lexical`
3. `npm install`
4. `npm run dev`
5. Go to the VS Code "Tests" tab, and expand the test tree until you reach the file level, it will not expand further. Go to a file with tests. Where each test starts there should be a button to run it, but there isn't.

# What I have tried

I tried:
- I have tried with another test project and the extension works.
Because of that, I assumed it would be a configuration issue, so [I posted it on Lexical](https://github.com/facebook/lexical/issues/3167). This issue was closed because it works for them and they consider it to be an error in the VS Code extension.
- disabling all other extensions except Playwright.
- Reinstalling VS Code.
- Replicate the process from another device.

In no case I can solve the problem.

# The current behavior
https://www.loom.com/share/e5077edd617b4ed4bb9ae20493fe847d

# The expected behavior
https://www.loom.com/share/50079aa607d44b1ab8dbffbd6ea90020

# Information
- Playwright Version: 1.23
- Operating System: Windows 11
- Node.js version: 16.13.0
- Visual Studio Code version: 1.72.1
- Playwright for VSCode extension version: 0.2.13
- Browser: All, Chromium, Firefox, WebKit
- Extra: [any specific details about your environment]

**Comment by yury-s** [comment] 2022-10-13 21:40
Hm, I cannot reproduce it either, the tests do start if I click on the green triangle icon. I see 'Jest Test Provider (lexical)` in the test panel on your video, I don't have such thing when running the tests from VS Code. Do you have a clue what adds it? I suspect it may be interfering with playwright VSCode extension.

**Comment by EgonBolton** [comment] 2022-10-13 22:02
Thanks for answering! Oh, wow.
What you mention is the Jest extension, which I have tried removing it too.
I'm running out of ideas :'(

**Comment by yury-s** [comment] 2022-10-13 23:47
Did you manage to remove it? Asking as it's on the video. Since it works on my machine with vscode 1.72.2 and you mentioned that it worked for other folks, the difference is most likely in one of the extensions.

**Comment by EgonBolton** [comment] 2022-10-14 04:04
Yes, I've tried removing the Jest extension, and what you mention disappears, but it still doesn't work.

I have tried on 2 different devices reinstalling everything from scratch and the error is reproduced exactly on both. And besides, Playwright works on another project. For those reasons I thought it was a project configuration problem.

But neither you nor the people at Lexical can reproduce the error. I don't know what we'll be doing differently. Is there a step I'm missing in "steps to reproduce"? Anything else I need to do to make it work?

**Comment by EgonBolton** [comment] 2022-10-14 04:35
Another strange fact.
If I click on "run test" it does not detect the tests nor does it let me expand the tests in the file.
Instead, if I click "Debug test" they can be executed, and I can expand and see the tests of each file but only for a couple of seconds.

https://www.loom.com/share/4db6e2a5c1664318b45fdedd9d7b9c90

**Comment by yury-s** [comment] 2022-10-14 22:14
> Now the only drawback is that when running the tests in debug mode, the inspector does not appear and they are not paused. It's like a simple headed test.

The inspector is not supposed to show up in that case. You can set a regular breakpoint in VSCode and do [step-by-step debugging](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright#debug-step-by-step-explore-selectors). I'm closing this issue as the original problem was resolved. Please file a new one with the repro if you experience issues with the debugger.

**Closed by yury-s** 2022-10-14 22:14 UTC
Labels: triaging
