### ISSUE TITLE
[BUG] page.waitForResponse() returns 307 (no body) in CI

### ISSUE THREAD

**Issue by moarwick** [microsoft/playwright#28191] opened 2023-11-16 15:49 UTC
### System info
- Playwright Version: 1.39
- Operating System: ubuntu-20.04 (CI)
- Browser: Chromium

### Source code
```JS
    const matchedRespPromise = page.waitForResponse(resp => {
      const operationName = resp.request().postDataJSON()?.operationName;
      const isMatch = operationName === 'GetCompanyMediaWeeks';
      return isMatch;
    });
    page.goto(pageUrl, {waitUntil: 'domcontentloaded'});
    const resp = await matchedRespPromise;
    console.warn(resp.status()); // <- 307, see below
    console.warn resp.headers()); // <-- see below
    const respJson = await resp.json(); // <-- no body in resp, fails
```
![logs](https://github.com/microsoft/playwright/assets/4442541/f01e3bd8-05a5-4fc9-9785-d35dbf0ef140)

**Config file**

```js
export default defineConfig({
  testDir: './playwright',
  fullyParallel: true,
  forbidOnly: false, // !!process.env.CI,
  retries: process.env.CI ? 3 : 0,
  workers: process.env.CI ? 1 : 1, // : undefined
  reporter: 'html',
  use: {
    baseURL: 'http://localhost:3000',
    trace: 'on-first-retry',
  },
  expect: {
    timeout: 10 * 1000,
  },
  projects: [
    {
      name: 'chromium',
      testMatch: /.*\.test\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        bypassCSP: true,
        launchOptions: {
          args: ['--disable-web-security'],
        },
      },
    }
  ],
  webServer: {
    command: 'env; yarn dev',
    url: 'http://localhost:3000',
    timeout: 120 * 1000,
    reuseExistingServer: !process.env.CI,
  },
});
```

Trialing Playwright as a Cypress replacement. All works fine locally and in CI, except for tests utilizing `page.waitForResponse` to intercept responses from our staging Graphql BE endpoint. In CI, these intercepts are returning `307` and no body, so those tests fail.

I was able to find a few issues describing this to be a Chrome request 'hijack' problem, however, the tests are running fine otherwise, whenever not intercepting (requests are succeeding, returning proper data to the browser/app), so it's strange it manifests itself when `waitForResponse` is used. Also, I made sure our server does not add a `Strict-Transport-Security` header in for staging CI at all.

**Comment by mxschmitt** [comment] 2023-11-16 19:39
This is most likely caused since you were adding the `Strict-Transport-Security` header before as per https://github.com/microsoft/playwright/issues/15613#issuecomment-1183598163. So the browser thinks your website must be served over https.

Closing since this is not caused by Playwright.

**Closed by mxschmitt** 2023-11-16 19:39 UTC

**Comment by moarwick** [comment] 2023-11-17 00:32
well, per my description, we do *not* add that header @mxschmitt. i was hoping for some other ideas :/

> I made sure our server does not add a `Strict-Transport-Security` header

**Comment by teosarca** [comment] 2025-02-13 22:07
having exactly the same problem. wondering how others are running playwright inside a docker container....
