### ISSUE TITLE
[BUG] fill two inputs one by one will clear prev input value

### ISSUE THREAD

**Issue by FrankWang117** [microsoft/playwright#15925] opened 2022-07-25 16:25 UTC
**Context:**
- Playwright Version: 1.20.1
- Operating System: Mac
- Node.js version: 16.15.0
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {

  // main testing is
       await page.fill('input[name="display_name"]', mockDisplayName);
       await page.fill('input[name="key"]', mockKey);

})();
```

**Describe the bug**
when I fill inputs one by one,something is wrong.
When the first fill done,this mockDisplayName is in input that name is display_name,but when run section fill,the first input value in empty and the second input not fill text.

**Comment by pavelfeldman** [comment] 2022-07-25 20:37
It passes my test, any reproduction you can report? Your page is probably updating itself after you filled the first field. Try running your test manually + emulating slow 3g connection and it is likely that your input will get reset. I.e. looks like your page has a bug that erases the user input.

**Comment by pavelfeldman** [comment] 2022-07-28 18:06
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2022-07-28 18:06 UTC
Labels: triaging

**Comment by FrankWang117** [comment] 2022-07-29 01:49
@pavelfeldman thx a lot,it is my page bug.
