### ISSUE TITLE
[BUG] Safebrowsing doesn't work

### ISSUE THREAD

**Issue by Lvl4Sword** [microsoft/playwright#26446] opened 2023-08-13 00:24 UTC
### System info
- Playwright Version: 1.36.0
- Operating System: Ubuntu 22.04 LTS
- Browser: Firefox
- Other info: Python-specific

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://gist.github.com/Lvl4Sword/b015a7a595227e5c1e12f8158994fc91

**Expected**

Safebrowsing should flag the site ( https://testsafebrowsing.appspot.com/s/phishing.html ) as phishing

**Actual**

Safebrowsing doesn't seem to be enabled / available. This isn't posted anywhere, and isn't conveyed properly if this is "`by design`".

**Comment by mxschmitt** [comment] 2023-08-14 17:22
What is your scenario?

**Comment by Lvl4Sword** [comment] 2023-08-14 17:45
@mxschmitt 
I'm not sure what you mean. Just trying to get Safebrowsing to work.

**Comment by mxschmitt** [comment] 2023-08-14 17:58
We need unfortunately a clear use-case and testing scenario to be able to act on it. So for now I'm closing it as working as intended.

**Closed by mxschmitt** 2023-08-14 17:58 UTC
Labels: triaging

**Comment by Lvl4Sword** [comment] 2023-08-14 17:59
?
My usecase is Safebrowsing working.
