### ISSUE TITLE
[Feature]: add page method start record

### ISSUE THREAD

**Issue by pan-alexey** [microsoft/playwright#30613] opened 2024-04-30 20:03 UTC
### 🚀 Feature Request

We can start new record session (screencast)[https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-startScreencast] in ffmpeg, if user 

### Example

```
 await page.startRecord({path: string}); // start record screencast by ffmpeg
 await page.stopRecord()
```

### Motivation
Maybe user need create video by request (Example scenario. Open page -> Choose option (adress or lang) -> [start record] -> click to submit -> [stop record])

**Comment by dgozman** [comment] 2024-04-30 20:40
Closing as a duplicate of #28183.

**Closed by dgozman** 2024-04-30 20:40 UTC
