### ISSUE TITLE
[BUG] test.skip() with a function can only be called inside describe block

### ISSUE THREAD

**Issue by Tyriar** [microsoft/playwright#8688] opened 2021-09-03 14:52 UTC
**Context:**
- Playwright Version: `"@playwright/test": "^1.14.1"`, `"playwright": "^1.14.1"`
- Operating System: Windows
- Node.js version: v14.16.1
- Browser: All

**Describe the bug**

I have the following deeply nested test and I'm trying to use test.skip but it's saying it's not within a describe block:

```ts
test.describe('InputHandler Integration Tests', function(): void {
...
test.describe('CSI', () => {
...
test.describe('SM: Set Mode', () => {
...
test('Pm = 2004, Set bracketed paste mode', async () => {
  test.skip(e => e.browserName !== 'chromium');
  ...
});
```

Here's the unexpected error:

```
  3) [Firefox Stable] › ..\..\test\playwright\InputHandler.test.ts:199:9 › InputHandler Integration Tests CSI SM: Set Mode CSI ? Pm h Pm = 2004, Set bracketed paste mode 

    Error: test\playwright\InputHandler.test.ts:200:16: test.skip() with a function can only be called inside describe block

      198 |         // TODO: This only works in Chromium? (isChromium ? it : it.skip)
      199 |         test('Pm = 2004, Set bracketed paste mode', async () => {
    > 200 |           test.skip(e => e.browserName !== 'chromium');
          |                ^
      201 |           strictEqual(await simulatePaste('foo'), 'foo');
      202 |           await ctx.proxy.write('\x1b[?2004h');
      203 |           strictEqual(await simulatePaste('bar'), '\x1b[200~bar\x1b[201~');
```

The docs show `test.skip` as a direct child of a `test` so not sure what it's complaining about: https://playwright.dev/docs/test-annotations#conditionally-skip-a-test

cc @mxschmitt 

The actual test can be found on this branch: https://github.com/Tyriar/xterm.js/tree/playwright_update

**Comment by Tyriar** [comment] 2021-09-03 15:02
My workaround in the meantime:

```ts
        test('Pm = 2004, Set bracketed paste mode', async ({ browserName }) => {
          if (browserName !== 'chromium') {
            return;
          }
```

**Comment by mxschmitt** [comment] 2021-09-03 15:18
Seems like it has to do with the custom TypeScript transcompilation. Minimum reproducible:

```js
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
const test = require("@playwright/test");
test.test('Pm = 2004, Set bracketed paste mode', () => __awaiter(this, void 0, void 0, function* () {
    test.test.skip(e => e.browserName !== 'chromium');
}));
```

Once you set the `target` in your tsconfig to e.g. `ESNext` it works.

**Comment by Tyriar** [comment] 2021-09-03 15:54
No that also gave this error unexpectedly:

> test.skip() with a function can only be called inside describe block

**Comment by yury-s** [comment] 2021-09-03 16:14
> No that also gave this error unexpectedly:
> 

Can you show the code, I just tried it and it worked? `test.skip()` inside test expects a boolean value or nothing, see [this signature](https://github.com/microsoft/playwright/blob/d9bcb0b17044ff4a085cf6021ec63c286d8f36d1/types/test.d.ts#L1365) whereas `test.skip` called outside of a test has [this signature](https://github.com/microsoft/playwright/blob/d9bcb0b17044ff4a085cf6021ec63c286d8f36d1/types/test.d.ts#L1367-L1386) and takes a function.

**Comment by yury-s** [comment] 2021-09-03 16:19
> The docs show `test.skip` as a direct child of a `test` so not sure what it's complaining about: https://playwright.dev/docs/test-annotations#conditionally-skip-a-test

Yeah, this is somewhat confusing, there are several overloads of `test.skip`, `test.skip(boolean)` can be called both inside and outside of a test while `test.skip(callback: (args: TestArgs & WorkerArgs) => boolean))` can only be placed outside of a test. The example uses the former one.

**Comment by Tyriar** [comment] 2021-09-03 17:40
Oh I see, so no callback inside the test? That is indeed confusing so it woup DBE good to remove that restriction or at least clarify the error message.

The callback is more convenient here as otherwise I would need to modify the outer test call to include browserName in its args.

**Comment by pavelfeldman** [comment] 2022-10-20 02:59
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-10-20 02:59 UTC
Labels: P3-collecting-feedback, feature-test-runner
