### ISSUE TITLE
[BUG] page.video().saveAs() writes both renamed and original files

### ISSUE THREAD

**Issue by worldomonation** [microsoft/playwright#6524] opened 2021-05-12 06:32 UTC
**Context:**
- Playwright Version: 1.11.0
- Operating System: macOS Big Sur 11.2.3 (20D91)
- Node.js version: 14.16.1
- Browser: Chromium
- Extra: Apple Silicon M1, mocha test runner

**Code Snippet**

```javascript 
const playwright = require('playwright');

describe('demonstration', function() {
	this.timeout(9000);

	let browser;
	let browserContext;
	let page;

	before(async function() {
		browser = await playwright.chromium.launch( {
			timeout: 9000
		} );

		browserContext = await browser.newContext( {
			recordVideo: { dir: '/tmp/video/' },
		} );

		page = await browserContext.newPage();
	});

	it('step', async function() {
		await page.goto('https://wordpress.com');
		await page.click('invalid_selector');
	});

	after(async function() {
		await page.close();
		await page.video().saveAs('/tmp/video/failed-video.webm');

		await browser.close();
	});
})
```

**Describe the bug**

When the `page.video().saveAs()` call is used, I would expect only the named file to be saved on disk.
However, it would appear the original file (with the alphanumeric string) is also saved on disk alongside the named file.

When run with the `DEBUG=pw:api` environment set, I see the following:

```
  demonstration
  pw:api => browserType.launch started +0ms
  pw:api <= browserType.launch succeeded +327ms
  pw:api => browser.newContext started +0ms
  pw:api <= browser.newContext succeeded +3ms
  pw:api => browserContext.newPage started +0ms
  pw:api <= browserContext.newPage succeeded +83ms
  pw:api => page.goto started +1ms
  pw:api navigating to "https://wordpress.com", waiting until "load" +1ms
  pw:api   navigated to "https://wordpress.com/" +143ms
  pw:api   "domcontentloaded" event fired +142ms
  pw:api   "load" event fired +96ms
  pw:api <= page.goto succeeded +1ms
  pw:api => page.click started +0ms
  pw:api waiting for selector "invalid_selector" +3ms
  pw:api   "networkidle" event fired +608ms
    1) step
  pw:api => page.close started +8s
  pw:api <= page.click failed +10ms
  pw:api <= page.close succeeded +0ms
  pw:api => .saveAs started +1ms
  pw:api <= .saveAs succeeded +1s
  pw:api => browser.close started +0ms
  pw:api <= browser.close succeeded +11ms


  0 passing (11s)
  1 failing

  1) demonstration
       step:
     Error: Timeout of 9000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/edwintakahashi/workspace/wp-calypso-second/test-spec.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```
![Screen Shot 2021-05-11 at 11 32 12 PM](https://user-images.githubusercontent.com/6549265/117929055-37335a80-b2b1-11eb-87e2-d7c45247870a.png)

**Comment by JoelEinbinder** [comment] 2021-05-13 15:52
I believe this is the intended behavior. If you want to rename the video, [fs.rename](https://nodejs.org/api/fs.html#fs_fs_rename_oldpath_newpath_callback) along with [videoPath](https://playwright.dev/docs/api/class-video#videopath).

@yury-s to confirm that this is the intended behavior.

**Comment by mortelee** [comment] 2021-05-14 12:30
After saveAs() you have the call "page.video().delete()". This will delete the original file, but keeps the saveAs file.

**Comment by worldomonation** [comment] 2021-05-14 17:05
> After saveAs() you have the call "page.video().delete()". This will delete the original file, but keeps the saveAs file.

Thanks for the feedback and clarification.

I had assumed that `saveAs` would handle renaming of the file _and_ removal of the original file. Looks like my assumptions were incorrect.

I think in general the Video feature can use some more documentation and/or examples. With that said, I highly appreciate the improvements introduced in 1.11.0, so a big thank you to the Playwright team.

**Comment by mxschmitt** [comment] 2021-05-25 10:25
Closing for now, after an offline discussion with Yury, `Video.saveAs` is designed to save a copy of the video on the disk.

**Closed by mxschmitt** 2021-05-25 10:25 UTC
Labels: triaging
