### ISSUE TITLE
[REGRESSION]: fixture that automatically attaches debug logs when the test fails - shows empty log.txt file

### ISSUE THREAD

**Issue by TesterrA** [microsoft/playwright#27612] opened 2023-10-14 11:01 UTC
**Context:**
- GOOD Playwright Version: [1.39.0]
- Operating System: Linux
- Extra: vscode, ubuntu latest

    
fixture : 

```ts
import * as debug from 'debug';
import * as fs from 'fs';
import { test as base } from '@playwright/test';

export const test = base.extend<{ saveLogs: void }>({
  saveLogs: [async ({}, use, testInfo) => {
    // Collecting logs during the test.
    const logs = [];
    debug.log = (...args) => logs.push(args.map(String).join(''));
    debug.enable('myserver');

    await use();
// After the test we can check whether the test passed or failed.
    if (testInfo.status !== testInfo.expectedStatus) {
      // outputPath() API guarantees a unique file name.
      const logFile = testInfo.outputPath('logs.txt');
      await fs.promises.writeFile(logFile, logs.join('\n'), 'utf8');
      testInfo.attachments.push({ name: 'logs', contentType: 'text/plain', path: logFile });
    }
  }, { auto: true }],
});
export { expect } from '@playwright/test';

test file : 

import { test, expect } from '../fixtures/fixture';

test("login test", async ({ page, baseURL, saveLogs }) => {
    console.log('This is a console log');
    await page.goto('');
    await page.waitForURL(baseURL + '/dashboard');
    console.log('This is another console log');
    await expect(2 + 2, 'wrong addition').toBe(6);
    page.close();
});
```

why this one shows empty log.txt file in html reporter. am i missing something in test file? or something in playwright.config file?

**Comment by mxschmitt** [comment] 2023-10-16 15:00
You marked it as a regression, was this working before?

I tried the following and it was working for me:

```ts
import { test as base } from '@playwright/test';
import * as debug from 'debug';
import * as fs from 'fs';

const test = base.extend<{ saveLogs: void }>({
  saveLogs: [async ({}, use, testInfo) => {
    // Collecting logs during the test.
    const logs = [];
    debug.log = (...args) => logs.push(args.map(String).join(''));
    debug.enable('myserver');

    await use();
    // After the test we can check whether the test passed or failed.
    if (testInfo.status !== testInfo.expectedStatus) {
      // outputPath() API guarantees a unique file name.
      const logFile = testInfo.outputPath('logs.txt');
      await fs.promises.writeFile(logFile, logs.join('\n'), 'utf8');
      testInfo.attachments.push({ name: 'logs.txt', contentType: 'text/plain', path: logFile });
    }
  }, { auto: true }],
});

test('login test', async ({ saveLogs }) => {
  debug.log('login test');
  throw new Error('login test failed');
});
```

You don't need to close the `page`, we create it for you and we also close it for you. So you can safely remove the ``page.close()` call. Only debug logs created via `debug.log('hello world')` are stored inside the array and then saved to the file / reporter. There is no correlation between `console.log` and in this example `debug.log`, the custom object to write debug output to the reporter API. Thats why your `console.log` does not end up there.

Does this make it more clear?

Unrelated to that I think what you actually want is to [enable Tracing](https://playwright.dev/docs/trace-viewer-intro) which includes all console.logs from the browser and from Node.js in a pretty form.

**Comment by mxschmitt** [comment] 2023-10-23 15:36
Closing as per above. Please re-file if you have more questions, since we don't monitor closed issues, thanks!

**Closed by mxschmitt** 2023-10-23 15:36 UTC
Labels: triaging
