### ISSUE TITLE
[BUG] rimraf causes failure with multiple browsers on Windows

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#808] opened 2020-02-02 22:18 UTC
**Context:**
- PlayWright Version: 0.10.0
- Operating System: [Windows 2019](https://github.com/qawolf/qawolf/runs/422107349)

Might relate to #680

**Code Snippet**

Run `npx jest`

```javascript
const { chromium } = require("playwright");

test("browser one success", async () => {
  const context = await chromium.launch();
  await context.close();
});

test("browser two failure", async () => {
  const context = await chromium.launch();
  await context.close();
});
```

**Describe the bug**

The second test throws this error.

```
assert(received)

    Expected value to be equal to:
      true
    Received:
      false

      at fixWinEPERM (node_modules/rimraf/rimraf.js:175:5)
      at node_modules/rimraf/rimraf.js:160:15
```

Others have seen this same issue with rimraf on windows. 
https://github.com/facebook/jest/issues/3942#issuecomment-313169747
https://github.com/GoogleChrome/lighthouse/pull/2641

I tried to force the playwright-core resolution to rimraf 3.0.1 but I ran into the same issue. 

Is there a way to remove the rimraf dependency and replace it with fs-extra, that seems to be an approach that worked here. https://github.com/getgauge/taiko/issues/837

**Comment by jperl** [comment] 2020-02-02 22:29
I am happy to submit a PR if you are willing to accept replacing rimraf with fs-extra.

**Comment by jperl** [comment] 2020-02-02 22:43
Updated with small reproduction.

**Comment by aslushnikov** [comment] 2020-02-04 00:19
> I am happy to submit a PR if you are willing to accept replacing rimraf with fs-extra.

@jperl If I understand correctly, fs-extra simply includes rimraf: 
- fs-extra's [rimraf](https://github.com/jprichardson/node-fs-extra/blob/master/lib/remove/rimraf.js)
- original [rimraf](https://github.com/isaacs/rimraf/blob/master/rimraf.js)

So I wonder how is this fixing the problem. I can reproduce this easily on win - interestingly, it only happens under jest environment, and never otherwise. The assert that fires is very weird too.

Let me see what's going on.

**Comment by aslushnikov** [comment] 2020-02-04 01:23
@jperl so `rimraf` turned out to have an assert that makes sure that errors reported by `fs` module are, well, actually errors:

https://github.com/isaacs/rimraf/blob/d709272f6122b008de66650616fda34c8ae6f954/rimraf.js#L168

The assert fails because it looks like jest is messing up with fs errors somehow. I can repro this with the following jest test:

```js
test('whoa', () => {
  try {
    require('fs').rmdirSync(__dirname);
  } catch (e) {
    console.log('caught error instanceof Error: ', e instanceof Error);;
  }
});
```

Running `npx jest` prints "caught error instance of Error: false" - on both Mac and Windows to me.

![image](https://user-images.githubusercontent.com/746130/73704844-345aba80-46a9-11ea-9eab-47696d627207.png)

This is somewhat surprising since jest explicitly states that they [don't mock core node modules](https://jestjs.io/docs/en/manual-mocks#mocking-node-modules). 

Let me dig further.

**Comment by jperl** [comment] 2020-02-04 03:10
@aslushnikov Thank you for investigating this 🙏.

**Comment by aslushnikov** [comment] 2020-02-04 03:14
Ok, we now know what's going on!

## Investigation 

1. Jest runs tests in separate [VMs](https://nodejs.org/api/vm.html) (or execution contexts).
2. For every VM, Jest creates a _test environment_: this defaults to [JSDOMEnvironment](https://github.com/facebook/jest/blob/master/packages/jest-environment-jsdom/src/index.ts). JSDOM's global is then used as VM's global.
3. Test is executed in VM's global.

A reduced repro of this behavior looks like this:

```js
const vm = require('vm');
const jsdom = require('jsdom');

const env = new jsdom.JSDOM('<!DOCTYPE html>', {
  runScripts: 'dangerously',
});

vm.createContext(env.window);

const testcode = `
  ((require, console) => {
    try {
      require('fs').rmdirSync(__dirname);
    } catch (e) {
      console.log('caught error instanceof Error: ', e instanceof Error);;
    }
  })
`;
vm.runInContext(testcode, env.window)(require, console);
```

<details>
<summary>Even Simpler Reproduction</summary>

```js
const vm = require('vm');

const context = { Error, console };
vm.createContext(context);

const testcode = `
  try {
    const foo = 10;
    foo = 20; // Error!
  } catch (e) {
    console.log('caught error instanceof Error: ', e instanceof Error);
  }
`;
vm.runInContext(testcode, context);
```
</details>

This code prints "false" because:
- the error in the global scope is coming from a **parent execution context**
- the error that we catch is generated by native c++ code and thus created by the **child execution context**
- these two errors are technically different in terms of `instanceof`'ing.

Now, rimraf is doing an instanceof check for some of the errors it's getting from FS module:

https://github.com/isaacs/rimraf/blob/d709272f6122b008de66650616fda34c8ae6f954/rimraf.js#L168

This check fails and yields this error.

## Mitigation 

Unfortunately, configuring jest to run in a `testEnvironment: node` (and thus not bringing in JSDOM) doesn't help to mitigate this issue, because jest's [NodeEnvironment](https://github.com/facebook/jest/blob/master/packages/jest-environment-node/src/index.ts) is doing a very similar thing. (And there seem to be some workarounds for some [similar problems](https://github.com/facebook/jest/blob/964dc1619b8c5345a648ef79bcd87c087995255a/packages/jest-environment-node/src/index.ts#L43-L46))

Short-term, we should try fixing this upstream in rimraf - instead of `instanceof`'ing errors, it'd be probably fine to check for existence of a `stack` property. 

Long-term, I wonder if there's something Jest can do better on their side to avoid this cross-vm type passing.

**Comment by jperl** [comment] 2020-02-04 03:24
I'm impressed at how quickly you got to the root of this complex issue. Would you like me to submit the PR for rimraf?

**Comment by aslushnikov** [comment] 2020-02-04 03:45
@jperl I'm on it, thanks! 👷‍♂️

**Comment by aslushnikov** [comment] 2020-02-04 03:57
Once/if https://github.com/isaacs/rimraf/pull/209 is merged and a new version is released, we can roll the dependency. It'll fix this bug. 

We'll probably wait for a week to see if we can land a fix to rimraf. If there's a delay, we can detect jest environment and provide `rimraf` with custom fs hooks that re-throw vm-native errors

```js
const isJestEnvironment = (function() {
  try {
    some_undefined_variable_goes_here;
  } catch (e) {
    return !(e instanceof  Error);
  }
})();
```

**Closed** 2020-02-10 19:27 UTC
