### ISSUE TITLE
[BUG] Child of `display:contents` element not visible to Playwright

### ISSUE THREAD

**Issue by hemlok** [microsoft/playwright#5949] opened 2021-03-25 13:58 UTC
**Context:**
- Playwright Version: 1.8.1
- Operating System: Linux, Mac
- Node.js version: 12.13.1
- Browser: Chromium

  System:
    OS: macOS 11.2.3
    Memory: 104.15 MB / 16.00 GB
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 2.4.0 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash

**Code Snippet**

```html
<div class="parent" style="display: contents;">
  <div class="child" style="width: 200px; height: 200px; position: relative;"></div>
</div> 
```

```javascript
...
await page.waitForSelector(`.child`, { state: "visible" })
...
```

**Describe the bug**

It seems that if a layer is the child of a layer with `style.display = "contents"`, calling `waitForSelector(`.child`, { state: "visible" })` Playwright doesn't believe the layer is visible. The issue can be worked around by using `{ state: "attached" }`. 

The same is true if `waitForSelector` is called on the parent, but this makes sense based on the [implementation](https://github.com/microsoft/playwright/blob/1e754a4d805118f0cb1847d91ba8cf3a7222deba/src/server/injected/selectorEvaluator.ts#L557-L558), which expects a bounding box, and elements with `display: contents` **do not** have a box, instead taking on the box of their contents, but is still not desired behaviour: https://developer.mozilla.org/en-US/docs/Web/CSS/display#box perhaps the [accessibility issues](https://developer.mozilla.org/en-US/docs/Web/CSS/display#display_contents) are impacting this?

Apologies for the over-simplified code snippet, this extracted from a company code base.

**Comment by pavelfeldman** [comment] 2021-03-25 15:27
Could you try latest Playwright v1.10? We had a fix for display:contents there.

**Comment by hemlok** [comment] 2021-03-25 16:44
Gave that a try, it was still unable to find the visible selector on 1.10!

**Comment by yury-s** [comment] 2021-03-25 17:01
The upstream fix hasn't been rolled yet (we are currently building chromium dev revision that contains the #5950). This issue is tracked in #5858, once it is closed I hope this bug will be fixed too.

**Comment by aslushnikov** [comment] 2021-03-26 19:57
Closing as dupe of #5858

**Closed by aslushnikov** 2021-03-26 19:57 UTC

**Comment by basilgood** [comment] 2022-01-05 11:04
This issue is still not resolved.
If a selector has ```display: none``` and his child has anything, when the parent becomes visible Playwright doesn't believe the layer is visible. The issue can be worked around by using ```{ state: "attached" }```.

Context:

* Playwright Version: 1.17.1

* Operating System: Linux

* Node.js version: 14.18.1

* Browser: Chromium

Code Snippet:
```js
      <div class="wrapper">
        Checkbox: <input type="checkbox" class="myCheck" onclick="myFunction()">

        <footer class="parent" style="display:none">
          <p class="child" style="display:contents">Checkbox is CHECKED!</p>
        </footer>
      </div>
      
    <script type = "text/javascript">
      function myFunction() {
        const checkBox = document.getElementById("myCheck");
        if (checkBox.checked == true) {
          pagefooter.style.display = "block";
        } else {
          pagefooter.style.display = "none";
        }
      }
    </script>
```
```js
await page.waitForSelector('.child')
```
```
waiting for selector ""Checkbox is CHECKED!"" to be visible
  selector resolved to hidden <p id="text">Checkbox is CHECKED!</p>
```

**Comment by basilgood** [comment] 2022-01-05 16:23
Yes thank you.
