### ISSUE TITLE
[BUG] :not([aria-hidden=true]) :text("Submit") finds hidden elements

### ISSUE THREAD

**Issue by TrySound** [microsoft/playwright#5129] opened 2021-01-24 15:05 UTC
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.8.0
- Operating System: [e.g. Windows, Linux or Mac] mac
- Node.js version: [e.g. 10.12, 10.14] 14.10.1
- Browser: [e.g. All, Chromium, Firefox, WebKit] chromium
- Extra: [any specific details about your environment]

**Code Snippet**

```js
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({
    headless: false,
  });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.setContent(`
    <div aria-hidden=true>
      <div>Submit</div>
    </div>
  `);
  const element = await page.$(`:not([aria-hidden=true]) :text("Submit")`);
  console.log(element == null)
})().catch(error => {
  console.error(error);
});
```

**Describe the bug**

Selecting aria-hidden=true as ancestor works fine but with negation "submit" still found

**Comment by mxschmitt** [comment] 2021-01-24 15:23
Looks like it is confused when you don't specify a tag name to the `:not()` selector (maybe its internally resolving it to the body tag). Having it like that works, see here: https://try.playwright.tech/?s=rbzdag3

```js
  const element = await page.$$(`div:not([aria-hidden=true]) :text("Submit")`);
```

**Comment by TrySound** [comment] 2021-01-24 17:37
Btw was aria-hidden considered for `:visible` pseudo-class? Would be a good addition to skip accessing elements behind modals for example.

**Comment by TrySound** [comment] 2021-01-25 08:16
I see. It look for the first match. Though if another div wraps hidden one we get the problem again
https://try.playwright.tech/?s=ndbdtps
```
    <div>
      <div aria-hidden=true>
        <div>Submit</div>
      </div>
    </div>
```

**Comment by TrySound** [comment] 2021-01-25 08:33
Btw, looks like custom selector engine cannot be registered. Always get the error `Error: "ariVisible" selector engine has been already registered`
https://try.playwright.tech/?s=9y8h7m8

**Comment by mxschmitt** [comment] 2021-01-25 14:25
@TrySound probably a bug on Try Playwright side (https://github.com/mxschmitt/try-playwright/issues/165).
So the best to not rely on that site, locally your code works from the last comment.

**Comment by TrySound** [comment] 2021-01-25 16:37
Good! I solved the problem like this for now.

```js
const createAriaVisibleEngine = () => ({
  query(root, selector) {
    return root.closest('[aria-hidden=true]') ? null : root;
  },
  queryAll(root, selector) {
    return root.closest('[aria-hidden=true]') ? [] : [root];
  },
});

...

const element = await page.$$(`:text("Submit") >> aria-visible=`);
```

Btw is it possible to extend css selector evaluator to make it pseudo-class instead? Would be a bit cleaner.

**Comment by dgozman** [comment] 2021-01-27 00:19
> Btw was aria-hidden considered for `:visible` pseudo-class? Would be a good addition to skip accessing elements behind modals for example.

This makes sense at the first glance. Let us consider this carefully and we'll probably implement it.

**Comment by TrySound** [comment] 2021-01-27 11:26
That would be good. Custom engine does not allow to cover all cases. For example here I need both relative element and button to be from modal not outside.
```css
button:near(:text('string'):aria-visible):aria-visible
```

**Comment by dgozman** [comment] 2021-02-03 19:05
> > Btw was aria-hidden considered for `:visible` pseudo-class? Would be a good addition to skip accessing elements behind modals for example.
> 
> This makes sense at the first glance. Let us consider this carefully and we'll probably implement it.

We considered using `aria-hidden` as a visibility signal and decided that real-world applications will bring too much false positives.

---

For the original issue, I'd suggest prefixing selectors with something for the modal element to scope the search. For example, `page.click('.my-dialog-container :text("Submit")')` or `page.click('dialog button:near(dialog :text("string"))')`.

**Closed by dgozman** 2021-02-03 19:05 UTC
Labels: P2-bug

**Comment by TrySound** [comment] 2021-02-03 19:10
I would prefer to not rely on classes or any other identifiers invisible for user. They kill the point of text selectors. I guess I'm stuck with custom layout querying for now.

**Comment by TrySound** [comment] 2021-02-03 19:15
Btw custom css pseudo-classes would be more useful than chained selectors.

**Comment by dgozman** [comment] 2021-02-03 19:37
> Btw custom css pseudo-classes would be more useful than chained selectors.

Yeah, we'll definitely do that once we are sure that our css extensions work as intended.
