### ISSUE TITLE
Both "Show browser" or "Run in Debug Mode" are not working

### ISSUE THREAD

**Issue by tadashi-aikawa** [microsoft/playwright#18424] opened 2022-10-29 09:34 UTC
Thank you for the great VSCode extension :) However, it doesn't work in both "Show browser" or "Run in Debug Mode".

https://user-images.githubusercontent.com/9500018/198824236-75862bc3-38ce-45e3-ad3f-10bea9811201.mp4

On the other hand, `npx playwright test --debug` works fine.

Best regards.

## My environment

- Windows 10
- VSCode: 1.72.2
- Playwright Test for VSCode: v0.2.13

```
$ npx playwright --version
Version 1.27.1
```

## Error message

```
テストを実行しようとしてエラーが発生しました: TypeError: Cannot read properties of undefined (reading 'setReuseBrowser')
```

**Comment by aslushnikov** [comment] 2022-11-01 18:05
@tadashi-aikawa Just tried, and works for me! Could you please try re-installing extension / playwright / everything? Also, could it be that you have multiple versions of Playwright installed in your project?

**Comment by tadashi-aikawa** [comment] 2022-11-02 00:28
Thank you for your reply, @aslushnikov :)

> Could you please try re-installing extension / playwright / everything?

I did, and not working. (The result was the same)

> could it be that you have multiple versions of Playwright installed in your project?

I believe that the project installed only one version. The commands I had executed before the steps in mp4 are only the following.

```
mkdir playwright-vscode-sample
code playwright-vscode-sample
```

**Comment by targos** [comment] 2022-11-02 07:36
I experience the same issue, also on Windows.
Using `@playwright/experimental-ct-react@1.27.1` in the latest VS Code Insiders.

**Comment by aslushnikov** [comment] 2022-11-02 19:59
@tadashi-aikawa @targos could you please prepare a small repository for me that will illustrate how VSCode extension does not work? Once there's a repro we can run & debug locally, we'll be able to fix this!

**Comment by tadashi-aikawa** [comment] 2022-11-03 11:44
@aslushnikov
I have created! I hope you will reproduce it 🙏 

https://github.com/tadashi-aikawa/playwright-minimal-sandbox

**Comment by aslushnikov** [comment] 2022-11-08 16:50
I still failed to repro; assigning to Yury who has access to a windows machine. I hope he'll be able to repro; otherwise, we won't be able to do much!

**Comment by targos** [comment] 2022-11-09 08:20
I can repro with the repo shared by @tadashi-aikawa. Is there anything I can do to help debugging this?

**Comment by pavelfeldman** [comment] 2022-11-15 19:37
@targos what is your VS Code extension version?

**Comment by targos** [comment] 2022-11-16 07:42
@pavelfeldman

VS Code extension version: v0.2.16 (Preview)

The error message has changed since last time:

```
An error occurred attempting to run tests: TypeError: Cannot read properties of undefined (reading 'setAutoClose')
```

**Comment by targos** [comment] 2022-11-21 07:38
I think this is fixed in v1.0.0!

**Comment by tadashi-aikawa** [comment] 2022-11-21 13:07
I have tried v1.0.0, but another error occurred.

![image](https://user-images.githubusercontent.com/9500018/203062785-7a9da877-8046-48d8-883b-9d5e9c75f7e2.png)

**Comment by tadashi-aikawa** [comment] 2022-11-21 13:13
However, I created a new project (https://github.com/microsoft/playwright/issues/18424#issue-1428319591), then it worked! Many thanks! 😄 

By the way, It downloaded a new Chromium. Did I download the one that contains a bug before?

```
It downloaded a new Chromium. Did I download the one that contains a bug before?Downloading Chromium 108.0.5359.29 (playwright build v1033) from https://playwright.azureedge.net/builds/chromium/1033/chromium-win64.zip
109.5 Mb [====================] 100% 0.0s
```

**Comment by aslushnikov** [comment] 2022-11-21 23:54
Looks like this was an issue with the setup; I'll close this then.

If anyone is still affected by this: please open a new issue with some repro steps! Unfortunately we can mostly fix things only if we can reproduce them.

**Closed by aslushnikov** 2022-11-21 23:54 UTC
Labels: v1.29
