### ISSUE TITLE
[BUG] Test times out while shutting down environment

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#12930] opened 2022-03-21 19:10 UTC
**Context:**
- Playwright Version: 1.20.0
- Operating System: Mac
- Node.js version: 12.22
- Browser: Chromium, WebKit
- Extra: [any specific details about your environment]

**Code Snippet**
```javascript
  test('example test', async ({ page }) => {
    await page.goto(<MY_URL>); // can share the url privately
  });
```
```javascript
// config.js
 use: {
    headless: true,
    trace: 'retain-on-failure',
    screenshot: 'on',
  },
  projects: [
    {
      name: 'Desktop Chrome',
      use: { ...devices['Desktop Chrome'] },
    },
  ]
```

**Describe the bug**
Navigating to MY_URL times out and reports the following error:
`Timeout of 20000ms exceeded while shutting down environment`

Browser logs:
```
 pw:browser <launching> /Users/test/Library/Caches/ms-playwright/chromium-978106/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/var/folders/z0/5n6p2nrn1p7_q6x11nb1ck1m0000gq/T/playwright_chromiumdev_profile-zUHo3B --remote-debugging-pipe --no-startup-window +0ms
  pw:browser <launched> pid=23926 +7ms
  pw:browser [pid=23926][err] [23926:68355:0321/104018.011736:ERROR:cert_verify_proc_builtin.cc(681)] CertVerifyProcBuiltin for tags.knewz.com failed: +6s
  pw:browser [pid=23926][err] ----- Certificate i=0 (CN=tags.knewz.com) ----- +0ms
  pw:browser [pid=23926][err] ERROR: Time is after notAfter +0ms
  pw:browser [pid=23926][err]  +0ms
  pw:browser [pid=23926][err]  +0ms
  pw:browser [pid=23926][err] [23926:51715:0321/104018.011955:ERROR:ssl_client_socket_impl.cc(996)] handshake failed; returned -1, SSL error code 1, net_error -201 +0ms
  pw:browser [pid=23926][err] [23989:259:0321/104026.452691:ERROR:system_services.cc(31)] SetApplicationIsDaemon: Error Domain=NSOSStatusErrorDomain Code=-50 "paramErr: error in user parameter list" (-50) +8s
  pw:browser [pid=23926][err] 2022-03-21 10:40:31.443 Chromium Helper[23989:567532] In -[NSApplication(NSQuietSafeQuit) _updateCanQuitQuietlyAndSafely], _LSSetApplicationInformationItem(NSCanQuitQuietlyAndSafely) returned error -50 +
```

**Comment by dgozman** [comment] 2022-03-21 21:36
@Nav-2d `Timeout of 20000ms exceeded while shutting down environment` means that cleanup did not work, most likely closing the page or the browser. A few question to help diagnose the issue:
- Is it expected that navigation times out?
- Does the trace recording work? Perhaps it could have a clue.
- Could you please try running with `DEBUG=pw:test*` to see what exactly timed out during shutdown?

**Comment by Nav-2d** [comment] 2022-03-21 22:17
@dgozman - Thank you for looking into this:
1. No, the navigation isn't supposed to time out
2. Sent you trace privately.
3. Logs:
```
 pw:test setup playwright +0ms
  pw:test setup _browserOptions +0ms
  pw:test setup baseURL +1ms
  pw:test setup _combinedContextOptions +0ms
  pw:test setup _artifactsDir +0ms
  pw:test setup _setupContextOptionsAndArtifacts +0ms
  pw:test setup browserName +0ms
  pw:test setup browser +0ms
  pw:test setup _contextFactory +302ms
  pw:test setup context +1ms
  pw:test setup page +12ms
  pw:test teardown page +12s
  pw:test teardown context +0ms
  pw:test teardown _contextFactory +0ms

Timeout of 30000ms exceeded while shutting down environment

Timeout of 30000ms exceeded while shutting down environment
```

**Comment by Nav-2d** [comment] 2022-03-21 22:30
Now, I am seeing the GPU stall issue again as mentioned in https://github.com/microsoft/playwright/issues/12756.

I am so confused :( And unfortunately only happening for one specific URL. And happening for multiple co-workers. 

Commenting out `screenshot: on` makes the test pass and turning it on fails the test.
 
```
  pw:browser <launching> /Users/navsingh/Library/Caches/ms-playwright/chromium-978106/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-p
  ✘  [Desktop Chrome] › Reports/second-file.spec.js:5:6 › example test (30s)4j1n2rz/T/playwright_chromiumdev_profile-7wjLHL --remote-debugging-pipe --no-startup-window +0ms
  pw:browser <launched> pid=96339 +6ms
  pw:browser [pid=96339][err] [0321/152555.171230:ERROR:ssl_client_socket_impl.cc(996)] handshake failed; returned -1, SSL error code 1, net_error -201 +5s
  pw:browser [pid=96339][err] [0321/152603.895002:ERROR:gl_utils.cc(319)] [.WebGL-0x4804f2f800]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels +9s

Timeout of 30000ms exceeded while shutting down environment
  pw:browser [pid=96339] <kill> +1m
  pw:browser [pid=96339] <will force kill> +0ms
  pw:browser [pid=96339] starting temporary directories cleanup +1ms
  pw:browser [pid=96339] finished temporary directories cleanup +144ms
  ```

**Comment by bshostak** [comment] 2022-03-22 19:54
Context:

    Playwright Version: 1.20.0 and 1.19.0
    Operating System: Mac
    Node.js version: 14.15.3
    Browser: Chrome
    Extra: [any specific details about your environment]

I'm able to duplicate this error with Playwright 1.20.0, 1.19.0 as well using:
``` 
{
      name: 'Google Chrome',
      use: {
        channel: 'chrome',

      },
    },
```
   I have a test that runs in about 7-8 seconds using all other browsers. When I use chrome, it takes 39-40 seconds to complete and then gives me an error of
```
Timeout of 30000ms exceeded while shutting down environment
```
My test still shows as passed though.

Below is my projects config when I experience the timeout shutting down error (thought this might help since it's reproducible every time):
```
projects: [
    // {
    //   name: 'chromium',
    //   use: {
    //     ...devices['Desktop Chrome'],
    //   },
    // },

        {
          name: 'Smoke',
          grep: /@smoke/,
          retries: 0,
        },

    // {
    //   name: 'firefox',
    //   use: {
    //     ...devices['Desktop Firefox'],
    //   },
    // },

    // {
    //   name: 'webkit',
    //   use: {
    //     ...devices['Desktop Safari'],
    //   },
    // },

    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: {
    //     ...devices['Pixel 5'],
    //   },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: {
    //     ...devices['iPhone 12'],
    //   },
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: {
    //     channel: 'msedge',
    //   },
    // },
     {
      name: 'Google Chrome',
      use: {
        channel: 'chrome',

      },
    },
  ],
  ```
  
 If I use this, it doesn't timeout and completes in 8 seconds (this is removing comments from the 'chromium' project instead of using the Branded Browser section):
 ```
projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },

        {
          name: 'Smoke',
          grep: /@smoke/,
          retries: 0,
        },

    // {
    //   name: 'firefox',
    //   use: {
    //     ...devices['Desktop Firefox'],
    //   },
    // },

    // {
    //   name: 'webkit',
    //   use: {
    //     ...devices['Desktop Safari'],
    //   },
    // },

    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: {
    //     ...devices['Pixel 5'],
    //   },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: {
    //     ...devices['iPhone 12'],
    //   },
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: {
    //     channel: 'msedge',
    //   },
    // },
    //  {
    //   name: 'Google Chrome',
    //   use: {
    //     channel: 'chrome',

    //   },
    // },
  ],
  ```

Test i'm running:
```
import { test, expect } from '@playwright/test';
import { DotComPage } from '../pages/dotcom.page';

test.describe("Dotcom UI tests", function () {
   
    test.beforeEach(async function({page}) {
    const dotComPage = new DotComPage(page);
    await dotComPage.get();
    await dotComPage.firstTimeButton.click();
    expect(dotComPage.firstTimeButton.isHidden());
   })

   
    test("Click Shop Button", async ({page}) => {
        const dotComPage = new DotComPage(page);
        let pagePromise = page.context().waitForEvent('page');
        await dotComPage.shopNavButton.click(); //opens new tab
        const newPage = await pagePromise;
        await newPage.bringToFront();
        await newPage.waitForLoadState('networkidle');
        expect(newPage.url()).toContain("landing?shopperSource=PHX-newDotCom");
    })
})
```

**Comment by Nav-2d** [comment] 2022-03-23 00:07
@bshostak - could you please post the logs as well?

`DEBUG=pw:test*`
`DEBUG=pw:browser`

**Comment by pjbowater** [comment] 2022-03-23 05:29
I've also been experiencing this since upgrading from 1.18 to 1.20

Context:
Playwright Version: 1.20.0
Operating System: Windows 10
Node.js version: v16.13.1
Browser: Chromium

As @Nav-2d alluded to, it seems to happen when screenshot is set to 'on' or 'only-on-failure'. Setting it to 'off' makes it work.

**Comment by bshostak** [comment] 2022-03-23 15:34
@Nav-2d Hope I did this right. I didn't see any logs doing the pw:test command.
```
pw:browser <launching> /Users/bshostak/Library/Caches/ms-playwright/chromium-978106/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-
  ✓  [chromium] › dotcom2.spec.ts:16:5 › Dotcom UI tests › Click Shop Button (9s)2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/var/folders/4z/p2dnz0g14r3dhfmwsdmz3vrr0000gq/T/playwright_chromiumdev_profile-98eBl1 --remote-debugging-pipe --no-startup-window +0ms
  pw:browser <launched> pid=43862 +6ms
  pw:browser [pid=43862][err] [0323/092549.121031:ERROR:command_buffer_proxy_impl.cc(125)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer. +520ms
 pw:browser [pid=43862] <gracefully close start> +10s
  pw:browser [pid=43862] <process did exit: exitCode=0, signal=null> +28ms
  pw:browser [pid=43862] starting temporary directories cleanup +0ms
  pw:browser [pid=43862] finished temporary directories cleanup +4ms
  pw:browser [pid=43862] <gracefully close end> +0ms
  ```

**Comment by dgozman** [comment] 2022-03-23 17:22
This could be the same issue #12711, which will have a fix in the next v1.20.1 release.

**Comment by Nav-2d** [comment] 2022-03-23 17:56
@dgozman - Could we try `@next` to verify?

**Comment by Nav-2d** [comment] 2022-03-23 19:03
I can confirm that my test is passing on `npm i playwright@1.20.1-beta-1648061377000`. Thank you!!

**Comment by dgozman** [comment] 2022-03-27 22:57
It looks like v1.20.1 fixed this one.

**Closed by dgozman** 2022-03-27 22:57 UTC
Labels: triaging
