### ISSUE TITLE
[BUG] page.goto: Navigation failed because page was closed! when executing test in Firefox in headed mode

### ISSUE THREAD

**Issue by chundhau** [microsoft/playwright#15691] opened 2022-07-15 00:18 UTC
**Context:**
- Playwright Version: 1.23.2
- Operating System: Windows
- Node.js version: 12.18.3
- Browser: firefox
- Extra: 

**Config File**
```javascript
const config = {
    outputDir: './test-results',
    use: {
      baseURL: 'http://localhost:5500',
      browserName: 'firefox',
      headless: false,
      viewport: { width: 600, height: 800 },
      video: 'on',
      launchOptions: {
        slowMo: 500,
      },
    },
  };
  
  module.exports = config;
```

**Test File**
```javascript
const { test, expect } = require('@playwright/test');

//Menu opens when clicked
test('open menu', async ({ page }) => {
  await page.goto(''); 
  await page.locator('#menuBtn').click();
  await expect(page.locator('#sideMenu')).toBeVisible();
});
```

**Describe the bug**
The test succeeds when I set the `browserName` to either `chromium` or `webkit` in the config file, but fails when I set `browserName` to `firefox` in the config file. When the test fails, I see this error:

```
PS C:\dev\book\speedscore> npx playwright test

Running 1 test using 1 worker

  ✘  tests\menuVisualTests.spec.js:4:1 › open menu (2s)


  1) tests\menuVisualTests.spec.js:4:1 › open menu =================================================

    page.goto: Navigation failed because page was closed!
    =========================== logs ===========================
    navigating to "http://localhost:5500/", waiting until "load"
    ============================================================

      3 | //Menu opens when clicked
      4 | test('open menu', async ({ page }) => {
    > 5 |   await page.goto(''); 
        |              ^
      6 |   await page.locator('#menuBtn').click();
      7 |   await expect(page.locator('#sideMenu')).toBeVisible();
      8 | });

        at C:\dev\book\speedscore\tests\menuVisualTests.spec.js:5:14
        at C:\dev\book\speedscore\node_modules\@playwright\test\lib\workerRunner.js:388:15
        at TestInfoImpl._runFn (C:\dev\book\speedscore\node_modules\@playwright\test\lib\testInfo.js:166:7)
        at C:\dev\book\speedscore\node_modules\@playwright\test\lib\workerRunner.js:344:26
        at TimeoutManager.runWithTimeout (C:\dev\book\speedscore\node_modules\@playwright\test\lib\timeoutManager.js:70:7)
        at TestInfoImpl._runWithTimeout (C:\dev\book\speedscore\node_modules\@playwright\test\lib\testInfo.js:154:26)
        at WorkerRunner._runTest (C:\dev\book\speedscore\node_modules\@playwright\test\lib\workerRunner.js:326:5)
        at WorkerRunner.runTestGroup (C:\dev\book\speedscore\node_modules\@playwright\test\lib\workerRunner.js:195:11)
        at process.<anonymous> (C:\dev\book\speedscore\node_modules\@playwright\test\lib\worker.js:87:5)


  1 failed
    tests\menuVisualTests.spec.js:4:1 › open menu ==================================================
```

Pretty strange, huh?

**Comment by yury-s** [comment] 2022-07-15 17:19
Can you also share the page on which the test fails?

**Comment by chundhau** [comment] 2022-07-15 19:14
I am running a local project at http://localhost:5500. I made a copy of the project I am using here:

https://github.com/FSWebDevBook/speedscore-pub

Clone the repo and use VSC to launch the `main` branch at localhost. Then do `npx playwright test` to reproduce the error.

**Comment by yury-s** [comment] 2022-07-16 00:59
I followed your instructions but the test passed 10 iterations in a row. I'm on linux though.

Can you run with `DEBUG=pw:browser` env variable and see if the browser logs any errors?

**Comment by chundhau** [comment] 2022-07-16 18:08
Can you please clarify how I can execute the test with that env variable? (Sorry, I'm new to Playwright.) Is that a command line option or do i need to add a line to my config file?

**Comment by dgozman** [comment] 2022-07-18 19:40
@chundhau Could you please follow [this section](https://playwright.dev/docs/debug#verbose-api-logs), but replace `pw:api`  with `pw:browser*,pw:api`, and then paste the logs here? Make sure to choose a powershell or a batch version, depending on what you use.

**Comment by dgozman** [comment] 2022-07-21 15:39
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue with it, and link to this one.

**Closed by dgozman** 2022-07-21 15:39 UTC
Labels: triaging

**Comment by BartVanRaemdonck** [comment] 2023-04-04 15:52
I had this in the past with page.reload(). It was fixed in a new webkit release I believe.
Now I have it again in the latest version of Playwright (1.32.2).
```
  Error: page.reload: Navigation failed because page was closed!
    =========================== logs ===========================
    waiting for navigation until "load"
```

**Comment by cinaaaa** [comment] 2023-05-01 10:51
Had the same issue here.
My machine is a macOS Ventura and page.goto passed on Webkit and Chrome but fails on the firefox.

```
1) [firefox] › urls-mobile.spec.ts:13:5 › Mobile URLs validation › URL: / ────

    page.goto: Navigation failed because page was closed!
    =========================== logs ===========================
    navigating to "http://localhost:1024/", waiting until "load"
    ============================================================

      12 |   URLS.forEach(async (URL) => {
      13 |     test(`URL: ${URL}`, async ({ page }) => {
    > 14 |       await page.goto(URL);
         |                  ^
      15 |       await expect(page).not.toHaveTitle(/Page not found!/);
      16 |     });
      17 |   });

```

I think there is a problem with the firefox driver or something.

**Comment by vaunus** [comment] 2023-06-13 15:55
Have seen this on an Ubuntu Linux CI container as well in Firefox. It happens randomly and is extremely rare.

**Comment by subhasish-smiles** [comment] 2023-07-03 15:40
Happening in ubuntu jammy in next js 13.4. Exact same error. Any fix so far? Other browsers are fine only safari mobile it is crashing

**Comment by danielmicko** [comment] 2023-07-05 11:47
I am having the same problem when running tests with Webkit on GitLab. Chrome and Firefox work fine or when I am running tests locally - they pass all fine. But when I am trying to navigate to the page in afterEach hook, I get the error  - Error: page.goto: Navigation failed because page was closed! 
When I look at the screenshots of the failed tests, they seem to be redirected to the required page. But they just fail.

**Comment by danielmicko** [comment] 2023-07-05 11:59
I am having the same problem when running tests with Webkit on GitLab - when I am trying to navigate to the page in afterEach hook it fails. Chrome and Firefox work fine and also when I am running tests locally - they pass all fine. But when I am trying to navigate to the page in afterEach hook, I get the error - Error: page.goto: Navigation failed because page was closed!
When I look at the screenshots of the failed tests, they seem to be redirected to the required page. But they just fail.

Test timeout of 30000ms exceeded while running "afterEach" hook.

   7 | })
   
   8 |
   
>  9 | test.afterEach(async ({project}) =>{

     |      ^
     
  10 |     await project.logOut();
  
  11 | })
  
  12 |
  
    at /builds/project-playwright/tests/DetailModalTest.spec.ts:9:6
    
Error: page.goto: Navigation failed because page was closed!

=========================== logs ===========================

navigating to URL, waiting until "load"

============================================================`
This is the step, where it fails :
async goTo(){ await this.page.goto('URL'); await this.page.waitForLoadState(); }

**Comment by ugurtrolley** [comment] 2023-07-18 00:47
same error, fails at VS code and terminal and elsewhere... 

getting authkey from session and using with page and nothing works!


----
import {test, expect} from "framework/fixtures/PageFixtures"
import { request} from "@playwright/test";

// const BASE_API = "http://127.0.0.1:3000"


const loginPayload = {"deviceId":"J8FdsKaxpE7C/RRuIirxEl+PvkA=","email":"sample@gmail.com","password":"trx*CXN!xga4xyb*udb"}
let token: string;

test.beforeAll( async ()=> {
    const apiContext = await request.newContext();
    const loginResponse = await apiContext.post("http://127.0.0.1:3000/auth/authenticate",
    {data:loginPayload})
    await expect(loginResponse.ok()).toBeTruthy()
    const loginResponseJson = await loginResponse.json();
    token = await loginResponseJson.token;
})

test("login test @api",async ({page}) => {
    page.addInitScript( value => {
        window.sessionStorage.setItem("auth-token", value);
    }, token)
    page.goto("http://localhost:9000/")

})

**Comment by lacazeto** [comment] 2023-07-24 08:05
I also get the same issue when running on github actions!

```
Test timeout of 30000ms exceeded.

    Error: page.goto: Navigation failed because page was closed!
    =========================== logs ===========================
    navigating to "http://127.0.0.1:3006/", waiting until "load"
    ============================================================

       at fixtures/portal.ts:40

      38 |
      39 | 	async login() {
    > 40 | 		await this.page.goto("/", {
         | 		                ^
      41 | 			waitUntil: "load",
      42 | 		});
      43 | 		await this.appLayout.signInButton.click();

        at Portal.login (/home/runner/work/portal/portal/tests/fixtures/portal.ts:40:[19](https://github.com/parcelLab/portal/actions/runs/5624032963/job/15239988693#step:6:20))
        at /home/runner/work/portal/portal/tests/integration/app.spec.ts:12:16
        at /home/runner/work/portal/portal/tests/integration/app.spec.ts:11:13
 ```
 
But I can't reproduce this in any way on my local!
It doesn't seem to be related to a specific browser, just fails on the 1st on that is set to run the test suite on (it is using only one worker).

Tried using goto with different event listeners and some timeout, but still, no improvements

**Comment by jernejcvek** [comment] 2023-07-24 08:28
We had the same issues. We run tests periodically (1 worker) on the VM (OS: Ubuntu), and the error has occurred occasionally. After increasing system resources (number of vCPU, RAM), it seems the problem vanished. 
I know this is not the solution to the problem, but maybe increasing system resources (if that's possible) helps as a workaround in the meantime.

**Comment by lacazeto** [comment] 2023-07-25 08:17
It seems it is just the 1st time, after installing npm packages and playwright dependencies, that the tests take very long to execute.
![Screenshot 2023-07-25 at 10 13 01](https://github.com/microsoft/playwright/assets/25816956/59ee5674-164b-4690-a097-4c5eaaaa5d16)

After that caching must come into play and things go much faster. The subsequent run:
![Screenshot 2023-07-25 at 10 13 13](https://github.com/microsoft/playwright/assets/25816956/29dd02f4-bf89-4a76-8cb1-a867c142402e)

So increasing resources was not a solution in here, but for now I'm increasing the timeouts as whenever I run in the CI it will be like a 1st time running and it will take a very long time.

**Comment by caribou-code** [comment] 2023-08-30 09:20
I'm seeing this issue intermittently, but not infrequently when running Playwright `1.35.1` in an Azure pipeline on the Docker image `mcr.microsoft.com/playwright:v1.35.0-jammy`. I've seen it happen on multiple previous versions too.

Unfortunately I can't provide a repo to replicate the issue due to the intermittent nature.

**Comment by AndrewESG** [comment] 2023-09-13 11:58
I use BuddyWorks pipelines and getting "Navigation failed because page was closed!" on any test browser. Works perfectly fine locally, but doesn't when I try to run simple tests in the pipeline. This is so frustrating.

**Comment by byungster** [comment] 2023-09-18 01:44
I got same error.

In order to by-pass, we might be use options param like {waitUntil: 'load'}

![image](https://github.com/microsoft/playwright/assets/34334571/25c81fde-11d0-4981-88ac-b3a528537a06)

**Comment by dunapanta** [comment] 2023-09-28 02:37
In my case I was experiencing this error since the previous week in a scrapping lambda function. I share aworkaround that has helped me and may help more than one.

Basically it consists of making a loop that if it fails with this error it falls into the catch and retries with a maximum of 3 retries in my case

` 
const maxRetries = 3;
for (let retry = 1; retry <= maxRetries; retry++) {
      try {
        if(retry > 1){
           chromium.setGraphicsMode = false;
           browser = await playwright.launch({
            args: chromium.args,
            executablePath: await chromium.executablePath(),
            //headless: new,
          });
         context = await browser.newContext({
          userAgent:
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
        });
 }
// CODE TO EXCECUTE
  break;
      } catch (err) {
        if (retry < maxRetries) {
          console.log("ANOTHER RETRY");
          await page.close(); 
          await browser.close();
          await new Promise((resolve) => setTimeout(resolve, 2000)); //WAIT 2 SECONDS
        } else {
          console.error(
            "ERROR MAX RETRY"
          );
          throw err;
        }
      }
`

**Comment by WcaleNieWolny** [comment] 2023-10-04 17:36
This is likely not going to help, however in my case a simple `await` fixed the problem
```ts
page.goto(`${BASE_URL}/app/p/com--demo--app/channel/23`)
```
```ts
await page.goto(`${BASE_URL}/app/p/com--demo--app/channel/23`)
```
