### ISSUE TITLE
[Bug]: Locator.fill() works in some cases and doesn't in other cases

### ISSUE THREAD

**Issue by joeltancej** [microsoft/playwright#29488] opened 2024-02-14 09:02 UTC
### Version

1.34.3

### Steps to reproduce

Hi, I am unable to provide a repository for reproduction of the issue, but there I have run into an issue where the locator.fill() method is not working. This mostly happens when I put one fill() command after another, but I'm not sure what are the possible reasons this could happen. I can get it to work by inserting another redundant fill() command (where it executes every alternative fill() command). What are some possible reasons that some fill() commands do not get executed (or do not work), although the test report generated eventually shows that it was executed?

A snippet of the code I have written:
![image](https://github.com/microsoft/playwright/assets/64303711/dc812982-6a03-4646-abba-32b1268a3569)

### Expected behavior

I expect to see the input field with the Test ID 'column-PinNumber-1' getting filled with the number 11, and then the input field with Test ID 'column-PinNumber-1' getting filled with the number 12. Thereafter the checkbox with Test ID 'column-Gnd-0' should be clicked.

### Actual behavior

Instead, after seeing the input field with the Test ID 'column-PinNumber-1' get filled with the number 11, and the next fill() command gets skipped, and the checkbox with Test ID 'column-Gnd-0' gets clicked.

I am only able to produce the desired behavior when I use another redundant fill() command, for some reason.

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz
    Memory: 8.08 GB / 15.78 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.86.1 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.21 - C:\Users\joeltan3\AppData\Local\Programs\Git\usr\bin\bash.EXE
  npmPackages:
    @playwright/test: 1.34.3 => 1.34.3
    playwright: 1.34.3 => 1.34.3
```

**Comment by mxschmitt** [comment] 2024-02-14 09:36
Without a reproduction we are unfortunately not able to assist. General advice would be to use the latest Playwright version, since you are not using the latest one. If the fill's are not getting 'accepted' then most likely it's the web-application's fault, that the app is not 'accepting' them. Either because its a bug in the web-application itself or a bug on our side where we fill incorrectly. In both cases having a reproduction would be necessary to proceed. I'll close it for now, since we can't act on that, thanks for your understanding and don't hesitate to re-file with a self-contained minimal repro.

**Closed by mxschmitt** 2024-02-14 09:36 UTC

**Comment by 42shadow42** [comment] 2024-03-13 21:13
I might be able to put together a reproduction here, we are encountering an issue that appears to fit the bill. It appears that its related to using multiple instances of the same browser, as is suggested by the naming of the variable currentWindow.
