### ISSUE TITLE
[BUG] Windows VM ERROR:main_dll_loader_win.cc(109)] Failed to load Chrome DLL

### ISSUE THREAD

**Issue by garciallorente-fer** [microsoft/playwright#21490] opened 2023-03-08 12:54 UTC
### System info
- Playwright Version: [v1.31.2]
- Operating System: [Windows VM]
- Browser: [ONLY in Chromium]
- Other info: It used to work fine until updated to v1.31 and now even if I revert back to previous versions still getting the same error (the error only happens in the Windows VM , not in my local machine, but I do not have access to that VM Windows machine)

**Error LOG**

```js
2023-03-07T09:27:22.6036536Z [31m  1) [testing Login Setup] › tests\login-setup.ts:6:5 › Login Setup [2m────────────────────────────────[22m[39m
2023-03-07T09:27:22.6037617Z 
2023-03-07T09:27:22.6038162Z     browserType.launch: Browser closed.
2023-03-07T09:27:22.6038793Z     ==================== Browser output: ====================
2023-03-07T09:27:22.6044850Z     <launching> C:\devops-agents\agent\_work\r65\a\Project.Web.Test.Automation\Output\node_modules\playwright-core\.local-browsers\chromium_win64_special-1050\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\SVC_TE~1\AppData\Local\Temp\playwright_chromiumdev_profile-uvQwhV --remote-debugging-pipe --no-startup-window
2023-03-07T09:27:22.6052457Z     <launched> pid=9100
2023-03-07T09:27:22.6054202Z     [pid=9100][err] [0307/092645.718:ERROR:main_dll_loader_win.cc(109)] Failed to load Chrome DLL from C:\devops-agents\agent\_work\r65\a\Project.Web.Test.Automation\Output\node_modules\playwright-core\.local-browsers\chromium_win64_special-1050\chrome-win\chrome.dll: The specified procedure could not be found. (0x7F)
2023-03-07T09:27:22.6056487Z     =========================== logs ===========================
2023-03-07T09:27:22.6062693Z     <launching> C:\devops-agents\agent\_work\r65\a\Project.Web.Test.Automation\Output\node_modules\playwright-core\.local-browsers\chromium_win64_special-1050\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\SVC_TE~1\AppData\Local\Temp\playwright_chromiumdev_profile-uvQwhV --remote-debugging-pipe --no-startup-window
2023-03-07T09:27:22.6068578Z     <launched> pid=9100
2023-03-07T09:27:22.6070213Z     [pid=9100][err] [0307/092645.718:ERROR:main_dll_loader_win.cc(109)] Failed to load Chrome DLL from C:\devops-agents\agent\_work\r65\a\Project.Web.Test.Automation\Output\node_modules\playwright-core\.local-browsers\chromium_win64_special-1050\chrome-win\chrome.dll: The specified procedure could not be found. (0x7F)
2023-03-07T09:27:22.6071990Z     ============================================================
```

**Test file**
```
import { test as setup } from '@playwright/test';

setup('Login Setup', async ({ page }) => {
      await this.page.goto('URL');
});
```

**Steps**
- run: "npm set PLAYWRIGHT_BROWSERS_PATH=0&& playwright install"
- runL "npm set PLAYWRIGHT_BROWSERS_PATH=0&& playwright test"

**Expected**
It used to work fine until updated to v1.31 and now even if I revert back to previous versions still getting the same error (the error only happens in the Windows VM , not in my local machine, but I do not have access to that VM Windows machine)

**Actual**
As you can see in the LOG error, the browser cannot even be executed now.

**Comment by mxschmitt** [comment] 2023-03-08 19:30
Looks like the browser installation is broken on your system, could you verify the existence of `C:\devops-agents\agent\_work\r65\a\Project.Web.Test.Automation\Output\node_modules\playwright-core\.local-browsers\chromium_win64_special-1050\chrome-win\chrome.dll`? If its not there, it was most likely removed due to e.g. an anti virus or high security policies. You can try to remove the whole `C:\devops-agents\agent\_work\r65\a\Project.Web.Test.Automation\Output\node_modules\playwright-core\.local-browsers\chromium_win64_special-1050\` folder and install chromium again with `npx playwright install` and test again.

I guess you already tried without using `PLAYWRIGHT_BROWSERS_PATH`?

**Comment by mxschmitt** [comment] 2023-03-14 12:00
Closing as per above, please re-file for further questions.

**Comment by harleyz** [comment] 2023-03-23 02:01
Had the same issue today after upgrading from 1.27.1 to 1.32.0.  I also during the CI process used 'npx playwright install --with-deps' for the first time, previously it was  'npx playwright install'

**Comment by aslushnikov** [comment] 2023-03-24 07:07
@garciallorente-fer Could it be that you have antivirus software that blocks access to certain libs?

**Closed** 2023-03-24 07:09 UTC
Labels: triaging

**Comment by AbhishekrishnaMurthy** [comment] 2023-03-24 20:30
Facing the exact same issue. Nothing changed from the code side but suddenly stopped working for chrome. How to downgrade playwright on windows server? ( If that would fix the issue ) Or should I be avoiding a particular version of chrome and playwright combination for now? Any suggestion is helpful.

**Comment by chilingling** [comment] 2023-03-28 11:33
> Facing the exact same issue. Nothing changed from the code side but suddenly stopped working for chrome. How to downgrade playwright on windows server? ( If that would fix the issue ) Or should I be avoiding a particular version of chrome and playwright combination for now? Any suggestion is helpful. @harleyz @aslushnikov @garciallorente-fer

Perhaps it is because your computer no longer supports a higher version of the Chrome browser. Starting from version 110, Chrome does not support Windows 7/8/8.1 and Windows Server 2012.

https://support.google.com/chrome/thread/185534985/sunsetting-support-for-windows-7-8-8-1-and-windows-server-2012-and-2012-r2-in-early-2023

**Comment by amankul** [comment] 2023-03-28 17:10
Following the thread since its affecting us too.

**Comment by amankul** [comment] 2023-03-28 17:15
> @AbhishekrishnaMurthy we'd be happy to look into this if we can reproduce this somewhere, e.g. on Github Actions workflow. Other than that, it's hard to recommend anything since we have no idea what's causing this.
> 
> To downgrade playwright, just install the older version of NPM package.

@aslushnikov Does github actions workflow allow you to choose platform? Can you see how it goes with "Windows Server 2012" if so.

**Comment by aslushnikov** [comment] 2023-03-28 23:08
@amankul here are the environments you can use in Github Actions: https://github.com/actions/runner-images

If you can repro in any of these, please do not hesitate to open a new issue right away.

**Comment by harleyz** [comment] 2023-04-23 00:55
@aslushnikov - tried again today with the same result.  updated to latest, failed with the error above and rolled back again to 1.27.1.  Had upgraded from angular 14 to angular 15 today so thought I'd give it another shot...  I can confirm I am on windows server 2019 and utilizing azure devops server on prem not sure if that helps at all, seems unrelated imo.

**Comment by harleyz** [comment] 2023-05-17 16:57
@amankul , @aslushnikov , @mxschmitt , @chilingling @garciallorente-fer - has anyone had success on an upgrade yet?

**Comment by Rycorlin** [comment] 2023-06-15 21:58
Came here just to chime in. 

I am just now setting up a project with dotNet Playwright and ran into the same issue with the newest version (1.35.0) during my ado pipeline run.

Thanks to this forum I was able to get it working by downgrading to 1.27.1

Can confirm its not yet fixed.

**Comment by harleyz** [comment] 2023-06-22 04:17
@amankul - any chance we can get this issue opened up and considered for triage?

**Comment by mxschmitt** [comment] 2023-06-22 07:08
Please file a new issue with more details about your ado pipeline.

**Comment by JenH11** [comment] 2023-07-04 15:12
I too have been seeing this problem with 1.35. I'm on the brink of trying to downgrade but am not filled with hope for it resolving the issue seeing as others have tried & it's not fixed. Any updates appreciated

**Comment by mxschmitt** [comment] 2023-07-04 22:25
Please file a new issue, since we don't monitor closed issues. Thanks.
