### ISSUE TITLE
[BUG]: get 'Failed to connect to the bus' error

### ISSUE THREAD

**Issue by Gong-la** [microsoft/playwright#24450] opened 2023-07-27 03:51 UTC
### System info
- Playwright Version: [v1.36.2]
- Operating System: [macOS 13.3.1]
- Browser: [Edge]
- Other info:

**Config file**

```ts
// playwright.config.ts
import { PlaywrightTestConfig } from '@playwright/test'
import { VIEWPORT } from './utils/constants'

const config: PlaywrightTestConfig = {
  timeout: 120000,
  reportSlowTests: { max: 0, threshold: 100001 },
  use: {
    headless: false,
    screenshot: 'only-on-failure',
    trace: 'retain-on-failure',
    ignoreHTTPSErrors: true, // ignore local certificate
    baseURL: 'xxx'
  },
  testDir: 'e2e',
  projects: [
  {

    name: 'Desktop Microsoft Edge',
    use: {
      // Supported Microsoft Edge channels are: msedge, msedge-beta, msedge-dev, msedge-canary
      channel: 'msedge-beta',
      viewport: VIEWPORT.DESKTOP
    }
  },
  ]
}

export default config

```
When I run tests in docker, some test filed and I got this error.
Could some one help me?

**Actual**

```
 1) [Desktop Microsoft Edge] › xxx/xxx/xxx.spec.ts:57:9 › test description › test name
Error: browserType.launch: Browser closed.
    ==================== Browser output: ====================
    <launching> /opt/microsoft/msedge-beta/msedge --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-RnrHNj --remote-debugging-pipe --no-startup-window
    <launched> pid=1309
    [pid=1309][err] [0727/033929.247596:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
    [pid=1309][err] [0727/033929.384299:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
    [pid=1309][err] [0727/033929.384874:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
    =========================== logs ===========================
    <launching> /opt/microsoft/msedge-beta/msedge --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-RnrHNj --remote-debugging-pipe --no-startup-window
    <launched> pid=1309
    [pid=1309][err] [0727/033929.247596:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
    [pid=1309][err] [0727/033929.384299:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
    [pid=1309][err] [0727/033929.384874:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
    ============================================================

```

**Comment by mxschmitt** [comment] 2023-07-28 09:24
Are you using our [Docker best practises](https://playwright.dev/docs/ci#docker)? (--init and --ipc=host)?

Are you on an M1 Mac? Since Microsoft Edge is [not available](https://techcommunity.microsoft.com/t5/discussions/edge-for-linux-arm64/m-p/1532272/page/2) for linux/arm64 and it can't be emulated there.

**Comment by Gong-la** [comment] 2023-08-02 00:35
> Are you using our [Docker best practises](https://playwright.dev/docs/ci#docker)? (--init and --ipc=host)?
> 
> Are you on an M1 Mac? Since Microsoft Edge is [not available](https://techcommunity.microsoft.com/t5/discussions/edge-for-linux-arm64/m-p/1532272/page/2) for linux/arm64 and it can't be emulated there.

I run it follow this:
```
docker build --tag playwright .
docker run \
  --ipc=host \
  --rm \
  -it \
  -v $(pwd):/app \
  --workdir="/app" \
  -e CI=true \
  playwright sh -c "npm ci && npx playwright install msedge-beta && npm run test"
```

**Comment by mxschmitt** [comment] 2023-08-02 08:15
Are you on a M1 Mac? Or how does your host system look like?

**Comment by Gong-la** [comment] 2023-08-02 11:09
> Are you on a M1 Mac? Or how does your host system look like?

Hi @mxschmitt , actually I'm not very sure, I run it on a Buildkite pipeline.

**Comment by mxschmitt** [comment] 2023-08-02 11:40
I can reproduce. We recently had a related issue and were in contact with the Microsoft Edge team. They fixed it in Dev and are going to cherry-pick it into their Beta channel.
-> I was able to repro it in Beta only, Stable and Dev were fine.

Repro:

```shell
docker run -it --ipc=host --rm -e CI=true mcr.microsoft.com/playwright:v1.36.0-jammy
cd /root
npm init playwright my-project
cd my-project
apt update && apt install nano -y
nano playwright.config.ts
-> add channel: 'msedge-beta', to chromium
npx playwright install msedge-beta
npx playwright test --project=chromium
```

So I recommend to wait for now until a new Edge Beta version got released or test on Dev instead in the meantime.

**Comment by Gong-la** [comment] 2023-08-03 07:40
> I can reproduce. We recently had a related issue and were in contact with the Microsoft Edge team. They fixed it in Dev and are going to cherry-pick it into their Beta channel. -> I was able to repro it in Beta only, Stable and Dev were fine.
> 
> Repro:
> 
> ```shell
> docker run -it --ipc=host --rm -e CI=true mcr.microsoft.com/playwright:v1.36.0-jammy
> cd /root
> npm init playwright my-project
> cd my-project
> apt update && apt install nano -y
> nano playwright.config.ts
> -> add channel: 'msedge-beta', to chromium
> npx playwright install msedge-beta
> npx playwright test --project=chromium
> ```
> 
> So I recommend to wait for now until a new Edge Beta version got released or test on Dev instead in the meantime.

Thanks a lot! @mxschmitt. I will use Dev instead.

**Comment by mxschmitt** [comment] 2023-08-03 13:43
Closing by that then for now.

**Closed by mxschmitt** 2023-08-03 13:43 UTC
Labels: triaging
