### ISSUE TITLE
[BUG] locator.check() unreliable

### ISSUE THREAD

**Issue by pascalknupper** [microsoft/playwright#28003] opened 2023-11-07 10:34 UTC
A bunch of test are failing unreliable in our CI worklfow with the exception "locator.check: Timeout 10000ms exceeded.". As this is not happening on local execution and only sometimes in our Github Action workflow, there seems to be something unreliable with checking radio buttons in Playwright. Happens even with force or no force option.
 
```
TimeoutError: locator.check: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for getByLabel('Frau')
  locator resolved to <input type="radio" value="MISSES" name="salutation" cl…/>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
```

### System info
- Playwright Version: 1.39.0
- Operating System: Image mcr.microsoft.com/playwright:v1.39.0-jammy
- Browser: All, but more often in Firefox

### Source code
Selector: 

```
this.femaleSalutationRadioBtn = page.getByLabel('Frau');
```

Checking of radio button

```
 async selectRadio(
    salutation: string,
  ) {
    if (salutation == 'female') {
      await this.femaleSalutationRadioBtn.check();
    } else if (salutation == 'male') {
      await this.maleSalutationRadioBtn.check();
    } else {
      await this.unknownSalutationRadioBtn.check();
    }
```

```
 async selectRadioForce(
    salutation: string,
  ) {
    if (salutation == 'female') {
      await this.femaleSalutationRadioBtn.check({ force: true });
    } else if (salutation == 'male') {
      await this.maleSalutationRadioBtn.check({ force: true });
    } else {
      await this.unknownSalutationRadioBtn.check({ force: true });
    }
```

**Expected**

No timeout and radio button is checked

**Actual**

Timeout on radio button selection  and sometime not even checked

**Comment by dgozman** [comment] 2023-11-07 16:38
@pascalknupper We need more information to act on this issue. Could you please provide a repro that we can run locally?

**Comment by pascalknupper** [comment] 2023-11-09 08:04
@dgozman I set up this repo [example](https://github.com/pascalknupper/playwright-check-example)

Here is one [example](https://pascalknupper.github.io/playwright-check-example/#?testId=a30a6eba6312f6b87ea5-aca734f71ffc3a668b1d) for such a case where the radio is not checked after the check method has been called successfully. I attached the corresponding traces.

[trace_check.zip](https://github.com/microsoft/playwright/files/13305399/trace_check.zip)

**Comment by dgozman** [comment] 2023-11-09 20:40
@pascalknupper Thank you for the repro. Unfortunately, I was not able to reproduce after running the tests ~100 times.

Looking at the trace though, it seems likely that your site clears the checkbox/radio state after it was clicked. Perhaps the site uses hydration, and resets to the original state after hydration is completed? You can read more [about hydration here](https://playwright.dev/docs/navigations#hydration).

**Comment by dgozman** [comment] 2023-11-13 05:19
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.

**Closed by dgozman** 2023-11-13 05:19 UTC
Labels: triaging
