### ISSUE TITLE
[Bug]: NPX Playwright Install is not installing the browsers

### ISSUE THREAD

**Issue by ShivaPotlapelli** [microsoft/playwright#29498] opened 2024-02-14 17:29 UTC
### Version

1.32.3

### Steps to reproduce

**Node version v18.12.0
NPM version 8.19.2
Os Macos 14.2.1 (23C71)**
Than do npm i and later perform npx playwright install

### Expected behavior

Should be able to install dependencies browsers

### Actual behavior

Terminal is struck up on and not showing any progress of installation

### Environment

```shell
**Node version v18.12.0
NPM version 8.19.2
Os Macos 14.2.1 (23C71)**
Than do npm i and later perform npx playwright install
```

**Comment by mxschmitt** [comment] 2024-02-14 17:52
Could you try this?

```
npm i -g npm@latest
DEBUG=pw:install npx playwright install
```

The first will update NPM and the second will install the browsers with having debug install logs enabled.

**Comment by ShivaPotlapelli** [comment] 2024-02-14 17:54
I did this as mxschmitt
now am seeing issue related to 
Failed to install browsers
Error: EACCES: permission denied, mkdir '/Users/shiva/Library/Caches/ms-playwright/__dirlock'

**Comment by mxschmitt** [comment] 2024-02-14 17:59
Looks like the folder has incorrectly confirmed permissions, I'd recommend:

    rm -rf /Users/shiva/Library/Caches/ms-playwright/

and execute install again.

**Comment by ShivaPotlapelli** [comment] 2024-02-14 18:00
@mxschmiit it worked

**Comment by mxschmitt** [comment] 2024-02-14 18:01
Closing by that then. If you have reproducible steps on how you ended up in this stage, we're happy to follow up to analyse further.

**Closed by mxschmitt** 2024-02-14 18:01 UTC
