### ISSUE TITLE
[BUG] browser._newContextForReuse: Navigation failed because page was closed

### ISSUE THREAD

**Issue by theisgroenbech** [microsoft/playwright#17903] opened 2022-10-07 09:45 UTC
**Context:**
- Playwright Version: 1.24.0 and above
- Operating System: Linux and Mac
- Node.js version: 16
- Browser: All

**Code Snippet**

```
2) [webkit] › components/testComponent/testComponent.test.tsx:17:1 › TestComponent is accessible

Test timeout of 10000ms exceeded while setting up "context".

  Pending operations:
  - browser._newContextForReuse

browser._newContextForReuse: Navigation failed because page was closed!
=========================== logs ===========================
navigating to "about:blank", waiting until "load"
============================================================
```

**Describe the bug**
There seem to have been introduced a race condition in version 1.24.0. (This bug is not present in version 1.23.4)

When I run a significant amount of component tests (over 100), some of them fail with the above error. It is always a random test.
If I run the given test in isolation, it works fine.

I have looked through the commits in the 1.24.0 release, and I think that the issue might have been introduced in this PR
https://github.com/microsoft/playwright/pull/15432

**Comment by pavelfeldman** [comment] 2022-10-07 20:38
Any chance we could get access to your repo? I'd love to be able to run it a bunch of times and nail down the root cause.

**Comment by theisgroenbech** [comment] 2022-10-10 06:28
I will create something for you

**Comment by pavelfeldman** [comment] 2022-10-17 15:57
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Comment by pavelfeldman** [comment] 2022-10-19 17:38
I confused this issue with another one, I now remember that you shared the repro offline with me.

**Comment by pavelfeldman** [comment] 2022-10-20 02:42
@theisgroenbech pinging you for a hidden module on Slack

**Comment by pavelfeldman** [comment] 2022-10-26 20:02
The reason is the `beforeunload` handler.

**Closed** 2022-10-26 22:17 UTC
Labels: v1.28
