### ISSUE TITLE
[Question]Unable to download csv file during automation

### ISSUE THREAD

**Issue by sirishamadhavaram** [microsoft/playwright#17284] opened 2022-09-13 08:33 UTC
I have a use case where in a csv file should be downloaded upon a button click. When i automate this, I see the downloaded file does not have any extension and is categorized as ' File' format . I cannot use the  SaveAs method as my use case has to validate that a csv file is downloaded from the application. Can you please help me with this.

**Comment by mxschmitt** [comment] 2022-09-13 08:37
Did you go through this guide? https://playwright.dev/docs/downloads

After clicking on the button a download event gets emitted.

Can you share code with us? you don't need to right click and click "Save As", if the browser emits a download event, Playwright will handle it.

**Comment by sirishamadhavaram** [comment] 2022-09-13 08:53
This is the code I have used
![image](https://user-images.githubusercontent.com/78092934/189857192-0e2014e2-6927-4067-af85-53855103e59c.png)

Also, the downloaded file looks like this  
![image](https://user-images.githubusercontent.com/78092934/189857401-39ea63ca-4ebf-4651-8d38-0dc6b6bb7a63.png)

![image](https://user-images.githubusercontent.com/78092934/189857476-97092150-c5db-4504-9f1b-4a797e2bf677.png)

**Comment by sirishamadhavaram** [comment] 2022-09-13 09:01
Also, when I try to download these files (I have tried .csv, .txt and .pdf files)  manually (not through any automated script) from the playwright initiated browser session, I have noticed the downloaded file is not of the expected type but is of the File type. 

![image](https://user-images.githubusercontent.com/78092934/189859082-96180d19-f664-4da0-a580-f7ea92fbb08e.png)

The same thing when downloaded from a normal browser session looks like 
![image](https://user-images.githubusercontent.com/78092934/189859412-db4e9970-229f-4dc1-b834-a8825a56bc56.png)

**Comment by mxschmitt** [comment] 2022-09-13 09:05
This is expected, Playwright is for end-to-end testing, so you never want to do stuff manually as a user.

You can assert the file name using `download.suggestedFilename()` and open the file with `download.path()` see [here](https://playwright.dev/docs/api/class-download).

**Comment by denys-vowel** [comment] 2022-09-14 10:11
I have the same problem when I try to download mp4 file. 
Also I can prove that this issue is reproducible for any browser opened by Playwright when I try to download manually.
<img width="672" alt="Screenshot 2022-09-14 at 13 08 58" src="https://user-images.githubusercontent.com/109543305/190126619-bca4aae2-e6fc-4e3d-8860-e34c08b6e61d.png">

**Comment by shadzpw** [comment] 2022-09-14 13:17
I am facing a similar issue while downloading an excel (.xlsx format), exporting excel from the ag-grid.

Getting the below error:-
**page.waitForEvent: Timeout 30000ms exceeded while waiting for event "download"**

I followed the same steps as described in https://playwright.dev/docs/api/class-download.

Note:
I can see the "download" event being triggered by running the same test in Cypress Test Runner console and
Test seems to be running fine in Cypress.

**Comment by mxschmitt** [comment] 2022-09-14 13:29
@shadzpw please file a separate issue with a repro, mixing different issues will lead to confusion.
@denys-vowel this is expected, Playwright is for automated end-to-end testing and you can get the details for the download via the Downlod API: https://playwright.dev/docs/downloads

**Comment by denys-vowel** [comment] 2022-09-14 13:36
@mxschmitt It looks weird, because the code in official documentation https://playwright.dev/docs/api/class-download#download-path throws the following error. 

<img width="578" alt="Screenshot 2022-09-14 at 16 32 26" src="https://user-images.githubusercontent.com/109543305/190168495-2d4ef0a8-8d55-47e9-bc31-353d46c35dc7.png">

For now I need to use the following workaround:
<img width="368" alt="Screenshot 2022-09-14 at 16 35 39" src="https://user-images.githubusercontent.com/109543305/190168687-6d9784eb-df24-4b47-a36a-b2a13a991dc3.png">

**Comment by mxschmitt** [comment] 2022-09-14 14:23
@denys-vowel yes you need to do what the exception says, use saveAs() instead of path() to save it and then be able to open it.

**Comment by mxschmitt** [comment] 2022-09-16 09:35
Closing as part of the triage process since it's answered as per above and multiple issues get mixed here. Please create a new issue with a detailed reproducible or feature request if you still face issues.

**Closed by mxschmitt** 2022-09-16 09:35 UTC
Labels: triaging
