### ISSUE TITLE
[Feature]: Create BrowserContext.MaximizeWindow function. PLEAAASE

### ISSUE THREAD

**Issue by PeterHevesi** [microsoft/playwright#33887] opened 2024-12-06 10:51 UTC
### 🚀 Feature Request

I have tried to explain to you, that many of us NEED this feature!
For me, because I can't set browser maximized, I can't make tests of our enterprise website reliable, because Firefox starts splitted into 2 screens instead of being on just 1 screen... Then the website rendering is not alright and my tests keep failing on my colleague workstation... And an ability to set the browser maximized would solve this... So this is not about your opinion, to tell everybody, that you just should use exact dimensions... Then why this issue had 96 upvotes and why many people were saying, that they NEED this feature?

At least tell us why you don't want to implement it. Is it because it is hard or impossible to solve it? I hardly doubt it is impossible....
Don't just ignore us! At least provide explanation, that would be fair... 

### Motivation

This will help me to solve SIGNIFICANT ISSUE I am facing... I have created it as a feature request, since that is how you would probably perceive this, but for me, this is like bug! It doesn't allow me to test our enterprise website using Firefox on my colleague's workstation...

**Comment by marshmn** [comment] 2024-12-06 12:51
Duplicate of #4046 

Further discussion in Discord: https://discord.com/channels/807756831384403968/1314545289914351697

**Comment by Skn0tt** [comment] 2024-12-06 17:23
Closing as duplicate.

**Closed by Skn0tt** 2024-12-06 17:23 UTC
