### ISSUE TITLE
[BUG] [Webkit] `http` authentication is failing without the browser refresh after the browser is authenticated with `http` authentication

### ISSUE THREAD

**Issue by ukdas** [microsoft/playwright#9930] opened 2021-11-01 18:49 UTC
**Context:**
- Playwright Version: 1.16.1 (Issue is not specific to this version as it's been observed with old versions also)
- Operating System: Windows
- Node.js version: v14.17.6
- Browser: WebKit only
- Environment Type: On-Premise
- Authentication: http authentication

**Code Snippet**
Below are the some snapped code for the Webkit browser's http authentication.

Used the below code to launch the `Webkit` browser server -

```
const browserType = "Webkit";
const browser = await playwright[browserType].launchServer(
		{
			headless: false,
			webSocket: true,
			defaultViewport: { width: 1200, height: 720 },
			args: ["--start-maximized", "--no-sandbox", "--disable-web-security"],
		},
		"server"
	);
```

Used `wsEndPoint` for connecting to the browser - 
```
await playwright[browserType ].connect({
			wsEndpoint: browser.wsEndpoint(),
		});

```
Used below code to perform `http` authentication & creating new context and page - 
```
context = await browser.newContext({
				httpCredentials: {
					username: userName,
					password: userPassword,
				},
			});
page = await context.newPage();
```

**Describe the bug**

`http` authentication is failing without the browser refresh after the `http` authentication is performed. The issue is only occurred for this `Webkit` browser.

Due to confidentiality issue, couldn't able to provide the environment details.

Error Message: HTTP Error 401.0 - Unauthorized

Previously logged issue - [8597](https://github.com/microsoft/playwright/issues/8597)

**Comment by unlikelyzero** [comment] 2021-11-01 20:28
The safari team does not support basic auth over wss://

https://bugs.webkit.org/show_bug.cgi?id=80362

**Comment by mxschmitt** [comment] 2021-11-02 11:39
> Due to confidentiality issue, couldn't able to provide the environment details. 

Without a repro, it's hard to help. Are you able to create a [minimum reproducible](https://stackoverflow.com/help/minimal-reproducible-example) for us?

**Comment by mxschmitt** [comment] 2021-11-08 09:56
Closing since the linked upstream bug is different and we don't have something to try locally. We need a repro otherwise we can't provide assistance.

**Closed by mxschmitt** 2021-11-08 09:56 UTC
Labels: triaging
