### ISSUE TITLE
[Feature]: multipart accepting form data

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright#29574] opened 2024-02-20 11:15 UTC
### 🚀 Feature Request

Hello,

Use case:
Back-end Glue API service accepts multiple files with same field name '**attachment**'

```
POST https://host:post/v1/email

--WebAppBoundary
Content-Disposition: form-data; name="email"; Content-Type: application/json

--WebAppBoundary
Content-Disposition: form-data; name="attachment"; filename="file1.pdf" Content-Type: application/octet-stream

--WebAppBoundary
Content-Disposition: form-data; name="attachment"; filename="file2.csv" Content-Type: application/octet-stream
```

Trying to send multiple files with following code, but multipart does not accept form data:

```
const formData = new FormData();
formData.append('email', {Json Payload});
formData.append('attachment', fs.createReadStream('file1.pdf'));
formData.append('attachment', fs.createReadStream('file2.csv'));

response = await request.post("https://host:post/v1/email", {
headers: setToken(),
multipart: formData
});
```

I saw Java language port supports that, but what about JS/TS ? 

![image](https://github.com/microsoft/playwright/assets/94455079/c86dac7e-61da-4bb0-85e3-eff19e4c4c74)

### Motivation

Supporting multiple file attachments (email API) when that API accepts form fields with the same name.

**Comment by mxschmitt** [comment] 2024-02-20 20:08
Looks like a duplicate of https://github.com/microsoft/playwright/issues/28070

**Comment by NikkTod** [comment] 2024-02-20 20:21
Yep, looks similar, is there some workaround :pray:

**Comment by mxschmitt** [comment] 2024-02-20 20:24
Unfortunately not as of today.

**Closed by mxschmitt** 2024-02-20 20:23 UTC
