### ISSUE TITLE
[Question] How to send Rest API request and fetch response in Playwright?

### ISSUE THREAD

**Issue by shiv-jirwankar** [microsoft/playwright#8717] opened 2021-09-05 12:28 UTC
I want to create all HTTP methods requests and fetch the response data with Playwright. Is there any way by which we can achieve this with Playwright or do we need to go for other API libraries for making API request?

**Comment by mxschmitt** [comment] 2021-09-06 11:09
Closing as a duplicate of https://github.com/microsoft/playwright/issues/5999 which gets released soonish, stay tuned!

**Closed by mxschmitt** 2021-09-06 11:09 UTC

**Comment by nishant-shah-social** [comment] 2021-09-07 13:31
@mxschmitt Just out of curiosity...How soonish? :)

**Comment by mxschmitt** [comment] 2021-09-07 13:36
Its marked as 1.15 so in around 1 week.

**Comment by shiv-jirwankar** [comment] 2021-09-22 09:54
@mxschmitt I see the v.1.15 is out now. Can you please share some code snippets in order to send Rest API request and fetch corresponding request's response. Thanks.

**Comment by mxschmitt** [comment] 2021-09-22 10:00
It got released as a beta-feature. See here for examples: https://github.com/microsoft/playwright/blob/43a690c20427dbe3882c4df18ab061c5746b06fe/tests/browsercontext-fetch.spec.ts

It gets announced and officially released in 1.16.
