### ISSUE TITLE
[BUG] Running in headless:true mode in Chrome triggers test failure with error 'EPERM: operation not permitted'

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#8911] opened 2021-09-14 06:37 UTC
**Context:**
- Playwright Version: 1.14.1
- Operating System: Windows
- Node.js version: 14.16.1
- Browser: Chromium
- IDE: Webstorm

**Code Snippet**

**Playwright configuration file:**

```javascript
import {PlaywrightTestConfig} from "@playwright/test";

const config: PlaywrightTestConfig = {
    retries: 1,
    timeout: 150000,
    globalTimeout: 3000000,
    reporter: [["./my-reporter.ts"], ["list"], ["junit", {outputFile: "reports/test-results.xml"}], ["allure-playwright"]],
    use: {
        browserName: 'chromium',
        trace: 'on',
        screenshot: 'on',
        viewport: {width: 1400, height: 900},
        video: {
            mode: "on-first-retry",
            size: {
                width: 1400,
                height: 900,
            }
        },
        contextOptions: {
            //viewport: {width: 1500, height: 1000},
        },
        // Browser options
        launchOptions: {
            channel: 'chrome', 
            headless: true,
        },
    },
};

export default config;

```
**package.json file**
```javascript
{
  "name": "playwright-seatgeek",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "npx playwright test",
    "test:1": "npx playwright test --workers=1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@playwright/test": "^1.14.1",
    "@types/faker": "^5.5.8",
    "playwright": "^1.14.1"
  },
  "dependencies": {
    "allure-playwright": "^2.0.0-beta.13",
    "faker": "^5.5.3",
    "tslog": "^3.2.2"
  }
}

```

**Test file**
```javascript
import {CrmEnum} from './../../../unify/navigationEnums/CrmEnum';
import {SalesEnum} from './../../../unify/navigationEnums/SalesEnum';
import test, {expect} from "@playwright/test";
import BasePage from "../../../common/BasePage";
import CrmPage, {GridStateEnum} from "../../../unify/pages/crm/CrmPage";
import ApplicationUrl from "../../../helpers/applicationUrl";

import UnifyLoginPage from "../../../unify/pages/UnifyLoginPage";
import SalesPage from "../../../unify/pages/sales/SalesPage";


test.describe("Crm payments tests", async () => {
    let basePage: BasePage;
    let unifyLoginPage: UnifyLoginPage;

    let crmPage: CrmPage;
    let salesPage: SalesPage;

    test.beforeEach(async ({page}) => {
        basePage = new BasePage(page);
        unifyLoginPage = new UnifyLoginPage(page);

        crmPage = new CrmPage(page);
        salesPage = new SalesPage(page);
        //await page.pause();
        await basePage.loadApplication(ApplicationUrl.UNIFY);
        await page.setViewportSize({width: 1400, height: 900});
        await unifyLoginPage.loginToUnify("sro", "1");
        await crmPage.goto();
    });

    test.afterEach(async ({context}) => {
        await context.clearCookies();
    });


    test.only("CRM - Paying for paid and unpaid tickets AUT-868", async ({page}) => {
        // https://seatgeek.atlassian.net/browse/AUT-985
        await crmPage.openDefaultClient();
        await buy2TicketsAndPayLater(page);
        await returnToCrmAndNavigateToBalanceUnpaid();
        await chooseOneTicketsYouBoughtAndPay4It()
        await salesPage.returnToCrm();
        await choosePaidTicketAndUnpaidTicketAndPayForItems();

        // Verify there is only one item to pay for
        await salesPage.expand();
        const numberOfItemsToPayFor = await salesPage.getNumberOfItemsToPayFor();
        console.log('numberOfItemsToPayFor => ', +numberOfItemsToPayFor);
        expect(numberOfItemsToPayFor).toBe('1');
    });

    async function buy2TicketsAndPayLater(page) {
        await crmPage.sellToCurrentClient();
        await salesPage.selectCategory(SalesEnum.Events);
        await salesPage.chooseSecondEvent();
        await salesPage.addBestSeats();
        await page.waitForTimeout(200);
        await salesPage.next();
        await salesPage.payLater();
        await salesPage.pressFinish();
    }

    async function returnToCrmAndNavigateToBalanceUnpaid() {
        await salesPage.returnToCrm();
        await crmPage.selectCategory(CrmEnum.Balance)
        await crmPage.selectSubCategory(CrmEnum.Unpaid)
        await crmPage.changeView(GridStateEnum.List);
    }

    async function chooseOneTicketsYouBoughtAndPay4It() {
        await crmPage.selectFirstRow();
        await crmPage.payForSelectedItems();
        await salesPage.addPayment();
        await salesPage.submit();
        await salesPage.pressFinish();
    }

    async function choosePaidTicketAndUnpaidTicketAndPayForItems() {
        await crmPage.displayUnpaid(true);
        await crmPage.selectFirstRow();
        await crmPage.selectSecondRow();
        await crmPage.payForSelectedItems();
    }
});





```

**Describe the bug**

I performed tests with the "headless: true" flag (see the config file above) and got the errors like the following:

![image](https://user-images.githubusercontent.com/52656401/133207223-d20cb204-9f1d-4401-a1a9-4ecd118a199b.png)

On the retry:

![image](https://user-images.githubusercontent.com/52656401/133207312-746b40ce-98b8-4a29-8c9f-7d4b61b406eb.png)

If I perform the test with the "headless: false" flag it succeeds.  

![image](https://user-images.githubusercontent.com/52656401/133207550-2b7bb463-8482-41ba-941c-b01a2483d8c5.png)

**Comment by dgozman** [comment] 2021-09-14 18:16
@AlexKomanov I think the headless/headed is just a symptom. The problem is that test runner tries to create a directory and fails. Could you run that `mkdir D:\projects\...` yourself and see whether it works? That might be an environment problem, in which I ma not sure we can help.

**Comment by dgozman** [comment] 2021-09-20 13:49
@AlexKomanov Does this still repro? Did you try running `mkdir` yourself?

**Comment by AlexKomanov** [comment] 2021-09-20 16:38
@dgozman 
Sorry. 
I forgot to update.
I'm able to create with your command.

**Comment by mxschmitt** [comment] 2021-09-21 08:04
So the issue seems solved now?

**Comment by mxschmitt** [comment] 2021-09-25 11:37
Closing since it seems fixed. Please create a new issue if you still encounter any issues, thanks!

**Closed by mxschmitt** 2021-09-25 11:37 UTC
Labels: triaging
