### ISSUE TITLE
[BUG] Empty recording files when using Electron

### ISSUE THREAD

**Issue by MeravYa** [microsoft/playwright#16453] opened 2022-08-11 12:38 UTC
**Context:**
- Playwright Version: 1.24.2
- Operating System: Windows

When trying to record while using Electron tests, the recording files are empty.
This is the way I've configured the recording:

  const options = {
        executablePath: appInfo.executable,
        recordVideo: {dir: 'videos/', size: { width: 1280, height: 720 }}
    };

    return await electron.launch(options);

Thanks

**Comment by mxschmitt** [comment] 2022-08-12 11:36
I tried to reproduce it, for me it was working by using the https://github.com/mxschmitt/electron-quick-start. Could you provide us a full repro?

We usually recommend the trace viewer instead of videos, since it also contains DOM, element inspection etc.: https://playwright.dev/docs/trace-viewer

**Comment by rwoll** [comment] 2022-08-14 17:15
Closing as part of triage per-above. Please file a new issue with the information requested above, and reference this issue.

A repro will help ensure we are actually debugging the same issue you are facing and will minimize us guessing. This is especially helpful when there are several layers/pieces involved.

Ideally the repro is a GitHub repository we can clone, download, and run to see the issue ourselves. It should include the commands to run it, too.

Thanks!

**Closed by rwoll** 2022-08-14 17:15 UTC
Labels: triaging
