### ISSUE TITLE
[BUG] Can not perform swiping on mobile browser of Playwright

### ISSUE THREAD

**Issue by nnson0310** [microsoft/playwright#22639] opened 2023-04-26 04:38 UTC
### System info
- Playwright Version: v1.32
- Operating System: All
- Browser: All

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  timeout: 120 * 1000,
  testDir: './e2e_tests',
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 5 : 5,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://127.0.0.1:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },

  /* Configure projects for major browsers */
  projects: [
    // {
    //   name: 'chromium',
    //   use: { ...devices['Desktop Chrome'] },
    // },

    // {
    //   name: 'firefox',
    //   use: { ...devices['Desktop Firefox'] },
    // },

    // {
    //   name: 'webkit',
    //   use: { ...devices['Desktop Safari'] },
    // },

    /* Test against mobile viewports. */
    {
      name: 'Mobile Chrome',
      use: { ...devices['Pixel 5'] },
    },
    // {
    //   name: 'Mobile Safari',
    //   use: { ...devices['iPhone 12'] },
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { ..devices['Desktop Chrome'], channel: 'chrome' },
    // },
  ],

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   url: 'http://127.0.0.1:3000',
  //   reuseExistingServer: !process.env.CI,
  // },
});

```

**Test file (self-contained)**

```js
import { test, expect, Page } from '@playwright/test';

test.beforeEach(async ({ page }) => {
    await page.goto('https://hoanghamobile.com/');
    await page.waitForTimeout(120);
    
})

test('Test Swipe Action', async ({ page }) => {
    
});
```

**Steps**
- Run the test and watch a browser is opened until 120 seconds is timed out
- Try to swipe the carousel block using mouse

**Expected**
The carousel should be swiped with no problem

**Actual**
The carousel block can not be swiped using mouse. Although, I can still swipe normally on mobile browser of Chrome/Firefox Dev Tools
See below videos:

https://user-images.githubusercontent.com/100401156/234471244-db557e89-ef46-4544-ab47-591705defab0.mp4

https://user-images.githubusercontent.com/100401156/234471255-a17dd71c-4678-4695-9b4c-1ea0bfb09120.mp4

**Comment by aslushnikov** [comment] 2023-04-26 22:13
Technically, your website doesn't listen to mouse events. DevTools emulates these, and Playwright codegen doesn't. 

Fundamentally, this is a dupe of https://github.com/microsoft/playwright/issues/2903
Please upvote to bump its priority!

**Closed by aslushnikov** 2023-04-26 22:13 UTC
