### ISSUE TITLE
[Question] `getByRole` is 1.5x slower than CSS selectors

### ISSUE THREAD

**Issue by ilyazub** [microsoft/playwright#28143] opened 2023-11-14 19:52 UTC
`getByRole` is 1.5x slower than CSS selectors. Probably, because [`getByRole` uses of `querySelectorAll('*')` and matches elements by the accessible name](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/injected/roleSelectorEngine.ts#L129-L161).

```js
// Visit a random page from the StackOverflow question
await page.goto('https://app.pws.int.cruk.org/support-us/details');

console.time("getByRole");
for (let i = 0; i < 100; i++) {
  const textContent = await page.getByRole('button', { name: 'Enter address manually' }).textContent()
}
console.timeEnd("getByRole");

console.time("CSS selector");
for (let i = 0; i < 100; i++) {
  const textContent = await page.locator('.ektjNL').textContent()
}
console.timeEnd("CSS selector");

// Output:
// getByRole: 677.5ms
// CSS selector: 497.306ms
```

I [debugged `getByRole` internals](https://serpapi.com/blog/css-selectors-faster-than-getbyrole-playwright/) but haven't profiled yet. I can profile and optimize the code if it's important for the community to improve the "smart" locators performance.

**Comment by mxschmitt** [comment] 2023-11-15 11:07
Does this create any issues for your tests or does it make tests unusable? So far this seems by design, since role selectors are by definition more performance intense.

**Comment by ilyazub** [comment] 2023-11-15 18:42
No, it doesn't create issues. I wondered if it's helpful to speed up the Playwright CI pipeline.

Let me know if you want me to close this issue.

**Comment by mxschmitt** [comment] 2023-11-15 19:50
Closing as per above then.

**Closed by mxschmitt** 2023-11-15 19:50 UTC
Labels: triaging
