### ISSUE TITLE
Playwright.config.ts - projects - when dependencies are improperly declared, UI mode loads tests suite endlessly 

### ISSUE THREAD

**Issue by rejectozaur** [microsoft/playwright#31813] opened 2024-07-23 11:11 UTC
**AS IS:**
1. In Playwright.config.ts have at least 2 projects added one below another.
2. Make the 2nd project have dependency on the 1st one, but include a typo in this dependency's name.
3. Try running tthe tests in the UI Mode.

**RESULT:** You get endless loading state for the tests suite with 0 feedback what's wrong. You either need to use some VS Code addon or find the typo on your own.
![image](https://github.com/user-attachments/assets/dd012a74-9c5f-479a-9802-ade1100b3f9b)

**Repro rate: 100%** 
Playwright version: ^1.43.1

**Fix suggestions:**
1. All the dependencies references to non existing/deviating by name projects should be highlighted as errors causing.
2. UI Mode should return error that this dependency doesn't exist/couldn't be found.

**Comment by pavelfeldman** [comment] 2024-07-24 01:31
I can't reproduce this issue. Could you follow the issue template and provide a repo or archive with your use case?

**Comment by pavelfeldman** [comment] 2024-07-28 21:09
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Closed by pavelfeldman** 2024-07-28 21:09 UTC
