### ISSUE TITLE
[Bug]: Screenshots may be overwritten with another test case

### ISSUE THREAD

**Issue by aokiken** [microsoft/playwright#8068] opened 2021-08-07 18:11 UTC
### Playwright version

1.13.0

### Operating system

MacOS, Linux

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

When executing "sanitizeForFilePath", the return value may be the same.
This has caused the screenshot to be overwritten.

I want adjustment the regular expression condition or make it a unique value so that it will not be overwritten.

https://github.com/microsoft/playwright/blob/b1dc84c953ce275e9e48e30810be858ce2fd3b6d/src/test/workerRunner.ts#L566-L568

### Code snippet to reproduce your bug

```shell
// failtest.spec.ts
import { test, expect } from '@playwright/test';

test('基本的なテスト', async ({ page }) => {
    await page.goto('https://playwright.dev/');
    const name = await page.innerText('.navbar__title');
    expect(name).toBe('Playwright!');
});

test('実験的なテスト', async ({ page }) => {
    await page.goto('https://playwright.dev/');
    const name = await page.innerText('.navbar__title');
    expect(name).toBe('Playwright!!');
});

// playwright.config.ts
import { PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
    use: {
        screenshot: 'only-on-failure',
    },
};
export default config;
```

**Comment by mxschmitt** [comment] 2021-08-08 17:33
I think this is related or a duplicate of #7632. Thanks for reporting!

**Closed** 2021-08-08 18:23 UTC
Labels: triaging, test-runner
