### ISSUE TITLE
[BUG] Can't do assertations using @playwright/test

### ISSUE THREAD

**Issue by BernhardHuberPlanBGmbH** [microsoft/playwright#7129] opened 2021-06-15 06:01 UTC
**Context:**
- Playwright Version: ^1.12.2 (@playwright/test)
- Operating System: macOS
- Node.js version: v14.17.0
- Browser: Chromium
- Extra:
![image](https://user-images.githubusercontent.com/58170799/122000739-9ce29d00-cdaf-11eb-8ff6-ecde3d53217b.png)
![image](https://user-images.githubusercontent.com/58170799/122000776-aa982280-cdaf-11eb-8693-8423da497800.png)

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```typescript
import { test, expect } from '@playwright/test';

test.describe('Some describe', () => {
  test('some test title', async ({ page }) => {
    const pageTitle: string | null = await page.textContent('#sample');
    expect(pageTitle).toBe('Expected element text');
  });
});

```

**Describe the bug**

All I do is just trying to assert text content of a DOM element. I'm unable to do so as the type the expect function returns does not seem to be correct.

**Comment by mxschmitt** [comment] 2021-06-15 07:14
Duplicate of https://github.com/microsoft/playwright/issues/7099

See there for a workaround. It's getting fixed in the next release.

**Closed** 2021-06-15 08:03 UTC
