### ISSUE TITLE
[BUG] SharedArrayBuffer is not enabled on Playwright build of Firefox

### ISSUE THREAD

**Issue by Friendseeker** [microsoft/playwright#8178] opened 2021-08-13 08:26 UTC
**Context:**
- Playwright Version: "@playwright/test": "^1.13.1"
- Operating System: Windows 10 19042.1165 & macOS Big Sur 11.5.2
- Node.js version: 16.6.2
- Browser: Firefox

**Code Snippet**

```javascript
typeof SharedArrayBuffer // Undefined on Playwright build of Firefox
// Function on non-Playwright stable & nightly build of Firefox
```

**Describe the bug**

SharedArrayBuffer is not enabled on Playwright build of Firefox, while is enabled on [stable](https://www.mozilla.org/en-CA/firefox/new/) & [nightly](https://www.mozilla.org/en-CA/firefox/channel/desktop/) channel of firefox.

***Playwright Build***
![playwright](https://i.imgur.com/6So6ulD.jpg)

***Non-playwright Build***
![non-playwright](https://i.imgur.com/fzdPIFf.jpg)

Extra Note: [test site I used](https://rolla-new.netlify.app/) has proper [cross-origin isolation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer). (2 Custom Headers are present)

**Steps to Reproduce**
- Open Playwright Build of Firefox (%USERPROFILE%\AppData\Local\ms-playwright\firefox-1278\firefox\firefox.exe)
- Open a cross-origin isolated website
- Open Console and type in `typeof SharedArrayBuffer`, then press enter

**Comment by aslushnikov** [comment] 2021-08-13 08:54
@Friendseeker indeed, interesting! I'll look into this

**Comment by aslushnikov** [comment] 2021-08-30 17:43
for the record: the test to reproduce this

```js
it.only('SharedArrayBuffer should work', async function({contextFactory, httpsServer, browserName}) {
  it.fail(browserName === 'webkit', 'no shared array bufffer on webkit');
  const context = await contextFactory({ ignoreHTTPSErrors: true });
  const page = await context.newPage();
  httpsServer.setRoute('/sharedarraybuffer', (req, res) => {
    res.setHeader('Cross-Origin-Opener-Policy', 'same-origin');
    res.setHeader('Cross-Origin-Embedder-Policy', 'require-corp');
    res.end();
  });
  await page.goto(httpsServer.PREFIX + '/sharedarraybuffer');
  // await page.goto(httpsServer.PREFIX + '/empty.html');
  // await page.goto(server.PREFIX + '/empty.html');
  expect(await page.evaluate(() => typeof SharedArrayBuffer)).toBe('function');
});
```

**Comment by aslushnikov** [comment] 2021-08-31 11:46
Further investigation showed that this happens due to us disabling cross-process navigation in Firefox preferences:

https://github.com/microsoft/playwright/blob/a205ee27cb8c22a2c44bbf4212a9741e9f3c531c/browser_patches/firefox-beta/preferences/playwright.cfg#L6-L8

We can force-enable SharedArrayBuffer for insecure contexts using `dom.postMessage.sharedArrayBuffer.bypassCOOP_COEP.insecure.enabled` setting, not sure if it's worth it though.

**Comment by aslushnikov** [comment] 2021-09-06 12:05
This is fixed on tip-of-tree

**Closed by aslushnikov** 2021-09-06 12:05 UTC
Labels: browser-firefox, v1.15
