### ISSUE TITLE
[Question] Possibly a bug. Why am I getting an extra blank window?

### ISSUE THREAD

**Issue by oscargforce** [microsoft/playwright#13714] opened 2022-04-23 14:56 UTC
https://user-images.githubusercontent.com/102926658/164911282-22113221-c434-4273-a6f7-4a56c39a1078.mp4

Somehow an extra blank browser is launched??
Please see the code and video.

```
test.only('Admin+Clinic @smoke', async ({browser})=>{ 
 const clinic = await browser.newPage()
  await clinic.goto('https://google.se')
  await clinic.pause()
})
```

**Comment by MindaugasMateika** [comment] 2022-04-23 15:36
Unless you have some other configuration not visible in the video, the playwright launches the browser and new page on its own. You don't need to launch a new page in your test. You can do `test('...', async ({ page }) => { page.goTo('...') /* and so on */ }`

**Comment by yury-s** [comment] 2022-04-23 18:33
Can you share full code of the reproducible example? Most likely your code opens a new page elsewhere, also as suggested above there is now need to call newPage manually, you can use [page](https://playwright.dev/docs/next/api/class-fixtures#fixtures-page) fixture.

**Comment by oscargforce** [comment] 2022-04-23 19:14
Hello!
Thank you for your replies.

I'm using the browser and not the page because I need to handle multiple windows.
The test is an online consultation wherein one page is the customer, and the other is the admin, hence why ({page}) is of no good.

Code:
![image](https://user-images.githubusercontent.com/102926658/164943115-be59be7f-cccc-4aa3-bc4c-23fb6510bbf4.png)


config file:
`import { devices, PlaywrightTestConfig } from "@playwright/test";

const config: PlaywrightTestConfig = {
   timeout:90000,
    retries: 0, 
    testDir:"testCases/partners",
    reporter:"html",
    workers: 3,
    use: {
        trace: 'retain-on-failure',
        headless: true,
        //...devices['Galaxy S9+'],
        //viewport: {width: 1280, height: 720},
        ignoreHTTPSErrors: true,
        actionTimeout: 10000,
        video:'retain-on-failure',
        screenshot:'only-on-failure',
        httpCredentials:{
            username:'platform24',
            password:'7592',
        },
    },
    expect: {
        timeout: 10000
      },/*
        projects: [ {
        name: 'chromium',
        use: {browserName:'chromium' }
    }, 
    {
        name: 'firefox',
        use: {browserName:'firefox' }
    }, 
    {
        name: 'webkit',
        use: {browserName:'webkit'  }
     
],}*/ 
}
export default config`

**Comment by oscargforce** [comment] 2022-04-23 19:26
And here was the issue..
![image](https://user-images.githubusercontent.com/102926658/164943423-be7831fa-372e-471b-8c3f-a9c543d50fd7.png)

**Comment by sergioariveros** [comment] 2022-04-25 04:43
So base on your last comments is a issue in your code @oscargforce ? Because we also saw that, but happens just some times and is quite difficult to reproduce, but we are seeing that as new tab in the same browser we are executing the test

**Comment by oscargforce** [comment] 2022-04-25 06:38
Hello!
Yes, so the issue was that in the beforeEach hook,
I had initialized the pageObjects with (page) 
which created a separate browser not belonging to the test.

**Comment by yury-s** [comment] 2022-04-25 16:18
Closing per the last comment.

**Closed by yury-s** 2022-04-25 16:18 UTC
Labels: triaging
