### ISSUE TITLE
[Feature] Allow "should fail" test to be marked as a failed test in the HTML reporter

### ISSUE THREAD

**Issue by zcsteele** [microsoft/playwright#17671] opened 2022-09-28 18:57 UTC
In the current implementation of the HTML reporter, any tests flagged as "should fail" (such as using `test.fail()` in the test code) are displayed in report as a passing result.

For my workflow, it would be helpful if these tests were marked as failing instead.

**Comment by aslushnikov** [comment] 2022-09-29 03:47
> In the current implementation of the HTML reporter, any tests flagged as "should fail" (such as using test.fail() in the test code) are displayed in report as a passing result.

This is by design.

> For my workflow, it would be helpful if these tests were marked as failing instead.

@zcsteele You can crash these tests just throwing some error on the first line!

**Comment by aslushnikov** [comment] 2022-09-30 16:05
Closing as per above. Please do no hesitate to file more issues with questions and suggestions! We appreciate that :)

**Closed by aslushnikov** 2022-09-30 16:05 UTC
Labels: triaging

**Comment by zcsteele** [comment] 2022-09-30 16:33
Thanks for clarifying the design!
