### ISSUE TITLE
[Feature] Simulation of mouse wheel user actions

### ISSUE THREAD

**Issue by canonic-epicure** [microsoft/playwright#8305] opened 2021-08-19 06:56 UTC
Hello,

I noticed that playwright does not have the simulation for mouse wheel user action. It is sometimes required, for example when you want to test the mouse wheel behavior in certain inputs (which are usually numeric and have increase/decrease buttons).

We are currently using Puppeteer, which provides this method: https://pptr.dev/#?product=Puppeteer&version=v9.1.1&show=api-mousewheeloptions

We are considering switching to Playwright, so would be great it will provide feature parity.

Thank you, Nickolay

**Comment by JoelEinbinder** [comment] 2021-08-19 16:36
Duplicate of #1115

**Closed by JoelEinbinder** 2021-08-19 16:36 UTC
