### ISSUE TITLE
[BUG] Error: route.fetch. Browser has been closed (headed) or Request context disposed (headless)

### ISSUE THREAD

**Issue by bondar-artem** [microsoft/playwright#24168] opened 2023-07-11 23:33 UTC
### System info
- Playwright Version: [v1.36]
- Operating System: [macOS 13.4.1]
- Browser: [Chromium, Firefox, WebKit]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],
});
```

**Test file (self-contained)**

```js
test('fetch returns error', async ({ page }) => {
    await page.route('https://conduit.productionready.io/api/tags', async route => {
      const response = await route.fetch()
      await route.fulfill({response})
    })
  
    await page.goto('https://angular.realworld.io/');
});
```

**Steps**
- [Run the test]

**Expected**

In this test, we intercept the "https://conduit.productionready.io/api/tags" that browsers redirect with 307 code to "
https://api.realworld.io/api/tags". route.fetch() should get the response from redirected API, save it into the "response" constant, and fulfill back to complete the call.

**Actual**

When executed in headed mode using VS Code extension, the test fails with the error "Error: route.fetch: Browser has been closed"
When executed in headless mode using, the test fails with the error: "Error: route.fetch: Request context disposed" 
Also execution log sometimes shows only the first GET request only, and sometimes the rest of the stack with 307 redirect and second GET call to redirect API Url
When executed in headed mode using CLI, sometimes error message is "Error: route.fetch: Protocol error (Storage.getCookies): Failed to find browser context for id"

As a result, I am unable to intercept the response of the redirected API URL to process the modified response.

![image](https://github.com/microsoft/playwright/assets/21285622/d7aaea30-0228-4360-8b1c-63288902c218)
![image](https://github.com/microsoft/playwright/assets/21285622/cdc425eb-cb36-49c0-a897-3dcd6015739a)

**Comment by mxschmitt** [comment] 2023-07-12 10:08
Sounds like a duplicate of https://github.com/microsoft/playwright/issues/23781

**Comment by mxschmitt** [comment] 2023-07-12 15:03
So what happens is that you are navigating (page.goto), the browser starts a network request and its coming into your page.route handler. But the test is already tearing down, so the context is disposing while your API request is being made. If you add a page.waitForTimeout(1000) after the page.goto it works as expected. (or an expect.toHaveText etc.).

So its a duplicate of #23781

**Closed by mxschmitt** 2023-07-12 15:03 UTC
Labels: triaging

**Comment by bondar-artem** [comment] 2023-07-12 15:15
Thank you for your quick response! I have checked your suggestion, and you are right it works, thank you! So I guess you can close this defect though.
