### ISSUE TITLE
Is it possible to test map products in a headless manner?

### ISSUE THREAD

**Issue by githublin8888** [microsoft/playwright#28870] opened 2024-01-04 20:01 UTC
Hi. I am applying playwright in an e commerce website that orders map products. After clicking on the product, a page opens with a map to select an area. The test passed if i 'show browser' but failed in headless mode. It also failed at trace viewer as the map has not been properly downloaded. Is it possible to solve this problem and what function or method do you suggest? Please have a check on the attatched pictures. I have tried wait for timeout and wait for load. It seems that it doesn't work. I'm using fixtures.

![Skärmbild (37)](https://github.com/microsoft/playwright/assets/117076811/44ae9c8d-d90f-4913-9bc8-739eafb5a9c2)
![Skärmbild (38)](https://github.com/microsoft/playwright/assets/117076811/934f2217-1e2e-46ce-8f94-31f12cc39c38)
![Skärmbild (40)](https://github.com/microsoft/playwright/assets/117076811/c574b0c8-f2f6-4470-87b4-ace1d4ba233b)
![Skärmbild (41)](https://github.com/microsoft/playwright/assets/117076811/6dc402af-e50a-44e8-b767-b02224333115)

**Comment by mxschmitt** [comment] 2024-01-04 21:08
Looks like a duplicate of https://github.com/microsoft/playwright/issues/23964.

**Closed** 2024-01-07 15:47 UTC
