### ISSUE TITLE
Re-Open Request - [Bug]: Playwright Should Never Fail Silently: It Should Always Report Why a Test Stopped #29426

### ISSUE THREAD

**Issue by jwalkerinterpres** [microsoft/playwright#29501] opened 2024-02-15 01:11 UTC
### Version

"@playwright/test": "^1.40.1", (originally 1.40.1 on main)

### Steps to reproduce

This is a general issue (not specific to any test/code).

### Expected behavior

When playwright exits, the user should always see some sort of explanation why. They should never see a screen like this one (or the one in my original ticket):
<img width="1505" alt="image" src="https://github.com/microsoft/playwright/assets/152227747/12ce4eb8-e8bb-47dd-a8f4-b908c0b9e617">

(Just as in the original ticket, all the other panels are blank also, except for the "Sources" tab, which simply shows the test itself, with the `test` line highlighted.)

### Actual behavior

You see a screen like that.  You have no idea why your test failed, and although Playwright must know at least _something_ about why it marked the test as failed ... it won't tell you.

### Additional context

Unfortunately switching to the test Playwright (as suggested in the original ticket) didn't help.

However, when I re-ran the test using the non-interactive test runner, it failed with several (I had retries) timeout failures.  I added `test.setTimeout(45 * 1000);` and ...  my test still failed with no error ... but I at least saw more normal failure output (although the stack list was stuck with a "spinner" graphic):

<img width="1494" alt="image" src="https://github.com/microsoft/playwright/assets/152227747/e4cd02f0-1db0-4880-a9d1-bb0124474953">

In my case at least, it seems like the core issue is with timeout errors not making it to the Errors panel (which is exacerbated by the stack list/detail panels above being blank intermittently).

But again, I really think _any_ instance of "test failed, but there's no explanation" should be considered a defect.  Like the interactive test runner should have this assertion when a test completes:

    if (testCompleted.withFailure && !errors.length) {
        throw new Error('Something really went wrong here: this shouldn't have happened.' +
                        'Please re-create a reproducible test case and submit it to the Playwright team!");
    }

It shouldn't just show an empty failure screen and pretend like everything is normal.

### Environment

```shell
System:
    OS: macOS 14.3
    Memory: 53.08 MB / 32.00 GB
  Binaries:
    Node: 21.2.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by mxschmitt** [comment] 2024-02-15 08:59
Closing for now since this issue is not following the issue template. Please re-refile and attach a minimal reproduction which we can run locally with expected / actual results. Clear reproduction steps are essential for us in order to triage bug reports like this. Thanks for your understanding.

[Canary](https://playwright.dev/docs/canary-releases) might already have a fix for it, we fixed a similar but recently.

**Closed by mxschmitt** 2024-02-15 08:59 UTC

**Comment by jwalkerinterpres** [comment] 2024-02-15 16:00
> Closing for now since this issue is not following the issue template. Please re-refile and attach a minimal reproduction which we can run locally with expected / actual results. Clear reproduction steps are essential for us in order to triage bug reports like this. Thanks for your understanding.

Again, the core issue has nothing to do with my specific case.  The core issue is that Playwright should never treat a failure without an explanation as a normal/expected case.  If Playwright can't explain why a test failed, I'm arguing it should treat that as an exceptional case.

By closing this ticket, you're essentially asserting that Playwright's interactive test runner _should_ treat failures without any explanation as normal/expected behavior.
 
> [Canary](https://playwright.dev/docs/canary-releases) might already have a fix for it, we fixed a similar but recently.
As I explained, I tried installing playwright's test version, (which I assume is the canary version?) and it didn't solve the issue.
