### ISSUE TITLE
[Feature]: Use remote folder for screenshot comparision 

### ISSUE THREAD

**Issue by bitttttten** [microsoft/playwright#31593] opened 2024-07-08 13:15 UTC
### 🚀 Feature Request

We have a lot of screenshots in our app, and we'd like to instead use a remote storage to store our screenshots.

In theory we could load the remote image as a buffer, take a screenshot into a buffer, and compare buffers although we miss a lot of the DX with the screenshot comparison tool.

### Motivation

The more images in our repo the slower it takes to clone and work on.

**Comment by mxschmitt** [comment] 2024-07-08 14:05
Duplicate of https://github.com/microsoft/playwright/issues/29227

**Closed by mxschmitt** 2024-07-08 14:05 UTC

**Comment by sudharsan-selvaraj** [comment] 2024-07-31 07:13
I was also looking for a similar solution and end up building one. refer to https://github.com/sudharsan-selvaraj/playshot

**What it covers:**

1. **Support for Multiple Cloud Storage Options**: Currently, the library supports uploading screenshots to Amazon S3 and SFTP servers. However, it can be easily adapted to work with other cloud storage providers.
2. **Automatic Screenshot Upload**: Screenshots are automatically uploaded to the remote server if there are test failures, eliminating the need to save them to version control.
3. **Screenshot Updates**: Users have the ability to individually update screenshots when there are changes in the UI.
4. **Flexible Validation**: The library provides methods for validating visual regressions for both entire pages and individual web elements.
5. **Support for Soft Assertions**: Built-in support for soft assertions is included, allowing the test suite to continue running even if a soft assertion fails, without interrupting the execution of subsequent test steps.
