### ISSUE TITLE
[Feature] Setting ffmpeg path

### ISSUE THREAD

**Issue by cor1** [microsoft/playwright#6491] opened 2021-05-10 20:33 UTC
Hello! Really loving playwright so far, I have run into an issue with ffmpeg, playwright, and aws lambda. I am wanting to use playwright on a lambda function that has ffmpeg in a layer. Is there a way to change the ffmpeg path playwright uses to use the ffmpeg that is brought in from the lambda layer so I can get past the "Please install ffmpeg in order to record video" error?

**Comment by cor1** [comment] 2021-05-14 16:34
just updating for anyone else having the same problem, I couldnt get it to work as I wanted on aws lambda so I moved the code over to gcp cloud run (i prefer that anyways) and used the playwright image and it works great now.

**Comment by kisscelia** [comment] 2021-11-30 06:29
Need to set the ffmpeg path too. if this, there is no necessary to care about the environments. 
thanks.

**Comment by Myrannas** [comment] 2022-03-29 22:54
I have playwright running in an environment where I can't download additional binaries, but ffmpeg is already available on the machine.

I've managed to (hackily) get this to work in my environment by modifying the executables in the Registry class; but it'd be great if this was a first class feature.

**Comment by pavelfeldman** [comment] 2022-10-20 06:18
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-10-20 06:18 UTC
Labels: P3-collecting-feedback, feature-video

**Comment by ckolumbus** [comment] 2023-06-12 14:24
I do have the same issue but it's motivated by regulatory requirements. I need to archive used packages and be able to reproduce a build only based on archived binaries. This would include our playwright based tests with chromium and ffmpeg. It would be necessary for us to provide a location where the initial install of these tools happen and where we can configure the build later on to re-use the tools that are installed/copied there so that we avoid additional downloads.

**Comment by chronotc** [comment] 2024-08-09 18:33
As op has mentioned, they couldn’t get this working on AWS Lambda and had to move to GCP.
The symlink solution isn’t ideal in certain environments. 

Is there resistance to allow Playwright to read from `process.env.FFMPEG_PATH` (similar to fluent-ffmpeg) in the registry file and fallback to Playwright’s default ffmpegExecutablePath when the environment variable doesn’t exist?

**Comment by kylegwalsh** [comment] 2024-08-15 02:53
I agree with @chronotc. There is no straight forward way to install ffmpeg on AWS Lambda and an environment variable for `FFMPEG_PATH` would be a good work around.

This is similar to the approach from the deprecated [playwright-video](https://github.com/qawolf/playwright-video/blob/master/README.md) library.

I'm able to upload ffmpeg to a lambda layer, but it ends up being stored in the `/proc/1/cwd` directory. Playwright can't seem to locate this since it's looking in the cache directory (which doesn't exist).

**Comment by juanzolotoochin** [comment] 2024-12-27 21:53
Can this be reopened? it seems like it would be straightforward to support passing an `FFMPEG_PATH` env variable.

**Comment by arquadrado** [comment] 2025-01-06 10:36
Please, reopen this and provide the requested feature.

**Comment by mwood23** [comment] 2025-02-02 19:09
There's a PR that was closed adding support for this: https://github.com/microsoft/playwright/pull/32102/files. You can patch your installed version to add support for this. Here's the patchfile using Bun:

```patch
diff --git a/node_modules/playwright-core/.bun-tag-d7c65d00dd85c2c2 b/.bun-tag-d7c65d00dd85c2c2
new file mode 100644
index 0000000000000000000000000000000000000000..e69de29bb2d1d6434b8b29ae775ad8c2e48c5391
diff --git a/lib/server/chromium/crPage.js b/lib/server/chromium/crPage.js
index aef12f34295ec18858b84b2099d5d7d08d27e622..ccc745b6813ac21abf5dafb40a888f1ad8a43a86 100644
--- a/lib/server/chromium/crPage.js
+++ b/lib/server/chromium/crPage.js
@@ -777,7 +777,7 @@ class FrameSession {
   }
   async _createVideoRecorder(screencastId, options) {
     (0, _utils.assert)(!this._screencastId);
-    const ffmpegPath = _registry.registry.findExecutable('ffmpeg').executablePathOrDie(this._page.attribution.playwright.options.sdkLanguage);
+    const ffmpegPath = process.env.PLAYWRIGHT_FFMPEG_PATH || _registry.registry.findExecutable('ffmpeg').executablePathOrDie(this._page.attribution.playwright.options.sdkLanguage);
     this._videoRecorder = await _videoRecorder.VideoRecorder.launch(this._crPage._page, ffmpegPath, options);
     this._screencastId = screencastId;
   }
```
