### ISSUE TITLE
[BUG] Images of the timeline view in the trace are not correctly centred and overly zoomed in

### ISSUE THREAD

**Issue by nbaldzhiev** [microsoft/playwright#27526] opened 2023-10-10 13:59 UTC
### System info
- Playwright Version: [v1.37.1, 1.38.0]
- Operating System: [tests run on ubuntu-20.04 runners, traces are viewed on macos 13.4.1, but I think it happens on any OS when viewing them]
- Browser: [WebKit]
- Other info: also happens in v.1.38. Same as https://github.com/microsoft/playwright/issues/23839

### Source code

Unfortunately I can't share even a partial repository as it contains sensitive company-related information. I think it should happen with any test.

**Config file**

```js
// playwright.config.ts, webkit config
    {
      name: 'webkit',
      use: {
        ...devices['Desktop Safari']
      },
      expect: {
        timeout: 2 * 15 * 1000
      }
    }
```

**Steps**
- Open a failed WebKit test in the trace viewer.

**Expected**

Timeline images are properly centred and zoom, same as the rest of the browsers

**Actual**

Timeline images are not properly centred and are very zoomed in.

![Screenshot 2023-10-10 at 16 58 28](https://github.com/microsoft/playwright/assets/19264892/deb9e915-877a-426c-ac58-39b756dd2b3e)

**Comment by dgozman** [comment] 2023-10-12 18:11
@nbaldzhiev What is your operating system where the browser runs?

**Comment by nbaldzhiev** [comment] 2023-10-12 18:53
> @nbaldzhiev What is your operating system where the browser runs?

I open the reports on macOS Ventura 13.4.1 (22F82) and the tests run in `ubuntu-20.04-4cpus` github runners. As additional information, we merge the html reports using the `playwright-merge-html-reports` package (`^0.2.8`), not using the recently released Playwright merge tool.

By the way, I just noticed that when I ran a failing test locally (on the macos) in webkit, the trace timeline images and the snapshot were actually okay 🤔 So I guess the platform where the tests run and where the traces get created is what makes the difference (as mentioned above, in CI we run in `ubuntu-20.04-4cpus` github runners).

**Comment by dgozman** [comment] 2023-10-12 19:24
@nbaldzhiev Thank you for the info. We test on this configuration and it works fine. I guess we'll need a repro for this issue. If you think it happens on any test, perhaps running on one of our example tests (e.g. what `npm init playwright` creates) would reproduce it for you? Please help us with making a repro, otherwise it's unlikely we'll be able to fix this.

**Comment by nbaldzhiev** [comment] 2023-10-13 13:38
@dgozman Okay, I'll try creating a reproducible example that I can share with you. One additional remark that I remembered I didn't do earlier is that we run Firefox and Webkit headed using `xvfb-run` and our command is as follows (omitting actual option values)

```
xvfb-run npx playwright test --project=project --shard=shard --headed
```

Any chance that it could be related to `xvfb-run`?

**Comment by mxschmitt** [comment] 2023-10-18 13:22
Most likely its not related to xvfb. The image on the right side looks like a map, is this a canvas element which does not get shown inside trace viewer?

**Comment by nbaldzhiev** [comment] 2023-10-18 14:32
Yes, there's a `canvas` element with a map, which uses `deckgl`. But I believe the trace always looks like this, even if the test doesn't open a page with the map canvas.
I'll work on trying to get a reproducible example, but it's all company code running via GitHub Actions workflows, so I need to allocate some time to work on creating an isolated, executable example.

**Comment by mxschmitt** [comment] 2023-10-18 17:59
Sounds like a duplicate of https://github.com/microsoft/playwright/issues/23964 then.

**Comment by nbaldzhiev** [comment] 2023-10-19 06:28
I don't think so, the issue you mentioned is a separate problem. The bug here is that the preview images in Webkit of the timeline view are not centred and are overly zoomed in. As such, hovering over the timeline view makes it difficult to debug in Webkit.

Here's another example of a page where there's no map:

![Screenshot 2023-10-19 at 9 28 17](https://github.com/microsoft/playwright/assets/19264892/b07b35e0-c6c3-4629-aa15-c61f2006887a)

**Comment by mxschmitt** [comment] 2023-10-19 10:01
You are right, sounds like a different bug. We need a repro then for that. In the meantime I recommend trying our latest release 1.39.0.

**Comment by nbaldzhiev** [comment] 2023-10-19 10:08
I was at `1.38.1` but I reverted because of https://github.com/microsoft/playwright/issues/27112, which seems to be expected behaviour now. I am assuming it would be part of `1.39.0` as well, which would stop me from upgrading.

**Comment by mxschmitt** [comment] 2023-10-19 10:59
Yes we unlikely will revert https://github.com/microsoft/playwright/issues/27112. So we need a repro, so we can look into it.

**Comment by yury-s** [comment] 2023-10-25 00:55
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Closed by yury-s** 2023-10-25 00:55 UTC
Labels: triaging
