### ISSUE TITLE
[Bug]:  Truncated download suggested name on webkit

### ISSUE THREAD

**Issue by Daemos87** [microsoft/playwright#7773] opened 2021-07-21 16:16 UTC
### Playwright version

1.12.0

### Operating system

MacOS

### What browsers are you seeing the problem on?

WebKit

### Other information

node version : v14.16.1

### What happened? / Describe the bug

Cannot share the real code or the website i'm working on, but it is something like this 

```typescript

   private async downloadLinks(links: string[]) {
        const fileNames: string[] = []
        for (const link of links) {
            await Promise.all([this.page.click(link), this.page.waitForEvent('download', { timeout: 60000 })
                .then(file => fileNames.push(file.suggestedFilename())])
                }
        }
        console.log(fileNames)
        return fileNames
    }
```

I get this on chromium or firefox 

`[
  'Allegato 3-4 -4-ter Reg 40_2018.pdf',
  'Set Informativo Amtrust.pdf',
  'Dichiarazione di coerenza.pdf',
  "Informativa sulla privacy ai sensi dell'articolo 13 del Regolamento UE 679-2016.pdf"
]`

and this on webkit 

`[
  '2018.pdf',
  'Set Informativo Amtrust.pdf',
  'Dichiarazione di coerenza.pdf',
  "Informativa sulla privacy ai sensi dell'articolo 13 del Regolamento UE 679-2016.pdf"
]`

So the first filename result truncated consistently only on webkit.  Can this be an issue in the playwright codebase ?

**Comment by pavelfeldman** [comment] 2021-07-21 18:43
I can't reproduce this without the actual page.

**Comment by dgozman** [comment] 2021-07-27 04:17
Closing this one since we cannot reproduce. If you have repro steps, please comment here and we'll reopen.

**Closed by dgozman** 2021-07-27 04:17 UTC
Labels: triaging
