### ISSUE TITLE
[BUG] playwright install does not respect playwright version in package.json

### ISSUE THREAD

**Issue by thmsobrmlr** [microsoft/playwright#19562] opened 2022-12-19 13:10 UTC
**Context:**
- Playwright Version: 1.28.1
- Operating System: Linux
- Node.js version: 18
- Browser: Chromium
- Extra: GitHub Actions

Running `pnpm dlx playwright install --with-deps` fails on GitHub actions with following message:
```
╔════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Playwright Test integrity check failed:                                                                ║
║ You have @playwright/test version '1.28.1' and 'playwright' version '1.29.0' installed!                ║
║ You probably added 'playwright' into your package.json by accident, remove it and re-run 'npm install' ║
╚════════════════════════════════════════════════════════════════════════════════════════════════════════╝
```
We don't have `playwright` in the package json, only `@playwright/test": "^1.28.1"`. We're using pnpm for package management. Playwright is run in a generic ubuntu docker container. I'd expect the install command to respect the version from package.json.

Our repo is public, see here for the issue https://github.com/PostHog/posthog/actions/runs/3730056567/jobs/6327087498. See also [here for brief discussion](https://playwright.slack.com/archives/CSUHZPVLM/p1671446299698409) on Slack.

**Comment by pavelfeldman** [comment] 2022-12-19 16:21
To make sure I understand what is happening:

- You have `"@playwright/test": 1.28.1` in your `package.json`
- You run `pnpm dlx playwright install --with-deps` in your build recipe
- You are seeing a conflicting versions message

The message is not entirely accurate, in your case it should be
`You have @playwright/test version '1.28.1' and @playwright/test version '1.29.0' installed!`

It seems like pnpm installs `@playwright/test@1.29` into `/home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/` and uses it from there upon your dlx call. I looked at the docs at https://pnpm.io/cli/dlx and unlike `npx`, there is nothing saying that `pnpm dlx` will respect your package.json. So I guess things are working as intended.

**Comment by thmsobrmlr** [comment] 2022-12-19 16:36
Yup, that's what's happening (the bullet points). I'm a bit confused with the error message now - where is `@playwright/test@1.29.0` installed on CI? It's not a dependency of `playwright`.

**Comment by pavelfeldman** [comment] 2022-12-21 21:00
As I said, ignore that it is saying 'playwright', it means '@playwright/test'. My understanding is that you installed extra copy when you ran `pnpm dlx`.

**Comment by brandensilva** [comment] 2022-12-22 00:31
Also hitting this issue and its driving me a bit crazy. 

I wanted to chime in here because there is some confusion as to the problem.

Per PNPM's second line on their install docs:

`In a CI environment, installation fails if a lockfile is present but needs an update.`

And further down the page:

`-frozen-lockfile
Default:
For non-CI: false
For CI: true, if a lockfile is present
Type: Boolean
If true, pnpm doesn't generate a lockfile and fails to install if the lockfile is out of sync with the manifest / an update is needed or no lockfile is present.`

So what I suspect is happening is the integrity issue props up because playwright/test gets an update, but our pnpm-lock files are a version behind because `pnpm i` installs with `--frozen-lock` in a CI environment.

**Comment by mw10013** [comment] 2022-12-22 02:11
I hit this issue too with "@playwright/test": "^1.29.0" as a dev dependency in package.json. Able to get around this by removing dlx from the github action steps for ci. Without dlx, seems pnpm uses the playwright installed based on package.json.

- name: Install playwright browsers
        run: pnpm playwright install --with-deps
 - name: Run playwright tests
        run: pnpm playwright test

https://github.com/scarab2022-personal/access-remix/blob/1ee38545b3c57251bc95a687bd687e71e919c34c/.github/workflows/ci.yml

**Comment by thmsobrmlr** [comment] 2022-12-22 08:30
I now also think this is an issue due to differences with pnpm and npm. More concretely pnpm dlx / pnpx does not respect the version specified in package.json, but npx does. Short test with jest locked to 28.1.3 in package.json:

    npx jest --version # 28.1.3, but 29.3.1 if node_modules aren't installed
    pnpm dlx jest --version # 29.3.1
    pnpx jest --version # 29.3.1
    pnpm exec jest --version # 28.1.3
  
We solved this in a workaround by locking the pnpm dlx step as following: 

- name: Install Playwright Browsers
  run: pnpm dlx playwright@1.28.1 install --with-deps

But since we are installing dependencies beforehand, I'm assuming

- name: Install Playwright Browsers
  run: pnpm exec playwright install --with-deps

would work as well.

Does that work for you @brandensilva @mw10013 as well?

**Comment by brandensilva** [comment] 2022-12-22 15:35
@thmsobrmlr I think you are right it is has to do with the pnpm dlx / pnpx functions differently than npx. 

I tested both @mw10013's solution and yours without exec and with. Both seem to work, interchangeably too.

So you can either drop dlx all together, or use exec over dlx to get past this playwright integrity mismatch issue.

**Comment by caleb531** [comment] 2022-12-22 19:28
_Just_ ran into this exact issue when running `pnpx playwright install` from CI (GitHub Actions):

> ║ Playwright Test integrity check failed:                                                                ║
> ║ You have @playwright/test version '1.29.0' and 'playwright' version '1.29.1' installed!

Fortunately, I can confirm that changing `pnpx playwright install` to `pnpm exec playwright install` (in my GitHub action YAML) fixes the issue completely.

**Comment by pavelfeldman** [comment] 2022-12-22 22:29
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Closed by pavelfeldman** 2022-12-22 22:29 UTC
Labels: triaging

**Comment by SalahAdDin** [comment] 2023-08-12 20:46
> pnpm exec playwright install

It didn't work for me:
``ỳaml
name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Enable pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: pnpm dlx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
 ```
 
 Result [here](https://github.com/SalahAdDin/react-ts-vite-template/actions/runs/5843347195/job/15845405750#step:7:15).
