### ISSUE TITLE
[Bug]: Internal API Requests Timeout on Webkit

### ISSUE THREAD

**Issue by Addison-Dalton** [microsoft/playwright#33518] opened 2024-11-08 18:54 UTC
### Version

1.48.0+

### Steps to reproduce

Here's the simple react app I setup to test this with: https://github.com/Addison-Dalton/playwright-webkit-bug-example.
Just note that I can't share the actual API endpoint itself.

1. Setup a fetch request to our API.
2. Render some of the returned data on screen.
3. Wrote a playwright test to assert the data is visible. 

### Expected behavior

When running the playwright tests on webkit I expect:

- The request to be made, and respond successfully.
- The test to pass (rendered data is visible)

### Actual behavior

The test ultimately times out. It gets stuck waiting for the API request to return, which also times out after a minute.

### Additional context

- This was not an issue on versions prior to 1.48.0.
- This is not an issue with chrome or firefox.
- If I setup the internal API locally, and use it, then webkit works as expected.
- This is not an issue on an actual Safari browser.

### Environment

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 14.68 GB / 31.71 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.95.0 - C:\Users\addison.dalton\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.12 - C:\Program Files\Git\usr\bin\bash.EXE
  npmPackages:
    @playwright/test: 1.48.2 => 1.48.2
```

**Comment by yury-s** [comment] 2024-11-09 00:12
I'm afraid we cannot take any meaningful action on this report without a reproduction. Can you try to extract relevant parts of the test into a standalone project, that we could run and reproduce the issue?

**Comment by JanLechvar** [comment] 2024-11-11 15:03
any chance it might be connected to these closed issues?
I'm too still having timeout issues in webkit since 1.48 on our internal applications (no issues on public ones)

https://github.com/microsoft/playwright/issues/33088
https://github.com/microsoft/playwright/issues/33055

**Comment by Addison-Dalton** [comment] 2024-11-11 15:12
> any chance it might be connected to these closed issues? I'm too still having timeout issues in webkit since 1.48 on our internal applications (no issues on public ones)
> 
> [#33088](https://github.com/microsoft/playwright/issues/33088) [#33055](https://github.com/microsoft/playwright/issues/33055)

#33088 certainly appears to be similar to what I'm encountering. Sorry you're also facing this, but glad I'm not the only one.

**Comment by pavelfeldman** [comment] 2024-11-11 19:20
We can only act on an issue like this if we can reproduce it.

**Comment by salemvi** [comment] 2024-11-13 13:56
I ran into this problem and tried to deal with it for quite a long time, at the moment I have not found a solution, it looks like a bug, the webkit does not work with the network

**Comment by Addison-Dalton** [comment] 2024-11-13 14:03
I just tried the beta build of 1.49.0, which upgrades to Webkit 18.2, and this is no longer an issue.

**Comment by Addison-Dalton** [comment] 2024-11-13 14:38
I tried `1.49.0-beta-1731497689000`. It's possible we're encountering different issues, but thankfully this solved it for me.

**Comment by salemvi** [comment] 2024-11-13 19:52
but how you install this version?
![Image](https://github.com/user-attachments/assets/03f87232-52df-474d-9263-71473ea157bf)

**Comment by Addison-Dalton** [comment] 2024-11-13 21:28
I updated the dependency version for playwright within our `package.json`, and then reinstall my dependencies.
```json
{
  "devDependencies": {
    "@playwright/test": "1.49.0-beta-1731497689000"
  }
}
```

**Comment by pavelfeldman** [comment] 2024-11-13 23:15
@salemvi I'll close this as the OR has the issue resolved, please file a separate bug for your issue.

**Closed by pavelfeldman** 2024-11-13 23:15 UTC
