### ISSUE TITLE
[Question] Split report by feature or tag ?

### ISSUE THREAD

**Issue by kamelbou** [microsoft/playwright#19524] opened 2022-12-16 17:25 UTC
[Question] 
Hi all, is there a way to split the report by feature or tag into smallest report? We have a lot of tests and a timeout is reached at the report generation.

Thank you.

**Comment by yury-s** [comment] 2022-12-19 17:32
There is no way to split the report except for running `npx playwright test` multiple times with different filters. Large number of tests should not be a problem for report generation, this is unexpected.

> We have a lot of tests and a timeout is reached at the report generation.

Can you elaborate on this, how many tests do you have? Do you use a custom reporter or builtin html reporter? 

It'd be great if you could share with us the project where it happens so that we could reproduce it locally.

**Comment by kamelbou** [comment] 2022-12-21 08:57
> There is no way to split the report except for running `npx playwright test` multiple times with different filters. Large number of tests should not be a problem for report generation, this is unexpected.
> **We have more than 500 tests and more than 100 are failing. 
We set `trace: 'retain-on-failure'` in our playwright config file. 
To allow HTML report generation, we added `node --max-old-space-size=8192` and we can see now that the report size is around 700Mo. It is a little bit too much, no ? :)**
> Can you elaborate on this, how many tests do you have? Do you use a custom reporter or builtin html reporter?
> **builtin html reporter**
> It'd be great if you could share with us the project where it happens so that we could reproduce it locally.
**Unfortunately, the project cannot be shared but I can share the logs ?**

**Comment by pavelfeldman** [comment] 2022-12-21 21:09
> We have more than 500 tests and more than 100 are failing.

I'd recommend that you run your tests locally until they start passing, after that you can enable the tracing feature and run them on CI. Tracing is only recommended for the post-mortem analysis, so you only enable it on CI/CD. And I assume you don't run 100 failing tests on CI/CD, if that is the case, disable tracing, fix the tests and re-enable it!

**Comment by kamelbou** [comment] 2022-12-23 18:29
> > We have more than 500 tests and more than 100 are failing.
> 
> I'd recommend that you run your tests locally until they start passing, after that you can enable the tracing feature and run them on CI. Tracing is only recommended for the post-mortem analysis, so you only enable it on CI/CD. And I assume you don't run 100 failing tests on CI/CD, if that is the case, disable tracing, fix the tests and re-enable it!

Thank you @pavelfeldman for your answer. Maybe my first post was not enough clear, I'm sorry.
We are enabling the tracing in CI/CD only in failure cases to be able to reproduce the bug but in our case, we had more than 100 fails because of some breaking change and to analyse them I was hoping to rely on the trace of the report but, because we reach a timeout during HTML generation in the CI, it's not possible. (except by adding `node --max-old-space-size=8192`). 
What we can do is disable tracing in the CI/CD in case of large number of fail tests and then re-run them locally with the trace enable to be able to analyse the failure ? I'm not comfortable with this approach. What do you think ?

**Comment by pavelfeldman** [comment] 2022-12-27 16:42
Could you share a report where one test is failing? It should not require you to set old space, etc - report generation should scale, be lightweight and fast. As a workaround, you can specify `maxFailures: 50` in your config - setting max failures to 10% is a good practice - it saves a ton of time on CI when someone lands a change that breaks the world.

**Comment by kamelbou** [comment] 2022-12-28 18:24
Thanks for your answer @pavelfeldman.
It will be difficult to share a report as we handle sensitive data. Will try to find how I can share you something. Meanwhile,  I will use your workaround.

Thank you.

**Comment by aslushnikov** [comment] 2022-12-31 08:22
Closing since there's no immediate action from Playwright team regarding this!

**Closed by aslushnikov** 2022-12-31 08:22 UTC
Labels: triaging
