### ISSUE TITLE
[BUG] Two chromium browser instances and Two Tabs in firefox getting launched Instead of One

### ISSUE THREAD

**Issue by MaxTester1** [microsoft/playwright#1309] opened 2020-03-10 15:12 UTC
**Context:**
- Playwright Version: [what Playwright version do you use?] "playwright": "^0.11.1"
- Operating System: [e.g. Windows, Linux or Mac] Windows 10
- Extra: [any specific details about your environment] 

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const playwright = require('playwright');

(async () => {
  for (const browserType of ['chromium', 'firefox']) {
    const browser = await playwright[browserType].launch({ headless: false });
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('http://google.com/');
    await page.screenshot({ path: `example-${browserType}.png` });
    await browser.close();
  }
})();
```

**Describe the bug**
Trying to Automate Web using Playwright, expected to get one browser launched and test executed
Add any other details about the problem here.

**Comment by aslushnikov** [comment] 2020-03-10 18:14
This is a dupe of #981 and is actually fixed on tip-of-tree and will be part of the next release (later this week). Meanwhile, you can try it installing `playwright@next`.

**Closed by aslushnikov** 2020-03-10 18:14 UTC

**Comment by MaxTester1** [comment] 2020-03-13 11:07
Thanks for confirming the issue, i tried the new version how to **skip launching chrome in Incognito mode** wanted to launch normal mode
