### ISSUE TITLE
Unable to set Microphones option using browsercontext

### ISSUE THREAD

**Issue by Bhagya767** [microsoft/playwright#3958] opened 2020-09-23 06:02 UTC
We have added microphone permission but still unable to setup a call.

Below is the code.

browserContext.grantPermissions(permissions[][, options]) 
adminContext = await browser.newContext({
      viewport: TestSettings.Viewport, permissions: ['microphone']
    });
    ChatContext = await browser.newContext({
      permissions: ['microphone']
 });

**Comment by mxschmitt** [comment] 2020-09-23 18:19
I was able to reproduce it with https://webcammictest.com/check-mic.html and also the `*` when passing does not work.

**Comment by dgozman** [comment] 2020-10-01 05:19
The following script works for me with playwright v1.4. It opens the page and I can click the "CHECK MICROPHONE" button and microphone works. Chromium does not ask for permission.

```js
const {chromium} = require('playwright');
(async () => {
  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext({
    permissions: ['microphone']
  });
  const page = await context.newPage();

  await page.goto('https://webcammictest.com/check-mic.html');
  await page.waitForTimeout(1000000);

  await browser.close();
})();
```

A few notes:
- When running this on Mac, I got the "Terminal wants to access the microphone" prompt from MacOS. This requires investigation - maybe we can grant access programmatically, but I am not sure.
- Firefox and WebKit do not support "microphone" permission and we throw an error `Unknown permission: microphone`. Do you use Chromium in your scripts?

How do you check whether microphone permission worked? Mind sharing a script?

**Comment by pavelfeldman** [comment] 2020-10-20 04:52
Closing as a part of triage. Please feel free to reopen with the additional details if this is still a problem!

**Closed by pavelfeldman** 2020-10-20 04:52 UTC
