### ISSUE TITLE
[BUG]  Device emulation not working with CLI

### ISSUE THREAD

**Issue by transplatin** [microsoft/playwright#6431] opened 2021-05-06 03:50 UTC
Device emulation not working with CLI

**Context:**
- Playwright Version: 1.10.0
- Operating System: Windows 10
- Node.js version:v14.16.1
- Browser: Playwright Default

## System:
 - OS: Windows 10 10.0.19042
 - Memory: 1.74 GB / 5.88 GB
## Binaries:
 - Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
 - npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - playwright: ^1.10.0 => 1.10.0

**Code Snippet**

I tried to emulate iPhone 11 using CLI but it is not working.

```# Emulate iPhone 11.
npx playwright open --device="iPhone 11" wikipedia.org
```

**Error**
'''
Device descriptor not found: 'iPhone', available devices are:
  "Blackberry PlayBook"
  "Blackberry PlayBook landscape"
  "BlackBerry Z30"
  "BlackBerry Z30 landscape"
  "Galaxy Note 3"
  "Galaxy Note 3 landscape"
  "Galaxy Note II"
  "Galaxy Note II landscape"
  "Galaxy S III" 
   and so on...

**Possible Issue**

It seems like it is only accepting the first word of every specified device rather than accepting it as **"iPhone 11"**, it is accepting it as **"iPhone"**.

**Comment by mxschmitt** [comment] 2021-05-06 08:57
I tried to reproduce it with Windows with Powershell and cmd.exe and it worked for me as expected in both cases. (I had Node.js 16 but this should not make a big difference there.)

Are you using some special terminal e.g.?

**Comment by transplatin** [comment] 2021-05-06 22:48
I am using the command prompt.

**Comment by aslushnikov** [comment] 2021-05-07 03:05
I can repro on one of our windows machines; looking into it!

**Comment by aslushnikov** [comment] 2021-05-07 03:18
So turns out this is an NPX issue on Windows:
- https://github.com/npm/npx/issues/43
- https://github.com/npm/cli/issues/502

This, however, is fixed in NPM v7, so that's why @mxschmitt wasn't able to reproduce.

@transplatin: the official "workaround" for this would be to [install NPM v7](https://github.com/npm/cli/issues/502#issuecomment-767371011):

```shell
$ npm i -g npm@v7
```

Worked for me! So closing this.

**Closed by aslushnikov** 2021-05-07 03:18 UTC
Labels: P2-bug

**Comment by transplatin** [comment] 2021-05-07 03:46
Yes, updating to npm@7 solves the issue. :)
