### ISSUE TITLE
[Bug]: Headful fails with Chrome 91+

### ISSUE THREAD

**Issue by joecanuelspotify** [microsoft/playwright#7502] opened 2021-07-07 16:18 UTC
### Playwright version

1.12.3

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### Other information

This is specific to Chrome, it doesn't happen with Chromium.

We first started noticing this issue when using Puppeteer and Chrome 90. We tried it with Playwright on Chrome  91.0.4472.114 and are seeing it fail here as well.

### What happened? / Describe the bug

When running Chrome headfully (i.e. `headless: false`), the browser crashes.

### Code snippet to reproduce your bug

```shell
import { chromium } from 'playwright';

async function main() {
  const browser = await chromium.launch({
    headless: false,
    executablePath:
      // Chrome 91.0.4472.114 at time of creating this example
      '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  });

  try {
    const page = await browser.newPage();
    await page.goto('https://www.google.com');
    await page.waitForTimeout(20000);
    // Browser auto-closes after a few seconds
    // and crashes on the next command
    await page.goto('https://www.google.com');
    await browser.close();
  } catch (e) {
    console.error(e);
    await browser.close();
  }
}

main();
```

### Relevant log output

```shell
page.goto: Navigation failed because page was closed!
=========================== logs ===========================
navigating to "https://www.google.com", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error:
    at Object.captureStackTrace (/Users/joecanuel/src/creator/mrkt-web/node_modules/playwright/lib/utils/stackTrace.js:51:19)
    at Connection.sendMessageToServer (/Users/joecanuel/src/creator/mrkt-web/node_modules/playwright/lib/client/connection.js:73:48)
    at Proxy.<anonymous> (/Users/joecanuel/src/creator/mrkt-web/node_modules/playwright/lib/client/channelOwner.js:64:61)
    at /Users/joecanuel/src/creator/mrkt-web/node_modules/playwright/lib/client/frame.js:100:65
    at Frame._wrapApiCall (/Users/joecanuel/src/creator/mrkt-web/node_modules/playwright/lib/client/channelOwner.js:77:34)
    at Frame.goto (/Users/joecanuel/src/creator/mrkt-web/node_modules/playwright/lib/client/frame.js:98:21)
    at /Users/joecanuel/src/creator/mrkt-web/node_modules/playwright/lib/client/page.js:267:60
    at Page._attributeToPage (/Users/joecanuel/src/creator/mrkt-web/node_modules/playwright/lib/client/page.js:202:20)
    at Page.goto (/Users/joecanuel/src/creator/mrkt-web/node_modules/playwright/lib/client/page.js:267:21)
    at main (/Users/joecanuel/src/creator/mrkt-web/apps/mrkt-web-synthetic-tests/test-chromium-headful-playwright.ts:17:16)
✨  Done in 53.04s.
```

**Comment by mxschmitt** [comment] 2021-07-07 17:13
Could you provide us the output while setting the `DEBUG=pw:browser,pw:api` environment variable?

**Comment by joecanuelspotify** [comment] 2021-07-07 17:40
@mxschmitt Sure thing.

```
yarn ts-run apps/mrkt-web-synthetic-tests/test-chromium-headful-playwright.ts
yarn run v1.16.0
$ /Users/joecanuel/src/creator/mrkt-web/node_modules/.bin/ts-run apps/mrkt-web-synthetic-tests/test-chromium-headful-playwright.ts
  pw:api => browserType.launch started +0ms
  pw:browser <launching> /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading,GlobalMediaControls --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=/var/folders/w1/wrsqcf_x3ssg42vnncdkrfnc0000gn/T/playwright_chromiumdev_profile-C32CAJ --remote-debugging-pipe --no-sandbox --disable-dev-shm-usage --no-startup-window +0ms
  pw:browser <launched> pid=15482 +11ms
  pw:api <= browserType.launch succeeded +1s
  pw:api => browser.newContext started +1ms
  pw:api <= browser.newContext succeeded +11ms
  pw:api => browserContext.newPage started +1ms
  pw:api <= browserContext.newPage succeeded +623ms
  pw:api => page.goto started +0ms
  pw:api navigating to "https://www.google.com", waiting until "load" +3ms
  pw:api   navigated to "https://www.google.com/" +271ms
  pw:api   navigated to "https://www.google.com/" +112ms
  pw:api   "domcontentloaded" event fired +0ms
  pw:api   "load" event fired +281ms
  pw:api <= page.goto succeeded +1ms
  pw:api => page.waitForTimeout started +0ms
  pw:api   "networkidle" event fired +661ms
  pw:api <= page.waitForTimeout succeeded +19s
  pw:api => page.goto started +0ms
  pw:api navigating to "https://www.google.com", waiting until "load" +1ms
  pw:api <= page.goto failed +1ms
page.goto: Navigation failed because page was closed!
=========================== logs ===========================
navigating to "https://www.google.com", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error:
    at Object.captureStackTrace (/Users/joecanuel/src/creator/mrkt-web/node_modules/playwright/lib/utils/stackTrace.js:51:19)
    at Connection.sendMessageToServer (/Users/joecanuel/src/creator/mrkt-web/node_modules/playwright/lib/client/connection.js:73:48)
    at Proxy.<anonymous> (/Users/joecanuel/src/creator/mrkt-web/node_modules/playwright/lib/client/channelOwner.js:64:61)
    at /Users/joecanuel/src/creator/mrkt-web/node_modules/playwright/lib/client/frame.js:100:65
    at Frame._wrapApiCall (/Users/joecanuel/src/creator/mrkt-web/node_modules/playwright/lib/client/channelOwner.js:77:34)
    at Frame.goto (/Users/joecanuel/src/creator/mrkt-web/node_modules/playwright/lib/client/frame.js:98:21)
    at /Users/joecanuel/src/creator/mrkt-web/node_modules/playwright/lib/client/page.js:267:60
    at Page._attributeToPage (/Users/joecanuel/src/creator/mrkt-web/node_modules/playwright/lib/client/page.js:202:20)
    at Page.goto (/Users/joecanuel/src/creator/mrkt-web/node_modules/playwright/lib/client/page.js:267:21)
    at main (/Users/joecanuel/src/creator/mrkt-web/apps/mrkt-web-synthetic-tests/test-chromium-headful-playwright.ts:18:16)
  pw:api => browser.close started +2ms
  pw:browser [pid=15482] <gracefully close start> +22s
  pw:browser [pid=15482] <kill> +30s
  pw:browser [pid=15482] <will force kill> +0ms
  pw:browser [pid=15482] starting temporary directories cleanup +0ms
  pw:browser [pid=15482] <process did exit: exitCode=null, signal=SIGKILL> +20ms
  pw:browser [pid=15482] starting temporary directories cleanup +0ms
  pw:browser [pid=15482] finished temporary directories cleanup +14ms
  pw:browser [pid=15482] <gracefully close end> +0ms
  pw:api <= browser.close succeeded +30s
  pw:browser [pid=15482] finished temporary directories cleanup +0ms
✨  Done in 53.95s.
```

**Comment by mxschmitt** [comment] 2021-07-07 21:55
I tried to reproduce it, I'm also running on a Mac, using the same Chrome version and Playwright version using ESM which works for me as expected. So unfortunately not able to repro.

I saw in your case you are using `ts-run`, is this something official which does some magic?

Also which Mac and with which OS version are you using?

**Comment by joecanuelspotify** [comment] 2021-07-08 14:29
Appreciate all the help looking into this!

For context, this is [ts-run](https://github.com/kirbysayshi/ts-run), but we can ignore that. I shouldn't have used that for my example and have switched to a js file and still get the issue when running with Node. I also moved it to a separate directory with the only install being Playwright.

Mac Model: 16 inch 2019 2.4GHz Core i9
Mac Os: Big Sur v11.4
Node Version: v14.15.4

New js script
```
const { chromium } = require('playwright');

async function main() {
  const browser = await chromium.launch({
    headless: false,
    executablePath:
      // Chrome 91.0.4472.114 at time of creating this example
      '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  });

  try {
    const page = await browser.newPage();
    await page.goto('https://www.google.com');
    await page.waitForTimeout(20000);
    // Browser auto-closes after a few seconds
    // and crashes on the next command
    await page.goto('https://www.google.com');
    await browser.close();
  } catch (e) {
    console.error(e);
    await browser.close();
  }
}

main();
```

Output:
```
 ✘ joecanuel@joecanuel-mbp  ~/examples  DEBUG=pw:browser,pw:api node test-chromium-headful-playwright.js
  pw:api => browserType.launch started +0ms
  pw:browser <launching> /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading,GlobalMediaControls --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=/var/folders/w1/wrsqcf_x3ssg42vnncdkrfnc0000gn/T/playwright_chromiumdev_profile-YCGKpY --remote-debugging-pipe --no-sandbox --no-startup-window +0ms
  pw:browser <launched> pid=7101 +3ms
  pw:api <= browserType.launch succeeded +722ms
  pw:api => browser.newContext started +0ms
  pw:api <= browser.newContext succeeded +7ms
  pw:api => browserContext.newPage started +0ms
  pw:api <= browserContext.newPage succeeded +436ms
  pw:api => page.goto started +1ms
  pw:api navigating to "https://www.google.com", waiting until "load" +1ms
  pw:api   navigated to "https://www.google.com/" +160ms
  pw:api   navigated to "https://www.google.com/" +104ms
  pw:api   "domcontentloaded" event fired +0ms
  pw:api   "load" event fired +185ms
  pw:api <= page.goto succeeded +0ms
  pw:api => page.waitForTimeout started +1ms
  pw:api   "networkidle" event fired +552ms
  pw:api <= page.waitForTimeout succeeded +19s
  pw:api => page.goto started +1ms
  pw:api navigating to "https://www.google.com", waiting until "load" +1ms
  pw:api <= page.goto failed +1ms
page.goto: Navigation failed because page was closed!
=========================== logs ===========================
navigating to "https://www.google.com", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error
    at Object.captureStackTrace (/Users/joecanuel/examples/node_modules/playwright/lib/utils/stackTrace.js:51:19)
    at Connection.sendMessageToServer (/Users/joecanuel/examples/node_modules/playwright/lib/client/connection.js:73:48)
    at Proxy.<anonymous> (/Users/joecanuel/examples/node_modules/playwright/lib/client/channelOwner.js:64:61)
    at /Users/joecanuel/examples/node_modules/playwright/lib/client/frame.js:100:65
    at Frame._wrapApiCall (/Users/joecanuel/examples/node_modules/playwright/lib/client/channelOwner.js:77:34)
    at Frame.goto (/Users/joecanuel/examples/node_modules/playwright/lib/client/frame.js:98:21)
    at /Users/joecanuel/examples/node_modules/playwright/lib/client/page.js:267:60
    at Page._attributeToPage (/Users/joecanuel/examples/node_modules/playwright/lib/client/page.js:202:20)
    at Page.goto (/Users/joecanuel/examples/node_modules/playwright/lib/client/page.js:267:21)
    at main (/Users/joecanuel/examples/test-chromium-headful-playwright.js:17:16)
  pw:api => browser.close started +3ms
  pw:browser [pid=7101] <gracefully close start> +22s
  pw:browser [pid=7101] <kill> +30s
  pw:browser [pid=7101] <will force kill> +1ms
  pw:browser [pid=7101] starting temporary directories cleanup +1ms
  pw:browser [pid=7101] <process did exit: exitCode=null, signal=SIGKILL> +20ms
  pw:browser [pid=7101] starting temporary directories cleanup +0ms
  pw:browser [pid=7101] finished temporary directories cleanup +16ms
  pw:browser [pid=7101] <gracefully close end> +0ms
  pw:api <= browser.close succeeded +30s
  pw:browser [pid=7101] finished temporary directories cleanup
```

**Comment by mxschmitt** [comment] 2021-07-08 14:37
Awesome, unfortunately the logs still give us no hints. Setting the env var to `DEBUG=pw:*` would be be another try to get something more useful out of it. Thank you for time!

**Comment by joecanuelspotify** [comment] 2021-07-08 15:45
With `DEBUG=pw:*` I am seeing the close event called, but I'm not sure why. I attached the full output in the file below, but here is a snippet of when I see the page close unexpectedly.

```
2021-07-08T15:40:29.966Z pw:api   "networkidle" event fired
2021-07-08T15:40:29.966Z pw:channel:event {
  guid: 'frame@56d91126cb60056742b18087ea9032ce',
  method: 'loadstate',
  params: { add: 'networkidle' }
}
2021-07-08T15:40:30.004Z pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"E3477C84C3469256623589513357FA6B","loaderId":"50FBDF501170F0E520494984F6CD7FB8","name":"networkAlmostIdle","timestamp":8025.481349},"sessionId":"77A4EBDCB5F258FB0C9809A09F0B294F"}
2021-07-08T15:40:30.022Z pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"E3477C84C3469256623589513357FA6B","loaderId":"50FBDF501170F0E520494984F6CD7FB8","name":"firstMeaningfulPaint","timestamp":8025.235929},"sessionId":"77A4EBDCB5F258FB0C9809A09F0B294F"}
2021-07-08T15:40:30.023Z pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"E3477C84C3469256623589513357FA6B","loaderId":"50FBDF501170F0E520494984F6CD7FB8","name":"networkIdle","timestamp":8025.609765},"sessionId":"77A4EBDCB5F258FB0C9809A09F0B294F"}
2021-07-08T15:40:33.120Z pw:protocol ◀ RECV {"method":"Target.detachedFromTarget","params":{"sessionId":"77A4EBDCB5F258FB0C9809A09F0B294F","targetId":"E3477C84C3469256623589513357FA6B"}}
2021-07-08T15:40:33.121Z pw:channel:event {
  guid: 'page@cbd62fbebc0501eb81ca475b9d88c7c8',
  method: 'close',
  params: {}
}
2021-07-08T15:40:33.122Z pw:channel:event {
  guid: 'page@cbd62fbebc0501eb81ca475b9d88c7c8',
  method: '__dispose__',
  params: {}
}
2021-07-08T15:40:49.323Z pw:api <= page.waitForTimeout succeeded
```

[output.txt](https://github.com/microsoft/playwright/files/6785766/output.txt)

**Comment by mxschmitt** [comment] 2021-07-08 20:52
Is your device managed or do you have any Google Chrome policies maybe applied? You can find them when navigating to `chrome://policy`. One of the differences between Google Chrome and Chromium is that they are only applied to Google Chrome. The logs are unfortunately not very meaningful even tho they are one of the highest verbose levels.

It seems basically that Google is closing the site by themselves, can you reproduce this also on other websites or how does it impact your Playwright experience?

**Comment by joecanuelspotify** [comment] 2021-07-09 14:26
I can reproduce on other websites. It's effecting our developers experience when working on our tests because they prefer to run headful tests when iterating on tests locally.

The laptop I'm using for testing is my company managed device and it does have policies applied to it. The policies sound like a likely culprit, since you can't replicate the issue. I will try to replicate on a personal laptop and update here after that. 

 Unfortunately I'm gone on vacation next week, so I'll update you in a couple of weeks.

**Comment by aslushnikov** [comment] 2021-07-15 13:37
@joecanuelspotify this might be related to some policies that are installed on your mac. One popular one is disable running chrome without extensions.

So could you please run the following snippet?

```ts
import { chromium } from 'playwright';

async function main() {
  const browser = await chromium.launch({
    headless: false,
    ignoreDefaultArgs: true,
    args: [
      '--remote-debugging-pipe',
      '--headless',
    ],
    executablePath:
      // Chrome 91.0.4472.114 at time of creating this example
      '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  });

  try {
    const page = await browser.newPage();
    await page.goto('https://www.google.com');
    await page.waitForTimeout(20000);
    // Browser auto-closes after a few seconds
    // and crashes on the next command
    await page.goto('https://www.google.com');
    await browser.close();
  } catch (e) {
    console.error(e);
    await browser.close();
  }
}

main();
```

**Comment by joecanuelspotify** [comment] 2021-07-19 16:41
@aslushnikov First, thanks for the input :) 

That code snippet does work (after changing the import statement to the js example), but it runs headless. The issue only comes up when I run it "headfully". If I remove the '--headless' it fails on startup for me on my managed device and on my personal device. It seems to be a different error unrelated to this issue.

**Comment by joecanuelspotify** [comment] 2021-07-19 16:46
@mxschmitt I confirmed it works fine on my personal machine, so it does look like it's an issue with the managed policies.

I plan on working with my IT/Security department to see if I can isolate which policy is causing it. I will update it here to help anyone else who encounters this issue or I'll update with any other info I find.

I'm going to close this ticket for now, because the issue appears to be on my side and not a general issue with Playwright. Really appreciate all the back and forth on this 👍

**Closed** 2021-07-19 16:48 UTC
Labels: triaging

**Comment by mxschmitt** [comment] 2021-07-19 16:52
Awesome Joe! Thanks for confirming.

**Comment by SpamapS** [comment] 2021-09-20 21:43
FYI, we've narrowed it down and believe that the problem is actually our Google managed chrome setup. Chrome starts up unmanaged, and puppeteer immediately can use it, but ~1s later it phones home, and when it discovers it is managed, seems to close all active CDP sessions.
