### ISSUE TITLE
[Question] How to name the video file of a recording?

### ISSUE THREAD

**Issue by chrisjsimpson** [microsoft/playwright#4900] opened 2021-01-05 21:59 UTC
Currently Playwright generates a uuid-style filename 

We're using Playright to record out tests in a pipeline which is providing excellent visual feedback thank you!  https://github.com/Subscribie/subscribie/actions/runs/462234262 (please see artifacts)

It's very valuable to visually see when/why a test fails as a video- so we start / stop a video recording for each test.

As you can see from the artifacts, it's hard to tell which video is which without being able to name the video file during record. Is there a mechanism/recommended way to do this?

Ref https://github.com/microsoft/playwright/issues/4682

**Comment by JoelEinbinder** [comment] 2021-01-05 22:27
The uuid file names are certainly ugly. Maybe we can do something about this @yury-s? Maybe page names?

I noticed you send the same video path as a context option into each of your tests. You can set a different folder for each context/test, and then you will only have one video in each folder. I think that's the intended way to solve this today.

**Comment by mxschmitt** [comment] 2021-01-05 22:27
Seems like a duplicate of #4131

**Comment by JoelEinbinder** [comment] 2021-01-05 22:28
Ooh, good catch max! Closing as duplicate of #4131

**Closed by JoelEinbinder** 2021-01-05 22:28 UTC
Labels: P3-collecting-feedback

**Comment by chrisjsimpson** [comment] 2021-01-07 23:43
Thanks both & @JoelEinbinder for the meanwhile suggestion much appreciated :+1:
