### ISSUE TITLE
[BUG] Firefox crashed when goto file

### ISSUE THREAD

**Issue by mmarkelov** [microsoft/playwright#946] opened 2020-02-12 10:02 UTC
**Context:**
- Playwright Version: [0.10.0]
- Operating System: [ Mac]

**Code Snippet**

I got some **example.html**:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>
<body>
    <h1>Example</h1>
</body>
</html>
```

```javascript
const path = require('path')
const { firefox } = require('playwright');

(async () => {
    const browser = await firefox.launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto(`file:${path.join(__dirname, 'example.html')}`)
    await page.screenshot({ path: `example.png` });
    await browser.close();
})();
```

**Describe the bug**

It is working fine with **chromium** and **webkit**, but for **firefox** i got:
```
(node:10999) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded
    at /Users/maksim.markelov/Desktop/test/node_modules/playwright-core/lib/frames.js:898:25
  -- ASYNC --
    at Frame.<anonymous> (/Users/maksim.markelov/Desktop/test/node_modules/playwright-core/lib/helper.js:54:23)
    at Page.goto (/Users/maksim.markelov/Desktop/test/node_modules/playwright-core/lib/page.js:215:33)
    at Page.<anonymous> (/Users/maksim.markelov/Desktop/test/node_modules/playwright-core/lib/helper.js:55:31)
    at /Users/maksim.markelov/Desktop/test/index.js:9:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:10999) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by aslushnikov** [comment] 2020-02-12 19:00
Thanks for reporting! This is a dupe of #822

**Closed by aslushnikov** 2020-02-12 19:00 UTC
