### ISSUE TITLE
[BUG] Cannot launch new browser when one already initialized

### ISSUE THREAD

**Issue by o-holyshevskyi** [microsoft/playwright#26347] opened 2023-08-08 13:53 UTC
### System info
- Playwright Version: [v1.36.2]
- Operating System: [Windows 11]
- Browser: [Chromium, Firefox, Webkit]
- Other info:

### Source code

I have the next fixture:

```ts
async function configPage<T extends IPages>(pageClass: new (args: Page) => T, fn: (page: T) => Promise<void>) {
  const browser = await chromium.launch();
  const fileName = './appLoginInfo.json';
  fs.writeFileSync(fileName, APP_LOGIN_INFO as string, 'utf-8');
  const context = await browser.newContext({ storageState: fileName });
  await context.route(/(analytics|fonts)/, (route) => route.abort());
  const page = new pageClass(await context.newPage());

  await fn(page);

  await browser.close();
  fs.unlinkSync(fileName);
}
```

and through the test I'm initialize new browser with new context and page like this:

```ts
static async initializeNewContextWithPage<IPages>(type: new (obj: Page) => IPages): Promise<IPages> {
    const browser = await chromium.launch();
    const context = await browser.newContext();
    await context.route(/(analytics|fonts)/, (route) => route.abort());
    const page = await context.newPage();
    return new type(page);
  }
```

when it's ran on the launching new browser 2nd time the timeout exception is thrown.

`Error: browserType.launch: Timeout 180000ms exceeded`

Any ideas? Before updating to the latest version it's worked

**Steps**
- [Run the test]
- [Call configPage() function in fixture]
- [Do some additional steps]
- [Call initializeNewContextWithPage() function in the test]

**Expected**

The new browser is launched after calling `await chromium.launch();` function

**Actual**

The test failed by the timeout on the step `await chromium.launch();` function

**Comment by dgozman** [comment] 2023-08-08 18:38
@o-holyshevskyi
- How do you run your tests? From the command line? What flags do you pass? From VSCode extension? Do you have "Show browser" checkbox on?
- Could you please share a self-contained repro? Unfortunately, I cannot just run two functions from the above, I need your `playwright.config` file and the whole test that is using these functions to reproduce the issue.

**Comment by dgozman** [comment] 2023-08-11 15:58
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.

**Closed by dgozman** 2023-08-11 15:58 UTC
Labels: triaging
