### ISSUE TITLE
[QUESTION] How to start browser with DevTools enabled and Network Preserve log option set

### ISSUE THREAD

**Issue by jaktestowac** [microsoft/playwright#28780] opened 2023-12-23 06:55 UTC
For easy request inspection generated by tests I wish to be able to run browser with **DevTools** opened and `Preserve log` option in Network tab enabled.

Currently this can be manually done by:
- Manually form VSC Plugin. It require opening browser (by running some test - there is no option to just open browser) and then opening DevTools and `Preserve log` options, and then running test.
- Trace Viewer is partially able to record some but missing detailed info like in DevTools. 
- Setting breakpoint at start of the test and running test in VSC JavaScript Debug Terminal with Project:
  ```
        use: {
          ...devices["Desktop Chrome"],
          launchOptions: {
            devtools: true,
            }
  ```
  and manually setting `Preserve log` in DevTools

1. How to automatically add `Preserve log` to DevTools regarding `projects` setup?
Here is some code made in Puppeteer https://stackoverflow.com/a/63719833 to make it happen
2. Is possible to customize VSC plugin to Show Browser with DevTools and options like `Preserve log` enabled?

**Comment by yury-s** [comment] 2023-12-27 18:21
There is no configuration option for this in Playwright today, you enumerated the ways to do it manually. For automatic collection of the information about network activity we recommend Playwright trace viewer. If some important information is missing there, please file a feature request.

Closing this issue, as this is not a bug in Playwright and we are not planning to add support for automatically checking settings in DevTools.

**Closed by yury-s** 2023-12-27 18:21 UTC
