### ISSUE TITLE
[Bug]: Launching chromium crashes on CI pipeline but works locally

### ISSUE THREAD

**Issue by zahraaalizadeh** [microsoft/playwright#30317] opened 2024-04-10 09:46 UTC
### Version

1.41.2

### Steps to reproduce

When running the following CI configs:

```yml
name: Continuous Integration

on: [push]

jobs:
  run-functional-tests:
    name: Run Functional Test Suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'poetry'

    - name: Install dependencies
      run: |
        pip install invoke poetry
        poetry install
        
    - name: Ensure browsers are installed
      run: poetry run playwright install --with-deps
      
    - name: Run the functional test suite
      run: poetry run invoke test
```

and the test looks like:

```python
from playwright.sync_api import Page


def test_can_get_humans_txt(live_server, page: Page):
    url = f"{live_server.url}/humans.txt"
    page.goto(url)
    assert "/* TEAM */" in page.content()
```

### Expected behavior

The test run successfully on CI, like how it behaves locally.

### Actual behavior

I can run all the tests successfully using `poetry run invoke test`, but running the ci config on docker container raises error.  Looks like the same issue @barisekici001 raised https://github.com/microsoft/playwright/issues/28537#issuecomment-1847017212 

I attempted the following but I received the same error in all cases:
- both headless and headed modes
- passing single-process flag when installing the deps
- using `image: mcr.microsoft.com/playwright/python:v1.42.0-jammy`

It crashes with this trace when launching chromium:
```
ERROR src/tests/functional/test_humans.py::test_can_get_humans_txt[chromium] - playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed
| Browser logs:
| 
| <launching> /ms-playwright/chromium-1097/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-Y3rMwA --remote-debugging-pipe --no-startup-window
| <launched> pid=4889
| [pid=4889][err] [0410/085733.867364:ERROR:stack_trace_posix.cc(873)] Failed to parse the contents of /proc/self/maps
| [pid=4889][err] [0410/085734.308809:ERROR:stack_trace_posix.cc(873)] Failed to parse the contents of /proc/self/maps
| [pid=4889][err] [0410/085734.308883:ERROR:stack_trace_posix.cc(873)] Failed to parse the contents of /proc/self/maps
| [pid=4889][err] [0410/085734.340266:FATAL:zygote_main_linux.cc(145)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded(). 
| [pid=4889][err] #0 0x004008474932 base::debug::CollectStackTrace()
| [pid=4889][err] #1 0x004008462573 base::debug::StackTrace::StackTrace()
| [pid=4889][err] #2 0x0040083b9cf3 logging::LogMessage::~LogMessage()
| [pid=4889][err] #3 0x0040083ba7ce logging::LogMessage::~LogMessage()
| [pid=4889][err] #4 0x0040083a3737 logging::CheckError::~CheckError()
| [pid=4889][err] #5 0x00400782ce12 content::ZygoteMain()
| [pid=4889][err] #6 0x004007825db6 content::RunZygote()
| [pid=4889][err] #7 0x004007826c68 content::RunOtherNamedProcessTypeMain()
| [pid=4889][err] #8 0x004007827d88 content::ContentMainRunnerImpl::Run()
| [pid=4889][err] #9 0x0040078256b8 content::RunContentProcess()
| [pid=4889][err] #10 0x0040078258dd content::ContentMain()
| [pid=4889][err] #11 0x004007ebfa1a headless::HeadlessShellMain()
| [pid=4889][err] #12 0x004003ced25a ChromeMain
| [pid=4889][err] #13 0x004011d2dd90 <unknown>
| [pid=4889][err] #14 0x004011d2de40 __libc_start_main
| [pid=4889][err] #15 0x004003ced02a _start
| [pid=4889][err] 
| [pid=4889][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
| [pid=4889][err] [0410/085734.340820:FATAL:zygote_main_linux.cc(145)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded(). 
| [pid=4889][err] #0 0x004008474932 base::debug::CollectStackTrace()
| [pid=4889][err] #1 0x004008462573 base::debug::StackTrace::StackTrace()
| [pid=4889][err] #2 0x0040083b9cf3 logging::LogMessage::~LogMessage()
| [pid=4889][err] #3 0x0040083ba7ce logging::LogMessage::~LogMessage()
| [pid=4889][err] #4 0x0040083a3737 logging::CheckError::~CheckError()
| [pid=4889][err] #5 0x00400782ce12 content::ZygoteMain()
| [pid=4889][err] #6 0x004007825db6 content::RunZygote()
| [pid=4889][err] #7 0x004007826c68 content::RunOtherNamedProcessTypeMain()
| [pid=4889][err] #8 0x004007827d88 content::ContentMainRunnerImpl::Run()
| [pid=4889][err] #9 0x0040078256b8 content::RunContentProcess()
| [pid=4889][err] #10 0x0040078258dd content::ContentMain()
| [pid=4889][err] #11 0x004007ebfa1a headless::HeadlessShellMain()
| [pid=4889][err] #12 0x004003ced25a ChromeMain
| [pid=4889][err] #13 0x004011d2dd90 <unknown>
| [pid=4889][err] #14 0x004011d2de40 __libc_start_main
| [pid=4889][err] #15 0x004003ced02a _start
| [pid=4889][err] 
| [pid=4889][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
| [pid=4889][err] Received signal 11 SEGV_MAPERR 6e696c2d656d6f
| [pid=4889][err] #0 0x004008474932 [0410/085735.002284:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
| [pid=4889][err] base::debug::CollectStackTrace()
| [pid=4889][err] #1 0x004008462573 base::debug::StackTrace::StackTrace()
| [pid=4889][err] #2 0x004008474351 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

### Environment

```shell
|   System:
|     OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
|     CPU: (5) x64 unknown
|     Memory: 16.40 GB / 19.52 GB
|     Container: Yes
|   Binaries:
|     Node: 18.20.1 - /opt/acttoolcache/node/18.20.1/x64/bin/node
|     npm: 10.5.0 - /opt/acttoolcache/node/18.20.1/x64/bin/npm
|   Languages:
|     Bash: 5.1.16 - /usr/bin/bash
```

**Comment by mxschmitt** [comment] 2024-04-10 10:13
Looks like this environment does not satisfy the Chromium requirements in order to start the browser. I'm not familiar with poetry, but how does it play along with Docker?

I saw you are doing `runs-on: ubuntu-latest` and in the end `invoke test` which does execute [this](https://github.com/ackama/django-template/blob/78b18b60e060d08ab6dae58773d10af5db65b6e2/template/tasks.py#L133) task, which just invokes Pytest?

Could you try to invoke Pytest directly?

Could you try to reproduce it without Poetry?

**Comment by zahraaalizadeh** [comment] 2024-04-15 23:54
Hi @mxschmitt, thanks for looking at this. yes, Poetry manages the environment requirements. I get the same result with running invoke directly and even with installing dependancies natively. Actually I noticed I get the error when I run the on an apple M1 machine using `act`: https://github.com/nektos/act. Not sure if it's something wrong with `act` or playwright.

**Comment by mxschmitt** [comment] 2024-04-22 17:22
Closing as per above since this does not look like a Playwright bug. Feel free to file a new issue with a repro (without poetry etc), thanks!

**Closed by mxschmitt** 2024-04-22 17:22 UTC
