### ISSUE TITLE
[Question] Query by text with space

### ISSUE THREAD

**Issue by maraisr** [microsoft/playwright#4318] opened 2020-11-03 07:47 UTC
Is there an ability to query for a selector that has extraneous space around it? I'm left to "test" some legacy Angular.js apps, which are notorious for this. 

![image](https://user-images.githubusercontent.com/599459/97960076-6ba6f500-1dfc-11eb-912b-57717d26d509.png)

my `await page.waitForSelector('"What does your Ford Focus need?"')` is never resolving, and upon DEBUG mode it never resolves.

![image](https://user-images.githubusercontent.com/599459/97960120-84170f80-1dfc-11eb-8f36-8633ffc6c3ec.png)

other elements I query do however work, so it could either be the dodgy space in there—or the fact that part of the "text" is nested in a span?

**Comment by mxschmitt** [comment] 2020-11-03 09:24
Hi, it does not work because your text is in multiple elements. Seems like its related or the same feature requests as in #3873.

**Comment by maraisr** [comment] 2020-11-03 10:00
Ouch! Is there a workaround for this atm? xpath something?

**Comment by JoelEinbinder** [comment] 2020-11-03 17:29
Closing as a duplicate of #2089. But I agree that angular apps are a very good use case for this. cc @dgozman

**Closed by JoelEinbinder** 2020-11-03 17:29 UTC
