### ISSUE TITLE
[BUG] Test status is during test execution skipped

### ISSUE THREAD

**Issue by qtpsudhakar** [microsoft/playwright#11542] opened 2022-01-21 11:19 UTC
**Context:**
- Playwright Version: 1.17 & 1.18
- Operating System: windows
- Node.js version: 16.13.1
- Browser: Chromium
**Code Snippet**

//CustomReporterConfig.ts
onStepEnd(test: TestCase, result: TestResult, step: TestStep) {
	console.log(`Finished Step : ${step.title} with status ${result.status}`);
}

**Describe the bug**
The steps status in custom reporter returned as skipped instead of pass or fail.

Finished Step : page.click(//button[text()='Save']) with status skipped
Finished Step : page.waitForSelector(div.loader) with status skipped
Finished Step : Verify Groups Creation with status skipped

Able to get test status with pass, fail and skipped but not for steps 
Test Case Completed : Smoke Test Status : passed

**Comment by mxschmitt** [comment] 2022-01-21 11:43
The reason for that is that `result.status` is actually the test-status and not the step status. It's kinda miss-leading that its skipped during the test-execution, but if you do for example this, you see that onTestEnd the test-status is success/failed and correct:

```js
  onStepEnd(test: TestCase, result: TestResult, step: TestStep) {
    console.log(`Finished Step : ${step.title} with status ${result.status}`);
  }
  override onTestEnd(test: TestCase, result: TestResult) {
    console.log(`Finished Test : ${test.title} with status ${result.status}`);
  }
```

**Comment by dgozman** [comment] 2022-01-21 16:15
I don't quite understand what is wrong here, and how it is supposed to be.

**Comment by mxschmitt** [comment] 2022-01-21 17:21
Closing, since this is working as intended after an offline discussion with dgozman.

**Closed by mxschmitt** 2022-01-21 17:21 UTC
Labels: test-runner, v1.19

**Comment by DeLuca-Agustin** [comment] 2022-05-18 18:12
> Closing, since this is working as intended after an offline discussion with dgozman.

@mxschmitt could you explain the intention behind this decision? What are the advantages of having the test result instead of the step result in the onStepEnd method?
