### ISSUE TITLE
[BUG] Typescript not working with ESM?

### ISSUE THREAD

**Issue by damianobarbati** [microsoft/playwright#17496] opened 2022-09-21 07:42 UTC
@rwoll reopening with repro here:  <https://github.com/damianobarbati/playwright-bug>

## System:
 - OS: macOS 12.6
 - Memory: 9.99 GB / 40.00 GB
## Binaries:
 - Node: 16.11.1 - ~/.nvm/versions/node/v16.11.1/bin/node
 - Yarn: 1.22.17 - ~/.nvm/versions/node/v16.11.1/bin/yarn
 - npm: 8.0.0 - ~/.nvm/versions/node/v16.11.1/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright: ^1.25.2 => 1.25.2

# Repro 
To reproduce locally, clone <https://github.com/damianobarbati/playwright-bug>
Then:
```sh
nvm install
yarn install
yarn test:e2e
```

The error:
```sh
$ PWDEBUG=console DEBUG=pw:webserver playwright test
(node:5412) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError: Unknown file extension ".ts" for /Users/damians/Desktop/playwright-bug/playwright.config.ts
    at new NodeError (node:internal/errors:371:5)
    at Loader.defaultGetFormat [as _getFormat] (node:internal/modules/esm/get_format:71:15)
    at Loader.getFormat (node:internal/modules/esm/loader:105:42)
    at Loader.getModuleJob (node:internal/modules/esm/loader:243:31)
    at Loader.import (node:internal/modules/esm/loader:177:17)
    at importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at Loader._requireOrImport (/Users/damians/Desktop/playwright-bug/node_modules/@playwright/test/lib/loader.js:309:28)
    at Loader._requireOrImportDefaultObject (/Users/damians/Desktop/playwright-bug/node_modules/@playwright/test/lib/loader.js:324:18)
    at Loader.loadConfigFile (/Users/damians/Desktop/playwright-bug/node_modules/@playwright/test/lib/loader.js:79:20)
    at Runner.loadConfigFromResolvedFile (/Users/damians/Desktop/playwright-bug/node_modules/@playwright/test/lib/runner.js:98:12)
    at runTests (/Users/damians/Desktop/playwright-bug/node_modules/@playwright/test/lib/cli.js:168:27)
    at Gi.<anonymous> (/Users/damians/Desktop/playwright-bug/node_modules/@playwright/test/lib/cli.js:79:7) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by pavelfeldman** [comment] 2022-09-22 04:37
As per ESM spec, once you enter the "type": "module" mode, you must specify `.js` extension in every import. Note that despite being TypeScript, per TypeScript ESM spec it should still be `.js`.

**Comment by damianobarbati** [comment] 2022-09-22 07:53
@pavelfeldman I don't see how it is supposed to work honestly. 
I tried, but renaming it to `.js` breaks everything. 

First you have to remove the typing:
```ts
import type { PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
```

Then loading .ts specs breaks:
```sh
$ PWDEBUG=console DEBUG=pw:webserver playwright test
(node:4464) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

Running 0 tests using 0 workers

TypeError: Unknown file extension ".ts" for /Users/damians/Desktop/predator/e2e/index.spec.ts
```

**Comment by pavelfeldman** [comment] 2022-09-28 04:35
I cloned the repo and everything worked for me. It does call `yarn dev` as a web server which does not exist, but if I remove it it starts the tests.

**Comment by aslushnikov** [comment] 2022-09-28 09:16
I'll close this as per above. Please do not hesitate to re-file if things still don't work for you!

**Comment by damianobarbati** [comment] 2022-09-28 09:44
@pavelfeldman thanks it's working now, closing.

**Comment by damianobarbati** [comment] 2022-09-30 08:53
@pavelfeldman sorry for the back and forth, but there's something very weird: the behaviour is not predictable. Sometime it works, sometime it doesn't: same repro, nothing changed, not running again.

**Comment by pavelfeldman** [comment] 2022-09-30 17:12
I just cloned it, it does not show and ESM / TS errors, but it fails due to the baseURL being set to /.

**Comment by yury-s** [comment] 2022-10-04 00:06
Closing per the response above, feel free to open a new issue and link to this one if it still doesn't work.

**Closed by yury-s** 2022-10-04 00:06 UTC
Labels: triaging

**Comment by Christopher2K** [comment] 2022-11-19 19:08
Hello! 
I'm reopening this issue just to say that I'm constantly reproducing this bug in my CI pipeline: https://github.com/Christopher2K/llcoolwebsite/actions/runs/3504747726/jobs/5870668804

The thing is, I'm really unable to get the same result on my computer. How can I help?
