### ISSUE TITLE
[BUG] Playwright Test recorded video is not correct resolution and blurry

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright#7246] opened 2021-06-21 10:18 UTC
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.12.2
- Operating System: [e.g. Windows, Linux or Mac] Windows 10 10.0.19043
- Node.js version: [e.g. 12.22, 14.6]  v16.3.0
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```ts
// foo.spec.ts
import { test, expect } from '@playwright/test';

test('basic test', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  const name = await page.innerText('.navbar__title');
  expect(name).toBe('Playwright');
});
```
```ts
// playwright.config.ts
import { PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
  use: {
    // Browser options
    headless: false,
    slowMo: 50,

    // Context options
    viewport: { width: 1920, height: 1080 },
    ignoreHTTPSErrors: true,

    // Artifacts
    screenshot: 'on',
    video: 'on',
  },
};
export default config;
```
**Describe the bug**

Playwright recorded video is blurry and is of resolution 800x450.

I expect playwright to record video in 1920x1080

**Comment by mxschmitt** [comment] 2021-06-21 13:01
You can set a custom resolution via:

```javascript
    video: {
      mode: 'on',
      size: {
        width: 1920,
        height: 1080,
      }
    },
```

instead of

```
video: 'on',
```

which will then be 1920x1080 since it by default follows the Playwright record.video defaults, see [here](https://playwright.dev/docs/next/api/class-browser#browser-new-context-option-record-video).

But as a user I would also have expected that the video size is equal to the viewport size by default.

**Comment by kumaraditya303** [comment] 2021-06-21 13:06
> You can set a custom resolution via:
> 
> ```js
>     video: {
>       mode: 'on',
>       size: {
>         width: 1920,
>         height: 1080,
>       }
>     },
> ```
> 
> instead of
> 
> ```
> video: 'on',
> ```
> 
> which will then be 1920x1080 since it by default follows the Playwright record.video defaults, see [here](https://playwright.dev/docs/next/api/class-browser#browser-new-context-option-record-video).
> 
> But as a user I would also have expected that the video size is equal to the viewport size by default.

It shows me error in VSCode, morover your sinppet does not even capture video now 
<img width="755" alt="Screenshot (76)" src="https://user-images.githubusercontent.com/59607654/122766818-91b3d380-d2bf-11eb-96b2-5c57816fad06.png">

**Comment by mxschmitt** [comment] 2021-06-21 13:08
Its afaik a new feature which gets released in v1.13. You can try it out today via `npm install @playwright/test@next`

**Comment by kumaraditya303** [comment] 2021-06-21 13:12
> Its afaik a new feature which gets released in v1.13. You can try it out today via `npm install @playwright/test@next`

Okay now its working but the video is upscaled in the browser window, it is not at 100% vw

**Comment by kumaraditya303** [comment] 2021-06-21 13:36
@mxschmitt  Also sometimes the test fails randomly with the error:

```console
❯ npx playwright test -u
Using config at D:\playwright-test\playwright.config.ts                                               test\workerRunner.js:290:

Running 1 test using 1 worker

  x 1) tests\foo.spec.ts:3:1 › [chromium] basic test (3s)


  1) tests\foo.spec.ts:3:1 › [chromium] basic test =================================================

    Error: SOI not found

      5 |   const name = await page.innerText(".navbar__title");
      6 |   expect(name).toBe("Playwright");
    > 7 |   expect(await page.screenshot()).toMatchSnapshot("foo.jpeg");
        |                                   ^
      8 | });
      9 |

        at constructor.parse (D:\playwright-test\node_modules\jpeg-js\lib\decoder.js:629:15)
        at Object.decode (D:\playwright-test\node_modules\jpeg-js\lib\decoder.js:1109:11)
        at compareImages (D:\playwright-test\node_modules\@playwright\test\lib\test\golden.js:54:95)  
        at Object.compare (D:\playwright-test\node_modules\@playwright\test\lib\test\golden.js:103:20)        at Object.toMatchSnapshot (D:\playwright-test\node_modules\@playwright\test\lib\test\expect.js:41:40)
        at __EXTERNAL_MATCHER_TRAP__ (D:\playwright-test\node_modules\expect\build\index.js:342:30)
        at Object.throwingMatcher (D:\playwright-test\node_modules\expect\build\index.js:343:15)
        at D:\playwright-test\tests\foo.spec.ts:7:35
        at WorkerRunner._runTestWithBeforeHooks (D:\playwright-test\node_modules\@playwright\test\lib\test\workerRunner.js:290:13)


  1 failed
    tests\foo.spec.ts:3:1 › [chromium] basic test ==================================================

```

**Comment by mxschmitt** [comment] 2021-06-21 17:59
Is this error reproducible for you? If so please create a separate issue with an attached reproducible.

**Comment by pavelfeldman** [comment] 2021-06-24 00:25
I think the video resolution part is addressed.

**Closed by pavelfeldman** 2021-06-24 00:25 UTC
Labels: test-runner, triaging
