### ISSUE TITLE
[BUG] fs.promises.readFile doesn't resolve in electron's preload

### ISSUE THREAD

**Issue by indutny-signal** [microsoft/playwright#10808] opened 2021-12-08 21:48 UTC
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows
- Node.js version: 16.9.1
- Browser: Electron 16
- Extra: see https://github.com/electron/electron/issues/32132

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

https://gist.github.com/indutny-signal/609177f4f6fb041f01ac1516f9f2e20f

Steps to reproduce:

1. Clone https://gist.github.com/indutny-signal/609177f4f6fb041f01ac1516f9f2e20f
2. `npm install`
3. `node test.js`

The window should display "done" (compare to `npm start`)

**Describe the bug**

`fs.promises.readFile` and `fs.readFile` never invoke the callback when Electron app runs under playwright.

**Comment by dgozman** [comment] 2021-12-08 23:17
@indutny-signal Playwright does not do anything special here, so any help debugging the issue is appreciated.

**Comment by indutny-signal** [comment] 2021-12-08 23:43
Thanks for a prompt response. I'm not proficient in playwright's codebase, but does it do anything on inspector connection that could potentially block renderer/preload threads?

**Comment by dgozman** [comment] 2021-12-08 23:48
@indutny-signal Hmm... Maybe there is a target that is paused and not resumed. If you could run with `DEBUG=pw:protocol*` and send us the logs, that would help!

**Comment by indutny-signal** [comment] 2021-12-08 23:52
@dgozman here you go: https://gist.github.com/indutny-signal/2bd93b820582e331ed8f4230ae7f1d91 thanks!

**Comment by dgozman** [comment] 2021-12-09 02:55
I don't see any issues in the log. I tried reproducing, and it all works for me with playwright 1.17.1, node 16.11.1 and electron 16.0.4 on macOS.

**Comment by indutny-signal** [comment] 2021-12-09 08:03
Ah, but it happens only on Windows. It works just fine for me on both macOS and Linux, otherwise.

**Comment by pavelfeldman** [comment] 2022-10-20 03:08
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by pavelfeldman** [comment] 2023-11-16 04:43
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Closed by pavelfeldman** 2023-11-16 04:43 UTC
Labels: P3-collecting-feedback, feature-electron
