### ISSUE TITLE
[BUG] Route.continue fails with "Failed to load resource: net::ERR_BLOCKED_BY_CLIENT" in Chorme

### ISSUE THREAD

**Issue by mhorejsi** [microsoft/playwright#23598] opened 2023-06-08 14:25 UTC
### System info
- Playwright Version: 1.33.0
- Operating System: macOS 11.7.6, official Playwright Docker image
- Browser: Chromium

This problem occurs only in Chrome. Firefox and Webkit work as expected without any issues. 

We want to proxy requests coming to `baseURL` to different process running to the same machine (localhost). Webserver used for Playwright tests is running at `http://localhost:8081`. We need to proxy the request to Express server running on the same protocol & host, but different port.

```ts
await page.route("/api/foo",
    async (route) => {
        route.continue({url: "http://localhost:9999/api/foo"});
    }
);
```

Note that `/api/foo` doesn't do any redirect.

The code snippet above works well in Firefox and Webkit, but fails in Chrome with `ERR_BLOCKED_BY_CLIENT`. I don't have adblock or any other extension that would block the request. Moreover, the same error happens when I run the tests in Docker container which uses the corresponding `mcr.microsoft.com/playwright` Docker image.

Workaround which works for regular HTTP requests is not to use `continue`, but `fetch` + `fulfill`:

```ts
await page.route("/api/foo",
    async (route) => {
        const response = await route.fetch({url: "http://localhost:9999/api/foo"})
        await route.fulfill({response: response});
    }
);
```

The workaround works well for regular requests / responses, but we cannot use it for Server Sent Events (SSE). SSE is a long-running request that "never" ends. We need Playwright to proxy the SSE requests to Express and let it handle the lifecycle of the connection.

Do you have any idea why we observe `ERR_BLOCKED_BY_CLIENT` in Chrome? I suppose that that's just some Chromium configuration issue, but I haven't found any Chromium [launch option](https://peter.sh/experiments/chromium-command-line-switches/) that would help.

**Comment by aslushnikov** [comment] 2023-06-08 23:19
@mhorejsi well, should work! Maybe it is something specific to SSE. Could you build a small repro that demonstrates the issue? It could be that this is a chromium bug and needs to be filed upstream.

**Comment by mhorejsi** [comment] 2023-06-09 16:31
You can see the repro here - https://github.com/mhorejsi/playwright-bug-repro-23598.

**Comment by aslushnikov** [comment] 2023-06-09 21:10
@mhorejsi thank you, I can see the issue with your repro. I'll try to simplify it a little bit more to see what exactly is going on.

P.S.: the `npm i` doesn't work for me on your reproduction usecase due to the `package-lock.json` that refers to some internal package registry. Removing it makes the repro work though.

**Comment by mhorejsi** [comment] 2023-06-12 07:27
@aslushnikov, sorry for the internal package registry. I didn't pay enough attention to `package-lock.json`. It's fixed now. And thanks for looking into this issue!

**Comment by aslushnikov** [comment] 2023-06-12 23:19
@mhorejsi I managed to reproduce this without any third-party modules:

```ts
import {test, expect} from "@playwright/test";
import http from 'http';

const createServer = (port, handler) => {
  const server = http.createServer(handler);
  return new Promise(x => server.listen(port, x));
};

test("The bug exists!", async ({ page }) => {
  await createServer(3000, (req, res) => {
    if (req.url.startsWith('/sse'))
      return res.end(503);
    res.setHeader('content-type', 'text/html');
    res.end(`
      <!doctype html>
      <h1></h1>
      <script type="text/javascript">
        const h1 = document.querySelector('h1');
        h1.textContent = 'sse: initializing...';

        const evtSource = new EventSource("/sse");
        evtSource.onerror = () => h1.textContent = 'sse: error';
        evtSource.onopen = () => h1.textContent = 'sse: opened';
        evtSource.onmessage = () => h1.textContent = 'sse: message received';
      </script>
    `);
  });

  await createServer(4321, (req, res) => {
    res.statusCode = 200;
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('connection', 'keep-alive');
    res.setHeader('Content-Type', 'text/event-stream');

    res.write(`id: ${(new Date()).toLocaleTimeString()}\ndata: hello, world!\n\n`);
  });

  // Setup in-page routing to redirect SSE requests to the mock SSE
  // server.
  await page.route(/sse/, async (route) => {
    console.log('intercepted!', route.request().url());
    await route.continue({ url: `http://localhost:4321/sse` });
  });

  // Navigate to the Web App.
  await page.goto(`http://localhost:3000?foo=bar`);
  await expect(page.locator('h1')).toHaveText(/message received/);
});
```

This looks like a chromium bug to me though; i'll follow-up with a repro to file upstream.

**Comment by aslushnikov** [comment] 2023-07-06 20:29
Filed upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=1462721

I'll close this in favor of the upstream bug. Thanks!

**Closed by aslushnikov** 2023-07-06 20:29 UTC
Labels: v1.36
