### ISSUE TITLE
[BUG] Pnpm + VScode extension does not work

### ISSUE THREAD

**Issue by WcaleNieWolny** [microsoft/playwright#28703] opened 2023-12-18 18:51 UTC
**Context:**
- Playwright Version: `    "@playwright/test": "1.41.0-alpha-dec-18-2023",`
- Operating System: Linux (endevour os)
- Node.js version: v21.4.0
- Visual Studio Code version: vscodium 1.85.0
- Playwright for VSCode extension version: 1.0.20 but i tried every version from 1.0.15 to 1.0.20
- Browser: not relevant
- Extra: [any specific details about your environment]

**Code Snippet**

none, but I do have [the repo](https://github.com/WcaleNieWolny/capgo/tree/fix_e2e_tests) with the bug as well as a list of installed extensions

![image](https://github.com/microsoft/playwright/assets/50914789/212281df-378c-4255-bc55-94da350f248f)

and one thread on discord describing a similar issue [here](https://discord.com/channels/807756831384403968/1163463216760901652/1163463216760901652) 

**Describe the bug**

I cannot get playwright extension to work. I get a wierd error message and this log
![image](https://github.com/microsoft/playwright/assets/50914789/a1aadec3-5d59-4441-8a9d-5b0040ce9976)

PS: I tried to run this command. Tho I use PNPM instead of npm. I ran this command and it did not change anything

**Comment by yury-s** [comment] 2023-12-18 18:59
Can you please provide exact steps how to reproduce the problem?

**Comment by WcaleNieWolny** [comment] 2023-12-18 19:19
Yes.
 * I have run `pnpn i` on a project with installed playwright (see linked repo)
 * I installed the playwright vscode extension
 * I clicked this refresh button
 
![image](https://github.com/microsoft/playwright/assets/50914789/90bffa1f-efac-43ea-ba9a-f08a7ede1fe8)

I got this
![image](https://github.com/microsoft/playwright/assets/50914789/fd562f26-2712-4931-ae8a-4b44df66dead)
![image](https://github.com/microsoft/playwright/assets/50914789/7017399e-d3d5-49b9-9286-e4e3539dc667)

I ran `npx playwright test` and everything works fine (expect the vscode extension which does not work at all)

**Comment by WcaleNieWolny** [comment] 2023-12-18 19:20
I tried multiple versions of playwright, multiple version of the extension. Always got the same error

**Comment by mxschmitt** [comment] 2023-12-18 23:58
Are you using PNPN in Plug'n Play mode? (is there a `.pnp.cjs` file - its a hidden file)

If so, then the following would work for you: https://github.com/microsoft/playwright-vscode/wiki/Experimental-Yarn-PNP-support. Could you try that?

**Comment by WcaleNieWolny** [comment] 2023-12-19 04:52
unfortunately there is not. I tried this regardless and it did not change anything

**Comment by WcaleNieWolny** [comment] 2023-12-19 05:07
I just created a new project with `pnpm create playwright`. Extension still does not work :/

**Comment by WcaleNieWolny** [comment] 2023-12-19 17:33
I have updated vscodium, I have reinstall the extension multiple times, I have downgraded node to LTS, nothing works

**Comment by yury-s** [comment] 2023-12-19 18:02
We can add more debug logging to make the resolution process easier:
- node.js binary resolution problems (like empty environment with no PATH)
- playwright config load failures (obscure no tests found issue)
- launching VSCode from macOS dock (unclear what to do)

**Comment by WcaleNieWolny** [comment] 2023-12-19 18:39
Is there any other way I can debug this/ help you figure it out? Any logs or anything

**Comment by mxschmitt** [comment] 2024-01-03 14:33
Opening the DevTools via the Command Prompt might yield more helpful output:

<img width="481" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/c53c35be-6413-4d81-a25f-cd19a0c8bda9">

and then under the console tab there might be different Playwright related output.

**Comment by WcaleNieWolny** [comment] 2024-01-09 04:53
![image](https://github.com/microsoft/playwright/assets/50914789/2b0336e0-0088-4b9f-bb3e-256792b41af7)
![image](https://github.com/microsoft/playwright/assets/50914789/7c0c062e-a061-4d4e-8241-e99f82dfbcd7)
![image](https://github.com/microsoft/playwright/assets/50914789/e5f4c88c-0a6f-4d94-bc00-f76774080e95)

**Comment by mxschmitt** [comment] 2024-01-09 11:21
Thats useful! Thanks! That was what we were guessing, we'll work on improved reporting / workaround for that soon.

In the meantime, what you can do to workaround, make sure to start VSCode with Node.js in the PATH or add a Node.js symlink in a PATH folder, so VSCode knows about it.

(The VSCode Terminal is different, since it invoked a new shell, this has nothing to do with the Playwright VSCode extension).

**Comment by mxschmitt** [comment] 2024-01-09 16:59
@WcaleNieWolny the issue should be fixed in our latest [Nightly build](https://github.com/microsoft/playwright-vscode/wiki), feel free to try this out if you want until it gets released.

**Comment by WcaleNieWolny** [comment] 2024-01-09 17:56
@mxschmitt thanks a lot! You fixed my issue :tada:

**Comment by mxschmitt** [comment] 2024-01-09 17:57
I'll reopen for now, since we want to add a bit more debugging logging for the future.

**Comment by WcaleNieWolny** [comment] 2024-01-12 05:15
![image](https://github.com/microsoft/playwright/assets/50914789/1a5f0669-072d-49b7-bad4-15249228a07a)

Not sure this is related but i also get this error. I checked devtools and no errors shows up. I run playwright with the same config on CI/CD and there it works fine

**Comment by WcaleNieWolny** [comment] 2024-01-12 05:22
And when I try to debug my test I get
![image](https://github.com/microsoft/playwright/assets/50914789/517c53fb-085a-4557-9c1a-5d1a27ae0d4e)

**Comment by mxschmitt** [comment] 2024-01-12 13:38
This issue is now similar to https://github.com/microsoft/vscode-js-debug/issues/1150. To summarise:

VSCode is started in an environment where there is no Node.js in the PATH and you as a user rely on nvm to find the right Node.js version. Workaround would be to start Code from the Terminal with just "code" so it has access to the current PATH.

Do you have `source ~/.nvm/nvm.sh` in your .bashrc file? Ideally VSCode should internally evaluate that to get the updated PATH.

**Comment by mxschmitt** [comment] 2024-01-12 23:36
The main issue has been addressed now, we landed a couple of patches https://github.com/microsoft/playwright-vscode/pull/400 https://github.com/microsoft/playwright-vscode/pull/401 https://github.com/microsoft/playwright-vscode/pull/402 in order to give there a better user experience. For the issue above / future issues, I recommend filing a new issue. We'll release an official update to the extension on Monday!

**Closed** 2024-01-12 23:36 UTC
Labels: v1.42
