### ISSUE TITLE
[BUG] using emulator doesn't click on an element not in view

### ISSUE THREAD

**Issue by gsarmientor** [microsoft/playwright#8322] opened 2021-08-19 19:49 UTC
**Context:**
- Playwright Version: 1.14
- Operating System: Windows
- Node.js version: v14.15.4
- Browser:  WebKit emulator

## System:
 - OS: Windows 10 10.0.19042
 - Memory: 4.70 GB / 15.86 GB
## Binaries:
 - Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 4.4.19 - C:\Program Files\Git\usr\bin\bash.EXE
## npmPackages:
 - playwright: ^1.14.0 => 1.14.0

**Describe the bug**
Running test using emulator (iPad11-webkit, Galaxy Tab 4 - chromium) as shown:
use: {
        headless: false,
        screenshot: 'on',
        browserName: 'webkit',
        ...devices['iPad Pro 11'],
      },
use: {
        headless: false,
        screenshot: 'on',
        browserName: 'chromium',
        ...devices['Galaxy Tab S4'],
      },

the execution generates the following error 

```

page.click: Evaluation failed: TypeError: undefined is not an object (evaluating 'e.nodeType')
=========================== logs ===========================
waiting for selector "hz-navbar hz-base-avatar div[class="avatar"]"
  selector resolved to visible <div class="avatar" _ngcontent-otn-c115="">…</div>
attempting click action
  waiting for element to be visible, enabled and stable
    element is not stable - waiting...
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (726.67,52.12)
============================================================
```
Using Chrome passes the test with different display settings but this only happens when using emulator. Test case:
- Navigate to a page
- page.click(avatar) 

when watching the test on the emulator: 
- page is loaded
- avatar is not in view but present in the DOM
- visually, scrolling doesn't seem to happen as element is never shown in view

**Comment by mxschmitt** [comment] 2021-08-19 19:56
This is probably a duplicate of #8229. Do you have a reproducible for that? (small script which demonstrates the bug).

**Comment by JoelEinbinder** [comment] 2021-08-24 00:08
Closing as duplicate of #8229

**Closed by JoelEinbinder** 2021-08-24 00:08 UTC
Labels: triaging
