### ISSUE TITLE
[BUG] Error: page.goto: GDBus.Error:org.freedesktop.portal.Error.NotAllowed

### ISSUE THREAD

**Issue by cheehongw** [microsoft/playwright#22404] opened 2023-04-14 10:34 UTC
### System info
- Playwright Version: v1.32.3
- Operating System: Ubuntu 22.04.2 LTS
- Browser: Webkit 16.4 (playwright build v1811)
- Node version: 14.21.2

I was testing out playwright as a e2e solution for one of my projects. It worked fine on Windows 10, but encountered this issue on Ubuntu 22.04.2

**Steps**
- Install playwright using `npm init playwright@latest`
- Select yes for installing browsers and OS dependencies
- Run `npx playwright run`

**Expected**

It should pass all test cases on the default `example.spec.ts` for all 3 configured browsers (Chromium, Firefox and Webkit)

**Actual**

All webkit tests fails with the following result:

```
Running 6 tests using 4 workers
  1) [webkit] › example.spec.ts:3:5 › has title ────────────────────────────────────────────────────

    Error: page.goto: GDBus.Error:org.freedesktop.portal.Error.NotAllowed: This call is not available inside the sandbox
    =========================== logs ===========================
    navigating to "https://playwright.dev/", waiting until "load"
    ============================================================

      2 |
      3 | test('has title', async ({ page }) => {
    > 4 |   await page.goto('https://playwright.dev/');
        |              ^
      5 |
      6 |   // Expect a title "to contain" a substring.
      7 |   await expect(page).toHaveTitle(/Playwright/);

        at /home/user/dummyProj/e2e//example.spec.ts:4:14

  2) [webkit] › example.spec.ts:10:5 › get started link ────────────────────────────────────────────

    Error: page.goto: GDBus.Error:org.freedesktop.portal.Error.NotAllowed: This call is not available inside the sandbox
    =========================== logs ===========================
    navigating to "https://playwright.dev/", waiting until "load"
    ============================================================

       9 |
      10 | test('get started link', async ({ page }) => {
    > 11 |   await page.goto('https://playwright.dev/');
         |              ^
      12 |
      13 |   // Click the get started link.
      14 |   await page.getByRole('link', { name: 'Get started' }).click();

        at /home/user/dummyProj/e2e/example.spec.ts:11:14

  2 failed
    [webkit] › example.spec.ts:3:5 › has title ─────────────────────────────────────────────────────
    [webkit] › example.spec.ts:10:5 › get started link ─────────────────────────────────────────────
  4 passed (4.7s)
```

**Comment by cheehongw** [comment] 2023-04-14 10:50
Deleted `~/.cache/ms-playwright` and reinstalled the browsers with `npx playwright install --with-deps`. 

Still the same error

**Comment by mxschmitt** [comment] 2023-04-16 19:07
Which Ubuntu desktop do you have installed is it KDE? Looks like your current user has no permissions to interact with your running x-server. Running it with sudo should make it work as a workaround.

**Comment by cheehongw** [comment] 2023-04-18 04:06
Thanks for replying! I have Unity installed for the ubuntu desktop. 

I installed node 14 as root user, tried the workaround that you mentioned and the webkit and chromium tests passes. 

However, the firefox tests failed with this error, so I doubt it is the cleanest workaround:

```
 1) [firefox] › example.spec.ts:3:5 › has title ───────────────────────────────────────────────────

    Error: browserType.launch: Browser.enable): Browser closed.
    ==================== Browser output: ====================
    <launching> /root/.cache/ms-playwright/firefox-1391/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-GtJbRR -juggler-pipe -silent
    <launched> pid=35891
    [pid=35891][err] Running Nightly as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/.mutter-Xwaylandauth.VIVL31 which is owned by cheehong.)
    [pid=35891] <process did exit: exitCode=1, signal=null>
    [pid=35891] starting temporary directories cleanup
    =========================== logs ===========================
    <launching> /root/.cache/ms-playwright/firefox-1391/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-GtJbRR -juggler-pipe -silent
    <launched> pid=35891
    [pid=35891][err] Running Nightly as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/.mutter-Xwaylandauth.VIVL31 which is owned by cheehong.)
    [pid=35891] <process did exit: exitCode=1, signal=null>
    [pid=35891] starting temporary directories cleanup
    ============================================================
```

**Comment by mxschmitt** [comment] 2023-04-20 15:40
Looks like something is going on with your Ubuntu Unity setup, hence WebKit doesn't like it. I have unfortunately no Ubuntu Unity VM, so wasn't able look deep enough into it.

For the Firefox issue it looks like its the same as https://github.com/microsoft/playwright/issues/6500#issuecomment-838515115 and can be fixed by setting the `HOME=/root` env var.

Not sure if its possible, but having a reproduction for the WebKit issue inside Docker would be the best for us.

In what kind of Terminal are you running your commands? Is it something like VSCode installed via Snap's Terminal?

**Comment by aslushnikov** [comment] 2023-04-30 07:14
Looks like the discussion has stalled; closing this. Please feel free to re-file if you have a better repro and you think we can be helpful!

**Closed by aslushnikov** 2023-04-30 07:14 UTC
Labels: triaging
