### ISSUE TITLE
[Question] Why is document.hidden not supported in Playwright?

### ISSUE THREAD

**Issue by hdorgeval** [microsoft/playwright#12099] opened 2022-02-14 23:12 UTC
It seems that `document.hidden` is not working once the browser is controlled by Playwright.

Given you open a browser tab (outside of playwright) and inject in the console the script :
```js
setInterval(() => {console.log(`document.hidden = ${document.hidden}`)}, 1000)
```

When you open a new browser tab
And you wait a few seconds
And you come back to the previous tab
Then you have the following logs in the console:

![Screen Shot 2022-02-14 at 23 51 53](https://user-images.githubusercontent.com/9698924/153960323-cc3926de-360f-495f-8131-de4c13768983.png)

When you do the same steps in a browser controlled by Playwright
Then you have the following logs in the console :
![Screen Shot 2022-02-15 at 00 00 38](https://user-images.githubusercontent.com/9698924/153961181-d88ee59d-cf26-4cdb-8c08-95998750a31f.png)

Unless I am wrong, `document.hidden` should be handled by Playwright.
This missing feature prevents to test the front stops specific activities (for example the front stops to poll a rest API endpoint) when the user switches from one browser tab to another, and vice-versa: the front should, for example, restart it's polling activity when the browser tab becomes actif again.

Regards

**Comment by dgozman** [comment] 2022-02-15 04:34
Playwright ensures that all pages open with it are considered "active" to avoid any issues with background/throttling/etc. when opening multiple pages at the same time. This is a deliberate choice to simplify common testing scenarios.

That said, there could in theory be a mode that disables this behavior, but it was not prioritized yet, as discussed in #3570. Let me close this issue as a duplicate of #3570.

**Closed by dgozman** 2022-02-15 04:34 UTC
