### ISSUE TITLE
[BUG]AssertionError: rimraf: callback function required

### ISSUE THREAD

**Issue by AdamGyori** [microsoft/playwright#28182] opened 2023-11-16 08:49 UTC
### System info
- Playwright Version: v1.39.0
- Operating System: macOS 
- Browser: Chromium
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Steps**
- [Run the test]
- [...]

**Expected**
Test being run as usually.

**Actual**

![Screenshot 2023-11-16 at 9 49 09](https://github.com/microsoft/playwright/assets/52413763/018cafe5-c9a1-4de4-811b-e1595e6642eb)
or]

**Comment by mxschmitt** [comment] 2023-11-16 10:43
Closing since this issue does not contain clear reproduction steps / follow the issue template.

Please re-file with exact repro steps, starting with "npm init playwright".

**Closed by mxschmitt** 2023-11-16 10:43 UTC
