### ISSUE TITLE
[BUG] The installation of cookies in the response to the request doesn't work

### ISSUE THREAD

**Issue by rytikovroman1994** [microsoft/playwright#23568] opened 2023-06-07 11:06 UTC
### System info
- Playwright Version: [v1.34.3]
- Operating System: [macOS 13.3.1]
- Browser: [All]
- Other info:

**Test file (self-contained)**

```js
await page.route(/navigation\/auth\/authorize/, async (route) => {
    route.fulfill({
      status: 400,
      headers: {
        "Last-Modified": "Tue, 23 May 2023 12:27:35 GMT",
        "Set-Cookie":
          "navi_token=tQ2AswTzvxrlG_hx9Nm4B",
      },
      body: `<!DOCTYPE html><html></body></html>`,
    });
  });
```

**Steps**
- [Run the test]

**Expected**

Response Headers:
Last-Modified: Tue, 23 May 2023 12:27:35 GMT
Set-Cookie: navi_token=tQ2AswTzvxrlG_hx9Nm4B

**Actual**
Response Headers:
Last-Modified: Tue, 23 May 2023 12:27:35 GMT

[Describe actual behavior]

Mock response to the address /navigation\/auth\/authorize/.
The response should have a header that sets cookies.
All other cookies except Set-Cookies are set. Cookies are also not installed.

**Comment by aslushnikov** [comment] 2023-06-08 05:22
This is a dupe of https://github.com/microsoft/playwright/issues/11035

**Closed by aslushnikov** 2023-06-08 05:22 UTC
