### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SevaDzenCode** [microsoft/playwright#22524] opened 2023-04-20 14:19 UTC
How i can resolve this issue "Note that handling the event forks the control flow and makes the script harder to follow. Your scenario might end while you are downloading a file since your main control flow is not awaiting for this operation to resolve." 
```
var fileElements = await page.QuerySelectorAllAsync("//div[@class='msg in hover file d-flex']//a");
            foreach (var fileElement in fileElements)
            {
                try
                {
                    string href = await fileElement.GetAttributeAsync("href");
                    string fileExtension = Path.GetExtension(href);
                    if (!string.Equals(fileExtension, ".png", StringComparison.OrdinalIgnoreCase))
                    {
                        var downloadTask = page.WaitForDownloadAsync();
                        await fileElement.ClickAsync();

                        var download = await downloadTask;
                        await download.SaveAsAsync("C:\\temp\\");
                    }
                }
                catch (TimeoutException ex)
                {
                    Console.WriteLine("Error: Download timed out. " + ex.Message);
                }

            }
```

After line var download = await downloadTask; my program throw error. 
Thanks a million

**Comment by dgozman** [comment] 2023-04-20 16:16
@SevaDzenCode Your code looks good. What's the error that you see? Could you share the full program so that we can run it locally and reproduce the issue?

**Comment by dgozman** [comment] 2023-04-24 14:32
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.

**Closed by dgozman** 2023-04-24 14:32 UTC
Labels: triaging
