### ISSUE TITLE
[BUG] `launchPersistentContext` crashes on Official docker image

### ISSUE THREAD

**Issue by devonpmack** [microsoft/playwright#28537] opened 2023-12-07 19:25 UTC
### System info
- Playwright Version: v1.36.0
- Operating System: Linux AMD64 host running Official docker image - mcr.microsoft.com/playwright:v1.40.0-jammy
- Browser: Google Chrome 120.0.6099.71
- Other info:
   Works locally on M1 mac host (running in docker)

### Source code

```ts
import { chromium } from '@playwright/test';

(async () => {
  const context = await chromium.launchPersistentContext("", {
    args: [
      '--disable-dev-shm-usage',
      '--no-sandbox',
      '--headless=new',
    ],
    headless: true,
  });
  const page = await context.pages()[0];

  await page.goto('https://example.com/');
  console.log(await page.title());
  await context.close();
})();
```

**Steps**
- Try to launch with persistent context

Note that regular `chromium.launch` is successful.

**Expected**

It launches successfully

**Actual**

It crashes with this trace

```
  - <launching> /ms-playwright/chromium-1091/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --disable-dev-shm-usage --no-sandbox --headless=new --user-data-dir=/tmp/playwright_chromiumdev_profile-zjxSCq --remote-debugging-pipe about:blank
2023-12-07 14:22:54.169	
  - <launched> pid=15940
2023-12-07 14:22:54.169	
  - [pid=15940][err] chrome_crashpad_handler: --database is required
2023-12-07 14:22:54.169	
  - [pid=15940][err] Try 'chrome_crashpad_handler --help' for more information.
2023-12-07 14:22:54.169	
  - [pid=15940][err] [15940:15940:1207/192253.744596:FATAL:crashpad_linux.cc(195)] Check failed: client.StartHandler(handler_path, *database_path, metrics_path, url, annotations, arguments, false, false). 
2023-12-07 14:22:54.169	
  - [pid=15940][err] #0 0x55eb4ddb2572 base::debug::CollectStackTrace()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #1 0x55eb4dd9ef43 base::debug::StackTrace::StackTrace()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #2 0x55eb4dcf7eb3 logging::LogMessage::~LogMessage()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #3 0x55eb4dcf898e logging::LogMessage::~LogMessage()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #4 0x55eb4dce0fd7 logging::CheckError::~CheckError()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #5 0x55eb5031bc24 crash_reporter::internal::PlatformCrashpadInitialization()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #6 0x55eb503129c8 crash_reporter::InitializeCrashpad()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #7 0x55eb4953dde3 ChromeMainDelegate::PreSandboxStartup()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #8 0x55eb4d152112 content::ContentMainRunnerImpl::Initialize()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #9 0x55eb4d150280 content::RunContentProcess()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #10 0x55eb4d15064d content::ContentMain()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #11 0x55eb4953c31b ChromeMain
2023-12-07 14:22:54.169	
  - [pid=15940][err] #12 0x7f6cbecf0d90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
2023-12-07 14:22:54.169	
  - [pid=15940][err] #13 0x7f6cbecf0e40 __libc_start_main
2023-12-07 14:22:54.169	
  - [pid=15940][err] #14 0x55eb4953c02a _start
2023-12-07 14:22:54.169	
  - [pid=15940][err] 
2023-12-07 14:22:54.169	
  - [pid=15940][err] Received signal 6
2023-12-07 14:22:54.169	
  - [pid=15940][err] #0 0x55eb4ddb2572 base::debug::CollectStackTrace()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #1 0x55eb4dd9ef43 base::debug::StackTrace::StackTrace()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #2 0x55eb4ddb1f91 base::debug::(anonymous namespace)::StackDumpSignalHandler()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #3 0x7f6cbed09520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
2023-12-07 14:22:54.169	
  - [pid=15940][err] #4 0x7f6cbed5d9fc pthread_kill
2023-12-07 14:22:54.169	
  - [pid=15940][err] #5 0x7f6cbed09476 raise
2023-12-07 14:22:54.169	
  - [pid=15940][err] #6 0x7f6cbecef7f3 abort
2023-12-07 14:22:54.169	
  - [pid=15940][err] #7 0x55eb4dd930a5 base::debug::BreakDebuggerAsyncSafe()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #8 0x55eb4dcf8914 base::RepeatingCallback<>::Run()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #9 0x55eb4dcf865b logging::LogMessage::~LogMessage()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #10 0x55eb4dcf898e logging::LogMessage::~LogMessage()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #11 0x55eb4dce0fd7 logging::CheckError::~CheckError()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #12 0x55eb5031bc24 crash_reporter::internal::PlatformCrashpadInitialization()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #13 0x55eb503129c8 crash_reporter::InitializeCrashpad()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #14 0x55eb4953dde3 ChromeMainDelegate::PreSandboxStartup()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #15 0x55eb4d152112 content::ContentMainRunnerImpl::Initialize()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #16 0x55eb4d150280 content::RunContentProcess()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #17 0x55eb4d15064d content::ContentMain()
2023-12-07 14:22:54.169	
  - [pid=15940][err] #18 0x55eb4953c31b ChromeMain
2023-12-07 14:22:54.169	
  - [pid=15940][err] #19 0x7f6cbecf0d90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
2023-12-07 14:22:54.169	
  - [pid=15940][err] #20 0x7f6cbecf0e40 __libc_start_main
2023-12-07 14:22:54.169	
  - [pid=15940][err] #21 0x55eb4953c02a _start
2023-12-07 14:22:54.169	
  - [pid=15940][err]   r8: 00007fff3f171410  r9: 0000000000000300 r10: 0000000000000008 r11: 0000000000000246
2023-12-07 14:22:54.169	
  - [pid=15940][err]  r12: 0000000000000006 r13: 0000000000000016 r14: 000055eb46ea3b9a r15: 00007fff3f171e10
2023-12-07 14:22:54.169	
  - [pid=15940][err]   di: 0000000000003e44  si: 0000000000003e44  bp: 0000000000003e44  bx: 00007f6cbdbdb380
2023-12-07 14:22:54.169	
  - [pid=15940][err]   dx: 0000000000000006  ax: 0000000000000000  cx: 00007f6cbed5d9fc  sp: 00007fff3f171340
2023-12-07 14:22:54.169	
  - [pid=15940][err]   ip: 00007f6cbed5d9fc efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
2023-12-07 14:22:54.169	
  - [pid=15940][err]  trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
2023-12-07 14:22:54.169	
  - [pid=15940][err] [end of stack trace]
2023-12-07 14:22:54.169	
]
```

**Comment by barisekici001** [comment] 2023-12-08 11:28
Hi @mxschmitt ,
I upgraded Playwright from version 1.39 to 1.40 on my local machine, and I did not face any issues locally. All of my tests are running successfully. To run it remotely, I pulled the image below to my local machine. After pulling version 1.40, I assigned a new name/tag and pushed it to a private repository. However, when I attempt to run it in the CI pipeline, I encounter the same error as @devonpmack 

Note: I tried both headless and headed modes for Chrome, Firefox, and WebKit, but I received the same error in all cases.

The issue might be related to the new Docker image ?

```
browserType.launch
Error: browserType.launch: Target page, context or browser has been closed
Browser logs:

<launching> /ms-playwright/chromium-1091/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-s6350N --remote-debugging-pipe --no-startup-window
<launched> pid=929
[pid=929][err] [1208/084506.834196:FATAL:zygote_main_linux.cc(145)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded(). 
[pid=929][err] #0 0x0055084aad90 base::debug::CollectStackTrace()
[pid=929][err] #1 0x005508498f04 base::debug::StackTrace::StackTrace()
[pid=929][err] #2 0x0055083f7780 logging::LogMessage::~LogMessage()
[pid=929][err] #3 0x0055083f8098 logging::LogMessage::~LogMessage()
[pid=929][err] #4 0x0055083e131c logging::CheckError::~CheckError()
[pid=929][err] #5 0x0055078e6728 content::ZygoteMain()
[pid=929][err] #6 0x0055078dfffc content::RunZygote()
[pid=929][err] #7 0x0055078e0ea4 content::RunOtherNamedProcessTypeMain()
[pid=929][err] #8 0x0055078e1f34 content::ContentMainRunnerImpl::Run()
[pid=929][err] #9 0x0055078df694 content::RunContentProcess()
[pid=929][err] #10 0x0055078dfb24 content::ContentMain()
[pid=929][err] #11 0x005507f2f358 headless::HeadlessShellMain()
[pid=929][err] #12 0x0055041eb22c ChromeMain
[pid=929][err] #13 0x005512ad73fc (/usr/lib/aarch64-linux-gnu/libc.so.6+0x273fb)
[pid=929][err] #14 0x005512ad74cc __libc_start_main
[pid=929][err] #15 0x0055041eb034 (/ms-playwright/chromium-1091/chrome-linux/chrome+0x41eb033)
[pid=929][err] 
[pid=929][err] [1208/084507.039775:FATAL:zygote_main_linux.cc(145)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded(). 
[pid=929][err] #0 0x0055084aad90 base::debug::CollectStackTrace()
[pid=929][err] #1 0x005508498f04 base::debug::StackTrace::StackTrace()
[pid=929][err] #2 0x0055083f7780 logging::LogMessage::~LogMessage()
[pid=929][err] #3 0x0055083f8098 logging::LogMessage::~LogMessage()
[pid=929][err] #4 0x0055083e131c logging::CheckError::~CheckError()
[pid=929][err] #5 0x0055078e6728 content::ZygoteMain()
[pid=929][err] #6 0x0055078dfffc content::RunZygote()
[pid=929][err] #7 0x0055078e0ea4 content::RunOtherNamedProcessTypeMain()
[pid=929][err] #8 0x0055078e1f34 content::ContentMainRunnerImpl::Run()
[pid=929][err] #9 0x0055078df694 content::RunContentProcess()
[pid=929][err] #10 0x0055078dfb24 content::ContentMain()
[pid=929][err] #11 0x005507f2f358 headless::HeadlessShellMain()
[pid=929][err] #12 0x0055041eb22c ChromeMain
[pid=929][err] #13 0x005512ad73fc (/usr/lib/aarch64-linux-gnu/libc.so.6+0x273fb)
[pid=929][err] #14 0x005512ad74cc __libc_start_main
[pid=929][err] #15 0x0055041eb034 (/ms-playwright/chromium-1091/chrome-linux/chrome+0x41eb033)
[pid=929][err] 
[pid=929][err] Received signal 11 SEGV_MAPERR 6e696c2d656d6f
[pid=929][err] #0 0x0055084aad90 [1208/084510.228140:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[pid=929][err] base::debug::CollectStackTrace()
[pid=929][err] #1 0x005508498f04 base::debug::StackTrace::StackTrace()
[pid=929][err] #2 0x0055084aac3c base::debug::(anonymous namespace)::StackDumpSignalHandler()
[pid=929][err] #3 0x005511af9000 (/usr/lib/aarch64-linux-gnu/ld-linux-aarch64.so.1+0x3dfff)
[pid=929][err] #4 0x0055085cf620 event_base_loop
[pid=929][err] #5 0x0055084b4338 base::MessagePumpLibevent::Run()
[pid=929][err] #6 0x00550845c268 
Call log:
  - <launching> /ms-playwright/chromium-1091/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-s6350N --remote-debugging-pipe --no-startup-window
  - <launched> pid=929
  - [pid=929][err] [1208/084506.834196:FATAL:zygote_main_linux.cc(145)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded(). 
  - [pid=929][err] #0 0x0055084aad90 base::debug::CollectStackTrace()
  - [pid=929][err] #1 0x005508498f04 base::debug::StackTrace::StackTrace()
  - [pid=929][err] #2 0x0055083f7780 logging::LogMessage::~LogMessage()
  - [pid=929][err] #3 0x0055083f8098 logging::LogMessage::~LogMessage()
  - [pid=929][err] #4 0x0055083e131c logging::CheckError::~CheckError()
  - [pid=929][err] #5 0x0055078e6728 content::ZygoteMain()
  - [pid=929][err] #6 0x0055078dfffc content::RunZygote()
  - [pid=929][err] #7 0x0055078e0ea4 content::RunOtherNamedProcessTypeMain()
  - [pid=929][err] #8 0x0055078e1f34 content::ContentMainRunnerImpl::Run()
  - [pid=929][err] #9 0x0055078df694 content::RunContentProcess()
  - [pid=929][err] #10 0x0055078dfb24 content::ContentMain()
  - [pid=929][err] #11 0x005507f2f358 headless::HeadlessShellMain()
  - [pid=929][err] #12 0x0055041eb22c ChromeMain
  - [pid=929][err] #13 0x005512ad73fc (/usr/lib/aarch64-linux-gnu/libc.so.6+0x273fb)
  - [pid=929][err] #14 0x005512ad74cc __libc_start_main
  - [pid=929][err] #15 0x0055041eb034 (/ms-playwright/chromium-1091/chrome-linux/chrome+0x41eb033)
  - [pid=929][err] 
  - [pid=929][err] [1208/084507.039775:FATAL:zygote_main_linux.cc(145)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded(). 
  - [pid=929][err] #0 0x0055084aad90 base::debug::CollectStackTrace()
  - [pid=929][err] #1 0x005508498f04 base::debug::StackTrace::StackTrace()
  - [pid=929][err] #2 0x0055083f7780 logging::LogMessage::~LogMessage()
  - [pid=929][err] #3 0x0055083f8098 logging::LogMessage::~LogMessage()
  - [pid=929][err] #4 0x0055083e131c logging::CheckError::~CheckError()
  - [pid=929][err] #5 0x0055078e6728 content::ZygoteMain()
  - [pid=929][err] #6 0x0055078dfffc content::RunZygote()
  - [pid=929][err] #7 0x0055078e0ea4 content::RunOtherNamedProcessTypeMain()
  - [pid=929][err] #8 0x0055078e1f34 content::ContentMainRunnerImpl::Run()
  - [pid=929][err] #9 0x0055078df694 content::RunContentProcess()
  - [pid=929][err] #10 0x0055078dfb24 content::ContentMain()
  - [pid=929][err] #11 0x005507f2f358 headless::HeadlessShellMain()
  - [pid=929][err] #12 0x0055041eb22c ChromeMain
  - [pid=929][err] #13 0x005512ad73fc (/usr/lib/aarch64-linux-gnu/libc.so.6+0x273fb)
  - [pid=929][err] #14 0x005512ad74cc __libc_start_main
  - [pid=929][err] #15 0x0055041eb034 (/ms-playwright/chromium-1091/chrome-linux/chrome+0x41eb033)
  - [pid=929][err] 
  - [pid=929][err] Received signal 11 SEGV_MAPERR 6e696c2d656d6f
  - [pid=929][err] #0 0x0055084aad90 [1208/084510.228140:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
  - [pid=929][err] base::debug::CollectStackTrace()
  - [pid=929][err] #1 0x005508498f04 base::debug::StackTrace::StackTrace()
  - [pid=929][err] #2 0x0055084aac3c base::debug::(anonymous namespace)::StackDumpSignalHandler()
  - [pid=929][err] #3 0x005511af9000 (/usr/lib/aarch64-linux-gnu/ld-linux-aarch64.so.1+0x3dfff)
  - [pid=929][err] #4 0x0055085cf620 event_base_loop
  - [pid=929][err] #5 0x0055084b4338 base::MessagePumpLibevent::Run()
  - [pid=929][err] #6 0x00550845c268 
```

**Comment by mxschmitt** [comment] 2023-12-13 17:59
Does this also reproduce without specifying any custom args?

We cannot guarantee the execution when custom args are passed.

**Comment by devonpmack** [comment] 2023-12-14 21:34
@mxschmitt Without any custom args, it runs 😲 But the `headless=new` flag seems to cause the crash. Unfortunately, according to https://playwright.dev/docs/chrome-extensions#headless-mode, you need to use this argument in order to run chrome extensions 😔 

**Minimal reproduction**
```
await chromium.launchPersistentContext('/tmp/playwright_user_data', {
  args: ['--headless=new'],
});
```

**Comment by mxschmitt** [comment] 2023-12-14 21:52
Playwright supports custom browsers args, but does not guarantee that all features continue to work as expected. I'll close this issue, since there is no action item for Playwright. That said, we'll take a look at the documentation and will try to make this clear.

**Closed by mxschmitt** 2023-12-14 21:52 UTC
