### ISSUE TITLE
[BUG]Navigate page failed with net::ERR_EMPTY_RESPONSE when using proxy

### ISSUE THREAD

**Issue by lxy2222** [microsoft/playwright#20703] opened 2023-02-07 07:22 UTC
**Context:**
- Playwright Version: 1.27.0
- Operating System: [e.g. Windows
- Node.js version: 16
- Browser: Chromium

Hi all, I am using proxy and `proxy.bypass` to mock add host for our domain, but the code is below
![image](https://user-images.githubusercontent.com/12553152/217174665-8d3b3c74-c30a-4264-adf4-14a90259dfb6.png)
when I am trying to test the case, there is a error shows `page.goto: net::ERR_EMPTY_RESPONSE at x.x.x.com/`

and the trace file shows
![image](https://user-images.githubusercontent.com/12553152/217175006-4ab15329-33ed-476e-b63f-e299e4a83e77.png)

I also test the IP like adding the ip: domain in my host file, it works fine with manually test
![image](https://user-images.githubusercontent.com/12553152/217176076-23c05fc2-7265-47fb-a91d-f77fab56cf7f.png)

Could you please tell me how I can solve this issue ? Thanks

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
 const browser = await chromium.launch(proxy ? {
            proxy: {
                server: proxy,
                bypass: getProxyBypassConfig(),
            }
        } : {});
```

**Comment by mxschmitt** [comment] 2023-02-07 09:58
How does your proxy bypass look like? Can you share a full repro with clear steps?

**Comment by lxy2222** [comment] 2023-02-07 13:26
Thanks @mxschmitt
The complete code looks like
```
const browser = await chromium.launch(proxy ? {
            proxy: {
                server: "per-context"
            },
        } : {});
this._mobileContext = await browser.newContext({
                ...devices["iPhone 6"],
                baseURL: this.baseUrl,
                storageState: `storageStateUser1${prefix}.json`,
                serviceWorkers: rootDirectory ? "block" : "allow",
                recordHar: {
                    path: "mobile.har"
                },
                proxy: {
                    server: proxy,
                    bypass: ".com,example.cdn.com"
                }
            });
```
the proxy here is a Ip address, like 1.1.1.1, the repro step is that

1.  add the proxy for browser context and run `npx playwrite test `
2. then will occur the error like below
![image](https://user-images.githubusercontent.com/12553152/217256620-dc8951b6-3990-4bba-9aa7-ed79eb7aff3d.png)
I also record the har between test, it's weird that the remote address can only show :80, the har file is in the attachment, could you please help figure out is there something I missed? Thank you very very much


[playwright har.zip](https://github.com/microsoft/playwright/files/10675418/playwright.har.zip)

**Comment by mxschmitt** [comment] 2023-02-08 00:40
I recommend reaching out to the Chromium bug tracker: https://bugs.chromium.org since we don't do anything special there and just set the proxy inside Chromium. What I would double check is that the proxy you are passing there is actually good, try to use it with curl, and make sure it works without bypass. Answering these questions would give more hints about what's going wrong.

**Comment by lxy2222** [comment] 2023-02-08 00:54
thanks, I do the test without bypass, but it does have the same error, so the only solution is to raise a bug to chrominum ?

**Comment by lxy2222** [comment] 2023-02-08 01:01
and I also record the har, the proxy is the ip address 52.109.89.37:443, but when I check the har, the proxy request looks like 
![image](https://user-images.githubusercontent.com/12553152/217401822-829a2e81-9f61-4c01-8549-39ab6e28bdf1.png)
could you please provide any other clues ?

**Comment by lxy2222** [comment] 2023-02-08 02:05
test with chromium directly, it shows the same error
one more question, we want to test the case in the domain with a specific proxy, in our daily usage is that  adding the ip address in the host file like
x.x.x.x  example.com
can we use playwright to achieve that ? Thanks very much

**Comment by mxschmitt** [comment] 2023-02-08 10:03
Playwright is not capable of doing that. Since the original issue is not caused by Playwright, I'm closing this one for now.

**Closed by mxschmitt** 2023-02-08 10:03 UTC
Labels: triaging
