### ISSUE TITLE
[BUG] apiContext fails on 1.40 and above specifically

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#28953] opened 2024-01-11 16:34 UTC
So I installed the latest playwright code on my suite of api tests and for some reason I am getting:

`Error: apiRequestContext.delete: Target page, context or browser has been closed`

This is not happening on `1.39` and earlier versions, but `1.40` and above are failing. The specific bit of code looks like this:

```
  public async delete(
    url: string,
    description: string,
    headers: any = {},
  ): Promise<APIResponse> {
    let getResponse: APIResponse;
    if (Object.keys(headers).length === 0) {
      headers = {
       //specific headers added here
      };
    }
    await test.step(`DELETE request for ${description}`, async () => {
      getResponse = await this.apiContext.delete(url, { headers: headers });
    });
    return getResponse;
  }
```
(This is simply a wrapper function for client api calls, but the error points at `getResponse = await this.apiContext.delete(url, { headers: headers });` line specifically.

The client code that calls it is fairly simple (For example)
```
public async deleteWidget(id: number, headers = null) {
    const DELETE_WIDGET_URL = `some/url/here`;
    const getResponse: APIResponse = await super.delete(
      DELETE_WIDGET_URL,
      `/widget/{id}`,
      headers ?? {},
    );
    return getResponse;
  }
```

What's strange is this is only happening for the `apiContext.delete` and none of these others (All the other wrapper methods are basically the same). It's also happening on the same API calls......which were working in `1.39` and below. Looking at the traceviewer I don't see anything strange particularly.

I will note in the example that fails I am passing an object with a bunch of "bad headers" essentially to test that I receive a `401` back.  (Which if I look at the traceviewer/network tab I AM getting a `401` back, but it's like it's closing the test too fast).

This also happens for `.patch` as well. I can't really figure it out either since it works fine in older versions. It also seems to be happening for a certain selection of tests. In traceviewer I can see the call but nothing in the "network" tab like it's closing before it can even finish.

EDIT: Looks like between `1.39` and `1.40` diff the `TargetClosedError` function is introduced. I do an "afterAll" cleanup and the trace network tab shows a "close" connection. Maybe since I am re-using the `apiContext` in my wrapper/client library it's causing some sort of error?

EDIT2: Further testing shows the test is working when I DO NOT reassign the created wrapper client class. my spec file looks something like this. It must be something to do with re-using the apicontext:

```
test.describe("PATCH /widgets", async () => {
  let widget: Widget;
  let widgetID: number;
  test.beforeAll(async ({ request }) => {
    widget = new Widget(request);
    //Create a widget before we patch it
    const res = await widget.addWidget();
    const json = await res.json();
    serverID = json.widgetID;
    expect(res.status()).toEqual(200);
  });
  test("Update Widget", async () => {
    const resPatch = await widget.updateWidget(widgetID);
    expect(resPatch.status()).toEqual(200);
  });
});
```

**Comment by msmith1114** [comment] 2024-01-11 18:14
I have confirmed the issue lies with re-using apiRequestContext after it's been disposed I assume. Which is unfortunate for using it as a "page object" type class since it doesn't allow you to re-use it once it's been disposed.

**Comment by dgozman** [comment] 2024-01-11 23:18
@msmith1114 It is hard to understand what's going on without the full source, but I think that `request` that is stored in the widget is closed at the end of `beforeAll`, and so is not accessible during the test. If you need a `request` that spans across tests, create one manually:

```ts
// Note the imported request factory here.
import { test, expect, request } from '@playwright/test';

let widget: Widget;

// Note no {request} argument.
test.beforeAll(async () => {
  // Create a new request context.
  const apiContext = await request.newContext();
  widget = new Widget(apiContext);
});
```

Let me know whether this helps.

**Comment by msmith1114** [comment] 2024-01-12 05:47
@dgozman That's what I had to do, I had some tests re-using the same apiRequestContext in my wrapper/baseclient class. I guess 1.40 introduced errors for that (Although technically it worked beforehand)

**Comment by dgozman** [comment] 2024-01-12 16:55
> Basically you can't re-use apiRequestContext anymore after it's been disposed it seems.

That's right, I think there was a bugfix in v1.40.

It seems like the issue is resolved, so closing it. If you still encounter problems, please file a new issue.

**Closed by dgozman** 2024-01-12 16:55 UTC
