### ISSUE TITLE
How can I get TypeScript `baseUrl` to work?

### ISSUE THREAD

**Issue by joakimgunst** [microsoft/playwright#12175] opened 2022-02-17 07:34 UTC
The `v1.18.0` [release notes](https://github.com/microsoft/playwright/releases/tag/v1.18.0) mention support for `baseUrl` in `tsconfig.json`. I'm not able to make it work.

Here is a minimal example: https://github.com/joakimgunst/playwright-debug

I have `baseUrl` set to `./src`, and import `src/titles.ts` as `from "titles"` in `e2e/example.spec.ts`.

When I run `npm run test` in the example repo, I get `Error: Cannot find module 'titles'`.

TypeScript does not show any errors when running `npm run tsc`.

If I change the import to `from "../src/titles"`, everything works as expected.

Also, thank you for creating this great library!

**Comment by dimas7** [comment] 2022-02-17 09:42
Same here
Works only when 'paths' specified

**Comment by dgozman** [comment] 2022-02-17 22:24
This is by design, `baseUrl` without `paths` is not supported because it is ambiguous. This is definitely not clear from the error or docs - we should improve them.

**Comment by joakimgunst** [comment] 2022-02-18 05:24
Okay, thank you for the replies!

I fixed the issue by adding `paths`:

```json
"baseUrl": "./src",
"paths": {
  "common/*": ["common/*"],
}
```

Now it is possible to import from `src/common` as `common`.

It would be good to update the docs, as it it surprising that this works differently from the [TypeScript module resolution](https://www.typescriptlang.org/docs/handbook/module-resolution.html#additional-module-resolution-flags).

**Comment by mitas1** [comment] 2022-02-21 13:54
> This is by design, baseUrl without paths is not supported because it is ambiguous.

@dgozman, can you elaborate on this more, please? What is the issue? Will it never be supported?

**Comment by pavelfeldman** [comment] 2022-02-28 23:55
Looks like @dgozman beat me to it. Closing as fixed, should work w/o path now as well.

**Closed by pavelfeldman** 2022-02-28 23:55 UTC
Labels: feature-test-runner, v1.20

**Comment by kristojorg** [comment] 2023-03-23 10:28
Is this fixed? I am still seeing the same error on playwright 1.32

**Comment by dgozman** [comment] 2023-03-23 15:53
@kristojorg Please file a new issue filling the "Bug Report" template and providing a repro we can run locally. We'd be happy to take a look!

**Comment by kristojorg** [comment] 2023-03-31 12:40
Okay I finally found the issue - for anyone else encountering this, the problem was that I had a directory in my `/src` and a node module that had the same name:

```
- node_modules/
  - msw/
- src/
  - msw/
    - handlers.ts
- playwright/
  - test-utils.ts
```

My `baseUrl` was set to `./src`, so I expected absolute imports from the `src` directory to work. Having the directory with the same name as the node module meant that when I tried to `import handlers from "msw/handlers"` from within `playwright/test-utils.ts`, I would get a module not found error for "msw". Changing this directory in src to `src/msw-utils` resolved the issue.

Hope that helps someone else one day : )

**Comment by kyle-chine-leismore** [comment] 2025-01-26 23:50
> Okay, thank you for the replies!
> 
> I fixed the issue by adding `paths`:
> 
> "baseUrl": "./src",
> "paths": {
>   "common/*": ["common/*"],
> }
> 
> Now it is possible to import from `src/common` as `common`.
> 
> It would be good to update the docs, as it it surprising that this works differently from the [TypeScript module resolution](https://www.typescriptlang.org/docs/handbook/module-resolution.html#additional-module-resolution-flags).

May I know is this in Browser or Node? I tried on Node.js 22. It is still complaining Can't Find Module, even after set baseUrl and Path.
