### ISSUE TITLE
[Bug]: Fullpage screenshot with different size

### ISSUE THREAD

**Issue by coolcorexix** [microsoft/playwright#7995] opened 2021-08-05 09:13 UTC
### Playwright version

1.13.0

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### Other information

Ubuntu 20.4

### What happened? / Describe the bug

I am using github action to run these playwright test. For some of my commit, the test failed because the full-page screenshot was different with size when the actual contain white gap below

Expected:
---
![sth-to-show-expected](https://user-images.githubusercontent.com/25930830/128324664-0941e59e-1d6f-442d-8dc3-dcbbba7afdb0.png)
---

Actual:
---
![sth-to-show-actual](https://user-images.githubusercontent.com/25930830/128327383-bbef8596-074c-419d-8d6d-f682271723a2.png)
---
Which cause the test to be flaky.

### Code snippet to reproduce your bug
This is my source code, powered with NextJs: https://github.com/coolcorexix/nemothecollector
Main code is in the homepage, located in packages/ntc-fe/src/home-page-data/RealHomePage.tsx

**Comment by mxschmitt** [comment] 2021-08-05 18:51
I guess we are talking about the [Dummy.spec.ts](https://github.com/coolcorexix/nemothecollector/blob/mainster/packages/ntc-fe-automation-test/suites/Dummy.spec.ts) test file. There I would recommend to wait instead of 1 second to wait for an actual selector, that the page is being rendered via [page.waitForSelector](https://playwright.dev/docs/api/class-page#page-wait-for-selector).

(if this does not help and thats the test, then I will take a more detailed look)

**Comment by phatNfqAsia** [comment] 2021-08-06 03:06
@mxschmitt the manually wait for 1000ms actually patch the bug. But the thing is it is not supposed to be there, I just do that to get my CI green. As you instructed to use page.waitForSelector, as you can see in the screenshot every element is ready so the browser should wait no more, but it just has different page size. Is there anything I can do to make the page size fixed?

**Comment by mxschmitt** [comment] 2021-08-06 13:09
Instead of `await page.waitForTimeout()` you could use `await page.waitForSelector("text=Soundcloud")`. Another guess is, since this is a Next.js site, maybe they have some auto-reloading overlays included which confuse Playwright. This is common with the local development servers. But since you are using `next build` with `next start` this should not be the case.

I tried it on the production site a few times and for me its giving expected results:

```js
const playwright = require('playwright');

(async () => {
    const browser = await playwright.chromium.launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('https://nemothecollector-git-mainster-coolcorexix.vercel.app/');
    await page.screenshot({ path: `example.png`, fullPage: true });
    await browser.close();
})()

// node test.js && exiftool example.png | grep "Image Height"
```

**Comment by coolcorexix** [comment] 2021-08-09 02:17
@mxschmitt it is very flaky from my POV. Just add some more commit then the error would emerge, like: it has fixed result for a commit but the next one it cause this error and the error also consistent throughout every single CI. I am finding the wrong commit after the right commit to show you.

**Comment by pavelfeldman** [comment] 2021-08-23 23:25
I don't think we'll be able to help w/o the repro. Depending on when you take a screenshot, it'll be of a different size, that's expected. I noticed following factors that all individually would contribute to weird behavior:
- can image has no explicit size, as it loads it is big, then it shrinks leaving the white patch below the page
- your web fonts load lazily, depending on when they render you get different screenshots
- second image has a broken infinite animation - inspect it in the devtools.

Visual regression testing requires a lot of determinism and care, so it'll be failing on the use cases like this. I'll close this bug, but if you fix those above and the problem persists, please feel free to open a new one.

**Closed by pavelfeldman** 2021-08-23 23:25 UTC
Labels: triaging
