### ISSUE TITLE
[BUG][Chromium] No option to start browser in not-incognito mode in launchOptions

### ISSUE THREAD

**Issue by StanislavIvanovQA** [microsoft/playwright#12053] opened 2022-02-11 23:29 UTC
**Context:**
- Playwright Version: 1.18.1

If you need to use extensions, there is no options to configure this behaviour for browser from launchOptions as in incognito mode browser removes all extensions.

**Comment by dgozman** [comment] 2022-02-14 19:24
@StanislavIvanovQA I assume this is about [`launchOptions`](https://playwright.dev/docs/api/class-testoptions#test-options-launch-options) in the config? If so, seems like a duplicate of #11833. Please let me know if you mean something else, and I'll reopen.

**Closed by dgozman** 2022-02-14 19:24 UTC

**Comment by StanislavIvanovQA** [comment] 2022-02-14 19:47
> @StanislavIvanovQA I assume this is about [`launchOptions`](https://playwright.dev/docs/api/class-testoptions#test-options-launch-options) in the config? If so, seems like a duplicate of #11833. Please let me know if you mean something else, and I'll reopen.

Yes, both tickets is about the same. Thank you!
