### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by caseyoneill** [microsoft/playwright#11465] opened 2022-01-18 21:41 UTC
**Context:**
- Playwright Version: 1.17.2
- Operating System: Mac
- Node.js version: 17.2.0
- Browser: Playwright default Chromium

## System:
 - OS: macOS 11.6.2
 - Memory: 1.92 GB / 32.00 GB
## Binaries:
 - Node: 17.2.0 - /usr/local/bin/node
 - npm: 8.1.4 - /usr/local/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright: ^1.17.2 => 1.17.2 

**Problem**
When Chromium or Chrome is opened by Playwright, the window.innerHeight value is incorrect. If you open the dev tools console and inspect that property you will most likely get a number that is not accurate. If you then resize the window and inspect again, the number will not have updated. Sometimes the innerHeight value is larger than the window.outerHeight value which should be impossible.

**Expected Result**
window.innerHeight should be accurate

**Code Snippet**

```const { chromium } = require("playwright");

// Simple script to demonstrate window.innerHeight bug
(async () => {
    const browser = await chromium.launch({
      headless: false,
    });
    const page = await browser.newPage();
    await page.goto("http://google.com");

    // Place breakpoint here. Go to browser window and open debug console.
    // inspect window.innerHeight. Resize window, inspect again and notice
    // that the value does not change.
    await page.screenshot({ path: `example.png` });
  })();
```

**Comment by mxschmitt** [comment] 2022-01-18 21:44
This is expected, by default Playwright has a viewport of 1280x720. If you want to disable that, you can pass `viewport: null` when creating a context. See here: https://playwright.dev/docs/emulation#viewport

```js
const page = await browser.newPage({ viewport: null });
// or
const context = await browser.newPage({ viewport: null });
```

**Comment by caseyoneill** [comment] 2022-01-18 22:14
Interesting. Why does Playwright hijack these values? I understand wanting to open or resize a browser to a specific size but why break properties that report window size if the browser is resized? I would expect the browser to open to the specified viewport but if it is resized, the inner height value should reflect the new browser size.

**Comment by mxschmitt** [comment] 2022-01-19 06:53
It's common to instruct browsers with a fixed viewport size in end-to-end tests. This makes them reproducible on different environments.

Other e2e libraries do similar things.

You can disable the fixed viewport by passing viewport: null. Closing since it's answered.

**Closed by mxschmitt** 2022-01-19 06:53 UTC
Labels: triaging
