### ISSUE TITLE
[Question]Not able to call APIRequest methods ( request.get / request.post ) in utility functions as the scope allows them to be used inside "test" function only

### ISSUE THREAD

**Issue by Palak-Jethwani** [microsoft/playwright#10787] opened 2021-12-08 12:39 UTC
**#1 :** 
In my test cases I use APIs for data clean up purposes (tear down, data changes reversal, data deletion) and since I have to use it multiple times I want to put the common code in utility function  (ApiHelper in log snippet) which is outside test function but when I do so the code fails

`1) [chromium] › profile.test.ts:28:10 › Update User Credential › Update Password - Positive Test @sanity @regression 

    **TypeError: request.get is not a function**

      72 |     finally{
      73 |         await test.step('Revert Changes',async()=>{
    > 74 |             await ApiHelper.changePassword(email,oldPswd);
         |                             ^
      75 |             // await page.waitForTimeout(3000);
      76 |             // await profileHeaderPage.clickDownArrow();
      77 |             // await profileHeaderPage.gotoSettings();

        at Function.changePassword (/Users/palakjethwani/Documents/Groww/groww-ui-automation/utils/Helpers/ApiHelper.ts:114:51)
        at /Users/palakjethwani/Documents/Groww/groww-ui-automation/test/profile.test.ts:74:29
        at TestTypeImpl._step (/Users/palakjethwani/Documents/Groww/groww-ui-automation/node_modules/@playwright/test/lib/testType.js:214:13)
        at Function.step (/Users/palakjethwani/Documents/Groww/groww-ui-automation/node_modules/@playwright/test/lib/transform.js:133:12)
        at /Users/palakjethwani/Documents/Groww/groww-ui-automation/test/profile.test.ts:73:20
        at WorkerRunner._runTestWithBeforeHooks (/Users/palakjethwani/Documents/Groww/groww-ui-automation/node_modules/@playwright/test/lib/workerRunner.js:478:7)
`
I will have to repeat this code again and again in every test function where as writing a utility is useful for me.
This is one problem.

**#2 :** Another problem is the api server host we are to provide in Test config for baseURL. Now since I am writing Web UI + API test (kind of ETE) and the hostname for ui server and api server is different then how do I manage that ? I want to be able to send complete url as argument in get/post method.

**Comment by dgozman** [comment] 2021-12-08 18:56
@Palak-Jethwani Could you please share the full test for the first issue? It says "request.get" is not a function, so something is messed up, but it's hard to say without looking at the code.

For the second issue, you can always pass complete urls to get/post:
```js
const response = await request.get('https://playwright.dev');
```

**Comment by dgozman** [comment] 2021-12-11 22:11
Closing because we cannot reproduce the issue. If you have a repro that we can run, please open a new bug.

**Closed by dgozman** 2021-12-11 22:11 UTC
Labels: triaging
