### ISSUE TITLE
[BUG] Test that passed on first retry  - defined as flaky and triggers failure of the whole test run

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#8849] opened 2021-09-10 21:21 UTC
**Context:**
- Playwright Version: 1.14.1
- Operating System: Windows
- Browser: Chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
import { PlaywrightTestConfig } from "@playwright/test";


const config: PlaywrightTestConfig = {
  retries: 1,
  timeout: 150000,
  globalTimeout: 3000000,
  reporter: [["./my-reporter.ts"], ["list"], ["junit", { outputFile: "reports/test-results.xml" }], ["allure-playwright"]],
  use: {
    browserName: 'chromium',
    trace: 'on',
    screenshot: 'on',
    viewport: {width: 1400, height: 900},
    video: {
      mode: "on-first-retry",
      size: {
        //UNIFY Recommended Resolution
        width: 1400,
        height: 900,
      }
    },
    contextOptions: {
      //viewport: {width: 1500, height: 1000},
    },
    // Browser options   
    launchOptions: {     
      channel: 'chrome', //Changed back to chromium due to the issue with chrome on CI
      headless: false,
      //args: ['--start-maximized']
    },
    //slowMo: 0,
  },
};

export default config;

```

**Describe the bug**

I run several tests in the test run.
I defined the **retry** parameter to 1. 
A particular test failed on the first run and finished with success on the retry. 
But the whole test run failed due to the 'flaky' definition of the test. 
As I understand - the successful retry should be an actual status of the test.
Am I wrong?

First run - failed.
![image](https://user-images.githubusercontent.com/52656401/132918667-939f1f1d-5fbc-4710-913a-182266095548.png)

Retry - finished successfully.
![image](https://user-images.githubusercontent.com/52656401/132918554-75e82da1-b195-4070-99f1-ff3026cbb442.png)

The whole run - failed.
![image](https://user-images.githubusercontent.com/52656401/132918425-fef8b00f-7f7f-4611-830a-b8ad4b66b6ba.png)

**Comment by pavelfeldman** [comment] 2021-09-11 05:08
> The whole run - failed.

Why do you think it failed? It passed with the process exit code 0 (=passed). You don't like that 1 flaky is printed in red?

**Comment by AlexKomanov** [comment] 2021-09-11 07:21
@pavelfeldman 
I run it on the CI - and it triggers the job to be failed.
Here the output:

 1 flaky
      tests\unify\crm\CrmPayment.spec.ts:36:5 › Crm payments tests CRM - Paying for paid and unpaid tickets AUT-868 
    7 passed (7m)
  Generating Allure Report
  Report successfully generated to reports\allure-report
C:\builds\zvjXhYj3\0\sro\sro4\Core\__build\Scripts\SRO.4000.core.integration.xml(317,3): error MSB3073: The command "powershell -File C:\builds\zvjXhYj3\0\sro\sro4\Core\__Build\Scripts\playwright-compile-run-tests.ps1" exited with code -1.
Done Building Project "C:\builds\zvjXhYj3\0\sro\sro4\Core\__build\Scripts\SRO.4000.core.integration.xml" (UIPlaywrightTest target(s)) -- FAILED.
Project Evaluation Performance Summary:
       44 ms  C:\builds\zvjXhYj3\0\sro\sro4\Core\__build\Scripts\SRO.4000.core.integration.xml   1 calls
Project Performance Summary:
    1017782 ms  C:\builds\zvjXhYj3\0\sro\sro4\Core\__build\Scripts\SRO.4000.core.integration.xml   1 calls
              1017782 ms  UIPlaywrightTest                           1 calls
Target Performance Summary:
        0 ms  GetDwhDatabaseName                         1 calls
        0 ms  GetDwhStagingEmptyDatabaseName             1 calls
        0 ms  GetDwhEmptyDatabaseName                    1 calls
        0 ms  GetDwhEtlTempDatabaseName                  1 calls
        0 ms  GetDwhStagingDatabaseName                  1 calls
        1 ms  GetDwhEtlTempSqlScriptProjectFilesEmptyDb   1 calls
        1 ms  GetDwhEtlTempExternalParameters            1 calls
       23 ms  CompileEtlTempNewEmptyDatabaseInstaller    1 calls
       35 ms  ReadSroVersions                            1 calls
       37 ms  ValidateConfiguration                      1 calls
       43 ms  DisplayParameters                          1 calls
       53 ms  CopyProjectSpecificConfigurations          1 calls
      151 ms  TestAccessToSystemDatabase                 1 calls
      563 ms  FindSqlScriptProjectFiles                  1 calls
     1093 ms  CompileNewDatabaseInstaller                1 calls
     2354 ms  BuildSystemTestDatabaseForDwhEtlTempDoNotGetData   1 calls
    17994 ms  UITestSQLAfterRestoreExe                   1 calls
    20632 ms  BuildUnitTestDatabase                      1 calls
    60091 ms  InstallMsi                                 1 calls
    148171 ms  VerifyUninstall                            1 calls
    291928 ms  RunConfigurationWizardImpl                 1 calls
    492593 ms  RunAutomationPlaywrightTests               1 calls
Task Performance Summary:
        0 ms  CreateProperty                             2 calls
       15 ms  Time                                       1 calls
       34 ms  XmlRead                                    7 calls
       41 ms  Copy                                       1 calls
       57 ms  Message                                  142 calls
      120 ms  TestDatabaseAccessibility                  1 calls
      586 ms  CreateItem                                27 calls
     1043 ms  CompileDbUpgradeFromSqlProj                2 calls
    17996 ms  CallTarget                                 2 calls
    20532 ms  InstallDbUpgrade                           2 calls
    53194 ms  RestoreDatabase                            7 calls
    942038 ms  Exec                                      17 calls
Build FAILED.
"C:\builds\zvjXhYj3\0\sro\sro4\Core\__build\Scripts\SRO.4000.core.integration.xml" (UIPlaywrightTest target) (1) ->
(VerifyUninstall target) -> 
  EXEC : warning : The process "Toptix.Foundation.Host.exe" not found. [C:\builds\zvjXhYj3\0\sro\sro4\Core\__build\Scripts\SRO.4000.core.integration.xml]
  C:\builds\zvjXhYj3\0\sro\sro4\Core\__build\Scripts\ci-system-test.targets(302,3): warning MSB3073: The command "Taskkill /IM Toptix.Foundation.Host.exe /F" exited with code 128. [C:\builds\zvjXhYj3\0\sro\sro4\Core\__build\Scripts\SRO.4000.core.integration.xml]
  C:\builds\zvjXhYj3\0\sro\sro4\Core\__build\Scripts\ci-system-test.targets(302,3): warning MSB4181: The "Exec" task returned false but did not log an error. [C:\builds\zvjXhYj3\0\sro\sro4\Core\__build\Scripts\SRO.4000.core.integration.xml]
"C:\builds\zvjXhYj3\0\sro\sro4\Core\__build\Scripts\SRO.4000.core.integration.xml" (UIPlaywrightTest target) (1) ->
(RunConfigurationWizardImpl target) -> 
  C:\builds\zvjXhYj3\0\sro\sro4\Core\__build\Scripts\ci-system-test.targets(447,3): warning MSB3073: The command " NET STOP SROCore4000_AppServer_1" exited with code 2. [C:\builds\zvjXhYj3\0\sro\sro4\Core\__build\Scripts\SRO.4000.core.integration.xml]
  C:\builds\zvjXhYj3\0\sro\sro4\Core\__build\Scripts\ci-system-test.targets(447,3): warning MSB4181: The "Exec" task returned false but did not log an error. [C:\builds\zvjXhYj3\0\sro\sro4\Core\__build\Scripts\SRO.4000.core.integration.xml]
"C:\builds\zvjXhYj3\0\sro\sro4\Core\__build\Scripts\SRO.4000.core.integration.xml" (UIPlaywrightTest target) (1) ->
(RunAutomationPlaywrightTests target) -> 
  EXEC : Internal error : step end without step begin: pw:api@page.waitForTimeout@7442021-09-10 20:55:13.629  ERROR [myLogger common\BasePage.ts:39  SalesPage.clickElement] Click on [aria-label="Return to CRM"] failed [C:\builds\zvjXhYj3\0\sro\sro4\Core\__build\Scripts\SRO.4000.core.integration.xml]
  C:\builds\zvjXhYj3\0\sro\sro4\Core\__build\Scripts\SRO.4000.core.integration.xml(317,3): error MSB3073: The command "powershell -File C:\builds\zvjXhYj3\0\sro\sro4\Core\__Build\Scripts\playwright-compile-run-tests.ps1" exited with code -1.
    5 Warning(s)
    2 Error(s)
Time Elapsed 00:16:57.86
Uploading artifacts for failed job
01:03
Version:      13.10.0
Git revision: 54944146
Git branch:   13-10-stable
GO version:   go1.13.8
Built:        2021-03-21T09:13:23+0000
OS/Arch:      windows/amd64
Uploading artifacts...
Runtime platform                                    arch=amd64 os=windows pid=1656 revision=54944146 version=13.10.0
Core\__artifacts\logs\: found 6 matching files and directories 
uiAutomation\PlaywrightTest\reports: found 864 matching files and directories 
uiAutomation\PlaywrightTest\test-results: found 29 matching files and directories 
Uploading artifacts as "archive" to coordinator... ok  id=1139032 responseStatus=201 Created token=Nn93t81r
Version:      13.10.0
Git revision: 54944146
Git branch:   13-10-stable
GO version:   go1.13.8
Built:        2021-03-21T09:13:23+0000
OS/Arch:      windows/amd64
Uploading artifacts...
Runtime platform                                    arch=amd64 os=windows pid=5396 revision=54944146 version=13.10.0
uiAutomation\PlaywrightTest\reports\test-results.xml: found 1 matching files and directories 
Uploading artifacts as "junit" to coordinator... ok  id=1139032 responseStatus=201 Created token=Nn93t81r
Cleaning up file based variables
00:00
**ERROR: Job failed: exit status 1**

The job runs perfectly if all the tests are marked as passed.

**Comment by AlexKomanov** [comment] 2021-09-11 07:27
@pavel
Here is the output from the local run:

![image](https://user-images.githubusercontent.com/52656401/132940133-c2b9d11e-22a9-4024-9db6-15316e9204a8.png)

So maybe I can suggest adding some annotation in order to include "passed flaky" tests in counter of all passed tests? And second - the red color of the flaky tests is very confusing.

**Comment by dgozman** [comment] 2021-09-13 22:29
My guess would be: this line somehow causes trouble.
```log
EXEC : Internal error : step end without step begin: pw:api@page.waitForTimeout@7442021-09-10 20:55:13.629  ERROR [myLogger common\BasePage.ts:39  SalesPage.clickElement] Click on [aria-label="Return to CRM"] failed [C:\builds\zvjXhYj3\0\sro\sro4\Core\__build\Scripts\SRO.4000.core.integration.xml]
```
Perhaps this is printed to stderr and your CI does not like non-empty stderr? I don't think we should change the output for everyone before confirming that the issue is with the "flaky" word somewhere.

Printing flaky as yellow makes sense!

**Comment by AlexKomanov** [comment] 2021-09-15 05:14
@dgozman 
I'll check from my side about our CI parsing and error.
Thanks for making sense of the color.

**Comment by dgozman** [comment] 2021-09-22 14:48
@AlexKomanov Were you able to figure out the problem? Let me know if there is something else we can do here.

**Comment by nickhodaly** [comment] 2021-09-22 23:57
@dgozman I believe we might be experiencing something similar. We have tracing enabled as well in our CI runs. My hunch was that perhaps an exception is being thrown somewhere in one of the built in fixtures after a test completes (maybe related saving traces?). I tested out this theory by throwing an exception an `afterAll()` hook and it has a similar effect in that all the tests pass but we still exit with code 1. 

Looking at one of our CI logs where this same issue occurred, the only thing I see logged that is out of the ordinary is 
```
Internal error: step end without step begin: pw:api@browserContext.close@124Internal error: step end without step begin: hook@After Hooks@123
```

Could there be some missing error handling somewhere? Will look around some more but just wanted to provide whatever information we had atm.

**Comment by dgozman** [comment] 2021-09-23 00:15
@nickhodaly Thank you, we'll be grateful for any reliable repro or information on this topic.

> I tested out a basic version of this theory by throwing an exception in an `afterAll()` hook and it has a similar effect in that all the tests pass but we still exit with code 1.

Do you get the error message in the terminal? In theory, any such error should be reported to the terminal before finishing with exit code 1. Can you try printing the exit code to confirm this?
```bash
npx playwright test && echo $?
```

**Comment by nickhodaly** [comment] 2021-09-23 00:26
@dgozman Aside from the console out that comes from the `list` reporter, the only other thing that was unusual was the `Internal error` log I pasted in my previous comment. 

Here is the rest of the output from our CI run where this issue occurred. You can see, no failed tests (just a couple flaky). But still `exit code 1`.
```
  Slow test: [Desktop - Safari] › xxx/pages/yyy/test.ui.ts (2m)                                                                                                                                                      
  Slow test: [Desktop - Chromium] › xxx/pages/yyy/test.ui.ts (2m)                                                                                                                                                    
  Slow test: [Desktop - Chromium] › xxx/pages/yyy/test.ui.ts (2m)                                                                                                                                                   
  Slow test: [Desktop - Safari] › xxx/pages/yyy/xxx.test.ui.ts (2m)                                                                                                                                                
  Slow test: [Desktop - Safari] › xxx/pages/yyy/test.ui.ts (2m)                                                                                                                                                     
                                                                                                                                                                                                                                 
  2 flaky                                                                                                                                                                                                                        
    [Desktop - Chromium] › xxx/pages/xxx/test.ui.ts:64:3 › xxx -  zzzzzzzz                                                                                                             
    [Desktop - Chromium] › xxx/pages/xxx/test.ui.ts:79:3 › xxx -  zzzzzz                                                      
  272 skipped                                                                                                                                                                                                                    
  644 passed (8m)                                                                                                                                                                                                                
error Command failed with exit code 1.                                                                                                                                                                                           
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Barruchou** [comment] 2022-01-20 09:02
Hi,

Same for us, as soon as there are "flaky" the exit code is 1

![image](https://user-images.githubusercontent.com/38187278/150306735-c08345f3-9730-4365-a614-ef8010944fb9.png)

**Comment by Barruchou** [comment] 2022-01-20 09:12
Hi,

Same for us, as soon as there are "flaky" the exit code is 1

```
8 flaky
    foo.test.js:71:13 › xxx/ (xxx) › 'xxx' › xxx
    foo.test.js:55:11 › xxx/ (xxx) › 'xxx' › xxx
    foo.test.js:107:13 › xxx/ (xxx) › 'xxx' › xxx
    foo.test.js:71:13 › xxx/ (xxx) › 'xxx' › xxx
    foo.test.js:71:13 › xxx/ (xxx) › 'xxx' › xxx
    foo.test.js:71:13 › xxx/ (xxx) › 'xxx' › xxx 
    foo.test.js:64:9 › xxx/ (xxx) › 'xxx' › xxx 
    foo.test.js:28:7 › xxx/ (xxx) › 'xxx' › xxx
  272 passed (38m)
Makefile:378: recipe for target 'run-e2e-tests' failed
make: *** [run-e2e-tests] Error 1
```

**Comment by lschricke** [comment] 2022-01-25 15:43
Hello there, 
Does anyone has a come up with solution about this issue yet? 
Have a good day!

**Comment by D-3V** [comment] 2022-01-26 16:58
The same problem here!

**Comment by antpingelli** [comment] 2022-01-31 19:43
I am also seeing this problem, but I have not seen anyone else reference `Error: Did not teardown test scope` which I am seeing. Could this be leading to the unexpected error exit? Cleaned output below showing the test fail, then succeed on retry

```
✘  [test] › Test (10s)

Error: Did not teardown test scope

    at FixtureRunner.setPool (/prod/msp/build/slave1/workspace/node_modules/@playwright/test/lib/test/fixtures.js:256:37)
    at WorkerRunner._runTestOrAllHook (/prod/msp/build/slave1/workspace/node_modules/@playwright/test/lib/test/workerRunner.js:365:25)
    at WorkerRunner._runSuite (/prod/msp/build/slave1/workspace/node_modules/@playwright/test/lib/test/workerRunner.js:213:18)
    at WorkerRunner._runSuite (/prod/msp/build/slave1/workspace/node_modules/@playwright/test/lib/test/workerRunner.js:203:9)
    at WorkerRunner.run (/prod/msp/build/slave1/workspace/node_modules/@playwright/test/lib/test/workerRunner.js:157:9) 
    at process.<anonymous> (/prod/msp/build/slave1/workspace/node_modules/@playwright/test/lib/test/worker.js:94:5)

✓  [test] › Test (8s)

  1) [test] › Test

    Timeout of 10000ms exceeded.

  1 flaky

    [test] › Test

  27 passed (2m)

script returned exit code 1
```

**Comment by dgozman** [comment] 2022-01-31 19:46
@antpingelli This is an internal error - definitely a bug in the test runner. If you could share a repro, that would be wonderful!

**Comment by antpingelli** [comment] 2022-01-31 20:00
Unfortunately I cannot as this is on Github Enterprise: is there anything I can provide to help? I was wondering if #9872 would fix this but I need to work on getting a more recent version of Chromium on our Artifactory so we are on v1.15.

Either way I assume my situation is related to this issue since it continued to run and succeeded after but still reported an error, but if not I apologize for adding this here

**Comment by dgozman** [comment] 2022-01-31 20:14
> Unfortunately I cannot as this is on Github Enterprise: is there anything I can provide to help?

Since this is a very much internal issue, I doubt we can help without debugging locally with a repro. Sorry!

> I was wondering if #9872 would fix this ...

Most likely, because symptoms are similar. I hope you would be able to upgrade and the issue would disappear 😄

**Comment by nickhodaly** [comment] 2022-01-31 23:32
I believe the issue went away for us when we upgraded from v1.15.0 -> 1.16.3. @antpingelli can you try upgrading to >=1.16.3 and see if it helps?

**Comment by pavelfeldman** [comment] 2022-10-20 03:17
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Closed by pavelfeldman** 2022-10-20 03:17 UTC
Labels: P3-collecting-feedback, feature-test-runner
