### ISSUE TITLE
[Feature] Record WebSocket frames in HAR

### ISSUE THREAD

**Issue by baltiyskiy** [microsoft/playwright#17838] opened 2022-10-05 11:27 UTC
As suggested in https://github.com/microsoft/playwright/issues/6254, creating an issue to support recording sent and received WebSocket frames in the HAR.

**Comment by mxschmitt** [comment] 2022-10-12 19:51
Sounds like a duplicate of https://github.com/microsoft/playwright/issues/17848.

**Comment by yury-s** [comment] 2022-10-13 18:59
Folding into https://github.com/microsoft/playwright/issues/17848, please upvote that issue instead.

**Closed by yury-s** 2022-10-13 18:59 UTC
Labels: triaging
