### ISSUE TITLE
[BUG]install python -m playwright install on windows7 Python3.8.7, got this error message:(node:5848) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 13.107.24 6.13:443

### ISSUE THREAD

**Issue by langxmchip** [microsoft/playwright#4996] opened 2021-01-13 08:25 UTC
trying to install python -m playwright install on windows7 Python3.8.7, got this error message:
C:\Users\10034852>python -m playwright install
(node:5848) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 13.107.24
6.13:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
(node:5848) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 1)
(node:5848) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by yury-s** [comment] 2021-01-13 22:04
The installer downloads browsers from urls like `https://playwright.azureedge.net/builds/webkit/1420/webkit-win64.zip` can you check that your network firewall doesn't block such urls?

**Comment by langxmchip** [comment] 2021-01-14 02:32
> twork firewall doesn't



> The installer downloads browsers from urls like `https://playwright.azureedge.net/builds/webkit/1420/webkit-win64.zip` can you check that your network firewall doesn't block such urls?
I can download webkit-win64.zip using your urls. So network firewall should not block such urls.

**Comment by yury-s** [comment] 2021-01-14 02:47
13.107.246.13 is a Microsoft Azure ip and it looks like playwright is having hard time connecting to it. Can you run the command with `DEBUG=pw:*` and attach the logs here?

**Comment by langxmchip** [comment] 2021-01-14 03:18
> 13.107.246.13 is a Microsoft Azure ip and it looks like playwright is having hard time connecting to it. Can you run the command with `DEBUG=pw:*` and attach the logs here?

C:\Users\10034852>set DEBUG=pw*

C:\Users\10034852>python -m playwright install
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'BrowserType',
  pw:channel:event     initializer: {
  pw:channel:event       executablePath: 'C:\\snapshot\\playwright-cli\\node_mod
ules\\playwright\\.local-browsers\\chromium-833159\\chrome-win\\chrome.exe',
  pw:channel:event       name: 'chromium'
  pw:channel:event     },
  pw:channel:event     guid: 'BrowserType@c782b929b35ec537706bd9677e2e5b61'
  pw:channel:event   }
  pw:channel:event } +0ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'BrowserType',
  pw:channel:event     initializer: {
  pw:channel:event       executablePath: 'C:\\snapshot\\playwright-cli\\node_mod
ules\\playwright\\.local-browsers\\firefox-1221\\firefox\\firefox.exe',
  pw:channel:event       name: 'firefox'
  pw:channel:event     },
  pw:channel:event     guid: 'BrowserType@7253eba22a15d1109c65accb472aa4e1'
  pw:channel:event   }
  pw:channel:event } +42ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'BrowserType',
  pw:channel:event     initializer: {
  pw:channel:event       executablePath: 'C:\\snapshot\\playwright-cli\\node_mod
ules\\playwright\\.local-browsers\\webkit-1402\\Playwright.exe',
  pw:channel:event       name: 'webkit'
  pw:channel:event     },
  pw:channel:event     guid: 'BrowserType@80289d21934ab6bd049294c456bd3ed6'
  pw:channel:event   }
  pw:channel:event } +32ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'Android',
  pw:channel:event     initializer: {},
  pw:channel:event     guid: 'Android@e6855a2b159a3f939aeed718814ac951'
  pw:channel:event   }
  pw:channel:event } +27ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'Electron',
  pw:channel:event     initializer: {},
  pw:channel:event     guid: 'Electron@e475296a7eae7ccdca696b44eff8bca2'
  pw:channel:event   }
  pw:channel:event } +19ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'Selectors',
  pw:channel:event     initializer: {},
  pw:channel:event     guid: 'Selectors@01d37fa89d8b0f7ba8cce567eaaf953c'
  pw:channel:event   }
  pw:channel:event } +19ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'Playwright',
  pw:channel:event     initializer: {
  pw:channel:event       chromium: [Object],
  pw:channel:event       firefox: [Object],
  pw:channel:event       webkit: [Object],
  pw:channel:event       android: [Object],
  pw:channel:event       electron: [Object],
  pw:channel:event       deviceDescriptors: [Array],
  pw:channel:event       selectors: [Object]
  pw:channel:event     },
  pw:channel:event     guid: 'Playwright'
  pw:channel:event   }
  pw:channel:event } +19ms
(node:5344) UnhandledPromiseRejectionWarning: Error: getaddrinfo EAI_AGAIN playw
right.azureedge.net
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
(node:5344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 1)
(node:5344) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by pavelfeldman** [comment] 2021-01-22 19:01
Yeah, looks like azure playwright.azureedge.net is not accessible from where you are :/

**Comment by aslushnikov** [comment] 2021-01-27 17:30
Closing since I don't think this is actionable on our side.

**Closed** 2021-01-27 17:33 UTC
Labels: triaging

**Comment by DJ-Glock** [comment] 2021-03-31 16:05
Hey guys.
I know the issue is closed, but probably it will help someone.

We faced similar issue. And the root cause was in proxy that was not set in environment variables.
We have a corporate proxy that is set on system level, also it was set in yarn-config. But it looks like PW uses envrionment variables HTTP_PROXY and HTTPS_PROXY to download browser.

So once proxy variables were set - everything became fine.
![image](https://user-images.githubusercontent.com/26511191/113175334-fbd65280-9253-11eb-97a3-db650a898ba4.png)

**Comment by jonathanpmartins** [comment] 2021-11-02 17:21
> Yeah, looks like azure playwright.azureedge.net is not accessible from where you are :/

I'm having this issue now and only a VPN connection solved the problem. So, to install a NPM package I need a VPN? What is going on?

I had problems only with the chrome part. Take a look: https://github.com/microsoft/playwright/issues/5442. But now the problem happens with playwright too.
