### ISSUE TITLE
[Feature] Add possiblity to have apiPort in playwright.config

### ISSUE THREAD

**Issue by deonxxx** [microsoft/playwright#23871] opened 2023-06-23 08:20 UTC
Hi, I would like to have an option to be able to add an apiPort, same as baseUrl to playwright.config what could possibly improve the way I can manage the projects - also helping to handle api testing.

**Comment by dgozman** [comment] 2023-06-24 21:27
Duplicate of #23738.

**Closed by dgozman** 2023-06-24 21:27 UTC
