### ISSUE TITLE
[Feature] soft assertion for playwright assertion 'toBe()'

### ISSUE THREAD

**Issue by HerryGu** [microsoft/playwright#26638] opened 2023-08-23 06:37 UTC
It looks like soft assertion doesn't work for playwright assertion 'toBe()'
Following the document (https://playwright.dev/docs/test-assertions), raise a soft assertion as below:
`expect.soft(ER).toBe('Y')`

However, the playwright still terminated test execution after executing the above code line.
May I know if this feature is only applicable for locator assertion?   If it is possible to extend the feature to apply on  all playwright assertions?

**Comment by yury-s** [comment] 2023-08-23 17:57
Soft assertions work for non-locator assertions too. I cannot reproduce the problem with this project https://github.com/yury-s/bug-26638. Please follow the bug template and provide full steps including a self-contained repro if you deem there is a bug in playwright.

**Comment by yury-s** [comment] 2023-08-28 15:59
Closing per the response above, feel free to open a new issue if it doesn't work.

**Closed by yury-s** 2023-08-28 15:59 UTC
Labels: triaging
