### ISSUE TITLE
[Question] How i can use external package with playwright ?

### ISSUE THREAD

**Issue by Amrkamel1** [microsoft/playwright#7017] opened 2021-06-10 14:02 UTC
I'm trying to use  mysql2 package with playwright with mocha, DB method in the it blocks is passing normally when I'm running only dataBase test , but when I combine playwright tests with DB tests, the DB tests are failing, do i need to use any kind of call back when I'm using external packages.

done below is an example : 

let user_id;

describe('Demo playwright', () => {

    before(async () => {
        await DB.main()  // initiated the DB pool connection 
        await baseSetup.navigateTo('/test/login')
    })

    after(async () => {
        await baseSetup.terminate()
    })

    it('05-1. should get an error when no email is provided', async () => {   // will pass
        const p = new Login(await baseSetup.page());
        await p.forgetPasswordOfInvalid('')
        expect(await p.expectEleToHaveText(p.emailError)).equal('The email you have entered does not exist in our system')
    });

    context('06. DB integration', () => {

        it('01. Get username from DB and login with id', async () => {     // will fail due to timeout 
            const output = await DB.submitDBQuery('select * from test.sb__user where id=1')
            const username = output[0].username;
            console.log(username)
            const p = new Login(await baseSetup.page());
            await p.loginWith(username, 'test')
        });

    })

    after(async () => {
        await DB.deleteUserRecord(user_id);
    });

    })

-----------------------------------------------------
if I execute only the DB test it will pass 

        it.only('01. Get username from DB and login with id', async () => {     // will pass successfully 
            const output = await DB.submitDBQuery('select * from test.sb__user where id=1')
            const username = output[0].username;
            console.log(username)
            const p = new Login(await baseSetup.page());
            await p.loginWith(username, 'test')
        });
        
-----------------------------------------------------------
       
example of the DB methods 
       
       let pool;

    class DB {
        sshClient = new Client();
        dbServer = D.dbServer
        tunnelConfig = D.tunnelConfig
        forwardConfig = D.forwardConfig

    async main() {
        new Promise((_resolve, reject) => {
            this.sshClient.on('ready', async () => {
                this.sshClient.forwardOut(
                    this.forwardConfig.srcHost,
                    this.forwardConfig.srcPort,
                    this.forwardConfig.dstHost,
                    this.forwardConfig.dstPort,
                    (err, stream) => {
                        if (err) reject(err);
                        // create a new DB server object including stream
                        const updatedDbServer = {
                            ...this.dbServer,
                            stream
                        }; // connect to mysql
                        pool = mysql.createPool(updatedDbServer);
                    });
            }).connect(this.tunnelConfig);
            console.log('%c ====> Connected to test DB <====', 'background: #222; color: #008000');
        });
    }

       async submitDBQuery(query) {
            const outPut = await pool.query(query);
            const results = JSON.parse(JSON.stringify(outPut));
            return results[0];
    }
}
       
        -------------------------------------------------------

**Comment by Amrkamel1** [comment] 2021-06-10 14:42
the screenshots below will explain the behaviour as well, first screenshot when I have multiple it blocks for playwright and last one failed for DB 
![image](https://user-images.githubusercontent.com/32042806/121545115-841e6400-ca0a-11eb-8463-36b05747b58a.png)

2nd screenshot show DB test passed when I disable all other playwright it blocks 
![image](https://user-images.githubusercontent.com/32042806/121545444-d495c180-ca0a-11eb-9d9a-9c56ba850258.png)

**Comment by pavelfeldman** [comment] 2021-06-10 23:42
Sorry, it is hard to help w/o ability to reproduce the issue. Could you try reducing the issue to a snippet that you could share?

**Comment by Amrkamel1** [comment] 2021-06-11 15:01
> Sorry, it is hard to help w/o ability to reproduce the issue. Could you try reducing the issue to a snippet that you could share? 

I will try to make a demo repo so you can reproduce the issue, but u would still need any access to DB through ssh tunnelling so you can reproduce the exact scenario.

I will let you know what exact parameter you should pass once i get it done.

**Comment by Amrkamel1** [comment] 2021-06-11 18:40
@pavelfeldman 
here you are 
https://github.com/Amrkamel1/demp.git

just note, that you will have to add here the relevant values  for your ssh remote server and for your DB 
![image](https://user-images.githubusercontent.com/32042806/121734193-be643000-caf4-11eb-9d34-57a60abfea8a.png)

two scenarios that you can try :
1- enable all it block  ( DB integration context will fail)
2- enable only DB it block it will pass

**Comment by pavelfeldman** [comment] 2021-06-15 17:34
Sorry, since I don't see any mentions of Playwright in any of the code above, I am not sure we can address it. Playwright is a library that you use in Node. It is a library, so you can use it along with other Node libraries, there is nothing special about Playwright that would make it stand out.

If you believe your problem is Playwright-related, could you file a bug with the short snippet that uses Playwright and showcases a problem? I have to close this bug as not-actionable.

**Closed by pavelfeldman** 2021-06-15 17:34 UTC
Labels: triaging
