### ISSUE TITLE
[Question] Chaining Locators instead of filter?

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#26540] opened 2023-08-18 12:50 UTC
So I haven't seen anywhere saying you cannot do this, but no-where in the documentation (that I saw) mentions if something like:
`await page.locator('input[type=checkbox]:nth-child(2)').getByLabel('Enable');` or similar is "valid" code.

It doesn't throw an error, but I know the `filter` method exists. Im just curious if this does the same thing. (Sort of how jquery uses `.find()`)

Thanks.

**Comment by mxschmitt** [comment] 2023-08-18 15:59
Yes its absolutely valid code. Locator.filter is for use-cases where you want to pass a full Locator into the filtering or where you want utility methods like negation, see here: https://playwright.dev/docs/api/class-locator#locator-filter

(jQuery has nothing to do with Playwright)

**Comment by yury-s** [comment] 2023-08-22 01:03
Closing per the response above, feel free to open a new issue if it doesn't work.

**Closed** 2023-08-22 01:02 UTC
Labels: triaging

**Comment by msmith1114** [comment] 2023-08-24 14:17
Does chaining locators act like a "within" scope I assume? (IE: Will everything after the first locator be filtered down to the children of that initial locator?)

**Comment by mxschmitt** [comment] 2023-08-24 14:46
Yes that's what it is about. Child elements in the DOM.

**Comment by maksnester** [comment] 2024-07-10 16:40
I ran into an issue when my locator that was written this way was selecting a different input on the page instead of the one that I selected with `.getByTestId` here

```ts
this.page
      .getByTestId('some-wrapper-over-input')
      // this finds any text box on the page, NOT withing the found wrapper
      .getByRole('textbox') 
      .fill('blah');
```

So I had to replace it with 

```ts
    await this.page
      .locator('[data-testid="some-wrapper-over-input"] input')
      .fill('blah');
```

Is it a bug or chained locators do not actually run within the previously found element?

**Comment by Snaptonis** [comment] 2024-12-09 13:46
Any update? I ran into this issue today trying to locate a button inside a dialog but another button outside of the dialog was found too.
Tried it like this: `page.getByRole("dialog").getByRole("button", {name: "x"}).`

Doing it like in the example in the [docs](https://playwright.dev/docs/locators#matching-inside-a-locator) 
`const saveButton = page.getByRole('button', { name: 'Save' });
// ...
const dialog = page.getByTestId('settings-dialog');
await dialog.locator(saveButton).click();`
doenst work either

**Comment by aleksijohansson** [comment] 2025-03-14 09:37
> I ran into an issue when my locator that was written this way was selecting a different input on the page instead of the one that I selected with `.getByTestId` here
> 
> this.page
>       .getByTestId('some-wrapper-over-input')
>       // this finds any text box on the page, NOT withing the found wrapper
>       .getByRole('textbox') 
>       .fill('blah');
> So I had to replace it with
> 
>     await this.page
>       .locator('[data-testid="some-wrapper-over-input"] input')
>       .fill('blah');
> Is it a bug or chained locators do not actually run within the previously found element?

I came across this issue as well. Any updates on this?

**Comment by aleksijohansson** [comment] 2025-03-14 09:45
For me the issue is specifically that `.first()` doesn't work in the middle of chaining like this:

```
this.page
      .getByTestId('some-wrapper-over-input')
      .first()
      // this finds all text boxes inside wrappers, not inside the first wrapper
      .getByRole('textbox') 
      .fill('blah');
```
