### ISSUE TITLE
[BUG] Launching Chromium on Windows complains about missing libraries

### ISSUE THREAD

**Issue by fawazahmed0** [microsoft/playwright#3496] opened 2020-08-17 00:42 UTC
**Context:**
- Playwright Version: 1.3.0
- Operating System: Windows 7
- Node.js version: 12.18
- Browser:Chromium

**Code Snippet**

```javascript
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();


  await browser.close();
})();
```

**Describe the bug**
Chromium doesn't work, but other browsers seems to work fine

**Console Output:**
```bash
G:\GitHub\quran-api>set "DEBUG=pw:api" && node dircheck.js
(node:16052) UnhandledPromiseRejectionWarning: Error: browserType.launch: Host s
ystem is missing dependencies!

Full list of missing libraries:
    api-ms-win-core-winrt-error-l1-1-0.dll

Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs
.
    at validateDependenciesWindows (G:\GitHub\quran-api\node_modules\playwright\
lib\server\validateDependencies.js:78:11)
    at async validateDependencies (G:\GitHub\quran-api\node_modules\playwright\l
ib\server\validateDependencies.js:47:16)
    at async Object.validateHostRequirements (G:\GitHub\quran-api\node_modules\p
laywright\lib\server\validateDependencies.js:34:5)
    at async Chromium._launchServer (G:\GitHub\quran-api\node_modules\playwright
\lib\server\browserType.js:154:13)
    at async Chromium._innerLaunch (G:\GitHub\quran-api\node_modules\playwright\
lib\server\browserType.js:76:61)
    at async ProgressController.run (G:\GitHub\quran-api\node_modules\playwright
\lib\progress.js:75:28)
    at async Chromium.launch (G:\GitHub\quran-api\node_modules\playwright\lib\se
rver\browserType.js:62:25)
    at async G:\GitHub\quran-api\dircheck.js:4:19
(node:16052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). To termin
ate the node process on unhandled promise rejection, use the CLI flag `--unhandl
ed-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejecti
ons_mode). (rejection id: 1)
(node:16052) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.
```

**Comment by mxschmitt** [comment] 2020-08-17 03:31
Thanks for reporting! Seems like a duplicate of #3435.

**Comment by fawazahmed0** [comment] 2020-08-17 10:44
The problem is only reproducible for chromium, other browsers seems to work fine irrespective of where the script is located.

**Comment by pavelfeldman** [comment] 2020-08-18 15:38
@aslushnikov ^^

**Comment by aslushnikov** [comment] 2020-08-20 07:08
Hey @fawazahmed0 
What windows 7 do you run? I just tried on a freshly installed Ultimate and it worked just fine

![image](https://user-images.githubusercontent.com/746130/90727934-ec803700-e278-11ea-893d-4476b425b46c.png)

Also, can you please check if you can run launch Chromium manually? Chromium can be found at `%USER%\AppData\Local\ms-playwright\chromium-792539`

**Comment by fawazahmed0** [comment] 2020-08-20 17:01
@aslushnikov   mine OS is same as yours

    C:\Users\Nawaz>systeminfo
    
    Host Name:                 NAWAZ-PC
    OS Name:                   Microsoft Windows 7 Ultimate
    OS Version:                6.1.7601 Service Pack 1 Build 7601
    OS Manufacturer:           Microsoft Corporation
    OS Configuration:          Standalone Workstation
    OS Build Type:             Multiprocessor Free

And yes I can launch chromium manually too
![-2020-aug-20-011](https://user-images.githubusercontent.com/20347013/90800743-af787b00-e332-11ea-8e8a-3a9264dd5617.jpg)

**Comment by aslushnikov** [comment] 2020-08-20 22:43
@fawazahmed0 interestingly, you say that Chromium doesn't work whereas other browsers launch for you just fine. In my setup, this is the opposite: none of the browsers launch except for chromium.

Did you install any additional libraries? Can you please point me to them?

**Comment by fawazahmed0** [comment] 2020-08-21 00:05
@aslushnikov nope, I did not explicitly installed any libraries, but I do have chrome, firefox and edge installed in my pc, it might be possible that they would be satisfying the library dependencies for playwright somehow.

Also you mentioned that you have freshly installed win7, you may want to install all the latest updates, maybe that might have the libraries required.

Do playwright store detailed debug logs somewhere? 

Here is the debug log of chromium when I launched it manually and it starts fine,  not sure if that will help:
[chromium log.txt](https://github.com/microsoft/playwright/files/5106022/chromium.log.txt)

**Comment by fawazahmed0** [comment] 2020-08-21 01:10
Opened chromium and firefox in dependency walker, seems like my system is missing some dlls, but it launches just fine without them, maybe disabling the dependency check in playwright might solve the problem for me:

![-2020-aug-21-012](https://user-images.githubusercontent.com/20347013/90840820-af02d300-e378-11ea-946a-78b100aae180.jpg)
![-2020-aug-21-013](https://user-images.githubusercontent.com/20347013/90840827-b32ef080-e378-11ea-8109-a477d44bb02e.jpg)

**Comment by OlgaKuksa** [comment] 2020-09-11 19:44
Faced the same issue with Chromium on old Windows Server 2008 R2 (yep, it's still used somewhere :) ). Downgrading from Playwright 1.4.0 to 1.2.0 solved the issue (actually, I already had 2 Teamcity configs running with Playwright 1.2.0 on the same machine and couldn't add a new one based on Playwright 1.4.0). Looks like you've broken smth between 1.2.0 (working) and 1.3.0 (broken), guys.

PS. Win10 Enterprise is fine with both 1.2.0 and 1.4.0.

**Comment by pavelfeldman** [comment] 2020-10-20 05:27
Is there an action item in this one? Trying to figure out if it is resovled.

**Comment by fawazahmed0** [comment] 2020-10-20 13:35
No not resolved yet, I just tested in v1.5.1

**Comment by egadsthefuzz** [comment] 2020-10-30 02:27
Just ran into this and the newest version that worked was 1.2.1. As others in the thread have said, same everything installed, same dependency walker on latest version. 
Here is the dependency walker for the version that works
![image](https://user-images.githubusercontent.com/17876873/97652661-07f69200-1ab3-11eb-8966-e6dd74faf730.png)

**Closed** 2020-12-15 00:40 UTC
Labels: P3-collecting-feedback

**Comment by aslushnikov** [comment] 2020-12-15 16:01
@fawazahmed0 can you please try now with `npm install playwright@next`?

**Comment by fawazahmed0** [comment] 2020-12-16 07:42
@aslushnikov yeah, chromium is working fine in v1.7, just tested now
![-2020-dec-16-115](https://user-images.githubusercontent.com/20347013/102319046-52b76500-3fa0-11eb-8419-43107ed19226.jpg)


Thanks

**Comment by OlgaKuksa** [comment] 2020-12-16 21:21
@aslushnikov just upgraded to 1.7.0 and ran tests on ancient Windows Server 2008 R2. It works now, thank you! 👍
