### ISSUE TITLE
[BUG] Error: Failed to install msedge in playwright docker image

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#13724] opened 2022-04-25 09:12 UTC
**Context:**
- Playwright Version: 1.22.1
- Operating System: Mac M1
- Node.js version: 14.6
- Browser: EDGE

**Code Snippet**

```
FROM mcr.microsoft.com/playwright
COPY . /MPRE-PW 
RUN chmod a+x ./E-PW/execute_test.sh
RUN apt update && apt install -y zip
RUN cd E-PW && npm ci
RUN npx playwright install msedge
CMD [ "/bin/bash" ]
```
Unable to install edge browser using playwright docker image

<img width="681" alt="Screenshot 2022-04-25 at 11 12 26" src="https://user-images.githubusercontent.com/32042806/165058470-f1063679-985d-40e6-8ebd-13e674e0ee83.png">

**Comment by mxschmitt** [comment] 2022-04-25 10:04
Microsoft Edge is not available for linux-arm64 yet, see [here](https://techcommunity.microsoft.com/t5/discussions/edge-for-linux-arm64/td-p/1532272).

You can build your Docker image with `--platform linux/amd64` as a workaround.

**Comment by amrsa1** [comment] 2022-04-25 10:43
@mxschmitt thanks now its installed, but actually all test are failing 

<img width="1294" alt="Screenshot 2022-04-25 at 12 42 33" src="https://user-images.githubusercontent.com/32042806/165074013-fe8f6153-f8ab-4875-b421-aec0ebc8bb85.png">

**Comment by markov00** [comment] 2022-04-28 15:37
We have a similar issue when we need to run playwright (in our case Chrome, not edge) from an M1 machine with the `--platform linux/amd64` flag.
The logs are similar, always `failed to connect to the bus` and the GPU process crash.
I've tried with various chromium args with no success: `--single-process`, different values for `--use-gl`, `--no-zygote`
We are using `playwright` `1.21.1`
<details>
<summary>Logs</summary>

```
==================== Browser output: ====================
    <launching> /ms-playwright/chromium-1000/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-vCXupi --remote-debugging-pipe --no-startup-window
    <launched> pid=2158
    [pid=2158][err] [0428/153101.435628:ERROR:stack_trace_posix.cc(707)] Failed to parse the contents of /proc/self/maps
    [pid=2158][err] [0428/153101.673983:ERROR:stack_trace_posix.cc(707)] Failed to parse the contents of /proc/self/maps
    [pid=2158][err] [0428/153101.678810:ERROR:stack_trace_posix.cc(707)] Failed to parse the contents of /proc/self/maps
    [pid=2158][err] [0428/153101.700642:FATAL:zygote_main_linux.cc(161)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded(). 
    [pid=2158][err] #0 0x004006fe3d79 <unknown>
    [pid=2158][err] #1 0x004006f487e3 <unknown>
    [pid=2158][err] #2 0x004006f5b5b0 <unknown>
    [pid=2158][err] #3 0x004006f5c15e <unknown>
    [pid=2158][err] #4 0x004006af57b6 <unknown>
    [pid=2158][err] #5 0x004006af0750 <unknown>
    [pid=2158][err] #6 0x004006af1379 <unknown>
    [pid=2158][err] #7 0x004006af200b <unknown>
    [pid=2158][err] #8 0x004006aef444 <unknown>
    [pid=2158][err] #9 0x004006aefd5e <unknown>
    [pid=2158][err] #10 0x004006b4b55a <unknown>
    [pid=2158][err] #11 0x004006b4b413 <unknown>
    [pid=2158][err] #12 0x004006b4a055 <unknown>
    [pid=2158][err] #13 0x0040035a23e8 <unknown>
    [pid=2158][err] #14 0x00400f4ef0b3 <unknown>
    [pid=2158][err] #15 0x0040035a222a <unknown>
    [pid=2158][err] 
    [pid=2158][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
    [pid=2158][err] [0428/153101.706209:FATAL:zygote_main_linux.cc(161)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded(). 
    [pid=2158][err] #0 0x004006fe3d79 <unknown>
    [pid=2158][err] #1 0x004006f487e3 <unknown>
    [pid=2158][err] #2 0x004006f5b5b0 <unknown>
    [pid=2158][err] #3 0x004006f5c15e <unknown>
    [pid=2158][err] #4 0x004006af57b6 <unknown>
    [pid=2158][err] #5 0x004006af0750 <unknown>
    [pid=2158][err] #6 0x004006af1379 <unknown>
    [pid=2158][err] #7 0x004006af200b <unknown>
    [pid=2158][err] #8 0x004006aef444 <unknown>
    [pid=2158][err] #9 0x004006aefd5e <unknown>
    [pid=2158][err] #10 0x004006b4b55a <unknown>
    [pid=2158][err] #11 0x004006b4b413 <unknown>
    [pid=2158][err] #12 0x004006b4a055 <unknown>
    [pid=2158][err] #13 0x0040035a23e8 <unknown>
    [pid=2158][err] #14 0x00400f4ef0b3 <unknown>
    [pid=2158][err] #15 0x0040035a222a <unknown>
    [pid=2158][err] 
    [pid=2158][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
    [pid=2158][err] [0428/153102.824766:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
    [pid=2158][err] [0428/153102.828942:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
    [pid=2158][err] [0428/153102.834013:ERROR:file_path_watcher_linux.cc(321)] inotify_init() failed: Function not implemented (38)
    [pid=2158][err] [0428/153102.963264:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
    [pid=2158][err] [0428/153102.968543:ERROR:gpu_process_host.cc(968)] GPU process launch failed: error_code=1002
    [pid=2158][err] [0428/153102.969546:WARNING:gpu_process_host.cc(1279)] The GPU process has crashed 1 time(s)
    [pid=2158][err] [0428/153103.004154:ERROR:gpu_process_host.cc(968)] GPU process launch failed: error_code=1002
    [pid=2158][err] [0428/153103.004257:WARNING:gpu_process_host.cc(1279)] The GPU process has crashed 2 time(s)
    [pid=2158][err] [0428/153103.020524:ERROR:gpu_process_host.cc(968)] GPU process launch failed: error_code=1002
    [pid=2158][err] [0428/153103.020610:WARNING:gpu_process_host.cc(1279)] The GPU process has crashed 3 time(s)
    [pid=2158][err] [0428/153103.028352:ERROR:gpu_process_host.cc(968)] GPU process launch failed: error_code=1002
    [pid=2158][err] [0428/153103.028414:WARNING:gpu_process_host.cc(1279)] The GPU process has crashed 4 time(s)
    [pid=2158][err] [0428/153103.039110:ERROR:gpu_process_host.cc(968)] GPU process launch failed: error_code=1002
    [pid=2158][err] [0428/153103.039230:WARNING:gpu_process_host.cc(1279)] The GPU process has crashed 5 time(s)
    [pid=2158][err] [0428/153103.044364:ERROR:gpu_process_host.cc(968)] GPU process launch failed: error_code=1002
    [pid=2158][err] [0428/153103.044497:WARNING:gpu_process_host.cc(1279)] The GPU process has crashed 6 time(s)
    [pid=2158][err] [0428/153103.051371:ERROR:gpu_process_host.cc(968)] GPU process launch failed: error_code=1002
    [pid=2158][err] [0428/153103.051511:WARNING:gpu_process_host.cc(1279)] The GPU process has crashed 7 time(s)
    [pid=2158][err] [0428/153103.054819:ERROR:gpu_process_host.cc(968)] GPU process launch failed: error_code=1002
    [pid=2158][err] [0428/153103.054875:WARNING:gpu_process_host.cc(1279)] The GPU process has crashed 8 time(s)
    [pid=2158][err] [0428/153103.058323:ERROR:gpu_process_host.cc(968)] GPU process launch failed: error_code=1002
    [pid=2158][err] [0428/153103.058373:WARNING:gpu_process_host.cc(1279)] The GPU process has crashed 9 time(s)
    [pid=2158][err] [0428/153103.058539:FATAL:gpu_data_manager_impl_private.cc(447)] GPU process isn't usable. Goodbye.
    [pid=2158][err] #0 0x004006fe3d79 <unknown>
    [pid=2158][err] #1 0x004006f487e3 <unknown>
    [pid=2158][err] #2 0x004006f5b5b0 <unknown>
    [pid=2158][err] #3 0x004004b0ff97 <unknown>
    [pid=2158][err] #4 0x004004b0d67e <unknown>
    [pid=2158][err] #5 0x004004b0c583 <unknown>
    [pid=2158][err] #6 0x004004b170b0 <unknown>
    [pid=2158][err] #7 0x004004b182d4 <unknown>
    [pid=2158][err] #8 0x004004990261 <unknown>
    [pid=2158][err] #9 0x0040049eaa75 <unknown>
    [pid=2158][err] #10 0x0040049eac95 <unknown>
    [pid=2158][err] #11 0x004006fa1fb0 <unknown>
    [pid=2158][err] #12 0x004006fb5ed9 <unknown>
    [pid=2158][err] #13 0x004006fb5bfc <unknown>
    [pid=2158][err] #14 0x004006fb63d2 <unknown>
    [pid=2158][err] #15 0x004006f63f13 <unknown>
    [pid=2158][err] #16 0x004006fb663e <unknown>
    [pid=2158][err] #17 0x004006f82bdd <unknown>
    [pid=2158][err] #18 0x0040049a81ad <unknown>
    [pid=2158][err] #19 0x0040049a9a62 <unknown>
    [pid=2158][err] #20 0x00400c52933e <unknown>
    [pid=2158][err] #21 0x004006af0ff2 <unknown>
    [pid=2158][err] #22 0x004006af249f <unknown>
    [pid=2158][err] #23 0x004006af202f <unknown>
    [pid=2158][err] #24 0x004006aef444 <unknown>
    [pid=2158][err] #25 0x004006aefd5e <unknown>
    [pid=2158][err] #26 0x004006b4b55a <unknown>
    [pid=2158][err] #27 0x004006b4b265 <unknown>
    [pid=2158][err] #28 0x0040035a23e8 <unknown>
    [pid=2158][err] #29 0x00400f4ef0b3 <unknown>
    [pid=2158][err] #30 0x0040035a222a <unknown>
    [pid=2158][err] Task trace:
    [pid=2158][err] #0 0x0040049ea92c <unknown>
    [pid=2158][err] #1 0x0040049ea32a <unknown>
    [pid=2158][err] #2 0x00400733d416 <unknown>
    [pid=2158][err] #3 0x00400733d416 <unknown>
    [pid=2158][err] #4 0x00400733d416 <unknown>
    [pid=2158][err] Task trace buffer limit hit, update PendingTask::kTaskBacktraceLength to increase.
    [pid=2158][err] 
    [pid=2158][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
```
</details>

**Comment by markov00** [comment] 2022-04-29 10:34
I like to add the following to my previous comment: we are using the `--platform linux/amd64` flag on an M1 because we are looking to have exactly the same docker image running on both local and CI. We are running VRTs and we always used a `0` threshold when comparing images to baseline. We noticed that the `amd64` vs the `arm64` images produce slight differences caused by antialiasing so we prefer to have exactly the same platform in both environments

**Comment by SpawnAtis** [comment] 2022-06-21 18:45
@markov00 I have the same problem

**Comment by aslushnikov** [comment] 2022-08-25 16:42
I'll close this since MS Edge is not available on x86_64. We'll be happy to follow-up once MSEdge is available on arm linux!

**Closed by aslushnikov** 2022-08-25 16:42 UTC
Labels: P3-collecting-feedback
