### ISSUE TITLE
[Bug]:  Sharding with projects grep not working as anticipated

### ISSUE THREAD

**Issue by costa-collibra** [microsoft/playwright#29638] opened 2024-02-23 18:33 UTC
### Version

1.41.1

### Steps to reproduce

Create 2 basic test files like this

Test File 1

```typescript
import test from '@playwright/test';

test.describe('Costas Tests', () => {
  test('@tag1 Test 1', async ({}) => {
    console.log('costa');
  });

  test('@tag2 Test 2', async ({}) => {
    console.log('viktor');
  });

  test('@tag2 Test 3', async ({}) => {
    console.log('viktor');
  });
});

```

Test File 2

```typescript
import test from '@playwright/test';

test.describe('Viktors Tests', () => {
  test('@tag1 Test 1', async ({}) => {
    console.log('costa');
  });

  test('@tag1 Test 2', async ({}) => {
    console.log('costa');
  });

  test('@tag2 Test 3', async ({}) => {
    console.log('viktor');
  });
});
```

With projects setup like this

```typescript
projects: [
    {
      name: 'Create Admin User',
      testMatch: /global.setup\.ts/,
      teardown: 'Delete Admin User',
      use: {
        headless: true,
      },
    },
    {
      name: 'Delete Admin User',
      testMatch: /global.teardown\.ts/,
      use: {
        headless: true,
      },
    },
    {
      name: 'Smoke Tests',
      dependencies: ['Create Admin User'],
      grep: /@tag1/,
      use: {
        ...devices['Desktop Chrome'],
      },
    },
    {
      name: 'P0 Tests',
      dependencies: ['Smoke Tests'],
      grep: /@tag2/,
      use: {
        ...devices['Desktop Chrome'],
      },
    },
  ],
```

Global Setup

```typescript
import { test as setup } from '@playwright/test';

setup('Create global admin user', async ({}) => {
  console.log('setup');
});
```

TearDown

```typescript
import { test as tearDown } from '@playwright/test';

tearDown('Delete global admin user', async ({}) => {
  console.log('teardown');
});
```

So when i run `npx playwright test` with a single shard I get the expected behaviour which is a total of 8 tests ran.

```
➜  playwright git:(project-smoke) ✗ npx playwright test

Running 8 tests using 1 worker

  ✓  1 [Create Admin User] › global.setup.ts:3:6 › Create global admin user (16ms)
setup
  ✓  2 [Smoke Tests] › asset-management/costa.test.ts:4:7 › Costas Tests › @tag1 Test 1 (13ms)
costa
  ✓  3 [Smoke Tests] › asset-management/viktor.test.ts:4:7 › Viktors Tests › @tag1 Test 1 (3ms)
costa
  ✓  4 [Smoke Tests] › asset-management/viktor.test.ts:8:7 › Viktors Tests › @tag1 Test 2 (3ms)
costa
  ✓  5 [P0 Tests] › asset-management/costa.test.ts:8:7 › Costas Tests › @tag2 Test 2 (14ms)
viktor
  ✓  6 [P0 Tests] › asset-management/costa.test.ts:12:7 › Costas Tests › @tag2 Test 3 (2ms)
viktor
  ✓  7 [P0 Tests] › asset-management/viktor.test.ts:12:7 › Viktors Tests › @tag2 Test 3 (3ms)
viktor
  ✓  8 [Delete Admin User] › global.teardown.ts:3:9 › Delete global admin user (15ms)
teardown

  8 passed (2.0s)
```

### Expected behavior

When I run:

`npx playwright test --shard=1/2`

I would expect to see these tests run:

```
➜  playwright git:(project-smoke) ✗ npx playwright test --shard=1/2

Running 5 tests using 1 worker

  ✓  1 [Create Admin User] › global.setup.ts:3:6 › Create global admin user (16ms)
setup
  ✓  2 [Smoke Tests] › asset-management/costa.test.ts:4:7 › Costas Tests › @tag1 Test 1 (13ms)
costa
  ✓  3 [P0 Tests] › asset-management/costa.test.ts:4:7 › Costas Tests › @tag2 Test 2 (3ms)
viktor
  ✓  4 [P0 Tests] › asset-management/costa.test.ts:8:7 › Costas Tests › @tag2 Test 3 (3ms)
viktor
  ✓  5 [Delete Admin User] › global.teardown.ts:3:9 › Delete global admin user (15ms)
teardown

  5 passed (2.0s)
```

And when I run: 

`npx playwright test --shard=2/2`

I would expect to see these tests results:

```
➜  playwright git:(project-smoke) ✗ npx playwright test --shard=2/2

Running 5 tests using 1 worker

  ✓  1 [Create Admin User] › global.setup.ts:3:6 › Create global admin user (16ms)
setup
  ✓  2 [Smoke Tests] › asset-management/viktor.test.ts:4:7 › Viktors Tests › @tag1 Test 1 (13ms)
costa
  ✓  3 [Smoke Tests] › asset-management/viktor.test.ts:4:7 › Viktors Tests › @tag1 Test 2 (3ms)
costa
  ✓  4 [P0 Tests] › asset-management/viktor.test.ts:8:7 › Viktors Tests › @tag2 Test 3 (3ms)
viktor
  ✓  5 [Delete Admin User] › global.teardown.ts:3:9 › Delete global admin user (15ms)
teardown

  5 passed (2.0s)
```

### Actual behavior

Including the global setup and teardown I have 8 tests

Shard 1

```
➜  playwright git:(project-smoke) ✗ npx playwright test --shard=1/2

Running 7 tests using 1 worker, shard 1 of 2

  ✓  1 [Create Admin User] › global.setup.ts:4:6 › Create global admin user (15ms)
setup
  ✓  2 [Smoke Tests] › asset-management/costa.test.ts:8:7 › Costas Tests › @viktor Test 2 (14ms)
viktor
  ✓  3 [Smoke Tests] › asset-management/viktor.test.ts:4:7 › Viktors Tests › @viktor Test 1 (2ms)
viktor
  ✓  4 [Smoke Tests] › asset-management/viktor.test.ts:8:7 › Viktors Tests › @viktor Test 2 (3ms)
viktor
  ✓  5 [P0 Tests] › asset-management/costa.test.ts:4:7 › Costas Tests › @costa Test 1 (14ms)
costa
  ✓  6 [P0 Tests] › asset-management/costa.test.ts:12:7 › Costas Tests › @costa Test 3 (3ms)
costa
  ✓  7 [Delete Admin User] › global.teardown.ts:3:9 › Delete global admin user (15ms)
teardown

  7 passed (2.0s)
```

Shard 2

```
➜  playwright git:(project-smoke) ✗ npx playwright test --shard=2/2

Running 6 tests using 1 worker, shard 2 of 2

  ✓  1 [Create Admin User] › global.setup.ts:4:6 › Create global admin user (16ms)
setup
  ✓  2 [Smoke Tests] › asset-management/costa.test.ts:8:7 › Costas Tests › @viktor Test 2 (14ms)
viktor
  ✓  3 [Smoke Tests] › asset-management/viktor.test.ts:4:7 › Viktors Tests › @viktor Test 1 (2ms)
viktor
  ✓  4 [Smoke Tests] › asset-management/viktor.test.ts:8:7 › Viktors Tests › @viktor Test 2 (3ms)
viktor
  ✓  5 [P0 Tests] › asset-management/viktor.test.ts:12:7 › Viktors Tests › @costa Test 3 (14ms)
costa
  ✓  6 [Delete Admin User] › global.teardown.ts:3:9 › Delete global admin user (15ms)
teardown

  6 passed (2.0s)
```

Why has it run a total of 13 test when I only have 8?

### Additional context

This is a tiny set of tests but if we have 100's or 1000's then running tests more than once is a waste of time and resources and could also include unexpected flakiness in the overall test results.

### Environment

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 70.81 MB / 32.00 GB
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  IDEs:
    VSCode: 1.86.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by MindaugasMateika** [comment] 2024-02-26 11:09
Your `P0 Tests` depends on `Smoke Tests`. So if both shards which are independent run `P0 Tests` then both shards will also run all `Smoke Tests`.

**Comment by costa-collibra** [comment] 2024-02-26 11:13
Ok it looks like I’m misusing dependencies.

P0 tests are not strictly dependent on smoke but rather I only wanted to
run the p0 tests if the smoke tests passed as technically the p0 tests
should not be able to pass if smoke failed. This is why I set up the
dependency.

I wanted to fail fast.

Costa Giannakopoulos
Senior Software Development Engineer in Test II
Him/He
—
07817826551
***@***.***
collibra.com

<https://www.collibra.com/us/en/united-by-data>

**Comment by pavelfeldman** [comment] 2024-02-26 17:49
Closing as working as intended!

**Closed by pavelfeldman** 2024-02-26 17:49 UTC
