### ISSUE TITLE
We *HAVE* to be able to assign arbitrary names to the videos and screenshots.

### ISSUE THREAD

**Issue by eliezercazares** [microsoft/playwright#13077] opened 2022-03-25 19:29 UTC
As of today, videos are stored with uuids which leads to end user SDET's having to create solutions of their own for things that should be considered granted in a Framework that attempts to be a one-solution-for-all.

This issue might be duplicated but I have not seen the staff of PW putting any attention to this issue.

Please provide a way to name the screenshots and videos. I suggest a configuration for each test scenario that can be passed to the playwright Page object.

**Comment by IanVS** [comment] 2022-03-25 19:45
Seems to be a duplicate of https://github.com/microsoft/playwright/issues/4131, which you also just commented on with a very demanding tone.  I'd suggest putting together a PR if this is something you care deeply about.  It's open source, after all.

**Comment by IanVS** [comment] 2022-03-25 19:55
>you're the one providing a service and neglecting requests even after 2 years

I'm just someone who started using playwright today and saw your issue/comment.  But I maintain other open source projects in my free time, so your attitude raised my hackles.  I'm pretty sure you haven't paid anything to the maintainers of this library, and you haven't contributed to the library, so they don't owe you anything.

**Comment by eliezercazares** [comment] 2022-03-25 19:57
I am appealing to professionalism and the will to contribute.

We all do maintain projects. That's why we are here. And yeah there's a lot of people that assume it has to be pay to play with a smile.

I don't care about attitudes, I care about results. And thanks for confirming you're only getting in the way of an adult talk. Thick skin and all.

**Comment by eliezercazares** [comment] 2022-03-25 20:21
> > you're the one providing a service and neglecting requests even after 2 years
> 
> I'm just someone who started using playwright today and saw your issue/comment. But I maintain other open source projects in my free time, so your attitude raised my hackles. I'm pretty sure you haven't paid anything to the maintainers of this library, and you haven't contributed to the library, so they don't owe you anything.

By the way, this is about Playwright. Not about me or Johnny Developer at Playwright.

So if you don't have anything to contribute, as I have done already with suggestions and code, please stay away from this topic. Let the people who have a say, to say it.

**Comment by dgozman** [comment] 2022-03-26 01:39
Closing in favor of #4131.

**Closed by dgozman** 2022-03-26 01:39 UTC
