### ISSUE TITLE
[BUG] page.frame({url:iframesrc}) returns null with firefox

### ISSUE THREAD

**Issue by mittster** [microsoft/playwright#29148] opened 2024-01-24 11:45 UTC
### System info
- Playwright Version: [v1.41.1]
- Operating System: [ tested on macOS 11.7.6]
- Browser: [Firefox]
- Other info:

### Source code

```ts
import puppeteer from "playwright";

export async function WaitForTimeout(ms){
    return new Promise(resolve => setTimeout(resolve, ms));
}

let url = "https://laptop.bg/"; // or any other page with cf protection on
var browser = await puppeteer.firefox.launch({
    headless:false,
    ignoreHTTPSErrors: true
});

const page = await browser.newPage();
let response = await page.goto(url, {waitUntil: "domcontentloaded", timeout: 40000});
await WaitForTimeout(6000);

//parsing iframe src
let pageContent = await page.content();
let iframeString = pageContent.substring(pageContent.indexOf("<iframe"), pageContent.indexOf(">",pageContent.indexOf("<iframe"))+1);
let iframeSrc = iframeString.substring(iframeString.indexOf('src="')+5, iframeString.indexOf('"',iframeString.indexOf('src="')+5));
console.log("parsed src: "+iframeSrc+"")

// print all iframe urls on the page, that is main and one child of main
// notice that no url is found for the actual iframe
console.log("all iframe srcs found via frame.url(), only main has src")
let allFrames = page.frames();
for (const singleFrame of allFrames) {
    console.log("url "+singleFrame.url());
}

let iframe = page.frame({url:iframeSrc}); // returns null when firefox is used, but it works with WebKit and Chromium
console.log(iframe);
```

**Steps**
- run the test with any page that has active cf turnstile protection on. Example is provided.

**Expected**

`page.frame({url:iframesrc})` is expected to return a Frame object. 

Frame objects returned by `page.frames()`  should return an url when by `Frame.url()` method is call

**Actual**

`page.frame({url:iframesrc})` returns null, even though iframe src is correct. Frame.url() does not return a iframe src url.

This only happens with firefox.  I think the iframe used by CF is special, because I was not able to reproduce the issue on this website: https://ui.vision/demo/webtest/frames/

The error may have something to do with the iframe attributes. `allow="cross-origin-isolated; fullscreen"` is mentioned in other issues, not sure if this is the same problem.

**Comment by mxschmitt** [comment] 2024-01-24 21:52
Looks like a duplicate of https://github.com/microsoft/playwright/issues/28966

**Comment by yury-s** [comment] 2024-01-24 22:52
The test itself is flaky in a few places, most of the times it prints 'parsed src: <!DO'. Sometimes it finds the frame but sometimes fails apparently due to frame not completely loaded. There is also cloudflare page in between which is shown when the script tries to find the frame. Inserting a delay before page.frame call makes it work in many cases:

```js
await new Promise(resolve => setTimeout(resolve, 2000));
let iframe = page.frame({url:iframeSrc}); // returns null when firefox is used, but it works with WebKit and Chromium
```

So far it looks like just a flaky test. If you think this is bug in playwright, please provide a reduced repro.

**Comment by yury-s** [comment] 2024-01-29 23:46
Closing per the response above, feel free to open a new issue if it doesn't work.

**Closed by yury-s** 2024-01-29 23:46 UTC
