### ISSUE TITLE
[Question] Allure-framework for Playwright - Setting "allure-results" folder path programmatically? 

### ISSUE THREAD

**Issue by DvDream** [microsoft/playwright#10429] opened 2021-11-19 08:06 UTC
Hi, I'm using the experimental-allure-playwright reporter, I can change the location of the "allure-report" folder by command line. However, it seems like the "allure-results" folder is always saved in the main project directory ora by setting it like an environmnet variable before launching the playwright script. Since I'm running the playwright runner programmatically,  what if I wanted to programmatically set that path or by the playwright.config field? Is there a way to do that? Thank you!

**Comment by mxschmitt** [comment] 2021-11-19 10:17
The experimental-allure-playwright is the old one, the new one is called allure-playwright and its living in this repository: https://github.com/allure-framework/allure-js

See here for up to date docs: https://github.com/allure-framework/allure-js/tree/master/packages/allure-playwright

Duplicate of https://github.com/allure-framework/allure-js/issues/405

**Closed by mxschmitt** 2021-11-19 10:17 UTC
