### ISSUE TITLE
[Question] Tests pass when running one file at a time but when all files are run, random ones start failing?

### ISSUE THREAD

**Issue by haramchang** [microsoft/playwright#13108] opened 2022-03-27 22:44 UTC
Hi, so I'm testing mostly links/buttons on the lucidmotors.com website, and some tests are really giving me a hard time - specifically the main nav, side nav and footer. When I run a minimal amount of tests at a time (like a handful or even just 1 file) on gitlab, everything passes. However, when I run all the tests at the same time tests start failing mostly because of timeouts while waiting for selectors or navigations and I know it's not a bug on the website's end because each time it's random ones that are failing (a certain test will pass one time and then fail the next) and I'll also go and try to reproduce the bug and nothing breaks. I've tried upping the workers and timeouts but that doesn't fix the problem. It's really hard trying to figure out what the problem is because I haven't found much when googling this issue.

All my tests follow the same type of layout:

```
test.describe.parallel('Footer on home page', () => {

  test.beforeEach(async ({ page }) => {
    await page.goto('https://www.lucidmotors.com');
    await page.locator('text=Accept Cookies').click();
  });

  test.afterEach(async ({ page }) => {
    await page.close();
  });

  test('Discover Air', async ({ page }) => {
    await page.locator('footer >> text=Discover Air').click();
    await expect(page).toHaveURL('https://www.lucidmotors.com/air')
  });

  test('Design Yours', async ({ page }) => {
     await page.locator('footer >> text=Design Yours').click();
     await expect(page).toHaveURL('https://www.lucidmotors.com/air/configure')
  });
```
obviously with more links, and then I thought it might be a network issue so I refactored to have them look like this:

```
test.describe.parallel('Footer on home page', () => {

  test.beforeEach(async ({ page }) => {
    await page.goto('https://www.lucidmotors.com');
    await page.locator('text=Accept Cookies').click();
  });

  test.afterEach(async ({ page }) => {
    await page.close();
  });

  test('Discover Air', async ({ page }) => {
       await expect(page.locator('footer >> a[href="/air"]')).toContainText("Discover Air");
  });

  test('Design Yours', async ({ page }) => {
       await expect(page.locator('footer >> a[href="/air/configure"]')).toContainText("Design Yours");
  });
```
I'm wondering if these are the correct way to be setting up the tests or if I'm missing something. Or if it's really due to some slow backend/network issues.

**Comment by rwoll** [comment] 2022-03-28 18:48
Thanks for your report! I tried the following (in Playwright 1.20):

```ts
import test, {expect} from '@playwright/test';

test.describe.parallel('Footer on home page', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('https://www.lucidmotors.com');
    await page.locator('text=Accept Cookies').click();
  });

  for (let i = 0; i < 100; i++)
    test(`Discover Air ${i}`, async ({ page }) => {
      await page.locator('footer >> text=Discover Air').click();
      await expect(page).toHaveURL('https://www.lucidmotors.com/air')
    });
});
```

and all 300 cases passed (WebKit, Firefox, Chromium).

The following block in your snippet is not needed:

```ts
  test.afterEach(async ({ page }) => {
    await page.close();
  });
```

For the built-in Playwright fixtures (https://playwright.dev/docs/test-fixtures#built-in-fixtures), Playwright Test will handle closing them for you.

To help debug further, can you ensure Tracing is enabled in your Playwright Config, and obtain a Trace for a failed test case. See https://playwright.dev/docs/trace-viewer for more information and a link to view the trace once you have it. This will hopefully help understand where the case(s) are failing in your exact scenario.

Please let us know what you find in the Trace, or if you need additional assistance!

**Comment by haramchang** [comment] 2022-03-28 20:02
Hi thanks for the response! Yeah I wasn't sure if the after hooks were truly necessary but it didn't seem to have an adverse effect on the tests and it also seemed like the pages for each test weren't closing until the whole test run was finished (?) so I thought it'd be best to leave it in there to avoid saturation. 
And weird!! I'll try seeing if I can get a Trace for a failed test case and I'll post it here! Thank you :)

**Comment by rwoll** [comment] 2022-03-29 19:30
> maybe due to a/b testing or the way the site is set up is weird

That would definitely cause things to flake! If you have A/B trials on your site under test, you'll want to ensure your tests run with the same A or B group of the site each time depending on your configuration. I recommend doing a Playwright Project per trial group if you need to test multiple trials: https://playwright.dev/docs/test-advanced#projects

>  but when running on gitlab they're missing from the html reports

Update your `paths` to include everything under `playwright-report/` (possibly deeply nested folders); not just the index.html file, and the videos/images should show up in the report (or at least be downloadable).

**Comment by haramchang** [comment] 2022-03-29 21:16
Yeah I'll have to look into it further! And thank you! That worked 😄

**Comment by rwoll** [comment] 2022-04-01 23:51
Closing as part of triage. Now that tracing is working for you, once you have more logs, please feel free to re-open if they do not help you resolve the issue.

I also recommend trying low worker count in your config. Some CI systems are more constrained, and will start flaking in unexpected ways if pushed to hard.

**Closed by rwoll** 2022-04-01 23:51 UTC
Labels: triaging

**Comment by jakebanks** [comment] 2022-11-10 03:46
@haramchang thanks for raising this issue, it sounds like what I'm seeing - were you able to work out the root cause? I am yet to work toward a CI environment that supports artifacts so haven't been able to investigate properly yet.
